### ISSUE TITLE
`dvc destroy` does it remove data files as well?

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1000]
Specify in the confirmation if that's the case. Fix docs. It feels a little bit dangerous.

**Comment by amka00** [comment]
Still the CLI help notes do not mention the deleting of data files themselves.
Same with online command reference (https://dvc.org/doc/commands-reference/destroy).

**Comment by efiop** [comment]
Hi @amka00 ! That should be handled by https://github.com/iterative/dvc/issues/1011

**Comment by efiop** [comment]
@amka00 Merged a patch for it in https://github.com/iterative/dvc/pull/2164 along with the docs. It is going to be released with the new version, which is coming soon.
