### ISSUE TITLE
`--to-remote` performance

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#10003]
`dvc import-url --to-remote` is way slower than doing `dvc import-url` and pushing to the remote would be:

https://github.com/iterative/dvc/assets/2308172/085cdc21-11ea-4d6c-a749-04b4363d27a7

Is it still a valid workflow we should support? If so, what is the effort to support it? If not, what's the alternative?

**Comment by pmrowla** [comment]
`--to-remote` was intended specifically for the case where you don't have enough local disk space to do `import-url` and then `push`, and your only option is to stream from the source and then to the remote.

The separate `--import-url` and `push` is always going to be faster than using `--to-remote`, since `--to-remote` streaming means you cannot download chunks for a single file in parallel (they have to be streamed in order since we need to MD5 hash the source file while it is being streamed). If the user enough local disk space then they should not be using `--to-remote`.

`--to-remote` still works for the specific case it was intended to solve, I think documenting this limitation should be enough to drop this from p1 for now, and then we can look into trying to re-optimize the `--to-remote` behavior later.

**Comment by dberenbaum** [comment]
It doesn't need to be as fast as other options, and maybe it doesn't need to be p1, but I made it p1 because the flag seems unusable now. Even for a single file, it looks so much slower that it doesn't seem practical to ever use it.

> you cannot download/upload chunks for a single file in parallel

Are we doing this now in aws? I thought it depended on https://github.com/iterative/dvc/issues/9893, or am I mixing something up?

**Comment by pmrowla** [comment]
> Are we doing this now in aws? I thought it depended on #9893, or am I mixing something up?

We don't do this for s3, but it depends on the remote type

**Comment by dberenbaum** [comment]
I'm surprised then that for s3, `--to-remote` is so much slower than importing locally and then pushing:

```
$ time dvc import-url s3://dave-sandbox-versioning/videos/0001ffba3c--6287e2f608ea00759b5c156e/replay_video.mp4

Importing 's3://dave-sandbox-versioning/videos/0001ffba3c--6287e2f608ea00759b5c156e/replay_video.mp4' -> 'replay_video.mp4'

To track the changes with git, run:

        git add replay_video.mp4.dvc .gitignore

To enable auto staging, run:

        dvc config core.autostage true
dvc import-url   0.86s user 0.27s system 18% cpu 6.254 total
(dvc) dave@davids-air:~/repo [main] 12:48:45
$ time dvc push
Everything is up to date.
dvc push  0.49s user 0.11s system 65% cpu 0.926 total
(dvc) dave@davids-air:~/repo [main] 12:48:51
$ dvc remove --outs replay_video.mp4.dvc
(dvc) dave@davids-air:~/repo [main] 12:49:10
$ time dvc import-url --to-remote s3://dave-sandbox-versioning/videos/0001ffba3c--6287e2f608ea00759b5c156e/replay_video.mp4


To track the changes with git, run:

        git add replay_video.mp4.dvc

To enable auto staging, run:

        dvc config core.autostage true
dvc import-url --to-remote   1.82s user 0.51s system 12% cpu 18.392 total
```

It takes ~2.5x as long for a single file. Why is that? I'm wondering if there's some easy fix to make them similar since I don't know any reason it should be slower for a single file.

**Comment by shcheklein** [comment]
Just a random thought. I had something like this with a buffer size (not) set to anything meaningful (e.g. it was 10 bytes, or something). And the process was reading in those small chunks. I wonder if there could be a case of some settings similar to this.

**Comment by pmrowla** [comment]
> It takes ~2.5x as long for a single file. Why is that? I'm wondering if there's some easy fix to make them similar since I don't know any reason it should be slower for a single file.

The underlying implementation for streaming is completely separate from the underlying implementation for upload/download (so it's a different set of s3 API calls that may also be less optimized then the regular upload/download case).

**Comment by dberenbaum** [comment]
Just tried this again and can't reproduce it, so closing this one.
