### ISSUE TITLE
IBM S3 Bucket cannot use DVC cloud versioning

### ISSUE THREAD

**Issue by SwapnilDreams100** [iterative/dvc#10008]
# Bug Report

IBM S3 Bucket cannot use DVC cloud versioning

## Description

I enabled object versioning(https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-versioning) on the IBM S3 bucket, but the files are still content labelled (randomly generated names)

### Reproduce

-> Enable Object versioning on IBM cloud cos bucket
-> dvc remote modify myremote version_aware true                                      
->  dvc push
### Expected

Files are in their natural name and directory structure
### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by efiop** [comment]
@SwapnilDreams100 Please post `dvc doctor` output.

**Comment by SwapnilDreams100** [comment]
Hi @efiop Here is the `dvc doctor` output: 

DVC version: 2.58.2 (pip)
-------------------------
Platform: Python 3.9.5 on macOS-13.4.1-arm64-arm-64bit
Subprojects:
	dvc_data = 0.51.0
	dvc_objects = 0.24.0
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.1.0
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2022.11.0, boto3 = 1.24.59)
Config:
	Global: /Users/swap/Library/Application Support/dvc
	System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3, s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/9ec58cc985a1fe0076d5c79d73a9e9f2

**Comment by efiop** [comment]
@SwapnilDreams100 Looks like you have two remotes configured.  Please show `dvc remote list`. Check that you are using a `version_aware` remote as a default.

**Comment by SwapnilDreams100** [comment]
Ah yes that did the trick thanks! Closing this issue.
