### ISSUE TITLE
`dvc data status` immediately after `dvc init` shows some deleted files

### ISSUE THREAD

**Issue by sreeprasannar** [iterative/dvc#10029]
# Bug Report

## dvc data status: shows deleted files even though I did dvc destory, then dvc init

I want to completely reinit dvc within a repository but immediately after `dvc destroy; dvc init`, I can see `deleted files` in `dvc data status` under `DVC committed changes:`

## Description

Why is `dvc data status` reflecting older changes after I have completely `destroy`-ed the dvc folder?
`dvc destroy` says:
```
This will destroy all information about your pipelines, all data files, as well as cache in .dvc/cache.
Are you sure you want to continue? [y/n]: y
```
But then why does it still retain some knowledge about prior committed files? 

### Reproduce

I have no clue how to reproduce cos this is super weird.
**Additional Information (if any):**

**Comment by sreeprasannar** [comment]
Turns out I still had the `.dvc` files being tracked by `git`. I had to delete those as well. I don't know why that works but now I can redo the dvc stuff and things seem to work?

**Comment by dberenbaum** [comment]
`dvc data status` compares changes since your last git commit, so if you have not yet done a git commit after `dvc destroy`, dvc will still compare the current (clean) state of your newly initialized repo with the state of the dvc repo in the last commit.
