### ISSUE TITLE
Getting Unexpected error for remote status

### ISSUE THREAD

**Issue by MeWu-IDM** [iterative/dvc#10053]
# Bug Report

## Description

I run into error on windows below (pip installed dvc)
dvc status --remote myremote
ERROR: unexpected error - Task <Task pending name='Task-6' coro=<AzureBlobFileSystem._exists() running at c:\python38\lib\site-packages\adlfs\spec.py:1417> cb=[_wait.<locals>._on_completion() at c:\python38\lib\asyncio\tasks.py:507]> got Future <Future pending> attached to a different loop

### Reproduce

python 3.8.0
dvc 3.1.8
windows 10
run dvc status is fine
but running dvc status --remote gets error

### Expected

should return as in documentation https://dvc.org/doc/command-reference/status#example-remote-comparisons
### Environment information

**Output of `dvc doctor`:**

```console
C:\github\polio-immunity-mapping>dvc doctor
DVC version: 3.18.0 (pip)
-------------------------
Platform: Python 3.8.0 on Windows-10-10.0.19041-SP0
Subprojects:
        dvc_data = 2.15.4
        dvc_objects = 1.0.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.3.1
Supports:
        azure (adlfs = 2023.8.0, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.17.0),
        gs (gcsfs = 2023.6.0),
        hdfs (fsspec = 2023.6.0, pyarrow = 9.0.0),
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        oss (ossfs = 2023.8.0),
        s3 (s3fs = 2023.6.0, boto3 = 1.28.17),
        ssh (sshfs = 2023.7.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2023.6.0)
Config:
        Global: C:\Users\meikangwu\AppData\Local\iterative\dvc
        System: C:\ProgramData\iterative\dvc
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: azure
Workspace directory: NTFS on C:\
Repo: dvc, git
Repo.site_cache_dir: C:\ProgramData\iterative\dvc\Cache\repo\8db6ffb75ca5a5c21411668e46621057
```

**Additional Information (if any):**

**Comment by efiop** [comment]
@MeWu-IDM Could you try newer python version, please? There were a bunch of async fixes since 3.8.0, so I wonder if you are running into a bug that got already fixed.
