### ISSUE TITLE
`params_show`: locking issues

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#10050]
`params_show` requires the lock, which breaks in multi-gpu/multi-node training. Need to reconsider whether it's needed and/or recommend another method for reading params, at least in multi-gpu/multi-node scenarios (see https://dvc.org/doc/dvclive/ml-frameworks/pytorch#distributeddataparallel).

**Comment by shcheklein** [comment]
Is it a git lock? can we add Git no lock option like @mattseddon did in VS Code?
