### ISSUE TITLE
fetch: failing on subpaths

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#10069]
> 2nd scenario: trying to access two files in succession out of a larger repo

I can reproduce this one, and it looks like a bug to me.

_Originally posted by @dberenbaum in https://github.com/iterative/dvc/issues/10052#issuecomment-1781133727_

**Comment by dberenbaum** [comment]
> 2nd scenario: trying to access two files in succession out of a larger repo a) trying to fetch one file actually fetches the whole folder unless I call `dvc data status --granular` first b) fetching the second file _claims_ success, but actually doesn't download anything. Trying to `checkout` causes an error.
> 
> ```
> mkdir dvc_test; cd dvc_test
> git init
> dvc init
> mkdir -p a/b; mkdir -p a/c
> echo d >> a/b/d
> echo e >> a/c/e
> dvc add a
> dvc remote add -d storage gs://unique_bucket_name
> git add a.dvc .gitignore .dvc/config
> git commit -m "initialised repo"
> dvc push
> cd ..
> git clone dvc_test dvc_test2; cd dvc_test2
> # dvc fetch a/b/d  # downloads 3 files (dir + 2x files)
> dvc data status --granular
> dvc fetch a/b/d  # downloads 2 file (dir + a/b/d)
> dvc checkout a/b/d  # works
> dvc fetch a/c/e  # claims success, but no file downloaded
> dvc checkout a/c/e  # error
> ```

**Comment by skshetry** [comment]
I was not able to solve this.

The problem lies somewhere in index, where it's not returning the `obj_id` for the file later in `iteritems()`.

https://github.com/iterative/dvc-data/blob/9db4a3e29f653ccebe0a1e6ccc11429b9a479a31/src/dvc_data/index/fetch.py#L65-L69

**Comment by dberenbaum** [comment]
Looks like this was fixed by https://github.com/iterative/dvc/pull/10090.

**Comment by efiop** [comment]
<img width="487" alt="Screenshot 2023-11-14 at 06 20 30" src="https://github.com/iterative/dvc/assets/5367102/2f619c20-d8d6-4b71-95ca-ab063490aad7">

Though @skshetry also created https://github.com/iterative/dvc/pull/10073 , i've rebased it, let's see if those pass.
