### ISSUE TITLE
Delete datasets that have been pulled locally so that sensitive data sets can be cleaned up easily

### ISSUE THREAD

**Issue by benjamincerigo** [iterative/dvc#10097]
In an open-source project I am working on: [Automatic Classifiers for Peace](https://gitlab.com/automatic-classifiers-for-peace/acfp) we have used dvc to manage shared data in the project. 

This shared data can contain sensitive information and I would like a simple way (hopefully using dvc) to remove all the data set files from the repo. It is important that sensitive data is not stored on the local machines of developers for longer than they need.

To explain a concrete example of what I am looking for:
1. There are a number of files in dvc version control: `shared_data/buildup/test.csv.dvc`
2. A developer will then pull the data using the command `cd shared_data/buildup/ && dvc pull`
3. This will then download the actual dataset to the local machine of the developer `shared_data/buildup/test.csv`
4. The developer will then do some work using the dataset
5. The developer needs to be then able to run a command to be able to delete the cache and local data set. 

Obviously in the example I give the developer could just do `rm shared_data/buildup/test.csv` and `dvc gc -w --not-in-remote`.  However, this can become problematic when there are 10+ datasets that are in dvc version control. 

Furthermore, since the project is open source developers of different levels will be working with the datasets and I want to try to make it as easy as possible for them to keep the sensitive data off their machine when they are finished with it. 

Any help would be great.

**Comment by pmrowla** [comment]
Are you expecting your users to be working with more than one dataset at a time? If you are trying to avoid using `dvc gc`, it may be easiest to just have them remove both the dataset and the entire local cache whenever they are finished working, and then they can pull whatever they specifically need to work on next (which will re-populate the local cache with only what's needed).

```
$ rm shared_data/buildup/test.csv [other_datasets...]
$ rm -rf .dvc/cache
```
