### ISSUE TITLE
pytest: No module named 'virtualenv'

### ISSUE THREAD

**Issue by drasmuss** [iterative/dvc#10118]
# Bug Report

## Description

Attempting to run `pytest` when `dvc==3.30.2` is installed results in an error: `ModuleNotFoundError: No module named 'virtualenv'`

This was introduced in https://github.com/iterative/dvc/pull/10103, which added the `import virtualenv`.

### Reproduce

1. pip install dvc[s3]==3.30.2 pytest
2. pytest --help

### Expected

No error when running `pytest`.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.30.2 (pip)
-------------------------
Platform: Python 3.9.18 on Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 2.22.1
        dvc_objects = 1.2.0
        dvc_render = 0.6.0
        dvc_task = 0.3.0
        scmrepo = 1.5.0
Supports:
        http (aiohttp = 3.9.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.9.1, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.10.0, boto3 = 1.28.64)
Config:
        Global: /home/drasmuss/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/9c1875cab89a9830c7f3983ed16ecdd6
```

**Additional Information (if any):**

Traceback:
```
Traceback (most recent call last):
  ...
  File "/home/drasmuss/mambaforge/envs/tmp/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/home/drasmuss/mambaforge/envs/tmp/lib/python3.9/site-packages/dvc/testing/plugin.py", line 1, in <module>
    from .benchmarks.fixtures import *  # noqa: F403
  File "/home/drasmuss/mambaforge/envs/tmp/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/home/drasmuss/mambaforge/envs/tmp/lib/python3.9/site-packages/dvc/testing/benchmarks/fixtures.py", line 8, in <module>
    import virtualenv
ModuleNotFoundError: No module named 'virtualenv'
```

**Comment by efiop** [comment]
@drasmuss `virtualenv` is in `testing` dependencies. You need to install dvc with `dev` extra. E.g. `pip install 'dvc[dev]'`

**Comment by drasmuss** [comment]
I don't need/want the dev dependencies though. I'm not trying to use the `dvc` testing infrastructure, I'm just trying to run pytest in my own project (and use `dvc` in the standard non-dev way).

**Comment by efiop** [comment]
oh, I see what you mean. Indeed, that import needs to be lazy. taking a look...

**Comment by efiop** [comment]
@drasmuss @snowman2 3.30.3 is out, please give it a try. Thanks for the feedback!

**Comment by drasmuss** [comment]
New release works great, thanks for the quick fix!

**Comment by skshetry** [comment]
Correct fix is to disable pytest plugin here, not make imports lazy.

https://github.com/iterative/dvc/blob/b6d231f9cfe8354ad06e0f2116dcb2c1542b6eb9/pyproject.toml#L131

**Comment by skshetry** [comment]
Done in #10121.

**Comment by efiop** [comment]
Thanks, @skshetry !
