### ISSUE TITLE
`artifacts import`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#10136]
We have `dvc artifacts get`, but it would be useful to also have `dvc artifacts import` to enable using artifacts in downstream dvc projects. More info in [slack](https://iterativeai.slack.com/archives/CUSNDR35K/p1701442649647219?thread_ts=1701378725.620539&cid=CUSNDR35K).

**Comment by dberenbaum** [comment]
@tibor-mach WDYT about the priority of this? I think it would be nice to complete the artifact-related functionality, but I don't see anyone asking for it and not sure it's worth spending time on until it comes up in a user scenario.

**Comment by tibor-mach** [comment]
@dberenbaum Agreed. Let's keep it on the side for now. There were some people asking about functionality which is related to this, but it is definitely not pressing at the moment. I will let you know once that changes (I think it will in a matter of weeks or a few months at most). So p2 seems correct.
