### ISSUE TITLE
dvc doctor gives unexpected error - cannot import name 'umask' from 'dvc_objects.fs.system'

### ISSUE THREAD

**Issue by rnoxy** [iterative/dvc#10142]
# Bug Report

Hello people,
I have encountered an issue today.
I have found that the `dvc doctor` is raising unexpected error.

### Reproduce 

Installed with poetry (ubuntu-latest):
```
gto = "^0.3.5"
dvc = "^3.10.0"
dvc-s3 = "^2.23.0"
s3fs = "^2023.5.0"
```

```
• Installing dvc-http (2.31.0)
• Installing dvc-objects (1.4.7)
• Installing dvc-studio-client (0.17.1)
• Installing dvc-render (0.7.0)
• Installing dvc-data (2.16.4)
• Installing dvc-task (0.3.0)
• Installing dvc (3.22.1)
• Installing dvc-s3 (2.23.0)
```

Run 
```
dvc doctor
```

```
ERROR: unexpected error - cannot import name 'umask' from 'dvc_objects.fs.system' (/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dvc_objects/fs/system.py)

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
Error: Process completed with exit code [25].
```

**Comment by efiop** [comment]
@rnoxy Please upgrade to newest dvc or to dvc-objects.

**Comment by rnoxy** [comment]
I see, thanks. 

These versions vere found by poetry solving
```
gto = "^0.3.5"
dvc = "^3.10.0"
dvc-s3 = "^2.23.0"
s3fs = "^2023.5.0"
```

There is no upper limit for dvc version.
Maybe I have other dependency limits, but I think I should not get "unexpected error".

**Comment by rnoxy** [comment]
Moreover, limiting `dvc-objects <= 1.3.2` seems to be some workaround.

**Comment by rnoxy** [comment]
Right, I have found the reason:
```
gto <= 0.3.5
```

```
gto (^0.3.5) and dvc (^3.33.0), version solving failed.
```

Thank you @efiop for the help.

**Comment by keithing** [comment]
Ran into this error in CI/CD pinned to version `3.18.0`.  Can confirm updating to `3.33.3` fixed the issue.
