### ISSUE TITLE
Imported .dir files not pushed to remote

### ISSUE THREAD

**Issue by johnyaku** [iterative/dvc#10157]
# Bug Report

## Description

`dvc import` creates a `.dvc` file for the imported data. 
When a directory is imported, this `.dvc` file inclues a reference to a `.dir` file that tracks the actual files within the directory (their checksums and relative paths).
This `.dir` file is created in the cache as part of the import process.

Bug: the `.dir` file does not get pushed to the remote -- either the remote for the source repo or the receiving repo.

Presumably `dvc push` overlooks this `.dir` file because it is an import.

Of course, there is no need to push the actual _data_ files to the remote for the receiving (importing) repo. 
They can be fetched from the source repo.
But we still need the `.dir` file in order to figure out what files to fetch.

### Reproduce

Tested with v2.58.2 and v3.27
```
1. `dvc import {source-repo} {path}`
2. `git add {path}.dvc`
3. `git commit -m "Import data"
4. `grep dir {path}.dvc` # check .dir file
5. `cat .dvc/cache/....dir` # substitute path to .dir file
6. `dvc  push`
7. Look for .dir file on remote

**Comment by johnyaku** [comment]
We discovered this bug after we switched from a single multi-project shared cache to having individual caches for each project.
Initially, the `.dir` files were in the multi-project shared cache, and so we could continue to check out the files.

But then we cleaned up the cache and tried to pull/checkout the imports, with no luck.

Our hacky workaround is to re-import the data and copy the `.dir` file around manually. 
But this is clunky across platforms.

**Comment by dberenbaum** [comment]
AFAIR this is actually expected and DVC should be able to regenerate the `.dir` file on the fly from the data in the source repo, but @efiop can confirm. Does pulling those imported files fail?

**Comment by johnyaku** [comment]
It was a pull failure that alerted us to the problem. We make heavy use of imports, but this problem only emerged after we started using different caches for the source and target repos. 
Manually copying the `.dir` file allows us to pull on another platform, or in another instance (clone) with a distinct cache.

**Comment by johnyaku** [comment]
Apologies. It appears we can `pull` but not `checkout` (with first pulling).
Previously we could simply `checkout` because our cache was shared across projects.

**Comment by johnyaku** [comment]
This bug appears to be resurfacing with v3.50.1.

My colleague imports data and pushes to the remote.
I then try to pull the data to a fresh clone.

If we both use the same local cache, then `pull` works because the `.dir` files are already in the cache.

But if I use a different local cache then `pull` fails with:
```
FileNotFoundError: [Errno 2] No such file or directory: path/to/local/cache/hash.dir
```

**Comment by dberenbaum** [comment]
I'm not able to reproduce with this script:

```
set -eux

REPO1=$(mktemp -d)
REMOTE=$(mktemp -d)
git init $REPO1
cd $REPO1
dvc init -q
dvc remote add -d myremote $REMOTE
dvc import https://github.com/iterative/dataset-registry get-started
git add .
git commit -m "import data"
dvc push

REPO2=$(mktemp -d)
git clone $REPO1 $REPO2
cd $REPO2
dvc pull
```
