### ISSUE TITLE
Remove data files from cloud

### ISSUE THREAD

**Issue by JohannesTK** [iterative/dvc#1019]
Remove data files from cloud after removing them locally because removing them manually is close to impossible as the names of the files/folders are random strings.

For example:

`dvc remove --cloud`

**Comment by efiop** [comment]
Hi @JohannesTK !

Thank you for the feedback! We have a command called [`dvc gc`](https://dvc.org/doc/commands-reference/gc) that removes unused cache from both local and remote. For example, to remove all unused cache on the default cloud, run: `dvc gc --all-branches -c`.

Thanks,
Ruslan

**Comment by JohannesTK** [comment]
Thanks for the reply.

"Note, this action does NOT remove data files from the remote storage."

So there is no good way to delete from cloud other than manually?

**Comment by JohannesTK** [comment]
Got it. Thanks!
