### ISSUE TITLE
push: data not pushed after switching from --external

### ISSUE THREAD

**Issue by johnyaku** [iterative/dvc#10211]
# Bug Report

## Description

I first ran `dvc add --external {target}` which created a `.dvc` and `.dir` file, with the `path` in the `.dvc` file pointing to `{target}`. 
After pushing, only the `.dir` file was pushed to the remote. 
I assume that this is expected behaviour, but not what I intended.

I then followed up with `dvc add {target} -o {path}`, which is what I intended to do originally.
This modified the `.dvc` file (changed the `path`) but the `.dir` file was identical because the content of `{target}` had not changed.

However, `dvc push` returned "Everything up to date" and `dvc data status` returned "No changes".
The actual content of the directory was still not pushed to the remote.

By renaming the `.dir` file on the remote, and then pushing again I was able to push the data files.

So it appears that both `dvc push` and `dvc status` only check the `.dir` file, and not the contents of the tracked directory.

Now that I know this, I can work around it, but this took the longest time to figure out!!

### Reproduce

See above

### Expected

Expected DVC to realise that the files tracked by the `.dir` file were not actually in the remote.
I understand that scanning `.dir` files is much more efficient than scanning individual files.
But it might be helpful if `dvc push` and `dvc data status` had options to force a more careful check.

### Environment information

```
DVC version: 2.58.2 (conda)
---------------------------
Platform: Python 3.10.0 on Linux-3.10.0-1160.42.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 0.51.0
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.1
        scmrepo = 1.0.3
Supports:
        gs (gcsfs = 2023.3.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.3.0, boto3 = 1.24.59),
        ssh (sshfs = 0.0.0)
Config:
        Global: /home/johree/.config/dvc
        System: /directflow/TumourProgressionGroupTemp/projects/config/dvc
Cache types: symlink
Cache directory: panfs on panfs://10.0.2.1/TumourProgressionGroupTemp
Caches: local
Remotes: ssh
Workspace directory: panfs on panfs://10.0.2.1/ScratchGeneral
Repo: dvc, git
Repo.site_cache_dir: /tmp/dvc/repo/78136d5785c06ef1e7b95e71eddbacf5
```

Apologies if this has been addressed in a more recent version!

**Comment by dberenbaum** [comment]
Since `dvc add --external` is no longer supported, I'm going to close this, but appreciate you posting it in case others run into this issue!
