### ISSUE TITLE
Exclude files from checksum computation

### ISSUE THREAD

**Issue by Guillaume-oso** [iterative/dvc#10225]
When a I set a folder as a dependency in the dvc.yaml, I cannot ignore ```__pycache__``` and folder like that inside the main folder even if I add ```**/__pycache__``` in the ```.dvcignore```

Is it a bug or a wanted behavior? 

Is there a way to exclude these files when ```dvc repro``` compute hash to update ```dvc.lock```, and also when I use ```dvc-data build folder``` ?

Thanks

########################
Looks like it works properly on toy example, but not on my project and dvc-data build does not take account of .dvcignore

**Comment by efiop** [comment]
@Guillaume-oso Maybe your dvcignore is in a gitignored location?
