### ISSUE TITLE
Azure Blob Storage: DVC uses (wrong) environment variable instead of SAS token

### ISSUE THREAD

**Issue by SoCrespo** [iterative/dvc#10246]
# Bug Report

## Description

If my environment variables contains a variable named `AZURE_STORAGE_ACCOUNT_KEY` (not related to the DVC Azure Blob Storage), `dvc pull` fails with message `"Authentication error"` or `"ERROR: unexpected error - Incorrect padding: Incorrect padding"`(depending on CLI used: Powershell, Bash...)

This happens even if there is a `config.local` file containing `sas_token = <valid SAS token for DVC Azure Blob Storage>`.

This is not the expected behavior for 2 reasons:

1. DVC doc does not mention any env. var named AZURE_STORAGE_ACCOUNT_KEY that it would use. Closest names are: 
- AZURE_STORAGE_CONNECTION_STRING
- AZURE_STORAGE_ACCOUNT
- AZURE_STORAGE_KEY
- AZURE_STORAGE_SAS_TOKEN

2. There is a valid `config.local` file that should be used first, according to [documentation ](https://dvc.org/doc/user-guide/data-management/remote-storage/azure-blob-storage#microsoft-azure-blob-storage):

> For custom authentication, you can set the following config params with [dvc remote modify --local](https://dvc.org/doc/command-reference/remote/modify#--local), use [environment variables](https://dvc.org/doc/user-guide/data-management/remote-storage/azure-blob-storage#authenticate-with-environment-variables), or an [Azure CLI config file](https://dvc.org/doc/user-guide/data-management/remote-storage/azure-blob-storage#authenticate-with-an-azure-cli-config-file) **(in that order).**

### Reproduce

(0. ``az logout`` to prevent any interference)
1. ``dvc remote modify --local myremote sas_token 'my_valid_sas_token'``
2. ``$Env:AZURE_STORAGE_ACCOUNT_KEY='hello' ``
3. ``dvc pull``

### Expected

Data pulled from Azure Blob Storage, thanks to point 1 above. Point 2 should not interfere.

### Environment information

```
DVC version: 2.45.1 (pip) // same bug with 3.39, I have downgraded in case it would solve the bug
-------------------------
Platform: Python 3.10.7 on Windows-10-10.0.19045-SP0
Subprojects:
        dvc_data = 0.40.3
        dvc_objects = 0.19.3
        dvc_render = 1.0.0
        dvc_task = 0.1.11
        dvclive = 2.2.0
        scmrepo = 0.1.11
Supports:
        azure (adlfs = 2023.10.0, knack = 0.11.0, azure-identity = 1.14.1),
        http (aiohttp = 3.8.6, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.6, aiohttp-retry = 2.8.3)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: azure
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by shcheklein** [comment]
Environment variables take precedence over DVC and Azure file-based configs (`.dvc/config`, `.dvc/config.local` `~/.azure/config`, etc). So, I think this behavior is correct. 

In this case, I would assume the `AZURE_STORAGE_ACCOUNT_KEY` doesn't have the key in the proper format (e.g. "hello" is not a correct base64 or something and that's why some error from the Azure lib is thrown). I can't find the reference to this env variable in Azure libraries docs right away, but my guess it is the same as the `AZURE_ACCOUNT_KEY` (I have tested this and both variables work the same way for me).

So, in this case, if you want to have that env var you need to get the [Account key](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal#view-account-access-keys)

If you feel there is still a concern, please reopen and provide a bit more details:

- please add more details on why this is an issue for you (why do you need both SAS and the KEY set)
- run `dvc pull -v` and include the full stack trace
- please upgrade DVC - it's quite old and outdated and might be bringing some outdated Azure libraries with it.

**Comment by pmrowla** [comment]
For reference, support for the `AZURE_STORAGE_ACCOUNT_KEY` env var comes from the underlying library DVC uses for accessing azure blob storage (https://github.com/fsspec/adlfs). As noted, it's a historical equivalent for the current Microsoft/Azure documented `AZURE_ACCOUNT_KEY`

> The following environmental variables can also be set and picked up for authentication:
>
> - "AZURE_STORAGE_CONNECTION_STRING"
> - "AZURE_STORAGE_ACCOUNT_NAME"
> - "AZURE_STORAGE_ACCOUNT_KEY"
> - "AZURE_STORAGE_SAS_TOKEN"
> - "AZURE_STORAGE_TENANT_ID"
> - "AZURE_STORAGE_CLIENT_ID"
> - "AZURE_STORAGE_CLIENT_SECRET"

**Comment by SoCrespo** [comment]
Thanks Ivan and Peter for your explanations. This subject in not a bug indeed, and you provided very useful explanation that maybe could be included in the documentation?

For context: 
_- please add more details on why this is an issue for you (why do you need both SAS and the KEY set)_
I need the KEY set for another Azure Storage access, that has nothing to do with DVC. (hence the "hello" value in my example, as useless for DVC as the real value I use).

_- please upgrade DVC - it's quite old and outdated and might be bringing some outdated Azure libraries with it._
As said, I used version 3.39 first, and the problem was the same, I downgraded to the version my colleagues use as an attempt to solve my issue. Happy to go back to latest version now :-) 

I propose to update the documentation to:

- clarify the precedence order of credentials. For now, the doc states the contrary of the real behavior (i.e. env. var first): 

> For custom authentication, you can set the following config params with [dvc remote modify --local](https://dvc.org/doc/command-reference/remote/modify#--local), use [environment variables](https://dvc.org/doc/user-guide/data-management/remote-storage/azure-blob-storage#authenticate-with-environment-variables), or an [Azure CLI config file](https://dvc.org/doc/user-guide/data-management/remote-storage/azure-blob-storage#authenticate-with-an-azure-cli-config-file) (**in that order**).

- explicitly warn users about environment variables names that should be avoided when working with DVC, including the names``adlfs`` uses.
