### ISSUE TITLE
Cannot set azure timeout: config file error: expected int for dictionary value @ data['remote']['dvc-remote']['timeout']

### ISSUE THREAD

**Issue by 1998jack1998** [iterative/dvc#10245]
## Bug Report

Cannot set azure timeout

## Description

I want to set longer azure timeouts to avoid some problems connected with poor network condition but when I try to do that I get msg:
 ERROR: configuration error - config file error: expected int for dictionary value @ data['remote']['dvc-remote']['timeout']

## Reproduce

dvc remote modify dvc-remote timeout 600

### Expected

Adding timeout parameter to dvc .config file

**Comment by dberenbaum** [comment]
@efiop It looks like in https://github.com/iterative/dvc/pull/10027, we should be using `Coerce(int)`:

https://github.com/iterative/dvc/blob/5c31189a919f6f7208db9ca29eef940113fe5155/dvc/config_schema.py#L263-L265

Do we have tests for the config schema to catch these kind of issues?

**Comment by 1998jack1998** [comment]
Thanks for fast response, I agree that value from config should be mapped to int.

**Comment by efiop** [comment]
@1998jack1998 Thanks for reporting!

@dberenbaum Nice catch! We do test those in python just to check that fs accepts those, but we don't really test the schema coerce rules that much as it is rare and might be excessive (aka we are lazy bums). Maybe I'm just lazy, but it doesn't seem worth it right now either.

**Comment by efiop** [comment]
@1998jack1998 Please feel free to give 3.40.1 a try. Thanks again!

**Comment by 1998jack1998** [comment]
@efiop works great. Thank you for fast solving this issue!
