### ISSUE TITLE
Read time out configuration

### ISSUE THREAD

**Issue by fadingonestar** [iterative/dvc#10261]
# Bug Report
dvc remote modify testremote read_timeout 120

## Description
above command throws onfiguration error - config file error: expected int for dictionary value @ data['remote']['testremote ']['read_timeout'] for Azure DVC
Could you guys tell me  what am I doing wrong here?

**Comment by efiop** [comment]
@fadingonestar Please upgrade to the latest dvc version.

For now closing as a duplicated of https://github.com/iterative/dvc/issues/10245
