### ISSUE TITLE
Allow customization of the temporary directory for dvc exp run --temp

### ISSUE THREAD

**Issue by mfakaehler** [iterative/dvc#10276]
Thanks for your great work on dvc!

Related to Issue #8980, which presents a slightly different use-case, I was wondering if one could add the possibility to customize the location of the `.dvc/tmp` directory.

My application is the following. I am working on an HPC-Cluster where I can only include my repository as read-only during a scheduled job. Allowing dvc exp run --temp to use a customized directory for my experiments outside of the workspace would allow to perform the experiment with --set-params, without the need to modify my workspace during job-execution.  

I tried replacing the directory `.dvc/tmp` by a symlink pointing elsewhere, however, this seems to cause an error somewhere in `dvc/repo/experiments/queue/tempdir.py`.

**Comment by dberenbaum** [comment]
What is your desired workflow here? Even if you run `dvc exp run --temp` inside your job and copy it to some external directory, DVC will have to do Git operations in the workspace repo to save the experiment to the queue and to save the final results in the repo.

**Comment by mfakaehler** [comment]
Thanks @dberenbaum  for your immediate reply. I must admit I did not realize that dvc needs to perform (altering) git operations on the workspace during execution of experiments. I was hoping for a workflow like this:

1. Run `dvc exp run --temp --set-params ...` in a scheduled job on my hpc (which  has no permission to write to my home-directory in our cluster)
2. Use `dvc exp apply` later to bring the changes to my repo.

My `cache` is already configured to be pointing to a shared cache somewhere else.
So this wouldn't work even with a customized `.dvc/tmp`-Folder, right? 
In that case, I will need to look for alternatives to cope with the restrictions of my HPC-Cluster. Probably, I will just have to move the entire repo to the temporary storage that is writable during  execution of the scheduled job. 

Feel free to close this issue, if you see no use in a custom tmp folder. Thanks for giving it your consideration.

**Comment by dberenbaum** [comment]
Yes, I think you have the right idea. Good luck!
