### ISSUE TITLE
`git gc` and (many) queued DVC experiments

### ISSUE THREAD

**Issue by tibor-mach** [iterative/dvc#10288]
We have a report of a following error in git garbage collection (presumably caused by running a lot of dvc experiments in a queue) from one of our customers:

```
error: The last gc run reported the following. Please correct the root cause and remove gc.log.
Automatic cleanup will not be performed until the file is removed.
warning: There are too many unreachable loose objects; run 'git prune' to remove them. 
```

Git version is 2.34.1, DVC version is 3.33.3

They are using a python script which runs a subprocess with bash commands to generate those experiments but the script does nothing special, it just queues experiments with different parameter sets for gridsearch hyperparameter tuning.

My impression is that this might have something to do with `git gc` perhaps not being run automatically while all of these experiments are created and so it has to be run manually as suggested in the `git gc` [documentation](https://git-scm.com/docs/git-gc)

> Running git gc manually should only be needed when adding objects to a repository without regularly running such porcelain commands, to do a one-off repository optimization, or e.g. to clean up a suboptimal mass-import. See the "PACKFILE OPTIMIZATION" section in [git-fast-import[1]](https://git-scm.com/docs/git-fast-import) for more details on the import case.

My initial guess is that simply running `git gc` manually is enough to resolve this without any unwanted side-effects, but I will try to do this first.

**Comment by tibor-mach** [comment]
@skshetry No, this is an output from git

**Comment by tibor-mach** [comment]
FYI so far  have been unable to reproduce the error...requesting more info from the customer.

**Comment by pmrowla** [comment]
> My impression is that this might have something to do with `git gc` perhaps not being run automatically while all of these experiments are created and so it has to be run manually as suggested in the `git gc` [documentation](https://git-scm.com/docs/git-gc)
> 
> My initial guess is that simply running `git gc` manually is enough to resolve this without any unwanted side-effects, but I will try to do this first.

This is correct. `git gc` is not run when DVC does Git operations for experiments. This is normally not an issue because we expect the user to eventually use a CLI Git command at some point as a part of their normal workflow (at which time CLI Git does `git gc --auto` to automatically gc whatever is needed).

`git prune` is also run as a part of `git gc`, but in this case the warning is due to this CLI Git behavior:

> If the file gc.log exists, then git gc --auto will print its content and exit with status zero instead of running unless that file is more than gc.logExpiry old. Default is "1.day". See gc.pruneExpire for more ways to specify its value.

(see https://git-scm.com/docs/git-gc#Documentation/git-gc.txt-gcpruneExpire)

If the user removes `gc.log` (I think it's probably located in `.git/gc.log`) the automatic `git gc` should work normally without printing any further warnings, but the user can also just wait a day for the log file to expire (assuming they have not modified the `gc.logExpiry` Git configuration option).

**Comment by pmrowla** [comment]
In the event that the user runs into this again, it is safe to manually run `git prune` as the message suggests, but I don't think it's actually needed. My understanding here is that what is happening is:

1. user runs a lot of experiments (which given enough experiments will end up generating a lot of loose git objects)
2. user finally runs a CLI Git command
    1. `git gc --auto` is run automatically by CLI Git
    2. `git gc` sees an unexpected state (more loose objects than it normally expects) and generates the log file message to notify the user about that state, but `git gc --auto` will still end up running `git prune` as normal
3. user eventually runs another CLI Git command
    1. `git gc --auto` is run automatically by CLI Git
    2. `git gc --auto` sees the log file generated by the prior command and the log file has not yet expired, so it prints the contents of the log file and then exits

**Comment by skshetry** [comment]
I don't think there is anything for us to do here. As Peter mentioned, it's okay to do a `git gc``/git prune` and is the correct fix/suggestion. Closing.
