### ISSUE TITLE
push/pull cache for all branches

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#103]
`dvc sync [file]` uploads/downloads data snapshot for only the current brunch.

`dvc sync -all [file]` should upload\download all versions of the file(s).

**Comment by efiop** [comment]
I am not sure it is worth implementing, as there are usually more branches that don't even belong to you(i.e. various branches from origin, upstream and etc), which makes pushing/pulling all branches counter-productive, as in those rare cases when you indeed need to sync a few branches, you can easily do so by checking out those branches with git yourself. Actually, same logic applies to `dvc metrics`, but there the cost of it was pretty low, so it was an easy choice to just implement it. Lets discuss this one later. Moving to 0.9.8 for consideration.
