### ISSUE TITLE
DVC Fetch stuck

### ISSUE THREAD

**Issue by lahrims** [iterative/dvc#10353]
# Bug Report
DVC fetch is stuck

dvc push works fine and pushes it to remote S3
but when i try fetch its stuck at dvc fetching

## Description
My team is trying to migrate to dvc and we first tried a sample project and i was able to push the data to S3 with dvc push. But on another computer when they clone it and do a dvc fetch its stuck at fetching, dvc fetch -v doesnt help much it just shows logs up till collecting and at Fetching its stuck

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
DVC version: 3.48.4 (pip)
-------------------------
Platform: Python 3.10.13 on macOS-13.1-arm64-arm-64bit
Subprojects:
	dvc_data = 3.14.1
	dvc_objects = 5.1.0
	dvc_render = 1.0.1
	dvc_task = 0.3.0
	scmrepo = 3.2.0
Supports:
	http (aiohttp = 3.9.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.9.3, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2024.2.0, boto3 = 1.34.51),
	ssh (sshfs = 2023.10.0)
Config:
	Global: /Users/user/Library/Application Support/dvc
	System: /Library/Application Support/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/..

**Additional Information (if any):**

**Comment by dberenbaum** [comment]
How much data/how many files do you have? How long is it stuck for?

**Comment by lahrims** [comment]
> How much data/how many files do you have? How long is it stuck for?

the file i am tryin to fetch is 39.3 MB and it finally did fetch the files @97.03s user 10.19s system 9% cpu 17:57.57 total
Is there a way to improve or fasten the process up, also i want to add that the the val directory has sub-folders and images inside them, if it helps.

**Comment by dberenbaum** [comment]
Some more questions that could help:
- Did you try running `dvc pull/fetch path/to/file` to only fetch the relevant file?
- How many total files do you have and what's the approximate total size?
- Are you using a remote with `version_aware = true`?

**Comment by lahrims** [comment]
> Some more questions that could help:

> * Did you try running `dvc pull/fetch path/to/file` to only fetch the relevant file?
yes i am trying to dvc fetch/pull only relevant files 
> * How many total files do you have and what's the approximate total size?
The total size of my data is 137.2 MB, but i was trying to fetch only about 32.4MB of it with specified path
> * Are you using a remote with `version_aware = true`?
yes

Thanks a million, for prompt reply

**Comment by dberenbaum** [comment]
> * Are you using a remote with `version_aware = true`?
>       yes

Is it critical for you? It sounds nice but often ends up presenting more problems than it solves. I think if you try without this option, you will see performance closer to your expectations.

**Comment by lahrims** [comment]
> > * Are you using a remote with `version_aware = true`?
> >   yes
> 
> Is it critical for you? It sounds nice but often ends up presenting more problems than it solves. I think if you try without this option, you will see performance closer to your expectations.

I can try with version_control = false, but i might need the VC feature on the prod model, and we use a lot of image data and S3 as the storage.

**Comment by dberenbaum** [comment]
> I can try with version_control = false, but i might need the Version aware feature on the prod model, and we use a lot of image data with S3 as the storage.


Can you explain why that feature is important for you and how you see it being helpful for those scenarios?

**Comment by lahrims** [comment]
> Can you explain why that feature is important for you and how you see it being helpful for those scenarios?
There is a possibility that we might move it to on prem storage and might want to have it as original files rather than hash values, as various teams (Non-ML) might need access to the images. But i see that it works super fast with version_aware as false, we can do a work around.
