### ISSUE TITLE
unexpected error - b'worktreeConfig'

### ISSUE THREAD

**Issue by ereli-okami** [iterative/dvc#10395]
# Bug Report

## Issue name

`pull: unexpected error - b'worktreeConfig'`

## Description

When attempting to use the `dvc pull` command in a repository with the `worktreeConfig` extension enabled in Git, DVC throws an unexpected error. The error message received is "ERROR: unexpected error - b'worktreeConfig'". This issue persists even after attempting to set `worktreeConfig` to false via the Git config.

### Reproduce

1. Initialize a Git repository with `git init`.
2. Enable `worktreeConfig` in the Git configuration with `git config extensions.worktreeConfig false`.
3. Initialize DVC within the repository with `dvc init`.
4. Add a dataset or file to manage with DVC using `dvc add file`.
5. Try to pull data or synchronize with a remote storage using `dvc pull`.

### Expected

The `dvc pull` command should execute without any errors, syncing the DVC-tracked files from the remote storage. The presence of the `worktreeConfig` setting in Git should not impact DVC operations.

**Comment by DimaAmega** [comment]
Yes, we also get an error in CI
https://github.com/evidentlyai/evidently/actions/runs/8790124101/job/24121478623

**Comment by shcheklein** [comment]
@DimaAmega yep, it seems tbh that Github has changed something with the way they setup git on CI. Again, sorry about that. We are looking into this.

**Comment by 0x2b3bfa0** [comment]
* https://github.com/jelmer/dulwich/issues/1285

**Comment by shcheklein** [comment]
Temporary workaround on CI:

```
      - name: Temporary workaround for GitVersion
        shell: bash
        run: |
          git config --unset-all extensions.worktreeconfig
          # See https://github.com/GitTools/actions/issues/1115
```

(borrowed from one the linked PRs in the Dulwich issue)

**Comment by shcheklein** [comment]
This is fixed upstream. A new fixed version of `scmrepo` and `dulwich` were published. @skshetry let me know if we should in this case bump the `scmrepo` on the DVC end.
