### ISSUE TITLE
Feature proposal: `dvc artifacts get --show-url`

### ISSUE THREAD

**Issue by tibor-mach** [iterative/dvc#10420]
DVC currently supports `dvc get --show-url` as a way to retrieve just the URL of a DVC-versioned object as opposed to the object itself.

However, there is no equivalent for `dvc artifacts get`. This came as a customer request (to allow easier sharing of results even to people who are not DVC/DVC Studio users). It also has advantages e.g. in model deployment to Sagemaker (which requires the artifact URL on S3).

**Comment by dberenbaum** [comment]
There is a Python workaround for now:

```python
import dvc.api

artifact = dvc.api.artifacts_show(
    'text-classification',
    version='v1.0.0',
    repo='https://github.com/iterative/example-get-started.git',
)
url = dvc.api.get_url(
    artifact['path'],
    rev=artifact['rev'],
    repo='https://github.com/iterative/example-get-started.git',
)
```
