### ISSUE TITLE
dvc repro: pygit2 update breaking changes

### ISSUE THREAD

**Issue by SimiPro** [iterative/dvc#10431]
# Bug Report

## Description

pygit2 renamed GIT_OBJ_COMMIT to GIT_OBJECT_COMMIT (I think)
because we get error GIT_OBJ_COMMIT not found. 

### Reproduce

install newest dvc , run dvc repro 

### Expected

no crash

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

you can fix it by using pip install pygit2==1.14.1

**Comment by shcheklein** [comment]
Should be fixed by https://github.com/iterative/scmrepo/pull/359

**Comment by Lhenzo** [comment]
Hello,

Thank you for the bump. Is there any release planned soon to make this available?

Thank you

**Comment by shcheklein** [comment]
yes, we'll do a release soon.
