### ISSUE TITLE
`dvc exp run --queue` should pass environment variables to queued tasks

### ISSUE THREAD

**Issue by igordertigor** [iterative/dvc#10464]
I like to structure my projects with two source folders of the form
```
src/
  scripts/
  shared/
```
where scripts contains entrypoints for dvc stages that can be run as `python src/scripts/myscript.py`. Typically, those scripts would import more global properties form `src/shared` as
```python
from shared import xxx
```
This requires setting `PYTHONPATH=src` and works fine with `dvc repro` but it fails with `dvc exp run --queue` because the queued experiment doesn't copy the `PYTHONPATH` variable. I would like it if either environment variables would generally be copied or alternatively there would be a setting similar to [tox passenv](https://tox.wiki/en/latest/config.html#passenv) that allows specifying which variables to pass. It feels like experiments are basically unusable without this feature.

**Comment by shcheklein** [comment]
@igordertigor how do you set it up for `dvc repro`? `export` or something like `PYTHONPATH=src dvc repro`? what is the exact value you pass to it? could you try to dump the `os.environ` in the script to see what values are being picked up and what not?

can you also do relative imports instead - even with `dvc repro` arguably it would be easier ...

**Comment by shcheklein** [comment]
Thanks for the details. I mean more or less something like `from ..shared import mymodule`. Probably you could also avoid using `-m` and do `python path-to-file` (?)

how / where do you run the queue then? is it happening in a different terminal?

if you do `export PYTHOPATH=src` it should be picked up by the `dvc queue start` as far as I can tell.

> Regarding the the os.environ dump, i would need to wait a bit. That would probably take until next week.

thanks

**Comment by igordertigor** [comment]
Hi @shcheklein , I currently have trouble reproducing this and would therefore leave it for the time being. If the issue comes up again, I'll reach out to you again.
