### ISSUE TITLE
dvc queue not found dvc.yaml  in .dvc/tmp/exps/tmp*/dvc.yaml

### ISSUE THREAD

**Issue by Hamzeluie** [iterative/dvc#10476]
# Bug Report

## dvc.yaml not found
when I mak a exp --queue it build a directory in .dvc/tmp/exps/tmp* and copy repo in there but not dvc.yaml just when I create a queue.i think this is reason of being the error.it can not found dvc.yaml
even params.yaml is there but dvc.yaml is not there.

## Description
ERROR: '<my path>/mnist/.dvc/tmp/exps/tmpxo1bv22y/dvc.yaml' does not exist

### Reproduce
this is my repo structure

    ├── data
    │   └── MNIST
    │       └── raw
    │           ├── t10k-images-idx3-ubyte
    │           ├── t10k-images-idx3-ubyte.gz
    │           ├── t10k-labels-idx1-ubyte
    │           ├── t10k-labels-idx1-ubyte.gz
    │           ├── train-images-idx3-ubyte
    │           ├── train-images-idx3-ubyte.gz
    │           ├── train-labels-idx1-ubyte
    │           └── train-labels-idx1-ubyte.gz
    ├── dvc.lock
    ├── dvc.yaml
    ├── nohup.out
    ├── params.yaml
    ├── results
    │   ├── metrics.json
    │   └── plots
    │       └── metrics
    │           ├── accuracy.tsv
    │           └── loss.tsv
    └── src
        ├── dvc_experiment.ipynb
        ├── modules.py
        ├── __pycache__
        │   ├── modules.cpython-39.pyc
        │   ├── tasks.cpython-310.pyc
        │   └── tasks.cpython-39.pyc
        └── train.py

this is params.yaml

    mnist:
      epochs: 1
      lr: 0.001
      momentum: 0.5

this is dvc.yaml

    stages:
      train:
        cmd: python mnist/src/train.py
        deps:
        - src/train.py
        params:
        - mnist.epochs
        - mnist.lr
        - mnist.momentum
    metrics:
    - results/metrics.json
    plots:
    - results/plots/metrics:
        x: step

steps of making queue
1.  dvc exp run --queue -S "mnist.lr=0.001" -S "mnist.momentum=0.2, 0.5" 

2. then I run all queue as experiment with 'dvc exp run --run-all'
then get error not found dvc.yaml in ERROR: '<my path>/mnist/.dvc/tmp/exps/tmpxo1bv22y/dvc.yaml' does not exist

3. or I run queue with start with 'dvc queue start'
get error but do not show the descriptions I will find it that get error with dvc queue status -> faild

### Expected
 run queue as like as single exp run

### Environment information

**Output of `dvc doctor`:**

    DVC version: 3.48.4 (pip)
    -------------------------
    Platform: Python 3.10.12 on Linux-6.5.0-41-generic-x86_64-with-glibc2.35
    Subprojects:
            dvc_data = 3.14.1
            dvc_objects = 5.1.0
            dvc_render = 1.0.1
            dvc_task = 0.3.0
            scmrepo = 3.2.0
    Supports:
            http (aiohttp = 3.9.3, aiohttp-retry = 2.8.3),
            https (aiohttp = 3.9.3, aiohttp-retry = 2.8.3),
            ssh (sshfs = 2023.10.0)
    Config:
            Global: /home/fteam4/.config/dvc
            System: /etc/xdg/dvc
    Cache types: hardlink, symlink
    Cache directory: ext4 on /dev/sda1
    Caches: local
    Remotes: local
    Workspace directory: ext4 on /dev/sda1
    Repo: dvc, git
    Repo.site_cache_dir: /var/tmp/dvc/repo/3ca893080cef4a8f55e4a30b7747face

**Additional Information (if any):**

**Comment by shcheklein** [comment]
Can you make sure that `dvc.yaml` is not gitignored and that it's committed to GIt?  Is there a repo to actually clone and try to run?

**Comment by Hamzeluie** [comment]
no it is not in gitignore and dvcignore
this issue solved. i do not know how.
i uninstall dvc then installed it again and it solved. but version of dvc does not changed.
an other problem occurred after running each example queue  give this warning 

"WARNING:dvc_studio_client:expected a dictionary for dictionary value @ data['metrics']['src/results/metrics.json']['error']. Got FileNotFoundError(2, 'No such file or directory')"

**Comment by shcheklein** [comment]
> then save just last experiment accuracy and loss and others do not save

could you clarify?

> "WARNING:dvc_studio_client:expected a dictionary for dictionary value @ data['metrics']['src/results/metrics.json']['error']. Got FileNotFoundError(2, 'No such file or directory')"

it seems you are not creating the file `src/results/metrics.json`. How does your dvclive code looks like?

(I'm closing this one, please create a new issue with answers and more details to continue)
