### ISSUE TITLE
dvc.api DVCFileSystem do not use cache

### ISSUE THREAD

**Issue by clenico** [iterative/dvc#10471]
Hi !
I am encountering some issues while using DVC. We would like to be able to fetch a versionned dataset using DVC.  

Help would be greatly appreciated ! 

Thank you a lot for the work you put into this !

# Bug Report

## Description

DVC documentation states that cache will be reused when using `DVCFileSystem.get` command. Running the function twice redownload everything. 

### Reproduce
Execute this inside a jupyter notebook:

Given a repository configured as:
``` toml
[core]
    analytics = false
    autostage = true
    remote = storage
['remote "storage"']
    url = s3://bucket/dataset/
    endpointurl = http://minio.endpoint.com:8910
    access_key_id = user
    secret_access_key = pass
```

``` python
from dvc.api import DVCFileSystem
url = f"https://user:{token}@path/to/repo"
dvc_fs = DVCFileSystem(url, rev="v3")
```
``` python
%%time
dvc_fs.get("data", "data", recursive=True)
```
``` python
%%time
dvc_fs.get("data", "data", recursive=True)
```
### Expected

I expected second call to be much quicker to execute since it should only check files are present.

### Environment information

Python 3.10.12
dvc==3.13.3

**Output of `dvc doctor`:**

```console
9:34:01 › dvc doctor                                                                                                                                                 
DVC version: 3.13.3 (pip)                                                                                                                       
-------------------------                                                                                                             
Platform: Python 3.10.12 on Linux-6.5.0-41-generic-x86_64-with-glibc2.35                                                                                               
Subprojects:                                                                                                                                                  
        dvc_data = 2.12.2
        dvc_objects = 0.25.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.1.0
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.28.17)
Config:
        Global: /home/imagedpt/.config/dvc
        System: /etc/xdg/xdg-xmonad/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/a51859b3cd5d2e970e30c86866fa3b40
```

**Comment by skshetry** [comment]
`3.13.3` is a very old dvc version. Could you please try with the latest version?

**Comment by clenico** [comment]
I somehow ended up with a old version of DVC... works like a charm on `dvc[s3]==3.51.2`.

**Comment by clenico** [comment]
For those who could be having the same issue. My workaround is the following:
first call `dvc_fs.repo.fetch()` that will fill up the cache using asyncio (faster). 

You can then call the get method that will be faster as cache will be used. To be noted, cache is not filled up by the get method call.

**Comment by skshetry** [comment]
`dvcfs.repo` is an internal of a DVCFileSystem, so I cannot help with it unfortunately.

I looked into `DVCFileSystem` and the fact that files are not cached is expected, since the cache directories are ephemeral for remote urls. Even for local urls, we'll spend unnecessary cycles saving them to the cache and can be much faster to just stream from remotes.

With that said, there is a yet to-be documented `cache=True|False` argument that you can pass to `get` and `get_file` API which will do the caching.
