### ISSUE TITLE
RPM missing dependency on RHEL 8 variants

### ISSUE THREAD

**Issue by darrinsmart** [iterative/dvc#10490]
# Bug Report

I can install the rpm on a Rocky 8 box without error. However the binary won't run:

```bash
$ dvc --help
[269041] Error loading Python lib '/usr/lib/dvc/libpython3.10.so.1.0': dlopen: libcrypt.so.2: cannot open shared object file: No such file or directory
```

It's usual for RPM packages to specify dependencies so that yum/dnf can pull in any required packages, but the list is very minimal here:

```bash
$ rpm -qp dvc-3.51.2-1.x86_64.rpm --requires
git >= 1.7.0
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
```

In any case if it had a dependency on libcrypt.so.2 it would not find one - el8 only has libcrypt.so.1 and I can't find an existing el8 package for the newer version.

Possible fixes:
1. Build against libcrypt.so.1 which would work on both el8 and el9 variants (el9 has the libxcrypt-compat package for the .so.1 version)
2. Bundle libcrypt.so.2 with the RPM, or statically link against it
3. Publish separate el8 and el9 RPMs
4. Document that the RPM is only for el9 & later RHEL variants

**Comment by shcheklein** [comment]
Yep, it's a bit hard for us to maintain separate version, static linking, etc. Especially, considering that in most cases people install it via pip / conda (since you need it for DVCLive to operate anyway).

We are thinking about dropping binaries, like RPM. 

@darrinsmart what is your use case? why `pip` / `conda` doesn't work in your case?

**Comment by darrinsmart** [comment]
It's not a big deal really. We deploy developer systems pre-configured with the necessary build tools & libraries, and it is currently all done with RPM packages. I was adding DVC into the mix and picked the RPM thinking it would be the easiest way.
We can just use the pip method instead.

**Comment by shcheklein** [comment]
Okay, let me close this since there is an easy workaround for now. Thanks @darrinsmart !
