### ISSUE TITLE
repro: change 'already exists' msg

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1050]
https://discuss.dvc.org/t/tutorial-improvement-other-suggestions/79

**Comment by SRITANU** [comment]
I'd like to take this one up.

**Comment by shcheklein** [comment]
@SRITANU sounds good!

**Comment by SRITANU** [comment]
I am extremely busy with my work. If anyone wants to take up the issue, please feel free to do that. If not, I am gonna get back to this issue when I get time.
