### ISSUE TITLE
Ability to track Docker images in Docker Hub or AWS ECR as artifacts

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#10508]
I am considering to use GTO for keeping track of the Git commits pointing to the HEAD from which a Docker image was built instead of plain Git tags, but tags with some more semantics. I think it might be useful if I could add the Docker image information and URI to the `artifacts` section of the `dvc.yaml`, where `path` is the image URI. But I don't think such URI is currently supported by DVC.

**Comment by shcheklein** [comment]
Hey, sounds intreresing.

AFAIR GTO can be used w/o `dvc.yaml` . 

Are you also considering using Studio to manipulate tags, visualize them, access directly those artifacts?

to probably rephrase it: what is the purpose of storing these URI in the `dvc.yaml` in your case?

**Comment by aschuh-hf** [comment]
Good question. TBH I just thought about using GTO for version control (indexing) of Docker images in ECR combined with CI/CD triggers to build and publish those images. To use GTO as a container image registry if you will, similar to a model registry. The first I was thinking was to add an entry to the `artifacts` section to document that such output exists, including the image URI of the image pushed by the CI/CD workflow alongside with some metadata which is of interest to consumers. Things that aren't captured by just a Git tag.

A concrete container image URI would also be a parameter / dependency of a DVC stage, e.g., one which submits a Ray job to a cluster (more specifically using Anyscale, where the [JobConfig](https://docs.anyscale.com/reference/job-api#jobconfig) has an `image_uri` key). The Docker image is a dependency here to make that DVC stage reproducible.

For now, I have separated Docker image build from Docker image use in a DVC pipeline, where the `image_uri` is a parameter rather than a dependency. But I wonder how to best make a link between the two stages, where a Docker image is an output of a DVC stage to be consumed by a subsequent stage. In this scenario, just like a trained model file, the Docker image is an artifact produced by the DVC pipeline.

**Comment by shcheklein** [comment]
I guess it can be just a simple file with a link inside that is produced by a stage that is preparing and publishing the docker image? It doesn't have to be inside the `dvc.yaml`. GTO can work w/o the artifacts section as well. WDYT?

**Comment by aschuh-hf** [comment]
Yes, I suppose that's sufficient. A colleague actually has gone down this road already.

**Comment by shcheklein** [comment]
Yep, closing this for now then. Feel free to reopen / ask more questions in this thread though :)
