### ISSUE TITLE
pipeline-show: add --dot option 

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1051]
Output in .dot format suitable for further rendering with graphviz

**Comment by dmpetrov** [comment]
We need to make sure it won't create any dependencies to low-level libs or drivers (the issue that we had before).

**Comment by efiop** [comment]
It wont, because we only need to write dot file and we don't need to render it.

**Comment by pared** [comment]
Hi, i would like to participate in this task. 
1. Now the only existing option is "--ascii"? (it seems so from help, just want to make sure)
2. If we want to further render it with graphviz, we need to provide filename as argument?

**Comment by efiop** [comment]
Hi @pared !

> 1. Now the only existing option is "--ascii"? (it seems so from help, just want to make sure)

There is also a default one that just prints stages sequentially.

> 2. If we want to further render it with graphviz, we need to provide filename as argument?

I don't think dvc should handle the dot -> image rendering itself, but it should output graph in .dot format that could be later rendered by user with any tool of his choice. So it should look something like:
```
$ dvc pipeline show --dot graph.dot
$ dot -Tps graph.dot -o graph.ps
```

The most of the logic is in `dvc/command/pipeline.py` where you could find examples for the default behavior as well as `--ascii`. Notice that `self.project.pipelines()` as well as `self.project.graph()` return networkx graph objects, so it should be easy to use them to produce the .dot file. Here is a simple [example](https://networkx.github.io/documentation/stable/auto_examples/pygraphviz/write_dotfile.html) .

Thank you so much for looking into it! Please feel free to ping me if you need anything.

-Ruslan

**Comment by pared** [comment]
During diggin in subject i saw that when we use 

`pipeline show X.dvc -o` 

(sample project from main webpage) out files are written to std under each other, while with `--ascii` data.tsv and data-test.tsv are on same level. Maybe we should display out files in format line per stage?
Just an idea for issue.
Pawel

**Comment by efiop** [comment]
Hi @pared !

Good point! The current default behavior of `pipeline show` is not great by itself in terms of visualization and we are thinking about ditching it in favor of `--ascii` being the new default behavior. So I don't think that it is worth bothering with, unless there are users for it. If you would be willing to submit a patch for that, we will be happy to merge it. Thank you for looking into it!

-Ruslan

**Comment by pared** [comment]
I guess we can close this issue?

**Comment by efiop** [comment]
Oops, sorry. I thought that your PR had `Fixes #1051` in it and it closed automatically.

Thanks again for the PR! Closing.

**Comment by pared** [comment]
My pleasure, I will take on another task, when I will be available. Should I look for "good first issue" or just take whatever fits me?

**Comment by efiop** [comment]
Please feel free to take any task you'd like, just be sure to give a heads up, so I know that it is taken. Also feel free to ping me(e.g. on [discord](https://dvc.org/chat)) if you need anything. Thank you so much!

**Comment by efiop** [comment]
Hi @pared !

I wanted to ask you a couple of general questions. Would you be willing to have a video call? Sorry, I couldn't find your email or any other contact info in your profile and google didn't help either. Please ping me through email(it is in my profile) or on discord PMs(my nick is ruslan) so we could arrange a date and time.

Thanks,
Ruslan
