### ISSUE TITLE
`dvc status`: add flag to ignore files excepted from cache.

### ISSUE THREAD

**Issue by c-w-feldmann** [iterative/dvc#10521]
Hi,
I have a project where I encoded a series of data processing steps as a dvc.yaml pipeline (great tool btw).
### Problem
One step results in a large (and fast to generate) file, which I excluded from beeing cached with:
```yaml
stage_xy:
    ...
    outs:
      - big_file.tsv:
          cache: false
```
Before merging changes in the projects I want to make sure that all files were pushed and the pipeline is up to date, so I added a CICD where I run:
```bash
dvc status --quiet
```
However, since this is executed on a Runner which does not have the original files, this command now fails. 
Running `dvc status` results in:
```bash
stage_xy:

	changed outs:
		deleted:           big_file.tsv
stage_yz:
        changed deps:
		deleted:            big_file.tsv
```
### Solution
I would like to propose the flag `ignore-not-cached` which would ignore files, for which no cached version is saved.

**Comment by dberenbaum** [comment]
You may want to take a look at https://dvc.org/doc/user-guide/pipelines/running-pipelines#verify-pipeline-status for ideas on how to do this.
