### ISSUE TITLE
Unable to track metrics on state file name not ending with "dvc"

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1053]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

**Comment by efiop** [comment]
Hi @pared,

Could you please elaborate on this?

**Comment by efiop** [comment]
Ok, looks like a duplicate of https://github.com/iterative/dvc/issues/1054
