### ISSUE TITLE
Slurm intergration

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1057]
Kudos @Hong-Xiang

**Comment by efiop** [comment]
Closing because of the lack of interest from the users. Please feel free to reopen.

**Comment by efiop** [comment]
@observingClouds Hi. Are you familiar with https://dvc.org/doc/command-reference/exp ? We are starting to work on remote execution for it right now, maybe that would suit your scenario better?

**Comment by observingClouds** [comment]
Thanks @efiop for your prompt reply. Is there already a documentation or an issue with the discussion on the "remote execution" which you could point me to? So far I can't see how I could use `dvc exp` to my advantage here as I assume it also has issues with `sbatch do_something.py`.

**Comment by dberenbaum** [comment]
@observingClouds Please take a look at https://github.com/iterative/dvc/issues/6440 to track progress on remote execution, which is still in its infancy right now.

More to the point, would it be possible to use `sbatch -W` (https://slurm.schedmd.com/sbatch.html#OPT_wait) to block the process until the job completes? Would this alleviate the problems you are facing?

**Comment by observingClouds** [comment]
The `sbatch -W` suggestion is fantastic! Thanks @dberenbaum. This indeed alleviate the problem quite drastically.
Thank you both for your swift and helpful comments. Keep up the great work!
