### ISSUE TITLE
cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust'

### ISSUE THREAD

**Issue by jamesdbrock** [iterative/dvc#10577]
# Bug Report

## Description

On `dvc push` or `dvc pull`, fails with

```
ERROR: unexpected error - cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)
```

### Reproduce

`dvc push` or `dvc pull`

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.55.2 (pip)
-------------------------
Platform: Python 3.10.14 on Linux-6.10.7-200.fc40.x86_64-x86_64-with-glibc2.39
Subprojects:
	dvc_data = 3.16.6
	dvc_objects = 5.1.0
	dvc_render = 1.0.2
	dvc_task = 0.3.0
	scmrepo = 3.3.8
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	ssh (sshfs = 2023.4.1)
Config:
	Global: /home/jbrock/.config/dvc
	System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/fedora_localhost--live-root
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/mapper/fedora_localhost--live-root
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/42a67e86cefc6c15df9eb735f73d7177
```

**Additional Information (if any):**

The error is happening from here in **cryptography**:

https://github.com/pyca/cryptography/blob/6b39f10598c1a291eaccdaa8b7bb2eedf4acab95/src/cryptography/exceptions.py#L9

**Comment by shcheklein** [comment]
Hmm, I've tried to rerun our tests across different OSs - https://github.com/iterative/dvc/actions/runs/11044464544 and it seems it's working fine. Could you try to use a different machine (if possible), try a fresh env?

It seems to be related to something on your env. 

Otherwise, can you reproduce it consistently with a particular fresh install of an OS?

**Comment by jamesdbrock** [comment]
I agree it's probably related to my env. If I solve the problem I'll write my notes in this issue.

**Comment by jamesdbrock** [comment]
Actually I'm going to use a different environment.
