### ISSUE TITLE
Cannot declare params in parent directory

### ISSUE THREAD

**Issue by OS-leonardopratesi** [iterative/dvc#10596]
# Bug Report
Hello we are trying to work with DVC in a monorepo configuration where in the same repo we will have multiple project each with his own pipeline inside its own dvc.yaml, this means that when we run an experiment in a specific project it will appear also in the other projects.

To overcome this we are want to have a common param for all experiment that can be then used to filter out the correct experiment group in the DVC VSCode UI.

To do this we need to have a "common_params.yaml" file in the parent directory of all the project and we expect this configuration to work inside the dvc.yaml of each pipeline:
```
params:´
- ../common_params.yaml:
   - experiment_group
```
Instead when declaring the param file as in the parent directory it is just ignored.

**Comment by shcheklein** [comment]
@OS-leonardopratesi have you considered using https://dvc.org/doc/command-reference/init#--subdir ?

that option would allow you to completely isolate DVC subprojects.

> Instead when declaring the param file as in the parent directory it is just ignored.

@OS-leonardopratesi could you clarify please? Do you mean this configuration that you mentioned:

```yaml
params:
- ../common_params.yaml:
   - experiment_group
```

or something else?

what do you mean by "ignored"? do you have stages that depend on those params outside? It would be great to have some minimal working example - a simple artificial pipelines with params outside and what command you run, etc.

**Comment by OS-leonardopratesi** [comment]
Hei I realized subdir does everything I needed, thanks.
