### ISSUE TITLE
`gc --not-in-remote`: misleading warning message

### ISSUE THREAD

**Issue by DGrady** [iterative/dvc#10590]
# Bug Report

## Description

The warning message printed when using the `--not-in-remote` flag appears to be incorrect. The behavior of the flag appears correct (consistent with the documentation); the warning message is not consistent with behavior or documentation.

### Reproduce

`dvc gc --workspace --not-in-remote`

Prints the following warning:

```
WARNING: This will remove all cache except items used in the workspace that are present in the DVC remote of the current repo.
Are you sure you want to proceed? [y/n]: 
```

The actual behavior for this command is to keep only the local cache items that are: a) referenced in the current workspace, and b) not present in the remote.

### Expected

The warning message should read, perhaps,

```
WARNING: This will remove all cache except items used in the workspace that are not present in the DVC remote of the current repo.
Are you sure you want to proceed? [y/n]: 
```

(That is, just adding the word "not".)

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

```
DVC version: 3.55.2 (pip)
-------------------------
Platform: Python 3.12.7 on macOS-15.0.1-x86_64-i386-64bit
Subprojects:
	dvc_data = 3.16.6
	dvc_objects = 5.1.0
	dvc_render = 1.0.2
	dvc_task = 0.40.2
	scmrepo = 3.3.8
Supports:
	http (aiohttp = 3.10.10, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.10.10, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2024.9.0, boto3 = 1.35.36)
Config:
	Global: /Users/dan/Library/Application Support/dvc
	System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/a60ba71a9b85f3c8d2c283884465924b
```

**Comment by shcheklein** [comment]
Good catch. It is consistent with this description I think:

https://dvc.org/doc/command-reference/gc#--not-in-remote

Please feel free to send a PR to fix this. It should be pretty straightforward hopefully.

**Comment by 5AIPAVAN** [comment]
as a beginner can i work on this please @shcheklein @DGrady :-)

**Comment by shcheklein** [comment]
@5AIPAVAN yes, absolutely, feel free to take it!

**Comment by DGrady** [comment]
@5AIPAVAN that would be great!
