### ISSUE TITLE
Cannot add azure remote

### ISSUE THREAD

**Issue by dom-nura** [iterative/dvc#10624]
# Bug Report
Following various instructions, this doesn't work on dvc 3.56, python 3.12

```
dvc remote add  azure azure://hello
dvc remote modify azure endpointurl azure://hello2
```

produces:
```
ERROR: configuration error - config file error: extra keys not allowed @ data['remote']['azure']['endpointurl']
```

how can I add account_name, connection_string, etc?

**Comment by skshetry** [comment]
PTAL at https://dvc.org/doc/user-guide/data-management/remote-storage/azure-blob-storage.

If you are trying to change the URL, (`azure://hello` to `azure://hello2`), you can do so via:

```console
dvc remote modify azure url azure://hello2
```

Take a note that it is a _url_, not the _endpointurl_. `endpointurl` is a different thing - it's a server url, not the path, and is not supported by Azure. That needs to be set in the `connection_string` for Azure (but I don't think you need that if you are connecting to Azure).

You can set `connection_string` and other configs like the way you have tried to set `endpointurl` above, but PTAL at the above docs.
