### ISSUE TITLE
`dvc exp remove --queue -A`: possibly incomplete result returned

### ISSUE THREAD

**Issue by rmic** [iterative/dvc#10638]
# Bug Report

## Description

As discussed in https://github.com/iterative/dvc/pull/10633#discussion_r1857943029, 
when using `dvc exp remove` with both `--queue` and `-A `, an incomplete list of removed experiments might be returned: the queued ones would be missing from the returned list, even if they are effectively removed as expected.

This is just a minor inconvenience at the moment, but for the sake of correctness and code cleanliness, I'll put it here.

### Reproduce

1. create repo
2. run experiments 
3. queue experiments (`dvc exp run --queue`)
4. `dvc exp remove --queue -A`

### Expected
The list of all experiments, both queued and committed
**Additional Information (if any):**

https://github.com/iterative/dvc/blob/d38b2dbcb873b5112976c5ad40c5574b5d2a41f3/dvc/repo/experiments/remove.py#L69-L71

line 71 should use `removed.extend` just as it is done in the other if / elif code blocks

I can start working on it soon.

**Comment by shcheklein** [comment]
thanks @rmic ! where do we use the returned value atm? E.g. does it affect the way we print the results for the `dvc exp remove` command to the screen?

**Comment by rmic** [comment]
The place where this seems the most visible is in 

https://github.com/iterative/dvc/blob/d38b2dbcb873b5112976c5ad40c5574b5d2a41f3/dvc/commands/experiments/remove.py#L30-L39

which is where the list of removed experiments is displayed to the user on the CLI

The returned value is probably also used in tests here and there, but as they all pass, this probably means that this combination is currently not being tested (or only with an empty queue). At least in the relevant tests I'm familiar with for remove (i.e.: [`tests/func/experiments/test_remove.py`](https://github.com/iterative/dvc/blob/d38b2dbcb873b5112976c5ad40c5574b5d2a41f3/tests/func/experiments/test_remove.py) ), there are tests that : 
- remove specific experiments from the queue
- remove all experiments from the queue
- remove specific commits 
- remove all commits 

but none that tests both all queued and all commits.

**Comment by shcheklein** [comment]
Good, thanks. I think it makes sense to fix it to return the proper list of experiments (even to be printed properly). It's weird that if we remove queued experiments we pretty much don't print anything (?). Thanks for the detailed analysis and explanation @rmic !
