### ISSUE TITLE
Set core.checksum_jobs can not accelerate dvc operations

### ISSUE THREAD

**Issue by jiangtann** [iterative/dvc#10648]
# Bug Report

## Description

I use git and dvc to manage my training datasets, which consists of thousands of `jsonl` files. 

I use `dvc add file1.jsonl file2.jsonl ... file9999.jsonl`(just to illustrate, a shell script is actually used) to add .dvc file for every jsonl file.

After I change `core.site_cache_dir` and execute `dvc status`, I can only see two dvc process in `htop`, although I have already set core.checksum_jobs as 8. And it takes too long to finish `dvc status`.

### Reproduce

```sh
cd /path/to/repo/
dvc config core.checksum_jobs 8

# First set core.site_cache_dir, so last site_cache_dir is at /var/tmp/dvc/repo/xxx
dvc config core.site_cache_dir $(pwd)/.dvc/site_cache_dir
dvc status
```
Execute `htop` in terminal:
![Image](https://github.com/user-attachments/assets/f09b5846-5224-47ac-9abf-6b4198b7c62e)

### Expected

`core.checksum_jobs=8` means 8 process hash different jsonl files concurrently, am I correct? Just like this:
```python
with multiprocessing.Pool(8) as pool:
    hashes = list(pool.map(hash_function, all_files_to_hash))
```

I expect to see at least 8 process in `htop`, so the `hashes` and `links` can be quickly built if I change core.site_cache_dir. Now it takes too long to execute `dvc status`.

I think `core.checksum_jobs` also influence `dvc add` and `dvc checkout`, so if `core.checksum_jobs` works correctly, the process of `dvc add` many jsonl files can be also accelerated.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.55.2 (pip)
-------------------------
Platform: Python 3.9.19 on Linux-5.14.0-284.25.1.el9_2.x86_64-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 3.16.5
        dvc_objects = 5.1.0
        dvc_render = 1.0.2
        dvc_task = 0.4.0
        scmrepo = 3.3.7
Supports:
        http (aiohttp = 3.10.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.10.5, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2024.6.1, boto3 = 1.35.7)
Config:
        Global: /mnt/afs/jiangtan/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: fuse.quarkfs_client on quarkfs_client
Caches: local
Remotes: s3
Workspace directory: fuse.quarkfs_client on quarkfs_client
Repo: dvc, git
Repo.site_cache_dir: /path/to/repo/.dvc/site_cache_dir/repo/eddf3641719990517f0cfc808ea33376
```

**Comment by skshetry** [comment]
DVC uses multiple threads to process files, not processes. The `core.checksum_jobs` only applies if:

1. The file size exceeds 1MB, and
2. The target is a directory (eg: `dvc add jsons/`).

Regarding the first, DVC hashes files in two stages: it uses multiple threads concurrently to hash file  larger than 1 MB, and then it hashes small files sequentially. This was done to reduce thread overhead. There have been suggestions to make this configurable, and I am open to it.

(NB: that happens here: https://github.com/iterative/dvc-data/blob/aea2be100b0cf4c8bcdb1dc0755bcee10bff296c/src/dvc_data/hashfile/build.py#L98-L102).

Additionally, I'd suggest tracking all those files as a directory.

**Comment by jiangtann** [comment]
Thank you for your answer!

So currently, `dvc add file1 file2 ...`, `dvc checkout` and `dvc status` all sequentially hash files? This means that unless the target is a directory, only the hash value of one file will be calculated at a time.

**The reason why we use a `.dvc` file to track a `jsonl` file instead of a directory:**

We are a LLM team,  and multiple colleagues continuously collect new training datasets (jsonl files, most files exceed 1MiB) together. We use git + dvc (similar to git-lfs) to manage our training dataset repository. We use an empty git branch to commit collected files and then create a PR. 

If we don't use an empty branch specifically for committing data, everyone will have to keep a completed repository (If using directories, you must `dvc pull` first and then move new data to a directory and then `dvc add directory`). But we expect to keep only one completed repository for sharing data or training LLM. In this way, we can reduce storage waste.

So in this situation, is there no other way to accelerate hashing files? Why not hash different files concurrently to get all hashes more quickly?

**Comment by skshetry** [comment]
> We use an empty git branch to commit collected files and then create a PR.

I don't understand what you mean by empty git branch.

> If we don't use an empty branch specifically for committing data, everyone will have to keep a completed repository (If using directories, you must `dvc pull` first and then move new data to a directory and then `dvc add directory`). 

Have you seen [Modifying Large Datasets - dvc.org](https://dvc.org/doc/user-guide/data-management/modifying-large-datasets)? You don't have to `pull` everything, you can modify/add/update a single file in a directory without downloading all the files.

```console
mkdir -p jsons
echo '{"key": "value"}' >> jsons/my.json
dvc add jsons/my.json
```

Then this will update `jsons.dvc` which you'll have to git-commit. Yes you will have to synchronize the merges to the `main` branch, but you don't have to keep a complete data locally.

> So in this situation, is there no other way to accelerate hashing files? Why not hash different files concurrently to get all hashes more quickly?

This is a limitation of our internal architecture. I'm afraid there's no way to parallelize hashing `add`, `commit` and `status` at the moment.

**Comment by jiangtann** [comment]
Thank you for the reminder. `dvc add jsons/my.json` works even if jsons/other_files do not exist locally.

The workflow of our repository:

`main branch`(Actually the directory structure is more complex):

```sh
$ cd /path/to/repo/
$ tree
.
├── 202408
│   ├── class1
│   │   ├── dataset_yyy.jsonl
│   │   ├── dataset_yyy.jsonl.dvc
│   ├── class2
│   │   ├── source_data
│   │   │    ├── original_dataset_xxx.jsonl
│   │   │    ├── original_dataset_xxx.jsonl.dvc
│   │   ├── dataset_xxx.jsonl
│   │   ├── dataset_xxx.jsonl.dvc
├── 202409
│   ├── class1
│   │   ├── dataset_xxx.jsonl
│   │   ├── dataset_xxx.jsonl.dvc
...
```

`empty branch` refers to a branch dedicated to committing data, which is initially empty but only new training datasets are added later
`empty branch` of Person A:

```sh
$ cd /path/to/repo/
$ tree
.
├── 202409
│   ├── class1
│   │   ├── new_dataset_yyy.jsonl
│   │   ├── new_dataset_yyy.jsonl.dvc
├── 202410
│   ├── class1
│   │   ├── new_dataset_xxx.jsonl
│   │   ├── new_dataset_xxx.jsonl.dvc
...
```

After A execute `dvc add && dvc push && git push` and create PR, the repository administrator merge PR and execute `git pull && dvc pull`.

`main branch`:
```sh
$ cd /path/to/repo/
$ tree
.
├── 202408
│   ├── class1
│   │   ├── dataset_yyy.jsonl
│   │   ├── dataset_yyy.jsonl.dvc
│   ├── class2
│   │   ├── source_data
│   │   │    ├── original_dataset_xxx.jsonl
│   │   │    ├── original_dataset_xxx.jsonl.dvc
│   │   ├── dataset_xxx.jsonl
│   │   ├── dataset_xxx.jsonl.dvc
├── 202409
│   ├── class1
│   │   ├── dataset_xxx.jsonl
│   │   ├── dataset_xxx.jsonl.dvc
│   │   ├── new_dataset_yyy.jsonl
│   │   ├── new_dataset_yyy.jsonl.dvc
├── 202410
│   ├── class1
│   │   ├── new_dataset_xxx.jsonl
│   │   ├── new_dataset_xxx.jsonl.dvc
...
```

Advantages of using this workflow:
- Person A do not need to know the repo structure or other training dataset files. He only needs to care about his own new dataset files.
- Git conflict is rare, unless different people use same directory name and same file name (very low probability)

Although `dvc add jsons/my.json` works, we plan to keep current workflow. Hope parallelize hashing can be realize in a later dvc version.

Anyway, thanks for your answer!

**Comment by skshetry** [comment]
What is the reason to use dvc/git here in your workflow instead of just pushing to s3 or any other cloud storage?

Is requiring administrator merge a compliance issue? 

I'm thinking whether https://github.com/iterative/datachain might be a right tool for you. It allows you to keep files in a cloud storage and provides a query layer to filter/transform data.

**Comment by jiangtann** [comment]
We need version control system of large files (most our jsonl files exceed 10MB). 

If directly push jsonl files to s3 without any version control system, we will miss a lof of information. For example, we do not know who commit the specific dataset if we find some errors exsit in the jsonl file. 

We often need to modify a jsonl file (format check, clean, filter etc.) . If a wrong modification occurs, we will need rollback.

In our workflow, dvc is an alternative to git-lfs. Because we use s3 as backend, we choose dvc.
