### ISSUE TITLE
dvc exp show does not visualize experiments

### ISSUE THREAD

**Issue by OS-leonardopratesi** [iterative/dvc#10645]
# Bug Report

After running some experiments in branch A,  I then pushed the experiments in dvc, then I squashed and merge branch A into main, and then deleted branch A.
Now I can still see the experiments with `dvc exp list --all`.
I can apply the experiments with `dvc exp apply`.
But it I do `dvc exp show` I cannot see any experiment.

### Reproduce
- run some experiments in a branch
- push the experiments `dvc exp push origin --all`
- squash and merge the branch
- delete the branch
- run `dvc exp show --all-commit --all-branches` 

### Expected
![Image](https://github.com/user-attachments/assets/79dd437f-9d62-458e-b695-86af0f7c665f)

### Environment information

DVC version: 3.56.0 (pip)
-------------------------
Platform: Python 3.10.12 on Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 3.16.7
        dvc_objects = 5.1.0
        dvc_render = 1.0.2
        dvc_task = 0.40.2
        scmrepo = 3.3.8
Supports:
        http (aiohttp = 3.11.4, aiohttp-retry = 2.9.1),
        https (aiohttp = 3.11.4, aiohttp-retry = 2.9.1),
        s3 (s3fs = 2024.10.0, boto3 = 1.35.36)
Config:
        Global: /home/leopra96/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sdc
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/c956f7904aee9f04196cd0369a56f204
```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by shcheklein** [comment]
Since branch is delete I'm not sure why those experiments should be still visible tbh.

Most likely `dvc exp list --all` is working in a bit different way - it will show all "dangling" experiments. Probably running `git gc` should clean them up. We can probably indicate it somehow in the output - but it's a separate issue.

**Comment by OS-leonardopratesi** [comment]
Thanks for the fast response, it makes sense. I was wondering what is the correct workflow you had in mind when designing dvc. The usual workflow of creating a branch - run the experiments - merge and delete the branch is not optimal in this case. 
It would be ideal to not lose the experiments once the branch is deleted, is there a way to move them to the main branch after the merge?
Thanks

**Comment by shcheklein** [comment]
@OS-leonardopratesi I guess you can make some of those experiments proper commits for example?

to a certain degree the idea was I think that it's fine to drop `dvc exp` experiments at some point, commits serve as a "best" version of them.

in case they are all needed - keep branches? which also gives some structure I think to it
