### ISSUE TITLE
Feature request: add a --yes option to dvc run

### ISSUE THREAD

**Issue by tdeboissiere** [iterative/dvc#1072]
At the moment, there is no straightforward way to call `dvc run XXX` twice without running into `XXX.dvc already exists. Do you wish to run the command and overwrite it? (y/n)`. It would be nice to provide an additional argument like `--yes` to force dvc to overwrite the `XXX.dvc` file.

Not sure if this functionality is really needed as we could always switch to dvc repro...

**Comment by efiop** [comment]
Great point! I'll look into it shortly. Thank you!
