### ISSUE TITLE
Feature request: Process dependencies with dvc pull

### ISSUE THREAD

**Issue by tdeboissiere** [iterative/dvc#1077]
- Let's say I have 2 dvc files: `File1.dvc`, `File2.dvc`. In this pipeline, `File2.dvc` depends on `File1.dvc`.
- Let's say each stage creates some data which is put under dvc control.
- If I remove the data thus created (without clearing the cache), and then call `dvc pull File2.dvc`, only the data created by `File2.dvc` is pulled.

Would it be possible to also pull the data from any dependency of `File2.dvc` ?

**Comment by efiop** [comment]
Got it! This is a truly useful feature, thank you for suggesting! I will be sure to add support for it ASAP, should be merged and released util tomorrow.

Thanks,
Ruslan

**Comment by efiop** [comment]
> Actually, several commands would likely benefit from such an option, for instance fetch, remove etc.

`fetch`, `pull` and `status -c` will sure get the same option. The case about `dvc remove` is a more interesting one, but seems to be very useful as well, I will be sure to take a look at it after I'm done with `pull/push/fetch`.

**Comment by efiop** [comment]
Sorry it takes longer than expected. Things got a little busy :slightly_smiling_face: Should be ready until the end of the week.

Thanks,
Ruslan

**Comment by efiop** [comment]
Hi @tdeboissiere !

Once again, sorry that it takes longer than expected. We plan to release 0.19 with this feature until Monday. Thank you for the patience!

-Ruslan
