### ISSUE TITLE
make `dvc cache type` check for available links

### ISSUE THREAD

**Issue by tdeboissiere** [iterative/dvc#1078]
`dvc config cache.type reflink` will modify `.dvc/config` even if reflinks are not available on a given system. The error will only be caught later when some command tries to add data to the cache.

Example with `dvc add`:
```
Error: Failed to add '/home/user//data/mydata': No possible cache types left to try out.
```

Would it be possible to catch the error at the time of the `dvc config` command ?

**Comment by efiop** [comment]
Hi @tdeboissiere !

You are right, we should check that at least as a matter of convenience. Also, note that if `cache.type` is not configured, dvc has a default list of four link types in such order(from best to worst): [reflink, hardlink, symlink, copy] and will go through them util it finds something that works.

Thanks,
Ruslan

**Comment by tdeboissiere** [comment]
@efiop indeed ! So far, I was not setting the `cache.type` manually and never had an issue. It was when I decided to try out reflinks that I found this issue.

**Comment by efiop** [comment]
Ah, I see. Mind that reflinks are supported only by some filesystems right now, though the support for them is coming to most of the newer filesystems and should be standard in the future. If I remember correctly, you are using Ubuntu, which by default formats drives in ext4, which currently does not support reflinks. If you want to use reflinks on Linux, you will have to format a partition(e.g. maybe an external drive or flash drive) in XFS(prefered) or BTRFS filesystem. If you have a recent Mac that uses APFS filesystem(i.e. High Sierra and never) will work as is.

Thanks,
Ruslan

**Comment by efiop** [comment]
`dvc version` shows which links are available. `dvc config` itself should not catch that, but maybe it looks like a the job for `dvc cache type`, which is allowed to be smarter :slightly_smiling_face:

**Comment by efiop** [comment]
Closing as stale.
