### ISSUE TITLE
Improve missing output message

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1085]
Command:

```
dvc run -d code/xml_to_tsv.py -d data/Posts.xml -o data/Posts.tsv python code/xml_to_tsv.py data/Posts.xml data/Posts.tsv
```

when script xml_to_tsv fails to produce output (no errors), DVC output this message:

Error: Failed to run command: Output 'data/Posts.tsv' error: does not exist

it's ambiguous - not clear if there is a problem with the script (fails to run) or DVC command. Let's try to explain it better.

**Comment by mroutis** [comment]
@shcheklein , is this still relevant? this is the current error message, it is clear for me:
```bash
❯ dvc run -o foo 'echo "something"'
Running command:
        echo "something"
something
ERROR: failed to run command - output 'foo' does not exist

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
```

**Comment by mroutis** [comment]
Maybe the error shouldn't say `failed to run command` because the command was, indeed, successful (exit code 0)

**Comment by shcheklein** [comment]
@mroutis the current message is the same as it was before. Cryptic and confusing. So, it's still relevant. We can come with a way better and user friendly message I hope :)

**Comment by efiop** [comment]
@shcheklein How is `output 'foo' does not exist` cryptic? It is clearly stating what is wrong. Do you suggest we add something like `Check that your command is indeed creating this output.`?
