### ISSUE TITLE
consider redesigning state file

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1091]
Currently we store state in a json file .dvc/state and limit it to 10000 entries. We also don't save state for files smaller than 7MB. While these were the means to workaround other limitations, we definitely need to consider thinking about a better solution.

**Comment by andrethrill** [comment]
Hi @efiop!

Does the current size limitation limits the number of files DVC can currently keep track of?

If yes, if I dvc track a directory, what goes into the state file:
- the info regarding the dir itself only (small state file usage)?
- the infor regarding the dir itself and all the files inside it (large state file usage?

**Comment by efiop** [comment]
Hi @andrethrill !

State file is only used for optimization, so you don't have to recompute checksums for large files. It doesn't affect the core functionality of dvc and doesn't limit the number of files that dvc can keep track of. 
When saving state for the directory, dvc will save state about the directory itself(effective inode, effective checksum, effective mtime) as well as state(inode, checksum, mtime) for each file in the directory that is bigger than 7MB. When the limit of entries in the state file is reached, dvc will simply drop the previous state and next time compute it once again and will put it into the state file for later use.

Thanks,
Ruslan

**Comment by efiop** [comment]
@andrethrill Unfortunately yes, in the current implementation. I'm working on a better solution right now, should be ready for 0.19.0 very soon. The current limit was introduced a day ago with 0.18.12 to help with another issue where I suspected that state file got way too big.

**Comment by andrethrill** [comment]
That's perfect. Thank you for the explanation!
