### ISSUE TITLE
Too much concurrence in remote push and pull

### ISSUE THREAD

**Issue by juhai** [iterative/dvc#1094]
DVC version 0.18.12, Mac High Sierra with pip on Python 3.6.4

We use [Minio](https://www.minio.io/) for a local S3 backend and I want to use that as the remote for my data files. DVC works ok for Amazon S3 (most likely due to slower network connection). For local network S3 backend connection, the following happens:
- RemoteLOCAL.push uses as many threads as there are chunks/files in the push command.
- After a few seconds of push, the progressbar stops and dvc can't be killed with Ctrl-C or Ctrl-Z
- Furthermore, my Mac stops responding to anything. I suspect the OS gets congested with a high level of concurrent network requests. I need to boot my Mac in most cases ;(

I have a fix for this:
In https://github.com/iterative/dvc/blob/master/dvc/remote/local.py#L658
```
        with ThreadPoolExecutor(max_workers=len(chunks)) as executor:
            for to_infos, from_infos, names in chunks:
                res = executor.submit(remote.upload,
                ...
```
The number of chunks defines level of concurrence, which I think this is wrong. Instead, there should be a sensible maximum concurrence. I have not noticed any issues with pull operation but that applies the same logic. AWS cli uses default concurrence of 10; that works for me but slows down other network connections too much. I would suggest to use four to make sure enough many operations are ongoing to allow small and large files to be processed simultaneously.

I will make a PR for this to limit amount of concurrence. I am afraid it's difficult to test, though.

**Comment by efiop** [comment]
Hi @juhai !

Dvc actually has a limit for the concurrent jobs which is regulated with `--jobs N` option for `dvc push/pull/fetch`. The default number of jobs is set here:

https://github.com/iterative/dvc/blob/master/dvc/cli.py#L260
```
                        default=8*cpu_count(),
```

So it defaults to 8 * (number of your cpu cores). If it is too much for your scenario, you can specify some smaller set number with `--jobs`.

Right before the code that you've noted, there is:

https://github.com/iterative/dvc/blob/master/dvc/remote/local.py#L646
```
        chunks = list(zip(to_chunks(path_infos, jobs),
                          to_chunks(cache, jobs),
                          to_chunks(names, jobs)))
```

which splits targets into `jobs` chunks, which is limiting the number of threads.

Thanks,
Ruslan

**Comment by juhai** [comment]
Amazing, how did I miss that. Works fine with that option. I still think the default is way too big and it might be better to have a more conservative default with user's choice to increase concurrence. On my Mac the default is 64.

**Comment by efiop** [comment]
Good point! What maximum number of threads works for you?

**Comment by juhai** [comment]
Hi @efiop, the push that previously failed with 64 threads, passes with 32 so I would be happy with a multiplier of 4. Is there any benefit from using anything above cpu_count()?

**Comment by efiop** [comment]
Great, I'll send a patch with a multiplier of 4 ASAP and will release new version after that.

Generally there is a benefit, since it is not a CPU intensive task and rather a IO intensive.

Thank you for your feedback!

**Comment by juhai** [comment]
Thanks for the quick fix!

**Comment by efiop** [comment]
@juhai 0.18.13 is out. Please feel free to give it a try. And thank you for the feedback!

**Comment by juhai** [comment]
@efiop Works now with the default concurrence.
