### ISSUE TITLE
`dvc run` without arguments should show help instead of producing an empty dvc file

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1100]
Right now `dvc run` produces:

```
cmd: ''
md5: 103a608cacf27fc1a59526a0096da33d
```

I'm not sure if it makes sense to do that. Probably it's just better to show help?

**Comment by efiop** [comment]
Hm, looked into it right now and discovered that I have added a test for that :slightly_smiling_face: Looks like I was considering it a corner case of sorts. I'll give it a better thought again soon. Thank you for noticing!

**Comment by shcheklein** [comment]
Cool, thank you. Could we check the commit message for the test? May be there is some explanation for that. Just a random suggestion :)

**Comment by shcheklein** [comment]
👍
