### ISSUE TITLE
Feature request: add flag to skip confirmation with dvc destroy

### ISSUE THREAD

**Issue by tdeboissiere** [iterative/dvc#1108]
With dvc 0.18.14, dvc destroy always asks for confirmation. There is no flag (like --yes) to skip this step.

**Comment by efiop** [comment]
Great point! Will add a support for it shortly. Probably going to be released with the 0.19 by the end of the week.

Thanks,
Ruslan

**Comment by efiop** [comment]
@tdeboissiere Have you tried `dvc destroy -f` ?

**Comment by tdeboissiere** [comment]
Yes, and it does work ! So probably destroy --yes is superfluous

**Comment by efiop** [comment]
I think so as well. Lets not introduce -y since -f works fine. Closing for now. Please feel free to reopen.
