### ISSUE TITLE
run: check that dvc file is not placed inside output directory

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1123]

**Comment by mroutis** [comment]
Why is this a bug?

Is this the correct way to reproduce it?
```
#!/usr/bin/env bash

rm -rf example
mkdir example
cd example

git init
dvc init

mkdir -p data
dvc run --cwd data -o foo 'echo foo > foo'
```

**Comment by efiop** [comment]
This is a bug, but a correct way to reproduce it would be:
```
#!/bin/bash

set -e
set -x

rm -rf myrepo
mkdir myrepo
cd myrepo
git init
dvc init

git commit -m init

dvc run -o dir 'mkdir dir && echo foo > dir/foo'
dvc run -c dir -o ../bar 'echo bar > ../bar'

dvc status
```
there is no bar.dvc in the last `dvc status`, because dvc doesn't see it, since it skips scanning output directories of other stages. So if you would to run `dvc repro dir.dvc`, it would wipe out `dir`, destroying `bar.dvc`. So we need to prevent this in the first place, by not allowing to place .dvc files in directories that are already specified as outputs in other stages.
