### ISSUE TITLE
SSH: authentication with password/passphrase

### ISSUE THREAD

**Issue by gcoter** [iterative/dvc#1124]
Hello,

If I try to connect to an SSH remote without a private key file, it fails with this message:

```
Error: Failed to push data to the cloud: No authentication methods available
```

Also note that it will try the default key (.ssh/id_rsa) if you have one.

If I try to connect with an encrypted key file (i.e. with a passphrase), it fails with this message:

```
Error: Failed to push data to the cloud: Private key file is encrypted
```

I think the reason is that no password is given to `ssh.connect` [there](https://github.com/iterative/dvc/blob/0.18.15/dvc/remote/ssh.py#L83). I wanted to submit a pull request to solve this but I have troubles with `dvc pull` (which opens several threads, each one with a separate connection apparently). So my fix is not fully functional...

Do you have ideas?

For information, I use DVC 0.18.15 on Windows, installed with pip.

**Comment by efiop** [comment]
Hi @gcoter !

You are correct, those errors are indeed caused by dvc not asking and not passing password/passphrase to connect(). Would you be okay with storing your password/phrase in .dvc/config or .dvc/config.local(not tracked by git) or would you like to manually enter them every time? Or both?

Thanks,
Ruslan

**Comment by efiop** [comment]
Hi @gcoter !

0.19.0 is out. Please feel free to upgrade.

**Comment by gcoter** [comment]
Hi @efiop !

The password authentication is working now, thank you!

However, I noticed that if I run `dvc pull` with `--jobs` greater than 1, it will ask the password several times. To avoid that, I have to run `dvc pull --jobs 1`.

**Comment by efiop** [comment]
Hi @gcoter !

Hm, strange. Looks like I've overlooked something. Created https://github.com/iterative/dvc/issues/1151 to track the progress on the issue. Will probably release in 0.19.2 soon.

Thanks,
Ruslan

**Comment by efiop** [comment]
Hi @gcoter !

I've forgot to check that pull indeed establishes a single connection before creating threads. Now that issue is fixed. I will release it with 0.19.3 later today. Thanks again for all the feedback!

-Ruslan
