### ISSUE TITLE
DVC must not ask for List Access on s3 buckets

### ISSUE THREAD

**Issue by appunni-dishq** [iterative/dvc#1127]
Being a version control, dvc already has all details about files it has to track and add, it must only do head requests with the files available in the local repository to check whether remote repo is up to date. Using List Access Opens up a security issue when access to files is restricted by restricting listing of files but put and read are available.

**Comment by appunni-dishq** [comment]
# NOTE: We mostly use exists() method when filtering a bulk of cache
        # files to decide if we need to download/upload them and in s3
        # list_objects_v2() is much-much faster than trying to check keys
        # one-by-one.

Can we do an alternate of check keys one-by-one if list_objects_v2 access is not given

**Comment by efiop** [comment]
Hi @appunni-dishq !

I think we could check somehow if we have List Access and if we dont - check keys one by one. Or maybe we could have a config option to choose the behavior. I will take a look at it shortly.

Thank you for the feedback!

-Ruslan

**Comment by mroutis** [comment]
Hi, @appunni-dishq, I was about to work on this issue but I'm not sure if my understanding is correct; why would using `ListAccess` would be a security concern, besides knowing the filenames on your bucket?

You can restrict the `GetObject`, `PutObject`, and `DeleteObject` to just allow the operations inside the dvc cache directory.

I think that using just a HEAD request to verify the existence of a file is a good enough solution, although slow.

Currently, I can't dimension the severity of this issue to triage it, what do you think about it @efiop ?

**Comment by appunni-dishq** [comment]
Multiple repositories depending on same bucket would cause issue. It's a
real use case we want. we would like to restrict access to data based on
access to repository.

**Comment by efiop** [comment]
@appunni-dishq are we talking about multiple dvc repositories depending on the same remote in the same bucket, right? If so, why would ability to list checksums be a threat? Or are we talking about dvc remote sharing a bucket with other data(unrelated to dvc) for which listing paths/names would be unwanted?

**Comment by appunni-dishq** [comment]
Case 1. Are these files encrypted? I do not know exact implementation but I
am guessing since they can list they can download those files thus access
to that data.

**Comment by efiop** [comment]
@appunni-dishq List Access doesn't mean Read Access though, so if you can list, it doesn't mean that you can download the data.

**Comment by appunni-dishq** [comment]
@efiop without Read Access how can another IAM user use the bucket as DVC. My use case is simple. I have multiple datascientists working in different teams on different projects. Central source of data store is a bucket, it's very difficult to add new permission everytime some one needs access. So inorder to do access control we gave the same bucket as the repo for all projects. Giving everyone just read access but not list access. Now DVC knows which files are for which projects. So having access to project should only give access to data. But since now everyone has list access they can download all files.  Without list access they can only download files which are known to DVC for a particular project they have access to.

**Comment by efiop** [comment]
Makes sense to me. I need to note that without ListAccess, you will not be able to use our garbage collector on your remote, but considering that you are using single remote for multiple projects, you are not using gc anyway :) But if you'd like to use it in the future, notice that `dvc gc` will need to have all the projects that use that remote in order to properly collect all the used cache files(see `dvc gc -p`). Please let me know if not being able to use gc is not a deal breaker for you, so could add implementing support for NoListAccess to my queue.

Thanks,
Ruslan

**Comment by appunni-dishq** [comment]
It is not a deal breaker, as the gc should only be allowed to be done from an admin account which has delete access it makes more sense too.

Thanks,
Appunni

**Comment by efiop** [comment]
@appunni-dishq That is a great point! Will send a patch shortly. Thank you for all the feedback! 🙂

**Comment by efiop** [comment]
Unfortunately no capacity to work on this and not enough demand for this change. Closing for now.
