### ISSUE TITLE
Easier tracking with git by outputing a `git add` command after `dvc run`

### ISSUE THREAD

**Issue by sotte** [iterative/dvc#1130]
Just an idea. I wish dvc would (1) show me what files it created/changed and (2) make it easier to track those files with git. Maybe something like this:
```
➤ dvc run -d infile -o outfile cp infile outfile
Running command:
        cp infile outfile
Saving 'outfile' to cache '.dvc/cache'.
Created 'hardlink': .dvc/cache/87/27026644df14a9006d71b59a6317ae -> outfile
Saving information to 'outfile.dvc'.

To track the changes with git run:

    git add outfile.dvc .gitignore
```
In this example it's pretty obvious what to track, but if you have output files deeper in the folder hierarchy it can be tedious to add these files.

This feature could be useful for `dvc add` and `dvc repro` as well.

**Comment by sotte** [comment]
You folks are amazing!

**Comment by sotte** [comment]
...and fast! Thanks!

**Comment by sotte** [comment]
I just tested the master and it works like a charm.

Does it make sense to also include the `.gitignore` file and not just the `*.dvc`s? What do you think?

**Comment by sotte** [comment]
Sorry, you're right. The .gitignore file already contained the change.

**Comment by efiop** [comment]
Hi @sotte !

FYI: 0.19 is out. Please feel free to upgrade.
