### ISSUE TITLE
Support tags for push/pull/gc

### ISSUE THREAD

**Issue by gcoter** [iterative/dvc#1150]
Hello,

It seems that DVC was designed to work mainly with branches, however I sometimes prefer using tags.

Usually, I use branches to separate the different models/preprocessings I use. But in the context of Kaggle competitions for instance, I like to make a tag each time I make a submission. I find tags really suited to submissions since I can make several submissions with the same model (Random Forest for instance).

If I work only locally, I can checkout the tags and everything works well. But, if I want to push the DVC cache to a remote, I can only push files which are used by the branches, not the tags. And if I run `dvc gc`, I am afraid that it deletes the files used by the tags since it seems to look only at the branches.

That's why I was wondering whether DVC could have an `--all-tags` option the same way it has a `--all-branches` option. What do you think?

**Comment by efiop** [comment]
Hi @gcoter !

Great suggestion as always! I think we could definitely  add `--all-tags` option similar to already existing `--all-branches`. I will look into it shortly.

Thanks,
Ruslan

**Comment by j-hartshorn** [comment]
I second this as a new feature. I only work locally at the moment, and it would be good to be able to use gc to free up some space while saving tagged milestones which do not necessarily have a branch on them anymore.

**Comment by efiop** [comment]
Hi @j-hartshorn !

Thank you for the feedback! We will be sure to include this feature into the next release(probably 0.19.4) very soon.

**Comment by j-hartshorn** [comment]
@efiop That's great, thanks! You're doing a great job with this project, it's incredibly useful.

If we could, it would be even better to have a way to enable this behaviour by default in the configuration, so that i don't accidentally type `dvc gc` and loose some tag data - a danger when working exclusively locally.

**Comment by efiop** [comment]
@j-hartshorn I agree, current gc implementation is rather dangerous. I don't think that we even have a confirmation prompt or anything there right now. Created https://github.com/iterative/dvc/issues/1169 to track the progress on that issue. I will look into it very soon. Thanks again for all the helpful feedback!
