### ISSUE TITLE
WebDav: new remote type

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#1153]
WebDav is a quite common protocol for file sharing.

It is especially convenient because box.com provides 10Gb free and supports WebDav.

**Comment by dmpetrov** [comment]
@jurasan, in `dvc/remote/` directory you can find code examples for S3, Azure and other remotes. WebDav should be just another remote for DVC.

**Comment by jurasan** [comment]
Which branch should I work on?

**Comment by efiop** [comment]
@jurasan On master. Work on your dvc fork and send a PR when you are ready. Also please feel free to ping us if you need anything.

**Comment by mroutis** [comment]
@jurasan, in addition to @efiop response, we have a contributing guide that may help you with your PR: https://dvc.org/doc/user-guide/contributing/

**Comment by jurasan** [comment]
box.com drop support for WebDav
https://community.box.com/t5/Box-Product-News/Deprecation-WebDAV-Support/ba-p/55684

**Comment by jurasan** [comment]
I'm now looking for a good python webdav library supporting python 2.7.
I found this one, though it's not maintained for the last 2 years. 
[https://github.com/CloudPolis/webdav-client-python](https://github.com/CloudPolis/webdav-client-python)

Does anyone have experience with this or can hint any other library.

**Comment by efiop** [comment]
@jurasan I agree. Do you plan on using webdav driver yourself(if so, with which storage provider?), or are you working on a patch for fun?

**Comment by jurasan** [comment]
We have our internal company cloud that uses WebDav

**Comment by efiop** [comment]
Ah, I see. Please don't hesitate to ping us if you need any help.

**Comment by garylschultz** [comment]
This is still of interest, as I've got a project that is pushing to use Citrix ShareFile, which supports WebDav. Is WebDav support still actively being worked on?

**Comment by efiop** [comment]
@garylschultz Our core team is not working on this (at least yet). But @jurasan seems to have been working on his patch, I'm not sure what state it is in though :slightly_frowning_face: @jurasan Maybe you need some help? Also, maybe @garylschultz will be willing to help out too :slightly_smiling_face:

**Comment by gw0** [comment]
WebDAV support would also enable the use of private file-hosting solutions, like Nextcloud, Owncloud, and others.

**Comment by shizacat** [comment]
Hi,
I try to create the remote - webdav and saw interesting thing. She different from remote http only one string - upload need method [PUT](https://github.com/iterative/dvc/blob/master/dvc/remote/http.py#L91)

Example in [PR](https://github.com/iterative/dvc/pull/3647)

But that need change base - schema change to http.
