### ISSUE TITLE
s3: Support AWS credential settings from environment variables

### ISSUE THREAD

**Issue by jeepkd** [iterative/dvc#1160]
dvc should also load credential information from system environment variables as awscli does.

Reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html

For example: we should be able to run `dvc pull` despite absence of AWS profiles in _~/.aws_ if we had set the following environment variables:

```
$ export AWS_ACCESS_KEY_ID=somekey
$ export AWS_SECRET_ACCESS_KEY=somekey
$ export AWS_DEFAULT_REGION=someregion
```

The following command works:
``` 
aws s3 ls s3://bucketname
```

But this one does not:
```
dvc pull
```

A usecase for this is doing `dvc pull` in docker image building process, which would be much easier if if we can override configuration via environment variables.

**Comment by efiop** [comment]
Hi @jeepkd !

Good point! I was sure that we support this already since this is how we pass creds in our travis tests, but turns out we write it to `.aws/` first. Will send a patch soon.

Thanks,
Ruslan

**Comment by efiop** [comment]
Hi @jeepkd !

FYI: 0.19.5 with a patch for this is out.

Thanks,
Ruslan

**Comment by jeepkd** [comment]
The issue still exists. Not sure if I can re-open this issue? 
PS. I will have a pull request for this one

**Comment by efiop** [comment]
Re-opened. Are there any specific env not supported?

**Comment by jeepkd** [comment]
I still get an on the 3 envs discussed above

```
$ export AWS_ACCESS_KEY_ID=somekey
$ export AWS_SECRET_ACCESS_KEY=somekey
$ export AWS_DEFAULT_REGION=someregion
$ dvc pull
Preparing to pull data from s3://[myrepo]
[##################            ] 60% Collecting informationError: Failed to pull data from the cloud: Unable to locate credentials
```

**Comment by jeepkd** [comment]
A fix is WIP 
https://github.com/jeepkd/dvc/tree/fix/aws-env
But I have to go outside for now. Will be back soon ;)
