### ISSUE TITLE
Failed to push data to the cloud: SSH session not active

### ISSUE THREAD

**Issue by yukw777** [iterative/dvc#1163]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))
I installed dvc using homebrew
```bash
$ dvc --version
0.19.2
```
When I push data up using an ssh remote, I get the following error:
`Failed to push data to the cloud: SSH session not active`

I believe this might be related to setting server keepalive. I'm not too sure though b/c supposedly dvc was sending data through ssh.

https://docs.paramiko.org/en/stable/api/transport.html#paramiko.transport.Transport.set_keepalive

**Comment by efiop** [comment]
Hi @yukw777 !

I think it is caused by too much concurrency that your server can't handle. Could you please try specifying `--jobs 4` flag to see if that will work?

Thanks,
Ruslan

**Comment by yukw777** [comment]
Ah, that's probably what it is. I was just pushing to my desktop from my laptop. I kept rerunning the push and it eventually worked. I'll close it!

**Comment by efiop** [comment]
Hi @yukw777 !

Glad it worked! This is not the first time we see such things and it is definitely time to do maybe introduce different defaults for different remote types. Created https://github.com/iterative/dvc/issues/1167 to track the progress on that.

Thank you for the feedback!

-Ruslan
