### ISSUE TITLE
Error: Failed to push data to the cloud: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by shaunirwin** [iterative/dvc#1178]
Hi,

I am trying to push to an SSH remote on my local network (_dvc push_) and receive the following error:

> Exception: Error reading SSH protocol banner
> Traceback (most recent call last):
>   File "/home/deepblue/miniconda3/lib/python3.6/site-packages/paramiko/transport.py", line 2138, in _check_banner
>     buf = self.packetizer.readline(timeout)
>   File "/home/deepblue/miniconda3/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
>     buf += self._read_timeout(timeout)
>   File "/home/deepblue/miniconda3/lib/python3.6/site-packages/paramiko/packet.py", line 563, in _read_timeout
>     raise EOFError()
> EOFError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/deepblue/miniconda3/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
>     self._check_banner()
>   File "/home/deepblue/miniconda3/lib/python3.6/site-packages/paramiko/transport.py", line 2143, in _check_banner
>     "Error reading SSH protocol banner" + str(e)
> paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
> 
> Exception: Error reading SSH protocol banner
> Traceback (most recent call last):
>   File "/home/deepblue/miniconda3/lib/python3.6/site-packages/paramiko/transport.py", line 2138, in _check_banner
>     buf = self.packetizer.readline(timeout)
>   File "/home/deepblue/miniconda3/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
>     buf += self._read_timeout(timeout)
>   File "/home/deepblue/miniconda3/lib/python3.6/site-packages/paramiko/packet.py", line 563, in _read_timeout
>     raise EOFError()
> EOFError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/deepblue/miniconda3/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
>     self._check_banner()
>   File "/home/deepblue/miniconda3/lib/python3.6/site-packages/paramiko/transport.py", line 2143, in _check_banner
>     "Error reading SSH protocol banner" + str(e)
> paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
> 

My DVC config:

['remote "myremote"']
url = /tmp/dvc-storage
[core]
remote = ubuntu
['remote "ubuntu"']
url = ssh://ubuntu@ubuntu:/tmp/dvc_datasets_store

It seems that Paramiko is hitting some sort of SSH request limit on the server (https://stackoverflow.com/a/29225295), at least from what I can gather. I am able to push the data after several _dvc push_ attempts, as each time some data is pushed before this error is shown. As such, I assume that this is not a bug with DVC itself. However, is there a way to prevent this issue by configuring the SSH server appropriately? Otherwise, is it possible to introduce a delay to prevent hitting the limit?

Apologies if this issue should rather be raised in Paramiko or elsewhere.

**My setup:**

DVC version: 0.19.5
Platform: Ubuntu (both the local machine and the remote)
Method of installation pip

**Comment by efiop** [comment]
Hi @shaunirwin !

This is indeed a concurrency limit you are hitting. This is a known issue, which could be worked around by setting `--jobs` parameter to a smaller than default value. For example, something like `dvc push -j 4` should work. I am currently preparing a patch https://github.com/iterative/dvc/issues/1167 that will allow us to set different default number of jobs for different remote types(e.g. for SSH we'll set something like 4 or 8). The patch should be ready soon and is going to be released in 0.19.6 until tomorrow.

Thank you so much for the feedback!

-Ruslan

**Comment by shaunirwin** [comment]
Thanks so much @efiop !

Ah, I see. I tested `dvc push -j 4` and it has completed without showing the error. Thanks very much for the swift response!

**Comment by efiop** [comment]
Hi @shaunirwin !

FYI: 0.19.6 is out, please consider upgrading. I've set 4 as a default number of jobs for SSH remote driver, so it should now work properly out of the box :slightly_smiling_face:

Thanks,
Ruslan

**Comment by Sunny-Day200** [comment]
$ dvc push left
Unknown exception: q must be exactly 160, 224, or 256 bits long
Traceback (most recent call last):
  File "site-packages\paramiko\transport.py", line 2109, in run
  File "site-packages\paramiko\auth_handler.py", line 298, in _parse_service_accept
  File "site-packages\paramiko\dsskey.py", line 116, in sign_ssh_data
  File "site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 243, in private_key
  File "site-packages\cryptography\hazmat\backends\openssl\backend.py", line 657, in load_dsa_private_numbers
  File "site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 142, in _check_dsa_private_numbers
  File "site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 134, in _check_dsa_parameters
ValueError: q must be exactly 160, 224, or 256 bits long

ERROR: unexpected error - q must be exactly 160, 224, or 256 bits long

**Comment by Sunny-Day200** [comment]
I'm sorry I can't understand the mistake

**Comment by efiop** [comment]
@Sunny-Day200 Probably something is unusual about your keys, similar to https://github.com/paramiko/paramiko/issues/750 . Can't put my finger on anything specific. If it is your work laptop, try contacting your sysadmin.
