### ISSUE TITLE
remote: support NFS

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1183]
Currently we do not support NFS remotes natively, but it is pretty easy to workaround that by mounting nfs location to some local directory/folder and specifying it as a local remote in dvc. For example, if you have your nfs location mounted to `/mnt/nfsshare`(or something like `Z:\\` on Windows), then you can simply use `dvc remote add -d /mnt/nfsshare`(or `dvc remote add -d `Z:\\` on Windows) to add it as a remote.

That being said, it would still be very useful to have a native support for it.

**Comment by mroutis** [comment]
How are you imaging the interface, @efiop ? (ie. `dvc remote add ...`)
The "workaround", seems like a straight forward solution to me

**Comment by efiop** [comment]
Hi @mroutis !

Should be similar to what we have with other remotes. E.g. `dvc remote add nfs://127.0.0.1/` or something like that. I agree that workaround works pretty well as is, but it should be pretty handy to have it working without manually mounting anything :) I am still hoping to see if there is an interest in this from the users, since we've only received a single question about nfs and the workaround was a suitable option in that particular case :)

Thanks,
Ruslan

**Comment by CMCDragonkai** [comment]
I'd be interested in this as well since we use NFS/EFS as a "cloud-based filesystem" (real posix filesystem) for high performance reads and writes for our ML system.

**Comment by efiop** [comment]
Doesn't look like this has enough interest for us to prioritize this. Considering that there is a good workaround with mounting your nfs to a local directory, I'll close this issue until there is more interest or there is someone who wants to implement this by himself.
