### ISSUE TITLE
init: mention that we have chat

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1184]

**Comment by shcheklein** [comment]
Let's also put something like `what's next` - check get started, `dvc add` to start tracking models or data sets, `dvc run` to create your first stage

**Comment by shcheklein** [comment]
Looks great, @mroutis !

I would simplify it a little bit. Remove `Start tracking ....` - it does not provide much value and covers only a specific niche - models. I would also change the chat copy:

`Join our community chat to get help and share ideas`

**Comment by mroutis** [comment]
Indeed, @shcheklein , I wasn't sure about that green part either:

![2018-11-19-22 31 24](https://user-images.githubusercontent.com/7363250/48751624-037c9a00-ec4b-11e8-8c31-f13840bfa4d0.png)

Final cut?

**Comment by shcheklein** [comment]
Yep, looks good to me! 👍
