### ISSUE TITLE
ssh: paramiko: not a valid RSA or private key file

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1187]

**Comment by mroutis** [comment]
Could you give more context or info about how to reproduce the bug, @efiop?

**Comment by efiop** [comment]
The context is that it seems like ssh remote with url and port configured raises an error on 0.19.7:

![image](https://user-images.githubusercontent.com/5367102/46510250-71fac980-c850-11e8-9dd4-e2756f30e77a.png)

![image](https://user-images.githubusercontent.com/5367102/46510305-d74eba80-c850-11e8-8c4d-c8bf2770507c.png)


and that error reportedly doesn't raise on 0.18.7. This bug was reported by a user today, but I am not able to reproduce it yet.

**Comment by mroutis** [comment]
mhm, I looked at `remote/ssh.py` and there's no usage of `SSHConfig`; maybe, the user was expecting some configuration to be pulled over the `.ssh/config` file (like keys).

maybe with something like:
```python
config = paramiko.SSHConfig()

with open('~/.ssh/config') as ssh_config_file:
    config.parse(ssh_config_file)
    config.lookup('hostname')
```

However, I don't know if this is intentional, but it would be a cool feature; also, taking into account that you commit the `.dvc/config` file, I don't think it is a good idea to put a `SSH` password there.

**Comment by efiop** [comment]
The main point here is that the problem seemingly disappeared when user downgraded to 0.18.7, which is strange, since there were no changes affecting his simple url + port configuration since then. So I don't think that it is related to .ssh/config, since it would've affected 0.18.7 as well.


> so, taking into account that you commit the .dvc/config file, I don't think it is a good idea to put a SSH password there.

We also have .dvc/config.local which is not tracked by git and stays private, so it is suitable for storing ssh keys if user wants to do it. We also have an ask_password option in the config, that will make dvc ask for a password before connecting to the remote.

**Comment by efiop** [comment]
Btw, great point about the `.ssh/config`! I was convinced that AutoPolicy accounts for it, but looking at it right now it seems like it doesn't :(

**Comment by efiop** [comment]
Ok, asked user once again and it turns out that 0.18.7 no longer works as well :) Btw, there is no `.ssh/config` this time, so we are pretty safe there :) One suspicions thing is that id_rsa has a `-----BEGIN OPENSSH PRIVATE KEY-----`, which makes me think that there might be something wrong with the paramiko not able to parse it properly. Looking into it right now.

**Comment by efiop** [comment]
@mroutis Great point! I actually have some updates on this issue. Turns out the key is not an rsa key, but placed in the id_rsa file for some reason. I tried mixing that and dvc was still connecting without any problem. User re-generated keys on some older machine(they are using ubuntu 16.04 and debian 9) and got a proper RSA key, which made everything work again. Regardless, this issue makes me wonder if we should stop using paramiko in favor of ssh CLI command wrapper or rsync CLI command wrapper. The main reason for doing that is that we would at least be shielded from paramiko bugs and ssh ones will be easily reproducible by just asking user to run `ssh example.com` and seeing if that works.

**Comment by efiop** [comment]
On the other hand, updating paramiko(or fabric) is easier than updating a usually system-wide commands such as ssh or rsync, which might be a problem on some legacy systems. That being said, we are a cutting edge project, so that should not be a problem.

**Comment by shcheklein** [comment]
Can we reproduce it after all? I would ask first paramiko to fix it. I would try to avoid depending on system environment (ssh command) that is outside DVC - it's might be even less predictable at the end.

**Comment by efiop** [comment]
@shcheklein I was not able to reproduce it yet. This is not the first issue where ssh command by itself is more accepting of file format than the paramiko itself(i.e. https://github.com/paramiko/paramiko/issues/1226, https://github.com/paramiko/paramiko/issues/1015) and I'm thinking if we could eliminate such problems altogether and have a better method of reproducing even potential issues by just switching to a much more used and reliable CLI commands. It doesn't get less predictable than python modules :) especially when you consider that we would use pretty basic functions of ssh or rsync, which have been stable for years. I haven't decided yet on which one I prefer the most, but these are the options that are worth considering.

**Comment by mroutis** [comment]
Relying on the system environment / userland is delegating the responsibility to the user; that way, DVC can handle a more "Unix" approach to remotes, something like:
```bash
dvc config.remote.command "rsync --archive --verbose --compress --progress --rsh 'ssh -i ~/ssh/aws.pem' .dvc/cache myhost:/tmp/dvc/cache"
```
or:
```bash
dvc config.remote.command "aws s3 cp .dvc/cache s3://dvc-bucket/cache"
```

allowing them to use `dvc push` as an alias to upload the dvc's caché.

I guess that decision depends a lot on the interface you want to maintain and how friendly you want it.

In my opinion, supporting native uploading to s3, azure, gcp, etc. is a great help for non-so-techy users that just want to collaborate with others, even if that implies taking care of some dependencies issues

**Comment by mroutis** [comment]
@efiop, can we close this one?

**Comment by efiop** [comment]
@mroutis Let's leave it open for now. I'll try to come back to this soon.

**Comment by kuzeyron** [comment]
> Ok, asked user once again and it turns out that 0.18.7 no longer works as well :) Btw, there is no `.ssh/config` this time, so we are pretty safe there :) One suspicions thing is that id_rsa has a `-----BEGIN OPENSSH PRIVATE KEY-----`, which makes me think that there might be something wrong with the paramiko not able to parse it properly. Looking into it right now.

I'm getting this BEGIN-OPENSSH part on Manjaro. I haven't found a solution for this. Most sites are telling me to use puttygen to convert it. But I cannot find the right method for this.

**Comment by efiop** [comment]
Hi @kuzeyron !

Tried to use ed25519 key again and it seems to work for me just fine. Could you please show your paramiko version? I.e. `pip freeze | grep paramiko` if you've installed dvc with pip.

Thanks,
Ruslan

**Comment by efiop** [comment]
@kuzeyron I am using 2.4.2 as well. ed25519 is not a commit, it is a type of key that produces `-----BEGIN OPENSSH PRIVATE KEY-----` header 🙂 . Are you getting the same `not a valid rsa` error that is shown in the logs above? Could you confirm that that key works when you use plain `ssh` command?

**Comment by kuzeyron** [comment]
@efiop I'm using the same key for connecting to other devices on my network.
I tried the `ed25519` by using: `ssh-keygen -t ed25519`
I have tried verifying with: `ssh-keygen -l -f ~/.ssh/id_ed25519` and it's a success.
Beginning of the output: `256 SHA256`

And within my Python code I tried using: `paramiko.ed25519key.Ed25519Key(filename=self.filename)`
And I've used this before the change from Linux Mint to Manjaro: `paramiko.RSAKey(filename=self.filename)`
Taken from the [documentation](http://docs.paramiko.org/en/2.4/api/keys.html#module-paramiko.ed25519key)

But no success. What Am I missing?

**Comment by efiop** [comment]
@kuzeyron Just to be clear, are you using dvc at all? :slightly_smiling_face: Or is it a question about paramiko in your project? If it is, it would be more appropriate to ask it in paramiko's issues, especially since you are able to reproduce it(unlike me) and it would be beneficial for everyone.

**Comment by kuzeyron** [comment]
Woops! Google pointed me to this page. Forgot to check the url. I read the posts instead. My bad!
I'll move this to Paramiko's page!

**Comment by efiop** [comment]
@kuzeyron No worries :slightly_smiling_face: It would be amazing if you could post a link to your issue here, so we could follow it :slightly_smiling_face:

**Comment by kuzeyron** [comment]
Sure I will do that :)

**Comment by kuzeyron** [comment]
One hack I just tried that will do for now is to use `openssl req -new -x509 -days 365 -nodes -out cert.pem -keyout cert.pem
`
Remove section `BEGIN CERTIFICATE`
And rename first line to `BEGIN RSA PRIVATE KEY`

**Comment by efiop** [comment]
For the record: This is a paramiko-specific issue discussed at https://github.com/paramiko/paramiko/issues/1015 Closing.

**Comment by nickconIO** [comment]
Had this error message as well.

How was the key generated?

If done without specifying the output as a PEM file, Paramiko can raise issues. More info here:
[https://github.com/paramiko/paramiko/issues/1313](url)

Hope this helps!

**Comment by SharkFourSix** [comment]
> Had this error message as well.
> 
> How was the key generated?
> 
> If done using ssh-keygen without specifying the output as a PEM file, Paramiko can raise issues. More info here:
> [https://github.com/paramiko/paramiko/issues/1313](url)
> 
> Hope this helps!

Link is dead. Sad that I'm still getting the same error on Fabric 2

**Comment by efiop** [comment]
@SharkFourSix Try https://github.com/paramiko/paramiko/issues/1313

**Comment by SharkFourSix** [comment]
> @SharkFourSix Try [paramiko/paramiko#1313](https://github.com/paramiko/paramiko/issues/1313)

I tried `-m PEM` switch but still not working.

SSH Client :  OpenSSH_7.4p1, OpenSSL 1.0.2j  26 Sep 2016
SSH Server: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

This sucks

**Comment by shcheklein** [comment]
@SharkFourSix could you please share the full DVC output when you run it with `-v` option? Also, how exactly do you run the ssh-keygen? could you share the commands please? All the information to reproduce this exactly would be useful - like your OS, dvc version, etc. Thanks!
