### ISSUE TITLE
dvc run doesn't handle quotes in the command correctly.

### ISSUE THREAD

**Issue by yukw777** [iterative/dvc#1196]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))
```
$ dvc --version
0.19.2
```
Installed using DEB.

If I wrap a string in my command with (double/single) quotes to escape some characters or utilize multiline strings, dvc would strip away the quotes, and the command will fail as a result.

**Comment by yukw777** [comment]
```
$ dvc run echo 'wow
> really?
> yeah.
> '
Running command:
	echo wow
really?
yeah.

wow
/bin/bash: line 1: really?: command not found
/bin/bash: line 2: yeah.: command not found
Error: Failed to run command: Stage 'Dvcfile' cmd echo wow
really?
yeah.
 failed
```

**Comment by efiop** [comment]
Hi @yukw777 !

The issue here is that quotes are being stripped by shell itself, since `dvc run` acts as a wrapper, you need to shield your command a bit more, so that the command itself gets to dvc run untouched by the shell. E.g.:

```
$ dvc run 'echo "wow
> really?
> yeah.
> "'
```

or


```
$ dvc run "echo 'wow
> really?
> yeah.
> '"
```

Thanks,
Ruslan

**Comment by yukw777** [comment]
huh, i thought i tried that. I'll close it. Thanks a lot for the speedy response!
