### ISSUE TITLE
Error: Unexpected error: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

### ISSUE THREAD

**Issue by amjadsaadeh** [iterative/dvc#1197]
**Setup information**
DVC version: 0.19.7, Platform: Windows 10  Pro (Version 1709), method of installation: pip (global), Python 3.6.6

Hello,
I would like to upload a directory with image data to hdfs and log this step in my DVC pipline. Therefore, I ran:

```
dvc run -d .\data\phaco_segmentation\ -o hdfs://<hostname>/data/phaco_segmentation/ hdfs dfs -put ./data/phaco_segmentation /data/
```

in powershell. Output gives me following output:
```
Running command:
        hdfs dfs -put ./data/phaco_segmentation /ignition_data/
Error: Unexpected error: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
```

Running `hdfs dfs -put` runs without any problems. May the [this flag](https://github.com/iterative/dvc/blob/ddf1839d38a507e0e2fbae0036469dfb6d2a3f36/dvc/remote/hdfs.py#L34) the possible cause of this?

**Comment by efiop** [comment]
Hi @amjadsaadeh !

Good catch! Thank you for investigating! Preparing a patch right now.

Thanks,
Ruslan

**Comment by efiop** [comment]
Hi @amjadsaadeh !

I'm releasing 0.19.8 right now and preparing our infrastructure to test hdfs on windows(we do test on linux though), which will take a little bit of time. Could you please try out 0.19.8 to see if it works for you while I'm setting up our windows tests? I will notify you when 0.19.8 is ready. ETA is 1 hour.

Btw, how about we schedule a video call some time this week? We would really like to ask you a couple of questions about the way you use DVC. Would you be up for that?

Thanks,
Ruslan

**Comment by efiop** [comment]
0.19.8 is out. Please feel free to upgrade.
