### ISSUE TITLE
Error: Unexpected error: cannot import name 'POINTER'

### ISSUE THREAD

**Issue by amjadsaadeh** [iterative/dvc#1215]
DVC version: 0.19.10+c6811a, Platform: Windows 10 Pro (Version 1709), method of installation: pip (global), Python 3.6.6

Hello,
I run the following command:

```
dvc run -d .\data\phaco_segmentation\ -o hdfs://<hostname>/data/phaco_segmentation/ hdfs dfs -put ./data/phaco_segmentation /data/
```
in powershell and get the following error message:

```
Error: Unexpected error: cannot import name 'POINTER'
```

I already got at fix for this problem. Pull request is incoming.

**Comment by efiop** [comment]
Thank you!

**Comment by efiop** [comment]
0.19.11 will be ready in an hour or so. I'll let you know.
