### ISSUE TITLE
Use progress bar to show a process of linking many files in a directory

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1222]
E.g. currently for a directory with 1M files, there will be 1M lines printed with message that says something like "Created 'hardlink' ...". Need to use progress bar to show that in a more compact way.

**Comment by mroutis** [comment]
Adding extra steps to replicate the issue:

```bash
#!/usr/bin/env bash

rm -rf repo
mkdir repo
cd repo
git init
dvc init
git add -A
git commit -m "Initial commit with DVC"

# Create data dir with 1000 files
mkdir data

# for file in {1..1000}; do echo $file > data/$file.txt; done
parallel 'echo {} > data/{}.txt' ::: {1..1000}

# Add the data directory and see a 1000 "Created 'hardlink'..."
dvc add data
```

@efiop, should the progress bar appear after a certain threshold (let's say 30)?

I think this is not that bad, maybe the user would like to `--quiet` the output instead of seeing a progress bar; also, when using `--quiet` the progress bar for:
```
Computing md5 for a large directory data. This is only done once.
[##############################] 100% data
```
Still appears.

**Comment by efiop** [comment]
@mroutis I think we should have a "Linking directory 'mydir'" message always, but print the progress bar when it is a large directory. E.g. we have LARGE_DIR_SIZE defined right now(https://github.com/iterative/dvc/blob/master/dvc/utils.py#L19) for deciding if we would show progress bar when computing md5 of some directory. I think that number is somewhat reasonable :slightly_smiling_face: 

Yes, progress bar should not appear in `-q` mode. We have a bug with that right now :(
