### ISSUE TITLE
Add gc support for azure

### ISSUE THREAD

**Issue by tdeboissiere** [iterative/dvc#1232]
python 3.6 install, dvc 0.19.12

After pushing to Azure successfully, I ran

```
dvc remove File.dvc --purge
dvc gc -c -r {remote_name}
```

And got:

```
Error: Unexpected error: 'RemoteAzure' object has no attribute 'gc'
```

So I guess gc support is not available for Azure right now. Any plans to do this in the future ?

**Comment by efiop** [comment]
Hi @tdeboissiere !

Indeed, gc for azure has been disabled temporarily. I'll prepare a patch for this until tomorrow.

Thanks,
Ruslan
