### ISSUE TITLE
Adding new file to new experiment strategy

### ISSUE THREAD

**Issue by AratorField** [iterative/dvc#1233]
I run many experiments with one task. Every experiment has its own branch. In one experiment I have added additional CSV file.
As normally I added it by `dvc add` command which put it to a .gitignore and creates a `.csv.dvc` file, then I committed these changes. But when I changed branch I realized that the CSV file appears in `git status`.
So I have to add it to the .gitignore in every branch which is uncomfortable.

I solved this problem by writing the `.gitignore` file on the `master` in such a way that `git` ignores all files in `data` directory except `.dvc` files.

Is there any feature to omit such problems or do you have plans to add it?

**Comment by efiop** [comment]
Hi @AratorField !

Do you `dvc checkout` after `git checkout`? If not, would it be suitable for your scenario? Our `dvc checkout` command would automatically remove all the links from the previous branch before checking out. We also have a `dvc install` feature, that will create a post-checkout git hook, that will automatically call `dvc checkout` after you call `git checkout`.

Thanks,
ruslan

**Comment by AratorField** [comment]
It looks like `dvc install` works fine. Thanks!
