### ISSUE TITLE
run/repro: check that --cwd is inside the repository

### ISSUE THREAD

**Issue by habernal** [iterative/dvc#1253]
macOS High Sierra 10.13.6 (17G65)
```
$ python --version
Python 3.6.6
```

Reproduce MWE:

Clean installation:

```
$ virtualenv venv --python=python3.6
$ source venv/bin/activate
$ pip install dvc==0.19.13
$ git init
$ dvc init
```

Minimal example that works:

```
$ dvc run -o /tmp/input.txt `echo "Test" > /tmp/input.txt`
$ dvc run -d /tmp/input.txt -o /tmp/output.txt `wc /tmp/input.txt > /tmp/output.txt`
$ dvc repro output.txt.dvc
```

Minimal example that crashes:

```
$ dvc run --cwd /tmp -o /tmp/input.txt `echo "Test" > /tmp/input.txt`
$ dvc run --cwd /tmp -d /tmp/input.txt -o /tmp/output.txt `wc /tmp/input.txt > /tmp/output.txt`
$ dvc repro --cwd /tmp /tmp/output.txt.dvc
Error: Unexpected error: '../../../../tmp/output.txt.dvc'
```

**Comment by habernal** [comment]
@efiop Thanks for clarifying, yes, the /tmp is outside of the project directory. I believe the fastest fix is to simply document it in the reference guide.

**Comment by efiop** [comment]
Agreed. I'll update help messages along with the command refs in the docs. Thank you for the feedback!

**Comment by efiop** [comment]
Merged a patch that checks for cwd being inside the project, updated dvc run/repro help messages as well as cmd reference on dvc.org/documentation. Thanks again for the feedback!
