### ISSUE TITLE
link: make `reflink,copy` default

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1257]

**Comment by efiop** [comment]
Need to learn more about systems that dvc is currently working on first. Depends on https://github.com/iterative/dvc/issues/693 .

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/issues/1821

**Comment by efiop** [comment]
If checkout takes too long, need to print a warning saying that it is possible to use hardlinks/symlinks to speed up everything.

**Comment by shcheklein** [comment]
Please, create a ticket or update the docs.
