### ISSUE TITLE
Don't require a lock for the dvc root command

### ISSUE THREAD

**Issue by villasv** [iterative/dvc#1260]
Is there any way that the `dvc root` would change in the middle of some `dvc` command that acquired lock? If not, I think `dvc root` could simply skip acquiring a lock so it can be used freely.

**Comment by efiop** [comment]
Good point! Could you please also share how you use `dvc root` in parallel with other `dvc` commands, so we are on the same page?

**Comment by villasv** [comment]
I ran into this because I've been experimenting with self-reporting data pipelines, and that diff script I mentioned in #770 plays a role on this. At first,  it coldn't be used inside a `dvc run` because it will issue a `dvc root` as subprocess.

I've worked around that using `git rev-parse --show-toplevel`, but that only works because I assume the git root and dvc root to be the same.

**Comment by efiop** [comment]
Got it. Thank you! Patch is going to be ready for merge in ~10 minutes or so.
