### ISSUE TITLE
system: Add support for reflink in Windows when using ReFS v2

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1263]
This is a reference implementation https://github.com/0xbadfca11/reflink

**Comment by efiop** [comment]
From https://en.wikipedia.org/wiki/ReFS

> The ability to create ReFS volumes was removed in Windows 10's 2017 Fall Creators Update for all editions except Enterprise and Pro for Workstations,[4] which would seem to indicate Microsoft is no longer intending ReFS as a general replacement for NTFS, at least in the near future.

Considering this and lack of interest from users, closing this issue for now.
