### ISSUE TITLE
remote: support PCloud

### ISSUE THREAD

**Issue by nicolalandro** [iterative/dvc#1274]
It is possible to add a cloud storage as Dropbox or PCloud as remote?

**Comment by efiop** [comment]
Hi @nicolalandro !

Unfortunately we don't currently support Dropbox or PCloud 🙁If you wish to contribute a native driver for one of those, please take a look at `dvc/remote/` directory, where we have drivers for AWS s3, Google Cloud Storage, Azure, HDFS, SSH and Local Directory and don't hesitate to ping us if you need any help with that. That being said, if you absolutely need one of those to work right now, you can use something like FUSE for one of those clouds. E.g. https://github.com/joe42/CloudFusion (not tested), mount it to some local directory and specify it as a LOCAL remote(i.e. `dvc remote add myremote /path/to/mounted/fuse/dir`).

Thanks,
Ruslan

**Comment by efiop** [comment]
Created https://github.com/iterative/dvc/issues/1277 for dropbox and renamed this issue for PCloud.

**Comment by dmpetrov** [comment]
It looks like PCloud supports WebDav protocol. #1153 should cover this PCloud issue.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/1153

**Comment by allenyllee** [comment]
Hi @efiop, I bump into here because I want pCloud support. I've try Webdav, but it seems deprecated by pCloud, and it doesn't support 2FA. Finally, I find a python package here: https://github.com/tomgross/pycloud, which provide python API for pCloud. So I think I can contribute to this, but I can't find `dvc/remote/` you've mentioned above, how can I do?

**Comment by efiop** [comment]
@allenyllee Hey. These days we base all our remotes on https://github.com/fsspec/filesystem_spec, so first step is to implement fsspec filesystem for pcloud. We currently don't accept any new filesystems into dvc, but in the near future we should be supporting dvc plugins, so users can use their own implementations.

**Comment by allenyllee** [comment]
@efiop Ok, so I have to wait until the plugin system publish, right?

**Comment by efiop** [comment]
@allenyllee You can start by implementing fsspec fs for pcloud (e.g. https://github.com/fsspec/s3fs) and testing it. You can easily patch dvc to use it too (e.g. see https://github.com/iterative/dvc-objects/blob/main/src/dvc_objects/fs/implementations/s3.py), I'm just saying that we will not officially support it ourselves and official mechanism to use third-party implementations will be introduced later in a form of plugins.
