### ISSUE TITLE
Use directory as output for dvc run when using hdfs as target

### ISSUE THREAD

**Issue by amjadsaadeh** [iterative/dvc#1275]
Hello,

I would like to track directories on hdfs for my pipeline. E.g. I run:

`dvc run -d ./images -o hdfs://<hostname>:<port>/image_data hdfs dfs -put ./images /image_data`

but currently this fails because hadoop cli cannot calculate the checksum of a directory.

**Comment by efiop** [comment]
Duplicate of https://github.com/iterative/dvc/issues/1083 .

**Comment by mroutis** [comment]
@efiop, why did you reopened the issue? Was it a mistake?

**Comment by efiop** [comment]
Moving to https://github.com/iterative/dvc/issues/1654
