### ISSUE TITLE
remote: support Dropbox

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1277]

**Comment by efiop** [comment]
Closing for the lack of interest.

**Comment by jmunox** [comment]
Hi, is there a plan to support Dropbox? If not, how can I contribute to make it happen?

**Comment by efiop** [comment]
@jmunox No current plans to support it, unfortunately :( To implement the support, one would need to create a class implementing a basic set of methods, similar to https://github.com/iterative/dvc/blob/5e69e29b2f0e3df9b9eab5d682988fd01121b015/dvc/tree/azure.py#L18 . E.g. here is an example of adding support or webdav https://github.com/iterative/dvc/pull/4256 . Let us know if you'll have any questions :slightly_smiling_face:

**Comment by jmunox** [comment]
Thanks for the swift response. I will give it a try.

**Comment by shcheklein** [comment]
(reopening the ticket)

@jmunox depending on how Dropbox exposes its API you might take a look at how the Google Drive support is done in DVC - https://github.com/iterative/dvc/blob/master/dvc/tree/gdrive.py (but I would start with something simpler first just to understand the structure and what method implementations are expected, I agree with @efiop on this - WebDAV, maybe HTTP/Azure are good candidates).

**Comment by gmrukwa** [comment]
Hello there! Is anyone working already on this issue? I would love to sync if I could help, to avoid duplication of work.

**Comment by efiop** [comment]
@gmrukwa Doesn't look like it. Feel free to give it a shot :slightly_smiling_face:

**Comment by jmunox** [comment]
@gmrukwa Thanks for taking the lead here :) I am quite busy with work and studies at the moment. 

I started looking at this as example: 
https://github.com/j-min/pydropbox
