### ISSUE TITLE
`dvc import` from `s3://...` fails when s3 provided by 3rd party provider.

### ISSUE THREAD

**Issue by bwalsh** [iterative/dvc#1280]
* Standard aws client works, if endpoint url provided.
  * aws --endpoint-url https://\<my-endpoint\> s3 ls \<my-path\>
* DVC repository works, endpoint_url provided
```
['remote "minio"']
url = s3://<my-path>
endpointurl = <my-endpoint>
```

**However** `dvc import` fails because no capability to specify `endpoint url`
More details: https://gist.github.com/bwalsh/1afea0a2499b5e81c507dbc24521038e

**Comment by efiop** [comment]
Hi @bwalsh !

You can actually use that remote in the `dvc import` command. E.g. `dvc import remote://minio/path`. Could you please try it out and see if it works for you?

Thanks,
Ruslan

**Comment by shcheklein** [comment]
@bwalsh if you want to use one bucket for remote cache and another bucket for remote dependencies, I believe, you will need to create a separate remote using `dvc remote add` - https://dvc.org/doc/commands-reference/remote#add and use it instead the `minio` one

**Comment by shcheklein** [comment]
@efiop @mroutis Just a thing to think. I don't have any good suggestions yet. It's a little bit confusing that we use the same notion of remotes for storing cache and to specify external dependencies. Term "remote" came from git where it has only one specific purpose - as a central place to store commits (cache).

**Comment by bwalsh** [comment]
@efiop @mroutis  @shcheklein thanks everyone for the quick response.  

I tried setting up the second remote, adding the endpoint url,  and importing.  I can confirm the import remote://... works, thanks.

Left to my own devices I wouldn't have guessed it was a possibility.
I wish aws would fix their cli config [this issue](https://github.com/aws/aws-cli/issues/1270) w/ awscli has been open for a while.   In the interim the remote:// solution works, but is semantically confusing.

**Comment by efiop** [comment]
@bwalsh Sorry for a dumb question, but I just want to clarify. Are you aware that the `dvc import` not only downloads the file, but also tracks the remote source of that file and re-downloads if it has changed?

**Comment by bwalsh** [comment]
@efiop : yes I was aware.  The semantics of `dvc import` are clear, it's the semantics the of `remote://` by import

**Comment by mroutis** [comment]
@efiop, I'm going to label this as `documentation` to improve/clarify the `remote://` "protocol"

**Comment by mroutis** [comment]
Related: https://github.com/iterative/dvc.org/issues/108

**Comment by efiop** [comment]
Let's close this one, since we have same issue opened on dvc.org.
