### ISSUE TITLE
Errors are written on stdout instead of stderr

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1291]
```bash
dvc config 'unknown.config' 2> /dev/null

# Still can see the following message:
# Error: Invalid option name unknown
#
# Having any troubles? Hit us up at dvc.org/support, we are always happy to help!
```

**Comment by pared** [comment]
Hi, i created pr.
https://github.com/iterative/dvc/pull/1292
Not sure how to write test for that one though, should there be one?

**Comment by efiop** [comment]
Hi @pared !

Sorry for a delay, github is sick again and not sending any notifications about PRs and comments.

Thank you so much for looking into it! I think you could redirect or mock stdout/stderr then try Logger.error(), Logger.info() and make sure that messages got written to correct channels. Could you please add such a test to tests/test_logger.py please?

Thanks,
Ruslan

**Comment by pared** [comment]
Oh right, it didn't occur to me. Sure, I will write it.

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/1292 . Kudos @pared ! :tada:
