### ISSUE TITLE
gc: support used cache collection for several repositories using the same remote storage

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1300]
E.g. you have 2 projects that have somewhat similar cache files, that you decided to put on the same remote. Currently, calling `dvc gc -c` in one of the projects will wipe out remote cache for the second project, since used cache is only collected for the current project. Need to add ability to collect used cache for several projects.

**Comment by efiop** [comment]
For the record: @ynop from discord volunteered to work on this.

**Comment by shcheklein** [comment]
@ynop this is cool stuff, thanks! @ynop @efiop please, create a iterative/dvc.org ticket to update the documentation
