### ISSUE TITLE
updater: Run the check async

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1304]
Right now, we are checking if the user is running on an outdated version in a synchronous way, this can take some time (from ~3s to ~10s) as it calls our API that tracks the latest version; If we could run the whole check in an asynchronous way (spawning another process) it would not interfere with the normal workflow.

Also, it would be great to have an `update-notifier` config option to supress the update notification.

**Comment by efiop** [comment]
Also, as a part of this logic, it would be great to save latest version in `.dvc/updater`(we have an empty marker-file there right now) and use it to remind user about available update each time he runs `dvc` after that.
