### ISSUE TITLE
logger: Respect `--quiet` option

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1308]
Progress currently uses the `print` function basically for the `print(message, end='')` functionality;

Now, `Logger` uses the `progress` function to wrap some calls https://github.com/iterative/dvc/blob/46831ea00a51e770e3a85c0b5fffb7c99677b149/dvc/logger.py#L137-L141

So we can't use `Logger` on `Progress`, that would create a circular dependency.

**Comment by mroutis** [comment]
There's another instance of Logger using `print` that will not respect the quiet output at all.

https://github.com/iterative/dvc/blob/46831ea00a51e770e3a85c0b5fffb7c99677b149/dvc/logger.py#L224-L230

**Comment by dmpetrov** [comment]
It is a quite important thing. I'd not wait - "help wanted".
