### ISSUE TITLE
Improve `-j` help messages 

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1310]
For example, `dvc gc -j N`. There are also other DVC commands that have this option.

`-j` specifies parallelism level for the command. 

It should specify that default number depends on a remote type and that to get defaults one should refer to docs.

**Comment by jorgeorpinel** [comment]
It now reads "Number of jobs to run simultaneously.". Is that better?

**Comment by shcheklein** [comment]
@jorgeorpinel I think the idea was to include something like "Refer to docs to get default value that depends on the remote type" (better written).

**Comment by nik123** [comment]
1. As far as I understand default value depends not only on remote type but also on hardware configuration.
1. It seems that short help messages are more desirable than long ones.

So why not just "Refer to docs to get default value"?
