### ISSUE TITLE
Cannot VACUUM from within a transaction

### ISSUE THREAD

**Issue by IamGianluca** [iterative/dvc#1314]
First of all, thank you for building DVC. I've just discover it recently but I like the idea a lot! Thank you for all your hard work.

I'm running a command which outputs around 5 million images. DVC seems to fail while processing the hardlinks. 

```
$ dvc run -d code/radek_csv2png.py -o data/train-128/ -o data/test-128/ python code/radek_csv2png.py --sz 128 --pct 0.10   

...
...
...

Created 'hardlink': .dvc/cache/73/37f8c8f4c9f67d9070506f2f7338df -> data/test-128/9999996442242305.png 
Warning: Cleaning up state. This might take a while
Error: Unexpected error: cannot VACUUM from within a transaction
```

The interesting thing is that I've successfully executed the command in the past, while building the same amount of images but in half the size. I'm not sure if the size of the images might be what is creating issues for DVC.  I'll try to re-execute the command to see if it keeps failing.

Here are more info about my system.
```
$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ dvc --version
0.20.2
```

I've installed DVC though `pip`.

**Comment by efiop** [comment]
Hi @IamGianluca !

Looks like we have a bug while cleaning up our state file. Our current default entry limit is 10 000 000 entries, which is clearly not enough in your case. While we are considering increasing default limit and looking into vacuuming bug, you can change limit yourself in your dvc config with `dvc config state.row_limit 100000000`, which should make it work for now. Could you also tell us how big your state file is right now(i.e. `ls -lh .dvc/state`)?

Thanks,
Ruslan

**Comment by efiop** [comment]
One more thing, are you using python 3.6, right?

**Comment by IamGianluca** [comment]
Hi @efiop ! My state file is 474Mb. I'm using Python 3.7.0.

Out of curiosity, let's say I have a program silently failing during execution with `dvc run`. Since the failure was silent, `dvc` would go ahead and do its magic. To restore the previous stage, do I need to do anything more than:

1. Remove the output files from my environment, `rm -rf /data/output_data/`
2. Remove the added data folder from `data/.gitignore`
3. Remove the newly created stage file

I'm mostly thinking about the files in `.dvc/cache`.

**Comment by efiop** [comment]
Thank you for the info! I was able to confirm this bug on 3.6 as well as 3.7. Already sent a fix for it, going to merge it ASAP and release it in 0.20.3 in an hour or so. I'll notify you here when it is ready.


> 1. Remove the output files from my environment, rm -rf /data/output_data/
> 2. Remove the added data folder from data/.gitignore
> 3. Remove the newly created stage file

We have `dvc remove -p` for all of that ;) E.g. `dvc remove -p stage.dvc`.

> I'm mostly thinking about the files in .dvc/cache.

`dvc remove` will not remove those files from cache, but you can utilize `dvc gc` command for that. Note that it can be configured to delete all cache except the one used in your current workspace(i.e. your current commit), all tags and all branches with `dvc gc -aT`.

Thank you for all the feedback! I'll keep this open until patch is merged.

**Comment by IamGianluca** [comment]
Thank you so much for the bug fix and all the info @efiop I really appreciate it!

I need to complete the tutorial and work on the rest of the documentation. `dvc` is an awesome tool!

**Comment by IamGianluca** [comment]
1.

**Comment by IamGianluca** [comment]
1.

**Comment by efiop** [comment]
@IamGianluca 0.20.3 is out. Please feel free to upgrade :slightly_smiling_face: Thanks for the feedback!
