### ISSUE TITLE
repro: introduce --recursive-deps option

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1342]
Currently we have two policies for dependency checks on repro:

1) *default* direct dependencies;
2) --force;

Let's introduce a third policy called --recursive-deps, which would consider stage as changed if dependencies of its dependency stages have changed, even if outputs of those dependency stages didn't change.

E.g. instead of specifying requirements.txt  as a dependency for each stage in the pipeline, we would be able to specify it just once in the first most stage and then use `dvc repro --recursive-deps`, so that even if output of the first stage didn't change, dvc would re-run other stages, since they could depend on requirements.txt.

**Comment by mroutis** [comment]
So, `--recursive-deps` will recompute all the stage.deps checksums and run the stage file **just** if the checksums are different?

**Comment by efiop** [comment]
It is a little hard to explain with words, so here is an example instead :slightly_smiling_face: 

```
#!/bin/bash

set -x
set -e

rm -rf myrepo
mkdir myrepo
cd myrepo
git init
dvc init
git commit -m init

echo "pyyaml==3.11" > requirements.txt

echo 'import yaml' > write.py
echo 'with open("foo", "w+") as fobj:' >> write.py
echo '    yaml.safe_dump({"some": "info"}, fobj)' >> write.py

echo 'import yaml' > read.py
echo 'with open("foo", "r") as fobj:' >> read.py
echo '    d = yaml.safe_load(fobj)' >> read.py
echo '    print(str(d))' >> read.py

dvc run -f write.dvc -d requirements.txt -d write.py -o foo python write.py
dvc run -f read.dvc -d foo python read.py

# Now we change reqs. Both read.py and write.py depend on yaml,
# but it is only specified as a dependency in write.dvc
echo "pyyaml==3.12" > requirements.txt

dvc repro read.dvc
```

produces 

```
+ dvc repro read.dvc
Dependency 'requirements.txt' of 'write.dvc' changed.
Stage 'write.dvc' changed.
Reproducing 'write.dvc'
Running command:
        python write.py
Output 'foo' didn't change. Skipping saving.
Saving information to 'write.dvc'.
Stage 'read.dvc' didn't change.

To track the changes with git run:

        git add write.dvc
```

as you can see, in this particular case we're lucky(well, kinda) in that change to requirements.txt didn't change write.dvc's output, so dvc detected that direct read.dvc dependency foo didn't change and so it didn't have to reproduce read.dvc. This is where `--recursive-deps` option could be useful. It would force read.dvc reproduction, even if foo didn't change.
