### ISSUE TITLE
Team members should use the same profile for s3?

### ISSUE THREAD

**Issue by mizgyo** [iterative/dvc#1355]
I usually use aws cli with a profile (for example `aws s3 ls --profile myprof`).

Therefore, I set .dvc/config as follows:
```
['remote "myremote"']
url = s3://mybucket/folder
profile = myprof
```

When this configuration file is pushed to the git repository, all members' profile for s3 is set to myprof.
Is there a way to personally set the profile?

(Sorry for sending it before completion)

**Comment by efiop** [comment]
Hi @mizgyo ! Could you please elaborate on your question?

**Comment by mroutis** [comment]
You could use the local configuration, @mizgyo, so every team member have a different assigned profiles.

Or you can create another one with just the access needed for S3 operations:

s3:ListBucket
s3:GetObject
s3:PutObject
s3:DeleteObject

**Comment by efiop** [comment]
@mizgyo You can use local config to set your private settings that are not going to be pushed to git. Just use `--local` flag for respective `dvc config` and `dvc remote` commands, or write directly to `.dvc/config.local`.

**Comment by mizgyo** [comment]
Thanks for your reply.
The local configuration is what I was looking for.
I misunderstood that local configuration is set in the repository instead of machine local.
