### ISSUE TITLE
dvc add output

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#1356]
In `dvc run` you can specify dvc-file name. Why don't we create a similar option for `dvc add`?

```
$ dvc add file.zip -f Dvcfile
```

**Comment by efiop** [comment]
Great idea! Also `-c` should be supported along with it. Which will require cwd(or wdir) param for dvc files. Related https://github.com/iterative/dvc/issues/1332.

**Comment by efiop** [comment]
Same for `dvc import`.

**Comment by dmpetrov** [comment]
One more request for this feature: https://discordapp.com/channels/485586884165107732/485586884165107734/537898841790480395

**Comment by mroutis** [comment]
@dmpetrov , @efiop , `dvc add` supports different targets (e.g. `dvc add foo.txt bar.txt`), creating one stage for each target (e.g. `foo.txt.dvc `, `bar.txt.dvc`), whereas `dvc run` always represent a single stage.

I'm thinking about ignoring the `--file` option when different targets are given, what are your thoughts on this one?

**Comment by shcheklein** [comment]
I don't like ignoring. Why don't we do one of:

1. Deprecate multiple targets. Raise an exception. Yes, it breaks compatibility a little bit but streamlines behavior.
2. Create a single DVC files with multiple outputs.

It just feels that if `dvc add` takes multiple targets it should be at least something more than solely replacing multiple `dvc add` commands.

**Comment by mroutis** [comment]
I like your approach, @shcheklein

1. Having multiple targets is somehow inconsistent with `run` (where the former one support globbing, while the later one you need several `-o` flags). I prefer to add

**Comment by efiop** [comment]
Or, we could simply not support `-f` with multiple targets. Backward compatibility will not be affected and we will support the target feature :tada:

**Comment by shcheklein** [comment]
Like raise an exception if multiple targets are specified? I'm fine with this option. I would probably deprecate multiple targets anyway in the future. Just don't see any reasons to complicate the logic.
