### ISSUE TITLE
dvc: consider introducing `dvc pipeline` subcommands

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1364]
We should move all the pipeline related functions under it. For example https://github.com/iterative/dvc/issues/1202.

`dvc repro` -> `dvc pl repro`
`dvc status` -> `dvc status`(for data, same as `git status`) + `dvc pl status`(for pipelines, which compliments `dvc pl repro` and has similar behavior)
`dvc pipeline show/list/etc` -> `dvc pl show/list/etc`

**Comment by efiop** [comment]
Agreed that `dvc pipeline` is better than shorter `dvc pl`, which we could introduce later if we really need to.

**Comment by skshetry** [comment]
@efiop, can this be closed as there's no `pipeline` command?

**Comment by efiop** [comment]
@skshetry The `repro/run/status` still might benefit from being separated into some subcommand. But yeah, let's close it.
