### ISSUE TITLE
run: support --non-deterministic

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1379]
This flag should mark dvc file as:

```
deterministic: False
```

and `dvc repro` should always reproduce it.

**Comment by prihoda** [comment]
Why not call it something like `--always-reproduce`, so that it can be used in other contexts?

**Comment by efiop** [comment]
@prihoda That is a actually a great name suggestion :) We'll use it instead. Thank you!

**Comment by prihoda** [comment]
I'm wondering, how about we discard callback stages and support that behavior with `--always-reproduce`? Personally, I don't see the causality in the "no dependencies" => "always reproduce" behavior.

**Comment by efiop** [comment]
@prihoda I agree, `--always-reproduce` is a much nicer way of achieving that `callback` behavior. I think we could abandon it in the 1.0. Created https://github.com/iterative/dvc/issues/1407 . Thanks! :slightly_smiling_face:

**Comment by efiop** [comment]
We now have `--always-changed` flag for `dvc run`. Closing this in favor of https://github.com/iterative/dvc/issues/1407
