### ISSUE TITLE
s3: add option to disable ssl verification

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1394]
I.e.
```
s3 = boto3.client('s3', verify=False)
```

Might be useful for people with strict ssl policies at a workplace.

**Comment by mroutis** [comment]
@efiop , could you describe a little bit more the use case?

I don't think it should be a good idea to disable verifying the certificates; there's another option `use_ssl`, tho, that will disable SSL.

For the ones who have custom endpoints without SSL certificates, for example: `http://localhost:8000` it will not force SSL usage.

**Comment by mroutis** [comment]
In case we implement this, I'm imagine something like: `dvc remote modify bucket disable_ssl true`, what do you think?

**Comment by efiop** [comment]
I was actually thinking about something like `dvc remote modify mys3remote verify_ssl false`(`true` by default`).
