### ISSUE TITLE
http: use Content-Md5 header if available

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1412]
We could use it for https://github.com/iterative/dvc/issues/1348 .

**Comment by efiop** [comment]
> That MD5 doesn't look good... I was expecting something like the result from: echo -n 'Check Integrity!' | md5sum.

It is just encoded in base64 and md5sum outputs hex. Here is us converting it in GS remove: https://github.com/iterative/dvc/blob/0.22.0/dvc/remote/gs.py#L55

**Comment by efiop** [comment]
> For #1348, the stagefile has the MD5 of the downloaded content, so we could use that one to check if it is already cached, alongside with the ETag.

Yes, that would be even better, I agree. Especially since our checksum is dos2unix + md5sum, so content-md5 might not always match our checksum.

**Comment by mroutis** [comment]
> > That MD5 doesn't look good... I was expecting something like the result from: echo -n 'Check Integrity!' | md5sum.
> 
> It is just encoded in base64 and md5sum outputs hex. Here is us converting it in GS remove: https://github.com/iterative/dvc/blob/0.22.0/dvc/remote/gs.py#L55

:sweat_smile: Thanks, @efiop.

Just to be clear, if `Content-MD5` header is available, we will store the decoded value as an `ETag` instead of searching for the `ETag` header, right?

**Comment by efiop** [comment]
Yes, seems right :) This is not top priority though, ETags works perfectly right now.
