### ISSUE TITLE
pipeline show only ancestors

### ISSUE THREAD

**Issue by vernt** [iterative/dvc#1419]
`dvc pipeline show --ascii my.dvc` seems to show all of the files involved in a dag. I'm interested in getting only the (recursive) ancestors of `my.dvc`, and excluding other descendants of the parents. 
Perhaps `--ancestors` or `--deps`.

**Comment by karajan1001** [comment]
I tested " pipline show --ascii [target dvc file]“ and it only shows the ancestors of the target now. May it been closed now? 
![image](https://user-images.githubusercontent.com/6745454/78761528-4f9dbb00-79b5-11ea-8b51-117ca6b2f581.png)

**Comment by efiop** [comment]
Thank you for the investigation @karajan1001 ! :pray: @vernt Maybe you meant descendants? E.g. like `--downstream` for `dvc repro`?
