### ISSUE TITLE
repro: Introduce an `--eta` option to show estimates of reproducing that stage

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1420]
## Why?
It seems useful to know how your stages are performing (for examle, how long it took to train a model).

The estimated would be based on a previous captured execution time of that stage (probably, at `dvc run`).

## Description
```bash
dvc import s3://mybucket/big-file.csv
# took ~15 minutes

dvc repro --eta big-file.dvc
# 15 minutes

dvc repro big-file.dvc
# Reproducing 'derp.dvc' (~15 minutes)
# ...
```

## Caveats
- Estimates would vary dependending on the machine / network.

**Comment by efiop** [comment]
Closing for the lack of interest from the community.
