### ISSUE TITLE
remote: local: support relative paths

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1421]
E.g. `dvc remote add mylocal ../../mydir`. Note that same as with `cache.dir`, path should be resolved relative to config file location, which is `.dvc`.

**Comment by dlazerka** [comment]
Great, I would take a caution about going ../ from the root dir (i.e. outside project), might be a security issue. Although I heard that it might be hard to really determine if you're "outside" (symlinks and whatnot).

**Comment by efiop** [comment]
@dlazerka DVC doesn't have any additional privileges, so it can't do much harm :) Unless I'm missing something.

**Comment by dmpetrov** [comment]
@dlazerka thank you for your feedback!

A relative path should not base on `.dvc`. However, we can resolve the path and save it as a relative to  `.dvc`.

#1284 is not a relevant explanation for this case since `dvc remote` is not a direct interface for config file manipulation. We should support "principle of least surprise" for high-level commands such as `dvc remote`.

**Comment by efiop** [comment]
@dmpetrov Turns out `git remote add myremote ../somedir` writes `../somedir` as is to the config file and then resolves it relative to the project's root. So following that logic and considering that `cache.dir` from #1284 is a shorthand for an implicit remote, we should indeed resolve `cache.dir` relative to the project's root, as you've mentioned in #1284 Funny enough, when you specify a remote with a relative path in your global(or system) config, git still resolves its path relative to the current project's root, which is extremely odd. That is why I think that resolving based on a config location is much more logical and with the "least surprise", since it provides a unified experience across all commands(config/remote) and all levels of config(local, project, global, system).
