### ISSUE TITLE
Remote storage management

### ISSUE THREAD

**Issue by AratorField** [iterative/dvc#1424]
Hi,
Is there any option to manage my remote storage?
My team run multiple experiments with multiple repos with multiple branches and everywhere we used the same remote storage.
Now I would like to clean my remote storage bc I need to save memory and throw away some of the useless files. But on remote, I have only md5 as a name of the files without any information about which repo/branch is the 'owner' of the file. It is almost impossible to manage my storage that way.

**Comment by efiop** [comment]
Please feel free to reopen.
