### ISSUE TITLE
no prompt for keyfile passphrase; unhelpful message not a valid OPENSSH private key file

### ISSUE THREAD

**Issue by sunavc** [iterative/dvc#1425]
Hi,

I have dvc setup with -
dvc version = 0.22.0
Platform = Ubuntu 16.04.5 LTS
Installation method = pip3 install dvc

I have configured a ssh remote and a passphrase protected keyfile. I have verified that I can ssh into the remote machine with the given keyfile. However, `dvc pull` fails with
> Error: Failed to pull data from the cloud: not a valid OPENSSH private key file
and doesn't prompt me for a passphrase

Could you enable prompt for passphrase for protected keyfiles?

**Comment by sunavc** [comment]
Ok. I tried setting the `ask_password true` and it effectively works. The prompt

> Enter password for host [host] port [port] user [user]:

is a bit misleading since the ssh key passphrase should be entered.

Also, adding this example to the documentation at https://github.com/iterative/dvc.org/blob/master/static/docs/commands-reference/remote.md#click-for-ssh-available-options will increase awareness.

Thanks!

**Comment by efiop** [comment]
Hi @sunavc !

Great point! Edited doc https://github.com/iterative/dvc.org/commit/ee7e7577a2623c8d0f2d6a54b4d3d863cb77d71d to mention that password can be used as a private key passphrase. Will edit password prompt message ASAP too, leaving this issue open until it is done. Thank you for the feedback!

**Comment by ccravens** [comment]
I know this issue is a bit old, but I'm wondering why we have to explicitly set  this option? Can't it just ask for the password once it detects it's encrypted by default?

Thanks!

**Comment by efiop** [comment]
Hi @ccravens ! We weren't able to find a reasonable way to auto-detect it with paramiko. If you know how to do it, please feel free to share or even consider submitting a PR(better discuss first though). 🙂
