### ISSUE TITLE
gc: optimize for directories with giant numbers of files

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1429]
https://github.com/iterative/dvc/issues/1340#issuecomment-443435956

**Comment by efiop** [comment]
To make it more clear: currently we collect all used cache and all unused cache into the memory and even copy those lists a few times while working on them. That can get ugly when you have a lot of giant directories (~1M files) in your workspace and cache. Need to investigate the bottlenecks and try to fix them.

**Comment by Suor** [comment]
The most obvious thing is md5 calculation being slow. We cache it, but only for 100 most recently used entries. So simply increasing this value might help.

**Comment by efiop** [comment]
@Suor I don't remember md5s being calculated during gc. Also, we cache 
 100000000 https://github.com/iterative/dvc/blob/master/dvc/state.py#L77 most recently used md5s.

**Comment by Suor** [comment]
I see now that it's overwritten later. `State.__init__` is confusing:
```python
        self.row_limit = 100
        ...
        state_config = config.get(Config.SECTION_STATE, {})
        self.row_limit = state_config.get(...)
````

**Comment by Suor** [comment]
Why this row limit is needed at all? Is it a legacy of JSON state? Should we drop it?

**Comment by efiop** [comment]
yeah, that `self.row_limit = 100` seems to be a leftover from some time in the past. We can safely remove those two lines.

> Why this row limit is needed at all? Is it a legacy of JSON state? Should we drop it?

It is needed so that your state db doesn't grow too big. I don't think we should drop it, since sqlite db can grow too big too.

**Comment by Suor** [comment]
I tried generating a directory and adding it with `dvc add` and then running `dvc gc` under profiler. This takes some time, but I can't see how this can take hours unless networks is involved or many md5s are missing.

P.S. there are some lists copies and unneeded path normalizations like:
```python
cls._replace_sep(path, "\\", "/")
```
The last took significant part of the whole time in my tests, significantly complicating the code as a bonus.

**Comment by Suor** [comment]
@efiop maybe there are some scenarios I am overlooking, like adding all that 100k files with separate stages. Do we support that?

**Comment by Suor** [comment]
Closing this for now. Asked @IamGianluca about specifics.
