### ISSUE TITLE
Got doubled data with `dvc add`

### ISSUE THREAD

**Issue by TezRomacH** [iterative/dvc#1442]
### Information about the environment
```
dvc --version
0.22.0
```
Installed with macOS package to macOS Mojave.

### Bug report
I tried [this tutorial](https://dvc.org/doc/tutorial/define-ml-pipeline) to reproduce and got some error.
During the tutorial, `dvc add` command should not copy cashed data. But as you can see below the total folder size is doubled.
```
aiml/tutorial_dvc/classify  master  
▶ du -sh data 
 41M	data

aiml/tutorial_dvc/classify  master  
▶ du -sh .dvc/cache 
 41M	.dvc/cache

aiml/tutorial_dvc/classify  master 
▶ du -sh .
 82M	.
```
Reflinks to nodes are different. Maybe it's the case. Let me know if you need some extra information about my environment.
```
aiml/tutorial_dvc/classify  master
▶ ls -i data/Posts.xml.zip
4690717 data/Posts.xml.zip

aiml/tutorial_dvc/classify  master
▶ ls -i .dvc/cache/ec/
4688793 1d2935f811b77cc49b031b999cbf17
```

**Comment by TezRomacH** [comment]
I've checked issue #942 but fix in `0.14.0` seems to be not working

**Comment by efiop** [comment]
Hi @TezRomacH !

Your system supports reflinks, so dvc used them to create a link from cache to your workspace. No data duplication has occurred. Unlike hardlink, reflink to a file has different inode, so it is a bit harder to see it working for yourself. Also, `du` utility still counts them as two separate full-blown files, even though there is no duplication on the filesystem level. We should definitely make it more clear in the documentation. Created https://github.com/iterative/dvc.org/issues/139 .

Thanks for the feedback!

**Comment by TezRomacH** [comment]
Oh, thanks, now it's clearer!
