### ISSUE TITLE
remote: Raise error when trying to use a remote without the needed packages

### ISSUE THREAD

**Issue by ghost** [iterative/dvc#1443]
For example, running the following command without having `boto3` installed:
```
dvc remote add bucket -d s3://mybucket
```

Should raise a meaningful error with instructions to install the missing dependencies.

**Comment by mroutis** [comment]
This issue changed a little bit... It looks like it was already implemented by @efiop before, however, the implementation is still buggy:

The logging is happening after the program exists:
![2018-12-20-11 34 59](https://user-images.githubusercontent.com/7363250/50302344-6da57c00-044f-11e9-96cb-b85a1b26e88f.png)

And when trying to check the status it crashes: 
![2018-12-20-11 42 50](https://user-images.githubusercontent.com/7363250/50302353-7433f380-044f-11e9-84ca-6a486b25cf7c.png)

Feel free to edit the title to have a better description of the problem
