### ISSUE TITLE
ask users to opt in/out of analytics, and document the feature

### ISSUE THREAD

**Issue by mdscruggs** [iterative/dvc#1449]
I was a bit surprised to see that DVC recently added analytics tracking without asking users' permission, and without updating the docs: https://github.com/iterative/dvc/pull/1395

I bet most users would rather not send system and other information to some random endpoint in the cloud. This kind of feature (and more importantly the lack of transparency) makes it harder to trust tools like DVC.

I suggest asking users upfront during `dvc init` if they want to enable analytics. That adds transparency and would at least give users a chance to opt in/out.

**Comment by mdscruggs** [comment]
Thanks for the thorough and quick reply @shcheklein, and thank you and the team for the work on DVC. It's a really useful tool!

It's good to hear the intent behind the analytics feature. My main concerns as a potential user of any open-source software include trust (in the devs/project/code), security, API stability, and of course performance/features (roughly in that order). Security risks can be introduced merely by upgrading OSS packages...which is akin to what could happen here with the release of DVC's analytics feature. Appropriate transparency and documentation should come alongside such features, not afterwards.

I suggest that your docs also include clear specifics of how the data *is* used in addition to how it is *not* used, along with how the data is stored, replicated, shared, retained, accessed, etc. Ideally the data would be rapidly aggregated, such that individual events are not persisted...although I realize that may not be feasible. Even better would be to share the statistics you're gathering publicly, in the spirit of OSS (you have a nice website to put them on too!).

Thanks again. Please know my intent is to provide constructive feedback, and that DVC is quite a nice tool.

**Comment by shcheklein** [comment]
@mdscruggs sorry, for the delay in response.

* We've made a change to the `dvc init`
<img width="500" alt="screen shot 2019-01-10 at 3 30 49 pm" src="https://user-images.githubusercontent.com/3659196/51003749-d632c680-14ec-11e9-8361-b4ae45ff85d0.png">

* We've published a document that describes all the details - https://dvc.org/doc/user-guide/analytics

> Appropriate transparency and documentation should come alongside such features, not afterwards.

Totally agree, we should have put that document before and start by modifying `dvc init` to mention that. It's our mistake. Even though we didn't have intention to hide anything (we had an open to everyone ticket on Github).

> Even better would be to share the statistics you're gathering publicly, in the spirit of OSS (you have a nice website to put them on too!).

This our intention. To share an aggregated view of the data when we have a better understanding how to do that.

> Please know my intent is to provide constructive feedback

Totally, rely on this kind of feedback to grow a healthy and open community around DVC. Thanks again!

Please take a look at these changes and let me know what your thoughts are.
