### ISSUE TITLE
dvc: support distributed cache

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1450]
E.g. you have a few hard drives and you want to spread your dvc cache across them.

**Comment by sotte** [comment]
Because distribution is much easier when you think in terms of immutability and content addressability I'll just reference #829 here.

**Comment by efiop** [comment]
@sotte Could you please elaborate?

**Comment by sotte** [comment]
@efiop Um, sorry, somehow I misinterpreted the ticket. Just forget it :)

I guess my thought was, that if you have content addressability storing stuff is easier (see git).

**Comment by ei-grad** [comment]
The problem mentioned in this issue should be addressed by LVM, RAID and similar technologies, not by dvc, IMHO.

**Comment by efiop** [comment]
I agree with @ei-grad . So far there was no request for handling this on dvc side. Closing for now
