### ISSUE TITLE
fix issues reported by pycharm

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1453]
Would be great if we could setup pycharm to check code on travis.

**Comment by jorgeorpinel** [comment]
> setup PyCharm to check code on Travis

What does that mean or look like? Confused 😋 

Would also vote for `p4` or no priority label here.

**Comment by efiop** [comment]
@jorgeorpinel 

> What does that mean or look like? Confused 😋

Running something from https://www.jetbrains.com/help/pycharm/command-line-code-inspector.html on travis.

> Would also vote for p4 or no priority label here.

p4 is being removed, but even if it wasn't it is more important that p4

**Comment by jorgeorpinel** [comment]
I see. And that's better/complementary to the deepsource.io and codeclimate.com checks? Just curious

**Comment by efiop** [comment]
@jorgeorpinel Yes, since those are going to be experienced by anyone using pycharm to develop dvc.

**Comment by jorgeorpinel** [comment]
Cool, is that the "official" IDE we're using? I mostly use VSCode nowadays but can switch to PyCharm when/if I get more involved with core dev. (Maybe something to mention on the contributing guide as well – I can add.)

**Comment by efiop** [comment]
@jorgeorpinel No, it is not a official IDE. But some developers are using pycharm and were raising the question about all of those warnings it is throwing.

**Comment by efiop** [comment]
Closing as stale. We have a few linters already + the ongoing mypy integration https://github.com/iterative/dvc/issues/4697 . Doesn't make sense to waste time on pycharm.
