### ISSUE TITLE
Version 0.23.2 does not work with Azure remote

### ISSUE THREAD

**Issue by raikhan** [iterative/dvc#1458]
Hi,

This is my first time writing a bug report, so please excuse me if I miss something. I am using DVC on Windows 10 with an Azure remote. After updating DVC to latest version (0.23.2) today, I tried to use 'dvc pull' which updated the state file version from '2' to '3' and then produced this error:

> [#########                     ] 30% Collecting informationClient-Request-ID=9c458912-0a4a-11e9-b07e-144f8a2a9eb3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 28 Dec 2018 02:45:18 GMT, Server-Request-ID=2808e2e3-a01e-005c-3357-9e6a14000000, HTTP status code=400, Exception=The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.RequestId:2808e2e3-a01e-005c-3357-9e6a14000000Time:2018-12-28T02:45:18.4898344Z</Message></Error>.
> Error: Failed to push data to the cloud: The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
> <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
> RequestId:2808e2e3-a01e-005c-3357-9e6a14000000
> Time:2018-12-28T02:45:18.4898344Z</Message></Error>

The issue is appearing even with a completely fresh dvc init. After reverting back to version 0.22.0, everything works again.

I suspect some non-ASCII characters are used with the new file version '3' which is causing the issue. Please let me know if any more info from my side can help.

**Comment by efiop** [comment]
Hi @raikhan !

Could you please run that command with `-v` flag added and show us the log?

**Comment by efiop** [comment]
@raikhan And could you please try reconfiguring your remote url like so:
```
dvc remote add -d myremote azure://dvctest/
```
(you can also just edit it right in your .dvc/config)
and see if that works?

**Comment by raikhan** [comment]
That seems to have done the trick! Here is the dvc pull -v again:

> Debug: PRAGMA user_version;
> Debug: fetched: [(3,)]
> Debug: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
> Debug: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
> Debug: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
> Debug: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
> Debug: PRAGMA user_version = 3;
> Preparing to download data from 'azure://dvctest/'
> Preparing to collect status from azure://dvctest/
> [##############################] 100% Collecting information
> [##############################] 100% Analysing status.
> Debug: SELECT count from state_info WHERE rowid=1
> Debug: fetched: [(0,)]
> Debug: UPDATE state_info SET count = 0 WHERE rowid = 1
> Debug: PRAGMA user_version;
> Debug: fetched: [(3,)]
> Debug: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
> Debug: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
> Debug: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
> Debug: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
> Debug: PRAGMA user_version = 3;
> Debug: SELECT * FROM link_state
> Debug: SELECT count from state_info WHERE rowid=1
> Debug: fetched: [(0,)]
> Debug: UPDATE state_info SET count = 0 WHERE rowid = 1
> Debug: Analytics is enabled.
> Debug: Trying to spawn '['c:\\users\\raicevim\\appdata\\local\\continuum\\anaconda3\\python.exe', '-m', 'dvc', 'daemon', '-q', 'analytics', 'C:\\Users\\raicevim\\AppData\\Local\\Temp\\tmp74_h015e']'
> Debug: Spawned '['c:\\users\\raicevim\\appdata\\local\\continuum\\anaconda3\\python.exe', '-m', 'dvc', 'daemon', '-q', 'analytics', 'C:\\Users\\raicevim\\AppData\\Local\\Temp\\tmp74_h015e']'

My config is now:

> 
> ['remote "dvctest"']
> url = azure://ContainerName=dvctest;
> [core]
> remote = myremote
> ['remote "myremote"']
> url = azure://dvctest/

So the "ContainerName" in the Azure URL is the issue? I was using the example from [documentation](https://dvc.org/doc/commands-reference/remote) when setting it up...

**Comment by efiop** [comment]
Yes, we've introduced a more natural url structure for azure remotes, but, apparently, didn't test backward compatibility well enough. Looking into fixing this right now. Thank you for the feedback! :)

**Comment by raikhan** [comment]
My pleasure @efiop , glad I could be of service :) Thank you for explaining the issue!

**Comment by efiop** [comment]
Let's keep this opened until everything is fixed :)

**Comment by efiop** [comment]
Also updated the docs at https://github.com/iterative/dvc.org/commit/0ef79751f84e920c41615851aee62094f3c3c3bc
