### ISSUE TITLE
pull/push/etc: support -R option

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1464]
E.g. `dvc pull -R ./subfolder` would walk down the subfolder, find all the .dvc files and pull all of them.

**Comment by efiop** [comment]
@pared Just noticed that in the current implementation -R has an argument, instead of it being a flag that affects how `targets` argument is treated. E.g. so you could do stuff like `dvc pull -R dataset1/ dataset2/`, `dvc pull dataset1/ dataset2/ -R` and so on. Same as -R works on `dvc add`. What do you think?

**Comment by pared** [comment]
Oh, yest, that is inconsistent. Ill look into that.
