### ISSUE TITLE
metrics show: support -R

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1465]
I.e. `dvc metrics show -R subfolder` would show metrics for everything in that subfolder and down below.

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/issues/1465

**Comment by AlJohri** [comment]
adding a related usecase:  each experiment of mine has multiple stages and also intermediate results for those stages. sometimes it makes sense to compare those together. like the cross-validated f1 score on training before hyperparamter tuning and after

it would be cool to use globbing or regex to provide the path I want `dvc metrics show` to use. for example:

```
dvc metrics show experiments/**/ml_model/level_5/scores.json
dvc metrics show experiments/**/rule_model/level_5/scores.json
dvc metrics show experiments/**/parameter_search/level_1/best_cv_scores.json
```

**Comment by efiop** [comment]
@AlJohri For the record: we've discussed it in discord and turns out it is related to https://github.com/iterative/dvc/issues/1497 and not this issue.

**Comment by efiop** [comment]
@tdeboissiere 3 is not related to this particular issue since the globbing is done by your shell when you run that command. Yeah, 2 seems complex and might interfere with 1. I would just stick with 1 for now. Thanks for looking into this :slightly_smiling_face:

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/1543
