### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by IlyaKisil** [iterative/dvc#1468]
There is a typo at the first line of installation commands for [Ubuntu/Debian (apt)](https://github.com/iterative/dvc#ubuntu--debian-apt). 

```
sudo wget https://dvc.org/deb/dvc.list -O etc/apt/sources.list.d/dvc.list
```

Forward slash is missing. It should be:
```
sudo wget https://dvc.org/deb/dvc.list -O /etc/apt/sources.list.d/dvc.list
```

**Comment by mroutis** [comment]
Good catch, @IlyaKisil! Do you want to submit a PR for it? :)

**Comment by IlyaKisil** [comment]
Yeap, sure)
