### ISSUE TITLE
ssh: support specifying port in the url

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1473]
Currently we only support specifying port with `dvc remote modify myssh port 1234`

I.e. need to modify our regex https://github.com/iterative/dvc/blob/0.23.2/dvc/remote/ssh.py#L48

**Comment by mroutis** [comment]
@efiop, maybe not even use a custom regex, what about `urllib.parse`? 

The API should expose the parts of the URL we are interested in.
Also, `urlparse` understands almost everything from connection urls:
```python
from urllib.parse import urlparse

p = urlparse('postgresql://mroutis:changeme@localhost:8080/database')

p.schema   # postgresql
p.username # mroutis
p.password # changeme
p.hostname # localhost
p.port     # 8080
p.path     # /database
```

The only problem I'm currently seeing and that stopped me from an RFC on the remotes, is Azure, they use a different kind of URL format (more like several key=value statements joined with a semicolon, IIRC), in this case, I was thinking to delegate the "url" validation to the Azure module, but didn't get that far on their documentation.
