### ISSUE TITLE
[Dev-process] Automatic coding style formatter

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#148]
Probably a good idea to add something like autopep8 to automatically format submitted code before merging it. This is not very crucial today as there are a few active contributors, but in the near future we expect to get more contributions and we better be prepared for it, as otherwise code might become a total mess.

**Comment by dmpetrov** [comment]
Right. It is not for today.
But it would be nice to have some doc.

**Comment by efiop** [comment]
Need to follow PEP8

**Comment by villasv** [comment]
My suggestion is [black](https://github.com/ambv/black) :-)

**Comment by efiop** [comment]
@villasv Thank you for a great suggestion! I'll take a closer look shortly.

**Comment by efiop** [comment]
Unfortunately black requires python > 3.5, which created a lot of hustle. So we are now using flake8, to simply check that code complies with pep8 when processing PR on travis.
