### ISSUE TITLE
remote: local: test hardlinks/symlinks/reflinks before using them

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1481]
E.g. some filesystems like sshfs will allow you to create a symlink, but won't allow to read it. So we need to first test that we can create a link and it is functional and only then move data to cache and create real links.

**Comment by mroutis** [comment]
@efiop we are already doing this with the `_try_links` method, isn't it?

**Comment by efiop** [comment]
@mroutis we are not testing if it is functional. Currently, we are moving things to cache and only then trying to link it, which is not the proper way to do it. We should first make sure that we can indeed create links and only then move things to cache.

**Comment by efiop** [comment]
This will introduce quite an overhead if we try to do that while linking. Doesn't seem like people are running into it much, so closing as stale for now.
