### ISSUE TITLE
state: investigate excessive checksum re-calculations

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1485]
From discord:

> I added the file, which computed checksum.  Then I dvc pushed, which computed checksum.  Then I dvc run -d thatfile, which computed checksum after the command finished.  Then I dvc pushed again (to make sure it wasn't going to push the dir that I untarred), which is computing the checksum again.

**Comment by efiop** [comment]
Might be related to https://github.com/iterative/dvc/issues/1221

**Comment by dmpetrov** [comment]
@efiop it might be helpful to provide links to Discord message like this https://discordapp.com/channels/485586884165107732/485596304961962003/532673018367967256.

An instruction if you have not done this before: https://support.discordapp.com/hc/en-us/community/posts/360032427392-Linking-chat-messages

**Comment by efiop** [comment]
@efiop Thanks! 🙂 Totally forgot about that useful feature!

**Comment by bwalsh** [comment]
FYI.  Seeing the same.
