### ISSUE TITLE
state: size == 0 for files

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1496]
https://api.travis-ci.com/v3/job/170074192/log.txt

After we've fixed checksum re-calculation issue, our tests on mac os started to fail, because we usually replace an input file foo->bar, which has the same size, so our state subsystem is unable to detect the change. Need to make self.FOO and self.BAR from TestDvc use content of different length. Otherwise we would need to bring back sleep() hacks for tests that we used to have before.

**Comment by mroutis** [comment]
Interesting :thinking:

**Comment by efiop** [comment]
Ok, I see it. In the mtime_and_size method we only sum up sizes for files in a directory. What we should do instead is:
```

        mtime = os.path.getmtime(path)

        if os.path.isdir(path):
            size = 0
            ...
        else:
            size = os.path.getsize(path)
```

**Comment by efiop** [comment]
fixed with https://github.com/iterative/dvc/pull/1502
