### ISSUE TITLE
metrics: show: support multiple targets

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1497]
Currently, it only supports one single target.

From Al on discord:

```
this works fine: dvc metrics show ml_model/level_1/scores.json
this doesn't: dvc metrics show ml_model/level_{1,2}/scores.json
Error: unrecognized arguments: ml_model/level_2/scores.json
```

**Comment by mroutis** [comment]
what's the purpose of doing `dvc metrics show` for a single path instead of using `cat`?

`cat ml_model/level_{1,2}/scores.json` ?

**Comment by mroutis** [comment]
what about `dvc metrics show ml_model/` ?

**Comment by shcheklein** [comment]
To run it with -a or -T for example?

**Comment by shcheklein** [comment]
Or `metrics show -R dir` another example for a single target case

**Comment by mroutis** [comment]
Indeed, @shcheklein :+1:

**Comment by mroutis** [comment]
@efiop , will the same `--xpath` be applied to the multiple targets? 

Also, the `--type` option looks more like a filter ("select all the metrics where type is csv") than something that will modify the  "show behavior" -- it is not that clear, we might need to edit the help message. I will prefer removing that option from `metrics show` and leave it under `metrics modify`.
What do you think, @efiop ?

**Comment by shcheklein** [comment]
> will the same --xpath be applied to the multiple targets?

@mroutis yes, this is how it's working now (if no targets are specified and -x or -t are provided). Changing this would be a separate ticket I would say.

>  it is not that clear, we might need to edit the help message

It would be great. The goes for docs. I would keep the option itself, even though I agree it's quite strange to apply the type. One use case that comes to my mind is when you have a history of metric and DVC-files in git that do not have type specified. You would need to provide the type to apply it retrospectively.

**Comment by shcheklein** [comment]
@efiop @mroutis update docs please :)
