### ISSUE TITLE
dvc: introduce `dvc md5` or `dvc checksum` command

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1500]
It would compute checksum for a file/directory the same way we do it in dvc. Useful for debugging purposes.

**Comment by dmpetrov** [comment]
A single command for a debugging purpose sounds like a too big API change. Is there a way to hide this command under some other command like `status` (which checks checksums) or `cache`?

A related question... We have a separate `dvc destroy` command but it looks like a revert operation to `dvc init`. Why don't we move it under `init` umbrella like `dvc init --destroy`?

**Comment by efiop** [comment]
Yeah, I agree. I was even thinking about the long gone "fsck" command, but I still don't like it :) It should indeed simply be a part of status output.

Related https://github.com/iterative/dvc/issues/1202 .

About the `destroy`. We already have it and there is no better use for that name as of today, so there is little to no incentive as to move it under `dvc init`. :)

**Comment by mroutis** [comment]
I'm about to work on this issue, I'm up to adding a new `dvc checksum` command, as `status` is currently for stage files, whereas `checksum` would be for files and directories.

**Comment by efiop** [comment]
@mroutis let's skip this one for now.

**Comment by efiop** [comment]
Closing as we now have `dvc commit` https://github.com/iterative/dvc/issues/919 and we no longer need to be able to construct checksums.

**Comment by mroutis** [comment]
@efiop , it would be a nice to have, tho; kind of like a _plumbing_ command

**Comment by efiop** [comment]
@mroutis Don't really see where it would be needed, and no one is asking for it after `dvc commit` was implemented.

**Comment by gerardsimons** [comment]
I think this would be still be useful. Sometimes I notice my models are not the same. I probably forgot to use a fixed random seed along the way somewhere, but finding at which stage this happens is a little painful as I have to md5sum all intermediate files, and I am never 100% sure if I am doing it the same way as DVC does it.

**Comment by skshetry** [comment]
> I think this would be still be useful. Sometimes I notice my models are not the same between different repro runs. I probably forgot to use a fixed random seed along the way somewhere, but finding at which stage this happens is a little painful as I have to md5sum all intermediate files, and I am never 100% sure if I am doing it the same way as DVC does it.

@gerardsimons, this is now possible with `dvc-data` cli that should be available if you installed `dvc` via pip. If not, you can install via:
```console
pip install dvc-data[cli] -U
```
There are two ways:
1. `dvc-data hash -p <file>` can only give you a md5sum for a file.
2. `dvc-data stage <file or directory>` can return you a final string result for a file or directory (which is stored in `.dvc` and `dvc.lock` files).

**Comment by gerardsimons** [comment]
Cool! That seems very useful! @skshetry thanks for the quick reply
