### ISSUE TITLE
Unable to upload large file (250MB) to Google Cloud Storage 

### ISSUE THREAD

**Issue by suraj-pai** [iterative/dvc#1516]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

DVC Version: 0.23.2
Platform: Ubuntu 16.04
Method of Installation: pip

Unable to upload a single large file ( around 250MB) to Google Cloud storage. 

I am able to upload smaller files through dvc push and able to upload the same large file via gsutil to Cloud storage.

Am I missing something here with respect to large files? The progress bar doesn't shift either and a timeout gets thrown after around 10 minutes approximately

**Comment by efiop** [comment]
Hi @suraj-pai !

Definitely looks like a bug. We'll try to reproduce it shortly.

Thanks for the feedback!

**Comment by suraj-pai** [comment]
Hi Ruslan,

The progress bar is stuck at the specific file name I am trying to upload. It works with smaller files however. 
Let me do some more debugging and give you an update.

Thanks,
Suraj

**Comment by efiop** [comment]
We've received a few reports(e.g. https://github.com/iterative/dvc/issues/1522) of strange google-cloud-storage behavior in the past few days, which makes me think that maybe this issue also has a related cause. Could you try upgrading your google-cloud-storage package and see if the issue still occurs? I.e. `pip install --upgrade google-cloud-storage`

**Comment by efiop** [comment]
@suraj-pai Any updates?

**Comment by efiop** [comment]
Closing as stale. Please feel free to reopen.
