### ISSUE TITLE
status: optimize cache validation for large directories

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1526]
Currently, when we are checking status for any directory, we not only check that its `md5.dir` cache file is not corrupted, but we also check for every individual file inside of it, which makes it very slow for repositories with large directories. Need to optimize this by parallelizing and tracking cache directory changes(e.g. if mtime and size of `.dvc/cache/2f` didn't change, we can be pretty sure that no 2f* cache files got corrupted).

**Comment by pared** [comment]
Referenced pull request (#1647) when analysing dir dependencies, will check if whole cache has changed. There is a bit hacky insert on state database (without cache_dir md5). We should consider some changes that would allow us to store cache directory state without inserting empty md5. It seems counterproductive to add new table, especially that, as noted by @efiop, cache data should not be different than any other state data (we analyse size, mtime and inode).

Maybe we should drop NOTNULL constraint on state table?

**Comment by pared** [comment]
Reopening the issue. We noticed that this hack might cause some problems when editing data directory added under DVC control. Today user actually found a way to trigger unexpected behaviour:
https://discordapp.com/channels/485586884165107732/485596304961962003/582962457945833476
I created PR to roll this change back. Ill revisit this issue and try to come up different solution.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/1969
