### ISSUE TITLE
Checkout output is too verbose

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#1527]
Version 0.24.2

```
$ dvc checkout
Checking out '{'scheme': 'local', 'path': '/Users/dmitry/src/dvc_roadmap/tmp/data'}' with cache '447dcba5ce03fae27f3d66b2fe74f76a.dir'.
Linking directory 'data'.
```

It is good to know what exactly was checked out. But having a schema, full path and checksum are too much. JSON format is also not the best output format for human experience (by default case for DVC). The last line `Linking directory 'data'.` also seems not very informative.

How it can look like:
```
$ dvc checkout
Checking out 'data' directory.
```
Could be added: ` from 'local' cache` or ` with checksum 447dcba` or ` with 3 files ` or ` with 3 files 4.5M size` (this on is probably the best if we have this info in dvc files). 

Another alternative: no output (like Git does). It does not seem like a perfecr solution since DVC checkout might take much more time comparing to Git. 

For machines, we can add another option like `--out-json` and generate pure json line by line like:
```
$ dvc checkout --out-json
{'scheme': 'local', 'path': 'data', 'cache': '447dcba5ce03fae27f3d66b2fe74f76a.dir'}
{'scheme': 'local', 'path': 'raw', 'cache': '0309f1c7abd40c828454887215955a.dir'}
```

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/1713
