### ISSUE TITLE
ssh: garbage packet received

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1548]
While `dvc pull`ing from a remote SSH, this error was raised:
```
"Error: failed to download file <filename> to <directory>... Garbage packet received"
```

Here's the Discord conversation for context:
https://discordapp.com/channels/485586884165107732/485596304961962003/539891897443942432

There are [some reports on paramiko's issue tracker](https://github.com/paramiko/paramiko/search?p=1&q=Garbage+packet+received&type=Issues) about users getting the same error.

**Comment by ericmjl** [comment]
I tried a few experiments.

In one `filename.dvc`, I saw the folowing:

```
md5: bd9abdb4aca0502c3fdf35be6d55b9cc
outs:
- cache: true
   md5: e4b726db5394d943747e09baba1ea3d0
   path: filename
```

Because of the "cache" keyword, I thought of changing `cache` to `false`. Upon doing so, this is the terminal output:

```
$ dvc pull -r ssh filename.dvc
Preparing to download data from '<remote_dir>'
Preparing to collect status from <remote_dir>
...
[##############################] 100% Collecting information
[##############################] 100% Analysing status.
```

However, `filename` did not show up in the correct directory.

In the `filename.dvc` file, I then changed back `cache` to `true`. 

```
$ dvc pull -r ssh filename.dvc
...
Error: failed to download '/path/to/e4/b726db5394d943747e09baba1ea3d0' to '/path/to/.dvc/cache/e4/b726db5394d943747e09baba1ea3d0' - Garbage packet received
...
Warning: Cache 'e4b726db5394d943747e09baba1ea3d0' not found. File '{'scheme': 'local', 'path': '/path/to/data/filename'}' won't be created.

**Comment by mroutis** [comment]
@ericmjl , we changed the way `dvc` communicates with the SSH remote, now `dvc` uses SFTP; I hope that it solves the problem, would you mind to confirm?
I couldn't replicate the issue with the latest version :)

**Comment by ericmjl** [comment]
Oh wow, that's amazing! 

Over the next few days, when I get a chance to try it out, I will ping back and let you all know what happened :smile:.

**Comment by ericmjl** [comment]
Just got a chance to try out DVC. New version works like a charm! Thanks for looking into this, @mroutis!

**Comment by ericmjl** [comment]
Oh wait! Actually, I responded too quickly on that.

**Comment by mroutis** [comment]
Dang, @ericmjl , sad to hear that the error still exists; I'm unable to reproduce it, making it really hard to debug :/

I'll leave this issue open for future references.

Thanks for reporting it, @ericmjl , if you find any error or inconvenience, don't hesitate to open an issue or ping us at our Discord server :)

**Comment by ericmjl** [comment]
@mroutis thanks for taking a look at the issue, regardless :)

**Comment by efiop** [comment]
@ericmjl @mroutis Looks like it is a paramiko's bug. There are a bunch of reports already (like this one https://github.com/paramiko/paramiko/issues/395), so there is no reason to keep it opened in our issues. Closing for now, please feel free to reopen.
