### ISSUE TITLE
Persist\tag files from GC

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#155]
We probably need a command to keep a subset of files from GC. For example, I had a previous version of my model (branch model_v1) and now I develop a new one (model_v2).

```
$ git checkout model_v1
$ dvc gc --tag m1 # or dvc gc --persist
$ git checkout model_v2
$ dvc gc --tag m2 # or dvc gc --persist
$ dvc gc --nuke # Remove all cache files (need to be implement) but not persistent.
```

Q: Do we need tags and can we utilize Git tags?

**Comment by efiop** [comment]
Added to 0.11.0 for future consideration.

**Comment by mroutis** [comment]
Is this the same as `gc --all-tags` ? Is it related with #1766 ?

**Comment by mroutis** [comment]
Closed by mistake! My bad

**Comment by efiop** [comment]
@mroutis #1766 mostly.

**Comment by skshetry** [comment]
@efiop @dmpetrov Maybe we can close this since we don't have tags at all now and `gc` has `--all-tags`?

**Comment by efiop** [comment]
We don't have our own tags, but we also don't have any mechanism to persist files from gc. Maybe this will be solved by not removing data sources on gc unless special flag is specified. Would keep this for now.
