### ISSUE TITLE
checkout: consider automatically pulling data from the remote

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1550]
Similar to how `git checkout someremotebranch` automatically creates a local copy. Need to not forget to add a special --no-auto-pull(or smth) flag to disable auto-pull on checkout.

**Comment by efiop** [comment]
This might be used in our post-checkout hook. That being said `dvc pull` seems to do precisely that, so we might just need to replace `dvc checkout` with `dvc pull` in that hook.

**Comment by skshetry** [comment]
Closing as not planned.

**Comment by Jendker** [comment]
Are there any comments on why this is not planned? Is it possible to get this behavior in a different way? For me that sounds like a nice improvement to the hooks.

**Comment by skshetry** [comment]
@Jendker, that's what `dvc pull` does.

**Comment by Jendker** [comment]
Is there a way to set it up in .pre-commit-config.yaml to have pre-checkout run `dvc pull` instead of `dvc checkout`?
