### ISSUE TITLE
repro: support multiple targets

### ISSUE THREAD

**Issue by AlJohri** [iterative/dvc#1554]
`dvc repro` should support multiple targets. the flags will apply to all targets. an example command would be: `dvc repro -f -s stage1.dvc stage2.dvc`

**Comment by yfarjoun** [comment]
I think it does already...I just launched a 

```
dvc repro -s stage1.dvc stage2.dvc 
```
with no problems.

**Comment by efiop** [comment]
@AlJohri @yfarjoun is right, this is already implemented and should work. Did you encounter any problems with it?

**Comment by AlJohri** [comment]
hi thanks! I totally missed to see that this already works. I tried it out and seems to work exactly as intended
