### ISSUE TITLE
repro: continue downstream

### ISSUE THREAD

**Issue by AlJohri** [iterative/dvc#1555]
Add an option `-d | --downstream` to `dvc repro` that starts from some stage X and continues downstream from X.

For example, in a pipeline `a -> b -> c -> d`, running `dvc repro -d b.dvc` would execute `b`, `c`, and `d`.

**Comment by yfarjoun** [comment]
related to #1571

**Comment by efiop** [comment]
For the record: current workaround would be
```
dvc lock a.dvc
dvc repro b
dvc unlock a.dvc
```

**Comment by shcheklein** [comment]
documentation, guys? )

**Comment by efiop** [comment]
@shcheklein linked in the PR: https://github.com/iterative/dvc.org/issues/271

**Comment by efiop** [comment]
@AlJohri This feature has been released in 0.40.1. Please upgrade 🙂 Thanks a lot for all the feedback!
