### ISSUE TITLE
Ask for permission before reformatting state file

### ISSUE THREAD

**Issue by vernt** [iterative/dvc#1557]
After upgrading from 0.22 to 0.24, dvc commands automatically reformatted the state file to version 3. Could it ask for permission before modifying anything? I might want to delay such operations until later.

**Comment by mroutis** [comment]
As far as I know, @vernt , state file version is tight to the `dvc` version; may I ask why would you want to delay it?

**Comment by vernt** [comment]
One reason is that it's slow and I have to wait for it to finish before doing anything. And it might break something. Sometimes I would prefer to say no, downgrade dvc to a previous version, and keep working until I'm ready take the time to upgrade and make sure everything's still okay.

**Comment by efiop** [comment]
There has been a lot of performance optimizations, especially for directories, which should make the process of re-calculating checksums much more bearable. Introducing a prompt might be annoying for other users that don't want to see it, so we don't really see a good way of implementing it. Also, these days our state db format is very stable, so those incidents should happen very rarely. Closing for now. If it gets annoying again, please feel free to reopen :slightly_smiling_face:
