### ISSUE TITLE
remote http: Support for weak ETags, Last-Modified, and Expires

### ISSUE THREAD

**Issue by ghost** [iterative/dvc#1560]
Some public data sets are served only with weak ETags -- It doesn't guarantees a byte-to-byte comparison, but in the worst case scenario, `dvc` wouldn't be able to download the new version if the server considered that the file was "semantically" the same, however, we can use the `Last-Modified` header (if available) as a backup to detect those cases.

DVC should be able to also incorporate the `Expires` header to invalidate the cache.

Although, we would need to add additional content to the [DVC file format](https://dvc.org/doc/user-guide/dvc-file-format)

Maybe adding a section if a file is from a remote (other than local), containing the `checksum`, `last-modified`, and `expires`.

So we can do `output.is_remote`, `output.remote.checksum`, `output.remote.last_modified`, `output.remote.expires`; maybe using `headers` instead of `remote` could be a better idea.

The idea is to do a conditional request using the `If-Modified-Since`, also, we can leverage the `If-None-Match` instead of relying on using a `HEAD` request before (this may not be as straight forward as it sounds, since we need to consider the case when the file being served is the same, so we can checkout it from the cache, in case of being available)

**Comment by efiop** [comment]
Closing as stale.
