### ISSUE TITLE
Consider adding ditaa support to pipeline show --ascii

### ISSUE THREAD

**Issue by emres** [iterative/dvc#1561]
It'd be great if you could add http://ditaa.sourceforge.net/ support to `pipeline show --ascii`. ditaa is a small command-line utility to convert diagrams drawn using ASCII art into proper bitmap graphics. 

In other words, having the ability to easily generate a properly rendered graphical output of a pipeline that can be easily inserted to other documentation systems would be very good. Plus, with a properly rendered graphics file (e.g. PNG), you don't have the risk of breaking formatting, indentation, etc. of ASCII art.

**Comment by efiop** [comment]
Hi @emres ! Thanks for the suggestion! We already have `--dot` option for it, that will create a dot file that you could be rendered with anything you'd like(e.g. plain graphviz, d3, etc) in any format(e.g. png, jpg, etc). Or do you need ditaa specifically?

**Comment by efiop** [comment]
@emres Great point! Added https://github.com/iterative/dvc.org/issues/172 . Thank you for the feedback! :slightly_smiling_face:
