### ISSUE TITLE
Set GOOGLE_APPLICATION_CREDENTIALS environment variable in .dvc/config

### ISSUE THREAD

**Issue by mhham** [iterative/dvc#1562]
Currently, `dvc` (in fact `google.cloud.storage`) needs an environment variable `GOOGLE_APPLICATION_CREDENTIALS` pointing to a JSON file containing credentials to be able to push and pull from a remote GCP.

While this can be set up manually via `export` or in a .bashrc or .zshrc, it would be more flexible to be able to set it in `.dvc/config`, so that different projects can work with different credentials.

**Comment by shcheklein** [comment]
Hi, @mhham ! Sounds like a good feature. Would you be interested in doing a PR? It looks pretty straightforward more or less: 

1. In `dvc/dvc/config.py` add `SECTION_GCP_CREDENTIALPATH= 'credentialpath' somewhere around line 200.
2. In `dvc/dvc/remote/gs.py` , `gs()` function that creates a Client pass the credentials path. Either set it via os.env[GOOGLE_APPLICATION_CREDENTIALS]=`path` or find some other way to pass it. I would probably check that path exists as well, but it depends on how the google python library behaves in case of erros.
3. Add some tests, we can help you.
4. Add some brief mention of this new config option in the docs, again we can help you and point to the right file.

The only question I have here (and @efiop can you give you more insights) is what should be the order - should GOOGLE_APPLICATION_CREDENTIALS still override dvc/config or not. It's quite easy to implement either.

I would great if you can contribute this! :)

**Comment by mhham** [comment]
I'll look into it !

**Comment by efiop** [comment]
Fixed by #1567

**Comment by pared** [comment]
Is this change documented? Or is there any issue for that? I cannot find it.
https://discordapp.com/channels/485586884165107732/485596304961962003/592958184096792576

**Comment by efiop** [comment]
@pared Good catch! Indeed, it is not documented neither can I find an issue for it. The configuration itself is the same as credentialpath in s3 though.

**Comment by efiop** [comment]
@pared added https://github.com/iterative/dvc.org/issues/453 so we don't forget.
