### ISSUE TITLE
checkout: throw a warning if user is trying to do `dvc checkout <branch>`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1563]
Requested by Al on discord. Currently if a user accidentally runs `dvc checkout <branch>` he gets:

```
(3.7.0-dvc) ➜  myrepo git:(ololo) ✗ dvc checkout master                                 
Error: unexpected error - 'master' does not exist.                                      
                                                                                        
Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help! 
```

Let's add a static warning that says something like "Do you mean `git checkout <branch>`?`".

**Comment by tdeboissiere** [comment]
I can have a look at that one

**Comment by efiop** [comment]
That would be amazing @tdeboissiere ! Thank you! :slightly_smiling_face: Please let us know if you need anything.

**Comment by tdeboissiere** [comment]
Sure thing !

The error message occurs during a `Stage.load` call. `Stage.load` can be called with various dvc commands, such as `dvc remove`. This means I need a way to identify what dvc command led to the `Stage.load` call.

The most straightforward way would be to add a keyword argument such as `from_checkout=False` if True, we can then change the error message to suggest `git checkout`.

While that would work, it is not particularly elegant. Thoughts ?
