### ISSUE TITLE
auto git add / commit when running dvc repro

### ISSUE THREAD

**Issue by AlJohri** [iterative/dvc#1576]
would be great to automatically git add/git commit after dvc repro. this may in the future enable something like `dvc repro --all-pipelines --all-branches`

ref discord convo: https://discordapp.com/channels/485586884165107732/485596304961962003/542085672941518929

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/issues/1558

**Comment by jorgeorpinel** [comment]
Maybe if `dvc install` has been run ("full Git integration mode").

**Comment by efiop** [comment]
We now have auto-stage option https://github.com/iterative/dvc/pull/4543 . Doesn't look like there is a lot of demand for comitting part.
