### ISSUE TITLE
Add option to `dvc run` retroactively

### ISSUE THREAD

**Issue by guysmoilov** [iterative/dvc#1586]
When working with dvc, I find this workflow to be very common:

1. I run some command I got from somewhere in the internet, whose outputs I don't know in advance. The simplest example would be a tarball with some structure I only find out about after I extract it, or more interestingly, a complex program which I will actually have to analyze to find out what it creates and where.
2. After running it, I would like to record that run as a dvc stage.
3. I get bummed about running `dvc run` since it forces me to actually re-run the command, instead of reusing the already existing outputs.

`--no-exec` doesn't work, since it records a blank file with no hashes, and I don't want to `dvc repro` if I can avoid it. I suppose I could manually add all the output files and dependencies and hashes, but that would suck.

I would suggest a `--retro` flag to `dvc run`, which will do everything `dvc run` does EXCEPT running the command itself.

If this is not a duplicate, I can get started on a PR.

**Comment by efiop** [comment]
Hi @guysmoilov !

This seems like a case for `dvc commit` command from https://github.com/iterative/dvc/issues/919 . So the workflow would be:

```
$ tar -xvf a.tar.gz
$ dvc run --no-exec -f untar.dvc -o out1 -o out2 -d a.tar.gz tar -xvf a.tar.gz
$ dvc commit untar.dvc # this will fill out all the checksums and will put outputs to cache
```

I'm working on `dvc commit` right now, it is 90% ready, I'll hopefully publish a change for it until the end of the week, maybe earlier.

Thanks,
Ruslan

**Comment by guysmoilov** [comment]
Great, thanks! I would still suggest the retro run as a possible UX improvement, if there's demand for it.

**Comment by efiop** [comment]
@guysmoilov So `--retro` would do both `--no-exec` and `commit` in a single command, right? If so, I agree, it would be useful. How about naming it `--commit` instead?

**Comment by efiop** [comment]
Also, another useful feature in such scenario would be https://github.com/iterative/dvc/issues/931 :)

**Comment by guysmoilov** [comment]
@efiop Right. Regarding the naming conventions, you're the boss, I just suggested the name that reflected my workflow.
I think I would be way too much of a coward to ever use #931 🤣

**Comment by efiop** [comment]
@guysmoilov We are trying hard to listen to our users, so I'm interested in hearing your opinion :slightly_smiling_face: 

I don't think `--auto-outs` would be that scary, if handled with care :slightly_smiling_face: But I agree, it is a bit too implicit.

**Comment by guysmoilov** [comment]
Hi @efiop , just wanted to ask if there's any update? Can I help somehow to release this soon?

I'll explain why this is urgent to me. I'm trying to use DVC for a large-ish NLP task, where each preprocessing stage takes me a whole night to run. Often, when I come in the morning, I find out that I made a slight mistake in the command and e.g. some unrelated files ended up in my cached output folder. I do NOT want to re-run `dvc run` and wait a whole night, and discover that I made another mistake. This is important, because if I was just a normal user, this would be the point where I give up on using DVC completely. I would like to just manually fix the mistake, modify the command in the dvc file, and run `dvc commit` to take a snapshot of the current (fixed) state of my file system, so I can push it and not have to recalculate it later. This may be problematic from a pure reproducibility perspective, but that's less immediately urgent than carrying on with my work.

**Comment by efiop** [comment]
Hi @guysmoilov !

Sorry, forgot to link it https://github.com/iterative/dvc/pull/1601 . There is only one question left to solve https://github.com/iterative/dvc/pull/1601#discussion_r255646527 . If it is very urgent, you could try it out right now. Dev version should be handled with care, of course :)

Thanks,
Ruslan

**Comment by efiop** [comment]
Hi @guysmoilov !

#1601 is merged into the upstream. We will release new version with it soon.

Thanks for the feedback! :slightly_smiling_face:

**Comment by guysmoilov** [comment]
@efiop Thanks buddy, I will try it out ASAP

**Comment by efiop** [comment]
@guysmoilov FYI: 0.28.1 is out :slightly_smiling_face:
