### ISSUE TITLE
Refactoring: replace data value path_info by classes

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#1588]
Manipilating with data values does not seem like a good practice:
```
self.path_info = {"scheme": "hdfs", "user": self.user}
```

It can be replaced by classes:
```
class BasePathInfo(object):
    def __init__(self, path=None):
    ....

class HdfsPathInfo(BasePathInfo):
    def __init__(self, path=None):
    ....

etc...
```

**Comment by efiop** [comment]
For the record: this got a lot worse since dir logic generalization, so we are prioritizing it to start using something like suggested PathInfo, which, when casted to string, would result in url for non-local paths and relpath for local paths.
