### ISSUE TITLE
Output module refactoring: get rid of a dynamically created class names

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#1589]
Code which generates class or methods name does not look appealing, it is dangerous to use and usually can be simplified:
```
self.info = getattr(self.project.cache, self.scheme).save(self.path_info)
```

It looks like `Cache` class needs to be redesigned by separating `CacheBase`, `CacheGS`, `CacheS3` etc.

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/issues/1527

**Comment by efiop** [comment]
Closing as stale.
