### ISSUE TITLE
remote ssh: Ask password by default if user don't provide any password

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1595]

**Comment by efiop** [comment]
But what if his host keys are enough? ssh CLI is able to detect that you actually need a password and will ask you about it, but I'm not aware how you can do that with paramiko.

**Comment by mroutis** [comment]
Sorry, @efiop, forgot to put a description!

I saw your comment on https://github.com/iterative/dvc/issues/1520#issuecomment-456406696

Although, I think we can achieve this by changing the `self.ask_password` attribute to a function `self.should_ask_for_password`:

```python
    def should_ask_for_password(self):
        from paramiko.dsskey import DSSKey
        from paramiko.ecdsakey import ECDSAKey
        from paramiko.ed25519key import Ed25519Key
        from paramiko.rsakey import RSAKey
        from paramiko.ssh_exception import (
            SSHException,
            PasswordRequiredException,
        )

        if self.password:
            return False

        if not self.keyfile:
            return True

        for pkey in (RSAKey, DSSKey, ECDSAKey, Ed25519Key):
            try:
                key = pkey.from_private_key_file(self.keyfile, self.password)
            except PasswordRequiredException:
                return True
            except SSHException:
                continue

        return False
```

**Comment by mroutis** [comment]
Also, we need to address this UI issue:
```
Preparing to upload data to 'ssh://root@localhost:1234/tmp/storage'
Preparing to collect status from ssh://root@localhost:1234/tmp/storage
[#########                     ] 30% Collecting informationEnter a private key passphrase or a password for host 'localhost' port '1234' user 'root':
```

**Comment by efiop** [comment]
Oh, didn't know there is a PasswordRequiredException! Nice!

The UI issue is from our logger RFC :wink:  Previously we've been checking if we are in the middle of progress bar :slightly_smiling_face:

**Comment by mroutis** [comment]
Thanks, @efiop , will diff to bring it back :)

**Comment by mroutis** [comment]
Oh, got it:

```python
        msg = '{}:\n'.format(msg)

        if not progress.is_finished:
            msg = u'\n' + msg
```

**Comment by mroutis** [comment]
There was an attempt to implement this interaction on PR #1596, but there are some unknowns that I couldn't address.

Explicit `ask_password` works as expected and covers all the use cases, so I'm closing this issue.
