### ISSUE TITLE
remote: ssh: don't evaluate the keyfile path when setting it in the config

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1608]
E.g. running

```
dvc remote modify myremote keyfile ~/.ssh/id_rsa
```

will result in `/home/user/.ssh/id_rsa` being written to `.dvc/config`, which is wrong and might lead to confusion https://discuss.dvc.org/t/dvc-pull-fails-without-sudo/114/7 .

**Comment by mroutis** [comment]
@efiop , path expansion is happening on the shell, you need to wrap it on quotes if you want to prevent this behavior (e.g. `dvc remote modify remote keyfile "~/.ssh/id_rsa"`)

**Comment by mroutis** [comment]
We can remove the `/home/$USER` section on the path and replace it with `~`.

**Comment by efiop** [comment]
@mroutis I don't think that is a good idea, we will not be able to distinguish between cases where it is intended and where it is not. Great point about shell expansion though! So this is not an issue after all.
