### ISSUE TITLE
Repro is broken on Mac (reflinks?)

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1623]
Three tests are failing. For example:

```
FAIL: test (tests.test_repro.TestReproChangedDirData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ivan/Projects/dvc/tests/test_repro.py", line 684, in test
    self.assertEqual(len(stages), 0)
AssertionError: 1 != 0
```
Do we run tests on Mac, or at least a system with reflinks?

**Comment by efiop** [comment]
Can confirm a few tests failing. We do run tests on Mac, but it turns out that we've been using an older xcode version that doesn't have reflinks enabled. Will add a newer xcode version to our build matrix. Thanks!

**Comment by shcheklein** [comment]
thanks, @efiop !

**Comment by efiop** [comment]
Fixed in https://github.com/iterative/dvc/commit/36510548a599b422f7152a25b27f7922f7977e2f , tested by https://github.com/iterative/dvc/pull/1625
