### ISSUE TITLE
config: option for `--jobs` value

### ISSUE THREAD

**Issue by andrethrill** [iterative/dvc#1626]
Several DVC commands have a `--jobs` option that has default values (e.g, https://dvc.org/doc/commands-reference/gc).

Afaik there is no way to change the default value. Having the option to change it through `dvc config` would be useful.

Can you consider adding it?

Thanks

**Comment by efiop** [comment]
Hi @andrethrill !

Currently, most, if not all, of those commands are those that are related somehow to remotes and use that --jobs option only to set a number of connections. Different remote types have different default values for --jobs, so it seems like it would be a good fit to start with adding `jobs` configuration option for separate remotes. We don't currently do anything in parallel within the core dvc (we will soon though :wink: ), but when we will do that, we could add `dvc config core.jobs` options for that, so it should fit nicely. I've added this to our todo list. Thanks for the feedback! :slightly_smiling_face:

**Comment by andrethrill** [comment]
Thanks for the clarification @efiop !

Just to be sure: so, at the moment, when I garbage collect the local cache only, it is a single thread job. Correct?

**Comment by efiop** [comment]
@andrethrill Yes, correct.

**Comment by efiop** [comment]
We'll add this option when additing something that uses it. Closing for now.

**Comment by pared** [comment]
Fixed in https://github.com/iterative/dvc/issues/4504

**Comment by pared** [comment]
Reopening due to https://github.com/iterative/dvc/issues/5647
