### ISSUE TITLE
hdfs: Support for WebHDFS

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1629]
Currently we require full hadoop access in order to be able to perform `copy` operation that is needed for external deps/outs/cache scenarios. But for simple push/pull/fetch/status we don't need that operation and can use strictly WebHDFS.

**Comment by efiop** [comment]
Note: `hadoop fs cp` is actually copying through the local machine, so it is the same as we would've downloaded the file and uploaded it back. So we can stop using hadoop cli only because of that.

**Comment by efiop** [comment]
Also, hdfs is extremely slow right now:
```
============================ slowest test durations ============================
558.38s call     tests/func/test_repro.py::TestReproExternalHDFS::test
196.74s call     tests/func/test_data_cloud.py::TestRemoteHDFSCLI::test
189.08s call     tests/func/test_data_cloud.py::TestRemoteHDFS::test
82.46s call     tests/func/test_repro.py::TestReproExternalS3::test
68.60s call     tests/func/test_repro.py::TestReproExternalSSH::test
43.70s call     tests/func/test_repro.py::TestReproExternalGS::test
36.58s call     tests/func/test_api.py::test_open[HDFS]
23.83s call     tests/func/test_install.py::TestInstall::test_should_post_checkout_hook_checkout
19.95s call     tests/func/test_install.py::TestInstall::test_should_pre_push_hook_push
17.56s call     tests/func/test_data_cloud.py::TestCompatRemoteS3CLI::test
11.58s call     tests/func/test_data_cloud.py::TestRemoteS3CLI::test
8.91s call     tests/func/test_data_cloud.py::TestRemoteGSCLI::test
8.65s call     tests/func/test_data_cloud.py::TestCompatRemoteGSCLI::test
8.63s call     tests/func/test_data_cloud.py::TestRemoteSSHCLI::test
8.34s call     tests/func/test_s3.py::test_copy_multipart_preserve_etag
7.76s call     tests/func/test_metrics.py::TestMetricsCLI::test
7.71s call     tests/func/test_metrics.py::TestMetrics::test_show
7.54s call     tests/func/test_data_cloud.py::TestRemoteS3::test
7.30s call     tests/func/test_data_cloud.py::TestRemoteGS::test
6.54s call     tests/func/test_data_cloud.py::TestRemoteSSH::test
6.51s call     tests/func/test_data_cloud.py::TestCompatRemoteLOCALCLI::test
6.50s call     tests/func/test_data_cloud.py::TestRemoteAZURECLI::test
```
https://api.travis-ci.com/v3/job/204722795/log.txt

Switching to testing it on cron and releases only.

**Comment by efiop** [comment]
For the record: we've switched to pyarrow which is much faster. Having WebHDFS support would be nice too, but since we support full blown HDFS with pyarrow, it might no longer be necessary.

**Comment by dmpetrov** [comment]
@efiop and @mroutis if there are not requests from users we should just close it. Did we have any during this time?

**Comment by shcheklein** [comment]
Also we don't support external anything stuff on HDFS. So, it can be closed. And we should finally remove mentions of HDFS for external* in the docs.

**Comment by efiop** [comment]
@dmpetrov @shcheklein How about we keep support for external deps? That way we will still support `import-url` and `dvc run -d hdfs://` without any issues (for deps checksum collisions don't matter that much), and will get rid of dangerous external outputs and will get rid of `hdfs CLI` usage.

**Comment by shcheklein** [comment]
I would argue that even `-d` support would require at least explaining the possible edge case (something you expect running does not actually run). Better to mention that use a separate custom stage with your own logic to detect remote changes.

**Comment by dmpetrov** [comment]
`-d` - makes sense. And some companies use DVC in that way (OK - is one example). So, closing this one (WebHDFS).

**Comment by dmpetrov** [comment]
Re `-d`... I mean, now people use HDFS as a remote. We can eventually implement `-d` (it is not supported now, right?). Anyway, these WebHDFS methods are not relevant for any of these cases and we can close it.

**Comment by shcheklein** [comment]
My bad, the initial ticket is about simplifying regular remote operations, so please disregard my comments about external* stuff :)

**Comment by shcheklein** [comment]
if we can drop external* stuff support can webhdfs simplify dependencies/speedup things @efiop @mroutis ?

**Comment by efiop** [comment]
@shcheklein Not really, webhdfs is a http-based protocol, we don't need to support it in hdfs remote. This ticket was created before pyarrow, so it is no longer relevant, except for the fact that we still use CLI to get hdfs checksums, which will be resolved by removing the support for external stuff. So let's keep this closed.
