### ISSUE TITLE
Metrics show reads from cache even if file exists in workspace

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1633]
It's not necessarily a bug, but looks like it would be considered as an unexpected behavior:

```
dvc run -m metrics.txt "echo 1 > metrics.txt"
dvc metrics show
    metrics.txt: 1
dvc unprotect metrics.txt.dvc
echo 2 > metrics.txt
dvc metrics show
    metrics.txt: 1
```

**Comment by efiop** [comment]
I think the current behaviour is suitable, with one major exception: we should notify user that he has unsaved changes and refuse to show metris until everything is saved. This is especially relevant since `dvc metrics` might walk branches/tags.

**Comment by shcheklein** [comment]
Considering the `dvc commit` logic we should always show existing uncommitted value. It's hard to compare the iteration before committing it otherwise. I think we can show it in addition to what we have. For example:

```
*:
    metrics.txt:1
master:
    metrics.txt:1
```

We can pick some other name instead of * to identify working space.

**Comment by shcheklein** [comment]
Another thing to think about is how will `dvc repro -m --no-commit` work in this case. It looks like `dvc repro -m` won't have any meaning in this scenario.

**Comment by shcheklein** [comment]
@efiop I this one is resolved now?

**Comment by efiop** [comment]
@shcheklein Not yet.
