### ISSUE TITLE
dvc: adding external file through a symlink to a directory

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1648]
https://discordapp.com/channels/485586884165107732/485596304961962003/548151166706647064

```
#!/bin/bash

mkdir dvc_example
cd dvc_example

# Create data dir
mkdir data
echo "data" >> data/data_file

mkdir my_repo
cd my_repo
ln -s ../data .

git init
dvc init

dvc add -v data/data_file

```

**Comment by mroutis** [comment]
@efiop , is this a bug or a feature request?

**Comment by efiop** [comment]
@mroutis sorry, forgot to add a label. It is a bug.

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/issues/774

**Comment by alexandre-rouxel** [comment]
I would like to add an external directory defined by a symlink. But it seems it is not supported :
dvc add --external link_to_dir

It will allow abstracting the local dir where I put my data (raid). The other contributor to the project may won't have raid disk.
What is the best

**Comment by efiop** [comment]
@alexandre-rouxel We don't recommend using `--external`. Seems like you are looking for straight-to-cache scenario https://github.com/iterative/dvc/issues/4520 , we are currentry working on it in a linked PR. For now the proper way to do it is to copy it to your dvc project and `dvc add dir` it there.
