### ISSUE TITLE
dvc add ignore unprotected files that have not been modified

### ISSUE THREAD

**Issue by rmcavoy** [iterative/dvc#1655]
DVC version 0.29.0 installed via pip on Linux

Following the sequence of commands
dvc unprotect data.dat
(modify data.dat)
dvc add data.dat

Correctly replaces dvc.dat with the correct kind of file link
but
dvc unprotect data.dat
(not modifying)
dvc add data.dat

Causes add to skip data.dat because it is already cached and leaves the file on disk without linking. Presumably the ideal behavior is to have dvc add check what kind of link the cache should use and update the file to that link even if the file was not modified. This way modified and unmodified data have the same behavior.

Currently the workaround is to rm the data file and checkout which is somewhat awkward.

**Comment by efiop** [comment]
Looks like it is a side effect of https://github.com/iterative/dvc/blob/0.29.0/dvc/stage.py#L423 . We should probably call `save()` on that stage if we see that it is already cached, just to ensure that all the cache is optimized.

**Comment by rmcavoy** [comment]
@efiop I am having problems with the work around of rm'ing the file and checking it out. If I have more than one such file, "dvc checkout" will only checkout file1.dat: and then quit with an error message "Error: unexpected error - [errno 1] Operation not permitted: file2.dat". If I call dvc checkout n'times where n is the number of files I can get all of them but this is very very tedious.

**Comment by efiop** [comment]
@rmcavoy So sorry for the delay! Notification got lost in the flow :slightly_frowning_face: . Does that issue still persist?

**Comment by efiop** [comment]
Closed accidentally.

**Comment by efiop** [comment]
@rmcavoy Fix for this has been released in 0.40.1. Please feel free to upgrade 🙂
