### ISSUE TITLE
Remove or change directory collection security prompt in GC

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1656]
To be precise, this one, in the `repo/__init__.py`:

```python
   logger.warning(
                    "Output '{}'({}) is missing version "
                    "info. Cache for it will not be collected. "
                    "Use dvc repro to get your pipeline up to "
                    "date.".format(out, out.stage)
```

Some context on the second prompt is here:

https://github.com/iterative/dvc/pull/1644#discussion_r258804861

Since we introduced the `--no-commit` mode for `dvc repro` and `dvc run` and it will become the default in 1.0, the situation when there is a directory in the workspace, a pointer to this directory is saved in DVC file, but the directory itself is not cached yet will be quite common. Our current `dvc gc` implementation will show a prompt and a warning, which is misleading.

**Suggestions:**

1. Check the workspace. Do not show this prompt if the directory in cache OR workspace.
2. Remove this prompt. Even w/o this issue with `--no-commit` it feels like this should not be a prompt and more like assert or cache is corrupted notification.
3. It's another reason to think more about non-symmetrical nature of `dvc commit` and `--no-commit` modes. If for example we made `--no-commit` that does not touch DVC files there would be no problem in this situation (not sure if there are any other possible similar edge cases except this `--no-commit` one)

**Comment by dberenbaum** [comment]
Since `--no-commit` mode was not made default, I don't think this issue is needed except maybe for rare edge cases. Closing for now. Feel free to reopen if I missed something.
