### ISSUE TITLE
Support for remote metrics files

### ISSUE THREAD

**Issue by PeterFogh** [iterative/dvc#1664]
Hi. First of all, thanks for your awesome tool.

I wish that the DVC metric feature supports metric files on remote servers.

An example would be: First we define a remote metric file by the command `dvc run -m remote://remote_server/metric.json python model_score.py` and then we can print that remote metric file using `dvc metrics show`.

Currently, DVC just raises an AssertionError when showing remote metrics. I wish that DVC just showed the content of the remote metric file like it would do if the file was stored locally.

Note that, this feature request (like #1654 ) concerns the general request that DVC should the same features for its remote files as it has for its local files.

**Comment by efiop** [comment]
Closing as stale. Will likely get revisited during https://github.com/iterative/dvc/issues/3920 research.
