### ISSUE TITLE
Can't push data on Windows machine

### ISSUE THREAD

**Issue by richardxy** [iterative/dvc#1697]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

I'm running DVC version 0.30.1 on Windows 10. DVC was installed via binary exe file. 

I've run "pip install google.cloud.storage" and "pip install dvc[all]", but still can't push data to remote Google Could Storage bucket. 

The exception message is:

> Error: failed to push data to the cloud - URL 'gs://cylera-data-science/device_port_for_device_classification' is supported but requires these missing dependencies: [u'google.cloud.storage']. If you have installed dvc using pip, choose one of these options to proceed:

> 
>     1) Install specific missing dependencies:
>         pip install google.cloud.storage
>     2) Install dvc package that includes those missing dependencies:
>         pip install dvc[gs]
>     3) Install dvc package with all possible dependencies included:
>         pip install dvc[all]
> 

> If you have installed dvc from a binary package and you are still seeing this message, please report it to us using https://github.com/iterative/dvc/issues. Thank you!

**Comment by richardxy** [comment]
Problem solved by uninstalling DVC installed via binary.

**Comment by mroutis** [comment]
@richardxy , I'll leave this open, as we need to check "binary" compatibility with external packages (`pip install ...`). Thanks for the report!

**Comment by efiop** [comment]
@mroutis Binary is not compatible with anything since it comes as an all-in-one package. Looks like pyinstaller was not able to include gcloud in our package. Will take a look.

**Comment by mroutis** [comment]
Thanks, @efiop !

**Comment by efiop** [comment]
Can confirm this bug also on linux when using binary packages.

**Comment by efiop** [comment]
Ok, turns out there was a bug in one of the dependencies, which is why pyinstaller was not able to collect it properly. Fixed and released in 0.34.1. Thank you so much for the feedback @richardxy ! :slightly_smiling_face:
