### ISSUE TITLE
No Such File Error if using ssh remote on windows

### ISSUE THREAD

**Issue by Qsi1984** [iterative/dvc#1701]
Hi

Since the Update to Version 0.30 I can't use my ssh remote anymore.
dvc pull and dvc status -c gives me a "No Such File"-Error. I was able to find the problem in the new ssh-remote-implementation of version 0.30:
https://github.com/iterative/dvc/blob/master/dvc/remote/ssh/connection.py#L131
This line of Code constructs a path to use on the ssh-server using os.path.join which is platform-dependent. 
The created path looks like this: /opt/dir/hdd/myfolder/dvcremote\9b which is not a valid unix-path. 

It would be great if this issue gets fixed. I patched my local connection.py-file to be able to work again.

Thanks!

**Comment by pared** [comment]
Hi @Qsi1984! That definitely seems like a bug, thanks for sharing!

**Comment by efiop** [comment]
We don't currently test ssh remote on windows in our CI, so that is why we didn't catch it right away. We definitely should've used posixpath there, as we do in other parts of that driver.

**Comment by efiop** [comment]
Also, @Qsi1984 if you are so deep in the code already and fixed it for yourself, would you mind contributing a PR too? 🙂

**Comment by Qsi1984** [comment]
I sadly won't have time to setup a dev-environment for dvc the next couple days.
But in my opinion the change is just to replace the mentioned code-line with
`            path = posixpath.join(directory, entry.filename)
`

**Comment by shcheklein** [comment]
@Qsi1984 btw, I think there is no need to setup a dev env for that, just open the file on github, click an edit button on the top and will create a fork and PR for you. No need even to do a clone in such a simple case.

**Comment by Qsi1984** [comment]
Ah didn’t know that this is enabled. Done.

**Comment by shcheklein** [comment]
@Qsi1984 yep, Github gives a super simple interface sometimes :) Thanks a lot, we'll review and merge asap!

**Comment by efiop** [comment]
Thank you @Qsi1984 ! I've created https://github.com/iterative/dvc/issues/1704 to track progress on enabling ssh test on windows, so that we catch such bugs in time.

**Comment by Qsi1984** [comment]
Can someone reopen this issue? It still doesn't work on windows (See: https://discuss.dvc.org/t/ssh-login-failed-after-upgrading-version-0-24-3-0-30-1/127/6?u=qsi)
The problem is in upload/download of connection.py (eg. here: https://github.com/iterative/dvc/blob/fdf2b1c01635bbe30f5c3a0bbca0bfa135d2ecb5/dvc/remote/ssh/connection.py#L151) the use of posixpath and os.path is mixed up. In the mentioned code-line dest is a windows-style path if os is windows, therefore dirname of posixpath returns none.

**Comment by efiop** [comment]
Fixed by #1725
