### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by siddygups** [iterative/dvc#1711]
super minor typo:

$dvc repro --help
 -c CWD, --cwd CWD     Directory within your repo to **reroduce** from.

dvc --version
0.30.1

**Comment by shcheklein** [comment]
@siddygups hi! thanks! could create a PR? You don't need to setup any environment for this - just open the https://github.com/iterative/dvc/blob/master/dvc/command/repro.py#L62 and click an edit button at the very top. You can edit right in-place and then create a PR :)

**Comment by siddygups** [comment]
sorry I missed this - lemme know if there is something else I can look into

**Comment by shcheklein** [comment]
np! Almost any of these should be easy enough https://github.com/iterative/dvc/labels/good%20first%20issue. Would be really great if could contribute one of them. Any help is great! :)
