### ISSUE TITLE
status: dependency on local cache

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1715]
**version**: 0.30.1

----

A [user on discord](https://discordapp.com/channels/485586884165107732/485596304961962003/555191347397525506) asked for an implementation of status to check whether a remote is synced without having any local cache.

Here's a reproduction script:

```bash
# Create disposable test directory
mkdir example
cd example

# Configure dvc with a local SSH remote
dvc init --no-scm
dvc remote add myssh ssh://localhost/tmp/remote-storage
dvc remote modify myssh ask_password true

# Create a the remote storage folder
mkdir /tmp/remote-storage

# Add some data to the cache
echo "hello" > hello
dvc add hello

# Run your status
dvc status --remote myssh
#
#   new: hello

# Delete stage file to test if status relies on stages
rm hello.dvc
dvc status --remote myssh
#
#   Pipeline is up to date. Nothing to reproduce.

# Create the stage file again but now delete the cache
dvc add hello
rm -rf .dvc/cache/
dvc status --remote myssh
#
#   Pipeline is up to date. Nothing to reproduce.
```

---

At first glance, it appears to be a bug / unexpected behavior, because requiring a `dvc pull` will always result on having a clean `dvc status --remote`.

**Comment by mroutis** [comment]
@efiop , @dmpetrov : What are your thoughts on this one? is it a bug or is there a reason behind this?

**Comment by efiop** [comment]
@mroutis This is actually a direct result of #1677 . Fix for it is coming in https://github.com/iterative/dvc/pull/1690 by @pared .
