### ISSUE TITLE
updater: previous API is stale at 0.23.0 version

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1717]
We changed APIs in this commit: https://github.com/iterative/dvc/commit/f3171e1d47f75a52c64f604de0f5dcb7f1aeebe7#diff-46f89beba79f7dd721424b0f4ebb4349

Users that are running versions previous to `0.23.0` will not know about newer versions (like `0.30.1`).

I already sent an announcement on Discord, however, it would be great to let them know through the CLI.

**Comment by shcheklein** [comment]
I've update the latest lambda to 0.30.1 manually in the old AWS account.
