### ISSUE TITLE
Add description for apt package

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1718]
As described by user:
https://discordapp.com/channels/485586884165107732/485598848111083531/555327757475905546

We should write some description for our apt package.

**Comment by efiop** [comment]
For the record: Just need to use `--description` in our fpm command in https://github.com/iterative/dvc/blob/master/scripts/build_posix.sh .

**Comment by kurianbenoy** [comment]
Can I work on this?

**Comment by kurianbenoy** [comment]
@efiop can you tell where to make the change? And as the description is the following okay:
`Data & models versioning for ML projects, make them shareable and reproducible`

> For the record: Just need to use `--description` in our fpm command in https://github.com/iterative/dvc/blob/master/scripts/build_posix.sh .

**Comment by shcheklein** [comment]
@kurianbenoy let's do something like:

`Data Version Control - datasets, models, and experiments versioning for ML or data science projects`

I think you need to add `--description` to somewhere around lines 50-51 to the script @efiop shared the link to.

**Comment by efiop** [comment]
@kurianbenoy Here https://github.com/iterative/dvc/blob/master/scripts/build_posix.sh#L46 . To the `fpm` command.
