### ISSUE TITLE
Error: not a dvc repository (checked up to mount point ...)

### ISSUE THREAD

**Issue by denfromufa** [iterative/dvc#1723]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

`pip install git+https://github.com/iterative/dvc -U --user`

Following tutorial:

https://dvc.org/doc/get-started/configure

`dvc remote add -d dvc_remote /data/gs/hp/dvc_data`

Error: not a dvc repository (checked up to mount point '/data/gs')

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

```
dvc --version
0.31.1
```

'Linux-3.10.0-693.el7.ppc64le-ppc64le-with-redhat-7.4-Maipo'

**Comment by pared** [comment]
Hi @denfromufa did you run `dvc init` beforehand?

**Comment by denfromufa** [comment]
My bad: I was in the parent directory, not the directory for dvc repo. But the error message may be improved I guess.

**Comment by denfromufa** [comment]
`git init` was done properly

**Comment by efiop** [comment]
@denfromufa Glad it works now :) How do you think we could improve that error message, though?

**Comment by denfromufa** [comment]
The current directory is not dvc directory. I was thinking that the remote is not dvc directory and hence got confused. Also because of testing I used the same local disk mount for both.

**Comment by efiop** [comment]
@denfromufa I see. How about something like `Error: current directory is not a dvc repository (checked up to mount point '/data/gs')`? What do you think?

**Comment by denfromufa** [comment]
Thanks for quick response, I hope this is an improvement

**Comment by efiop** [comment]
@denfromufa Thanks for the feedback! :slightly_smiling_face:  We'll release a new version with the updated msg soon.
