### ISSUE TITLE
progress: use `logger.info()` instead of `print()`

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1724]
Progress bar writes directly to `sys.stdout`, logger does not.
Need to make progress bar use `logger.info()` instead of `print()`

**Comment by J0** [comment]
@pared can I take this issue?

**Comment by pared** [comment]
@J0 sure, if it is unassigned feel free to go, thanks for notice :)

**Comment by pared** [comment]
I cannot assign you, @efiop can you do that?

**Comment by efiop** [comment]
@pared Unfortunately I can't :slightly_frowning_face:  Only members can be assigned to a task.

**Comment by shcheklein** [comment]
@J0 I've sent you a collaborator invite. After that we will be able to assign ticket to you. Most likely, you will be able to take them on your own :).

**Comment by J0** [comment]
@efiop I would like to trouble you for help/advice on this issue. I was under the impression that naively changing the [print static method](https://github.com/iterative/dvc/blob/master/dvc/progress.py) in `progress.py` 
from

```
@staticmethod
def print(*args, **kwargs):
    import dvc.logger as logger
    if logger.is_quiet():
        return

    print(*args, **kwargs)
```
to

```    
@staticmethod
def print(*args, **kwargs):
    import dvc.logger as logger

    if logger.is_quiet():
        return
    logger.info(*args, **kwargs)
```
would solve the issue but unfortunately, this causes most of the tests to break. Any idea what might be going on and any suggestions on how I should proceed?

**Comment by mroutis** [comment]
@J0 , I'm currently working on this issue #1753 that will refactor how DVC uses `logging`, and then, I'll tackle #1797, rewriting how tests with logging work.

Would you mind waiting a little bit until those two issues are closed?

Thanks for your interest in contributing, tho, that's awesome :tada: !

**Comment by J0** [comment]
Sure! I'll go work on the other issues I've been assigned to first

**Comment by efiop** [comment]
This is no longer needed. Proper solution will be introduced in https://github.com/iterative/dvc/issues/2148
