### ISSUE TITLE
dvc status fails when printing list of strings

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#1727]
With commit ac27b4076a2216fe78d5c33f37718edde27a9d00 this code was removed from status command:
```
        if isinstance(status, str):
            logger.info("{}{}".format(ind, status))
            return
```
It's actually needed since a list is printed by sending each element back into `_show`:

```
        if isinstance(status, list):
            for entry in status:
                self._show(entry, indent)
            return
```

Now the command fails on asserting that status is not a dict.

**Comment by efiop** [comment]
@prihoda Great catch! Removed it since i didn't notice it being used and covered by any test :slightly_frowning_face: Reverted that commit for now. Really need to work on our test coverage :(

**Comment by efiop** [comment]
Will leave it open until the test is merged.

**Comment by efiop** [comment]
Closing as stale.
