### ISSUE TITLE
scripts: update completion scripts for bash  and zsh

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1732]
Files are located in: https://github.com/iterative/dvc/tree/master/scripts/completion

There are some missing flags and maybe some commands that weren't contemplated when the scripts were written.

Any other improvements are more than welcome :)

**Comment by bayethiernodiop** [comment]
gonna try to work on this in my spare time(little busy though)

**Comment by shcheklein** [comment]
@bayethiernodiop that would be great! @mroutis do we want to reassign it then?

**Comment by mroutis** [comment]
@bayethiernodiop , sorry I didn't see your message before!
I already worked on a patch for it, but it would be great if you can review my pull request :) !

There are some things that we are missing on `zsh`, tho, like completion for sub-sub-commands (e.g. `dvc remote add <tab>` or `dvc cache dir <tab>`)

https://github.com/iterative/dvc/pull/1764

Please, @bayethiernodiop , feel free to leave any comments!

**Comment by bayethiernodiop** [comment]
happy to hear that. Nice work @mroutis i really wanted that feature.
