### ISSUE TITLE
`python -m tests` do not execute tests as contribution guide says.

### ISSUE THREAD

**Issue by PeterFogh** [iterative/dvc#1736]
**Please provide information about your setup**
dvc --version = 0.32.1+db5a0 and local and remote server uses ubuntu 18.04.2.

**Problem**
It's my first time contributing to DVC - or any other open source for that matter. I'm trying to run the test as described in your contribution guide https://dvc.org/doc/user-guide/contributing#running-tests. However, the command `python -m tests` do not execute the test as the guide says it will - it just outputted:
```
Name                           Stmts   Miss  Cover
--------------------------------------------------
... (like "dvc/utils/fs.py      38      5    87%")
--------------------------------------------------
TOTAL                           5263   2424    54%

===Flaky Test Report=== 

===End Flaky Test Report===
---------------------------------------------------------------------- 
Ran 0 tests in 5.499s

OK
```

To run the tests, I needed to run `python -m tests --exe`.
Am I during something wrong or should the guide be updated?

**Comment by efiop** [comment]
@PeterFogh Hm, that is strange. Are you running them from the root of dvc project?

**Comment by PeterFogh** [comment]
@efiop, I'm running them from the root of the repository folder, so yaah the root and not from `/dvc/dvc/`

I'm using Conda as the environment, but most packages are installed with PyPi  - nose==1.3.7

Additionnaly, this `--exe` creates alot of `.coverage.[PC_NAME]` files - is that to be expected?

**Comment by efiop** [comment]
@PeterFogh Hm, could you please show `ls -la tests/` output? Maybe there is something weird about the mount point that you are using and it has weird permissions on it (e.g. +x for some reason).

> Additionnaly, this --exe creates alot of .coverage.[PC_NAME] files - is that to be expected?

Yes, that is expected. Those are coverage reports that will get combined in the end, after the testing is done, and all the .coverage* will be removed.

**Comment by PeterFogh** [comment]
Here you go - the output of ` ls -la tests/` [ls_test.txt](https://github.com/iterative/dvc/files/2975154/ls_test.txt)

> Yes, that is expected. Those are coverage reports that will get combined in the end, after the testing is done, and all the .coverage* will be removed.

Okay, thanks for the explanation :)

**Comment by efiop** [comment]
@PeterFogh 

```
-rwxrwxrwx 1 root root  3567 Mar 16 09:47 basic_env.py
```

Are you running everything from root? Or did you just mount that partition as root and then did `chmod 0777 -R` on it? So that is the problem with your setup and that is why `--exe` is needed in your case, as it allows running tests that have exec permissions set on them.

**Comment by PeterFogh** [comment]
ohh.. Okay, I'm running everthing a root, as I'm using Windows Subsystem for Linux (WSL).
I guess that I just have to continue using `--exe`?

**Comment by efiop** [comment]
@PeterFogh I see. I guess it is not the last time we see this problem then :slightly_smiling_face: Would you be so kind to add `--exe` to `tests/__main__.py` with a comment about it, please? :slightly_smiling_face:

**Comment by PeterFogh** [comment]
@efiop, Okay, "jobs done" - #1738

I'm just e bit trubbeled by the argument documentation:
"
 --exe
Look for tests in python modules that are executable.
**Normal behavior is to exclude executable modules,
since they may not be import-safe [NOSE_INCLUDE_EXE]**
"
Do you still think adding the `--exe` as defult is a good idea?

**Comment by efiop** [comment]
@PeterFogh Thank you! :slightly_smiling_face: 

Usually, I would rather not add this flag, since it is related to a particular incorrect workspace setup. But since it is done that way in WLS, which is something that people use, then rather than creating obstacles for new contributors in the future, we might as well just add this flag, especially since we don't have any not import-safe tests anyway.
