### ISSUE TITLE
pipeline: show: dot: check that user doesn't accidentally write to dvc file

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1743]
Two users on discord https://discordapp.com/channels/485586884165107732/485586884165107734/557205072971431957 accidentally corrupted their dvc files by using `dvc pipeline show --dot my.dvc`.

**Comment by mroutis** [comment]
@efiop , should it be better to actually `show` (print to stdout) the content instead of writing it to a file?

It can work like `dvc pipeline show --dot my.dvc > my.dot`

**Comment by efiop** [comment]
@mroutis Agreed :)

**Comment by efiop** [comment]
Fixed by #2035
