### ISSUE TITLE
metrics: show: investigate error

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1746]
https://discordapp.com/channels/485586884165107732/485586884165107734/557279967465963540

**Comment by ei-grad** [comment]
would be fixed with #1709 probably

**Comment by pared** [comment]
Should we close that one?

**Comment by efiop** [comment]
Yep, fixed with #1709 . Thanks for the heads up, guys!

**Comment by efiop** [comment]
Or, let me make sure by confirming with the user.

**Comment by efiop** [comment]
Will release new dvc version today and will notify user to try it out. Leaving open for now.
