### ISSUE TITLE
cache: dir option is not working correctly

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1747]
version: `0.32.1`

-----

It raises an error when using the command:
```bash
❯ dvc cache dir
Error: unexpected error - 'NoneType' object has no attribute 'startswith'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

**Comment by mroutis** [comment]
Is there any reason to have the `dir` subcommand after `cache`?

**Comment by shcheklein** [comment]
If understood the essence of the question correctly, the reason for this is that `cache` has multiple configuration options - dir, type, etc. For now we exposed only one through this wrapper, but later we may decide to support `dvc cache type` for example.
