### ISSUE TITLE
Stage.stages filter_dirs performance

### ISSUE THREAD

**Issue by ei-grad** [iterative/dvc#1751]
There is a problem with filter_dirs implementation, it actually could make the things slower if there are many outs.

```python
def filter_dirs(dname, root=root):
    path = os.path.join(root, dname)
    if path in (self.dvc_dir, self.scm.dir):
        return False
    for out in outs:
        if path == os.path.normpath(out) or path.startswith(out):
	    return False
    return True
```
Running it in a loop over the list of dirs results in the computational complexity of `O(num_dirs * num_outs)` and it could be reduced by using `set` to store outs and checking that it contains path or any of its parents.

**Comment by skshetry** [comment]
@efiop, close this? I guess, this is no longer an issue, as we do use a set, and the codebase is quite different:
https://github.com/iterative/dvc/blob/59105ec639c3acdba09f284fee80b0866bb79497/dvc/repo/__init__.py#L548

**Comment by efiop** [comment]
@skshetry Good point! Closing.
