### ISSUE TITLE
Logging: the python way

### ISSUE THREAD

**Issue by ei-grad** [iterative/dvc#1753]
Here are some concerns about the current `dvc/logger.py` usage and implementation:
1. it doesn't provide the lazy evaluation/formatting for messages which wouldn't be printed due to logging level filter
2. `parse_exception` thing in warning is the duplicate of standard `exc_info=True` behavior
3. usage of Formatter to colorize the output would make it more clean and customizable
4. `progress_aware` should be replaced by custom logging.Handler to make it work with logs coming from other libraries

**Comment by efiop** [comment]
Great points @ei-grad ! Thank you! :slightly_smiling_face: 

1. Could you please elaborate on this one?

2. exc_info doesn't work with our custom chained exceptions(see `cause` in dvc/exceptions.py and _walk_exc in dvc/logger.py) on python2 though, so we walk those ourselves, hence a special option. Or is your point about the naming itself?

3. Great point!

4. Great point as well! :slightly_smiling_face:

**Comment by dmpetrov** [comment]
I can add that naming is not perfect. It is not `logger` actually. It is kind of outputted or something.

Also, in this class we have output\printing functions as well as logging functions (like printing SQL queries to SQLite) together. We can think of separating these two feature sets.

**Comment by mroutis** [comment]
@dmpetrov , what do you mean by SQL queries?

**Comment by ei-grad** [comment]
@mroutis there is a debug logging of the state database queries which comes from https://github.com/iterative/dvc/blob/master/dvc/state.py#L138 I guess

**Comment by mroutis** [comment]
Got it, @ei-grad ^
