### ISSUE TITLE
add: Suggest to use `dvc add folder/` instead of irregular `dvc add -R` for large amount of files

### ISSUE THREAD

**Issue by ei-grad** [iterative/dvc#1758]
Related #1756

**Comment by efiop** [comment]
Or maybe it is worth renaming it into something else than `--recursive` to break association with `cp`.

**Comment by ei-grad** [comment]
But is it needed at all?

**Comment by efiop** [comment]
@ei-grad that is also a great question :) We do have a user that requested it though https://github.com/iterative/dvc/issues/1026 .

**Comment by ei-grad** [comment]
That one could be better solved by `dvc add -u` as of my opinion to be honest. But anyway just removing the `-R` option is not an option now.

**Comment by ei-grad** [comment]
The point is likely to not touch this, but add a suggestion to use `dvc add folder` where it worth.

**Comment by efiop** [comment]
Could you elaborate on `dvc add -u`, please?

I agree about not removing it. I just threw in a thought that if it is indeed needed, maybe it is worth thinking about renaming it. A suggestion to use `dvc add directory` also seems good to me.

**Comment by ei-grad** [comment]
>>> We do have a user that indirectly requested it #1026
>> That one could be better solved by dvc add -u
> Could you elaborate on dvc add -u, please?

The actual request in #1026 was to provide an ability to `dvc add` all the changed files in one command. This is what `git add -u` does for git repository.
