### ISSUE TITLE
perf: remote: status: don't pull full list of files from remote

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1762]
Currently, we retrieve the full list of files from remote and then compare it with local cache, which gets really slow if user has lots of files on the remote already. So instead of doing this https://github.com/iterative/dvc/blob/0.32.1/dvc/remote/local.py#L591 we should compare it with local cache more carefully and efficiently. 

https://discordapp.com/channels/485586884165107732/485596304961962003/558288115249184775

**Comment by robguinness** [comment]
Looking forward to this one!

**Comment by rpip** [comment]
Working on this now

**Comment by efiop** [comment]
Keeping open for the progress bar.
