### ISSUE TITLE
Cyclic import in dvc.scm.git.tree

### ISSUE THREAD

**Issue by ei-grad** [iterative/dvc#1769]
#1709 dvc.scm.git.tree imports dvc.repo.tree, and this introduced a cyclic import which fires when `dvc.scm` is imported before `dvc.repo`:

### To reproduce

```
> python -c "import dvc.scm"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "dvc/scm/__init__.py", line 6, in <module>
    from dvc.scm.git import Git
  File "dvc/scm/git/__init__.py", line 15, in <module>
    from dvc.scm.git.tree import GitTree
  File "dvc/scm/git/tree.py", line 6, in <module>
    from dvc.repo.tree import BaseTree
  File "dvc/repo/__init__.py", line 10, in <module>
    class Repo(object):
  File "dvc/repo/__init__.py", line 15, in Repo
    from dvc.repo.add import add
  File "dvc/repo/add.py", line 3, in <module>
    from dvc.scm import scm_context
ImportError: cannot import name scm_context
```

**Comment by dmpetrov** [comment]
The same issue might happened in `dvc/repo/init.py` which is part of `Repo` class but still imports `Repo`.

**Comment by ei-grad** [comment]
@dmpetrov there are many issues with circular imports and to "import dependency inside the methods" is not the proper solution for them. But it looks like the only one which fires currently is this one with `dvc.scm.git.tree`. I'd like come up with the proper solutions for existing issues next week, but for this one I propose just move `dvc.scm.tree` to `dvc.tree`.

**Comment by efiop** [comment]
Couldn't it be solved with dynamic imports, though?

**Comment by efiop** [comment]
@ei-grad Also, when does this reproduce?

**Comment by ei-grad** [comment]
@efiop added reproduction step to the post

**Comment by efiop** [comment]
@ei-grad But that doesn't happen during regular dvc execution, right? Can't you just solve it with dynamic imports?
