### ISSUE TITLE
RFC: introduce `dvc version` command

### ISSUE THREAD

**Issue by ei-grad** [iterative/dvc#1783]
I propose to introduce the `dvc version` command, which would output the system/environment information together with the dvc version itself.

Example output:

```
$ dvc version
DVC version: 0.32.1
Python version: 3.7.2 (default, Jan 10 2019, 23:51:51)
[GCC 8.2.1 20181127]
VIRTUAL_ENV: /home/ei-grad/.virtualenvs/dvc
Platform: Linux 5.0.2-arch1-1-ARCH
LSB Release: lsb-release command not found
Cache: hardlink (symlink:yes reflink:no fs:ext4)
```

The current template of the bug issues on Github asks the user to add platform and installation method description. I think it would be nice to have the dvc's own method to capture the important information from the environment.

What other information should we include here?

Some things to refine:
* [ ] The "cache" part needs clarification.
* [ ] How it would coexist `dvc --version`? What are the best practices faced in other software?
* [ ] Do we have something special related to PyInstaller builds to collect?
* [ ] Are there any libraries which versions should be also included in such output? Should it include e.g. GitPython version?

**Comment by dmpetrov** [comment]
Great idea. I especially like `Cache: hardlink (symlink:yes reflink:no fs:ext4)`. I'd only remove `symlink` part - can we work on a system when symlink are not supported?

It would be great to have method of installation. Basically, we need everything that we ask in bug reports.

Btw.. is Python information useful? Also, which of DVC packages include Python (except Windows)?

Do we need `VIRTUAL_ENV: /home/ei-grad/.virtualenvs/dvc`? It contains a path which you probably don't want to share in a bug report.

**Comment by shcheklein** [comment]
Love the idea to print more information (especially, caching type).

Few questions/options to consider:

1. Why do we need a separate command for that, it's not clear. Why is `--version` alone not enough.
2. Would it be better to dump more information only when we run `dvc --version` in the verbose mode? And keep it clean and simple by default.
3. I think we still could support something like `dvc cache type` that by default prints actual DVC cache type being used.

**Comment by mroutis** [comment]
> Why do we need a separate command for that, it's not clear. Why is --version alone not enough.
@shcheklein, usually a command is more detailed,  for example:
```bash
❯ docker version
Client:
 Version:           18.09.3-ce
 API version:       1.39
 Go version:        go1.12
 Git commit:        774a1f4eee
 Built:             Thu Feb 28 20:38:40 2019
 OS/Arch:           linux/amd64
 Experimental:      false

❯ docker --version
Docker version 18.09.3-ce, build 774a1f4eee
```

**Comment by shcheklein** [comment]
@mroutis looks good!

**Comment by mroutis** [comment]
Related: https://github.com/mahmoud/boltons/blob/master/boltons/ecoutils.py

```
    $ python -m boltons.ecoutils
    {
      "_eco_version": "1.0.0",
      "cpu_count": 4,
      "cwd": "/home/mahmoud/projects/boltons",
      "fs_encoding": "UTF-8",
      "guid": "6b139e7bbf5ad4ed8d4063bf6235b4d2",
      "hostfqdn": "mahmoud-host",
      "hostname": "mahmoud-host",
      "linux_dist_name": "Ubuntu",
      "linux_dist_version": "14.04",
      "python": {
        "argv": "boltons/ecoutils.py",
        "bin": "/usr/bin/python",
        "build_date": "Jun 22 2015 17:58:13",
        "compiler": "GCC 4.8.2",
        "features": {
          "64bit": true,
          "expat": "expat_2.1.0",
          "ipv6": true,
          "openssl": "OpenSSL 1.0.1f 6 Jan 2014",
          "readline": true,
          "sqlite": "3.8.2",
          "threading": true,
          "tkinter": "8.6",
          "unicode_wide": true,
          "zlib": "1.2.8"
        },
        "version": "2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]",
        "version_info": [
          2,
          7,
          6,
          "final",
          0
        ]
      },
      "time_utc": "2016-05-24 07:59:40.473140",
      "time_utc_offset": -8.0,
      "ulimit_hard": 4096,
      "ulimit_soft": 1024,
      "umask": "002",
      "uname": {
        "machine": "x86_64",
        "node": "mahmoud-host",
        "processor": "x86_64",
        "release": "3.13.0-85-generic",
        "system": "Linux",
        "version": "#129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016"
      },
      "username": "mahmoud"
    }
```

It might be more than what we need, but it is a good starting point.

**Comment by algomaster99** [comment]
I am currently working on this issue. Will submit a PR after I figure it out :smile:.

**Comment by algomaster99** [comment]
@ei-grad How did you get the cache information?

**Comment by efiop** [comment]
Fixed by #1963

**Comment by efiop** [comment]
Leaving open for the last part: listing if dvc is installed from binary or not.

**Comment by algomaster99** [comment]
@efiop where is the binary code released? Are we talking about the `.exe` file?

**Comment by efiop** [comment]
@algomaster99 We have a helper to determine whether or not dvc is installed from binary or not. Simply use `is_binary` something like:
```
from dvc.utils import is_binary

info += "Binary: {}".format(is_binary())
```

**Comment by algomaster99** [comment]
@efiop but where can we find the binary release? There are only `.deb`, `.exe`, `.rpm` and `.pkg` in the releases.

**Comment by efiop** [comment]
@algomaster99 Yes, all of those contain binaries built by pyinstaller. Non-binary releases are the ones on homebrew formulas and pypi.

**Comment by shcheklein** [comment]
we need to update docs
