### ISSUE TITLE
Consider safe_remove for reused output names

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1790]
After merging #1789 use case:
```
dvc run -o out 'echo 1 >> out'
dvc run -o out 'echo 2 >> out'
```
described by @efiop  in #1786  will behave with respect to recently introduced (#1759) `persist` flag.
In case of `-o` new run command will silently remove out before executing new command.
We should consider introducing mechanism using safe remove here, as it might result in unaware data removal.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/2027
