### ISSUE TITLE
Pull file automatically when necessary for pipeline

### ISSUE THREAD

**Issue by bon** [iterative/dvc#1792]
If a data file that dvc knows about is needed for a pipeline it needs to be present. If it's not, it has to be pulled manually before running the pipeline. Couldn't dvc pull the file as part of the pipeline so it doesn't have to be pulled manually?

**Comment by shcheklein** [comment]
Duplicate #1791

**Comment by shcheklein** [comment]
@bon it does not do it now :( We'll keep the feature request open in #1791 . Thank you for your feedback!!
