### ISSUE TITLE
Drop support for Python 2.7

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1818]
Python will drop support for 2.7 in January 1st, 2020, I think DVC should too, it will ease the maintenance (spending less time dealing with str/unicode issues, default support for type checking syntax, access to a more robust standard library, etc.).

_Countdown for Python 2.7 EOL: https://pythonclock.org/_

I don't know how many users are currently running on Python 2.7, but we can get a clue by [analyzing pypi stats with BigQuery](https://packaging.python.org/guides/analyzing-pypi-package-downloads/) or using [pypinfo](https://github.com/ofek/pypinfo).

There are some maintenance tasks to migrate to a Python 3.x only codebase:
- [x] ~~Remove 2.7 and 3.4 from our conda package~~
- [x] Remove Python 2.7 from TravisCI (EDIT(30 Dec) removed from travis.yaml already, but need to cleanup scripts/ci/* from py2 code)
- [x] ~~Upgrade AppVeyor's Python version~~
- [x] Modify `python_requires` and explicit version classifiers (kudos to @hugovk !)
- [x] [Update the package](https://packaging.python.org/guides/dropping-older-python-versions/)
- [x] Remove all calls/dependencies to `future`
- [x] Remove all code linked to `utils.compat`
- [x] Refactor code with comments about python 2 backwards compatibility
- [x] Update `super()` to new syntax
- [x] Refactor `DvcExceptions` to use default traceback instead of custom one
  + [x] Refactor `logger.py.` ~~Remove `logging` formatter `parse_exc` logic and use `formatException` and `formatStack` instead~~
- [x] Refactor `system.py` module to use the default `os` methods for linking, as they include Windows support
- [ ] ~Make keyword params kwonly in dvc.api. Consider the same in other places.~ (#3108)

Feel free to edit this comment, modifying the list of tasks that should happen to make a clean transition.

_NOTE: This issue was created to **keep track** of what should be done. I'm not implying that this will happen in a near future, neither expressing the ideas of the rest of the maintainers.
It would be great if you can write down your opinion so we reach a consensus between the maintainers and the community._

**Comment by hugovk** [comment]
I'd recommend adding `python_requires` and explicit version classifiers, especially useful when 2.7 is dropped, and also useful now. Please see PR https://github.com/iterative/dvc/pull/1845.

---

> I don't know how many users are currently running on Python 2.7, but we can get a clue by [analyzing pypi stats with BigQuery](https://packaging.python.org/guides/analyzing-pypi-package-downloads/) or using [pypinfo](https://github.com/ofek/pypinfo).

Here's the pip installs for dvc from PyPI for March 2019:

| category | percent | downloads |
|----------|--------:|----------:|
|        3 |  73.99% |     6,320 |
|        2 |  17.53% |     1,497 |
| null     |   8.49% |       725 |
| Total    |         |     8,542 |

Source: `pypistats python_major dvc --last-month # pip install pypistats`


| category | percent | downloads |
|----------|--------:|----------:|
|      3.6 |  42.39% |     3,621 |
|      3.5 |  20.21% |     1,726 |
|      2.7 |  17.51% |     1,496 |
|      3.7 |  11.33% |       968 |
| null     |   8.49% |       725 |
|      3.4 |   0.06% |         5 |
|      2.6 |   0.01% |         1 |
| Total    |         |     8,542 |

Source: `pypistats python_minor dvc --last-month # pip install pypistats`

That's a very low proportion of Python 2, see https://dev.to/hugovk/python-version-share-over-time-4-26hm for some other projects.

**Comment by mroutis** [comment]
Thank you so much for the detailed stats and for contributing with #1845 and #1847 , @hugovk ! :fire:

**Comment by mroutis** [comment]
Time flies when you're having fun)
EOL is around the corner, I'm eager to close this issue))

**Comment by efiop** [comment]
For the record: trying to drop support for 2.7 (and 3.4, as it has reached EOL already) in https://github.com/conda-forge/dvc-feedstock/pull/54 , as it is starting to cause problems during the build.

**Comment by mroutis** [comment]
what do you mean, @efiop ? is it happening? are we finally dropping 2.7?
I can happily spend my weekend on the migration :sweat_smile:

**Comment by efiop** [comment]
@mroutis No, just dropping it where it causes serious issues. The main feast will come later, you won't miss it 😄

**Comment by mroutis** [comment]
I'm starting to feel the christmas spirit, we all joyful writing python 3.x code :slightly_smiling_face: 
![image](https://user-images.githubusercontent.com/7363250/70351568-d6d3fa00-182e-11ea-9b52-dca455aab604.png)

**Comment by efiop** [comment]
@mroutis The joy probably won't come until py35 is dead, which is 1 more year 🙂

**Comment by mroutis** [comment]
https://github.com/asottile/pyupgrade

**Comment by casperdcl** [comment]
Eek `python_requires` is the most important version-related keyword. Really bad that it wasn't included all this time. Definitely need at least one release explicitly allowing py>=3,<=3.4 and py<3 otherwise things could break in future. Looks like that's happened already though.

**Comment by efiop** [comment]
@casperdcl Last release was 0.78.1 and it has py2 support. We'll limit to >py3.4 in the next one. Plus would be probably nice to put some kind of sanity check for that in CLI and when importing `dvc`

**Comment by mroutis** [comment]
It is happening!

![](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fblog.chron.com%2Ftubular%2Ffiles%2F2015%2F11%2Fcharlie-brown-christmas-dancing.gif&f=1&nofb=1)

**Comment by mroutis** [comment]
yay or nay for _relative imports_?

**Comment by mroutis** [comment]
what about using `ABCs`?

**Comment by casperdcl** [comment]
Are there py3-specific ABC features you refer to?

**Comment by mroutis** [comment]
No, @casperdcl; I thought that ABCs weren't implemented in Python 2.7, don't know why we are not using them for `Remote`s and `Output`s, then :thinking:

**Comment by efiop** [comment]
@mroutis Let's not do that within this sprint, but rather create a separate ticket for that for later. We'll keep in mind them next time we are going to create appropriate classes. Relative imports could be moved to a separate ticket as well, as it is a bit unrelated and we currently mismatch relative and abs imports all over the codebase :slightly_smiling_face:

**Comment by casperdcl** [comment]
I agree with @efiop - both features were supported in py2 (may have needed things like `__future__.absolute_import`) but not related to deprecation. I'm fine with removal of `__future__` (which has already happened) but as @efiop said would leave actually using relative imports everywhere for another issue.

**Comment by mroutis** [comment]
Great, @efiop , @casperdcl ; should check better next time, I thought they were not supported in Python 2.7, this is what I was asking :sweat_smile:

**Comment by mroutis** [comment]
The last thing to address is using `kwargs` only on `api.py` module.

This is how it looks like: 
```python
>>> def hello(*, name='world'): print('hello', name)
>>> hello()
"hello world"
>>> hello("people")
TypeError: hello() takes 0 positional arguments but 1 was given
```

It makes the interface more explicit.
To make it work you only need to put an asterisk before the keyword arguments.

I can do it for `api.py` but not sure if make sense for other modules. I would leave it as a separate issue.

**Comment by mroutis** [comment]
Should we close this one or anyone has any other suggestion? @iterative/engineering

**Comment by mroutis** [comment]
Let's not leave this one open, we can handle any further suggestions on separate issues :)
