### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by robguinness** [iterative/dvc#1824]
When installing DVC using pip (`pip install dvc`), the version information supplied by dvc does not match that reported by pip:

Specifically, pip reports that 0.34.0 is installed, but `dvc --version` returns:

0.29.0+220b4b.mod

This is also confirmed by running the following command:

```
python -c 'import dvc; print(dvc.VERSION)'
0.29.0+220b4b.mod
```

```
python -c 'import dvc; print(dvc.VERSION_BASE)'
0.34.0
```

**Please provide information about your setup**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by efiop** [comment]
Related discussion on discord https://discordapp.com/channels/485586884165107732/485596304961962003/562979911888011270 .
