### ISSUE TITLE
More verbose output after dvc push to SSH remote

### ISSUE THREAD

**Issue by robguinness** [iterative/dvc#1825]
After running `dvc push` to an SSH remote, even with the verbose flags maxed out (`-vvv`), there is no output for awhile after dvc requests the credentials for the remote. This leads the user (at least in my case) to suspect a problem with SSH authentication when in reality dvc is working on something else (according to @efiop this is the case).

It would be nice to have more verbose info printed to the console. For example, "SSH authentication suceeded. Now doing _XXX_...". In my opinion, especially when using `-vvv`, the user should always have an idea what dvc is actually trying to do.

**Comment by ei-grad** [comment]
If it hangs on "Collecting information" state, then this is the problem with the `status` gathering, which would have a progress bar when #1762 would be merged. This is how it looks now and how it would be looking (wait a bit for the second `dvc push` run): https://asciinema.org/a/KARzjWgeijP6sK2Qj7vUbYFc1.

**Comment by ei-grad** [comment]
Though it still could "hang" in the scenario when the current repository needs a small amount of files from the remote which has a huge amount of files. For this case DVC should not only notice the ssh auth success, but suggest `no_traversal = true` to be specified.

**Comment by efiop** [comment]
@ei-grad Wow, that looks amazing! :fire: :fire: :fire:
