### ISSUE TITLE
Init does not respect analytics system level analytics flag

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1832]
I tried to run it on the MatrixDS env and set an opt out flag with:

`sudo dvc config --system core.analytics false`

Nonetheless, when you run `dvc init` you can see 4 daemon instances spawned.

**Comment by mroutis** [comment]
@shcheklein , it looks like analytics is indeed disabled:
```
❯ dvc init --verbose --no-scm --force
DEBUG: Trying to spawn '['/home/mroutis/src/iterative/dvc/.venv/bin/python2.7', u'-m', u'dvc', u'daemon', u'-q', u'updater']'
DEBUG: Spawned '['/home/mroutis/src/iterative/dvc/.venv/bin/python2.7', u'-m', u'dvc', u'daemon', u'-q', u'updater']'
+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|              https://dvc.org/doc/user-guide/analytics               |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: https://dvc.org/doc
- Get help and share ideas: https://dvc.org/chat
- Star us on GitHub: https://github.com/iterative/dvc
DEBUG: Trying to spawn '['/home/mroutis/src/iterative/dvc/.venv/bin/python2.7', u'-m', u'dvc', u'daemon', u'-q', u'updater']'
DEBUG: Spawned '['/home/mroutis/src/iterative/dvc/.venv/bin/python2.7', u'-m', u'dvc', u'daemon', u'-q', u'updater']'
DEBUG: Analytics is disabled.
```

Are you getting confused with the `updater` process?

**Comment by shcheklein** [comment]
This is how it looks like for me:

```matrix@tool-5ca6d6e08f48fd83c6cc6069-mcn6f:/home/test$ cat /etc/xdg/dvc/config
[core]
analytics = false```

And `dvc init` results in:

```
matrix      97     1  0 21:21 ?        00:00:00 /usr/bin/python -m dvc daemon -q analytics /tmp/tmpfador7g7
matrix     120     1  0 21:24 ?        00:00:00 /usr/bin/python -m dvc daemon -q analytics /tmp/tmpxaj1wghc
matrix     134     1  0 21:38 ?        00:00:00 /usr/bin/python -m dvc daemon -q analytics /tmp/tmpi9ex356n
root       145     1  0 21:38 ?        00:00:00 /usr/bin/python -m dvc daemon -q analytics /tmp/tmpfyhd4sh9
matrix     248    18  0 21:53 pts/0    00:00:00 /usr/bin/python /usr/local/bin/dvc init
```

**Comment by efiop** [comment]
@shcheklein Are you sure those are not from your earlier runs? For example you can see one from `root`, which is clearly the one from `sudo dvc config` that you've run before and clearly wasn't spawned by `dvc init`. Try killing all of those and trying to run `dvc init -v` again.

**Comment by shcheklein** [comment]
False alarm. I've tried to reproduce it on a clean instance, don't see these daemons now.
