### ISSUE TITLE
make status take .dvcignore into account

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1834]
After merging #1499 user might want to ignore some files. Add functionality to dvc status, that will allow user verify if his .dvcignore works as intended.  
E.g.: when using git, `git status` shows all files in repository that are not ignored. There is no such straightforward  command in dvc.

**Comment by shcheklein** [comment]
@pared will this one be closed as well soon?

**Comment by pared** [comment]
@shcheklein 
Yes, now every use case of `walk` in our codebase will take `.dvcignore` into account (besides some tests)

**Comment by pared** [comment]
@efiop I think we need to reopen it, or open new issue. The title of this issue is about something different than description, thats my fault. While status take .dvcignore into account while traversing now, we still need some easy way to show user that .dvcignore is working, as intended.

**Comment by efiop** [comment]
@pared Aah, got it. I've seen it listed as `Fixes #1876 #1834` in https://github.com/iterative/dvc/pull/2161 and so thought that it just wasn't closed accidentally. Ok, reopenning. But do we actually need it though? Git doesn't show the files it ignores, why should we?

**Comment by pared** [comment]
@efiop thats my bad, sorry.
 Well, there is indirect way of detecting ignores, when you use `git status` and you don't see ignored files. Our status does not work the same way as `git` does so there is not even indirect way of doing it.

**Comment by efiop** [comment]
@pared Well, but if it is not ignored by us, then `git status` will show those files, no? I don't quite understand what functionality from `dvc status` do you expect. Maybe you could provide an example?

**Comment by pared** [comment]
@efiop, ok, now that I started to think about example, i doubt we need to implement some feature, indicating that something is ignored. 
If someone has data dir, and ignores something inside, status will show it changed, and that is important.

I was thinking about some command that would display all ignored files, but now I don't think it is necessary (at least until someone asks for it with proper reasoning). We can re-close it, sorry.
