### ISSUE TITLE
pull hangs even if all the files needed exist in cache

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1839]
I've noticed that `dvc pull` hangs for a few seconds every time you run it. Even if all the files needed exist in cache.

```
(.env) [ivan@ivan ~/Projects/example-get-started]$ dvc pull
Preparing to download data from 'https://remote.dvc.org/get-started'
Preparing to collect status from https://remote.dvc.org/get-started
[#########                     ] 30% Collecting information
```

Is it expected or just is it just a lack of optimization?

Can be reproduced with the example-get-started project and HTTP remote.

**Comment by efiop** [comment]
Lack of optimization. Here https://github.com/iterative/dvc/blob/0.34.2/dvc/remote/local.py#L684 we collect full-blown status even for an already present cache on `dvc pull`, which is causing that delay. Need to fix that by skipping collecting status for already present cache files on `pull/fetch`. Thanks for reporting this! 🙂
