### ISSUE TITLE
`dvc run` always removes outputs

### ISSUE THREAD

**Issue by guerrapin** [iterative/dvc#1851]
Hi there, 

Since version `0.33.1`, it appears that `dvc run` always removes outputs no matter the use of the option `--remove-outs`.

Here is a failing code snippet that used to work before the update.
```
git init
dvc init
mkdir outs
dvc run -o outs "echo foo >> outs/toto.txt"
```
Is this behaviour the expected one ?

Some fixes to this situation could be:
* replace `-o outs` by  `-o outs/toto.txt`
* use the command `"mkdir outs; echo foo >> outs/toto.txt"`
 
Anyway, it seems `--remove-outs` became useless. Am I right ?

Thanks :)

**Comment by efiop** [comment]
Hi @guerrapin !

Indeed, we've decided to switch from not-removing by default to avoid a potentially dangerous situation when your command doesn't actually produce those outputs and so you will only find it out when your `dvc repro` fails in the future :slightly_frowning_face: Could you describe the scenario in which you used to not remove outputs, please, so we could maybe propose a proper approach with dvc? :slightly_smiling_face: 

Thanks,
Ruslan

**Comment by guerrapin** [comment]
Hi @efiop 

Ok I understand. I don't have a specific scenario. 
I wasn't using the command the perfect way (i.e. pointing a directory as output while the command only produces files in this directory) and it now prevents me from doing this anymore. 
I'll pick the second solution : if I point a directory as an ouput then the command I execute must create this directory (`dvc run -o outs/ "mkdir outs; ..."`)

Thanks for your reply :)
