### ISSUE TITLE
Repro: logger doesn't work correctly on exception

### ISSUE THREAD

**Issue by olveirap** [iterative/dvc#1858]
DVC version: 0.35.5+d80137,
Platform: Linux
Method of installation: pip install from git

https://github.com/iterative/dvc/blob/54072d70b542115a78a374fa702129b6959a1d02/dvc/command/repro.py#L50-L51 

This lines should be:
```
except DvcException, msg:
            logger.exception(msg)
```

**Comment by efiop** [comment]
Great catch @olveirap !

@mroutis This seems to be related to the logger redesign. We used to have logger.error(), that was able to work without any message by simply printing the last exception. Should we support the same with new logger or should we simply pass something like an empty string there?

**Comment by mroutis** [comment]
@efiop , I was using empty strings, I'll submit a patch fixing any instance.

**Comment by efiop** [comment]
@mroutis Wow, that was fast :zap: :zap: :zap: Thank you! :slightly_smiling_face:
