### ISSUE TITLE
add: warning is misleading

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1868]
When you update a data directory/file and run `dvc add` to save this new version to cache the output looks like this:

```
WARNING: Output 'images' of 'images.dvc' changed because it is 'modified'
Saving 'images' to cache '.dvc/cache'.
Linking directory 'images'.
Saving information to 'images.dvc'.

To track the changes with git run:

	git add images.dvc
```

I think WARNING is misleading here. I'm not doing anything wrong here and feels like that when I see this WARNING.

**Comment by efiop** [comment]
Moved to debug. Closing.
