### ISSUE TITLE
dvc: dvc run should check if dependency is output of another pipeline

### ISSUE THREAD

**Issue by olveirap** [iterative/dvc#1883]
When performing a `dvc run` and using as dependency the output of another pipeline, this pipeline isn't checked if it should be run again. The only solution for this is to do `dvc run` and then do a `dvc repro` to rerun everything updating the dependencies. One could make the mistake of just running `dvc run` and if this happens on a final stage of their project, find out late that the last output was run with outdated dependencies.

**Comment by efiop** [comment]
Some more context from discord https://discordapp.com/channels/485586884165107732/485596304961962003/566396864086147092

**Comment by efiop** [comment]
I don't think this should be done by default, but we definitely could add `--repro` option for `dvc run` to do that. Would that suit you, @olveirap ?

**Comment by efiop** [comment]
@olveirap ^

**Comment by efiop** [comment]
Closing as stale.
