### ISSUE TITLE
test: tests need more love

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#1888]
There are several issues with tests, which make them annoying and less efficient part of developer workflow (staging is fine). Here is a list:

- [x] updater and analytics processes are started during tests
- [ ] errors are wrapped in friendly messages, which bloats output
- [x] debug log level bloats output
- [x] temporary dirs not cleared #1770
- [ ] tests are slow

Some of this is either fine or must in staging environment, like DEBUG log level and tests being slow, however, this inhibits developers performance.

On tests being slow. Ramdisk or mocked file system access might be used to speed them up in depeveloper environment, while running same as now on staging.

**Comment by Suor** [comment]
May look at [pyfakefs](https://pypi.org/project/pyfakefs/) for speeding it up in dev env.

**Comment by efiop** [comment]
stale
