### ISSUE TITLE
checkout: print reminder of other link types on default link cache

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1890]
Related to #1257 
After mergin #1841 we make reflink and copy default link types.
That might slow process of checking out for bigger files. Implement mechanism to detect prolonged checkout time and print some kind of information that other link types might speed process up. Also, there should probably be easy way to turn this message off, if someone deliberately leaves defaults.

**Comment by shcheklein** [comment]
We should also add the message when we move files to the cache initially - `dvc add`, `dvc run`, `dvc import`...

**Comment by pared** [comment]
Ok, can we make it to new issue?

**Comment by shcheklein** [comment]
@pared I would split if the patch for the first part is almost ready

**Comment by pared** [comment]
Ok, ill just rename config options so that they match all situations, to prevent potential backward incompatibility.

**Comment by efiop** [comment]
`slow_link_warning` is the one that we need. It applies to add, checkout, etc. And it actually might answer the question of how this warning should be handled in general :slightly_smiling_face:

**Comment by pared** [comment]
Example:
https://asciinema.org/a/2XsHkAUcUfx1aHfmUV7atnpoJ
