### ISSUE TITLE
refactoring: use kwargs instead of long lists of explicit args

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1900]
E.g. 

https://github.com/iterative/dvc/blob/master/dvc/repo/run.py

https://github.com/iterative/dvc/blob/master/dvc/repo/reproduce.py

In general, need to look where CC complains about too much args.

**Comment by Suor** [comment]
Some args end up not being used like `target` and `active` in `_load_all_used_cache()`. Another thing is that many args are passed through, which is code smell.
