### ISSUE TITLE
Feature: `dvc add` add file by remote link

### ISSUE THREAD

**Issue by puhoshville** [iterative/dvc#1901]
Regular pipeline:
1) Download data from place A;
2) Add that data to DVC and push it to place B (remote storage);

But if A and B are the same a file will be duplicated since DVC names files by hash. The option to add a data file by remote link will save a lot of time and storage.

**Comment by efiop** [comment]
Hi @puhoshville !

Sorry, not sure I follow. Could you please elaborate?

**Comment by puhoshville** [comment]
Hi @efiop, sorry for a late answer.
I'm about way we are adding dataset (*.dvc files) and pushing it to the remote storage. From the documentation (https://dvc.org/doc/get-started/add-files):
```
    # define remote s3
    $ dvc remote add myremote s3://mybucket/myproject
   
    # download data
    $ mkdir data
    $ wget https://dvc.org/s3/get-started/data.xml -O data/data.xml

   # add to dvc
    $ dvc add data/data.xml
    $ git add data/.gitignore data/data.xml.dvc
    $ git commit -m "add source data to DVC"
    
    # push to the remote
    $ dvc push
```

But let's assume that the data we need to use already placed in s3://mybucket/myproject. It will look like:
```
    # define remote s3
    $ dvc remote add myremote s3://mybucket/myproject
   
    # download data
    $ mkdir data
    $ aws s3 cp  s3://mybucket/myproject/data.xml data/data.xml

   # add to dvc
    $ dvc add data/data.xml
    $ git add data/.gitignore data/data.xml.dvc
    $ git commit -m "add source data to DVC"
    
    # push to the remote
    $ dvc push # At this moment duplicate created in s3
```

My suggestion is to introduce a new feature: add a file by link.  It must look like:
```
    # define remote s3
    $ dvc remote add myremote s3://mybucket/myproject

    # add data
    $ mkdir data
    $ dvc add --remote s3://mybucket/myproject/data.xml data/data.xml
    $ git add data/.gitignore data/data.xml.dvc
    $ git commit -m "add source data to DVC"

    # download data:
    $ dvc pull data/data.xml.dvc

    # No need to push data
```

This feature can be useful for many users of cloud services because they have a simple opportunity to unload data from DB to S3 and after use that in their dvc pipeline.
What do you think?

**Comment by efiop** [comment]
@puhoshville But dvc cache that you push to your remote is not compatible with a plain file on your remote and it serves a totally different purpose by providng cache that your data is versioned to. Maybe you are looking for [external dependencies](https://dvc.org/doc/user-guide/external-dependencies) or [external outputs](https://dvc.org/doc/user-guide/external-outputs) feature?

**Comment by puhoshville** [comment]
@efiop Oh, it fully satisfies needs I was talking about, sorry for a false bell. Everything already was provided in advance, thank you!
