### ISSUE TITLE
UX issue with dvc pull - does not pull entire remote cache

### ISSUE THREAD

**Issue by robogeek** [iterative/dvc#1905]
**Please provide information about your setup**

Mac OS X with:

```
$ dvc --version
0.35.7
```

The issue is replicable using the Getting Started workspace.

When set up using these commands:

```
$  git clone https://github.com/iterative/example-get-started
$  cd example-get-started/
$ pip install -r requirements.txt
$  dvc pull
```

It appears the cache is incomplete.  This is observed by checking out different Git tags and attempting to use `dvc checkout`.

```
$ git tag
0-empty
1-initialize
2-remote
3-add-file
4-sources
5-preparation
6-featurization
7-train
8-evaluation
9-bigrams
baseline-experiment
bigrams-experiment

$ git checkout 7-train
Note: checking out '7-train'.

$ dvc status
featurize.dvc:
	changed outs:
		not in cache:       data/features
train.dvc:
	changed deps:
		modified:           data/features
	changed outs:
		not in cache:       model.pkl

$ dvc checkout
ERROR: Failed to load dir cache '.dvc/cache/33/38d2c21bdb521cda0ba4add89e1cb0.dir' - [Errno 2] No such file or directory: '/Volumes/Extra/dvc/example-get-started/.dvc/cache/33/38d2c21bdb521cda0ba4add89e1cb0.dir'

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
WARNING: Cache 'a66489653d1b6a8ba989799367b32c43' not found. File '{'scheme': 'local', 'path': '/Volumes/Extra/dvc/example-get-started/model.pkl'}' won't be created.
WARNING: Cache '3338d2c21bdb521cda0ba4add89e1cb0.dir' not found. File '{'scheme': 'local', 'path': '/Volumes/Extra/dvc/example-get-started/data/features'}' won't be created.
[##############################] 100% Checkout finished!

$ ls .dvc/cache
38	42	58	68	9d	a3	aa	dc
```

Notice that the directory `.dvc/cache/33` is not there, just as the error message says.

If instead we initialize the workspace using `dvc fetch -T` or `dvc fetch -aT` this command does not fail.

**Comment by robogeek** [comment]
To add a bit of analysis.

I believe we can describe the behavior of `git pull` as ensuring all commits from the remote repository are copied down to the local repository.

Therefore the parallel for DVC should be that all data files in the remote cache are copied down to the local cache.  That is the behavior I expected.

**Comment by efiop** [comment]
@robogeek `dvc pull` has `--all-branches` and `--all-tags` options. The reason why `dvc pull` doesn't have those enabled by default is that it is dealing with data, and pulling cache for all references might take up too much space.

**Comment by shcheklein** [comment]
I think the point was that we need to introduce an option to auto-pull (we have a ticket for this, ritht) when we use git hooks. Otherwise there is no easy now to, let's say go to a certain git commit (no tag, no branch) if some data is missing in cache. There is no way to go to a tag w/o fetching the whole cache, right?

**Comment by efiop** [comment]
@shcheklein Not really. `dvc pull` will pull what is currently used. So if you `git checkout tag` and then `dvc pull`. it will pull data for that specific tag.

**Comment by shcheklein** [comment]
Okay, there is some misunderstanding. I though (from the discord discussion) that the purpose of the ticket is a little bit different. To be precise, the question comes down to: if dvc checkout hook is installed can we do git checkout without fetching the whole cache first - this is what bothers me, sorry that my question was out of the context.

**Comment by robogeek** [comment]
It seems there is confusion about my thought about this.  First I filed it because @shcheklein  asked me to do so ;-)

But to me the issue is not about `dvc checkout` but about the behavior of `dvc pull` with no options.

My expectation was that `dvc pull` with no options would pull down all data files (ditto with `dvc fetch`).  

I was honestly surprised to see that it had not.  My initial assumption was that the remote cache used by the example repository was somehow incomplete.  Then I noticed @jorgeorpinel had noted the exact same issue earlier in the week.

That two of us fell into the same problem to me indicates that the UX is not correct.  Back in the 1980's on Usenet we used the phrase "principle of least surprise" which says that a program should produce the least surprise for the user.

By comparison, `git pull` with no options ensures that all commits are pulled from the remote repository.

**Comment by shcheklein** [comment]
This all true, @robogeek . But like Ruslan mentioned ML and Data Science are different. It's very unreasonable to pull all data at once - in most cases you don't even have enough space for that. The lack of this laziness is one of the reason why git breaks when you try to save binary files in it - clone becomes too slow. 

Your and @jorgeorpinel's point still makes sense. What we can do is to emphasize this difference in the documentation, in the help message. May be in the command output (?).

I'm still worried about hooks and checkout - this lazy semantics makes certain things unusable from what I get.

**Comment by efiop** [comment]
Maybe some info message that looks something like "Pulling cache for the current workspace. To pull cache for the whole project see `dvc pull -h`." ? Would it help to make it more clear?

**Comment by jorgeorpinel** [comment]
I like the concept of "principle of least surprise". However I'm not sure what my natural expectation would be with `dvc pull`... Even when I did have the same problem initially in not understanding what I was missing (`dvc fetch -T`) I think I do agree more with Ivan and Ruslan that it's not very reasonable for DVC to download all the data files by default. For example, from what I remember Git LFS only downloads the files you need for each `git checkout` or `git pull` command on a specific reference/branch (and then it does keep those files previously downloaded in a cache, which can be cleaned up manually with `git lfs prune`).

**Comment by jorgeorpinel** [comment]
p.s. have we considered DVC automatically adding hooks to `git checkout` and `git pull` like Git LFS does to save the user the need to type the `dvc pull` command?

**Comment by jorgeorpinel** [comment]
Oh lol sorry the auto-pull option is exactly what Ivan was talking about! Maybe we should open another ticket for that.

Anyway I'm happy to volunteer to change docs and command help message/ output text for now if that's the route decided. Please lmk

**Comment by efiop** [comment]
Closing as stale. Doesn't look like any other users are running into this.
