### ISSUE TITLE
Does it make sense to support `--file` option for `add` and `import` commands?

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1912]
The purpose of using the same name for stage files and regular files (`hello.txt` <-> `hello.txt.dvc`) was to use stage files as a placeholder for the actual files. Having `dvc add --file` and `dvc import --file` would _break_ this notion.

However, it make sense to have that option for `run`, as you might use it to assign a name that reassembles what that stage does (e.g. `train.dvc`, `transform.dvc`).

**Comment by shcheklein** [comment]
Good point!

But on the other hand, what if you don't these placeholders to be less visible or completely invisible (git-lfs style?)?

**Comment by efiop** [comment]
Closing for now as stale. Please feel free to reopen.
