### ISSUE TITLE
"dvc metrics show -a" doesn't work if a metric file is missing

### ISSUE THREAD

**Issue by mastaer** [iterative/dvc#1917]
> Hi everyone,

I have three branches. Every branch is one experiment. One experiment should create a metric file as output. Two experiments are already finished, the third experiment is still running. So I have two experiments (= branches) with a metric file and one without.

Now I want to use "dvc metrics show -a" to get the result from the two already finished experiments. But I got an error that the branch with the running experiment does not have a metric file.

I am working with the pip installed DVC (version 0.35.7). The system is a ubuntu 18.04 and use anaconda.

I got help from ruslan in the forum: https://discordapp.com/channels/485586884165107732/563406153334128681/570262271847039028

thanks for the help!

> cmd: python code/train.py 
> deps:
> - path: data/toy_3dpatients_on_mrt.npy
> - path: data/toy_3dpatients_on_mrt_settings.npy
> - path: data/toy_3dpatients_on_mrt_test.npy
> outs:
> - cache: false
>   metric: true
>   path: metrics/test_local_False.json
> - cache: true
>   metric: false
>   path: tensorboards/test_local_False_test
> - cache: true
>   metric: false
>   path: tensorboards/test_local_False_train
> - cache: true
>   metric: false
>   path: tensorflow_models/model_weights_test_local_False.h5

And here is the output from the command `dvc metrics show -v -a`
> (tf-gpu) j@t:~/Documents/gitlab/0005_3d_siamesenet$ dvc metrics show -v -a
> ERROR: unexpected error - [Errno 2] No such file in branch 'test_local': 'metrics/test_local_False.json'
> ------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/j/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dvc/main.py", line 37, in main
>     ret = cmd.run_cmd()
>   File "/home/j/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dvc/command/base.py", line 60, in run_cmd
>     return self.run()
>   File "/home/j/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dvc/command/metrics.py", line 47, in run
>     recursive=self.args.recursive,
>   File "/home/j/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dvc/repo/metrics/init.py", line 18, in show
>     return show(self.repo, *args, **kwargs)
>   File "/home/j/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dvc/repo/metrics/show.py", line 263, in show
>     metrics = _read_metrics(self, entries, branch)
>   File "/home/j/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dvc/repo/metrics/show.py", line 237, in _read_metrics
>     fd = self.tree.open(out.path)
>   File "/home/j/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dvc/scm/git/tree.py", line 34, in open
>     raise IOError(errno.ENOENT, msg, relpath)
> FileNotFoundError: [Errno 2] No such file in branch 'test_local': 'metrics/test_local_False.json'

**Comment by efiop** [comment]
@mastaer The fix for this bug has been released in 0.40.1. Please upgrade. Thanks a lot for this bug report! 🙂
