### ISSUE TITLE
dvc metrics show - implement jsonpath-ng instead of python-jsonpath-rw

### ISSUE THREAD

**Issue by brbarkley** [iterative/dvc#1919]
Hello,

For passing JSONPath to ``dvc metrics show`` is it possible to use [jsonpath-ng](https://github.com/h2non/jsonpath-ng) under the hood instead of [python-jsonpath-rw](https://github.com/kennknowles/python-jsonpath-rw)?

``jsonpath-ng`` seems to more fully support JSONPath features, for example the ability to filter on certain values: ``$..book[?(@.price<10)]`` which would be useful for comparing metrics with greater specificity from dvc metrics files.

Thanks for considering!

**Comment by efiop** [comment]
Hi @brbarkley !

Great question! I don't quite remember why we've opted for `python-jsonpath-rw`. Looks like we could simply start using `jsonpath-ng` instead and we should be fine as long as tests pass. Would you like to submit a PR? :slightly_smiling_face: 

Thanks,
Ruslan

**Comment by efiop** [comment]
@brbarkley This feature was released as a part of 0.40.1. Please upgrade 🙂
