### ISSUE TITLE
test: stop using unix specific tools in tests

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#1922]
There are [cat](https://github.com/iterative/dvc/blob/b8018c16a7e847a8a9cfb3493ac024219932cb85/tests/func/test_add.py#L240) and [ls](https://github.com/iterative/dvc/blob/b8018c16a7e847a8a9cfb3493ac024219932cb85/tests/func/test_add.py#L262) used in tests. Which may fail or not on windows depending on env.

**Comment by Suor** [comment]
Also test `TestShouldNotCheckoutUponCorruptedLocalHardlinkCache.test` fails with 
```
'cp' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mroutis** [comment]
that's a shame! :disappointed:

**Comment by efiop** [comment]
That is why we usually use `CODE` from `TestDvc` that implements `cp` as a python script and works everywhere. Usage of unix-specific tools slipped into some of our tests.
