### ISSUE TITLE
Autocomplete for file names doesn't work (partially) [bash]

### ISSUE THREAD

**Issue by belskikh** [iterative/dvc#1923]
Hello!
When I use autocompletion script from here `https://github.com/iterative/dvc.org/blob/master/static/docs/user-guide/autocomplete.md` it doesn't complete file and directory names from current directory for the command `dvc repro ...`.
But if I add some flag, for example `dvc repro --force ...` then it works fine.
What should be changed in bash autocomplete script to allow autocompletion for `dvc repro ...` without any flags?

**Comment by efiop** [comment]
Hi @belskikh !

Thanks for the feedback! I suppose you'd like to contribute a fix for it? @mroutis should be able to help with it.

For the record: moved issue from dvc.org repo to dvc repo.

**Comment by belskikh** [comment]
Hi, @efiop 
Yes, I will fix it, if someone helps me

**Comment by mroutis** [comment]
@belskikh , are you using the latest version of the script?
It should be working (or at least it does for me), the line that deals with this is the following:

https://github.com/iterative/dvc/blob/dd8598e53ea03aaa7554c6ebf8fa7fe37baffc31/scripts/completion/dvc.zsh#L150

**Comment by belskikh** [comment]
@mroutis I am using this version
https://github.com/iterative/dvc/blob/dd8598e53ea03aaa7554c6ebf8fa7fe37baffc31/scripts/completion/dvc.bash

**Comment by mroutis** [comment]
check this out, @belskikh :

[![asciicast](https://asciinema.org/a/242753.svg)](https://asciinema.org/a/242753)

**Comment by belskikh** [comment]
@mroutis that's awesome, and I will definetly try `zsh` , but for standard Ubuntu bash terminal it doesn't work. 
Can you help me to understand, what I should add/change in `dvc.bash` script to fix it?

**Comment by mroutis** [comment]
ohh my bad, @belskikh ! :see_no_evil: 

I don't have a good understanding of Bash's completion engine, but you'll need to add something like `compgen -f -X '!*.dvc'` over here https://github.com/iterative/dvc/blob/dd8598e53ea03aaa7554c6ebf8fa7fe37baffc31/scripts/completion/dvc.bash#L57-L63

Be aware that some commands accepts something more than just _stage files_ (the ones ending in `.dvc`).

The script itself have some _references_ that you can look up to understand how the file was created, I'll leave you with one more: https://www.linuxjournal.com/content/more-using-bash-complete-command

By the way, installing Zsh is not that hard:
```bash
# Download and install from the package repository 
sudo apt-get install zsh

#[ch]ange [sh]ell to Zsh
chsh -s $(which zsh)
```

And you are all set!

If you want colors and stuff like that, I can recommend you the [pure prompt](https://github.com/sindresorhus/pure)

I'm currently using [spaceship-prompt](https://github.com/denysdovhan/spaceship-prompt) but requires a little bit more of configuration.

There's also [geometry prompt](https://github.com/geometry-zsh/geometry)

Those are my favorites :sweat_smile: .

Anyways, if you manage to make completion work with bash it would be awesome! good luck :duck:

**Comment by casperdcl** [comment]
this is annoying. doesn't work for me for `dvc add` in the latest version either

**Comment by mroutis** [comment]
@casperdcl , Bash, right?

**Comment by casperdcl** [comment]
@mroutis if it was `zsh` I'd assign you :D

**Comment by mroutis** [comment]
@casperdcl, please feel free :slightly_smiling_face:

**Comment by g-simmons2** [comment]
Not having the completions is definitely annoying, I switched to zsh just to have them :)

Would it be possible to make the completions work for 3-token commands (not sure if this is the right terminology) - for example `dvc pipeline show <tab to choose a file>`?

The current behavior for `dvc pipeline show <tab>` is to list the available options:
```
 -- option --
--help     -h  -- Show help message related to the command.                                                                                             
--quiet    -q  -- Be quiet.                                                                                                                             
--verbose  -v  -- Be verbose. 
```

And the output for `dvc pipeline show incomplete_filename<tab>` is
```
-- no more arguments --
```
meaning one has to type the complete filename by hand.

Would certainly be a nice to have!

**Comment by casperdcl** [comment]
@g-simmons2 definitely possible but you're talking about #1924 (zsh).

I'll submit a `bash` PR soon...

**Comment by g-simmons2** [comment]
@casperdcl If it works on bash I'll switch back 😄

**Comment by verasativa** [comment]
+1 on the annoyed crew here, I'm looking forward for @casperdcl PR 🙄

**Comment by casperdcl** [comment]
> looking forward for @casperdcl PR

hah me too :D

**Comment by casperdcl** [comment]
Fix coming soon (#3360)!

**Comment by efiop** [comment]
@casperdcl Should we create a ticket for subdir support?

**Comment by casperdcl** [comment]
definitely will do it soon :)
