### ISSUE TITLE
scripts: Zsh completion should work with subcommands 

### ISSUE THREAD

**Issue by ghost** [iterative/dvc#1924]
For example: `dvc metrics show <tab>`.

The way to support this would be to modify the way we parse our arguments to support subcommands https://github.com/iterative/dvc/blob/dd8598e53ea03aaa7554c6ebf8fa7fe37baffc31/scripts/completion/dvc.zsh#L231-L240

**Comment by jorgeorpinel** [comment]
I just want to add that specifically for `dvc cache dir` the `_dvc_global_options` (`-h`, `-q`, and `-v`) don't exist while for all the other subcommands I think they do. Something to consider. (Maybe they should be added to the subcommand?)

**Comment by efiop** [comment]
@jorgeorpinel Good catch! Indeed, we've missed those there. Looks like we just need to use `parents=[parent_parser, parent_config_parser]` in https://github.com/iterative/dvc/blob/master/dvc/command/cache.py#L46 .

**Comment by casperdcl** [comment]
also see https://stackoverflow.com/questions/9000698/completion-when-program-has-sub-commands

**Comment by efiop** [comment]
Fixed in https://github.com/iterative/shtab
