### ISSUE TITLE
test: symlinks tests fail on Windows

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#1927]
Tests
```
TestShouldAddDataFromExternalSymlink.test
TestShouldAddDataFromInternalSymlink.test
TestCheckoutMovedCacheDirWithSymlinks.test
TestRemoveBrokenSymlink.test
TestRunUnprotectOutsSymlink.test
```

fail on windows with various unhelpful messages. @efiop clarified that symlinks require special rights to be used on Windows. So we should either skip these tests in the absence of symlink rights or give better error messages.

**Comment by efiop** [comment]
stale
