### ISSUE TITLE
dvc: pyproject.toml doesn't work with `pip install -e .`

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#1933]
When running `pip install -e .` from [Contributing guide](https://dvc.org/doc/user-guide/contributing/) I get:

> ERROR: Error installing 'file:///home/suor/projects/dvc': editable mode is not supported for pyproject.toml-style projects. pip is processing this project as pyproject.toml-style because it has a pyproject.toml file. Since the project has a setup.py and the pyproject.toml has no "build-backend" key for the "build_system" value, you may pass --no-use-pep517 to opt out of pyproject.toml-style processing. See PEP 517 for details on pyproject.toml-style projects.

Using
```bash
pip install -e . --no-use-pep517
```
fixes that. 

We should update the guide or get rid of `pyproject.toml` file, e.g. somehow using `black --config` option.

**Comment by efiop** [comment]
@Suor Great catch!

**Comment by efiop** [comment]
No longer the case in pip 19.1.1
