### ISSUE TITLE
dvc: use box.com as remote storage solution

### ISSUE THREAD

**Issue by dangadadanga** [iterative/dvc#1940]
My company has unlimited storage for Box.com and I would like to use it to store my models/data. This is the only thing preventing me currently from using DVC although I would like to. 

I know Box.com allows access through FTP and API, maybe you can integrate with it. 
See these pages for additional info:
https://developer.box.com/reference#upload-a-file
https://community.box.com/t5/Managing-Content-Troubleshooting/I-m-Having-Trouble-Using-FTP-with-Box/ta-p/323

They also have user accounts and app accounts. Authentication for the user account is based on OAUTH (if I remember correctly). We mostly use app accounts so that would be ideal (although both would work).  

Note: I saw there's a ticket for WebDav, but WebDav has been retired.

**Comment by efiop** [comment]
Hi @dangadadanga !

Great feature request! I'm not at all familiar with box.com myself, but we have a feature request for supporting FTP at https://github.com/iterative/dvc/issues/1696 supporting which should probably be enough for some basic workflows. Let's keep this ticket open to see if there is any interest from the community for specifically box.com. If you would like to implement support for it yourself, take a look at `dvc/remote/` directory, where or drivers for AWS s3, Google Cloud Storage, SSH/SFTP, etc are located, which could be used as a template/example :slightly_smiling_face: 

Thanks,
Ruslan

**Comment by dangadadanga** [comment]
Thanks Ruslan! I'll keep an eye on the ticket.

**Comment by efiop** [comment]
Closing this due to the lack of interest from other users 🙁 If anyone is interested in this or is willing to contribute, please ping us and we'll reopen.

**Comment by pokey** [comment]
This is something I'd love to see.  We use Box with SSO fwiw.  I think our workaround for now will be to use the local Box Drive directory as a local remote, and have an initial step in our `README` telling users to configure Box Drive local directory in local config.

**Comment by efiop** [comment]
@dangadadanga @pokey Also you could mount it as ftp to your local directory and use it as a local remote with dvc. :slightly_smiling_face: Ok, let's reopen this one to see if anyone is willing to implement this, since this is not in the core-team focus.

**Comment by efiop** [comment]
Actually, I'll close this one in favor or https://github.com/iterative/dvc/issues/1696 , since box.com implementation would be through ftp.

**Comment by jorgeorpinel** [comment]
@efiop why favor FTP vs. a specific integration to the Box.com API? https://developer.box.com/reference#upload-a-file. I guess FTP can catch more cases?

**Comment by efiop** [comment]
@jorgeorpinel Good point. box seems to also have python api https://github.com/box/box-python-sdk . Reopening.

**Comment by efiop** [comment]
Closing since there is not enough interest. If you are interested in this, please leave a comment. :slightly_smiling_face:

**Comment by kjnam** [comment]
@efiop I am interested in using Box.com for the remote backend. I wonder if this can be re-opened.

**Comment by efiop** [comment]
@kjnam Hey :) Thanks for your interest! These days we use fsspec as a backend, which has support for ftp https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/ftp.py so box.com could potentially be supported through that (we don't support ftp natively in dvc, but it can be implemented fairly easily). We've been working on  introducing plugin mechanism (e.g. https://github.com/iterative/dvc-plugins and https://github.com/iterative/cookiecutter-dvc-plugin) for such support, and ftp support will likely happen after that, as we are trying to shift from the number of officially supported remotes to the quality of the ones we already have, so we are a bit hesitant to adopt a new remote type until it is well tested.

If you are interested in getting involved, you could just fork dvc and try out fsspec's ftp implementation similar to how we use, for example, webhdfs https://github.com/iterative/dvc/blob/main/dvc/fs/webhdfs.py Any feedback about that would be really helpful.

**Comment by kjnam** [comment]
@efiop Thanks for your prompt response. In may case, Box.com is via my company, so I do not think I will be able to use ftp for Box. At any rate, I will look into what you suggested.

**Comment by nickp60** [comment]
I'd be interested in Box support as well!  Working in healthcare, and only a few storage services are internally approved for sensitive data

**Comment by nickp60** [comment]
Hi @skshetry I'm not familiar with WebDAV. it looks like it was at one point supported but that was depreciated in 2019 https://support.box.com/hc/en-us/articles/360043696414-WebDAV-with-Box

**Comment by skshetry** [comment]
> Hi @skshetry I'm not familiar with WebDAV. it looks like it was at one point supported but that was depreciated in 2019 https://support.box.com/hc/en-us/articles/360043696414-WebDAV-with-Box

The article says that it still works if I am reading it right.

**Comment by nickp60** [comment]
That's my understanding too, but some of the limitations looks pretty prohibitive (eg "Cannot download more than 50 MB")

**Comment by youngdjn** [comment]
I'd also be very interested in support for Box via its native API, for dev work at the [Open Forest Observatory](https://openforestobservatory.org/) and other academic research projects.

**Comment by itcarroll** [comment]
There is an implementation of the fsspec protocol for box: [IBM/boxfs](https://github.com/IBM/boxfs). So ... how do we use that?

**Comment by efiop** [comment]
We don't have the plugin mechanism fully ready yet, but apart from a few hacks, for boxfs one would need to do something similar to https://github.com/iterative/dvc-s3 to wrap boxfs.

**Comment by rtbs-dev** [comment]
Similar situation here, Box is approved for use and hosting DVC data registries that go along with github code would be really, _really_ nice. I assume I should wait for a `dvc-box` type wrapper repository?
