### ISSUE TITLE
init: the welcome message appears even when --quiet is used

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1941]
version: `0.35.7`

To reproduce: `dvc init --quiet`
Expected: No message at all
Current: Displays the following
```
+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|              https://dvc.org/doc/user-guide/analytics               |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: https://dvc.org/doc
- Get help and share ideas: https://dvc.org/chat
- Star us on GitHub: https://github.com/iterative/dvc
```

**Comment by pared** [comment]
I am not sure that should be hidden on 'quiet'. This is quite important information for some users, and might be treated as lack of transparency from our side if implemented. Maybe we should consider adding manual config option to turn this message off?

**Comment by shcheklein** [comment]
I think if someone specifies a `--quiet` option explicitly then they understand what are they doing already and are probably running `dvc init` from a script or something.
