### ISSUE TITLE
Allow `dvc fetch` to target checksums directly

### ISSUE THREAD

**Issue by villasv** [iterative/dvc#1943]
In my understanding, dvc files are good targets because they store data files checksums. It's ergonomic, they work like `refs` in git.

But I think we should be able to fetch files also by checksum directly, no matter the current state of the workspace. In `git`, you can fetch a ref but you can also fetch a specific commit by hash.

My use case is that I have my own diff tooling, which is used by reference testing, that compares the current version of the dataset with the previous version reading it directly from the cache. If the file is not there, currently I have to checkout that commit in git before doing a dvc fetch and then checkout back, which is often impossible because I have pending changes.

**Comment by villasv** [comment]
I have plans to change that workflow to have the old version of the dataset also in the current workspace and have my script not to depend on dvc to find the old version, but that's kind of not the point here. 

Fetching specific versions of a file by hash is the kind of plumbing command that makes sense to exist IMO.

**Comment by efiop** [comment]
```
My use case is that I have my own diff tooling, which is used by reference testing, that compares the current version of the dataset with the previous version reading it directly from the cache. If the file is not there, currently I have to checkout that commit in git before doing a dvc fetch and then checkout back, which is often impossible because I have pending changes.
```

You could use something like `git show reference:file` to show dvc file for specific reference, save it to a temporary file `tmp.dvc` and run `dvc fetch tmp.dvc` :slightly_smiling_face:

**Comment by efiop** [comment]
@villasv Btw, you can now do `dvc get /my/repo mydata --rev <gitsha>` to obtain your data from any git commit without doing a manual `git checkout`. That one seems more suitable, since you don't even have to extract the checksum to pass it to `dvc fetch`. What do you think?

**Comment by villasv** [comment]
Even better indeed :-) thanks for the heads up

**Comment by efiop** [comment]
@villasv In that case, should we close this issue for now? :)

**Comment by villasv** [comment]
The issue itself was not implemented, though it’s not needed anymore. IMO we can close it ;-)
