### ISSUE TITLE
Prevent repo from setting log level

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1952]
Currently, we can set logger level at `dvc/repo.Repo.__init__`:
```       
 level = core.get(Config.SECTION_CORE_LOGLEVEL)
 if level:
        logger.setLevel(level.upper())
```
We should decouple setting log level from `Repo`. 
Some context #1942

**Comment by efiop** [comment]
Maybe we could even remove that logic in 1.0, since it is a part of an old config and there doesn't seem to be a need for config-side loglevel configuration.

**Comment by mroutis** [comment]
@efiop , agree, users are using DVC as a module, they can adjust the log level manually:
```python
logger = logging.getLogger('dvc')
logger.setLevel(...)
```
