### ISSUE TITLE
remote: add support for aliyun oss

### ISSUE THREAD

**Issue by nanaya-tachibana** [iterative/dvc#1954]
I would like to use aliyun oss to store my models. I will follow the implementation of azure to implement this feature.

**Comment by efiop** [comment]
@nanaya-tachibana Great plan! :slightly_smiling_face: Feel free to ping us if you need any help. We have a dev channel #dev-general at https://dvc.org/chat :slightly_smiling_face:

**Comment by efiop** [comment]
@nanaya-tachibana OSS support was released in 0.40.1. Please upgrade 🙂 Big thanks for the PR!

**Comment by mroutis** [comment]
Should we close this? @efiop

**Comment by efiop** [comment]
@mroutis Thanks for the heads up! Closed by https://github.com/iterative/dvc/pull/1961
