### ISSUE TITLE
Parametrize install to choose installed hooks?

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1955]
Currently we have 3 hooks. Depending how discussion in #1551 goes, we might end up with few more. 

Should we parametrize install command to let user choose which hooks to install?
What do you think guys?

**Comment by efiop** [comment]
@pared As long as there is no interest from the community, I think it is not worth bothering with, especially since you could go ahead and disable some hooks after `dvc install` if you so desire :slightly_smiling_face:

**Comment by shcheklein** [comment]
it's too early to judge about the interest, right? :) we are just going to introduce them.

I would at least document this workaround (disable manually) with a link to Git docs. Or may be write a line in the `dvc install` output as well.

In case of DVC too much magic (i.e. too many hooks) might be not what all users expect.

**Comment by efiop** [comment]
We've had 2 hooks for a long long time and no one requested this feature, so if it continues to be that way in the future then maybe no one actually wants it :slightly_smiling_face:

> I would at least document this workaround (disable manually) with a link to Git docs. Or maybe write a line in the dvc install output as well.

:+1:

**Comment by Naba7** [comment]
@pared  It will be really nice to get more number of hooks. I have used ``dvc push`` and ``dvc pull``. What is the third one? Parameterizing install command will be a great idea, but why not use all the hooks.

**Comment by efiop** [comment]
Hi @Naba7 ! We are installing all the hooks that we can right now. There are no git hooks left to utilize for us :( We are thinking about other possibilities to automatically do certain things on git commands or vice-versa: do some git things automatically when running dvc. E.g. `dvc push` -> `git push + dvc push`. The discussion about it is in https://github.com/iterative/dvc/issues/1551. Please feel free to join :slightly_smiling_face:

**Comment by efiop** [comment]
Closing for now due to a lack of interest from the community.
