### ISSUE TITLE
Add support for server side encryption for AWS S3 uploads/copies

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#1967]
For s3 buckets which require encryption, there is no way to upload or copy via dvc, making it impossible to use a protected bucket as a remote. The boto3 upload and copy functions have parameters to specify server-side encryption. It would be great to have support for adding an s3 remote such that all writes to the bucket use the specified encryption.

**Comment by efiop** [comment]
Hi @dberenbaum !

Great idea! I see that you are already familiar with boto3, maybe you would be willing to contribute such a feature? :slightly_smiling_face:  It is pretty simple, you could take a look at `use_ssl` option
```
grep SECTION_AWS_USE_SSL -R dvc
```
as an example. From our side, we will be happy to help with everything we can. :slightly_smiling_face:
