### ISSUE TITLE
checkout: partial directory cache

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1969]
Currently, if, for some reason, you've lost some of the cache files for a part of your directory, dvc will throw assertion error:
```
ERROR: failed to pull data from the cloud
------------------------------------------------------------
Traceback (most recent call last):
  File "/var/akonshin/.virtualenvs/tr/lib/python3.5/site-packages/dvc/command/data_sync.py", line 46, in do_run
    recursive=self.args.recursive,
  File "/var/akonshin/.virtualenvs/tr/lib/python3.5/site-packages/dvc/repo/pull.py", line 27, in pull
    target=target, with_deps=with_deps, force=force, recursive=recursive
  File "/var/akonshin/.virtualenvs/tr/lib/python3.5/site-packages/dvc/repo/checkout.py", line 54, in checkout
    stage.checkout(force=force, progress_callback=progress_callback)
  File "/var/akonshin/.virtualenvs/tr/lib/python3.5/site-packages/dvc/stage.py", line 822, in checkout
    force=force, tag=self.tag, progress_callback=progress_callback
  File "/var/akonshin/.virtualenvs/tr/lib/python3.5/site-packages/dvc/output/base.py", line 228, in checkout
    progress_callback=progress_callback,
  File "/var/akonshin/.virtualenvs/tr/lib/python3.5/site-packages/dvc/remote/base.py", line 370, in checkout
    progress_callback=progress_callback,
  File "/var/akonshin/.virtualenvs/tr/lib/python3.5/site-packages/dvc/remote/local.py", line 353, in do_checkout
    self.link(c, p)
  File "/var/akonshin/.virtualenvs/tr/lib/python3.5/site-packages/dvc/remote/local.py", line 155, in link
    assert os.path.isfile(cache)
AssertionError
------------------------------------------------------------
```

This is because unlike for regular data files, we don't check for cache file existence before linking it. With standalone data files we print a warning that "cache file doesn't exist and file is not going to be created", so we need to do something similar here.

Some backstory: user on ODS was getting this error and turned out that he had ran `dvc gc -c` for some time and then interrupted it, so parts of data were removed and so when he tried to `dvc pull` later, he got this error.

**Comment by efiop** [comment]
Related issue https://discordapp.com/channels/485586884165107732/485596304961962003/580749209205080104 .

**Comment by efiop** [comment]
Also related https://github.com/iterative/dvc/issues/2038

**Comment by efiop** [comment]
For the record: turns out our cache dir optimization is faulty, so we need to use a better way to verify cache integrity quickly. As a possible solution that won't require full cache verification, we could do the following trick. Say we have a cache for directory 1234.dir. Then, create `.dvc/cache/12/34.dir.dir`(or a better name) directory with all the files in it as hardlinks(these will be always possible because the cache is guaranteed to be on the same fs with itself) and then use mtime/inode/size combo that we use for `.dvc/cache` currently to quickly check if anything was deleted or corrupted, since hardlinks will fully reflect that.

**Comment by pared** [comment]
Mentioned cache optimization was introduced in #1526

**Comment by efiop** [comment]
As @Suor noticed, we are doing one SELECT per 1 inode, which will get slow when processing large directories. We could do one SELECT for a batch of inodes to make it much faster. That could be used in addition or instead of #1969 . This approach is less hacky than #1969, but #1969 might be faster, since you are doing one SELECT for 1 inode total, instead of SELECT for all files in batches.

**Comment by efiop** [comment]
Also, another user is having a similar problem:
https://discordapp.com/channels/485586884165107732/485596304961962003/582993878865543169

When RemoteBase.save() tries to optimize disk usage by checking out from cache, changed_cache() reports that everything is fine and so when it then tries to checkout particular new file it hits that assert.

**Comment by efiop** [comment]
Closed with https://github.com/iterative/dvc/pull/2090
