### ISSUE TITLE
Add DVC repro --recursive

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#1989]
It would be nice to be able to use `dvc repro -R` on a directory just like `dvc pull -R`. Hopefully it won't be confusing that dependencies found outside this folder would also be reproduced.

**Comment by mroutis** [comment]
@prihoda , can you explain your use case for this?
I'm imagining that you have a directory with some stage files, and you want to reproduce only the stage files that are found in that directory. If so, how did you arrange your project?

**Comment by prihoda** [comment]
For example, a directory can contain results of one separate data analysis and I want to reproduce them. I know I can create a Dvcfile with all the outputs but it would need to be updated each time I add an output figure.

**Comment by mroutis** [comment]
@prihoda , are the stage files on such directory related? How does the pipeline looks like?
Sorry for bordering you with a lot of questions, just trying to understand better the scenario before implementing this feature :sweat_smile:

**Comment by prihoda** [comment]
Sure I understand 😄It's the same usecase as `dvc push -R` and `dvc pull -R` really. The stages are related for the same reason that they are put in the given directory 😄For example, it can be ROC plots and Precision-Recall plots for a set of trained models.

Directory structure:
```
data/
    models/
    plots/
        rocs/
        pr/
```

I would like to run `dvc repro -R data/plots/`.

**Comment by prihoda** [comment]
Working on it https://github.com/iterative/dvc/pull/2030

**Comment by mroutis** [comment]
Thanks, @prihoda !

**Comment by jorgeorpinel** [comment]
I was just passing by and noticed this issue is still open. Should it have been closed along with PR #2030 ?

**Comment by pared** [comment]
Good point @jorgeorpinel!
