### ISSUE TITLE
`dvc cache -h` and `dvc cache dir -h` have confusing output

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#1994]
1 `dvc cache -h` positional arguments:
```console
$ dvc cache -h
usage: dvc cache [-h] [-q | -v] {dir} ...

Manage cache settings.
documentation: https://man.dvc.org/cache

positional arguments:
  {dir}          Use dvc cache CMD --help for command-specific help.
    dir          Configure cache directory location.
```

The lines under "positional arguments" with `{dir}` and `dir` are confusing to read if you don't already know that `{dir}` is a list of sub-commands. I suggest this since there's just one sub-command option:

```console
positional arguments:
    dir          Sub-command to configure cache directory location.
                 Use dvc cache dir --help for detailed help.
```

<br>

2 `dvc cache dir -h` description:
```console
$ dvc cache dir -h
usage: dvc cache dir [-h] [--global] [--system] [--local] [-u] value

Manage cache settings.
documentation: https://man.dvc.org/cache-dir
```

I think the description should be "Configure cache directory location.", not "Manage cache settings."

**Comment by jorgeorpinel** [comment]
In fact... For problem 1, how about instead of calling them "positional arguments" in these parent commands (dvc cache, dvc metrics, dvc pipeline, and dvc remote), we call them "accepted sub-commands"?

**Comment by shcheklein** [comment]
Agreed, we should change to subcommands or something like that. The "positional arguments" is probably hardcoded in `argparse` library. Hopefully, there is an easy way to override it.

**Comment by efiop** [comment]
Closing as stale
