### ISSUE TITLE
ssh: fix exception reporting during upload

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1996]
See https://github.com/iterative/dvc/blob/0.40.1/dvc/remote/ssh/__init__.py#L237

should be:
```
                        "failed to upload '{}' to '{}'".format(from_info, to_info)
```

Discord https://discordapp.com/channels/485586884165107732/485596304961962003/577533105611735051

**Comment by kurianbenoy** [comment]
can I work on this issue?

**Comment by efiop** [comment]
@kurianbenoy Sure! :) Please let us know if you need any help.

**Comment by efiop** [comment]
@kurianbenoy Btw, be sure to check out our [contribution guide](https://dvc.org/doc/user-guide/contributing). Also, don't hesitate to join [our chat](https://dvc.org/chat), we also have a #dev-general channel there for a development-related discussions, so if you have any questions feel free to ask them there :slightly_smiling_face:
