### ISSUE TITLE
have `dvc cache dir` print the current cache dir when no cmd flags are used

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#1998]
> https://discordapp.com/channels/485586884165107732/565699007037571084/577605813271658519

Currently `dvc cache dir` by itself throws an error and display's the command help. It would be useful to, instead, print the location of the currently used cache dir, so that users can always know what it is (even if it's not specified in `.dvc/config` and thus unknown to `dvc config cache.dir`).

**Comment by cwallaceh** [comment]
@jorgeorpinel How about adding a new command like "dvc cache current" to return the current cache dir?

**Comment by shcheklein** [comment]
@cwallaceh hi! why don't we just reuse the existing subcommand - `dvc cache dir`? Do you have any concerns/see any potential problems in that solution?

**Comment by cwallaceh** [comment]
@shcheklein not really, just an idea of how it could be more clearer, I'll go with reusing the existing `dvc cache dir`

**Comment by jorgeorpinel** [comment]
Thanks for the suggestion @cwallaceh but I agree with @shcheklein it's best to reuse the existing one, which was the original idea 🤓

**Comment by cwallaceh** [comment]
Ok, so for this issue I need to make the "value" argument into an optional "--value" to prevent getting an error, so the command will look like this:

`dvc cache dir` <- Will return the current cache dir
`dvc cache dir --value ./cache` <- Will set the cache directory to ./cache
`dvc cache dir -v ./cache` <- Will set the cache directory to ./cache

I'm not sure you can make optional a positional argument without the "-" or "--" flags

What do you think?
