### ISSUE TITLE
progress: flickers when updating to fast

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2005]
[![asciicast](https://asciinema.org/a/246240.svg)](https://asciinema.org/a/246240)

A solution would be to track the current progress bar and compare it with the new one, and not refreshing it if it is the same.

**Comment by efiop** [comment]
The nice thing about our progress bar is its simplicity, or at least it used to be :slightly_smiling_face:. If we would to go as far as tracking the current frame, I would probably try to give some third-party library a shot once again.

**Comment by casperdcl** [comment]
should also be noted that excessive console output could be speed bottleneck
