### ISSUE TITLE
Misleading warning (Removing before checkout)

### ISSUE THREAD

**Issue by pauloalves86** [iterative/dvc#2016]
During a manual update of a file, I've faced the following message:
>WARNING: data 'foo' exists. Removing before checkout.

It puzzled me, I thought it would overwrite my file, since checkout restores the file based on current DVC file.
I don't know why the file was replaced by the same file. It took a long time (huge file on a HDD).

@efiop provided me a script that reproduces the message:
```
#!/bin/bash     
                
set -e          
set -x          
                
rm -rf myrepo   
mkdir myrepo    
cd myrepo       
                
git init        
dvc init        
                
echo foo > foo  
dvc add foo     
                
echo bar > bar  
dvc add bar     
                
echo bar > foo  
dvc add foo     
cat foo         
dvc status
```

I think a better message and avoiding re-copying the file would be great improvements.

**Comment by efiop** [comment]
Discord context: https://discordapp.com/channels/485586884165107732/485596304961962003/579053609271164929

**Comment by efiop** [comment]
Also when running `dvc run -o metrics.txt "echo 0.9643 > metrics.txt"` twice or if metrics.txt is already in cache.

**Comment by efiop** [comment]
Need to make sure this also works properly for directories.
