### ISSUE TITLE
Google Drive

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#2018]
Based on a conversation with @ternaus ...

Many people use G-drive to share data and models (through web-UI). This is the drive almost everyone has.

Moreover, people from academia can easily get unlimited storage for a lifetime (even after leaving academia). Which makes GDrive default storage from many of these guys.

It might worth to implement GDrive support in DVC to cover people who play with ML outside of work: students, Kaggle-players and other enthusiasts.

From the implementation point of view, It looks like Google Drive has a decent REST API: https://developers.google.com/drive/api/v3/about-sdk

**Comment by antonkulaga** [comment]
Looks like a super-useful feature

**Comment by dmpetrov** [comment]
@iterative/engineering should we close this or something still needs to be implemented?

**Comment by shcheklein** [comment]
yes, can be closed. It's implemented, documented, released. There is a list of improvements - mostly code and tests + one to get tokens with increased limits to simplify on-boarding potentially - https://github.com/iterative/dvc/issues/2865
