### ISSUE TITLE
dvc run jobs option not respected

### ISSUE THREAD

**Issue by bon** [iterative/dvc#2019]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

When I run `dvc pull -j 32` i expect many threads/processes running the md5sums and transfers but it remains at a single one. 

Version 0.40.2 of dvc on Arch Linux 4.9

**Comment by efiop** [comment]
Hi @bon ! Thanks for reporting! We'll investigate.

**Comment by pared** [comment]
@bon What kind of remote are you using? Local or different?

**Comment by bon** [comment]
> @bon What kind of remote are you using? Local or different?

It's local.

**Comment by efiop** [comment]
@bon md5s are currently computed in a single thread, see https://github.com/iterative/dvc/issues/2073#issuecomment-497583655 related to improving that. As to transfers, I've confirmed that the transfer itself is respecting --jobs. I think the issue you are repoting is related to the fact that we are not using --jobs when collecting status before pull/push. We are currently solving that issue in https://github.com/iterative/dvc/pull/2044 . Stay tuned, fixes should be coming soon! :slightly_smiling_face: Closing this issue in favor of the linked ones for now. Please feel free to reopen.
