### ISSUE TITLE
Messages as constants

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2026]
Find all usages of messages duplicated in code and tests, extract those messages to class constants and reuse them in tests.

**Comment by mroutis** [comment]
I'm not sure about this one, we have messages that are not "constant" (that means, we use some string interpolation).

Also, I don't think that tests should require to modify the API (that means, adding an attribute/property to a class just for the sake of testing).

**Comment by efiop** [comment]
@mroutis If that makes testing easier and doesn't change public API, then it is totally ok and much better than just copy-pasting stuff from code to your test. There is a balance though, and there are cases when it is easier and better to just copypaste.

**Comment by shcheklein** [comment]
my 2 cents - it feels that reusing strings in code and tests simultaneously means leaking you actual code into tests. It defeats the purpose of testing to some extent. For example, if you edit a message now in code and make a mistake (or if you changed it by mistake - like remove a new line) there is a chance you will catch it with tests. It would not be the case with the proposed change.

**Comment by jorgeorpinel** [comment]
Interesting point Ivan. Although another use for extracting message strings in the future could be i18n.

Anyway, I noticed a similar problem with help messages from command `-h` outputs: they have to be repeated in the autocomplete scripts (which aren't Python) anyway so I guess we'll always have this kind of text duplication problems in the repo 😢

**Comment by efiop** [comment]
@jorgeorpinel With autocomplete there is no way around that, you have to copy things with regular bash/zsh scripts. What we could do there is to use something like https://argcomplete.readthedocs.io/en/latest/ , but it requires some special setup too, which might be even less familiar than zsh/bash.

**Comment by efiop** [comment]
We've had discussions about it earlier and decided to use strings instead. Closing.
