### ISSUE TITLE
Add command to prune data older than a given date (locally or on remote)

### ISSUE THREAD

**Issue by mhham** [iterative/dvc#2032]
It would be nice to be able to clean the dvc cache in a local or remote repository, by removing data older than a given date.

This is especially useful for huge datafiles which may fill up the storage quite fast.

For the moment, there is the `dvc gc` command that allows to clean everything in the cache except the files corresponding to the current `.dvc` files, but some more flexibility might be useful.

Once again, thanks for the great work !

**Comment by efiop** [comment]
Hi @mhham ! Thanks for this request! We have a very similar ticket already https://github.com/iterative/dvc/issues/678 that I'll close this one in favor of.
