### ISSUE TITLE
retrieve cached version of file to compare to currently checked out version

### ISSUE THREAD

**Issue by brbarkley** [iterative/dvc#2033]
**Problem**: 
I find myself in some instances wanting to retrieve one or multiple cached version(s) of a file to compare to the currently checked out version. Usually, this is out of desire to quickly compare model results from different specifications/versions. 

Say, I might want to throw together some rough tables for comparison based on different model outputs and I'm not sure at this point if it warrants incorporating said tables into the dvc pipeline. I'm more in a scratchpad environment and not editing my underlying code base. I'm experimenting.

**Current solution:** 
Currently, because my data is small enough, I can put one of the model output files in question under git control and run `git show <tag-name>:<file-name> > <local-version-of-cache-file>`. Note, I save this file locally to disk in a git ignored location because it's more or less just for temporary use. Then, I'll create a comparison table between it and the version at the HEAD of my git branch. Okay for now, but for larger data, this will be problematic with git. 

**REQUEST:** 
**Could DVC be used to quickly retrieve a specific version of a file associated with a git tag or branch from its cache for the user to access and compare with the currently dvc checked out version similar to what `git show` allows with files under git control?**

**Other solutions attempted:** 
I've tried to use `dvc metrics show` and its useful in some narrow cases, but I feel like I've reached its limits. For example, `dvc metrics show` would be much more useful if it returned its output in some standard format, perhaps the format of the input metric files (e.g., json if json, csv if csv, etc.). The output would then be useable as some kind of input into a formatted table or chart. It's also quite slow (in the minutes order of magnitude...which is maybe not the slow in the grand scheme of things...but feels clunky) when returning metric files across tags or branches. 

Thanks for considering,
@brbarkley

**Comment by efiop** [comment]
@brbarkley Great request! You might find this discussion interesting https://discordapp.com/channels/485586884165107732/563406153334128681/578610283291869194 .

We also have initial implementation of `dvc diff`, that is able to simply show files added/removed between revisions, but ideally we would like to see it being able to show `git diff`-like output for text and supported binary files. Maybe you would be interested in something like that? If you are interested in actually getting direct paths to cache files based on a particular git revision, take a look at the link above, there is a user that is doing that through our python API.

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/issues/2058 .

Also, @brbarkley you might find `dvc get` feature interesting. You could use it to retrieve any dvc-tracked output from any git/dvc project. E.g. `dvc get /path/to/myrepo path/to/data/in/repo --rev mygitbranch`
