### ISSUE TITLE
config: should `cache.protected` be hidden and automatic?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2041]
Could/Should the `cache.protected` mode be hidden to the user, enabled automatically for `cache.type` `hardlink` or `symlink`, and disabled otherwise?

Just wondering what's the value of having the user manually configure something that is always required for those cache link types.

**Comment by efiop** [comment]
There was a debate over whether or not we should stay with `reflink,hardlink,symlink,copy` with `protected` enabled by default or if we should switch to `reflink,copy` by default. Currently we've chosen the latter one, which eliminates the need for protected  mode being enabled by default for those links. And `hardlink,symlink` are now kinda an "advanced" mode, in which user can choose to either enable protected mode or keep it disabled. We should definitely make it enabled by default, so the risk of corrupting your cache is lower. Thanks for the heads up!

**Comment by jorgeorpinel** [comment]
So just to confirm, do you agree that `cache.protected` should be enabled automatically when the `cache.type` in use is `hardlink` or `symlink`, and disabled automatically when it changes to `reflink` or `copy`? And that it would then be unnecessary to even expose `cache.protected` for the user to set manually with `dvc config`? Thanks

**Comment by efiop** [comment]
@jorgeorpinel I agree with everything except

> And that it would then be unnecessary to even expose cache.protected for the user to set manually with dvc config? 

that makes me think whether or not that config option could be useful or not any longer... Seems like it is indeed useless. Might need to give it a final thought before removing it.

**Comment by mroutis** [comment]
What's the conclusion on this one? @iterative/engineering 

I'd like to remove it, indeed

**Comment by jorgeorpinel** [comment]
So far all in favor, I think. ✋

**Comment by shcheklein** [comment]
👍
