### ISSUE TITLE
.gitignore not ignoring files with square brackets

### ISSUE THREAD

**Issue by cbecker** [iterative/dvc#2043]
Conditions to reproduce: I am trying to `dvc add` a file that contains brackets in the file name, like `[4] hello.png`. The .gitignore file contains the same text as the file name, but it doesn't work because git will interpret the square brackets differently: https://superuser.com/questions/1125249/filenames-having-square-brackets-not-ignored-by-gitignore

A solution is to add a backslash to [ ] , as \[ and \]. I believe the same issue may be happening with '?'

(at least happens on Linux, but I think it extends to other platforms too)

**Comment by shcheklein** [comment]
@cbecker good catch! Looks like we need to escape other special symbols as well - https://git-scm.com/docs/gitignore . At least leading !, * . I'm not sure if can overescape them "safely", i.e. - `\*\*\*` should be parsed as `***` w/o any special meaning.

I believe, the code to fix it located at:

`dvc/scm/git/__init__.py:134 - _add_entry_to_gitignore`
