### ISSUE TITLE
gc: unused arguments

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2046]
Might be a bug https://github.com/iterative/dvc/pull/2029#issuecomment-494268568

**Comment by Suor** [comment]
We have many arguments in many functions and methods, which might be not used. It could be beneficial adding `pylint` or other tool to check it to our pipeline.

**Comment by efiop** [comment]
@Suor Yes, we've been planning to enable pylint as a forced check along black and flake8 for a long time, but just didn't have time to go through the code base and clean everything up(e.g. with docstring checks disabled for now, since fixing those is too much hustle).
