### ISSUE TITLE
overview at the end of `dvc repro` and the deterministic feature

### ISSUE THREAD

**Issue by mastaer** [iterative/dvc#2050]
Hey, we talked about this feature in our telephone conference at wednesday.

Initial situation:
I build a pipeline (+execute it) and share **only the git repository** to others. This git repository contains all the code and dvc files needed to reproduce the entire pipeline. Additional there are also the metric files and the hash sums in the dvc files.
**The user who can only see my git can't see the dvc repo. So all cache files for him are missing!**

What I want:
I want guarantee the user, that just clone my git repository, that my resulst comes from the same pipeline!

**First Feature Request: overview at the end of `dvc repro`**
The user cloning my git repository is now running `dvc repro -P`, and the user sees the following table at the end of the pipeline as output.
*The difference to `dvc status`:*
-  Some steps need to be reproduced for the user because he has missing output files that are cached by dvc.
- If he reproduces the pipeline with `dvc repro -P`, the hashes are overwritten, so he has no chance of seeing that this are the same results or not. (This could manage the third column in the table.)

| Stages       | Reproduced | Changed | Info
| ------------- | ------------- | ------------- | ------------- |
| pull_data.dvc              | yes  | no |  -
| preprocess_data.dvc  | yes  | no |  -
| visualize.dvc               | yes  | no |  -
| train_model.dvc          | yes  | yes | models/model1.npy, tensorboards/tensorboard1, ... 
| test_model.dvc           | yes  | yes | metrics/metric1, summary.rd, ...
| visualization1.dvc       | yes  | yes |  img3.png
| visualization2.dvc       | yes  | no |  -
| visualization3.dvc       | yes  | yes |  img1.png

*The problem with the first feature request:*
Many ML scripts cannot (or will not) be written to achieve exactly the same results every time. [You can see how hard this can be here.](https://www.youtube.com/watch?v=Ys8ofBeR2kA&t=623s). This is why I want to ask for a second Feature:

**Second Feature Request: the deterministic feature**

I would like to have a determenistic flag in all DVC files that can be used for any DVC stages and/or other dependencies and describes whether this is deterministic or not. For example:

If I have the following Pipeline:
![image](https://user-images.githubusercontent.com/16793027/58344945-639d0480-7e57-11e9-850a-426079550027.png)

I want that all files that are none deterministic or depend on a non-deterministic stage or dependencies get a *second* checksum. So all in the blue square. If this feature is interest, than we would need to talk about how the *second* checksum could be calculated. One example could be:

(first) checksum of all deterministic stages + own (first) checksum ====== a function ======> the *second* checksum for this non-deterministic stages and output files.

`dvc check deterministic`
Output:
```
Dependencies and stages that are deterministic:
   - dep. 1
   - dep. 2
   - dep. 3
   - dep. 4
   - dep. 5
   - Stage 1
   - Stage 2
   - Stage 5
Dependencies and stages that are none deterministic:
   - Stage 3
   - metric 1
   - metric 2
Dependencies and stages that are deterministic but depend on a none deterministic stage:
   - Stage 4

Check output-files by the given deterministic stages:
  - metric 1: is valid
  - metric 2: is valid
```

*Why could I want this feature?*
A user who clones my git repository can now see **without reproducing the entire pipeline** whether the metric file he can see really comes from that pipeline or not. So it's a little protection against fraud for the user. You can still cheat, but it would make it a lot harder.

**Comment by efiop** [comment]
Hi @mastaer !

I think our `dvc status` should do what you want already. If you place files where they should be, it will check that they have proper checksums and if everything is fine it will print "Pipeline is up-to-date. Nothing to reproduce". If anything doesn't match, it will say something like:
```
stage1.dvc:
       output1: checksum mismatch
```
Would that suit your scenario?

**Comment by mastaer** [comment]
Hey @efiop,
thank you for your prompt reply. But no ```dvc status``` does not fit my use case. The user that only have access to the git repository and not to the dvc repository have a lot of missing files. If he wants all files, he has to reproduce the results.

In the first use case (the table), the information that the newly generated metric and the old metric (which was previously in the git repro) are the same is lost.

In the second use case, the metrics will always be different due to the reproduction of the code. So there is no way to say that the metric from the git was really created by this pipeline and not by an older version of it. This is why I think that it would need a new flag, which I called deterministic.

What do you think?

**Comment by efiop** [comment]
Sorry, might be missing something. Dvc already by-default assumes that everything is deterministic and it has all checksums listed in the dvc files. Missing files is fine, `dvc status` is able to look at every and each stage file and see if any of its direct dependencies/outputs have changed. I might be missing some context, as my internet connection went out during our video call, and I've missed most of the meeting. Maybe other guys understand this better? (@mroutis , @pared , @shcheklein , @dmpetrov )

**Comment by mastaer** [comment]
Hi @efiop, thanks, I've updated the feature request. Please let me know if it's clearer now or not.

**Comment by pared** [comment]
Lets maybe use some concrete specific example.

Use case - non deterministic training : for example CNN trained on GPU.

1. End user (reproducer) does not have access to Dvc Remote (for example SSH), so he/she cannot  just `dvc checkout`
2. We still want this user to be able to reproduce pipeline
3.  @mastaer would like some kind of second checksum that would let user verify that even though his (for example) metric is a bit different than original, the reproduction has been done using the same stages and code that @mastaer has prepared.
Am I right so far, @mastaer ?

**Comment by efiop** [comment]
Big thanks to @pared for helping me understand this during our discussion in a private chat! :slightly_smiling_face:

@mastaer A few more questions:

1) So with that `dvc repro` summary table, do you also want it to be parsable or is it only for displaying purposes?

2) About that `deterministic` feature. As I understand, you want dvc to keep a separate checksum for a deterministic subset of dvc files, right? I imagine if it wasn't about `subset` thing, git sha as is would cut it for you? Or how strong of validation do you need? We are currently using md5-only, which seems pretty weak for any real security purposes. E.g. even when talking about our cache files, tossing up an md5 is pretty doable. Luckily, we have [a support for other hash types coming](https://github.com/iterative/dvc/pull/2022).

**Comment by mastaer** [comment]
thanks, @pared for your clear and simple explanation. That's exactly what I meant.
Also many thanks to @efiop, who tries to understand my gibberish description ;-)

to your questions:

1. I thought on a table only at the end of `dvc repro`, so it's just for display.

2. No, you don't understand me here. I want that a owner can set a `deterministic flag` (True / False) on all stages. When I run the pipeline, I want all stages that are `non-deterministic` or depend on a `non-deterministic` stage to get a second checksum. And this checksum gets calculated with all checksums of the `deterministic` stages.

**Comment by mastaer** [comment]
What does this mean for a possible implementation?

- In the command `dvc run` it must give new parameters. Like `-od` for a deterministic output that gets cached. And more parameters like: `-Od`, `-md` and `-Md`.

- If I run the pipeline or a stage, then all stages that are `non-deterministic` gets a second checksum that is calculated by the dependent `deterministic` stages.

- With a new command (i.e. `dvc check deterministic`) I could always check a `non-deterministic` file if this is a **valid** output file. Valid has here the meaning, that this output comes from this code and this pipeline.

**Comment by efiop** [comment]
@mastaer 

> If I run the pipeline or a stage, then all stages that are non-deterministic gets a second checksum that is calculated by the dependent deterministic stages.

Why would you need another checksum though? Your stages depend on particular files, so if your stage depends on an output of some non-deterministic stage, then it will have the checksum for that output as a dependency.

> With a new command (i.e. dvc check deterministic) I could always check a non-deterministic file if this is a valid output file. Valid has here the meaning, that this output comes from this code and this pipeline.

What is the `valid` output though? If it was indeed created by that particular stage, right? If so, we have output checksum along with stage file checksum already, that could serve that purpose.

**Comment by mastaer** [comment]
Hi @efiop, I am sorry but I still think we don't understand each other right... Maybe I miss something... I think the only way we can understand each other is if we look at an example. I need some time (because I'm really busy at the moment), but I'll create one. And maybe with this example, you can explain to me what I missed.

**Comment by mastaer** [comment]
Hi @efiop, it needed a lot of time but now I created an example :) And I think you are right. You need already really bad habits to manipulate the pipeline.

But here is the example:
```
rm -R test
mkdir test
cd test

git init
dvc init

# a deterministic process
dvc run --no-exec -o someout.txt "echo HELLO_WORLD > someout.txt"

# a none deterministic process
echo "import numpy as np
with open('someout.txt') as f:
    data = f.read()
result = np.sum([ord(d) for d in data]) + np.random.randint(1000)
np.save('someout2.npy', result)
" > somecode.py
dvc run --no-exec -d someout.txt -m someout2.npy "python somecode.py"

dvc repro -P

git add -A
git commit -m 'pipeline was executed'

dvc status



# simulate that a other user just downloaded the git repo
# now he should see that the someout2.npy was created with this pipeline !
rm someout.txt
dvc status

OUTPUT:
# someout.txt.dvc:
# 	 always changed
# 

# manipulate the output file
echo "bla" > someout2.npy
dvc status

OUTPUT:
# someout2.npy.dvc:
#	 changed outs:
#		 modified:           someout2.npy
# someout.txt.dvc:
#	 always changed


```
