### ISSUE TITLE
add/run: preserve comments and `meta` when running again

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2055]
e.g
```
echo foo > foo
dvc add foo
echo "# my comment" >> foo.dvc
echo "meta: mydata" >> foo.dvc
rm foo
echo bar > foo
dvc add foo # will remove the comment and the `meta`
```
same with `run`.

Related https://github.com/iterative/dvc/issues/1799

**Comment by Suor** [comment]
I see two distinct cases to dvc run, one is running a completely new command the other one is iterating other the previous one.  Preserving comments only makes sense in the latter case, however, it's impossible or at least very hard for dvc to know what do you mean.

**Comment by Suor** [comment]
Is this still relevant?

**Comment by efiop** [comment]
@Suor Good points. Looks like no one asks for this, so let's close it for now.
