### ISSUE TITLE
dvc: refactor DataCloud, Cache and friends

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2056]
Looks like we have several places where we manage remotes, which have overlapping functionality and code. One example of such functionality is creating a remote from config and/or name. 

Now we have: 
- `DataCloud._init_remote()` plus other its methods
- `Cache._get_remote()`
- `Config.get_remote_settings()`
- `CmdRemote*`
- `dvc.remote.__init__`

We need one place to create a remote from config/name, add or update a remote, list them and so on whether it be `DataCloud`, `Cache` or `dvc.remote.__init__`. 

Other related issues, which might be or not fixed by the same refactoring:
- we use `remote` to refer to both remote name and remote object through out our code, but they are not interchangable
- `DataCloud.pull()/.push()/.status()` and `Remote.pull()/.push().status()` have complicated interface, e.g. they don't accept `Output` objects as targets as one might expect, but their dict serialization with additional `branch` key 

This is a takeaway from #2053.

**Comment by efiop** [comment]
Closing as stale
