### ISSUE TITLE
pkg: `dvc pkg` has no `-h` option

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2065]
It still gives you the usage but just because that's the default behavior for errors in the command syntax:

```console
$ dvc pkg -h                
ERROR: the following arguments are required: cmd

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
usage: dvc pkg [-q | -v] {install} ...

...
```

**Comment by efiop** [comment]
@jorgeorpinel `dvc pkg` is intentionally hidden for now. See `add_help=False,` at https://github.com/iterative/dvc/blob/master/dvc/command/pkg.py#L39 .

**Comment by jorgeorpinel** [comment]
Got it. OK I assume it will exist when this is released then. Will include it in the cmd ref. Thanks
