### ISSUE TITLE
List all tracked files

### ISSUE THREAD

**Issue by nisace** [iterative/dvc#2067]
Hi,
It would be nice to have a command similar to `git ls-files` to show all the files tracked by DVC.

The `dvc pipeline show` command exists but it expects a target and thus only shows files that are part of the selected pipeline(s). In some cases, one may have files outside of any pipeline.

For example, a small test data file that is not part of a pipeline because no data is generated from it. It is just used to run a test script that prints the results.

Thanks !

**Comment by dashohoxha** [comment]
Related discussion: https://github.com/iterative/dvc.org/commit/289e03b8c6e8245ce504f8d230a776eed1cf04f8#r35041286

**Comment by jorgeorpinel** [comment]
@nisace thanks again for this request. We are moving in this direction, feel free to join the discussion in #2509. I'm closing this issue to avoid duplicity.
