### ISSUE TITLE
scripts: update bash autocomplete script

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2069]
As detected in https://github.com/iterative/dvc/pull/2064#pullrequestreview-243033761 ~~(wait for that PR to merge)~~

Script located in https://github.com/iterative/dvc/blob/master/scripts/completion/dvc.bash

- [x] So commands and their options are current (previous update: #1732)
- [x] It would be nice that it completes file names appropriate to the context as indicated in the docs (per [this](https://discordapp.com/channels/485586884165107732/485596304961962003/586169235735052319) discord message).

**Comment by Naba7** [comment]
@shcheklein  Can you please explain me what has to be done here? I guess one of the tasks is completed.

**Comment by mroutis** [comment]
@Naba7 , the autocompletion script is outdated https://github.com/iterative/dvc/blob/master/scripts/completion/dvc.bash

It means that it's missing some commands and options, one half of the task is to make sure that all the commands are supported with their respective flags.

And the other one is to add support for completing file names, for example: `$(compgen -G '*.dvc')`.

**Comment by Naba7** [comment]
Alright, Thanks. I am checking onto that.

**Comment by jorgeorpinel** [comment]
Yet another desirable improvement is to include command and option descriptions to the autocomplete like in the [zsh script](https://github.com/iterative/dvc/blob/master/scripts/completion/dvc.zsh) but I'm not sure bash supports that. Thanks

**Comment by mroutis** [comment]
@jorgeorpinel , I think it Bash doesn't support such thing :sweat:

**Comment by jorgeorpinel** [comment]
Hi. PR #2205 may close this. Can someone who uses bash check? @Naba7 perhaps. (You'd have to pull from my fork and run DVC on [dev mode](https://dvc.org/doc/user-guide/contributing#development-environment) from there.)

**Comment by shcheklein** [comment]
@jorgeorpinel how can #2205 close this? I'm not sure I'm following this :)

**Comment by jorgeorpinel** [comment]
with the changes to scripts/completion/dvc.bash. See https://github.com/iterative/dvc/pull/2205/files#diff-52c40123385500205889d77541831837

**Comment by jorgeorpinel** [comment]
This was closed accidentally with e04e4c0 BTW. Please re-open (I can't), not sure that's all the updates needed to the bash autocomplete script.

**Comment by efiop** [comment]
@jorgeorpinel Reopened.

**Comment by efiop** [comment]
Aand closed with #2195 :slightly_smiling_face:

**Comment by efiop** [comment]
Ok, but the subcommands for bash are not supported yet. This might be the solution https://stackoverflow.com/questions/17879322/how-do-i-autocomplete-nested-multi-level-subcommands . Will keep this open for now.

**Comment by nik123** [comment]
Does the lack of subcommands blocks the #2181 ? Commands and file names completion already seems as a great improvement and having it out of the box would be nice.

**Comment by efiop** [comment]
@nik123 It doesn't :slightly_smiling_face:  As I've mentioned in https://github.com/iterative/dvc/issues/2181#issuecomment-505134891 , we can totally include what we have already into our packages, and update our bash scripts later.

**Comment by jorgeorpinel** [comment]
> Aand closed with #2195 🙂

Haha thanks.

> https://stackoverflow.com/a/17881946/761963

Def. worth trying 😃

**Comment by Naba7** [comment]
Yes, I will check into this @efiop @jorgeorpinel

**Comment by Naba7** [comment]
The previous script only showed files not the commands. I have updated and added commands as well as files.

**Comment by nik123** [comment]
@Naba7 does it really work with files? I have just downloaded the latest version from [here](https://github.com/iterative/dvc/blob/01e2fe379caeff52e1f00f6d2143dbec18069f47/scripts/completion/dvc.bash) and put it in `/etc/bash_completion.d` it doesn't complete file names. 

For example I have `train.dvc` file in my repo. I type `dvc status tr` and press tab key. I expect that command will be completed with `train.dvc` but nothing happens.

**Comment by Naba7** [comment]
I am still working on it.
