### ISSUE TITLE
Improve message that says to use git add

### ISSUE THREAD

**Issue by ricardoserradas** [iterative/dvc#2076]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

* DVC version 0.41.3

After running a command like `dvc run`, we're presented the following message:

```bash
Running command:
	python src/featurization.py data/prepared data/features
The input data frame data/prepared/train.tsv size is (20108, 3)
The output matrix data/features/train.pkl size is (20108, 5002) and data type is float64
The input data frame data/prepared/test.tsv size is (4889, 3)
The output matrix data/features/test.pkl size is (4889, 5002) and data type is float64
Adding 'data/features' to 'data/.gitignore'.
Saving 'data/features' to '.dvc/cache/03/f88305ab6a26beaf43e7daa3a992a3.dir'.
Saving information to 'featurize.dvc'.

To track the changes with git run:

	git add data/.gitignore featurize.dvc
```

My point is specifically with this part: `To track the changes with git run`. My first understanding was that we need to use `git run` to track changes, whereas we need to `run` the `git add` command to track changes.

So the change I'm submitting in a second just adds a comma to this message. It will then be like below:

`To track the changes with git, run`

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/2077
