### ISSUE TITLE
`dvc push` command should return non-zero code if push operation has failed

### ISSUE THREAD

**Issue by nik123** [iterative/dvc#2078]
**Use case:**
I want to push my changes to DVC remote repository and then push my git changes to the git remote repository. I want to push to git **only** if `dvc push` was successful.

In Unix-like system one would expect to execute it with the following bash command:

```
dvc push && git push
```

If I use SSH and I haven't configured SSH authentication properly then `dvc push` will produce the following error:

```
ERROR: failed to push data to the cloud - No authentication methods available
```

In Unix one would expect that `git push` wouldn't be executed. However bash still runs `git push` command because dvc returned zero. Therefore source code changes along with *.dvc files has been pushed to remote.

**Comment by efiop** [comment]
Hi @mhham ! This has the same reasons as described in https://github.com/iterative/dvc/issues/2038 and due for the change. I'll close this one in favor of https://github.com/iterative/dvc/issues/2038, if you don't mind :slightly_smiling_face:  Please feel free to reopen.
