### ISSUE TITLE
metrics show all tags includes master branch

### ISSUE THREAD

**Issue by ricardoserradas** [iterative/dvc#2079]
I was going through the `compare-experiments.md` and I faced the following expected output:

```bash
$ dvc metrics show -T

baseline-experiment:
    auc.metric: 0.588426
bigram-experiment:
    auc.metric: 0.602818
```

But mine was:

```bash
$ dvc metrics show -T
Working Tree:
	auc.metric: 0.620421
master:
	auc.metric: 0.588765
baseline-experiment:
	auc.metric: 0.588765
```

Although the output shows an understandable message, I assume there might be a previous step to create the `bigram-experiment` due to the presented context.

I see two solving options here:

- Adding the steps to create the `bigram-experiment` or
- Updating the expected output from `dvc metrics show -T`

**Comment by efiop** [comment]
Also need to adjust the docs.
