### ISSUE TITLE
status: remove  `--show-checksums`

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2085]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

Currently, `status --show-checksums` will have same output as `status`. Make it display as described in [options](https://dvc.org/doc/commands-reference/status#options).

**Comment by pared** [comment]
Reproduction script:
```
#!/bin/zsh

rm -rf repo
mkdir repo

cd repo

git init >> /dev/null && dvc init >> /dev/null

mkdir data

echo 1 >> data/1
echo 2 >> data/2

dvc add data >> /dev/null
echo 3 >> data/3

dvc status --show-checksums
```

**Comment by efiop** [comment]
From docs `Applies only if --cloud is specified.`. Works for me with `-c`.

**Comment by shcheklein** [comment]
Was the intention of the ticket to implement it for both local and cloud? I think documentation was written to represent the things as they now, not how they should be.

**Comment by efiop** [comment]
Maybe @pared will correct me.

**Comment by pared** [comment]
At the beggining I though it was bug, but as @efiop mentioned, docs specify when it should work.
I didn't have in mind whether it should work locally, because I didn't noticed in docs that it should work only for `--cloud`.

**Comment by shcheklein** [comment]
@pared does not matter what docs specify (they are written to reflect the current state in most cases). It can be a bug (including docs). I don't see any logical reasons to not support it in a regular `status` tbh. @efiop what was the initial intention for `--show-checksums`? Did someone ask for it? Or we just implemented it in-advance?

**Comment by efiop** [comment]
@shcheklein status without `-c` just doesn't need this, really, no need to implement it. `--show-checksums` with `-c` was our initial implementation, and we've then abandoned, leaving `--show-checksums` for debugging purposes. We can simply remove `--show-checksums` for good. Let;s repurpose this issue.

**Comment by shcheklein** [comment]
should we remove it everywhere then - pull/push/gc, etc? I think it still can be useful to see what's going on. Reopening this to make the decision and remove if we are all agree. Btw, can I see checksums in the debug logs with `-v`? Just to have at least some way to track the stuff.

**Comment by efiop** [comment]
@shcheklein sure we need to remove it from everywhere. Yes, you can see them in -v. No, it is not really useful, since you can see output names and they map pretty well with checksums.

**Comment by shcheklein** [comment]
@efiop sounds good.

**Comment by kurianbenoy** [comment]
Can I work on this issue @shcheklein ?

**Comment by shcheklein** [comment]
@kurianbenoy absolutely! :)
