### ISSUE TITLE
dvc: unify class naming

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2089]
E.g. RemoteS3 -> S3Remote, DependencyS3 -> S3Dependency, etc.

**Comment by nik123** [comment]
Is it still relevant? May I implement it?

**Comment by efiop** [comment]
Hi @nik123 !

Sure! :pray:  Could start with start with unifying Remote* class names. You can find all of them in `dvc/remote/` dir. We should follow pep8 with those.

**Comment by nik123** [comment]
@efiop deepsource says that several abstract methods of `BaseRemote` are not implemented in subclasses. Should they be implemented as well as a part of this issue?

**Comment by efiop** [comment]
Keeping open for other classes.

**Comment by efiop** [comment]
> @efiop deepsource says that several abstract methods of BaseRemote are not implemented in subclasses. Should they be implemented as well as a part of this issue?

@nik123 Not really, this one is purely about naming. Could do that one later too, though :wink:

**Comment by nik123** [comment]
@efiop , which classes should be next?

**Comment by efiop** [comment]
@nik123 Actually, I think that's it! :tada: Thank you so much!
