### ISSUE TITLE
add: using a remote path doesn't load the configuration

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2092]
version: `0.41.3`

```bash
dvc remote add ssh ssh://localhost
dvc remote modify ssh user none
dvc remote modify ssh port 111
dvc config cache.ssh ssh
dvc add remote://ssh/something
```

`ERROR: unexpected error - [Errno None] Unable to connect to port 111 on 127.0.0.1 or ::1`

:warning: **Couldn't reproduce the issue** :warning: 

More context:
https://discordapp.com/channels/485586884165107732/485596304961962003/585454599117471744

**Comment by thomasryck** [comment]
I couldn't reproduce the issue with your command workflow.
The only difference I see, is that I was using:
dvc add ssh://sshcache/incident_old.csv
and 
in your workflow it is:
dvc add remote://sshcache/incident_old.csv

**Comment by thomasryck** [comment]
https://dvc.org/doc/user-guide/external-outputs

I guess the doc is misleading on that point

**Comment by mroutis** [comment]
@thomasryck , thanks for the notice!

The problem here is that when you are using the `ssh` syntax you need to provide everything on the URI (user, port, etc.), however, with `remote://` the configuration it is going to be fetched from such remote.

(cc: @jorgeorpinel maybe is worth to open an issue about this on the docs :thinking: )

**Comment by jorgeorpinel** [comment]
Is this the issue? https://github.com/iterative/dvc.org/issues/411

**Comment by ryokugyu** [comment]
> I couldn't reproduce the issue with your command workflow.
> The only difference I see, is that I was using:
> dvc add ssh://sshcache/incident_old.csv
> and
> in your workflow it is:
> dvc add remote://sshcache/incident_old.csv
![dvc-error](https://user-images.githubusercontent.com/16274905/59524640-13631080-8ef2-11e9-9bfd-e3d9e63cf61d.png)
I am getting this error while running the `dvc add ssh://sshcache/car.txt`
