### ISSUE TITLE
Optimize state database access

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2093]
During our work on #1969 and reopening of #1526 
We realized our approach to handling state database updates could be improved.
Currently, all operations on state database are single file oriented. When inserting or getting file status we perform database operations per file/inode. Even if (for example) we are adding whole directory, we will iterate over all files inside and insert metadata (mtime, size, md5 etc) one by one. 

We could reduce time spend on database handling, if we modify our code to handle those operations in bulk. 

The problem is, that our code reflects "single file" approach, so modifying state database will not be enough to introduce this change. 

Refactor code interacting with database, so that db operations can be performed in batches.

**Comment by efiop** [comment]
Closed with https://github.com/iterative/dvc/pull/2090

**Comment by efiop** [comment]
Reopening for state db command batching.
