### ISSUE TITLE
Commit changes by dependency

### ISSUE THREAD

**Issue by legendawes** [iterative/dvc#2094]
Be able to dvc commit changes in a file to all .dvc file that depend on the changed file.

For example, load.dvc and preprocess.dvc depend on used_sources.py.
A small change in used_sources.py would require manual commit to all .dvc files:
dvc commit load.dvc
dvc commit preprocess.dvc.

Suggested feature would allow to do the following:
dvc commit --by-dep used_sources.py,

**Comment by efiop** [comment]
Hi @legendawes !

Thanks for a feature request! Continuing our discussion from ods, here is a basic walkthrough for what needs to be done to implement this feature.

1) Add `--by-dep` flag to our CLI from `dvc commit`
https://github.com/iterative/dvc/blob/master/dvc/command/commit.py#L67

2) Pass `self.args.by_dep` to API
https://github.com/iterative/dvc/blob/master/dvc/command/commit.py#L24

3) In API pass `by_dep` to collect method
https://github.com/iterative/dvc/blob/master/dvc/repo/commit.py#L2

4) In `collect` method, make it walk through all stages and collect those that have target dependency
https://github.com/iterative/dvc/blob/master/dvc/repo/__init__.py#L157
something like
```
ret = []
for stage in self.active_stages():
    for dep in stage.deps:
        if dep.scheme == "local" and dep.path == path:
            ret.append(stage)
return ret
```

and that is pretty much it :slightly_smiling_face:

**Comment by dmpetrov** [comment]
@legendawes could you please share a bit more details? Are you talking about a shared `common.py` file which is imported from other files like `process.py`, `train.py`? Or you have the same `train.py` which is used in different stages with different parameters?

Can be this option useful for `dvc repro` as well? If so, we might consider a separate (sub)command (like `dvc stage`) instead of an option (`--by-dep`). The usage will look like 
```
$ dvc commit `dvc stage common.py`
```
and
```
$ dvc repro `dvc stage common.py`
```

**Comment by legendawes** [comment]
@dmpetrov 
In my case a shared `common.py` file is imported from other files like `process.py`, `train.py`.

Not sure how it can be used in `dvc repro`:
The only usage I can imagine is to recalculate all stages which depend on `common.py', but it would be equivalent to `dvc repro train.dvc` (if `train.dvc` is the latest stage which uses `common.py`), so it seems like an unnecessary complication.

**Comment by dmpetrov** [comment]
@legendawes thank you for clarification. Yes, this option does not make sense for `repro` since it redoes everything by default.

**Comment by efiop** [comment]
closing as stale
