### ISSUE TITLE
s3: check if bucket exists and print appropriate error

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2100]
https://github.com/iterative/dvc.org/issues/415#issuecomment-499578137

**Comment by isidentical** [comment]
Currently, we are raising `FileNotFoundError`s for the fsspec-provided implementations (including s3) instead of a custom error. Should we keep this behaviour or add custom errors for bucket-not-found case?

**Comment by efiop** [comment]
@isidentical Hard to tell, I think `FileNotFoundError` could work great, if we properly handle it in `odb`, as `odb` is the one that should care about it when we are pushing to it.

**Comment by efiop** [comment]
closing as stale
