### ISSUE TITLE
fs: don't automatically create buckets

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2101]
~~We currently do that in azure https://github.com/iterative/dvc/blob/master/dvc/remote/azure.py#L90 .~~

Related https://github.com/iterative/dvc.org/issues/415

**Comment by pared** [comment]
Maybe it should be prompted? In case of for example, making mistake in bucket name?

**Comment by isidentical** [comment]
The only place we are creating the bucket (container, TBMP) is the azure, and I think we'd better off if the user creates the buckets explicitly on their end.

**Comment by efiop** [comment]
@isidentical Agreed. I think ssh and local are also like that, but `bucket`(aka container_name) is not quite the same as nonexistent dir in local and ssh, so we should be at least consistent within typical cloud group (s3, gs, azure, oss, etc).
