### ISSUE TITLE
dvc version: incomplete output

### ISSUE THREAD

**Issue by ryokugyu** [iterative/dvc#2105]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

![Screenshot (36)](https://user-images.githubusercontent.com/16274905/59120125-392c6a80-8972-11e9-9caa-43f823b42472.png)

But, it mentions  [here](https://github.com/iterative/dvc.org/blob/master/static/docs/commands-reference/version.md)
that `filesystem type ` and `cache` information will be shown too. 
There is no output like this.

**Comment by shcheklein** [comment]
@ryokugyu I believe, the version with this change is not released yet, please try the development version:

either this way: https://dvc.org/doc/user-guide/development
or this: https://dvc.org/doc/user-guide/contributing
