### ISSUE TITLE
Progress callback new line for long strings

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2109]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

dvc version: 0.41.3
Ubuntu 18.04

When calling ProgressCallback.update() with long string (eg full path of some file) we might encounter situation where instead of caret return progress callback prints to new line.

example:
```
from dvc.progress import progress, ProgressCallback

l = list(range(10))

pgc = ProgressCallback(len(l))

for i in l:
    import time
    time.sleep(0.5)
    pgc.update("short string {}".format(i))
```
https://asciinema.org/a/cFIZrki1HjcSZB7O7E6YMamcZ

and when we change displayed string to something longer:

https://asciinema.org/a/jKjtHOBgiLfezKVmrbuTnoNn2

**Comment by efiop** [comment]
This is the same issue as in https://github.com/iterative/dvc/issues/2051 . The solution would be to detect screen size and format(e.g. shorten) accordingly, but I'm not sure that there is a cross-platform way to do that. E.g. if you try `wget` you'll get the same result.
