### ISSUE TITLE
Dvc add data unprotect files for each use

### ISSUE THREAD

**Issue by jimmy15923** [iterative/dvc#2125]
My DVC version 
![image](https://user-images.githubusercontent.com/20395242/59399222-dac61880-8dc5-11e9-88db-c5fc4e232d56.png)

This issue comes from **Share NAS data in serve**r in the [discuss post 11#](https://discuss.dvc.org/t/share-nas-data-in-server/180/11?u=jimmy15923)

When adding new data, dvc will unprotect all data which cost lots of time (about 20 mins) which seems inevitable.

![image](https://user-images.githubusercontent.com/20395242/59399331-2aa4df80-8dc6-11e9-9aa2-f0c2ef9d4b01.png)

**Comment by DXist** [comment]
+1

I unprotected and changed a single file in a directory. dvc add for this directory makes unnecessary unprotection and copy.

**Comment by pared** [comment]
@jimmy15923 @DXist, this issue should be solved.
