### ISSUE TITLE
dvc: update file utilities

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2137]
Some file utilities live in `dvc.utils.fs` while some other in `dvc.utils.__init__`. I suggest grouping them in a single place.

Also, some of them accept Path-like objects, i.e. `Path`, `PurePath`, `PathInfo`, etc and some do not. This makes people guess at the call site whether they need to wrap arguments into `fspath()`, `fspath_py35()` or none. So I propose that our file utilities will always accept that, this way we will concentrate those wrapper call in one place and remove the guessing part, at least for our own functions, calling `os.path.*()` will still need wrapping as long as we use Python 3.5-.

- [ ] move to `dvc.utils.fs` (Fixed by #3093 )
- [x] make Path-like objects aware (Fixed by #2673 #2698 #2740 #2746 #2752 #2757 #2769 #2795 #2808 #3035 #3037 )

**Comment by efiop** [comment]
For the record, this one is taken by @algomaster99 . Not able to assign yet, working on adding him to organization.

**Comment by mroutis** [comment]
@efiop , @skshetry is this done?

**Comment by efiop** [comment]
@mroutis Not yet, as you can see there are still things like `makedirs` in `__init__.py`
