### ISSUE TITLE
import: support importing the whole repo

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2140]
From #2012 Support importing the whole repo with `dvc import myrepo`. This is going to be similar to specifying multiple datas within the repo, e.g. `dvc import myrepo data1 data2`, but we will have to collect it ourselves for the whole repo. Probably worth putting into a directory by default. E.g. `dvc import https://github.com/iterative/dvc` -> create 'dvc' directory in which data files will be places same way they are placed in the original repo.

**Comment by pared** [comment]
Question: 
We will want to import dependecies of current `HEAD`?

**Comment by efiop** [comment]
@pared Dependencies of dvc files? Only those that are outputs for other stages :) Basically, we need to import all cached outputs of the package(or external repo in new terminology).

**Comment by Suor** [comment]
Do people ask for this?

**Comment by efiop** [comment]
@Suor No direct requests yet.

**Comment by jorgeorpinel** [comment]
Is this issue still relevant? We don't have `pkg` commands any more :P

**Comment by efiop** [comment]
@jorgeorpinel The naming is bad, but it is still relevant. I'll rename it. Thank you for the heads up! :slightly_smiling_face:

**Comment by pared** [comment]
Would this task differ somehow from `git checkout && dvc pull`?

**Comment by efiop** [comment]
@dmpetrov @shcheklein Guys, do you remember specific requests for it, by any chance?

**Comment by dberenbaum** [comment]
@efiop What do you think of the priority of this one? I haven't seen this requested, so IMO it could be p2 or even p3.

**Comment by efiop** [comment]
@dberenbaum Thanks for the heads up! Indeed, downgraded the priority. The underlying functionality is actually already present (repofs and dvcfs are both work with repo roots just fine and we are able to stage any directory), so just a matter of making sure import/get don't do anything funny or don't have safeguards for this.

**Comment by efiop** [comment]
With dvcfs introduction we now support import/get-ing the whole repo, but automatic output name is a bit broken, so one needs to:

```
dvc get https://github.com/iterative/dataset-registry . -o dataset-registry
```

for it to work, but that's a separate issue. Closing.
