### ISSUE TITLE
run: improve ERROR message for existing 'Dvcfile'

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2145]
Try

```console
$ echo abc > file.txt
$ dvc run -d file.txt cat file.txt
# ^ creates Dvcfile
$ echo qwerty > qwerty.txt
$ dvc run -d qwerty.txt cat qwerty.txt
'Dvcfile' already exists. Do you wish to run the command and overwrite it? [y/n] n
ERROR: failed to run command - stage 'Dvcfile' already exists
```

My suggestion is to add a sentence to the error message above for this case: `Use -f option to specify a different stage name (ending in '.dvc').`

**Comment by jorgeorpinel** [comment]
p.s. how hard would it be to use the base name of the first argument to the command as the fallback default stage name? In this case `qwerty.dvc`

**Comment by efiop** [comment]
@jorgeorpinel 

> p.s. how hard would it be to use the base name of the first argument to the command as the fallback default stage name? In this case qwerty.dvc?

It is not hard at all, but the idea was that it should correspond either to the function or to the output. If we start using dependencies as well, it is easy to see how `dvc add qwerty` + `dvc -d qwerty ...` might get us into an even worse position.

**Comment by kurianbenoy** [comment]
Can I reserve this issue to be used for today's Devsprints?

**Comment by efiop** [comment]
@kurianbenoy sure!

**Comment by kurianbenoy** [comment]
Since the event is over, the issue is now open.

**Comment by efiop** [comment]
No longer relevant with the new dvc.yaml design. E.g. now it will fail with
```
ERROR: Stage 'mystage' already exists in 'dvc.yaml'. Use '--force' to overwrite.
```

**Comment by jorgeorpinel** [comment]
Sounds good.
