### ISSUE TITLE
Delete the Output-Files by checkout to other branches.

### ISSUE THREAD

**Issue by mastaer** [iterative/dvc#2146]
Hi guys,

in the current DVC-Version the DVC-Output / Metric-Files get not deleted after switching the Branch. I.E.: The `someout.txt` should not be in the `master` branch

```
rm -R test
mkdir test
cd test

git init
dvc init

dvc run --no-exec -o someout.txt "echo HELLO_WORLD > someout.txt"

git add -A
git commit -m 'add job'

git checkout -b second_branch

dvc repro -P

git add -A
git commit -m 'pipeline was executed'

git checkout master
dvc checkout
```

**Comment by mroutis** [comment]
@efiop , isn't conserving the file the intended behavior?

By using `--no-exec`, a DVC-file is created, referencing such output, thus, taking `something.txt` as a _used_ link. Should we consider as used only outputs with checksums?

**Comment by efiop** [comment]
@mroutis Not really. The thing is, on master there should not be `someout.txt` at all, because it doesn't have the assotiated checksum info int it. The `someout.txt` that is left out in the example above, belongs to the second branch, so it should be removed when checking out.
