### ISSUE TITLE
ui: better progress bars

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2148]
Currently we have progress bars for each individual file, which is not helpful when we have many of them. Furthermore when using several threads - a common case - they just fill up a screen, with no indication of where we are.

So I propose switch to using one progress bar for a single mass operation. There was a question from @efiop: how do we show all the filenames that are being processed? I would say we can only show single file taking longest so far like:
```
[========                             ] 17% big-dataset.csv + 7 other files
```
Or we can list them in a second line after the progress bar, but I don't think it matters too much.

Another thing that we should probably approach simultaneously is how we code that. Now we pass flags like `no_progress_bar`, sometimes deep enough to make code ugly. I suggest using global progress bar variable, like logger instances so we won't need pass anything. To guarantee that scope won't leek we can use context managers:
```python
with progress(name=..., total=...):
    # ...
    progress.update(value)  # This may come in some nested func
    # ...
```
Or wrap iterables:
```python
for item in progress(seq, name=..., total=...):
    # process item
```
To hide progress bars in all called code, without any flags passing:
```python
with progress.hide():
    # ...
```

**Comment by shcheklein** [comment]
Can we somehow show a progress for the whole operation (vs per file)? For example count the total files size and show progress by bytes transferred, also would be great to see total speed per second and other stats.

+1 on refactoring the code.

**Comment by efiop** [comment]
From https://github.com/iterative/dvc/issues/2192 :
```
status: don't show every file in the --cloud mode

If there is directory with 1M files it can be a huge list. We need to show a summary.

There are also extra spaces between file, don't think we need them.
```

**Comment by mroutis** [comment]
Hello, @casperdcl ! Not directly related to _progress bar_ but I would like to hear your input on this one https://github.com/iterative/dvc/issues/2329 (also related to UI)
