### ISSUE TITLE
pipeline: list and show use opposite order

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2151]
Why is the order or stages in `pipeline list` the opposite as in `pipeline show`? `list` has stages from last to first and `show` from first to last.

One idea is that probably `list` was meant to run in `repro` order but is there a reason for `show` to use the opposite order? Otherwise for consistency it may be better to change it to have the same order in both. (which one?)

**Comment by skshetry** [comment]
`pipeline` command no longer exists. Closing ...
