### ISSUE TITLE
Fix dvc -h usage for `dvc gc`

### ISSUE THREAD

**Issue by kurianbenoy** [iterative/dvc#2154]
**Please provide information about your setup**
DVC version: 0.41.3
Someone should add usage for `dvc status -R ` option

context
-https://github.com/iterative/dvc.org/pull/396#discussion_r292251163

**Comment by jorgeorpinel** [comment]
In fact most cmd refs need to be checked for updated usage blocks...

**Comment by kurianbenoy** [comment]
Some other commands, when I checked command reference are:
dvc `status` , `metrics`, `remove`

**Comment by efiop** [comment]
There is no `-R` for `gc`, where did you get it from @kurianbenoy ?

**Comment by kurianbenoy** [comment]
dvc metrics -R doesn't seem to be defined

**Comment by efiop** [comment]
@kurianbenoy `dvc metrics show -R` is though.

**Comment by kurianbenoy** [comment]
Ok

**Comment by efiop** [comment]
Closing. -R in metrics is also documented.
