### ISSUE TITLE
test: signal set in Stage.run() wreaks havoc in tests

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2171]
Random tests are randomly failing with `ValueError: signal only works in main thread`. 

Can't reproduce that locally so far, `pytest-xdist` uses processes (at least it says so) so this should not be an issue.

**Comment by efiop** [comment]
Yep, that is a weird one. I've added a check for main thread to https://github.com/iterative/dvc/pull/2167

**Comment by Suor** [comment]
@efiop doesn't look like a proper solution, rather like a stop gap)

**Comment by Suor** [comment]
@efiop anyway when do you plan to merge that? Or maybe that be easier to do with a separate PR?

**Comment by efiop** [comment]
@Suor Not 100% sure if that is a proper solution or not, just using it to help progress with fixing tests on py3 on windows.

Will merge as soon as it works and makes sense 🙂 Will try to finish today with it, if not - will submit a separate PR.

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/2167
