### ISSUE TITLE
having a "dvc grep" command like to "git grep"

### ISSUE THREAD

**Issue by dnabanita7** [iterative/dvc#2175]
This command will help the users to navigate through DVC cache files and config files to find the keyword they are searching as well as in the whole repo like ``git grep`` searches for the particular phrase or word.

**Comment by mroutis** [comment]
@Naba7 , can you add a little bit more of detail about how should it work?

**Comment by Naba7** [comment]
Look for specified patterns in the tracked files in the work tree, blobs registered in the index file, or blobs in given tree objects. Those patterns are separated by a newline. Searching into all the config and cache files is a lot of work. So to simplify the work and find the specified pattern or keyword, we can use ``dvc grep``

**Comment by mroutis** [comment]
@Naba7 , in what ways `dvc grep` is different from running `grep -R 'something' .dvc/cache` ?

I'm imagining something like:
- Search for a pattern in all .dvc/cache to retrieve a path: `grep -R <pattern> .dvc/cache`
- Get the checksum from such path: `sed 's/.dvc\/cache\/\(.*\)\//\1/'`
- Use such checksum to search through the whole git index for commits where the DVC-file contains such checksum: `git grep <checksum> $(git rev-list --all)`
- Show the user the revision and DVC-file where such entry is used?

**Comment by Naba7** [comment]
We can use ``git log`` to get the checksum but ``dvc grep`` can help getting the checksums and the related commits to it along with searching for a pattern in cache files. Running a single command ``git grep`` doesn't show the contents of cache or config files. So, having an additional ``dvc grep`` maybe used to add the functionalities of ``git log`` and ``git grep`` along  with searching through cache files.

**Comment by mroutis** [comment]
@Naba7 , I still have some questions :sweat_smile: 
What would the output of `dvc grep` look like? What should be the input (a pattern, a DVC-file, branch, etc.)?
What is the use cases for it? (In what scenario a user would need to use `dvc grep`)

**Comment by Naba7** [comment]
Output of ``dvc grep`` can be thought of as showing the ``PATH`` of the pattern located in the file or checksums related to it separated by a newline.

Input can be any pattern including a keyword or a DVC-file . I haven't thought of a branch.

We can get the hash values of commits made, reflinks or softlinks can be produced.

**Comment by skshetry** [comment]
Since it's been three years and not a lot of interest in this, I am closing this issue as not planned as it's unlikely we'll be getting to it soon.
