### ISSUE TITLE
status: don't show every file in the --cloud mode

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#2192]
If there is directory with 1M files it can be a huge list. We need to show a summary.

There are also extra spaces between file, don't think we need them.

**Comment by shaunirwin** [comment]
Hi @shcheklein, I also encountered this recently. I think it could be very useful if the summary could be grouped according to which .dvc files they correspond to, so that it is clear to the user which .dvc file needs to be pushed.

**Comment by efiop** [comment]
Closing as stale. And we also have `dvc data status` these days.
