### ISSUE TITLE
bugs in bash autocomplete script

### ISSUE THREAD

**Issue by Naba7** [iterative/dvc#2196]
DVC version :  0.40.7
Installed through :  Debian(package)

``index`` doesn't have ``-h, -q,  -V`` flags , then it will be a problem keeping ``_dvc_global_options`` and ``_dvc_options``

**Comment by efiop** [comment]
Hi @Naba7 ! I don't think I follow, what is `index`?

**Comment by Naba7** [comment]
By ``index`` I mean ``docs/commands-reference/index.md``. I have added it as a dvc command in ``dvc.bash`` script.

**Comment by efiop** [comment]
@Naba7 But it is not a command. It is just an `index` page in our docs, that is used internally https://github.com/iterative/dvc.org/blob/master/static/docs/commands-reference/index.md . I guess it was just a confusion? :) Let's close this issue then.
