### ISSUE TITLE
Skip computing md5 if file isn't being cached

### ISSUE THREAD

**Issue by umangs94** [iterative/dvc#2198]
If a file isn't being put under DVC control (i.e. using the -O option in `dvc run`), then should its md5 still be cached?:
```
Computing md5 for a large file data_split/x_train.npy. This is only done once.
[##############################] 100% data_split/x_train.npy

Output 'data_split/x_train.npy' doesn't use cache. Skipping saving.
```

This computation takes up a lot of time, especially as it happens on every run.

**Comment by efiop** [comment]
@umangs94 The checksum is used to determine if your output has changed or not and if dvc needs to perform `dvc repro` later, so we should compute it. If you don't need the checksum and don't care about dvc even knowing about that output and not tracking it, you could just not specify it in your `dvc run` command at all. Maybe I'm not quite understanding your scenario, could you elaborate please?

**Comment by umangs94** [comment]
I see. I’m mostly confused about the use cases for -o and -O in `dvc run`. Especially the latter, when should that one really be used?

**Comment by efiop** [comment]
@umangs94 when you want dvc to detect changes to it, but you don't want dvc to cache it, so you could either leave that file lying as is or track it with git. Hope it makes sense :)

**Comment by umangs94** [comment]
Yep, that helps. Thanks!
