### ISSUE TITLE
lock, unlock: nothing happens without `targets` arg

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2199]
```
DVC version: 0.50.1+936f94
Python version: 3.7.3
Platform: Darwin-18.6.0-x86_64-i386-64bit
Binary: False
Cache: reflink - True, hardlink - True, symlink - True
Filesystem type (cache directory): ('apfs', '/dev/disk1s1')
Filesystem type (workspace): ('apfs', '/dev/disk1s1')
```

Their `-h` output indicates `[targets [targets ...]]` as optional argument(s) but not providing `targets` with these commands results in nothing happening from my tests. I think `targets` is actually required in practice.

E.g. change a stage dependency and confirm with `dvc status`, then run `dvc lock` and `dvc status` again will print the exact same report as before.

**Possible fixes:**

- Change argparse code so the help output indicates `targets` are required and command output so it gives an error when missing (and docs to match the change); or
- Chose a default behavior when no `targets` are provided. Currently the 2 options used in other commands are a) lock/unlock all stage files present in the workspace (recursively) or b) default to attempting to lock/unlock `Dvcfile` (erroring out if inexistent).

**Comment by efiop** [comment]
Nice catch @jorgeorpinel !

> Change argparse code so the help output indicates targets are required and command output so it gives an error when missing (and docs to match the change); or

This one is the right approach :) Locking/unlocking everything doesn't make a lot sense so far. I can kinda see `dvc unlock` being used to unlock everything, but no one requested it so I don't think we should support it.

**Comment by efiop** [comment]
Correction: this doesn't happen in master
```
dvc lock
ERROR: the following arguments are required: targets 
```
only in your branch https://github.com/iterative/dvc/pull/2112#pullrequestreview-255082022

**Comment by jorgeorpinel** [comment]
It was happening on `master` last time I tried with version `0.50.1+936f94` as reported but no longer happens on `0.50.1+d0718c`. Probably because of my accidental changes to lock/unlock `targets` `narg`...

**Comment by efiop** [comment]
@jorgeorpinel Still, thanks for the feedback, better safe than sorry :smiley:
