### ISSUE TITLE
How to properly configure dvc for use with azure storage

### ISSUE THREAD

**Issue by JohanMollevik** [iterative/dvc#2200]
Hi

I have been unable to configure dvc to use azure storage. I ran

`dvc remote add -d myremote azure://jmollevidvctest/`

which seemed to work bu when I run

`dvc push`

I get an error

`ERROR: failed to push data to the cloud - azure storage connection string missing`

What am I missing, is there any example for adding all the data needed to dvc to make pushing data to azure work?

**Comment by efiop** [comment]
Hi @JohanMollevik !

You need to specify your connection string with
```
dvc remote modify myremote connection_string my-connection-string
```
Are you familiar with `az` utility? Do you specify the connection string there?

**Comment by JohanMollevik** [comment]
No I am not, I have an azure account assigned to my at work but I am in the process of learning the ins and outs of it. Do you know how I find the connection strings or do you have an example so I know how one looks like so that I am able to search for it in the azure portal. (I'm trying to connect from linux if that makes a difference)

**Comment by efiop** [comment]
@JohanMollevik Ah, got it. Go to your storage account in the azure portal and click `Access keys`, it should be there. 
![image](https://user-images.githubusercontent.com/5367102/60264931-0b8d6e00-98ed-11e9-9b54-acbe71c6366e.png)

**Comment by shcheklein** [comment]
create a https://github.com/iterative/dvc.org/issues/462, to add more info to the docs

**Comment by JohanMollevik** [comment]
@efiop Thanks, that seems to have done the trick, now the azure storage account is filling up nicely

**Comment by josecelano** [comment]
I did not know how to set up all the configurations on the Azure side to get the config values for DVC. I did it with a sample app. It might be useful for someone else:

https://github.com/josecelano/data-version-control/blob/master/docs/azure-blob-storage.md
