### ISSUE TITLE
warnings when using dvc

### ISSUE THREAD

**Issue by catherineweiss** [iterative/dvc#2204]
Every time I run a dvc command, I receive the following user warning: 
c:\anaconda\envs\py36-dvc-versioning\lib\site-packages\git\repo\base.py:128: UserWarning: The use of environment variables in paths is deprecated
for security reasons and may be removed in the future!!
  "\nfor security reasons and may be removed in the future!!")

**Setup**
DVC version(i.e. `dvc --version`) = 0.50.0, 
Platform and method of installation = pip

**Comment by efiop** [comment]
Related discord discussion: https://discordapp.com/channels/485586884165107732/485596304961962003/593896912529260584

We might consider using https://pypi.org/project/pytest-warnings/ with `-W error` to catch those warnings during the testing.

**Comment by efiop** [comment]
@catherineweiss Do you have GIT_DIR env var defined in your environment by any chance?

**Comment by efiop** [comment]
The warning comes from gitpython when it detects GIT_DIR in the environment, which we don't use. Related to https://github.com/iterative/dvc/issues/2215 . Closing
