### ISSUE TITLE
Overeager error "failed to run command - output OUTPUT does not exist"

### ISSUE THREAD

**Issue by estandiaa-marain** [iterative/dvc#2207]
Hi dvc-team,
When calling ``dvc run`` with multiple commands (separated by semicolons), dvc throws an error if the output file is not there after every step.

Consider the following command where we clean test_dir before running the command
```bash
dvc run \
-f test_dir.dvc \
-o test_dir \
rm -rf test_dir; \
mkdir test_dir; \
touch test_dir/test_file_1.txt; \
touch test_dir/test_file_2.txt;
```
This throws the error: 
```
Running command:
	rm -rf test_dir
ERROR: failed to run command - output 'test_dir' does not exist
```
even though this is the intended functionality and the output is there in the end.
It is also a bit surprising, that the commands after ``rm -rf test_dir`` are executed despite the error. Nonetheless,  the `` test_dir.dvc`` file is not created

**Environment information**
dvc version: 0.50.1
Platform: Ubuntu 16.04
Method of installation: deb repository

**Comment by estandiaa-marain** [comment]
Never mind, this is not an issue. It is a problem with the command. It can be fixed by running:
```bash
dvc run \
-f test_dir.dvc \
-o test_dir \
"rm -rf test_dir; \
mkdir test_dir; \
touch test_dir/test_file_1.txt; \
touch test_dir/test_file_2.txt"
```

Sorry.

**Comment by efiop** [comment]
No worries @estandiaa-marain ! Glad it works now! :slightly_smiling_face:
