### ISSUE TITLE
investigate error handlling 'dvc metrics show -a'  fetch remote branch

### ISSUE THREAD

**Issue by AlessandroBregoli** [iterative/dvc#2213]
Executing  'dvc metrics show -a` ask for github credentials in loop. If there is an ssh key for github  the command work but is really slow (more than a minute). If no remote is set for git all work without problem.

**Please provide information about your setup**
DVC version `0.50.1`,  Installed with pip3 on ubuntu 18.04

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/485596304961962003/595218255489138690

**Comment by efiop** [comment]
culprit https://github.com/iterative/dvc/blob/master/dvc/scm/git/tree.py#L81

**Comment by efiop** [comment]
This is where we actually need that branch fetching https://github.com/iterative/dvc/blob/0.50.1/dvc/external_repo.py#L66

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/issues/2201

**Comment by Suor** [comment]
**Diagnose:** `show-ref --verify` requires exact ref path like `refs/heads/some-branch` and we use non-qualified branch names got from `repo.scm.list_branches()`. 

I suggest to never fetch anything as a side effect. We should always work with working tree and git repo state in its actual state. @efiop do we still need that `._try_fetch_from_remote()`?

**Comment by efiop** [comment]
@Suor Indeed, after https://github.com/iterative/dvc/pull/2218 we don't need `_try_fetch_from_remote()` at all.
