### ISSUE TITLE
Configurable Group Permission for SSH remote

### ISSUE THREAD

**Issue by daskol** [iterative/dvc#2214]
There is a use case when SSH remote is used by group of colloborators. Each colloborator has his/her own credentials to access server over SSH. Say remote URL is similar to `ssh://servername/data` i.e. it points to directory which could be potentially accessed by every colloborator. The issue is that `dvc push` command sets permisions `0664` and `0775`. This prevents object modification by colloborators. The common approach to share access to files among users is group permissions. So, I suggest to allow user to configure DVC in order to set group which all collaborators are in.

Here is an example to clarify above statement. Currently, `dvc` sets the following permissions.
```
/data$ ls -l
total 14
drwxrwxr-x 2 daskol daskol 4096 Jul  1 19:18 11
drwxrwxr-x 2 daskol daskol 4096 Jul  1 19:18 12
drwxrwxr-x 2 daskol daskol 4096 Jul  1 19:18 1a
```
But it would be great to configure UNIX group to replace default `daskol` with custom `data`.
```
/data$ ls -l
total 14
drwxrwxr-x 2 daskol data 4096 Jul  1 19:18 11
drwxrwxr-x 2 daskol data 4096 Jul  1 19:18 12
drwxrwxr-x 2 daskol data 4096 Jul  1 19:18 1a
```

**Comment by mroutis** [comment]
Good suggestion, @daskol ! 
You can also set the directory group to data (`chown -R :data <directory>`) and then inherit the group of the directory instead of using the primary group ID: `chmod g+s directory`.

DVC will create the files with the corresponding group ID :slightly_smiling_face: 

Otherwise, DVC would need to `chown` after uploading/moving files.

**Comment by mroutis** [comment]
Let me know if you find it useful, @daskol , I can add the information to DVC's documentation.

**Comment by daskol** [comment]
@mroutis Thanks! I totally forget about set-group-ID option.

**Comment by shcheklein** [comment]
@mroutis @daskol really good tip! Would be great to put a not in the docs, guys. Closing this as solved, thanks @mroutis 🎉
