### ISSUE TITLE
failed to add file - output 'gs://$BUCKET/testing/images/' does not exist but the file exists in that bucket.

### ISSUE THREAD

**Issue by AnsujJoshi** [iterative/dvc#2233]
dvc version = 0.50.1
Platform = DEB(Linux)
Installation method = pip

I am trying to do dvc add gs://$BUCKET/testing/images and it's giving me the error that the file does not exist but if I give dvc add gs://$BUCKET/testing/images/$image_name that works fine. 

I think i should be able to add directory to dvc add command. My folder gs://$BUCKET/testing/images contains about 2000 files. 

What is the problem here, am i doing something wrong or is it some problem with dvc?

Thanks in advance.

**Comment by efiop** [comment]
Hi @AnsujJoshi !

Currently we only support local and ssh directories, gs is not supported. See https://github.com/iterative/dvc/issues/1654
