### ISSUE TITLE
Config option constants naming

### ISSUE THREAD

**Issue by ei-grad** [iterative/dvc#2234]
Follow up on https://github.com/iterative/dvc/pull/2040#discussion_r290985693.

1. Config option name constants are named with the `SECTION_XXX_` prefix. It seems more natural for me to use `OPTION_` prefix for them.

2. `STORAGEPATH` and `CREDENTIALPATH` options name constant from `SECTION_AWS` section is assigned to `SECTION_GCP` and `SECTION_LOCAL`.

It looks that this is coming from the remainings of the legacy cloud config schema. And probably should be refactored.

What do you think?

**Comment by efiop** [comment]
Great points @ei-grad ! Btw, we could even consider dropping that legacy stuff, since it has been quite a while and we only had it in the first dvc versions, and were mentioned only by a very old tutorial. All our docs never mentionined legacy storagepath and friend at all.

**Comment by efiop** [comment]
No longer relevant with the new config.
