### ISSUE TITLE
Less Verbose Output of dvc push to SSH remote

### ISSUE THREAD

**Issue by daskol** [iterative/dvc#2235]
I need to push about 10k objects  to remote. So `dvc push` produces too noisy output like
```
[##############################] 100% data/27245.png
[##############################] 100% data/27245.png
[##############################] 100% data/27312.png
[##############################] 100% data/27312.png
```
First of all, it is a bit strange to see progress bar for each file twice. Secondly, I would like not to see progress bar for every upload. It would be great to see single progress bar for a whole bunch of files.

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/issues/2148 . @Suor Looks like you are not working on this, I'll unsign you.

**Comment by shcheklein** [comment]
Should be fixed @efiop @casperdcl ?

**Comment by efiop** [comment]
Yes, we can close it.
