### ISSUE TITLE
remote: use `file://` scheme for "local" remotes?

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2236]
To make the URL format match the generic URI generic syntax.

**Comment by efiop** [comment]
@mroutis Is there any use case for it?

**Comment by mroutis** [comment]
It wouldn't change behavior, just part of the interface, @efiop

**Comment by efiop** [comment]
@mroutis Yeah, but why would anyone want to use that? :slightly_smiling_face: And if no one needs it, why implement that?

**Comment by mroutis** [comment]
> why would anyone want to use that?
I'm not sure people  _want_ to use it.

> if no one needs it, why implement that?
I thought it made more sense to have valid URL's as remote `url` and not make the distinction between `url` and `path`. However, a `path` without any scheme is a "valid" `url`.

```python
>>> urllib.parse.urlparse('/tmp/example')
ParseResult(scheme='', netloc='', path='/tmp/example', params='', query='', fragment='')
```

**Comment by mroutis** [comment]
Closing because there's no reason from the user perspective
