### ISSUE TITLE
import-url: lock by default

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2238]
To make it symmetrical to `dvc import` command https://github.com/iterative/dvc/pull/2218 . For updating, we could introduce `dvc update-url`

**Comment by Suor** [comment]
I don't think we need `update-url`. Why not use `dvc update` to update that?

**Comment by efiop** [comment]
@Suor to have an ability to update ones or the others. Though, for that one could specify particular .dvc files, so the usefulness is disputable :)

**Comment by efiop** [comment]
Had a discussion and decided to go with `dvc update` for urls too.

**Comment by efiop** [comment]
Need to make import-url lock by default and make `dvc update` work on import-urls.
