### ISSUE TITLE
remote: bugs in repo dep

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2252]
I was looking through our code and looks like there is one bug and one inefficiency in `DependencyREPO.download()` in [these two lines](https://github.com/iterative/dvc/blob/ccb0d7d1b3cc8e34fd10d912c6068f31032db41c/dvc/dependency/repo.py#L70-L71):
1. `self.def_path` is relative to `stage.wdir` usually, not repo root as `Repo.find_out_by_relpath()` assumes. (not a bug, ignore)
2. The code is fetching all stage outs instead if a single one. (take a look at Repo.open that does that already)

@efiop do you mind taking a look?

**Comment by efiop** [comment]
Also need to take a look at `dvc get`
