### ISSUE TITLE
Warning message in google colabs

### ISSUE THREAD

**Issue by kurianbenoy** [iterative/dvc#2265]
https://colab.research.google.com/drive/1rUPC_IBrZO2Dep3ckm5zHLeFYEFmuWzY#scrollTo=T_Heaa1AA4yG

The error message is shown in the above link. This happens only when I am using google colabs

**Please provide information about your setup**
DVC version: 0.50.1

**Comment by efiop** [comment]
@kurianbenoy you have enum34 installed. Uninstall it and those errors will disappear. Related https://github.com/iterative/dvc/issues/1995 https://github.com/iterative/dvc/issues/1582

**Comment by efiop** [comment]
@kurianbenoy could you please take a look at piptree to see what package installed enum34 as a dependency?

**Comment by kurianbenoy** [comment]
Yep on removing `enum34` the error message disappeared. I am closing this issue now

**Comment by shcheklein** [comment]
@kurianbenoy @efiop any idea what caused this? can we come up with some workaround to fix it for good and do not require ppl uninstalling stuff?

**Comment by efiop** [comment]
@shcheklein please see the linked issue. In short: there is nothing we can do about it on our side.

**Comment by efiop** [comment]
@kurianbenoy Though seeing piptree to see what package installed enum34 as a dependency would be very helpful. Could you check that please?
