### ISSUE TITLE
hadoop command not found

### ISSUE THREAD

**Issue by JoshuaPostel** [iterative/dvc#2273]
**DVC version:** 
0.52.0
**Hadoop Version:**
2.7.3
**Platform:** 
Linux 4.15.0-54-generic 
Ubuntu 18.04.02 LTS
**Method of installation:** 
`pip3 install dvc[hdfs]`

### Error:

When running `dvc push` I receive:
```
ERROR: failed to upload '.dvc/cache/64/a414dd1dd7f45f5f8e14d7607b05ce' 
to 'hdfs://MyUserName@MyServer/path/to/dvc/storage' - 
hdfs command 'HADOOP_USER_NAME=MyUserName hadoop fs -mkdir -p hdfs://MyUserName@MyServer/path/to/dvc/storage'
finished with non-zero return code 127': b'/bin/bash: hadoop: command not found\n'

...

ERROR: failed to push data to the cloud - 4 file(s) failed to upload
```

### Debugging Attempts:

Running `which hadoop` on `MyUserName@MyServer` returns `/usr/bin/hadoop`.  I am also able to run the following remote command successfully. 
```
ssh -t MyUserName@MyServer 'HADOOP_USER_NAME=MyUserName 
hadoop fs -mkdir -p hdfs://MyUserName@MyServer/path/to/dvc/storage'
```
I tried getting information about environment in which `dvc` is executing by cloning the repository and editing... 

https://github.com/iterative/dvc/blob/fc5d3c182c08a02b6257652654c62b723c854671/dvc/remote/hdfs.py#L37 

...however, it is returning the environment information of my local machine.  Could the issue be that `dvc` is trying to launch the hadoop command on my local machine? If there are suggestions on how to debug the remote environment, please let me know.

### Further Details:

I was able to run the commands above on May 13th 2019 without an issue, however, the server environment (`MyUserName@MyServer`) has likely changed since then.

**Comment by efiop** [comment]
Hi @JoshuaPostel !

Indeed, dvc is trying to launch `hadoop` on your local machine to access your remote machine. To fix that, just install hadoop on your local machine :slightly_smiling_face: A more proper fix for us would be to stop using hadoop CLI and use API instead. We have an issue for it at https://github.com/iterative/dvc/issues/1629 .

**Comment by JoshuaPostel** [comment]
That did the trick :)

I probably should have caught that from #1629, but thank you for spelling it out for me!
