### ISSUE TITLE
completion: support import-url and get-url

### ISSUE THREAD

**Issue by Naba7** [iterative/dvc#2279]
Add support for `dvc import-url` and `dvc get-url` into bash auto-completion script.

**What should be done:**

As to `import-url` and `get-url`, you would need to convert on `${COMP_WORDS[1]}` first that would replace all `-` with `_`, so that `option_list` becomes `_dvc_import_url` and not `_dvc_import-url`.

**Comment by efiop** [comment]
Context https://github.com/iterative/dvc/pull/2226#issuecomment-511155421

**Comment by algomaster99** [comment]
@shcheklein Shall I take up this issue?

**Comment by efiop** [comment]
@algomaster99 Sure!
