### ISSUE TITLE
Metrics show xpath does not override dvcfile xpath

### ISSUE THREAD

**Issue by Casyfill** [iterative/dvc#2285]
I do have a Dvcfile with metrics, and for some period of time (a few commits) I defined a specific xpath in that file; Now, when I run a different xpath on `dvc metrics show`, the old xpath (and hense, different metric) shows up for the commits where dvcfile specified it:

```
>>> dvc metric show -x pe20

working tree:
        data/rentals/nyc/metrics.json: [88.15]
bin_bedroom:
        data/rentals/nyc/metrics.json: [88.25]
first-iteration:
        data/rentals/nyc/metrics.json: [88.13]
nhds:
        data/rentals/nyc/metrics.json: [7.45]
roosevelt:
        data/rentals/nyc/metrics.json: [7.11]
``` 

obviosly pe20 was > 88 for all the commits, it's just showing median error for the `nhds` and `roosevelt`

**Comment by efiop** [comment]
Thanks for reporting @Casyfill ! Indeed, we need to overwrite it. We'll take a look.

**Comment by Casyfill** [comment]
You probably can instead just check for the xpath in the current Dvcfile, and override it with the explicit path, if needed?

**Comment by efiop** [comment]
@Casyfill Yes, the explicitly specified xpath should override the one specified in Dvcfile.

**Comment by shcheklein** [comment]
@efiop @pared metric type should probably behave the same way.

also, what about multiple metric files? or a single file fetched from different tags? now, you can have them with different settings, and explicitly specified xpath and type are essentially defaults if one of the files is not specifying them. That will change and we'll be applying same settings to all files.

I can actually imagine both options are valuable.

**Comment by shcheklein** [comment]
it looks like right now if you specify type + xpath or just type they will override setting in the DVC-file. xpath alone is not enough.

**Comment by shcheklein** [comment]
@efiop @pared reopening to fix comments, logic if needed and fix the docs appropriately.
