### ISSUE TITLE
dvc: replace unpacked dir optimization with a virtual dir

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2291]
The idea is instead of creating a real unpacked dir with hard links and making a state record for it we make a record for a virtual directory with some fake inode and files listed in directory cache json. The check would be: get json refered by checksum, calculate aggregate mtime and size as we do for real dir, 

Pros:
- we won't need to set up a real dir, thus better setup time
- no interference with gc
- simpler code

Cons:
- slower check time
- need to modify state to work with virtual dir

**Comment by Suor** [comment]
**P.S.** Thinking a bit more about it batching `state.get()` in this piece:
```python
        for entry in self.get_dir_cache(checksum):
            entry_checksum = entry[self.PARAM_CHECKSUM]
            if self.changed_cache_file(entry_checksum):
                return True
```
might get us close too.

**Comment by efiop** [comment]
This is relevant for https://github.com/iterative/dvc/issues/2287 , since we are not able to create hardlinks to  files that are not owned by us(at least with protected_hardlinks set, which is how it is on most distros).

**Comment by mroutis** [comment]
Is this related to https://github.com/iterative/dvc/issues/2093 ?

**Comment by efiop** [comment]
Need to get back to this after https://github.com/iterative/dvc/issues/2093 to see if we even need unpacked dirs.

**Comment by efiop** [comment]
Closing since we no longer have unpacked dirs at all.
