### ISSUE TITLE
dvc: rethink jobs/checksum_jobs mess

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2295]
We should rethink all `jobs/checksum_jobs/--jobs` mess, currently we have the following issues:
- surprising number of default jobs - `4 * cpu_count()`,
- surprising number of default checksum jobs - `cpu_count() / 2` capped between 1 and 4,
- no way to override `checksum_jobs` from command line, `-j1` will probably surprise people to not affect it,
- `checksum_jobs` defined globally, not per remote (at least this is how the intention looks, [the code](https://github.com/iterative/dvc/blob/432373fb42c7b2430cc2fc20b70d3dee67a4aaa7/dvc/remote/base.py#L111-L114) looks broken as it looks into `remote_config["core"]["checksum_jobs"]`),
- we need to maintain conservative ssh jobs, like 4, to not exhaust the session limit. This is inefficient when  dealing with large number of smaller files.

We should look into unifying these or remove some setting, switching to auto guessing, or do something else.

**Comment by skshetry** [comment]
Closing as stale. This is still a problem, but lots of things have changed internally. We'll leave most of these things to the underlying filesystem, we'll revisit this later.
Feel free to reopen if you disagree.
