### ISSUE TITLE
checkout: no message when there's no cache

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2296]
DVC version: 0.52.1

```bash
dvc run -O hello.txt "echo hello > hello.txt"
rm hello.txt
dvc checkout hello.txt.dvc
```

I would expect something like "nothing to checkout"

**Comment by kurianbenoy** [comment]
I am interested in working with this issue

**Comment by efiop** [comment]
@kurianbenoy Please feel free :slightly_smiling_face:

**Comment by shcheklein** [comment]
@kurianbenoy before we jump implementing this, could you please show the exact message how will it look like? with some example, multiple DVC-file w/o cache.

**Comment by kurianbenoy** [comment]
Maybe my message can be something like:

`No DVC file to checkout`

**Comment by mroutis** [comment]
@shcheklein , I think it make sense to show the message @kurianbenoy suggested only when there's no output at all (don't need to worry about multiple files)

**Comment by shcheklein** [comment]
@mroutis okay, what is the primary goal to show this message at all?

**Comment by mroutis** [comment]
@shcheklein let know the user nothing happened, but I guess they can assume that by not showing any progress bar?

**Comment by shcheklein** [comment]
I see. I though that the idea was to show that some data is can be only partially checked out bc cache files are missing ... is that a problem at all?

**Comment by mroutis** [comment]
Well, is not a problem for me, but might be for someone who is not aware of `--outs-no-cache`.

I don't know, maybe the issue is more about how _clear_ is that an operation was successful or not.

You can _rely_ your prompt to show somehow the exit code of your command, or you can assume that if there's no output is because nothing happened. For example, in this case `dvc checkout` from a file without cached outputs is successful? It didn't face any errors, but it didn't perform any operation at all.

Maybe I'm just tripping with this :sweat_smile:

**Comment by shcheklein** [comment]
yep, it makes sense. 

btw, does dvc checkout fail if there are some cached outputs missing?

**Comment by mroutis** [comment]
@shcheklein noup, exit code `0` and this message:
```
WARNING: Cache 'b1946ac92492d2347c6235b4d2611184' not found. File 'hello' won't be created.
[##############################] 100% Checkout finished!
```

(reproduction script: `dvc init --no-scm --force && echo "hello" && dvc add hello && rm -f .dvc/cache/* hello && dvc checkout dvc.hello`)

**Comment by shcheklein** [comment]
Kk. We have warning at least here. I understand now that your message is a completely different one. @kurianbenoy we can proceed if you'd like to contribute this :)

**Comment by mroutis** [comment]
It now shows `Nothing to do`.
