### ISSUE TITLE
Pull with masked targets is slow

### ISSUE THREAD

**Issue by ematvey** [iterative/dvc#2308]
`dvc pull` with specifying targets by shell-expanded glob mask (e.g. `dvc pull */*.dvc`) works significantly slower then global `dvc pull`. This is especially hurtful when pulling large number of small files. At the same time, passing glob mask to dvc via `dvc pull '*/*.dvc'` does not seem to be supported.

Should this be optimized?

As mentioned in chat, workaround is `dvc pull -R dir`.

DVC version: 0.50.1
Platform: Ubuntu 18.04, installation via pip

**Comment by shcheklein** [comment]
Probably the same applies to all commands that take DVC-files as a target. It's slow because it's processing them one-by-one.

**Comment by Suor** [comment]
We'll need to refactor how all data commands go to fix this. Going to be a nice refactoring :)

**Comment by efiop** [comment]
Note: removing from weekly tasks in favor of gitpython task. This was discussed during the planning, just forgot to remove it.
