### ISSUE TITLE
api: get/open: avoid creating a copy of the file locally

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#2311]
In API implementation, when we open a file via Git repo, we want to avoid downloading file to the local filesystem.

**Comment by Suor** [comment]
I don't thing this is about performance, there won't be much difference if we change this to streaming. The only significant upside is that we won't need to store a potentially big file in local fs. Is it really important?

**Comment by shcheklein** [comment]
It limits number of cases the API can be used. For example 2GB and only 1GB tmp space. Or if I want to read huge CSV file and process in memory I would like to stream it, again there are a lot of case in production when you just don't have enough space to put those files.

And it's about performance as well. You are writing to disk after. In certain environments it can be potentially even slower than network now (EC2 has 20GB networks).

**Comment by shcheklein** [comment]
I'll remove pefromance tag, it's not primary goal here. I can agree on that.

**Comment by efiop** [comment]
@shcheklein it doesn't feel like p1 though, could you elaborate on why you've decided to prioritize it so much?

**Comment by shcheklein** [comment]
@efiop bc we will be making a release around get/import/api features. I would like to remove as much friction as possible around use cases.

**Comment by efiop** [comment]
Checklist
- [x] [azure](https://github.com/iterative/dvc/pull/2371)
- [ ] [s3, gs, oss](https://github.com/iterative/dvc/pull/2389)
- [ ] hdfs
- [ ] ssh
