### ISSUE TITLE
ui: inconsistent warnings on deps and outs changed in repro

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2313]
Linux, master branch.

The warnings are shown only about first found changed dep and first found changed out. There should be showed all or none. Showing all of them will slow down things a bit because we will need to give up short-circuiting.

I wonder how valuable there warning really are.

**Comment by Suor** [comment]
Then we have `Stage changed` warning on top, which looks silly if we show `DVC-file '{}' changed.` right before that.

**Comment by dberenbaum** [comment]
@Suor Do you know if this is still a relevant issue?
