### ISSUE TITLE
improve docstrings around dvc.api

### ISSUE THREAD

**Issue by Naba7** [iterative/dvc#2316]
As per, [comment](https://github.com/iterative/dvc.org/issues/463#issuecomment-513877418) . The methods ``open``, ``get_url``, ``read`` 's docstrings needs to be updated and explained a bit more.

**Comment by shcheklein** [comment]
@jorgeorpinel is it a duplicate?

**Comment by jorgeorpinel** [comment]
Ah yeah! Mine is a duplicate technically, but since it has some more activity, closing this one in favor of #3092. Thanks Ivan!
