### ISSUE TITLE
metrics show: doesn't support directories

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2318]
In the description, the path says that it supports directories, I'm not sure if this is intended.

```
❯ dvc metrics show --help
usage: dvc metrics show [-h] [-q | -v] [-t TYPE] [-x XPATH] [-a] [-T] [-R]
                        [path]

Output metric values.
documentation: https://man.dvc.org/metrics-show

positional arguments:
  path                  Path to a metric file or a directory.
```

**Comment by shcheklein** [comment]
I think it's intended, if -R specified it accepts a directory to look for metric files inside.

**Comment by mroutis** [comment]
@shcheklein, `dvc metrics show -R dir` works, should we assume `-R` when a dir is used as input?

**Comment by shcheklein** [comment]
It's a good question, @mroutis . It symmetric across all commands that have -R. I would imagine it would a bit dangerous for other commands to adopt the same semantics as you suggested, we would like to preserve the same explicit -R semantics. I would double check though.

**Comment by mroutis** [comment]
@efiop , I think this is not a bug; it is more like an "implicit -R".

**Comment by mroutis** [comment]
Also, I think we can close this issue if we agree on _explicitness over implicitness_ as a "design guideline" of DVC (to stay consistent)
