### ISSUE TITLE
Doing `commit` after `move`

### ISSUE THREAD

**Issue by danielfleischer** [iterative/dvc#2322]
Hi, after using `dvc move` to move versioned data files, when doing `dvc status` one gets `changed checksum` so these files need to be `dvc commit`. I suggest combining `move+commit` because this is obviously what we want to do.

**Comment by pared** [comment]
It looks reasonable to me. @efiop do you think there is some use case of move that does not require commiting?

**Comment by efiop** [comment]
@pared I'm actually surprised that it doesn't, this is probably a bug.

**Comment by danielfleischer** [comment]
I'll do it. I'll add a `commit` step by default with a possible flag `--no-commit`.

**Comment by efiop** [comment]
@danielfleischer I think we are simply missing `stage.save()` in https://github.com/iterative/dvc/blob/master/dvc/repo/move.py#L68
