### ISSUE TITLE
ssh: Support Kerberos Keytab

### ISSUE THREAD

**Issue by JoshuaPostel** [iterative/dvc#2327]
Keytab files for Kerberos authentication are binary files, however, `dvc remote modify myremote keyfile /etc/krb5.keytab` followed by `dvc --verbose push -r myremote` throws
```
Preparing to upload data to 'ssh:xxx'
Preparing to collect status from ssh:xxx
Collecting information from local cache...
[##############################] 100% 

Collecting information from remote cache...
ERROR: unexpected error - 'utf-8' codec can't decode byte 0x87 in position 38: invalid start byte
```
Looks like dvc does not want to accept the binary file.  Would a fix to reading the file allow for kerberos authentication or is there more to be done here?  I cannot tell from the [documentation](https://dvc.org/doc/commands-reference/remote-modify) if `dvc remote modify myremote keyfile` supports multiple types of authentication or only ssh keyfiles.

Apologies for another kerberos related issue.

**Comment by efiop** [comment]
Hi @JoshuaPostel !

Looks like to use kerberos with paramiko(the lib that we are using for ssh connections) you need to specify special `gss_auth` and `gss_kex`(optional) parameters to the ssh connection https://github.com/iterative/dvc/blob/master/dvc/remote/ssh/connection.py#L61 . We won't be able to use `keyfile` for that (at least as is) and will need to create a special config option(s) for ssh remote. Should be pretty straightforward though. Let us know if you'd be willing to contribute a patch for this, we'll be happy to help with everything we can. :slightly_smiling_face:

**Comment by JoshuaPostel** [comment]
I'll take a crack at it! Might be a week or two before I can put some effort into it, but I'll keep this updated.
