### ISSUE TITLE
remote: delegate sync operations to archival / backup tools

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2330]
Another idea that has been around for a while on my head but didn't share because I haven't consider all the scenarios and if this is possible, reasonable, etc. let's discuss it together :sweat_smile: 

In my mind, `pull`/`push`/`gc` are _sync_ operations, they synchronize the local cache (`.dvc/cache`) of a repository with the remote cache (central source of truth). The `target` along with some options like `--all-branches`, `--all-tags` modifies the scope of what's going to be synced.

There are tools like [rclone](https://github.com/ncw/rclone) or [bup](https://github.com/bup/bup) that support this _sync_ operations, support several clouds and are optimized for this purposes. ( [awesome list of backup tools](https://github.com/oz123/awesome-backup), a post about [rsync in python](https://blog.liw.fi/posts/rsync-in-python/) )

I haven't evaluated yet if they could work completely with DVC, but if we are able to delegate this to other tools might reduce the complexity of the tool a lot. However, the most interesting part is the performance, right now this sync operations are slow in DVC -- making progress, of course, a lot of improvements on SSH, S3, etc. but I'm not sure if this is the way to go (adding and spending time on each remote).

**Comment by mroutis** [comment]
https://github.com/iterative/dvc/issues/2147#issuecomment-522918839

`rclone` is slower than the current implementation of DVC ^

kudos to @Suor !

**Comment by efiop** [comment]
@mroutis should we close this? You can use any backup tool with a local dvc remote.

**Comment by mroutis** [comment]
@efiop , this issue was more about DVC's internal implementation of remotes, but yeah, let's close this

**Comment by efiop** [comment]
As @Suor noted, rclone will be a hustle to deploy and interact with for us, limiting the way we could work with remotes in the future. For example, current API's `Remote.open()` functionatility is not possible in the streaming form with any backup tool. Bup doesn't even have a pypi package :slightly_smiling_face:
