### ISSUE TITLE
dvc: refactor/optimize how we collect cache for several targets

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2344]
The way it's implemented now we repeatedly call `Repo.stages()`, `.active_stages()`, `.piplelines()` and `.graph()` for each target, which includes walking repo tree each time.

This will further speed up #2308.

**Comment by Suor** [comment]
Since we cache `graph`, `stages` and friends this is less of an issue now. We may, however, improve things by storing outs in a dict and looking it up without the full search.

**Comment by efiop** [comment]
> We may, however, improve things by storing outs in a dict and looking it up without the full search.

Could you please elaborate? @Suor

**Comment by Suor** [comment]
@efiop we now construct full outs list each time and then filter it. We can make a dict and then look up them instead. To support recursive case we will need to build some tree, which might also be used to speed up graph construction.

Not sure this is worth the effort though. Let's close it and return to this if we ever run into any issues.
