### ISSUE TITLE
investigate dvc being slow on windows 

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2360]
@shcheklein noted that dvc installed from pip on windows is extremely slow.

**Comment by pared** [comment]
@shcheklein did you have some particular scenario? I did small experiment for clear virtualenv and freshly installed dvc from pip with following results:
version:
```0.54.1```
code:
```
import os, shutil, time, logging
from dvc.repo import Repo as DvcRepo
from git import Repo as GitRepo
logger = logging.getLogger("dvc")
logger.setLevel(logging.CRITICAL)
cwd = os.getcwd()
FILES_NUMS = [100, 1000, 10000]
for fn in FILES_NUMS:
    os.chdir(cwd)
    repo_dir = "repo"
    if os.path.exists(repo_dir):
        shutil.rmtree(repo_dir)

    os.makedirs(repo_dir)
    os.chdir(repo_dir)

    GitRepo.init()
    repo = DvcRepo.init()

    data_dir = "data"
    os.makedirs(data_dir)

    for i in range(fn):
        with open(os.path.join(data_dir, str(i)), "w") as fobj:
            fobj.write(str(i))


    start = time.time()
    repo.add(data_dir)
    end = time.time()

    exec_time = end - start

    print("Adding: {} files, execution time: {} s".format(fn, exec_time))
```
Ubuntu:
```
Adding: 100 files, execution time: 0.2940998077392578 s
Adding: 1000 files, execution time: 0.9594559669494629 s
Adding: 10000 files, execution time: 9.471035242080688 s
```
Windows 10, Defender on, no exceptions:
```
Adding: 100 files, execution time: 0.7673771381378174 s
Adding: 1000 files, execution time: 4.094652414321899 s
Adding: 10000 files, execution time: 40.989408016204834 s
```

**Comment by jorgeorpinel** [comment]
Been using Windows recently and it's probably because Windows is slow with file IO in general. Like 1990s slow. Disabling file search indexing helps a little but I hear the real drag is Windows Defender (built-in antivirus)... We already have most of these notes in https://dvc.org/doc/user-guide/running-dvc-on-windows (except the one about file indexing) so maybe we should transfer this issue to dvc.org and address there?

**Comment by shcheklein** [comment]
we need ideally run profiler with different link types, different amount of files and see what the bottleneck is (if any left after disabling know stuff). Yes, def include indexing if it helps.

**Comment by jorgeorpinel** [comment]
Added note in fe2ae7a5 for #1103

**Comment by jorgeorpinel** [comment]
Hi! I noticed that when a command is working, e.g. even as simple as `dvc status` which takes a few seconds, Ctrl+C is not instantaneous (I'm using Git Bash on Cmder). It feels like it waits until the whole operation is finished and then it aborts, saving you no time by interrupting. Is this also a Windows-specific problem (so part of this issue)? Or should I open a separate issue to investigate on other platforms? Thanks

**Comment by efiop** [comment]
@jorgeorpinel might be threading too. Python is funky with threads like that. We have a same issue with push/pull. If that's the one, then it is a known issue.

**Comment by iesahin** [comment]
Are there new tests about this? My recent experience with dvc on Windows doesn't show such a drastic difference.

**Comment by efiop** [comment]
We still don't have any windows-specific benchmarks yet (though we can run them in https://github.com/iterative/dvc-bench in the future.

Closing as stale for now
