### ISSUE TITLE
Fix `cache_exists` for RemoteHTTP

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2380]
As noted by @Suor  in https://github.com/iterative/dvc/pull/2375
Http remote will not be working properly in case of `no_traverse=False`, due to fact that `list_cache_paths` is not implemented for `RemoteHTTP`.

**Comment by efiop** [comment]
We can set `no_traverse = False` in RemoteHTTP.__init__ permanently,

**Comment by mroutis** [comment]
Throw an exception if no_traverse is set for HTTP

**Comment by mroutis** [comment]
Add test for this

**Comment by mroutis** [comment]
@efiop , does it make sense to raise an exception? what about defaulting to `traverse`?
Just setting `self.no_traverse = False` on the `RemoteHTTP.__init__` should work as intended.

**Comment by efiop** [comment]
@mroutis But in that case setting that option in config will have no affect on it and user won't even know that it is not working.

**Comment by mroutis** [comment]
@efiop , as @pared  noticed, `list_cache_paths` is not implemented for `RemoteHTTP` (neither `gc`). I'm wondering how `HTTP` was used as a cache :thinking:

**Comment by efiop** [comment]
@mroutis it is used through no_traverse and has been that way always. gc is not implemented because HTTP doesn't support write, http has been always used as read-only(i.e. pull/fetch only).

**Comment by mroutis** [comment]
@efiop , but what are you going to pull if you haven't `push`ed anything?

**Comment by efiop** [comment]
@mroutis You could push through s3 and then pull through http, as we've been doing in dvc for a long time already https://github.com/iterative/dvc/blob/master/.dvc/config#L2

**Comment by shcheklein** [comment]
Yep, the same we do with `example-get-started` - `dvc remote add --local s3` to push and `dvc remote add http` to then expose it to public as a read-only data repo.
