### ISSUE TITLE
Questions about how versioning of non-deterministic large dataset pipelines work

### ISSUE THREAD

**Issue by luisfelipehsr** [iterative/dvc#2382]
I want to use DVC to version a pipeline that makes use of a very large dataset and some parts of it generates large outputs in a non-deterministic way. It's not clear to me how DVC handles this scenario.
From what I understand DVC has the latest versions of these files on remote such that someone can run a `dvc repro` and know that everything is the correct version to generate those results.

* What happens if I keep using a `dvc repro -f`. Does DVC replace those output files and keeps adding them to the cache, which will create a huge cache with time? 
* How does the cache interact with the tags that can be added to git? 
    * Does it only keep track of the versions I have tagged?
    * If it keeps track of the tagged versions, does it move them to remote when I do a `dvc push`, such that it keeps locally only the latest and checked out versions, which will save space? 
    * If someone does a `dvc pull` are all versions downloaded resulting in a really large download?

**Comment by efiop** [comment]
Hi @luisfelipehsr !

> What happens if I keep using a dvc repro -f. Does DVC replace those output files and keeps adding them to the cache, which will create a huge cache with time?

Yes, it will put those files to cache and if they are always different then you will indeed have all of those files in cache.

> How does the cache interact with the tags that can be added to git?
> Does it only keep track of the versions I have tagged?

Tags will only be accounted for if you specify `--all-tags` flag to commands such as `dvc push/pull/fetch/status/gc`.

> If it keeps track of the tagged versions, does it move them to remote when I do a dvc push, such that it keeps locally only the latest and checked out versions, which will save space?

`dvc push`(no flags or arguments) will push only the cache that is used in your current workspace, you need to use `--all-tags` and/or `--all-branches` flags for it to push cache used in tags and/or branches.

> If someone does a dvc pull are all versions downloaded resulting in a really large download?

`dvc pull`(no flags or arguments) downloads cache that is used in your current workspace, it doesn't download data for any other tags/branches. Similar to `push`, `--all-tags/branches` flags could be applied here too :)

**Comment by shcheklein** [comment]
> Does DVC replace those output files and keeps adding them to the cache, which will create a huge cache with time?

There is `--no-commit` option here: https://dvc.org/doc/commands-reference/repro#options. Basically, it means that you will be running `dvc commit` explicitly to save files to cache when you feel that you need this (ready to save a snapshot).

Also, saving files to cache is not the same a pushing them to remote storage. And there is `dvc gc` command that can help you remove unused/unreferenced files in the cache (and in the remote storage if needed).

> ... If it keeps track of the tagged versions, does it move them to remote when I do a `dvc push`, such that it keeps locally only the latest and checked out versions, which will save space?

So, regarding the tags. Nothing special is happening with them. No special integration, etc. They are convenient to specify/expand the scope for gc, push, pull, etc. For example:

`dvc push` - will push only artifacts from your cache that are referenced in the workspace (it does not analyze any history whatsoever, and does not push everything)- it's pretty scoped and granular operation by default.
`dvc push -T` - the same as above but now it analyzes all tags.
`dvc gc` - remove everything from the cache that is not referenced in the workspace.

So, the case you described is more or less default behavior. The only thing you should be doing is run `dvc gc` from time to time (and don't forget to do `dvc push` or `dvc push -T`).

**Comment by shcheklein** [comment]
@luisfelipehsr please check the answers above and let us know if you have more questions.

**Comment by efiop** [comment]
Closing as inactive.
