### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by hankelvin** [iterative/dvc#2388]
**Please provide information about your setup**
DVC version:0.53.2, Platform: MacOSX and method of installation pip

I set up a remote to an S3, but went on to delete it (and all other remotes from dvc remote list), now I have an error on the config file which does not go away even though that remote referenced in the error message is no longer in my dvc remote list, or even after I tried adding a new remote. 

ERROR: configuration error - config file error: config format error: Key 'remote "https://<s3 bucket>.s3-eu-west-1.amazonaws.com/"' error:
Missing key: 'url'

How could I resolve this?

**Comment by efiop** [comment]
Hi @hankelvin !

Could you please show your `cat .dvc/config`? Looks like you didn't add remote correctly in the first place and then removed it without removing the config section for it. How did you remove it, btw?

**Comment by hankelvin** [comment]
hi, thanks for the quick reply! yes i think i didn't set the remote correctly initially. 

cat .dvc/config is:

['remote "<a new S3 bucket remote i just 'dvc remote add' after removing the initial and facing the error>"']
url = s3://<new S3 bucket remote i just 'dvc remote add' after removing the initial and facing the error>

__________

i removed the initial remote with 'dvc remote remove <initial remote name>'

**Comment by efiop** [comment]
@hankelvin So now everything works?

**Comment by hankelvin** [comment]
no it does not. I have not been able to solve the config error as per my first post.

**Comment by efiop** [comment]
@hankelvin Do you have `.dvc/config.local` in your repo? Have you used --local/--system/--global flags when running `dvc remote`?

**Comment by hankelvin** [comment]
yes i do i have .dvc/config.local in my repo. I used --global when trying to set dvc remote

**Comment by efiop** [comment]
@hankelvin Ok, if the error is as it is in the original comment, then try running
```
dvc remote remove https://.s3-eu-west-1.amazonaws.com/ --local
dvc remote remove https://.s3-eu-west-1.amazonaws.com/ --global
```

**Comment by hankelvin** [comment]
it worked! thank you so much @efiop
