### ISSUE TITLE
git checkout some-file causes dvc to try to remove a dvc-managed file

### ISSUE THREAD

**Issue by gthb** [iterative/dvc#2400]
When I `git checkout some-file` to clean away my local changes to that file, the dvc hook butts in and says:

> ERROR: unexpected error - unable to remove 'data/qix/1a285cea-7b71-4492-9b4d-87092bfb9869.json.gz' without a confirmation from the user. Use '-f' to force.

But I did not request removal of that file, and I don't understand why DVC is trying to do that.

Note that I'm _not_ switching to a different branch/tag/commit, because I specified a path to `git checkout`. So I'm only modifying files in my working tree. I don't think that should trigger DVC to [try to] remove files.

Platform: macOS, Python 3.7.4 virtualenv installed using `pyenv`, and:
```bash
$ dvc --version
0.54.1+5e4d26
```

**Comment by efiop** [comment]
@gthb Thanks for reporting this! Looks like we are not using post-checkout parameters that are being passed to us by git and is indicating if we are checking out a specific file or a branch/tag/etc. https://git-scm.com/docs/githooks#_post_checkout We need to adjust our hook accordingly.

**Comment by efiop** [comment]
@gthb Looks like the third parameter is just what we need. You could try modifying your git hook by hand to see if that will do the job for you. If it does, please let us know, and maybe consider submitting a PR, we really appreciate your contributions :slightly_smiling_face: If it doesn't work, please ping us as well.

**Comment by SergioG-M** [comment]
I am having this same issue with dvc 2.12.0 and using pre-commit hooks. I followed the docs https://dvc.org/doc/command-reference/install. Any idea what ay it be?

**Comment by daavoo** [comment]
> I am having this same issue with dvc 2.12.0 and using pre-commit hooks. I followed the docs https://dvc.org/doc/command-reference/install. Any idea what ay it be?

Hi @SergioG-M ! could you open a new issue, sharing a detailed traceback? This issue is really old and the codebase has significantly changed since
