### ISSUE TITLE
`dvc run` suggests to run the command even with --no-exec

### ISSUE THREAD

**Issue by dniku** [iterative/dvc#2401]
`dvc run` contains a hardcoded message for `dvc run` which does not change regardless of whether the `--no-exec` is provided. This message is misleading, as the command is not going to be run if `--no-exec` is present:

https://github.com/iterative/dvc/blob/507879e841aa28bdcc62d238d9f49e218a75c62b/dvc/stage.py#L517-L520

**Comment by jorgeorpinel** [comment]
For details on `dvc run` and its `--no-exec` option see https://dvc.org/doc/commands-reference/run

**Comment by dniku** [comment]
@jorgeorpinel thank you. I am aware of the documentation; the bug report solely indicates that the message is incorrect.

**Comment by jorgeorpinel** [comment]
Hi @dniku I was just adding context to this issue in case a member of the OS community wants to understand the problem and contribute to the project 🙂

**Comment by kss682** [comment]
Hi , I would like to work on this issue .

**Comment by efiop** [comment]
@kss682 Sure! Let us know if you have any questions. :slightly_smiling_face:

**Comment by geo7** [comment]
@efiop Seems that this is can be closed? I think `4042d5232dc8aa5238f800e917e9b062719d8ec9` got rid of the message mentioned in the original comment, and `git grep "Do you wish to run the command"` brings up nothing for me.

**Comment by codeybear** [comment]
I noticed this also when I tried to investigate also, it look like another commit has removed this problem.

**Comment by daavoo** [comment]
The issue was fixed.
