### ISSUE TITLE
Consider changing behavior of `dvc add` related to wdir

### ISSUE THREAD

**Issue by ematvey** [iterative/dvc#2404]
I suggest we change the `dvc add path` behavior to always treat the deepest-level directory in path as a wdir, such that in resulting dvc files wdir will always be `.` and not relative to cwd. Similarly, `.gitignore` should be placed in the same deepest-level directory.

The reason for this proposed change is to 
- make dvc add behavior independant of cwd and more intuitive overall
- make resulting dvc-files and .gitignores as portable as possible
- wdir serve no purpose in `add`ed files anyway

An alternative would be to remove wdir for `add`ed dvc files altogather.

**Comment by efiop** [comment]
@ematvey Regarding the gitignore, it is already placed right beside the output file:
```
mkdir -p a/b
echo foo > a/b/foo
dvc add a/b/foo
```
will create a/b/.gitignore. Maybe I've misunderstood your question?

**Comment by efiop** [comment]
About the wdir and paths in that case, you are right, it is incorrect. Looks like we haven't noticed this bug, but it used to be(and was intended for those precise reasons of portability) to make wdir . and path `foo`.

**Comment by ematvey** [comment]
I might be mistaken about `.gitignore`.
