### ISSUE TITLE
local variable 'old_handler' referenced before assignment

### ISSUE THREAD

**Issue by AlJohri** [iterative/dvc#2406]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

dvc version: 0.55.0 on macos via homebrew cask

![Screen Shot 2019-08-19 at 3 31 14 AM](https://user-images.githubusercontent.com/2790092/63246986-e3a5f100-c231-11e9-8f96-0fcd9c77ba9e.png)

**Comment by AlJohri** [comment]
edit: this is actually on EC2, not macos. installed via pip

**Comment by efiop** [comment]
@AlJohri Could you please run that command with `-v` added and post the full log? I.e. `dvc repro data/raw.dvc -v`

**Comment by efiop** [comment]
Although, I already see where the bug is. Will send a patch ASAP.

**Comment by efiop** [comment]
Alright, I've jumped the gun, 3.x tests have failed, looking into it.

**Comment by AlJohri** [comment]
Thanks for looking into it so quickly!

**Comment by efiop** [comment]
@AlJohri Fixed on master. Triggering the release right now.
