### ISSUE TITLE
Typo in DVC help command

### ISSUE THREAD

**Issue by umangs94** [iterative/dvc#2413]
DVC version 0.54.1

There is a typo in the dvc help command (`dvc -h`):
`version      Show DVC version and system/environment informaion.`

**Comment by shcheklein** [comment]
@umangs94 nice catch ... is it fixed? why did we close this? would be great if you can do a PR with this small fix :)

**Comment by umangs94** [comment]
I closed it because I updated to version 0.55 and noticed that it was fixed. I should have commented before closing it though.
