### ISSUE TITLE
get: relpath in error message for inexistent `path` is not nice

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2430]
UPDATE: See https://github.com/iterative/dvc/issues/2430#issuecomment-524546265

---

~~Example:~~

```console
$ dvc get https://github.com/iterative/dvc.org \
          I-dont-exist.zip
ERROR: failed to get ' ' from 'https://github.com/iterative/dvc.org' - you are not
inside of a dvc repository (checked up to mount point '/')
...
```
> Note that https://github.com/iterative/dvc.org is NOT a DVC project.

First of all, the command takes a long time to error out.

Also, `you are not inside of a dvc repository`? I thought `dvc get` "doesn't require an existing DVC project to run in", at least according to [our docs](https://dvc.org/doc/commands-reference/get) (which I wrote 😋).

```console
DVC version: 0.57.0
Python version: 3.7.3
Platform: Darwin-18.7.0-x86_64-i386-64bit
Binary: False
Filesystem type (workspace): ('apfs', '/dev/disk1s1')
```

---

Maybe related to #2309

**Comment by pared** [comment]
It seems to me that `NoDvcRepoError` should be intercepted [here](https://github.com/iterative/dvc/blob/41351a2df2f36ed04846d5e3d976d6d99b71a151/dvc/external_repo.py#L46) and treated differently than "normal" NoDvcRepo

**Comment by efiop** [comment]
Not able to reproduce this

```
(3.7.0-dvc) ➜  sfd dvc get https://github.com/iterative/dataset-registry I-dont-exist.zip                                                                                   
ERROR: failed to get 'I-dont-exist.zip' from 'https://github.com/iterative/dataset-registry' - unable to find DVC-file with output '../tmpuig76zzhdvc-repo/I-dont-exist.zip'
                                                                                                                                                                            
Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!                                                                                    
```

The relpath in the error msg is not really nice though.

**Comment by jorgeorpinel** [comment]
I can confirm this is no longer happening to me either 🤷‍♂  Updated title and description of issue.

**Comment by pared** [comment]
Its because `https://github.com/iterative/dataset-registry` became dvc repository 3 days ago.

try:
```
dvc get https://github.com/iterative/dvc.org \         
          I-dont-exist.zip
```

**Comment by pared** [comment]
Isse still exists, investigating

**Comment by efiop** [comment]
Reopenning to address non-existent output error in https://github.com/iterative/dvc/pull/2435
