### ISSUE TITLE
gc: dvc gc cli is confusing

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2431]
- there is a `-c` (cloud) flag, but remote cache is collected even if that flag is not set
- even if `-c` is set local cache is still collected
- `dvc gc` collects local and remote caches, but not remotes, which are not set as caches even default one
- `dvc gc -c` collects local, remote caches and default remote
- `dvc gc -r myremote` does not collect `myremote`, but local and registered remote caches
- `dvc gc -c -r myremote` collects local, registered remote caches and `myremote`

Everything feels gobbled up and unsafe.

**Comment by efiop** [comment]
@Suor Maybe let's include this into https://github.com/iterative/dvc/issues/2325 ?

**Comment by Suor** [comment]
@efiop I am ok with it.

**Comment by efiop** [comment]
Closing in favor of #2325
