### ISSUE TITLE
pull: manage dependencies depth

### ISSUE THREAD

**Issue by nisace** [iterative/dvc#2450]
It would be nice to be able to pull target dependencies up to a certain stage.

An example of use case is a pipeline where the first stage is a very big file, followed by an extraction stage of a small part of this file (and this stage won't change very often). After that stage, I want users to quickly iterate. So the starting point for experiments is the small extracted file. I want to have the big file in dvc for reference but only the small file is required for day-to-day experiments.

Consider this pipeline:
```
big-file -> small-extracted-file -> processed-small-extracted-file
```

Some possible solutions:
## 1. lock
`dvc lock small-extracted-file.dvc`
`dvc pull --with-deps processed-small-extracted-file`

Currently (`dvc 0.57.0`) this will pull `big-file` and `small-extracted-file` but wouldn't it make more sense to download `small-extracted-file` only?

## 2. --downstream
Add `--downstream` option for `pull`
`dvc pull --downstream small-extracted-file processed-small-extracted-file`

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/485596304961962003/616250865795334144

**Comment by nisace** [comment]
@mroutis my mistake. I didn't understand `--downstream` correctly. 

What I meant was `dvc pull --with-deps processed-small-extracted-file` starting from `small-extracted-file.dvc`

**Comment by nisace** [comment]
`--with-depth` already exists and it pulls the specified target as well as all its dependencies.

What I suggest is a way to limit the dependencies search to a certain depth (or up to a given stage).

**Comment by nisace** [comment]
hum I was thinking the other way around `dvc pull --with-depth --from 2.dvc 3.dvc`

**Comment by nisace** [comment]
I agree. Maybe fixing `dvc lock` is better.

**Comment by efiop** [comment]
> Or what do you mean by fixing dvc lock ?

@mroutis Check the linked discord discussion. We were talking about introducing pull-specific lock instead of our old repro-lock that we've misused.

**Comment by efiop** [comment]
@mroutis We've heard some scenarios, where some data is public, while other is private and you might want to only push public one(e.g. source data, some intermediate results), but not push stuff like the resulting model that you have your private config file for. Also we've heard about people wanting to push such things to different remotes. Just wanted to mention that we've seen similar requests previously.

**Comment by efiop** [comment]
Another idea https://discordapp.com/channels/485586884165107732/565699007037571084/616471868936945683
