### ISSUE TITLE
gc: produce collection report on success

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2451]
When I run `dvc gc` or/and `dvc gc --cloud` after removing some data from DVC control, it outputs and prompts:

```console
WARNING: this will remove all cache except the cache that is used in the current git branch of the current repo.
Are you sure you want to proceed? [y/n] 
```

Then, when I say `y` it just completes the operation and exits with no more output. Maybe a report of what was collected (and from where) would be more informative. This way the user could know something actually happened, without having to understand and check DVC internals before and after running the command.

> Per https://discordapp.com/channels/485586884165107732/563406153334128681/616421757808541721

**Comment by jorgeorpinel** [comment]
Maybe something to include in #2325

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/2325
