### ISSUE TITLE
Sort output of DVC pipeline list

### ISSUE THREAD

**Issue by AlJohri** [iterative/dvc#2452]
`dvc pipeline list` currently returns an unsorted list

```
experiments/prod/export.dvc
data/make_preprocessor.dvc
experiments/prod/train.dvc
experiments/prod/test.dvc
data/preprocess.dvc
experiments/prod/evaluate.dvc
experiments/old/download.dvc
experiments/old/test.dvc
experiments/old/evaluate.dvc
data/sample.dvc
data/raw.dvc
================================================================================
experiments/google/evaluate.dvc
data/google_test_scores.parquet.dvc
================================================================================
2 pipelines total
```

`dvc pipeline show experiments/prod/evaluate.dvc` works well and shows a sorted list:

```
data/raw.dvc
data/sample.dvc
data/make_preprocessor.dvc
data/preprocess.dvc
experiments/prod/train.dvc
experiments/prod/test.dvc
experiments/prod/evaluate.dvc
```

It would be great to have `dvc pipeline list` output generally sorted by order of execution, perhaps even including an ascii mode.

Ref Confo: https://discordapp.com/channels/485586884165107732/563406153334128681/616740796737126594

**Comment by mroutis** [comment]
@AlJohri , can you give more detail about this? I can't replicate it :thinking: 

```bash
#!/usr/bin/env bash
dvc init --no-scm
dvc run -o 1 'echo 1 > 1'
dvc run -d 1 -o 2 'echo 2 > 2'
dvc run -d 2 -o 3 'echo 3 > 3'

dvc run -o C 'echo C > C'
dvc run -d C -o B 'echo B > B'
dvc run -d B -o A 'echo A > A'
```

`dvc pipeline list`:
```
1.dvc
2.dvc
3.dvc
================================================================================
C.dvc
B.dvc
A.dvc
================================================================================
2 pipelines total
```

**Comment by AlJohri** [comment]
![Screen Shot 2019-08-29 at 5 22 34 PM](https://user-images.githubusercontent.com/2790092/63977360-a3404180-ca81-11e9-8b4a-a39914fafc48.png)

**Comment by AlJohri** [comment]
It's a bit strange because I don't think `experiments/old` should show up in this pipeline?

**Comment by mroutis** [comment]
@AlJohri , Is any of those DVC-files locked?

**Comment by AlJohri** [comment]
@mroutis nope

**Comment by kss682** [comment]
Could I take up this issue , if it is open.

**Comment by efiop** [comment]
@kss682 There is a pending PR for it https://github.com/iterative/dvc/pull/2669  by @SrividyaKK

**Comment by Suor** [comment]
Also, should we up the priority? It's UI time)

**Comment by efiop** [comment]
@Suor Not really, it is not that critical.

**Comment by nvazquez** [comment]
Hi guys, I am working on a fix for this issue on the (work-in-progress) PR: #2928

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/3743
