### ISSUE TITLE
pipeline: list scoped to a directory

### ISSUE THREAD

**Issue by ghost** [iterative/dvc#2453]
Introduce support for listing stages inside a directory, **or** list only the parents/ascendants of a given stage.

Consider the following case were there are two different experiments, each one inside their own directory, however, both rely on a `pre-process` stage (connecting the two experiments with that node):

```bash
#!/usr/bin/env bash
dvc init --no-scm

# Create different directories to store experiments
mkdir {foo,bar}

# Have a pre-process stage
dvc run -f pre-process.dvc -o data "echo data > data"

# Two different experiments depending on the pre-process stage
cd foo
dvc run -d ../data -o 1 'echo 1 > 1'
dvc run -d 1 -o 2 'echo 2 > 2'
dvc run -d 2 -o 3 'echo 3 > 3'
cd ..

cd bar
dvc run -d ../data -o C 'echo C > C'
dvc run -d C -o B 'echo B > B'
dvc run -d B -o A 'echo A > A'
cd ..
```

If you run `dvc pipeline show --ascii foo/3.dvc` you'll see both experiments:

```
          +-----------------+
          | pre-process.dvc |
          +-----------------+
            ***          ***
           *                *
         **                  **
+-----------+             +-----------+
| foo/1.dvc |             | bar/C.dvc |
+-----------+             +-----------+
      *                         *
      *                         *
      *                         *
+-----------+             +-----------+
| foo/2.dvc |             | bar/B.dvc |
+-----------+             +-----------+
      *                         *
      *                         *
      *                         *
+-----------+             +-----------+
| foo/3.dvc |             | bar/A.dvc |
+-----------+             +-----------+
```

This looks pretty, but it will grow depending on the number of experiments, rendering a hard-to-read ascii graph.

Also, the `dvc pipeline list`  could end up like this: https://github.com/iterative/dvc/issues/2452#issue-487179406

It would be better to have a tree-like output like (know, overkill):

```
pre-process.dvc
├── bar
│  ├── C.dvc
│  ├── B.dvc
│  └── A.dvc
└── foo
   ├── 1.dvc
   ├── 2.dvc
   └── 3.dvc
================================================================================
1 pipeline
```

So, the idea was to use introduce a `pipeline list foo/` that outputs something similar to `pipeline show foo/3.dvc`:
```
pre-process.dvc
foo/1.dvc
foo/2.dvc
foo/3.dvc
```

This is related to https://github.com/iterative/dvc/issues/2452

**Comment by efiop** [comment]
> It would be better to have a tree-like output like (know, overkill):

**Comment by efiop** [comment]
Closing as stale.
