### ISSUE TITLE
Missing conda dependency paramiko

### ISSUE THREAD

**Issue by DonjetaR** [iterative/dvc#2463]
Hi I have installed the dvc version 0.54.1 package through the conda channel "conda-forge", but it is missing the package dependency "paramiku".

**Comment by pared** [comment]
Hi @DonjetaR!
Can you post what system are you working on, and command that you used to install dvc?

**Comment by efiop** [comment]
@DonjetaR 0.54.1 is quite old, the current version is 0.58.0, could you please install it and see if it solves the issue for you? :slightly_smiling_face:

**Comment by DonjetaR** [comment]
EDIT: The missing dependency package name was "paramiko" and not "paramiku".

I have conda version 4.7.11 and the command to install dvc was with "conda create -n [environment_name] dvc". Note that I install a lot of other packages too in that environment.

The missing dependecy error ocurred when i ran the command "dvc checkout" as seen below:
ERROR: unexpected error - URL 'ssh://**********' is supported but requires these missing dependencies: ['paramiko']. 

I have installed "paramiko" from the main channel in my conda environment and I have no problems anymore, but thought you should know that that dependecy is missing in the dvc conda package.

**Comment by efiop** [comment]
@DonjetaR 0.54.1 didn't have paramiko listed as a dependency, we've added it later in https://github.com/conda-forge/dvc-feedstock/commit/17caeb63736586a054a7fd53a11ea56d599caa56#diff-e178b687b10a71a3348107ae3154e44c . In the current versions (since 0.55.0) of dvc it should already work, please give it a try.

**Comment by efiop** [comment]
@DonjetaR Thank you so much for reporting this issue! I'll close it for now, as it seems to be solved. If it still doesn't work for you with the never versions, please let us know here and we will reopen the ticket. Thanks! :slightly_smiling_face:

**Comment by DonjetaR** [comment]
Thank you for your answers!
I tried to install a newer version of DVC in my conda environment but there were conflicts for version 0.55, 0.56 and 0.57. 0.58 is not avaliable through conda forge. I think that it's because the dependecies DVC require are newer versions (fx. paramiku>=2.5) and it conflicts with the other packages in my environment. Does DVC really need these new versions of the dependecies?

Right now I'll keep the older version of DVC and install paramiko too, but would like to install a newer version of DVC in the future.

The output in my terminal:
"Solving environment: - 
Found conflicts! Looking for incompatible packages. ..."

**Comment by efiop** [comment]
@DonjetaR 

> Does DVC really need these new versions of the dependencies?

For some of those - yes. E.g. tqdm.

> Right now I'll keep the older version of DVC and install paramiko 2.4.2 too, but would like to install a newer version of DVC in the future.

Sounds good. Be sure to let us know how it will go. 🙂
