### ISSUE TITLE
get: error while fetching DVC-file

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2468]
`dvc get` is to download data artifacts, but if the user hasn't this clear, they might try to `get` a DVC-file and the error is not that clear.

```
❯ dvc get https://github.com/iterative/dvc scripts/innosetup/dvc.ico.dvc
ERROR: failed to get 'scripts/innosetup/dvc.ico.dvc' from 'https://github.com/iterative/dvc' - unable to find DVC-file with output '../../../tmp/tmpbzwhrmqcdvc-repo/scripts/innosetup/dvc.ico.dvc'
```

I suggest showing a message to guard from this behavior:
```
ERROR: failed to get 'scripts/innosetup/dvc.ico.dvc' from 'https://github.com/iterative/dvc' - this is a DVC-file, you must specify the path of an output
```

**Comment by efiop** [comment]
Another way to handle that would be to download all outputs of the specified dvcfile :slightly_smiling_face: But that is more about dvc in general.

**Comment by mroutis** [comment]
@efiop , great suggestion, it is a more straightforward interface, since <path> is always a dvcfile instead of figuring out if the file that you want was cached or not.
