### ISSUE TITLE
Consider throwing exception/logging warning on `dvc init --no-scm` in git repo

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2472]
Currently DVC will silently ignore `--no-scm` on `dvc init` in `git` repository and use `git` as SCM.

That is not a big problem, but can make tests inconsistent:

`def test1(dvc_repo, git)`

and

`def test2(git, dvc_repo)`

will behave differently, as in second case `dvc_repo.scm` is `Git` instance and in first: `NoSCM`

**Comment by jorgeorpinel** [comment]
I ➕1 this.

If a user accidentally `dvc init --no-scm`s in a Git repo, they may end up tracking data both with Git and DVC.

**Comment by jorgeorpinel** [comment]
We could even automate detecting whether there's a Git repo underneath and not offer this option, merging this issue with #2901.

**Comment by efiop** [comment]
This is no longer the case, as `no-scm` is now explicit, so sequential dvc runs won't use git automatically.

@jorgeorpinel `dvc init --no-scm` doesn't look like an accidental thing, it is a very explicit command.

**Comment by jorgeorpinel** [comment]
What do you think about automating Git detection so the `--no-scm` option is not even needed @pared, @efiop, @shcheklein? Is it worth opening its own issue? Thanks

**Comment by efiop** [comment]
@jorgeorpinel So if no git is detected we will assume no-scm? If so, that is error-prone.

**Comment by jorgeorpinel** [comment]
Yes, that's my suggestion. I'm trying to think of how that would be error prone but I'm not seeing it:

If the directory is Git-tracked, why would you use `dvc init --no-scm`? That would be a mistake (as we discussed in https://github.com/iterative/dvc/issues/2472#issuecomment-590184536 and https://github.com/iterative/dvc/issues/2472#issuecomment-591239038 above) so actually not having the explicit option seems like its LESS error-prone from this PoV.

If it's not tracked by Git, you HAVE to use `--no-scm`, or `dvc init` fails.

**Comment by efiop** [comment]
@jorgeorpinel Because it is an explicit action and you might want to `--no-scm` in a git repo if you don't want dvc to mess around with your git. We've used it previously for some debugging purpuses too. Yes, it is a very specific advanced feature that is not popular, but it has its own explicit flag that is unlikely to be used accidentally. Let's just leave it as is, it doesn't harm anything. :slightly_smiling_face:

**Comment by jorgeorpinel** [comment]
> you might want to --no-scm in a git repo if you don't want dvc to mess around with your git. We've used it previously...

OK if this is an actual use case then sure, let's keep it.

But keeping something unnecessary because it doesn't seem to hurt would not be a strong argument IMO, I'd even argue it hurts user experience compared to making it implicit/invisible.

👍
