### ISSUE TITLE
move: does not work with symlinks

### ISSUE THREAD

**Issue by BaruchYoussin** [iterative/dvc#2476]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))
dvc version 0.57.0
Ubuntu 16.04 pip.

@Ruslan at discord said that this link should be enough:
https://discordapp.com/channels/485586884165107732/485596304961962003/620590523144470557

**Comment by pared** [comment]
@BaruchYoussin, you probably meant @efiop  :)

**Comment by BaruchYoussin** [comment]
I am using the name he uses at discord where I had a conversation with him.
