### ISSUE TITLE
typing git login info over https many times upon dvc update

### ISSUE THREAD

**Issue by kaleidoescape** [iterative/dvc#2484]
DVC version: `0.59.2` on debian linux with pip installed DVC.

I made some steps and did `dvc push`, and committed all the dvc files and did `git push`, all on machine1. Now I am on machine2, and I did `git clone myrepo`, and I would like to do `dvc pull`.  This file originally came from a `dvc import` from another repo. I get an error something like:
```
WARNING: DVC-file 'myfile.dvc' is locked. Its dependencies are not going to be checked out.
WARNING: Cache '164d41a82cbe89e43e1ee88bb145a648.dir' not found. File 'myfile' won't be created.
ERROR: failed to download '../../.dvc/cache/16/4d41a82cbe89e43e1ee88bb145a648.dir' to '../../../../../tmp/tmpre5z9crq' - [Errno 2] No such file or directory: '/mypath/.dvc/cache/16/4d41a82cbe89e43e1ee88bb145a648.dir'

ERROR: Failed to load dir cache '../../.dvc/cache/16/4d41a82cbe89e43e1ee88bb145a648.dir' - Expecting value: line 1 column 1 (char 0)
```
It is true what the error says, that there is no file `/mypath/.dvc/cache/16/`... but there is a `/mypath/.dvc/cache`. I believe this problem is related to this issue: https://github.com/iterative/dvc/issues/2423

After I got this error, I performed `dvc update myfile.dvc` and then `dvc pull myfile`. This seemed to work to retrieve the data, although I still can't do `dvc pull` on its own (without the file argument).

However, I currently don't have ssh keys set up on the machine I am working on yet, so when doing the update, I had to type my username/password a bunch of times.

```
Username for 'https://gitlab.com': kaleidoescape
Password for 'https://kaleidoescape@gitlab.com': 
Username for 'https://gitlab.com': kaleidoescape
Password for 'https://kaleidoescape@gitlab.com': 
Username for 'https://gitlab.com': kaleidoescape
Password for 'https://kaleidoescape@gitlab.com': 
WARNING: Output 'myfile' of 'myfile.dvc' changed because it is 'not in cache'
WARNING: Stage 'myfile.dvc' changed.
Importing 'myfile (https://gitlab.com/myrepo.git)' -> 'myfile'
Username for 'https://gitlab.com': kaleidoescape
Password for 'https://kaleidoescape@gitlab.com': 
Username for 'https://gitlab.com': kaleidoescape
Password for 'https://kaleidoescape@gitlab.com': 
Username for 'https://gitlab.com': kaleidoescape
Password for 'https://kaleidoescape@gitlab.com': 
Output 'myfile' didn't change. Skipping saving.                                                                                                                                                   
Saving information to 'myfile.dvc'.
```

**Comment by pared** [comment]
Might be related #2305 #2310

**Comment by efiop** [comment]
Will be fixed by https://github.com/iterative/dvc/issues/2490

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/2583 .

**Comment by efiop** [comment]
@kaleidoescape 0.63.3 is out. Please give it a try and let us know if it fixed it for you :) Thanks for the feedback!
