### ISSUE TITLE
ui: very short progress bar

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2487]
On master branch.

Steps to reproduce:
- create a dvc repo
- create a directory of 150 moderately large files, say 10mb
- `dvc add` them

The progress bar looks like 10 chars in width.

**Comment by efiop** [comment]
@Suor a screenshot would be helpful to assess the severity.

**Comment by efiop** [comment]
@Suor 

> is ugly

Less ugly then it was originally without tqdm. I dont think this one counts as urgent.

> has limited functionality (poorly shows progress)

Not really, since it has the right part to it where you get more granular `N/M` thingy. Again, not urgent.

> So I would say either revert to misaligned ones or put text on top of the bar body and invert text/background color when it is filled.

Reverting would be problematic for this one, I would rather not do that. What do you mean by inverting? Not sure I follow that one.

**Comment by casperdcl** [comment]
I'm assuming inverting means black text on white background where necessary (to have description drawing on top of the bar).

Not sure if there's a reliable cross-platform way to display such a thing. Also wouldn't work well on non-unicode envs which will currently display hashes for the bar.

**Comment by shcheklein** [comment]
Is there a specific reason to keep so small? Can we do a quick fix to make it 3x wider?

I agree with Ruslan, the whole output might change soon, so I would not put too much effort into fixing this, just a cosmetic minor quick stuff if it's possible.

**Comment by casperdcl** [comment]
the problem with fixing to say width 30 is increased chance of overflow (on narrow terminals or long descriptions)

**Comment by shcheklein** [comment]
@casperdcl yeah, totally, I was just assuming probably that we can calculate in advance or tqdm supports this - and specify something like this `min(30, number of symbols to the description)`

**Comment by Suor** [comment]
I am against fixed pbars, these look bad.

**Comment by Suor** [comment]
BTW, the reason behind fixed with bars is several of those dancing when we perform some work in several threads.

**Comment by Suor** [comment]
This shows how tqdm looks by default and in dvc: https://asciinema.org/a/283771
It looks pathetic in dvc. May we fix it?
