### ISSUE TITLE
import: downloads repository every time

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2490]
```bash
dvc init --no-scm
dvc import https://github.com/iterative/dvc scripts/innosetup/dvc.ico

# Adding '../../../tmp/tmpp4_abkehdvc-repo/.dvc/tmp' to '../../../tmp/tmpp4_abkehdvc-repo/.dvc/.gitignore'.

dvc unlock dvc.ico.dvc
dvc repro dvc.ico.dvc

# Adding '../../../tmp/tmpqx36r24_dvc-repo/.dvc/tmp' to '../../../tmp/tmpqx36r24_dvc-repo/.dvc/.gitignore'.
```

Why not using `.dvc/repositories` to store the imported git repository?

**Comment by efiop** [comment]
For the record, this is the main cause for https://github.com/iterative/dvc/issues/2484

**Comment by efiop** [comment]
Need to figure out possible options to solve it. E.g. possible solutions right now are:

1) Cache cloned repos (will need to implement switching branches though); E.g. in https://github.com/iterative/dvc/blob/master/dvc/external_repo.py#L18 ;

2) Cache credentials (so need to ask them and then pass them to git clone)
