### ISSUE TITLE
Erroneous (?) configuration error when --local is omitted from dvc config

### ISSUE THREAD

**Issue by gwerbin** [iterative/dvc#2502]
DVC: `0.59.2`, installed with Conda
Python: `Python 3.6.9 :: Anaconda, Inc.`
Platform: Linux kernel 3.10.0, x86-64

```bash
dvc config cache.dir /share/data
dvc config cache.dir
```
correctly prints `/share/data`. However
```bash
dvc config cache.dir /share/data
dvc config --local cache.dir
```
produces
```
ERROR: configuration error - config file error: section 'cache' doesn't exist
```
even though the local `.dvc/config` was updated by the command.

Running
```bash
dvc config --local cache.dir /share/data
dvc config --local cache.dir
```
works as expected.

**Comment by efiop** [comment]
@gwerbin Local config is `.dvc/config.local` and not `.dvc/config`(which we sometimes call project/repo config). So `dvc config --local cache.dir` tries to access `.dvc/config.local`, which doesn't have section `cache` in it.
