### ISSUE TITLE
long running dvc add does not print a message to use symlinks, hardlinks

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#2508]
Comes from a discussion on ODS. User was trying to add 4TB data.

Check that it's actually happening. Or may be message is just not visible enough?

Check other operations that are affected by cache type (checkout, pull).

Write tests to make sure we don't break it in the future again.

**Comment by efiop** [comment]
For the record: https://opendatascience.slack.com/archives/CGGLZJ119/p1568705318005400

**Comment by pared** [comment]
Ok, so it seems that the problem with "Consider other link types" warning is that it shows up when a single linking operation takes more than 10 seconds. Clearly, that applies only to copying huge singular files. If the user adds a directory, the limit might never be reached, and the message might not be displayed. We should probably consider how to apply `slow_link_guard` to directory-related operations. The first thing that comes to my mind, would be to consider slow_link_guard as a static object that would aggregate time spent on linking.

 Now that I wrote it down, that does not sound elegant.

**Comment by Suor** [comment]
Should we raise it to p1? Since we onto UI somewhat nowdays)

**Comment by dberenbaum** [comment]
@dtrifiro Using the UI to manage performance expectations is another direction we can pursue. Putting this as p2 for now, but let me know if you have any thoughts on it.
