### ISSUE TITLE
lock: improve error message when .dvc/lock is taken

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2520]
https://github.com/iterative/dvc/pull/2519#discussion_r326844119

**Comment by mroutis** [comment]
related: #2559

**Comment by shcheklein** [comment]
related: https://discordapp.com/channels/485586884165107732/485596304961962003/633654336110460929

**Comment by shcheklein** [comment]
related:
https://discordapp.com/channels/485586884165107732/485596304961962003/640511613698441217

it's tempting to make it p-0 ... we keep answering the same question over and over again

**Comment by algomaster99** [comment]
@efiop Shall I assign this to myself?

**Comment by shcheklein** [comment]
@algomaster99 yes, feel free to take it

**Comment by shcheklein** [comment]
Related: https://discordapp.com/channels/485586884165107732/485596304961962003/643849467069595668
