### ISSUE TITLE
about improving `dvc remove`

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc#2521]
There is a discussion [here](https://discordapp.com/channels/485586884165107732/565699007037571084/623904108750831639) about deprecating `dvc move` and `dvc remove`.

About `dvc remove`, it seems that it is useless, and even misleading and dangerous for data-tracking files (those created with `dvc add`), but it is OK for stage files (created with `dvc run`).
   1. One suggestion to improve `dvc remove` for data files is to give it as argument the data file itself (not the corresponding `.dvc` file). Then the option `-p, --purge` would remove the `.dvc` file and the cached file as well.
   2. For stage files it should work as it works right now: we give it the stage file (`.dvc`) as argument, and it removes its outputs. However with the option `-p, --purge` it would remove not only the stage file itself (as it does now), but the cached files as well.

This would be like combining two different commands into a single one, but it seems reasonable to me and makes sense.

If we would like to split those commands (maybe in the future), we could do it like this: `dvc data remove` and `dvc stage remove`. However this obviously requires a new level of subcommands, which right now does not seem to be feasible.

**Comment by efiop** [comment]
Related to https://github.com/iterative/dvc/issues/763

**Comment by mroutis** [comment]
> P.s. Can we create a label "discussion"? Because "question" does not feel quite right.

@dashohoxha , great suggestion!

**Comment by shcheklein** [comment]
Btw, what happens if outputs are not cached? In docs we write "This command safely removes data files", is it true in that case? Do we prompt or notify that data will be lost?

**Comment by mroutis** [comment]
@shcheklein , glad that you asked :sweat_smile: 
It looks like we have a bug because there's no prompt on this one:

```
dvc init --no-scm
echo 'foo' > foo
dvc add foo
rm -rf .dvc/cache
dvc remove foo.dvc
```

**Comment by mroutis** [comment]
@shcheklein , if that's the case, it is not that hard to solve:
```diff
diff --git a/dvc/repo/remove.py b/dvc/repo/remove.py
index 6c751e56..89e8832e 100644
--- a/dvc/repo/remove.py
+++ b/dvc/repo/remove.py
@@ -7,7 +7,9 @@ def remove(self, target, outs_only=False):
 
     stage = Stage.load(self, target)
     if outs_only:
-        stage.remove_outs(force=True)
+        with self.state:
+            for out in stage.outs:
+                out.cache.safe_remove(out.path_info)
     else:
         stage.remove(force=True)
 ```

We will would need to improve UI, tho, because it will be redundant:
```console
$ dvc remove foo.dvc
file 'foo' is going to be removed. Are you sure you want to proceed? [y/n]

```

**Comment by dashohoxha** [comment]
Closing in favor if this: https://github.com/iterative/dvc/issues/2575
