### ISSUE TITLE
fetch: refactor exception logic

### ISSUE THREAD

**Issue by ghost** [iterative/dvc#2522]
https://github.com/iterative/dvc/pull/2499#discussion_r326868308

**Comment by efiop** [comment]
To be clear, this is more about `DependencyRepo` and the way we import data in it's `download` method, which caused such a weird logic in `fetch()` that has to catch those exceptions noted in an attached comment.

**Comment by efiop** [comment]
Closing as stale. Erepo logic will be refactored.
