### ISSUE TITLE
Crash if .dvc is a symlink

### ISSUE THREAD

**Issue by dniku** [iterative/dvc#2530]
tl;dr: if the `.dvc` directory is a symlink pointing elsewhere, `dvc` cannot function.

Steps to reproduce:

```bash
mkdir /tmp/test-dvc
cd /tmp/test-dvc
git init
dvc init
mv .dvc ../dvc
ln -s /tmp/dvc .dvc
dvc status
```

Output:

```
ERROR: unexpected error - /tmp/dvc/config.local

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
```

In my particular case, the rationale for having `.dvc` elsewhere is the fact that I store my code under a synchronization tool (ownCloud), and I do not want to store there my data as well.

Environment:

```bash
$ dvc --version
0.59.2
$ uname -srv
Linux 4.19.69-1-MANJARO #1 SMP PREEMPT Thu Aug 29 08:51:46 UTC 2019
```

`dvc` is installed via `pip`.

**Comment by dniku** [comment]
This is most likely an invalid complaint. `git` does not interpret symlinks transparently, so it becomes impossible to store, for example, `.dvc/config` under `git`. Furthermore, there is the [`cache.dir`](https://dvc.org/doc/commands-reference/config#cache) option that solves my problem.

**Comment by efiop** [comment]
@dniku Glad you've found a solution! :slightly_smiling_face: It is still not nice that we fail like that, so let's keep this issue open, we'll try to take a look to see if there is anything we can do to make this work properly or at least not to fail as abruptly. Thank you for the feedback!

**Comment by omesser** [comment]
@efiop  - today, trying this seems to fail reasonably:
```sh
❯ dvc status
ERROR: '/MYPATH/tmp/dvc/config.local' is outside of git repository '/MYPATH/tmp/dvc_symlink'
```

If it's not meaningful enough to tackle anytime soon, I suggest to close 🤷 
🧹 🧹 🧹

**Comment by dberenbaum** [comment]
@omesser I'll close and @efiop can reopen if needed.
