### ISSUE TITLE
How can I update dvc file to not cause the whole pipeline rerun?

### ISSUE THREAD

**Issue by markb21** [iterative/dvc#2534]
DVC version: 0.60.0
Platform: Ubuntu
Method of installation: pip

I have defined pipeline with two steps. I realised that I need to update imports in the script for the first step because directory structure has changed. It means that update does not change anything (output will be the same after rerunning the updated script).
However, dvc detects the change and tries to rerun the whole pipeline after dvc repro. How can I update my script so that dvc does not detect change?

**Comment by efiop** [comment]
Hi @markb21 ! Just run `dvc commit`, it will re-calculate all the hashes without running your command.

**Comment by markb21** [comment]
Cool. Thank you very much :)

**Comment by efiop** [comment]
@markb21 Sure :) Let us know if you have any questions.
