### ISSUE TITLE
ui: pbar during md5 calc doesn't need to be multithreaded 

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2539]
The "Mutithreaded" prefix is confusing, also jumping through screen doesn't work with redirection well.

**Comment by shcheklein** [comment]
💯 on this!

**Comment by casperdcl** [comment]
@Suor just to confirm for other multi-threaded commands is `screen` still giving you trouble?

perhaps this is https://github.com/tqdm/tqdm/issues/798 - you [may need `screen -U`](https://stackoverflow.com/questions/52250556/tqdm-in-screen-environment-printing-new-line-and-unknown-charactors)

**Comment by Suor** [comment]
Never ran `dvc` in `screen`. I had, however, similar problem when redirecting `dvc` output, special line up sequence got swallowed somewhere in the process.

**Comment by efiop** [comment]
Btw, @casperdcl , just wondering, does tqdm use `is_tty` to avoid printing some things when it is not using a console?

**Comment by casperdcl** [comment]
@efiop no, that would be an interesting feature request. The thing is if you pipe output to a file and then `cat` the file, often the control characters are parsed properly.

**Comment by efiop** [comment]
@casperdcl Yeah, but you usually don't `cat` if you redirect it to a file :) If you are redirecting, then you want a log file to read later(to grep, to vim or whatever), which doesn't need control chars and they might even be harmful. I'm pretty sure I've seen tools use `isatty` to distinguish those cases a lot. Our old progress bar did that too if I recall correctly. The downside of that approach is that now you suddenly have two types of outputs, which might cause some things to not get enough testing. So there are pros and cons to both approaches, for sure.

**Comment by casperdcl** [comment]
nvm correction this was solved way back in https://github.com/tqdm/tqdm/pull/281 - it's just propagated to `dvc`.
