### ISSUE TITLE
errors: add hints to solve the errors, if possible

### ISSUE THREAD

**Issue by ghost** [iterative/dvc#2559]
We can take as an example the way Elm handles errors in the compiler: https://elm-lang.org/news/compiler-errors-for-humans

DVC already does this in some extent but I'm sure there's room for improvement on this one.

Also, thinking about introducing another method for logger: `hint`, that will output something like:

```
ERROR: this stuff failed
HINT: you could try X or Y prevent this from happening
```

(`HINT` could be colored in purple)

**Comment by jmhsi** [comment]
Ivan was helping me on discord and it seems relevant:

My error:
ERROR: failed to run command - file/directory 'data/csvs/raw_zipped_csvs' is specified as an output in more than onestage: run/01_download_LC_csvs.dvc
    data/csvs/raw_zipped_csvs.dvc

Potential Hints:
HINT: try running `dvc pipeline show --ascii data/csvs/raw_zipped_csvs.dvc`
HINT: remove 'data/csvs/raw_zipped_csvs' as an output from "run/01_download_LC_csvs.dvc" or
    "data/csvs/raw_zipped_csvs.dvc" with `dvc remove`

**Comment by efiop** [comment]
First step: improve ^ error to something like

```
ERROR: failed to run command - file/directory 'data/csvs/raw_zipped_csvs' is already taken by `data/csvs/raw_zipped_csvs.dvc`, consider using a different output name.
```

**Comment by efiop** [comment]
Closing as too generic. Output message was improved, we are trying to fix things as we go.
