### ISSUE TITLE
Warning messages in stdout

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#2561]
```
$ dvc -V
0.60.1+39104a
$ dvc pipeline show > OUT
$ cat OUT
WARNING: assuming default target 'Dvcfile'.
data/data.xml.dvc
prepare.dvc
featurize.dvc
train.dvc
evaluate.dvc
Dvcfile
```

The warning message `WARNING: assuming default target 'Dvcfile'.` is supposed to be in stderr, not stdout. This seems to work just fine for error messages, but not for warnings.

Many other commands might have the same warning issue. It would be great if this can be fixed holistically.

**Comment by pared** [comment]
Might be related: https://github.com/iterative/dvc/issues/1291

**Comment by efiop** [comment]
@pared You are right, it is the same thing. Looks like we've lost it during logger redesign.

**Comment by mroutis** [comment]
@efiop , @pared  #1291 is not the same thing, this is about warning messages (the other one was about `ERROR` messages :slightly_smiling_face: )
