### ISSUE TITLE
Local cache directory creation does not propagate the parent directory persmissions

### ISSUE THREAD

**Issue by mazzma12** [iterative/dvc#2563]
**Please provide information about your setup**
* DVC >= 0.59
* Platform : Ubuntu 18.04 

Cache directory does not inherit their parent ownership settings, **if they are created by DVC**. For example, the directory created by dvc will lack write permissions for the user group. This can cause conflicts when using the share group option for multi-user access (iterative/dvc.org#497)

If the cache directory referenced by `dir = /myPath`  exists, there is no problem. The current workaround is to create beforehand the cache directory path with the right permissions

Thanks for helping  @efiop !

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/563406153334128681/628897840839786496
