### ISSUE TITLE
dvc add is too verbose

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#2565]
```
$ dvc -V
0.60.1+39104a

$ vi sea_ice.csv # Modify a data file

$ dvc add sea_ice.csv # Update the data file
WARNING: Output 'sea_ice.csv' of 'sea_ice.csv.dvc' changed because it is 'modified'
Saving 'sea_ice.csv' to '.dvc/cache/c9/3f5350dae07d4fbbbade828c805f93'.
Saving information to 'sea_ice.csv.dvc'.

To track the changes with git, run:

	git add sea_ice.csv.dvc
```

3 lines - it is too much. At least the 2nd line (about cache) is not needed.

**Comment by mazzma12** [comment]
+1 for this, IMO the quite option should be default. 
Also related, the section about tracking to git is not often easy to copy paster from terminal, especially on remote servers with files running on multilines screen. An option like `--git ` to stage automatically would be great

**Comment by dashohoxha** [comment]
> An option like `--git` to stage automatically would be great

Maybe staging to Git should be the default behavior for `dvc add`, because this is what you want and what you do in 99% of the cases. If someone does not want `.dvc` files to be tracked by Git, he can unstage them.

This is what `dvc init` already does. Maybe `dvc run` should do it too.
In general, all the commands that output a suggestion like `git add ...`, they should actually do it, instead of suggesting it, and then inform the user that they staged those files to git (the same way that they inform that they saved the data files to cache).

**Comment by mazzma12** [comment]
> Maybe staging to Git should be the default behavior for `dvc add`, because this is what you want and what you do in 99% of the cases. If someone does not want `.dvc` files to be tracked by Git, he can unstage them.

+1, Default make more sense from what I have experienced. And just `git reset` if you don't want it

**Comment by algomaster99** [comment]
@efiop Can I take up this issue? To summarize the tasks here:
- Explicitly add `--verbose` to display all 3 lines.
- Make `dvc add` stage files to git too.
Am I correct?

**Comment by pared** [comment]
@algomaster99 
Definitely, point nr 1 makes sense.
Having said that, second point should probably be discussed in a separate issue. It is definitely not logging problem and also it indicates changing behaviour of one of our commands.

**Comment by dmpetrov** [comment]
It was solved already. Closing.
```
$ dvc add fffff
100% Add|██████████████████████████████████████████████|1/1 [00:00,  1.40file/s]

To track the changes with git, run:

	git add .gitignore fffff.dvc
```

**Comment by mazzma12** [comment]
> @algomaster99
> Definitely, point nr 1 makes sense.
> Having said that, second point should probably be discussed in a separate issue. It is definitely not logging problem and also it indicates changing behaviour of one of our commands.

For the record, this was discussed here (#4330) and was merged already
