### ISSUE TITLE
pip install errors: moto/boto3, awscli/colorama, requests?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2570]
> As noted in https://discordapp.com/channels/485586884165107732/565699007037571084/629449391266070563

I already have the repo cloned. I fetch and pull the latest master branch (to this moment) and freshly regenerate my virtualenv in `.env`, activate it and run `pip install -e ".[all,tests]" ` (as instructed in https://dvc.org/doc/user-guide/contributing). It succeeds but I get the following errors:

```console
Building wheels for collected packages: psutil
...
ERROR: moto 1.3.14.dev302 has requirement boto3>=1.9.201, but you'll have boto3 1.9.115 which is incompatible.
ERROR: awscli 1.16.252 has requirement colorama<=0.3.9,>=0.2.5, but you'll have colorama 0.4.1 which is incompatible.
```

**Comment by pared** [comment]
@jorgeorpinel 
What can you give some more details about your env? I am unable to reproduce on fresh `Python 3.7.4` environment,
tried:
`pip install -e ."[all,tests]"`
and
`pip install -e ."[all,tests]" --no-cache`

**Comment by jorgeorpinel** [comment]
OK so I pull the latest version of master (`449f43f3`) rn, I make sure no venv is active and remove my previous `.env` dir. Then:

```console
$ virtualenv --python python3 .env
...
$ source .env/bin/activate
...
$ pip install -e ".[all,tests]"  

Obtaining file:///.../dvc
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting requests>=2.22.0 (from dvc==0.61.2+449f43)
...
## See full output in https://pastebin.com/f7c59V4n
...
Collecting jsonpointer>=1.9 (from jsonpatch->cfn-lint>=0.4.0->moto>=1.3.14.dev55; extra == "tests"->dvc==0.61.2+449f43) ...
Building wheels for collected packages: pathspec, aws-sam-translator
  Building wheel for pathspec (setup.py) ... done
  ...
Successfully built pathspec aws-sam-translator
ERROR: awscli 1.16.252 has requirement colorama<=0.3.9,>=0.2.5, but you'll have colorama 0.4.1 which is incompatible.
ERROR: moto 1.3.14.dev312 has requirement boto3>=1.9.201, but you'll have boto3 1.9.115 which is incompatible.
talling collected packages: certifi, ...
$ which dvc
/Users/drbidibombom/dvc/.env/bin/dvc
$ dvc version             
DVC version: 0.60.1
Python version: 3.7.3
Platform: Darwin-18.7.0-x86_64-i386-64bit
Binary: False
Cache: reflink - True, hardlink - True, symlink - True
Filesystem type (cache directory): ('apfs', '/dev/disk1s1')
Filesystem type (workspace): ('apfs', '/dev/disk1s1')
```

**Comment by jorgeorpinel** [comment]
BTW I just upgraded my system DVC with `pip3 install dvc --upgrade` and it worked but with 2 red lines:
```
docker-compose 1.23.2 has requirement requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1, but you'll have requests 2.22.0 which is incompatible.
awsebcli 3.15.3 has requirement requests<2.21,>=2.20.1, but you'll have requests 2.22.0 which is incompatible.
```
which seems like a similar thing.
`dvc version` after update:
```console
DVC version: 0.61.2
Python version: 3.7.3
Platform: Darwin-18.7.0-x86_64-i386-64bit
Binary: False
Cache: reflink - True, hardlink - True, symlink - True
Filesystem type (cache directory): ('apfs', '/dev/disk1s1')
Filesystem type (workspace): ('apfs', '/dev/disk1s1')
```

**Comment by efiop** [comment]
> BTW I just upgraded my system DVC with pip3 install dvc --upgrade and it worked but with 2 red lines:

This one is about your previously installed packages, that require something else than what dvc requires. There is nothing we can do about it on our side.

**Comment by efiop** [comment]
And these
> ERROR: awscli 1.16.252 has requirement colorama<=0.3.9,>=0.2.5, but you'll have colorama 0.4.1 which is incompatible.
> ERROR: moto 1.3.14.dev312 has requirement boto3>=1.9.201, but you'll have boto3 1.9.115 which is incompatible.
are valid and are our fault, as our `all` reqs conflict with `test` reqs, which doesn't affect users, but does affect developers in a minor way. We should fix that, for sure.

**Comment by shcheklein** [comment]
> This one is about your previously installed packages, that require something else than what dvc requires. There is nothing we can do about it on our side.

How is it possible if it was installed in the clean `virtualenv`?

**Comment by efiop** [comment]
@shcheklein Apparently it wasn't clean, but rather inherited from the global env. `docker-compose` and `awsebcli` are definitely not our dependencies.

**Comment by jorgeorpinel** [comment]
> How is it possible if it was installed in the clean virtualenv?

Ruslan is right about that one @shcheklein. In that https://github.com/iterative/dvc/issues/2570#issuecomment-538624781 I was referring to updating my system DVC installed as a package with `pip`, not to the development version installed as a git repo. Sorry for the confusion, we can safely ignore that comment and focus on https://github.com/iterative/dvc/issues/2570#issuecomment-538645844:

> are valid and are our fault, as our all reqs conflict with test reqs, which doesn't affect users, but does affect developers in a minor way. We should fix that, for sure.

**Comment by jorgeorpinel** [comment]
p.s. do you mind if I hide https://github.com/iterative/dvc/issues/2570#issuecomment-538624781 and all its responses, kinda off-topic and now resolved? 😋

**Comment by efiop** [comment]
> p.s. do you mind if I hide #2570 (comment) and all its responses, off-topic and now resolved?

@jorgeorpinel Please don't hide comments. These were related to the topic.

**Comment by mroutis** [comment]
is this still relevant?

**Comment by efiop** [comment]
@mroutis Yes, it is, I've seen it myself not that long ago.

**Comment by edisongustavo** [comment]
Hello, I am also affected by this issue.

I think the root cause of the problem is that DVC requires a [specific version of boto3](https://github.com/iterative/dvc/blob/4917a6e818fe71296ca4800df6492c9fdea08c82/setup.py#L98):

```
s3 = ["boto3==1.9.115"]
```

The problem is that this makes DVC impossible to install DVC together with other libraries that also depend on boto3 that don't fit this specific requirement.

My proposal is to depend on a version of boto3 that is newer than 1.9.115:
1. `boto3>=1.9.115,<2` (pin to major version)
2. `boto3>=1.9.115,<1.10` (pin to minor version).

I think option **1** is the best. I don't really believe that boto3 will break compatibility in the future `1.*` versions. I wouldn't recommend option **2** because it requires bumping DVC's version when an upgrade to boto3 is required.

**Comment by mroutis** [comment]
Thanks, @edisongustavo :) ! There's a PR already that should fix this https://github.com/iterative/dvc/pull/2902

**Comment by mroutis** [comment]
@edisongustavo , by the way, it felt a bit weird that I submitted the PR after your comment. It looks  discouraging, to some extend, maybe you had the intention to submit a PR for it :slightly_smiling_face: I just had the commit laying right there a few hours before but forgot to create the PR :see_no_evil:  https://github.com/iterative/dvc/issues/2570#ref-commit-4fd7013
Thanks again for your comment, appreciate your research! :slightly_smiling_face:

**Comment by edisongustavo** [comment]
@mroutis hahaha, no no, not at all :)

I just wanted to give a signal that this is also important for me :)
