### ISSUE TITLE
ImportError: sys.meta_path is None on repo in script

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2573]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

Dvc installed via `pip install -e ."[all,test]"` in virtualenv with `Python 3.6.8`.

Reproduction:
1. Create repo:
```
#!/bin/bash
rm -rf repo
mkdir repo
cd repo
set -e
set -x

git init >> /dev/null && dvc init -q
```

2. Try to initialize it in script:
```
from dvc.repo import Repo
repo = Repo("repo")
```

3. Result:
```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/prd/development/tools/venvs/dvc3.6/lib/python3.6/site-packa
ges/flufl/lock/_lockfile.py", line 331, in __del__
  File "/home/prd/development/tools/venvs/dvc3.6/lib/python3.6/site-packa
ges/flufl/lock/_lockfile.py", line 326, in finalize
  File "/home/prd/development/tools/venvs/dvc3.6/lib/python3.6/site-packa
ges/flufl/lock/_lockfile.py", line 285, in unlock
  File "/home/prd/development/tools/venvs/dvc3.6/lib/python3.6/site-packa
ges/flufl/lock/_lockfile.py", line 312, in is_locked
  File "/home/prd/development/tools/venvs/dvc3.6/lib/python3.6/site-packa
ges/flufl/lock/_lockfile.py", line 459, in _touch
ImportError: sys.meta_path is None, Python is likely shutting down
```

4. Something to start with:
if we `del repo` before the end of the script, the problem does not occur.

**Comment by efiop** [comment]
@pared this doesn't happen during normal CLI operation, right?

**Comment by pared** [comment]
@efiop correct, it seems like its in-script use issue.

**Comment by efiop** [comment]
@Suor FYI ^ , maybe you have any ideas :)

**Comment by Suor** [comment]
@efiop flufl locks have destructor, heh. It's their issue and they even [have it reported](https://gitlab.com/warsaw/flufl.lock/issues/7) 7 months ago, with no reaction.

We can use workaround provided there or just make `.__del__()` noop, not sure we need it.
