### ISSUE TITLE
Potential bug when testing run with metrics_no_cache

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2574]
In our test base, `TestDirFixture.CODE` copies src to target. It can cause problem if one decides to write a test like:

```
dvc_repo.add(repo_dir.FOO)
metric_file = "metric.txt"
dvc_repo.run(
        deps=[repo_dir.FOO],
        metrics_no_cache=[metric_file],
        cmd="python {} {} {}".format(repo_dir.CODE, repo_dir.FOO, metric_file),
    )
```
In this case metric is not supposed to be in cache. But due to fact that it is identical as `repo_dir.FOO` it is inside cache, so we might end up "finding" it for example [here](https://github.com/iterative/dvc/blob/092c498baac40be46185588596af6727bedd9c01/dvc/repo/__init__.py#L464). Which can lead to some unexpected behaviour.

Currently, there is no test using CODE to create metric, so I would not prioritize this task, though we should do something to discourage or prevent this use case.

**Comment by efiop** [comment]
Closing as stale
