### ISSUE TITLE
dvc: CheckoutError is not properly postponed for multiple targets

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2580]
On master branch.

Checkout errors are collected and postponed in `Repo._checkout()` this means that for `dvc checkout/pull` with multiple targets error will be raised on first not fully successfully checked out target and the rest will be skipped.

Also, the error collection process is very cumbersome we might want to invent something better.

**Comment by efiop** [comment]
> Checkout errors are collected and postponed in Repo._checkout() this means that for dvc checkout/pull with multiple targets error will be raised on first not fully successfully checked out target and the rest will be skipped.

Not sure I follow. So we are postponing them so that we checkout everything we can and then fail, so how are we skipping? Could you clarify, please?

**Comment by Suor** [comment]
For multiple targets we call ._checkout() multiple times. Any of those
might fail preventing checkout for remaining targets.

вс, 6 окт. 2019 г., 23:54 Ruslan Kuprieiev <notifications@github.com>:

**Comment by efiop** [comment]
@Suor Ah, I see. Good point, we should've supported multiple targets in checkout a long time ago.
