### ISSUE TITLE
dvc: missing caches and DownloadError

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2581]
Missing caches yields a warning while any other error leading to partial fetch leads to `DownloadError`. This discrepancy will cause issues, e.g. with `CheckoutError` later.

An example would be this test:
https://github.com/iterative/dvc/blob/156fc9d4e1b438a5b9766a343af090f8bd22385c/tests/func/test_import.py#L67-L81

If we repalce `shutil.rmtree(erepo.root_dir)` with `shutil.rmtree(erepo.dvc.cache.local.cache_dir)`, then suddenly we don't have `DownloadError` anymore it's `CheckoutError`, but maybe that test is just bad.

**Comment by efiop** [comment]
@Suor Are you sure this happens on master and not in your caching patch?

**Comment by Suor** [comment]
The issue is that missing caches is not an error, in master, it never was. This made some sense while we were ignoring download errors also, but it's an incoherency, which will cause issues.

**Comment by Suor** [comment]
This is related to https://github.com/iterative/dvc/pull/2608

**Comment by dmpetrov** [comment]
@Suor was this issue resolved by #2608?

**Comment by Suor** [comment]
@dmpetrov No, that PR was not solving this and it was closed not merged.

**Comment by skshetry** [comment]
Closing as stale.
