### ISSUE TITLE
Blobfuse does not support symlinks - Errno 38 Function not implemented

### ISSUE THREAD

**Issue by smohan123** [iterative/dvc#2594]
**# dvc add --verbose training_output/metrics.json
ERROR: unexpected error - [Errno 38] Function not implemented: '/opt/engine/notebooks/data/.dvc/tmp/80edfb5c2896b5bbebbfc5fb9739dad0.lock' -> '/opt/engine/notebooks/data/.dvc/updater.lock'**
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/dvc/main.py", line 40, in main
    cmd = args.func(args)
  File "/opt/conda/lib/python3.7/site-packages/dvc/command/base.py", line 47, in init
    updater.check()
  File "/opt/conda/lib/python3.7/site-packages/dvc/updater.py", line 51, in check
    self._with_lock(self._check, "checking")
  File "/opt/conda/lib/python3.7/site-packages/dvc/updater.py", line 41, in _with_lock
    with self.lock:
  File "/opt/conda/lib/python3.7/site-packages/flufl/lock/_lockfile.py", line 334, in enter
    self.lock()
  File "/opt/conda/lib/python3.7/site-packages/dvc/lock.py", line 54, in lock
    super(Lock, self).lock(timedelta(seconds=DEFAULT_TIMEOUT))
  File "/opt/conda/lib/python3.7/site-packages/flufl/lock/_lockfile.py", line 216, in lock
    os.link(self._claimfile, self._lockfile)
OSError: [Errno 38] Function not implemented: '/opt/engine/notebooks/data/.dvc/tmp/80edfb5c2896b5bbebbfc5fb9739dad0.lock' -> '/opt/engine/notebooks/data/.dvc/updater.lock'
 
**dvc version
0.60.1**
 
**Python version: 3.7.3
Platform: Linux-4.15.0-1059-azure-x86_64-with-debian-stretch-sid
Binary: False
Cache: reflink - False, hardlink - False, symlink - False
Filesystem type (cache directory): ('fuse', 'blobfuse')
Filesystem type (workspace): ('fuse', 'blobfuse')**
 
mroutisToday at 10:32 AM
@samir , DVC uses links for its locking mechanism, it looks like your file system doesn't support it :confused:
 
samirToday at 10:33 AM
...it is mounted Blob storage where i have initialized Git and DVC
 
mroutisToday at 10:34 AM
@samir , you can interact with azure blob storage through dvc push/pull commands, but I think it is not that convenient; @ruslan do you have any workaround for this?
 
ruslanToday at 10:35 AM
@mroutis @samir you just can't use have the workspace for your repo on that fs, but you totally can use it as a cache directory.
blobfuse doesn't support symlinks in it, but I wonder if it supports symlinks pointint from another fs to it...
if so you could have your dvc repo on a normal filesystem, say in ~/mydvcproj and
dvc config cache.dir /path/to/blobfuse/dir/mycache
dvc config cache.type symlink
dvc config cache.protected true

so it will create symlinks to your cache on blobfuse
 
samirToday at 10:39 AM
ok i was discussing with a colleague and that was what we were pondering, though i think these commands were not known to either of us
my directory structure is engine/notebooks/data <-- this is where the volume is mounted
so i will dvc init and git init in notebooks and then use your commands to try to point to files inside of data
if i understand both your advice
 
ruslanToday at 10:40 AM
yes, sounds good. Do you version your notebooks with git?
I imagine git doesn't really work on blobfuse as well.
 
samirToday at 10:43 AM
we do version with git for notebooks but we do a CICD process to build the container with the notebook in it for our Dev. i like to work in local and then push and have it reprovision.
out of curiosity, in your experience, is blob just more difficult than other filesystem options in this regard?
 
ruslanToday at 10:47 AM
@samir to be honest, I don't have that much experience with blobfuse specifically, but it is true that we've heard more limitations related to it than to things like sshfs, s3fs, etc. But than again, it might be that those are less popular or that those users just silently vanish once they hit any problems, we can't really know. :slight_frown:
@samir 

i like to work in local and then push and have it reprovision.

not sure how it works with the approach of trying to have dvc repo as a whole on the blogfuse mount.
@samir You could also set that mount as a dvc remote and push to it. It would look like
dvc remote add myremote -d /path/to/blobfuse
dvc push
 
samirToday at 10:51 AM
point #1 i totally get. :sweat_smile: 
point #2 i like that concept except i am worried that i lose my .dvc files if my container goes down, which is why i had wanted to initialize inside of data originally
 
ruslanToday at 10:54 AM
@samir hm, looks like I don't quite get it :slight_smile:
So what is "my container"? It is a temporary container that CI/CD uses?
to, like, run dvc repro?
@samir if it is the case, I would consider making it create a PR or push to itsown git repo, so that you don't lose .dvc files.
 
samirToday at 10:57 AM
kubernetes orchestrated docker container....
 
mroutisToday at 11:07 AM
@samir , so, for a recap, you are using docker containers to run your experiments (which are in jupyter notebooks) with a mounted blobfuse to access your data, right?
 
samirToday at 11:17 AM
yeah right
 
mroutisToday at 11:19 AM
@samir , and you are using git to version your notebooks and want to use dvc to version your data, right?
 
samirToday at 11:19 AM
spot on
 
mroutisToday at 11:27 AM
@samir , again, as part of the recap, having a dvc repository (created by the dvc init command) under blobfuse won't work, since the locking mechanism needs links.

You need to use dvc init somewhere else (for example, under the notebooks directory); wondering how you persist your code changes on the container; is notebooks a mounted volume?
@samir , when you are talking about the CI/CD process, are you also mounting the blobfuse on the container?
 
samirToday at 11:32 AM
notebooks is not a mounted volume. we don't persist the other data. we rely on git for that. CICD does a checkout of the project when it provisions the container. then volume mount blob storage under data (also at provisioning time)
i push my notebook to the repo and changes to master trigger reprovisioning
 
**mroutisToday at 12:06 PM
@samir , it's quite complicated, looks like blobfuse doesn't support symlinks https://github.com/Azure/azure-storage-fuse/pull/212/files

you can try it by doing:
cd notebooks/data
touch something
ln -s something link

RESULT:
ln: failed to create symbolic link 'linkls': Function not implemented**

**Comment by mroutis** [comment]
Discord conversation: https://discordapp.com/channels/485586884165107732/485596304961962003/631859232307675136

**Comment by mroutis** [comment]
@smohan123 , after checking and discussing with @efiop ; the only think you can do in this case is to configure the cache to `copy`. This will duplicate the data under the blob storage.
A more detail explanation:

Usually, users have their dvc repository alongside their git one.
This is because DVC creates files that references the _versioned_ data (the so-called _dvcfiles_). 
All these versions are stored under a _cache directory_ (by default `.dvc/cache`).
Then `dvc` links or copy the data from the cache to the _original location_.
So, when you run `dvc checkout` it creates a link/copy from the cache to the working directory (that's why it is fast).

For example:
```bash
dvc init --no-scm
echo "foo" > foo
dvc add foo
```

If you inspect the directory tree, you'll find the following:

```
.
├── .dvc
│  ├── cache
│  │  └── d3
│  │     └── b07384d113edec49eaa6238ad5ff00
│  ├── config
│  ├── state
│  ├── tmp
│  └── updater
├── foo
└── foo.dvc
```

If you `rm foo` and then `dvc checkout` it will link or copy `.dvc/cache/d3/b07...` to `foo`.

To prevent data duplication DVC tries to use links (i.e. reflink, hardlink, symlink) but as I already stated _blobfuse_ doesn't support links (although, there's an open pull request to support symlink). You can configure the cache to use `copy`.

I'm closing this issue because it is on the `blobfuse` side to support links.

Let me know if you have more questions :)

**Comment by mroutis** [comment]
For the record, this issue was a follow up from a Discord conversation.
