### ISSUE TITLE
Issue with dvc push to AWS s3 remote

### ISSUE THREAD

**Issue by jonhilgart22** [iterative/dvc#2598]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

DVC: 0.62.1
Mac: Mojave 10.13
Install with pip

issue with `dvc push`

![image](https://user-images.githubusercontent.com/8621935/66682880-fc77c500-ec2a-11e9-9c37-6e276bca005a.png)

**Comment by efiop** [comment]
Hi @jonhilgart22 ! Could you show `dvc version` output please?

**Comment by jonhilgart22** [comment]
![image](https://user-images.githubusercontent.com/8621935/66685343-14524780-ec31-11e9-896c-a1205f585e64.png)

**Comment by efiop** [comment]
@jonhilgart22 Thanks! And could you show `dvc push -v` output, please?

**Comment by jonhilgart22** [comment]
![image](https://user-images.githubusercontent.com/8621935/66685441-65fad200-ec31-11e9-90f4-5d6708eaac08.png)

![image](https://user-images.githubusercontent.com/8621935/66685449-6d21e000-ec31-11e9-9329-cbcb61c21aff.png)

**Comment by efiop** [comment]
@jonhilgart22 And `pip freeze | grep tqdm` please?

**Comment by jonhilgart22** [comment]
![image](https://user-images.githubusercontent.com/8621935/66685558-c0942e00-ec31-11e9-9955-27de5d80b95f.png)

**Comment by jonhilgart22** [comment]
Weird - I just tried `dvc push` again and it worked.

**Comment by efiop** [comment]
@jonhilgart22 Hm, just like that? O_o You've done nothing else and it started working?

**Comment by jonhilgart22** [comment]
yep! strange

**Comment by efiop** [comment]
@jonhilgart22 Maybe you've updated python or something recently? We've seen some flukes like that when virtualenv breaks after updating a python.

**Comment by jonhilgart22** [comment]
Not sure but thanks for the help!

**Comment by jonhilgart22** [comment]
Alright, I'm running into this issue again.

I've installed DVC inside of a pipenv.


![image](https://user-images.githubusercontent.com/8621935/66968269-23723480-f039-11e9-8ac4-9a28bc5611ae.png)

**Comment by jonhilgart22** [comment]
![image](https://user-images.githubusercontent.com/8621935/66968280-3422aa80-f039-11e9-9d54-77aec055ce8e.png)

**Comment by efiop** [comment]
Hi @casperdcl ! Seems to be related to tqdm. Maybe you have some ideas? :slightly_smiling_face:

**Comment by casperdcl** [comment]
@jonhilgart22 can you run `tqdm --version` in the pipenv too?

**Comment by jonhilgart22** [comment]
tqdm=4.36.1

**Comment by casperdcl** [comment]
I wonder if this is some sort of edge case with `=` in the filenames or something similar. The best way to debug this would be if @jonhilgart22 could patch `tqdm/std.py` and post the error output.

```diff
diff --git a/tqdm/std.py b/tqdm/std.py
index 8c73c8f..9d9938b 100644
--- a/tqdm/std.py
+++ b/tqdm/std.py
@@ -466,7 +466,10 @@ class tqdm(Comparable):
                 bar_format = "{l_bar}{bar}{r_bar}"
 
             full_bar = FormatReplace()
-            nobar = bar_format.format(bar=full_bar, **format_dict)
+            try:
+                nobar = bar_format.format(bar=full_bar, **format_dict)
+            except:
+                raise KeyError(bar_format + "<-" + str(format_dict))
             if not full_bar.format_called:
                 # no {bar}, we can just format and return
                 return nobar
```
or
`pip install --force-reinstall git+https://github.com/tqdm/tqdm.git@bar_format_bug#egg=tqdm`

**Comment by jonhilgart22** [comment]
after 

`pip install --force-reinstall git+https://github.com/tqdm/tqdm.git@bar_format_bug#egg=tqdm`


I see this.

![image](https://user-images.githubusercontent.com/8621935/67039789-ee1c2400-f0d6-11e9-9d8a-717361b41f68.png)

**Comment by casperdcl** [comment]
well I just typed that all out rather than asking for text to copy-paste :)

problem was `ncols_desc==0`.

**Comment by efiop** [comment]
@casperdcl Great investigation! Thank you! :tada: 

@jonhilgart22 Btw, may I ask why are you taking a photo of your screen instead of copy-pasting? I'm honestly really curious :slightly_smiling_face:

**Comment by casperdcl** [comment]
yes I felt it was urgent. Thankfully didn't get distracted trying to tweak an OCR program to work on the image!

Also thankfully not an upstream [@tqdm/tqdm](https://github.com/tqdm/tqdm/) bug.

Also surprised by how critical this bug is yet how hard it would've been to trace without the last response (https://github.com/iterative/dvc/issues/2598#issuecomment-543319161) and without knowing a lot about `tqdm` internals.

**Comment by efiop** [comment]
@jonhilgart22 0.63.3 is out, please feel free to give it a try :) Thanks for the feedback!

**Comment by jonhilgart22** [comment]
Thanks for the quick response!
