### ISSUE TITLE
remote: a bug in _collect_used_dir_cache() for non local

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2631]
On master branch.

These lines
https://github.com/iterative/dvc/blob/638aaa254ea475947545edd046116befe82040f1/dvc/output/base.py#L360-L366
try to pull dir listing to local cache, but later we try to open it on remote, with `self.cache.open(...)`.

**Comment by efiop** [comment]
For the record: This is a leftover from the time when we didn't have `Remote.open()`.

**Comment by dmpetrov** [comment]
Guys, is it still relevant?

**Comment by Suor** [comment]
@dmpetrov yes, it doesn't lead to an error though, only makes unneeded download or status check if a dir listing is already downloaded.

**Comment by efiop** [comment]
Yeah, let's close now.
