### ISSUE TITLE
update/uninstall: add these commands?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2637]
> From https://github.com/iterative/dvc.org/issues/702#issuecomment-543536849

- `dvc update` - depending on how DVC was installed, the process is different and you may forget how it was installed and finding out exactly may not always be so trivial. Maybe we can simplify this by providing a self-update (version upgrade) command? (We already have an update notice.)
- `dvc uninstall` - same but for completely removing DVC from the system. Maybe leaving global config unless `--config` is used.

**Comment by jorgeorpinel** [comment]
Per #2611 it seems we already detect most of the kinds of installs.

**Comment by mroutis** [comment]
@jorgeorpinel , my experience with `update` commands are not nice at all. I think it is not worth it.
`uninstall` is also a weird one :thinking: .

I'm not sure what's the experience of the rest, but with mine, I'd hesitate to add this.

**Comment by shcheklein** [comment]
@jorgeorpinel agreed with @mroutis on this one. It's not very common for CLI tools to have a special command for this. Neither it is easy to implement to make it work reliably.

**Comment by shcheklein** [comment]
closing this for now. I think it too early and too complicated to have these commands

**Comment by jorgeorpinel** [comment]
OK, iterative/dvc.org/issues/702 should be enough then. Thanks!
