### ISSUE TITLE
DVC assumes pythonpath will be set which is not necessarily true

### ISSUE THREAD

**Issue by nagisa** [iterative/dvc#2652]
```
$ dvc cache dir ../dvc_cache/
Traceback (most recent call last):
  File "/nix/store/lm2jmpn00yjizgqyimaa973gsp2ap8vw-python3.6-dvc-0.40.7/bin/.dvc-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/lm2jmpn00yjizgqyimaa973gsp2ap8vw-python3.6-dvc-0.40.7/lib/python3.6/site-packages/dvc/main.py", line 53, in main
    Analytics().send_cmd(cmd, args, ret)
  File "/nix/store/lm2jmpn00yjizgqyimaa973gsp2ap8vw-python3.6-dvc-0.40.7/lib/python3.6/site-packages/dvc/analytics.py", line 261, in send_cmd
    daemon(["analytics", analytics.dump()])
  File "/nix/store/lm2jmpn00yjizgqyimaa973gsp2ap8vw-python3.6-dvc-0.40.7/lib/python3.6/site-packages/dvc/daemon.py", line 103, in daemon
    env['PYTHONPATH']
KeyError: 'PYTHONPATH'
$ dvc --version
0.40.7
```

**Comment by efiop** [comment]
@nagisa Thanks for reporting this issue! I see that you are using a very old dvc version. Could you please upgrade and see if that issue still reproduces? Current dvc version is 0.63.4

**Comment by nagisa** [comment]
Not able to update it currently, but a brief look at the code suggests that `PYTHONPATH` is still unconditionally indexed [`here`](https://github.com/iterative/dvc/blob/bfc0a3596f9ea633dc7037de07be958b7f322525/dvc/daemon.py#L102) and there appear to be no attempts to fix it up anywhere in either the old version nor the master.

**Comment by efiop** [comment]
@nagisa But we are setting it there, not getting it. It won't cause KeyError, since we are the ones who are setting that key in that line.

**Comment by nagisa** [comment]
Oh, in that case it must be fixed. Thanks for pointing it out :)

**Comment by efiop** [comment]
@nagisa Btw, even in 0.40.7 I'm not seeing `env['PYTHONPATH']` https://github.com/iterative/dvc/blob/0.40.7/dvc/daemon.py#L102 . I'm not seeing it in newer or older files. This is quite strange. Is there anything special about your setup?

**Comment by nagisa** [comment]
It is special in that `nix` is used to build `dvc`, but, otherwise, not really.

**Comment by efiop** [comment]
@nagisa I'm not familiar with nix :thinking: But it has to be the cause, most likely. Please feel free to try a newer version, if nix pkg is still broken, please try contacting its maintainers too, since they are probably more familiar with this type of issues. But if pip is also available for you, I would try it out as well, as it will most likely work. :slightly_smiling_face:
