### ISSUE TITLE
"dvc pull" shows progress bar too early 

### ISSUE THREAD

**Issue by nik123** [iterative/dvc#2653]
**Information about setup**

DVC version: 0.63.4
Method of installation: pip
Platform: Ubuntu Linux 16.04

**Description:**
I access my dvc remote via ssh. Whenever I execute `dvc pull` command dvc asks for passphrase for my RSA key and immediately shows progress bar before I've entered anything from my keyboard:

```
Enter a private key passphrase or a password for host 'ipaddress' port 'port' user 'dvcrepo':
  0%|          |Querying cache in ssh://dvcrepo@ipaddress:port/path/to/dvc                                                                                                                                                  0/1 [00:00<?,     ?file/s]
```

Such format is confusing: first time I've executed `dvc pull` I was wondering for several minutes why cache quering stuck on 0% before I realized that dvc expects me to enter passphrase.

Progress bar should be shown **after** I've entered passphrase.

**Comment by shcheklein** [comment]
@casperdcl could you take a look please?

**Comment by casperdcl** [comment]
ah, the bar might actually be showing before the prompt, but it's just drawn below all text (including the prompt).
