### ISSUE TITLE
version: detect and show the way DVC was installed

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#2655]
The way the `dvc version` command works:

```
$ dvc version

DVC version: 0.41.3+f36162
Python version: 3.7.1
Platform: Linux-4.15.0-50-generic-x86_64-with-debian-buster-sid
Binary: False
Cache: reflink - False, hardlink - True, symlink - True
Filesystem type (cache directory): ('ext4', '/dev/sdb3')
Filesystem type (workspace): ('ext4', '/dev/sdb3')
```

It outputs only `Binary: False` or `Binary: True` depending on how DVC was installed. Which is not granular enough.

See also docs: https://dvc.org/doc/command-reference/version

We can try and use the logic behind the update message (`def _get_package_manager(self)` from the `updater.py`) to show in the `dvc version` output how exactly DVC was installed - `pip`, `conda`, `brew`, package, etc. It'll help to **debug faster**, **potentially can help users when they need to upgrade**.

Almost all the logic required should be available already in the before mentioned `updater.py`

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/issues/2611
