### ISSUE TITLE
DVC file cannot be a dependency

### ISSUE THREAD

**Issue by fmannhardt** [iterative/dvc#2662]
**Please provide information about your setup**
dvc 0.63.4
Windows

I updated DVC to 0.63.4 and now get the error message:

> ERROR: failed to fetch data from the cloud - Stage file 'data/sealant.dvc' cannot be a dependency.

for any operation. This seems to be related to the following change: https://github.com/iterative/dvc/pull/2493

I understand that it was wrong usage to use the DVC file as input instead of its output. I can fix this manually in the file, but what about my GIT history? How can I get the result for previous tags or branches that I cannot update. This seems to break the whole project and cannot be repaired, which is a serious issue.

**Comment by efiop** [comment]
Hi @fmannhardt !

You are using `-a` and/or `-T` flag with `dvc fetch`, right?

**Comment by fmannhardt** [comment]
No, the error also occurred when simply calling:
`dvc fetch`
and there is a .dvc file in the repository that refers to another .dvc file as dependency. 

My problem is basically that I can change this for the future, but when I need to checkout an old tag then I would be unable to fetch the results.

**Comment by efiop** [comment]
@fmannhardt Got it. So you can just fix it for now. In theory tags and branches can be updated too, but I totally see your point. We will consider changing this error for a warning, it doesn't seem like that would hurt anything much. Really we should've risen that error since day 1, but we were missing that until now 🙁 Thanks for the feedback!

**Comment by shcheklein** [comment]
@efiop is it still `p-0`?

**Comment by efiop** [comment]
@shcheklein We didn't see any other reports yet and this one does have a workaround, so we'll lower it a bit for now.

**Comment by efiop** [comment]
We haven't received any reports about this(it has been quite a few versions released since october), so we'll keep the error as is.
