### ISSUE TITLE
skip dag checks for large repos

### ISSUE THREAD

**Issue by danfischetti** [iterative/dvc#2666]
"dvc add <file>" can take hours in a repo with 1000s of files, due to the `repo.check_modified_graph(stages)` step. Can we make this configurable so I can avoid checking the graph if i know I'm not introducing cycles? 

Similarly, when we `checkout` a file, the `repo.collect` step will always create a graph `G = graph or self.graph`, even if i explicitly pass in the path for a single file. This graph construction is extremely costly with large repos, and isn't used for checking out individual files.

**Comment by efiop** [comment]
Hi @danfischetti !

This is a lack of optimization for large DAGs on our side. Ideally, we should investigate it and optimize it, 1000 nodes in a DAG shouldn't take hours, for sure. But if you need quick and effective solution, just monkey patch `check_acyclic` with `noop` and you should be set. I suppose you are only using dvc through API, right? If so, then monkey patch is the best quick and dirty solution here. I don't think we should introduce config option for such a hack, but we should fix it properly by optimizing :slightly_smiling_face:

**Comment by efiop** [comment]
@danfischetti Btw, could you post cProfile output, please? That way we can have a better overlook at what is slowing you down.

**Comment by efiop** [comment]
Tried to check if `check_acyclic` was slow with
```
import networkx as nx                   
from dvc.repo.graph import check_acyclic
                                        
G = nx.scale_free_graph(20000)          
                                        
check_acyclic(G)                        
```

but it only took 1 sec. So looks like it is not the culprit, looking into `_collect_graph`...

**Comment by efiop** [comment]
@danfischetti Ok, found the issue. We are using `nx.simple_cycles` instead of simply using `nx.find_cycle` which is a lot faster. Preparing a patch right now.
