### ISSUE TITLE
install: Mac pkg is from an unidenfitied developer

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2677]
Not easy to install the MacOS pkg obtained from the Download button on dvc.org landing page:

![image](https://user-images.githubusercontent.com/1477535/67628475-14a73100-f834-11e9-9ba9-51c23bf9eaa4.png)

Of course this can be overcome from the Security & Privacy panel in System Preferences, but I don't know if a lot of people know this:

<details>

![image](https://user-images.githubusercontent.com/1477535/67628507-a57e0c80-f834-11e9-8d94-cd4fbf38d55e.png)

</details>

Also I assume this is a known problem but I'm not seeing an existing issue to track progress, if anything can be done about it.

Related: iterative/dvc.org/issues/749

**Comment by shcheklein** [comment]
Yeah as far as I remember you can hold Cmd or Ctrl when you click the package to install it - it will give an option to install right away. Would be great to figure out how to sign it though. The same for Windows. Just haven't had enough time to that yet.

**Comment by shcheklein** [comment]
We can add a note into install page about Ctrl or Cmd trick for now.

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/issues/936

**Comment by efiop** [comment]
Kinda considering getting rid of os-specific installers, as there is brew and chocolatey and pip etc. But need to think about downsides carefully. If we decide to keep the installer, then need to get some keys to sign stuff properly. Similar to https://github.com/iterative/dvc/issues/936

**Comment by jorgeorpinel** [comment]
> ...you can hold Cmd or Ctrl when you click the package to install it - it will give an option to install right away .

I was able to do this! Using the "Open with..." menu, accessible with right-click (secondary click or Ctrl+click):

![image](https://user-images.githubusercontent.com/1477535/67652536-fa8c5200-f90a-11e9-834a-c1fc8b9e2ed8.png)
![image](https://user-images.githubusercontent.com/1477535/67652571-1bed3e00-f90b-11e9-9d23-aa746dd375a2.png)

> ...considering getting rid of os-specific installers ...

Related: iterative/dvc.org/issues/749

**Comment by jorgeorpinel** [comment]
>  We can add a note into install page about Ctrl or Cmd trick for now.

Note added in https://github.com/iterative/dvc.org/pull/725/commits/d557fe142cd377a310ca2bb3b83479fd4274c82c!

For more info on how to sign/notarize Mac app, see https://developer.apple.com/developer-id/

**Comment by dmpetrov** [comment]
@iterative/engineering should we prioritize this issue? It seems important.

**Comment by efiop** [comment]
@dmpetrov I don't think we should, as our primary mac packages are brew, conda, pip. pkg might be dropped at some point.

**Comment by dmpetrov** [comment]
pip and conda are not the best installation methods actually - it forces you to install DVC for each of your virtual env. It is great to support OS-specific packages with the assumption it does not take too much of our resources.

PS: we can potentially outsource this issue - it seems pretty independent.

**Comment by jorgeorpinel** [comment]
> obtained from the Download button

Well, if we prioritize iterative/dvc.org/issues/919 in the docs repo, maybe this one won't be as urgent.

But still, `brew` although great implies the extra step to install Homebrew, so I'm not sure how many people will still prefer the package anyway.

**Comment by efiop** [comment]
I don't think that there are many of our target audience that have mac that don't have brew. :slightly_smiling_face:  It is like a defacto standard package manager. Maintaining a pkg is a hustle (previously discussed pyinstaller) and uninstalling it is cumbersome and updating is even worse, unless we invest in some auto-updater, which feels wasteful.

**Comment by jorgeorpinel** [comment]
Is this still relevant or p2 now that we want to remove the Mac download from the dvc.org download button? See dvc.org/issues/919.

**Comment by efiop** [comment]
@jorgeorpinel Yes, still relevant as long as we are keeping it. Could lower it to p3, sure.

**Comment by efiop** [comment]
mac pkg is signed and notarized. See https://github.com/iterative/dvc/issues/936#issuecomment-801533021 .

E.g. 2.0.17 installs without any warnings

**Comment by jorgeorpinel** [comment]
Great!
