### ISSUE TITLE
install: "Cask 'dvc' is not installed." error

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2680]
Installed DVC 0.64.0 via pkg on MacOS:

```console
$ dvc version
DVC version: 0.64.0
Python version: 3.6.5
Platform: Darwin-19.0.0-x86_64-i386-64bit
Binary: True
Cache: reflink - True, hardlink - True, symlink - True
Filesystem type (cache directory): ('apfs', '/dev/disk1s5')
Filesystem type (workspace): ('apfs', '/dev/disk1s5')
```

Cloned and changed into the cloned iterative/example-get-started project, and ran dvc pull twice. Second run:

```dvc
$ dvc pull
Error: Cask 'dvc' is not installed.
+----------------------------------------------------------+
|                                                          |
|            Update available 0.64.0 -> 0.66.0             |
|                Find the latest release at                |
|     https://github.com/iterative/dvc/releases/latest     |
|                                                          |
+----------------------------------------------------------+

Everything is up to date.                                                                                                                                     
```

I realize this may be a fixed bug but just double checking it's not related to the updater.

**Comment by jorgeorpinel** [comment]
*updater

**Comment by efiop** [comment]
@jorgeorpinel I think it happens here https://github.com/iterative/dvc/blob/0.66.1/dvc/updater.py#L176 since we are not silencing the output.

**Comment by efiop** [comment]
For the record, we can remove cask detection now, as we've abandoned it.

**Comment by efiop** [comment]
So one would need to delete https://github.com/iterative/dvc/blob/0.66.3/dvc/updater.py#L126 and this code block https://github.com/iterative/dvc/blob/0.66.3/dvc/updater.py#L173

**Comment by kss682** [comment]
I would like to work on it .

**Comment by efiop** [comment]
@kss682 Sure, go ahead! 🙂

**Comment by jorgeorpinel** [comment]
Thanks guys. So to summarize, the outputmentioned in https://github.com/iterative/dvc/issues/2680#issuecomment-546743254 should be silenced and Cask detection should be removed, as mentioned in https://github.com/iterative/dvc/issues/2680#issuecomment-549063932). Right?
