### ISSUE TITLE
pull: wrong warning on pulling import stage

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#2685]
Script to reproduce:

```
mkdir test
dvc import https://github.com/iterative/example-get-started model.pkl
git add .
git commit -am "init"
cd ..
git clone test test1
cd test1
dvc pull
```

outputs only:

```
WARNING: DVC-file 'model.pkl.dvc' is locked. Its dependencies are not going to be checked out.
```

I think there should be no warning, especially considering that it has done the job - pulled the `model.pkl`. Like we discussed in #2667 there should be some statistics instead.

**Comment by sadielbartholomew** [comment]
Hi, I will give this a try for Hacktoberfest if that's okay?

**Comment by shcheklein** [comment]
@sadielbartholomew absolutely! let us know if you need any help.

**Comment by Amith1206** [comment]
Is this issue solved?

**Comment by efiop** [comment]
@Amith1206 It is not, but it is taken by @sadielbartholomew

**Comment by skshetry** [comment]
Looks like this was fixed long time ago. I'm not able to reproduce, and find out what fixed it.
