### ISSUE TITLE
ui: remove multi threaded prefix before each progress bar

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#2686]
When you run even a simple `dvc pull` for a single dvc file for a project that has only one data file it still shows the `Multi threaded` prefix before the progress bar.

```
git clone https://github.com/iterative/example-get-started
cd example-get-started
dvc pull
```

outputs some like:

```
Multi-Threaded:
 17%|█▋        |data/prepared/train.ts...
```

Commands like `dvc pull`, `dvc push`, etc are affected. I would expect to see something meaningful instead: `Downloading files (multiple threads)` or even w/o multiple threads.

Sometimes this `Multi-Threaded:` is blinking and replacing the progress bar itself which makes experience even worse.

**Comment by harsh8398** [comment]
@shcheklein you just want different static message right? or want some conditional message?

**Comment by kurianbenoy** [comment]
I would like to work on this, I am curious what is causing this Multi-Threaded message to come though?

**Comment by shcheklein** [comment]
@harsh8398 it's better to have a conditional message - that describes what is happening depending on the command.

We def should remove the blinking behavior.

@kurianbenoy feel free! but please coordinate with @harsh8398 if needed and please ask an advice with @casperdcl  - an expert in TQDM :)

**Comment by casperdcl** [comment]
https://github.com/iterative/dvc/blob/a48481b01fd607b36f9ea5b643af24c938254f60/dvc/progress.py#L23

but @shcheklein "Sometimes this `Multi-Threaded:` is blinking and replacing the progress bar itself which makes experience even worse." shouldn't happen - is this still a thing after #2546?

**Comment by casperdcl** [comment]
I'm referring to specifically the blinking and overwriting. Shouldn't happen.

Anyway there has to at least be a temporary blank line (could replace `"Multi-Threaded:"` with an empty string) as that's by far the most painless way of letting `tqdm` know about being in multi-threaded mode.

**Comment by Suor** [comment]
Didn't get the last thing. Why tqdm can't be in multi-threaded mode without stating that with a message?

**Comment by kurianbenoy** [comment]
So @casperdcl will it be possible to write conditional messages for each command as @shcheklein said?
