### ISSUE TITLE
add: cleanup and improve output

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#2699]
- [x] tidy up remaining stats (no need for `<00:00`, add total size in bytes, etc)
- [ ] add progress to other uses of `stage.dump`
- [x] profile `repo.check_modified_graph()`, `stage.save()`, `stage.dump()` etc to find out what other functions are slow, perhaps add progress for them too
  + md5sums only take about 10% of the total time. There must be other more time consuming functions
- [x] make sure we don't show an extra progress bar when there is only one target (majority of cases, see below)
- [x] cleanup output when if fails  https://github.com/iterative/dvc/issues/2699#issuecomment-548082165
- [x] large dirs progress bar hanging when collecting files before computing checksums https://github.com/iterative/dvc/issues/2770 https://github.com/iterative/dvc/issues/2699#issuecomment-548149404 
- [ ] make sure that we show HINT message to enable cache optimization properly when copy is taking too long already 

---------------------

**Extra progress bar concern:**

We started using an extra progress bar that is counting targets, as described and shown here: #2658 . In most cases though there is a single target - `dvc add file` or `dvc add directory`. That extra progress bar is not needed in those cases. It's needed in case of multiple targets or if `-R` option is specified.

**Comment by shcheklein** [comment]
Also, when if fails to add the output is also confusing: 

```
100%|██████████|Add                                                  1/1 [00:02<00:00,  2.86s/file]
ERROR: output 'n01667114' does not exist
```

Failure or success or both?

**Comment by shcheklein** [comment]
Also on a large directory it looks like it hangs for a long time on:

```
  0%|          |Add                                                           0/1 [00:00<?,     ?file/s]
```

not clear what is it doing inside before running the `Computing hashes` phase.

**Comment by Suor** [comment]
+1 on final message and the rest.

We never had systematic approach to UI, this is the core reason of all of these.

**Comment by shcheklein** [comment]
💯 on `We never had systematic approach to UI, this is the core reason of all of these.` 🙏

**Comment by shcheklein** [comment]
Also, it looks like on Windows `dvc add` does not print anything at all for a long period of time. I don't see any progress bars whatsoever.

**Comment by shcheklein** [comment]
Created a separate ticket to deal with the missing output on Windows - #2747

**Comment by efiop** [comment]
Also, would probably have to add a progress bar for `RemoteBase._save_dir` since it takes quite a while on dirs with giant number of files.

**Comment by shcheklein** [comment]
@efiop @casperdcl just to double check - all checkboxes are fixed in this ticket?

**Comment by casperdcl** [comment]
no it's continued in #3060

**Comment by casperdcl** [comment]
@shcheklein @efiop I think this (#2699) can be closed as #3060 mentions everything outstanding without needing to come back here for more context.

**Comment by casperdcl** [comment]
I've also checked more boxes here given #2846

**Comment by efiop** [comment]
Closing.
