### ISSUE TITLE
remote: fail if does not exist

### ISSUE THREAD

**Issue by nkrot** [iterative/dvc#2700]
This is my first use of dvc and I may have missed something. If so, please disregard this issue.

So, I have configured remote to be a directory accessible via ssh. However, the last component in this path does not exist. I would expect `dvc` to fail but in reality, missing subdirectory was created on the remote machine when I pushed.

Illustration:
```
#  on the remote machine, we create a remote to the user project named `your-project`
mkdir -p /var/dvc-storage/your-project

# the user, on his/her own machine configures the remote in the wrong way
dvc remote add -d ssh://user@host/var/data/dvc-storage/your-project/someshit
# and then
dvc push
```

As a result, the subdirectory `somethit` is created and `dvc push` succeeds. Would it make sense to restrict remote to existing locations only, to avoid that user mess up the storage? This behaviour could be configurable but the default should be restrictive, imo.

kind regards,

**Comment by Suor** [comment]
This is intended and worked this way from the start, so it would be hard to change it now. And I think we shouldn't:
- current behavior simplifies cache setup
- the cost of this error is low (no data lost or anything like that)

**Comment by Suor** [comment]
Thank for the feedback though and sorry to hear that your first dvc experience was somewhat confusing :)
