### ISSUE TITLE
Allow restriction `dvc pull` to targets

### ISSUE THREAD

**Issue by Titousensei** [iterative/dvc#2706]
We have a big mono repo where all the projects are eventually merged. We plan to put the dvc files related to a model in the same directory, and we will have many such directories. In that case, doing `dvc pull` will start pulling all the files cached in remote storage (potentially terabytes of data), right? If a user does `dvc pull <target>` she will only load the cached file needed by this target, which is what we really want the user to do.

It would be nice to have a way to prevent the `dvc pull` without a target, like a config option `pull.disable_global`.

**Comment by shcheklein** [comment]
Context: https://discordapp.com/channels/485586884165107732/563406153334128681/639582276388388870

**Comment by Suor** [comment]
I think letting user interrupt the process is ok solution unless there is a significant delay before it's obvious that lots of things will be pulled now.

**Comment by dmpetrov** [comment]
It is quite dangerous to change a command behavior (syntax of the command in this case) by a config option. This  should be done only in exceptional cases.

For this particular case, managing multiple DVC projects inside a single mono-repo might be a better solution with additional benefit. See #2349. The implementation is coming soon #3257.

I’m closing the issue in favor of #2349. Please provide more details if I missed something and multiple dvc repro won’t solve the issue.

**Comment by Suor** [comment]
@dmpetrov #2349 looks way more dangerous and way more heavy.

**Comment by dmpetrov** [comment]
@Suor it is more general and it should not be heavy. Otherwise, we will end up with many ways of doing the same thing.
