### ISSUE TITLE
bundler/partitioner middleware

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2708]
See iterative/dvc.org/issues/682 for context.

It seems like large data sets (in the TBs) tend to get bundled and/or partitioned in different ways and formats such as HDFS/HDF5/TFRecord files. This poses a challenge for DVC data versioning which calculates checksums at the file (or directory) level.

What would be the easiest way to extend DVC support for this kind of dataset storing practice? Perhaps a tool separate to DVC itself even, as some sort of middleware that enables transparency between the actual dataset, however it's organized into bundles and partitions, and DVC commands.

**Comment by mroutis** [comment]
@jorgeorpinel , I guess one way would be to support chunking but not sure if HDFS has the API to interact with chunks instead of files

**Comment by jorgeorpinel** [comment]
It seems HDF5 supports chunking and there's a [HDF5 Connector](https://www.hdfgroup.org/solutions/enterprise-support/hadoop-hdfs-hdf5-connector/) for Hadoop "to extract metadata and raw data from HDF5 and netCDF4 files on HDFS".

**Comment by efiop** [comment]
Closing as stale. HDFS supports such files, and provides built-in checksum, so dvc uses it with external outs/deps (though there are some limitations like checksum not being a hash).
