### ISSUE TITLE
Can't brew upgrade new dvc version

### ISSUE THREAD

**Issue by ciberger** [iterative/dvc#2724]
Hi all! 

Thanks for making this great tool! 

I believe I found a minor bug, for example:

> ❯ dvc push
> +-------------------------------------------+
> |                                                                           |
> |     Update available 0.66.3 -> 0.66.4             |
> |           Run brew upgrade dvc                          |
> |                                                                           |
> +-------------------------------------------+

then

> ❯ brew upgrade dvc
> Error: dvc 0.66.3 already installed

Thanks!

**Please provide information about your setup**
DVC version 0.66.3
Homebrew 2.1.15
Mac Mojave 10.14.6

**Comment by efiop** [comment]
Hi @ciberger !

We've been accepted into homebrew-core recently and still getting used to the new release workflow. :slightly_frowning_face: 0.66.4 should become available on homebrew a bit later today. We'll adjust our workflow to enable update notifications only _after_ homebrew is ready.

Sorry for the inconvenience!

**Comment by efiop** [comment]
@ciberger I've rolled back the notifications for now. Dvc updater will be using cached version, so you might want to `rm -f .dvc/updater` to reset it and get rid of notifications for now.

Thank you for the feedback! :slightly_smiling_face:

**Comment by efiop** [comment]
@ciberger 0.66.4 is now available through homebrew :tada: Thank you!
