### ISSUE TITLE
can't create lock files on Azure mounted as a blobfuse

### ISSUE THREAD

**Issue by cokeSchlumpf** [iterative/dvc#2738]
Hi,

We are trying to use DVC together with Azure ML. On the Azure ML compute target AZ Blob Storage is used which doesn't support linking. Sometimes (and I don't actually understand when), DVC tries to create `.dvc/updater.lock` using a symlink which does not work on the file system:

```bash
$ dvc checkout
ERROR: unexpected error - [Errno 38] Function not implemented: /foo/mounts/workspaceblobstore/azureml/bar_1572957435_9410bff6/.dvc/tmp/7a8e5da0afade35b03f7ed01dfdf3ef7.lock' -> '/foo/mounts/workspaceblobstore/azureml/bar_1572957435_9410bff6/.dvc/updater.lock'
```

`cache.type` is configured to use `copy`. I guess this somehow doesn't apply since no data is really cached here.

Is there a proper way to disable the behavior or to disable the updater-check?

**Please provide information about your setup**

```$
dvc --version
0.66.6
```

As described, we are running on Azure ML compute, basically a Docker Image using Ubuntu with storage mounted from Azure Blob Storage.

**Comment by efiop** [comment]
Hi @cokeSchlumpf !

Locking is not affected by `cache.type` as it is a completely separate subsystem. The lock that we are using is an nfs-compatible lock, which uses hardlink to create a lock atomically. I suppose you are mounting your azure storage through blobfuse, which doesn't have `hardlink` implemented:

> Current Limitations
Some file system APIs have not been implemented: readlink, symlink, link, chmod, chown, fsync, lock and extended attribute calls.

Unfortunately, it means that most of the dvc won't work if you place your whole project on blobfuse :slightly_frowning_face: . What you could do instead, is have your dvc project (git repo) somewhere outside of blobfuse and configure an external cache directory pointing to blobfuse mount. With that approach, if you don't have enough storage for your workspace file copies (not the whole cache, just outputs that are currently used in your workspace), you could also consider using `cache.type symlink` along with `cache.protected true`(to add cache corruption protection).

Let me know if that works for you and/or if you have any questions :slightly_smiling_face:

**Comment by efiop** [comment]
@cokeSchlumpf Btw, does git work on blobfuse?

**Comment by cokeSchlumpf** [comment]
@efiop Thank you for the response. I will try to figure out a working way (but anyhow, sometimes it works without the mentioned error message - now I'm wondering why). 

Within the training runtime we don't use any git commands - Azure basically uploads all project files and mounts them into the docker container when executing the training.

I'll spend some time tomorrow investigating. I'll let you know. Than you!

**Comment by shcheklein** [comment]
We probably can support options like lock files location for cases like this.

**Comment by efiop** [comment]
@cokeSchlumpf How is it going? Were you able to find a workaround for your scenario?

**Comment by efiop** [comment]
Closing as inactive.
