### ISSUE TITLE
consider getting rid of packages/binaries built by pyinstaller (windows exe and mac pkg)

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2760]
We've been running into issues with pyinstaller-built binaries for a long time and now I wonder if we should abandon them for good.

Mac: we have brew, pip and conda, doesn't seem like there is any need for our own pkg installer. We can't really make pkg installer install non-binary package for now, as we depend on python and mac has py2, which is soon to be dead. Supporting py2 only for that is not an option as well, since it causes a lot more issues than pyinstaller, so we'll drop py2 a bit before or right at Jan 1 2020. Considering how popular and powerful brew, pip and conda are, feels like we can just drop pkg for good.

Win: we have pip and conda, feels like something like chocolatey package would be a nice addition, that would eliminate the need for our own exe installer, but I haven't researched it enough.  Also can't really make our current exe install non-binary, as there is no default python to rely on :slight_frown: Seems like conda is de-facto the standard for DS on windows, so maybe we could also simply drop the exe.

Linux: we have pip and conda. We also have deb and rpm packages and repos, which are currently packing binaries, but we could totally make it python-dependendent. That would take a bit more work to convert dep python packages, but it seems like a good idea in the long run, if any of the deb/rpm distros ever decide to include dvc into default repos.

From https://discordapp.com/channels/485586884165107732/565699007037571084/642407396790239254

**Comment by efiop** [comment]
If there are any users that need these, please let us know here in the comments. :slightly_smiling_face:

**Comment by efiop** [comment]
Some stats on our pkg and exe downloads: https://www.somsubhra.com/github-release-stats/?username=iterative&repository=dvc Some of those are from our tests. So not many downloads for windows and mac installers. deb/pkg are usually served from our s3 repos, so those don't count.

**Comment by mroutis** [comment]
Python is not that hard to get on Windows: https://blog.adafruit.com/2019/06/04/new-guide-python-is-in-the-latest-build-of-windows-10-adafruitlearningsystem-python-adafruit-win10-windows-adafruit/

You can search it on the store, without going to Python.org :eyes:

https://www.microsoft.com/en-us/p/python-37/9nj46sx7x90p

**Comment by efiop** [comment]
@mroutis Still not as simple as current installer. Maybe there is a better way to package this.

**Comment by efiop** [comment]
Not finding any good alternative :( Looks like the options for distributing python app are the same as they were 2 years ago. Looks like we will simply have to suck it up and improve our testing to catch those issues early. :slightly_frowning_face:

**Comment by efiop** [comment]
Things like awscli are also still using pyinstaller, even though they run into similar issues from time to time. Looks like there is no other way for now. Closing.

**Comment by mroutis** [comment]
@efiop , I think you are overestimating the installation task; right now is as easy as searching python on the store, click download, `pip install dvc` and you are done :)

**Comment by efiop** [comment]
@mroutis That's a good point! Though awscli, mercurial and others do provide windows/mac installers to make it a1 stop shop, instead of making you install python and run pip. To me it seems like our users are advanced enough to do that, but it might not be a valid excuse to raise the bar for the newbies. Need to learn more about why people are even using those.  Will keep this opened for now, maybe someone will share their thoughts (i'll also try to actively ask users about that).

**Comment by mroutis** [comment]
looks like the reason behind `aws-cli` providing Windows installers is the lack of Python providers from the OS: https://github.com/aws/aws-cli/issues/2501#issuecomment-287942662

And from their web page, looks like they are going with `pip` for OSX: https://aws.amazon.com/cli/

![2019-11-08-14:08:55](https://user-images.githubusercontent.com/7363250/68507278-21168b00-0231-11ea-806b-e6efab942fd4.png)

**Comment by efiop** [comment]
@mroutis Yeah, but default python on mac is not very good too :slightly_frowning_face: It is an ancient python 2, which we will drop in 2 months, so can't rely on it :slightly_frowning_face:

**Comment by mroutis** [comment]
@efiop , true that :disappointed: 

I read that they are discouraging users to rely on python 2: https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_release_notes

**Comment by casperdcl** [comment]
Since you asked @mroutis - my opinion on this issue is the same thing I always say: who needs users when you have devs?

![](https://imgs.xkcd.com/comics/linux_user_at_best_buy.png)

On a serious note I also go through similar pain packaging executables bundling a python interpreter for windows. Don't think there's an easy way around it. Recommending anaconda and/or chocolatey and/or docker may work. Speaking of which... New issue time.

**Comment by efiop** [comment]
Reasons why users are using bin packages:

https://github.com/iterative/dvc/issues/2749#issuecomment-552355651

https://github.com/iterative/dvc/issues/2754#issuecomment-552374209

**Comment by nightscape** [comment]
If I may chime in here as a Windows user:
I've installed dvc via [scoop](http://scoop.sh/), which imo is the nicest way to install stuff on Windows.
[Here is the package definition for dvc](https://github.com/ScoopInstaller/Main/blob/master/bucket/dvc.json).
It doesn't require `.exe` files, but usually some kind of archive that can be downloaded and unzipped (e.g. to `~/scoop/apps/dvc/0.66.9`). It then sets paths, creates shims, etc. in order to put things on the path.
Afaik the innosetup part is rather an annoyance in that case, because innosetup packages can't just be unpacked, but have to be installed, with potentially unknown side effects.
So, from scoop perspective having some archive which contains everything needed would be the preferred option.

**Comment by casperdcl** [comment]
Hmm does that scoop repo link get an automated PR every single time one of the supported packages gets an update? Seems like a nightmare to manage.

I'll also post another vaguely related comic with the excuse that I didn't post the first one so can't be accused of starting this...

![](https://imgs.xkcd.com/comics/python_environment.png)

**Comment by nightscape** [comment]
@casperdcl afaik each scoop bucket contains a script that updates all dependencies. That script is run automatically every hour or so and the result automatically committed and pushed to Github.
Imo the approach is really great. I've submitted quite a few package declarations now, it really takes only a few minutes to provide them and in return I get free package updates for live 😄

**Comment by mroutis** [comment]
I'm still in favor of deprecating `pyinstaller`, although, we can wait until we drop support for Python 2)

@nightscape , would requiring a Windows user to install Python (either by a package manager, store, or via the python.org webpage) and then use `pip` to manage (install/upgrade/etc.) DVC would be a significant downgrade on the user experience?

**Comment by nightscape** [comment]
@mroutis I haven't found any scoop packages that install via `pip`  ([nteract installs ipykernel via pip](https://github.com/lukesampson/scoop-extras/blob/master/bucket/nteract.json#L15), but still relies on a `.exe` file to do the main installation), but of course users could just manage dvc outside of scoop.

**Comment by casperdcl** [comment]
On this topic, what *is* the best possible way to install `dvc`? My guess is:

1. preferably use Ubuntu 18.04
1. install conda
1. `conda create -n dvc python=3 dvc`
1. `mkdir -p ~/.local/bin/dvc`
1. possibly make sure the dir above is added to `$PATH` in `~/.profile` or `~/.bashrc`
1. `cat '#!'"$CONDA_PREFIX"/envs/dvc/bin/dvc > ~/.local/bin/dvc`

And to update

`conda update -n dvc --all`

**Comment by efiop** [comment]
For the record: we now have a chocolatey package for windows https://chocolatey.org/packages/dvc . Waiting for moderators and some final testing.

**Comment by casperdcl** [comment]
We also have a snap package (https://snapcraft.io/dvc, not fully working due to restricted privileges/permissions) and pending request for permissions & inclusion in the store (https://forum.snapcraft.io/t/classic-confinement-request-for-dvc/14124)

**Comment by mroutis** [comment]
By the way, `heroku-cli` is using snap for Linux-based distros: https://devcenter.heroku.com/articles/heroku-cli#download-and-install

**Comment by shcheklein** [comment]
and aws-cli is snap distributed as well:

that's what ubuntu recommends if command is not found.

sudo snap install aws-cli  # version 1.16.266, or

**Comment by efiop** [comment]
We are now signing our binaries and they are still useful. Pyinstaller is causing some problems from time to time (usually just because of a missing hook), but the benefits are still worth keeping it around. Closing.
