### ISSUE TITLE
progress when collecting directories with giant number of files

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2770]
Was adding one particularly large dataset of a few hundred G with lots of files and saw dvc appear to be frozen when it was collecting all the files to start adding them around https://github.com/iterative/dvc/blob/0.67.0/dvc/remote/base.py#L196 . Would be nice to either speed it up so it is not noticable(which I really doubt is possible with that amount of files to walk through) or at least provide a progress bar to keep the user updated.

**Comment by shcheklein** [comment]
@efiop I think it's part of the #2546 ? see, the `large dirs progress bar hanging` checkbox and the relevant comment there.

**Comment by efiop** [comment]
@shcheklein Not seeing that checkbox there. Could you clarify?

**Comment by efiop** [comment]
@shcheklein You meant https://github.com/iterative/dvc/issues/2699 . Got it.
