### ISSUE TITLE
get/import: don't require default remote for get/import in certain cases

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2780]
As pointed in discussion under #2711
DVC, upon `get` and `import` operations requires that default remote is defined in target repo. 
We should remove this requirement. 

**UPDATE:**

check this comment that generalizes it to non-cached files when cache is present already.

https://github.com/iterative/dvc/issues/2780#issuecomment-572205877

**Comment by efiop** [comment]
Will need to be solved as a part of https://github.com/iterative/dvc/issues/2515

**Comment by shcheklein** [comment]
I think this requirement can be removed even for `cached` files if they exist in cache already? The case can be a shared cache (all repos use the same cache effectively and sometimes don't even use remote at all).

Double check the behavior with directories (when they only partially cached).

**Comment by sharidas** [comment]
I am looking into this issue.

**Comment by sharidas** [comment]
Below are the steps I tried:
- Created a local folder `mylocalchange` and `example-get-started`.
- Inside `mylocalchange`:
  - execute `git init; dvc init`
  - added folder `data2` ( didn't executed `dvc add dataset1` ) so its not in the cache.
- Now from the `example-get-started` folder where (`git init; dvc init` executed )
   - execute `dvc import ../mylocalchange dataset1`
   - error logged in the console:
```
failed to import 'data2' from '../mylocalchange'. - The path 'data2' does not exist in the target repository '../mylocalchange' neighther as an output nor a git-handled file.
```

- Say if I created the folder `dataset1` in `mylocalchange` and then executed `dvc add dataset1`. This way the cache is generated in the source.
- Inside folder `example-get-started` execute:
   - `dvc import ../mylocalchange dataset1` , the data gets imported without errors.

Anything that I am missing here to reproduce the issue?

**Comment by shcheklein** [comment]
@sharidas could you try when the external repo is cloned from the remote URL, not a local one?

**Comment by efiop** [comment]
@sharidas Here is a script that illustrates the issue:
```
#!/bin/bash

set -e
set -x

rm -rf mytest
mkdir mytest
cd mytest

git init
dvc init

# iterative/dvc has dvc.ico too, so we can get it to pre-fill our cache
mkdir tmp
dvc get https://github.com/iterative/dvc scripts/innosetup/dvc.ico -o tmp
dvc add tmp/dvc.ico
rm -rf tmp
tree .dvc/cache

# getting git files works fine
dvc get https://github.com/efiop/dvc --rev no_remote setup.py

# importing git files works fine
dvc import https://github.com/efiop/dvc --rev no_remote setup.py

# but this fails because of a missing remote. This should be fixed.
dvc import https://github.com/efiop/dvc --rev no_remote scripts/innosetup/dvc.ico -v

# getting cached files fails and it should stay that way, as there is
# nowhere we can get the cache from, as `get` should work in or outside of repo,
# so it when you are in repo it is not using its facilities. Could discuss 
# whether or not `get` should detect that it is running in the repo and try to
# use its cache, but that is a separate issue that is out of focus for now.
dvc get https://github.com/efiop/dvc --rev no_remote scripts/innosetup/dvc.ico -v
```

Note that I'm using my git repo instead of a temporary local one. The reason for that is that we have an optimization in our code, that sets .dvc/cache of a repository we are getting/importing from if that repository is a local one: https://github.com/iterative/dvc/blob/0.80.0/dvc/external_repo.py#L71 . So we need to either disable that optimization for the test or use a non-local url. Let us know if you'll have any questions 🙂
