### ISSUE TITLE
restyled runs yapf, which we don't want

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2783]
For some reason https://github.com/iterative/dvc/pull/2776 runs yapf, which we don't even use and it is not enabled in the config. Investigating.

**Comment by efiop** [comment]
https://github.com/iterative/dvc/pull/2551#issuecomment-553103983

**Comment by casperdcl** [comment]
Love that this was labelled `p0`

Critical for devs but no end user would care :D

**Comment by efiop** [comment]
@casperdcl Well, you can say that the team members are "internal users" :) Luckily this one was very simple to resolve, I was afraid of something more serious.
