### ISSUE TITLE
colorama: standardize and apply output message colors

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2784]
I just recently discovered we're using `colorama` when reviewing https://github.com/iterative/dvc/pull/2765/files but haven't really noticed it much in most DVC output.

[Current use](https://github.com/iterative/dvc/search?utf8=%E2%9C%93&q=colorama&type=) I can see now:

- `colorama.Fore.BLUE` is used for some URLs. I like this, should check it's ALL URLs.
- `RED` and `GREEN` are used in the updater. This seems OK.
- `BLUE`, `RED`, and `YELLOW` [in the logger]().
- `CYAN` (called `blue`) is used for the man.dvc.org URLs [here](https://github.com/iterative/dvc/blob/ee70822bd434adb36c41e20c63939af69bf0bc64/dvc/command/base.py#L30-L34) and [here](https://github.com/iterative/dvc/blob/ee70822bd434adb36c41e20c63939af69bf0bc64/dvc/command/base.py#L30-L35). Not sure we need this per the first bullet (`BLUE`).
- `MAGENTA` for 2 "HINT" messages [here](https://github.com/iterative/dvc/blob/ee70822bd434adb36c41e20c63939af69bf0bc64/dvc/repo/add.py#L36-L43) and [here](https://github.com/iterative/dvc/blob/ee70822bd434adb36c41e20c63939af69bf0bc64/tests/func/test_add.py#L99-L106). Should check it's used in all such hints, and that other "SOMETHING:" messages always have heir own colors.
- There's this `colorize` function in dvc/dvc/utils/__init__.py:
  https://github.com/iterative/dvc/blob/cfc442e932701af5ef94b94d8b70b8bd117fc6f8/dvc/utils/__init__.py#L349-L359
  ~~but [doesn't seem](https://github.com/iterative/dvc/search?q=colorize&unscoped_q=colorize) to be in use. Use it or lose it.~~ only used [in boxify](https://github.com/iterative/dvc/blob/master/dvc/utils/__init__.py#L389). Use it more (or remove it).
- Finally, PR #2765 may introduce `BLUE` for sample commands in the output (those surrounded with back ticks ` for example. Should we apply this everywhere? (Also "dynamic" commands, printed inside single quotes `'`.)

**Comment by efiop** [comment]
Good catch @jorgeorpinel ! 

> There's this colorize function in dvc/dvc/utils/init.py

It is used in `boxify` https://github.com/iterative/dvc/blob/master/dvc/utils/__init__.py#L389 .

**Comment by jorgeorpinel** [comment]
Thanks. Should probably use it more or remove it?

**Comment by efiop** [comment]
@jorgeorpinel Hm, why remove it? But yeah, could definitely use it more :)

**Comment by jorgeorpinel** [comment]
Idk. It only knows 4 colors and the ending syntax is not that easy to read, at least in boxify:

```python
        "{border}{space}{border}\n".format(
            border=colorize(chars["vertical"], color=border_color),
            space=chars["empty"] * box_size_horizontal,
```

vs. something like `"{blue}{space}{nc}\n".format(blue=colorama.Fore.BLUE...`

**Comment by skshetry** [comment]
Closing as stale.
