### ISSUE TITLE
Remove back ticks (and quotes) from command output? How to highlight?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2793]
In #2644 @efiop and I decided it would be good to standardize the use of back ticks ` and single quotes in command outputs. We decided the former would be used for file names, commands, arguments, etc. and the latter for dynamic output (stuff that varies in the message). Let's review this convention per 
 https://github.com/iterative/dvc/pull/2765#pullrequestreview-316671192. @shcheklein's comments:

> is it a regular practice to use backticks in command line? It seems to me that we should not use markup if the client (command line) does not know how to render it. CLI UI should use plain english with common regular rules. For example it should not include jso or XML or html or Markdown... Probably it's a good idea to highlight path somehow. I would take look at how other popular command line tools do this.

**Comment by jorgeorpinel** [comment]
> highlight path somehow ... how other popular command line tools do this.

I think mostly with terminal text coloring e.g. using `colorama` in Python (related: #2784)

So yeah, firstly, separating between back ticks and single quotes was probably not that useful since to the user, which part of the text is dynamic is probably completely irrelevant. So the convention I would recommend is to either only use `'` which I doubt can cause any trouble in terminal output (we need to check) or to not use either type of quote, but rather a special color that's not used for anything else (again, see #2784). What do you think?

**Comment by efiop** [comment]
backtics are not only markup, they are also an old-ish way of "evaluate" for your commands. E.g. in sh you can use backtics or $() to wrap your command.

**Comment by efiop** [comment]
You can look through things like cpython, backtics are quite widely used in command output.

**Comment by jorgeorpinel** [comment]
@shcheklein what do you think?

@efiop OK good points.  But so you don't think colors are better than back ticks?
And what do you think about stopping using single quotes per:

> probably not that useful since, to the user, which part of the output string is dynamic is probably completely irrelevant...

?

**Comment by shcheklein** [comment]
@jorgeorpinel I would say it's a bit unusual for me, but I don't have a strong opinion - so I'm fine with either for now. We can get back to it later when we start doing UI/UX more systematically.

**Comment by efiop** [comment]
@jorgeorpinel Colors are good too, but they won't show up in the logs when you redirect them to the file. Marking things with quotes and ticks is not only for the user, but also for the developer, so I can visually inspect the log and understand what is a dynamic part and what is not on first sight, instead of having to look into code right away.

**Comment by jorgeorpinel** [comment]
Hm. OK, I'm restoring the last bullet in #2784 to separate this discussion from the matter of coloring.

> Marking things with quotes and ticks is not only for the user, but also for the developer, so I can visually inspect the log and understand what is a dynamic part and what is not on first sight

I would personally recommend to standardize only to back ticks, so the output for the user is consistent. I can't imagine it's that much more difficult to figure out which parts are dynamic when inspecting logs. But then again I may be completely wrong. Another option would be to only use quotes for dynamic stuff when `-v` is used.

But please close this issue if you think we should keep things as they are now. 🙂

**Comment by efiop** [comment]
@jorgeorpinel But the use case for back tics is different from the one for single quotes, as we've discussed previously. Having backtics around dynamic parts would look odd. Let's stick to the current one, as we at least have it figured out already, no need to spend more time on developing a new stadard when we have one ready. 🙂 CLosing.
