### ISSUE TITLE
DVC is busy and locked

### ISSUE THREAD

**Issue by MathieuMarauri** [iterative/dvc#2797]
Hello,

I am trying DVC and it looks really promising so far, thanks for the good work. 

I am having an issue I can't seem to be able to fix, whatever the dvc command I run I am having the following error:

`ERROR: failed to obtain data status - cannot perform the cmd since DVC is busy and locked. Please retry the cmd later.`

What can I do? I even tried completely restarting my computer. 

Cheers, 
Mathieu

**Comment by shcheklein** [comment]
Closing as duplicate to https://github.com/iterative/dvc/issues/2520

**Comment by MathieuMarauri** [comment]
Hello, 

Thank you for your help. I was trying to run a `dvc run` command but as things were too slow (from the train code I was using) I exited the command and closed my computer. When I worked again on this project, I got stuck with the error. 

Cheers, 
Mathieu

**Comment by pared** [comment]
@efiop Do you think we should implement some general logic to remove the lock on `KeyboardInterrupt`? On the other side, without knowing what process created it, we risk removing the lock that was not created by the interrupted command.

**Comment by efiop** [comment]
@pared Hm, does it not remove itself in KeyboardInterrupt? 🤔

**Comment by pared** [comment]
@efiop sorry, you are right, seems like `lock.__del__`` is taking care of lock file deletion.

**Comment by juliensiebert** [comment]
> 
> 
> Hello,
> 
> Thank you for your help. I was trying to run a `dvc run` command but as things were too slow (from the train code I was using) I exited the command and closed my computer. When I worked again on this project, I got stuck with the error.
> 
> Cheers,
> Mathieu

Hi, I actually had the same problem.
I deleted the tmp/rwlock as well, and it solved the problem.

Cheers
