### ISSUE TITLE
pipeline show: use pager instead of rendering ourselves

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2807]
After many discussions https://github.com/iterative/dvc/issues/2420 https://github.com/iterative/dvc/issues/2768 about why our --ascii rendering is bad, I've finally remembered 🤦‍♂  that I should probably check how git does it and, lo and behold, git does use `less` https://github.com/git/git/blob/v2.24.0/pager.c#L8 or whatever is configured to show you things like `git log` instead of rendering it by itself using ncurses. We should do the same.

**Comment by xliiv** [comment]
I'll take it.  @efiop If you have any hints to make work more efficient, I'll grateful :)
