### ISSUE TITLE
Busy and locked DVC after command abortion

### ISSUE THREAD

**Issue by Jenny12344** [iterative/dvc#2811]
Hey everyone,
I just started using DVC on my machine:
DVC version: 0.68.1
Python version: 3.5.6
Platform: Linux-5.0.0-36-generic-x86_64-with-debian-buster-sid
Binary: False
Package: pip
Cache: hardlink - True, symlink - True, reflink - False
Ubuntu 18.04

I started a dvc run command and aborted it afterwards, because I forgot to change something  in my code. Now, when I try to run the command again or when I try to run dvc metrics or others, I get the message:

ERROR: failed to run command - cannot perform the cmd since DVC is busy and locked. Please retry the cmd later.

How can I unlock my DVC again?

Best,
Jenny

**Comment by efiop** [comment]
Hi @Jenny12344 !

I guess it was your email on support@dvc.org mailing list, right? 🙂 But just in case I'll copy my response here too:

> If you are sure that there is no other dvc instance running in that repo (e.g. you could check by running `ps xaf | grep dvc` on linux), you could safely delete `.dvc/lock` file and the issue should disappear. This is a known issue and we've merged a patch with a better instructions in https://github.com/iterative/dvc/pull/2765 , which will be released in 0.68.2 very soon. Please be sure to let us know if that fixes the issue for you :)

**Comment by Jenny12344** [comment]
Yeah, that was also me :) Thanks for your fast answer and for your help, it's working again! -- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 18.11.19, 10:59 schrieb Ruslan Kuprieiev <notifications@github.com>:
Hi @Jenny12344 !

I guess it was your email on support@dvc.org mailing list, right? 🙂 But just in case I'll copy my response here too:



If you are sure that there is no other dvc instance running in that repo (e.g. you could check by running ps xaf | grep dvc on linux), you could safely delete .dvc/lock file and the issue should disappear. This is a known issue and we've merged a patch with a better instructions in #2765 , which will be released in 0.68.2 very soon. Please be sure to let us know if that fixes the issue for you :)





—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/iterative/dvc/issues/2811?email_source=notifications\u0026email_token=ANZWIV62IPDORATIWGRAP2DQUJROFA5CNFSM4JOQJRQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEJ4BKA#issuecomment-554942632",

"url": "https://github.com/iterative/dvc/issues/2811?email_source=notifications\u0026email_token=ANZWIV62IPDORATIWGRAP2DQUJROFA5CNFSM4JOQJRQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEJ4BKA#issuecomment-554942632",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
