### ISSUE TITLE
remote default with no argument removes default

### ISSUE THREAD

**Issue by kaiogu** [iterative/dvc#2813]
Running `dvc remote default` with no argument sets default remote to `None`.
According to [documentation](https://dvc.org/doc/command-reference/remote/default) this should show the default remote though.

Setting default remote:
```
>>dvc remote default my_remote
>>git diff
... 
+[core]
+remote = my_remote
...
```

This should query the default, but sets default to `None`:
```
>>dvc remote default
>>git diff
...
+[core]
+remote = None
```
DVC version: 0.66.11
OS: Ubuntu 18.04.2 LTS
Method: From repository

**Comment by efiop** [comment]
Hi @kaiogu !

This is definitely a bug on our side. Need to modify https://github.com/iterative/dvc/blob/0.69.0/dvc/command/remote.py#L51 to just `logger.info()` the existing value.

Thanks for the feedback!

**Comment by kaiogu** [comment]
Hi @efiop, thanks for developing DVC!

I could give it a try if you haven't already!

**Comment by efiop** [comment]
@kaiogu Sure, please go ahead! Let us know if you have any questions, we will be happy to help with it!
