### ISSUE TITLE
Use path_isin instead of startswith to compare filepaths

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#2823]
The PR #2798 introduced `dvc.utils.fs.path_isin` that can be used to compare child paths and parent paths and therefore, *raw*  string compare with `startswith` can be replaced with this new function.

Refactor usage of `startswith` for paths with `path_isin`.

**Comment by skshetry** [comment]
@efiop, can I take this? If yes, please assign me. :)

**Comment by efiop** [comment]
@skshetry Sure, go ahead 🙂

**Comment by skshetry** [comment]
Looked through the codebase. The difference between `path_isin` and `startswith` is that, the former will be false if they are same path. The latter is being used here in the cases of where the path are same as well. Found 5/6 uses of `startswith` only.
