### ISSUE TITLE
[FR] Initialize dvc in sub-directory of a git repo

### ISSUE THREAD

**Issue by Tradunsky** [iterative/dvc#2828]
For the case of using monorepo it can be useful to have dvc initialized per model dir, but if you try to init it under a sub-dir it says:

> ERROR: failed to initiate dvc - monorepo-models/an-ordinary-model is not tracked by any supported scm tool (e.g. git). Use `--no-scm` if you don't want to use any scm.

**Comment by Tradunsky** [comment]
An option is to init dvc without scm, but Ivan says that there is an implication that you won't be able to use features that expect branches, tags, or commits exist - e.g. show metrics - it needs Git to analyze different versions.

**Comment by efiop** [comment]
@Tradunsky Looks like a duplicate of https://github.com/iterative/dvc/issues/2349 . If you agree, let's close this one and move the discussion there.
