### ISSUE TITLE
--no-scm option seems not working

### ISSUE THREAD

**Issue by andrewBatutin** [iterative/dvc#2859]
dvc version - 0.71.0

pkg Mac install

can't get dvc stop ignoring data files 

i init repo with 

dvc init --no-scm

then

dvc add data

creates .gitignore with /data folder in it

is there something wrong i'm doing ?

**Comment by efiop** [comment]
Hi @andrewBatutin ! `--no-scm` only affects `dvc init`. After that `dvc` dynamically determines if you are using git or not and if you do - it also starts using it. Could you describe your scenario, please? 🙂

**Comment by andrewBatutin** [comment]
What i want to achieve is to get .dvc file for my data folder and keep data folder in project, so it doesn't fall under gitignore settings 

And i thought --no-scm option during init won't ignore files and folders i add to dvc

**Comment by efiop** [comment]
@andrewBatutin Not sure I follow. What do you mean "keep data folder in project"? You mean `dvc add` it, while having some git-tracked files inside?

**Comment by andrewBatutin** [comment]
yes this case

i want to `dvc add data` and keep files inside `data` under git tracking

**Comment by efiop** [comment]
@andrewBatutin It is not possible, as dvc treats `data` as a whole directory. Maybe you could elaborate on your scenario, so we could better understand your use case and maybe suggest a better approach? 🙂

**Comment by andrewBatutin** [comment]
Actually i think i can use just git for my scenario)

I want to easily track changes at precomputed word embedding files

Save to file there SHA checksum every time they changed to keep track of
them

I think i can just use git + hooks to do that

Thnx)

**Comment by efiop** [comment]
I still don't quite understand your scenario 🙁 But happy that you could find a workaround. Please ping us if you will have any questions 🙂

**Comment by shcheklein** [comment]
@andrewBatutin I think what you need is to use non-cached data artifacts with DVC. It calculates checksums but does not put file into .gitignore. The command you would need is `dvc run` in this case:

`dvc run -O data -f data.dvc`

or you can use full power of it create DAG from multiple stages (all w/o caching or gitignoring files).

In this case you have git to version your actual files but also you have DVC to create .dvc files to capture checksums, etc. I see that it can be helpful if you want to use only pipelines for examples, w/o storing data with DVC>

**Comment by andrewBatutin** [comment]
Greate

It seems what i want )

Спасибо)
