### ISSUE TITLE
flufl.lock sleeps random amount of time

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2860]
https://gitlab.com/warsaw/flufl.lock/blob/master/flufl/lock/_lockfile.py#L274 Happens whenever lock is taken. So this results in dvc freezeing at the begging of any operation, when it checks the updater lock. Related to https://github.com/iterative/dvc/issues/2831 . Need to consider bringing back zc.lockfile as described there and only falling back to flufl when flock() is not working.

**Comment by efiop** [comment]
@Suor noted that sleep is under the `while` there, so it shouldn't be ran each time.

**Comment by Suor** [comment]
Is this still important or actually an issue?

**Comment by efiop** [comment]
@Suor Good point. It is an issue to investigate, but no longer p1, since we are not using flufl by default anymore.

**Comment by efiop** [comment]
Closing for now, since this is no longer relevant.
