### ISSUE TITLE
checkout: confusing "Nothing to do" message

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2869]
When checking out an empty directory, it shows "Nothing to do" because `get_all_files_numbers(stages)` throws 0 -- `dvc/repo/checkout.py`.

The checkout works but it shows the message.

```bash
mkdir empty
dvc add empty
rmdir empty
dvc checkout empty.dvc
```

**Comment by skshetry** [comment]
No longer an issue. `checkout` does not print anything if there are no changes, otherwise it prints the list of file changes with their statuses.
