### ISSUE TITLE
travis: use preinstalled docker to run azurite

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2872]
We use it on linux only anyway and ubuntu xenial on travis has [docker preinstalled](https://docs.travis-ci.com/user/reference/xenial/#docker). That one could be [activated with](https://docs.travis-ci.com/user/docker/):
```yaml
services:
  - docker
```
We will save on `apt-get update; apt-get install ...` time.

**Comment by efiop** [comment]
Great catch @Suor !

**Comment by efiop** [comment]
Fixed with the new docker fixtures.
