### ISSUE TITLE
Refactor test/remotes.py by merging inside remote classes

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#2878]
#2853 was just merged, which refactored different helper functions into `test/remotes.py`. There are different remote classes (such as S3, Azure, etc) and functions such as `get_aws_url()`/`get_gcp_url`. 

It'd be good to merge them inside their respective remote classes. :)

**Comment by skshetry** [comment]
I have started working on it. :)

**Comment by skshetry** [comment]
I haven't been able to continue working on this. I'll continue working on this after Christmas. Sorry for not being quick on this. :slightly_smiling_face:

**Comment by efiop** [comment]
@skshetry No worries 🙂 Thanks for the heads up!
