### ISSUE TITLE
Support Oracle Cloud Infra

### ISSUE THREAD

**Issue by ianycxu** [iterative/dvc#2890]
Hi DVC Team,

Thanks for this great work. Are you planning to support Oracle Cloud Infra (OCI) as well?

**Comment by shcheklein** [comment]
@ianycxu it looks like it has S3 compatible API, so this:

https://dvc.org/doc/command-reference/remote/add#supported-storage-types

`Click for S3 API compatible storage`

should work, right?

Please, give it a try and close this or let us know if we need to add some specific features or improve docs (?).
