### ISSUE TITLE
test: convert pytest-style tests to dir_helpers fixtures

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2896]
This is a continuation of https://github.com/iterative/dvc/pull/2837.

This might be done on a per module basis to get a taste of it, leave a comment here if you are migrating particular test module to prevent double effort. I will convert whatever is not done by the end of the sprint. 

So @mroutis, @pared, @efiop, this goes after loose ends are closed as we agreed on planning. Ping me here if you have issues with any new fixtures.

When this is done, someone should kill chimera pytest fixtures in `conftest.py`: `repo_dir`, `git`, `dvc_repo`, `erepo`, `git_erepo`. `temporary_windows_drive` should be inlined or moved closer to its usage.

- [x] migrate old pytest-style tests
- [ ] kill chimera fixtures
- [ ] inline or move `temporary_windows_drive`, stop using `repo_dir` there

**Comment by pared** [comment]
migrating `test_add`

**Comment by mroutis** [comment]
migrating `test_analytics`

**Comment by mroutis** [comment]
Advice extracted from https://github.com/iterative/dvc/pull/2898/files#r354523910

> The order doesn't matter to python, but it matters to reader. Let's list fixtures in the same order everywhere: `tmp_dir`, `scm` (if used), `dvc`. This is chronological: temp dir is created, then git init, then dvc init.

**Comment by Suor** [comment]
Migrating `test_ignore`.

**Comment by pared** [comment]
Migrating `test_move`

**Comment by pared** [comment]
Migrating `test_commit`

**Comment by Suor** [comment]
A note to everyone, including myself:

> The plan was to migrate only old pytest style test in the first phase, let's limit ourselves to that for now [this sprint]. Converting all unit tests might divert us to much from the sprint.

**Comment by pared** [comment]
Migrating `test_checkout`

**Comment by pared** [comment]
Migrating `test_import`

**Comment by mroutis** [comment]
Migrating `test_update`

**Comment by mroutis** [comment]
Migrating `test_destroy`

**Comment by Suor** [comment]
@mroutis @pared let's finish whatever you started today (on Friday), so that I can finalize and clean up everything on Monday.

**Comment by mroutis** [comment]
Migrating `test_stage`

**Comment by Suor** [comment]
So no new free hunting from this point. Finish whatever you started I will handle the rest.

**Comment by Suor** [comment]
Free hunting for those who finished their PRs :monkey::gun:

**Comment by efiop** [comment]
Migrating tests/func/test_get.py

**Comment by pared** [comment]
Fixing tests/func/test_api.py

**Comment by pared** [comment]
Migrating `tests/func/remote/test_local.py`

**Comment by pared** [comment]
Migrating `tests/unit/test_analytics.py`

**Comment by pared** [comment]
Migrating `tests/func/test_cache.py`

**Comment by pared** [comment]
Migrating `tests/func/test_dependency.py`

**Comment by pared** [comment]
migrating `unit/command/test_imp`, `unit/command/test_imp_url`, `unit/test_http`

**Comment by pared** [comment]
migrating `func/test_import_url`

**Comment by pared** [comment]
migrating `func/test_install`

**Comment by pared** [comment]
migrating `func/test_output.py`

**Comment by pared** [comment]
migrating `func/test_pipeline.py`

**Comment by pared** [comment]
migrating `func/test_remote.py`

**Comment by pared** [comment]
migrating `func/test_repro.py`

**Comment by pared** [comment]
migrating `func/test_run.py`

**Comment by pared** [comment]
migrating `func/test_state.py`

**Comment by pared** [comment]
migrating `func/test_stage.py`

**Comment by pared** [comment]
migrating `func/test_update.py`

**Comment by efiop** [comment]
Migrating tests/func/test_get_url.py

**Comment by efiop** [comment]
Migrating tests/func/test_scm.py

**Comment by efiop** [comment]
migrating tests/func/test_init.py

**Comment by efiop** [comment]
Migrating tests/func/test_external_repo.py

**Comment by efiop** [comment]
Created PRs for the rest of the func tests. I think that is it with func tests. Now need to convert unit tests.

**Comment by pared** [comment]
migrating `unit/test_local.py`

**Comment by pared** [comment]
Closing this one, since #3142 there are not pytest-style tests not conforming with dir_helpers. What's left, are `unittest` style tests.
