### ISSUE TITLE
dvc metrics show -a mixes branches

### ISSUE THREAD

**Issue by drorata** [iterative/dvc#2929]
As mentioned in [this discussion](https://discordapp.com/channels/485586884165107732/485596304961962003/653877964588711936):

In https://dvc.org/doc/tutorials/deep/reproducibility#adding-bigrams, it seems like the changes made on the branch have to be first committed before `dvc metrics show -a` returns the nice output. Is that correct?

Compare:

```
# without first committing
➜ dvc metrics show -a
working tree:
    data/eval.txt: AUC: 0.615290
bigrams, master:
    data/eval.txt: AUC: 0.630725
```

and 

```
# with first committing
➜ dvc metrics show -a
working tree:
    data/eval.txt: AUC: 0.615290
bigrams:
    data/eval.txt: AUC: 0.615290
master:
    data/eval.txt: AUC: 0.630725
```

**Comment by pared** [comment]
reproduction script:
```
#!/bin/bash

rm -rf repo storage
mkdir repo

pushd repo

git init >> /dev/null && dvc init -q

printf "with open('metric', 'w+') as fd:\n    fd.write('master')">>code.py

dvc run -q -d code.py -m metric "python code.py"
git add -A && git commit -am "commit" >> /dev/null

git checkout -b bigrams >> /dev/null
sed -i 's/master/bigrams/g' code.py
dvc repro -q metric.dvc

#comment it
# git add -A && git commit -am "commit_bigrams" >> /dev/null

dvc metrics show -a 
```

**Comment by pared** [comment]
@drorata 
Well, its not a bug, its a feature!
We are seing that `bigrams` have same metric value as `master`, because this branch has been checked-out from the `HEAD` of `master` so, at the point when we are on `bigrams` branch and we did not commit anything, from the `git` point of view, metrics value is the same as it is on `master`.
