### ISSUE TITLE
Extend S3 remote support for custom ACL

### ISSUE THREAD

**Issue by rbvesb** [iterative/dvc#2930]
##### The problem:
When using AWS S3 it is a common practice to have multiple accounts - either for each team or for each environment in example. This leads to a problem called permissions! When we want to share data between accounts - i.e. BA team can share some reports with the ML team to help them understanding a specific problem for the company, we need to grant, the ML team, specific permissions over BA's reports (S3 objects).

##### The details:
AWS S3 objects are with private access by default (only owner has access). So, in our example, to grant custom permissions to the ML team over BA's reports, we need to apply ACL (Access Control List) on the reports' S3 object. This ACL will specify a grantee and its permissions over the the specific S3 object. There is a [good documentation about grantees and permissions](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html) in AWS docs. In short the ML team is the [grantee?](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#specifying-grantee) and [permissions?](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#permissions) it needs over BA's reports are read only.

##### The AIM:
Currently DVC has support for applying ACL but only [canned ACL?](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl). Canned ACL is an alias for predefined permissions to a group of grantees. In our case where we want to grant a specific READ permissions to a specific GRANTEE (the ML team), this Canned ACL is not enough. Thus we need to extend DVC functionality to support the ability to apply more granular ACL.

##### The Change:
To achieve this we need to add a few more dvc remote's options for each [ACL permissions](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#permissions) (Note: WRITE is not applicable for S3 objects). We need an option per permission because those options will later be represented as separate headers in S3 HTTP request for [CreateMultipartUpload#Access-Control-List (ACL)-Specific Request Headers~](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateMultipartUpload.html).

##### The implementation:
We are going to add the following new options in dvc's s3 remote functionality:
- `dvc remote modify REMOTE_NAME grant_read <string>`
- `dvc remote modify REMOTE_NAME grant_read_acp <string>`
- `dvc remote modify REMOTE_NAME grant_write_acp <string>`
- `dvc remote modify REMOTE_NAME grant_full_control <string>`
`<string>` is a string representing the corresponding AWS header's value format for grantee - `type=value` pair.
- `id=aws-account-canonical-user-id, id=aws-account-canonical-user-id-2`
- `emailAddress="xyz@amazon.com", emailAddress="abc@amazon.com"`
- `uri=predefined-group, uri=another-predefined-group`

##### Gotchas and drawbacks:
However, there is one tiny gotcha with those headers - they ARE NOT APPENDING grantees but overwrites them. So you have to explicitly set all the grantees at once.

**Comment by rbvesb** [comment]
Here the PRs about this issue:
- [remote: Extend S3 remote support for custom ACL #2931](https://github.com/iterative/dvc/pull/2931)
- [Docs about extended S3 remote support for custom ACL](https://github.com/iterative/dvc.org/pull/851)

**Comment by Suor** [comment]
@rbvesb noted that you started implementing it.

**Comment by shcheklein** [comment]
@efiop merged? can be closed?

**Comment by efiop** [comment]
@shcheklein Yes, thanks for the heads up. 🙏
