### ISSUE TITLE
Try to repro imported files if cache unavialable

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2933]
[Source](https://discordapp.com/channels/485586884165107732/563406153334128681/653935028941750301)

@verasativa tried pulling project, while `import-url`-ed data was not in the cache. Maybe we should consider doing `dvc repro` if stage stands for imported file and data is not avialable inside cache?

reproduction script:

```
#!/bin/bash

rm -rf repo storage
mkdir repo storage

pushd repo

git init >> /dev/null && dvc init -q
dvc remote add -d rmt ../storage

dvc import-url https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg img.jpg

rm img.jpg
rm -rf .dvc/cache

dvc pull img.jpg.dvc
```

**Comment by mroutis** [comment]
@pared , `git init` also has a `--quiet` option

**Comment by skshetry** [comment]
Closing as fixed, we now pull imports. (unfortunately, I don't have a link to point to).
