### ISSUE TITLE
copy type "linking" from cache is not atomic

### ISSUE THREAD

**Issue by salotz** [iterative/dvc#2942]
Installation: Debian and anaconda
```
--> dvc --version
0.75.0
```

Consider the scenario where I am adding a large file with 'copy' type linking:
```
dvc add large_file.h5
```
And I interrupt this with Ctrl-C or something. Most likely the interrupt will come during the copy back to the work area and leave the file half copied. This should probably be an atomic operation, at least to the users point of view.

**Comment by efiop** [comment]
For the record: to solve it, we need to make https://github.com/iterative/dvc/blob/0.75.1/dvc/remote/local.py#L169 first copy to a temporary path right beside the target and then rename it. That way if we are caught mid-copying we won't create a half-baked link. This is the same how we do `download`s and `upload`s in our remotes.
