### ISSUE TITLE
Reliance on relative path for `.dvc/tmp/gdrive-user-credentials.json`

### ISSUE THREAD

**Issue by e3bo** [iterative/dvc#2947]
DVC versions 75.1 and 77.0, Linux, installed via pip

`dvc status -r gdrive_remote` works when I run it from the top directory of the repository, but it fails when I run it from a subdirectory, with output

     /home/eamon/venv/lib/python3.7/site-packages/oauth2client/_helpers.py:255: UserWarning:    Cannot access .dvc/tmp/gdrive-user-credentials.json: No such file or directory
     warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
    Go to the following link in your browser:

        https://accounts.google.com/o/oauth2/auth?client_id=my_id&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata&access_type=offline&response_type=code&approval_prompt=force

    Enter verification code: 4/uQEMOYFiR17UwfHzYPaaSI7_ujyVYnEkv2W2qb_bVEVywcyetGTQs5Q
Authentication successful.
ERROR: failed to obtain data status - Credentials file cannot be symbolic link

A file containing the output with the verbose option enabled is here:

[output.txt](https://github.com/iterative/dvc/files/3962850/output.txt)

**Comment by efiop** [comment]
@MaxRis Just FYI, dvc can run from any directory in the project, so we shouldn't hardcode paths that are relative to the repo root, and also shouldn't hardcode posixpaths, as we might run on Windows 🙂

**Comment by MaxRis** [comment]
@efiop thank you for fixing that!
Idea was to put `gdrive-user-credentials.json` into already .gitignored directory to avoid accidental sharing of file. Might need to think how to use absolute path with prepended repo's root directory to `.dvc/tmp/gdrive-user-credentials.json`.

**Comment by efiop** [comment]
@MaxRis I didn't fix that, @e3bo did 🙂

> Might need to think how to use absolute path with prepended repo's root directory to .dvc/tmp/gdrive-user-credentials.json.

Not sure I follow, could you elaborate?

**Comment by MaxRis** [comment]
@e3bo, I'm sorry, thought the PR is from @efiop 

> Might need to think how to use absolute path with prepended repo's root directory to .dvc/tmp/gdrive-user-credentials.json.

@efiop please ignore my above comment, changes in PR look great and prepend `self.repo.tmp_dir` already ( the thing I was worried about ).
