### ISSUE TITLE
status: implement support for import-ed files

### ISSUE THREAD

**Issue by Baranowski** [iterative/dvc#2959]
See https://github.com/iterative/dvc/pull/2889#discussion_r357950906 for context

**Comment by efiop** [comment]
Context: we do have status implemented for the DependencyREPO, but it is not tested and also doesn't really run because the stage is locked.

**Comment by plaintextview** [comment]
+1 for me as well; when my Data Scientists clone a project repo which uses a data-registry repo, running `dvc status` on the project repo returns the following:

```
$ dvc status
WARNING: DVC-file 'data.dvc' is locked. Its dependencies are not going to be shown in the status output.
data.dvc:
    changed outs:
        not in cache:    data
```

## Repro
My data-registry repo:
```
.
├── .dvc
│   ├── .gitignore
│   └── config
├── README.md
├── projectA
│   ├── .gitignore
│   └── data.dvc
└── projectB
    ├── .gitignore
    └── data.dvc
```

Update `projectA` to use data managed by `data-registry` repo:
```
$ git clone git@gitlab.com:path/to/projectA.git
$ cd projectA
$ dvc init
$ dvc import git@gitlab.com:<the-data-repo.git> projectA/data
$ git add data.dvc
$ git commit -m "Using DVC!!"
$ git push
```

Another user clones the (updated) `projectA` repo, and checks dvc:
```
$ git clone git@gitlab.com:path/to/projectA.git
$ cd projectA
$ dvc status
WARNING: DVC-file 'data.dvc' is locked. Its dependencies are not going to be shown in the status output.
data.dvc:
    changed outs:
        not in cache:    data
```

It's less than optimal UX, and I know I will get emails over this ; )

**Comment by pared** [comment]
repro script:
```
mkdir remote_repo repo

set -e
set -x

maindir=$(pwd)

pushd remote_repo
git init -q && dvc init -q

echo data >> data
dvc add data

git add -A
git commit -am "add data"

popd

pushd repo
git init -q && dvc init -q
dvc import $maindir/remote_repo data

dvc status
```

**Comment by efiop** [comment]
Need to research how git does it, maybe it has some caching mechanism inside. It would be nice to do a similar thing to make `dvc status` instant even for imported files.

**Comment by dmpetrov** [comment]
@pared thank you for the repro script! It would be even more helpful to add important outputs into it (and probably some comments with problem/expected outputs) :)

**Comment by pared** [comment]
@dmpetrov sorry for that. I provided some context, please check it out. :)

**Comment by fabiosantoscode** [comment]
I'm picking this one up!
