### ISSUE TITLE
dvc command throw "ERROR: unexpected error - __init__() got an unexpected keyword argument 'verify'"

### ISSUE THREAD

**Issue by xwk** [iterative/dvc#2961]
Running dvc commands like 'dvc add', 'dvc status', 'dvc push' will  all result an error message like below being printed , but the expected functionality does not seem to be impacted.

ERROR: unexpected error - __init__() got an unexpected keyword argument 'verify'

OS: Ubuntu 18.04
DVC version: 0.76.0

**Comment by shcheklein** [comment]
@xwk please, try to upgrade DVC. I think, this has been fixed a few days ago with DVC 0.77.0. Please, feel free to reopen if it doesn't work for you.
