### ISSUE TITLE
Add an option in 'dvc status' to show details of the files changed in a directory tracked by DVC

### ISSUE THREAD

**Issue by xwk** [iterative/dvc#2964]
Suppose I have a directory tracked by DVC, and I added some files (or delete/changed some files) later. Currently 'dvc status' will only tell me the directory is modified, but does not show detail of what are changed exactly. The 'dvc diff' does not help  as well, as it only supports diff between two GIT commits, but I've not commited the directory change to DVC and GIT yet.  

I suggest to add an option in 'dvc status' command to show details of the files changed in a directory tracked by DVC.

**Comment by efiop** [comment]
Hi @xwk !

Thanks for this feature request! We have a ticket for it already in https://github.com/iterative/dvc/issues/2180 , so I'll close this one as a duplicate.
