### ISSUE TITLE
Create error handler for remotes

### ISSUE THREAD

**Issue by pared** [iterative/dvc#2965]
As in
https://github.com/iterative/dvc/pull/2866#issuecomment-566014336

@mroutis @Suor @efiop 
I would like to ask your opinions on that, though AFAIK, @efiop agrees.

**Comment by efiop** [comment]
So the change would be that each `_download/_upload` knows which specific errors to catch (e.g. ClientError for s3) and the rest falls through and is either being caught in `RemoteBASE.download/upload` if it is something common but remote-related, or it is caught by main.py (e.g. ulimit issue). Currently we catch _everything_ in `RemoteBASE.download/upload` and treat it as something recoverable, which is not the case.

**Comment by Suor** [comment]
I don't see much value in this refactoring unless we actually do something useful with that specific errors, i.e. retry or dynamic_chunk_size. Otherwise we will just add lots of code, which may make it harder for us to actually do something useful later.

**Comment by mroutis** [comment]
Can't imagine how would it look like, @pared, but I agree that we should treat exceptions better

**Comment by efiop** [comment]
Migrating to fsspec that adapts cloud specific errors to OSError's and even retries stuff if needed. Closing as stale.
