### ISSUE TITLE
update: Handle Git-tracked import-ed files

### ISSUE THREAD

**Issue by Baranowski** [iterative/dvc#2976]
After https://github.com/iterative/dvc/pull/2889, `dvc import` can also import files that are tracked by Git but not DVC. When the user tries to `dvc update` them, the operation fails. See also https://github.com/iterative/dvc/issues/2959

**Comment by pared** [comment]
reproduction script
```
#!/bin/bash

rm -rf repo remote_repo storage
mkdir repo remote_repo storage

set -e
set -x
main_dir=$(pwd)
pushd remote_repo

git init --quiet && dvc init -q
echo content >> git_file
git add git_file
git commit -am "init"

git add git_file

popd
pushd repo

git init --quiet && dvc init -q
dvc import -q $main_dir/remote_repo git_file
dvc update git_file
```

Do I get it right, that we want to extend `update` functionality? So far `target` could be only [`*.dvc` file](https://dvc.org/doc/command-reference/update#update).
If we want to extend the functionality, we probably should add the ability to update output by its name. That should probably be solved in https://github.com/iterative/dvc/issues/2458 but better keep info on that also in this issue.

**Comment by fabiosantoscode** [comment]
@pared I think this issue is about imported files which are tracked in a remote non-DVC git repository.

If you change the last line of your repro script to `dvc update git_file.dvc` you get the right repro:

```
+ dvc update git_file.dvc
ERROR: failed to update 'git_file.dvc'. - config file error: Section 'remote "auto-generated-upstream"' a
ready exists. Use `-f|--force` to overwrite section with new value.
```

**Comment by fabiosantoscode** [comment]
My bad, you also have to not run `dvc init` in remote_repo

**Comment by fabiosantoscode** [comment]
I'm on this one. It's a tiny tiny fix.
