### ISSUE TITLE
import: Handle non-DVC Git repositories 

### ISSUE THREAD

**Issue by Baranowski** [iterative/dvc#2977]
After https://github.com/iterative/dvc/pull/2889, `dvc import` can also import files that are tracked by Git but not DVC. DVC still requires that they come from a DVC repository rather than any Git repository, although there is no longer need for that.

**Comment by pared** [comment]
reproduction script
```
#!/bin/bash

rm -rf repo remote_repo storage
mkdir repo remote_repo storage

set -e
set -x
main_dir=$(pwd)
pushd remote_repo

git init --quiet && dvc init -q
echo content >> git_file
git add git_file
git commit -am "init"

git add git_file

popd
pushd repo

git init --quiet && dvc init -q
dvc import -q $main_dir/remote_repo git_file
dvc update git_file
```

Do I get it right, that we want to extend `update` functionality? So far `target` could be only [`*.dvc` file](https://dvc.org/doc/command-reference/update#update).
If we want to extend the functionality, we probably should add the ability to update output by its name. That should probably be solved in https://github.com/iterative/dvc/issues/2458 but better keep info on that also in this issue.

**Comment by chatcannon** [comment]
Hello all, @shcheklein asked me to work on this as a recruitment test. I have tracked down the reason why this is not yet working: the `import` process tries to create a `Repo` instance from a temporary local clone of the `url` argument (i.e. the source repo from which the file should be imported). Since this directory does not contain a '.dvc' subdirectory, the `Repo.find_root` function fails.

**Comment by chatcannon** [comment]
Here are some ideas for resolving this; I'm not sure which fits better with the overall design:

* Add code to `Repo.find_root` to allow creating a `Repo` instance from a git repo with no '.dvc' directory
* Run the equivalent of `dvc init` in the temporary clone before calling `external_repo`

**Comment by efiop** [comment]
@chatcannon Sorry for the delay! The first two ideas are pretty hacky, the third one would ideally be the way to go. Unless there is a good reason to go with the hacks, of course 🙂

**Comment by Suor** [comment]
@chatcannon I would say we can integrate this into existing code path. Otherwise will need to duplicate lots of things. Just don't create a `Repo` if there is no `.dvc` dir in there.
