### ISSUE TITLE
zenodo

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#2978]
Zenodo (https://zenodo.org/) can archive datasets and software, providing unique DOIs per-version as well as one DOI for all versions (e.g. https://doi.org/10.5281/zenodo.595120). Uploading can be automated (github releases automatically triggers a new DOI). It's a nice first step for people to cite `dvc`.

Things to discuss:

- author list (contributors/company name/etc). If left blank, GitHub contributors are automatically used.
  + `creators`
  + `contributors`

**Comment by efiop** [comment]
@casperdcl It would be great if you could elaborate on what this is about. I don't think many of us are familiar with zenodo 🙂

**Comment by casperdcl** [comment]
Well it's nice to have a DOI for people to cite dvc, and Zenodo can issue DOIs. This I think this is its main relevance for software packages.

e.g. badges: [![](https://img.shields.io/badge/DOI-10.5281/zenodo.012345-blue.svg)](https://doi.org/10.5281/zenodo.012345) or a citation: "[1] iterative.ai, *dvc: Data Version Control - Git for Data & Models* (2019) [DOI:10.5281/zenodo.012345](https://doi.org/10.5281/zenodo.012345)" for people to use in papers & dependencies.

It won't require much set-up from our end.

**Comment by dmpetrov** [comment]
@casperdcl it is a good idea. Several people (3?) have already asked how they can reference DVC in their papers. I was thinking about writing some paper and publish in arxiv.org but zenodo.org can be a temporary workaround.

**Comment by casperdcl** [comment]
@dmpetrov I'd recommend writing a paper *after* zenodo.
