### ISSUE TITLE
checkout:  add `--relink` to tab completion scripts

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2983]
> Per #2492 

~~And are there any other relatively newly added/changed/removed command options we should add to the tab completion files? Or commands, for that matter...~~ Moved to #2985

**Comment by jorgeorpinel** [comment]
> And are there any other relatively newly added/changed/removed command options

e.g. **gc: remove `--all-commits` options from usage output** #2681

**Comment by jorgeorpinel** [comment]
Another e.g.: `dvc run --remove-outs` is now deprecated.

**Comment by shcheklein** [comment]
@Suor could you please take care of the `--relink`, please? It was part of the PR you created, right?

**Comment by jorgeorpinel** [comment]
I'll move everything else to #2985 so this issue is just about `--relink` now.

**Comment by jorgeorpinel** [comment]
Not sure this is closed. Please see https://github.com/iterative/dvc/pull/3026#pullrequestreview-337949246
