### ISSUE TITLE
tab completion scripts need more love

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2985]
Seems to me it's about time we review and update tab completion scripts again (like in #1732)? There are some new and removed commands, options, etc, I think. See also #2983. Some other examples:

- `gc --all-commits` has been hidden from help output (#2681).
- `dvc run --remove-outs` is now deprecated.

And maybe we could add a checkbox to .github/PULL_REQUEST_TEMPLATE.md similar to the one for updating docs but for tab completion scripts?

**Comment by mroutis** [comment]
Indeed, @jorgeorpinel

**Comment by shcheklein** [comment]
+1 on adding a checkbox. Updating these scripts should be responsibility of one who is creating a PR.

It reminds me updating requirements though, and checking licenses, etc. We should consider creating a document for the core team - like extended instruction "before-merge-sequence".

**Comment by efiop** [comment]
@shcheklein Licences and stuff like this is tiresome and will only make the contribution process harder, plus no one really reads that stuff anyway once it is past 2-3 checkboxes. Licences and completion can be automated by proper scripts, so I would rather take a look at that instead.

**Comment by shcheklein** [comment]
@efiop yes, I didn't mean to put them as checkboxes. I suggest we keep them to 3 as we have now. More like an internal pre-merge check-list. If it can be made a part of the automation - that asks you certain questions before you able to merge - that would be really nice.

**Comment by efiop** [comment]
@shcheklein Developers don't read those boxes either 🙂 For Licences and completion it would probably be easier to automate the checks or even generation (for bash and zsh). Need to take a look at some point.

**Comment by shcheklein** [comment]
@efiop it's not for developers either - it's mostly for maintainers. Before you push the merge button make sure to check that list.

**Comment by efiop** [comment]
@shcheklein I meant for core developers/maintainers. No one likes checklists.

**Comment by shcheklein** [comment]
@efiop totally, that's why this "unlove" will be a constant reminder to automate, right? :) the worst scenario here is to have nothing and fix things afterwards. Also that check list is a requirement list for the automation anyway.

**Comment by jorgeorpinel** [comment]
I like checklists. But anyway, since we want to keep this one 3 boxes long, should we at least add a note about trying to keep tab completion up-to-date in the core contrib guide?

**Comment by efiop** [comment]
@shcheklein @jorgeorpinel Sure, let it be at least checkboxes for now.

**Comment by benjaminal** [comment]
Claro como funciona

**Comment by mroutis** [comment]
> Claro como funciona

@benjaminal , I didn't get your comment, was it that _tab completion_ doesn't work for you? :upside_down_face:

**Comment by jorgeorpinel** [comment]
Basically fixed by https://github.com/iterative/dvc/pull/3495#issuecomment-600206961.

**Comment by jorgeorpinel** [comment]
Basically fixed by https://github.com/iterative/dvc/pull/3495#issuecomment-600206961.

**Comment by benjaminal** [comment]
Cloused #2985
