### ISSUE TITLE
perf: `_find_all_targets()` has quadratic complexity because of `Git.is_tracked()`

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#3000]
`Git.is_tracked()` recreates a list of tracked files for each call and is called for each file `walk_files()` will find. Both lists are proportional to repo size, which makes `_find_all_targets() ~ O(repo_size ** 2)`.

**Comment by efiop** [comment]
https://github.com/iterative/dvc/blob/0.77.3/dvc/scm/git/__init__.py#L236

**Comment by Suor** [comment]
There should be a way to access git index by name and thus implement `Git.is_tracked()` in `O(1)`.
