### ISSUE TITLE
perf: unneeded runs on repro

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#3004]
This [NOTE](https://github.com/iterative/dvc/blob/dd68e9a569928e717202d5957fe63fbfaf88e78e/dvc/repo/reproduce.py#L179-L183) looks wrong. Example stage depends on a python script, a user adds a comment to that script that makes `dvc repro` rerun that stage, however, the outs are the same, so the of the pipeline should not be rerun.

**Comment by skshetry** [comment]
Fixed by https://github.com/iterative/dvc/pull/3788.
