### ISSUE TITLE
UI: output glitches

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#3008]
- [x] `dvc version` has an empty line in the end if psutil is not installed (fixed in #3006)
- [ ] `dvc init` doesn't have a message about something is done,
       there is an empty line an then "You can now commit the changes to git"
- [ ] analytics prints errors after dvc exit if there is a network issue 
- [ ] `dvc version` 
    > WARNING: ... but you could create it manually to enable this check 
    
    ... can create ...
- [ ] `dvc add` pbar is named "Add", we do big efforts to show filenames when it's not really needed, like individual pushed files, but don't show filename in `dvc add filename` for single file
    We shouldn't show this pbar at all probably, esp. for small files.
- [ ] `dvc add` pbar doesn't disappear
- [ ] `dvc move 1.csv 2.csv` dup messages:
    > Output '2.csv' didn't change. Skipping saving.                       
    Output '2.csv' didn't change. Skipping saving.
    ...
    
    Also, why do even need to say it's not changed? we are moving things here.
- [ ] `dvc move` on command out suggest moving by hand and editing stage file, should also metion about updating `.gitignore`
- [ ] `dvc repro`s
    > WARNING: Output 'foo' of 'foo.dvc' changed because it is 'modified'     

    Looks idiotic and slightly confusing. "changed" and "modified" are synonyms, and why the ''s? This is "Hello a [stupid] robot is talking to you" approach to messages I'd like to get rid of.
- [ ] `dvc repro` not all changed deps are listed because of short-curcuiting:
    > WARNING: Dependency 'foo' of 'foobar.dvc' changed because it is 'modified'.
    WARNING: Stage 'foobar.dvc' changed.
    Running command:

    Both `foo` and `bar` were changed, but we don't say it. Generally short-curcuiting should not affect UI.

Common source of many of these is printing at low-level where not all the context is available. So I suggest:
- stop printing anything in predicate methods
- print in action methods mostly

**Comment by dmpetrov** [comment]
@Suor thank you! It is a good one.

It might be related to #2565, #2979

**Comment by dberenbaum** [comment]
@skshetry Any sense of how many of these are still applicable?

**Comment by efiop** [comment]
closing as stale
