### ISSUE TITLE
unnecessary recalc of hashes on first checkout of a clone

### ISSUE THREAD

**Issue by vincilab** [iterative/dvc#3009]
If you have a project setup to use symlinks onto a NAS:

```
$ cat .dvc/config
[core]
analytics = false
remote = myremote
['remote "myremote"']
url = /net/dvc_test
[cache]
dir = /net/dvc_cache
type = "hardlink,symlink"
protected = true
```

If you clone that repo and use `dvc checkout`, it will correctly symlink to the files on the NAS, but it will also recalculate md5 hashes for all the dvc-managed files unnecessarily. This can take a really long time if you have a really large dataset, and makes it impractical to use widely on machines that need access to the files quickly, like a build agent (which, for every build, will git clone the repo and should be able to start churning through the dataset without waiting for 2TB of md5 hashes to be computed).

**Comment by efiop** [comment]
Hi @vincilab !

Thanks for the feedback! I'll close this one in favor of https://github.com/iterative/dvc/issues/2676 , which also contains a description of how to implement that.
