### ISSUE TITLE
Submodels and metadata

### ISSUE THREAD

**Issue by kskyten** [iterative/dvc#301]
It would be great to have a convenient way of packaging the different components of a workflow into their own repositories with metadata. This could be combined with a community curated super repository of components and datasets. This would enable things like searching for the highest rated feature extractor for the MNIST dataset, for example. [DataLad](http://www.datalad.org/) implements something like this for datasets.

The components should be self-contained with all the dependencies required to run the code. I recommend [nix-shells](https://nixos.org/nix/manual/#sec-nix-shell) for this purpose, but docker containers could also be used.

**Comment by efiop** [comment]
Discussion moved to https://github.com/iterative/dvc/issues/1472 . Closing this one for now.
