### ISSUE TITLE
Move get_mtime_and_size to tree

### ISSUE THREAD

**Issue by pared** [iterative/dvc#3011]
After fixing #2914, there will be no use case of `get_mtime_and_size` without a `*Tree` object.
Need to move `get_mtime_and_size` method to be tree function. Probably it will need to be `CleanTree`(we need to use `.dvcignore` during metadata gathering) though, there should probably be the mechanism of checking that we are trying to obtain the metadata from WorkingTree because this method does not make sense for `GitTree`

**Comment by pared** [comment]
Some context from #3018:
>test_open_external[Local] fails on is_working_tree assertion inside get_mtime_and_size
This is happening because during the execution of used_cache when pushing for all branches we need to iterate over branches, changing repo.tree to GitTree. The particular file that fails is a cache entry file for directory that we are trying to get checksum for from state. So, in fact, we are trying to get mtime_and_size for file, and not a directory. That is not critical bug as for now, as we are using tree only when calculating dir mtime_and_size. I think we could move is_working_tree assertion after verifying that we want dir mtime_and_size, but I would not leave that as it is. I think we should bump up importance of #3011, move get_mtime_and_size to CleanTree as it will probably enforce us to implement tree.stat methods. We should also reconsider state.get, because, as test_open_external shows, it allows situation when we are trying to get some cache file metadata, using GitTree in repo at the same time, which does not seem logical at all, even if its working now, just because get_mtime_and_size uses os.stat.

**Comment by efiop** [comment]
Closing as stale for now
