### ISSUE TITLE
Deploying on AWS Lambda

### ISSUE THREAD

**Issue by kskyten** [iterative/dvc#302]
It would be amazing to be able to deploy a workflow (#299) to [AWS Lambda](https://aws.amazon.com/lambda/). Rough idea of how this would work:
- each component (#301) knows how to package itself as a zip-file suitable for Lambda
- additional specification in the workflow file or a separate deployment configuration describes the specifics of the deployment

**Comment by efiop** [comment]
Closing as stale. Discussion about similar components is now at https://github.com/iterative/dvc/issues/1472 .
