### ISSUE TITLE
support python 3.8

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#3033]
It is officially released, but we are waiting for [pyarrow](https://pypi.org/project/pyarrow/#files) to release their wheels ([issue](https://issues.apache.org/jira/projects/ARROW/issues/ARROW-6955?filter=allopenissues)).

There's still some other projects that are not supporting Python 3.8 -- https://pyreadiness.org/3.8/

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc/pull/2912
