### ISSUE TITLE
dvc pull pending forever on s3 remote

### ISSUE THREAD

**Issue by mazzma12** [iterative/dvc#3038]
**Please provide information about your setup**
* dvc version: 0.80.0
* installed with pip
* Ubuntu 18.04

I have an already existing repo with a remote config for an s3-like file system that used to work perfectly. However `dvc pull` is pending forever, here is the verbose snippet: 

```
DEBUG: PRAGMA user_version;                                              
DEBUG: fetched: [(3,)]                                                   
DEBUG: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime
 TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT
 NULL)                                                                   
DEBUG: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)             
DEBUG: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inod
e INTEGER NOT NULL, mtime TEXT NOT NULL)                                 
DEBUG: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS
 (SELECT * FROM state_info)                                              
DEBUG: PRAGMA user_version = 3;                                          
```

Do you have is PRAGMA and what could be wrong ? Thank you for your support.

Also here is my `.dvc/config` :
```
['remote "myremote"']               
url = s3://mybucket
endpointurl = https://myendpoint.org
[core]                              
remote = myremote                   
[cache]                             
type = "hardlink,symlink"           
protected = true
```

I have `awscli` installed in my python environment and running `aws s3 ls s3://mybucket` gives the corresponding cache. Note that other teammates manage to pull from the remote...

**Comment by efiop** [comment]
Hi @mazzma12 !

Could you please run `dvc pull -v` again and when it freezes, try CTRL + C and show us full log?

**Comment by efiop** [comment]
Also, could you please show us `dvc version` output?

**Comment by mazzma12** [comment]
Hi @efiop ,

Sorry for this late reply, it somehow get out of my mind. 
The upside of this is that retrying 11 days made it work... that's the beauty. I have no explanation, perhaps I had run a system update and my laptop needed a restart.

Just for the record here is my `dvc version`

```DVC version: 0.80.0
Python version: 3.6.9
Platform: Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid
Binary: False
Package: pip
Cache: reflink - False, hardlink - True, symlink - True
``` 

I close this for now. Thank you !

**Comment by efiop** [comment]
@mazzma12 No worries :) Let us know if the issue will come back.
