### ISSUE TITLE
summon api: caching during interactive sessions

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#3062]
```
$ dvc -V
0.80.0+7f92cc
```

In Python session:
```python
>>> import dvc.api
>>> m = dvc.api.summon('resnext101', 'https://github.com/dmpetrov/dvc-pretrained-resnet', 'test_summon', 'resnext101_32x8d.yml')
...
dvc.api.SummonError: extra keys not allowed @ data['objects'][0]['summon']['file'] at 'resnext101_32x8d.yml' in 'https://github.com/dmpetrov/dvc-pretrained-resnet'
```

I fix the error in the repo without leaving the Python session and summon the object again:

```python
>>> import dvc.api
>>> m = dvc.api.summon('resnext101', 'https://github.com/dmpetrov/dvc-pretrained-resnet', 'test_summon', 'resnext101_32x8d.yml')
...
dvc.api.SummonError: extra keys not allowed @ data['objects'][0]['summon']['file'] at 'resnext101_32x8d.yml' in 'https://github.com/dmpetrov/dvc-pretrained-resnet'
```

The same error while the issue is fixed.

This issue affects one of the summon scenarios - using data objects from interactive IDEs such as Jupyther Notebooks and RStudio.

**Comment by dmpetrov** [comment]
FYI: If you try to reproduce - in `dmpetrov/dvc-pretrained-resnet` repo I merged the `test_summon`  branch to `master`.

**Comment by Suor** [comment]
But you generally want caching during interactive sessions. I.e. you don't want to type in password each time. So we should somehow provide both.
