### ISSUE TITLE
Newline in .gitignore

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#310]

**Comment by efiop** [comment]
Scm driver how has newline detection implemented by @dmpetrov https://github.com/dataversioncontrol/dvc/blob/master/dvc/scm.py#L89 . Closing.

**Comment by nik123** [comment]
Can this issue be reopened? It seems that it's back in the last release (0.41.3)

**Comment by efiop** [comment]
Hi @nik123 !

Could you provide more details?

**Comment by nik123** [comment]
I have dvc 0.41.3 on Ubuntu 16.04 installed as a deb package. 

In my system I can easily reproduce the bug by executing the following commands in bash:
```
$ mkdir tmp
$ cd tmp
$ git init
$ dvc init
$ echo "Hello, world!" > data.txt
$ dvc add data.txt
```

The `.gitignore` file generated by `dvc add data.txt` command doesn't have a newline (i.e. `\n`) character at the end of `/data.txt` line. I can easily detect absence of newline character by executing:

```
$ git add .gitignore
$ git diff --cached .gitignore
```

The commands above give me the following output:

```
diff --git a/.gitignore b/.gitignore
new file mode 100644
index 0000000..604fb1f
--- /dev/null
+++ b/.gitignore
@@ -0,0 +1 @@
+/data.txt
\ No newline at end of file
```

**Comment by efiop** [comment]
@nik123 Thanks! Reopening.
