### ISSUE TITLE
api: use only kwargs

### ISSUE THREAD

**Issue by ghost** [iterative/dvc#3108]
Details from: https://github.com/iterative/dvc/issues/1818#issuecomment-573262055

> The last thing to address is using `kwargs` only on `api.py` module.
> 
> This is how it looks like: 
```python
>>> def hello(*, name='world'): print('hello', name)
>>> hello()
"hello world"
>>> hello("people")
TypeError: hello() takes 0 positional arguments but 1 was given
```

> It makes the interface more explicit.
> To make it work you only need to put an asterisk before the keyword arguments.

**Comment by efiop** [comment]
CC @Suor

**Comment by Suor** [comment]
Will need to update docs examples.
