### ISSUE TITLE
push: improve 'no remote specified hint

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3121]
> More context around https://discordapp.com/channels/485586884165107732/563406153334128681/666010834702696450

```console
$ dvc version
DVC version: 0.80.0
Python version: 3.7.6
Platform: Darwin-19.0.0-x86_64-i386-64bit
Binary: False
Package: brew

$ dvc init --no-scm
...
$ dvc push
ERROR: failed to push data to the cloud - config file error: no remote specified. Setup default remote with
    dvc config core.remote <name>
or use:
    dvc push -r <name>



Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```
- ✅  `config file error: no remote specified`: OK, this is the problem.
- ❌  `Setup default remote with... or use...`: Oops, actually I haven't even setup a remote. Maybe the hint should be different in this case?
- ❓  There 3 new lines between the hint and `Having any troubles? ...`

**Comment by jorgeorpinel** [comment]
May also affect other sync commands (`pull`, `fetch`).

**Comment by fabiosantoscode** [comment]
Picked this up and added a PR!
