### ISSUE TITLE
remote: allow modifying only existing entries

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#3131]
**DVC version**: `0.81.0`

Using `dvc remote modify` on a non-existing entry creates an invalid remote configuration, since it creates a remote without a URL.

```bash
dvc init --no-scm
dvc remote modify missing <option> <value>
```

Ideally, raising an error should prevent the user from introducing an invalid remote entry.

[Discord discussion](https://discordapp.com/channels/485586884165107732/485596304961962003/666411899499315221)

**Comment by shcheklein** [comment]
@mroutis does it come from the Discord discussion? please include a link to it if it's possible.
