### ISSUE TITLE
Document new dir_helpers fixtures

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3144]
We are converting pytest style tests to use `dir_helpers` fixtures (ref: #2896).
It'd be great to document a basic usage of such fixtures, so, that, it'd take less effort for new contributors to start writing tests.

We can document it in `conftest.py` or `dir_helpers.py` itself, and small generic documentation on Contributing guide (that is on, dvc.org?).

**Comment by mroutis** [comment]
@skshetry , isn't the module's docstring enough? I found it pretty useful)

**Comment by efiop** [comment]
Closing as stale
