### ISSUE TITLE
test: GDrive tests are getting skipped.

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3157]
As the title says, tests for GDrive are getting skipped on travis.

**Comment by shcheklein** [comment]
@MaxRis JFYI

**Comment by efiop** [comment]
`should_test` is checking for `GDRIVE_USER_CREDENTIALS_DATA` but I don't see it in .travis.yml nor in travis env vars tab. But I do see OAUTH env vars in travis env tab. CC @MaxRis

**Comment by efiop** [comment]
Looks like need to create setttings.yml for PyDrive https://gsuitedevs.github.io/PyDrive/docs/build/html/oauth.html and use our `dvc-test` project's creds.

**Comment by MaxRis** [comment]
It was supposed to set encrypted `GDRIVE_USER_CREDENTIALS_DATA` in Travis configuration for DVC repo under Iterative's account. I should give update later today on this.
