### ISSUE TITLE
improve message for rwlock error

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#3164]
https://discordapp.com/channels/485586884165107732/563406153334128681/667133061380571146

Current message:
```
ERROR: failed to reproduce 'device_download.dvc': 'data/device_modifier.parquet' is busy, it is being read by:
  (PID 28324): dvc repro device_train.dvc

even though I removed .dvc/lock file
```

**Comment by shcheklein** [comment]
consider adding the second troubleshooting section now that we have a good mechanism for this :)

**Comment by mroutis** [comment]
It is not clear how to improve it :sweat_smile: 
@efiop , any specific suggestions?

**Comment by shcheklein** [comment]
@mroutis I suppose in any way that would prevent us answering the same question on Discord again and again, right? :)

**Comment by efiop** [comment]
@mroutis yep, at least a hint how to delete it. Same as we do with `.dvc/lock`
