### ISSUE TITLE
api/get: local repo with custom rev is not supported

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3179]
```python
import dvc.api

dvc.api.get_url("file", repo=".", rev="HEAD")
```
throws following error:
```
AssertionError: Custom revision is not supported for local repo
```

Similarly, issue exists with `dvc get --show-url` (introduced by #3156):
```
➜ dvc get . foo --rev=HEAD@{5.days.ago} --show-url
ERROR: unexpected error - Custom revision is not supported for local repo
```

**Comment by Suor** [comment]
Title is misleading `dvc get` will work with rev, while `dvc get --show-url` won't because it's completely different command. Call it `dvc get-url` maybe?

**Comment by skshetry** [comment]
We already have a `get-url`: https://dvc.org/doc/command-reference/get-url
And, for now, `--show-url` is a part of `get`. It'd be good to have a better category (but should be covered by description). :slightly_smiling_face:
