### ISSUE TITLE
api: get_url() returns path to `.dir` for directory

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3182]
Currently, `get_url()` returns path to `.dir` files. I'd propose to have some way to parse `get_url()` and return list or dicts (or, iterator) of  files inside the directory (`get_url(recurse=True)`?).

`dvc get . dir/ --show-url` works the same way.

**Comment by Suor** [comment]
I am not a big fan if complicating `.get_url()`, this was always intended for files not dirs. Maybe we should not support `.get_url()` for dirs at all? What's the use case anyway?

**Comment by efiop** [comment]
Note: as we've discussed in #2994 , `get_url` might not even be able to access the cache url that it shows, so we won't always be able to parse `.dir` 🙁

**Comment by jorgeorpinel** [comment]
I'm adding some notes about `.dir` cache files as a preamble to document this in the api docs as well. See [f4900e8..7d1b469](https://github.com/iterative/dvc.org/compare/f4900e8..7d1b469) (part of #931).

**Comment by islamashraf98** [comment]
I think it would be a great option to be added, I have tons of images in a directory, so it would be more practical to get them once using `get_url()`

**Comment by dberenbaum** [comment]
@islamashraf98 You may want to take a look at https://github.com/iterative/dvc/pull/6850.

**Comment by skshetry** [comment]
Closing as stale.
