### ISSUE TITLE
rename or alias `dvc version` to `dvc doctor`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#3185]
Just tired of explaining that `dvc version` is not the same as `dvc --version`. `doctor` seems pretty common and is self-explanatory. What do you guys think?

**Comment by mroutis** [comment]
I prefer `info`: https://docs.docker.com/engine/reference/commandline/info/

I have never ran such thing like `doctor`)

**Comment by shcheklein** [comment]
I also vote for info. I would expect from `doctor` to "heal" something (like corrupted cache for example? ) 

Although we might just make --version an alias for `dvc version`?

**Comment by Suor** [comment]
@shcheklein `dvc --version` should be very simple and fast. This might be used in some install/check/automation scripts.

**Comment by efiop** [comment]
`info` works for me as well.

**Comment by mroutis** [comment]
Remember to change GitHub contribution message and docs

**Comment by shcheklein** [comment]
`info` - can it be confused with something like `dvc info data.dvc`? (similar to git show?). Would it limit us from using it in the future?

**Comment by mroutis** [comment]
@shcheklein, if it is a concern, let's do something more specific: `dvc system-info`

I would prefer not to have such thing as `dvc info file.dvc` 😅, the intention is not clear enough for me

**Comment by efiop** [comment]
Nice thing about `doctor` is that it is specific enough that we sure won't be using it for other functions :) I don't remember specific tools that have `doctor` command, but I surely remember a few in proprietary linux software as well as in some open source (don't remember the names though).

**Comment by mroutis** [comment]
@efiop , looks like `hombrew` uses it: https://docs.brew.sh/Manpage#doctor-options

We don't _check for potential problems_, but we do _use the output to help the maintainers with debugging if you file an issue_.

I'm still rooting for `system-info`. The output is more predictable (definitively something to do with "system-wide information").

In `analytics.py` we already have a `runtime_info` (includes: _dvc version, binary, git repo, user id, and the output of `system_info`_) and `system_info` (includes: _os related information_).

Not related, but we should change in `analytics.py` `system_info` to `os_info` / `platform_info`.
We could even reuse some stuff between `analytics.py` and the current `version.py`.

**Comment by efiop** [comment]
So `info` is too generic after all and `system-info` might be weird becuase it will show dvc version and other stuff which is not really `system` info (sounds like something global like arch, CPU, RAM, etc). I propose `doctor` after all, as it most certainly won't overlap with anything in the future and it is x10 times better than current `dvc version`. Need to remember that this is not a user-centric command, this is something that we need as developers.

**Comment by jorgeorpinel** [comment]
Late to this party but `info` or sys or sysinfo seem better to me. `doctor` sounds like it will find and fix problems in the DVC installation or in the repo or something like that. In case there's still room to reconsider!
