### ISSUE TITLE
get/import: update output (again?)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3196]
I'm not sure what happened because I think we've changed this recently (e.g. #3077), but I'm seeing:

```
$ dvc version
DVC version: 0.80.0
Python version: 3.7.6
Platform: Darwin-19.0.0-x86_64-i386-64bit
Binary: False
Package: brew

$ dvc get -h
usage: dvc get [-h] [-q | -v] [-o [OUT]] [--rev [REV]] url path

Download/copy files or directories from DVC repository...

positional arguments:
  url                   URL of Git repository with DVC project to download
                        from.
  path                  Path to a file or directory within a DVC repository.
...

$ dvc import -h
usage: dvc import [-h] [-q | -v] [-o [OUT]] [--rev [REV]] url path

Download data from DVC repository and take it under DVC control...

positional arguments:
  url                   URL of Git repository with DVC project to download from.
  path                  Path to data within DVC repository.
...
```

The descriptions of the commands as well as of their arguments are outdated. Maybe there was a bad merge somewhere but from what I'm seeing in the docs, they should be something like:

**get**
Download file or directory from any DVC project or Git repository.

**import**
Download file or directory from any DVC project or Git repository into the workspace, and track it.

**positional arguments**
```
  url         Location of DVC project or Git repository to download from
  path        Path to a file or directory within the project or repository
```

which I remember came from PRs to this repo. So anyway, we should update it again, I think. I can do it myself if people agree.

- ~~And make sure docs are in sync with the same text as well.~~ Implicit in #3214

**Comment by pared** [comment]
Checked the `master` and the latest version (`0.82.1`) and it seems to me that help output is proper.
- [get help](https://github.com/iterative/dvc/blob/04161ad6f2d24b02798aa79fe2fcd8fbb76dab15/dvc/command/get.py#L55)
- [import help](https://github.com/iterative/dvc/blob/04161ad6f2d24b02798aa79fe2fcd8fbb76dab15/dvc/command/imp.py#L33)

It seems that `0.80.0` was released at the beginning of January, so it might be that those changes were not incorporated back then.



@jorgeorpinel ?

**Comment by jorgeorpinel** [comment]
Hm yeah this newest version seems closer to correct:
https://github.com/iterative/dvc/blob/04161ad6f2d24b02798aa79fe2fcd8fbb76dab15/dvc/command/get.py#L53-L56
https://github.com/iterative/dvc/blob/04161ad6f2d24b02798aa79fe2fcd8fbb76dab15/dvc/command/get.py#L64-L71
and
https://github.com/iterative/dvc/blob/04161ad6f2d24b02798aa79fe2fcd8fbb76dab15/dvc/command/imp.py#L31-L35
https://github.com/iterative/dvc/blob/04161ad6f2d24b02798aa79fe2fcd8fbb76dab15/dvc/command/imp.py#L44-L51
Let me think...

**Comment by jorgeorpinel** [comment]
EDIT: I've updated the https://github.com/iterative/dvc/issues/3196#issuecomment-577306219 above with notes on what to change, will open a small PR for this.

**Comment by jorgeorpinel** [comment]
> will open a small PR for this.

Done: #3214
