### ISSUE TITLE
Remove spy method

### ISSUE THREAD

**Issue by pared** [iterative/dvc#3198]
In some places, we use `tests/utils/spy` method to mock spied method so that we can observe how particular actions interact with the target method/function. Current implementation:
```
def spy(method_to_decorate):
    mock = MagicMock()

    def wrapper(self, *args, **kwargs):
        mock(*args, **kwargs)
        return method_to_decorate(self, *args, **kwargs)

    wrapper.mock = mock
    return wrapper
```

assumes that we are spying on some class method (by having `self` in wrapper args). This is not always true, and it leads to hiding first argument if we will use it to spy on function (eg `file_md5`) which results in trimmed call args for functions. 

Example:
```
def test_spy(tmp_dir):
    tmp_dir.gen("file", "file content")

    from tests.utils import spy
    import dvc
    checksum_spy = spy(dvc.utils.file_md5)
    checksum_spy("file")
    assert checksum_spy.mock.call_args_list[0].args == ("file",)
```
should pass, while it does not because args tuple is empty.

[EDIT]
As @mroutis  noted, `pytest`'s mocker can `spy`, so it would be good to remove current spy usages and replace them with `mocker.spy`.

**Comment by mroutis** [comment]
@pawel,  there's a `mocker.spy` already: https://pypi.org/project/pytest-mock/

maybe we could move to that one?

**Comment by pared** [comment]
@mroutis Thanks for pointing that out! Renaming the issue.

**Comment by fabiosantoscode** [comment]
Hey there! I'm on this one :)

**Comment by pared** [comment]
@fabiosantoscode 
Sure, I just would like to note that most use cases of our spy are in UnitTest style tests, so removal might go along with refactoring said tests to pytest style tests.

**Comment by fabiosantoscode** [comment]
@pared 

I've gotten around that with this small TestDvc subclass:

```
class TestDvcWithMocker(TestDvc):
    @pytest.fixture(autouse=True)
    def use_mocker(self, mocker):
        self.mocker = mocker     
```  

Then subclassing it and accessing self.mocker. I didn't want to go ahead and convert the tests because it felt out of scope, although I do agree that they should be converted.
