### ISSUE TITLE
WebUI to manage model

### ISSUE THREAD

**Issue by codergh** [iterative/dvc#3203]
I want to build a webui to manage model version , how can I use dvc to build it

**Comment by efiop** [comment]
Hi @codergh !

Please take a look at https://github.com/iterative/dvc/issues/1074 . If you have any questions, could you elaborate on what you have in mind? Your current question is a bit too generic, hard to respond with anything in particular 🙂

**Comment by jorgeorpinel** [comment]
p.s. some of the comments in that other thread are a bit outdated, I would focus on this https://github.com/iterative/dvc/issues/1074#issuecomment-421482906 and below 🙂
