### ISSUE TITLE
Introduce remote fixture

### ISSUE THREAD

**Issue by pared** [iterative/dvc#3210]
In many places in the tests we create local remote using `tmp_path_factory` (can be found by looking for `RemoteConfig` usages). And set it up "by hand". Introducing `remote` fixture should let us get rid of this boilerplate code. Few notes:

- consider how to handle non-local remotes, and if we should create such fixture for each kind of remote
- in erepo, we currently set remote to point to its cache, we should probably reconsider that and prepare separate remote for it when necessary

**Comment by efiop** [comment]
We now have multiple remote fixtures as well as `local_remote` fixture. Closing.
