### ISSUE TITLE
some files are not uploaded to TeamDrive

### ISSUE THREAD

**Issue by antonkulaga** [iterative/dvc#3215]
I have a problem with pushing files to the teamdrive in my https://gitlab.com/sysbio-aging/cross-species-web
[updload.log](https://github.com/iterative/dvc/files/4099657/updload.log)

**Comment by shcheklein** [comment]
Looks like this is the reason: https://stackoverflow.com/questions/59815620/gcloud-upload-httplib2-redirectmissinglocation-redirected-but-the-response-is-m

We probably need to update the packages properly.

**Comment by shcheklein** [comment]
@antonkulaga could you force install the httplib2 0.16 to try to fix this, please?

**Comment by antonkulaga** [comment]
@shcheklein I confirm, after downgrading to httplib2=0.15.0 from 0.16 it works. Please, update dvc conda packages to have old httplib2 as dependency

**Comment by shcheklein** [comment]
@antonkulaga first steps to fix this - https://github.com/iterative/PyDrive2/pull/5/files
