### ISSUE TITLE
remote: handle -d ERROR 

### ISSUE THREAD

**Issue by qwljasmine** [iterative/dvc#3219]
I encountered **ERROR: unexpected error - expected str, bytes or os.PathLike object, not NoneType** 
when I run command **_dvc remote add -d tmpremote [a shared Windows drive]_** at default home directory of my environment.

The issue is gone when I run the same command at my git folder. 

![image](https://user-images.githubusercontent.com/40971461/72943074-ed280d80-3d29-11ea-8e58-1e40d28e5fac.png)

EDIT:

More context:

https://discordapp.com/channels/485586884165107732/485596304961962003/669661824190513162

**Comment by efiop** [comment]
Hi @qwljasmine !

I see that the path you are supplying is `//something/dvc_tmp_repo` wich doesn't look like a valid path for windows. Could you please use a proper windows path instead and see if that helps?

**Comment by qwljasmine** [comment]
> Hi @qwljasmine !
> 
> I see that the path you are supplying is `//something/dvc_tmp_repo` wich doesn't look like a valid path for windows. Could you please use a proper windows path instead and see if that helps?

Hi @efiop  this is the path that my teammate shared to me and as I mentioned I am able to use it when I execute the command at my git directory. So I guess I am not able to try out another kind of path since that is the only path I have. Thanks

**Comment by shcheklein** [comment]
... it also looks like no matter if that path is correct or not we have some strange behavior with that exception.

**Comment by efiop** [comment]
@qwljasmine sorry for the delay. Could you try removing the leading `/` and see if that helps? Though I think it will still fail, because you are using posix path on windows machine. Is your colleague running linux or mac?

**Comment by qwljasmine** [comment]
@efiop removing the leading / can run. My colleague is running windows 10

**Comment by efiop** [comment]
@qwljasmine So `/` helped and now it works as expected? Is the issue resolved?

**Comment by shcheklein** [comment]
@efiop I think the problem is that certain command line options combination leads to this unhandled properly exception "ERROR: unexpected error - expected str, bytes or os.PathLike object, not NoneType".

**Comment by efiop** [comment]
@shcheklein It is a problem (i've mentioned "except that we could indeed present it better"), but not a core problem. Just checking if the core problem is resolved or not.

**Comment by shcheklein** [comment]
@efiop ah, yeah. It looks like it was from the Discord discussion. Not 100% sure though.

**Comment by efiop** [comment]
Closing as stale. The general "unexpected error" is a topic for a separate discussion.
