### ISSUE TITLE
readme: update badges

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#3233]
- travis badge seems to be hardcoded as green/ok (vis https://github.com/iterative/dvc.org/issues/918#issuecomment-577345881)
- add other install methods (vis https://github.com/iterative/dvc.org/issues/904#issue-546378276)
- ensure consistent style (flat, square, round)

**Comment by efiop** [comment]
> travis badge seems to be hardcoded as green/ok (vis iterative/dvc.org#918 (comment))

It is meant that way. To not scare off people by failing build. We have another badge just beside that is dynamic and reflects build status on master.

**Comment by casperdcl** [comment]
I'd argue that makes the badge pointless. Also it shouldn't really ever be the case that a tagged release build fails. On the rare instance that it does, it should be fixed very quickly.

**Comment by efiop** [comment]
@casperdcl AFAIK, travis only allows badges for branches and not for the latest release or tag, hence why we have that dummy badge plus a real one for `master`

**Comment by dmpetrov** [comment]
I guess, the common approach is to have `prod` branch and release only from this branch. So, the badge will be green 99.99%.

But it seems like a bit heavy solution. Are there any other reasons to have a separate branch? 😀

**Comment by casperdcl** [comment]
Hmm I feel like what this needs is a PR on shields.io to automatically pick up the last travis tagged build. Or Travis CI itself could provide that badge. In the meantime I think just a badge for master should ne enough. Normally `master` should never fail to build either since we should test things in dev branches before merging...

**Comment by efiop** [comment]
dev branch complicates the workflow, we've considered this awhile ago. So far there is no real need in it and a badge is hardly a reason. Current dummy badge is hackish, but it serves the purpose. Hence why  I don't think we should bother messing around with it for now.
