### ISSUE TITLE
get/import-url: better handle remote:// notation errors

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3236]
Working inside a fresh clone of https://github.com/iterative/dataset-registry 👍 
```console
$ dvc version
DVC version: 0.82.2
Python version: 3.7.6
Platform: Darwin-19.0.0-x86_64-i386-64bit
Binary: False
Package: brew
Cache: reflink - supported, hardlink - supported, symlink - supported

$ dvc get-url -v remote://storage/get-started/data.xml
ERROR: unexpected error - 'NoneType' object has no attribute 'repo'
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/0.82.2/libexec/lib/python3.7/site-packages/dvc/main.py", line 48, in main
    ret = cmd.run()
  File "/usr/local/Cellar/dvc/0.82.2/libexec/lib/python3.7/site-packages/dvc/command/get_url.py", line 17, in run
    Repo.get_url(self.args.url, out=self.args.out)
  File "/usr/local/Cellar/dvc/0.82.2/libexec/lib/python3.7/site-packages/dvc/repo/get_url.py", line 17, in get_url
    dep, = dependency.loads_from(None, [url])
  File "/usr/local/Cellar/dvc/0.82.2/libexec/lib/python3.7/site-packages/dvc/dependency/__init__.py", line 77, in loads_from
    ret.append(_get(stage, s, info))
  File "/usr/local/Cellar/dvc/0.82.2/libexec/lib/python3.7/site-packages/dvc/dependency/__init__.py", line 52, in _get
    remote = Remote(stage.repo, name=parsed.netloc)
AttributeError: 'NoneType' object has no attribute 'repo'
------------------------------------------------------------
```
> Discord: https://discordapp.com/channels/485586884165107732/563406153334128681/670363031330619392

**Comment by jorgeorpinel** [comment]
p.s. is it expected that get/get-url do NOT support `remote://` URLs? I mean, they could (when inside a DVC repo).

**Comment by efiop** [comment]
@jorgeorpinel Yes, it is, because they work without any notion of the repo they are working on, they are not even parsing global or system configs, where remote definitions might be.

**Comment by jorgeorpinel** [comment]
Sounds like this is a non-issue.

**Comment by jorgeorpinel** [comment]
I think?

**Comment by dberenbaum** [comment]
@jorgeorpinel It seems the behavior is expected. Is there a docs issue?

**Comment by jorgeorpinel** [comment]
Actually there is some error related to this in https://dvc.org/doc/command-reference/get-url, yes. Solving in https://github.com/iterative/dvc.org/pull/2565/commits/153318206fc644d032d73ba5741e4a4a7fe53a28

But I'm not sure what `import-url` does (vs what it should do)... Let me check ⌛

**Comment by jorgeorpinel** [comment]
```console
$ dvc import-url remote://storage/get-started/data.xml
Importing 'remote://storage/get-started/data.xml' -> 'data.xml'
ERROR: failed to import remote://storage/get-started/data.xml. You could also try downloading it manually, 
and adding it with `dvc add`. - dependency 'remote://storage/get-started/data.xml' does not exist
```

re `remote://storage/get-started/data.xml' does not exist` - @efiop should `import-url` be able to resolve this? For now I'm removing `remote://` mentions from https://dvc.org/doc/command-reference/import-url in #2565...

If not please close this 🙂

**Comment by pmrowla** [comment]
> @jorgeorpinel Yes, it is, because they work without any notion of the repo they are working on, they are not even parsing global or system configs, where remote definitions might be.

I think this is a pretty significant limitation, since this means you can't use `get-url` in an authenticated context unless its for a cloud storage backend that can be configured via env vars like w/AWS profiles and s3.

At the very least, when `get-url` is run from in a DVC repo, I think it should respect the remote configs (even if we don't want to get into reading the global/system configs when run outside of a repo)

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/9886
