### ISSUE TITLE
Allow using symlinks as targets

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#324]
I.e. we have foo -> bar. 'dvc repro foo' should be equal to 'dvc repro bar'. This feature will help users use dvc in a more flexible way.

**Comment by efiop** [comment]
Leaving for the next release.

**Comment by mroutis** [comment]
@efiop , do you consider it still useful?

**Comment by efiop** [comment]
@mroutis Yes, I do. Not receiving much support from users though, so let's close it for now.
