### ISSUE TITLE
git hook post-checkout does not work as expected 

### ISSUE THREAD

**Issue by nkhdiscovery** [iterative/dvc#3241]
Hi, 
The best procedure to reproduce the bug is following step 4 of basic scenarios, versioning:
https://katacoda.com/dvc/courses/basics/versioning

It is expected that git checkout automatically triggers dvc checkout so the file.txt is restored to proper version which was committed, but it does not and `cat file.txt` gives `test 3` after every checkout. `dvc install` has successfully installed the hooks, I checked, but I do not know if the tutorial is wrong or the hook is not working properly.

**Comment by shcheklein** [comment]
Yep, was able to reproduce. It can be skipped to the step 4 directly to reproduce this.

**Comment by nkhdiscovery** [comment]
@shcheklein Thanks for approval.

**Comment by efiop** [comment]
For the record, it is caused by my recent change to post-checkout hook, which accounted for branches but didn't account for tags properly :slightly_frowning_face: I will look into it soon. Thanks for the feedback!
