### ISSUE TITLE
Unexpected dvc remove behaviour

### ISSUE THREAD

**Issue by r0f1** [iterative/dvc#3242]
Hi, I just encountered an unexpected `dvc remove` behavior. Is the following behavior intended?

```
> ls
report.html  report.html.dvc 
> dvc remove report.html
ERROR: failed to remove 'report.html' - bad DVC-file name 'report.html'. DVC-files should be named 'Dvcfile' or have a '.dvc' suffix (e.g. 'report.html.dvc').

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
> ls
report.html.dvc
```
So I tried to remove the `.html` got an error that I should remove the `.html.dvc` file instead, but unexpectedly the `.html` was removed! Is this intended?

```
dvc --version
0.82.3
```

**Comment by efiop** [comment]
Hi @r0f1 !

I'm not able to reproduce. Maybe you've ran `dvc remove report.html.dvc` after that? It is removing outputs by default, but leaves the `.dvc` file intact unless `--purge` is specified.

**Comment by r0f1** [comment]
Thanks for the quick response. I tried to reproduce the behaviour today, but I could not. So, I am closing this again. Thanks anyways!
