### ISSUE TITLE
tests: flatten the test structure / merg unit with functional

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#3243]
I see no advantage in distinguishing between unit and functional tests.

Now that migratation to pytest is happening, tests are getting more slim and descriptive (thanks to fixtures and helpers), we could fit all the tests of a module in a single file `test_<module>.py`.

**Comment by efiop** [comment]
@mroutis By definition, func and unit tests serve different purposes and have different requirements. Mixing those together will just result in giant files with mixed test contexts, which is a terrible idea. We will get integration tests at some point too, which will add to the chaos if we don't keep them separate. Migration to pytest has nothing to do here, it is just a test framework.
