### ISSUE TITLE
checksum: new command or api function to generate file hashes?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3249]
Extreacted from https://github.com/iterative/dvc/issues/3102#issuecomment-573228714

> 💡 Maybe a DVC command to generate DVC checksums from arbitrary files could be useful in these or other situations, basically exposing our internal function that does this (which I know is based on MD5 but not always exactly that).

Not sure how useful this would be since `dvc commit` can recalculate checksums when DVC-files are edited manually.

**Comment by efiop** [comment]
@jorgeorpinel Yeah, we've heard such requests previously, but they were all solved by introduction of `dvc commit`. Wouldn't consider implementing this unless there are users with real use cases.

**Comment by jorgeorpinel** [comment]
Makes sense!
