### ISSUE TITLE
CopyFile2 not supported in Windows 7

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#3259]
A user reported on [discord](https://discordapp.com/channels/485586884165107732/485596304961962003/672482282522673162) that `dvc add` was throwing the following error:

```
ERROR: unexpected error - function 'CopyFile2' not found
```

Here's the output of `dvc version`:
```
DVC version: 0.82.6
Python version: 3.6.3
Platform: Windows-7-6.1.7601-SP1
Binary: False
Package: pip
Cache: reflink - not supported, hardlink - supported, symlink - not supported
```

We are using `CopyFile2` on Windows to increase the performance of copy (see [speedcopy](https://github.com/antirotor/speedcopy)), but that [system call was introduced in Windows 8](
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-copyfile2).

The solution was to `pip uninstall speedcopy` and let DVC fallback to Python's `copy` implementation.

**What should we do?**
* Catch `AttributeError: function 'CopyFile2' not found` and output an actionable error message to fix it.
* State in README / docs that we don't support `< Windows 8`?
* Nothing?

**Comment by shcheklein** [comment]
Looks like Windows 7 EOL is already here? Considering that the whole Windows users share for DVC is about 2% or something not sure we should spend too much time on it?

We definitely should introduce some user-friendly message though and change docs is needed.

**Comment by mroutis** [comment]
@shcheklein , totally, looks like it already happened:


[EOL: Windows 7, service pack 1*, (mainstream) January 13, 2015 - (extended) January 14, 2020](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet)
