### ISSUE TITLE
HTTPSConnectionPool(host='analytics.dvc.org', port=443): Read timed out

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc#3262]
For a few minutes analytics.dvc.org was down and DVC was constantly showing this error:

```sh
Error: ERROR: unexpected error - HTTPSConnectionPool(host='analytics.dvc.org', port=443): Read timed out. (read timeout=5)
```

#### Settings
```
DVC: 0.81.3
pip install DVC[all]
Python 2.7.17
Ubuntu 18.04
```

**Comment by efiop** [comment]
> Python 2.7.17

Just a reminder that we've dropped support for python 2.7, you shouldn't use it. Not sure how you've even managed to do that, as `pip install DVC[all]` will not install 0.81.3 on python 2.

Thanks for the report though! We will take a closer look ASAP!

**Comment by sid-marain** [comment]
Perhaps similarly?: `ERROR: unexpected error - HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url:<REDACTED>?fields=name (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1051)')))`

**Settings**
DVC 0.82.2
Python 3.6
Ubuntu 18.04

**Comment by shcheklein** [comment]
@sid-marain no, it's a different one. Could you please create a separate, include `dvc <command> -v <args>` (command arfg - those that produce the error), share the output, please?

**Comment by mroutis** [comment]
Related: #3275

**Comment by efiop** [comment]
Need to look into handling analytics errors more gracefully. E.g. https://github.com/iterative/dvc/blob/0.82.8/dvc/main.py#L90 is outside of main's try-execept, so no friendly footer (the one with "need some help?") will be printed.

**Comment by pared** [comment]
Related to #3292
