### ISSUE TITLE
Google Remote API Error (max retries exceeded)

### ISSUE THREAD

**Issue by sid-marain** [iterative/dvc#3265]
```
ERROR: unexpected error - HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url:<REDACTED>?fields=name (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1051)')))
```

due to `dvc push`

excerpt from `dvc push -v`

```
DEBUG: fetched: [('1580439350437543424', '589', 'dc87bd29786e1cc8b2b3738ca8130c78', '1580440243730723328')]
DEBUG: UPDATE state SET timestamp = ? WHERE inode = ?
DEBUG: cache '.dvc/cache/dc/87bd29786e1cc8b2b3738ca8130c78' expected 'dc87bd29786e1cc8b2b3738ca8130c78' actual 'dc87bd29786e1cc8b2b3738ca8130c78'
DEBUG: Path .dvc/cache/05/31f82fec9701d95ef53ccf929dbaed inode 5738793
DEBUG: SELECT mtime, size, md5, timestamp from state WHERE inode=?
DEBUG: fetched: [('1580439350425543424', '28717', '0531f82fec9701d95ef53ccf929dbaed', '1580440243730771968')]
DEBUG: UPDATE state SET timestamp = ? WHERE inode = ?
DEBUG: cache '.dvc/cache/05/31f82fec9701d95ef53ccf929dbaed' expected '0531f82fec9701d95ef53ccf929dbaed' actual '0531f82fec9701d95ef53ccf929dbaed'
DEBUG: Path .dvc/cache/e9/c97e5d0a774d08c0a2d5b0e2e510b7 inode 5738794
DEBUG: SELECT mtime, size, md5, timestamp from state WHERE inode=?
DEBUG: fetched: [('1580439350437543424', '25515', 'e9c97e5d0a774d08c0a2d5b0e2e510b7', '1580440243730871296')]
DEBUG: UPDATE state SET timestamp = ? WHERE inode = ?
DEBUG: cache '.dvc/cache/e9/c97e5d0a774d08c0a2d5b0e2e510b7' expected 'e9c97e5d0a774d08c0a2d5b0e2e510b7' actual 'e9c97e5d0a774d08c0a2d5b0e2e510b7'`
```
Settings
DVC 0.82.6
Python 3.6
Ubuntu 18.04

**Comment by shcheklein** [comment]
@sid-marain what remote type do you use? Google Drive or GCP?

can you push at least one file or it happens in the middle?

**Comment by sid-marain** [comment]
It's GCP.

I can push at least two files, I believe, but the last fails. This happens somewhat infrequently. I am running dvc in a distributed manner from docker in a batch process.

**Comment by shcheklein** [comment]
@sid-marain thanks! could you also please share the last part of the stack trace? 

It's not clear yet what is happening. To be honest looks more like an environment error to me. We would need to find a way (together?) to reproduce this most likely to understand what's happening.

**Comment by mroutis** [comment]
@sid-marain , looks like GCP rate-limits you if you are doing consecutive requests: https://cloud.google.com/storage/docs/request-rate#auto-scaling

**Comment by sid-marain** [comment]
@shcheklein : That's all I'm getting from the stack trace. It's difficult to reproduce this error because, as mentioned above, it only seems to happen once every so often.

@mroutis : that might be it. We are potentially doing quite a few requests. Could  retry the dvc call w/ exponential backoff.

**Comment by mroutis** [comment]
> @mroutis : that might be it. We are potentially doing quite a few requests. Could retry the dvc call w/ exponential backoff.

@sid-marain , as far as I remember, `dvc push` is smart enough to detect already uploaded files, so a retry mechanism could definitely help.

**Comment by sid-marain** [comment]
@mroutis: Yeah. Based on review of the timing of this error on logs,  the requests were submitted and failed within a 20 second window. We don't really have a way to coordinate the call to dvc push across the batch, so I think the retry mechanism will have to do. Thanks!
