### ISSUE TITLE
diff: strange error when a ref (cmd argument) doesn't exist

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3266]
Note that this bug report is on the new (unreleased as of now) revision of `dvc diff` from #3229:

```console
$ .venv/bin/dvc version
DVC version: 0.82.6+d864ca
Python version: 3.7.6
Platform: Darwin-19.0.0-x86_64-i386-64bit
Binary: False
Package: None
Cache: reflink - supported, hardlink - supported, symlink - supported

...

$ dvc diff -t small.txt HEAD^   # This is a newish repo and HEAD^ doesn't exist yet.
ERROR: unexpected error - Cmd('git') failed due to: exit code(128)      
  cmdline: git rev-parse --short HEAD^
  stderr: 'fatal: Needed a single revision'


Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

See https://github.com/iterative/dvc/issues/2999#issuecomment-580600796 for a fully reproducible script.

**Comment by dmpetrov** [comment]
@jorgeorpinel thank you for finding this!
I thought it was solved already. See cases 1 and 2 from https://github.com/iterative/dvc/pull/3229#pullrequestreview-348892487 

But it seems like a special case of this bug.

**Comment by mroutis** [comment]
@jorgeorpinel , I can't replicate the error, I tried with the following:

```console
$ git init
$ dvc init
$ dvc diff 'HEAD^'

ERROR: failed to get diff - unknown Git revision 'HEAD^'
```

**Comment by shcheklein** [comment]
@mroutis did you try the original repro script @jorgeorpinel put together in the comment above:

> See #2999 (comment) for a fully reproducible script.

**Comment by mroutis** [comment]
@shcheklein , I didn't see the script, thanks for pointing that out.

I tried it one more time with the original reproduction script and still couldn't reproduce it :slightly_frowning_face: 

@jorgeorpinel , in this version of `dvc diff` we deprecated the use of `--target`.

**Comment by dmpetrov** [comment]
I guess @jorgeorpinel was found the bug in the old version. It was a race condition between us 😄
It looks like it can be closed. @jorgeorpinel please reopen if I missed something.

**Comment by jorgeorpinel** [comment]
Thanks guys! I guess it was fixed before the feature was officially released. I was trying on the beta while writing the docs.
