### ISSUE TITLE
No dot graphs in deb installation of DVC

### ISSUE THREAD

**Issue by kaiogu** [iterative/dvc#3267]
If I run `dvc pipeline show --dot` with the deb installation of DVC I get the following error:
```
$ dvc pipeline show -v --dot my_pipeline.dvc
ERROR: unexpected error - No module named 'pydot'
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/main.py", line 48, in main
  File "dvc/command/pipeline.py", line 130, in run
  File "dvc/command/pipeline.py", line 115, in __write_dot
  File "</usr/lib/dvc/decorator.pyc:decorator-gen-674>", line 2, in write_dot
  File "site-packages/networkx/utils/decorators.py", line 240, in _open_file
  File "site-packages/networkx/drawing/nx_pydot.py", line 46, in write_dot
  File "site-packages/networkx/drawing/nx_pydot.py", line 191, in to_pydot
  File "site-packages/networkx/drawing/nx_pydot.py", line 367, in _import_pydot
ModuleNotFoundError: No module named 'pydot'
------------------------------------------------------------

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

I tried many combinations of installing pydot and graphviz via `conda`, `pip`  and `apt`, but all lead to the error above.

Dot graph generation works when DVC (and pydot) is installed via conda.

**Please provide information about your setup**
DVC version: 0.82.2
Python version: 3.7.1
Platform: Linux-4.15.0-74-generic-x86_64-with-debian-buster-sid
Binary: True
Package: deb
Cache: reflink - not supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('xfs', '/dev/mapper/vg_sdb-lv_sdb')
Filesystem type (workspace): ('xfs', '/dev/mapper/vg_sdb-lv_sdb')

**Comment by kaiogu** [comment]
Conda installation of DVC is turning out to be problematic. It is not upgrading past version 0.54.1, probably due to a dependency conflict in my environment.

**Comment by efiop** [comment]
@kaiogu Maybe try pipenv?

**Comment by efiop** [comment]
For the record: issue here is that pydot is not included into regular dependencies in any package. We were afraid of it requireing graphviz, but looks like the installation itself is harmless and we could include it. It will raise an error when you try to use it though, if you don't have graphviz installed.

**Comment by efiop** [comment]
Adjusted out setup.py, 0.82.7 is releasing now. Will update conda package as well. Thanks for the feedback!
