### ISSUE TITLE
install: support pre-commit util

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#3271]
So far looks like we only need `pre-commit` to add support for `post-checkout` hook. Authors are ok with implementing it https://github.com/pre-commit/pre-commit/issues/1120 and the implementation is pretty straightforward. Might consider contributing that to provide the best experience for the users (as our dvc hooks get into conflict with out pre-commit hooks already).

**Comment by andrewhare** [comment]
I'm beginning work on this ticket now.

**Comment by andrewhare** [comment]
I've written up two PRs for `pre-commit`:
* https://github.com/pre-commit/pre-commit/pull/1339
* https://github.com/pre-commit/pre-commit.github.io/pull/307
