### ISSUE TITLE
ARM architecture support

### ISSUE THREAD

**Issue by nik123** [iterative/dvc#3279]
Recently I have tried to install DVC on Nvidia Jetson TX2 without any success (I have tried pip and deb packages). It seems that amd64 is the only supported architecture by now. Are there any plans for ARM-based devices support (Nvidia Jetson, Raspberry Pi, etc.)?

**Requirements:**
1. Hardware: Jetson TX2.
1. OS: Ubuntu 18.04.3.
1. Python version: 3.6.9 (inside virtual environment).

**Steps to reproduce:**
```
pip install dvc[all]
```
**Result:**

Installation fails with error message:

```
  CMake Error at cmake_modules/FindNumPy.cmake:62 (message):
    NumPy import failure:
  
    Traceback (most recent call last):
  
      File "<string>", line 1, in <module>
  
    ModuleNotFoundError: No module named 'numpy'
  
  Call Stack (most recent call first):
    CMakeLists.txt:189 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-xrq0e8dy/pyarrow/build/temp.linux-aarch64-3.6/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-xrq0e8dy/pyarrow/build/temp.linux-aarch64-3.6/CMakeFiles/CMakeError.log".
  error: command 'cmake' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyarrow
Failed to build pyarrow
ERROR: Could not build wheels for pyarrow which use PEP 517 and cannot be installed directly
```

**P.S.:**
You can find full log for `pip install dvc[all]` here: https://gist.github.com/nik123/f12c7e26c1005d12bbccff3e97ae586c

**Comment by mroutis** [comment]
@nik123 , have you encountered any specific error?

**Comment by efiop** [comment]
@nik123 To be honest, we haven't ever looked into ARM support :slightly_smiling_face: Indeed, deb package is a binary package, which is only meant for x86_64. Have you tried installing from conda or pip?

**Comment by mroutis** [comment]
@efiop , from his comment:

> I have tried pip and deb packages

**Comment by efiop** [comment]
@mroutis Oops, sorry, long day :slightly_smiling_face: Yeah, would love to see the pip error then. I imagine the issue there might be that some of our dependencies don't have binary wheels for arm and so pip tries to compile and fails.

**Comment by nik123** [comment]
@efiop I have tried to install via pip too. Right now I don't have access to the arm device. But as soon as I will have access to it I will try to install dvc again and post result here.

**Comment by nik123** [comment]
@mroutis , @efiop : I have updated description with error message and also attached full log for `pip install dvc[all]`

**P.S.:**
It seems if I install dvc itself (`pip install dvc`) it works fine. However if I try `pip install dvc[all]` it fails with error.

**Comment by efiop** [comment]
@nik123 Ok, looks like `pyarrow` is the cause there. Do you need support for hdfs? If not, just use whichever options you need instead of `all`, except for `hdfs`. E.g. `pip install '[gs,s3,azure,oss,ssh,gdrive]'` to install everything except for `hdfs` support. Please try it out and let us know how if it works or not. :slightly_smiling_face:

**Comment by nik123** [comment]
@efiop `pip install 'dvc[gs,s3,azure,oss,ssh,gdrive]'` ended with success.

**Comment by efiop** [comment]
@nik123 That is great! :slightly_smiling_face: Btw, could you show the error you were getting when installing deb package? It seems to have the platform info in it, so i expect it to handle incorrect destination platform gracefully.

I suppose `pip` package suits you in that form? Or do you need deb package?

In terms of action points here, so far we may be able to put some env marker check (e.g. https://github.com/vlachoudis/bCNC/blob/master/setup.py#L26 or maybe just `if` in setup.py would work, unsure) to not include pyarrow into `all` target on ARM. Though, I can't really guarantee that some another dependency won't break, as we admittedly don't support ARM "officially".

This is the first time someone reached out about using dvc on ARM, so I am wondering how many ARM users we have and if it would be reasonable to add an arm machine on travis to check that...

**Comment by Suor** [comment]
Setting aside the question whether we need to support ARM, it's a pyarrow issue, i.e. `pip install pyarrow` will fail as well. It makes sense opening issue there too.

**Comment by shcheklein** [comment]
@Suor yep! (but I would surprised if they are not aware about this already. I saw a post from Wes complaining about lack of wheels and how it's hard to support them, etc ...)

**Comment by casperdcl** [comment]
Looks likely necessary to `pip imstall numpy` first based on the logs

**Comment by casperdcl** [comment]
Fyi `pip install dvc` works fine on my arm64 phone

**Comment by nik123** [comment]
> @nik123 That is great! slightly_smiling_face Does dvc also work as expected after installation?

@efiop It works as intended. Although I mostly use `dvc pull` to get data.

> Btw, could you show the error you were getting when installing deb package? It seems to have the platform info in it, so i expect it to handle incorrect destination platform gracefully.

Package manager says that deb package doesn't support arm64. Here is the error message (sorry it's not english. Unfortunately it's the way my device is configured):

```
$ dpkg -i dvc_0.82.8_amd64.deb
dpkg: ошибка при обработке архива dvc_0.82.8_amd64.deb (--install):
 архитектура пакета (amd64) не соответствует архитектуре системы (armhf)
При обработке следующих пакетов произошли ошибки:
 dvc_0.82.8_amd64.deb
```

> I suppose pip package suits you in that form? Or do you need deb package?

Yes, pip package covers my needs. Thanks!

**Comment by casperdcl** [comment]
@nik123 can you try `pip install numpy` and then `pip install dvc[all]` again?

**Comment by nik123** [comment]
> @nik123 can you try pip install numpy and then pip install dvc[all] again?
I tried. It fails with the same error. Full log: https://gist.github.com/nik123/7af9ca1103a097e976f7caa57c6d079a

**Comment by efiop** [comment]
@casperdcl pyarrow compilation is quite hard in all aspects, we've ran into it previously.

@nik123 So deb is indeed showing a meaningful error, so no action is required from our package side. Though we could explicitly document that we don't provide binary packages for ARM, but that might be excessive considering that we are getting rid of binary packages in our docs in favour of package managers like pip, conda, brew, choco, etc. That being said,  we should probably document that dvc can be installed on ARM through pip and maybe other package managers.

Also, looks like we should setup travis ARM worker after all.

So leaving this ticket opened for the sake of ^ action points.

@nik123 Thanks for the feedback! :slightly_smiling_face:

**Comment by casperdcl** [comment]
ah I see

- `pip3 install numpy` might work?
- might need to mess with findNumpy/cmake vars (https://github.com/ray-project/ray/pull/820)
- related to https://github.com/apache/arrow/issues/5987

should be an upstream issue.

**Comment by federicomassa** [comment]
If anybody needs it, I installed it on arm64 with gdrive support (but if you don't need it you can just `pip install dvc` in the last command) on Nvidia PX2 (Ubuntu 16.04) like below (add `sudo` to each command if you need it). 
```
apt install -y software-properties-common && \
add-apt-repository ppa:deadsnakes/ppa       && \
apt update && \
apt install -y libffi-dev && \
apt install -y python3.6-dev && \
apt install -y python3-pip && \
python3.6 -m pip install --upgrade pip && \
python3.6 -m pip install --upgrade setuptools && \
python3.6 -m pip install dvc[gdrive]
```

**Comment by efiop** [comment]
Closing as stale.

**Comment by simplymathematics** [comment]
Am very interested. DVC would be particularly useful in a cluster or iOT environment where tracking models/data/parameters across many parallel experiments is critical. Particularly since the results and config file formats are so friendly to web services. I'm a PhD student and would likely have institutional support for the hardware/bandwidth. I'd be able to dedicate some time to this next year since

**Comment by wzhou0776** [comment]
Hi, is there any update on this? Tried to install on jetson nano but didn't succeed.

**Comment by efiop** [comment]
@wzhou0776 No updates, unfortunately.

**Comment by karajan1001** [comment]
On apple silicon it works.

**Comment by Alberto1404** [comment]
> 

Hi, is there any other way rather than using a virtual environment? In my case, I have the default python 2.7.17 and python 3.6.9. When doing ```pip install dvc``` the installation is not successfull because it is taking the python2 version. COuld it be possible to someone tell him to take the pytho3 version?
```
Collecting dvc
  Using cached https://files.pythonhosted.org/packages/a1/4a/8eae614946f71cb9e51b9f160c0e8d84f0ed1eaaa6cb5c1c69b6df21f597/dvc-0.78.1-py2.py3-none-any.whl
Collecting shortuuid>=0.5.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/80/d7/2bfc9332e68d3e15ea97b9b1588b3899ad565120253d3fd71c8f7f13b4fe/shortuuid-0.5.0.tar.gz
Collecting pathlib2; python_version == "2.7" (from dvc)
  Using cached https://files.pythonhosted.org/packages/09/eb/4af4bcd5b8731366b676192675221c5324394a580dfae469d498313b5c4a/pathlib2-2.3.7.post1-py2.py3-none-any.whl
Collecting pathspec>=0.6.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/42/ba/a9d64c7bcbc7e3e8e5f93a52721b377e994c22d16196e2b0f1236774353a/pathspec-0.9.0-py2.py3-none-any.whl
Collecting grandalf==0.6 (from dvc)
  Using cached https://files.pythonhosted.org/packages/0e/5a/129a9857f4970e3a543a7efe63ae1c6bad8d87f13162bdd5aa263636b539/grandalf-0.6-py2-none-any.whl
Collecting configobj>=5.0.6 (from dvc)
  Using cached https://files.pythonhosted.org/packages/d3/bb/d10e531b297dd1d46f6b1fd11d018247af9f2d460037554bb7bb9011c6ac/configobj-5.0.8-py2.py3-none-any.whl
Collecting setuptools>=34.0.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/e1/b7/182161210a13158cd3ccc41ee19aadef54496b74f2817cc147006ec932b4/setuptools-44.1.1-py2.py3-none-any.whl
Collecting future>=0.16.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/8f/2e/cf6accf7415237d6faeeebdc7832023c90e0282aa16fd3263db0eb4715ec/future-0.18.3.tar.gz
Collecting funcy>=1.14 (from dvc)
  Using cached https://files.pythonhosted.org/packages/e6/c1/8f2c327498b9a15bd7ba426d539760c5ad60b1c1ee8e372bbf43d36f7023/funcy-1.18-py2.py3-none-any.whl
Collecting contextlib2; python_version == "2.7" (from dvc)
  Using cached https://files.pythonhosted.org/packages/85/60/370352f7ef6aa96c52fb001831622f50f923c1d575427d021b8ab3311236/contextlib2-0.6.0.post1-py2.py3-none-any.whl
Collecting appdirs>=1.4.3 (from dvc)
  Using cached https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
Collecting packaging>=19.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/3e/89/7ea760b4daa42653ece2380531c90f64788d979110a2ab51049d92f408af/packaging-20.9-py2.py3-none-any.whl
Collecting ruamel.yaml>=0.16.1 (from dvc)
  Using cached https://files.pythonhosted.org/packages/65/e9/494f4a4ae771028900ff085d41f39c7f117b9e839ad8c15c2101ca4e16f1/ruamel.yaml-0.17.1-py2.py3-none-any.whl
Collecting zc.lockfile>=1.2.1 (from dvc)
  Using cached https://files.pythonhosted.org/packages/75/0b/b7ea42dbb55ed0dc238246a5489dff59da228331acfcfc281800ef368b73/zc.lockfile-3.0.tar.gz
Collecting tqdm<5,>=4.40.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/47/bb/849011636c4da2e44f1253cd927cfb20ada4374d8b3a4e425416e84900cc/tqdm-4.64.1-py2.py3-none-any.whl
Collecting voluptuous>=0.11.7 (from dvc)
  Using cached https://files.pythonhosted.org/packages/72/0c/0ed7352eeb7bd3d53d2c0ae87fa1e222170f53815b8df7d9cdce7ffedec0/voluptuous-0.13.1.tar.gz
Collecting distro>=1.3.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/b3/8d/a0a5c389d76f90c766e956515d34c3408a1e18f60fbaa08221d1f6b87490/distro-1.6.0-py2.py3-none-any.whl
Collecting inflect<4,>=2.1.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/2a/14/49a8afaaa66fb49cda8e60512f0fc07594232fb10ea6aa8995c069172cf6/inflect-3.0.2-py2.py3-none-any.whl
Collecting networkx<2.4,>=2.1 (from dvc)
  Using cached https://files.pythonhosted.org/packages/f3/f4/7e20ef40b118478191cec0b58c3192f822cace858c19505c7670961b76b2/networkx-2.2.zip
Collecting nanotime>=0.5.2 (from dvc)
  Using cached https://files.pythonhosted.org/packages/d5/54/6d5924f59cf671326e7809f4b3f70fa8df535d67e952ad0b6fea02f52faf/nanotime-0.5.2.tar.gz
Collecting jsonpath-ng>=1.4.3 (from dvc)
  Using cached https://files.pythonhosted.org/packages/64/37/71a4ad7df50e424424af942ea47688900550ea621c287adeb7bcaf5748ef/jsonpath_ng-1.5.3-py2-none-any.whl
Collecting colorama>=0.3.9 (from dvc)
  Using cached https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl
Collecting ply>=3.9 (from dvc)
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Collecting pyasn1>=0.4.1 (from dvc)
  Using cached https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl
Collecting PyYAML<5.2,>=5.1.2 (from dvc)
  Using cached https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz
Collecting configparser>=3.5.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
Collecting futures; python_version == "2.7" (from dvc)
  Using cached https://files.pythonhosted.org/packages/d4/ea/9d513529a89bcbcd07c8acbac9eecfad29e7562e0b9d69d14f475987ad70/futures-3.4.0-py2-none-any.whl
Collecting python-dateutil<2.8.1,>=2.1 (from dvc)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting requests>=2.22.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl
Collecting humanize>=0.5.1 (from dvc)
  Using cached https://files.pythonhosted.org/packages/4a/73/6c3e7fae17203610523953f35ce9fefebb61d72b5af1c5ecd1e3fd23ada7/humanize-1.0.0-py2.py3-none-any.whl
Collecting gitdb2>=2.0.6 (from dvc)
  Using cached https://files.pythonhosted.org/packages/97/97/6ad081c9f3efa1545fd11149f14602a53e2003c153312c8bfa825ba27b89/gitdb2-4.0.2.tar.gz
Collecting treelib>=1.5.5 (from dvc)
  Using cached https://files.pythonhosted.org/packages/04/b0/2269c328abffbb63979f7143351a24a066776b87526d79956aea5018b80a/treelib-1.6.1.tar.gz
Collecting gitpython>=2.1.8 (from dvc)
  Using cached https://files.pythonhosted.org/packages/7a/c9/6e1aec0893efe66f407d2e14a3daba73dbb39bbeeb72142b037c4a224d40/GitPython-2.1.15-py2.py3-none-any.whl
Collecting typing; python_version < "3.5" (from pathlib2; python_version == "2.7"->dvc)
  Using cached https://files.pythonhosted.org/packages/0b/cb/da856e81731833b94da70a08712f658416266a5fb2a9d9e426c8061becef/typing-3.10.0.0-py2-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7"->dvc)
  Using cached https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz
Collecting six (from pathlib2; python_version == "2.7"->dvc)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting pyparsing (from grandalf==0.6->dvc)
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" (from ruamel.yaml>=0.16.1->dvc)
  Using cached https://files.pythonhosted.org/packages/b7/81/c04fb9be62657d4dce8aa2d99fde258a3af1cd77ec72af525593e9560127/ruamel.yaml.clib-0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    minimum python version(s): [(3, 5)]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iBxABK/ruamel.yaml.clib/
```

**Comment by efiop** [comment]
@Alberto1404 The error looks related to not being able to build pygit2 wheels (try intalling it separately and debugging from there), seems like you are missing parts of the error log. pygit2 doesn't provide arm wheels (nor most of projects) so you'll need to tinker to get that to build first.

Also note that you are using python 3.6, but dvc (and many other tools) stopped supporting it more than a year ago and currently 3.8+ is supported. Hence why venv is recommended.

**Comment by Alberto1404** [comment]
Understood. Thank you for your fast reply!
I deleted because as soon as I posted it, the problem was solved executing: 
```
sudo python3 -m pip install -U pip
sudo python3 -m pip install -U setuptools
```

**Comment by jpvelez** [comment]
+1 for .deb files that work on arm! A must for working with docker-based devcontainers on apple silicon

**Comment by simplymathematics** [comment]
Compiling from source on an Nvidia Orin worked.
