### ISSUE TITLE
CondaValueError: Malformed version string '~': invalid character(s).

### ISSUE THREAD

**Issue by anderl80** [iterative/dvc#3281]
# System Info

Linux version 2.6.32-754.23.1.el6.x86_64 (mockbuild@x86-vm-26.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) ) #1 SMP Tue Sep 17 09:46:55 EDT 2019

# Conda Info

```bash
     active environment : platform_related
    active env location : /home/.../.conda/envs/platform_related
            shell level : 2
       user config file : /home/.../.condarc
 populated config files : /home/.../.condarc
          conda version : 4.5.11
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /opt/anaconda3  (read only)
           channel URLs : ...
          package cache : /opt/anaconda3/pkgs
                          /home/.../.conda/pkgs
       envs directories : /home/.../.conda/envs
                          /opt/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.4 Linux/2.6.32-754.23.1.el6.x86_64 rhel/6.10 glibc/2.12
                UID:GID : 843337735:843200513
             netrc file : None
           offline mode : False
```

# Bug

```bash
conda install conda-forge::dvc
Solving environment: failed

CondaValueError: Malformed version string '~': invalid character(s).
```

**Comment by efiop** [comment]
Hi @anderl80 !

Looks like it is a conda issue: https://stackoverflow.com/questions/56084960/condavalueerror-malformed-version-string-invalid-characters . Could you try upgrading your conda with `conda upgrade -n base conda` and see if that helps, please?

**Comment by anderl80** [comment]
I will, it's a collaborativ system and I have to wait for operations to update the conda environment.

**Comment by efiop** [comment]
@anderl80 Any luck? :slightly_smiling_face: Another user (@andronovhopf ) has run into this issue and it was solved by updating conda.

**Comment by shcheklein** [comment]
@anderl80 btw, could you use a different method to install DVC on this system? E.g. `snap` or `rpm` package?

**Comment by anderl80** [comment]
I can use pip now 👌🏼. So then let’s close the ticket. Must talk to my customer on maintenance and updates 😉.

Schöne Grüße,
Dr. Andreas Hopfgartner
________________________________
Von: Ivan Shcheklein <notifications@github.com>
Gesendet: Saturday, February 15, 2020 2:23:02 AM
An: iterative/dvc <dvc@noreply.github.com>
Cc: Dr. Andreas Hopfgartner <schotterschorsch@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [iterative/dvc] CondaValueError: Malformed version string '~': invalid character(s). (#3281)


@anderl80<https://github.com/anderl80> btw, could you use a different method to install DVC on this system? E.g. snap or rpm package?

**Comment by efiop** [comment]
@anderl80 Sounds good :) Closing for now, please feel free to reopen.

**Comment by 999sanfentang** [comment]
修改.condarc文件

全选替换为：

ssl_verify: false
channels:
  - defaults
show_channel_urls: true
channel_alias: http://mirrors.tuna.tsinghua.edu.cn/anaconda
default_channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
envs_dirs:
  - /anaconda/envs
pkgs_dirs:
  - /anaconda/envs
show_channel_urls: true

具体参考我的博客https://blog.csdn.net/weixin_68331871/article/details/134834475?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22134834475%22%2C%22source%22%3A%22weixin_68331871%22%7D
