### ISSUE TITLE
Specify directory to hold dvc files

### ISSUE THREAD

**Issue by vernt** [iterative/dvc#3291]
If I `dvc run` from my project root, I get a lot of dvc files in that directory. One existing option is

```
dvc run -w dvcfiles/ -d ../data/input.csv -o ../data/output.csv python ../script.py
```
but I don't really want to change the working directory of my command just to set the location of the dvc file.

Another existing option is 

```
dvc run -f dvcfiles/script.dvc -d data/input.csv -o data/output.csv python script.py
```
but that means I have to pass a name for my dvc file when I don't really care about the name.

I would like a flag that takes a directory where the dvc file will go without having to pass a name.

**Comment by efiop** [comment]
Hi @vernt !

Please take a look at discussion in https://github.com/iterative/dvc/issues/1871 , we are considering creating pipeline-files that you could store your whole DAG (or parts of it) in. Maybe that would be a better alternative to what you currently suggest?

**Comment by efiop** [comment]
Closing as stale.
