### ISSUE TITLE
term: replace "working tree/dir" for "workspace"? (where appropriate)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3302]
> Extracted from https://github.com/iterative/dvc/issues/3245#issuecomment-580386915

I found it in the following places, at least:

https://github.com/iterative/dvc/blob/de1f67afbd93929d51c5dd052d5f8a951e77c182/dvc/command/gc.py#L15-L17
https://github.com/iterative/dvc/blob/b99c5e4aad6528199ef960d04043f8ffdf3f528c/dvc/repo/brancher.py#L33
https://github.com/iterative/dvc/blob/de1f67afbd93929d51c5dd052d5f8a951e77c182/scripts/completion/dvc.zsh#L76

**Comment by jorgeorpinel** [comment]
@shcheklein another option is to remove the term "workspace" from everywhere and use "working tree" borrowed from Git/SCM. Not sure it would make sense to use that term for `--no`scm` projects though.

Related: https://github.com/iterative/dvc.org/pull/931#discussion_r376181149

**Comment by jorgeorpinel** [comment]
I think this was closed by #3914 no @efiop ? 🙂

**Comment by efiop** [comment]
@jorgeorpinel Yes! Sorry for the delay. Closing for now.
