### ISSUE TITLE
`dvc add` print not quote-wrapped file-paths if they contain spaces

### ISSUE THREAD

**Issue by byaka** [iterative/dvc#3303]
dvc 0.82.8
installed via yum
centos 7

Some of our, khm, windows-users put files in project with spaces in names.
In this case `dvc add`, when prints hint-command `git add blah-blah`, not wrap path with quotes so copy-paste this hint-command not working ofc.

**Comment by efiop** [comment]
Off topic: Makes me think if we should re-consider auto `git add`ing files. :thinking:

**Comment by byaka** [comment]
> Off topic: Makes me think if we should re-consider auto `git add`ing files.

think it good idea if it will not break old setups after upgrade :)

**Comment by efiop** [comment]
@byaka Good point, the only thing it might break is if some users commit subsets of files, as dvc will have all of those git-added automatically. Would that break your setup?

We have heard some requests about `git-add`ing automatically previously: https://github.com/iterative/dvc/issues/1576, https://github.com/iterative/dvc/issues/1558 .

CC @iterative/engineering what do you think, guys?

**Comment by casperdcl** [comment]
Still think `--git` flag would be the first thing to add (which would in this case `git add`). Making it automatic/default would be a discussion for later.

**Comment by jorgeorpinel** [comment]
> CC @iterative/engineering what do you think, guys?

Maybe let's discuss that in https://github.com/iterative/dvc/issues/1576#issuecomment-590658711? 🙂 

---

As for this issue, I think we should definitely wrap file names that have spaces in them (or maybe just all file names) with quotes in the `git add` hint after `dvc add`. It's not even just a Windows problem, it can happen anywhere. It's basically a (small) bug.

POSIX terminal repro script:
```console
$ echo foo > data\ with\ spaces
$ ls -l
total 16
-rw-r--r--  1 jop  staff    4 Feb 24 21:05 data with spaces
$ dvc add data\ with\ spaces
$ 100% Add|█████████████████████████████████████████████████████████████████████████████████████████████████████████████|1/1 [00:01,  1.03s/file]

To track the changes with git, run:

	git add data with spaces.dvc .gitignore
$ git add data with spaces.dvc .gitignore
fatal: pathspec 'data' did not match any files
```

**Comment by jorgeorpinel** [comment]
^ p.s. if I had an unstaged file/dir named data this could lead to errors.

**Comment by efiop** [comment]
> Still think --git flag would be the first thing to add (which would in this case git add). Making it automatic/default would be a discussion for later.

That flag doesn't make much sense, as we already know that we are running in git, hence the note about `git add` after `dvc add`ing anything.

**Comment by efiop** [comment]
@jorgeorpinel we do have a PR that handles that for posix through shlex, but for windows we need mslex which doesn't even have a conda package, plus it is not really compatible with gitbash, and we are currently not distinguishing between windows cmd/powershell and gitbash in our code. So if we go through so much trouble for mslex, it might be more reasonable to discuss auto git-adding instead.

**Comment by casperdcl** [comment]
@efiop not sure we are on the same page. Just to be clear, I mean:

```bash
$ dvc add file
...
To track the changes with git, run:

	git add file.dvc .gitignore
$ git status
...
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   .gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        file.dvc
```

versus:

```bash
$ dvc add --git file
...
$ git status
...
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   .gitignore
        new file:   file.dvc
```

I'm not too fussed about what the new flag is called, though `--git` seems to make most sense since it is generic so can be used in other commands as well (e.g. `dvc move --git file data`).

Perhaps we should discuss this in a different issue?

**Comment by efiop** [comment]
@casperdcl I don't like the `--git` flag, it looks messy no matter how you call it. It feels like we could safely just assume `--git` always. Need to discuss it and give it a thought, maybe there are some problems I'm not foreseeing right now.

**Comment by byaka** [comment]
> @byaka Good point, the only thing it might break is if some users commit subsets of files, as dvc will have all of those git-added automatically. Would that break your setup?

yep, we often use adding files by mask like `folder/*.jbl` and folder can contain 200+ files.
is this problem?

also we using dvc right from our code (and not always this projects have git configured).
