### ISSUE TITLE
import: behave like `add`, `move`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3304]
> More context around https://discordapp.com/channels/485586884165107732/485596304961962003/676398069469806603

Currently `dvc import` has a `-o` option to specify where to place the downloaded data, but the DVC-file itself gets created in the CWD. It would be more intuitive to have the DVC-file in the same `--out` location, similar to how `dvc add` behaves.

This is especially strange when using `dvc move` on an import stage, as it moves both the data and the DVC-file into the `dst` location.

May apply to `dvc import-url` as well, haven't checked.

**Comment by jorgeorpinel** [comment]
p.s. this may apply to `dvc import-url` as well, haven't checked.

**Comment by efiop** [comment]
I feel like this might be a bug that we didn't notice, as I do remember implementing this behavior for original `import`(now `import-url`). :confused: Will take a look.

**Comment by pared** [comment]
As import is using `imp_url` fixing this issue for `imp_url` will probably fix it also for `imp`.

**Comment by pared** [comment]
repro script
```
#!/bin/bash

rm -rf erepo repo
mkdir erepo repo
MAIN=$(pwd)

pushd erepo
git init --quiet
dvc init -q

echo data >> data
dvc add data
git add -A
git commit -am "init"

popd
pushd repo
git init --quiet && dvc init -q

mkdir dir
dvc import $MAIN/erepo data -o dir/data
ls
```
ls shows that `data.dvc` is in root project dir, while it should not be
