### ISSUE TITLE
perf: checkout: subsequent runs slow

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#3313]
Running `dvc checkout` multiple times shows slow progress going through all files rather than returning quickly. Using local remote (both on a different drive as well as same drive):

[![asciicast](https://asciinema.org/a/Jywdxkf1t3MmC3PVoYgp9P2aJ.svg)](https://asciinema.org/a/Jywdxkf1t3MmC3PVoYgp9P2aJ?speed=4)

```
DVC version: 0.83.0
Python version: 3.6.9
Platform: Linux-4.15.0-58-generic-x86_64-with-Ubuntu-16.04-xenial
Binary: False
Package: snap
Cache: reflink - not supported, hardlink - supported, symlink - supported
```

**Comment by dberenbaum** [comment]
@dtrifiro `dvc checkout` performance on subsequent runs could be a good area to research. Let's consider what the priority should be for this.
