### ISSUE TITLE
remove: change default behaviour to `--purge`, port back patch from 1.0 branch

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3317]
`dvc remote --outs` is the default behavior so will this option ever be used?

**Comment by efiop** [comment]
It was meant for backward compatibility. We've planned to switch from it in 1.0 https://github.com/iterative/dvc/issues/763 and even have a patch there already. I guess we could consider switching it earlier. `dvc remove` needs some reconsideration in general, we are also thinking about it in terms of removing cache for a file, which is related to `gc` discussion.

**Comment by jorgeorpinel** [comment]
Gotcha. Feel free to close this if it's included in some other issue or you feel it's not really impactful. Thanks for the explanation though!

**Comment by efiop** [comment]
@jorgeorpinel Let's close it since it is fixed in 1.0 branch.

**Comment by efiop** [comment]
On second thought... It is so trivial to fix that it is not worth waiting for 1.0 and we've been breaking worse stuff previously, so no need to be overprotective here. Keeping it open.
