### ISSUE TITLE
missing progress

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#3332]
any reason why `no_progress_bar=True` in these three places?

- `remote.gdrive.RemoteGDrive.gdrive_upload_file()`
  + from e7227898e4e10a1 by @MaxRis
- `remote.base.RemoteBASE._get_dir_info_checksum():self.cache.upload()`
  + from 00cfb04fea04694 by @efiop
- `remote.gs.RemoteGDrive.RemoteGS._upload()` and `_download()`
  + from 28b99dc4c78a7bc by, er, @casperdcl

(related: #3060)

**Comment by MaxRis** [comment]
@casperdcl both places in `gdrive` and `gs` remotes expect `no_progress_bar` value to be passed from `RemoteBase` class. Default `True` values seems are only the preference to be silent by default if internal methods will be reused in future by `gdrive` or `gs`.
