### ISSUE TITLE
dvc disables logging of other packages

### ISSUE THREAD

**Issue by ttekampe** [iterative/dvc#3344]
DVC version is 0.80.0 and I am running Linux. The package was installed from AUR

To reproduce the issue run the following few lines of code
```
import logging

LOGGER = logging.getLogger(__name__)

print(LOGGER.disabled)

import dvc
print(LOGGER.disabled)
```

which will output
```
False
True
```

The reason for this is the usage of `logging.config.dictConfig` [here](https://github.com/iterative/dvc/blob/19edc1ab1d2020711c43f8bb9ad58930c74802f6/dvc/logger.py#L147) without adding `"disable_existing_loggers": False` to the dict

**Comment by efiop** [comment]
Hi @ttekampe !

Good catch! And thanks for the PR!

Please be aware that AUR package is not officially supported, so consider using some other package.
