### ISSUE TITLE
metrics diff: support numeric string delta for json metrics

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc#3354]
Hi, python is very problematic serialising JSON floats. With the standard library is very easy to incur in 

```sh
TypeError: 0.873 is not JSON serializable
```
also if you specify the value as a float you are giving the control to the JSON parser which may not be very precise, and precision may be here very important. 

a_ver : 
```json
{"accuracy": "0.8729"}
```

b_ver
```json
{"accuracy":  "0.8755"}
```
outputs no diff
```json
{"metrics/eval.json": {"accuracy": {"old": "0.8729", "new": "0.8755"}}} 
```

or 

```sh
      Path           Metric    Value         Change                     
metrics/eval.json   accuracy   0.875   diff not supported
```

**Comment by efiop** [comment]
@DavidGOrtega Could you please show where `TypeError: 0.873 is not JSON serializable` came from?

**Comment by DavidGOrtega** [comment]
@efiop what I say is that if you do json.dump( of floats in my metrics with python I have that error, thats why I store them as strings. Said that also is a good way to store them as strings if you want to be very precise because if not you rely on the json decoder.

**Comment by efiop** [comment]
@DavidGOrtega I just don't quite understand how to reproduce your issue:
```
>>> import json
>>> json.dumps({"a": 0.873})
'{"a": 0.873}'           
```
works fine for me.

**Comment by DavidGOrtega** [comment]
Its tricky but very well known:
https://bugs.python.org/issue16535

Aside of that I like to store in string not handle my self the precision

**Comment by efiop** [comment]
Closing for now.
