### ISSUE TITLE
remove: implement a --cache option/behavior?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3355]
> Context: https://discordapp.com/channels/485586884165107732/563406153334128681/678885051815165953

This option would also remove the DVC-file outputs from cache (not just from workspace).

Use case: freeing up space used by intermediate results once a final result/modes is stable.

It would also make `dvc remove` more useful for single-output stages.

> Similar to https://git-annex.branchable.com/git-annex-drop/

**Comment by efiop** [comment]
Will be solved after gc, because it is directly related to it https://github.com/iterative/dvc/issues/2325

**Comment by efiop** [comment]
Closing as stale.
