### ISSUE TITLE
--show-json support for dvc metrics show

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc#3356]
The current output is difficult to be handled. Specially with multiple metrics json files.
Since some metrics ops offers the --show-json I would be great if that were supported.

**Comment by efiop** [comment]
@DavidGOrtega @JIoJIaJIu Guys, talked with @dmpetrov and he advised not to implement this until we redesign `dvc metrics show` as a whole. So removing from this sprint for now.

**Comment by dmpetrov** [comment]
It looks like the current `dvc metrics diff` if enough. This info can be extracted from there.

Closing.
