### ISSUE TITLE
dvc diff includes folders

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc#3358]
Not sure if this works as intended.

output
```json
{"added": [], "deleted": [{"path": "models/checkpoint"}, {"path": "models/mnist.data-00000-of-00001"}, {"path": "models/mnist.index"}, {"path": "models/mnist.meta"}], "modified": [{"path": "metrics/confusion_matrix.json"}, {"path": "metrics/eval.json"}, {"path": "metrics/history.json"}, {"path": "metrics/train.json"}, {"path": "models/"}]}
```

**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

Ubuntu 18.04
dvc 0.84.0
Python 3.6.9

**Comment by efiop** [comment]
@DavidGOrtega Could you elaborate please?

**Comment by DavidGOrtega** [comment]
@efiop indeed I can!

in my output   {"path": "models/"} is a folder

**Comment by efiop** [comment]
@DavidGOrtega Did you `dvc add models` as a whole dir?

**Comment by DavidGOrtega** [comment]
yes

```
dvc run --no-exec \
    -f train.dvc \
    -d code/train.py \
    -d data \
    -o models \
    -M metrics/train.json \
    -M metrics/history.json \
    python code/train.py

dvc run --no-exec \
    -f eval.dvc \
    -d code/eval.py \
    -d data \
    -d models \
    -M metrics/eval.json \
    -M metrics/confusion_matrix.json \
    python code/eval.py
```

**Comment by efiop** [comment]
@DavidGOrtega Then it is expected. `models` is tracked as a whole and it was modified as a whole, which is reflected in the diff. Does it cause any issues for you? Or maybe you've expected to see something else?

**Comment by DavidGOrtega** [comment]
> Not sure if this works as intended.

Ok! I just wanted to be sure. Despite that sounds to me a little bit redundant since we are showing files inside that folder.

**Comment by efiop** [comment]
@DavidGOrtega Ok, so leaving as is for now. Thanks for the heads up!
