### ISSUE TITLE
Not pushing when there are empty md5 clauses in any DVC-file

### ISSUE THREAD

**Issue by adrianohrl** [iterative/dvc#3359]
Instead of using the `dvc run` command, I manually created a DVC-file to compose my processo  pipeline as its last stage. For minimizing my efforts, I cleaned all md5 clauses presented in this DVC-file. Before reproducing it, I ran the `dvc push` command, leading to an issue. I could not push properly until I removed all empty md5 clauses from this DVC-file.

DVC version: 0.83.0
Platform: Ubuntu 18.04
Method of installation: apt install dvc[s3]

**Comment by efiop** [comment]
For the record: The issue happens if you replace `md5: 123456` with `md5: ` in any dvc-file and then try to `dvc push` or `dvc status -c` it.

Discord context: https://discordapp.com/channels/485586884165107732/485596304961962003/679431956777402368

**Comment by pared** [comment]
Error message fixed in #3365

**Comment by pared** [comment]
@adrianohrl now when trying to push you should see suggestion how lack of `md5`'s can be fixed.
