### ISSUE TITLE
Misclassification of binary files as text files

### ISSUE THREAD

**Issue by kevin-hanselman** [iterative/dvc#3364]
In the case where binary files have a large text header, the current
checksum routine will treat said files as text files and normalize
line-endings before performing the checksum. Not only is it dangerous to
manipulate binary files like this, it also doubles the runtime of the
checksum routine, as every block of data must be read twice.

As noted in #3264, at the minimum, DVC should probably match
Git's text file detection routine, which interrogates the first 8 kilobytes
(and doesn't do heuristics on ratio of printable characters,
as DVC currently does).

**Comment by efiop** [comment]
Note that changing this heuristic will break backward compatibility, so we won't be able to adjust this right now.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/4658
