### ISSUE TITLE
get rid of `show_checksum` arg for Repo cloud APIs

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#3383]
Since we don't provide it via CLI anymore (except diff, that will be renamed on the CLI level to show-hash soon) is there a point of supporting them on the Repo API level?

If we think they can help to debug, let's review include proper `logger.debug`.

**Comment by efiop** [comment]
It is a leftover from a contributed PR. Will require adjusting tests though, so might happen when we redesign tests.

**Comment by efiop** [comment]
No longer relevant, was removed during one of the refactorings.
