### ISSUE TITLE
tests: conflicting test requirements/deps

### ISSUE THREAD

**Issue by kaiogu** [iterative/dvc#3389]
**Please provide information about your setup**
```
$ dvc --version
0.86.5+ffa8fe
```
I'm running Ubuntu 19.10 and installed via pip from source. I tried following the instructions in the contribution guidelines but got a fatal error (issue opened [here](https://github.com/iterative/dvc.org/issues/1016)). After working around that, I managed to build, but got two non-fatal errors:

```
ERROR: python-dev-tools 2020.2.5 has requirement pydocstyle==5.0.2, but you'll have pydocstyle 3.0.0 which is incompatible.
ERROR: moto 1.3.14.dev464 has requirement idna<2.9,>=2.5, but you'll have idna 2.9 which is incompatible.
```

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/565699007037571084/681167250455003210

**Comment by skshetry** [comment]
This might no longer be an issue as we have updated the tests dependencies to the latest version. And, we haven't received any other reports for a long time. Closing ...
