### ISSUE TITLE
diff: if cache is missing we should at least notify that results are partial

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#3391]
It's confusing to see just:

```
Modified:
    auc.metric
    data/features/
    model.pkl

files summary: 0 added, 0 deleted, 2 modified
```

when the actual output looks like this:

```
Modified:
    auc.metric
    data/features/
    data/features/test.pkl
    data/features/train.pkl
    model.pkl

files summary: 0 added, 0 deleted, 4 modified
```

Can we at least mention that result is partial (limited since cache is not available)?

**Comment by dmpetrov** [comment]
It shouldn't notify. It has to work properly without any cache. See reopened issue #2998

I increased the priority of #2998 because of this bug and mentioned that it is related to no cached data-dirs.
