### ISSUE TITLE
list: cannot list content of the data folder

### ISSUE THREAD

**Issue by JIoJIaJIu** [iterative/dvc#3394]
## Description
`dvc list url target`  where `target` is out-directory cannot list content of it

## Steps for reproduce
```
$ mkdir folder
$ echo content > folder/data.raw
$ dvc add folder
...
To track the changes with git, run:

        git add folder.dvc .gitignore

$ git add folder.dvc 
$ git commit -m 'add folder'
[master 9dc66b6] add folder
 1 file changed, 7 insertions(+)
 create mode 100644 folder.dvc
```
```
$ dvc list . folder
folder
$ dvc list . folder -R
folder
```
but **expects**
```
$ dvc list . folder
data.raw
$ dvc list . folder -R
data.raw
```
## Info
```
$ dvc --version
0.86.2+d4b019.mod
```

## Relates
#2509

**Comment by efiop** [comment]
Related to https://github.com/iterative/dvc/issues/3182 , as we will also need to download .dir cache files and parse them for this functionality.

**Comment by rdwrt** [comment]
This will be a very useful change, +1

**Comment by efiop** [comment]
Closing this in favor of https://github.com/iterative/dvc/issues/4107 , since it is newer. I have a WIP PR that should be ready later today.
