### ISSUE TITLE
ERROR: Stage file '<path-to-dvc>.dvc' cannot be an output.

### ISSUE THREAD

**Issue by i-Hun** [iterative/dvc#3402]
Hi!
I faced a strange and previously unseen issue trying to add some newly created files to DVC with `dvc add <path-to-files>`.
The full error log is 
```
Stage is cached, skipping.                                                                                  
  0% Add|                                                                   |0.00/1.13k [00:00,     ?file/s]
ERROR: Stage file 'data/xDeepFM-2-1/lbes_cat_101.jbl.dvc' cannot be an output.    
```
DVC: version 0.82.8.
OS: Ubuntu 18.04.3 LTS

**Comment by efiop** [comment]
Hi @i-Hun !

Looks like you are trying to `dvc add` a `.dvc`-file, right? If so, it is not allowed.

**Comment by i-Hun** [comment]
Oh, you are right. Thanks and sorry for silly question.

**Comment by Roman-** [comment]
> Oh, you are right. Thanks and sorry for the silly question.

This isn't as silly as it might seem, especially when one does `dvc add ./dataset1/*` which adds all subdirectories (with existing .dvc files!) of the `dataset1` directory. I think dvc should not cancel its job in these cases and just ignore adding .dvc files to dvc.

**Comment by vargonis** [comment]
@Roman-  I'm running exactly into the problem you describe. I tried adding `.dvc` to `.dvcignore`, to no avail. Any suggestion to be able to add all the contents of a directory that was previously added, thus creating the corresponding `.dvc` files inside?

**Comment by dberenbaum** [comment]
@vargonis If you have a directory full of `.dvc` files, you should be able to do something like:

```
$ dvc remove dir/*.dvc
$ dvc add dir
```
