### ISSUE TITLE
api: support streaming from Google Drive remotes

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3408]
> Extracted from https://github.com/iterative/dvc.org/pull/908#discussion_r382941301

GDrive is the only remote type that doesn't support file streaming. Should we work on adding it?

- [ ] and update docs (e.g. api ref)

**Comment by jorgeorpinel** [comment]
p.s. maybe could be included in #2865 and closed here.

**Comment by shcheklein** [comment]
@jorgeorpinel yes, let's add a check box to that list and keep/remove this ticket - I don't have a strong preference

**Comment by casperdcl** [comment]
depends on https://github.com/iterative/PyDrive2/pull/39

**Comment by jorgeorpinel** [comment]
Both PRs are merged now, does it mean maybe this is now supported? If so, to QA it. Thanks

**Comment by casperdcl** [comment]
well it means #3910 is (maybe) no longer blocked so it's getting close to being supported :)
