### ISSUE TITLE
Metrics: separating scalar and continuous/graphs metrics

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#3409]
## Problem

There are two types of metrics in ML projects: **scalar metrics** or just a number (like AUC) and **continuous metrics** or a sequence of numbers (like ROC curve - an array of numbers).

Today we support csv and json files as metrics without specifying what metrics are needed. In fact, DVC commands support only scalars: `dvc metrics diff`.

## Solution

It is important to support both, understand the semantics of the metrics and provide more value.

1. For **scalar metrics**, DVC should provide (and it does provide it now) `dvc metrics diff` functionality. We just need clearly file format in the documentation to make sure only scalar metrics are supported. Json/Ini are both good formats for scalar metrics.
2. For **continuous metrics**, DVC should provide plots/graph visualization functionality. Like `dvc viz show roc.json` and `dvc viz diff roc.json HEAD HEAD^^`. Both of the commands should generate graphs. The second command - two graphs (not diff).

## Types

Types might improve visualization a lot. There many possible types of graphs for `dvc viz`. It would be great to support a few common ones like regular plot, confusion matrix.

For scalar types, it is also important to specify a type. A scalar can be the result of the minimization of some function or maximization. If the user can specify this information it might help to show proper color: red if max meterics was decreased and green if increased.

We should not make the metrics file format complicated. So, it might be a better solution to specify metrics format in a separate file (like `Dvcfile` or special metrics file). 

```
- scalars_types:
      AUC: max
      error_1: min
- metrics:
      roc.json: plot
      error.csv: plot
      mx.json: confusion_matrix
```

## Open questions

1. Should we include `dvc viz` in the core dvc package? Problem - most likely it will bring dependencies to some graphics libraries which can cause installation issues in OS without graphics (like default EC2 instances). What options do we have?
2. How we should specify the format of the graphs. Do we need any customization? For example, mlflow supports only one type of graph and cannot show something more advance (like a confusion matrix). If we choose Vega-graph as the format we can support graph customization.
3. The metrics can be related to experiment parameters (see #3393) because we are introducing new DVC file types and can use a single DVC file to preserve some information about metrics or metrics types.

## Actions

- [ ] Modify DVC documentation - only scalar metrics are supported in the current format and DVC commands.
- [x] Implement continuous metrics with `dvc viz` command.
- [ ] Add support of types.

**Comment by efiop** [comment]
From discussion: need to delete/hide `-m` option for `dvc run` so that metrics are in git. `dvc metrics add` stays though.

**Comment by dmpetrov** [comment]
In order to make this scalar/continuous metrics separation, the current scalar metrics need to be redesigned. 

1. CSV/TSV types are specific to continuous metrics. There is no need to keep them in current, scalar ones. Let's **get rid of `CSV/TSV/HCSV/HTSV` metrics format**.
2. **Add support for YAML** since it is an often-used format - https://github.com/iterative/dvc/issues/3393#issuecomment-599929705
3. With two simple json/yaml formats, do we really need `raw` format? Let's **get rid of `raw` metrics format**.
4. Do we really need `xpath` in dvc-files? I see a clear use case in `metrics show` as a filter but not in other commands. **Let's consider removing `xpath`**.
5. Metrics `type` was mostly used for distinguishing xpath algorithms between hierarchical json and flat csv/tsv/hcsv/htsv. It looks like it is not needed if only json/yaml left. **Let's remove metrics `type`.**
6. **Change docs** - we should be very explicit about supporting only JSON/YAML format.
7. [Optional] Redesign `metrics show`. Transform it into a table-like format.

**Comment by jorgeorpinel** [comment]
> continuous/graphs

I would call these "series", "array", or "track" metrics. Not sure about term "continuous". Just a thought

> Json/Ini are both good formats for scalar metrics.

ini=YAML?

> Should we include dvc viz in the core dvc package?

Probably not. DVCx then? In this case x can also mean "eXperiment mgmt".

I have doubts about the command names though. So we're keeping `dvc metrics` only for scalars which have an entry called `scalars_types` in the "Metricsfile", and new command `dvc viz` for series with entry `metrics`? I think we can improve the naming, I'll come up with a suggestion 🙂 

> If we choose Vega-graph as the format we can support graph customization.

Sounds smart to leave this to a viz package like thar and just refer users to their formatting guidelines.

**Comment by jorgeorpinel** [comment]
> metrics can be related to experiment parameters (see #3393) because we are introducing new DVC file types and can use a single DVC file to preserve some information about metrics

Is there a decision on what the hyperparam metafiles are going to look like? It could be relevant to know for this point ^

> do we really need raw format? Let's get rid of raw metrics format

What about metrics that just spit a single number into a text file. That's not really something we want to support? (It could even be stored directly in the DVC-file in the future.)

**Comment by jorgeorpinel** [comment]
Note: point 6. in https://github.com/iterative/dvc/issues/3409#issuecomment-605444643 above should be automatic with our process. It will be addressed in com/iterative/dvc.org/pull/1097 and in the docs PR derived from addressing 2. 🙂

**Comment by jorgeorpinel** [comment]
@efiop 

> From discussion: need to delete/hide -m option

So we would remove `--metrics` as well and keep `--metrics-no-cache`? I like the shorter option name better. How about doing so but renaming `--metrics-no-cache` -> `--metric` (plural)?

> Having the current --metrics/-m behave like -M would be ideal but breaks backward compatibility.

**Comment by jorgeorpinel** [comment]
*singular

**Comment by jorgeorpinel** [comment]
One last comment for now, sorry:

> Implement continuous metrics with dvc viz command.

Keep in mind some of the text deleted in #1097 could be restored when writing docs for `dvc viz` (or whatever the command name ends up being). E.g. https://github.com/iterative/dvc.org/pull/1097/files#diff-5941ad4a74935aeef222249cb407d385L72-L74

**Comment by pared** [comment]
@dmpetrov as plot got joined into master, I am ticking point `dvc viz` as completed.

**Comment by pared** [comment]
Also, should I take care of other points on the checklist? @dmpetrov

**Comment by efiop** [comment]
Had a conversation with @dmpetrov and @shcheklein and decided to rename current `dvc metrics` into `dvc scores` and `dvc plot` to `dvc metrics`.

**Comment by efiop** [comment]
Also `dvc plot show` -> `dvc metrics plot`

**Comment by pared** [comment]
Do we really want to separate `scalars` from `metrics`?  
why not
```- metrics:
      AUC: max
      error_1: min
      roc.json: plot
      error.csv: plot
      mx.json: confusion_matrix```
?
I think that its quite a bit to expect users mark scalars vs metrics, especially that from user point of view, both cases are `metrics` its just that some of them are structured and some others are just numbers. I think that when running training, Ill think of `AUC` as the same type of asset as `ROC`. Of course, there is a difference in structure, but in both cases we talk about an entity used to measure my model performance. Should I mark it in my versioning tool as different entities then?

 Shouldn't we inform user about the mistake, when for example he tries to plot scalar and diff structured metric?

**Comment by jorgeorpinel** [comment]
> from user point of view, both cases are metrics

I agree with this concern. If we're going to do an aggressive change in terminology for 1.0, that's fine but let's try to avoid regrets later or motives to change it again.

Question: will scores and continuous metrics be saved with the same format in pipeline files? I.e. are they fundamentally the same?

"scalar metrics" (1) vs "continuous metric" (2) was the most correct jargon, I think. But it's probably too long/difficult.

For 1. I do like the term "score". Other ideas are "grade", "measure", "level", "scalar", "value", "quantity", "magnitude", "numeric", "figure" — notice use of singular here

For 2. I never really liked "plots". Ideas: "tables", "charts", "curves", "matrices", "metrics" — notice plural

But I'm not so used to the ML terminology so ultimately I think we should trust the teammates with the most data science/ ML experience

**Comment by dmpetrov** [comment]
> I think that its quite a bit to expect users mark scalars vs metrics, especially that from user point of view, both cases are `metrics`

Both cases are definitely metrics and this exactly what creates the problem. We need to distinguish them somehow.

Another possible solution might be not to use metrics command at all. Keep `dvc plot` and rename the scalar ones to `dvc scores` or something. So, we can strictly say that DVC supports two types of metrics - plots and scores.

What do you think about not using `dvc metrics` at all? :)

> For 1. I do like the term "score". Other ideas are "grade", "measure", "level", "scalar", "value", "quantity", "magnitude", "numeric", "figure" — notice use of singular here

My list was: 
- "summary" - good term from statistics
- "score" - pretty common
- "scalars"  - precise but not common
- "stats".

> For 2. I never really liked "plots". Ideas: "series", "tables", "charts", "graphs", "curves", "matrices", "metrics" — notice plural

My list:
- "plot"
- "graph"
- "viz"
- now "metrics"

**Comment by pared** [comment]
@dmpetrov 
>Another possible solution might be not to use metrics command at all. Keep dvc plot and rename the scalar ones to dvc scores or something. So, we can strictly say that DVC supports two types of metrics - plots and scores.

It makes much more sense to me when its presented that way.

**Comment by shcheklein** [comment]
> Another possible solution might be not to use metrics command at all.

It feels a bit strange to me that this split forces us to move away from a very basic and common in ML term "metrics".

> Do we really want to separate scalars from metrics? why not

@pared could you try to elaborate? how would `dvc metrics *` command look like in this case? are we going to keep `dvc plot` and just document that it deals with metrics (not trying to invent a separate term). Like both commands will be about metrics and that's it?

**Comment by jorgeorpinel** [comment]
Could we just continue to use `dvc run -m` to define all kinds of metrics file? And `dvc metrics add/modify/remove`

The problem with keeping `dvc metrics` is that we would need sub subommands e.g. `dvc metrics score:show/diff` and `dvc metrics series:show/diff`

**Comment by pared** [comment]
@shcheklein 
Well, I was thinking that we might let the user mark every type of metric as `-m` and try to handle its type in a "lazy way" that is the moment user tries to interact with it. For example, throw an error with a proper message when trying to `plot` scalar, or `metrics diff` values array/ csv.

**Comment by shcheklein** [comment]
@pared the only problem, is that we already have `dvc plot diff` (third level for the plot alone) - how would we incorporate it back into `dvc metrics`?

**Comment by pared** [comment]
@shcheklein I would not incorporate it into metrics. The thing about this command is that it works with properly structured metrics. I thnk its fine to give feedback to the user that his metric of choice is unfit to be plotted. I would leave `dvc plot` as is, though the `dvc metric` should probably be changed because it indicates that this is the command to interact with metrics.

**Comment by shcheklein** [comment]
> ... changed because it indicates that this is the command to interact with metrics.

right. anything good comes to your mind in terms of the name?  

Btw, if we keep both commands then it's not so about laziness for these command anymore, right? It will be more about auto-detecting metric type automatically ...

**Comment by efiop** [comment]
@pared It doesn't make sense to "keep" `plot`, as it is not something that anyone relies on. People will be searching for `dvc metrics` and it will be harder for them to find `plot` command, which sounds ambiguous. And with `dvc metrics` + `dvc scores` it is deterministic, intuitive and easy to find.

**Comment by jorgeorpinel** [comment]
The obvious but ugly alternative is to have `dvc metrics score-show/score-diff/plot-show/plot-diff`. A lazy/autodetect metrics file format approach with the old `dvc metrics` commands (no `dvc plot`) sounds better. We'd just need to document the types of metrics and how they're autodetected very clearly.

**Comment by shcheklein** [comment]
yeah, I agree with @efiop . But the only question I still have in my mind - should we try to make all the functionality part of the `dvc metrics` and detect types automatically? Or we should indeed have two commands `dvc metrics` and `dvc plot`?

**Comment by efiop** [comment]
It makes more sense to me to have `dvc metrics diff/show`(old `dvc plot`) and `dvc scores diff/show`(old `dvc metrics`). It looks like we will also separate those on the dvc-file level with different markers, so it makes even more sense to just have separate commands. @jorgeorpinel approach with autodetecting won't work for commands that work without arguments: e.g. `diff` which plots a graph for metric-metrics and shows a table for score-metrics, which is impossible to nicely combine together.

**Comment by dmpetrov** [comment]
By assigning `dvc metrics` name to one (scalar) or another (continuous) we simplify and kind of promote one over another. We should think which of the scenarios is basic for DVC. @efiop is right that people will be looking for `dvc metrics` while they need plots. However, it works in the opposite direction.

What action we can make:
1. "Prioritize" scalars and keep everything as is. It is very natural for DVC since we focus on commits - experiment results. It emphasizes team collaboration scenarios.
2. "Prioritize" plots (`dvc scores` and `dvc metrics` for plots). It is more appealing for an individual ML engineer, not a team collaboration.
3. No "prioritization", just distinguish the commands `dvc scores` and `dvc plots` WITHOUT `dvc metrics`. Or `dvc metrics score\plot` as @jorgeorpinel mentioned.

Given the nature of DVC, it makes sense to emphasizes the team collaboration scenario over the others and keep the names as is.

I need to make another iteration on metrics docs. I'll start with this assumption and I should have more context on how it goes.

> try to handle its type in a "lazy way" that is the moment user tries to interact with it. For example, throw an error with a proper message when trying to `plot` scalar, or `metrics diff` values array/ csv.

@pared Sure. We should do that anyway, no matter what naming decision we choose.

> should we try to make all the functionality part of the `dvc metrics` and detect types automatically? Or we should indeed have two commands `dvc metrics` and `dvc plot`?

@shcheklein we should use two separate commands. With one command we introduce even more confusion for users. There are many cases when you cannot confidently say if this is a wrong file type or just an error in the file.

**Comment by shcheklein** [comment]
@dmpetrov 👍 can we clarify how `dvc run` and `dvc.yaml` entries look like in this case?

**Comment by dmpetrov** [comment]
>  can we clarify how `dvc run` and `dvc.yaml` entries look like in this case?

```yaml
tages:
  train:
    cmd: python train.py
    metrics:
    - summary.json:
        cache:false          # have we made a decision on how to define `-M`
    plots:
    - logs.csv:
         cache: false
    - auc.csv
```

The only issue with this naming - `-p`/`-P` in `dvc run` is busy by params. We have to use something like `-l/-L` for pLots.

**Comment by shcheklein** [comment]
Looks fine to me 👍  not perfect though ... `dvc plot` sounds like a verb/action to me that you do on _metrics_, and `plots` entry looks strange. And a separate `-l` - not sure I like it. We'll have to use some term in docs to distinguish `-m` and `-l`.

> # have we made a decision on how to define `-M`

I think cache: false should be default for metrics - so just skip it? not sure about `-l`.

A crazy idea -become opinionated? Like with params  - come up with default fine name for both types of metrics? This way we can at least simplify `dvc.yaml` and potentially `dvc run` significantly. (and if you need to make some output a metric you would need to add a boolean flag in the `outs` section).

`dvc run -O scores.json`
`dvc run -O metrics.json`

and yaml as simple as:

```yaml
stages:
  train:
  cmd:...
  outs:
  - metrics.json
  - scores.json
```

**Comment by dmpetrov** [comment]
> I think cache: false should be default for metrics - so just skip it? not sure about `-l`.

Let's use the same default for all types of outputs. I really don't want to keep in my head when it is false and when it is true by default :)

> A crazy idea -become opinionated? Like with params - come up with default fine name for both types of metrics?

@shcheklein it is a good idea. However, it prevents us from having multiple metrics files or changes the metrics file names. We can easily solve this problem by introducing `metrics` in `dvc.yaml` with `metrics: metrics.json` by default (the same for plots).

In a simple case, the user just writes metrics to `metrics.json`. For more advance scenario, user chooses to introduce `metrics: [metrics.json, output/mymetrics.yaml]` in `dvc.yaml` or calls the command with the explicit file name `dvc metrics diff --target output/mymetrics.yaml`.

The same for plots. You can even specify a template in `dvc.yaml`.

What do you think folks?

**Comment by shcheklein** [comment]
> For more advance scenario, user chooses to introduce metrics: [metrics.json, output/mymetrics.yaml]

Alternatively (to avoid names duplication) you we can use the same trick as we do now for `cache: false|true` - make it an output parameter.

**Comment by jorgeorpinel** [comment]
> dvc plot sounds like a verb

Agree. If we keep `dvc metrics ...` (plural) let's consider using `dvc plots ...` instead? Consistency

> not sure about -l

Yes this one is tricky but -p is taken for --plot. So keeping -m for both types is out of the question? (autodetection) TBH I didn't quite understand why that was not impossible. Maybe something like `-m scalar:auc.txt` and `-m plot:classes.json`? (`[scalar:]` could be the default).
Another alternativeL Changing `dvc plot` to `dvc graphs` and use -g in run.

> A crazy idea -become opinionated? Like with params - come up with default fine name for both types of metrics

But what is the pipeline uses some compiled tool that outputs a CSV,JSON,etc file with a name you can't control, and you just want to mark that output as a metric? You could add a helper stage to rename it and mark it as metric but what if it outputs several files you want as metrics, like Dmitry mentioned? It's not a crazy idea but seems limiting.

> We can easily solve this problem by introducing metrics in dvc.yaml
> ...or calls the command with the explicit file name dvc metrics diff --target output/mymetrics.yaml

OK so no need for the -m or -l/g options in `dvc run`? This one is intriguing... Need to think about the implications 🧠

**Comment by dmpetrov** [comment]
> > We can easily solve this problem by introducing metrics in dvc.yaml
> > ...or calls the command with the explicit file name dvc metrics diff --target output/mymetrics.yaml
> 
> OK so no need for the -m or -l/g options in `dvc run`? This one is intriguing... Need to think about the implications 🧠

I've spent some time on 🧠 :) I think, it won't be easy to work with the default metrics and plots files since in many cases user have multiple of theses, in contrast to params\config file. Also, I've seen metrics files under directories in many cases. So, I'd prefer to specify these files directly with `-m`, `-l/-g` options.

```yaml
stages:
  train:
    cmd: python train.py
    metrics:
    - summary.json:
        cache:false
    plots:
    - logs.csv:
         cache: false
    - auc.csv
```

Alternatively, we can use all as outputs and metrics\plot flag:
```yaml
    outs:
    - summary.json:
        metrics: true
        cache:false
    - logs.csv:
         plots: true
         cache: false
    - auc.csv:
         plots: true
```

> Changing `dvc plot` to `dvc graphs` and use -g in run.

This is a good idea. We should seriously consider this.

**Comment by dmpetrov** [comment]
It seems like we agreed on most of the items and can finalize the scalar and continuous metrics change.

ToDo:
- [ ] Introduce `plots` in `dvc.yaml` and `-l`/`-L` option in `dvc run`. (we need to decide on `graphs`/`-g` during the process - not a blocker)
- [ ] Replace `metrics_no_cache` by flag `cache: false`. The same for plots.
- [ ] `dvc metrics diff` should take the default target files from `dvc.yaml`
- [ ] `dvc plot diff` should plot all the plot files by default the same way as metrics diff does (same for `plot show` if we meet it - see below). 
- [ ] (Nice to have) Generate a single output file if there are many plots in `dvc.yaml`.

To discuss (we should decide after the first iteration is implemented):
- [ ] Replace `metrics` and `plots`/`graph` in `dvc.yaml` by flag `metrics: true` and `plot: true`.
- [ ] Consider moving `dvc plot diff` under metrics umbrella `dvc metrics plot` (no `diff`) and deprecating `dvc metrics show` since it does the same thing as diff.

**Comment by jorgeorpinel** [comment]
> Alternatively, we can use all as outputs and metrics\plot flag

On this I think maybe not because metrics/plot support files tracked by Git (not outputs).

Nice to-do list! Please note there's a corresponding docs issue here: https://github.com/iterative/dvc.org/issues/1175 — it's checkbox list may need updating.

**Comment by efiop** [comment]
> To discuss (we should decide after the first iteration is implemented):
> Consider renaming plot to plots

Kinda jumped the gun here https://github.com/iterative/dvc/pull/3802 , but it hurts my OCD and will simplify the new commands and terminology for the rest of the points.

**Comment by dmpetrov** [comment]
Should we close this issue? It looks like everything is already implemented (probably except xpath/filer) - but it s fine for now.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/3945
