### ISSUE TITLE
list: behavior in no-scm projects

### ISSUE THREAD

**Issue by pared** [iterative/dvc#3417]
Upon running:
`dvc list .`
inside my home directory, I get following output:
```
ERROR: failed to list '.' - Failed to clone repo '.' to '/tmp/tmpwy4abbuldvc-clone': Cmd('git') failed due to: exit code(128)
  cmdline: git clone --no-single-branch -v . /tmp/tmpwy4abbuldvc-clone
  stderr: 'fatal: repository '.' does not exist
'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

Shouldn't this message be simpler, like `. is not an Git nor DVC repositroy`?

**Comment by jorgeorpinel** [comment]
➕1 to improving this error message to something more friendly like `` `dvc list` can only list contents of Git-tracked DVC repos.`` (note that it doesn't support git-tracked no-scm DVC repos).

**Comment by jorgeorpinel** [comment]
Lol sorry I meant just "doesn't support no-scm DVC repos" 😋

**Comment by jorgeorpinel** [comment]
*projects
... 😒
