### ISSUE TITLE
repro: unexpected behavior 

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#3419]
```
(.env) [ivan@ivan ~/Projects/example-get-started]$ dvc repro evaluate.dvc
WARNING: Output 'data/features' of 'featurize.dvc' changed because it is 'modified'
WARNING: Stage 'featurize.dvc' changed.
Running command:
	python src/featurization.py data/prepared data/features
Output 'data/features' didn't change. Skipping saving.
WARNING: Output 'model.pkl' of 'train.dvc' changed because it is 'modified'
WARNING: Stage 'train.dvc' changed.
Running command:
	python src/train.py data/features model.pkl
Output 'model.pkl' didn't change. Skipping saving.

To track the changes with git, run:

	git add train.dvc featurize.dvc
```

**Comment by shcheklein** [comment]
Closing, mostly problem with a confusing repro output. Let's keep for the future.

**Comment by dmpetrov** [comment]
@shcheklein It would be really great if you could specify what part is unexpected.

Issues that I see:
1. Double warning messages (modified output and then modified stage). The second message is not needed (included in the 1st one).
2. It should not be a warning - regular DVC behavior. Just an output (not INFO either).

Anything else?

**Comment by shcheklein** [comment]
@dmpetrov it looks like I forgot I wrote that I'm closing this but forgot to actually close this. As far as I remember it looked to me that it was running something that it's not supposed to run - but turned out I was wrong. So, my intention was to close this and eventually create UI tickets when we get to repro.
