### ISSUE TITLE
dvc: option/param consistency

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3422]
One thing I think we should not do as Git is to have inconsistent options (and API parameters) (e.g. `git branch -D` vs. `git remote remove`). Better consistency in command/subcommand usage decrease the learning curve and makes for an enjoyable CLI (`heroku` is a good example).

Here's the ones I've found after briefly checking all refs:

- `add/run/import -f` (DVC-file name) `checkout/init/etc -f` (force)
- `get-url/import-url [out]` vs. `get/import --out` vs `move dst`
- `gc --projects REPOS` – is it project or repo?
- `add targets`, `metric diffs --targets` vs. `metrics ...  path` (or `path` API param)
   UPDATE: and now `list url target`? See https://github.com/iterative/dvc/issues/3381#issuecomment-594231471
- `--show-json` vs `--show-hash/--show-url` (different meaning of "show")
- `--show-json` vs `--ascii`
- Order of standard -hqv options in help output. Usually they're shown first as `[-h] [-q | -v]` but not always, for example `remote ... [-h] [--global] [--system] [--local] [-q | -v]`
- `config name [value]` vs `dvc remote modify name option [value]`
- maybe `remove -p` (purge) vs `repro -p` (pipeline)

This may seem like a polishing thing but I think it's actually best to address sooner than later, before too many users learn the existing options which makes it harder to change them. In any case, renamed options should be left hidden for some time, for legacy/scripting support.

---

Other misc. comments:
- `repro --pull` is specific to the run-cache.
  Should it be `--pull-run-cache`? See https://github.com/iterative/dvc.org/pull/2242#pullrequestreview-611662116 (also rel #4742)

**Comment by jorgeorpinel** [comment]
This issue needs an update... See also https://github.com/iterative/dvc/issues/5413#issuecomment-785251510

**Comment by efiop** [comment]
Closing as stale.
