### ISSUE TITLE
Warn users when traversing special directories, recommend to ignore 

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3436]
Currently, we ignore `.dvc`, `.git` and `.hg` directories by default. Still, we might be traversing through other special directories such as: `node_modules`, `.venv/venv/env`, `__pycache__`, `dist/eggs/wheels`, `htmlcov`, `docs`, `.mypy_cache`, `.pytest_cache`, etc.

We could throw warning if the users have not ignored these kind of directories and recommend them to add to `.dvcignore`. We could start with a small set of such directories.

### Context:

> Exactly. There can be tons of special/hidden dirs you don't want DVC to traverse (.idea/ .project/ 
> .env/ .ds_store/ venv/), and you can just add them to .gitignore or .dvcignore. Why are we secretly
> integrating with Mercurial if we don't actually support it? What if someone wants to version a .hg 
> dir? (edge case I know)
>
> It just seems very arbitrary to me, but OK maybe I'm missing something...

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc/pull/3257#discussion_r385515891_

**Comment by shcheklein** [comment]
@skshetry please, consider adding a link to the discussion - I think it can be valuable.
