### ISSUE TITLE
dvc metrics diff error if rev is not still tracked

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc#3437]
If you try to do ```dvc metrics diff``` with a_rev not yet tracked by dvc it warns you that the metric files can not be found and then unexpected error. 

Example
```
dvc metrics diff HEAD~1 HEAD
```
where HEAD~1 is not still tracked by dvc

I would expect to see an empty old, new with the current experiment and diff 0.

**Please provide information about your setup**
dvc 0.87.0
Python 3.6.9
ubuntu 10.04

**Comment by DavidGOrtega** [comment]
duplicated https://github.com/iterative/dvc/issues/3469

**Comment by shcheklein** [comment]
are sure this is a duplicate? It might be they have the root, but potentially different use cases - one - metric it tracked, but there is no value, second rev is not tracked at all. I would test both scenarios even if they have the root as a cause.

**Comment by shcheklein** [comment]
Feel free to close again if they are indeed the same. Or may be we can create checkboxes in one of the tickets?

**Comment by DavidGOrtega** [comment]
I understood that checkbox 1 in #3469 covered this:
> Handle metrics diff based on one version only

**Comment by shcheklein** [comment]
Yep, may be add a comment or edit that description to clarify? Closing this.
