### ISSUE TITLE
import: git sparse-checkout

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#3438]
`dvc import https://some/git/repo/ some_file` should probably do a sparse checkout.

Currently looks like it does a full clone:

https://github.com/iterative/dvc/blob/05cc023164766fbbec91642d7d8af513c8d4079b/dvc/stage.py#L941 would call https://github.com/iterative/dvc/blob/05cc023164766fbbec91642d7d8af513c8d4079b/dvc/dependency/repo.py#L73-L81

On a related note, is the repo locally cached by default https://github.com/iterative/dvc/blob/05cc023164766fbbec91642d7d8af513c8d4079b/dvc/dependency/repo.py#L78-L79 so that `dvc update` won't re-clone?

**Comment by efiop** [comment]
Related to https://github.com/iterative/dvc/issues/3473

**Comment by Suor** [comment]
Local caches only used within one dvc execution or one python session. 

Sparse checkout or at least shallow checkouts might be used, this will complicate out `external_repo()` abstraction, including its caching. But looks like there is no way around.

**Comment by casperdcl** [comment]
I think we had a discussion with @efiop and @shcheklein about which is more important to fix first (persistent repo cache or sparse checkout) and there was no clear outcome. Will open a new issue for persistent repo cache...

**Comment by skshetry** [comment]
We don't have a persistent repo checkout, but we do shallow clone these days. Closing...
