### ISSUE TITLE
dvc remote upload get stuck at 100%

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc#3440]
Sometimes dvc gets stuck at 100% without ending properly

```
root@da5d7363f7bc:/code/dvc-mnist-v1# dvc push
WARNING: Output 'models'(Stage: 'train.dvc') is missing version info. Cache for it will not be collected. Use `dvc repro` to get your pipeline up to date.
You can also use `dvc commit train.dvc` to associate existing 'models' with 'train.dvc'.
100% data/mnist_test.csv|#####################################################################################|17.4M/17.4M [42:53<00:00,    2.98kB/s]
100%|##########|data/mnist_train.csv                                                                             104M/104M [37:09<00:00,    8.51kB/s]
```

Of course dvc pull fails. There is no data.
```
Pulling from Dvc remote ...
Failed pulling from Dvc remote
Running dvc repro eval.dvc
##[error]Command failed: dvc repro eval.dvc
WARNING: Output 'data' of 'data.dvc' changed because it is 'not in cache'
WARNING: Stage 'data.dvc' changed.
ERROR: failed to reproduce 'data.dvc': missing data 'source': data
```

**Please provide information about your setup**
dvc 0.87.0
Python 3.6.9
ubuntu 10.04

**Comment by shcheklein** [comment]
@DavidGOrtega could you interrupt it to see how does the stack trace look like? Is there an easy way to reproduce for us?

**Comment by DavidGOrtega** [comment]
I interrupted it with ctrl-c.
I saw the stack trace but I could not see nothing interesting unfortunately I did not recorded it.
Im unable to reproduce it again also, sorry.

**Comment by shcheklein** [comment]
@DavidGOrtega closing this for now then. Please share more info if you see it again and can share the stack trace at least. Other information would be great to see as well - what remote type did you use for example.
