### ISSUE TITLE
Implement a way to pass remote settings to commands like `add/run`

### ISSUE THREAD

**Issue by pared** [iterative/dvc#3441]
Context:
https://discordapp.com/channels/485586884165107732/563406153334128681/684696237810647051

When initializing the output [here](https://github.com/iterative/dvc/blob/abc4e3c2d0c8d09a2f04db88e6bf0b331ca166bc/dvc/output/__init__.py#L85), (during `dvc add` for example) we cannot specify `remote`. It is fine as long as we work with `aws` buckets.

In this case, user has MinIO set up locally.
1. There is s3 bucket `s3://cache` in `endpoint-url`: `localhost:9000`.
Cache set up can be achieved with `dvc remote modify myremote endpointurl`
2. User has another bucket that contains data, lets say `s3://data/file` also on this MinIO.

3. User cannot `dvc add s3://data/file` because there is no way to specify that we want dvc to handle bucket under our own `endpoint-url`.

I tried tinkering with `aws` cli tool, hoping there will be some way to set up default endpoint and stumbled upon this issue:
https://github.com/aws/aws-cli/issues/1270

there is some workaround, but I wonder whether it would not be better for us to provide a way to handle it.

**Comment by efiop** [comment]
@pared How about `dvc remote add mys3 ...` + `dvc remote modify` + `dvc add remote://path`?

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc.org/issues/108

**Comment by efiop** [comment]
For the record:
if user has
```
[cache]
    s3 = s3cache
[core]
    remote = logs
['remote "s3cache"']
    url = s3://dvc-storage
    endpointurl = http://localhost:9000/
    use_ssl = False
['remote "logs"']
    url = s3://logs
    endpointurl = http://localhost:9000/
    use_ssl = False
```
then the command should be `dvc add remote://logs/shapes_128_128_20180914T1515`

**Comment by pared** [comment]
Fr the record, setting up remote seems to solve the problem, though we have another one:
When I set up MinIO locally with 2 buckets : `dvc-cache` and `data`, where data contains `file` and try to run:
```
#!/bin/bash

rm -rf repo
mkdir repo

pushd repo
git init --quiet
dvc init -q

export AWS_ACCESS_KEY_ID="minioadmin"
export AWS_SECRET_ACCESS_KEY="minioadmin"  

dvc remote add s3cache s3://dvc-cache/cache
dvc config cache.s3 s3cache
dvc remote modify s3cache endpointurl http://localhost:9000
dvc remote modify s3cache use_ssl False

dvc remote add miniodata s3://data
dvc remote modify miniodata endpointurl http://localhost:9000
dvc remote modify miniodata use_ssl False

dvc add remote://miniodata/file
```

adding fails with:

```
ERROR: ETag mismatch detected when copying file to cache! (expected:
 '4e102ec8d6ab714aae04d9e3c7b4c190-1', actual: 'ca9e5ed43f3fbee6edec
bb5ac6fba77e-1')
```

**Comment by efiop** [comment]
@pared Should we create a separate issue for that?

**Comment by pared** [comment]
@efiop I believe this problem has been already noticed by @mroutis:
https://github.com/iterative/dvc/issues/2629#issuecomment-544746872
But since #2629 is about default MinIO ETag, i will create issue.
