### ISSUE TITLE
endpointurl for remote using S3 API compatible storage not working

### ISSUE THREAD

**Issue by deatinor** [iterative/dvc#3442]
Hello,

I'm having some problems setting the `endpointurl` for an s3 API compatible remote.
My config is the following:
```
[core]
    remote = s3remote
['remote "s3remote"']
    url = s3://<bucket_name>/
    endpointurl = https://sos-ch-dk-2.exo.io
```
I get this error message while running `dvc push`:
```
ERROR: unexpected error - Could not connect to the endpoint URL: "https://s3.ch-gva-2.amazonaws.com/<bucket_name>/a3/04afb96060aad90176268345e10355"
```
It looks like it is not using the endpointurl provided, but the AWS default one.
I tried to set credentials both via `~/.aws/config` and environment variables, but it gives the same errors.

Thanks for your help!

DVC version: 0.87.0
Platform: Unix
Installation method: pip

**Comment by pared** [comment]
@deatinor 
What command are you trying to use?

**Comment by deatinor** [comment]
Yes, sorry: `dvc push`

**Comment by shcheklein** [comment]
@deatinor what about your environment variables, could you check those please? 

Could you determine where does `https://s3.ch-gva-2.amazonaws.com/` come from?

**Comment by deatinor** [comment]
I fixed my problem. I used the wrong `endpointurl`, the right one was `https://sos-ch-gva-2.exo.io` in my case. 

Still, I think it is pretty weird that it automatically redirects to the `AWS` url. I'm not familiar with the code base. Let me know if you want to investigate this further or I can close the issue.

**Comment by pared** [comment]
@deatinor 
So do I get it right:
1. You misspelled endpointurl
2. Instead of throwing something like `No such url`/ `403` we silently ommited the error and tried to request default amazon?

If so, then I would say it is a bug.

**Comment by deatinor** [comment]
Yes, that is the situation. 
Just to provide more information, here is my `.aws/config` file:

    [default]
    aws_access_key_id = <access_key>
    aws_secret_access_key = <secret_key>

Also, one thing very weird is the following:

- the mispelled endpointurl was `https://sos-ch-dk-2.exo.io`
- the redirection to amazon was made to `https://s3.ch-gva-2.amazonaws.com/` which contains `ch-gva-2` which is the right region

I really can't figure it out why it got the right region.

**Comment by pared** [comment]
@deatinor Can you check your aws cli config?
`cat ~/.aws/config`, I suppose the region will be set there.

**Comment by deatinor** [comment]
I think I detected a potential problem. So, first of all no region is set in the system, but:

- putting a random `endpointurl` the error message is correct
- it tries to connect to Amazon and changes the url only if I put this: `https://sos-ch-dk-2.exo.io`. `ch-dk-2` is another region in the cluster (not the right one). 

So maybe what happens is that for some reason he is able to get into the cluster and infer the right reason, but then it switches back to Amazon

**Comment by efiop** [comment]
This is what boto3 does internally when you use a valid but incorrect endpoint, not much we can do about this on our side. Closing for now.

**Comment by pmrowla** [comment]
@SeropB how are you configuring `endpointurl` for use with `dvc get-url`? Also, can you please run `dvc doctor` and post the output

**Comment by okoko-cs** [comment]
I have the same problem, I can do` dvc push `and `dvc push` on my s3 storage. But when I try `dvc list-url s3://bucket-name/test` command I get an error 
`unexpected error - Could not connect to the endpoint URL: https://<buckect-name>.s3.sbg.amazonaws.com/`
I configured the endpoint url on a OVH s3 server but the amazon ending is added to the url in the error is super weird. 
```
[core]
    remote = storage
['remote "storage"']
    url = s3://<buckect-name>/test
    endpointurl = https://s3.sbg.perf.cloud.ovh.net
```
dvc doctor output: 

```
DVC version: 3.50.2 (pip)
-------------------------
Platform: Python 3.9.13 on Linux-5.15.0-105-generic-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 3.15.1
        dvc_objects = 5.0.0
        dvc_render = 1.0.1
        dvc_task = 0.3.0
        scmrepo = 3.3.3
Supports:
        http (aiohttp = 3.9.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.9.3, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2024.3.1, boto3 = 1.34.69)
Config:
        Global: /home/user/.config/dvc
        System: /etc/xdg/xdg-ubuntu/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/....
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/.....
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/.....
```
