### ISSUE TITLE
forbid using subrepo as a target

### ISSUE THREAD

**Issue by pared** [iterative/dvc#3444]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

After introducing support for multiple DVC roots in #3257, in case of following setup:
```
.
├── .dvc
├── .git
└── subrepo
    ├── data
    ├── data.dvc
    ├── .dvc
    └── .gitignore
```
Running command `dvc push/pull/fetch subrepo/data.dvc` will have some unexpected results.
Eg. push will push to remote stored in parent repo. 
The reason for that is that we are not resolving Repo basing on `target`, but `cwd`. 
To solve this, we should either forbid initializing `Repo` under other `Repo`, or implement dynamic resolving of target paths. 
Other commands that need to be checked for this issue:
`destroy`, `remove`, `move`, `repro`, `status`, `import`, `get`, `root`, `update`, `pipeline`.

As simply forbidding seems like easier way, we will probably need to solve this problem anyway, to support `import` and  `get`.

Related to https://github.com/iterative/dvc.org/pull/1022

**Comment by efiop** [comment]
Ok, so discussed with @pmrowla and @pared that it makes sense to forbid it. If someone asks for this in the future, we could introduce `--subrepos` or smth like that for push/pull/etc.

**Comment by efiop** [comment]
The reason it does't throw an error right now is https://github.com/iterative/dvc/blob/1.0.0a1/dvc/repo/__init__.py#L210 . It opens dvcfile directly without consulting with the clean tree.
