### ISSUE TITLE
Support for storing large files as blobs (to reduce duplication of chunks)

### ISSUE THREAD

**Issue by dldx** [iterative/dvc#3445]
In some instances, it is necessary to store large text (eg. CSV) or binary (eg. HDF5) files which are appended to over time. This means that versioning quickly becomes impractical as DVC treats each small addition as a completely new file and stores them independently.

A better system would be to store larger files as a collection of blobs (and therefore dvc metadata would save a collection of md5 hashes corresponding to each blob). By using a collection rather than a single blob, the majority of the file is not duplicated every time a new change is made, thus saving a significant amount of space.

**Comment by shcheklein** [comment]
Related #829 ?

**Comment by dldx** [comment]
Yes, it's the same issue. I'll comment there instead.
