### ISSUE TITLE
pip install dvc[all|gs] failing

### ISSUE THREAD

**Issue by cyberbeast** [iterative/dvc#3447]
When running `pip install dvc[gs]`, I am running into the following error.

```
Collecting gitdb>=4.0.1 (from gitdb2>=2.0.6->dvc[all])
  ERROR: Could not find a version that satisfies the requirement gitdb>=4.0.1 (from gitdb2>=2.0.6->dvc[all]) (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4)
ERROR: No matching distribution found for gitdb>=4.0.1 (from gitdb2>=2.0.6->dvc[all])`
```

Any recommendations on how to fix this?

**Comment by shcheklein** [comment]
@cyberbeast hi! what operating system, environment do you use? Could also share the full `pip install -v dvc[gs]`, please?

**Comment by cyberbeast** [comment]
Hi @shcheklein,
OS - Debian

The output for `pip install -v dvc[gs]` is too long for a github comment. I've hosted the output  [here](https://paste.ubuntu.com/p/tmHzGgg9Ms/).

**Comment by shcheklein** [comment]
@cyberbeast it looks like you are using Python 2, we don't support it anymore.

I would recommend two options: 

1. snap - it's the best option to install DVC on Ubuntu https://dvc.org/doc/install/linux#install-with-snap if you don't need to use `import dvc.api` and only run DVC from CLI.
2. use conda - https://dvc.org/doc/install/linux#install-with-conda
3. use pip with virtualenv or https://packaging.python.org/guides/installing-stand-alone-command-line-tools/ 

```
virtualenv -p python3 .env
source .env/bin/activate
pip install dvc[gs]
```

let me know if that helped you.

**Comment by cyberbeast** [comment]
@shcheklein Thank you for that. Installing with a `python3` environment worked like a charm. Thank you so much. :)
