### ISSUE TITLE
s3 and compatible: add a config option to support validate_certs

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#3450]
Similar to use_ssl, we should probably provide a config for this.

More context here - https://discordapp.com/channels/485586884165107732/485596304961962003/685129104214851595

**Comment by skshetry** [comment]
We should provide this option, but it's better if user explicitly provided their custom certs via (`AWS_CA_BUNDLE`) (need to check though if it really works).

**Comment by shcheklein** [comment]
I think both options complement each other, don't see any contradiction. The same as boto probably supports both, as far as I understand. Do you have any specific concerns, @skshetry ?

**Comment by skshetry** [comment]
No. It's just that, when you are providing custom cert, it'll still be validated. But, if the validation is entirely disabled, you are trusting anything. So, providing custom certs is more secure.

Obviously, we should also support disabling validation of certs.

**Comment by charlesbaynham** [comment]
> 
> 
> We should provide this option, but it's better if user explicitly provided their custom certs via (`AWS_CA_BUNDLE`) (need to check though if it really works).

I can confirm that this does work, that's what I'm doing at the moment
