### ISSUE TITLE
'dvc get' is cloning the full bitbucket repo when only one branch is needed

### ISSUE THREAD

**Issue by anjapago** [iterative/dvc#3473]
DVC version : 0.82.2

When using `dvc get` to get data from a large bitbucket repository (with full command  `dvc get --rev branchname  https://.../gitrepo  data/data.csv`), this results in cloning the full git repository, even though only the one specified branch was needed. It would be preferable to be able to only clone the one specified branch.

**Comment by shcheklein** [comment]
hi, @anjapago , could you try to see this quick and dirty workaround helps:

pip install git+https://github.com/shcheklein/dvc@workaround-3473

(use it this way `dvc get --rev=feb20gem https://github.com/iterative/blog yarn.lock` - always specify `--rev`)

**Comment by shcheklein** [comment]
More context from the discussion. Full clone takes ~20min which makes commands like `dvc get`, `dvc list`, `dvc import` as well as `dvc.api` effectively unusable.

**Comment by casperdcl** [comment]
Right. Ping myself :)
