### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#3475]
DVC use to be optimized for running time. It looks like another round of optimization is needed.

Even simple command run in an empty repo takes about 1 second:

```
$ time dvc init -q

real	0m0.942s
user	0m0.576s
sys	0m0.307s

$ dvc add -q users.csv

real	0m1.274s
user	0m1.416s
sys	0m0.501s

dvc run -q -d users.csv -o model.pkl -o metrics.json 'sed -e '\''s/data/USERS data/'\'' users.csv > model.pkl; touch metrics.json'

real	0m1.371s
user	0m1.491s
sys	0m0.492s
```

**Comment by casperdcl** [comment]
Also

```
$ time dvc completion >/dev/null

real	0m0.898s
user	0m0.828s
sys	0m0.076s
```

which e.g. prevents recommending adding `eval "$(dvc completion -s bash)"` to `.bashrc`

**Comment by dmpetrov** [comment]
It seems like the start time degraded again:
```
$ time dvc --version
1.7.4+46bc89

real	0m1.013s
user	0m0.765s
sys	0m0.206s

```

**Comment by dmpetrov** [comment]
@iterative/engineering should we prioritize this?

**Comment by efiop** [comment]
@dmpetrov Not seeing the regression in https://iterative.github.io/dvc-bench/#startup.StartupBench.time_startup , nor able to reproduce.

I see that you are using a development version, which generates the version dynamically by calling git, which might be slower. Official packages don't do that, could you try one of those? E.g. pip.

**Comment by Suor** [comment]
@efiop bench you linked show 500ms, which is also slower than 200ms we had after working on startup time again.

**Comment by dmpetrov** [comment]
@efiop yes, the dev version can be slower but not like half a second slower :) All the commands take more than 1 sec which is very slow. Another example:

```
$ time dvc add file
...

real	0m1.701s
user	0m1.656s
sys	0m0.551s
```

**Comment by skshetry** [comment]
The startup time is [much better now](https://iterative.github.io/dvc-bench/#startup.StartupBench.time_startup) in the latest version.

Installed using:
```console
$ pip install -U git+https://github.com/iterative/dvc.git
```

```console
$ hyperfine --warmup 3  "dvc --version"
Benchmark #1: dvc --version
  Time (mean ± σ):     181.9 ms ±   2.4 ms    [User: 153.2 ms, System: 31.7 ms]
  Range (min … max):   178.5 ms … 188.6 ms    16 runs

$ hyperfine --warmup 3 "dvc completion > /dev/null"
Benchmark #1: dvc completion > /dev/null
  Time (mean ± σ):     259.8 ms ±   1.2 ms    [User: 226.0 ms, System: 36.6 ms]
  Range (min … max):   256.8 ms … 261.1 ms    11 runs

$ cd $(mktemp -d) && \
  hyperfine --warmup 3 --prepare "rm -rf .dvc .dvcignore && git init -q" \
  "dvc init"
Benchmark #1: dvc init
  Time (mean ± σ):     305.1 ms ±   1.3 ms    [User: 268.6 ms, System: 38.5 ms]
  Range (min … max):   303.3 ms … 306.9 ms    10 runs

$ cd $(mktemp -d) && \
  hyperfine --warmup 3 --prepare "rm -rf .dvc*" \
  "dvc init --no-scm"
Benchmark #1: dvc init --no-scm
  Time (mean ± σ):     254.1 ms ±   1.3 ms    [User: 222.7 ms, System: 34.2 ms]
  Range (min … max):   252.6 ms … 257.1 ms    11 runs

$ cd "$(mktemp -d)" && git init -q && dvc init -q &&
  hyperfine --prepare  "rm -rf .dvc/cache foo*; echo foo>foo" \
  "dvc add foo"
Benchmark #1: dvc add foo
  Time (mean ± σ):     466.8 ms ±   3.3 ms    [User: 419.8 ms, System: 48.1 ms]
  Range (min … max):   459.2 ms … 470.3 ms    10 runs
```

@dmpetrov, let me know if this good for now. Thanks.

**Comment by shcheklein** [comment]
Great stuff ❤️ !

<img width="1200" alt="Screen Shot 2021-01-08 at 10 59 00 AM" src="https://user-images.githubusercontent.com/3659196/104054518-20b1b100-51a2-11eb-8cf6-1e9957558258.png">
