### ISSUE TITLE
gc: --cloud with multiple git repositories referencing the same dvc remote

### ISSUE THREAD

**Issue by macieksk** [iterative/dvc#3476]
Hi, I have a multpile git repositories with dvc files in them, all referencing the same dvc remote (for simplicity, and possible same file reusage).

Is there any way I can safely use `dvc gc --cloud` that would clean old version of files from one git repository *only* and leave files kept in other git repositories safely unchanged?

This could be done per file, or per directory: `dvc gc --cloud dir` could clean all files that where ever kept in `dir` except for those who are present in current/selected brach.

Thanks, Maciek

**Comment by shcheklein** [comment]
hi @macieksk ! It should be possible yes, but I need to ask you a question first.

> clean old version of files from one git repository

how do you determine this in your use case. What files are old and what are new in this single repo?

**Comment by macieksk** [comment]
hi @shcheklein , the usual use case is: I replace a set of very large files in a folder with newer versions of these files, I `dvc add`, `dvc commit`, `dvc push` it. Then I `git commit` new `.dvc` files. I may be keeping an old git branch with previous `.dvc` files for some purposes. After some time I'd like to garbage collect from dvc repo *all old files that were ever committed (through their `.dvc` files) in this git repo within this folder, except from files which (`.dvc` of) are present in a currently checked out branch, and possibly any other branch I pass at the command line.*. 

This way garbage collection is limited only to files, that have ever resided within this directory, within this git repo. Cases of `git mv` from within this folder outside of it in the past commit history would need special handling: possibly one good solution is to check for every such file (`.dvc` of) if it's still present *anywhere else* in the repo in the current and selected branches. Are there any other dubious situations?

**Comment by macieksk** [comment]
I currently do not check out same file in two different repos, but if I would, this would be another use case to handle: `dvc gc` would need to accept a set of tuples `path_to_git_repository/folder@branch` to protect. Or better: just a list of git repositories files from which are always protected (irrespective of folders and branches); these mutliple-repositories files could be just listed to console so user can delete them himself.

**Comment by shcheklein** [comment]
Thanks for clarifying this @macieksk .

We definitely need to add a more granular support on the command line to pass specific commits, branches to keep, etc, e.g.:

- list of revisions to keep
- filters (branch names, tag names, commit messages)
- number of commits to keep

Good question is the support for multiple projects, how is it aligned with all these filtering options.

**The safest options for you right now is to:**

1. clone you main repo with `git clone --depth 1 --single-branch URL` 
2. in that clone fetch branche(s) that you want to keep the last commit for - again, use `--depth 1`
3. use `-p <paths>, --projects <paths>` from the https://dvc.org/doc/command-reference/gc and pass this cloned repo + all other repos. Use `--all-commits` + `-c`.

**If you are sure that your repos do not overlap in terms of data yet, you can simply do something like:**

`dvc gc -a -c` - it will keep only the latest commit for every branch

remove locally certain branches you don't need and run the same command if you want to be more "aggressive"

**Comment by macieksk** [comment]
Ah, so if I pass all my git repositories, which refer to the same dvc repo, with `-p`, and use option `--all-commits`, then files from these repos are going to be protected - yes, this is what I'm looking for, this wasn't entirely clear from the documentation.

One comment though: this is an *opt-out* from deletion solution. An *opt-in* feels safer when comes to deleting many files.

Thanks @shcheklein

**Comment by shcheklein** [comment]
> this wasn't entirely clear from the documentation.

any suggestions how to improve it? :) since you have a fresh perspective you are the best person to advice how to try to change it.

> One comment though: this is an opt-out from deletion solution. An opt-in feels safer when comes to deleting many files.

That's true! And we have been discussing to introduce opt-in `dvc remove` or `dvc clean` where you can specifically say _what_ to remove, instead of what to _keep_. Both approaches makes sense to my mind in certain scenarios. 

The interesting question in your case though that a regular `opt-in` is not enough, right? E.g. you would still need to specify a list of projects you want to make sure data is kept the way I understood your case?

**Comment by efiop** [comment]
Closing as stale.
