### ISSUE TITLE
Allow git hooks to be installed individually

### ISSUE THREAD

**Issue by fferegrino** [iterative/dvc#3479]
Currently `dvc install` tries to install all three hooks, it would be nice to allow them to be installed indivudually.

Why?

I am using `pre-commit` to manage other hooks and it breaks when I try to install the remaining ones. It seems that after https://github.com/iterative/dvc/issues/3271 gets implemented there will be better integration, but I am not sure it will solve the problem.

I tried searching for other, similar issue but I could not find any.

Thanks for the this awesome tool!

**Comment by efiop** [comment]
Hi @fferegrino !

> I am using pre-commit to manage other hooks and it breaks when I try to install the remaining ones. It seems that after #3271 gets implemented there will be better integration, but I am not sure it will solve the problem.

Looks like it should indeed solve it for you, as it won't break any of your existing hooks. We actually already have a PR for that: https://github.com/iterative/dvc/pull/3406 .

**Comment by fferegrino** [comment]
I'll keep an eye on that other issue. Thanks for the response!

**Comment by efiop** [comment]
@fferegrino It is actually merged and released already :) Give it a try and let us know how it goes. Docs: https://dvc.org/doc/command-reference/install#using-pre-commit-tool
