### ISSUE TITLE
checkout: --relink show helpful message on completion

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3484]
https://github.com/iterative/dvc/pull/3401 is merged. This introduced showing detailed checkout changes. If everything is relinked, but not changed (so, workspace is as it was before but everything was relinked), no output message is shown. We can at least show a message on `dvc checkout --relink`:
```sh
relinked successfully
```

**Comment by skshetry** [comment]
I have intentionally left another enhancement:

At the moment, we don't have any way to differentiate between modified and relinked, as we just don't know if anything was modified on the workspace during checkout. I'd wait for users to ask for this (will not be easy to implement).

**Comment by mtszkw** [comment]
Is this change still needed? This sounds like a perfect first issue to me @skshetry

**Comment by pared** [comment]
@mtszkw Yest it is still needed, would you be interested in that? Sorry for late replay.
