### ISSUE TITLE
pull/fetch: show how many files were downloaded

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3485]
https://github.com/iterative/dvc/pull/3401 is merged. This introduced showing changes during checkout. `pull` is a fetch + checkout, so, the output is a bit mixed. It'd be good to get statistics of what was downloaded during fetch or even better, what files were downloaded.

**Comment by xnutsive** [comment]
Yes please! 

I'm a new DVC user, working on a hobby app with a friend. I've pushed a few files, and then when the friend ran `dvc pull`, he just got a console output of `1 added`. 

`1 added` is not exactly friendly or clear on what happened (which is, one data object containing a bunch of files was added to the local dvc env, I guess).
