### ISSUE TITLE
update: add `-R, --recursive` flag

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#3511]
`dvc update -R/--recursive` should recursively find & update all DVC-files which are updateable (and be incompatible with `--rev`).

Allows replacing:
```
dvc update <long list of files> && dvc repro -P
```
with:
```
dvc update -R && dvc repro -P
```

**Comment by efiop** [comment]
Let's not take `-a`, as we use it for `--all-branches` in othe rplaces already. Let's just use `--all` for now.

**Comment by skshetry** [comment]
It'd be symmetrical with push/pull if we used `--recursive/-R` instead.

**Comment by nik123** [comment]
I'd like to implement it. May I?

**Comment by MD-key6** [comment]
في ثلاثاء، 5 مايو، 2020 في 1:05 م، كتب nik123 <notifications@github.com>:

**Comment by MD-key6** [comment]
p g
