### ISSUE TITLE
Implement `--no-exec` option for `import-url` command

### ISSUE THREAD

**Issue by anotherbugmaster** [iterative/dvc#3513]
`dvc import-url` creates new `.dvc` file, just as `dvc run`. Sometimes files which would be imported are already present locally and it's quite inconvenient that they should be downloaded again in order to create a pipeline step.

Because of that it would be great to add `--no-exec` option: we create pipeline step, then use `dvc commit` to update its md5 with already downloaded file.

**Comment by shcheklein** [comment]
Context: https://discordapp.com/channels/485586884165107732/485596304961962003/690194007816798243

**Comment by Eliska-0111** [comment]
taking a look

**Comment by jorgeorpinel** [comment]
I know this is kind of old! But another alternative is to create the import .dvc file manually. We've documented the spec better now so it should be doable: https://dvc.org/doc/user-guide/dvc-files-and-directories#dvc-files

That's assuming `commit` will calculate the eTag/MD5/checksum value...

p.s. we should probably have this option in regular `import` too for the same reasons and consistency (see #4567)

**Comment by anotherbugmaster** [comment]
@jorgeorpinel good point, that's exactly what I did as a workaround actually :)
