### ISSUE TITLE
api: support granularity (files inside dirs)

### ISSUE THREAD

**Issue by javierjsa** [iterative/dvc#3541]
Ubuntu 16.04. Virtualenv with python 3.5.2. Pip install. DVC version 0.90.2

I am unable  to retrieve a file with api.read, however what DVC is tracking is not the file itself, but the folder the file is in. The file can be retrieved sucessfully with dvc get.

This is the code snippet:

```
import dvc.api

if name == "main":

   modelpkl = dvc.api.read('relative/path/in/python/project/model.pb',
                           repo='ssh://git@repo.com/myproject.git',
                           remote='https://my-bucket.s3-us-west-2.amazonaws.com/folder_in_bucket_where_DVC_data_is, 
                           mode='rb')
```

This doesn't work either:

`dvc list ssh://git@repo.com/myproject.git relative/path/in/python/project/model.pb`

`relative/path/in/python/project/model.pb does not exist in the target repository neither as a DVC output nor as a Git-tracked file`

But this does:

`dvc get ssh://git@repo.com/myproject.git relative/path/in/python/project/model.pb`

Discord chat: https://discordapp.com/channels/485586884165107732/485596304961962003/692766090081730651

**Comment by pared** [comment]
Prerequisite is #3716

**Comment by efiop** [comment]
Will be automatically fixed by https://github.com/iterative/dvc/issues/3811
