### ISSUE TITLE
remote: upgrade Azure Blob storage version

### ISSUE THREAD

**Issue by trallard** [iterative/dvc#3546]
Hi!

At the moment `dvc[azure]` has as a requirement `azure = ["azure-storage-blob==2.1.0"]`

Recently there Python SDKs were massively improved to be more Pythonic and efficient. I was wondering if it would be possible to allow for the use of the latest version (12.1). Or if there are any blockers for this I can help with?

**Comment by shcheklein** [comment]
@trallard I don't expect any major blockers and we would really appreciate a help with this! Could try to bump it up and see if we can run tests (create a PR from a fork)?
