### ISSUE TITLE
push: improve err user output for gdrive remotes

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3553]
UPDATE: Jump to https://github.com/iterative/dvc/issues/3553#issuecomment-606348995

---
```console
λ dvc version
DVC version: 0.90.2
Python version: 3.7.5
Platform: Windows-10-10.0.18362-SP0
Binary: True
Package: exe
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache: reflink - not supported, hardlink - supported, symlink - not supported
Filesystem type (cache directory): ('NTFS', 'C:\\')
Filesystem type (workspace): ('NTFS', 'C:\\')

λ dvc init --no-scm
λ dvc remote add -d mygdroot gdrive://root
λ echo data > data
λ dvc add data
λ dvc push
ERROR: failed to push data to the cloud - Please specify Google Drive's client id and secret in DVC config. Learn more at <https://man.dvc.org/remote/modify>.
```

^ The error message should be more along these lines: `Please configure an authentication mechanism for Google Drive remote 'mygdroot'. Learn more at <https://man.dvc.org/remote/modify>.`

**Comment by shcheklein** [comment]
@jorgeorpinel you should not see this error, try the latest version.

**Comment by jorgeorpinel** [comment]
Still getting this message on DVC 0.91.1 (Win)

**Comment by shcheklein** [comment]
@jorgeorpinel how does you config look like? could you try dev version, it might be that we haven't released it yet

**Comment by jorgeorpinel** [comment]
```
[core]
    no_scm = True
    remote = mygdroot
['remote "mygdroot"']
    url = gdrive://root
```

Will try. Haven't even installed Python on this new Windows machine yet so it's a good opportunity ⏳

**Comment by shcheklein** [comment]
The latest version is 0.91.2 - that where it was released.

**Comment by jorgeorpinel** [comment]
I see. It's not released for Windows yet.

Still trying to install Python. Yep it takes a long time. Windows is really bad.

**Comment by shcheklein** [comment]
@jorgeorpinel probably we just forgot to update the link on the main page? cc @efiop

**Comment by jorgeorpinel** [comment]
I only see source code assets for the release: https://github.com/iterative/dvc/releases/tag/0.91.2

**Comment by jorgeorpinel** [comment]
OK I was able to try the dev version and I see this message is no longer there, now we have:

```console
λ dvc push
  0% Querying cache in gdrive://root|                                                                                 |0/1 [00:00<?,     ?file/s]C:\Users\poj12\dvc\.venv\lib\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access C:\Users\poj12\DVC-repos\test\.dvc\tmp\gdrive-user-credentials.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?...

Enter verification code: 
```

This works. But the whole first part
```
  0% Querying cache in gdrive://root|                                                                                 |0/1 [00:00<?,     ?file/s]C:\Users\poj12\dvc\.venv\lib\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access C:\Users\poj12\DVC-repos\test\.dvc\tmp\gdrive-user-credentials.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
```
seems unnecessary? Also is `.dvc/tmp/` really a temporary directory or is it just confusing naming? Thanks

**Comment by shcheklein** [comment]
> seems miss-formatted and unnecessary

yes! we have a checkbox for this. This is not DVC-generated. I'll get to it soon.

**Comment by shcheklein** [comment]
can we close this?

**Comment by jorgeorpinel** [comment]
Yes. Thanks!

p.s. should we worry about the 0.91.2 release not having binaries? See https://github.com/iterative/dvc/releases/tag/0.91.2 cc @efiop

**Comment by efiop** [comment]
Will update it soon, I'm just waiting to update brew package. After it is accepted, I'll update our links. It is the usual process, there might be an hour to a day or two delay between pip release and our links being updated. Could update download links earlier though, will look into it.

**Comment by jorgeorpinel** [comment]
No rush, sounds good. Thanks Ruslan!
