### ISSUE TITLE
ssh remote: Pass `ProxyCommand` to paramiko

### ISSUE THREAD

**Issue by gio8tisu** [iterative/dvc#3560]
If you want to set a ssh remote to a private server you should be able to do so by doing a proxy jump using the `ProxyCommand` option in your ssh config file, e.g:
```
Host <ON-PREMISES-SERVER>
        User <USER>
        ProxyCommand ssh -W %h:%p <PUBLIC-SERVER>

Host <PUBLIC-SERVER>
        HostName <PUBLIC-IP>
        User <USER>
        Port <PORT>
```
Currently the `ProxyCommand` is not passed to paramiko, so the on-premises server name is not found, e.g.:
```bash
$ dvc remote add -d <ON-PREMISES-SERVER> ssh://<ON-PREMISES-SERVER>/path/to/directory/
$ dvc push
ERROR: unexpected error - [Errno -2] Name or service not known
```

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/485596304961962003/694489311164235854

**Comment by shcheklein** [comment]
@gio8tisu @efiop thanks! please create a ticket or add docs PR?

**Comment by efiop** [comment]
@shcheklein There is no need for the docs PR, it is what should work out of the box. It is not configurable by users.

**Comment by shcheklein** [comment]
@efiop got it, thanks!
