### ISSUE TITLE
figshare integration ?

### ISSUE THREAD

**Issue by romainFr** [iterative/dvc#359]
Not so much an issue than a feature suggestion. Would there be an interest to interface the data storage part with [figshare](https://figshare.com) ? They have a pretty extensive [API doc](https://docs.figshare.com/). 
I'm very impressed with dvc, but for publication my institution has a very strong preference for putting the data on figshare -- and I think it's going to be true of a number of biology/physics/social science institutions.
Thanks for the great work anyway !

**Comment by dmpetrov** [comment]
Hi @romainFr 
Thank you very much for your kind words about DVC.
Figshare looks interesting. Is there any command line tool to download\upload files from this services except curl\wget?

**Comment by romainFr** [comment]
I don't think so. There's a small python client to access the API if that helps.

Since I'm on the data storage topic, one interesting option used in the biology/social science community is https://osf.io. The nice thing is that there is a command line tool that seems pretty straightforward : https://github.com/osfclient/osfclient that allow to access data from different sources (including figshare) linked to the user account.

**Comment by dmpetrov** [comment]
In the new DVC version, we exclude all data importing features. So, no `dvc import https://...` command anymore. DVC will work like Git or Git-LFS from data importing point of view:

```
$ wget https://.../file.tgz
$ dvc add file.tgz
```

Nevertheless, cloud storage synchronization stays in its place.
```
$ dvc push file.tgz
```

So, some command line tool is definitely needed for `figshare`. We can probably figure out how to get\push data to\from `figshare` by `curl` or `wget` command.

**Comment by efiop** [comment]
Looks like there is no interest from anyone in this. Closing as stale. Please feel free to reopen, if you'd like to introduce some activity.

**Comment by efiop** [comment]
For the record: if anyone would be interested in contributing figshare support, one would need to start at implementing fsspec-compatible figshare filesystem https://github.com/intake/filesystem_spec . DVC is on its way to supporting fsspec plugins, so we once figsharefs is implemented, you'll be able to use it with DVC.
