### ISSUE TITLE
Partially missing dir cache leads to no data at all after dvc pull 

### ISSUE THREAD

**Issue by zimka** [iterative/dvc#3596]
**Setup**
Fedora release 31, dvc version 0.91.1
**Description**
I have faced a situation when our dataset (directory with many video) cache was somehow not fully pushed to cloud (2 videos cache lost), which have led to inability to load anything from the dataset at all.
It would be nice to be able to checkout partial cache in such situation.
I have prepared a python script that reproduces this situation from scratch with local remote:

- creates git and dvc repo, creates local remote
- creates fake data dir with several files, adds dvc cache
- deletes some random piece of cache
- pushes data to local storage
- cleans cache

Expected behaviour after **dvc pull**: being able to pull at least some files
Actual behaviour after **dvc pull**: no data at all

So, to reproduce the error please run:
$ python  prepare_broken_partial_pull.py
$ dvc pull
[prepare_broken_partial_pull.zip](https://github.com/iterative/dvc/files/4434547/prepare_broken_partial_pull.zip)

**Comment by efiop** [comment]
@zimka In your reproduction script you delete `.dir` file, which contains all information about how the directory is structured, without which there is no way to partially restore your directory. This is expected behaviour. If you would be missing some cache files for cache files listed inside of that `.dir` - dvc will partially restore it.

**Comment by zimka** [comment]
As far as I understand there is one cache chunk for each file and one additional cache chunk per directory itself in .dvc/cache - therefore for 4 files there are 5 cache chunks at the step 3 .
One random cache chunk is deleted at step 4 (I am not sure how can I distinguish file-cache-chunk from dir-cache-chunk).
The deleted cache chunk can be either for file or for the whole directory - it can be seen from warning message, which is either:
```
WARNING: ... Missing cache files: 
name: data/3, md5: ...
```
or
```
WARNING: ... Missing cache files: 
name: data, md5: ...
```
However the behaviour of `dvc pull ` is the same in all cases - no data after execution.  
It is clear that there should be some cache chunks related to the whole directory which are critical for the whole dataset, but probably not all of them at the same time.
E.g if you set N_FILES var in the script as 400 - this would lead to the situation when cache for 399 files is available, and 1 is deleted, but still no data after `dvc pull`.

In my opinion such behaviour is not very reliable (if it is expected), because this mean that any single lost cache chunk for large dataset destroys the whole dataset, which is kinda sad.
Please correct me if I understand it wrong.
@efiop

**Comment by efiop** [comment]
@zimka Indeed, there is a regression that doesn't create the directory if some cache file is missing. Looking into it...

**Comment by efiop** [comment]
New checkout handles partial checkouts just fine.
