### ISSUE TITLE
progress: clear nested bars on `ThreadPool` exit

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#3597]
- don't clear nested bars when they finish (avoids blank space)
- manually clear `ncols` lines in `ThreadPoolExecutor.__exit__` (clean up bars at the end)
- from https://github.com/iterative/dvc/pull/3594#issuecomment-609492624
- continues #3583

**Comment by skshetry** [comment]
There are still issues with progressbars in DVC, but this issue feels stale at this point. I am closing this but feel free to reopen if you think otherwise.

**Comment by skshetry** [comment]
There are still issues with progressbars in DVC, but this issue feels stale at this point. I am closing this but feel free to reopen if you think otherwise.
