### ISSUE TITLE
dvc metrics add: should it dvc add untracked files?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3606]
I propose `dvc metrics add`, when used with an untracked file, automatically creates the orphan DVC-stage for it (calling `dvc add` under the hood) instead of

```console
λ dvc metrics add un-tracked.file
ERROR: failed to add metric file 'metric' - Unable to find DVC-file with output 'metric'
```

**Comment by efiop** [comment]
Oops, forgot to post the comment that this is going to happen after multistage dvcfile, as we will pretty much decouple metrics from the rest of the things. So you would be able to
```
metrics:
    - mymetrics.json
stages:
  ....
```
in your pipeline file.

**Comment by jorgeorpinel** [comment]
Sounds good. But is the multistage DVC-file change going to existing commands in a non-backward compatible way so that this request will become outdated? Otherwise maybe we should still considered doing this separately.

**Comment by efiop** [comment]
Yes, it will become outdated.
