### ISSUE TITLE
dvc: command to list file/dir versions/history

### ISSUE THREAD

**Issue by nabil-aitbaha** [iterative/dvc#3616]
Actually to see versions of a DVC file, we need to use "git log" but this command need to clone the repository before. So if I need to import a specific version of a dataset on an another project, I need to clone the entire repository.
A better way should to use a command like "dvc list --versions url".

**Comment by efiop** [comment]
For the record: would probably reconsider adding this to the `list` itself, feels like it doesn't belong there. Maybe we need a different command for such functionality.

**Comment by efiop** [comment]
For now `git log my.dvc` does the job. Discord context: https://discordapp.com/channels/485586884165107732/563406153334128681/697826620601532496

**Comment by tall-josh** [comment]
On a similar note, I've been doing the following. Say I have some Tensorboard logs I wish to track with dvc. That's great, but Tensorboard also allows you to specify many separate `logdirs` so you can visualize multiple runs at once. What I have been doing recently is generating a `history` directory that contains symlinks to files in `.dvc/cache`.

ie, If I had a directory structure like this:
```
myproject/
  artefacts/
    tf-logs/        # Track with dvc
    metrics/
      train.yaml    # Track file with dvc
      eval.taml     # Track file with dvc
```

Then assuming I have 2 git tags `run1` and `run2` with corresponding tracking information in `.dvc` files I generate a history dir:

```
history/
  artefacts/
    tf-logs/
      run1/    # Recreate directory structure of tf-log dir where the bottom 
               # of the tree consists of symlinks to files in `.dvc/cache` from
               # git tag `run1`
      run2/    # Same but for git tag `run2`
    metrics/
      train.yaml/
        run1   # Symlink to `.dvc/cache` file from `run1`
        run2   # Symlink to `.dvc/cache` file from `run2`
      eval.yaml/
        run1   # Symlink to `.dvc/cache` file from `run1`
        run2   # Symlink to `.dvc/cache` file from `run2`
```

I've been doing this with `git show $TAG --name-only | grep .dvc` and `git show $TAG:$DVCFILE`

**Comment by jums92** [comment]
@tall-josh  Yes it is a good idea thanks :+1:
