### ISSUE TITLE
repro -P seems to check status of dependancies too often

### ISSUE THREAD

**Issue by charlesbaynham** [iterative/dvc#3644]
DVC 0.91.0, Windows 10, pip

Description
========

Running `dvc repro -P` on a large graph seems to check all the early dependences once for each output, even if it has already been checked. 

In the following repo:

                            step1.dvc
                              |
             ----------------------------------------
             |            |            |            |           
     step2_A.dvc  step2_B.dvc  step2_C.dvc  step2_D.dvc

Where each of the step 2 stages depends on steps 1, I think that calling `dvc repro -P` results in 4x checks of the outputs of step1. 

I conclude this because, in my repo, I have several hundred stages in "step2" which all depend on a "step1" which is an import. When I run `dvc repro -P`, I get the

    WARNING: DVC-file 'xxx.dvc' is locked. Its dependencies are not going to be reproduced.

message several hundred times.

**Comment by charlesbaynham** [comment]
In Discord, @efiop suggested problem might be in 
https://github.com/iterative/dvc/blob/11e56dbdf921c6eacf603bcdcc2e7a46ac7a3b88/dvc/repo/reproduce.py#L78-L90

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/3645 . Kudos @charlesbaynham :1st_place_medal:
