### ISSUE TITLE
Support dvcignore for external dependencies.

### ISSUE THREAD

**Issue by benjamintanweihao** [iterative/dvc#3656]
Current `.dvcignore` doesn't seem to apply to external dependencies. Our current use case is that we have models and data as external dependencies stored on an NFS drive (the cache is also on NFS), and there are certain datasets in `/mnt/nfs/data` that we do not want to expose to DVC.

**Comment by jorgeorpinel** [comment]
External outputs are also not supported by .dvcignore .

**Comment by efiop** [comment]
Closing as stale.
