### ISSUE TITLE
Pipeline show for all a project

### ISSUE THREAD

**Issue by AmineBarrak** [iterative/dvc#3661]
I was wondering if there is a way to print all the pipeline for a project?
I found that we can find only a pipeline for a DVC file.

**Comment by efiop** [comment]
@AmineBarrak There is `dvc pipeline list` that will show all pipelines when ran without arguments.

**Comment by shcheklein** [comment]
For the record (a context from the conversation). `--dot` or `--ascii` do not show a full pipeline (only pipeline up to a give stage), so there is no ways to visualize a pipeline that has multiple leaf stages. As far as I understood, `pipeline list` format is not enough - a DAG visualization was required.

**Comment by AmineBarrak** [comment]
There is a need for printing all the pipeline and print all interaction in one graph.
As a solution for me I did the following:
`def get_nodes(dot_file, file):
	list_remove = []
	(graph,) = pydot.graph_from_dot_file(output_folder_dot)
		# print (graph.get_node_list())
	for n in graph.get_node_list():
		list_remove.append(n.get_name().strip('"'))

	if file in list_remove:
		list_remove.remove(file)

	return list_remove`
`def remove_subtree(l1, l2):
	l3 = [x for x in l1 if x not in l2]

	return l3`
`for file in list_dvc_files:
		print (file)
		# dvc pipeline show file --dot 
		p1 = subprocess.Popen(['dvc', 'pipeline', 'show', file, '--dot'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		p_status = p1.wait()
		match_f = p1.communicate()[0].decode("utf-8").strip()
		# print (match_f)
		with open(output_folder_dot, "w") as text_file:
			text_file.write(match_f)
		
		list_nodes_remove = get_nodes(output_folder_dot, file)
		
		list_dvc_files = remove_subtree(list_dvc_files, list_nodes_remove)`

**Comment by AmineBarrak** [comment]
```
for file in list_dvc_files:
		print (file)
		# dvc pipeline show file --dot 
		p1 = subprocess.Popen(['dvc', 'pipeline', 'show', file, '--dot'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		p_status = p1.wait()
		match_f = p1.communicate()[0].decode("utf-8").strip()
		# print (match_f)
		with open(output_folder_dot, "w") as text_file:
			text_file.write(match_f)
		
		list_nodes_remove = get_nodes(output_folder_dot, file)
		
		list_dvc_files = remove_subtree(list_dvc_files, list_nodes_remove)
```

**Comment by antonkulaga** [comment]
dvc pipeline list is somewhat misleading to me as it shows both stages and regular dvc files
