### ISSUE TITLE
publish conda package for python 3.8

### ISSUE THREAD

**Issue by antonkulaga** [iterative/dvc#3685]
Right now python 3.8 is default python=3 for conda/mamba packages, however dvc does not seem to be published for 3.8 (at least I do not see it in anaconda cloud and mamba does not resolve it under 3.8)

**Comment by efiop** [comment]
Hi @antonkulaga ! That's correct, we didn't publish 3.8 package for conda yet (https://github.com/conda-forge/dvc-feedstock/pull/109 waiting to resolve some issues), but you could install it through pip in the mean time. We will publish 3.8 likely this week.

**Comment by efiop** [comment]
Fixed by https://github.com/conda-forge/dvc-feedstock/pull/109 . @antonkulaga Please give it a try :slightly_smiling_face: Thanks for the feedback!
