### ISSUE TITLE
install: rename Windows package installation name

### ISSUE THREAD

**Issue by fabiosantoscode** [iterative/dvc#3687]
UPDATE: Jump to https://github.com/iterative/dvc/issues/3687#issuecomment-620226378

---

I've used the windows .exe installer to install DVC, but now I can't find it in the "add or remove programs" screen in the Control Panel.

However, [this page](https://dvc.org/doc/install/windows#windows-installer) reads:

> You may use Windows Uninstaller to remove the program.

I think this line should either contain a more accurate description of how to uninstall, or not be present.

**Comment by jorgeorpinel** [comment]
I'll remove the note from docs for now... In https://github.com/iterative/dvc.org/pull/1195

**Comment by efiop** [comment]
@fabiosantoscode IIRC, it is called `Data Version Control` there. Might want to rename it to DVC, for sure.

**Comment by efiop** [comment]
For the record, here is where it is defined https://github.com/iterative/dvc/blob/master/scripts/innosetup/setup.iss#L1

**Comment by jorgeorpinel** [comment]
OMG you're right 🤦‍♂️ 

![image](https://user-images.githubusercontent.com/1477535/80441446-8b4ee500-88d0-11ea-96bd-245e6733aa50.png)

Maybe rename it "DVC (Data Version Control)" ?

Updated issue desc.

**Comment by efiop** [comment]
@jorgeorpinel Adjusted it like that for now. Thanks!

**Comment by jorgeorpinel** [comment]
Thank you!
