### ISSUE TITLE
--show-md output for metrics, params and dvc diff

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#3690]
Today we support JSON output for the diff commands. However, CI/CD systems understand only the MD format. We need to add the MD format support to avoid the conversion.

**Comment by dmpetrov** [comment]
It might be related to #3435

**Comment by dmpetrov** [comment]
A bit more clarification: we are interested only in MD format with no html.

A nice option that can be included:
1. `--no-path` - do not show the first path column since the user might decide to output tables per file with a separate headers for each of the table.
2. `--no-text` - now `dvc metrics diff` output `None`  and  `diff not supported`. it might be better to have empty values instead.

**Comment by dmpetrov** [comment]
For `dvc diff` MD result should show the operation as a column `deleted\added\modified`.

It would be nice to have options like  `--added-only` \ `--modified--only` \ `--deleted-only`. It'll help the user to create separate sections in MD file if the separation is important and simplifies the table since the operation type column won't needed.

**Comment by efiop** [comment]
> It would be nice to have options like --added-only \ --modified--only \ --deleted-only. It'll help the user to create separate sections in MD file if the separation is important and simplifies the table since the operation type column won't needed.

For the record: decided not to go with these, as it seems too out of scope for `dvc diff`. It is easy to parse from the MD table.

**Comment by efiop** [comment]
Keeping open to consider 1,2,3 above.

**Comment by efiop** [comment]
1,2 implemented. 3 is not clear if needed, as it might make sense to just revisit the defaults. Closing for now.
