### ISSUE TITLE
Linking type should not be committed to git

### ISSUE THREAD

**Issue by drorata** [iterative/dvc#3697]
Consider the case that a project is cloned on two different platform, one which supports reflinks and the other only supports copying. Currently, `dvc config cache.type copy` would be committed to git and be used on both systems although one of them can enjoy a much smarter linking.

In other words, the cache type (and maybe other configurations) are local to the environment and should not be part of the `.dvc/config` which is committed to git.

[Ref](https://discordapp.com/channels/485586884165107732/563406153334128681/704964511492472982)

**Comment by efiop** [comment]
@drorata You could use `.dvc/config.local` for that. Just use `--local` flag when configuring your link type. Works for other config options too.

**Comment by drorata** [comment]
That makes a lot of sense! Thanks for the pointer. Maybe it is worthy to mention in the docs of `cache.type` that it is recommended to use the `--local` flag for the config?

**Comment by shcheklein** [comment]
@drorata there is an even simpler solution to this, I believe. You can set a comma separated list of cache types - DVC'll be trying them one by one. E.g.:

`reflink,copy` - means try reflinks, if they are not available, go with copy.

You can combine any link types like this.

**Comment by efiop** [comment]
Closing. Docs issue https://github.com/iterative/dvc.org/issues/1368 . Thanks again for the feedback @drorata !
