### ISSUE TITLE
Relax pip dependency versions constraints for python-dateutil

### ISSUE THREAD

**Issue by dchichkov** [iterative/dvc#3701]
Description of the problem:
ERROR: dvc 0.93.0 has requirement python-dateutil **<2.8.1** ,>=2.1, but you'll have python-dateutil 2.8.1 which is incompatible.

It'd be good to remove or relax upper constraints on python-dateutil, to include 2.8.1 and 2.8.2.  Is there a good reason why these are not included, or something is broken after 2.8.1 ?

**Comment by efiop** [comment]
Hi @dchichkov ! 

Mind submitting a PR to remove it? https://github.com/iterative/dvc/blob/master/setup.py#L50 It is an old sync requirement that is probably no longer needed. We'll see in the PR CI tests.
