### ISSUE TITLE
ERROR: unexpected error - are any errors expected by the user?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3718]
The following example is to drive my point home, but, yeah, the `unexpected error` is unnecessary.
```sh
$ cd  `mktemp -d`
$ mkdir .dvc
$ dvc status
ERROR: unexpected error - expected str, bytes or os.PathLike object, not NoneType

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

**Comment by efiop** [comment]
@skshetry Yes, some errors are expected: like target that doesn't exist or something like that. But sometimes some random exceptions make its way all the way up without being caught/handled, so to us they are unexpected. Your example is for an issue that we should've handled nicer before it was caught by the top level `except Exception` and so it shouldn't be an `unexpected error`.

**Comment by skshetry** [comment]
@efiop, I mean, `ERROR` is enough here. Adding `unexpected error` is not important at all.

**Comment by efiop** [comment]
@skshetry Some exceptions like AssertionError will not have any str at all :) So it would show up as `ERROR: ` without anything else :slightly_smiling_face: So `unexpected error` is somewhat useful. But ideally dvc should handle everything before it hits the `unexpected error`, that's our last line of defense :slightly_smiling_face:
