### ISSUE TITLE
status: add --recursive flag

### ISSUE THREAD

**Issue by nik123** [iterative/dvc#3720]
For some reason `dvc status` doesn't have `-R` flag in v 0.93.

**Comment by efiop** [comment]
Hi @nik123 !

`status` never had `-R` flag. We need to introduce it. All logic is there, we would simply need to add it to `dvc/command/status.py` and `dvc/repo/status.py`, that would then pass it to `collect` and `used_cache` in `dvc/repo/status.py`, similar how push/pull/fetch/etc do that.
