### ISSUE TITLE
[s3/windows]  HeadObject operation: Not Found

### ISSUE THREAD

**Issue by prashaw** [iterative/dvc#3745]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

Hello,

I get this error when using `dvc add` on s3 bucket when the files are deep inside the directories.
```
C:\Users\user\Desktop\AD>dvc add s3://samplebucket/dvc-test/6b –recursive
Adding...
ERROR: s3://samplebucket/dvc-test/6b/test\test\test.csv does not exist: An error occurred (404) when calling the HeadObject operation: Not Found
```
The error visible here is with mismatched **nt vs posix** paths. This works without issues in ubuntu 18.04.

DVC version:
```
C:\Users\user\Desktop\AD>dvc version
WARNING: Unable to detect supported link types, as cache directory '.dvc\cache' doesn't exist. It is usually auto-created by commands such as `dvc add/fetch/pull/run/import`, but you could create it manually to enable this check.
DVC version: 0.93.0
Python version: 3.7.4
Platform: Windows-10-10.0.17763-SP0
Binary: False
Package: pip
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Repo: dvc, git
```
The commands I followed prior to this including setting correct aws credentials are:
```
pip install awscli, boto3, dvc[all]
git init
dvc init
git commit .dvc/config -m "Configure bitbucket remote"
dvc remote add s3cache s3://samplebucket/dvc-test/d4 -f
dvc config cache.s3 s3cache
```
Thank you!

**Comment by xmaayy** [comment]
I am also getting this bug, any solutions?

**Comment by efiop** [comment]
Hi @xmaayy ! Are you also using cache.s3? If so, you are probably misusing `--external`. What you really want is https://github.com/iterative/dvc/issues/4520 , which we don't have implemented yet, so you need to download the data manually to your local machine, `dvc add` it and `dvc push` it.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/3920 for the scenario itself
