### ISSUE TITLE
DVC should check credentials for AWS sooner

### ISSUE THREAD

**Issue by greaber** [iterative/dvc#3752]
When pushing or pulling to/from S3, I often forget to set my AWS credentials.  It takes a pretty long time before dvc realizes this, I guess because it does a lot of other work first.  For instance, I just tested a `dvc pull`, and it takes about three and a half minutes before telling me it is unable to locate credentials.

On a side note, maybe there is some way to speed up the work that dvc pull and push need to do before they can start transferring files in general?

**Comment by efiop** [comment]
Hi @greaber ! Could you please upgrade to 0.94.0 (released yesterday) and see if that helps?

**Comment by greaber** [comment]
Oh wow, this issue seems fixed in 0.94!
