### ISSUE TITLE
Plot: link to docs

### ISSUE THREAD

**Issue by pared** [iterative/dvc#3755]
Link to docs as per @jorgeorpinel review under https://github.com/iterative/dvc/pull/3577, after plot documentation is merged from https://github.com/iterative/dvc.org/pull/1186.

**Comment by jorgeorpinel** [comment]
Thanks. I did start doing this in #3759 and mentioned it in https://github.com/iterative/dvc.org/pull/1186#pullrequestreview-407626236 but having the issue also doesn't hurt 🙂
