### ISSUE TITLE
Tab autocomplete when adding dirs not ignoring case even though it is set to in my .inputrc

### ISSUE THREAD

**Issue by george-gca** [iterative/dvc#3769]
When I am trying to add dirs to my dvc repo, when I press tab to autocomplete its name it is not ignoring case, even though `set completion-ignore-case On` is set on my `.inputrc` file.

Steps to reproduce: just try to add a folder that starts with upper case by inserting its lower case version and pressing tab to autocomplete.

DVC Version: 0.94.0
Install method: snap
System: Ubuntu Desktop 18.04

**Comment by efiop** [comment]
@george-gca Are you using bash or zsh?

**Comment by george-gca** [comment]
Sorry for missing that, using bash.

**Comment by efiop** [comment]
Closing as stale
