### ISSUE TITLE
snap: get repo fails

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#3775]
$ dvc get https://github.com/iterative/dataset-registry get-started/data.xml -o data.xml
ERROR: failed to get 'get-started/data.xml' from 'https://github.com/iterative/dataset-registry' - Failed to clone repo 'https://github.com/iterative/dataset-registry' to '/tmp/tmpq46_7szmdvc-clone': Cmd('/snap/dvc/388/usr/bin/git') failed due to: exit code(128)
  cmdline: /snap/dvc/388/usr/bin/git clone --no-single-branch --progress -v https://github.com/iterative/dataset-registry /tmp/tmpq46_7szmdvc-cloneHaving any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

- also as an aside, the above is not formatted as a code block because it's all on 3 lines which are super annoying to scroll sideways. Could improve this error message.

**Comment by casperdcl** [comment]
Note that snap "layouts" https://snapcraft.io/docs/snap-layouts are a standard way of mounting common file system paths, but that cannot be used because:

1. > `<target-path>` can include nearly any path except for [...] `/tmp`
2. > Layouts do not work with *classic* snaps

Basically this means we need DVC's tempdir to be configurable (e.g. via env vars or `dvc config --system/--global`)

**Comment by efiop** [comment]
No longer reproducible.
