### ISSUE TITLE
set rwlock on all dvcfiles when load/dump-ing

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3789]
We support running `repro`/`run` in parallel, so, there might be some chance of things getting overwritten between the load-serialize-dump process, creating a "_last writer wins_" situation.

**Comment by efiop** [comment]
Related #3653

**Comment by skshetry** [comment]
Looks like we don't completely allow running parallel execution, as we lock the repo most of the times and only unlock when the command is really running.

https://github.com/iterative/dvc/blob/afbb3a0add741a823397c4eca93f145a755d5197/dvc/stage/run.py#L37-L38 

As the collection of stages happen when the repo is locked in, only one process of dvc can really
be running at a given time. So, I'm reducing it's priority for now and removing from 1.0 milestone.

But, if we later come to remove that lock or make amends to it to allow parallel execution at all times, this will be `p0-critical`.

**Comment by skshetry** [comment]
Closing as stale.
