### ISSUE TITLE
Implement API for moving of DVC files

### ISSUE THREAD

**Issue by drorata** [iterative/dvc#3795]
It happens rather often: you hit the enter on a `dvc run ...` and when it finishes (maybe after a very long time) you realize you forgot to specify the location and name of the `.dvc` file. Currently, it seems that there are [two options](https://discuss.dvc.org/t/move-a-dvc-stage-without-re-run/384/2?u=drorata):

1. Use absolute paths. This is undermining the portability of the project
2. Manually update the `.dvc` file with the right paths. This is rather error-prone. 

Ideally, I could do something like `dvc move wrong_named_and_placed.dvc right/place/and/name.dvc`.

> Context: https://discuss.dvc.org/t/move-a-dvc-stage-without-re-run/384

**Comment by jorgeorpinel** [comment]
I wonder if this will still be the case with the new dvc.yml files 🙂 let's check.

**Comment by drorata** [comment]
I have no idea --- I didn't have the chance to pick up on the new `dvc.yml`... The main project where I'm using dvc is too important to risk with backward incompatibilities.

**Comment by jorgeorpinel** [comment]
Sure, I meant that note for the team internally. Thanks!

**Comment by efiop** [comment]
Closing as stale.
