### ISSUE TITLE
dvc gc WARNING

### ISSUE THREAD

**Issue by Sunny-Day200** [iterative/dvc#3809]
windows 
dvc-0.92.0

I deleted some data files and updated the. dvc file (dvc add). I want to use dvc gc -w to update the local cache. "WARNING:This will remove all cache except items used in the working tree and all git branches and tags of the current repo"
This is true for every command I use "DVC gc", and the cache has not been deleted

**Comment by efiop** [comment]
@Sunny-Day200 Could you share more details please? `gc` didn't delete any files? Are those files still used by dvcfiles present in your repo?

**Comment by Sunny-Day200** [comment]
> @ Sunny-Day200您能否分享更多详细信息？`gc`没有删除任何文件？您的存储库中是否仍存在dvcfiles使用的那些文件？

$ dvc gc -w -v
2020-05-21 14:33:13,803 DEBUG: Trying to spawn '['D:\\dvc\\Data Version Control\\dvc.exe', 'daemon', '-q', 'updater']'
2020-05-21 14:33:19,336 DEBUG: Spawned '['D:\\dvc\\Data Version Control\\dvc.exe', 'daemon', '-q', 'updater']'
2020-05-21 14:33:19,337 WARNING: This will remove all cache except items used in the working tree of the current repo.

------------------------------------------------------------------------
It seems so. My local invalid cache is too big
1. The size of the cache file does not change after gc
2. After I withdraw the git version, I can still checkout to the deleted data

**Comment by efiop** [comment]
Closing as stale.
