### ISSUE TITLE
End of file fixer

### ISSUE THREAD

**Issue by ternaus** [iterative/dvc#3814]
I am using an [end-of-file fixer in the pre-commit hook](https://pre-commit.com/hooks.html). It checks that the file ends with an empty new line.

It looks like files

```
	modified:   .dvc/plots/confusion.json
	modified:   .dvc/plots/default.json
	modified:   .dvc/plots/scatter.json

```

That are automatically created by `dvc init` do not have an empty line at the end of the file.

**Comment by efiop** [comment]
@ternaus Thanks! Feel free to contribute the PR, we'll really appreciate it!
