### ISSUE TITLE
Output of `dvc pipeline show --tree --out` weird. 

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#3824]
**Please provide information about your setup**

DVC version: 0.92.1
Platform and method of installation: pip
System: macOS

![image](https://user-images.githubusercontent.com/6745454/82308826-e6b65380-99f4-11ea-8ec1-f53201b7f8c6.png)

Probably related to these lines?

> Graph of `--out` is not the same as the stage graph.
https://github.com/iterative/dvc/blob/6ab06bbf9e3dfea552e14b626d5618bfdfe2384d/dvc/command/pipeline.py#L67

> Root node of `--out` is also a file, not a stage. 
https://github.com/iterative/dvc/blob/6ab06bbf9e3dfea552e14b626d5618bfdfe2384d/dvc/command/pipeline.py#L92

Finally, the graph of `--out` might be a forest instead of a tree. Should we show out each tree of the forest?

**Comment by efiop** [comment]
Closing since this command doesn't exist anymore and doesn't look like anyone is asking for `dvc dag --tree` neither.
