### ISSUE TITLE
Feature request: add a config option to change the default save location for .dvc files

### ISSUE THREAD

**Issue by gwerbin** [iterative/dvc#3837]
In a big project, I can end up with a large number of "top-level" DVC files. This looks very messy at the top level of a repository.

It would be nice if there were a config option to have `dvc run` create its files in a specified directory by default, e.g. `./dvc/`. This could potentially save a lot of typing `-f ...` command line options.

This might be obviated by the 1.0 changes with YAML files, but maybe other people have interest in this idea as well.

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/563406153334128681/712712083929563216

**Comment by efiop** [comment]
Closing as stale.
