### ISSUE TITLE
Bash/Zsh autocompletion scripts of command `DVC remote rename`

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#3847]
According to @shcheklein in iterative/dvc.org#1318 autocompletion scripts are forgotten in the previous PR #3794 .

**Comment by karajan1001** [comment]
@efiop 
May I ask a question? What does Tag `completion` means. Literally, it means this issues had been solved, but I found neither a PR nor a linked issue? 

I was just going to look into it.

**Comment by skshetry** [comment]
@karajan1001, it means this issue is about fixing auto-**completion** scripts.

You can take a look into it, if you can. :slightly_smiling_face:

**Comment by karajan1001** [comment]
@skshetry Thank you. Haha, the name `completion` confused me. 

I had updated the two scripts and tested them on my own computer. But there is another question that is there any method to create unit-tests for them?

**Comment by efiop** [comment]
@karajan1001 No unit tests required for those :slightly_smiling_face: Thank you so much!
