### ISSUE TITLE
tests: flaky ssh tests

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3888]
https://travis-ci.com/github/iterative/dvc/jobs/340412779

```sh
tests/unit/remote/ssh/test_connection.py::test_hardlink 
[gw1] [ 80%] FAILED tests/unit/remote/ssh/test_connection.py::test_hardlink 
tests/unit/remote/ssh/test_connection.py::test_copy 
[gw1] [ 80%] FAILED tests/unit/remote/ssh/test_connection.py::test_copy 
```

I thought this was only failing on my machine, so I was ignoring it. But, looks like it occasionally happens on the CI. On my machine though this always appears.

Also, an important thing to note here is that, locally on my machine. it only fails when I'm running all of the tests, but when I rerun failed tests, it passes.

**Comment by efiop** [comment]
Might consider making ssh_server fixture's scope extend to `session`. That might help, but I'm not 100% sure.

**Comment by efiop** [comment]
Nope, didn't solve https://travis-ci.com/github/iterative/dvc/jobs/340941135

**Comment by skshetry** [comment]
Now, it''s failing, because of course, `mock-ssh-server` uses `select.select()`, why not?
