### ISSUE TITLE
dvc: invisible stderr ERROR message in some terminals?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3902]
UPDATE: I'm using Git Bash (via std. Cmder) on Windows
UPDATE: Go to https://github.com/iterative/dvc/issues/3902#issuecomment-636106003

## Bug Report

```console
λ dvc run -n test2 -d output.data -o out-short.data head output.data > out-short.data
ERROR
```

The error is that I'm not wrapping the command in quotes but the output is just `ERROR`.

### Please provide information about your setup

**Output of `dvc version`:**

```console
λ dvc version
DVC version: 1.0.0a6+283718
Python version: 3.8.2
Platform: Windows-10-10.0.18362-SP0
Binary: False
Package: None
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache: reflink - not supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('NTFS', 'C:\\')
Repo: dvc, git
Filesystem type (workspace): ('NTFS', 'C:\\')
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by skshetry** [comment]
Not much dvc can do here.

Unless quoted, shell will assume `>` is a redirection and `dvc` will only get upto `head output.data` and the stdout will be redirected to `out-short.data`.

**Comment by efiop** [comment]
@skshetry But error should go to `stderror` and not to `stdout`.

**Comment by skshetry** [comment]
I am not able to reproduce that. I am getting the error message, so, I am waiting for @jorgeorpinel to respond.

**Comment by jorgeorpinel** [comment]
What is the question for me, @skshetry?

**Comment by jorgeorpinel** [comment]
i.e. yes this is still happening to me.

**Comment by jorgeorpinel** [comment]
Wait... the stdout is there! But I have to select it:

![image](https://user-images.githubusercontent.com/1477535/83290631-866da180-a1ac-11ea-9867-7b4c4dcf8564.png)

![image](https://user-images.githubusercontent.com/1477535/83290661-95ecea80-a1ac-11ea-892e-65ed792ed5a8.png)

so this bug report is invalid. However **maybe there's a problem with the output coloring**?

**Comment by jorgeorpinel** [comment]
I mean stderr

**Comment by skshetry** [comment]
@jorgeorpinel, can you try the following snippet and see if it's visible:
```console
$ echo "hello world" >&2
```

Just want to rule out if it's the command prompt at fault here.

**Comment by jorgeorpinel** [comment]
Sorry for the delay @skshetry. Both outputs are visible:

![image](https://user-images.githubusercontent.com/1477535/83429534-cb3a4800-a3f9-11ea-9d3f-f1e3c7b26faa.png)

![image](https://user-images.githubusercontent.com/1477535/83429587-ddb48180-a3f9-11ea-8262-88fafad6c0f3.png)

**Comment by jorgeorpinel** [comment]
p.s. now I'm getting a longer invisible output with the reported command on `1.0.0a6+283718` dev version:

![image](https://user-images.githubusercontent.com/1477535/83429840-4a2f8080-a3fa-11ea-9cc4-e8561b8ce7c5.png)

![image](https://user-images.githubusercontent.com/1477535/83429908-659a8b80-a3fa-11ea-85ac-11f5ff23fb41.png)

**Comment by jorgeorpinel** [comment]
I'm using Git Bash (via Cmder) on Windows BTW.

**Comment by skshetry** [comment]
I think the issue is more or less with [Maximus5/ConEmu](https://github.com/Maximus5/ConEmu) here. 



> Sorry for the delay @skshetry. Both outputs are visible:

First one demonstrates that `stderr` are correctly shown by term.
Second one demonstrates that `stderr` is correctly  prepared by dvc, and supported by terminal.

Looks like ANSI Escape sequences + stream redirection is buggy on the terminal.

**Comment by jorgeorpinel** [comment]
OK np should we open an issue in their repo and close this?

**Comment by skshetry** [comment]
> OK np should we open an issue in their repo and close this?

I'd leave that up to you. ;)

**Comment by majidaldo** [comment]
This isn't with conemu. Happens in cmd.exe too. In my case it happens with the git hooks.
I changed the hooks to redirect stderr like `exec dvc git-hook pre-commit $@ 2>%1` so now it's visible.

Oddly, if my terminal widh is 80 chars or less, I can still see it.

**Comment by efiop** [comment]
@majidaldo Btw, do you use https://pre-commit.com/ ? If so, could you give it a shot with `dvc install --use-pre-commit-tool` and see if that helps?

**Comment by majidaldo** [comment]
> @majidaldo Btw, do you use https://pre-commit.com/ ? If so, could you give it a shot with `dvc install --use-pre-commit-tool` and see if that helps?

Well, I can tell you that you have to have a valid .pre-commit-config.yaml (already) before you can use --use-pre-commit-tool. It should error out with something like .pre-commit-config.yaml does not exist.

**Comment by efiop** [comment]
@majidaldo Yes, it is our assumption that people already use it for something else, hence why I've asked you if you use it :slightly_smiling_face:

**Comment by efiop** [comment]
Closing since there isn't much we can do on our side.

**Comment by majidaldo** [comment]
> > @majidaldo Btw, do you use https://pre-commit.com/ ? If so, could you give it a shot with `dvc install --use-pre-commit-tool` and see if that helps?
> 
> Well, I can tell you that you have to have a valid .pre-commit-config.yaml (already) before you can use --use-pre-commit-tool. It should error out with something like: .pre-commit-config.yaml not found.

starting to use it. seems to be working. works even in my interoperating conda envs (though i know what i'm doing).
