### ISSUE TITLE
dvc status -R does not work

### ISSUE THREAD

**Issue by Wirg** [iterative/dvc#3909]
## Bug Report
`dvc status -R` does not work.

This is probably just a doc issue :
- the option can be found here [https://dvc.org/doc/command-reference/status](https://dvc.org/doc/command-reference/status)
- but not in the `dvc status --help`

What is the proper equivalent to the `-R` ? Right now I am relying on the the terminal wildcards `**/*dvc`.
 
### Please provide information about your setup

**Output of `dvc version`:**
```console
$ dvc version
DVC version: 0.94.0
Python version: 3.6.9
Platform: Linux-5.3.0-53-generic-x86_64-with-Ubuntu-18.04-bionic
Binary: False
Package: pip
Supported remotes: http, https, s3, ssh
Cache: reflink - not supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('ext4', '/dev/nvme0n1p2')
Repo: dvc, git
Filesystem type (workspace): ('ext4', '/dev/nvme0n1p2')
```

**Comment by Wirg** [comment]
Hi @skshetry,

Thank you for your answer.

I don't think I can give you much details with verbose, the failure is during the command resolution.
```console
$ dvc status -R --verbose .
ERROR: unrecognized arguments: -R
usage: dvc [-q | -v] [-h] [-V] COMMAND ...

Data Version Control
... rest of the help for dvc status ...
```

**Comment by efiop** [comment]
@Wirg Ah, ok, that makes sense now. `-R` was introduced https://github.com/iterative/dvc/pull/3726 after `0.94.0` and is only available in the pre-release version of dvc (use `pip install --pre dvc` to install it), feel free to upgrade and give it a try. There are no plans to backport it to 0.x right now.
