### ISSUE TITLE
plots show: targets are required but help output indicates otherwise [qa]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3925]
## Bug Report

Help output indicates `targets` are optional, but an error is thrown if not provided:

```console
λ dvc plots show -h
usage: dvc plots show [-h] [-q | -v] [-t [TEMPLATE]] [-o OUT] [-x X] [-y Y] [--no-csv-header] [--show-json] [--title TITLE] [--xlab XLAB]
                      [--ylab YLAB]
                      [targets [targets ...]]
...
positional arguments:
  targets               Metrics files to visualize. Shows all plots by default.

λ dvc plots show
ERROR: Datafile or template is not specified.
```

- [ ] ~~I assume targets are indeed required so they should be printed without `[]` in the usage, and the param description should not read "Shows all plots by default."~~
  UPDATE: Improve the error message when there are no plots in the workspace.
  + [ ] and update docs (figure out exact behavior first)

- [ ] Also note that the error uses the term "Datafile" which is confusing as it's no longer the name of the argument — Let's probably review this term all over the code base, not just in this one message?

### Please provide information about your setup

DVC 1.0.0a6+283718

**Comment by efiop** [comment]
Without targets it should collect and show all plots. Might be caused by https://github.com/iterative/dvc/pull/3911 CC @Suor

**Comment by jorgeorpinel** [comment]
OK. Well I don't have any plots when I run it. How do you register plots? Did we end up adding an option for `dvc run`? I'm still a bit lost in the 1.0 changes, sorry!

**Comment by skshetry** [comment]
@jorgeorpinel, we have `--plots` and `--plots-no-cache` option in the `dvc run`.

**Comment by Suor** [comment]
I didn't change this behavior, we still show all plots. Besides those options in run we can use `dvc plots modify` on any out to mark it as plot and add some props.

**Comment by jorgeorpinel** [comment]
So maybe the problem here is that when there are no plots in the project, e.g. in a new DVC repo, the error message is misleading? Maybe it should check for this particular condition and have a special error message.

**Comment by efiop** [comment]
Confirmed. This is something that I've missed initially. 

```
(dvc-3.8.3) ➜  dvc git:(fix-1545) ✗ dvc plots show                                     
ERROR: Datafile or template is not specified.                                          
                                                                                       
Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

This is a p0.
