### ISSUE TITLE
Fix CLI description formatter for links

### ISSUE THREAD

**Issue by pared** [iterative/dvc#3934]
Formatter for parser does not prioritize keeping link as a whole, and it should.

Example:
![help_msg](https://user-images.githubusercontent.com/10195618/83528513-78d85480-a4e9-11ea-8cfd-3d5a1ffecbdc.png)

**Comment by efiop** [comment]
@pared If your terminal is big enough it shows the whole link. Or am I missing something?

**Comment by pared** [comment]
Hmm, does not seem so:
![Screenshot from 2020-06-03 18-02-04](https://user-images.githubusercontent.com/10195618/83659953-7e569d00-a5c4-11ea-827c-867b33f9cb0f.png)

**Comment by efiop** [comment]
@pared Strange, works for me. Could you show `dvc version`? Mostly interested in python version.

![Screenshot from 2020-06-03 20-44-04](https://user-images.githubusercontent.com/5367102/83669935-08a9fb80-a5db-11ea-9d9e-b5fc4b745c8f.png)

**Comment by pared** [comment]
```
DVC version: 1.0.0a7+9a55b9
Python version: 3.7.6
Platform: Linux-5.3.0-53-generic-x86_64-with-Ubuntu-18.04-bionic
```
Maybe its something with terminal settings?

**Comment by pared** [comment]
Huh, I installed Python 3.8 and it works fine, maybe there is a difference in `Formatter` implementation.

**Comment by pared** [comment]
3.6 has the same problem

**Comment by efiop** [comment]
Yeah, looks like argparse fixed it in 3.8.

**Comment by pared** [comment]
I guess we can close it then.

**Comment by efiop** [comment]
We could consider monkeypatching it if it is easy enough.
