### ISSUE TITLE
raise NoMetrics/Plots/ParamsError in CLI and not in API

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#3944]
https://github.com/iterative/dvc/pull/3940#discussion_r434306852 CC @Suor

**Comment by skshetry** [comment]
This seem to have happened at some point. I don't see any such exceptions in API/CLI, in fact it returns empty dictionary as suggested in #3940.

**Comment by skshetry** [comment]
This seem to have happened at some point. I don't see any such exceptions in API/CLI, in fact it returns empty dictionary as suggested in #3940.
