### ISSUE TITLE
metrics: add xpath/filter support

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#3945]
leftover from https://github.com/iterative/dvc/issues/3409

**Comment by bobertlo** [comment]
Would the `--include-metrics/--exclude-metrics` and params syntax used in `experiments show` be appropriate to be used here?

Ah, I looked at the original issue and see `--select` was given as the flag. Would select still be preferred over include/exclude?

**Comment by daavoo** [comment]
I was tryingsome of the [dvclive](https://github.com/iterative/dvclive) integratons and think that having `--include-metrics/--exclude-metrics` would be quite handy. 

Depending on the *ML Framework*, `dvclive` generates a significant amount of metrics that makes `dvc metrics show/diff` not really usable from the terminal.

Not sure if it makes sense to address it know, given the assigned priority, but for the record I think I might be able to solve it as I'm a little familiar with the existing `exp show --include/exclude` implementation (https://github.com/iterative/dvc/pull/5720)

**Comment by dberenbaum** [comment]
Are you finding `metrics` commands useful over `exp show`?

I think if it's an easy or useful PR for you, feel free to go for it, but I don't think there's much urgency to add this unless you see it as a frequent issue for dvclive users.

**Comment by daavoo** [comment]
> Are you finding `metrics` commands useful over `exp show`?

I was setting up a version without using `experiments` first and just discovered because of your comment that you can use `exp show` even if you didn't use `exp run`. So I guess that now I'm a little confused about the scope of each command.

> I think if it's an easy or useful PR for you, feel free to go for it, but I don't think there's much urgency to add this unless you see it as a frequent issue for dvclive users.

Probably not really an issue now that I know that you can use `exp show` in any case

**Comment by dberenbaum** [comment]
The `exp` commands generally combine `metrics` and `params`, so we should probably better document how they can be used and recommend them in place of `metrics` and `params` in many cases.

**Comment by skshetry** [comment]
Should this be close this? Or, are we still interested in supporting `filter`/`xpath`?

**Comment by skshetry** [comment]
Closing this issue since there are better ways to filter metrics with `exp show` as discussed above, feel free to reopen if you disagree.
