### ISSUE TITLE
term: "unset" is not a verb

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3950]
> Extracted from https://github.com/iterative/dvc.org/pull/1382#pullrequestreview-423710068

I don't think "to unset" is a proper word for an action but we use it in several commands. Specifically `config` (and `cache dir`, `remote default/modify`, and `plots modify`.

I recommend "forget" or "remove".

**Comment by efiop** [comment]
@jorgeorpinel `git config` has `--unset`. This is where we got our `--unset` from.

**Comment by jorgeorpinel** [comment]
Good point. I guess that's a good enough authority for this case. Still, if we can improve it in the future, why not

**Comment by efiop** [comment]
@jorgeorpinel I don't actually understand why `unset` is bad. Things like bash/zsh/etc have `unset` command. Not sure it is worth renaming.

**Comment by jorgeorpinel** [comment]
It's just not a real word (used as a verb) according to formal English. But yes it's true that in command line it's common enough so I guess you're right. No need to complicate things over a non-issue.
