### ISSUE TITLE
Get Warning/Error when cache directory is not present/valid

### ISSUE THREAD

**Issue by sttobia** [iterative/dvc#3955]
For one of my projects I had the local cache directory located on an external SSD which worked fine in the beginning.
At some point I started to develop from inside a docker container and initially forgot to also mount the external SSD with the DVC cache on it. When checking with dvc status I would have assumed, that DVC would warn me about the cache not being present neither under .dvc/cache nor at the specified location in the local config file. But it did not and instead always threw warnings about files not being present in the cache. 

I think one simple Warning about the cache folder not being present/valid could solve a lot of future problems and confusion of users.

**Comment by efiop** [comment]
Closing as stale.
