### ISSUE TITLE
question - Working with codecommmit on AWS

### ISSUE THREAD

**Issue by sunny1401** [iterative/dvc#3961]
Hi,

I have just started looking into this library yesterday. When I try to do dvc init in a code-commit library, it simply states Error:Failed to initiate DVC - [Dicrectory name] is not tracked by any supported SCM tool. 

Does it not support code commit or I am doing something wrong.

Thank You

**Comment by efiop** [comment]
Hi @sunny1401 ! Were you able to find a way to make it work for you?

**Comment by sunny1401** [comment]
Hi - yes - I was trying from a folder inside the base folder. Since the application has a fit like support - I assumed it would init from there as fit can detect status change. Anyhow moving to the base directory works.. thank you for replying.
