### ISSUE TITLE
plots: diff: targets and revisions behaviour

### ISSUE THREAD

**Issue by pared** [iterative/dvc#3962]
When `--targets` is present, argument parser will not be able to grab revisions, due to fact that both options use `nargs='*'`.

**Comment by efiop** [comment]
How about `--revs` then? CC @dmpetrov @Suor

**Comment by dmpetrov** [comment]
It should work the same way with the same params as `metrics diff`. Do we have the same issue with ht metrics command?

**Comment by pared** [comment]
@dmpetrov 
> It should work the same way with the same params as metrics diff

I think we should discuss it. Arg parser allows us to have only one multiple-params argument (or few optional). So I guess it all boils down to question whether API consistency and ability to `diff` multiple targets is more desired than being able to plot multiple revisions on a single plot. In initial discussions, I got the impression that we need to support multiple `revisions`.

**Comment by efiop** [comment]
@pared Btw, it mixes them up only if you do that explicitly:
```
dvc plots diff --targets t1 t2 r1 r2 r3 r4
```
but it is actually normal, there is a special `--` that argparse supports natively when you need to tell it that you are done declaring the args for one of the options:
```
dvc plots diff --targets t1 t2 -- r1 r2 r3 r4
```
and normal stuff like
```
dvc plots diff r1 r2 r3 r4 --targets t1 t2
```
works fine.

Same with `metrics diff`. So we don't really need to do anything, unless we really want to make this explicit too.

**Comment by dmpetrov** [comment]
Agree with @efiop - we can keep it as-is and just remember this trick. I still feel like it can confuse some users and we should be prepared for this. But it looks like the best solution for today.

Let's keep as-is and close this issue! What do you think @pared?

**Comment by pared** [comment]
@dmpetrov @efiop I agree, lets close it. I will create ticket for docs for that issue. I think some kind of a Note under `dvc plots diff` section of documentation could save some hassle. And regretfully, it's not easy to find the `--` usage instructions in python docs. I was not aware of that.

**Comment by Suor** [comment]
Show we add examples to our `dvc <command> --help`?

**Comment by efiop** [comment]
@Suor Not really. To the docs -- maybe, but even still `--` thing is a common one, it applies to pretty much any CLI command anywhere, not only to plots diff.
