### ISSUE TITLE
plots show/diff: template anchors shown in plot [qa]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3968]
## Bug Report

Using logs.csv from the example in https://dvc-landing-2020-05-31-evbiu1f.herokuapp.com/doc/command-reference/plots/modify#examples (see iterative/dvc.org/pull/1382):

```console
dvc plots show
file://C:\Users\poj12\DVC-repos\tests\plots.html
```
> Exact same resulting plot with `diff`.

![image](https://user-images.githubusercontent.com/1477535/83982515-c17a7e00-a8ec-11ea-8661-749414a8b122.png)

I don't think `<DVC_METRIC_X_TITLE>` should be shown. For X it's supposed to be `index`, and `loss` for Y in the case of this metric file.

### Please provide information about your setup

**Output of `dvc version`:**

```console
λ dvc version
DVC version: 1.0.0a9+3683c2
Python version: 3.8.2
Platform: Windows-10-10.0.18362-SP0
Binary: False
Package: None
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache: reflink - not supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('NTFS', 'C:\\')
Repo: dvc, git
Filesystem type (workspace): ('NTFS', 'C:\\')
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by jorgeorpinel** [comment]
Also, an effect of this is that all the `--x-label` and `--y-label` of all plot subcommands have no effect.

**Comment by efiop** [comment]
CC @pared

**Comment by efiop** [comment]
@jorgeorpinel Unable to reproduce. Shows `index` in the bottom for me.
![Screenshot from 2020-06-08 23-12-38](https://user-images.githubusercontent.com/5367102/84075919-93289b80-a9dd-11ea-8e1e-48de8ba3adac.png)

**Comment by efiop** [comment]
Same with --x/y-label:
![Screenshot from 2020-06-08 23-13-40](https://user-images.githubusercontent.com/5367102/84076023-beab8600-a9dd-11ea-9d92-38de76ec594b.png)

**Comment by efiop** [comment]
Unless we have some windows-specific bug, of course. But it would be great to double-check @jorgeorpinel , maybe it was some accidental corruption or something.

**Comment by jorgeorpinel** [comment]
Hmmm OK let me try in a fresh DVC repo... ⏳

**Comment by jorgeorpinel** [comment]
I pulled the latest master branch and installed the dev env again to `1.0.0a10+c1b0e9` and created a new project. It works now 🤷‍♂️ 

I guess it was corrupted after all! Phew!
