### ISSUE TITLE
plots diff: WARN about bad templates sent to -t [qa]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3969]
## ~~Bug Report~~

UPDATE: Jump to https://github.com/iterative/dvc/issues/3969#issuecomment-640879725

---
OLD:

Using logs.csv from the example in https://dvc-landing-2020-05-31-evbiu1f.herokuapp.com/doc/command-reference/plots/modify#examples (see iterative/dvc.org/pull/1382):

```console
dvc plots diff -t train.json
file://C:\Users\poj12\DVC-repos\tests\plots.html
```

![image](https://user-images.githubusercontent.com/1477535/83983047-c3ded700-a8f0-11ea-90e7-d3db24a21916.png)

### Please provide information about your setup

**Output of `dvc version`:**

```console
λ dvc version
DVC version: 1.0.0a9+3683c2
Python version: 3.8.2
Platform: Windows-10-10.0.18362-SP0
Binary: False
Package: None
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache: reflink - not supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('NTFS', 'C:\\')
Repo: dvc, git
Filesystem type (workspace): ('NTFS', 'C:\\')
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by jorgeorpinel** [comment]
Oops wrong screenshot. Here it is:

![image](https://user-images.githubusercontent.com/1477535/83983047-c3ded700-a8f0-11ea-90e7-d3db24a21916.png)

**Comment by jorgeorpinel** [comment]
Page source:

```html

<!DOCTYPE html>
<html>
<head>
    <title>DVC Plot</title>
    <script src="https://cdn.jsdelivr.net/npm/vega@5.10.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-lite@4.8.1"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-embed@6.5.1"></script>
</head>
<body>
    <div id = "plot0"></div>
<script type = "text/javascript">
    var spec = epoch,accuracy,loss
0,0.9403833150863647,0.2019129991531372
1,0.9733833074569702,0.08973673731088638
2,0.9815833568572998,0.06529958546161652
3,0.9861999750137329,0.04984375461935997
4,0.9882333278656006,0.041892342269420624
5,1.0,0.1
6,1.0,0.2
;
    vegaEmbed('#plot0', spec);
</script>
</body>
</html>
```

**Comment by efiop** [comment]
That's pretty strange, works for me:
```
<!DOCTYPE html>
--
  | <html>
  | <head>
  | <title>DVC Plot</title>
  | <script src="https://cdn.jsdelivr.net/npm/vega@5.10.0"></script>
  | <script src="https://cdn.jsdelivr.net/npm/vega-lite@4.8.1"></script>
  | <script src="https://cdn.jsdelivr.net/npm/vega-embed@6.5.1"></script>
  | </head>
  | <body>
  | <div id = "plot0"></div>
  | <script type = "text/javascript">
  | var spec = {
  | "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  | "data": {
  | "values": [
  | {
  | "accuracy": "0.9403833150863647",
  | "epoch": "0",
  | "index": 0,
  | "loss": "0.2019129991531372",
  | "rev": "workspace"
  | },
  | {
  | "accuracy": "0.9733833074569702",
  | "epoch": "1",
  | "index": 1,
  | "loss": "0.08973673731088638",
  | "rev": "workspace"
  | },
  | {
  | "accuracy": "0.9815833568572998",
  | "epoch": "2",
  | "index": 2,
  | "loss": "0.06529958546161652",
  | "rev": "workspace"
  | },
  | {
  | "accuracy": "0.9861999750137329",
  | "epoch": "3",
  | "index": 3,
  | "loss": "0.04984375461935997",
  | "rev": "workspace"
  | },
  | {
  | "accuracy": "0.9882333278656006",
  | "epoch": "4",
  | "index": 4,
  | "loss": "0.041892342269420624",
  | "rev": "workspace"
  | }
  | ]
  | },
  | "title": "",
  | "mark": {
  | "type": "line"
  | },
  | "encoding": {
  | "x": {
  | "field": "index",
  | "type": "quantitative",
  | "title": "index"
  | },
  | "y": {
  | "field": "loss",
  | "type": "quantitative",
  | "title": "loss",
  | "scale": {
  | "zero": false
  | }
  | },
  | "color": {
  | "field": "rev",
  | "type": "nominal"
  | }
  | }
  | }
  | ;
  | vegaEmbed('#plot0', spec);
  | </script>
  | </body>
  | </html>
```

**Comment by efiop** [comment]
@jorgeorpinel did you use standard templates?

**Comment by jorgeorpinel** [comment]
> ```
> <!DOCTYPE html>
> --
>  | <html>
>  | <head>
> ...
> ```

Tehehe copy paste from Chrome "view source" introduces a bunch of characters (works properly with ctrl+shift+v for me).

**Comment by jorgeorpinel** [comment]
> did you use standard templates?

🤦 ! I mistakenly used the `-t train.json` flag thinking it meant `--targets` but it means `--template` ! `dvc plots diff --targets train.json` works.

**Comment by jorgeorpinel** [comment]
Maybe we should reconsider the option letters? Or at least print a warning when a provided template file does not exist or is invalit!

**Comment by efiop** [comment]
@jorgeorpinel It already throws if the template is not found:

```
(dvc-3.8.3) ➜  dvc git:(fix-3897) ✗ dvc plots diff -t sdf
ERROR: Template 'sdf' not found.

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

It is not able to detect a bad template, that is true, but I'm not completely sure if we can do that in a general case. Seems like the best we could do is to check that it is indeed a json/yaml (once we get rid of html support), but I'm not sure we could require it to hit any quotas on anchors that it uses.  CC @pared

**Comment by jorgeorpinel** [comment]
> not able to detect a bad template, that is true, but I'm not completely sure if we can do that in a general case

Maybe let's just keep an eye on this to see if users make the same error I did and at least detect when a given template is actually a metrics file in that case (and WARN/ERROR out).

**Comment by pared** [comment]
We can check that template is valid by checking for `DVC_METRIC_DATA` anchor. I don't see a use case where one would like to use `dvc plots` and not provide it. 

Also if we are talking about JSON templates, what is a common property of a JSON specification is `$schema` field.
eg
- for vega:
`"$schema": "https://vega.github.io/schema/vega/v5.json"`
- vega lite:
` "$schema": "https://vega.github.io/schema/vega-lite/v4.json"`

**Comment by jorgeorpinel** [comment]
It can even be done by [JSON schema validation](https://datatracker.ietf.org/doc/draft-handrews-json-schema-validation/) but seems overkill (unless there's a quick python lib that does easily).

**Comment by pared** [comment]
@efiop yep, I think this would solve this issue.
