### ISSUE TITLE
make sure metrics/plots can compare dirty repo with the last commit by default

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#3974]
>  Which versions get compared by default? without sending arguments
> I expected the present metrics file to be plotted on top of the last commit but if I manually change this metrics file, the changes are not reflected in the plot.
>  Only if I run dvc repro in a way that generates a different metrics file does it pick up the changes and plots them.
>  Where is this version coming from? I haven't committed anything to Git.
>  On DVC 1.0

https://discordapp.com/channels/485586884165107732/563406153334128681/719342575835676733

**Comment by jorgeorpinel** [comment]
Sweat, thanks!

It would be great to confirm whether the description currently in iterative/dvc.org/pull/1382 (hopefully merged soon) is the correct desired behavior.

**Comment by efiop** [comment]
Yep, can confirm the issue. Preparing a fix right now.

**Comment by jorgeorpinel** [comment]
Consider fixing this (and maybe other p0 bugs you can think of) in a 0.95 old version as a last support release for legacy users. Not a priority right now obviously but should we open a little epic issue on this?

**Comment by efiop** [comment]
@jorgeorpinel No, there are no plans to backport it to 0.9x. We should encourage people to upgrade to 1.0.
