### ISSUE TITLE
Make dvc status readable

### ISSUE THREAD

**Issue by hdcasti** [iterative/dvc#3975]
HI, it will be interesting to make dvc status readable in a json file for example so that it can be parsed and used, for example to notify users using an IDE of changes in the files or give suggestions.

**Comment by shcheklein** [comment]
Hi, @hdcasti ! It's an important feature request and is much needed to start doing IDE integrations. We'll try to prioritize it for next sprint, but if you need it earlier, the implementation should be pretty straightforward. Check this example:

https://github.com/iterative/dvc/blob/666e203bbba3a36e2b6c2a6a4015718c36e77374/dvc/command/diff.py#L162
https://github.com/iterative/dvc/blob/666e203bbba3a36e2b6c2a6a4015718c36e77374/dvc/command/diff.py#L120

For the status, you we can do pretty much the same here:

https://github.com/iterative/dvc/blob/b8aa8ad9511762c94c539680ab917f86ddc24569/dvc/command/status.py#L57

What I would try to check first though - does the output we provide now enough? do we need to change it somehow to support integrations, etc. You have probably more visibility, so any recommendations are welcome.

**Comment by efiop** [comment]
Hi @hdcasti ! Please take a look at https://github.com/iterative/dvc/issues/1406 . I'll close this one, since there is more info in that issue.
