### ISSUE TITLE
init: details related to .git/ and subdirs

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3980]
UPDATE: Jump to https://github.com/iterative/dvc/issues/3980#issuecomment-640849160

---
OLD:
I think this has been discussed before but couldn't find the issue after a quick search.

Probably most DVC projects use Git, but not all. And since we don't want DVC to seem like it's completely dependent on Git, could `dvc init` automatically apply `--no-scm` when there's no Git repo? Maybe just output a WARNING or INFO message about it in case the user forgot to `git init`. If .git/ is present, the flag could still be used explicitly if desired (I imagine this is very rare) — maybe even disallow that.

Motivation: this would be nice for example in our introductory guides such as the Get Started so I can just explain DVC and don't even mention Git until versioning comes to play.

> Also renaming to --no-git (and removing the silent .hg/ integration of Dvcignore) would be interesting to revisit, but those are separate issues.

### Please provide information about your setup

DVC 1.0

**Comment by efiop** [comment]
> Probably most DVC projects use Git, but not all. And since we don't want DVC to seem like it's completely dependent on Git, could dvc init automatically apply --no-scm when there's no Git repo? Maybe just output a WARNING or INFO message about it in case the user forgot to git init. If .git/ is present, the flag could still be used explicitly if desired (I imagine this is very rare) — maybe even disallow that.

But most of them use git. And dvc without git has a lot less features. If we make that automatic, people will acidentally run and it and will be confused on why stuff like `dvc metrics` doesn't work.

`--no-scm` is an advanced scenario suitable for some of the applications, but not really for our core scenario (get-started without git won't work, as you won't even be able to show metrics), And warnings wouldn't help, people don't read them, we know that from experience.

**Comment by jorgeorpinel** [comment]
> get-started without git won't work

I'm writing a new new Get Started with several different example projects, the introductory one is just about tracking data without versioning so I have to use `--no-scm`.

**Comment by jorgeorpinel** [comment]
> If we make that automatic, people will acidentally run and it and will be confused on why stuff like dvc metrics doesn't work.

This is a valid concern but seems pretty speculative.

**Comment by efiop** [comment]
> I'm writing a new new Get Started with several different example projects, the first one is just about tracking data (dvc add and run) without versioning so I have to use --no-scm, which makes is seem more complicated than necessary.

@jorgeorpinel How are you going to explain metrics, plots, params though without git? Sure, you could run a few basic `dvc add/run`s in the vacuum without git, but you'll hit a barrier pretty fast. It is even not really clear what you would do with that after, as you can't share it even, because you need git repo/remote to share it with you or other people.

**Comment by shcheklein** [comment]
> ... so I have to use --no-scm, which makes is seem more complicated than necessary.

you don't have to, just assume that project is Git based? Also, it would complicate even data management explanations.

I would suggest to consider `--no-scm` an advanced mode. It should be used only by people who really need it when they need it.

I agree though that there are some issues with `--no-scm`/DVC complaining if .git is not detected (e.g. building project in Docker when .git is not available looks like a very common use case we'll have to deal with).

Also, what we should do when we run `dvc init` without arguments in a subdir/subproject?

**Comment by jorgeorpinel** [comment]
> How are you going to explain metrics, plots, params though without git?

I wasn't planning to do that. For those I will use an actually Git-enabled example later after introducing the Git-DVC relationship.

> you even can't share it

No need to share an introductory tutorial

> just assume that project is Git based?

OK sure, I can do this!

> consider --no-scm an advanced mode

Got it. That's why I didn't want to even have to mention it in Get Started.

Of course one guide in our docs wouldn't justify changing the behavior of `dvc init` by itself. It was just an example. Since there seems to be no other good use cases, I guess this is a no. Thanks

Leaving this open just to finish discussing this part:

> there are some issues with --no-scm/DVC complaining if .git is not detected (e.g. building project in Docker when .git is not available looks like a very common use case...
> Also, what we should do when we run dvc init without arguments in a subdir/subproject?

**Comment by efiop** [comment]
@jorgeorpinel We have https://github.com/iterative/dvc/issues/3574 for that. Let's move there. Closing.
