### ISSUE TITLE
move: support dvc.yaml stages (1.0) [qa]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3982]
I understand `dvc move` only works for data added (.dvc files) in 1.0

However `dvc remove` works for both stages in dvc.yaml as well as .dvc files. Should move also support dvc.yaml stages or their outputs?

> Partial context: https://github.com/iterative/dvc.org/pull/1403#pullrequestreview-426039417

**Comment by efiop** [comment]
> Should move also support dvc.yaml stages or their outputs?

Unfortunately, there is no general way to do that, as it will require adjusting the command in a some non-trivial way (or paths might even be baked into the script, which we have 0 power over), so we can't do that :( So yeah, we can `dvc remove` any stage(`dvc.yaml`, old and new `.dvc`), but we can only `dvc move` `.dvc (new ones are only produced by `add` and `import[-url]`) files.
