### ISSUE TITLE
plots modify: change --no-csv-header to --no-header?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3996]
> Extracted from https://github.com/iterative/dvc.org/pull/1382#pullrequestreview-425769472

> should it be just --no-header? - @shcheklein

> or --no-table-header since TSV is also supported. This way it remains obvious that it only applies to tabular metric files. But I could also support --no-header — cleaner.
- me

> I like the --no-table-header - @pared 

### Please provide information about your setup

DVC 1.0

**Comment by efiop** [comment]
Guys, so maybe `--no-header` after all? Or do you see a different usecase for `--no-header` that will force us to create `--no-table-header` in the future to differentiate the use cases? @pared

**Comment by shcheklein** [comment]
+1 for `--no-header`, at least `--no-csv-header` feels wrong since it's not CSV only

**Comment by sahilbhosale63** [comment]
Hi, Can I work on this issue?

**Comment by pared** [comment]
I don't see a future use case for `--no-header` as of today, let's do it. I guess if there would be more important and viable use case for that option, we would know by now.

**Comment by efiop** [comment]
Hi @sahilbhosale63 !

Sorry, don't mean to discourage, but this one is already WIP by me, so, if you still would like to contribute, please take a look at `good-first-issue` and `help-needed` labels in our issues list. Thank you! :pray:
