### ISSUE TITLE
dvc repro: change dir

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#401]
The same as `make -C external-lib`.
Important: Make sure it works with Git submodules!

```
$ dvc repro -C myproj
```

```
$ dvc repro -C myproj myproj/Posts.xml.dvc
```

**Comment by efiop** [comment]
Submodules will require dvc to detect and use appropriate .dvc for each target, otherwise it will not use appropriate cache and config. I suggest we leave this feature for the next release.

**Comment by dmpetrov** [comment]
Let's use `-c` \ `--cwd` as the option name - the same as `dvc run`.

If dvc-file was created outside of dvc-root dir (`dvc run` without `--cwd`) then a user should be able to reproduce this command later: `dvc repro --cwd`.
