### ISSUE TITLE
dvc remove'd folder stays in gitignore

### ISSUE THREAD

**Issue by ammarasmro** [iterative/dvc#4013]
### Please provide information about your setup
The removed folder's name is still in `.gitignore`. Not sure if that's intentional or not
**Output of `dvc version`:**

```console
$ dvc version

DVC version: 0.93.0
Python version: 3.7.5
Platform: Darwin-19.5.0-x86_64-i386-64bit
Binary: True
Package: osxpkg
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache: reflink - supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('apfs', '/dev/disk1s5')
Repo: dvc, git
Filesystem type (workspace): ('apfs', '/dev/disk1s5')
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by nik123** [comment]
I'd like to pick it up. The naive way to fix it is to add `ignore_remove` into `BaseOutput` and add `ignore_remove_outs` then modify the stage.remove:

```
def remove(self, force=False, remove_outs=True, purge=True):
    if remove_outs:
        self.remove_outs(ignore_remove=True, force=force)
    else:
        self.unprotect_outs()
        self.ignore_remove_outs()
        if purge:
            self.dvcfile.remove_stage(self)
```

But adding these methods seems like an overkill for such a simple task. Am I missing something?

**Comment by efiop** [comment]
@nik123 That looks like a pretty good approach! Let's do that for now. Thanks! :pray:
