### ISSUE TITLE
DVC 1.0 QA results, part 2

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#4014]
```
DVC version: 1.0.0a10+4042d5
Python version: 3.7.7
Platform: Darwin-19.4.0-x86_64-i386-64bit
Binary: False
Package: None
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Repo: dvc, git
Filesystem type (workspace): ('apfs', '/dev/disk1s1')
```

No new _and_ major findings this time.

- [x] `dvc run -f` (ex `--overwrite`) changes order of stages in the file (#4035) -https://gist.github.com/shcheklein/30103d6fcb9d58e8be85e0be0f1b22a0
- [x] We should probably include newline at the end of the `dvc.yaml`. A lot of editors do this automatically meaning that we change hash of it (?) Having a new line at the end is a good practices for code files.
- [x] 💅 ~~no dot at the end in the `dvc --help` for unprotect~~ Too tedious to make it consistent everywhere.
- [x] 💅 ~~`or between a commit and the workspace.` is included for some `diff` commands, not for others in `dvc --help`~~
- [x] ~~check and update autocompletion scripts - we've done a lot of renaming/changes recently~~ (#3921)

A bunch of issues with plots, but I think we already have tickets for them or at least aware. A few other issues have been fixed yesterday ⚡

**Comment by skshetry** [comment]
> dvc run -f (ex --overwrite) changes order of stages in the file

I would not like to spend time in preserving order on `-f`. Is there any strong reasons to?
I understand that by preserving order, we will be able to have a better diff and preserve comments + meta (which might also mean, accidentally it could copy unnecessary leftovers from previous entry as well, but my quick test did not show such behavior though). But, promising order  is a slippery slope. With `-f`, you can provide any options which essentially makes it a new stage (only the `name` is shared at minimum).

Again, by using `-f`, you are creating a new stage. So, it's better to treat it as such and append at the end.

> We should probably include newline at the end of the dvc.yaml

@shcheklein, can you double check this? This should already be the case.
Try with:
```console
tail -c1 dvc.yaml
```

**Comment by shcheklein** [comment]
> Is there any strong reasons to?

`-f` is being used to _edit_ stages, not create new ones. If we allow _editing_  the stages we should be doing this w/o messing user defined order.

Alternative here - don't allow `-f`.

> But, promising order is a slippery slope. 

Not sure I understand this. You don't promise any oder - you just keep it.

> Again, by using -f, you are creating a new stage. So, it's better to treat it as such and append at the end.

Usual case for `-f` is to edit, not create a new one. See above.
 
>  This should already be the case.

yep, checked ✅ !

**Comment by efiop** [comment]
Leftover points are too big and abstract with questionable usefulness.
