### ISSUE TITLE
introduce cache check/repair command(s)

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#4020]
Not 100% sure about the naming, but the idea is for dvc to make sure that it has all the permissions in-check for the cache that it will use. E.g. https://github.com/iterative/dvc/issues/3964 , where we had an issue with shared cache.

`dvc cache check` could walk around the cache, making sure it is able to read and write to it (though read-only is also fine for some scenarios, especially since we no longer have the unpacked dir) and `dvc cache repair` would possibly ask for sudo and chmod everything as it sees fit.

**Comment by ANaumann85** [comment]
I think that something like a _content check_ would also help to user to see, if the cache got corrupted at some point
