### ISSUE TITLE
~/.config/dvc created to full-world writeable

### ISSUE THREAD

**Issue by bjonnh** [iterative/dvc#4021]
### Please provide information about your setup

**Output of `dvc version`:**

```console
DVC version: 0.94.0
Python version: 3.8.3
Platform: Linux-5.6.15-arch1-1-x86_64-with-glibc2.2.5
Binary: False
Package: pip
Supported remotes: http, https
Repo: dvc, git
```

**Additional Information (if any):**

creating a new repo, setting a config, the ~/.config/dvc is created with 777 (rwx for all)
it should be 770 at most.

**Comment by efiop** [comment]
@bjonnh dvc creates your config file with default permissions that are determined by the umask you have setup in your environment. This is the same as what `git` does when it creates its config file.

The only sensitive thing that might be present in a dvc config is `password` for `ssh` remote, but we do not recommend using it. You should handle it by creating a ssh keyfile or using ssh keystore.

**Comment by bjonnh** [comment]
This is really weird because my umask is not that one, it is 022

**Comment by bjonnh** [comment]
But you are running os.umask(0) in a few places. (including daemon.py)
so it resets the system umask.

**Comment by bjonnh** [comment]
and also you are changing the umask when running os.umask(0o777 - mode) in dvc/utils/fs.py

**Comment by bjonnh** [comment]
You can test that on a fresh install in a docker
docker run -it --rm ubuntu:20.04 bash
```console
 apt-get update && apt-get install -y python virtualenv git
 virtualenv venv
 source venv/bin/activate
 pip install dvc
 mkdir test && cd test &&  git init . && dvc init
 ls -ld ~/.config/dvc 
```
and you get: drwxrwxrwx 2 root root 4096 Jun 11 15:33 /root/.config/dvc

**Comment by efiop** [comment]
Ah, got it. I missed that you were talking about ~/.config/dvc . Indeed, that is a bug on our side!

**Comment by efiop** [comment]
> But you are running os.umask(0) in daemon.py so it overrides the system umask as well (and sets it to 777)

Good catch! I think it is the one that is causing the issue. Let's remove it, I think it is a leftover.

> and also you are changing the umask when running os.umask(0o777 - mode) in dvc/utils/fs.py

We are only doing that when we get a `mode` that is set to anything and we set it back properly.

**Comment by efiop** [comment]
Hm, I am not able to reproduce this locally though... Looking into it.

**Comment by efiop** [comment]
Yep, can confirm that removing `umask` call from daemon.py fixes the bug. @bjonnh Could you update the PR, please?
