### ISSUE TITLE
keep a human-readable changelog

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4023]
We need a better changelog. Current github release adds every PR to the changelog, plus it's not really structured, due to which it takes a long time to scan through and find out what's really changed.

I'd love to have one in the repo as well. 

One idea is to keep a changelog on `CHANGELOG.md`, and add an entry manually. Based on that, we can create Github releases automatically.
https://keepachangelog.com/en/1.0.0/

Another one could be, do whatever we do now, but add labels to the PR that'd generate better structure on Github releases changelog. So, `bugfix` label adds it to appropriate section, etc.
And, whenever we need to add/remove from changelog, we can do so manually.

Another one, maybe we have no perfect tooling  for this, but if we have, we could keep generate github releases from PR descriptions.

Or, add a bot everywhere that adds it to `CHANGELOG.md` automatically on each PR (or, on each PR merge) and even creates releases automatically.

**Comment by pared** [comment]
Another way to go would be to try doing it automatically using labels.
Sample: https://github.com/canonical-web-and-design/vanilla-framework/pulls?q=is%3Apr+is%3Aclosed
