### ISSUE TITLE
dvc: check all command usage and options vs docs after main 1.0 release

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4024]
After the top items (mission critical) in iterative/dvc.org/issues/1255 are done.

1. Check that docs reflect latest usage strings and options from core.
2. Open a PR here with any output string update written to the command references in docs.

Full sync!

**Comment by efiop** [comment]
@jorgeorpinel shouldn't this be in the docs themselves? This is unrealistic to check it twice. Let's create the tickets as we go.

**Comment by jorgeorpinel** [comment]
Yes you're right we need to do it in docs first. But when doing that some times the usage strings are improved so that's what I mean here. A full sync both ways.

Updated description and added checkbox in iterative/dvc.org/issues/1255.
