### ISSUE TITLE
Use a DVC command, but without having to change directories (like git -C <dir>)

### ISSUE THREAD

**Issue by dchichkov** [iterative/dvc#4025]
Similar to:  [ Starting git 1.8.5 (Q4 2013)](https://github.com/git/git/blob/5fd09df3937f54c5cfda4f1087f5d99433cce527/Documentation/RelNotes/1.8.5.txt#L115-L116), you will be able to "use a Git command, but without having to change directories.  Just like "make -C <directory>", "git -C <directory> ..." tells Git to go there before doing anything else.

Could a similar to Git and Make  '-C' option be added to DVC?   

The particular use case I have in mind, if DVC is used from Jupyter, spurious `%cd` -  add quite a bit of clutter:

```
   %cd  $datasets
   !dvc pull --force --recursive xxxx --quiet
   %cd -
```

You can end up in a wrong directory and then things fail.  Much nicer, if one will be able to write:

```
   !dvc -C $datasets pull --force --recursive xxxx --quiet
```

**Comment by efiop** [comment]
Hi @dchichkov !

Great request! We actually have one `-C` in `dvc repro`. It has been there for a long time, but we haven't heard any requests about other commands (nor about that one, really) ever, so it is interesting to get this feature request :slightly_smiling_face: The implementation should be pretty simple: we'd need to add `-C` to the parent parser and chdir in `dvc/command/base.py:CmdBase`.

Maybe you would like to give a shot implementing it? :slightly_smiling_face: We'll try to help with everything we can.

**Comment by JosephTLucas** [comment]
If @dchichkov doesn’tt want to implement, I’d like the chance.

**Comment by efiop** [comment]
@JosephTLucas Sounds great! Please feel free! :pray:
