### ISSUE TITLE
plots: make modify behave like config/remote modify

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#4048]
https://github.com/iterative/dvc/issues/3906#issuecomment-644282035

Currently `plots modify` has special flags to handle each option, which makes it quite confusing. Maybe option/value approach from `dvc config`, `dvc remote modify` and (now deleted, but will be re-introduced in the future)(`dvc metrics modify`) would be a better choice.

**Comment by dmpetrov** [comment]
We had a discussion with @Suor about a generalization of this approach - replacing the flags (or subset of the flags) by customer values that the user can define.

It is a great direction.
