### ISSUE TITLE
GitTree.walk() raises an error on a non-existing dir

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#4055]
This is inconsistent with `os.walk()`.

**Comment by pmrowla** [comment]
This is technically expected/documented in `BaseTree.walk` but we should probably just support `onerror` like `os.walk`

https://github.com/iterative/dvc/blob/5d957b18301efd4f51e594bc9e9d86d1bd951d33/dvc/scm/tree.py#L24-L30
