### ISSUE TITLE
v0: final release

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#4072]
There's a failing SSH test on the `0.94.0-dev` branch: https://travis-ci.com/github/iterative/dvc/jobs/348781315#L7880

Would be great to fix it so that a new (final) v0 release can be made to address #3872.

**Comment by efiop** [comment]
@casperdcl Not worth spending time on it.

**Comment by efiop** [comment]
You can release even with failing tests, if you restart the `deploy` jobs on travis (just click `restart` there)

**Comment by casperdcl** [comment]
last time I checked that wasn't possible. Admittedly a very long time ago.

So in that case can you create a new v0 release? That would start the clock for putting it to bed...

**Comment by skshetry** [comment]
@casperdcl, why do we need to release a `v0`? Does `snap` not allow these kind of changes?

**Comment by casperdcl** [comment]
I mean tagging & releasing `dvc==0.95.0` or similar from the current https://github.com/iterative/dvc/tree/0.94.0-dev

**Comment by efiop** [comment]
@casperdcl Will do in a sec.

**Comment by efiop** [comment]
@casperdcl https://travis-ci.com/github/iterative/dvc/builds/172217010

**Comment by efiop** [comment]
@casperdcl Looks like it is done. Closing for now. Let me know if something is off about the snap.

**Comment by casperdcl** [comment]
![image](https://user-images.githubusercontent.com/10780059/85142798-c9b5b000-b240-11ea-9ad0-75e2310c7d56.png)

Running

- `snap refresh dvc --channel=v0/stable`, or
- `snap refresh dvc --channel=latest/beta`

makes the message go away.

**Comment by efiop** [comment]
@casperdcl Amazing stuff! Thank you! :pray:

**Comment by casperdcl** [comment]
great; there are a couple of quick items in https://github.com/iterative/dvc/issues/3872 which we'll be able to check off in a month and then never mention this again :D
