### ISSUE TITLE
hooks: support subrepos

### ISSUE THREAD

**Issue by marcglobality** [iterative/dvc#4073]
### Please provide information about your setup

When having `.git` in a parent of the location where `.dvc` is, `dvc install` adds the hooks there (which is ok), but the hooks get confused as cannot find the `.dvc` directory

Is there a fix for this? it seems like a bug, but maybe haven't checked the documentation fully

**Comment by efiop** [comment]
Hi @marcglobality !

Which `$ dvc version` are you using?

**Comment by marcglobality** [comment]
DVC version: 0.94.0
Python version: 3.7.7
Platform: Darwin-19.5.0-x86_64-i386-64bit
Binary: False
Package: pip
Supported remotes: http, https, s3
Cache: reflink - supported, hardlink - supported, symlink - supported
Repo: dvc (subdir), git

**Comment by efiop** [comment]
@marcglobality Thanks! And what errors do the hooks generate? Could you also show `cat .git/hooks/post-checkout`, for example?

**Comment by marcglobality** [comment]
Structure of the project 

```
marc$ tree -a -L 2
.
├── .git
│   ├── COMMIT_EDITMSG
│   ├── HEAD
│   ├── config
│   ├── description
│   ├── hooks
│   ├── index
│   ├── info
│   ├── logs
│   ├── objects
│   └── refs
├── README.md
└── project
    ├── .dvc
    ├── .gitignore
    ├── text.txt
    └── text.txt.dvc
```

Here it's the one failing when called from inside `project`
```
marc$ cat ../.git/hooks/pre-push
#!/bin/sh
exec dvc git-hook pre-push $@
```

and here the error that is giving to me 

```
git push --set-upstream origin dvc
ERROR: you are not inside of a DVC repository (checked up to mount point '/')

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
error: failed to push some refs to 'git@github.com:marcglobality/marc-test-dvc.git'
```

**Comment by efiop** [comment]
@marcglobality Could you modify your pre-push hook to be:
```
#!/bin/sh
exec dvc git-hook pre-push -v $@
```
and share the log, please?

**Comment by marcglobality** [comment]
Sorry for the delay, here you have

```
(hack) Marcs-MacBook-Pro:project marctorrellassocastro$ git push --set-upstream origin dvc
2020-06-23 13:23:02,374 ERROR: you are not inside of a DVC repository (checked up to mount point '/')
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marctorrellassocastro/miniconda3/envs/hack/lib/python3.7/site-packages/dvc/main.py", line 48, in main
    cmd = args.func(args)
  File "/Users/marctorrellassocastro/miniconda3/envs/hack/lib/python3.7/site-packages/dvc/command/base.py", line 35, in __init__
    self.repo = Repo()
  File "/Users/marctorrellassocastro/miniconda3/envs/hack/lib/python3.7/site-packages/dvc/repo/__init__.py", line 76, in __init__
    root_dir = self.find_root(root_dir)
  File "/Users/marctorrellassocastro/miniconda3/envs/hack/lib/python3.7/site-packages/dvc/repo/__init__.py", line 145, in find_root
    raise NotDvcRepoError(message)
dvc.exceptions.NotDvcRepoError: you are not inside of a DVC repository (checked up to mount point '/')
------------------------------------------------------------

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2020-06-23 13:23:02,380 DEBUG: Analytics is enabled.
2020-06-23 13:23:02,442 DEBUG: Trying to spawn '['/Users/marctorrellassocastro/miniconda3/envs/hack/bin/python', '/Users/marctorrellassocastro/miniconda3/envs/hack/bin/dvc', 'daemon', '-q', 'analytics', '/var/folders/jk/fdqxg_9d3q1brtscpzs4fplw0000gn/T/tmp52t1nyer']'
2020-06-23 13:23:02,444 DEBUG: Spawned '['/Users/marctorrellassocastro/miniconda3/envs/hack/bin/python', '/Users/marctorrellassocastro/miniconda3/envs/hack/bin/dvc', 'daemon', '-q', 'analytics', '/var/folders/jk/fdqxg_9d3q1brtscpzs4fplw0000gn/T/tmp52t1nyer']'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
error: failed to push some refs to 'git@github.com:marcglobality/marc-test-dvc.git'
(hack) Marcs-MacBook-Pro:project marctorrellassocastro$ pwd
/Users/marctorrellassocastro/Globality/hackday/marc-test-dvc/project
```

**Comment by efiop** [comment]
@marcglobality Thanks! Ok, looks like we forgot to check if this is a git repo in pre-push hook. Preparing a fix...

**Comment by efiop** [comment]
@marcglobality But just to clarify: the current fix will just make our hooks do nothing when they detect that they are not in a repo, so they will be useless for your use case, so you might as well just uninstall them :(

But I suppose, the expected behaviour for you is for out hooks to do their things in all dvc repos inside of your git monorepo?

**Comment by marcglobality** [comment]
I guess the expected behaviour is to do the `dvc push` in the project where I am, not for all dvc repos in the git monorepo. If that's not possible, i would disable them but show a warning as it's not supported?

**Comment by efiop** [comment]
> I guess the expected behaviour is to do the dvc push in the project where I am, not for all dvc repos in the git monorepo. If that's not possible, i would disable them but show a warning as it's not supported?

Git hooks are always executed from git root, so that won't work. Warning is not possible too, because we don't discover subrepos for performance reasons. For now, I've just fixed those hooks to not run in non-dvc repo. In the future, we might support subrepos, but it requires a few other features related to subrepos before we could work on git hooks. :slightly_frowning_face:

**Comment by efiop** [comment]
Closing as stale.
