### ISSUE TITLE
dvc run does not recognize -n/--name option

### ISSUE THREAD

**Issue by saeedshojaee** [iterative/dvc#4077]
## Bug Report
This command produces the following error:
```console
$ dvc run \
-f plot.dvc \
-d create_plots.py \
-d prediction \
-d features \
-o plots/plot.pdf \
-o plots/plot_df.csv \
--verbose \
python create_plots.py
```
results in 
```console
ERROR: `-n|--name` is required 
```
I tried adding name but I got the same error.
```console
$ dvc run \
-f plot.dvc \
-d create_plots.py \
-d prediction \
-d features \
-o plots/plot.pdf \
-o plots/plot_df.csv \
-n features \
--verbose \
python create_plots.py
```
results in 
```console
ERROR: `-n|--name` is required 
```

**Output of `dvc version`:**

```console
$ dvc version
```
DVC version: 1.0.0
Python version: 3.7.7
Platform: Linux-5.4.0-37-generic-x86_64-with-Ubuntu-20.04-focal
Binary: False
Package: pip
Supported remotes: http, https
Cache: reflink - not supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('ext4', '/dev/nvme0n1p2')
Repo: dvc, git
Filesystem type (workspace): ('ext4', '/dev/nvme0n1p2')

**Comment by skshetry** [comment]
@saeedshojaee, `-f` is no longer supported in v1.0 for files, due to which `argparse` is going crazy on this.

Try:
```console
dvc run \
-d create_plots.py \
-d prediction \
-d features \
-o plots/plot.pdf \
-o plots/plot_df.csv \
-n features \
--verbose \
python create_plots.py
```

Note that the above command will create a multistage dvcfiles in `dvc.yaml` with something like this:
```yaml
stages:
  features:
    cmd: python create_plots.py
    deps:
    - create_plots.py
    - features
    - prediction
    outs:
    - plots/plot.pdf
    - plots/plot_df.csv
```

and, a corresponding `dvc.lock` file. The single-stage file `.dvc` file is not produced for `dvc run`, only for `dvc add/import`.

**Comment by saeedshojaee** [comment]
Thanks, I will close the issue.
