### ISSUE TITLE
trace dependencies in dvc run

### ISSUE THREAD

**Issue by utkarshsingh99** [iterative/dvc#4081]
https://docs.python.org/2/library/trace.html

`dvc run` requires the user to specify all the dependencies that will be required, that is, all the scripts that will be executed while running the main command.
What if we could find a way to automatically detect those dependency files?
Assuming all the files would be in Python, I think `trace` could be used when the command is being executed for the first time before adding them to the stage.

**Comment by efiop** [comment]
Hi @utkarshsingh99 .

That is a very interesting idea! Wouldn't it be too noisy to use everything reported by trace?

Related https://github.com/iterative/dvc/issues/1577

**Comment by efiop** [comment]
Closing as stale
