### ISSUE TITLE
run: hide --file and --single-stage

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4084]
## Report

Per https://github.com/iterative/dvc.org/pull/1420#discussion_r442644095:

--file is still in the help output of `dvc run -h`, mentions DVC-file (a concept we are removing), and makes no sense without --single-stage (which is hidden). Please hide both for now.

### Please provide information about your setup

DVC 1.0

**Comment by efiop** [comment]
@jorgeorpinel --single-stage is already hidden. `--file` will likely be used in the future, but could hide it for now. Will send an update.

**Comment by jorgeorpinel** [comment]
Thanks!
