### ISSUE TITLE
run: make -M and --plots-no-cache the default behavior?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4085]
I've noticed we use -M and --plots-no-cache most of the time in our examples throughout docs and other places (e.g. Get Started: iterative/dvc.org/pull/1472). Shouldn't those be the default behaviors with `-m` and `-p`? Seems like we expect users to version their metrics/plots files directly on Git themselves, since these are not large files you want to have to `dvc pull/push`.

**Comment by efiop** [comment]
@jorgeorpinel capital and lower letters are used because of the symmetry with `-o` and `-O`. I don't think it is worth changing, nor we really can do it right now. `-p` is taken by plots.

**Comment by jorgeorpinel** [comment]
Agree about -p but the point is that we seem to expect the base case for metrics and plots usage is that they are tracked by Git. So that should be the assumption of --metrics (-m) and --plots (no short flag or maybe -l). We would then need --metrics-cached and --plots-cached to enable DVC to track them instead.

**Comment by efiop** [comment]
@jorgeorpinel I agree, but changing the short options is not possible right now. We could get rid of -m and -M for now and force people to use `--metrics-cache` and `--metrics-no-cache`, but we will be revisiting stage creation in the future (e.g. `dvc stage create`), and it is probably better to just do that switch/redesign there.

**Comment by jorgeorpinel** [comment]
Cool. Is there an issue somewhere about `dvc stage` specs/ design? To note this 🙂

**Comment by efiop** [comment]
@jorgeorpinel I don't think we have a particular ticket for it, it is just in the discussion stage.
