### ISSUE TITLE
remove: remove dvc.yaml and dvc.lock if they are empty

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#4090]
https://github.com/iterative/dvc/pull/4074#issuecomment-648097445

```
$ cat dvc.lock
{}                                               
$ cat dvc.yaml
stages: {}                                       
```

**Comment by nik123** [comment]
The implementaiton of it seems quite straightforward. May I pick it up?

**Comment by efiop** [comment]
@nik123 Sure! Thank you so much for looking into it! :pray:
