### ISSUE TITLE
Support `dvc import --file`

### ISSUE THREAD

**Issue by pokey** [iterative/dvc#4093]
Currently, `--file` is supported on `dvc add` and `dvc import-url`, but not on `dvc import`.  This functionality would be useful for keeping `.dvc` files in a special place.

**Comment by efiop** [comment]
Hi @pokey ! Would you be willing to contribute a small PR for that? It is pretty trivial:

1) add `--file` to https://github.com/iterative/dvc/blob/master/dvc/command/imp.py#L66
2) pass self.args.file in https://github.com/iterative/dvc/blob/master/dvc/command/imp.py#L18
3) pass `fname=fname` to imp_url in https://github.com/iterative/dvc/blob/master/dvc/repo/imp.py#L6

:slightly_smiling_face:

**Comment by pokey** [comment]
Does look like a nice warm-up PR 😊.  Not a ton of time to knock it out but next time I find myself wanting that command maybe I'll take a crack at it
