### ISSUE TITLE
Retrive plots from run cache

### ISSUE THREAD

**Issue by pared** [iterative/dvc#4096]
reproduction script:

```
#!/bin/bash
rm -rf repo storage
mkdir repo
main=$(pwd)
set -ex
pushd repo
git init --quiet && dvc init --quiet

echo data >> data
dvc add data -q
dvc remote add -d str $main/storage
git add -A
git commit -am "initial"

echo "dvc.lock >> .gitignore"
dvc run -n make_result -d data --plots result.json python -c "import random,json;f=open('result.json', 'w');json.dump([{'val':str(random.random())}], f);f.close()"
dvc push

rm dvc.lock
rm result.json

# dvc repro make_result
dvc plots show -v
```
`result.json` is defined as plot from `make_result` stage. We get error when trying to plot it, but there is no problem plotting it if we `dvc repro make_result` first, retrieving it from run cache. We should check if we are able to retrive it from run cache when its not available right away.

EDIT:
need to check `metrics` too

**Comment by efiop** [comment]
@pared run cache is only used durring attempted execution. Metrics, params, plots don't use it directly and I'm not sure if they should, as that is too implicit and might be confusing.

**Comment by pared** [comment]
@efiop that makes sense.
I had an discussion with @dmpetrov that such functionality might come in hand, when we will get to experiments implementations, and will want to compare experiments results in order to choose the best. Currently, we would need to tie experiments to git revisions in order to be able to do that.
