### ISSUE TITLE
dvc checkout: create empty files if no cache

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#410]
This is an open question.

**Comment by efiop** [comment]
I don't think we should do that, sounds very counter intuitive to be honest. Unless I'm missing something.

**Comment by dmpetrov** [comment]
I agree. I just like to raise the question - we should be clear about this behavior.

`dvc checkout` outputs this correctly. But it looks like we need a better error message. And again, we probably need a special message for data sources.

```
$ dvc checkout
'data/matrix-train.p': cache file not found
'data/matrix-test.p': cache file not found
...
'data/Posts.xml.tgz': cache file not found
```

How about:
```
$ dvc checkout
'data/matrix-train.p': cache file not found. The file won't be created.
'data/matrix-test.p': cache file not found. The file won't be created.
...
'data/Posts.xml.tgz': data source is missing. Data source update is needed.
```

**Comment by efiop** [comment]
Sorry for such a late response, somehow totally missed this.

I agree that the msgs can be improved. I don't like the "Data source update is needed." one, as it introduces more confusion. I've created https://github.com/iterative/dvc/pull/824 that will change msg to: `Cache 'd3b07384d113edec49eaa6238ad5ff00' not found. File 'foo' won't be created.`.
