### ISSUE TITLE
`dvc pull` causes an error when there is an empty file in a remote

### ISSUE THREAD

**Issue by MGniew** [iterative/dvc#4104]
## Bug Report

Hi there, I hope I find you well :)
First of all, congratulation on a new release. It is absolutely awesome!

Recently I was working with a new dataset and the following error surprised me:
```
ERROR: failed to download 's3://blahblagh/myproject/d4/1d8cd98f00b204e9800998ecf8427e' to '.dvc/cache/d4/1d8cd98f00b204e9800998ecf8427e' - 'ContentLength' 
```
It turns out that one of my files was empty and therefore could not be downloaded from the remote host via https (S3).

**What is an issue:**

Empty files causes error when you are trying to download them from a remote.

**Steps to Reproduce:**

1. Initialize your git repo: `git init`
2. Initialize dvc: `dvc init`
3. Add a remote (I'm using Minio):

```
dvc remote add -d myremote s3://mybucket/path/to/dir
dvc remote modify myremote endpointurl https://object-storage.example.com
``` 
4. Create a directory with 2 example files:

```
mkdir data
echo "not empty" > data/not-empty.txt
> data/empty.txt
```
5. Upload them to the remote `dvc add data && dvc push`.
7. Files are now successfully uploaded. I can see them and download them manually from my remote storage.
6. Remove ./data and .dvc/cache
7. Try to download them: `dvc pull`

I dont think that this is an important bug (I simply found and deleted the empty file) but it might have other consequences that I can't think about.

**Output of `dvc version`:**

```console
$ DVC version: 1.0.1
Python version: 3.6.10
Platform: Linux-5.4.0-37-generic-x86_64-with-Ubuntu-20.04-focal
Binary: False
Package: pip
Supported remotes: http, https, s3
Cache: reflink - not supported, hardlink - supported, symlink - supported
Repo: dvc, git
```

**Additional Information (if any):**

It`s a KeyError exception:

```console
  File "..../venv/lib/python3.6/site-packages/dvc/remote/s3.py", line 333, in _download
    )["ContentLength"]
KeyError: 'ContentLength'
```

In case of lack of "ContentLength" header, it probably should assume it is 0 and create an empty file anyway.

**Comment by efiop** [comment]
Hi @MGniew ! Are you using genuine s3 or some s3-compatible storage?

**Comment by MGniew** [comment]
> Hi @MGniew ! Are you using genuine s3 or some s3-compatible storage?

Hi @efiop. Im using Minio (https://min.io/).

Also, Ive started to playing with DVC code myself and it is not only a remote/s3.py/_download:333 problem (this line is responsible for tqdm total parameter). KeyError also occurs in /s3transfer/download.py:346

**Comment by efiop** [comment]
@MGniew Got it. So genuine s3 doesn't have that bug, it is just a yet another minio discrepancy with s3. Could you open an issue in minio about it as well? As to dvc, I think we could totally handle that by just defaulting to 0 if we are not able to get ContentLength. Would you like to submit a PR for it? :slightly_smiling_face:

**Comment by MGniew** [comment]
> @MGniew Got it. So genuine s3 doesn't have that bug, it is just a yet another minio discrepancy with s3. Could you open an issue in minio about it as well? Maybe that's something that they would want to fix on their end as well.
> 
> As to dvc, I think we could totally handle that by just defaulting to 0 if we are not able to get ContentLength. Would you like to submit a PR for it? slightly_smiling_face

@efiop I will try first to reproduce this issue with publicly available minio server (https://play.min.io) to make sure it is not a minio's version issue (mine is from 2 months ago). Thank you for your help :) 

Also sorry for closing/reopening this issue - missclick

**Comment by MGniew** [comment]
Ok, so I've try to reproduce this issue on https://play.min.io and it worked! Then I've updated my Minio server and it also worked!
I should have thought about it before I submitted this issue... Sorry for the false alarm and thank you for your support :100: 

I'm closing this issue and the PR.

**Comment by efiop** [comment]
@MGniew Great news! :tada: Thank you for reporting the issue, maybe someone else will run into it and will find this info useful :slightly_smiling_face:
