### ISSUE TITLE
dvc.yaml pipelines groupings

### ISSUE THREAD

**Issue by sdelo** [iterative/dvc#4118]
At the moment there is no way to visualize pipeline groupings in the dvc.yaml file. It would be nice to have multiple names lists (pipelines) under the stages.

**Comment by skshetry** [comment]
@sdelo, does `dvc dag` work for you? 
Another question, will  having a separate file for each pipelines work (one `dvc.yaml-like file for one pipeline)?

**Comment by shcheklein** [comment]
@sdelo btw, as a workaround you can group them using directories as far as I know:

```
classifier/dvc.yaml
scraper/dvc.yaml
```

**Comment by sdelo** [comment]
Yes `dvc dag` will work. Also how do I specify the file location for the dvc.yaml so I can group them by directory? Is it just dependent on where I execute `dvc run`?

**Comment by efiop** [comment]
@sdelo Yes, it just creates it in the current directory. If you need to run your script from some other dir, just use `--wdir` to specify that.
