### ISSUE TITLE
Newlines after dvc metrics diff

### ISSUE THREAD

**Issue by andronovhopf** [iterative/dvc#4123]
I am working on printing `dvc metrics diff --show-md` into a markdown document, i.e....

`dvc metrics diff --show-md >> doc.md`

 and if I don't manually follow this command with a newline:
`echo >> doc.md`

Then everything that follows in `doc.md` gets inserted into the table. Is there maybe a newline character missing from the metrics .md table?

**Comment by efiop** [comment]
@andronovhopf Indeed, md table is not complete without the trailing newline, which is a bit non-intuitive when compared to regular cli workflow (at least for me), but it totally makes sense to make this right. Looks like right now only cml is using this feature, so not too worried about breaking something for someone else. Will send a fix ASAP.

**Comment by efiop** [comment]
Hm, though it would still feel a bit weird when the table is the last thing in the file and you have a trailing newline for no reason. :thinking:

**Comment by efiop** [comment]
Also, not using a trailing newline means that you could expand the table on-the-fly. But that's a feature no one has asked for :smile:

**Comment by andronovhopf** [comment]
hahaha yes! I think the "extra newline if the table is the last thing in
your report" is probably only a minor weirdness. i imagine (although can't
be positive yet) that more people will have to debug "why is everything
getting sucked into my table?" than "why is there an extra line after my
table?"
