### ISSUE TITLE
Consider removing the support link from the CLI output

### ISSUE THREAD

**Issue by honnibal** [iterative/dvc#4126]
This is definitely a matter of opinion, but I wanted to raise my own reaction and see how others feel.

Personally, I _hate_ the support link that's printed after every error, so much so that I'm thinking of making myself an alias or something that strips it out.

The message is uninformative, especially after the first time it's shown. It also really feels out of place for an open-source tool. As a user I might write a dozen commands in a few minutes that each end with exit 1. So my screen is just full of this message, `Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!`, over and over again. This quickly creates quite the opposite feeling from what you're going for.

Anyway, this is definitely subjective, and it intersects with strategic considerations etc. So, up to you! But I thought I'd at least mention my reaction to it.

**Comment by efiop** [comment]
Hi @honnibal !

Indeed, printing the footer on every error might be a bit too much. I think we could safely switch to printing it only on unexpected errors. So we would move https://github.com/iterative/dvc/blob/83a2afc7b05e38014aca224ab85949b0974d9bec/dvc/main.py#L94 to around https://github.com/iterative/dvc/blob/83a2afc7b05e38014aca224ab85949b0974d9bec/dvc/main.py#L80 . What do you think?

**Comment by honnibal** [comment]
I think that sounds like a good step, sure! After all, most of my errors will be things like getting a URL or a path wrong. It doesn't make sense to be told about support in these situations.
