### ISSUE TITLE
conf: credentialpath is not recalculated when it's a relpath

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#4136]
This one supposed to be relative to config file and converted to absolute and back on config load/save. This is done for `cache.dir`, local urls and `gdrive_user_credentials_file`, but not for `credentialpath`, which is used in s3 and gs.

Example: `cache.dir` - https://dvc.org/doc/command-reference/cache/dir#description.

**Comment by damakuno** [comment]
@efiop @Suor can I work on this issue?

**Comment by godfryd** [comment]
@efiop I started looking into this.

**Comment by shcheklein** [comment]
@damakuno thanks 🙏 to clarify, we discussed this with @godfryd offline a while ago and he had agreed to take a look. Could you please find another ticket? Let me know if you need my help on this.

**Comment by damakuno** [comment]
@shcheklein alright,  I'll look for another ticket then 👍
