### ISSUE TITLE
Developping a workflow for simultaneous work

### ISSUE THREAD

**Issue by bjonnh** [iterative/dvc#4162]
The idea would be to provide guidance to users in order to optimize parallel work to avoid conflicts when pushing on the same repository.

There are two aspects to that issue:
- organizational: what would be the workflow that would reduce chances of getting conflicts
- technical: can we make tools that would ease such conflicts

Organizational tools:
- a document that provides an example problematic workflow and how it can be overcome

Technical tools:
- a tool that would allow to merge two versions of dir contents  (could it work like a git rebase?)

**Comment by efiop** [comment]
Discord context: https://discordapp.com/channels/485586884165107732/485596304961962003/728651039657558066

Possible solution: git merge driver.

**Comment by efiop** [comment]
Hi @bjonnh !

We've added a git merge-driver (released in dvc 1.6.0) that should help with append-only datasets and created a doc about merge conflicts in general https://dvc.org/doc/user-guide/merge-conflicts (the recipe for setting up our merge-driver is there as well). Please take a look and let us know what you think :slightly_smiling_face:

**Comment by bjonnh** [comment]
This is really nice! Thanks for all your work we'll try that on our repositories see how that goes.

**Comment by efiop** [comment]
Closing for now. Feel free to reopen if you'll have a chance to give it a try and will have any feedback. :slightly_smiling_face:
