### ISSUE TITLE
import: same command creates .dvc file in different locations

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#4169]
## DVC Version

```console
~/example-get-started$ dvc version
DVC version: 1.0.1
Python version: 3.7.1
Platform: Linux-4.15.0-88-generic-x86_64-with-debian-buster-sid
Binary: True
Package: deb
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache: reflink - not supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('ext4', '/dev/mapper/host01--vg-root')
Repo: dvc, git
Filesystem type (workspace): ('ext4', '/dev/mapper/host01--vg-root')
```

## Reproduce

Run the same command:

`dvc import https://github.com/iterative/dataset-registry get-started/data.xml -o data/data.xml`

when `data` directory exists and when it does not.

In the first case we get:

```console
Importing 'get-started/data.xml (https://github.com/iterative/dataset-registry)' -> 'data/data.xml'

To track the changes with git, run:

        git add data/data.xml.dvc
```

In the second case:

```console
Importing 'get-started/data.xml (https://github.com/iterative/dataset-registry)' -> 'data/data.xml'

To track the changes with git, run:

        git add data.xml.dvc data/.gitignore
```

**There are two bugs:**

- [ ] It creates `data.xml.dvc` in different locations (`data/data.xml.dvc` vs `data.xml.dvc`)
- [x] It doesn't mention `.gitignore` in the first case in the `git add` hint.

**Comment by efiop** [comment]
> It creates data.xml.dvc in different locations (data/data.xml.dvc vs data.xml.dvc)

Good catch!

>  It doesn't mention .gitignore in the first case in the git add hint.

Works for me, I suppose you just had gitignore entry before that (probably from the previous run).

**Comment by shcheklein** [comment]
> Works for me, I suppose you just had gitignore entry before that (probably from the previous run).

yep, confirmed.
