### ISSUE TITLE
Different Versions from Different Install Methods

### ISSUE THREAD

**Issue by Robbie-Palmer** [iterative/dvc#4171]
I'm installing DVC on Linux (Ubuntu v18.04)
When I install DVC via conda `conda install -c conda-forge dvc` I get version `1.1.7`
When I install from repository I get version `1.0.1` following the [Linux install from repository steps](https://dvc.org/doc/install/linux#install-from-repository)
```
sudo wget \
       https://dvc.org/deb/dvc.list \
       -O /etc/apt/sources.list.d/dvc.list
sudo apt update
sudo apt install dvc
```

**Comment by efiop** [comment]
Hi @Robbie-Palmer !

Thanks for the feedback! Indeed, we had some delay in uploading deb/rpm packages, but it is fixed now. Please give it a try.
