### ISSUE TITLE
plots diff/show: `--open` flag to directly open it in the default browser

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4179]
As the title says

**Comment by efiop** [comment]
Context https://github.com/iterative/dvc/issues/4158#issuecomment-655314446

**Comment by efiop** [comment]
Might be easier to just click the link than use that flag, but we might consider doing that by default when in interactive mode. Not sure.

**Comment by skshetry** [comment]
Using :computer_mouse: is quite an effort. You have to hover it to the location of the link, and then Ctrl-Click it. Quite a hassle. :smile: 
And, not everyone's terminal is nice enough to support that.
