### ISSUE TITLE
DAG with inputs/outputs?

### ISSUE THREAD

**Issue by WestXu** [iterative/dvc#4181]
A full DAG like dagshub will be just really cool and informative. 

https://dagshub.com/Guy/pipeline-intermediate-files-example

**Comment by pared** [comment]
I think this is duplicate: 
https://github.com/iterative/dvc/issues/1065

**Comment by pared** [comment]
@WestXu Can I ask you to upvote #1065?

**Comment by WestXu** [comment]
@pared Oops, sorry missed that one somehow.

**Comment by pared** [comment]
@WestXu no problem, sometimes it's hard to pinpoint if the issue already exists :)
