### ISSUE TITLE
Running tests pollutes workspace

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4182]
Looks like `http` server for tests is to blame? Refer 07da9f1

```console
$ pytest > /dev/null
$ git status -s
? 0910e8b7-52b1-4bc8-ae0c-eef57062da8e/
?? 0c355f19-5da9-46a8-9753-1e8245220b02/
?? 3c900c05-c66c-4886-96da-cf13234079f8/
?? f1b4994c-2171-42fe-80b9-b51f5139e9f3/
```

**Comment by efiop** [comment]
Hm, not able to reproduce. @skshetry Could you give it another try, please?

**Comment by efiop** [comment]
For the record: discussed with @skshetry and turns out it is python 3.6. So my hack in https://github.com/iterative/dvc/blob/master/tests/utils/httpd.py#L15 doesn't work. Looking into it.
