### ISSUE TITLE
dvc get --rev doesn't work if master is not a dvc repo

### ISSUE THREAD

**Issue by jackspitts** [iterative/dvc#4188]
### Please provide information about your setup

**Output of `dvc version`:**

```console
DVC version: 1.1.7
Python version: 3.7.2
Platform: Darwin-18.7.0-x86_64-i386-64bit
Binary: False
Package: pip
Supported remotes: http, https, s3
Cache: reflink - supported, hardlink - supported, symlink - supported
Repo: dvc, git
```

**Additional Information (if any):**

Discord link with all info

https://discordapp.com/channels/485586884165107732/485596304961962003/731227119954427904

**Comment by efiop** [comment]
For the record: the issue is that in external repo we operate on virtual trees(we don't checkout to the branch), but we still read config through regular open() calls, which is causing this issue. Need to make our config use repo's `self.tree` to read/write configs.

**Comment by efiop** [comment]
@jackspitts 1.1.9 is out with the fix. Please upgrade and give it a try :slightly_smiling_face: Thanks for the feedback!

**Comment by jackspitts** [comment]
@efiop Upgraded and `dvc get --rev` works like a charm. Thanks for the quick turn around!
