### ISSUE TITLE
status: change "changed checksum" state to "changed command"

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4189]
## Report

> Extracted from https://github.com/iterative/dvc.org/pull/1384#pullrequestreview-446033807

The _changed checksum_ status (which only applies to .dvc files, mostly for backward compatibility purposes) should be called something else probably, maybe _changed command_. Something that reflects better what the change or state is.

### Please provide information about your setup

DVC 1.1

**Comment by jorgeorpinel** [comment]
P/s addressing this will imply a small change to the `status` cmd ref in the docs.

**Comment by efiop** [comment]
> The changed checksum status (which only applies to .dvc files, mostly for backward compatibility purposes) should be called something else probably, maybe changed command. Something that reflects better what the change or state is.

There is no command in `.dvc` files created by `add` and `import[-url]`. So current `changed checksum` still makes sense.

**Comment by jorgeorpinel** [comment]
OK. But .dvc files no longer store their own checksums, right? Also, the term we use is "file hash" or sometimes "hash value". `checksum` was deemed inaccurate, and refers only to HDFS external deps/outs now.

P/s I opened this issue per your https://github.com/iterative/dvc.org/pull/1384#issuecomment-656381385, Ruslan 🙂 so up to you if you want to close it.

**Comment by efiop** [comment]
> OK. But .dvc files no longer store their own checksums, right?

`dvc import[-url]`ed do store checksums.
