### ISSUE TITLE
TLDR for DVC [https://github.com/tldr-pages/tldr]

### ISSUE THREAD

**Issue by PuneethaPai** [iterative/dvc#4194]
Can we think of creating TLDR for dvc and all it's sub commands??
---

[TLDR cmd](https://github.com/tldr-pages/tldr):
Given a command tldr gives list of it's comman usage pattern to get started quick. 

### For example: GIT _which is closest to dvc_:
```bash
~ tldr git

git

Distributed version control system.
More information: <https://git-scm.com/>.

- Check the Git version:
    git --version

- Call general help:
    git --help

- Call help on a command:
    git help command

- Execute Git command:
    git command
```

```bash
 ~ tldr git pull

git pull

Fetch branch from a remote repository and merge it to local repository.
More information: <https://git-scm.com/docs/git-pull>.

- Download changes from default remote repository and merge it:
    git pull

- Download changes from default remote repository and use fast forward:
    git pull --rebase

- Download changes from given remote repository and branch, then merge them into HEAD:
    git pull remote_name branch
```

```bash
~ tldr git add

git add

Adds changed files to the index.
More information: <https://git-scm.com/docs/git-add>.

- Add a file to the index:
    git add path/to/file

- Add all files (tracked and untracked):
    git add -A

- Only add already tracked files:
    git add -u

- Also add ignored files:
    git add -f

- Interactively stage parts of files:
    git add -p

- Interactively stage parts of a given file:
    git add -p path/to/file

- Interactively stage a file:
    git add -i
```

**Comment by PuneethaPai** [comment]
Happy to give it a shot, if makes sense. :)

**Comment by efiop** [comment]
@PuneethaPai Looks very cool! Sure, please feel free to give it a shot! :pray:

**Comment by PuneethaPai** [comment]
@efiop 

Here is linked pull request: https://github.com/tldr-pages/tldr/pull/4225
I have started work on it. Completed creating pages for 13 sub commands.
I still have like 33 more to go 😜 .

**Comment by PuneethaPai** [comment]
How tldr works is like we have to generate `cmd.md` files **keeping in mind first time user**.
What I can think of for automation is, we can go up to generating these files and raising Pull Request. 
After which we/they can quickly validate and merge it. 

Let me know if there are better ways. We still need to figure out how to generate the pages.

**Comment by efiop** [comment]
Closing as stale.

**Comment by efiop** [comment]
Rushed with the closing. Looks like there is a pretty clear list of next steps. Keeping open for now.

**Comment by efiop** [comment]
Closing as stale after all.
