### ISSUE TITLE
dvc add: .dvcignore example not working as expected [qa]

### ISSUE THREAD

**Issue by utkarshsingh99** [iterative/dvc#4197]
![Screenshot from 2020-07-13 00-44-27](https://user-images.githubusercontent.com/32031518/87254720-299b2180-c4a2-11ea-9bb6-d4a67ff4e502.png)

I was following this [example](https://dvc.org/doc/command-reference/add#example-dvcignore) and it does detect changes in the file in dvc.

DVC Version: 1.1.9 (virtualenv)

I'm not sure if this is a bug in the .dvcignore feature of DVC itself, or rather just a mistake on my part. Thus, opening the issue here and not in the orig DVC repo.

P.S.: The `dir/file1` already had its content as file_one_changed and that's why there is no change detected in the first `dvc status` command

**Comment by shcheklein** [comment]
@pared could you take a look and confirm is it an example or DVC core problem?

**Comment by pared** [comment]
So the problem of `file1` getting added to cache, even though it is ignored is related to: https://github.com/iterative/dvc/issues/4110 and https://github.com/iterative/dvc/pull/4125
taking care of it.

**Comment by pared** [comment]
@utkarshsingh99 The fix for this issue has been merged. New release should be available soon.
