### ISSUE TITLE
Repo cache?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4203]
DVC clones the `url` repo whenever `list`, `get`, or `import` are used. This is done over and over again — particularly noticeable when browsing files with `dvc list`. Sometimes this takes a while, depending on the repo.

What about a mechanism to store cloned repos somewhere in the user files? I think a user-wide cache would be appropriate (instead of project-wide).

**Comment by skshetry** [comment]
We already have an opened issue regarding this on https://github.com/iterative/dvc/issues/3496.

**Comment by jorgeorpinel** [comment]
OK so this is a dupe! Thanks
