### ISSUE TITLE
metrics diff: accept multiple revisions (like plots diff)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4211]
Context: https://discuss.dvc.org/t/fill-back-metrics/441

> Related: https://github.com/iterative/dvc/issues/4210

**Comment by dmpetrov** [comment]
It should be a separate command like `dvc experiment show HEAD HEAD^ ab3132d`
It might be a part of #2799

**Comment by jorgeorpinel** [comment]
Will metrics and plots be combined into that single command?

**Comment by efiop** [comment]
@jorgeorpinel Yes, in the experiments.

**Comment by jorgeorpinel** [comment]
I guess it can be considered a duplicate of #4210 — I opened this from the same context.

**Comment by efiop** [comment]
> Will metrics and plots be combined into that single command @dmpetrov ?

@jorgeorpinel Yep, it is alredy in a hidden `dvc experiments show/diff`.

**Comment by jorgeorpinel** [comment]
Nice. But that will replace metrics and plots? (just to be extra clear)

**Comment by efiop** [comment]
@jorgeorpinel It won't, it will be an addition.
