### ISSUE TITLE
Make `dvc pull --run-cache` allow `targets` for a granular pull process

### ISSUE THREAD

**Issue by maricatovictor** [iterative/dvc#4223]
Right now, if I do 

`dvc pull [target]`
this will pull *only* the `target` I am interested in.

However, if I do `dvc pull --run-cache [targets]`
the `target` is ignored, *everything* is pulled from remote. Not even a warning is thrown that `--run-cache` does not accept granularly pulling files.

This is based on https://discuss.dvc.org/t/dvc-pull-run-cache-target/444 discussion

**Comment by efiop** [comment]
For the record: `--run-cache` flag is just a temporary solution and is not meant to accept targets. We will likely just support `dvc pull target` that will then somehow look into the run-cache by itself and pull by itself or suggest a hint on how to do it. run-cache is really an implementation detail that should be hidden away. We need to take a closer look at this.

**Comment by maricatovictor** [comment]
Oh, ok. Is there any kind of estimative on this being prioritized? 

As described in the forum, I was planning to use `--run-cache` as a workaround for deploying models, but the lack of targets selection makes it impossible.

**Comment by efiop** [comment]
Hi @maricatovictor ! Sorry for the delay. We've added this task to the next sprint (starting next week).
