### ISSUE TITLE
Katacode - stages interactive tutorial

### ISSUE THREAD

**Issue by yevgenypats** [iterative/dvc#4231]
## Bug Report

There is a bug in the stages tutorial https://katacoda.com/dvc/courses/get-started/stages, step-2 doesn't really work as
`prepare.dvc` is missing and probably dvc api was changed a bit so it is also expecting `-n` parameter which is not provided.

**Comment by shcheklein** [comment]
Closing this a duplicate https://github.com/iterative/dvc.org/issues/1586 . Sorry for the inconvenience, we are still in the process of updating our docs and tutorials after DVC 1.0 release.
