### ISSUE TITLE
safe `Dvcfile.dump()`

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4235]
Initially, the idea was not to touch `dvc.yaml` at all, but as we are doing it quite often, it's better to protect `dvc.lock` rather than `dvc.yaml` by default.
So, we could change it to the following default:
```py
def dump(pipeline=True, lock=False):
    pass
```

The only place where we need to update `lock` are `dvc repro` and `dvc run`, at least atm.

_Originally posted by @skshetry in https://github.com/iterative/dvc/pull/3994#discussion_r437529134_

**Comment by efiop** [comment]
@skshetry Is this something that you are tackling right now(judging by the assignee)? If not, could you please elaborate a bit more? Also, please feel free to set appropriate labels.

**Comment by skshetry** [comment]
I'm not working right now, but something that I'd like to tackle next. 
https://github.com/iterative/dvc/pull/3994#discussion_r437529134 should have enough context about the issue.

**Comment by efiop** [comment]
@skshetry What about labels then?
