### ISSUE TITLE
tests failing when not using venv and behind a firewall

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#4241]
## Bug Report

Four `pytests` failed

### Please provide information about your setup

**Output of `dvc version`:** 1.1.11

```console
$ dvc version
```

**Additional Information (if any):**

from https://discord.com/channels/485586884165107732/565699007037571084/734402524869820436

1. I didn't use a `virtualenv`
2. I'm behind the great girewall which blocks google.

logfile:

[logfile.txt](https://github.com/iterative/dvc/files/4943766/logfile.txt)

If applicable

, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by efiop** [comment]
pytest-servers should be able to handle this these days.
