### ISSUE TITLE
Add support for PUT method for remote http storage

### ISSUE THREAD

**Issue by em2er** [iterative/dvc#4248]
Binaries management web-services such as Artifactory or Sonatype Nexus use PUT method to deploy file over http. For now, dvc supports only POST method. It would be great if some kind of support of PUT method added. For example, by adding parameter 'method' to config:

```
dvc remote add -d origin https://artifactory.company/artifactory/dvc-local/
dvc remote modify origin http_method put
```

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/485596304961962003/734834300867838032

**Comment by em2er** [comment]
I've just replaced POST with PUT https://github.com/iterative/dvc/blob/b77ce02f6b7f66efa9fc73b7146f1c4bf4fa6da3/dvc/tree/http.py#L184 locally and it works fine with Artifactory

**Comment by efiop** [comment]
For the record: probably the best choice is to try `PUT` by default and fallback to `POST` if it is not supported (405 code).

**Comment by shcheklein** [comment]
@efiop this way we'll be doing a lot of extra operations? or should we try once and remember the choice?

**Comment by efiop** [comment]
@shcheklein  Remember the choice, yes.

**Comment by ClementWalter** [comment]
I plan to use artifactory with dvc, still required? I could work on it ASAP

**Comment by skshetry** [comment]
Closing as this is already implemented on https://github.com/iterative/dvc/pull/4553.

The http method could be modified as follows:
```console
dvc remote modify myremote method PUT
```

Please check the docs for more information: https://dvc.org/doc/command-reference/remote/modify#available-parameters-per-storage-type
