### ISSUE TITLE
plots: support multiple Y fields? [qa]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4255]
Let's say I have a tabular plots file `plot.csv`:
```csv
h1,h2,h3
1,1,0
2,2,0
3,4,-1
4,8,7
```
and I want to overlay all 3 Hs in a single graph. I can't. I have to pick one at a time, e.g.:
```console
$ dvc plots show -y h2 plot.csv
```
In fact even with `plots diff` there's no way to visualize these columns in a single graph (the file would have to be split into 3, each one versioned in a different commit). So what if `-y` simply accepted multiple field names (or `plots diff` accepted multiple`-y` flags)? E.g.:
```console
$ dvc plots show -y h1,h2,h3 plot.csv
# or
$ dvc plots show -y h1 -y h2 -y h3 plot.csv
```
---
In fact this could also apply to `-x`. But it could only be done with one or the other, not both (to keep things relatively simple).

**Comment by jorgeorpinel** [comment]
Cc @dmpetrov

**Comment by jorgeorpinel** [comment]
Motivation: deep learning or other scenarios where a single stage generates multiple results that need to be evaluated. The user would program the stage to output a single plots file with multiple columns in order to compare many variations. (This is a different option for experiments that doesn't need either run-cache nor multiple commits.)

**Comment by jorgeorpinel** [comment]
Of course it won't be very helpful to plot more than 4 or 5 lines in our little Vega graphs, so not 100% sure this has a real application. I just think it's a kind of intuitive feature to add.

**Comment by efiop** [comment]
Closing for now as stale
