### ISSUE TITLE
Bash and zsh completion for dvc

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#426]

**Comment by efiop** [comment]
Leaving for the next release. Also need to support Powershell.

**Comment by mroutis** [comment]
@efiop, is anyone working on this? I could help with the Zsh one

**Comment by efiop** [comment]
No one is working on it yet. It would be amazing if you could take a look! Let me know if you need anything!

**Comment by shcheklein** [comment]
I would also drop some comment here as well - https://dvc.org/doc/get-started/install

**Comment by efiop** [comment]
Created ticket on dvc.org. Closing.
