### ISSUE TITLE
`ignore-check` for DVC?

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#4260]
In #4249 #4110 #4103 etc. We need to check if some files were ignored or not.
Current solutions are something like, 
```
python -c "from dvc.repo import Repo;print(list(Repo().tree.walk_files('data')))"
# or 
dvc pull -v subdata1.dvc | grep "xml"
# etc. 
```
These unofficial usages are neither elegant nor detailed. While a `git ignore-check` can tell you which pattern matches and finally influences your file.
![image](https://user-images.githubusercontent.com/6745454/88172708-fbf96980-cc53-11ea-8ba9-aa36c194a7f2.png)
This is helpful when we are writing some complex `.dvcignore` patterns or debugging.

**Comment by skshetry** [comment]
@karajan1001, is this the duplicate of #3736?

**Comment by karajan1001** [comment]
@skshetry Haha, I didn't know there already has been one.
