### ISSUE TITLE
remote local config does not see existing remote

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#4276]
### Please provide information about your setup

**Output of `dvc version`:**

```console
DVC version: 1.1.10+1c9588
Python version: 3.8.4
Platform: macOS-10.15.4-x86_64-i386-64bit
Binary: False
Package: None
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Repo: dvc, git
Filesystem type (workspace): ('apfs', '/dev/disk1s1')
```

**Additional Information (if any):**

```
dvc remote add -d storage s3://storage
dvc remote modify storage region us-east-2 --local
```

complains:

```
ERROR: configuration error - config file error: remote 'storage' doesn't exists.
```

For example, it breaks the use case of using `dvc remote modify` to store credentials in the local config only.

**Comment by efiop** [comment]
This one is a known issue since the config refactor. Workaround is to simply first do:
```
dvc remote add storage s3://storage --local
```

**Comment by shcheklein** [comment]
just to let you know this breaks all the docs/examples
