### ISSUE TITLE
gdrive: failed to pull empty file

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#4286]
CC @imflash217  and @we-taper 

https://github.com/iterative/dvc/issues/1376#issuecomment-664004339

**Comment by efiop** [comment]
Looks like ideally this should be solved on PyDrive2 side... Looking into it...

**Comment by efiop** [comment]
Guys, could you try installing a dev version with
```
pip install git+https://github.com/iterative/dvc@fix-4286
```
and giving it a try, please?

**Comment by we-taper** [comment]
I gave it a ago and it seemed to works. Thanks @efiop !

**Comment by efiop** [comment]
@we-taper Thanks for the feedback! In the interest of time, I'll merge and release that workaround (1.2.3, will be ready in half an hour), but will continue with a proper fix on PyDrive2 side in https://github.com/iterative/PyDrive2/pull/48
