### ISSUE TITLE
http: do not ignore HTTP statuses when working with HTTP(S) remotes

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#4288]
On master.

Exists check now simply says yes if request is successful. So If we get 403 Forbidden or 401 Auth Required these are ignored, which looks the same as absent files to dvc. The simplest fix would be using `res.raise_for_status()` in `.exists()` check unless we have success or 404.

**Comment by Suor** [comment]
BTW, we already do something like that in `utils.http.iter_url()`.

**Comment by damakuno** [comment]
Does this still need to be worked on? If so can I work on this? I'll need some guidance on where to start.

**Comment by efiop** [comment]
@damakuno Sure! The above comment is talking about https://github.com/iterative/dvc/blob/0669d8d885307edff8971c75ee569baf6f65450c/dvc/tree/http.py#L143 .

**Comment by damakuno** [comment]
Noted, I can add more functional tests to `dvc/dvc/tests/funct/test_tree.py` to verify that it's raising Exceptions as intended yeah? Now I'm wondering how to initialize a http remote to perform the test though...

**Comment by efiop** [comment]
@damakuno Simple unit test would be enough, no need for a functional one :slightly_smiling_face: It would be added to tests/unit/remote/test_http.py .
