### ISSUE TITLE
Add argument --user -u for specifying  a user credential

### ISSUE THREAD

**Issue by davebulaval** [iterative/dvc#4291]
As one can have many AWS credentials, you need to `export AWS_PROFILE=user1` (Linux/Mac) for using the right credentials. Could be interesting to have something similar directly in the DVC commands. 

Here the [doc](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) for AWS but I don't know for the other storage option.

**Comment by efiop** [comment]
Hi @davebulaval You can specify it in your config. E.g.
```
dvc remote modify myremote profile myprofile --local
```

**Comment by davebulaval** [comment]
The command does not work even if a setted a local config file.

**Comment by efiop** [comment]
@davebulaval What do you mean? The command itself? Or push/pull?

**Comment by davebulaval** [comment]
@efiop The command itself.

Here the error `ERROR: configuration error - config file error: remote 'storage' doesn't exists.`

Here my .dvc repo:

```
.dvc
├── cache/
├── config
├── config.local
├── plots/
└── tmp/
```

DVC version: `1.2.1`

**Comment by efiop** [comment]
@davebulaval Ah, that's because of a well known `--local` bug (working on solving it). Current workaround is to first:
```
dvc remote add myremote s3://bucket/path --local   # yes, in addition to what you've already added without --local
dvc remote modify myremote profile myprofile --local
```
or you could just add the profile to .dvc/config by:
```
dvc remote modify myremote profile myprofile
```

**Comment by davebulaval** [comment]
Worked like a charm, that solution should be in the documentation (or is it already ?)

**Comment by efiop** [comment]
@davebulaval `profile` is already in the docs https://dvc.org/doc/command-reference/remote/modify .

**Comment by davebulaval** [comment]
@efiop Yes, but not as clear as explain using this issue. I could not come with that solution using the doc.

**Comment by efiop** [comment]
@davebulaval Not quite sure how to improve it :( Would appreciate any ideas.

**Comment by davebulaval** [comment]
@efiop I will think about it and propose a PR this weekend.
