### ISSUE TITLE
repro: enforce targets (and update desc) when -R is present? [qa]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4292]
The `-R` option of `dvc repro` has no effect when no `targets` that are directories are also given. For example, `dvc repro -R` is the same as just `dvc repro`. For UI and consistency improvement I propose
1. - [ ] `targets` are enforced when `-R` is used, or at least WARN msg is printed otherwise so the user is aware he might be expecting something that's not being done.
2. - [ ] Even if `targets` are given, at least one of them should be an existing directory path, or the above enforcement/warning will happen.
3. (This may already be the case) if the target directory has no .dvc files or dvc.yaml, print a separate warning about that?

> UPDATE: See https://github.com/iterative/dvc/issues/4292#issuecomment-664710105 below for an alternative solution — maybe easier.

---
THE REMAINING TEXT HAS BEEN EXTRACTED TO #4393 (so stop reading)

Separately (but related), the `targets` param accepted by `dvc repro` is described (in its help output) as `Stages to reproduce. 'dvc.yaml' by default.` This message is confusing as dvc.yaml is not a stage. In docs we're using `Stage or .dvc file to reproduce` but that's not correct either because apparently paths to dvc.yaml files are also accepted.

- Should we use `Stage or path to dvc.yaml or .dvc file to reproduce` instead?
- ^ still doesn't cover the case of accepting directory paths with -R, but that we can explain in that argument's description:
```diff
-  -R, --recursive       Reproduce all stages in the specified directory.
+  -R, --recursive       Reproduce all stages in the specified directories.
+                        These can be given as `targets` arguments.
```
and I'll explain this special case further in the cmd ref. **Options**.

**Comment by jorgeorpinel** [comment]
> ii. Separately (but related)

Should I extract this to a separate issue?

**Comment by jorgeorpinel** [comment]
> 1. For UI and consistency improvement I propose...

An alternative to this, as I discussed with @efiop, is to make -R accept an argument, instead of relying on `targets`. His answer was that it's still basically a target so why not just use the command's argument(s), which was convincing. However, I just noticed that the `-c` option does accept a `<path>` argument (specifically for directories), so maybe after all (for consistency) the best option is to add an arg to -R, instead of points 1-3 above (and apply the logic to that arg).

**Comment by efiop** [comment]
> However, I just noticed that the -c option does accept a <path> argument (specifically for directories), so maybe after all (for consistency) the best option is to add an arg to -R, instead of points 1-3 above (and apply the logic to that arg).

`-c` is a whole different thing, it is in no way related to targets. It just makes dvc chdir to that directory and work from there.

**Comment by jorgeorpinel** [comment]
True, you could combine the args like `dvc repo -c some/path stage1 stage2`. OK, never mind about the alternative then.

> P/s I wonder what happens if you supply a path to a dvc.yaml file as target along with a `-c`, is it made relative to the `-c` path arg? ⏳

**Comment by jorgeorpinel** [comment]
> P/s I wonder what happens if you supply a path to a dvc.yaml file as target along with a `-c`, is it made relative to the `-c` path arg? ⏳ 

UPDATE: Yes, it is. So, strangely, `dvc repro` = `dvc repro -c subdir/ ../dvc.yaml` 🤷
