### ISSUE TITLE
commit: support granularity

### ISSUE THREAD

**Issue by pared** [iterative/dvc#4297]
Update: see https://github.com/iterative/dvc/issues/4297#issuecomment-739848041

~~version : `1.2.2`~~

~~commiting output instead of stage, when there is no `dvc.yaml` results in:~~

~~`ERROR: failed to commit data - 'dvc.yaml' does not exist.`~~

~~in `0.94.0` it used to be:
`ERROR: failed to commit data - bad DVC-file name 'data'. DVC-files should be named 'Dvcfile' or have a '.dvc' suffix (e.g. 'data.dvc').`~~

~~Reproduction script:~~
```
#!/bin/bash

rm -rf repo
mkdir repo

pushd repo
git init --quiet
dvc init --quiet

echo data >> data
dvc add data

git add -A
git commit -am "init"

dvc commit data
```
NOTE:
When `dvc.yaml` is present, error is more readable:
`failed to commit data - "Stage 'data' not found inside 'dvc.yaml' file"
`

**Comment by efiop** [comment]
The problem here is that we are using `collect` instead of `collect_granular` when resolving the target. Likely just need to do the switch. CC @skshetry or am I missing something?

**Comment by skshetry** [comment]
@efiop, I don't think it was ever supported. Switching from `collect` to `collect_granular` would help, though it won't help with outputs being granular, it will commit all of the stage outputs.

**Comment by efiop** [comment]
@skshetry Thanks! So looks like collect_granular + filter_info support for `commit` and we should be set :slightly_smiling_face:

**Comment by efiop** [comment]
Discussed with @skshetry that we could start with just output-level granularity, e.g.
```
dvc add datafile
...
dvc commit datafile

dvc add datadir
...
dvc commit datadir
```
More granular commits like
```
dvc add datadir
....
dvc commit datadir/subdir/file
```
would require a bit more work on `cache.save` side, for it to accept filter_info and handle it properly, so we could do it as the next step after output-level granularity.

**Comment by mbiesek** [comment]
@efiop I would like to start working on this.

**Comment by efiop** [comment]
@mbiesek Great! Let us know if you'll have any questions :slightly_smiling_face:

**Comment by skshetry** [comment]
@pmrowla, can we close this one?

**Comment by dberenbaum** [comment]
@skshetry Can we close this one as completed or maybe open a new issue/edit the title to reflect the remaining work you would like to address? I think the original issue is solved, right?
