### ISSUE TITLE
ERROR: unexpected error - database disk image is malformed

### ISSUE THREAD

**Issue by bjonnh** [iterative/dvc#4326]
### Please provide information about your setup

**Output of `dvc version`:** 1.3.1

**Additional Information (if any):**

Was doing a dvc pull after another dvc pull that crashed due to a full disk.  I think I did a dvc pull in between that worked properly , but I can't say for sure. That's in a repo with 5 dvc files so only the sqlite section of that specific dataset failed.

Here is a full -vv output : https://bjonnh.net/share/out.gz

I tried to dump and restore the sqlite "state" db, but nothing solved the issue so I just deleted the cache, state, locks and files and dvc pulled the full thing again.

Unfortunately I deleted the state file and forgot to make a copy.

**Comment by efiop** [comment]
Hi @bjonnh .

> I tried to dump and restore the sqlite "state" db, but nothing solved the issue so I just deleted the cache, state, locks and files and dvc pulled the full thing again.

Deleting the `.dvc/tmp` would be enough. state db is purely for local optimization and deleting it is safe.

**Comment by efiop** [comment]
Closing for now due to inactivity.

**Comment by gregstarr** [comment]
Deleting tmp folder fixed issue for me
