### ISSUE TITLE
dvc diff support for -R, --recursive

### ISSUE THREAD

**Issue by garylschultz** [iterative/dvc#4342]
I'm using dvc for a project that has all of my original data under git/dvc control in a data/ directory, and am using pipelines and the **dvc repro** command. This tool rocks! 

I would like to look at which of my data/ contents have changed from one commit to another. However, I don't know how to restrict the **dvc diff** command to look at just the data/ directory. There are so many items in the pipeline that it is difficult to see what I'm interested in. 

It would be really nice to just say **dvc diff -R data/**

Thanks in advance for considering this.

**Comment by pared** [comment]
@garylschultz aren't you looking for: https://github.com/iterative/dvc/issues/3388 ?
I guess -R is not exactly it, but I guess they are related.

**Comment by garylschultz** [comment]
Thanks. They do seem related. 

If targets would apply to all .dvc files in a specified directory, then that would solve my problem.  So targets are probably the best solution.

**Comment by pared** [comment]
@garylschultz Feel free to upvote that issue, it helps us see what is important to users and prioritize appropriately.
