### ISSUE TITLE
version: missing fields in the output

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#4355]
On this repo, right after clone:

`dvc version` outputs only:

```
DVC version: 1.4.0
---------------------------------
Platform: Python 3.8.5 on macOS-10.15.4-x86_64-i386-64bit
Supports: All remotes
```

Looks like quite a few items are missing here.

**Comment by efiop** [comment]
@shcheklein You are probably simply not in a dvc repo. Unable to reproduce in a dvc repo.

**Comment by shcheklein** [comment]
@efiop yep, I think so. `master` of that repo is not DVC-enabled. Probably got confused since previously it was printing regular cache warning even w/o DVC repo.
