### ISSUE TITLE
can't move dvc.yaml?

### ISSUE THREAD

**Issue by majidaldo** [iterative/dvc#4360]
### Please provide information about your setup

**Output of `dvc version`:**
1.2.1

```console
$ dvc version
```

```
<doing work>
dot dot dot
Generating lock file 'pipelining\dvc.lock'
To track the changes with git, run:
        git add 'pipelining\dvc.lock'
ERROR: 'dvc.yaml' does not exist.
```

**Comment by efiop** [comment]
@majidaldo What command results in that error? `dvc move`?

**Comment by majidaldo** [comment]
oh sorry!!
I was just executing a stage in the pipeline defined in the dvc.yaml. When the dvc.yaml is in the root of the repo its works but not when I put it in a directory.

Not sure if this is by design or a bug.

**Comment by majidaldo** [comment]
On that note, I'm not sure how dvc.yaml is supposed to be managed.

**Comment by efiop** [comment]
@majidaldo By default `dvc repro` will try to reproduce `dvc.yaml` from your current directory, if it doesn't exist - it will error-out.

So just to make sure I understand you correctly, you had `dvc.yaml` in the project's root, then you moved it to `pipelining.dvc.yaml` and ran `dvc repro` in the root?

**Comment by majidaldo** [comment]
> @majidaldo By default `dvc repro` will try to reproduce `dvc.yaml` from your current directory, if it doesn't exist - it will error-out.
> 
> So just to make sure I understand you correctly, you had `dvc.yaml` in the project's root, then you moved it to `pipelining.dvc.yaml` and ran `dvc repro` in the root?

ah. yes.

**Comment by efiop** [comment]
@majidaldo Then that's the expected and correct behavior. I was not able to reproduce those strange messages before `ERROR: 'dvc.yaml' does not exist.` though, could you provide more details on how to reproduce it?

**Comment by majidaldo** [comment]
> @majidaldo Then that's the expected and correct behavior. I was not able to reproduce those strange messages before `ERROR: 'dvc.yaml' does not exist.` though, could you provide more details on how to reproduce it?

That's ok. Feel free to close. I'll open again if I get an unexpected problem. Thanks!
