### ISSUE TITLE
check-ignore: exit --stdin silently on empty string [qa]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4361]
> Extracted from https://github.com/iterative/dvc/pull/4323#discussion_r467356171

When you use check-ignore in interactive mode, empty strings produce an error and exit. However empty strings are accepted (never match) without `--stdin`:

```console
λ cat .dvcignore
*

λ dvc check-ignore --stdin
 anything
anything
 # <- just hit Enter
Empty string is not a valid pathspec. Please use . instead if you meant to match all paths.

λ dvc check-ignore -dn ''
::
```

So I propose that a) empty strings in --stdin interactive mode simply cause the tool to exit back to the shell prompt and/or b) empty strings sent as `targets` should just be ignored? (exit tool silently)

**Comment by jorgeorpinel** [comment]
Cc @karajan1001 WDYT?

**Comment by jorgeorpinel** [comment]
And as an extra (from https://github.com/iterative/dvc/pull/4323#pullrequestreview-463603712), the `` cannot use both `--details` and `--quiet` `` error could also be avoided by just having `--quiet` win i.e. `--details` could imply have no effect if combined with --quiet.

**Comment by karajan1001** [comment]
@jorgeorpinel 
For empty string error. I just followed what the `Git` do, 
![check-ignore-error](https://user-images.githubusercontent.com/6745454/89722757-fbb4e880-da1f-11ea-8318-cec12e3bc061.jpg)
And they didn't mention this in there [documents](https://git-scm.com/docs/git-check-ignore). 

So the question is do we need another exiting method besides `Ctrl+C`. If so, `a)` plan and mention it in our doc, if not just `b)` plan.

"cannot use both `--details` and `--quiet`" I agree

**Comment by jorgeorpinel** [comment]
I see. Well, Git has notoriously poor interface and docs, so not a role model on every single detail 🙂

BTW, `git check-ignore --stdin` doesn't throw an error on `Ctrl+C`.

> do we need another exiting method besides Ctrl+C

I think my suggestion to use `Enter` makes for an intuitive UI (except if you're used to `git check-ignore` but I doubt it's a well known command). And yes either way have a small mention of how to exit--stdin interactive mode in docs.

Thanks!

**Comment by karajan1001** [comment]
> I see. Well, Git has notoriously poor interface and docs, so not a role model on every single detail 🙂
> 
> BTW, `git check-ignore --stdin` doesn't throw an error on `Ctrl+C`.
> 
> > do we need another exiting method besides Ctrl+C
> 
> I think my suggestion to use `Enter` makes for an intuitive UI (except if you're used to `git check-ignore` but I doubt it's a well known command). And yes either way we'll have a small mention of how to exit --stdin interactive mode in docs.
> 
> Thanks!
@jorgeorpinel 
I'm sorry, I'm not quite understanding here. Only `Enter` without other things gives an empty string to the program if we use `input()` this is what we are doing here.

**Comment by jorgeorpinel** [comment]
> Only Enter without other things gives an empty string to the program

Ohhh good point sorry, I was confused about that. My idea was to end the interactive mode on empty string then. I see you've already done that in #4368, thanks @karajan1001 !
