### ISSUE TITLE
remote modify: better handle unrecognized parameters [qa]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4362]
> Context: https://discord.com/channels/485586884165107732/485596304961962003/741358864888365116

DVC knows the type of remote from the URL given to `remote add`. If you accidentally give a bad URL (e.g. forget to include the `protocol//:`) then DVC will think the remote is of some other/unknown?/local type. If you then try to modify one of the parameters for the type you intended (not what DVC thinks it is), you'll get a generic config error like:

`ERROR: configuration error - config file error: extra keys not allowed @ ...`.

This doesn't really give any hint as to what the problem is. Ideas to improve this:

- Extra: Should `remote` commands validate URL formats?
- Should `remote` commands print out the type of remote when it is added or when URL is modified? E.g.:
  ```console
  $ dvc add -d myremote local/path
  Added 'default' 'LOCAL' remote with 'new/existing' 'RELATIVE path' 'local/path'.
  $ dvc modify myremote url https://example.com/path
  WARNING: Modified 'myremote' type to 'HTTP' with URL 'https://example.com/path'.
  ```
- Give out the type of remote when `remote modify` can't recognize the parameter, even hint that it belongs to another type of remote if it exists. E.g.:
  ```console
  $ dvc modify myremote badparam value
  ERROR: Config param 'badparam' is unknown.
  $ dvc modify myremote gdrive_trash_only true
  ERROR: Remote 'myremote' is of 'HTTP' type. Config param 'gdrive_trash_only' is only available for 'GDRIVE' remotes.
  ```

**Comment by shcheklein** [comment]
Two most recent complains to the same issue:

https://github.com/iterative/dvc/issues/4388
https://github.com/iterative/dvc/issues/4367

I guess it's time to prioritize this?
