### ISSUE TITLE
whenever CTRL+D or any errors happens on dvc repro, the dvc does proccess does not terminate

### ISSUE THREAD

**Issue by antonkulaga** [iterative/dvc#4366]
Whenever I either Ctrl+d during dvc repro or there is an error in the script, the dvc process does not terminate and gives:
```
ERROR: failed to reproduce 'dvc.yaml': 'data/interim/selected/species.tsv' is busy, it is being blocked by:
  (PID 23189): /opt/miniconda3/envs/yspecies/bin/dvc repro tune
```
Maybe it should ask "do you want to terminate running dvc process Y/N" ? so the user can avoid going to system-monitor each time to terminate it. Also, I think that it should check if CTRL+D was pushed to terminate it properly

**Comment by dberenbaum** [comment]
Closing as stale
