### ISSUE TITLE
Ubuntu install unknown gpg key

### ISSUE THREAD

**Issue by qypea** [iterative/dvc#4385]
When installing using the [repository instructions](https://github.com/iterative/dvc.org/blob/master/content/docs/install/linux.md#on-debianubuntu) on ubuntu 18.04 amd64 I am getting the following error:
```
$ sudo apt update
...                                 
Get:10 https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb stable InRelease [2,679 B]
Ign:10 https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb stable InRelease
Fetched 2,679 B in 1s (1,941 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: GPG error: https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3409A777FEEDE364
```

Where would I find the public GPG key to import into apt so it can verify this repository?

**Comment by efiop** [comment]
Hi @qypea !

That is not really an error, but a warning that can be safely ignored for now.  We are aware of the problem but simply didn't get to creating a proper signature for our deb packages. Other packages like pip, conda, brew, etc are not affected by this.

Closing in favor of https://github.com/iterative/dvc-s3-repo/issues/3 .

Thank you for the feedback! :pray:
