### ISSUE TITLE
remote[ssh]: ask for password when needed

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4392]
## Report

UPDATE: Jump to https://github.com/iterative/dvc/issues/4392#issuecomment-674448191

I setup OpenSSH server on Windows 10 (it's a beta feature, see [guide](https://winscp.net/eng/docs/guide_windows_openssh_server#win10)) but for some reason it doesn't care about my `authorized_keys` files so I can't configure key-based auth (Windows is really good at wasting people's time). So I'm stuck with password auth. Here's what happens:

```console
λ dvc add data  # Track something.
...

# Setup an SSH remote with password auth:
λ dvc remote add sshcache ssh://myuser@MyLaptop/cache
λ dvc remote modify --local sshcache password 'mypassw'

λ dvc push -r sshcache data
1 file pushed  # OK, the remote works.

λ dvc config cache.ssh sshcache  # Setup external cache

λ dvc add --external ssh://myuser@MyLaptop/mydata
Adding...
ERROR: unexpected error - Authentication failed.
```

I wonder if it's a Windows-specific problem or if anyone with SSH password auth will have this issue.

Other errors I've run into:

```console
λ dvc add --external ssh://myuser:mypassw@MyLaptop/mydata
Adding...
ERROR: unexpected error
```
^ Should probably say "Bad SSH URL format" or something?

```console
λ cat ~/.ssh/config
Host ThisLaptop
	HostName MyLaptop
	User myuser
λ dvc add --external ssh://ThisLaptop/mydata
Adding...
ERROR: unexpected error - [Errno 11001] getaddrinfo failed
```
a) `ThisLaptop` should be recognized by paramiko?
b) Users will have no idea what `getaddrinfo` is.

### Please provide information about your setup

**Output of `dvc version`:**

```console
λ dvc version
DVC version: 1.5.0 (exe)
---------------------------------
Platform: Python 3.7.5 on Windows-10-10.0.18362-SP0
Supports: All remotes
Cache types: hardlink
Cache directory: NTFS on C:\
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by jorgeorpinel** [comment]
p.s. I updated to DVC 1.5 and get the same errors.

**Comment by jorgeorpinel** [comment]
UPDATE: I setup the `password` with `dvc remote modify` and that fixes the problem for `dvc push`. But add --external still gets `Authentication failed.`

**Comment by efiop** [comment]
@jorgeorpinel `--external` get's that error because you are using ssh:// url instead of `remote://myremote/...`, so it doesn't know that it should ask you for a password.

**Comment by jorgeorpinel** [comment]
OK. I get that I configured the `sshcache` remote to ask for password, not any DVC command using that SSH URL, but that's kind of confusing. We, for example, have this example in https://dvc.org/doc/user-guide/managing-external-data#ssh:

````console
dvc remote add sshcache ssh://user@example.com:/cache
dvc config cache.ssh sshcache
dvc add --external ssh://user@example.com:/mydata
```

Which would fail with password auth, even if the user configures the `sshcache` remote to ask for password.

Bottom line: Shouldn't DVC know to ask for password for ssh:// URLs when needed, regardless of remote config?

Otherwise please transfer this to dvc.org and I'll just update the External Data and other appropriate examples to cover or at least mention password auth.

**Comment by efiop** [comment]
> Bottom line: Shouldn't DVC know to ask for password for ssh:// URLs when needed, regardless of remote config?

@jorgeorpinel Yes, this was requested before. It is paramiko's limitation, nothing we can do here.

**Comment by efiop** [comment]
@jorgeorpinel I wouldn't focus on `--external` for now. It is a pretty raw feature, would not spend too much effort on it for now.

**Comment by jorgeorpinel** [comment]
Gotcha. I'll just add a small note about the password for now. I understand SSH is pretty popular remote type and people will probably bump into this limitation regularly while it's there.

P.s. not sure if this helps but an idea: https://stackoverflow.com/a/373870/761963

**Comment by efiop** [comment]
@jorgeorpinel Should we close this or transfer to docs?

**Comment by jorgeorpinel** [comment]
Up to you! I already added the note in docs. I'd personally leave it as `nice-to-have`. TBH I'm not convinced there's nothing that can be done about this, but I understand that it may be a huge effort for a small need 🙂

**Comment by efiop** [comment]
> TBH I'm not convinced there's nothing that can be done about this, but I understand that it may be a huge effort for a small need slightly_smiling_face

We've done the research in the past. If you feel like we've missed something, please feel free to let us know :slightly_smiling_face:
