### ISSUE TITLE
dvc help starts with lowercase

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#440]
Help message should start with upper case. `--help` or `-h` option is special - the library generates message automatically.

We need to replace that and make it as all other messages - starting from upper case.

```
$ dvc -h
[SKIP]
optional arguments:
  -h, --help            show this help message and exit     <-- Here it is. Should be "Show this help..."
  -q, --quiet           Be quiet.
  -v, --verbose         Be verbose.
  -V, --version         Show program's version
```

**Comment by dmpetrov** [comment]
You can take a look how this issue was solved for `-V` flag. The same approach does not work for `-h`.

I'm not sure we can fix that without hacking `argparse` lib. So, a patch to `argparse` might be a good solution.

**Comment by npow** [comment]
You can set `add_help=False` and add that action manually. [Link to docs.](https://docs.python.org/3/library/argparse.html#add-help)
```
npow@jupiter:~$ cat test_argparse.py
import argparse
parser = argparse.ArgumentParser(add_help=False)
parser.add_argument('-h', '--help', action='help', default=argparse.SUPPRESS,
                    help='Show this help message and exit.')
print(parser.format_help())
npow@jupiter:~$ python test_argparse.py
usage: test_argparse.py [-h]

optional arguments:
  -h, --help  Show this help message and exit.
```

**Comment by efiop** [comment]
Hi @npow !

Thanks for the tip! If you wish to contribute a proper pull request, we will be happy to accept it :slightly_smiling_face: Feel free to ping us if you need any help with that.

Thanks,
Ruslan

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/1064
