### ISSUE TITLE
Auto upgrade pre-commit's hooks

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4404]
pre-commit does provide a way to [`autoupdate`](https://pre-commit.com/#pre-commit-autoupdate). 

It'd be good to figure out a way to update it by creating a PR (some have [done that using Github Actions](https://github.com/browniebroke/cookiecutter-pypackage/blob/master/.github/workflows/pre-commit-autoupdate.yml) which we could do in a similar way).

**Comment by efiop** [comment]
Great idea! Feel free add that action.

**Comment by isidentical** [comment]
For this, we can use the `pre-commit.ci`. It is like dependabot, scans pre-commit config files automatically and sends a PR to upgrade it whenever needed.

**Comment by skshetry** [comment]
@isidentical, is `pre-commit.ci` stable? It was in development when I made this issue I think. Let's use it then. 🙂

**Comment by isidentical** [comment]
> @isidentical, is pre-commit.ci stable?

I believe so, it works totally fine for my side projects.

**Comment by skshetry** [comment]
We have auto upgrade now thanks to `pre-commit.ci`. Closing ...
