### ISSUE TITLE
Tests in Windows seem to take quite a long time

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4406]
Right now, it takes 8 - 12 mins to run the tests for Linux, whereas, on Windows, it takes 20-22 mins. This makes every CI build slower as other stages need to wait for it to finish (complete build takes 35-40 mins). 

So, I looked at it on the logs, and found something fishy:
```
138.93s call     tests/func/test_update.py::test_update_import[False]
102.95s call     tests/func/test_update.py::test_update_import[True]
60.92s teardown tests/unit/utils/test_utils.py::test_dict_sha256[d0-f472eda60f09660a4750e8b3208cf90b3a3b24e5f42e0371d829710e9464d74a]
50.32s teardown tests/unit/utils/test_utils.py::test_dict_sha256[d1-a239b67073bd58affcdb81fff3305d1726c6e7f9c86f3d4fca0e92e8147dc7b0]
46.63s teardown tests/func/test_ls.py::test_ls_repo_with_path_subdir
34.15s call     tests/func/test_data_cloud.py::test_pull_external_dvc_imports
```

`test_update_import` passes in under 3 seconds in my machine (discounting the test collections).
Is sha256 that slow for a simple dictionary on Windows? The test does not even have a teardown (could be because of parametrization though).

We also have some issues on Linux (11-12 minutes on it is quite high too).
```
173.69s setup    tests/func/test_add.py::test_add_external_file[hdfs-checksum-000002000000000000000000a86fe4d846edc1bf4c355cb6112f141e]
147.32s setup    tests/func/test_api.py::test_open_granular[oss]
140.48s setup    tests/func/test_api.py::test_get_url[oss]
137.63s setup    tests/func/test_api.py::test_open_granular[azure]
32.21s call     tests/func/test_run_multistage.py::test_run_external_outputs[hdfs-checksum-0000020000000000000000003dba826b9be9c6a8e2f8310a770555c4-00000200000000000000000075433c81259d3c38e364b348af52e84d]
26.75s call     tests/func/test_add.py::test_add_external_file[hdfs-checksum-000002000000000000000000a86fe4d846edc1bf4c355cb6112f141e]
24.54s call     tests/func/test_gc.py::test_gc_external_output[hdfs]
18.06s setup    tests/func/test_api.py::test_open_granular[hdfs]
17.47s call     tests/func/test_update.py::test_update_import_url[hdfs]
17.06s setup    tests/func/test_api.py::test_open[hdfs]
16.42s call     tests/func/test_update.py::test_update_import[True]
14.84s call     tests/func/test_update.py::test_update_import[False]
```

Notice the last 2 lines, it takes 14-16 seconds to run that test on Linux which is equally high. But, on Windows, it takes 10X more time.

Let's see how much time it takes for dict_sha256:
```
0.34s teardown tests/unit/utils/test_utils.py::test_dict_sha256[d1-a239b67073bd58affcdb81fff3305d1726c6e7f9c86f3d4fca0e92e8147dc7b0]
0.01s teardown tests/unit/utils/test_utils.py::test_dict_sha256[d0-f472eda60f09660a4750e8b3208cf90b3a3b24e5f42e0371d829710e9464d74a]
```

Slow CI builds slows down everyone. We should investigate.

**Comment by efiop** [comment]
Let's wait for https://github.com/iterative/dvc/pull/4469 until we do the research, so we don't waste our time on travis.

**Comment by efiop** [comment]
likely the main cause https://github.com/gitpython-developers/GitPython/blob/9541d6bffe4e4275351d69fec2baf6327e1ff053/git/repo/base.py#L233

**Comment by skshetry** [comment]
It is still an issue, but we can lower the priority here as it seems we cannot do much here.

**Comment by skshetry** [comment]
Closing as stale.
