### ISSUE TITLE
dvc conda build contains wrong packaging type

### ISSUE THREAD

**Issue by autayeu** [iterative/dvc#4408]
## Bug Report

dvc uses wrong packaging type when installed through conda.

In particular, this leads to printing wrong packaging type in `dvc version` output:
```console
DVC version: 1.5.0 (pip)
```

Furthermore, this leads to dvc printing a confusing update message:
```text
+-----------------------------------------+
|                                         |
|     Update available 1.4.0 -> 1.5.0     |
|     Run `pip install dvc --upgrade`     |
|                                         |
+-----------------------------------------+
```

This could be particularly confusing for conda users as conda also supports pip. Conda users might inadvertently copy-paste the command (inline with authors intention) and switch to managing dvc through pip in a conda environment.

Lack of `How to build` section in Contributors guide makes it harder to provide further pointers, but this behavior looks connected to `.build` file generation somewhere during build process. For example, `.build` is imported in `dvc/utils/pkg.py` and used further throughout the project, in particular for update message.

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.5.0 (pip)
---------------------------------
Platform: Python 3.8.5 on macOS-10.15.6-x86_64-i386-64bit
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
```

Notice dvc reports version with pip in round brackets. However, dvc was installed through conda environment.

**Additional Information (if any):**

```console
$ conda list | grep dvc
dvc                       1.5.0            py38h32f6830_0    conda-forge
```

**Comment by skshetry** [comment]
Thanks for reporting the issue. It is weird, but as you pointed out, `.build` file is missing, hence, `PKG` of original build (i.e. pip) is returned (which should have been patched properly).

This is an issue on https://github.com/conda-forge/dvc-feedstock. I'll reopen it there.

**Comment by skshetry** [comment]
Opened https://github.com/conda-forge/dvc-feedstock/issues/136
