### ISSUE TITLE
checkout: unpredictable file deletion behavior

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4413]
## Bug? Report

> Extracted from a [support case](https://discord.com/channels/485586884165107732/485596304961962003/744979999982878870).

```console
λ echo x > x && echo y > y
λ dvc config cache.type symlink
WARNING: You have changed the 'cache.type' option. This doesn't update any existing ...
             dvc checkout --relink
λ dvc add x y
λ ls
x@  x.dvc  y@  y.dvc

# May want to git commit so far to try going back and forth

λ dvc remove y.dvc
λ ls
x@  x.dvc  y  # Notice y is no longer a symlink.
λ ls .dvc/cache/
00/  40/  # The cache still has both files BTW.
λ dvc checkout  # Does nothing
λ ls
x@  x.dvc  y
```

1. We expected `checkout` to remove `y`, I think. Otherwise this remove+checkout combo is not very predictable.

2. In fact checkout in general seems unpredictable some times. How does it decide what untracked data to remove? If the .dvc file is gone, how can it tell which untracked files/dirs used to be there before, does it check all previous commits? (Would be nice to be explain this in the docs.)

### Please provide information about your setup

**Output of `dvc version`:**

```console
λ dvc version
DVC version: 1.5.0+8cd4ee
---------------------------------
Platform: Python 3.8.2 on Windows-10-10.0.18362-SP0
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: NTFS on C:\
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by skshetry** [comment]
`remove` by default does not remove files, only unprotects them. Also, by default it removes the dvcfiles.

As there's no dvcfile, DVC is not aware that `y` was once a DVC output (which is a correct assumption). Better to suggest `remove --outs` that does this in a single action. 

If you do `dvc remove`, DVC should not and does not take any responsibility thereafter. _You are on your own_.  :smile:

**Comment by Teque5** [comment]
@jorgeorpinel I think we can close this issue. I think I misunderstood what `dvc checkout` was doing. I now know I have to `rm y` after `dvc remove`.

Essentially I was trying to use a shared remote cache as follows. The behavior is as I expect below:
```bash
$ cd /tmp/
$ mkdir dvctmp
$ cd dvctmp/
$ mkdir src # simulated git repo in small fast partition (1TB)
$ mkdir shared # shared external cache on raid (10 TB)
$ mkdir bigdisk # fake external remote (1000 TB)
$ cd src/
$ git init
$ dvc init
$ dvc remote add -d bigdisk /tmp/dvctmp/bigdisk/
$ dvc config cache.dir /tmp/dvctmp/shared/
$ dvc config cache.type symlink
$ git commit -am 'init repo'

$ echo x > x && echo y > y
$ dvc add x y
$ git add .gitignore x.dvc y.dvc
$ git commit -am 'added x & y'
$ dvc remove y.dvc
$ rm y
$ git commit -am 'removed y'
$ git checkout HEAD^
$ ls
x x.dvc y y.dvc
$ git checkout master
$ dvc checkout
$ ls
x x.dvc
```
I do think your website needs an example for this kind of setup under **Use Cases -> Shared Development Server**.

**Comment by jorgeorpinel** [comment]
> only unprotects them

- [ ] OK we need to emphasize this in the `remove` ref, I'll open a docs issue or PR based on this ticket.

> Better to suggest remove --outs that does this in a single action.

Yes good point. @Teque5 please use `dvc remove --outs` instead of `remove`+`rm`. This way `checkout` is more predictable when switching back and forth between versions.

**Comment by jorgeorpinel** [comment]
> If you do dvc remove, DVC should not and does not take any responsibility thereafter.

@skshetry I'm not sure about this though. Or probably I just don't fully understand `checkout` (so we may be missing some key explanations in its cmd ref.)

How exactly does it determine when data used to be tracked but no longer is and thus deletes it? I remembering having unexpected results before. Does it look for .dvc files in all previous commits? Is it based on what's in the cache (what if `gc` was run)?

**Comment by jorgeorpinel** [comment]
No one seems to have this problem so I'll close it for now but still, if you could help me answer the question of when does `checkout` delete data (what's the logic), that would be great (for docs purposes) @skshetry and maybe cc @efiop 

Thanks!
