### ISSUE TITLE
migrate from travis to github actions

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#4418]

**Comment by pared** [comment]
- [ ] migrating tests
- [ ] provide AWS credentials to github actions
- [ ] configure AWS tests on github actions for build on master
- [ ] fix tests currently skipped by me and marked as `#FIXME`

**Comment by efiop** [comment]
>  provide AWS credentials to github actions

>  configure AWS tests on github actions for build on master

Only 1 test is using `real_s3` fixture, and only because there is a bug in moto. We can lower the priority of these points.
