### ISSUE TITLE
glob* operators for move

### ISSUE THREAD

**Issue by Teque5** [iterative/dvc#4419]
Some commands like `add` work with glob operators, but it would be really nice if `move` worked.
```bash
$ dvc move old/*.wav new/
```
Right now it broadcasts the operators into `move` and gets confused. dvc v1.5.0.

My janky workaround: `$ for f in old/*.wav; do dvc move $f new/;done`

**Comment by efiop** [comment]
Discord context: https://discordapp.com/channels/485586884165107732/485596304961962003/745414867015565312

Just for the record, this is not really about dvc handling the glob, but rather accepting multiple sources (your shell will evaluate the glob and pass the list of files).

The implementation would require adjusting CLI in https://github.com/iterative/dvc/blob/master/dvc/command/move.py to accept multiple sources and pass them to API. And adjusting the API in https://github.com/iterative/dvc/blob/master/dvc/repo/move.py to handle that list of sources.

**Comment by polvoazul** [comment]
I will do this issue :)

**Comment by efiop** [comment]
Closing in favor of #4816
