### ISSUE TITLE
Azure cloud

### ISSUE THREAD

**Issue by up201007037** [iterative/dvc#442]
Hi,

Do you have plans to support azure cloud storage?
Thank you so much for your work.

**Comment by dmpetrov** [comment]
Hi! Thank you for using DVC.

Yes, we definitely do have plans to support Azure cloud.
Unfortunately, not in the next release (in a month).

If you decide to implement that - please go ahead I can point you to a right place in the codebase.

**Comment by up201007037** [comment]
Hi, thank you for your answer. I am not sure if I am able to do it, but I can take a look and try :) 
Is it under dvc/cloud?

**Comment by dmpetrov** [comment]
Yes, `dvc/cloud` dir. Take a look at `base.py`. See `aws.py` and `gcp.py` as examples.

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/868
