### ISSUE TITLE
repro: walk through dag/pipeline only once rather than going through multiple pipelines

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4444]
```console
$ dvc repro
Restored stage 'split-into-two' from run-cache
Skipping run, checking out outputs

Stage 'copy-foo-bar' is cached
Skipping run, checking out outputs

Stage 'copy-bar-foobar' is cached
Skipping run, checking out outputs
```

Notice `copy-bar-foobar` runs twice, i.e. each of two pipelines there is from DAG.
We should only walk through a single DAG once and run which will help us clear the outputs as well as prevent us from running something twice (in case of `always_changed` for example).

**Comment by efiop** [comment]
@skshetry Do you remember more details about this by any chance? Looks like I'm not able to reproduce with 1.3.1(August 1st) or newer. The log in the description doesn't check out with the text though.

**Comment by skshetry** [comment]
@efiop, looks like it was fixed with your recent `repro` changes. Closing ...
