### ISSUE TITLE
list: dvc hangs for quite a time

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4447]
```console
$ dvc list . --cprofile
.codecov.yml
.coveragerc
.github
.gitignore
.mailmap
.pre-commit-config.yaml
.pre-commit-hooks.yaml
.pylintrc
.restyled.yaml
.travis.yml
.zenodo.json
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
MANIFEST.in
README.rst
bin
debian
dvc
fastentrypoints.py
pyproject.toml
scripts
setup.cfg
setup.py
snap
tests
         342769 function calls (339869 primitive calls) in 22.731 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   22.730   22.730 __init__.py:26(run)
        1    0.000    0.000   22.729   22.729 ls.py:7(ls)
    33/22    0.000    0.000   22.451    1.020 {built-in method builtins.next}
        2    0.000    0.000   22.448   11.224 external_repo.py:30(external_repo)
        5    0.000    0.000   22.448    4.490 contextlib.py:79(__enter__)
       28    0.000    0.000   22.385    0.799 decorators.py:37(wrapper)
       28    0.000    0.000   22.384    0.799 flow.py:240(wrap_with)
       28    0.000    0.000   22.384    0.799 decorators.py:58(__call__)
        1    0.000    0.000   22.384   22.384 external_repo.py:263(_cached_clone)
        1    0.000    0.000   22.383   22.383 external_repo.py:290(_clone_default_branch)
        1    0.000    0.000   22.383   22.383 git.py:95(clone)
        1    0.000    0.000   22.320   22.320 base.py:1000(clone_from)
        1    0.000    0.000   22.320   22.320 base.py:927(_clone)
        1    0.000    0.000   22.309   22.309 cmd.py:59(handle_process_output)
       20   22.309    1.115   22.309    1.115 {method 'acquire' of '_thread.lock' objects}
        3    0.000    0.000   22.309    7.436 threading.py:1024(join)
        3    0.000    0.000   22.309    7.436 threading.py:1062(_wait_for_tstate_lock)
        1    0.000    0.000    0.281    0.281 ls.py:52(_ls)
```

This a part of the cProfile dump. From time to time, I see DVC commands that "clones" hanging. 

On "normal" times, I see `dvc list .` complete in under 0.4s for DVC's own repo. But, time to time hangs.
I looked in `GitPython`'s repository and found this issue: https://github.com/gitpython-developers/GitPython/issues/969

GitPython hangs for a long-running process, and as `gitpython` uses `git` at the end anyway, we could just clone from subprocess and try to get predictable results.

I suspect that this might be related to our travis tests being slow, see: https://github.com/gitpython-developers/GitPython/issues/245

**Comment by dberenbaum** [comment]
@mattseddon Have you experienced intermittent hanging like this?

**Comment by mattseddon** [comment]
Not that I am aware of. It could quite easily be happening in the background underneath a VS code session.

I do see a difference in performance at the very start of a session (when there is a lot of activity and things are being resolved) vs when the session is idle. Also, if I run `list` when I'm running an experiment I see a significant decrease in performance (nearly a 100% increase in run time -> ~1.45s vs  ~0.73s).

Hope this helps.

**Comment by dberenbaum** [comment]
@skshetry Can we close this one?

**Comment by skshetry** [comment]
Closing, we don't use `gitpython` for cloning these days.
