### ISSUE TITLE
params.yaml - dependency to all params

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#4454]
In some projects only one pipeline step is used, but `params.yaml` is still useful for example for `dvc plots diff`. It might be handy to have a dependency to all the params the `params.yaml` for this case. Like `dvc run -p '*' ...`

It is especially useful for flat params structure when every param name modification\additoin\delition requires to change the command as well.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/4112
