### ISSUE TITLE
experiments: parallel coordinates plot 

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#4455]
I'd love to see a parallel coordinates plot for an experiment.

```
$ dvc exp show --no-pager --include-metrics accuracy --include-params epochs,opt.lr --all-commits
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┓
┃ Experiment                        ┃ accuracy ┃ epochs ┃ opt.lr ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━┩
│ workspace                         │  0.48982 │ 2      │ 0.0    │
│ 794e714 (2020-08-24 03:01:44)     │  0.48982 │ 2      │ 0.0    │
│ ├── a0f6717 (2020-08-24 03:17:31) │  0.84703 │ 2      │ 1e-05  │
│ ├── 59b2759 (2020-08-24 03:12:42) │  0.86678 │ 2      │ 1e-05  │
│ ├── 26656e0 (2020-08-24 03:16:02) │  0.67587 │ 2      │ 0.0    │
│ └── 0a81605 (2020-08-24 03:16:42) │  0.81715 │ 2      │ 1e-05  │
│ 650049c (2020-08-21 20:43:31)     │  0.48607 │ 2      │ -      │
...
$ dvc exp plots 794e714 # show all ephemeral commits of a given commit as a  parallel coordinates plot 
file:///..../plot.png

$ dvc exp plots a0f6717 59b2759 ba39f4  # given set of ephemeral commits
file:///..../plot.png

$ dvc exp plots a0f6717 59b2759 ba39f4 --order epochs,opt.lr,accuracy  # change the order
file:///..../plot.png
```

![image](https://user-images.githubusercontent.com/10081867/91033995-1f983280-e5b9-11ea-9a09-807fe2c295f0.png)

**Comment by pared** [comment]
Seems like it will involve creating a new template.

**Comment by pmrowla** [comment]
See https://vega.github.io/vega-lite/examples/parallel_coordinate.html for example parallel coordinates plot schema

This will also require adding support for parameters in DVC plots, my understanding is that we cannot currently plot values from `params.yaml` since it is not a DVC out
@pared can you confirm this?

**Comment by pared** [comment]
@pmrowla That is correct, currently we are using `find_outs_by_path` to gather plot data. We probably should generalize it to accept any viable file.
Related: https://github.com/iterative/dvc/issues/4446

**Comment by pared** [comment]
NOTE: accepting any viable file is already implemented in #4446

**Comment by daavoo** [comment]
Would this belong in `dvc plots` or could it be an optional flag in `dvc exp show`? 

It feels like parallel plots don't make much sense without experiments and the implementation would probably be easier if we handle the generation as an optional flag of `dvc exp show` like the existing `--show-json` and `--show-csv`. Something like `--show-plot`?

**Comment by dberenbaum** [comment]
What field will be used to determine line colors?
