### ISSUE TITLE
azure: don't require permissions for getting container properties

### ISSUE THREAD

**Issue by MetalBlueberry** [iterative/dvc#4473]
## Bug Report

I don't know if this can be treated as a bug. 

The thing is that the current Azure remote implementation is using the following code to check if the container exist

```python
        try:  # verify that container exists
            container_client.get_container_properties()
        except ResourceNotFoundError:
            container_client.create_container()
```

The problem is that the get_container_properties() requires special permissions and with the current keys that my client is providing I cannot perform the operation.

is there any other way to check for the container existence that doesn't require extra privileges?

Thank you!

**Output of `dvc version`:**

```console
DVC version: 1.6.1 (pip)
---------------------------------
Platform: Python 3.6.9 on Linux-5.3.0-28-generic-x86_64-with-Ubuntu-18.04-bionic
Supports: All remotes
Cache types: hardlink, symlink
Repo: dvc, git
```

**Comment by efiop** [comment]
Hi @MetalBlueberry !

Good catch! Indeed, we could use something else instead. For example, we could use:
```
        try:
            container_client.create_container()
        except ResourceExistsError:
            pass
```
but that would require container creation permissions, which I suppose are not a problem, right? If they are, then we could do something like
```
        try:  # verify that container exists
            container_client.list_blobs()
        except ResourceNotFoundError:
            container_client.create_container()
```
or along those lines.

**Comment by MetalBlueberry** [comment]
For my specific case, I only have permissions to list blobs so I do not know what will happen with the first solution. Provably it will fail with Unauthorized error.

I think a good solution could be.

```python
try:
    container_client.create_container()
except ResourceExistsError:
    pass
except Unauthorized: # I don't know the exact exception
   warning("The container doesn't exist and cannot be created")
```
With this approach, dvc wouldn't fail if you cannot create, list or inspect containers. it will just warn you that the container existence cannot be guaranteed. Then, if you try to push/pull it will fail with appropriate error.

**Comment by efiop** [comment]
@MetalBlueberry A safe approach is to just
```
try:
    container_client.create_container()
except ResourceExistsError:
    pass
```
for now and let the other exception fall through. Would you be able to adjust that code and give it a try in your setup?

**Comment by MetalBlueberry** [comment]
sure, I will get you back with the output

**Comment by MetalBlueberry** [comment]
as I assumed, it fails with unauthorized error.
If I handle the exception, it fails when trying to list files because I only have permissions to list containers, upload and download files.

I think that we could modify the current azure implementation to work with minimal credentials but I also think that its not worth the effort.

So I've requested more privileged credentials to my client =)

Thank you for your support.
You can close this issue

**Comment by efiop** [comment]
@MetalBlueberry Glad you were able to find a way to do that :) Closing for now. Please let us know if it gets in your way again. Thank you!
