### ISSUE TITLE
dvc import and .dvc/config.local

### ISSUE THREAD

**Issue by wdixon** [iterative/dvc#4475]
## Bug Report

In an attempt to setup a data registry - I had created a .dvc/config containing 
the remote definition, and a .dvc/local - containing the name of the profile 
to use when accessing the remote bucket

.dvc/config
[core]
    remote = origin
['remote "origin"']
    url = s3://bucket/dataset/dvc_project_name
    endpointurl = https://local_server

.dvc/config.local
['remote "origin"']
    profile = minio

When attempting a dvc import /local/path/to/registry/checkout path_to_import (or https://remote_git/repo.git)
Fails with a 403 Forbidden - as it isn't using the proper credentials.

If I move the profile = minio to the .dvc/config (and commit it to git) - it works, but this implies that everyone will need to configure their environment with the same profile to use their personal credentials?

There doesn't seem to be a way to configure which credentials to use from within the project repo you are importing into.

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ DVC version: 1.6.0 (conda)
---------------------------------
Platform: Python 3.8.5 on Linux-4.15.0-64-generic-x86_64-with-glibc2.10
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache types: hardlink, symlink
Repo: dvc (no_scm)
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by efiop** [comment]
Hi @wdixon !

`dvc get/import` don't use your host project's configs at all, the only way to set additional options for those is to either add them with `dvc config --global` or `dvc config --system`, which will merge your system/global configs with the ones in the external repo. Alternatively you could just set AWS_PROFILE= env var and run `dvc get/import` as usual. We are considering adding a more explicit way for get/import https://github.com/iterative/dvc/issues/2466 , but it is not ready yet, as we need to agree on an approach in which we will set those remotes/remote options.

**Comment by wdixon** [comment]
I suppose global might work for me - though I could see this being challenging if you had different remotes with different credentials - you might need to explicitly define a profile name for each dvc project - and have those credentials associated/replicated in your .aws/credentials?

**Comment by efiop** [comment]
@wdixon Correct, that's just a current workaround. Ideally we need some way to specify things in `dvc get/import` themselves.

**Comment by shcheklein** [comment]
@wdixon just to clarify a bit, when we talk about using different profile names, different remotes - do you expect a single project (you are getting/importing data from) to have multiple remotes? or just multiple projects - one remote per each project?

>  and have those credentials associated/replicated in your .aws/credentials?

I'm not sure why do we need to replicate this? I guess the workaround the way I understood this is the following:

Let's say we have a project `project-A` and we know that we want/need to access it with aws profile `profile-A`. In the project itself we setup a remote with a project specific name `remote-A`:

```
dvc remote add -d remote-A s3://something/data
dvc remote remote-A ... # some additional config, like endpoint, etc
git add .dvc/config
git commit .dvc/config -m "dvc config: add default remote"
```

After this we can use `--global` or `--system` config on the client side to define profile name:

```
['remote "remote-A"']
profile = minio
```

The key here is that DVC will merge these configs when `dvc get` or `dvc import` runs. So, no need to do anything specific fo the AWS credentials file.

The only ugly thing here is that we have to use some conventions around remote names. Unless I'm missing something, guys - @efiop @wdixon ?

Also, @wdixon how would the best interface for this look like for you?

**Comment by wdixon** [comment]
We were defining a data registry projects to represent a complete set of images and annotations, backed by a single remote.  We are creating multiple registry projects (representing different kinds of data)

In much the same way with git, I was defaulting the name of the remote to "origin". Each project remotes used the same name, but pointed to a different location.

When it comes to a training a model...  A separate git/dvc project is being setup, with its own remote... We expect to track/push the model outputs to this remote....  The data for training would be dvc imported from 1 or more registry project(s).  My first model relies on 2 separate registry projects (2 remotes)

In my current situation - we are using the same bucket (same credentials) - to store each dvc project, under a separate folder (though this may change)....  the different remotes currently amount to a different path.

What we did was adopt a convention to use a profile name (in the dvc config) - that maps to a logical bucket...  And then everyone needs to ensure they have their aws credentials associated with the project configured profile name(s).

So I think you can either have a convention around remote names, or profile names - and accomplish the same thing? But I do like your unique remote name concept - as you then have complete control of the mapping to credentials, without the need to have a common profile name(s).  You do however require each team member create separate entries (in their global config) for each new project (we are in a conda environment that does not allow for /etc/ writing without getting our IT involved)

**Comment by shcheklein** [comment]
> So I think you can either have a convention around remote names, or profile names - and accomplish the same thing?

I guess, yes!

Overall, sounds like a great setup and great use of all the DVC features! I hope that it all will work well. Let us know if you hit any other bumps here.

**Comment by wdixon** [comment]
thanks for help
