### ISSUE TITLE
Tests and commands leftowers in in /tmp

### ISSUE THREAD

**Issue by pared** [iterative/dvc#4484]
```
DVC version: 1.6.1+334556 
---------------------------------
Platform: Python 3.7.5 on Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
Supports: All remotes
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
```

After running commands/tests we are leaving some leftovers in `/tmp`:
- [ ] analytics should remove the [target](https://github.com/iterative/dvc/blob/026c4fa47d0b3ed7d3bf931298d6fdf4ea6ee115/dvc/command/daemon.py#L32).

I see that also ExternalRepo lefts a lot of temporary dirs, though it seems like it might be part of https://github.com/iterative/dvc/pull/3286
@skshetry  change #4465 fixes removal of temporary cache dir in case of `dvc get`.

**Comment by skshetry** [comment]
@pared, this won't be solved by that PR. And, I think it's fine to not clear `/tmp`.

**Comment by pared** [comment]
@skshetry It seems to me that #4465 will take care of removing temporary cache in case of `dvc get`, because it will prevent its creation. Now we create [temporary cache](https://github.com/iterative/dvc/blob/026c4fa47d0b3ed7d3bf931298d6fdf4ea6ee115/dvc/repo/get.py#L39) and substitute its dir with another temporary dir. The original one, created inside `ExternalRepo` never gets removed.

**Comment by skshetry** [comment]
For the get and fetch, it will. But, `import/status`, it might not. One example is the checksum calculation. We could just elect to use dvc's cache, but it might need to work outside of repos as well, not sure about that.
