### ISSUE TITLE
push: seems like dvc fails when remote url is just the bucket

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4492]
## Bug Report
Failing command: `dvc push --run-cache`. Check screenshots below for more info. [It seems the url is just a bucket name](https://discord.com/channels/485586884165107732/485596304961962003/748540065872871530).

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
```
![dvc version](https://cdn.discordapp.com/attachments/485596304961962003/748537973930459217/unknown.png)

**Additional Information (if any):**

Context: https://discord.com/channels/485586884165107732/485596304961962003/748536752037167184

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

![verbose logging](https://cdn.discordapp.com/attachments/485596304961962003/748538487656939610/unknown.png)

**Comment by efiop** [comment]
Not able to reproduce. Might be related to our s3fs migration.
