### ISSUE TITLE
dvc broken when creating any environment with pipenv

### ISSUE THREAD

**Issue by cred-sillas** [iterative/dvc#4494]
## Bug Report

I am using an Ubuntu laptop and trying to installing dvc on a pipenv environment, but it does not work at all.

Here's what I do:

1. Create an empty folder called "test"
2. Initialize a pipenv by using `pip install`  with [this Pipfile template](https://pipenv-fork.readthedocs.io/en/latest/basics.html)
3. Run `pip shell` and `pip install dvc==0.62.1`
4. Run `git init` and then `dvc init`

Then I get this error message:

![](https://i.imgur.com/qqErbik.png)

**Comment by efiop** [comment]
Hi @cred-sillas ! 0.62.1 is extremely old, could you upgrade to the latest version and give it a try?

**Comment by efiop** [comment]
Closing as stale.
