### ISSUE TITLE
remove one of many stage outputs: misleading error message

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#4497]
Users cannot remove a data file if it is only one output of many for a stage. It is a valid behavior that needs a better error message:

```
$ dvc remove model.h5
ERROR: failed to remove 'model.h5' - "Stage 'model.h5' not found inside 'dvc.yaml' file"
```

The pipeline:
```
$ cat dvc.yaml
stages:
  train:
    cmd: python train.py
    deps:
    - users.csv
    - train.py
    - mymodel.py
    params:
    - epochs
    - opt
    - log_file
    - dropout
    outs:
    - logs
    - model.h5       # <-- trying to remove this one
    metrics:
    - summary.json:
        cache: false
    plots:
    - logs.csv:
        cache: false
```

**Comment by dmpetrov** [comment]
Also, formatting issues:
1. The prefix ` failed to remove 'model.h5' -` is not needed. Too obvious.
2. Quoted error message `"Stage 'model.h5' not ..."`

**Comment by skshetry** [comment]
@dmpetrov, we don't support removing a `.dvc` file by its output name yet. The target should be either a `.dvc` file or a name of the stage.

**Comment by efiop** [comment]
Another user ran into it https://discord.com/channels/485586884165107732/485596304961962003/798834932217937970
