### ISSUE TITLE
configuration based job limit

### ISSUE THREAD

**Issue by wdixon** [iterative/dvc#4504]
Seems that the current DVC push defaults --jobs to 4 * cpu_count()...  This is probably too high for larger machines - leading to file descriptor limits...    It would be nice to have this as a config option, so you don't have to always specify --jobs to limit the concurrency.

### Please provide information about your setup

**Output of `dvc version`:**

```console
DVC version: 1.6.3+828d1a 
---------------------------------
Platform: Python 3.8.5 on Linux-4.15.0-64-generic-x86_64-with-glibc2.10
Supports: http, https, s3
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by jenishah** [comment]
Hi, I would like to  work on this. Can someone suggest me on how the new [schema](https://github.com/iterative/dvc/blob/fcdb503b4eff1297e5c1c1ed18f5606fe780e481/dvc/config.py#L134) should look like ?

**Comment by efiop** [comment]
@jenishah Sure! You will simply need to add `jobs` to `REMOTE_COMMON` there and that should be enough.

**Comment by I159** [comment]
Hey there. I'm going to start it tonight.

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/4872 . Thanks @I159 ! :pray:
