### ISSUE TITLE
No module named 'azure.core'

### ISSUE THREAD

**Issue by dean-sh** [iterative/dvc#4522]
## Bug Report
We're using DVC installed with pip on Ubuntu 20.04.
We have a local cache and a remote on Azure blob storage.

On version 1.5.x till 1.6.6, we're experiencing this error while trying to use `dvc push`.
```
ERROR: unexpected error - No module named 'azure.core'
```
We've tried to install azure-core package using pip, but this basically installs an incompatible version with DVC.
Downgrading to 1.3.1 solves the issue.

### Please provide information about your setup

Running DVC from version 1.5 to 1.6.6 gives the same error.
Ubuntu 20.04

**Comment by pmrowla** [comment]
Hi @dean-sh, you most likely need to upgrade the `azure-storage-blob` pip package (which should then install the correct version of `azure-core`).

In DVC 1.5, the required azure dependency was changed to require `azure-storage-blob >= 12.0`, previously we required `azure-storage-blob==2.1.0`. You should be able to check which version you have installed with
```
pip freeze | grep azure-storage-blob
```

**Comment by dean-sh** [comment]
Hey,
Thanks for the assistance - solved our issue.

Upgrading with `pip install --upgrade dvc[azure]` solved the issue - I was wondering why the azure dependency wasn't upgraded with DVC itself.

Do you think you could add this to the documentation?

**Comment by efiop** [comment]
@dean-sh Totally! We have a ticket for it https://github.com/iterative/dvc.org/issues/702 . Thank you for the feedback!
