### ISSUE TITLE
add: improve message for overlapping outputs

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#4529]
### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.6.6+79e8e4
---------------------------------
Platform: Python 3.8.5 on macOS-10.15.6-x86_64-i386-64bit
Supports: All remotes
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1
Workspace directory: apfs on /dev/disk1s1
Repo: dvc, git
```

### Reproduce

Run `dvc add` on a directory with some data twice and get something like:

```console
(.env) √ Projects/test-dvc % dvc add data
Stage is cached, skipping
```

### Problem

~~`stage` term is not applicable here. This message should be fixed/changed.~~ https://github.com/iterative/dvc/pull/5385

### Bonus

Error message on the overlapping data should be avoiding term `output`. Instead we should be using `directory` or `file`. Also should we recommend `dvc add data` instead of commit (might be easier for users, no need to learn a new command).

```
(.env) √ Projects/test-dvc % dvc add data/file3
Adding...
ERROR: Cannot add 'data/file3', because it is overlapping with other DVC tracked output: 'data'.
To include 'data/file3' in 'data', run 'dvc commit data.dvc'
```

**Comment by gsvolt** [comment]
@shcheklein - may I work on this issue?

**Comment by shcheklein** [comment]
@gsvolt yes! absolutely, feel free to take it! thanks 🙏

**Comment by DiPaolo** [comment]
Is it fine to use a message similar I've tried to use at https://github.com/iterative/dvc/pull/5236? Something like this:
```WARNING 'data' is already under DVC control``` 

If it's okay, I will fix the issue soon.

**Comment by efiop** [comment]
Repurposing for the "bonus"

**Comment by skshetry** [comment]
Note that the message these days says something like following:
```
ERROR: bad DVC file name 'data/file3.dvc' is git-ignored.
```
