### ISSUE TITLE
solved: metrics: will not find other branches in my project

### ISSUE THREAD

**Issue by bobertlo** [iterative/dvc#4531]
Edit: solved

### Please provide information about your setup

**Output of `dvc version`:**

```console
DVC version: 1.6.1 (conda)
---------------------------------
Platform: Python 3.6.10 on Linux-5.7.10_1-x86_64-with-glibc2.9
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache types: hardlink, symlink
Repo: dvc, git
```

**Additional Information (if any):**

I did some troubleshooting yesterday with @efiop the git repo is clean, all data and pipelines are up to date. The metrics files are marked as such in `dvc.yaml` and being tracked by DVC (but I did create an experimental branch and turned `cache: false` on them and tracked with git, but it did not change anything.)

When running `dvc metrics diff`, all metrics say `diff not supported`.

```console
(autodev) [robert@cygnus automator (data)]$ dvc metrics diff --old --verbose  
2020-09-04 08:50:40,299 DEBUG: Check for update is enabled.                   
2020-09-04 08:50:40,433 DEBUG: fetched: [(3,)]                                
2020-09-04 08:50:41,461 DEBUG: fetched: [(3718097,)]                          
2020-09-04 08:50:41,481 DEBUG: fetched: [(3,)]                                
2020-09-04 08:50:42,200 DEBUG: fetched: [(3718097,)]                          
Path                      Metric            Old    New      Change            
metrics/dtextbox1.json    overall_accuracy  None   0.99777  diff not supported
metrics/dtextbox1.json    test_accuracy     None   0.99166  diff not supported
metrics/dtextbox1.json    train_accuracy    None   0.9993   diff not supported
metrics/biostext1.json    overall_accuracy  None   0.99984  diff not supported
metrics/biostext1.json    test_accuracy     None   0.99957  diff not supported
metrics/biostext1.json    train_accuracy    None   0.99991  diff not supported
```

Also, `dvc metrics show -a` will only show the current workspace:

```console
(autodev) [robert@cygnus automator (data)]$ dvc metrics show -a --verbose            
2020-09-04 08:51:28,867 DEBUG: Check for update is enabled.
2020-09-04 08:51:28,871 DEBUG: fetched: [(3,)]                        
2020-09-04 08:51:30,140 DEBUG: fetched: [(3718097,)]
workspace:                                                                          
        metrics/dbox1.json:                                                         
                train_accuracy: 1.0
                test_accuracy: 1.0                                                  
                overall_accuracy: 1.0                                               
```

Based on this second output I think it is just silently not able to see other branches/tags/commits? I'll see if i can manage to setup a dev copy and trace around. I'm just surprised there isn't an error coming up from this? I tried to reproduce in a fresh new repo, by producing metrics from scripts in the same way, but it worked just fine.

This current repo was created before `1.0` and has seen some interesting things... but I don't see how that could affect this? Maybe I can try deleting some of the generated state for troubleshooting?

Edit: also, `dvc params` works just as expected, so it is probably specific to the metrics code?

**Comment by iakremnev** [comment]
I can confirm this bug happens in DVC `v1.6.6`.
I just followed the *Getting Started: Experiments* section on dvc.org, working on the single master branch.
```
$ dvc params diff HEAD^1 HEAD
Path         Param                   Old    New
params.yaml  featurize.max_features  500    1500
params.yaml  featurize.ngrams        1      2
$ dvc metrics diff HEAD^1 HEAD
$ dvc metrics diff HEAD^1
Path         Metric    Value    Change
scores.json  auc       0.5674   diff not supported
```

And here's git diff:
```
$ git diff HEAD^1 dvc.lock
diff --git a/dvc.lock b/dvc.lock
index 20c1d45..d614a34 100644
--- a/dvc.lock
+++ b/dvc.lock
@@ -21,16 +21,16 @@ featurize:
     md5: 02180903aa05599ceaa6ff6ee2471d00
   params:
     params.yaml:
-      featurize.max_features: 500
-      featurize.ngrams: 1
+      featurize.max_features: 1500
+      featurize.ngrams: 2
   outs:
   - path: data/features
-    md5: 7fd2f827edc8bd4981b43f878253cdd1.dir
+    md5: 4de51b54708b84ebb50c7c12fd57179f.dir
 train:
   cmd: python src/train.py data/features model.pkl
   deps:
   - path: data/features
-    md5: 7fd2f827edc8bd4981b43f878253cdd1.dir
+    md5: 4de51b54708b84ebb50c7c12fd57179f.dir
   - path: src/train.py
     md5: ad8e71b2cca4334a7d3bb6495645068c
   params:
@@ -39,18 +39,18 @@ train:
       train.seed: 20170428
   outs:
   - path: model.pkl
-    md5: c4c067076a008802a8adc1881b870dec
+    md5: 17b3d1efc339b416c4b5615b1ce1b97e
 evaluate:
   cmd: python src/evaluate.py model.pkl data/features scores.json prc.json
   deps:
   - path: data/features
-    md5: 7fd2f827edc8bd4981b43f878253cdd1.dir
+    md5: 4de51b54708b84ebb50c7c12fd57179f.dir
   - path: model.pkl
-    md5: c4c067076a008802a8adc1881b870dec
+    md5: 17b3d1efc339b416c4b5615b1ce1b97e
   - path: src/evaluate.py
     md5: 631fd3f13434edcf4abd56a5b798e8b2
   outs:
   - path: prc.json
-    md5: cd433c034acfa2ebd5679a3838b65c7c
+    md5: d3c57bccfa924bee85e00f674b8724f9
   - path: scores.json
-    md5: 06df1f4765480cd62052eab00517a8d2
+    md5: 662bf00be6fe3172b69944b9d6f704cd
```

`dvc plots diff` works just fine.

**Comment by iakremnev** [comment]
Oops, my bad. Turns out I initially ran `dvc run <...> -o scores.json`, which added scores to `.gitignore`. After that I ran `dvc run --force <...> -M scores.json`. Git wasn't able to track scores and DVC couldn't compare metrics.

**Comment by efiop** [comment]
@iakremnev So the issue is resolved?

**Comment by iakremnev** [comment]
In my case, yes. I thought that my experience can be useful to @bobertlo.

**Comment by bobertlo** [comment]
@iakremnev no that was not the mistake I made. It is definitely still not working for me. 

Here is what my dvc.yaml looks like:

```
stages:
  gf5-training-gen:
    cmd: python training-gen.py gf5
    deps:
     - data/sorted
     - training-gen.py
     - automator/cnn/architectures/gf5.py
    params:
    - gf5.arch
    - gf5.data
    outs:
    - data/gen/gf5
  gf5-train:
    cmd: python train-model.py gf5
    deps:
    - data/gen/gf5
    - train-model.py
    - automator/cnn/architectures/gf5.py
    params:
    - gf5.arch
    - gf5.training
    outs:
    - cnndata/gf5
  gf5-eval:
    cmd: python evaluate-model.py gf5 results/gf5.csv metrics/gf5.json
    deps:
    - evaluate-model.py
    - cnndata/gf5
    outs:
    - results/gf5.csv
    metrics:
    - metrics/gf5.json
```

This is repeated many times and generated with a script. All the outputs are tracked with DVC and in `.gitignore`s. @efiop do you see anything I'm doing wrong?

**Comment by efiop** [comment]
@bobertlo Not right away, no, but admitedly didn't spend a lot of time looking into it. The simplest and the fastest way to find out what's wrong is to either have a reproducer script or for you to share your repo with one of us, so we could figure it out quickly. Would something like that be possible?

**Comment by bobertlo** [comment]
@efiop unfortunately, I don't think my employer would want me to share the repository.

When I get time I will see if I can reproduce this error. To start I will try to copy the pipeline systems into a new repository.

**Comment by bobertlo** [comment]
@efiop I just pulled out enough boilerplate code from the pipeline system I created to run `dvc repro` and the bug is reproduced.

I put the repository here: https://github.com/bobertlo/dvc-metrics-bug

I don't have anywhere public to place the dvc cache but I was just using a public dataset. Any images placed in class folders will get the pipeline running.

**Comment by efiop** [comment]
@bobertlo Thanks! :pray: Trying to reproduce right now...

**Comment by efiop** [comment]
For the record: agreed to have a call tomorrow to figure this out quicker on-site.

**Comment by bobertlo** [comment]
@efiop was very helpful troubleshooting this with me.

I was generating `dvc.yaml` from a script to handle many models with slightly different dependencies and had it in my `.gitignore`. It worked fine for me in running my pipelines and I forgot I had done this when it came time to generate metrics. Removing the `.gitignore` entry and tracking `dvc.yaml` solved my issue. It's a little embarrassing!

Thanks for the help!
