### ISSUE TITLE
dvc dag --outs

### ISSUE THREAD

**Issue by liamkesatoran** [iterative/dvc#4532]
In the `0.xx` version days, there was a `dvc pipeline show --outs` command that was able to show a DAG that included outputs. 
I thought this was a really nice feature. For instance, I have a `train_test_split` stage that creates two outputs, `train` and `test`, and it would be nice to see them taking different paths in the DAG.
Can you maybe (re)implement this feature?
Thanks!

**Comment by efiop** [comment]
Hi @liamkesatoran ! Thanks for the feature request! Indeed, we used to have it before 1.0, but decided to drop it as we were not sure how many users are actually using it.

The whole `dvc dag` implementation is located in https://github.com/iterative/dvc/blob/master/dvc/command/dag.py, we'll need to create a dag based on `stage.outs` for all stages.
