### ISSUE TITLE
DVC v.1.6.6 cannot be imported after Bokeh v.22.1 as both uses logging levelName = "TRACE"

### ISSUE THREAD

**Issue by PeterFogh** [iterative/dvc#4546]
## Bug Report
It has been a long time since I updated my DVC version - previously, I have used version 0.84.0 - but I have now updated to version 1.6.6. However, I get an assert error, when I first import Bokeh, before I import DVC in my python script - as seen in the image below (it fails both with `import dvc` and `import dvc.api`).
![dvc error](https://user-images.githubusercontent.com/5435299/92484948-9d2f8580-f1ea-11ea-9e01-eac0d9c7a0a9.png)

The assert shows that both DVC and Bokeh creates a loggingLevel and loggerClass, named "TRACE" and "trace", respectively.
I think DVC should handle - i.e. not fail at - this edge case, where TRACE already have been defined by another Python package or user code before DVC is imported.

PS: Thanks for the big improvements all DVC developer have done since version 0.84.0 - I'm so excited to use all of the new features 😄

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.6.6 (conda)
---------------------------------
Platform: Python 3.8.2 on Linux-5.4.0-45-generic-x86_64-with-glibc2.10
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
```

**Comment by efiop** [comment]
Might be solved by https://github.com/iterative/dvc/pull/4487

**Comment by efiop** [comment]
@PeterFogh Btw, what dvc API functionality were you planning to use here? Would a simple workaround of calling dvc through CLI do the trick for now for you?

**Comment by PeterFogh** [comment]
@efiop,
Well, we have used the `dvc.repo.Repo('.').graph` to save the DVC pipeline as a experiment artifact (pydot graph to a PNG image). However, we know that the DVC API is changing, and often we just fix our code to the new versions of the API.

**Comment by efiop** [comment]
@PeterFogh Sure, `dvc.repo.Repo('.').graph` is still there. You could use `dvc dag --dot` through CLI though, to save the dag in dot format.

**Comment by PeterFogh** [comment]
@efiop - super. However, we may still want to do in in Python - such that we only have one DVC stage (Python script) creating all of our artifacts.

**Comment by efiop** [comment]
@PeterFogh Totally. Just making sure it is not a blocker for you. Ideally, we should take a closer look at our logger in general in https://github.com/iterative/dvc/pull/4487 , but maybe there is a quick fix in a shape of changing TRACE to DVC_TRACE or something, just to run into conflicts with bokeh. Though, the conflicts are pretty harmless, we could also consider removing that assert, for now, to quickly unblock this.

**Comment by DonjetaR** [comment]
@efiop Dask also creates the same logging attribute "TRACE" as DVC does and we have again the issue about the import order.

![dvc_attribute_error](https://user-images.githubusercontent.com/23300143/94788935-956f9500-03d4-11eb-9c19-e112974e9981.PNG)

**Comment by asford** [comment]
@efiop This is currently a problem in applications that want to use `dvc.api` to retrieve data files from a `dvc` data repo. `dask`, and to a lesser extent, `bokeh` are pretty common parts of the python data science stack, so I think this may become more pressing as `dvc.api` sees more uptake.

Would you be open to fix at https://github.com/iterative/dvc/blob/cf1070a531456a267c3b57a35d17795397437699/dvc/logger.py#L21-L46
that adds the level if not present, rather than failing if the level is already exists?

As far as I can tell though a quick glace, DVC doesn't have a hard dependency on the numeric logging level and accesses the level the `trace` or `TRACE` symbolic names so this "should" be safe.
