### ISSUE TITLE
ERROR: failed to push data to the cloud - URL 'gdrive://**' is supported but requires these missing dependencies: ['pydrive2'].

### ISSUE THREAD

**Issue by kamal1262** [iterative/dvc#4560]
## Bug Report
I have install dvc using pip  but still throws me the follwoing error :

 If you have installed dvc using pip, choose one of these options to proceed: 

    1) Install specific missing dependencies:
        pip install pydrive2
    2) Install dvc package that includes those missing dependencies: 
        pip install 'dvc[gdrive]'
    3) Install dvc package with all possible dependencies included: 
        pip install 'dvc[all]'

I have followed the steps but it does not solve the issue.  

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.6.6 (pip)
---------------------------------
Platform: Python 3.7.7 on Darwin-19.6.0-x86_64-i386-64bit
Supports: gs, hdfs, http, https, s3, ssh
Cache types: reflink, hardlink, symlink
Repo: dvc, git
```
**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by efiop** [comment]
Hi @kamal1262 . Try `pip install 'dvc[gdrive]'` or `pip install 'dvc[all]'` to install deps for all clouds.

**Comment by popigg** [comment]
similar error here on version 1.7.2 with azure-storage-blob.

dvc push
ERROR: failed to push data to the cloud - URL 'azure://***' is supported but requires these missing dependencies: ['azure-storage-blob']. If you have installed dvc using pip, choose one of these options to proceed: 

    1) Install specific missing dependencies:
        pip install azure-storage-blob
    2) Install dvc package that includes those missing dependencies: 
        pip install 'dvc[azure]'
    3) Install dvc package with all possible dependencies included: 
        pip install 'dvc[all]'

If you have installed dvc from a binary package and you are still seeing this message, please report it to us using https://github.com/iterative/dvc/issues. Thank you!

Already installed dependencies

**Comment by efiop** [comment]
@popigg Azure also requires dependencies. You could either `pip install 'dvc[azure]'` or `pip install 'dvc[all]'` to install with all dependencies for all remotes, as noted in that error message.

**Comment by efiop** [comment]
@popigg So you've installed them and you are still getting the same error? Check that you've installed it into the same environment. Could you show `$ dvc version` output, please? Note that it contains more info than just the version itself.

**Comment by popigg** [comment]
sorry for the trouble, restarting the computer make it working. Looks like installed dependencies weren't updated in the same terminal tab. Thanks
Nevertheless 

DVC version: 1.7.2 (pip)
---------------------------------
Platform: Python 3.7.4 on Darwin-19.6.0-x86_64-i386-64bit
Supports: All remotes
Cache types: reflink, hardlink, symlink
Repo: dvc, git

**Comment by efiop** [comment]
Glad to hear it works now :slightly_smiling_face: Closing.

**Comment by anthony-khong** [comment]
I understand this is an old issue, but I did not quite find the solution, so I'll share mine.

I ran into the same issue with Google Drive on MacOS. I had to `pip install "dvc[gdrive]"`, but that doesn't quite do it. I had to reinstall `dvc` with `brew uninstall dvc` then `brew install dvc`.

**Comment by efiop** [comment]
@anthony-khong pip install shouldn't affect dvc brew package. My guess is that maybe you've installed the new brew package in the last step and it started working (we had some problems not that long ago https://github.com/Homebrew/homebrew-core/pull/74742 )

**Comment by anthony-khong** [comment]
Thank you @efiop for the clarification. The issue you mentioned seems to be relevant here. I did install DVC using brew shortly before you opened the issue!
