### ISSUE TITLE
dvc import allow for artifact re-name

### ISSUE THREAD

**Issue by wdixon** [iterative/dvc#4563]
Currently DVC import requires that the imported artifact have the same name as the resource name being imported:

```bash
usage: dvc import [-h] [-q | -v] [-o <path>] [--rev <commit>] url path

Example:
    dvc import https://foo.com.git my_dvc_resource
```
However; if you choose to name the resource with a common name, like *images* - you may want to import more than one resource having the same name.  This forces you to introduce folders in the import project - so the imported dvc resource names don't collide.  Or you may have some desired path structure that isn't aligned with the dataset you are importing. 

It seems once you import the resource, you could edit the .dvc file, and change the outs, and likely rename my_dvc_resource.dvc file to alternative_dvc_resource_name.dvc to avoid file name collision and prevent confusion.

```bash
md5: 6ad067bdd582e50be74f41b9fe4be1bd
frozen: true
deps:
- path: my_dvc_resource
  repo:
    url: https://foo.com/datasets_regression.git
    rev_lock: 3873c875874a8efa84beef454a4b40ab3541d124
outs:
- md5: d25ed5d7cf4a5b35852f597f771e188b.dir
  path: alternative_dvc_resource_name
```

- While this manual process appears to work *(any issues wit what I just did?)* 
- it would be convenient if this could be handled directly at time of import

```bash
usage: dvc import [-h] [-q | -v] [-o <path>] [--rev <commit>] url path [name_in_import]

Example:
    dvc import https://foo.com/datasets_regression.git my_dvc_resource alternative_dvc_resource_name
```

Thoughts?  Issues? Warnings?

**Comment by efiop** [comment]
@wdixon Might be missing something, but have you tried `-o` option?

**Comment by wdixon** [comment]
Sorry, I had missed that option...  That was what I was looking for!

Thanks

**Comment by efiop** [comment]
@wdixon Maybe you have suggestions for https://dvc.org/doc/command-reference/import on how to clarify it? Maybe worth adding an example for renaming the artifact?
