### ISSUE TITLE
debian: GPG key required to add dvc repository

### ISSUE THREAD

**Issue by bobertlo** [iterative/dvc#4565]
Someone reported on discord that installing on debian did not work:

```
@ruslan Hi again,
I am trying to install dvc on compute engine on a debian machine
$ uname -a
Linux instance-1 4.19.0-10-cloud-amd64 iterative/dvc.org#1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

Here are the commands that I try to install on debian machine.
$ sudo wget \
       https://dvc.org/deb/dvc.list \
       -O /etc/apt/sources.list.d/dvc.list
$ sudo apt update
$ sudo apt install dvc

Unfortunately this returns
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dvc

Can you help about it please?
```

I verified the instructions on the website but was suspicious since there was no key added. I tried on my machine (Debian WSL) and got this error when running `sudo apt update`:

```
W: GPG error: https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 13587BADC50AAAD1
```

**Comment by efiop** [comment]
Hi @bobertlo ! Thanks for creating this issue!

That one is a known issue https://github.com/iterative/dvc-s3-repo/issues/3 with our deb packages, but it is a warning that is normally ignored by apt (it is a GPG error, but deb warning), so shouldn't affect users, unless a strict policy is in place that doesn't allow installing such packages.

Closing in favor of https://github.com/iterative/dvc-s3-repo/issues/3 . Thanks again for the feedback! :pray:

**Comment by bmabir17-asj** [comment]
Hello @efiop ,
I am getting a similar error
`W: GPG error: https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F84CB84729F1B545`
The workflow was working fine 2 days ago.

**Comment by efiop** [comment]
@bmabir17-asj Hey. Could you please make sure you ran

```
wget -qO - https://dvc.org/deb/iterative.asc | sudo apt-key add -
```

from https://dvc.org/doc/install/linux#from-repo-on-debian-ubuntu ?

**Comment by bmabir17-asj** [comment]
@efiop ,
Thanks . After running
```bash 
wget -qO - https://dvc.org/deb/iterative.asc | sudo apt-key add -
```
I got another error with `NO_PUBKEY` for nvidia cuda package and solved it with the following commands
```bash 
sudo apt update 2>&1 1>/dev/null | sed -ne 's/.*NO_PUBKEY //p' | while read key; do if ! [[ ${keys[*]} =~ "$key" ]]; then sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys "$key"; keys+=("$key"); fi; done

```

**Comment by efiop** [comment]
@bmabir17-asj So it solved the issue for you, right? Just making sure 🙂

**Comment by bmabir17-asj** [comment]
@efiop yes

**Comment by david-waterworth** [comment]
Note on Ubuntu 22.04 this method works but is deprecated

``` bash
wget -qO - https://dvc.org/deb/iterative.asc | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
```

**Comment by efiop** [comment]
Thanks @david-waterworth ! 🙏 Created https://github.com/iterative/dvc-s3-repo/issues/121
