### ISSUE TITLE
import: support --no-exec

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4567]
What's the point of `import-url --no-exec`?

Our [docs](https://dvc.org/doc/command-reference/import-url#options) read "E.g. if the file or directory already exist it can be used to skip download. dvc commit <out>.dvc should be used to calculate the URL and data hash, update the .dvc files, and save existing data to the cache."

Why would you want to import a file that you already have, and that would the be immediately overwritten as a regular output with `commit`? (if I get that last part right)

And why doesn't it exist in `import`?

**Comment by jorgeorpinel** [comment]
Please transfer to dvc.org if this is mainly a matter of re-explaining the option's motivation. But it seems inconsistent that `import` doesn't also have it so we could keep this one as a request to add it there.

**Comment by skshetry** [comment]
@jorgeorpinel, a contributor asked for it, here's the motivation: #3513.

**Comment by jorgeorpinel** [comment]
I see. Shouldn't it be in `import` as well though? For consistency at least, and because of the same motivation.

**Comment by efiop** [comment]
@jorgeorpinel We'll add one if someone asks for it.

**Comment by jorgeorpinel** [comment]
I'm mentioning all this because someone asked for it implicitly in https://discuss.dvc.org/t/direct-copy-between-shared-cache-and-external-dependencies-outputs/487/3

**Comment by efiop** [comment]
@jorgeorpinel Ah, ok, makes sense. Repurposing this issue then.

**Comment by jorgeorpinel** [comment]
Thanks!

**Comment by BurnzZ** [comment]
Hello everyone! I'm picking this up. :)
