### ISSUE TITLE
when executing: dvc repro --run-all set ENVIRONMENT_VARIABLE with current dvc workspace and pass it to the command executed by dvc run/repro

### ISSUE THREAD

**Issue by yogi81** [iterative/dvc#4586]
when executing: dvc repro --run-all set ENVIRONMENT_VARIABLE with current dvc workspace and pass it to the command executed by dvc run/repro

This is needed to be able to execute parallel runs in docker like environment.

**Comment by pared** [comment]
@yogi81 can you elaborate a little bit?
What is the system you run on?

Wouldn't (in case of bash) `ENV_VAR={value} dvc run/repro`  solve the problem?

**Comment by yogi81** [comment]
@pared No this is not possible to set a variable in advance, because only dvc has the knowledge where a temporal workspace is created after dvc has created it in a preparation step of command executing.

Additionally it would be good to have additional meta information like for example experiment queue index number if multiple queue entries are executed.

**Comment by aschuh-hf** [comment]
I second this request (cf. [Discord message](https://discord.com/channels/485586884165107732/563406153334128681/811627066612514866). In my case, I am interested in being able to specify `CUDA_VISIBLE_DEVICES` such that multiple queued experiments use their dedicated GPU on a multi-GPU server. Otherwise parallel runs of processes requiring GPUs will fail because they are running out of GPU memory.

**Comment by pared** [comment]
We already are able to attach `env` to the stage internally, thanks to `checkpoints` and `live`. So supporting this should be a matter of defining how to handle variables from user perspective. `--env` option for `run` and `env` section for stage in `dvc.yaml` sounds like a reasonable solution, which we could expand later (for example env for whole `dvc.yaml`)

**Comment by aschuh-hf** [comment]
@pared I think an explicit support to set environment variables would be nice. Given your suggestion, I am now wondering however how this would differ from setting a parameter in the `params` section or via `--params`? Except for that user program would have to set the environment variable from the parameter if required. For example in my case, would the following work?

`train.py`:
```
import os

params = load_params("params.yaml")  # Load params
os.environ["CUDA_VISIBLE_DEVICES"] = str(params.CUDA_VISIBLE_DEVICES)
```

`dvc.yaml`:
```
stages:
  train:
    cmd: python train.py
```

```shell
> dvc exp run --params CUDA_VISIBLE_DEVICES=0 train
```

**Comment by dberenbaum** [comment]
Yes, good points, @aschuh-hf ! Not sure if you are still following in Discord, but there is one caution in there that you might want to consider. I'd agree that this is a separate issue (you don't need any info about the current DVC workspace), so maybe following up in Discord is best.
