### ISSUE TITLE
Missing package paramiko error for ssh connection when installing via conda-forge and pip

### ISSUE THREAD

**Issue by JenniferHem** [iterative/dvc#4616]
I wanted to use DVC to track files and push them via SSH to a remote repository. I am not sure if I misread the installation guide. I was assuming that installation via conda-forge would contain the ssh dependency as well.  However, when using DVC in my project and trying to push changes to a ssh remote I get the following error:

    ERROR: failed to push data to the cloud - URL {ssh:user@host/path/to/file}  is supported but requires these missing 
    dependencies: ['paramiko']. If you have installed dvc using pip, choose one of these options to proceed:

    1) Install specific missing dependencies:
        pip install paramiko
    2) Install dvc package that includes those missing dependencies:
        pip install 'dvc[ssh]'
    3) Install dvc package with all possible dependencies included:
        pip install 'dvc[all]

I have installed DVC via conda-forge and conda list shows: 
dvc                       1.7.3            py37hc8dfbb8_0    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge

**Output of `dvc version`:**

```console
$ dvc version

DVC version: 1.7.3 (conda)
---------------------------------
Platform: Python 3.7.0 on Windows-10-10.0.18362-SP0
Supports: azure, gdrive, gs, hdfs, http, https, s3, oss
Cache types: hardlink
Repo: dvc, git 

```

Installation of dvc or paramiko fails beause it is already part of the einvironment. Did I miss to install any package via conda to make it work? 

Edit:
--> the same occurs when installing via pip (pip install dvc[all])

```console
$ dvc version

DVC version: 1.7.4 (pip)
---------------------------------
Platform: Python 3.7.0 on Windows-10-10.0.18362-SP0
Supports: azure, gdrive, gs, hdfs, http, https, s3, oss, webdav, webdavs
Cache types: hardlink
Repo: dvc, git

```

**Comment by efiop** [comment]
@JenniferHem Could you show full log for ` pip install 'dvc[all]'`, please?

**Comment by efiop** [comment]
Not able to reproduce on linux, might be some windows-specific conflicts or something. Need to investigate.

**Comment by efiop** [comment]
Might be related to https://github.com/iterative/dvc/issues/4589 .

**Comment by efiop** [comment]
Also worth improving that error message, as we now know the package type and can choose an appropriate message.

**Comment by efiop** [comment]
Ok, found the cause: https://github.com/iterative/dvc/issues/4589#issuecomment-698366656 . Working on a fix.

**Comment by JenniferHem** [comment]
Okay I did a clean install in a new repository and here is the log
Here is the full log: [log.txt](https://github.com/iterative/dvc/files/5276479/log.txt)

Interestingly now I got dvc version 1.7.5 before I only got 1.7.4 (after uninstalling dvc with conda and reinstalling with pip) --> It works now on a fresh install. 

So this triggered a few tests: 

1) If i create a repository with `conda create -n dvctest -c conda-forge dvc` I also get the ssh dependency, however it installs python 3.8

1) If i create a repository with `conda create -n dvctest python=3.7` and then install dvc later via `conda install -c conda-forge dvc` I do not get the ssh dependency (Python version 3.7.0) --> log is here: [log_conda.txt](https://github.com/iterative/dvc/files/5276678/log_conda.txt)

**Comment by efiop** [comment]
@JenniferHem  Btw, are you using Match in your ssh config?

**Comment by JenniferHem** [comment]
@efiop no I am not using match

**Comment by efiop** [comment]
1.7.6 is out on pypi. Conda package will be released later today. Please give it a try and let us know how it goes slightly_smiling_face Thanks again for the feedback!
