### ISSUE TITLE
`dvc gc -w` breaks run cache for non-cached files

### ISSUE THREAD

**Issue by peper0** [iterative/dvc#4634]
## Bug Report

If we have output files with `cache: false` in the repository, running `gc clean` removes these files from the cache wile `dvc repro` wants to restore them through run cache. Using `--no-run-cache` option workarounds this problem. The script below shows exact way of reproducing the bug.

```
#!/bin/bash -x

git init
dvc init
dvc cache dir .dvccache
echo 1 >a
dvc run -d a -M b -n makeb 'cat a a > b'
echo 2 >a && dvc repro

echo 1 >a && dvc repro # ok, restores the file
echo 2 >a && dvc repro # ok too

dvc gc -w

echo 1 >a && dvc repro # FAIL

dvc repro --no-run-cache # now ok
```

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.7.9 (deb)
---------------------------------
Platform: Python 3.7.9 on Linux-4.15.0-112-generic-x86_64-with-debian-buster-sid
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda2
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git
```

**Comment by peper0** [comment]
Hi. It seems that in version 2.9.3 the problem is not present anymore. Currently, if run-cache refers to a file that does not exist in the cache, dvc simply reproduces the file.

**Comment by dtrifiro** [comment]
Thanks @peper0! Closing the issue
