### ISSUE TITLE
Azure service principal authentication

### ISSUE THREAD

**Issue by JordanSimba** [iterative/dvc#4635]
I want to be able to authenticate against my remote using service principal (service account) credentials. The motivation being that these carry some identity when transacting against the data in the cloud which is a necessity for my auditing solution for sensitive data. 

[This](https://stackoverflow.com/questions/54324146/azure-datalake-with-dvc) is another individual after the same feature.
[This](https://discord.com/channels/485586884165107732/485586884165107734/784482317699121203) (edit by @shcheklein)
https://github.com/iterative/dvc/issues/5045 - another user asking about this

I'm keen to implement this and put up a PR.

One gotcha straight off the bat:

- Testing will require live cloud credentials as I cant really find a local emulator for this kind of auth. After speaking with some contributors it seems like live credentials exist for AWS, but not necessarily Azure. Would this be something the project is willing to add?

**Comment by efiop** [comment]
@JordanSimba Live credentials complicate and slow down the testing, so if we could at least have a unit test + a by-hand verification from an actual user (you) - we would be happy to accept the PR.

**Comment by itraveribon** [comment]
Hi,

first of all, thank you for the nice job you are doing here with your tool. The use of SAS keys is not recommended in my company. They recommended us to use Service Principal Authentication instead. Do you know when is expected to release this feature?

Thank you in advance

**Comment by JordanSimba** [comment]
Hey @itraveribon, I've been quite busy with work, I'm can't give you a timeline, but I will be getting back to development on my pull request now.

**Comment by isidentical** [comment]
Hey @JordanSimba, a gentle ping on the PR. Are you available to continue? (no worries if you are busy)

**Comment by efiop** [comment]
Fixe
