### ISSUE TITLE
Should we shift this log to `trace`?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4638]
> Assuming '/<cache path>' is unchanged since it is read-only

Just had to read a log of 100098 lines, out of which 100009 lines where those.
Only 89 lines had somewhat meaningful information.

**Comment by efiop** [comment]
@skshetry Sure, let's do that. :+1:

**Comment by skshetry** [comment]
Also, we need to set string repr for `CacheInfo`.

Should we also change these to `trace`?
```
2020-09-29 15:39:13,956 DEBUG: fetched: []
100087:2020-09-29 15:39:13,956 DEBUG: Path '.dvc/cache/cb/39aad982e843bb9a8bd42844617a88' inode '66237166'
100088:2020-09-29 15:39:13,956 DEBUG: fetched: [('1601365128351995136', '33727104', 'cb39aad982e843bb9a8bd42844617a88', '1601365152697586944')]

```

**Comment by efiop** [comment]
@skshetry Sure, makes total sense! Please feel free to move to trace any messages that you see fit. :ok_hand:
