### ISSUE TITLE
Generate list of cache objects in use

### ISSUE THREAD

**Issue by MetalBlueberry** [iterative/dvc#4663]
Hi all!!

I'm planing to have a shared cache with several projects and I'm worried about long-term health. The main worry is that people will run experiments on side branches that can be eventually removed. The result of this operations is that the stored files in the remote will be virtually lost as the hash wont be tracked anywhere. 

- The current `dvc gc` won't work because it works on single repositories
- The flag `dvc gc -p` may work, but feels like magic and requires that dvc removes the file directly from the remote. For example, this is not supported by http remotes.

I would like to have a command that just prints all the references used by a given project. This way it would be really easy to use external tools to cleanup remotes. I think `dvc gc` is already doing something like this under the hood, so I hope this is easy to implement.

Use cases

- Generate list of all files used by different projects sharing the same remote so you can remove unused files.
- Generate a list of files used by tagged commits so you can cleanup intermediate commits to save remote space.
- Generate a list of files used by a single project to migrate the data to another remote with external tools.

**Comment by efiop** [comment]
@MetalBlueberry Could you elaborate why `dvc gc --projects` doesn't work for you? I don't think it will remove anything from the remote unless you specify `-c` as well.

**Comment by MetalBlueberry** [comment]
The main goal is to remove things from the remote. What I do not want is dvc removing it for me.

Following the previous example, the HTTP remote doesn't allow to remove data because it is not implemented so `dvc gc` won't work.

I think that having a list of the files used by a given project is something that dvc can easily provide, and with that list, it is really easy to clean up remotes using external tooling.

**Comment by efiop** [comment]
> Following the previous example, the HTTP remote doesn't allow to remove data because it is not implemented so dvc gc won't work.

Maybe let's just implement that in HTTPTree? IIRC, we didn't do that simply because there wasn't anyone using it with HTTP. All one needs to do is to implement `remove()` and `walk_files`(does your server support this?) methods in https://github.com/iterative/dvc/blob/master/dvc/tree/http.py and gc should start working.

> I think that having a list of the files used by a given project is something that dvc can easily provide, and with that list, it is really easy to clean up remotes using external tooling.

Sure, but if only the lack of gc support for http is the problem, it makes a lot of sense to just implement it and use it. If that is not an option, sure we could implement something like `--dry` for it.

**Comment by MetalBlueberry** [comment]
My main objective is to keep things simple.

- print list of used files? easy.
- remove data from different supported remotes? hard.
- remove data from shared remote? really hard.

I'm not saying that we should not support this features, I just say that the first one can be implemented in one day, while the others will require a little longer.

**Comment by efiop** [comment]
@MetalBlueberry Sorry, but it still seems like there is still misunderstanding here.

> remove data from different supported remotes? hard.

Already implemented for all remotes except http. E.g. `dvc gc --cloud`

> remove data from shared remote? really hard.

Already implemented for all remotes except http. E.g. `dvc gc -p proj1 -p proj2 --cloud`

I guess I'm still not quite understanding why implement your own gc collection if you can simply add http support to an existing gc. Or is there something else in the way? Don't get me wrong, I'm not against `gc --dry` per se, we'll be glad to accept a PR for it.

**Comment by karajan1001** [comment]
> remove data from shared remote? really hard.

How can we know remote repo files' tracking conditions in a distributed code repo? As our code is distributed, only go through all repo of code can we make sure that if some files are useless. So the remote DVC repo can only add not delete its contents.

**Comment by MetalBlueberry** [comment]
> @MetalBlueberry Sorry, but it still seems like there is still misunderstanding here.
> 
> > remove data from different supported remotes? hard.
> 
> Already implemented for all remotes except http. E.g. `dvc gc --cloud`
> 
> > remove data from shared remote? really hard.
> 
> Already implemented for all remotes except http. E.g. `dvc gc -p proj1 -p proj2 --cloud`

I see your point, I will evaluate this approach

> Don't get me wrong, I'm not against `gc --dry` per se, we'll be glad to accept a PR for it.

I would like to have the time and the knowledge to do it myself, but this is not a priority in our current roadmap so it will stay in the backlog.

Thank you for your help. maybe we can just leave this open with `help wanted`

**Comment by efiop** [comment]
@MetalBlueberry Can't really keep it with `help wanted` as it is not even clear what approach you really need implemented: `http` support for gc or `gc --dry`. So far I still don't see the reasons why you want to implement `gc` manually, if you could simply implement http support for it. Feel free to point me to specific reasons if I've missed any. Let's just close this issue for now, as there are no more requests for --dry. We'll be glad to reopen/create a new issue for the approach that you will decide to choose. Thank you for the feedback! :pray:
