### ISSUE TITLE
add support for WebHDFS

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#4687]
We currently support real HDFS by using pyarrow, but the problem with it is that it still requires libhdfs, which has to be installed separately and in some cases (on osx) is not at all trivial to install (brew's hadoop package doesn't provide it, for example). See https://github.com/iterative/dvc/issues/4656 Also [pyarrow itself has caused us some problems](https://github.com/iterative/dvc/issues?q=is%3Aissue+pyarrow+), as it requires wheels to be present for all platforms.

WebHDFS is often enabled by default alongside pure HDFS and there are lots of available libs for working with it https://pypi.org/search/?q=hdfs . It would be great if we could implement some basic support for it to have it as a potential alternative to pure HDFS. To do that, we need to support urls that look like `webhdfs://example.com/path`, e.g.:

```
dvc remote add my webhdfs://example.com/path
```

which requires creating `dvc/tree/webhdfs.py` with an appropriate Tree class, which should at least implement these methods:

```
exists
_upload
_download
```
which will allow us to use `dvc push/fetch/pull/(status -c)`. One could use one of the existing implementation for other clouds in dvc/tree, e.g. https://github.com/iterative/dvc/blob/master/dvc/tree/oss.py  as a template.

**Comment by efiop** [comment]
Regarding the tests, as initial support, it would be totally fine to have some manual confirmation that the author of the PR has ran it and it works for him. But the next step could be to adjust our existing hdfs testing infrastructure (it spins docker container https://github.com/iterative/dvc/blob/master/tests/docker-compose.yml) to use webhdfs port too and create a `webhdfs` fixture in https://github.com/iterative/dvc/blob/master/tests/remotes/hdfs.py , that we could then add to the list in https://github.com/iterative/dvc/blob/c16d3fa43d144dc800aea7d7aa80f772bab4312b/tests/func/test_data_cloud.py#L24

**Comment by efiop** [comment]
Some info about performance:

```
For light load applications, WebHDFS and native protobuf RPCs provide comparable data throughput, but native connectivity is generally considered to be more scalable and suitable for production use.
```

from https://wesmckinney.com/blog/python-hdfs-interfaces/ . Though clearly it will depend on particular library, there might be some bad ones. But still, this is an experiment :slightly_smiling_face:

**Comment by tomasfarias** [comment]
I'd like the chance to work on this if nobody is taking it already. If it's not too much of a hassle, I have created a draft PR to discuss a few points: https://github.com/iterative/dvc/pull/4747

Documentation issues/work is still missing, but I intend to also tackle it once the PR has been ironed out.
