### ISSUE TITLE
sync: ssh remote support not included on the Windows build

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4712]
## Bug Report

```console
λ dvc push -r localssh
ERROR: failed to push data to the cloud - URL 'ssh://poj12@localhost' is supported
but requires these missing dependencies: ['paramiko']. If you have installed dvc using pip...
```

### Please provide information about your setup

**Output of `dvc version`:**

```console
λ dvc version
DVC version: 1.8.1 (exe)
---------------------------------
Platform: Python 3.7.9 on Windows-10-10.0.18362-SP0
Supports: azure, gdrive, gs, hdfs, http, https, s3, oss, webdav, webdavs
Cache types: hardlink
Cache directory: NTFS on C:\
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Additional Information (if any):**

Notice how `Supports` doesn't include `ssh`.

**Comment by efiop** [comment]
Might be related to https://github.com/iterative/dvc/issues/4616

**Comment by efiop** [comment]
Unable to reproduce with 1.8.1 or newer versions. All exes show that all remotes are supported. @jorgeorpinel Could you confirm that you still see that error and `dvc version` still shows that it is from exe but doesn't have all remotes?

**Comment by jorgeorpinel** [comment]
I was still seeing the problem. I uninstalled DVC and re-installed it, AND restarted because it was throwing a weird error, and now it's normal. Windows... 😠
