### ISSUE TITLE
dvc diff takes forever

### ISSUE THREAD

**Issue by kweston** [iterative/dvc#4744]
## Bug Report
Running a dvc diff took about 70 minutes to run. 
### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
```
DVC version: 1.8.1 (pip)
---------------------------------
Platform: Python 3.7.7 on Linux-4.15.0-101-generic-x86_64-with-debian-buster-sid
Supports: gs, http, https
Cache types: hardlink, symlink
Repo: dvc, git

**Additional Information (if any):**

I have 16722 files in my .dvc cache and 5 .dvc files. 3 of which point to directories. 

And my .dvc/config file:
```
[core]
    remote = nas
['remote "nas"']
    url = /mnt/NAS/Production/project/dvc-cache

```
I'm using a NAS as the remote and most of the data is images. Looks like there is about 900 MB of data total

Here is the output of `dvc diff -v`

[diffout.gz](https://github.com/iterative/dvc/files/5402958/diffout.gz)

**Comment by efiop** [comment]
Hi @kweston !

Could you please run

```
dvc diff -v --cprofile --cprofile-dump diff.prof &> log.log
```
and post `diff.prof` and `log.log`?

**Comment by kweston** [comment]
[log.log](https://github.com/iterative/dvc/files/5404442/log.log)
[diff.prof.gz](https://github.com/iterative/dvc/files/5404448/diff.prof.gz)
Hi @efiop 
Here you go

**Comment by pmrowla** [comment]
This is most likely the diff directory performance issue (#4580) which was addressed in DVC 1.8.2. @kweston can you update DVC and then try running diff again?

**Comment by kweston** [comment]
You are correct. Updated dvc to v1.8.4 and now it takes just 16 seconds for a diff. I can live with this. Thanks for the help!

**Comment by efiop** [comment]
Closing for now. There will be more optimizations soon, stay tuned! :wink:
