### ISSUE TITLE
md5 hash calculation breaks on ssh remote for filepaths with spaces

### ISSUE THREAD

**Issue by SNeugber** [iterative/dvc#4766]
### Please provide information about your setup

**Output of `dvc version`:**

```console
DVC version: 1.7.2 (conda)
---------------------------------
Platform: Python 3.8.3 on Windows-10-10.0.18362-SP0
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
```

**Additional Information (if any):**

When tracking external outputs on an SSH remote, the md5sum command breaks when there are files with spaces in their path.

(PR for fix will follow shortly)

**Comment by efiop** [comment]
Likely related https://github.com/iterative/dvc/issues/4628
