### ISSUE TITLE
tree: better NotImplemented error handling

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#4787]
In certain cases (e.g. remote doesn't support external dep, import-url, etc) we throw a `NotImplementedError` error. From the user perspective it looks like:

```
ERROR: unexpected error
```

It is not an unexpected error. Also it is not informative- we must provide details- what kind of feature, is there some hint, is it temporary unavailable or it's impossible to implement at all, etc.

Ideally we should make deps, outs, trees behave in a way that force answering properly all those questions above ^^ while implementing it. Otherwise we'll have a constant long tail of issues like this - per function, per remote, per tree.

**Comment by efiop** [comment]
For the record: we use RemoteActionNotImplemented for nicer error where we expect them, and NotImplementedError for abstact methods. But we do have some mixups. Need to switch to ABC for a base tree so these cases are easier to distinguish.

**Comment by shcheklein** [comment]
from the message for `RemoteActionNotImplemented` I see that it's mostly for those actions that are impossible to implement at all (not supported != not implemented to me actually). Ideally we should distinguish with those that are not implemented yet, e.g. we have a ticket for this.

**Comment by efiop** [comment]
Closing as stale. Migrating to fsspec where we'll have less of NotImplementedError's , as there are only a handful of methods to implement for any new fs.
