### ISSUE TITLE
Provide a way for .metrics.show() and .plots.collect() users to see missing files

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#4788]
This is needed to warn a user that something went wrong.

**Comment by shcheklein** [comment]
@Suor could expand a bit on the scenario?

**Comment by Suor** [comment]
Now absent files, usually from cache, which wasn't checked out, are silently skipped. `Repo.metrics.show()` makes a warning, `Repo.plots.collect()` is silent. I want to get some info when I call either of those, like a list of missing files.

**Comment by shcheklein** [comment]
@Suor got it, thanks! (does it come from the Viewer - like detect when we need credentials to be set?)

**Comment by Suor** [comment]
Comes from viewer. It's not about credentials, but simply showing a user that something is absent:
- forgot to `git add` a git tracked metric/plot
- forgot to `dvc push`

It's not even always possible to set credentials, e.g. if a user is using a local remote or if remote is only specified in local/global config and we don't see it.

**Comment by dberenbaum** [comment]
Closing as stale
