### ISSUE TITLE
Investigate flaky tests_open_granular[azure]

### ISSUE THREAD

**Issue by pared** [iterative/dvc#4792]
`tests/func/test_api.py::test_open_granular[azure]` seems to be failing sometimes ([example](https://github.com/iterative/dvc/pull/4791/checks?check_run_id=1309923097)). We need to fix it.

**Comment by efiop** [comment]
Looks like it is simply racing a bit. The container is not ready when this is called. Just need to add a flaky decorator.

**Comment by skshetry** [comment]
@efiop, better to wait for and timeout than adding flaky, as rerunning it still has chances of the container not being ready.

**Comment by ju0gri** [comment]
I'll be looking into this issue.

**Comment by efiop** [comment]
@skshetry Ideally we need some retrying logic in our trees, but that is a much bigger task. Just slapping a flaky decorator should do the trick for now.
