### ISSUE TITLE
status: detect moved artifacts

### ISSUE THREAD

**Issue by jnothman** [iterative/dvc#4794]
## Bug Report

Moving or renaming a file in an imported registry will result in `dvc status` failing with an ERROR.

### Steps to reproduce

```sh
cd /tmp
mkdir registry user
cd registry
git init
dvc init
touch foo
dvc add foo
git add .gitignore foo.dvc
git commit -am "Add foo"
cd ../user
git init
dvc init
dvc import /tmp/registry foo
cd ../registry
dvc move foo bar
git add bar.dvc .gitignore
git commit -am "foo -> bar"
cd ../user
dvc status
```

### What happened

```
ERROR: The path 'foo' does not exist in the target repository '/tmp/registry' neither as a DVC output nor as a Git-tracked file.:
```
EXIT STATUS 1

### What I expected

```
foo.dvc:
	changed deps:
		path missing:   foo (/tmp/registry)
```

by analogy to

```
foo.dvc:
	changed deps:
		update available:   foo (/tmp/registry)
```

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.9.0 (brew)
---------------------------------
Platform: Python 3.9.0 on macOS-10.15.7-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Repo: dvc, git
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by efiop** [comment]
Just to clarify: this is not a bug. Unlike git, dvc doesn't really detect the things being moved. Theoretically, we could do that, but that would introduce an additional level of complexity and could be error-prone. It would also introduce quite an overhead (at least I don't see an efficient way to do it), as we will have to parse the git history to find moved similar .dvc files, which will degrade the performance when handling an error (which might seem like an ok thing, but users might complain). Overall, an acceptable alternative for data-registries would be to introduce some explicit `aliases`(aka `redirects`) mechanism (e.g. file) that people could adjust by hand, but we didn't hear any requests for it just yet.

**Comment by efiop** [comment]
Closing as stale.
