### ISSUE TITLE
dvc params diff doesn't compare commits properly

### ISSUE THREAD

**Issue by lefos99** [iterative/dvc#4798]
### Please provide information about your setup

**Output of `dvc version`:**
```console
$ dvc version
DVC version: 1.9.0 (deb)
---------------------------------
Platform: Python 3.7.9 on Linux-5.4.0-48-generic-x86_64-with-debian-buster-sid
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
```
Hey all,
So I encountered a problem by running my dvc experiments, so let me describe it:

Steps:
### Running first experiment ###
1. Firstly I run `dvc repro evaluation_v1`. This is the stage that triggers my whole pipeline:
![image](https://user-images.githubusercontent.com/9488658/97420836-18203d00-190c-11eb-979a-ad0f71e30061.png)
2. This will run successfully and will alternate as expected my `dvc.lock` file. After that, I `git add && git commit` the `dvc.lock`. 
The following picture shows the git diff of this commit:
![image](https://user-images.githubusercontent.com/9488658/97422290-e5774400-190d-11eb-8983-5a530410d7fa.png)
As you can see, apart from some hashes, there are no parameters that have changed.
### Running second experiment ###
3. Then I decide to run another experiment and the only thing that I change are two parameters in my training routine. Thus I run again `dvc repro evaluation_v1`.
4.  This will run successfully and will alternate as expected my `dvc.lock` file. After that, I `git add && git commit` the `dvc.lock`. 
The following picture shows the git diff of this commit:
![image](https://user-images.githubusercontent.com/9488658/97421200-8664ff80-190c-11eb-9c7d-07a6969072bd.png)
As you can see, apart from some hashes, there are two parameters that have changed that affect my training pipeline:
- checkpoint
- num_epochs

### Comparing the two experiments ###
5. By running `dvc metrics diff 8077dedd13ac98a13007e7b11294d5954e195f1f ae0d16ba8ecf839a84aa189bc0d759f8486c0bdd`, I get correctly the different metrics results. :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/9488658/97422521-325b1a80-190e-11eb-8294-60ac8aa7c25d.png)

6. The problem appears when I want to compare these different commits in regard to their parameters: :x: 
`dvc params diff 8077dedd13ac98a13007e7b11294d5954e195f1f ae0d16ba8ecf839a84aa189bc0d759f8486c0bdd --verbose`
returns 
```
2020-10-28 10:12:54,216 DEBUG: Check for update is enabled.
2020-10-28 10:12:54,252 DEBUG: fetched: [(3,)]                        
2020-10-28 10:13:14,135 DEBUG: fetched: [(3905922,)]
2020-10-28 10:13:14,160 DEBUG: fetched: [(3,)]                        
2020-10-28 10:13:34,874 DEBUG: fetched: [(3905922,)]
2020-10-28 10:13:34,904 DEBUG: Analytics is enabled.
2020-10-28 10:13:34,936 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmprxx6l9me']'
2020-10-28 10:13:34,938 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmprxx6l9me']'
(base) deep@okocha:~/users/lefos/code/ihc_cell_detection/ihc_cell_detection/ki67_er_pr$ [37959] Failed to execute script __main__
```

**Comment by pmrowla** [comment]
`[37959] Failed to execute script __main__`
This makes it look like it might actually be a process crash.

If you just run `dvc params diff` with no arguments, do you see the same error message? (Using no arguments will diff your current workspace with HEAD, but even if there are no changes the process should normally just exit cleanly with a `0` return code)

**Comment by lefos99** [comment]
By running `dvc params diff --verbose`, I get the following:
```
2020-10-28 11:00:37,130 DEBUG: Check for update is enabled.
2020-10-28 11:00:37,172 DEBUG: fetched: [(3,)]                        
2020-10-28 11:00:57,595 DEBUG: fetched: [(3905922,)]
2020-10-28 11:00:57,617 DEBUG: fetched: [(3,)]                        
2020-10-28 11:01:18,477 DEBUG: fetched: [(3905922,)]
Path                                     Param            Old    New
training/config/config_train_debug.json  checkpoint              /home/deep/data/dvc_cache/46/a53b475c0f0f6d5fe80ffad8ba85c1
training/config/config_train_debug.json  experiment_name         hunter_without_anti
training/config/config_train_debug.json  gpu_idx          [0]    [1]
training/config/config_train_debug.json  num_epochs       10000  50
2020-10-28 11:01:18,510 DEBUG: Analytics is enabled.
2020-10-28 11:01:18,545 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpnz8hh59m']'
2020-10-28 11:01:18,547 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpnz8hh59m']'
(base) deep@okocha:~/users/lefos/code/ihc_cell_detection/ihc_cell_detection/ki67_er_pr$ [41074] Failed to execute script __main__

```

**Comment by pmrowla** [comment]
Ah ok, so the error message is just from the analytics daemon and is unrelated.

One other possible thing I noticed is:

> 2. This will run successfully and will alternate as expected my `dvc.lock` file. After that, I `git add && git commit` the `dvc.lock`.

You should also be `git commit`'ing your changes to your parameters file (`config_train_debug.json`). If you are only committing `dvc.lock` changes, that would be the cause for your problem.

`dvc.lock` is used internally in certain parts of DVC as a way for us to see that "this particular combination of input dependencies and parameters will give this particular set of outputs", but when using commands like `params diff` and `metrics diff`, DVC will read the values from the actual params and metrics files, not from a `dvc.lock` file.

**Comment by lefos99** [comment]
Perfect! Thanks for the detailed and clear explanation @pmrowla ! :smiley_cat: 

You may close the issue then! :+1:
