### ISSUE TITLE
plots show "missing" options that metrics show has: -aTR and --all-commits

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4799]
Options that `plots show` doesn't have but `metrics show` does:

![image](https://user-images.githubusercontent.com/1477535/97480954-b9fa5680-1919-11eb-8aa6-e55b826dff49.png)
> From https://dvc.org/doc/command-reference/metrics/show#options

Should they be added? (except `--show-json`)

**Comment by jorgeorpinel** [comment]
Cc @pared

**Comment by pared** [comment]
@jorgeorpinel This is a good question, since we are aiming to unify behavior for `plots` and `metrics` in aspects like UX (errors) it would make sense to make their options consistent. 

@dmpetrov am I right?

Related to #4446

**Comment by jorgeorpinel** [comment]
p.s. BTW maybe `--all-commits` could have short flag `-C`.
