### ISSUE TITLE
[WinError 123]  problem while pushing to google drive 

### ISSUE THREAD

**Issue by kumarsuraj9450** [iterative/dvc#4800]
I was following DVC tutorial on youtube and at 'dvc push' stage I got an error :

```
ERROR: unexpected error - [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\HP\\Desktop\\cml_test1\\.dvc\\gdrive:\\11OX2HCLGQNMuBudP508LOfwGF35s0qpK'
```

also whenever I add remote gdrive directory .dvc\config file shows:
```console
$ dvc remote add -d -f remote gdrive://11OX2HCLGQNMuBudP508LOfwGF35s0qpK  

[core]
remote = remote
['remote "remote"']
url = ..\gdrive:\11OX2HCLGQNMuBudP508LOfwGF35s0qpK

```

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version

PS C:\Users\HP\Desktop\cml_test1> dvc version                                                                                                                                                                                                DVC version: 0.54.1
Python version: 3.7.9
Platform: Windows-10-10.0.18362-SP0
Binary: False
Cache: reflink - False, hardlink - True, symlink - True
Filesystem type (cache directory): ('NTFS', 'C:\\')
Filesystem type (workspace): ('NTFS', 'C:\\')
```

**Comment by kumarsuraj9450** [comment]
Even if i make changes to .dvc/config manually 
```
[core]
remote = remote
['remote "remote"']
url = gdrive://11OX2HCLGQNMuBudP508LOfwGF35s0qpK

```

Error is still there

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/485596304961962003/771100323653484564

@kumarsuraj9450 Your `dvc version` output seems to be missing the version itself. Also by looking at the rest of the output, I see that you are probably using some very old version of dvc (please check `dvc --version`). Could you try upgrading (current version is 1.9) and giving it a try again? Please make sure that `dvc --version` shows a correct version after the upgrade.

**Comment by kumarsuraj9450** [comment]
okay i'll try

**Comment by kumarsuraj9450** [comment]
Thanks a lot. It's working now
