### ISSUE TITLE
dvc move provides incorrect instructions for how to track the change in git

### ISSUE THREAD

**Issue by algal** [iterative/dvc#4814]
## Bug Report

If you do a `dvc move` command, DVC tells you what git command you should execute in order to track the changes in git.

However, DVC provides an incorrect guidance.

It only tells you to do a `git add` operation to add the new `.dvc` file, a modified `.gitignore` file in the destination directory, and a modified `.gitignore` file in the source directory.

It does not tell you that must also do, in addition, either a `git rm` command to remove the old `.dvc` from the source directory, or else a `git mv` command to effect the move of the `.dvc`.

So if you followed DVC's instruction, you'd be left with unstaged changes left over in your working directory.

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.9.1 (brew)
---------------------------------
Platform: Python 3.9.0 on macOS-10.15.7-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Repo: dvc, git
```
<img width="738" alt="Screen Shot 2020-10-30 at 11 53 29" src="https://user-images.githubusercontent.com/264412/97761249-6ecf7780-1ac2-11eb-8f88-4f2c6af06701.png">

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by algal** [comment]
Any interest in me submitting a PR to fix this? If the PR were good, would that be likely to make into master within a month?

**Comment by shcheklein** [comment]
@algal absolutely! that would be great 🙏 . I don't anticipate this PR to be very complex, so it should be merged fast. And we do release quite often.
