### ISSUE TITLE
--no-fetch for import and pull

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#4815]
It can be useful when only a subset of files needs to be pooled or imported. From here https://discuss.dvc.org/t/working-with-a-small-subset-of-remote-data/541

**Comment by dmpetrov** [comment]
An alternative name `--dry-run` (like in `dvc run`)

**Comment by shcheklein** [comment]
@dmpetrov why `--no-fetch` is needed for `dvc pull`?

@efiop it looks this is solve, `import` has `--no-exec` now?

**Comment by efiop** [comment]
Closing as stale.
