### ISSUE TITLE
import: `--jobs` option

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#4838]
`dvc import` Provides an easy way to reuse files or directories tracked in any DVC repository. This external tracked data might be stored in a remote DVC repository. In this situation `--job` which controls the parallelism level for DVC to download data from remote storage would be a useful option.

**Comment by karajan1001** [comment]
@efiop

**Comment by efiop** [comment]
@karajan1001 ? :slightly_smiling_face:

**Comment by karajan1001** [comment]
@efiop 
What is the difference between `BaseTree.download` and `RepoTree.get_dir_hash`?
In the first one, `jobs` is read from a config file while in the second, it was passed as a parameter.

And in 
https://github.com/iterative/dvc/blob/6d745eb4f0fc4578e3abea25a9becaf2c9da1612/dvc/dependency/repo.py#L71-L80
This function inherited from the first one calls the second. Is it OK to add a `jobs` param to the first function which might be redundant?

**Comment by efiop** [comment]
@karajan1001 Usually for `download` the parallelization happens before calling it, e.g. in `Remote.push/pull/status`. For `get_dir_hash`, depending on how it is configured, it might need to `pull` the whole directory with all the files, and that's where the `jobs` is used. So considering that dvc is not splitting files into blocks and downloading whole files, `--jobs` for import only makes sense for directories.
