### ISSUE TITLE
is there a Docker image?

### ISSUE THREAD

**Issue by joehoeller** [iterative/dvc#4849]
is there a Dockerfile avail for this?

**Comment by shcheklein** [comment]
@joehoeller there is no Docker image that is specifically built for DVC. (What would be your use case, btw? DVC seems to be pretty lightweight to be installed independently). There is a Docker image for our second project - [CML](https://cml.dev) that also installs DVC among other things- `docker://dvcorg/cml-py3:latest`.

**Comment by joehoeller** [comment]
I need to build out a K8s deployment (helm chart)

**Comment by shcheklein** [comment]
@joehoeller would apt install work for you (as described [here](https://dvc.org/doc/install/linux#install-from-package))?

```console
$ wget https://github.com/iterative/dvc/releases/download/1.9.1/dvc_1.9.1_amd64.deb
$ apt install ./dvc_1.9.1_amd64.deb
```

**Comment by joehoeller** [comment]
No - I’ll build a docker image and deploy it to k8 pods.

**Comment by shcheklein** [comment]
@joehoeller sorry, I didn't make it clear I guess. I mean you could use `RUN` command in your Dockerfile to install dvc. Something like this: https://github.com/iterative/cml/blob/master/docker/Dockerfile#L30 (except that you don't probably need other stuff besides `git` and `dvc`). Would it work for you?

**Comment by joehoeller** [comment]
I’ll give it a try and see and let you know. Thank you.

**Comment by efiop** [comment]
@joehoeller Any luck so far? :slightly_smiling_face:

**Comment by joehoeller** [comment]
havent had a chance, but ill get there ;)

**Comment by efiop** [comment]
Closing for now, feel free to reopen if you'll have any questions :)
