### ISSUE TITLE
Size for Git file

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#4856]
DVC started tracking files and dirs size. It make sense for data files since the files are not available in the repo. Do we really need size/nfiles for files tracked by Git? Let's remove these for Git files.

```
   - path: src/evaluate.py
     md5: 631fd3f13434edcf4abd56a5b798e8b2
     size: 1091
```

**Comment by efiop** [comment]
My logic here is that it might be very useful meta information to identify the things that your pipeline was run with (deps also have sizes/nfiles). I would keep it as is, as it is better to have it than not have it.

**Comment by efiop** [comment]
Had a private discussion and decided to leave it.
