### ISSUE TITLE
Make the dvc files hidden

### ISSUE THREAD

**Issue by klakhdhar** [iterative/dvc#4857]
It would be nice to make the .dvc files hidden to be consistent with git for instance like with .gitignore.
That would make projects look visually better organized.
Thanks

**Comment by skshetry** [comment]
Hi @klakhdhar. Could you please care to explain what you mean by hidden? The description does not help us at all.

**Comment by klakhdhar** [comment]
Hi @skshetry,
When one adds a file to be tracked by issuing dvc add command. For instance, tracking a file named **data.csv**, DVC creates a **data.csv.dvc** file and also **.gitignore** file.
I was wondering if it's possible to make the created dvc files hidden. In the example that would mean having a dvc file called **.data.csv.dvc** please notice the **.** in front of the dvc file. This way we can avoid duplicating the visual content of a folder

**Comment by skshetry** [comment]
@klakhdhar, you can specify `-f` flags when using `dvc add`, and yes to also create hidden files. But, hiding it that way is not a good practice. Most of the users create a separate directory to keep those `.dvc` files and I'll recommend you the same, if it has gotten out of hands.

Let's say you have `dvcfiles` directory.
You can do `dvc add data.csv --file dvcfiles/data.csv.dvc`

But, I'd like to have it all on a single file, maybe optionally, but that's bad for the merges, so ...

**Comment by klakhdhar** [comment]
Great thanks. Having all the dvc files in one folder is more appropriate in this case.
Thanks, I'm closing this feature request then.
Regards,
