### ISSUE TITLE
dvc repro does not churn out outputs of previously executed run-caches in another folder/machine

### ISSUE THREAD

**Issue by ryzalk** [iterative/dvc#4861]
## Bug Report
This issue pertains to the usage of DVC's `run-cache`. As highlighted in [this discussion](https://discuss.dvc.org/t/dvc-1-0-release/412/5), `run-cache` is supposed to have a long memory of runs. Any changes to code and parameters for which its values have been used (executed) before, with or without commits, `dvc repro` will comb through the run caches and retrieves the output(s) that matches the version of the code and parameters that is being accounted for.

### Please provide information about your setup

A repository dedicated to reproducing/replicating the aforementioned issue can be found [here](https://github.com/ryzalk/test-dvc-rc-pub). It contains a [`README.md`](https://github.com/ryzalk/test-dvc-rc-pub/blob/master/README.md) with detailed instructions to do that.

**Additional Information (if any):**

Detailed information and instructions can be found in the aforementioned repository:
https://github.com/ryzalk/test-dvc-rc-pub

### Outcome
The issue is considered reproduced/replicated when the `slice` stage is executed with the following output:
```bash
'titanic.csv.dvc' didn't change, skipping
Running stage 'slice' with command:
	python slice-data.py
Updating lock file 'dvc.lock'

To track the changes with git, run:

	git add dvc.lock
```

**Comment by efiop** [comment]
Closing as stale.
