### ISSUE TITLE
experiments: consider using hydra for CLI params syntax

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#4883]
Follow up to #4780

python-benedict for parsing raw yaml syntax works for the moment, but as noted by @skshetry something like [hydra](https://hydra.cc/docs/next/advanced/override_grammar/basic/) would probably be more user-friendly

**Comment by sjawhar** [comment]
Just to clarify: python-benedict does **not** parse raw yaml. That is being handled by ruamel.YAML here:
https://github.com/iterative/dvc/blob/251a3269c2c5f7e39938274b06fca319de1bf79b/dvc/repo/experiments/run.py#L22-L30
https://github.com/iterative/dvc/blob/251a3269c2c5f7e39938274b06fca319de1bf79b/dvc/utils/serialize/_yaml.py#L69-L70

Benedit handles putting the parsed param value into the params dict using the dot-separated key path. Hydra definitely looks awesome, but it looks like its use case is a bit different than what you're looking for here (and seems to only have experimental support for what this issue would need: https://hydra.cc/docs/next/experimental/compose_api)

**Comment by johnnychen94** [comment]
To properly set up GitLab CI, I need to modify parameters with a much much smaller network and dataset, then I ran into this...

```yaml
  scripts:
    - dvc exp run --params models.gaussian_15.data.max_num_patches=1000,models.gaussian_15.train.model_width=8,models.gaussian_15.train.model_depth=5,models.gaussian_15.train.batch_size=32,models.gaussian_15.train.epochs=2,models.gaussian_25.data.max_num_patches=1000,models.gaussian_25.train.model_width=8,models.gaussian_25.train.model_depth=5,models.gaussian_25.train.batch_size=32,models.gaussian_25.train.epochs=2,models.gaussian_50.data.max_num_patches=1000,models.gaussian_50.train.model_width=8,models.gaussian_50.train.model_depth=5,models.gaussian_50.train.batch_size=32,models.gaussian_50.train.epochs=2
```

Which would be much easier to read if we can reformat them into:

```yaml
  # will insert one extra space between each param, which doesn't follow the current dvc params syntax
  scripts:
    - dvc exp run --params
      models.gaussian_15.data.max_num_patches=1000,
      models.gaussian_15.train.model_width=8,
      models.gaussian_15.train.model_depth=5,
      models.gaussian_15.train.batch_size=32,
      models.gaussian_15.train.epochs=2,
      models.gaussian_25.data.max_num_patches=1000,
      models.gaussian_25.train.model_width=8,
      models.gaussian_25.train.model_depth=5,
      models.gaussian_25.train.batch_size=32,
      models.gaussian_25.train.epochs=2,
      models.gaussian_50.data.max_num_patches=1000,
      models.gaussian_50.train.model_width=8,
      models.gaussian_50.train.model_depth=5,
      models.gaussian_50.train.batch_size=32,
      models.gaussian_50.train.epochs=2
```

It currents failed to parse the params input because one extra whitespace is inserted when flattening multiline scripts into oneliner...

**Comment by pmrowla** [comment]
For running an experiment with this many modified parameters, I would recommend editing `params.yaml` directly rather than using the `dvc exp run --params` option. `dvc exp run` will include any uncommitted changes to `params.yaml` in the experiment.

Whether you do this via `sed` or a separate script that writes `params.yaml` would be up to you.

**Comment by johnnychen94** [comment]
Does it sound good to have `dvc exp run --params test_params.yaml` which loads all the params in that file?

**Comment by turian** [comment]
I also would be interested in Hydra support for DVC. I am using Hydra but would like to use DVC too.

**Comment by paantya** [comment]
Hydra has been updated and now these are not such "experimental" functions as they were before!
@sjawhar

**Comment by sjawhar** [comment]
> Hydra has been updated and now these are not such "experimental" functions as they were before!
> @sjawhar

Indeed! I just did a quick test and it seems like it might work. I'd have to refresh myself on the DVC param parsing codebase (It's been a while since I last contributed), but this could mean that DVC wouldn't need to maintain any param merging logic :)

```python
# %%
import pathlib

import hydra

params_file = pathlib.Path("relative/path/to/params.yaml")
with hydra.initialize(config_path=params_file.parent, job_name="dvc"):
    params = hydra.compose(
        config_name=params_file.stem, overrides=["foo.bar=a"]
    )
    print(params)
```
