### ISSUE TITLE
api: `Repo.stage` for loading/dumping stages

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4886]
Right now, this _service_ was provided through `Dvcfile.stages` and `Dvcfile.stage`. The problem with the API is it requires us to create `Dvcfile` each time even if we don't need it. 

We already have wrappers around it due to above reason: 

https://github.com/iterative/dvc/blob/3daeeaffdb43989283719d9cd8a7a4825dda19d5/dvc/repo/__init__.py#L258
https://github.com/iterative/dvc/blob/3daeeaffdb43989283719d9cd8a7a4825dda19d5/dvc/repo/__init__.py#L266

This might get more complicated with group stage run target, i.e. name of the stage group of a foreach.
So, it'd be great to have a simple wrapper that'd look like this:
```python
>>> repo.stage.load_one("build", file="dvc.yaml")
>>> repo.stage.load_all(file="data.csv.dvc")
>>> repo.stage.load(target="", file="")
```

The API might improve, when trying to improve this. That is what I have in mind.

**Comment by efiop** [comment]
@skshetry Is it required for some other feature/usecase? Just wondering about the background.
