### ISSUE TITLE
Git submodule ignored in the dvc dependency

### ISSUE THREAD

**Issue by dmidge8** [iterative/dvc#4894]
## Bug Report

I created a dvc run "makefile", based on two dependencies. One which is the data, successfully tracked with a dvc repository imported through dvc import. The second dependency tracked is a git submodule that contains the code. However, when there is a modification in the git submodule, dvc fails to track the changes, either local or commited/pushed.

The output is:
`2020-11-14 13:34:31,218 DEBUG: Assuming '/pathtotraincode/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only`.
It seems it does check that no changes happen, even though it doesn't show unless the verbose option is enabled, but the changes are not registered.

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
1.9.1
```

**Comment by pared** [comment]
@dmidge8 I am unable to reproduce your problem.
I created git submodule, added it as a dependency to my "main" repo run command. Modifying code (and running `dvc repro`) results in the reproduction of the whole run command. 
Could you share the result of `dvc repro -v`? Also, if its possible, could you share `dvc.yaml` section responsible for this particular run?

**Comment by dmidge8** [comment]
Very good question. Looking at the dvc.yaml to send it to you, I understood what went wrong. The command that I was executing was containing several commands which were seperated by "&&". Because of that, only the first part of the command was executed and reproduced, not the rest of it.
My bad, sorry for the noise.

**Comment by pared** [comment]
@dmidge8 no problem, we are here to help :)
