### ISSUE TITLE
plots: allow to modify any (Vega) prop

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4909]
Could `plots modify` behave a bit more like `config` where it accepts a key pair as arguments? Instead of relying on specific options like `-x` and `--title` to set the corresponding Vega properties.

All of these could be valid keys: https://vega.github.io/vega/docs/specification/ although validating the values could be tricky...

**Comment by pared** [comment]
We could actually go with dictionary/json update. When we were talking about smoothing plots I mentioned [that approach](https://github.com/iterative/dvc/issues/3906#issuecomment-639483890). 
We could let user provide his own "modification" that would be applied only to particular plot - so the end plot would be a sum of template + modification applied with dvc plots modify (or even yaml written in `dvc.yaml`).

**Comment by pared** [comment]
As to veryfing, maybe we could make use of vega schema, but its quite big, not sure if its worth it:
https://raw.githubusercontent.com/vega/schema/master/vega-lite/v4.17.0.json

**Comment by skshetry** [comment]
@pared, `pydantic` can generate the `model` from the JSONSchema: https://pydantic-docs.helpmanual.io/datamodel_code_generator. That might be useful.
