### ISSUE TITLE
repro: glob-style selection of stages

### ISSUE THREAD

**Issue by mdekstrand** [iterative/dvc#4912]
It would be useful to be able to select stages by glob, either at the top level or within a specific `dvc.yaml` file.

For example, if I have `eval/dvc.yaml` that evaluates several models over several data sets, I would like to be able to reproduce the evaluations over one data set with something like:

    dvc repro eval/dvc.yaml:AZ-*

Or:

    dvc repro --stages='AZ-*' eval/dvc.yaml

With the much-improved support for executing unrelated jobs in parallel in recent versions of DVC, this will enable me to submit each data set as a separate job to the cluster's batch scheduler, along with I imagine a host of other use cases.

**Comment by efiop** [comment]
We've added `--glob` for `dvc add` very recently https://github.com/iterative/dvc/pull/4864 , so it makes to continue https://github.com/iterative/dvc/pull/4864 with this ticket as well. I would say `dvc repro eval/dvc.yaml:AZ-*` works well, but I would probably make it an opt-in behavior with `--glob` flag for now, same as we currently have in `dvc add`, just to be safe. We'll turn this on everywhere by-default in the near future.

**Comment by skshetry** [comment]
@mdekstrand, I have created #4976 to support this feature. Please take a look.
