### ISSUE TITLE
Cache expiration time

### ISSUE THREAD

**Issue by Once88** [iterative/dvc#4919]
I think it is a reasonable requirement to set the expiration time for the cache. Especially for shared cache, we may only need, say, cache within 7 days. Then, dvc can help us automatically delete expired cache data to prevent the cache directory from getting bloated.

Context: https://discord.com/channels/485586884165107732/485596304961962003/779263477067022336

**Comment by jorgeorpinel** [comment]
Related to #678.

**Comment by efiop** [comment]
Closing in favor of #678.
