### ISSUE TITLE
Modify dataset in registry from pipeline

### ISSUE THREAD

**Issue by jvendegna** [iterative/dvc#4931]
When using a [data registry](https://dvc.org/doc/use-cases/data-registries) there is no way to modify a dataset from a downstream project/pipeline.
Currently a work-around is needed. We can clone the data registry in our pipeline and dvc update, git commit, dvc push from there.

Request: provide a way to pull specific dataset(s) from a registry, modify them, and update the registry from a downstream project/pipeline that uses them.

**Comment by efiop** [comment]
Hi @jvendegna .

You use `dvc import` to get that dataset into your project, right? If so, first thing that comes to mind is something like `dvc export` to shove the changes back into the registry, but that will require either a `git push` if it belongs to you or `git push` + creating a PR to the original project. Also not clear how to handle imports with a specific `rev` that might be some random commit.

Or do you use dvc through API?

We actually do have a library in the works (not public yet) that has pretty much that in a form of `publish` method. Shame it is not public yet, but IIRC @shcheklein has given you an early access already :slightly_smiling_face:

**Comment by efiop** [comment]
Closing as stale
