### ISSUE TITLE
remove: delete .gitignore file if empty

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4962]
Just like `dvc remove` deletes dvc.yaml and dvc.lock if they're empty after the removal, should it do the same to .gitignore? Currently it's left there even if empty, which shows up as a change in git (so it's pretty obvious).

**Comment by devramx** [comment]
I am exploring DVC. Can I be assigned this one ?

**Comment by efiop** [comment]
@devramx Sure! Thanks for looking into it! :pray:
