### ISSUE TITLE
dvc gc says "ERROR: Unable to acquire lock" when using -p option

### ISSUE THREAD

**Issue by lumbric** [iterative/dvc#4965]
## Bug Report

When I try to call `dvc gc -p <some path>`, I get the following error message:

```
$ dvc gc --workspace -p data/input/some_folder
WARNING: This will remove all cache except items used in the workspace of the current and the following repos:
  - /home/user/path/to/repo/data/input/some_folder
Are you sure you want to proceed? [y/n] y
ERROR: Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
```

There is definitely no other instance of dvc running. If I remove the lock file and run `dvc gc` again, I get the same error message again and the lock file has been re-created.

What seems suspicious to me is that there are like 200 tmp files in the cache:

```
./.dvc/cache/.CGpUDKbQJHzxfdDfc3YFKv.tmp
./.dvc/cache/29/fc25639deaf9c8e54d62a5703eeecc.JyNyLMdBV3KfEufjH9DXFF.tmp
./.dvc/cache/74/2c181c0b8984002c53cf88e1d66990.fSeDjfdEtMKCSUoxtnsK3Y.tmp
...
```
But on the other hand, the issue seems to be reproducible for me...

### How to reproduce

```
# create folders
mkdir testrepo
cd testrepo
mkdir data

# initialize
git init
dvc init
git commit -m 'Initialize'

# create some large file
dd if=/dev/zero of=data/largefile  bs=1M count=5
git add .gitignore data.dvc
git commit -m 'Add data to DVC'

echo 'change large file' > data/largefile
dvc add data
git commit -am 'Change large file'

# reproduce bug
dvc gc --workspace -p .
```

Note that `dvc gc --workspace` without the `-p` option does not raise this error.

### Older error message

Before upgrading to dvc 1.10.1, the error message looked like this:

```
ERROR: cannot perform the command because another DVC process seems to be running on this project. If that is not the case, manually remove `.dvc/tmp/lock` and try again.
```
(This might help others using older versions to google for this ticket.)

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.10.1 (conda)
---------------------------------
Platform: Python 3.8.5 on Linux-5.3.0-45-generic-x86_64-with-glibc2.10
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/xubuntu--vg-root
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/mapper/xubuntu--vg-root
Repo: dvc, git
```

**Comment by pmrowla** [comment]
> But on the other hand, the issue seems to be reproducible for me...
> 
> ### How to reproduce
> ```
> # reproduce bug
> dvc gc --workspace -p .
> ```
> 
> Note that `dvc gc --workspace` without the `-p` option does not raise this error.

So for this case, this is currently expected behavior, although it probably shouldn't be. If you pass `-p .` into `gc`, DVC will try to open your current repo twice: once when you call `dvc gc` inside your DVC repo, and a second time when DVC looks through any repos passed in with `-p`. (So the repo will already be locked when we try to open it the second time)

---

Regarding `data/input/some_folder`, is this the path to another DVC repo? The way you run are running `gc` makes it look like this path is actually just a subfolder inside your current DVC repo, which will cause the same "open current repo twice" behavior as using `gc -p .`.

**Comment by lumbric** [comment]
Hm don't really understand what you mean by "expected behavior". Doesn't this completely break the `-p` option?

Yes my example is a bit confusing, `-p .` doesn't make sense. What I wanted to achieve is to garbage collect files of some specific folders. So `dvc gc --workspace -p data` would make more sense for the example to demonstrate my use case and it leads to the same error message.

**Comment by lumbric** [comment]
Oh sorry, I think I completely misunderstood the `-p` option. Reread the help text and now I understand also your post... :)
I think what I was looking for is an option which allows to keep the complete cache for sub folders of the repository.

I guess this ticket can be closed or maybe the error message improved. Not sure if nested repositories is really a thing which needs to be supported.
 Sorry for the noise!
