### ISSUE TITLE
repro: don't show `push` helper message when outputs did not change 

### ISSUE THREAD

**Issue by pared** [iterative/dvc#4981]
`version: 1.10.2`

From: https://github.com/iterative/dvc/pull/4737#discussion_r531502639

When we run `repro` and some stages get reproduced, we get a reminder about using push to keep our [updated files](https://github.com/iterative/dvc/blob/c989b28eae536f08767d3cb32e790187d63a581b/dvc/command/repro.py#L34).

The bug: in docs example we update code only, without affecting outputs (we are just adding `print` in our code). Yet,
the helper message is shown. We should probably base the need to display this message basing on `dvc status` and not reproduced stages.

reproduction script:

```
#!/bin/bash

rm -rf repo
mkdir repo
pushd repo

set -ex
git init --quiet
dvc init --quiet

git add -A
git commit -am "init"

echo "data" >> data

echo -e "with open('data','r') as f1, open('out', 'w') as f2:\n\tf2.write(f1.read())" >> code.py

dvc run -n copy -d data -d code.py -o out python code.py


echo -e "with open('data','r') as f1, open('out', 'w') as f2:\n\tf2.write(f1.read())\n\tprint('something')" > code.py

dvc status
dvc repro
```

`status` shows that only `code.py` is changed (non-dvc managed asset), and `dvc repro` shows `Use dvc push to send your updates to remote storage.` This message should not be shown, as there is nothing to push by `dvc`.

**Comment by Vonski** [comment]
Hey, I would like to do this one if it is free to grab?

I've just played around with it a little bit and if I understand correctly desired behaviour will be to display this message only if some files tracked by dvc were changed. Is that correct?

If so, I do not see a way to determine it basing only on status, because `...reproduce(...)` line is modifying state of the repo. In this example you can't say from inside the body of `run` method of `CmdRepro` class if the reproduced stage changed any output files or not if you only use status method.

The solution I was thinking about was to validate at the beginning of the command if the current status does not show any changes in files tracked by dvc, then gather current metadata of tracked files connected to the stages from status if any is present and compare this metadata with its counterpart after `...reproduce(...)` line.

I'm new to the codebase, I'll be grateful for every tip and explanation. If I misunderstood smth please point it out.

**Comment by pared** [comment]
> I've just played around with it a little bit and if I understand correctly desired behaviour will be to display this message only if some files tracked by dvc were changed. Is that correct?

Yes, this is correct.

> If so, I do not see a way to determine it basing only on status, because ...reproduce(...) line is modifying state of the repo. In this example you can't say from inside the body of run method of CmdRepro class if the reproduced stage changed any output files or not if you only use status method.

I think its not true:
1. `Repo.repro` returns list of reproduced stages.
2. We can use reproduced stages to get their outputs
3. We can use the outputs to provide `targets` for `status`

That way we can obtain status results for reproduced stages outputs.
One fallacy for this logic I see, is

**Comment by Vonski** [comment]
Ok, but wouldn't status from these targets be empty after reproduction?

**Comment by pared** [comment]
@Vonski , sorry, I made a mistake here.

`Status` is meant to check the pipeline and pinpoint how changing our assets influences our pipeline. I presumed we will get some results for the uncommitted `dvc.yaml` file, which was not true, my bad. 
So please discredit my previous answer.

It seems to me that trying to touch this subject from `cmd` level will be problematic.
The problem is that `status` is unable to determine whether a change in particular dependency will result in a change of output.
The only way to do that is to verify the outputs before and after reproduce.
So what I am thinking now is that we can create a mapping of the stage, its outs, and their respective checksums before and after reproduction. That way we don't have to make any additional calls and return changed outs information from within `repro` method. 
Particular stage reproduction happens around [here](https://github.com/iterative/dvc/blob/77bc27799b683bb2d77254b0911b1449989ac211/dvc/repo/reproduce.py#L40).
I think it would be ok to refactor this method and `_reproduce_stages` in a way, that besides list of reproduced stages would return even particular outs reproduced by this method. 

For the sake of this issue we don't even have to return particular, reproduced outs. `outs_changed` = `True/False` would be enough to decide whether we should display suggestion to use `push`.

**Comment by pared** [comment]
Ok, after some discussions:

1.It seems that there is no easy way to extract information which particular outputs have changed during `reproduce`
2. Solution proposed by me breaks API and provides functionality that is not required that much (as of today)
3. Solution proposed by @Vonski might work, but would require extra `status` call before and after `reproduce` - which can take some time in case of bigger repos.

Also both our approaches do not address other situations: when we repro something and get an identical result as some previous work, which results are in our remote - in that case, message should also not show up. Fix? `dvc status -c` - but we can't do that for each and every `repro` as it's expensive and can take a lot of time. Solving this issue requires exchanging information between workspace, cache and remote, all of that to decide whether we should remind user to use `dvc push`.

I think we should close this issue for now as the solution seems to be much more expensive than the value it would bring.

@Vonski sorry you had to face it as your first issue. If you are still interested in contributing, I will gladly help you choose something less headachy.

**Comment by Vonski** [comment]
No problem at all. Although I would appreciate a recommendation for next issue to hit :)
