### ISSUE TITLE
"dvc status" checks for remote updates in git imports when checking for workspace changes

### ISSUE THREAD

**Issue by zhiltsov-max** [iterative/dvc#4983]
## Bug Report

Reproduce:

```
dvc init
dvc import <git repo>
dvc status
```

The `status` call will download the repository into a temporary folder and compare workspace against it, instead of comparing workspace against cache (like the documentation describes). This can be fixed by changing [this line](https://github.com/iterative/dvc/blob/master/dvc/repo/status.py#L23) with `check_updates=False`, but I'm not sure, if this is intended. Looking at documentation, I would expect the status command to download anything only when working in `cloud` or `remote` modes.

### Please provide information about your setup

**Output of `dvc version`:**

```console
DVC version: 1.10.2 (pip)
---------------------------------
Platform: Python 3.6.5 on Linux-4.15.0-99-generic-x86_64-with-debian-buster-sid
Supports: http, https, ssh
Cache types: hardlink, symlink
Caches: local
Remotes: local, local
Repo: dvc, git
```

**Comment by pmrowla** [comment]
If you are referring to how `status` will do a shallow clone of the source git repo, this is expected behavior for imports and external dependencies. `status` has to examine (clone) the source repo in order to determine whether or not the imported file has been updated in the source repo.

**Comment by efiop** [comment]
We do plan on adding caching for these git repos https://github.com/iterative/dvc/issues/3496 in the future.

**Comment by zhiltsov-max** [comment]
> `status` has to examine (clone) the source repo in order to determine whether or not the imported file has been updated in the source repo.

According to the documentation, `status` has to compare the workspace against the cache:

> Comparisons are made between data files in the workspace and corresponding files in the cache directory (e.g. .dvc/cache)

I would expect it to check file existence and hashes, and compare them to the saved ones in .dvc files.

**Comment by pmrowla** [comment]
> I would expect it to check file existence and hashes, and compare them to the saved ones in .dvc files, like git status does.

This is what `dvc status` does for regular tracked files, whether they are added via `dvc add` or `repro`/`run` pipeline outputs. But imported/external files are handled differently, since it makes sense for status to also check the status of the imported `.dvc` file itself.
