### ISSUE TITLE
import-url: can have unexpected behaviour when imported data includes `.dvc` files

### ISSUE THREAD

**Issue by zhiltsov-max** [iterative/dvc#4984]
## Bug Report

Reproduce:

```
test/remote/
test/remote/a.txt
test/remote/a.txt.dvc

$ git init
$ dvc init
$ mkdir -p extra/dir
$ dvc import-url --file extra/dir/a.dvc ../test/remote/ a
Importing '../test/remote' -> 'a'

To track the changes with git, run:

        git add .gitignore extra/dir/a.dvc

$ dvc import-url --file extra/dir/b.dvc ../test/remote/ b
ERROR: failed to import ../test/remote/. You could also try downloading it manually, and adding it with `dvc add`. - Paths for outs:
'a'('extra/dir/a.dvc')
'a/a.txt' ('a/a.txt.dvc')
overlap. To avoid unpredictable behaviour, rerun command with non overlapping outs paths.
```

Basically, when `dvc import-url` downloads some `.dvc` files, dvc can start to have unexpected behaviour in different places:
- different results of `import-url` with and w/o `--no-exec` option + `update` 
- random problems with overlapping paths

Looks like a support for recursive remotes, but can have some unpredictable problems.

### Please provide information about your setup

**Output of `dvc version`:**

```console
DVC version: 1.10.2 (pip)
---------------------------------
Platform: Python 3.6.5 on Linux-4.15.0-99-generic-x86_64-with-debian-buster-sid
Supports: http, https, ssh
Cache types: hardlink, symlink
Caches: local
Remotes: local, local
Repo: dvc, git
```

**Comment by pmrowla** [comment]
So in this example, is `test/remote` a DVC repo? Could you elaborate a bit here on why you are trying to use `dvc import-url` on a path containing `.dvc` files in the first place?

Normally in this scenario you would use `dvc import` (and not `dvc import-url`) to import from the source DVC repo.

**Comment by zhiltsov-max** [comment]
It happened occasionally. I was triyng to import a local directory and it happened to contain a .dvc file. Once I tried to import it for the second time, I've got the error, which was really hard to be understood. I has no intentions in importing a dvc repo.

**Comment by pmrowla** [comment]
I see, we could consider adding a warning if a user tries to use `import-url` with a directory containing `.dvc` files. But yes essentially it is expected that this will break things, since the repo will end up reading the imported `.dvc` file and treating it like any other `.dvc` file.

**Comment by pmrowla** [comment]
Hi @SangamSwadiK, I think this issue is actually no longer relevant in the latest version of DVC due to changes that have been introduced since 1.10 (chained imports are now supported). Sorry for any confusion

closing this issue as stale
