### ISSUE TITLE
version: separate DVC from project info & clarify field names

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4990]
> From https://github.com/iterative/dvc/pull/4848#issuecomment-735345668

- Separate the output of the `version` command into a **DVC** section and a **Project** section.
- Clarify field names for ambiguity and preciseness.

Example:

```console
$ dvc version
Platform: Python 3.8.6 on Linux-5.9.6-arch1-1-x86_64-with-glibc2.2.5

DVC Version: 1.10.1 (pip)
    Remotes supported: {Always list, even "All"}
    Link types supported: hardlink, symlink, copy

Project location: /home/user/mydvcproject/
    Repo: DVC, Git
    Workspace fs: ext4 on /dev/sda4
    Cache fs: ext4 on /dev/sda4
    Caches used: ssh, local
    Remotes used: ssh, azure
```

**Comment by skshetry** [comment]
@jorgeorpinel, your output looks good. I don't agree on listing all of the remotes, as there's too many of them (3 have open PRs) and too few people that use them.

I think we should just throw a JSON output (or, via `--json` flag), which would allow us to add more information without making the `dvc version` crowded. 
We can ask for `dvc version --json` or `dvc repo --json` for support, and keep small, less-informational on `dvc version`.

**Comment by jorgeorpinel** [comment]
Cool!

> I don't agree on listing all of the remotes, as there's too many of them

Not a very strong opinion, but most people won't know what "All" includes. I also don't see a problem in the list being long, so I would def. vote to list them all. Another option is to include a link to https://dvc.org/doc/command-reference/remote instead.

Also no preference on what info. you guys want to include in the output or if only a --json version will include all of it, but if the info mixes DVC and Project info, it's better to clearly separate them IMO.

And also importantly, to clarify the field names because currently there are confusions like `Cache types` (link types = supported values for `cache.type`) vs. `Caches` (external cache location types, closer to remote types).

**Comment by efiop** [comment]
Closing as stale
