### ISSUE TITLE
conda: docs for conda extras and "missing" help messages

### ISSUE THREAD

**Issue by jamesmyatt** [iterative/dvc#4997]
As far as I can tell, there's no documentation of the conda "power user" packages, as described in https://github.com/conda-forge/dvc-feedstock/blob/master/recipe/meta.yaml

Can this be added, please?

**Comment by pmrowla** [comment]
I think this is by design, the recommended way for installing via conda is to install the full `dvc` package which includes everything, like all of our other binary packages.

I'd consider "power user" in this case to be someone familiar enough with how conda/conda-forge works to investigate the extras sub-packages themselves.

**Comment by efiop** [comment]
@pmrowla We do document it for pip package, so it makes sense to do the same for conda.

**Comment by jamesmyatt** [comment]
@efiop , that's my thinking. I only discovered the sub-packages by installing everything and being shocked by the number of dependencies. I would have been much happier to see this mentioned in the docs.

In fact, it's a bit odd that on pip `dvc` is the minimum and `dvc[all]` is everything, while on conda `dvc` is everything and `dvc-base` is the minimum. I understand that was a choice and a consequence of the way conda and pip do extra dependencies, but when you're installing in a conda environment, you almost certainly only need one (at most) of the extra dependencies.

**Comment by efiop** [comment]
@jamesmyatt Extras for conda package were introduced very recently, so we kinda had to preserve `dvc` as `all-in-one` to not break it for existing users. We could consider switching in an upcoming 2.0 release though. We'll need to adjust the instructions https://github.com/iterative/dvc/blob/1e1a0999f6b3cde830d9b8810009d0451bcc953d/dvc/tree/base.py#L110 to have the same thing for conda as we do for pypi and that should be it. But we should definitely start with docs.

**Comment by efiop** [comment]
Created https://github.com/conda-forge/dvc-feedstock/issues/168 for conda to make a switch in 2.0. Added checkbox https://github.com/iterative/dvc/issues/4841

**Comment by jamesmyatt** [comment]
Making a change for version 2.0 sounds like a sensible idea. Thanks.

**Comment by jamesmyatt** [comment]
Looks like v2.0 has changed `dvc-base` to `dvc` :D https://github.com/conda-forge/dvc-feedstock/pull/185

**Comment by efiop** [comment]
@jamesmyatt Thanks for the heads up! Created https://github.com/iterative/dvc.org/pull/2273
