### ISSUE TITLE
dvc: parametrization upgrade path

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#5008]
We used to use `use` key and then switched to `vars`, which breaks older commits for whoever used it earlier. Is it possible to make both be readable? I.e. if that was simple rename then shouldn't take much code.

**Comment by efiop** [comment]
For the record: these keys were never officially released and anyone who used them took an explicit risk by enabling a special config option.

@skshetry WDYT?

**Comment by Suor** [comment]
If it takes significant effort to fix or support then we should drop it.

**Comment by skshetry** [comment]
@Suor, right now, it's only enabled via flag. I assume Viewer only collects through brancher, which means it has to either set the config before collecting all (which might slow down collection as it's not optimized) or set repo config on each iteration of the branches.

> If it takes significant effort to fix or support then we should drop it.

It might be easy to add the support back, but that means we have to support this syntax everywhere (not just on the Viewer side).

**Comment by skshetry** [comment]
@Suor, maybe adding support for skipping stage collection for that particular file would be a better option here, rather than having those syntax supported *forever*.

**Comment by skshetry** [comment]
@Suor, could you please respond? If there's nothing for me to do, please close the issue.

**Comment by Suor** [comment]
There is only one file - `dvc.yaml` if we ignore it we might simply ignore the whole commit as it's done now. If this is a nuisance to support it you can drop it.

**Comment by skshetry** [comment]
> There is only one file - dvc.yaml if we ignore it we might simply ignore the whole commit as it's done now.

What do you mean? There can be many `dvc.yaml` files in a repository.

**Comment by Suor** [comment]
It's common to have one.

**Comment by skshetry** [comment]
>  If this is a nuisance to support it you can drop it.

Closing then. There have been some discussions on how we could fix/avoid this, for example, by having a version identifier, explicitly ignoring some commits, and making DVC able to cope with syntax errors. But, there's nothing to add/do here in the short term.
