### ISSUE TITLE
dvc: metrics.show() and params.show() order

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#5009]
It looks like these go in somewhat random order. Is it possible to make them reflect the order in `dvc.yaml` file? Since Python 3.6 dicts preserve order so we can still use that as an output type.

**Comment by efiop** [comment]
@Suor Could you elaborate why that even matters?

**Comment by Suor** [comment]
As a default order of columns in the viewer. Sure we can simply sort alphabetically, but the order in a file is probably user defined already and then we should use it.

**Comment by efiop** [comment]
That seems really viewer-specific. Not sure if it is worth adopting as dvc core behavior. Have you implemented it in the viewer already?

**Comment by efiop** [comment]
Ok, had a private discussion about it. So this matters for dvc CLI as well, so it is our problem too, though not as urgent. We don't have capacity to deal with it right now ourselves, so if it can be implemented in viewer for now or you could contribute the change back (at least for API) - that would be great.

**Comment by Suor** [comment]
Can't be implemented in the viewer (without monkey patching). So no not implemented yet in any way.

**Comment by dmpetrov** [comment]
It is important in CLI as well. It is hard to use with real-life files with dozens of metrics or params.

We should assume that users pay a lot of attention to order items inside the files and reuse this user' afford.

ToDo:
- [ ] preserve order in metrics: dvc metrics diff/show
- [ ] preserve order in params: dvc params diff/show

**Comment by Suor** [comment]
Implementation note: don't need to use `OrderedDict` in Python 3.6+, order is stable for `dict` too.

**Comment by auvipy** [comment]
> Implementation/API note: don't need to use `OrderedDict` in Python 3.6+, order is stable for `dict` too.

Changed in version 3.7: Dictionary order is guaranteed to be insertion order. This behavior was an implementation detail of CPython from 3.6.

**Comment by skshetry** [comment]
> This behavior was an implementation detail of CPython from 3.6.

@auvipy, the behaviour is very much unlikely to change. So, we can depend on it (we already do on a lot of places).

**Comment by dmpetrov** [comment]
One more important item:
- [ ] preserve the order in `dvc exp show` for metrics as well as params
@pmrowla I'd appreciate it if you can take a look at it.

Also, I had a discussion with @pared re summary files in dvclive - we should store `step` as the 1st metrics (if presented) and the rest should be stored in the order that the user's code reported. Do we need a separate issue in dvclive?

**Comment by pared** [comment]
@dmpetrov no need, it should already be at master, I'll create issue to research keras callback - the order there is obtained from args provided by keras, so I need to see if its possible at all in this case. `step` will be first for sure.
