### ISSUE TITLE
Method to add all changed files

### ISSUE THREAD

**Issue by theelderbeever** [iterative/dvc#5024]
Add a method that adds all of the changed files that are tracked by `dvc`.  Occasionally, when a lot of files have been changed in a project using dvc it can be a pain to try and add all of the changed files. `dvc add --glob **/*.extension` works in some regards but it can be difficult to come up with a "non" greedy wildcard expression. 

Consider adding something like...
```
dvc add -c, --changed
dvc add -a, --all # this would be kind of like git
dvc add $(dvc status --quiet) # in this scenario quiet would only return paths to files instead of nothing the extra boilerplate that is returned now. This would be similar to how the docker cli behaves.
```

**Comment by shcheklein** [comment]
@theelderbeever may be `dvc commit` works in this case?

**Comment by efiop** [comment]
Closing as stale

**Comment by mazzma12** [comment]
Hi, why not using 
```
dvc add -u
```
?

As in git, it will only stage modified tracked files

**Comment by shalphi** [comment]
dvc add $(ls)
or another way to get tree of files
