### ISSUE TITLE
ValueError while reading dvc repo

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#5027]
Getting
```
ValueError: too many values to unpack (expected 1)
  File "repos/parsing/dvcmeat.py", line 37, in parse_dvc
    _parse_metrics(repo, commit)
  File "repos/parsing/dvcmeat.py", line 64, in _parse_metrics
    metrics = repo.metrics.show()[""]
  File "dvc/repo/metrics/__init__.py", line 8, in show
    return show(self.repo, *args, **kwargs)
  File "dvc/repo/__init__.py", line 60, in wrapper
    return f(repo, *args, **kwargs)
  File "dvc/repo/metrics/show.py", line 100, in show
    vals = _read_metrics(repo, metrics, rev)
  File "dvc/repo/metrics/show.py", line 58, in _read_metrics
    if not tree.exists(metric):
  File "dvc/tree/repo.py", line 170, in exists
    (out,) = meta.outs
```

while reading dvc repo history, https://sentry.io/organizations/iterative/issues/2068029832/?project=5220519&query=is%3Aunresolved&statsPeriod=14d

```
DVC version: 1.10.2 (pip)
---------------------------------
Platform: Python 3.8.6 on Linux-4.14.198-152.320.amzn2.x86_64-x86_64-with
Supports: azure, gdrive, gs, http, https, s3, ssh
```

**Comment by skshetry** [comment]
@Suor, is there more information regarding the repo? It seems that the path is overlapped in the `outs`/`metrics` section. See https://github.com/iterative/dvc/issues/4010, there are assumptions in `tree`s that outputs are always unique, which is wrong.

**Comment by Suor** [comment]
All the additional info is in Sentry.

**Comment by skshetry** [comment]
Discussed this with @efiop to fix this on `find_outs_by_path` to use `list(self.graph)` instead of `self.stages`.
https://github.com/iterative/dvc/blob/69eb86a06f1a6d2ae501a3f0b380ad2939e0e09c/dvc/repo/__init__.py#L377-L379

**Comment by Suor** [comment]
> Discussed this with @efiop to fix this on find_outs_by_path to use list(self.graph) instead of self.stages.

Will it make it slower?
