### ISSUE TITLE
LockfileCorruptedError while reading dvc repo

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#5028]
```
MultipleInvalid: required key not provided @ data['dupe_key']['cmd']
  File "dvc/dvcfile.py", line 122, in validate
    cls.SCHEMA(d)  # pylint: disable=not-callable
  File "voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)

StageFileFormatError: '../tmp/vrepo-7t6ui6xo/dvc.lock' format error: required key not provided @ data['dupe_key']['cmd']
  File "dvc/dvcfile.py", line 288, in load
    self.validate(data, fname=self.relpath)
  File "dvc/dvcfile.py", line 124, in validate
    raise StageFileFormatError(f"'{fname}' format error: {exc}")

LockfileCorruptedError: Lockfile '../tmp/vrepo-7t6ui6xo/dvc.lock' is corrupted.
  File "repos/parsing/dvcmeat.py", line 36, in parse_dvc
    _parse_stages(repo, commit)
  File "repos/parsing/dvcmeat.py", line 53, in _parse_stages
    for stage in repo.stages:
  File "funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "dvc/repo/__init__.py", line 575, in stages
    return self._collect_stages()
  File "dvc/repo/__init__.py", line 583, in _collect_stages
    new_stages = self.get_stages(os.path.join(root, file_name))
  File "dvc/repo/__init__.py", line 275, in get_stages
    return list(dvcfile.stages.values())
  File "dvc/dvcfile.py", line 244, in stages
    lockfile_data = self._lockfile.load()
  File "dvc/dvcfile.py", line 290, in load
    raise LockfileCorruptedError(
```
https://sentry.io/organizations/iterative/issues/2070050025/?project=5220519&query=is%3Aunresolved&statsPeriod=14d

### Please provide information about your setup

dvc version 1.9.1+96ead9

**Comment by skshetry** [comment]
@Suor this does not look like a bug to me. `cmd` is clearly missing from `dvc.lock`, and it's mandatory.

**Comment by Suor** [comment]
So bug is somewhere in creation of `dvc.lock`.

**Comment by skshetry** [comment]
> So bug is somewhere in creation of `dvc.lock`.

It's unlikely a bug. Most likely, the user remove the `cmd` from the lockfile.

**Comment by skshetry** [comment]
Looking at the repo, it seems it was intended to make it crash by @fabiosantoscode:

https://github.com/fabiosantoscode/example-get-started/commit/c7148b094c2af3f0770ca60734e3cf6ea9f12c20

We can fix this specific issue by loosening the validation and ignoring the unknown stages (i.e. using single source of truth from dvc.yaml), but since the same format is used for the run-cache, I don't think it's a good idea to do it yet just to catch this specific case.

**Comment by fabiosantoscode** [comment]
Hey there! Yes, I was trying to reproduce a production issue. This wasn't it. Eventually 600k metrics broke things to my satisfaction :)
