### ISSUE TITLE
Add ability to skip "dirty" commits during `dvc gc`

### ISSUE THREAD

**Issue by courentin** [iterative/dvc#5037]
Following https://github.com/iterative/dvc/issues/3885, I'd like to add the ability to skip commits that generate errors during `dvc gc`.

To sum-up, running `dvc gc` in a codebase that contains a commit where dvc is in a dirty state (eg. the `dvc.yaml` is badly formatted, one of the output is dvcignored, etc.) make it failing.

Thus, if feel assuming that **every** commits are clean and let dvc in a usable state is a bit too optimistic. Except if you have a very rigorous process with dvc, it is almost impossible.

Thus, I'd suggest 2 things.
First adding a log to explain where (which branch/commit) the error has been raised.
Second, adding an option to gc: `dvc gc --skip-failing-collect`. Not sure of the naming but the behaviour would be to skip the collection of branches/commits that produce `DvcException`.

What do think?
I've started an implementation that I'll link to this issue.

**Comment by skshetry** [comment]
@courentin, I think `--ignore-revs`/`--ignore-commits` are more reliable than `--skip-failing-collect` as it is clear on what your intentions are, considering `gc` is a dangerous command.

**Comment by courentin** [comment]
Yes, explicit is better than implicit indeed!

**Comment by amka66** [comment]
I think this is not a feature request but rather a bug.

I would like to reduce the cache as it is eating up my hard drive, but i cannot do it due to one or two broken .yaml files in my git commit history.
@efiop or anyone, please help, what can i do?

Unless there is a reasonable solution, I am stuck we a full hard drive. This requires a quick resolutions. Thanks!

**Comment by WilliamHarvey97** [comment]
I had this issue. Nothing to add here, but this looks quiet serious to me because it makes `dvc gc -A` such a dangerous command.

**Comment by dberenbaum** [comment]
> @courentin, I think `--ignore-revs`/`--ignore-commits` are more reliable than `--skip-failing-collect` (being a conditional flag) as it is clear on what your intentions are, considering `gc` is a dangerous command. What do you think?

In addition, we recently introduced `-n` to various `dvc exp` commands to specify the last n commits. The same option might be useful for `gc` to keep some limited history.

**Comment by daavoo** [comment]
> In addition, we recently introduced -n to various dvc exp commands to specify the last n commits. The same option might be useful for gc to keep some limited history.

https://github.com/iterative/dvc/issues/7695
