### ISSUE TITLE
metrics/plots: detect missing cached files and suggest fetch

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5039]
This is specifically for `metrics/plots --all-{label}` as well as `metrics/plots diff`.

Based on the dvc.lock files in the Git history, these commands could detect that cached metrics or plots files are missing in the cache (probably they already do that internally but don't handle that state specially.)

Currently they just get skipped as if no metrics/plots even existed in the lock file. My proposal is that they can print warnings so the user is aware of what commits reference cached metrics/plots files that are not in the cache, and that it suggests to use `fetch` to download them before trying again.

**Comment by efiop** [comment]
Another alternative is to auto-fetch or even stream the values. The support for that is built into RepoTree/DvcTree already.

**Comment by jorgeorpinel** [comment]
The streaming idea is great. Not sure about auto-fetch as the user may have a reason to not have them in cache... Though then again they're probably tiny files so yeah, it should be fine. But only fetch/stream metrics and plots (not other outputs).

In any case probably a warning or info message would be needed so the user is aware of what's happening.
