### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by hyperparameters** [iterative/dvc#5050]
Hello, developers,
kudos to you for awesome work :champagne: 
But was hoping if we can have all the cli command in python API too. 
I like to experiment in jupyter notebooks and that python API will be more flexible to use in such cases. 
Is there any roadmap for this, I would like to contribute if any need :smile:

**Comment by efiop** [comment]
Hi @hyperparameters !

See `Repo` class from `dvc.repo`. E.g.
```
from dvc.repo import Repo

repo = Repo(".")
repo.add("foo")
```

it is not officially released yet in the sense that there are no official docs for it, but our CLI has been using the same thing for years now, so it is more or less stable. Still, I have to stress that as it is not officially released yet, we don't give a 100% guarantee about it's stability and your mileage may vary.

We will definitely document this part of API in the future, but there is no particular timeframe for now :slightly_frowning_face:

**Comment by hyperparameters** [comment]
@efiop thanx for pointing me to class, will explore this part and share my feedback.

**Comment by efiop** [comment]
Closing for now.
