### ISSUE TITLE
pull: failed to pull large file with reporting 'InconsistentError: IncompleteRead from source' with aliyun-oss

### ISSUE THREAD

**Issue by 9173860** [iterative/dvc#5051]
# Bug Report
pull: failed to download with reporting 'InconsistentError: IncompleteRead from source' with aliyun-oss

## Description
If any file pushed onto aliyun-oss needs more than 60s to download in dvc pull, it will throw error with:
```
ERROR: failed to download 'oss://<bucket>/<path>/<cache_dir>' to '.dvc/cache/<cache_dir>' - {'status': -3, 'x-oss-request-id': '<RANDOM-REQUEST-ID>', 'details': 'InconsistentError: IncompleteRead from source'}
```

### Reproduce
1. dvc init
2. configure an aliyun oss remote as `remote add` document
3. dvc add <any single large file that needs more than 60s to download in dvc pull>
4. dvc push
5. commit git repo

6. clone git repo
7. git pull
8. dvc pull

### Expected
It should pull success with files fetched return.

```console
$ dvc version
DVC version: 1.10.2 (brew)
---------------------------------
Platform: Python 3.9.0 on macOS-11.0.1-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Caches: local
Remotes: oss
Repo: dvc, git
```

**Additional Information (if any):**
https://github.com/iterative/dvc/blob/c4f92314dbb0dd0f0686b6117942154c58a7e41f/dvc/tree/oss.py#L131

The download function here should be `oss2.resumable_download` instead of `get_object_to_file`, otherwise the download timeout will exceed connection_timeout and the connection will be force closed.

**Comment by skshetry** [comment]
> The download function here should be oss2.resumable_download instead of get_object_to_file, otherwise the download timeout will exceed connection_timeout and the connection will be force closed.

@9173860, is there any way to increase that session timeout? And, does this also affect the `push`/`upload`?

I could not find a way to increase it, but the documentation for `resumable_download` is [here](https://translate.google.com/translate?hl=&sl=zh-CN&tl=en&u=https%3A%2F%2Faliyun-oss-python-sdk.readthedocs.io%2Fen%2Flatest%2Feasy.html%23id3).

**Comment by 9173860** [comment]
> > The download function here should be oss2.resumable_download instead of get_object_to_file, otherwise the download timeout will exceed connection_timeout and the connection will be force closed.
> 
> @9173860, is there any way to increase that session timeout? And, does this also affect the `push`/`upload`?
> 
> I could not find a way to increase it, but the documentation for `resumable_download` is [here](https://translate.google.com/translate?hl=&sl=zh-CN&tl=en&u=https%3A%2F%2Faliyun-oss-python-sdk.readthedocs.io%2Fen%2Flatest%2Feasy.html%23id3).

It only has effects when pull, and not affect push or upload.  We can initial oss Bucket with a connect_timeout param to increase session timeout. But using resumable download is still a better way to do it.

The implement of `oss2.resumable_download` will download file piece by piece if the downloading file is larger than 10M. So if the client could finish download 10M of pieces in 60s, it will not be enduring session timeout, hence we can avoid just increasing session timeout to an arbitrary number for any filesize and make it more robust.

**Comment by skshetry** [comment]
@9173860, is this timeout of being 60s documented anywhere? 

> It only has effects when pull, and not affect push or upload

Again, can you please point me to the documentation? 

Please consider creating a pull request with your above change. If you want to run test locally, just run with `pytest --enable-oss`, otherwise just create a pull request. Thanks.

**Comment by 9173860** [comment]
The document for setting timeout [here](https://aliyun-oss-python-sdk.readthedocs.io/en/stable/oss2.html#oss2.api.Bucket) and default value for connect_timeout lays [here](https://github.com/aliyun/aliyun-oss-python-sdk/blob/master/oss2/defaults.py) without any documentation.

And PR opened #5053
