### ISSUE TITLE
plots/metrics/params: allow comparing between different paths

### ISSUE THREAD

**Issue by pared** [iterative/dvc#5074]
[In some use cases](https://discuss.dvc.org/t/comparing-different-metric-param-plot-files/582)
user might want to compare different metrics in different paths.

We need to discuss if and how we are going to support it.
My initial idea is to expand how we provide `rev` :
instead of `dvc plots diff tag1` we could go with `dvc plots diff tag1:{path}`

**Comment by qthurier** [comment]
This would be very helpful for example when experiments are isolated in different folders on the same branch (as opposed to each experiment being on a dedicated branch).

The scenario comparing metric1.json from branch1 with metric2.json from branch2 can be helpful too but it is not my primary use case. I think ideally we should be able to perform diff on 2 combination of (path, revision).

**Comment by pared** [comment]
Closing in favour of #5693
