### ISSUE TITLE
Preserve user-order in metrics and params diff outputs

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#5099]
Today `metrics show/diff` & `params show/diff` commands have a random order in outputs. It makes it really hard to use with real-life files with dozens of metrics or params. We should assume that users pay a lot of attention to order the items inside the files and preserve the order in the command outputs.

ToDo:
- [ ] preserve order in metrics: `dvc metrics diff/show`
- [ ] preserve order in params: `dvc params diff/show`

**Comment by skshetry** [comment]
Related to https://github.com/iterative/dvc/issues/5009

**Comment by dmpetrov** [comment]
thank you @skshetry. It is duplication. closing.
