### ISSUE TITLE
experiments: ambiguous error on no `dvc.lock` in repo

### ISSUE THREAD

**Issue by pared** [iterative/dvc#5109]
`1.11.0`
Related: https://github.com/iterative/vscode-dvc/issues/16

When running experiment, if `dvc.lock` is ignored, we will get very ambiguous error on `dvc exp run`.

Reproduction script:
```
#!/bin/bash

rm -rf repo
mkdir repo

pushd repo
set -ex

git init --quiet
dvc init --quiet

echo 'dvc.lock' >> .gitignore
git add -A
git commit -am "init"

echo "data" >> data
echo "y: 1" >> params.yaml
dvc add data
git add params.yaml

dvc add data
git add -A
dvc run -n cp -d data -o out --params y "cp data out" 
git add -A
git commit -am "second"

git status

dvc exp run cp --params y=2
```

Error:
```
ERROR: Failed to reproduce experiment '68afe3a' - Checkout failed for following targets:                                                          
C
h
e
c
k
o
u
t
 
f
a
i
l
e
d
 
f
o
r
 
f
o
l
l
o
w
i
n
g
 
t
a
r
g
e
t
s
:


o
u
t


I
s
 
y
o
u
r
 
c
a
c
h
e
 
u
p
 
t
o
 
d
a
t
e
?


<

[
3
6
m
h
t
t
p
s
:
/
/
e
r
r
o
r
.
d
v
c
.
o
r
g
/
m
i
s
s
i
n
g
-
f
i
l
e
s

[
3
9
m
>
Is your cache up to date?
<https://error.dvc.org/missing-files>: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/prd/development/projects/dvc/dvc/repo/experiments/executor.py", line 253, in reproduce
    dvc_checkout(dvc, force=True, quiet=True)
  File "/home/prd/development/projects/dvc/dvc/repo/__init__.py", line 53, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/prd/development/projects/dvc/dvc/repo/checkout.py", line 121, in checkout
    raise CheckoutError(stats["failed"], stats)
dvc.exceptions.CheckoutError: Checkout failed for following targets:
out
Is your cache up to date?
<https://error.dvc.org/missing-files>
```

I don't think that running `exeriments` without `dvc.lock` in repo makes any sense, but we could use some error message pointing us to what the problem might be.

So:

1. Should experiments work if `dvc.lock` is ignored?
2. No matter what answer for 1 might be, we should probably check if we have `dvc.lock` in experiment dir, as its necessary to checkout, at least in `checkpoint` use case.

**Comment by pmrowla** [comment]
The issue with `dvc.lock` (or uncached outputs/metrics) not being included in the output experiment if it is initially untracked by git (or non-existent) in the user's workspace is fixed by #5093.

If `dvc.lock` is gitignored, user's will have other issues with DVC, as you would never be able to run `dvc checkout` without doing `dvc repro` first to generate the lock file.
