### ISSUE TITLE
config: add support for --show-origin

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#5119]
Same as `git config`:
```
$ git config --list --show-origin
file:/home/efiop/.gitconfig     user.email=ruslan@iterative.ai
file:/home/efiop/.gitconfig     user.name=Ruslan Kuprieiev
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=true
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        remote.origin.url=git@github.com:efiop/dvc
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
file:.git/config        remote.upstream.url=git@github.com:iterative/dvc
file:.git/config        remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
file:.git/config        branch.fix-4050.remote=origin
file:.git/config        branch.fix-4050.merge=refs/heads/fix-4050
file:.git/config        branch.fix-4162.remote=origin
file:.git/config        branch.fix-4162.merge=refs/heads/fix-4162
```

i'm not personally sold on `file:` prefix in path (just because I don't really know why git does that, maybe there is a good reason), but the rest looks pretty good. We now have `dvc config --list`, so now we need `dvc config --list --show-origin` as the next step.

This will be realy handy to have for users to figure out where the configs are and also handy for us, developers, when debugging particular issues.

**Comment by mrstegeman** [comment]
I'll pick this up and submit a PR soon.

**Comment by pmrowla** [comment]
> i'm not personally sold on `file:` prefix in path (just because I don't really know why git does that, maybe there is a good reason), but the rest looks pretty good. We now have `dvc config --list`, so now we need `dvc config --list --show-origin` as the next step.

For reference, it's because git config options can come from other sources - stdin, command line, or git blobs. I don't think we would ever have anything besides `file` in DVC though

**Comment by efiop** [comment]
@pmrowla Oh, didn't know that! Makes sense now. Thank you for clarifying! :pray:

**Comment by efiop** [comment]
Reopening to support it for a new correct `dvc config` behavior. https://github.com/iterative/dvc/pull/5184
