### ISSUE TITLE
api: get_url: support recursive

### ISSUE THREAD

**Issue by copaah** [iterative/dvc#5133]
Moving discussion from Discord with @efiop  to here. Basically I have a use case where I do around 13,000 calls to `get_url` from the DVC python API. This is slow and @efiop suggested to add `recursive` argument to `get_url` to speed things up since all my tracked DVC files live in the same directory either way.

I will let @efiop add his thoughts on this.

**Comment by efiop** [comment]
Discord context https://discord.com/channels/485586884165107732/563406153334128681/789562453671411712

**Comment by skshetry** [comment]
Related to #3182

**Comment by copaah** [comment]
@efiop Are you sure that supporting recursive will improve the speed of this call? My main request is not supporting recursive - I am interested in speeding up this call. If that is by supporting recursive that is fine, but I want to make sure that the main request is not forgotten.

**Comment by efiop** [comment]
@copaah Your main request is speeding up `get_url` for a list of values, right? I thought we've established that the list you provide is just files in directory, so it should be more natural to support recursive instead of supporting a list of arbitrary files in `get_url`.

In both cases we are saving up on some init overhead and connection overhead for cached dirs, as we need to retrieve `.dir` cache file in order to serve hashes from it.

**Comment by copaah** [comment]
@efiop  Yes, my main request is speeding up `get_url` for a list of values. And yes, the files are usually in the same directory.

Sounds good though - just wanted to clarify!

**Comment by copaah** [comment]
@efiop

I was wondering if I could hack this myself. As far as I understand I can just parse the link to the cache, e.g. the following link:

```
../.dvc/cache/38/af44a886b0dc3204db3195d820b0f3
```

Will become

```
https://storage-name.blob.core.windows.net/container-name/38/af44a886b0dc3204db3195d820b0f3
```

And it seems like this is the correct path to the Blob URL.

Am I missing something here? It seems straightforward.

**Comment by efiop** [comment]
@copaah Sorry for the delay, we've been pushing some pre-requisites for related functionality.

Correct, that's all it does. It also tries to generate pre-signed urls for some clouds, but if that kind of url suits you - you can do that manually just like that. For files inside of cached dirs, it needs to open corresponding .dir cache file to parse file hashes.

**Comment by efiop** [comment]
Hi @copaah !

We've pushed some changes to the upstream that fixed bugs that were slowing down get_url significantly. There are still more things to optimize there, but maybe you would be keen on trying it right now, just to see if that makes any difference in your case.

**Comment by efiop** [comment]
Closing as stale.
