### ISSUE TITLE
Dependency between `dvc.yaml` files.

### ISSUE THREAD

**Issue by copaah** [iterative/dvc#5134]
I have a `dvc`  setup that looks something like this:

```
dvc/
    main_data_pipeline/dvc.yaml
    second_data_pipeline/dvc.yaml
```
My `second_data_pipeline/dvc.yaml` has an implicit dependency on one of the outputs from the `main_data_pipeline/dvc.yaml`.

An idea to resolve this could be to add an `include` directive so you can include other `dvc.yaml` files.

**Comment by efiop** [comment]
@copaah Is that dependency declared in `second_data_pipeline/dvc.yaml` or is it really absolutely implicit?

Also, could you elaborate on `include`?

**Comment by skshetry** [comment]
Closing as the issue not clear and the OP has not responded.
