### ISSUE TITLE
completion: not working well in Oh My Zsh

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5146]
# Bug? Report

## Description

No commands are found when I hit tab.

### Reproduce

Follow https://dvc.org/doc/install/completion#zsh-completion, result:

```console
$  dvc r # Press [tab] key
 -- no matches found --
```

### Expected

```console
$ dvc r # Press [tab] key
Completing dvc commands
remote  -- Set up and manage data remotes.
remove  -- Remove stage entry and unprotect outputs
repro   -- Reproduce complete or partial pipelines by executing their stages
root    -- Return the relative path to the root of the DVC project.
run     -- Generate a stage file from a command and execute the command.
```

### Environment information

**Output of `dvc version`:**

```console
$  dvc version
DVC version: 1.11.8 (pip)
---------------------------------
Platform: Python 3.6.9 on Linux-4.19.128-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic
Supports: gdrive, gs, hdfs, http, https, s3, ssh, oss
```

(WSL 2)

**Comment by jorgeorpinel** [comment]
Also if I [tab] after a full command name, the shell autocompletes a file or directory name instantly, and then if I [tab] again it shows the DVC auto-complete options, which is weird (and wrong):

```console
$  dvc run # *Hits Tab*
$  dvc run test/# *Hits Tab*
 -- file --
dvc.lock       dvc.yaml       model-us.hdf5  params.yaml
```

**Comment by pmrowla** [comment]
@jorgeorpinel can you run
```
$ echo $fpath
```
(from a zsh shell)
Maybe zsh on WSL has some other default search location than `/usr/local/share/zsh/site-functions/`

**Comment by jorgeorpinel** [comment]
It's somewhere in there:

`/home/jop/.oh-my-zsh/plugins/zsh_reload /home/jop/.oh-my-zsh/plugins/yarn /home/jop/.oh-my-zsh/plugins/ubuntu /home/jop/.oh-my-zsh/plugins/sudo /home/jop/.oh-my-zsh/plugins/ssh-agent /home/jop/.oh-my-zsh/plugins/pip /home/jop/.oh-my-zsh/plugins/git /home/jop/.oh-my-zsh/plugins/colored-man-pages /home/jop/.oh-my-zsh/functions /home/jop/.oh-my-zsh/completions /usr/local/share/zsh/site-functions /usr/share/zsh/vendor-functions /usr/share/zsh/vendor-completions /usr/share/zsh/functions/Calendar /usr/share/zsh/functions/Chpwd /usr/share/zsh/functions/Completion /usr/share/zsh/functions/Completion/AIX /usr/share/zsh/functions/Completion/BSD /usr/share/zsh/functions/Completion/Base /usr/share/zsh/functions/Completion/Cygwin /usr/share/zsh/functions/Completion/Darwin /usr/share/zsh/functions/Completion/Debian /usr/share/zsh/functions/Completion/Linux /usr/share/zsh/functions/Completion/Mandriva /usr/share/zsh/functions/Completion/Redhat /usr/share/zsh/functions/Completion/Solaris /usr/share/zsh/functions/Completion/Unix /usr/share/zsh/functions/Completion/X /usr/share/zsh/functions/Completion/Zsh /usr/share/zsh/functions/Completion/openSUSE /usr/share/zsh/functions/Exceptions /usr/share/zsh/functions/MIME /usr/share/zsh/functions/Math /usr/share/zsh/functions/Misc /usr/share/zsh/functions/Newuser /usr/share/zsh/functions/Prompts /usr/share/zsh/functions/TCP /usr/share/zsh/functions/VCS_Info /usr/share/zsh/functions/VCS_Info/Backends /usr/share/zsh/functions/Zftp /usr/share/zsh/functions/Zle`

Maybe it's more of a compatibility issue with Oh-My-Zsh than with WSL.

**Comment by jorgeorpinel** [comment]
This was answered in https://github.com/iterative/dvc/issues/5149#issuecomment-753748010 (thanks @skshetry).

By bad. I deleted by `_dvc` and followed the instructions again and it works normally now. Closing!
