### ISSUE TITLE
completion: needs an update once more

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5149]
in terms of the command descriptions, options, etc.

And probably will need even more along with 2.0 updates

**Comment by efiop** [comment]
@jorgeorpinel Could you be more specific, please? So far looks too generic, without action points :slightly_frowning_face:

**Comment by jorgeorpinel** [comment]
Sure! Sorry. Since this is done periodically I thought it would be clear what I meant.

So, for example the top code block in https://dvc.org/doc/install/completion has 

`remove  -- Remove stage entry and unprotect outputs`

which is no longer the help output of that command, but that's what gets installed by the script I think. I'm not sure because it's not working on my Zsh (See #5146).

And writing this I just realized that there's a `dvc completion` command! Does it just copy some file or does it generate it now? I see the old script/completion/ files are gone.

At least we may want to update that block in the install/completion doc and document `dvc completion`.

**Comment by jorgeorpinel** [comment]
> At least we may want to update that block in the install/completion doc and document dvc completion.

If that's the case please transfer this to dvc.org @efiop

**Comment by skshetry** [comment]
@jorgeorpinel, we automatically generate the completion scripts nowadays. So, the `remove` entry might be coming from old completion scripts that you have. You have to update it from time to time yourself. 

You can try refreshing the completion each time you open a terminal, but it'll be slower.

> At least we may want to update that block in the install/completion doc and document dvc completion

I think this is enough: https://dvc.org/doc/install/completion#shell-tab-completion

**Comment by jorgeorpinel** [comment]
OK I will update the docs (in iterative/dvc.org/pull/2086). Closing!
