### ISSUE TITLE
merge-driver: add allow deleted files

### ISSUE THREAD

**Issue by cgebbe** [iterative/dvc#5151]
(Based on this discussion https://discuss.dvc.org/t/merging-of-files-in-dvc-tracked-directories/599)

Would it be possible to create a DVC merging strategy for the following scenarios? 

Situation 1
common_branch: A-AB
branch1: ABC (add file C)
branch2: A (delete file B)
expected merge: AC

Situation 2
common_branch: A
branch1: AB-ABC (add files B,C)
branch2: AD-A (add file D, then delete file D)
expected merge: ABC

In my understanding, one would have to compute the difference of each branch with respect to the common ancestor node. Then, the union of those two differences is the expected merge outcome.

P.s.: I am pretty sure that this is too difficult for me to implement as a first pull request to DVC, but if there is some assistance task I'll gladly support.

**Comment by efiop** [comment]
@cgebbe Thanks for the request! :pray: 

The whole merge logic is in https://github.com/iterative/dvc/blob/a6151eaf9e25692fc86af26167c4c84c2d6ce7ab/dvc/dir_info.py#L21 , where we forbid deleted files.
