### ISSUE TITLE
repro/run: remove .gitignore entries when no longer needed

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5156]
> Similar to #4962

If I change the name of an output in my code and dvc.yaml and re-run repro, the new name gets added to .gitignore, but the old one is not removed.

One reason I may be changing the name is to liberate the previous one and perhaps add it to Git. So I think this would be an intuitive/expected behavior.

**Comment by efiop** [comment]
@jorgeorpinel Changing by hand in `dvc.yaml`?

**Comment by jorgeorpinel** [comment]
In any way.

```diff
      outs:
-       file.txt
+       file.dat
```

After repro .gitignore will have:

```
/file.txt # This one is no longer in use by DVC.
/file.dat
```

**Comment by skshetry** [comment]
I am not sure how DVC could determine this.
Anyway, we should not change user's workspace needlessly - you change things, you fix them. If DVC changed those, then that's a different discussion.

**Comment by jorgeorpinel** [comment]
But the entries were created by DVC so isn't it expected that DVC will manage them going forward? Imagine you make such a name change several times and end up with a .gitignore file full of clutter (names that are not being tracked by DVC) — it would be a strange setup I think so users would have to manually clean up after DVC.

Then again if no one has complained about this, I suppose there's no priority here, maybe just a "nice-to-have" until/if actual users have this problem.

**Comment by sanpreet** [comment]
I am comparing the question ' **remove .gitignore entries when no longer needed**' with the below analogy.
`
git rm --cached <file>
`
Can something like this be used because it can remove the entry which is no longer needed. I hope there can be some way like this.

**Comment by jorgeorpinel** [comment]
@sanpreet in your case `dvc remove` should do it. Please see https://dvc.org/doc/command-reference/remove.
