### ISSUE TITLE
pull/checkout: pulling multiple files consecutively from a folder checks out only first

### ISSUE THREAD

**Issue by Xyand** [iterative/dvc#5158]
# Bug Report

## Description

When attempting to pull individual files from dvc tracked folder, only the first pull creates file links. Similar behavior with `checkout` unless `--relink` is used.

### Reproduce
0. (git + dvc init)

1. mkdir db
2. touch db/a.txt && touch db/b.txt
3. dvc add db
4. git add db.dvc && git commit -m "dvc"
5. dvc remote add -d tmp /tmp/remote
6. dvc push
7. rm db/*
8. dvc pull db/a.txt
9. dvc pull db/b.txt

### Expected

db/a.txt & db/b.txt exist (When in fact b.txt doesn't). 

Getting messages:
dvc pull db/a.txt --> 1 file modified
dvc pull db/b.txt --> Everything is up to date. 

### Environment information

DVC version: 1.11.9 (pip)
---------------------------------
Platform: Python 3.6.10 on Linux-4.18.0-1024-azure-x86_64-with-debian-buster-sid
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda1
Caches: local
Remotes: local
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git

**Comment by isidentical** [comment]
I'd like to propose a patch for this if no one else already prepared something (cc: @efiop)
