### ISSUE TITLE
repro --pull to retrieve tracked files/folders added using `add`

### ISSUE THREAD

**Issue by Xyand** [iterative/dvc#5159]
Currently files tracked using `add` need to be manually pulled/checked-out although the dependency is specified in a pipeline.

**Comment by pmrowla** [comment]
This is a known limitation, `repro --pull` currently only pulls run cache and not data. Closing as a duplicate of https://github.com/iterative/dvc/issues/4742

**Comment by Xyand** [comment]
I suggest to explain it in the docs until implemented. Current
documentation  is misleading.

**Comment by efiop** [comment]
@Xyand Thanks for the suggestion! That feature is on our short todo list, stay tuned!
