### ISSUE TITLE
checkout: ugly error when providing wrong target

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5169]
```console
$ dvc checkout 123
ERROR: Did you mean `git checkout 123`?: '123' does not exist as an output or a stage name in 'dvc.yaml': "Stage '123' not found inside 'dvc.yaml' file": Could not find '123'
```

Better to just remove this hint. I don't find it helpful, as the `git`/`dvc` commands being similar is intended and per design.

**Comment by efiop** [comment]
Discussed during the meeting that alternatively, we could separate the hint somehow to make it nicer.

**Comment by skshetry** [comment]
Closing as not planned.
