### ISSUE TITLE
params diff: problems with file types

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5186]
# ~~Bug~~ Report

> Found during https://github.com/iterative/dvc.org/pull/2062#pullrequestreview-560258772

## Description

`params diff` assumes file content types.

### Reproduce

In a fresh DVC repo:

```console
$ echo "foo: 1" > params.yaml
$ echo "bar: 2" > params.json  # YAML file with json extension

$  dvc params diff
Path         Param    Old    New
params.yaml  foo      —      1
$ dvc params diff --targets params.json  # (1) First inconsistency
WARNING: 'params.json' was not found at: 'HEAD'.

$ git add --all
$ git commit -m "add 2 params files"

$ echo "foo: 2" > params.yaml
$ echo "bar: 4" > params.json

$ dvc params diff
Path         Param    Old    New
params.yaml  foo      1      2
$ dvc params diff --targets params.json  # (2) 2nd (main) problem
# No output
```

### Expected

`dvc params diff` to tell me why nothing is displayed for `params.json`.

### Environment information

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.11.0+6fcafc
---------------------------------
Platform: Python 3.6.9 on Linux-4.19.128-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/sdb
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by jorgeorpinel** [comment]
I'm tracking this feature and it seems to come from https://github.com/iterative/dvc/issues/4446#issuecomment-683379112/https://github.com/iterative/dvc/issues/4446#issuecomment-744362801, via https://github.com/iterative/dvc/pull/5122 so maybe @pared can help clarify what's going on here 🙂

**Comment by skshetry** [comment]
@jorgeorpinel, you are piping a yaml data to a `json` file. That's why it is getting ignored.

**Comment by jorgeorpinel** [comment]
> you are piping a yaml data to a json file

Good point! Although it's not a JSON file, it's a YAML file with `.json` extension in this case. And if I don't give it a file extension or use `.txt`, it works... Why? Maybe DVC shouldn't assume a type from the file ext. or at least output a warning when it finds a mismatch?

Updated issue labels and description.

**Comment by skshetry** [comment]
> YAML file with json extension

What? If it has a `json`, it should be a JSON file. We do fallback to YAML if they have a different extension or not at all, but otherwise, the extension is what we use to decide. We support many file formats: json/yaml/toml/python, so it's not easy to detect.

**Comment by efiop** [comment]
Retrying with the whole list of supported formats might be a huge performance concern too, so I also don't think we should stop using extensions as first hints. Though a warning about the mismatch or a special entry "malformed"/etc in the table would be nice.

**Comment by jorgeorpinel** [comment]
OK sure, up to you.

> a warning about the mismatch or a special entry "malformed"/etc in the table would be nice.

Agree, but this issue has been closed.

**Comment by efiop** [comment]
We used to have a field like that in the table, but then decided against it because there might be old metrics/params in now unsupported format. Warnings are also too noisy and we consciously decided against them earlier. There are debug messages though in verbose mode.

**Comment by jorgeorpinel** [comment]
Thanks for the context. The problem with verbose mode is that you need to a) think that there is a problem and b) know that it exists to use it. Without a warning the user may just move on assuming everything is fine. I don't think it's too noisy for our own standards, we print warnings for a bunch of things in different commands 🙂 though maybe you have a criteria for that internally that I'm unaware of.

**Comment by efiop** [comment]
Yeah, clearly we need to formalize our approaches in some design docs so we could reference them and not rethink it each time. Kinda like no-prompt policy that we've been talking about for a long time now. I have it on my todo list, just need to get to it. For now this behaviour is consistent with the approach that we chose earlier, so let's keep it as is.

**Comment by pared** [comment]
@jorgeorpinel We should probably formalize some of our design decisions. The `debug/warning` problem was solved by using `debug` in most of the cases, because there was a point in time where even simple use cases spewed few warnings at a time, and `warning` lost its meaning.
