### ISSUE TITLE
gitignore: put all DVC ignore items under a separate section

### ISSUE THREAD

**Issue by DiPaolo** [iterative/dvc#5213]
### Goal
To keep .gitignore clear and readable as well as follow default GitHub's .gitignore style.

### Problem
As of today, default Python .gitignore provided by GitHub looks like this:
```
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/

...

# mkdocs documentation
/site

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Pyre type checker
.pyre/
```

The problem is that after adding user's files it looks as follows (just an example):
```
...

# Pyre type checker
.pyre/
/database.db
/dataset
```

As you may see, there are two new lines added by DVC.

The problem is that they're placed under Pyre section. It could be confused as well as it doesn't follow the initial file structure.

### Suggestion
I would suggest to place all DVC specific ignore items under its own section. The example above could be rewritten as:
```
...

# Pyre type checker
.pyre/

# DVC
/database.db
/dataset
```

### Feature Formal Description
- [ ] DVC adds gitignore to a separate section called ```DVC``` (**TBD**)
- [ ] There is an empty line above the section
- [ ] New DVC-related files/folders are added under the section (even if new gitignore lines had been added below by someone else later)

**Comment by efiop** [comment]
Closing as stale
