### ISSUE TITLE
cache pull and push strategy

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#522]
For small files `dvc cache pull -j 64` works ~2 times faster than the default settings.

1. Why don't we increase the default number to 64 or 32?
2. It would be great to start with large files. Is it possible\cheap to implement?

The same staff for `dvc push`.

**Comment by efiop** [comment]
#529

**Comment by dmpetrov** [comment]
Large file issue example...

I wait for ~1 minute for `fd/47d523fa82bb9c282b897b55be0442` pull. When it was done 40 more small files were pulled.

```
(24959/25001): [##############################] 100% 2c/418de86963acfed9c3b3b60ee0cf8f
(24960/25001): [#######################       ] 77% fd/47d523fa82bb9c282b897b55be0442


(24960/25001): [##############################] 100% fd/47d523fa82bb9c282b897b55be0442
(24961/25001): [##############################] 100% 66/9eb8a94c61e26da0285de06bc5546e
(24962/25001): [##############################] 100% 91/e8dd29e4265f60e066b9e35c82b1ac
(24963/25001): [##############################] 100% 80/b13239ccf18734c2dc66bcb2612bf5
(24964/25001): [##############################] 100% c5/62df6abaae0257b0bfd3408f9450a6
```

**Comment by efiop** [comment]
No longer relevant with new remote design.
