### ISSUE TITLE
`alias`d commands help message starts from next line

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5238]
```console
$ dvc --help
...
 version (doctor)
                     Display the DVC version and system/environment information.
    update           Update data artifacts imported from other DVC repositories.
    plots            Commands to visualize and compare plot metrics in structured files (JSON, YAML, CSV, TSV)
    experiments (exp)
                     Commands to run and compare experiments.
```

**Comment by DiPaolo** [comment]
I've made an investigation on this. For me it looks like an issue in Python's ```argparse```.

I was able to fix the issue locally. So I filed a ticket https://bugs.python.org/issue42875 as well as made a fix. Hope my PR into Python repository (https://github.com/python/cpython/pull/24177) will be reviewed and accepted.

**Comment by skshetry** [comment]
This is a bug in python, which is being tracked upstream. Closing.
