### ISSUE TITLE
s3: support MFA token code

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#5241]
Would be extremely handy if we could configure dvc to ask for the mfa code and just use the sts creds automatically. E.g. https://stackoverflow.com/questions/42706254/are-there-any-boto3-mfa-examples-out-there

Currently, we do something like
```
$ aws sts get-session-token --serial-number arn:aws:iam::123456:mfa/ruslan --token-code code-from-token
```
and then use key, secret key and session token through aws config, env vars or dvc config, which is annoying. Though there is probably some tool to handle it on the cli level, but native dvc support would amazing to have.

**Comment by shcheklein** [comment]
@efiop yep, there are tools and scripts that modify default credentials. I wonder if other tools like `rclone` provide that high level abstraction? We would have to write it into `--local` config?

**Comment by efiop** [comment]
@shcheklein Briefly checked rclone earlier, I don't think they support it natively.

The option to use mfa token would be in config, local or not, since the whole team is probably using it. If you are asking about the token itself, it doesn't make much sense to save it anywhere, but actually dvc would have to prompt for it, kinda like `ask_password` in ssh remote. Seems to be the most handy way to use it.

**Comment by shcheklein** [comment]
@efiop hmm, but you would need to ask it again and again, then (every new command). STS can give you a token that expires in hours at least, and usually (I do at least) there is a script that saves it (and also secret, and key) into `.aws/credentials`. Thus you are done for a day at least :)

**Comment by efiop** [comment]
@shcheklein Ah, you meant that. No, i would hide it into .dvc/tmp or something, similar to the way we do it with gdrive.

**Comment by efiop** [comment]
Closing as stale.
