### ISSUE TITLE
pull: warning on failed objects is too low level

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#5248]
## DVC Version

```
DVC version: 1.11.0+322fc6
---------------------------------
Platform: Python 3.8.6 on macOS-10.15.6-x86_64-i386-64bit
Supports: All remotes
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1
Caches: local
Remotes: dropbox
Workspace directory: apfs on /dev/disk1s1
Repo: dvc, git
```

## Reproduce

Clean remote storage, pull a file:

`dvc pull images.tar.dvc`

## Output

```
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
name: images.tar, md5: 721d011095cf62dd7cd5be2ea2c269b7
WARNING: Cache 'HashInfo(name='md5', value='721d011095cf62dd7cd5be2ea2c269b7', dir_info=None, size=192139264, nfiles=None)' not found. File 'images.tar' won't be created.
1 file failed
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
images.tar
Is your cache up to date?
```

## Problems

- ~~`HashInfo(name='md5', value='721d011095cf62dd7cd5be2ea2c269b7', dir_info=None, size=192139264, nfiles=None)` is not acceptable for UI~~ https://github.com/iterative/dvc/pull/5319
- WARNING prefix looks ugly
- warnings are probably not needed (especially if it's causing ERROR at the end - ERROR in this case should be better)

**Comment by pmrowla** [comment]
Note from https://github.com/iterative/dvc/pull/5320#pullrequestreview-575086369:

in addition to the low level warnings needing to be cleaned up, the error message itself should be addressed as well:

> If a file which needs to be fetched does not exist in the remote, what happens now is that we only display the "checkout failed" message:
> 
> ```
> $ dvc pull
> 1 file failed
> ERROR: failed to pull data from the cloud - Checkout failed for following targets:
> data/data.xml
> Is your cache up to date?
> <https://error.dvc.org/missing-files>
> ```
> 
> In this case the real cause of the problem is not that the (local cache) checkout step failed, it's that the (remote) fetch step failed. It seems to me like what is really needed here for `dvc fetch/pull` would be a "is your remote up to date" hint (because someone else forgot to `dvc push`) rather than "is your (local) cache up to date" (because you forgot to `dvc fetch/pull`) hint.
