### ISSUE TITLE
get[-url]/import-url: jobs option?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5267]
`import` has `--jobs` (used by most commands that download data from DVC remotes) but `get` is missing it.

And what about import-url and get-url? They use the same remote interfaces after all.

**Comment by isidentical** [comment]
I avoided adding `--jobs` until we decided on whether to use both `add`/`import-url` or one of them, but we will definitely need it for #5198!

**Comment by isidentical** [comment]
By the way, `repo.imp_url()` already takes a `jobs=` parameter so only thing missing is a CLI arg

**Comment by jorgeorpinel** [comment]
Thanks! #5362 didn't implement `import-url --jobs` though. Is that because we decided not to? Or should we reopen this for that last detail.

**Comment by isidentical** [comment]
It is already implemented in my straight-to-remote PR
