### ISSUE TITLE
permanent deletion config for versioned S3 repositories during garbage collection

### ISSUE THREAD

**Issue by charlesmelby** [iterative/dvc#5269]
When working with data involving restrictions (e.g. personal information), it is often necessary to be able to delete it at a later date.

If the data has to go onto an S3 bucket with versioning enabled (the situation I'm in now), garbage collection only adds a delete marker, and the data can still be recovered.

I would like to propose adding a config option for S3 remotes that enables permanent deletion.
When set on a versioned remote, any object deleted during garbage collection would be deleted permanently.

Apparently permanent deletion can be done with boto3, e.g.
https://stackoverflow.com/questions/46819590/delete-all-versions-of-an-object-in-s3-using-python/53872419#53872419

**Comment by efiop** [comment]
discord context https://discord.com/channels/485586884165107732/563406153334128681/799190657435828274

**Comment by skshetry** [comment]
This may be potentially out of scope for DVC. cc @dberenbaum.

**Comment by dberenbaum** [comment]
Good thought @skshetry, but given our increased support for cloud versioning, I think this one is likely to be a need when doing gc on cloud-versioned remotes. cc @pmrowla
