### ISSUE TITLE
Automate `dvc add`

### ISSUE THREAD

**Issue by rakesh4real** [iterative/dvc#5308]
Hi,

I am new to dvc. I see that we need to run `dvc add` to update our data changes. Why don't we create something that executes `dvc add` as soon as `git add ...` is run in terminal

**Comment by efiop** [comment]
@rakesh4real Did you mean `git add` after `dvc add`?

**Comment by rakesh4real** [comment]
Yes, my bad.  `git add` after `dvc add`.

**Comment by skshetry** [comment]
@rakesh4real, there's `autostage` config that does that. Look for `core.autostage` in the docs for more information: https://dvc.org/doc/command-reference/config#core
