### ISSUE TITLE
AWS S3 remote storage object life cycle support

### ISSUE THREAD

**Issue by ainhattv** [iterative/dvc#5313]
Hi DVC team,

In the current, our team uses DVC to versioning and store models and assets data.
We use S3 as remote storage. We have a large scale dataset and growth so quickly.
We want to enable S3 life cycle policy to clean the old files in the bucket to save cost.
**Is there any problems if we change the object layer or remove it such as dvc hash files?**

Thanks,
Nhat Tran

**Comment by pmrowla** [comment]
It's possible that you may end up removing an object that is still referenced in your DVC repo, in which case you would no longer be able to `dvc pull` the file from that S3 remote and then `dvc checkout` that file. You may want to consider using `dvc gc -c` instead: https://dvc.org/doc/command-reference/gc#gc

As an example,
```
$ dvc gc -c -r <your_s3_remote_name> --all-branches
```
would remove all files from your S3 remote which are not referenced in the most recent tips of any git branches in your repo.

Automating something to run `gc -c` on a regular basis would allow you to regularly prune old files from your bucket without potentially breaking the most recent commit(s) in your DVC repo.

**Comment by isidentical** [comment]
As @pmrowla mentioned, the policies might remove something that is still referenced so it is safer to use `dvc gc` with the appropriate scope to do the cleaning. Closing now since the question in answered
