### ISSUE TITLE
ignore dvc.lock file?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5338]
We started not traversing through git-ignored directories and files looking for `.dvc` file and `dvc.yaml` file for performance reasons on #5265.

But there's a question for what should we do if the `dvc.lock` file is git-ignored. Currently, we assume the lockfile as empty if
it dvc-ignored, but the check for gitignore is not done.

@pmrowla had some concerns regarding experiments:

> > An open question is, what should we do about lockfiles if they are git-ignored or dvc-ignored?
> 
> I think users should be able to ignore lockfile. Dvc is able (to some extent) to work without it, so removing this possibility would limit `dvc`'s functionality. And I guess one can come with some use cases where this is actually a feature. For example any educational material that's purpose is to show how running the pipeline looks like.

One thing to keep in mind is that experiments runs in temp directories (and on remote machines in the future) have to git commit `dvc.lock` in order for us to retrieve the experiment result. We can (and already do) force-add gitignored lock files internally for these types of runs, and on the user's local `exp apply` the dvc.lock file would no longer be staged/committed like normal. But this does seem like the kind of thing that may lead to unexpected behavior in the future and it may be safer for us to forbid it?

_Originally posted by @pmrowla in https://github.com/iterative/dvc/issues/5265#issuecomment-765231979_

---

**Comment by pared** [comment]
Related: 
https://github.com/iterative/dvc/issues/5396

**Comment by pared** [comment]
Seing https://github.com/iterative/dvc/issues/6025 makes me wonder whether forbidding to `.gitignore` was a right choice. Maybe we should have detect that upon running experiments and throw an error only in such situation?

**Comment by stephanrb3** [comment]
I have a use case for this:

We don't store the pipeline in the repo itself we store it in a separate repo which is pulled down to each model repo during ci pipelines. And we also have separate pipelines stored locally for other purposes. So we run different pipelines depending on what the engineer is trying to do. So we always have at least 2 completely different pipelines that run in the same repo, and we don't want to commit the dvc lock file back to repo in the ci runs, because it invalidates the local pipelines.

**Comment by karajan1001** [comment]
> I have a use case for this:
> 
> We don't store the pipeline in the repo itself we store it in a separate repo which is pulled down to each model repo during ci pipelines. And we also have separate pipelines stored locally for other purposes. So we run different pipelines depending on what the engineer is trying to do. So we always have at least 2 completely different pipelines that run in the same repo, and we don't want to commit the dvc lock file back to repo in the ci runs, because it invalidates the local pipelines.

Excuse me, I have a question here, why can't store all of the pipelines in the `dvc.yaml` and do different executions in different ci progress `dvc run "special stage name"`?

**Comment by stephanrb3** [comment]
We run one pipeline universally for all of our models, and each individual model has its own pipelines. We have dozens of models, so adding all of their pipelines to our universal pipeline would represent a massive overhead. Besides that we still pull down the required files and the pipeline itself from another repo, so dvc.lock would recognize that as a modification.

**Comment by karajan1001** [comment]
> We run one pipeline universally for all of our models, and each individual model has its own pipelines. We have dozens of models, so adding all of their pipelines to our universal pipeline would represent a massive overhead. Besides that we still pull down the required files and the pipeline itself from another repo, so dvc.lock would recognize that as a modification.

I don't think you need to add all of the model generation pipelines to your universal pipeline, instead, you can just create some model training pipelines to generate these models and push them to the remote. And in the inference pipelines, you can use `dvc import` to import them from the training repo.
