### ISSUE TITLE
stage:add: decide on `-c` command vs remainder arg for user's script

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5342]
On `dvc run`, the remainder positional argument is considered as a script. 
```console
$ dvc run -n stage_name -o bar -w data echo bar > bar
```

But, we have heard complaints from users that it's confusing, as trying to add certain flags to `dvc run` at the end is now assumed to be part of the user's script. 

So, on `stage:add`, we moved it under the `-c`/`--command` flag and now needs to be explicitly specified and quoted.
```console
$ dvc stage add stage_name -o bar -w data -c "echo bar > bar"
```

@dmpetrov later pointed out that it breaks the autocompletion for users. This discussion was without any DVC's autocompletion installed.

With DVC's autocompletion installed, the autocompletion anyway does not work as it is assumed as a plain string.

Anyway, we have to either choose between`-c` and the remainder arg in `run`.

cc @dberenbaum @shcheklein @jorgeorpinel

**Comment by dberenbaum** [comment]
I don't understand the autocompletion issue with the `-c "echo bar > bar"` format. I'm able to autocomplete on Ubuntu in bash and zsh even inside of quotes. Is there an example of how this breaks autocompletion? Is it a specific issue with OSX? Maybe @dmpetrov can elaborate?

**Comment by skshetry** [comment]
@dberenbaum, that's strange. For me (on Linux), it never autocompletes, with or without DVC's autocompletion.

**Comment by dberenbaum** [comment]
@skshetry What are you trying to autocomplete? What shell are you using? Does autocomplete work for you without the `-c` flag and quotes?

**Comment by dmpetrov** [comment]
@dberenbaum Autocompletion issue - the default autocomplete suggests files that I have in a dir when I type `dvc run -n s1 python tr<TAB>`. It won't suggest inside a quoted string - `dvc run s1 -c " python tr<TAB>` (however, it suggests as 1st item in a string `dvc run s1 -c "tr<TAB>` which is not a usual corner case).

@skshetry The decision about string VS reminder was made in the very first version of DVC. I considered a `-c/--command` option as the opposite of the remainder. The reminder looks more common and convenient. An analogy with a reminder - `xargs`.

To my mind, the issue with mixing up params is not a major one. By replacing the behavior we might have new issues (the autocomplete is one of them). I suggest not changing the behavior and keep cmd as a reminder.

**Comment by dberenbaum** [comment]
Thanks, @dmpetrov! I was trying the equivalent of `dvc run s1 -c "tr<TAB>`, but now I understand and see the same on my end.

**Comment by shcheklein** [comment]
I agree that `But, we have heard complaints from users that it's confusing, as trying to add certain flags to dvc run at the end is now assumed to be part of the user's script.` doesn't sound like a big issue, considering that people will have to double quote commands now (and escaping if needed) + they will have to remember/learn about `-c` + it breaks autocompletion (not matter DVC's one installed or not).

**Comment by dberenbaum** [comment]
Yup, let's stick with the existing syntax unless you have any concerns @skshetry .

**Comment by skshetry** [comment]
One thing I noticed was since both the name and the command are positional arguments, if the user forgets those and for example, types as following, it is error-prone since we don't run scripts like `dvc run` does.
```
$ dvc stage add echo "foo bar"
```

But that's a minor thing I guess. I made a PR to keep the behaviour same as of  `dvc run` in #5350.
