### ISSUE TITLE
pre-push hook: Missing dependencies ['google-cloud-storage'] when it tries to push dvc data to google cloud storage cache

### ISSUE THREAD

**Issue by dpcabo** [iterative/dvc#5345]
# Bug Report

pre-push hook: Missing dependencies ['google-cloud-storage'] when it tries to push dvc data to google cloud storage cache.

## Description
I am getting the following error when pre-push hook is enabled and git push is called:

```console
DVC pre-push.............................................................Failed
- hook id: dvc-pre-push
- exit code: 1

ERROR: failed to push data to the cloud - URL 'gs://dvc_cache' is supported but requires these missing dependencies: ['google-cloud-storage']. Please report this bug to <https://github.com/iterative/dvc/issues>. Thank you!
```

However, If I run dvc push, it works fine.

### Reproduce

0. pip install pre-commit
1. git init
2. dvc init
3. dvc remote add -d gscache gs://dvc_cache
4. dvc install --use-pre-commit-tool
5. dvc run -n first-stage -o one-file touch one-file
6. git push -u origin main

### Expected

Same behaviour than dvc push 

### Environment information

conda environment with python=3.6 google-cloud-storage=1.19.0 pre-commit pip dvc dvc[gs]

**Output of `dvc version`:**

```console
DVC version: 1.11.13
```

**Comment by skshetry** [comment]
@dpcabo, please checkout the [hooks install guide](https://dvc.org/doc/command-reference/install#using-the-pre-commit-tool). You just need to specify `additional_dependencies`. 

Closing the issue. Feel free to reopen if there's any issues with it. Thanks.

**Comment by skshetry** [comment]
That is:
```yaml
additional_dependencies: ['.[gs]']
```
