### ISSUE TITLE
Python api - pull file from local cache if available

### ISSUE THREAD

**Issue by MikeCoppola-AI** [iterative/dvc#5349]
Hi,
My use case for dvc is as follows:
- data files are stored in an s3 remote
- dvc repo is remote
- our code base that uses the tracked dvc files is a separate repo
- from the code repo, we use the python api to pull files (using remote repo and `rev`)
- multiple users that share the code repo will be frequently re-running experiments, so if the local cached version of the file exists, it would be beneficial for us if the api loaded the file from cache rather than re-downloading from the remote.

This feature would allow us to easily share the code repo without the need to modify paths in the code, help us work from the same data versions for experiments, and increase productivity.

Looking forward to feedback. Let me know if any questions.
Regards,
Mike

**Comment by skshetry** [comment]
@MikeCoppola-AI, would it be possible to use a global cache? Right now, we don't have a good support for this for external URLs. 

You can try out the following APIs to see if it fits your need:
```python
from contextlib import contextmanager

@contextmanager
def dvc_repo(url: str, *args, cache_dir: str = None, **kwargs):
    with Repo.open(url, *args, **kwargs) as repo:
        if cache_dir:
            repo.cache.local.cache_dir = cache_dir
        yield repo
```

And, you can use this as follows (eg: to emulate as `dvc.api.open`):
```python
with dvc_repo(repo="git@github.com:<my_remote_github_repo>", rev="rev", cache_dir="<cache_dir>") as repo:
    with repo.open_by_relpath("<path_to_file>") as fd:
        df = pd.read_csv(fd)
```

You can read the code for API, which is using the same internal API:
https://github.com/iterative/dvc/blob/master/dvc/api/__init__.py#L80-L85

---

Note that the API mentioned above is a new one, only available in the master branch. And, we are improving on it, so it might change.

**Comment by skshetry** [comment]
You might even be able to mock it if you set global cache dir through global variable (instead of passing). Which would effectively be:
```python
import dvc.api

dvc.api._make_repo = dvc_repo
with dvc.api.open() as fd:
    fd.read()
```

**Comment by skshetry** [comment]
Closing as stale.
