### ISSUE TITLE
run: hard to create a stage when dependency doesn't exist yet

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#5359]
# Bug Report

## Description

When we'd like to create a pipeline with `dvc run`, but we don't execute stages yet, or raw input files (e.g. `import-url`, `import` ) are not there yet, there is not option to create a stage, it keeps complaining that dependency doesn't exist.

It affects a lot of other potential scenarios. E.g. I'd like to change a stage (with `-f` but some dependencies do not exist yet/anymore (e.g. removed by `dvc repro`, or manually). 

It feels it should allow deps do not exist in `--no-exec` and/or `--no-commit` mode, just don't set checksums.

We also should potentially revisit semantics of the `--no-commit` option. Its name implies that it's a reverse of `dvc commit`, while it's not (it updates `dvc.lock`?).

### Reproduce

```
dvc import-url --no-exec s3://dvc-temp/images.tar
dvc run --no-commit -d images.tar -n dummy echo "dummy"
```

Gives:

`ERROR: dependency 'images.tar' does not exist`

### Expected

I think `--no-commit` should not be updating `dvc.lock` (be reverse of the `dvc commit`)
In this case it won't requited `images.tar` to be present.

### Environment information

**Output of `dvc version`:**

```console
DVC version: 1.11.0+3ea090
---------------------------------
Platform: Python 3.8.6 on macOS-10.15.6-x86_64-i386-64bit
Supports: All remotes
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1
Repo: dvc, git
```

**Comment by dberenbaum** [comment]
@shcheklein It seems like this has been addressed by `stage add`? Feel free to reopen if I misunderstood.
