### ISSUE TITLE
change `dvc metrics show` table similar to `dvc metrics diff`?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5376]
# Bug Report

If you have a lot of metrics in a single file (>5), the table soft-wraps to the next line and is hard to distinguish which is what. For an API data from GitHub:
```console
$ dvc metrics show
Path       archived    disabled    fork    forks    forks_count    has_downloads    has_issues    h
as_pages    has_projects    has_wiki    id        network_count    open_issues    open_issues_count    organization.id    organization.site_admin    owner.id    owner.site_admin    private    size    stargazers_count    subscribers_count    watchers    watchers_count
data.json  False       False       False   691      691            True             True          False        True            True        83878269  691              518            518                  39572954           False                      39572954    False               False      11575   7182                119                  7182        7182
```

While `metrics diff` is really easy to view:
```console
$ dvc metrics diff
Path       Metric                   Old    New       Change           
data.json  archived                 —      False     —
data.json  disabled                 —      False     —
data.json  fork                     —      False     —
data.json  forks                    —      691       —
data.json  forks_count              —      691       —
data.json  has_downloads            —      True      —
data.json  has_issues               —      True      —
data.json  has_pages                —      False     —
data.json  has_projects             —      True      —
data.json  has_wiki                 —      True      —
data.json  id                       —      83878269  —
data.json  network_count            —      691       —
data.json  open_issues              —      518       —
data.json  open_issues_count        —      518       —
data.json  organization.id          —      39572954  —
data.json  organization.site_admin  —      False     —
data.json  owner.id                 —      39572954  —
data.json  owner.site_admin         —      False     —
data.json  private                  —      False     —
data.json  size                     —      11575     —
data.json  stargazers_count         —      7182      —
data.json  subscribers_count        —      119       —
data.json  watchers                 —      7182      —
data.json  watchers_count           —      7182      —
```

Should we consider moving to `diff`-like table or at least provide a flag to flatten them?

**Comment by dberenbaum** [comment]
For a single stage, the diff-like table would work, but maybe not if there are metrics for multiple stages. For someone using `foreach`, for example, there could be lots of rows in the metrics table. In that case, does a diff-like format makes sense?

The flag to flatten seems easier. Maybe `dvc metrics show` can borrow the `dvc exp show` format for consistency. Thoughts @skshetry and @pmrowla ?

**Comment by j-hartshorn** [comment]
I've just run into this issue and would be keen to see an improvement here.

The other option is to wrap the whole table that's currently shown. For example, going from:

| Path  | metric_1 | metric_2 | metric_3 | metric_4 |
|-------|----------|----------|----------|----------|
| File1 | 0.2      | 0.3      | 0.4      | 0.5      |
| File2 | 0.25     | 0.35     | 0.45     | 0.55     |

to:

| Path  | metric_1 | metric_2 |
|-------|----------|----------|
| File1 | 0.2      | 0.3      |
| File2 | 0.25     | 0.35     |

| Path  | metric_3 | metric_4 |
|-------|----------|----------|
| File1 | 0.4      | 0.5      |
| File2 | 0.45     | 0.55     |

**Comment by skshetry** [comment]
@j-hartshorn, good idea, thanks for the suggestion. Although this might not make it easy to grep, WDYT?

**Comment by efiop** [comment]
Both use same table from https://github.com/iterative/dvc/blob/main/dvc/compare.py
