### ISSUE TITLE
dvc import-url should have a flag to write to dvc.lock instead of .dvc file.

### ISSUE THREAD

**Issue by antonkulaga** [iterative/dvc#5379]
I had a lot of confusion with .dvc files and dvc import URLs https://github.com/iterative/dvc/issues/5370 
I think one of the cause was that I was trying to move data from .dvc files generated by dvc import-url to dvc.yaml (while in fact I should have moved it to dvc.lock). I believe that it makes sense just to make a flag in dvc import-url to put output to dvc.lock instead of creating .dvc file. This will allow organizations who try to keep everything in dvc.lock+dvc.yaml just to do it instantly without bothering copy-pasting dvc import-url output and making mistakes in the process.

**Comment by efiop** [comment]
We plan on getting rid of `.dvc` for imports and using `dvc.yaml`(+dvc.lock) instead. Closing in favor of https://github.com/iterative/dvc/issues/5058
