### ISSUE TITLE
unable to use GS remote

### ISSUE THREAD

**Issue by no-mans** [iterative/dvc#5400]
Hi - I have an issue using DVC with GS in one of the team's machines.
`dvc pull` yields:
```bash
ERROR: failed to pull data from the cloud - URL 'gs://XXX' is supported but requires these missing dependencies: ['google-cloud-storage']. To install dvc with those dependencies...
```
It is similar to [this published issue](https://www.gitmemory.com/issue/iterative/dvc/4560/696111759) only with GS instead of GDRIVE.

dvc was installed with `pip install "dvc[gs]"`, and we also later tried with `dvc[all]`, both produced the same issue.
we verified that `google-cloud-storage` is installed.

`dvc --version` output:

```bash
DVC version: 1.11.15 (pip)
---------------------------------
Platform: Python 3.7.4 on Darwin-19.6.0-x86_64-i386-64bit
Supports: hdfs, http, https, s3
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: gs
Workspace directory: apfs on /dev/disk1s1
Repo: dvc, git
```

Can you please advise?
Thanks

**Comment by efiop** [comment]
Hi @no-mans !

Could you show 
```
pip freeze | grep google-cloud-storage
```

?

Also, could you try:
```
python -c 'import google.cloud.storage'
``` 
and show full log?

**Comment by efiop** [comment]
Closing as stale
