### ISSUE TITLE
dvc exp gc: can't run experiments after garbage collection

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#5405]
# Bug Report

## Description

Experiments fail after garbage collection via `dvc exp gc`.

### Reproduce

1. dvc init
2. dvc stage add -n foo -M foo.yaml 'echo "score: 1" > foo.yaml'
3. git add .
4. git commit -m "add stage"
5. dvc exp run
6. dvc exp gc -fT
7. dvc exp run

```console
Stage 'foo' didn't change, skipping
ERROR: Failed to set 'refs/exps/d1/5cee9fd7a4fc20c5d7167671df4ed78b3cfb7a/exp-985c5'
ERROR: Failed to set 'refs/exps/d1/5cee9fd7a4fc20c5d7167671df4ed78b3cfb7a/exp-985c5'
```

### Expected

`dvc exp run` to successfully run experiment.

### Environment information

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 2.0.0a0+adedd1
---------------------------------
Platform: Python 3.9.1 on Linux-5.8.0-38-generic-x86_64-with-glibc2.31
Supports: http, https
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by pmrowla** [comment]
After the fix, this issue should be resolved in new repos.

In an existing repo in the state which is causing the error, you may need to run 
```
$ git symbolic-ref -d refs/exps/exec/EXEC_BRANCH
```
manually first
