### ISSUE TITLE
dvc pull will Stuck on download 97%

### ISSUE THREAD

**Issue by kobewangSky** [iterative/dvc#5417]
# Bug Report

dvc pull     will stop in download 97%

## Description
I push data to dvc, and small data can work, but if I push data over 30G, when I want pull, will stop in 97%
and I put all data in one folder, I just push that folder.

--data
         |--test
         |--train

I push data

### Reproduce

nothing just stop in download

git clone  XXX
git checkout dev
dvc pull

### Expected
finish download

### Environment information

**Output of `dvc version`:**

```console
$ dvc version
```
DVC version: 1.11.10 (deb)
---------------------------------
Platform: Python 3.7.9 on Linux-5.3.0-40-generic-x86_64-with-debian-buster-sid
Supports: All remotes

**Additional Information (if any):**

**Comment by isidentical** [comment]
Is it possible for you to supply the whole output of `dvc pull -v`?

**Comment by efiop** [comment]
Closing as stale
