### ISSUE TITLE
Failed to push data to the cloud - URL gdrive token is supported but requires these missing dependencies: ['pydrive2'].

### ISSUE THREAD

**Issue by Prem948** [iterative/dvc#5422]
# Bug Report

### Environment information

**Output of `dvc version`:**

```console
$ dvc version
```

**Additional Information (if any):**

**Comment by efiop** [comment]
Hi @Prem948 . Could you provide `$ dvc version`, please?

**Comment by Prem948** [comment]
DVC version: 1.11.10 (exe)

**Comment by efiop** [comment]
@Prem948 Thanks! Could you provide __full__ `$ dvc version` output, please? :slightly_smiling_face:

**Comment by efiop** [comment]
Closing as stale
