### ISSUE TITLE
azure: QA our implementation

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#5435]
People have been complaining about our azure remotes having other issues with authentication, e.g.

https://github.com/iterative/dvc/issues/4534
https://github.com/iterative/dvc/issues/4635

Azure support is very important for us, but unfortunately, no one in the core team is using it regularly (except for the tests that we have, which are clearly not enough). Need to take a look into it, check different auth options, check performance, etc.

**Comment by isidentical** [comment]
After reviewing the requirements, and also the future plans it seemed like a reasonable approach to use fsspec for our implementation. It supports authenticating with account key, principals, sas token out of the box. And already covers all the functionality we need.

**Comment by friggog** [comment]
I have a few comments from using DVC with Azure

First service principal auth, which I know is being worked on. Specifically on Azure DevOps CI, the environment variables for service principal auth are set automatically and it would be nice if DVC could use these directly:
```python
from azure.common.credentials import ServicePrincipalCredentials
from azure.storage.blob import ContainerClient

tenant_id = os.environ['tenantId']
client_id = os.environ['servicePrincipalId']
client_secret = os.environ['servicePrincipalKey']
credential = ServicePrincipalCredentials(tenant=tenant_id, client_id=client_id, secret=client_secret)
client = ContainerClient([url], [container], credential=cred)
```

Secondly, DVC doesn't have support for role based authentication - this is pretty important if, for example, I want a user to be able to read but not write to my DVC remote (or just don't want to give them full access to my storage account through the access key). Plus this can be a totally automated process with interactive login on the first time.

```python
from azure.common.credentials import get_azure_cli_credentials

cred, sub = get_azure_cli_credentials() # requires Azure CLI login to have happened (can be prompted through code using azure.cli.core)
client = ContainerClient([url], [container], credential=cred)

# you can also create a connection string from the token
token = cred.get_token("https://storage.azure.com").token
connection_string = f"DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName={storage_account_name};Token={token}"
```

**Comment by isidentical** [comment]
> First service principal auth, which I know is being worked on. Specifically on Azure DevOps CI, the environment variables for service principal auth are set automatically and it would be nice if DVC could use these directly without user input/configuration:

Is there a reference that you can point me to for these environment variables? Azure's python [client documentation](https://docs.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#environment-variables) mentions about the environment variables in the form of `AZURE_CLIENT_ID`/AZURE_TENANT_ID` not `tenantId`/`servicePrincipalId`.

**Comment by isidentical** [comment]
> Secondly, DVC doesn't have support for role based authentication - this is pretty important if, for example, I want a user to be able to read but not write to my DVC remote (or just don't want to give them full access to my storage account through the access key). 

Would you mind supplying a link for this as well? If it could be done by embedding into the connection string, we already support it though if it is something else it would be nice to see a complete example regarding how role-based auth works.

**Comment by friggog** [comment]
Regarding SPA - this is when using an AzureCLI task in a devops pipeline, see here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops under 'addSpnToEnvironment' in the table.

The token provided by the credential is temporary (with a reasonably short timeout I think), so saving it in the config file doesn't work. It would be possible to use the token if every DVC operation happened through some python wrapper that refreshed the connection string - but that's a pain.

Here is RBAC overview: https://docs.microsoft.com/en-us/azure/role-based-access-control/overview
This is the common credentials module: https://docs.microsoft.com/en-us/python/api/azure-common/azure.common.credentials?view=azure-python

My impression is that RBAC is the intention for managing permission on azure in the future as it gives much more fine-grained control than older methods

**Comment by isidentical** [comment]
Just for reference, it seems like we might benefit from `from azure.common.credentials import get_azure_cli_credentials` when using adlfs (passing it as `credential=`). I didn't try yet, so might not work as expected but the path for passing credential-like objects (with `get_token`/`signed_session` methods) seems present.

**Comment by friggog** [comment]
Sounds great - an all round solution for SPA and RBAC auth should look something like this, auth will open in a browser window the first time for cli creds:

```python
from adal import AdalError
from azure.cli.core import get_default_cli
from azure.cli.core._profile import Profile
from azure.common.credentials import get_azure_cli_credentials, _CliCredentials, ServicePrincipalCredentials
from knack.util import CLIError
from typing import Union


def _get_credential() -> Union[_CliCredentials, ServicePrincipalCredentials]:
        if 'servicePrincipalId' in os.environ:
            tenant_id = os.environ['tenantId']
            client_id = os.environ['servicePrincipalId']
            client_secret = os.environ['servicePrincipalKey']
            return ServicePrincipalCredentials(tenant=tenant_id, client_id=client_id, secret=client_secret)

        try:
            credential, _ = get_azure_cli_credentials()        # throws FileNotFoundError on a clean machine
            credential.get_token('https://storage.azure.com')  # throws CLIError if token not available and
                                                               # throws AdalError if authentication has expired
        except (FileNotFoundError, CLIError, AdalError):
            # Azure CLI token is not available. Perform interactive authentication to create it.
            # This is equivalent to running "az login".

            # get_default_cli() is required when running on a clean machine.
            get_default_cli()

            # async_persist=False will cause credentials cache to be flushed to disk immediately (instead of waiting
            # for program exit).
            print('Please complete the login process in the web browser.')
            profile = Profile(async_persist=False)
            profile.find_subscriptions_on_login(
                interactive=True,
                username=None,
                password=None,
                is_service_principal=False,
                tenant=None,
            )
            print('Done.\n')
            credential, _ = get_azure_cli_credentials()

        return credential
```

**Comment by isidentical** [comment]
Hey @friggog would you mind creating a new issue for your examples / ideas? It would be nice to track the progress for it in another issue (maybe even you can contribute!)
