### ISSUE TITLE
repo/run: Gitignores with exclusion and sub-gitignore produce duplicates

### ISSUE THREAD

**Issue by courentin** [iterative/dvc#5438]
# Bug Report

## Description

I've identified that the bug is coming from dulwich, you'll find more information in https://github.com/dulwich/dulwich/issues/836.
See the steps below to reproduce it with dvc.

I've created this bug report to make sure to update dulwich when the bug will be solved.

### Reproduce

```bash
dvc init
mkdir -p foo/bar
echo "/*" > foo/.gitignore
echo "\!/bar" >> foo/.gitignore
echo "/should_be_ignored" > foo/bar/.gitignore
dvc run -n test -o foo/bar/should_be_ignored echo "ignored" \> foo/bar/should_be_ignored
```

In `foo/bar/.gitignore` we have:
```text
/should_be_ignored
/should_be_ignored
```

### Expected

In `foo/bar/.gitignore` we should have:
```
/should_be_ignored
```

### Environment information

**Output of `dvc version`:**

```console
DVC version: 1.11.15 (pip)
---------------------------------
Platform: Python 3.7.6 on Darwin-20.2.0-x86_64-i386-64bit
Supports: http, https
Cache types: reflink, hardlink, symlink
Caches: local
Remotes: None
Repo: dvc, git
```

**Comment by pared** [comment]
It's not necessarily a bug on our side, though it's still a bug, so marking it as one. The best way to solve it would be to contribute to dulwich and update the version in our setup.

**Comment by courentin** [comment]
A new dulwich version has been released with the fix, I've linked the PR to make sure to use the right dulwich version.
