### ISSUE TITLE
exp show csv/tsv option

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#5446]
See https://github.com/iterative/dvc/pull/5381#issuecomment-773555945 for context. 

This is NOT a requirement for 2.0 release, but a nice-to-have that could be added after release.

Proposed format:
```
"Branch","Experiment","Revision","Queued","Checkpoint Tip","Checkpoint Parent","Created",...(params and metrics columns as they appear in CLI)
"workspace","baseline",,false,,,,...
"master","baseline","bcbee294fc6df6d096acdf1872a54e05818ce427",false,,,"2021-02-09T13:05:04",...
"master","exp-cd493","bcbee294fc6df6d096acdf1872a54e05818ce427",false,,,"2021-02-09T13:05:04",...
"master","named-exp","d4caebb5162878d16ea89ec125f88cb595a08491",false,,,"2021-02-10T11:18:00",...
"master","exp-deb9f","24f0f31b6daa46d57b7cd55d9238d55971b8a2b2",true,,,"2021-02-10T14:13:00",...
"checkpoints_branch","exp-c5edd","73b69e032634e69a0f96fb8f6c41d51485a9428d",false,"73b69e032634e69a0f96fb8f6c41d51485a9428d","0a7d8aa973c72bb88cb308b06273777260f21de6","2021-02-10T14:46:14",...
"checkpoints_branch","exp-c5edd","0a7d8aa973c72bb88cb308b06273777260f21de6",false,"73b69e032634e69a0f96fb8f6c41d51485a9428d","bcbee294fc6df6d096acdf1872a54e05818ce427","2021-02-10T14:46:13",...
```

Questions:
- Do the columns names make sense?
- Is any info missing?
- Is "Checkpoint Tip" redundant if "Experiment ID" is included in each row? Would a checkpoint boolean column be more helpful (indicating whether or not this is a checkpoint)?

@pmrowla @dmpetrov

**Comment by pmrowla** [comment]
The checkpoint tip column is redundant here, the json field is pretty specific to how we are rendering the table in the CLI & vscode extensions. (You can figure out the tip of a checkpoint branch by tracing the checkpoint parents field in reverse).

I'm also not sure if `branch` should be a column here vs using the git commit sha's, since you can have multiple branches/tags/etc pointing to a single git sha. We just choose one when we display the table in the CLI, but it might make more sense for us to have a git sha column and then a separate column for branch/tag names which point to that sha.

**Comment by dberenbaum** [comment]
We could have a "Branches" or "Refs" (to include tags) column like this:

```
"Experiment","Git Hash","Branches","Queued","Checkpoint Parent","Created",...(params and metrics columns as they appear in CLI)
"workspace",,"['master']",false,,,...
"baseline","bcbee294fc6df6d096acdf1872a54e05818ce427","['master']",false,,"2021-02-09T13:05:04",...
"exp-cd493","bcbee294fc6df6d096acdf1872a54e05818ce427","['master']",false,,"2021-02-09T13:05:04",...
"named-exp","d4caebb5162878d16ea89ec125f88cb595a08491","['master']",false,,"2021-02-10T11:18:00",...
"exp-deb9f","24f0f31b6daa46d57b7cd55d9238d55971b8a2b2","['master']",true,,"2021-02-10T14:13:00",...
"exp-c5edd","73b69e032634e69a0f96fb8f6c41d51485a9428d","['checkpoints_branch', 'master']",false,"0a7d8aa973c72bb88cb308b06273777260f21de6","2021-02-10T14:46:14",...
"exp-c5edd","0a7d8aa973c72bb88cb308b06273777260f21de6","['checkpoints_branch', 'master']",false,"bcbee294fc6df6d096acdf1872a54e05818ce427","2021-02-10T14:46:13",...
```

Or maybe it makes more sense to drop this column completely?

**Comment by robSanders818** [comment]
I think it'd be really useful to include a to_csv option.  Personally I just find the `dvc exp show` table impossible to read.  I have a lot of metrics that are being tracked, and some of them have longer names/fields, so the table gets cut off.  I can't scroll right on the table to view columns, so this would give the basic functionality of seeing every column.

In addition I plan on running my pipeline lots of times, and the table this command shows is perfect, it would just be nice to store a lot of iterations of the pipeline in a csv file.  This would enable the data to be easily viewed in excel, and manipulated in that environment which would be a really helpful functionality!  Thanks!

**Comment by dberenbaum** [comment]
This should be easy to do if it's simply taking the existing table that shows in the terminal and putting it into csv format (instead of designing a specific csv format like the comments above).
