### ISSUE TITLE
UnicodeDecodeError in plots.collect()

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#5490]
Have a PDF file in plots, which breaks `repo.plots.collect()` call:

```python
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 10: invalid start byte
  File "repos/parsing/dvcmeat.py", line 49, in parse_dvc
    _parse_plots(repo, commit)
  File "repos/parsing/dvcmeat.py", line 96, in _parse_plots
    commit.plots = repo.plots.collect().get("workspace", {})
  File "dvc/repo/plots/__init__.py", line 64, in collect
    data[rev][datafile]["data"] = fd.read()
  File "codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
```

More context: https://sentry.io/organizations/iterative/issues/2138285532/?project=5220519&referrer=slack

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.11.0+af26d5 
---------------------------------
Platform: Python 3.8.2 on Linux-5.4.0-58-generic-x86_64-with-glibc2.27
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss

```

**Comment by Suor** [comment]
Not sure what I expect to happen here. The options are:
- don't decode, live it binary
- skip file and continue with a warning

**Comment by pared** [comment]
Created PR to fix the issue. 
I went with "skip with warning" approach, as I am not sure how leaving as is would work. Down the line, we have to prepare HTML anyway, so somewhere we need to do some data transformation. We could probably think about allowing other files format and pasting them "as is" into HTML though. But there has been no request for that so I am not sure if it's worth thinking about, at least for now.
