### ISSUE TITLE
checkout: unsafe behaviour when trying to remove unused links

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5503]
It seems that the `dvc checkout` (without any targets) does not consider `pwd` of the user, and tries to act on the path that is relative to the root of the repo, rather than the one relative to the working directory of the user.

This has a few effects, if the user is using `checkout` from a directory other than the root of the repo:
1. Even though it says it deleted some files, it's not deleted. 
2. It might end up deleting a different file.

I think 2) to be a serious issue. Let me demonstrate:

```bash
#! /usr/bin/bash

cd "$(mktemp -d)" && git init && dvc init
echo "foo" > foo
dvc add foo

# remove file so that `unused_links` gets into effect
rm foo.dvc

mkdir data && cd $_
echo "foobar" > foo
dvc checkout
tree ..
```

Output (of interest):
```console
$ dvc checkout
D	foo
$ tree ..
.
├── data
└── foo
```

This will end up deleting the `foo` in the data rather than the one in the root of the repo.
Even if there was no file with the same name, the message would still show `D foo` there which is clearly wrong.

Also note that the message in the checkout stats is relative to the root of the repo, which is also confusing.

**Comment by skshetry** [comment]
Setting this as `p0`, as it could delete the user's file. Feel free to change the priority if you think otherwise.

**Comment by skshetry** [comment]
Another question, should we try to remove links/files/directories at all during `dvc checkout` that were removed using `dvc remove` earlier?

**Comment by efiop** [comment]
Ran into this too while playing with diskcache. The problem is that https://github.com/iterative/dvc/blob/cccead344194b61dc6d891bbfe705fb66dc9127b/dvc/state.py#L507 should do os.path.join(self.root_dir, path).

**Comment by efiop** [comment]
Fixed by #5505

**Comment by skshetry** [comment]
Even though the main issue of data deletion is fixed, the stats are still relative to the root of the repo instead of the working directory.

And, I have an open question on https://github.com/iterative/dvc/issues/5503#issuecomment-782792758.

**Comment by skshetry** [comment]
Bumping the priority, I see it as a p1.

**Comment by dberenbaum** [comment]
@skshetry Do you intend to look into this? Do you want to keep it as p1?

**Comment by skshetry** [comment]
I think this should be looked at as being part of `dvc-data` than `ui`, as I think it should always return stats in relative terms. cc @efiop.

**Comment by skshetry** [comment]
Closing as not planned. The critical issue was fixed and the only remaining issue was/is for UI.
