### ISSUE TITLE
More complete Azure authentication

### ISSUE THREAD

**Issue by friggog** [iterative/dvc#5511]
Continuing discussion from #5435.

I believe SPA has somewhat been addressed, but my two primary requests are:
- Automatic detection of azure auth env vars on azure devops CI when using [AzureCLI task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops), these are added as `servicePrincipalId`, `servicePrincipalKey` and `tenantId`.
- Support for [RBAC](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview) auth rather than relying on account key.

The code snippet below supports authentication for azure blob storage using SPA with the above env vars, falling back to RBAC auth through get_azure_cli_credentials. This triggers interactive login in the browser (through azure CLI) if the user hasn't logged in on that machine already, from then on it happens silently.

```python
from adal import AdalError
from azure.cli.core import get_default_cli
from azure.cli.core._profile import Profile
from azure.common.credentials import get_azure_cli_credentials, _CliCredentials, ServicePrincipalCredentials
from knack.util import CLIError
from typing import Union


def _get_credential() -> Union[_CliCredentials, ServicePrincipalCredentials]:
        if 'servicePrincipalId' in os.environ:
            tenant_id = os.environ['tenantId']
            client_id = os.environ['servicePrincipalId']
            client_secret = os.environ['servicePrincipalKey']
            return ServicePrincipalCredentials(tenant=tenant_id, client_id=client_id, secret=client_secret)

        try:
            credential, _ = get_azure_cli_credentials()        # throws FileNotFoundError on a clean machine
            credential.get_token('https://storage.azure.com')  # throws CLIError if token not available and
                                                               # throws AdalError if authentication has expired
        except (FileNotFoundError, CLIError, AdalError):
            # Azure CLI token is not available. Perform interactive authentication to create it.
            # This is equivalent to running "az login".

            # get_default_cli() is required when running on a clean machine.
            get_default_cli()

            # async_persist=False will cause credentials cache to be flushed to disk immediately (instead of waiting
            # for program exit).
            print('Please complete the login process in the web browser.')
            profile = Profile(async_persist=False)
            profile.find_subscriptions_on_login(
                interactive=True,
                username=None,
                password=None,
                is_service_principal=False,
                tenant=None,
            )
            print('Done.\n')
            credential, _ = get_azure_cli_credentials()

        return credential
```

Regarding recent updates, I'm not sure exactly what `DefaultAzureCredential` does, though it seems like a simpler solution to the second point above?

**Comment by efiop** [comment]
@friggog It would be great to see if there are any other tools that support that. For example `rclone`?

**Comment by friggog** [comment]
I'm not aware of any similar open source tools that do this kind of auth with Azure Blob Storage

Trying out the latest version (2.0.3) and it seems like most issues are resolved by DefaultAzureCredential! SPA on devops CI isn't discovered automatically using DefaultAzureCredential, but is easy to set up in my case - might be nice for this to be automatic, but not a big deal.

The only change that _may_ be required is adding an argument to the DefaultAzureCredential constructor to allow interactive login?
`DefaultAzureCredential(exclude_interactive_browser_credential=False)` 
I have CLI credentials cached on my machine so it 'just works' but I'm not sure how this would play out on a fresh machine (where the above snippet would open the browser and cache them automatically).

Also the docs for azure remotes are out of date:
![image](https://user-images.githubusercontent.com/6437437/110109669-aff3d300-7da5-11eb-9ad1-ea9ad5fc5c36.png)
