### ISSUE TITLE
Switch to using etag from md5 for google storage dependencies

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#5527]
In this way, it appears to be that we don't support composite objects due to they don't have an attached md5 hash: https://cloud.google.com/storage/docs/composite-objects#metadata

> Composite objects do not have an MD5 hash metadata field.

I don't know how breaking the transition would be, though 2.0 seems like the best place to target considering it won't take much effort to switch those in the codebase. Related #5500

**Comment by efiop** [comment]
@isidentical `--external` workflow is experimental and broken for gs already anyway, so we can indeed just switch to etag right now or later. The issue might be that etag is not preserved for `copy` operation (s3 does preserve it), which will mean that we are better off just dropping `--external` support for gs outputs for good.

**Comment by dberenbaum** [comment]
If you do this, please reference it in https://github.com/iterative/dvc.org/issues/2228. Thanks!

**Comment by isidentical** [comment]
Just verified that etag is indeed not preserved on copies.
```py
import secrets
from pprint import pprint
from gcsfs import GCSFileSystem

fs = GCSFileSystem()
bucket = 'batuhan-test/'
folder = bucket + secrets.token_hex(12) + '/'
with fs.open(folder + 'foo', 'w') as stream:
    stream.write('bruh')
fs.copy(folder + 'foo', folder + 'bar')

foo_etag = fs.info(folder + 'foo')['etag']
bar_etag = fs.info(folder + 'bar')['etag']
print(f'{foo_etag = } {bar_etag = }')
```

I'll drop support for external outputs on gs then.

**Comment by efiop** [comment]
@isidentical Sounds good! Thanks for the research!
