### ISSUE TITLE
pre-commit pre-push hook fails asserting dependency missing

### ISSUE THREAD

**Issue by WarrierRajeev** [iterative/dvc#5533]
# Bug Report
### In pre-commit `rev:2.0.0a3`
During `git push` : 
```ERROR: failed to push data to the cloud - URL 'gs://<bucket-name>/<folder>/' is supported but requires these missing dependencies: ['gcsfs']. Please report this bug to <https://github.com/iterative/dvc/issues>. Thank you!```
### In pre-commit `rev:1.11.16`
During `git push` : 
```ERROR: failed to push data to the cloud - URL 'gs://<bucket-name>/<folder>/' is supported but requires these missing dependencies: ['google-cloud-storage']. Please report this bug to <https://github.com/iterative/dvc/issues>. Thank you!```

## Description

`dvc push` works but pre-push hook fails.
I did pip install in both cases and still the same result.

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.11.16 (pip)
---------------------------------
Platform: Python 3.8.8 on Linux-5.4.0-66-generic-x86_64-with-glibc2.10
Supports: gs, http, https
Cache types: hardlink, symlink
Caches: local
Remotes: gs
Repo: dvc, git
```

**Comment by pmrowla** [comment]
Hi @WarrierRajeev 

Did you configure the `additional_dependencies` section in your `.pre-commit-config.yaml`? pre-commit uses it's own virtual env which is separate from your regular dvc environment, so you have to also tell pre-commit which additional remote dependencies to install.

If you take a look at the example in our docs: https://dvc.org/doc/command-reference/install#using-the-pre-commit-tool, your configuration needs an entry like:
```yaml
      - id: dvc-pre-push
        # use s3/gs/etc instead of all to only install specific cloud support
        additional_dependencies: ['.[gs]']
```

**Comment by WarrierRajeev** [comment]
Sorry I completely missed that! I checked and it works now. Thank you for the quick response!
This is slightly misleading in the docs:
>you can either use `dvc install --use-pre-commit-tool` or add these entries by hand:
Might want to rephrase there or add another line.
Anyway, Thank you :))
