### ISSUE TITLE
s3: allow switching regions / signature versions

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#5555]
`boto` supports switching to different regions and using different signature versions (like v2 instead of v4, though only for certain regions). We only use the defaults and set the signature version to `s3v4` but that might not always be the wanted case. [Here](https://discord.com/channels/485586884165107732/485596304961962003/816735883629559870) is a support request which gets a region mismatch error. I think we should allow users to change their regions / signature versions by `remote modify .

**Comment by isidentical** [comment]
It appears to be that we already support different regions https://github.com/iterative/dvc/blob/70f4c44ec6711a9344cb0d34bbd0bab7e88a0489/dvc/fs/s3.py#L36 so we only have to add an option for changing the signature version.

**Comment by pmrowla** [comment]
Related: https://github.com/iterative/dvc/issues/5660

Looks like some of the S3-compatible storages don't take `s3v4` as well

**Comment by isidentical** [comment]
We probably are going to just drop this off (hard coded signature_version) when switching to s3fs

**Comment by isidentical** [comment]
Closing as per s3fs is landed.
