### ISSUE TITLE
git hook that automates "dvc commit" before "git commit"

### ISSUE THREAD

**Issue by ThyrixYang** [iterative/dvc#5572]
The existing commit hook just "automates dvc status before git commit when needed", so we should add the changed directory manually.
I suggest adding a hook that automates "dvc commit" before "git commit" which may be more convenient in some cases. For example, this will make git plugins in text editors like vscode work smoothly with dvc.

I'm aware that this would be less efficient, but it's more intuitive and aligns with git.

**Comment by pmrowla** [comment]
The reason the current DVC pre-commit hook only runs `dvc status` is that if the repo state isn't up to date, there are two potential reasons that require two different actions be taken:

- In some scenarios the user may need to run `dvc repro` to update the data in the repo
- In other scenarios the user may need to run `dvc commit` to commit the existing data in the repo

It is not really obvious to DVC which action it should take, so it's left up to the user.

If you know for sure that the behavior you will always want is `dvc commit` and not `dvc repro`, you can always just write your own simple shell script which calls `dvc commit` to use as a git hook.

**Comment by ThyrixYang** [comment]
@pmrowla I think it would be better if such script is provided in the install and we can choose the needed behavior when we install the hook
