### ISSUE TITLE
Numer of jobs for dvc repro

### ISSUE THREAD

**Issue by BMarcin** [iterative/dvc#5578]
Hi! I'm using `dvc repro --pull` command for my repro pipeline in CI/CD. I think that a nice feature to have there would be a specified number of jobs to pull the data from a remote. It should work the same way as it works with `dvc pull -j 12`, so my suggestion is to have at the end a command `dvc repro --pull -j 12` that reproduces the whole pipeline with data pulling with a specified number of jobs.

Thanks!

**Comment by efiop** [comment]
Hi @BMarcin You could use `dvc remote modify myremote jobs 12` to set it in the config. `--jobs` for `repro` might get confused with repro parallelization. Btw, do you expect `-j 12` to start pulling data for the whole pipeline in parallel? Or just for a specific pipeline stage but with 12 workers? If the former, then that depends on repro parallelization, which is not supported yet.

**Comment by BMarcin** [comment]
I expected it to pull the data from a remote for specific stage using 12 workers. Thanks a lot for a tip to modify my remote 😊!
