### ISSUE TITLE
metrics show/diff: UnicodeEncodeError: 'ascii' codec can't encode character '\u2014'

### ISSUE THREAD

**Issue by gcoter** [iterative/dvc#5591]
# Bug Report

## Description

I have an encoding error on one of the remote server I use. I think it is linked to the default encoding which is configured on this machine. But I wanted to raise this issue just in case you didn't know that for some particular configuration, displaying metrics can fail. The problematic character is `—`, which is used when a metric value is missing. For the same project, `dvc metrics show` and `dvc metrics diff` display it normally on my local dev machine but on the remote server it fails with the encoding error.

### Reproduce

Basically, take a machine (or a docker container, see the image I used in the next section) with ascii encoding being used for the console and run `dvc metrics show` or `dvc metrics diff` in a context in which a metric value is missing.

For instance, make two metric files with different metric names. If you run `dvc metrics show`, it will try to display something like this:

```console
                                 Metric Name 1     Metric Name 2
metric_file_1.json               0.15833           —          
metric_file_2.json               —                 0.98103
```

If the default encoding is ascii, this will fail.

### Expected

I would expect the command to work in all contexts. For instance, the `—` character could be replaced with `-` or `NA` if it cannot be displayed.

### Environment information
I run my code in a docker container based on `nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04`

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.0.3 (pip)
---------------------------------
Platform: Python 3.6.12 on Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with-debian-stretch-sid
Supports: hdfs, http, https, ssh
Cache types: hardlink, symlink
Cache directory: overlay on overlay
Caches: local
Remotes: ssh
Workspace directory: overlay on overlay
Repo: dvc, git
```

**Additional Information (if any):**

```console
$ dvc metrics show --verbose
Traceback (most recent call last):
  File "/opt/conda/envs/my-env/lib/python3.6/site-packages/dvc/logger.py", line 136, in emit
    msg, file=self.stream, end=getattr(self, "terminator", "\n")
  File "/opt/conda/envs/my-env/lib/python3.6/site-packages/tqdm/std.py", line 619, in write
    fp.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 301: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/my-env/lib/python3.6/site-packages/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "/opt/conda/envs/my-env/lib/python3.6/site-packages/dvc/command/metrics.py", line 100, in run
    logger.info(table)
  File "/opt/conda/envs/my-env/lib/python3.6/logging/__init__.py", line 1308, in info
    self._log(INFO, msg, args, **kwargs)
  File "/opt/conda/envs/my-env/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/opt/conda/envs/my-env/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/opt/conda/envs/my-env/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/opt/conda/envs/my-env/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/opt/conda/envs/my-env/lib/python3.6/site-packages/dvc/logger.py", line 142, in emit
    self.handleError(record)
  File "/opt/conda/envs/my-env/lib/python3.6/site-packages/dvc/logger.py", line 129, in handleError
    raise LoggingException(record)
dvc.logger.LoggingException: failed to log <LogRecord: dvc.command.metrics, 20, /opt/conda/envs/my-env/lib/python3.6/site-packages/dvc/command/metrics.py, 100
```

I cannot show the whole log because it contains confidential metrics but I think that with these information you will be able to understand where is the issue in the code of DVC. Otherwise, don't hesitate to ask me :wink:

**Comment by skshetry** [comment]
@gcoter, could you please share more information about the docker container, and why is it running on `ascii` encoding?

`print` has the same behaviour with ASCII encoding, if you try to print other Unicode characters. If it's in your control, I'd suggest you use another `utf-8` encoding or set `PYTHONIOENCODING=utf-8` envvar inside docker. 

Here, the change is simple as we could detect them easily, but it might not always be the case (considering we have some big changes coming in the CLI/UI). What if the metrics themselves are in the unicode?

**Comment by gcoter** [comment]
Hi @skshetry, `PYTHONIOENCODING=utf-8` did solve the problem! I don't know why ascii is being used by default, but I will use your trick :slightly_smiling_face: Thank you

**Comment by iesahin** [comment]
I observed this error in one of our Katacoda containers as well. Related with iterative/katacoda-scenarios#55

This happens when `LOCALE` is not set to some `UTF-8` 

```
~/example-get-started$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

when I set 

```
export LANG=C.UTF-8
```

I don't get this error. 

You can get possible values with

```
locale -a
```

and add all locales on a Debian/Ubuntu container with 

```
apt install locales-all
```

This may be a more general fix than setting `PYTHONIOENCODING`. 

@gcoter

**Comment by gcoter** [comment]
Thank you @iesahin for the fix, I think it is indeed more general :slightly_smiling_face:
