### ISSUE TITLE
ERROR: unexpected error - list.remove(x): x not in list, if I execute "dvc diff HEAD~",  after  dvc version is updated from 1.1.15 to 2.0.5

### ISSUE THREAD

**Issue by arrowkato** [iterative/dvc#5597]
# Bug Report

ERROR: unexpected error - list.remove(x): x not in list, if I execute "dvc diff HEAD~", after dvc version is updated from 1.1.15 to 2.0.5

## Description

"dvc diff" command is wrong in version 2.0.5.

### Reproduce

Step list of how to reproduce the bug

1. I made dvc repository in 1.11.15 and push data into GCS.
2. "pip install dvc --upgrade"
3. Create a file in a directory named foo managed by dvc
4. "dvc add foo"
5. "dvc diff HEAD~"
6. shown "ERROR: unexpected error - list.remove(x): x not in list"

### Expected

"dvc diff" command execute as well as 1.11.15.
looks like below.
```
Added:
    bar.txt
```

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

```console
DVC version: 2.0.5 (pip)
---------------------------------
Platform: Python 3.7.9 on Darwin-19.6.0-x86_64-i386-64bit
Supports: gs, hdfs, webhdfs, http, https
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s2
Caches: local
Remotes: gs
Workspace directory: apfs on /dev/disk1s2
Repo: dvc, git
```

**Additional Information (if any):**

part of error message of ```dvc diff --verbose HEAD~``` is below.
```
Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "<reposistory>/venv/lib/python3.7/site-packages/dvc/command/diff.py", line 138, in run
    self.args.a_rev, self.args.b_rev, self.args.targets
  File "<reposistory>/venv/lib/python3.7/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "<reposistory>/venv/lib/python3.7/site-packages/dvc/repo/diff.py", line 79, in diff
    deleted.remove(renamed_item["path"]["old"])
ValueError: list.remove(x): x not in list
```

version 2.0.0 is wrong too.
version 1.11.16 is correct.

Thanks.

**Comment by pmrowla** [comment]
Just to confirm, if you use the actual git revision for the previous commit instead of `HEAD~` shorthand, do you still get the same error?

**Comment by arrowkato** [comment]
Yes. I executed ``` dvc diff REVISION_1 ``` .
REVISION_1 is git revision like 2ef5b363692e27c786e0fee85dc1b1cb93e32ba5 and it shows the same revision of "HEAD~".

I still got the same error. ```ERROR: unexpected error - list.remove(x): x not in list```

I alse executed ``` dvc diff  REVISION_2  REVISION_1 ``` .
REVISION_1 is the same as HEAD~. 
REVISION_2 is thea same as HEAD.

I still got the same error too. ```ERROR: unexpected error - list.remove(x): x not in list```

regards.

**Comment by skshetry** [comment]
@arrowkato, would it be possible to install the following patched dvc version?
```console
$ pip install git+https://github.com/skshetry/dvc.git@fix-5597#egg=dvc[gs,hdfs,webhdfs]
```

Just want to make sure it's fixed (and, if there aren't other bugs at all). Please verify, and then we'll merge it.

Please also take a look at #5652 for the code changes as well. Thanks.

**Comment by arrowkato** [comment]
I made sure it was fixed, after I installed fix-5597 in dvc 2.0.5.

```
$ dvc diff HEAD
+----------------------------------------------------------+
|                                                          |
|             Update available 2.0.5 -> 2.0.6              |
|                Find the latest release at                |
|     https://github.com/iterative/dvc/releases/latest     |
|                                                          |
+----------------------------------------------------------+

Added: 
   <shown difference of my model.dvc>
.....
```
```dvc diff HEAD~``` command had been fixed as well.

Thank you for your support!

**Comment by skshetry** [comment]
@arrowkato, would it be possible to show the non-redacted `Rename` entries section if possible (or, at least an obfuscated one)?

**Comment by skshetry** [comment]
Thanks, @arrowkato, Could you please confirm if it's the case with files of the same hashes being renamed?

**Comment by arrowkato** [comment]
I don't know much about your question, but the following is exactly what I wanted.
The specific confirmation procedure is written below.

# step0 directories
```
repository_root
+-foo.dvc
+- foo
     +- bar1.txt
```
Git hash : XXXXXXXXXX (= HEAD)

# step1 add and edit files in foo directory
- Add bar2.txt in foo directory
- Edit bar1.txt

```
repository_root
+foo.dvc
+foo
     + bar1.txt
     + bar2.txt
```

# step2 register my change 

I executed "dvc add foo" command.

# step3 confirm difference

I executed "dvc diff HEAD" command.

```bash
$ dvc diff HEAD

Added:
    bar2.txt

Modified:
    foo/
    foo/foo1.txt
```

Is it an answer to your question?

**Comment by skshetry** [comment]
@arrowkato, would it be possible for you to paste the output of the following command:
```console
$ dvc diff HEAD~ --show-hash --show-json
```

They only contain file paths and hashes, so it is safe for you to share the diff contents. I am mostly interested in `Renamed` entries.

**Comment by arrowkato** [comment]
Command
```bash
$ dvc diff HEAD~ --show-hash --show-json
```

Result
```
{"added": [{"path": "foo/bar2.txt", "hash": "d9a3fdfc7ca17c47ed007bed5d2eb873"}], "deleted": [], "modified": [{"path": "foo/", "hash": {"old": "c71e98eaf3493345c4b1bfb5da7c4229.dir", "new": "1ded2bd87d5f4cfa0970034508d1e029.dir"}}, {"path": "foo/bar1.txt", "hash": {"old": "5951e59c055402dc46d160d6e7f8a1ae", "new": "29dcae71cfa76a1c54601f8356a8ba02"}}], "renamed": [], "not in cache": []}
```

The Contenxt of "bar1.txt" file is changed. However, file name of "bar1.txt" is not changed.
"bar2.txt" is an additional file.  ​
There are no files whose phial names have been changed.
