### ISSUE TITLE
pull: not pulling all files after upgrade to 2.0

### ISSUE THREAD

**Issue by jotsif** [iterative/dvc#5612]
# Bug Report

## Description

`dvc pull` ignoring some dependencies in dvc pull

### Reproduce

Git clone a repo with files tracked by dvc. Upgrade to DVC 2.0. run dvc pull and see files missing (dependencies).

Downgrade to dvc pre 2.0. (I just tried 1.11.16)

Run dvc pull and get missing files.

### Expected

Dvc pull with recent versions should get all tracked dependencies.

### Environment information
```
⟩ dvc doctor
DVC version: 2.0.5 (pip)
---------------------------------
Platform: Python 3.9.2 on macOS-11.2.1-arm64-arm-64bit
Supports: http, https, s3
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Additional Information (if any):**

We have a multi dvc.yaml environment (same git repo with four different model pipelines tracked by dvc). Dvc pull missed *dependencies*, i.e. files just going into to the `deps` part of two out of four of the pipelines.

**Comment by skshetry** [comment]
@jotsif, could you please provide more information? One particular change that could affect the behaviour of the pull is that `dvc` will not traverse through any directories that are git-ignored. Is that the case here?

**Comment by jotsif** [comment]
Hi @skshetry! Yes that is exactly the issue. They are in a git ignored directory.

**Comment by skshetry** [comment]
@jotsif, would it be possible to unignore them?

**Comment by jotsif** [comment]
Yes :) If this intentional we will change it like that

**Comment by skshetry** [comment]
@jotsif, if you have strong usecase for it, feel free to share it in https://github.com/iterative/dvc/issues/5396. Thanks. 🙂
