### ISSUE TITLE
exp queue: command for managing queues

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc#5615]
AFAICT, currently it's not possible to manage the experiment queue created by `dvc exp run --queue`. We can create experiments, but cannot remove them or change their order. 

I'd like to have a `dvc exp queue` command to list, modify, save and restore queues. Experiment queues, along with the parallel jobs, seem to be an important aspect of future DVC. 

`dvc exp queue --add` can work identically with the current `dvc exp run --queue`. `--add` may be the default command and the users may write `dvc exp queue -S myparam=3 -n exp-1 python3 train.py` instead of `dvc exp run --queue`. 

`dvc exp queue --list` may list jobs and their state. (Run, Waiting, Error)

`dvc exp queue --remove` may remove a job from the waiting list. 

`dvc exp queue --save` can save a list of commands to a file. (Think about moving experiments to another workstation.)

`dvc exp queue --restore` can restore such a list from a file. 

I didn't check the implementation but these should be pretty straightforward to add to the experiment management.

**Comment by pmrowla** [comment]
As you noted, work related to queuing/running/managing experiments is something we will get to in the long term, but in the short term this is p3 for now.

**Comment by dberenbaum** [comment]
@iesahin Can we modify the name of this issue to something more general? I can never find it when I want to 😄 .

**Comment by iesahin** [comment]
You can update the title to something easier to remember :) @dberenbaum
