### ISSUE TITLE
s3: s3fs migration

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#5622]
Roadmap;
- [x] A basic `S3FileSystem` class like the rest of providers
- [x] Passing the bare minimum tests (apparently moto doesn't work well with aiobotocore when used in wrapper mode, aio-libs/aiobotocore/issues/755, so we probably would have to rewrite the test remote using the server mode)
- [x] Porting `~/.aws/config` parsing
- [x] Permission/grant mangement
- [x] Port functional/unit tests (and drop the redundant ones)
- [x] etag-preserving server side copy implementation (possibly by overriding the s3fs's copy method while preserving the underlying logic) (dask/s3fs/pull/441)
- [x] support [exception unrolling](https://github.com/iterative/dvc/blob/dcc55aa645c361a865d24df33f6989bb15e13f24/dvc/logger.py#L153-L157) (dask/s3fs/pull/443)
- [x] s3fs doesn't support 3.6 (dask/s3fs/issues/445) [perhaps we can have a fork for 3.6 only and have it on pypi until we also drop the support, EOL is in 9 months]
- [ ] try to setup dvc bench
- [ ] end to end performance testing
- [ ] Collecting issues regarding s3 on the bug tracker and checking whether they still apply or not

Future;
- [ ] should we continue to wrap boto-based exceptions (e.g NoCreds/NoBucketFound etc)
- [ ] Look into whether we can preserve / port the `walk_files(prefix=)` optimization

**Comment by isidentical** [comment]
It seems like the naive approach on s3fs (using the FSSpecWrapper without any additions) is about 1.5-3x slower than the current master of simple push/pull/status

Some stats regarding API calls;
```
       master         s3fs
GET     160            103
PUT      81             89
HEAD    132            278
POST      2              3
        375            473
```

Looking at the possible optimizations :eyes:

**Comment by isidentical** [comment]
Here are some new numbers (real timings instead of request amounts), it appears to be that pull of small files is extremely slow (25x);
https://gist.github.com/isidentical/e0c33a5db41aca10509fcb5c95489247

**Comment by isidentical** [comment]
I've re-implemented the push/pull logic in async way to see how much it affects, and it appears to be that this made the pull only 2x slower (compared to 9x slower in the previous version) though the push is now 4x slower (instead of 3x);

|                   | master    | s3fs      | s3fs with download/upload APIs | ASYNC s3fs with download/upload APIs |
|-------------------|-----------|-----------|--------------------------------|--------------------------------------|
| push (single big) | 8.30 min  | 12 min    | 9.20 min                       | 9.15 min                             |
| push (10k small)  | 5.40 min  | 24 min    | 15.20 min                      | ~22.30 min                           |
| pull (single big) | 1.34 min  | 10.50 min | 3 min                          | 2.30 min                             |
| pull (10k small)  | 11.40 min | ~4 hours  | ~1.5 hours                     | 22 min                               |

I am not sure about how much time we want to allocate on this, though I'll give it a shot on implementing a way that combines multiprocessing (not threading) + async and try to see with that. It appears fsspec instances care about [serialisability](https://filesystem-spec.readthedocs.io/en/latest/features.html#serialisability) but I am not sure about the rest of the dvc code (@efiop mentioned some parts are not serializable, yet IIRC). We might need to create a filesystem per process to avoid some potential problems.

**Comment by efiop** [comment]
@isidentical Another option might be to for now convert our current implementation to comply with fsspec, so that we could play around with swapping it for s3fs a bit later, after we fully migrate the rest of fs/*.py to fsspec.

**Comment by dberenbaum** [comment]
Would this be a good use case to consider merging to a non-master branch to avoid needing to convert the current implementation?

**Comment by isidentical** [comment]
We decided to put s3fs migration on hold, and use a temporary sync fs like our current S3FileSystem for the time being. There are multiple issues present, including py3.6 being not supported, pull/push on big files are 0.10x~ slow, pull/push on directories with huge amounts of small files are 2-3x slow (at best, with an async pull/push system).

**Comment by isidentical** [comment]
With #5683's approach now push/pull are the same (as well as status / gc), will do the same tests with partial data and copy on big files...
https://gist.github.com/isidentical/c2c97798681ed574525017b25009cec8

**Comment by martindurant** [comment]
Can you show me the code for *non-async* s3fs up/downloads, to see if there's any obvious improvement I can see?

**Comment by isidentical** [comment]
> Can you show me the code for non-async s3fs up/downloads, to see if there's any obvious improvement I can see?

The code was actually just a wrapper around `fs.put_file`/`fs.get_file` and then we basically submit those calls to the thread pool (`func` below refers to one of `put_file`/`get_file`)
https://github.com/iterative/dvc/blob/4f8cfc025b429e2e0c31c3152f380940a3b6318b/dvc/remote/base.py#L382-L389

and the async version of that code looked like this;
```py
    def _create_async_tasks(self, executor, jobs, func, pbar, file_plans):
        fails = 0
        jobs *= 4
        file_plan_iterator = iter(file_plans)

        def create_taskset(amount):
            return [
                func(from_info, to_info, name)
                for from_info, to_info, name, _ in itertools.islice(
                    file_plan_iterator, amount
                )
            ]

        async def runner(func=func, file_plans=file_plans):
            fails = 0
            tasks = create_taskset(jobs)
            while tasks:
                fails += sum(await asyncio.gather(*tasks))
                pbar.update(len(tasks))
                tasks = create_taskset(jobs)
            return fails

        fails = asyncio.run(runner())
        self.fs.invalidate_async_fs()
        return fails
```
(invalidate_async_fs just removes the cached fsspec instance, since the event loop is closed we need to re `_connect` with it)

**Comment by martindurant** [comment]
OK, so the standard `get` and `put` will actually work on whole lists of files, using `asyncio.gather` internally. You should not need to submit anything to an executor, nor throttle the number of jobs
```
from_list, to_list = get_all_files()  # from your iterator of create_taskset
s3.put(from_list, to_list)
```
Similarly, when in an async context, you can
```
await s3._put(from_list, to_list)
```
and not

**Comment by isidentical** [comment]
Let's close this and track the remaining stuff (aioboto issue etc) in a separate issue #5969

**Comment by efiop** [comment]
@isidentical There seem to be more checkboxes though, are those not needed anymore?

**Comment by isidentical** [comment]
> @isidentical There seem to be more checkboxes though, are those not needed anymore?

updated, the only missing is the issue triaging. I'll be doing that tomorrow, and try to traverse issue tracker for all s3 issues :eyes:
