### ISSUE TITLE
exp run: unexpected error when git user/email has not been configured

### ISSUE THREAD

**Issue by UrszulaCzerwinska** [iterative/dvc#5627]
# Bug Report

## Description

After running a pipeline (dvc run) with sucess, using experiments with modiciation params leads to the error:
`ERROR: unexpected error - "config value 'user.name' was not found`

### Reproduce

see the google collab notebook:
https://colab.research.google.com/drive/1xMMKMwI22Wws3hrSH2rhwAkrLhCH1mnn?usp=sharing

in short
- dvc run ... OK
- modify params 
- dvc repro ... OK
- dvc exp run ERROR

### Expected

Running experiment

### Environment information

```console
DVC version: 2.0.5 (pip)
---------------------------------
Platform: Python 3.7.10 on Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Supports: hdfs, http, https, s3
Cache types: hardlink, symlink
Cache directory: overlay on overlay
Caches: local
Remotes: None
Workspace directory: overlay on overlay
Repo: dvc, git
```

**Comment by pmrowla** [comment]
`exp run` will generate hidden git commits, which requires that git user/email settings be configured. You likely do not have any user configured for git on collab.

Typically, this is done with
```
$ git config --global user.name <name>
$ git config --global user.email <email>
```

**Comment by pmrowla** [comment]
On the DVC UI side, we can do a better job of catching this exception in the scm backends and outputting a better error message

**Comment by pmrowla** [comment]
Re-opening this until the UI issue is addressed

**Comment by casperdcl** [comment]
@pmrowla are we missing some docs about this in https://dvc.org/doc/command-reference/exp/run? Just had a CML Learn meetup where a CI workflow was failing do to missing `git config --global user.(name|email)`.

**Comment by pmrowla** [comment]
It should probably be documented somewhere, but I'm not sure if belongs in the command reference. This is really specific to CI use cases, since any other typical user git installation will force the user to configure `user.name` and `user.email`

**Comment by daavoo** [comment]
I'm not sure why but this workflow (https://github.com/iterative/dataset-dvc-issues/blob/main/.github/workflows/fetch_issues_weekly.yaml) uses `dvc exp run` and works, but I'm not setting user.email / user.name

**Comment by pmrowla** [comment]
IIRC github sets some placeholder value in actions based on the token used? @casperdcl was the issue you are talking about in github actions or a different CI platform (gitlab?)

**Comment by casperdcl** [comment]
yes [this commit](https://github.com/iterative/dvc-learn-project/commit/8d453d2ff3557507e263dc6cda0a69fa4504a1b1#comments) fixed [this failure](https://github.com/iterative/dvc-learn-project/runs/4240686851?check_suite_focus=true)

**Comment by daavoo** [comment]
> yes [this commit (adding `user.name|email)`](https://github.com/iterative/dvc-learn-project/commit/8d453d2ff3557507e263dc6cda0a69fa4504a1b1#comments) fixed [this failure (GHActions DVC Learn example repo)](https://github.com/iterative/dvc-learn-project/runs/4240686851?check_suite_focus=true)

Isn't the error coming from `dvc get`?

**Comment by casperdcl** [comment]
idk - if so would that be a separate issue?
