### ISSUE TITLE
run: non-cache metric is not autostaged 

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#5635]
I am running a script producing a git tracked metrics file like below. Everything works fine but `metrics.json` is not autostaged.

```python
repo.config["core"]["autostage"] = True
repo.run(
    name="evaluate",
    cmd="python evaluate.py model.pkl",
    deps=["evaluate.py", "model.pkl"],
    ...
    metrics_no_cache=["metrics.json"],
)
```

Even if I stage `metrics.json` manually changes to it caused by `dvc repro` won't be staged later:

```bash
git add metrics.json
git commit -m "..."

vim evaluate.py  # Change how metrics are calculated  
dvc repro
git status  # metrics.json changes are unstaged here
```

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.0.5 (pip)
---------------------------------
Platform: Python 3.9.0+ on Linux-5.4.0-66-generic-x86_64-with-glibc2.31
Supports: http, https
```

**Edit.** Added a part about `dvc repro`.

**Comment by Suor** [comment]
Also, happens with `.reproduce()`.

**Comment by skshetry** [comment]
I think this is expected, non-cached means that it may or may not be tracked (including in git).

**Comment by pmrowla** [comment]
Yeah, it's a bit unclear what we should be doing here, since uncached outs don't necessarily have to be git-tracked at all.

We could check to see if the out is already git-tracked, and then only autostage them if they were already tracked (basically just `git add --update` for uncached outs).

**Comment by Suor** [comment]
> I think this is expected, non-cached means that it may or may not be tracked (including in git).

Do you treat other non cache outputs the same?

**Comment by Suor** [comment]
Played a bit more with it. The `.reproduce()` not staging changes is the most annoying.
