### ISSUE TITLE
push: s3 api not working with ibmcloud cos

### ISSUE THREAD

**Issue by gabriellm1** [iterative/dvc#5637]
# Bug Report

## Description

Basically, I'm trying to set remote storage with DVC and IBM Cloud Object Storage.  I followed DVC docs and since IBM COS works with S3 API, I set everything just like the docs recommends, with .aws/credentials with hmac credentials. When running `dvc push` I get `ERROR: unexpected error - An error occurred (404) when calling the ListObjects operation: Not Found`

### Reproduce

*.dvc/config*
`
[core]

    remote = dvc-remote

['remote "dvc-remote"']

    url = s3://bucketname/

    endpointurl = https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints
`

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.0.5 (pip)
---------------------------------
Platform: Python 3.7.3 on Darwin-20.3.0-x86_64-i386-64bit
Supports: All remotes
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Comment by efiop** [comment]
@gabriellm1 Are you able to use `aws` CLI with that? If you are not - please first make sure that things like `aws s3 ls s3://bucket/path` and basic upload/download works.

**Comment by efiop** [comment]
Closing as stale
