### ISSUE TITLE
Hadoop with Kerberos authentication

### ISSUE THREAD

**Issue by TM-Rin** [iterative/dvc#5645]
Greetings, fellow developers.
I am requesting adding a feature to accept `kerb_ticket` path while connecting to HDFS.
[PyArrow docs](http://arrow.apache.org/docs/python/generated/pyarrow.fs.HadoopFileSystem.html#pyarrow.fs.HadoopFileSystem)
Right now DVC does not use custom kerberos ticket paths and connecting with NULL ticket.

**Comment by pared** [comment]
Seems like we should acknowlege the `kerb_ticket`, probably [here](https://github.com/iterative/dvc/blob/6026573860de2e395e4a7cdc3ab4b1739823af83/dvc/fs/hdfs.py#L98)

**Comment by pared** [comment]
Related: #2283

**Comment by naveen24691** [comment]
I have gone through the issues and related issues. It seems to be straight forward. I have raised a PR https://github.com/iterative/dvc/pull/5809  for this. Let me know if you are still planning to integrate this in the main branch.
