### ISSUE TITLE
push: remote.jobs in .dvc/config is ignored

### ISSUE THREAD

**Issue by lueisert** [iterative/dvc#5647]
# Bug Report

## Description

I originally had the problem that dvc push in combination with a webdavs remote lead to connection problems. The problem could be solved by using
`dvc push -j4`
because the webdav server was not able to handle the 4*cpu_cores spawned by the cluster.
However, if I add the restriction on the job number with `dvc remote modify datashare jobs 4` to .dvc/config; the error is back.
.dvc/config looks like this
```
[core]
    remote = datashare
['remote "datashare"']
    url = ...
    user = ...
    jobs = 4
```

I therefore assume that the jobs field is ignored by the command.

## Solution?
In dvc/fs/base.py I found
```
    def jobs(self):
        return (
            self.config.get("jobs")
            or (self.repo and self.repo.config["core"].get("jobs"))
            or self.JOBS
        )
```
If "self.repo.config" corresponds to .dvc/config: the "jobs" keyword seems to be wrongly searched for under the ["core"] keyword.

**Output of `dvc doctor`:**

```
DVC version: 2.0.6 (pip)
---------------------------------
Platform: Python 3.7.6 on Linux-4.12.14-122.57-default-x86_64-with-SuSE-12-x86_64
Supports: http, https, webdav, webdavs
Cache types: hardlink, symlink
Cache directory: gpfs on ...
Caches: local
Remotes: webdavs
Workspace directory: gpfs on ...
Repo: dvc, git
```

**Comment by pared** [comment]
@lueisert Thank you for reporting the issue!

I see 2 problems here:
1. The reason for failing `push`:  dvc seems to not respect `remote.jobs` value:

```python
def test_push(tmp_dir, scm,dvc, local_remote, mocker):
    from dvc.main import main
    tmp_dir.dvc_gen({"data": {"foo": "content"}}, commit="add data")

    process_mock = mocker.spy(dvc_module.remote.base.Remote, "_process_plans")
    main(["push", "-j", "4"])
    # checking `jobs` arg
    assert process_mock.call_args[0][6] == 4

    shutil.rmtree(local_remote.url)
    assert main(["remote", "modify", "upstream", "jobs", "4"]) == 0

    main(["push"])
    # fail
    assert process_mock.call_args[0][6] == 4
```

2. The `core.jobs` config option is not working (thanks @lueisert for pointing that out) - there is no documentation for that config option, and it seems that it actually cannot be set with `dvc config core.jobs {X}`:

```bash
(dvc3.7) repo git:master ✩  ❯ dvc config core.jobs 4
ERROR: configuration error - config file error: extra keys not allowed @ data['core']['jobs']
```
Related: https://github.com/iterative/dvc/pull/4872

**Comment by pared** [comment]
Reopened #1626 To fix point 2. 
This issue should focus on fixing `remote.jobs` issue.
