### ISSUE TITLE
add: confusing interaction with gitignore'd subdirectories

### ISSUE THREAD

**Issue by mattlbeck** [iterative/dvc#5650]
# Bug Report

## Description

`dvc add` will happily complete when targeting subdirectories that appear transiently in a `.gitignore`. The tracked data has a corresponding `.dvc` file generated and appears in the cache correctly, but attempts to push to a remote is met with a silent failure, a `dvc remove` with a more vocal error, and most alarmingly a `dvc pull` deletes the data from the workspace (although it can still be found in the cache).

The behaviour is confusing and difficult to debug due to the fact that everything pretends to work or fails silently except for `dvc remove`, which was the only clue as to what was causing this.

### Reproduce

```console
$ git init
$ dvc init
$ dvc remote add -d ...
$ mkdir datadir/subdir
$ echo "data" > datadir/subdir/data.txt
$ echo "datadir/" > .gitignore
$ dvc add datadir/subdir/
$ dvc status
There are no data or pipelines tracked in this project yet. 
See <https://dvc.org/doc/start> to get started!
$ dvc push
Everything is up to date.
$ dvc remove datadir/subdir.dvc
ERROR: 'datadir/subdir.dvc' is git-ignored.
$ dvc pull
D       datadir/subdir/                                                                                                             
1 file deleted
```

### Expected

If tracking gitignored directories is not allowed, `dvc add` should fail with the same error as `dvc remove`.

I don't fully understand why adding gitignored subdirectories is not allowed however. Is the issue more that the generated '.dvc' file is transiently gitignored?

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.0.6 (pip)
---------------------------------
Platform: Python 3.7.3 on Linux-5.4.0-67-generic-x86_64-with-debian-bullseye-sid
Supports: http, https, s3, ssh
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/ubuntu--vg-root
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/mapper/ubuntu--vg-root
Repo: dvc, git
```

**Comment by pared** [comment]
Following test should fail:

```python
def test_add_ignored(tmp_dir, scm, dvc):
    tmp_dir.gen({"dir": {"subdir": {"file": "content"}}, ".gitignore": "dir/"})
    dvc.add(targets=[os.path.join("dir", "subdir")])
```

@mattlbeck 
> I don't fully understand why adding gitignored subdirectories is not allowed however. Is the issue more that the generated '.dvc' file is transiently gitignored?

Its ok to add `.gitignored` data to dvc - actually dvc by itself makes `.gitignore` entires for added data. You are right assuming that the issue is about `.dvc` file being ignored, this is a bug.

**Comment by pmrowla** [comment]
In this case I'm not sure it's a bug, I think the initial add should maybe just fail, since the resulting `.dvc` file ends up being gitignored? We disallow ignoring `dvc.yaml` and `dvc.lock`, we should have the same rules for `.dvc` files (and it should be checked on add).

In this case, to get the add to work, we should require the user do `dvc add datadir/subdir -o subdir.dvc` so that the `.dvc` file goes in the current directory instead of in `datadir/` (so the the resulting `.dvc` path is not gitignored). Alternatively, there should be an explicit `!datadir/*.dvc` rule to unignore dvcfiles in that directory.

**Comment by efiop** [comment]
For the record: another user on mailing list is running into this.
