### ISSUE TITLE
exp remove: questions [QA]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5664]
### 1. Can't target experiments by hash

Is this by design? Is there a reason?

```console
$ dvc exp show --no-pager --sha
┏━━━━━━━━━━━━━┳━━━━━━━━━━┓
┃ Experiment  ┃ Created  ┃
┡━━━━━━━━━━━━━╇━━━━━━━━━━┩
│ workspace   │ -        │
│ dc97c59     │ 07:56 PM │
│ ├── 1fb0dbc │ 08:14 PM │
│ │ ╓ 010859c │ 08:10 PM │
│ │ ╟ eaf8980 │ 08:05 PM │
│ ├─╨ 202b744 │ 08:05 PM │
└─────────────┴──────────┘
$ dvc exp remove 1fb0dbc
ERROR: '1fb0dbc' is not a valid experiment name
```
> BTW missing period `.` after that error message.

#### 1.1 Can't target specific checkpoints

> Notice the table above shows a 3-checkpoint experiment.

```console
$ dvc exp remove 010859c
ERROR: '1fb0dbc' is not a valid experiment name
```

Is there a special reason to disallow this, or is it just a result of (1) above?

**Comment by pmrowla** [comment]
You can only remove experiments by name, it's the same as with deleting a git branch or tag (you do it by name, not by a commit SHA).

With regard to removing individual checkpoints, I'm not sure what behavior you would even expect here, since you are asking DVC to remove an individual commit from the middle of a git branch.

**Comment by jorgeorpinel** [comment]
Makes sense. So `exp remove` only deletes de custom ref? Meaning that the commits are left "dangling" (unreachable). B/c I think that's what happens when deleting branches/tags (see this [SO/a](https://stackoverflow.com/a/4528593/761963)).

And if so, do you know if `gc --all-commits` include unreachable ones?

Closing for now, thanks.

**Comment by pmrowla** [comment]
Yes the commits are left dangling until git decides to gc them (usually after 30 days iirc). dvc gc is only aware of reachable/referenced commits.

**Comment by jorgeorpinel** [comment]
Kewl. Adding some of the info to https://github.com/iterative/dvc.org/pull/2300/commits/d34e8f8ba12cb16e11529a6a771f6d9f54da5524.
