### ISSUE TITLE
Remote cache is not created

### ISSUE THREAD

**Issue by ankxyz** [iterative/dvc#5665]
# Bug Report

## Description

I configure cache - set up remote (ssh cache):

```bash
# Add ssh remote
dvc remote add ssh_remote ssh://root@server

# Configure ssh remote
dvc remote modify ssh_remote password root 
dvc remote modify ssh_remote ask_password true

# Add and configure ssh remote for cache
dvc remote add sshcache ssh://root@server:/cache/ext_deps_ssh
dvc remote modify sshcache password root
dvc remote modify sshcache ask_password true

# Add remote cache
dvc config cache.ssh sshcache
```

As result I have `.dvc/config`:

```
[cache]
    ssh = sshcache
['remote "ssh_remote"']
    url = ssh://root@server
    password = root
    ask_password = true
['remote "sshcache"']
    url = ssh://root@server:/cache/ext_deps_ssh
    password = root
    ask_password = true
```

When I create and run any pipeline, I expect all artifacts will cached remotely - on the `server`, in folder `/cache/ext_deps_ssh`.

But just local cache is created.

The same result when trying to configure gs cache.

### Environment information

**OS**: Ubuntu Linux 20.04 LTS
**Environment**: Docker
**Python version**: 3.8.2
**DVC version**: 2.0.6

**Output of `dvc doctor`:**

```
DVC version: 2.0.6 (pip)
---------------------------------
Platform: Python 3.8.2 on Linux-5.8.0-45-generic-x86_64-with-glibc2.2.5
Supports: gs, http, https, ssh
```

Thank you for advance.

**Comment by efiop** [comment]
Closing as stale.
