### ISSUE TITLE
Error when trying to add file from Google Cloud Storage under dvc control

### ISSUE THREAD

**Issue by ankxyz** [iterative/dvc#5666]
# Bug Report

## Description

I try:

```bash
dvc add gs://<bucket>/<file> --external
```

result:

```
ERROR: output 'gs:/<bucket>/<file>' does not exist
```

Note: path 'gs:/<bucket>/<file>' contains exactly one slash after `gs:`.

### Environment information

**OS**: Ubuntu Linux 20.04 LTS
**Environment**: Docker
**Python version**: 3.8.2
**DVC version**: 2.0.6

**Output of `dvc doctor`:**

```
DVC version: 2.0.6 (pip)
---------------------------------
Platform: Python 3.8.2 on Linux-5.8.0-45-generic-x86_64-with-glibc2.2.5
Supports: gs, http, https, ssh
```

Thank you for advance.

**Comment by efiop** [comment]
Hi @ankxyz !

`--external` is an advanced and experimental feature that we usually don't recommend, so could you please elaborate on your scenario, please?

As to the actual issue, are you sure that file actually exists? Could you check that with gsutil?

**Comment by efiop** [comment]
Closing as stale
