### ISSUE TITLE
checking for push before garbage collect on local cache

### ISSUE THREAD

**Issue by kumarshreshtha** [iterative/dvc#5669]
When doing `gc` without the `--cloud` option maybe we should have a feature that checks before deleting the local copy if a copy exists on the remote storage and only garbage collect if it does? 
This check is already done for instance on the `git lfs prune` command for  [git lfs](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-prune.1.ronn). I think it'll be good to have a safety check  to ensure we don't loose files this way and then we can have a `--force` behavior or something similar to forcefully remove the non-pushed files in case the user feels the need for it. 
This would really help when you have multiple users sharing a cache directory so that one user doesn't accidentally delete the files of the other user while performing a `gc`.

**Comment by jorgeorpinel** [comment]
Seems related (maybe a dupe) of #2036.

**Comment by dberenbaum** [comment]
Thanks @jorgeorpinel . Closing this in favor of that one.
