### ISSUE TITLE
VSCode extension

### ISSUE THREAD

**Issue by Gizzio** [iterative/dvc#5671]
It would be great if you develop a VSCode extension allowing manage DVC pipeline in a similar way that it allows managing git. 

---

We are working on VS Code DVC extension for Experiments, Plots and data files. If you'd like to participate in the alpha releases and/or give it a try, please contact `@ivan` on Discord. Check the [announcement](https://discord.com/channels/485586884165107732/497187456051970048/841831363157032960) here.

**Comment by courentin** [comment]
**Idea dropping:**
Something nice to have would be the ability to repro a stage from a `dvc.yaml` file directly (as weel as the ability to launch it in debug mode)

<img width="711" alt="Screenshot 2021-03-29 at 20 39 33" src="https://user-images.githubusercontent.com/12371832/112883770-fe5b6f80-90ce-11eb-8678-8db74f82c3d2.png">

**Comment by skshetry** [comment]
We are on our path to developing the VS Code extension UI for DVC - experiments, plots, data files, etc. Please ping @shcheklein (discord: @ivan) on Discord (see [here](https://discord.com/channels/485586884165107732/497187456051970048/841831363157032960)) if you'd like to give a try, and be an alpha user.
