### ISSUE TITLE
Remove all experiments in the workspace

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#5676]
Have a `dvc exp remove --workspace` command or similar to drop all experiments in the workspace. Should be equivalent to `dvc exp list --names-only | xargs dvc exp remove`. This allows users to reset their experiments workspace if they have made mistakes or were playing around with some changes they ultimately want to roll back.

Some background:
* https://discord.com/channels/485586884165107732/485596304961962003/823901428652965898
* https://github.com/iterative/dvc/issues/5553#issuecomment-791717274
* https://github.com/iterative/dvc/issues/5437#issuecomment-776861639

**Comment by gdiepen** [comment]
This indeed would be a great functionality!

One possible (very likely) outcome of running experiment is that you find this path is not worth pursuing. In that case, would like to purge all of the experiments to be able to continue with the next idea

**Comment by dberenbaum** [comment]
`dvc exp remove -A/--all-commits` might also be useful.

@pmrowla What do you think about moving up the priority of this one? The workaround is not difficult, but it's not that easy for people to find in this thread, and it seems like it's a straightforward feature to implement.

**Comment by pmrowla** [comment]
I guess we just need to be clear that by workspace here we mean all experiments based on the current HEAD right?

Regarding priority, I think it's up to you. This is an issue that anyone should be able to fix - codebase-wise, it won't actually require touching anything on the experiments internals side of things.

**Comment by dberenbaum** [comment]
> I guess we just need to be clear that by workspace here we mean all experiments based on the current HEAD right?

Right, it should match `dvc exp show`, which is described in https://dvc.org/doc/command-reference/exp/show#description:

> Only the experiments derived from the Git HEAD are shown by default


> This is an issue that anyone should be able to fix - codebase-wise, it won't actually require touching anything on the experiments internals side of things.

Yes, this could be a good opportunity for either one of the other devs or contributors.

**Comment by casperdcl** [comment]
I find the `dvc exp gc` flags a little confusing. They're mostly "keep all except" (exclusive) rather than "remove only" (inclusive). Ideally we should have both. Related #6006.

I'd prefer a new flag inverts the meaning:

```
  -w, --workspace     Keep experiments derived from the current workspace.
...
  --queued            Keep queued experiments (experiments run queue will be
                      cleared by default).
  -R, --remove/--no-keep   Inverts meaning of the above options
                           (remove rather than keep).
```

**Comment by iesahin** [comment]
Could we support `--keep` and `--remove` options, that can take
```
workspace
all-branches
all-tags
all-commits
<specific-experiment-id>
```
as parameters.

So `dvc exp gc --keep workspace` will be identical with the current `dvc exp gc --workspace` and `dvc exp gc --remove exp-abc123` will remove that. 

We can also use `dvc exp remove` for this. `gc` can just be a flag to `remove`, that basically says "run dvc gc after removing these to clean up the cache" So ınstead of `dvc exp gc --workspace && dvc gc --workspace`, the user can run `dvc exp remove --keep workspace --gc`.

@efiop @dberenbaum @pmrowla @karajan1001

**Comment by dberenbaum** [comment]
> I'd prefer a new flag which inverts the meaning:

Is this the same functionality as the proposed `dvc exp remove -w`? Is the point that you would prefer `dvc exp gc -w -R` to `dvc exp remove -w`? I agree that `gc` can be confusing, which is why I suggested to add this option to `remove` instead.

I'd say that introducing `gc -R` or `gc --keep/--remove` is a separate feature request since it does more than what's requested here, and `gc` applies to more than experiments. For example, would `dvc exp gc -R/--remove` ever make sense for all branches or tags? I think the ideas make sense, but I don't want them to block the simpler feature request here.

If the `--workspace` option seems awkward in `dvc exp remove`, we can simply implement `dvc exp remove --all` and save the distinctions between `--workspace` and similar options to another feature request.

**Comment by iesahin** [comment]
> Is this the same functionality as the proposed `dvc exp remove -w`? Is the point that you would prefer `dvc exp gc -w -R` to `dvc exp remove -w`? I agree that `gc` can be confusing, which is why I suggested to add this option to `remove` instead.

IMHO, the flags should be explicit. Having a `--reverse` flag is confusing. The user shouldn't have to look up the help text about the meaning. What are we reversing to what?





> I'd say that introducing `gc -R` or `gc --keep/--remove` is a separate feature request since it does more than what's requested here, and `gc` applies to more than experiments. For example, would `dvc exp gc -R/--remove` ever make sense for all branches or tags? I think the ideas make sense, but I don't want them to block the simpler feature request here.

Implementation-wise, these are not that different. Basically, the command will iterate over all experiments and decide whether an experiment is within the group specified for deletion. If some of the groups are empty, so be it. 



> If the `--workspace` option seems awkward in `dvc exp remove`, we can simply implement `dvc exp remove --all` and save the distinctions between `--workspace` and similar options to another feature request.

`--all` is better than `--workspace`. `--workspace` is a smaller set than `--all`. 

BTW if `dvc exp remove` will be the primary removal command, having `--include` and `--exclude` options may be better semantically. `dvc exp remove --include all --exclude exp-123abc` says "delete all experiments except exp-123abc", but this is another feature as you say. 

@dberenbaum

**Comment by casperdcl** [comment]
> Is this the same functionality as the proposed `dvc exp remove`

ah so you mean `dvc exp remove <flag>` is intended to be identical to my proposed `dvc exp gc -R <flag>`?

If that's the case, the main problem I see with `dvc exp remove` is that it's easy to confuse with `dvc remove`. Meanwhile, `dvc exp gc` and `dvc gc` can remain similar. For this reason alone I'd actually recommend deprecation of `dvc exp remove` completely.

**Comment by dberenbaum** [comment]
For the record, the syntax for now will be `dvc exp remove -A/--all`. I'd rather experiment removal not be tied to the existing `gc` commands and flags. Let's see what feedback we get and continue to discuss in #6429.
