### ISSUE TITLE
metrics: visualize metrics history among range of revisions

### ISSUE THREAD

**Issue by BeatWolf** [iterative/dvc#5710]
During development it is often important to have an idea how a ML model improved over time, across development.

DVC has metrics, which are nice to compare two revisions, and plots which are nice to see how a value evolves inside training.

But what is missing is a combination. Having a plot of the history of a metric.
Most likely this command would require the metrics file and the name of the variable inside the metrics file to be plotted

**Comment by pared** [comment]
I think we could approach that with additional command to `dvc metrics`. For example `dvc metrics history`, extract the metrcis values and plot them with revision on x-axis. We would need some sensible mechanism of defining revisions range. I think its hard to expect users to provide revisions as list, so some easy to access options might be needed. For example 
`dvc metrics history metric.json:accuracy --last 10` would show plot for last 10 revisions.

**Comment by BeatWolf** [comment]
--last 10 sounds great.
--since TAG_NAME and or "--only-tags" would certainly also be interesting

**Comment by dberenbaum** [comment]
If you want to compare metrics across more than two revisions, have you tried to use `dvc exp show -n 10`? This compares metrics over the last 10 commits. This doesn't get you the visual plots, but if you are looking for something that might help you right away, take a look!

**Comment by shcheklein** [comment]
It's called `trends` in the viewer.iterative.ai, I guess we can/should synchronize names? Let me know if you'd like to have access to the service, it would be great to have your feedback.

**Comment by BeatWolf** [comment]
> It's called `trends` in the viewer.iterative.ai, I guess we can/should synchronize names? Let me know if you'd like to have access to the service, it would be great to have your feedback.

Yes that sounds interesting

**Comment by shcheklein** [comment]
@BeatWolf done, you can login now. And please ping me when/if you need any help at [ivan @ iterative.ai]. 

You could clone https://github.com/iterative/jameson-metrics and/or https://github.com/iterative/example-get-started to connect them (add view).
