### ISSUE TITLE
add/import-url: merge --to-remote and --remote

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5719]
Per https://github.com/iterative/dvc/pull/5198#pullrequestreview-566902933 / https://github.com/iterative/dvc/pull/5198#issuecomment-765839003

By adding an optional `<remote>` argument to `--to-remote`:

```console
$ dvc remote add tmp /tmp/dvcstore
$ dvc add /external/path --to-remote tmp
```

**Comment by efiop** [comment]
https://github.com/iterative/dvc/pull/5721#issuecomment-812512451
