### ISSUE TITLE
Wrong URL to the docs in the dvc exp --help

### ISSUE THREAD

**Issue by yalozhkin** [iterative/dvc#5735]
# Bug Report

Run `dvc exp --help` and got the link to the docs:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/454947/113030433-4396a480-9196-11eb-8b27-1d832e6141e7.png">

## Description

The link is broken and includes the `>` symbol.

**Comment by ltn100** [comment]
I'm not sure if this has already been fixed, but I am not seeing the issue on the latest DVC version from PyPI (2.0.17)

![Screenshot from 2021-04-10 11-31-29](https://user-images.githubusercontent.com/77056/114266885-bb639b00-99f0-11eb-88b5-14c0250c8c31.png)

If this has not been explicitly addressed, then I suspect the issue may be with the OP's terminal URL parser. It works fine with my terminal (Terminator 1.91) and the default gnome terminal on Ubuntu (3.36.2). I also tried on a mac with both iTerm2 and the default OSX terminal with no issue.

@yalozhkin, which DVC version are you using, and which terminal emulator?

**Comment by Darion** [comment]
Looks like a terminal emulator issue. `>` can't be a part of the URL by [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt). But some terminal emulators include `<>` in their URL detection regexps. Like sakura: https://git.launchpad.net/sakura/tree/src/sakura.c#n329

**Comment by skshetry** [comment]
Thanks @Darion @ltn100. @yalozhkin, we don't do anything with the URL right now (we might use [`rich`'s link markup](https://rich.readthedocs.io/en/latest/markup.html) in some of the outputs later), so it is definitely an issue with the URL detection in the terminal as pointed by @Darion. 

Closing ...

**Comment by shcheklein** [comment]
If some terminals (emulators) behave this way would it be easier to get rid of < > ? They do not have any meaning, do not play any role, right? And getting rid of them could improve experience for some folks?
