### ISSUE TITLE
Indent in --set-param

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#5736]
`dvc exp run --set-param` sets a new space indeed. It is problem because of:
1. It creates a huge `git params diff` even for a one params change.
2. Some teams might have an agreement on indent and formating and might not be ready to change it.

It would be great to keep the existing indent if the implementation is not too heavy.

**Comment by dberenbaum** [comment]
@dmpetrov I don't understand where you are seeing an indent/space. Could you provide an example or elaborate?

**Comment by pmrowla** [comment]
When we edit a parameter, we will output a modified version of `params.yaml` using however `ruamel.yaml` decides to serialize it, with ruamel's default indentation rules (which may not match the existing indentation of `params.yaml`).

I think getting our serialization methods to preserve indentation would require overriding some of the ruamel serialization classes and is probably not a trivial change? @skshetry might have a bit more insight here

**Comment by skshetry** [comment]
Closing in favor of #8720 which has more context/discussion.
