### ISSUE TITLE
drive v2 ERROR when dvc push

### ISSUE THREAD

**Issue by math-sasso** [iterative/dvc#5761]
ERROR:

![image](https://user-images.githubusercontent.com/23565626/112201664-3f471600-8bef-11eb-8af6-d2b0d5166205.png)

My  config file
![image](https://user-images.githubusercontent.com/23565626/112201707-4a01ab00-8bef-11eb-9f07-95ae06f52b5a.png)

**Comment by shcheklein** [comment]
Hi @math-sasso. I think this error has been fixed in the most recent versions of DVC. Please give it a try.

**Comment by math-sasso** [comment]
I discovered that you cant commit your code on git before push on DVC.

 In other words you cant do:
git add .
git commit -m "my message"
git push

Before do:
 dvc add data_folder
dvc push

**Comment by efiop** [comment]
@math-sasso Not sure I follow. Could you elaborate?
