### ISSUE TITLE
dvc push: fails because of pydrive2 dependency

### ISSUE THREAD

**Issue by mmfausnaugh** [iterative/dvc#5776]
# Bug Report

## Description
updated to 2.0.17, and now have this error when running dvc push:

```
ERROR: failed to push data to the cloud - URL 'gdrive://1cQxzcWTZvn47i7iYY2W44mwj5Tv7zMaH' is supported but requires these missing dependencies: ['pydrive2']. Please report this bug to <https://github.com/iterative/dvc/issues>. Thank you!
```
tried `pip install pydrive2`, but it doesn't work.  Else, just following directions.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by efiop** [comment]
@mmfausnaugh Please post `dvc doctor` output

**Comment by mmfausnaugh** [comment]
DVC version: 2.0.17 (brew)
---------------------------------
Platform: Python 3.9.4 on macOS-11.2.3-x86_64-i386-64bit
Supports: azure, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: gdrive
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git

**Comment by skshetry** [comment]
looks like `pydrive2` is not specified as a dependency for the brew package.
https://github.com/Homebrew/homebrew-core/blob/a0da6ef8229128041dc8f594ac9562b6dac05c6e/Formula/dvc.rb#L436-L439

**Comment by efiop** [comment]
@skshetry Great catch! Indeed, homebrew guys did some major changes to our formula not long ago and looks like they've mixed up pydrive and pydrive2: https://github.com/Homebrew/homebrew-core/blob/master/pypi_formula_mappings.json#L42 Looks like that's the only thing we need to adjust.

**Comment by carlocab** [comment]
This was my mistake. Apologies for the inconvenience!

**Comment by efiop** [comment]
@carlocab No worries, it also means that we need to improve end-to-end package testing on our side :slightly_smiling_face: Thanks a lot for your great work on homebrew :pray: 

@mmfausnaugh Thank you for the feedback!
