### ISSUE TITLE
conda install doesnt work for dvc-azure 2.0.17 on linux and mac

### ISSUE THREAD

**Issue by majidaldo** [iterative/dvc#5787]
...it says to install adlfs via the conda command `conda install -c conda-forge dvc-azure`. pip install works.

please take care of conda. this is not the first time i've had a dvc install not work with conda but work with pip.

**Comment by skshetry** [comment]
@majidaldo, is that a typo or did you try `azure-dvc` to install? Please try installing `dvc-azure`. It seems that we are getting conflicts somewhere making installation froze for a while.

Could you please add more information about the error that you get (with `--verbose` flag)? Thanks.

**Comment by majidaldo** [comment]
indeed it hesitates to install . 
 but it's working now!!! i confirmed it not working yesterday on both linux and mac.

**Comment by maresb** [comment]
@majidaldo I strongly suspect that the problem is the slow solver which `conda` uses. I've always had much better luck with `mamba`. See #5625 for details.

**Comment by majidaldo** [comment]
> @majidaldo I strongly suspect that the problem is the slow solver which `conda` uses. I've always had much better luck with `mamba`. See #5625 for details.

but even if it hesitates, it should functionally be the same.

**Comment by maresb** [comment]
In theory yes. There might be slight implementation differences, but `conda` and `mamba` are mostly interchangeable.

@majidaldo does `mamba` solve your issue, or is there still a problem?

**Comment by majidaldo** [comment]
> In theory yes. There might be slight implementation differences, but `conda` and `mamba` are mostly interchangeable.
> 
> @majidaldo does `mamba` solve your issue, or is there still a problem?

i haven't tried as i depend on, what you might say, a conda-based 'build system' to install packages in environments.
just tried using conda again and it's still working. the solver takes a few minutes but it's tolerable. i just worry about the solver 'failing' and then trying a 'flexible solve'.

thanks!

**Comment by skshetry** [comment]
@majidaldo, are all your conda packages up to date? If there are some old packages, I have seen that conda struggle to solve dependency resolution in those cases. Please see if `conda update --all` solves the issue.

**Comment by majidaldo** [comment]
> @majidaldo, are all your conda packages up to date? If there are some old packages, I have seen that conda struggle to solve dependency resolution in those cases. Please see if `conda update --all` solves the issue.

yes. fyi i install dvc in its own environment isolated from other libraries. i rebuild my dvc environment regularly.

**Comment by majidaldo** [comment]
not dvc's fault but i had an issue that got fixed with https://stackoverflow.com/a/71550539/1922945

**Comment by majidaldo** [comment]
not dvc's fault but on windows i had an issue that got fixed with https://stackoverflow.com/a/71550539/1922945
