### ISSUE TITLE
list:  endless wait/freeze on Windows with old Git for private data registries

### ISSUE THREAD

**Issue by zimka** [iterative/dvc#5792]
# Bug Report

## Description
When any data registry related command (list, get, import etc) is used on Windows with old GitForWindows( <2.31, checked for 2.21), it freezes forever after auth attempt. Checked for github only, happens both in GitBash and PowerShell.
Looks like the problem is caused by Github auth issues, similar to [this](https://stackoverflow.com/questions/55768926/logon-failed-use-ctrlc-to-cancel-basic-credential-prompt-to-git-in-azure-devop). 
Freeze can not be interrupted with Ctrl+C, process keeps running with lock, can be killed using Windows TaskManager only.
Checked that issue does not happen on Linux.
**Problem disappears once git is updated using `git update-for-windows`.**

##### Short
1. Create private fork https://github.com/iterative/example-get-started
2. Try to use `dvc list` (on Windows with old git) on it - it freezes
```
$ dvc list https://github.com/<you>/example-get-started -- verbose
2021-04-09 11:00:26,806 DEBUG: Creating external repo https://github.com/zimka/example-get-started@None
2021-04-09 11:00:26,807 DEBUG: erepo: git clone 'https://github.com/zimka/example-get-started' to a temporary dir
# Github login window appears, but nothing happens when credentials are entered
# Process keeps running (holding) without any changes forever
```
##### Long (Git Bash)
```
$ dvc version
DVC version: 2.0.7 (exe)
---------------------------------
Platform: Python 3.7.9 on Windows-10-10.0.19041-SP0
Supports: All remotes

$ git version
git version 2.21.0.windows.1

# Create private repo somewhere, e.g. https://github.com/<you>/example-get-started
# Put there example-get-started repo
$ git clone --bare https://github.com/iterative/example-get-started.git
$ cd example-get-started.git/
$ git remote add privatefork https://github.com/<you>/example-get-started
$ git push privatefork master

# Create new project
$ mkdir ../myproj
$ cd ../myproj
$ git init
$ dvc init

# Check remote dvc project content for public parent - works fine
$ dvc list https://github.com/iterative/example-get-started
.dvcignore
.gitignore
README.md
data
dvc.lock
dvc.yaml
model.pkl
params.yaml
prc.json
roc.json
scores.json
src
# Check remote dvc project content for private fork - it breaks down
$ dvc list https://github.com/<you>/example-get-started -- verbose
2021-04-09 11:00:26,806 DEBUG: Creating external repo https://github.com/zimka/example-get-started@None
2021-04-09 11:00:26,807 DEBUG: erepo: git clone 'https://github.com/zimka/example-get-started' to a temporary dir
# Github login window appears, but nothing happens when credentials are entered
# Process keeps running (holding) without any changes forever
 
```

### Expected
`dvc list` command on Windows with old git produces for private fork the same output as for public parent repo  
OR  after some waiting DVC cancels the command, warns user about the problem and recommends to update git.

### Environment information
**Output of `dvc doctor`:**
DVC version: 2.0.7 (exe)
---------------------------------
Platform: Python 3.7.9 on Windows-10-10.0.19041-SP0
Supports: All remotes
```console
$ dvc doctor
```

**Additional Information (if any):**
Similar issue happens with `dvc get `, `dvc import` for the same reason.

**Comment by pmrowla** [comment]
This issue will probably be resolved by the erepo/clone changes in https://github.com/iterative/dvc/issues/2215 (clone will be moved entirely into dulwich), but it's still probably worth it for us to document a minimum supported CLI Git version for Windows

**Comment by skshetry** [comment]
Closing for now as per the post above, it does not happen with the newer versions of Windows, and we are trying to move away from depending on the installed git binary. 

Thanks @zimka for creating the issue.

**Comment by zimka** [comment]
From my point of view this issue was pretty hard to relate to git auth problems and it was not clear that it could be fixed with git update, so either cli warning (e.g. git version check) or some info about the issue in the [docs](https://dvc.org/doc/user-guide/running-dvc-on-windows) could be very helpful.
Just to make it clear - while problem is defninitely caused by git (may be not even it's python bindings), from user point of view it looks like a dvc issue, since GitBash at this version works properly with private repos.
I would rather propose to close this issue once either some kind of warning is added, or issue disappears because of library change, since for now the problem is actually presesnt for some users and it is not documented or solved.
@skshetry

**Comment by efiop** [comment]
@zimka Would you be interested in sending a doc update for this?

The warning or error check likely needs to be added to gitpython, as that's what we are using for cloning and so it should likely be handled there. If you can reproduce it with gitpython's clone, please feel free to create an issue in gitpython, let's see what they have to say.

From dvc perspective a forementioned dulwich clone is rather close, so it makes sense to wait for it, as it will likely resolve this issue automatically.

**Comment by efiop** [comment]
Keeping it open until the switch is done.

**Comment by zimka** [comment]
FYI I have created a PR for docs with problem description @efiop 
https://github.com/iterative/dvc.org/pull/2392

**Comment by efiop** [comment]
We use dulwich to clone now, closing.
