### ISSUE TITLE
exp show: wrong params display after params modified.

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#5803]
# Bug Report

![image](https://user-images.githubusercontent.com/6745454/114495175-37a7e980-9c50-11eb-83ab-c24bbaf3c8e5.png)
![image](https://user-images.githubusercontent.com/6745454/114495217-468e9c00-9c50-11eb-9798-9db3f3d3ed1c.png)

Same exp branches with different shown values in branch `exp-44136`.

### Reproduce

1. delete some params, both in `dvc.yaml` and `params.yaml`. Delete fields or slots, not the values.
2. dvc exp run
3. dvc exp show
4. dvc exp apply <newly add exp branch>
5. dvc exp show

### Expected

Params value to be consistent in `dvc exp show`.

### Environment information
```
DVC version: 2.0.17+353e4c
---------------------------------
Platform: Python 3.8.5 on Linux-5.4.0-70-generic-x86_64-with-glibc2.29
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sda2
Caches: local
Remotes: None
Workspace directory: xfs on /dev/sda2
Repo: dvc, git
```

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by pmrowla** [comment]
@karajan1001 can you include an actual reproduction script here? It's not clear what exactly you are modifying and applying

**Comment by karajan1001** [comment]
@pmrowla 
```
 $ git init
 $ dvc init
 $ git commit -m "init"
 $ echo '{"acc":0.90}' > acc
 $ dvc run -d acc -m result.json -n copy "cat acc>result.json"
 $ git add dvc.lock .gitignore dvc.yaml
 $ git commit -m "first version"
 $ dvc exp run -f
 $ echo 'lr: 0.01' > params.yaml
 $ vim dvc.yaml # add lr to field params
 $ echo '{"acc":0.95}' > acc
 $ dvc exp run
 $ dvc exp show
 $ dvc exp apply exp-d2074 # here to the old version  
 $ dvc exp show
```
