### ISSUE TITLE
Track stage logs automatically

### ISSUE THREAD

**Issue by mattlbeck** [iterative/dvc#5807]
Very often I find myself needing to keep hold of logs from previous runs of a pipeline and sometimes even compare them with a current run. There are a variety of scenarios where tracking the logs along with the stages outputs is very useful - in fact if this isn't done by the user it is often the only piece missing to a tracked DVC pipeline upon review. There are also many ways in which DVC can be run on remote or cloud instances, many of which make it harder to view or keep the logs if not properly configured.

It is fairly straightforward to track logs using DVC with a bit of extra configuration

```
stages:
    A: 
       cmd: ./run_stage.sh 2>&1 | tee outs/A.log
       outs:
            - outs/A.log
```

However, since dvc `run` and `repro` forward the output streams, they are in an ideal position to log those streams to a tracked file by default, perhaps to a path such as `.dvc/cache/logs/` with a `logs` entry in the lock file and automatically push the logs to a remote with the rest of the cache. Doing so will remove the need to configure tracking of logs, will promote keeping hold of logs for those who don't do it, and allow DVC to act on logs as first class artifacts. For example, users then may want to access those logs through a top level command such as `dvc logs`, which could provide functionality such as:

- `dvc logs checkout [target] [path]` checkout logs for the current run to a particular directory
- `dvc logs show [target]` view the logs for a target on the command line, with an optional `--grep` to filter lines by
- `dvc logs diff [target] [ref]` provide a diff of logs between current run and specified git ref, with an optional `--grep` to filter lines by

**Comment by dmpetrov** [comment]
@mattlbeck good scenario!

What kind of logs are you creating? I'm wondering is `dvc log diff` is enough - in many cases, logs are not really diff-able. Examples would be really helpful.

**Comment by efiop** [comment]
Closing as stale and in favor of https://github.com/iterative/dvc/issues/1495
