### ISSUE TITLE
dvc init --exists-ok

### ISSUE THREAD

**Issue by majidaldo** [iterative/dvc#5810]
dvc init should have the option of returning with 0 exit code.

**Comment by efiop** [comment]
@majidaldo Have you seen `dvc init --force`?

**Comment by dberenbaum** [comment]
`dvc init --force` is a bit different in that it will overwrite any dvc config, right? I wonder how likely it is to have a scenario where neither `dvc init --force` nor `dvc init | true` are sufficient?

**Comment by majidaldo** [comment]
> `dvc init --force` is a bit different in that it will overwrite any dvc config, right? I wonder how likely it is to have a scenario where neither `dvc init --force` nor `dvc init | true` are sufficient?

Yup. I think reasonable behavior is to have init be idempotent.
