### ISSUE TITLE
`remote`: remove/hide `--project` option?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5828]
> Context: https://github.com/iterative/dvc.org/pull/2064#pullrequestreview-622776218

`--project` is available along with `--system/global/local` for all commands that change DVC config. However it never has an effect in `remote add/modify/remove/rename` (which only write to config). So should we just remove it from those, or at least hide it in the CLI (and remove from docs) ?

**Comment by jorgeorpinel** [comment]
Cc @efiop thanks

**Comment by pmrowla** [comment]
The remote config commands should actually get proper support for reading/writing to other config locations: https://github.com/iterative/dvc/issues/5585

**Comment by efiop** [comment]
As noted in the review, the main reason is symmetry right now. But also it allows one to be explicit with the commands, pluse potential for level-specific functionality in the future. It is not worth removing right now.
