### ISSUE TITLE
dvc list: Error on empty directory. 

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#5841]
# Bug Report

Got error message on an empty directory, shouldn't it show nothing? like ls command.

## Description
![image](https://user-images.githubusercontent.com/6745454/115115559-bfcb1d80-9fc7-11eb-82d4-bb04d0413795.png)
Error when list a empty path, strange behavior.
Might relate to https://github.com/iterative/dvc/blob/daf07451f8e8f3e76a791c696b0ea175e8ed3ac1/dvc/repo/ls.py#L40-L41

### Reproduce

1. git init
2. dvc init
3. mkdir empty
4. dvc list . empty

### Expected
Show nothing like ls command
![image](https://user-images.githubusercontent.com/6745454/115115651-2a7c5900-9fc8-11eb-9a86-884626d240ea.png)

### Environment information
DVC version: 2.0.17+7e4851
---------------------------------
Platform: Python 3.8.8 on macOS-10.16-x86_64-i386-64bit
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by karajan1001** [comment]
We have already had a test about this.

https://github.com/iterative/dvc/blob/68897aa0def4e509a27d75f2e78106495d08e0c4/tests/func/test_ls.py#L167-L173

and it was introduced from #3246 at the beginning of `dvc list` command.

**Comment by evanrittenhouse** [comment]
@karajan1001 is this still open? New to open source, but would love to take a stab at it

**Comment by karajan1001** [comment]
> open

Sorry, we had already had a PR for it (#6120) but was blocked by some refactoring. So maybe it is better to start with some other issues with `good first issue`.
