### ISSUE TITLE
Basic operations performance on Win

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#5842]
Context https://discord.com/channels/485586884165107732/485596304961962003/832144403635109898

> Hi, I have started a new project and wanted to try out dvc for the first time. I have a data folder that has 37.7k images totaling to 600MB. I tried dvc add and I had to wait for 30 min while it was computing hashes and still it didn't finish. Does it always take such a long time or did I do something wrong?

CProfile: https://drive.google.com/file/d/1grD3dHgDatjarXbS6Z-Cye6DaeQKvdgT/view?usp=sharing

DVC version:

```
DVC version: 2.0.17 (conda)
---------------------------------
Platform: Python 3.8.3 on Windows-10-10.0.19041-SP0
Supports: gdrive, http, https
```

Regular (not network drive).

<img width="1413" alt="Screen Shot 2021-04-17 at 1 38 26 PM" src="https://user-images.githubusercontent.com/3659196/115126245-7d332200-9f82-11eb-80f6-29ef0640cdd4.png">

It looks like we read itself takes 10s out of 450s. A lot of time goes into doing path operations, SQLlite, etc. Even if we could improve specific `nt.stat` and other calls, question still valid - why do we do `12x * number of files` of those? (+ a lot of other path, string manipulations).

Steps I would suggest to do:

- create Win bench for this - to start tracking basic Win operations. Can we answer the question how - is it a regression or not?
- consolidate this with other similar Win performance tickets
- try to reproduce this - make sure that we are not missing anything
- research what can we do.

**Comment by dberenbaum** [comment]
Related to #2360

**Comment by pzhy13** [comment]
I am facing the similar problem, and my add.prof file is here.
https://github.com/pzhy13/fyp/blob/main/add.prof
Also my dvc doctor:
DVC version: 2.1.0 (exe)
---------------------------------
Platform: Python 3.8.9 on Windows-10-10.0.14393-SP0
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: NTFS on D:\
Caches: local
Remotes: None
Workspace directory: NTFS on D:\
Repo: dvc, git

**Comment by pared** [comment]
> create Win bench for this

We could get back to this subject, it will probably require setting up (another runner)[https://github.com/iterative/dvc-bench/issues/196#issuecomment-669877825]. We have been considering upgrading our linux one, so maybe we could join those tasks.
