### ISSUE TITLE
metrics show --all-commits fails on corrupt historic commits

### ISSUE THREAD

**Issue by jheister** [iterative/dvc#5844]
When using `metrics show --all-commits` we got failures due to a historic commit where a `dvc.lock` file was committed with merge conflicts in it.

I think it would be best to skip (and log warnings) revisions where a `LockfileCorruptedError` is thrown.

**Comment by dberenbaum** [comment]
Sorry, missed that you submitted a PR for this! I'll leave open for now then.

**Comment by pared** [comment]
Fixed by #5984
