### ISSUE TITLE
replace `dvc run`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#5846]
Add `dvc stage add --run` option that mimics `dvc run` (adds a stage and reproduces it). See https://github.com/iterative/dvc/discussions/5819.

- [ ] Decide how to update docs due to this. Probably phase out all `run` examples and redirect its ref to `stage add`.

**Comment by skshetry** [comment]
There's a small difference between current behaviour of `dvc stage add` and `dvc run --no-exec`, that the former tries not to check too many things and not fail as much as possible as a result of that. `dvc run` validates of a lot of things and runs the script. If the script fails or the validation fails, it won't dump that stage to `dvc.yaml`. 

What should the behaviour of `dvc stage add --run` be in that case? Should it also not dump those stages (similar to `dvc run`)? Or, should it dump anyway even if it fails (i.e. how stage add works)?

**Comment by dberenbaum** [comment]
Good question! IMO let's keep it consistent with `dvc stage add` and keep it in `dvc.yaml` if it would have succeeded without `--run`. Thoughts @jorgeorpinel @shcheklein ?

**Comment by shcheklein** [comment]
Agreed. It sound simpler and users would add force if they need to fix and run it again.

**Comment by jorgeorpinel** [comment]
> let's keep it consistent with dvc stage add and keep it in dvc.yaml if it would have succeeded without --run

➕

**Comment by jorgeorpinel** [comment]
Q. Will `run` get deprecated eventually or turned into an alias of `stage add --run`? The latter sounds nicer but the former may be less problematic (support-wise).

**Comment by skshetry** [comment]
What about existing options like `--no-run-cache`/`--no-exec` and `--no-commit`? Do they need to be supported in `dvc stage add --run`?

**Comment by skshetry** [comment]
I guess probably not as this is more of a helper utility than trying to be a replacement.
