### ISSUE TITLE
dvc pull: (from hdfs) Missing dependencies on Linux & Windows

### ISSUE THREAD

**Issue by benjaminalt** [iterative/dvc#5858]
## Description

When running `dvc pull` for a hdfs remote, I get various missing dependency errors, depending on how dvc was installed. I was not able to get `dvc pull` to work on either Windows or Linux, even after manually installing the missing dependencies.

Here is what I tried:

**1. Ubuntu 18.04, installation via `apt`**
```
sudo wget \
       https://dvc.org/deb/dvc.list \
       -O /etc/apt/sources.list.d/dvc.list
wget -qO - https://dvc.org/deb/iterative.asc | sudo apt-key add -
sudo apt update
sudo apt install dvc
dvc pull
ERROR: unexpected error - Unable to load libhdfs: ./libhdfs.so: cannot open shared object file: No such file or directory
```
I get the same error when downloading the `.deb` and installing it from the file.
**2. Ubuntu 18.04, installation via `snap`**
```
sudo snap install dvc --classic
dvc pull
Everything is up to date.                                             
ERROR: failed to pull data from the cloud - URL 'hdfs://hadoop@134.102.137.65:9000/neems/pr2-pick-and-place-milk-in-unreal' is supported but requires these missing dependencies: ['pyarrow']. Please report this bug to <https://github.com/iterative/dvc/issues>. Thank you!
```
**3. Ubuntu 18.04, installation via `pip`**
```
pip install dvc[all]
dvc pull
ERROR: unexpected error - Unable to load libhdfs: ./libhdfs.so: cannot open shared object file: No such file or directory
```
**4. Windows 10, installation via the .exe installer**
```
dvc pull
ERROR: unexpected error - Unable to load libjvm: Das angegebene Modul wurde nicht gefunden.
```

Trying to install libhdfs on Ubuntu without installing the entire Hadoop ecosystem led to all kinds of dependency hell. When I manually installed pyarrow and could successfully import it in Python, the error message from the `snap` dvc install kept persisting.

### Reproduce

1. Install DVC via one of the methods listed above
2. Clone a DVC repo with a HDFS remote, e.g. https://neemgit.informatik.uni-bremen.de/neems/pr2-pick-and-place-cereal-in-projection.git
3. `cd` into the repo and run `dvc pull`

### Expected

`dvc pull` should work for HDFS remotes, both on Linux and on Windows. I haven't gotten it to work on either.

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.0.18 (deb)
---------------------------------
Platform: Python 3.8.9 on Linux-4.15.0-142-generic-x86_64-with-glibc2.4
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: hdfs
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git
```

**Comment by efiop** [comment]
Hi @benjaminalt !

Would webhdfs be an option for you in the meantime?

**Comment by benjaminalt** [comment]
Hi! I don't have administrative access to the hadoop server, so I can't set up webhdfs there. I can get the data another way though. If this issue can be reproduced by others, I still think it should be fixed (DVC + HDFS is probably a popular and certainly a powerful combination) in the medium term.
Am 21. Apr. 2021, um 18:22, Ruslan Kuprieiev ***@***.******@***.***>> schrieb:

Hi @benjaminalt<https://github.com/benjaminalt> !

Would webhdfs be an option for you in the meantime?

**Comment by efiop** [comment]
@benjaminalt webhdfs might be already enabled by default, so if you can - give it a try. Webhdfs has an advantage of being an http-based, which means that there are no complex dependencies needed to use it.

> 1. Ubuntu 18.04, installation via apt

You need to install libhdfs with hadoop, there is no alternative way, unfortunately. :slightly_frowning_face: 

> 2. Ubuntu 18.04, installation via snap

This one is temporarily excluded from snap package https://github.com/iterative/dvc-snap/issues/2 , we should at least improve the error.

> 3. Ubuntu 18.04, installation via pip

Same as in 1.

> 4. Windows 10, installation via the .exe installer

I'm not familiar with hadoop on windows, but looks like it is similar to 1. , just need to set up hadoop.

Our assumption with hdfs is that the user has already set up hadoop for his code, so dvc could use the same libraries. Are you using hdfs only as dvc remote or for something else as well? If so, how do you access it?

**Comment by benjaminalt** [comment]
Thank you a lot for your explanations. I did the full Hadoop install and `dvc pull` worked. I intuitively did not expect to have to do this (and expected hdfs to be part of the dvc install) because I actually only wanted to download the data from the remote (which happens to use hdfs). Reading data from a hdfs server without being a Hadoop instance myself might be a niche use case, so I guess I'm closing this issue :)

**Comment by efiop** [comment]
@benjaminalt We really wish we could have a self-contained hdfs support too :smile: There is a very cool project that implements lots of the stuff in pure-python https://github.com/spotify/snakebite , but unfortunately it has been dead for 5 years now with no active forks :slightly_frowning_face: So for now we are stuck with heavyweight libhdfs approach or lightweight webhdfs.

Glad that it works for you now. Thanks for the feedback! :pray:

**Comment by shcheklein** [comment]
@efiop @benjaminalt quick question - would improving the docs/messages somehow can help to mitigate this?

**Comment by benjaminalt** [comment]
@shcheklein When installing dvc, I naively thought it would automatically install all of its dependencies, like most other apt or snap packages. The documentation for the `pip` install (https://dvc.org/doc/install/linux#install-with-pip) explicitly states that for some types, optional dependencies would be installed. Maybe analogously there could be a statement for all install methods that for some remote types, dependencies will not be installed. The same applies to the Windows installer too - where it is even more common to ship all DLLs needed by an application.

**Comment by shcheklein** [comment]
@benjaminalt thanks, I've added a small note here https://github.com/iterative/dvc.org/commit/ef40410a8136b3a01e42c967bda60c233f6aac7f . I'll be redeployed soon and can hopefully save other users time.
