### ISSUE TITLE
import-url: parent dir '../' gets truncated from the import path if I define output directory or file

### ISSUE THREAD

**Issue by AhtiAhde** [iterative/dvc#5862]
# Bug Report

## Description

If I try to us import-url for importing files from the local file system AND the files are outside of the active DVC workspace, the `../` part of the path will get truncated and I get error messages like:

```
ERROR: failed to import ../some/path/data. You could also try downloading it manually, and adding it with `dvc add`. - dependency 'some/path/data' does not exist
```

As you can see the `-depencency  ...` has removed that path segment which has `../`

This doesn't apply only to the first `../` but all of them will get truncated from the path:
```
ERROR: failed to import ../some/path/../path/data. You could also try downloading it manually, and adding it with `dvc add`. - dependency 'some/path/data' does not exist
```

### Reproduce

Here is a script for reproduction:
```
#!/bin/bash

set -ex

rm -rf wspace
mkdir wspace

pushd wspace

data_dir=./some/path
mkdir -p $data_dir
echo data >> $data_dir/data

mkdir repo
pushd repo
mkdir data-sets

git init --quiet
dvc init --quiet
git add -A
git commit -am "init"

dvc import-url ../some/path/../path/data data-sets
```

### Expected

Expected behavior of course would be that the relative path would be intact without parent dir accessors getting truncated.

### Environment information

**Output of `dvc doctor`:**

DVC version: 2.0.17 (pip)
---------------------------------
Platform: Python 3.7.6 on Linux-4.19.128-microsoft-standard-x86_64-with-debian-bullseye-sid
Supports: gdrive, http, https
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/sdb
Repo: dvc, git

**Additional Information (if any):**

No additional information.

**Comment by pared** [comment]
The issue seems to be originating in our [local output](https://github.com/iterative/dvc/blob/d87ace0968656912db9e6de3b638b594ceeda43b/dvc/output/local.py#L45) Where we generate relative path basing on stage `wdir` and imported URL `path` (relative one) and not considering the fact that `stage.wdir` might not be the same as `curdir` (which is the necessary ingredient required to resolve URL).
