### ISSUE TITLE
`dvc remote modify`  : the s3 wrapper doesn't accept the verify_ssl config parameter

### ISSUE THREAD

**Issue by louistransfer** [iterative/dvc#5863]
# Bug Report

The command `dvc remote modify remote_name verify_ssl false` fails to add the parameter verify_ssl = false to the config file when using the S3 connector.

## Description

I configured a S3 remote storage as a remote in dvc and I previously configured the aws-cli correctly. I have also installed dvc-s3. 

Since we use a company proxy, I need to add the 'verify_ssl = false' parameter to the remote configuration in order to avoid a ssl certificate verification error. However, using the command `dvc remote modify scality-test verify_ssl false ` raises the following error : 

ERROR : configuration error - config file error : extra keys not allowed @ data['remote']['scality_test']['verify_ssl']

The dvc documentation for the s3 connector indicates that dvc remote modify remote_name verify_ssl false should be the way to add the parameter to the config file: 

![dvc_remote_doc](https://user-images.githubusercontent.com/62989686/115559403-f6e54b80-a2b3-11eb-880c-b4d3bf9dbe5f.png)

I believe that it is a bug, as other modify commands such as `dvc remote modify use_ssl false` work and add the line use_ssl = false to the config file. Furthermore when I manually add the line 'verify_ssl = false' to the dvc config file, the certificate issue that I had disappears and the file is correctly pushed to the S3 bucket: DVC doesn't appear to recognize the key 'verify_ssl' in the modify command but it still reads the parameter correctly in the config file.

### Reproduce

1. dvc add remote -d s3_remote_name <s3://remote_bucket_path>
2. dvc remote modify s3_remote_name  endpoint_url <url_to_s3_endpoint>
3. dvc remote modify s3_remote_name verify_ssl false

### Expected

The config file should be updated with the line 'verify_ssl = false'.

### Environment information

dvc was installed on a git project on a Xubuntu environment within a virtual machine and it runs on Python version 3.9.2.

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.0.18 (conda)
------------------------------—
Platform: Python 3.9.2 on Linux-5.8.0-48-generic-x86_64-with-glibc2.31
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda5
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sda5
Repo: dvc, git
```

**Additional Information (if any):**

Here is the complete verbose error output :

2021-04-21 15:18:03,732 ERROR: configuration error - config file error: extra keys not allowed @ data['remote']['scality-test']['verify_ssl']

Traceback (most recent call last):
File "/home/louis/miniforge3/envs/data-registry/lib/python3.9/site-packages/dvc/main.py", line 55, in main
ret = cmd.run()
File "/home/louis/miniforge3/envs/data-registry/lib/python3.9/site-packages/dvc/command/remote.py", line 80, in run
section[self.args.option] = self.args.value
File "/home/louis/miniforge3/envs/data-registry/lib/python3.9/contextlib.py", line 124, in **exit**
next(self.gen)
File "/home/louis/miniforge3/envs/data-registry/lib/python3.9/site-packages/dvc/config.py", line 280, in edit
self.validate(merged_conf)
File "/home/louis/miniforge3/envs/data-registry/lib/python3.9/site-packages/dvc/config.py", line 292, in validate
raise ConfigError(str(exc)) from None
dvc.config.ConfigError: config file error: extra keys not allowed @ data['remote']['scality-test']['verify_ssl']

2021-04-21 15:18:03,739 DEBUG: Analytics is enabled.
2021-04-21 15:18:03,778 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpeqpqrrtb']'
2021-04-21 15:18:03,779 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpeqpqrrtb']'

**Comment by pared** [comment]
@louistransfer seems to me like we should fix docs - can you try `ssl_verify` instead of `verify_ssl`?

**Comment by louistransfer** [comment]
@pared Thanks four your help ! Indeed, `dvc remote modify scality-test ssl_verify false` works as expected.

**Comment by pared** [comment]
Created PR for docs, closing
