### ISSUE TITLE
list . : inconsistent behaviour

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#5866]
# Bug Report

## Description

Inconsistent behaviour for `dvc list . --dvc-only` depending on use of `-R` and the directory queried.

### Reproduce

In the vscode demo project (which is a subdir) there is a dvc tracked folder (`data/MNIST/raw`) which contains 8 datasets:
```
t10k-images-idx3-ubyte
t10k-images-idx3-ubyte.gz
t10k-labels-idx1-ubyte
t10k-labels-idx1-ubyte.gz
train-images-idx3-ubyte
train-images-idx3-ubyte.gz
train-labels-idx1-ubyte
train-labels-idx1-ubyte.gz
```

After deleting `t10k-images-idx3-ubyte.gz` and running the following command:
`echo 'dot -R from the root lists all' && dvc list . -R --dvc-only && echo '-------------\n-R from the parent directory lists all' && dvc list . data/MNIST -R --dvc-only && echo '-------------\n-R in the directory lists local only' && dvc list . data/MNIST/raw -R --dvc-only && echo '-------------\ndot by itself in the directory shows local only' && dvc list . data/MNIST/raw`

the following output is received:

```
dot -R from the root lists all
data/MNIST/raw/t10k-images-idx3-ubyte
data/MNIST/raw/t10k-images-idx3-ubyte.gz
data/MNIST/raw/t10k-labels-idx1-ubyte
data/MNIST/raw/t10k-labels-idx1-ubyte.gz
data/MNIST/raw/train-images-idx3-ubyte
data/MNIST/raw/train-images-idx3-ubyte.gz
data/MNIST/raw/train-labels-idx1-ubyte
data/MNIST/raw/train-labels-idx1-ubyte.gz
logs/acc.tsv
logs/loss.tsv
model.pt
-------------
-R from the parent directory lists all
raw/t10k-images-idx3-ubyte
raw/t10k-images-idx3-ubyte.gz
raw/t10k-labels-idx1-ubyte
raw/t10k-labels-idx1-ubyte.gz
raw/train-images-idx3-ubyte
raw/train-images-idx3-ubyte.gz
raw/train-labels-idx1-ubyte
raw/train-labels-idx1-ubyte.gz
-------------
-R in the directory lists local only
t10k-images-idx3-ubyte
t10k-labels-idx1-ubyte
t10k-labels-idx1-ubyte.gz
train-images-idx3-ubyte
train-images-idx3-ubyte.gz
train-labels-idx1-ubyte
train-labels-idx1-ubyte.gz
-------------
dot by itself in the directory shows local only
t10k-images-idx3-ubyte
t10k-labels-idx1-ubyte
t10k-labels-idx1-ubyte.gz
train-images-idx3-ubyte
train-images-idx3-ubyte.gz
train-labels-idx1-ubyte
train-labels-idx1-ubyte.gz
```
### Expected

Consistent behaviour for at least the use of the `-R` flag (i.e -R in the directory lists ~local only~ all).

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor: DVC version: 2.0.18 (pip)
---------------------------------
Platform: Python 3.8.7 on macOS-11.2.3-x86_64-i386-64bit
Supports: http, https, s3
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc (subdir), git
```

**Additional Information (if any):**

Discovered while working through https://github.com/iterative/dvc/issues/5712, https://github.com/iterative/vscode-dvc/issues/176 & https://github.com/iterative/vscode-dvc/issues/169. Please reach out on slack if you need any further information. 

CC @dberenbaum

**Comment by dberenbaum** [comment]
@mattseddon Is this still an issue for you?

**Comment by mattseddon** [comment]
Will come back to you shortly, sorry for the delay. Been caught up away from anything that use `list`.

**Comment by mattseddon** [comment]
@dberenbaum the inconsistency is still there but this is not a priority for me. 

QQ what is the best thing to do when I find something that is inconsistent / doesn't make sense but that I don't necessarily need fixed straight away?

**Comment by efiop** [comment]
Closing in favor of #5712

**Comment by dberenbaum** [comment]
> @dberenbaum the inconsistency is still there but this is not a priority for me (version 2.1.0).
> 
> QQ what is the best thing to do when I find something that is inconsistent / doesn't make sense but that I don't necessarily need fixed straight away?

Good question. I would say just explain the priority for you in the issue whether it is urgent or not.
