### ISSUE TITLE
import: using relative repo url in subdirectories cannot be cloned from project root (or other subdirectories)

### ISSUE THREAD

**Issue by iksnagreb** [iterative/dvc#5875]
# Bug Report

## Description
Importing data from a git repository referenced by a relative path breaks dvc commands which try to clone the repository (e.g. `dvc status`) from other directories (esp. from the project root). The relative repository url is not resolved correctly from other than the original location.

**The error message looks like:**
```
ERROR: Failed to clone repo '../src' to '/tmp/tmpufczzo73dvc-clone': Cmd('git') failed due to: exit code(128)                                                                                                                                      
  cmdline: git clone --no-single-branch --progress -v ../src /tmp/tmpufczzo73dvc-clone
```

### Reproduce
```
#/bin/bash

rm -rf wspace
mkdir wspace
pushd wspace

set -ex
main=$(pwd)

mkdir src
pushd src

git init --quiet

dvc init --quiet

git add -A
git commit -am "init"
echo data >> data

dvc add data
git add -A
git commit -am "add data"
popd

mkdir repo
pushd repo

git init --quiet
dvc init --quiet

git add -A
git commit -am "init"

mkdir data
mkdir dvc_files
dvc import ../src data -o data/data --file dvc_files/data.dvc

pushd data
dvc status
```

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.0.18 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-5.4.0-72-generic-x86_64-with-glibc2.29
Supports: gdrive, http, https, webdav, webdavs
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda1
Caches: local
Remotes: webdavs, webdavs
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git
```

**Additional Information (if any):**

Discord context:
https://discord.com/channels/485586884165107732/485596304961962003/835923263745687612
https://discord.com/channels/485586884165107732/485596304961962003/835973460140359700
https://discord.com/channels/485586884165107732/485596304961962003/835998128129310771

CC @pared

**Comment by pared** [comment]
Might be related to https://github.com/iterative/dvc/issues/5862
