### ISSUE TITLE
list: Add --show-json (or similar flag)

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#5881]
In the vs code project we have a view that uses `dvc list . --dvc-only` to show all paths that are tracked by DVC in a tree view.  Reasons for this view, some discussion around it and a short demo are shown here: https://github.com/iterative/vscode-dvc/issues/318.

At the moment we take the stdout from the command, split the string into a list (using `\n` as a delimiter) and then post process to work out whether or not the paths relate to files or directories. I can see from the output of the command that directories are already highlighted: 

![image](https://user-images.githubusercontent.com/37993418/116164073-676cec00-a73c-11eb-9404-48cd273798cf.png)

From the above I assume that the work to determine what the path is (file or dir) has already been done by the cli. Rather than working out this information again it would be ideal if the cli could pass us json that contains the aforementioned information.

This will reduce the amount of code required in the extension and should increase performance (ever so slightly).

Please let me know if any of the above is unclear.

Thanks

**Comment by mattseddon** [comment]
Thank you @pared. 

Can you guys LMK when you release `2.0.19` to PyPi (so I can install via pip). Please and thank you.

We are using `dvc[s3]>=2.0.x` in our test project's `requirements.txt`. Not sure if I can move to `git+https://github.com/iterative/dvc` without breaking anything.

**Comment by efiop** [comment]
@mattseddon 2.1.0 is out :slightly_smiling_face:
