### ISSUE TITLE
move: creates inconsistency when moving tracked file into tracked folder 

### ISSUE THREAD

**Issue by mistermult** [iterative/dvc#5886]
# Bug Report

## Description
Assume that you track the whole folder `dir1` with `dir1.dvc`. You cannot add an extra file `dir1/a.txt` and track with `dir1/a.txt.dvc` (with the command `dvc add a.txt` you get an error). However, you can first create a file `b.txt` outside `dir1` and move it with the .dvc-file into  `dir1` with `dvc move`.

### Reproduce

```bash
dvc init
mkdir dir1
dvc add dir1

# Error as excected
touch dir1/a.txt
dvc add dir1/a.txt

# No error (unexpected)
touch b.txt
dvc add b.txt
dvc move b.txt
dvc move b.txt dir1

# Result
ls dir1
## a.txt  b.txt  b.txt.dvc

# After a commit we get
dvc commit
cat dir1.dvc 
#outs:
#- md5: c53e75a492b0e8ccefef15fbf24d4c22.dir
#  size: 70
#  nfiles: 3
#  path: dir1
```

### Expected
I excpeted one of the two cases:
1. One should not be able to move a tracked file into a tracked folder and get an error.
2. Only the `b.txt` should be moved to the folder `dir1`. `b.txt.dvc` should be removed (or modified if it tracks other files).

### Environment information

Sorry, dvc doctor hangs on my system. Produced on Linux with ext4.

**Comment by karajan1001** [comment]
@mistermult , thanks.

> Sorry, dvc doctor hangs on my system. Produced on Linux with ext4.
 
Strange, but I had tested on the latest version, it can be reproduced. In my opinion, it is a bug.

**Comment by pmrowla** [comment]
for reference, after the fix this `dvc move` operation (trying to move a tracked file into an already tracked dir) will result in an error before anything is actually modified
