### ISSUE TITLE
dvc add throwing numpy error

### ISSUE THREAD

**Issue by JoaoDeDynam** [iterative/dvc#5900]
# Bug Report

## Description
dvc add throwing numpy error when trying to add directory or single file

### Reproduce

dvc init 
dvc add <path_to_file_or_directory>
Adding...                                                                                                                                                                             
ERROR: unexpected error - module 'numpy' has no attribute 'float64'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

### Expected
directory/files added to .dvcignore

### Environment information
MacOS Catalina. dvc installed with Brew install command

**Output of `dvc doctor`:**
DVC version: 2.0.18 (pip)
---------------------------------
Platform: Python 3.9.4 on macOS-10.15.7-x86_64-i386-64bit
Supports: http, https, s3
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1
Repo: dvc, git
```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by efiop** [comment]
@JoaoDeDynam Please add `-v` to `dvc add` and show full log. Also, please provide `dvc doctor` output.

**Comment by JoaoDeDynam** [comment]
<img width="434" alt="Screen Shot 2021-04-29 at 3 40 56 PM" src="https://user-images.githubusercontent.com/83429637/116627072-4bff0e00-a901-11eb-836a-727026ab81c7.png">
This is my dvc doctor ouput

**Comment by JoaoDeDynam** [comment]
dvc add -v <path_to_file>
2021-04-29 15:41:28,455 DEBUG: Check for update is enabled.
Adding...                                                                                                                                                                             
2021-04-29 15:41:28,875 ERROR: unexpected error - module 'numpy' has no attribute 'float64'
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.run()
  File "/usr/local/lib/python3.9/site-packages/dvc/command/add.py", line 21, in run
    self.repo.add(
  File "/usr/local/lib/python3.9/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/dvc/repo/add.py", line 102, in add
    repo.check_modified_graph(stages)
  File "/usr/local/lib/python3.9/site-packages/dvc/repo/__init__.py", line 343, in check_modified_graph
    build_graph(existing_stages + new_stages)
  File "/usr/local/lib/python3.9/site-packages/dvc/repo/graph.py", line 93, in build_graph
    import networkx as nx
  File "/usr/local/lib/python3.9/site-packages/networkx/__init__.py", line 64, in <module>
    import networkx.readwrite
  File "/usr/local/lib/python3.9/site-packages/networkx/readwrite/__init__.py", line 15, in <module>
    from networkx.readwrite.graphml import *
  File "/usr/local/lib/python3.9/site-packages/networkx/readwrite/graphml.py", line 344, in <module>
    class GraphML:
  File "/usr/local/lib/python3.9/site-packages/networkx/readwrite/graphml.py", line 374, in GraphML
    (np.float64, "float"),
AttributeError: module 'numpy' has no attribute 'float64'
------------------------------------------------------------
2021-04-29 15:41:29,137 DEBUG: Version info for developers:
DVC version: 2.0.18 (pip)
---------------------------------
Platform: Python 3.9.4 on macOS-10.15.7-x86_64-i386-64bit
Supports: http, https, s3
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-04-29 15:41:29,139 DEBUG: Analytics is enabled.
2021-04-29 15:41:29,244 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/9m/xx24sxdx2fvb9s5q5rt1jxy00000gn/T/tmpma81ujhk']'
2021-04-29 15:41:29,246 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/9m/xx24sxdx2fvb9s5q5rt1jxy00000gn/T/tmpma81ujhk']'

**Comment by efiop** [comment]
@JoaoDeDynam Could you run `pip check` and show the results?

Likely your environment is corrupted, you've probably installed some package that requires an older numpy, which made networkx break. Or maybe there is a similar situation with networkx.

If you are not using dvc as a python library and only use it through CLI, consider installing dvc from homebrew `brew install dvc`, that way it will have itsown separate isolated environment that won't conflict with your other python packages.

**Comment by JoaoDeDynam** [comment]
pip3 check
timezonefinder 5.0.0 requires numpy, which is not installed.
tifffile 2021.1.14 requires numpy, which is not installed.
snuggs 1.4.7 requires numpy, which is not installed.
scipy 1.6.0 requires numpy, which is not installed.
scikit-image 0.18.1 requires numpy, which is not installed.
rasterio 1.1.8 requires numpy, which is not installed.
pywavelets 1.1.1 requires numpy, which is not installed.
pandas 1.2.0 requires numpy, which is not installed.
opencv-python 4.5.1.48 requires numpy, which is not installed.
matplotlib 3.3.3 requires numpy, which is not installed.
imageio 2.9.0 requires numpy, which is not installed.
flirimageextractor 1.4.0 requires numpy, which is not installed.
bottleneck 1.3.2 requires numpy, which is not installed.
johnathan@Johnathans-MBP workbench % pip check
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
matplotlib 1.3.1 requires nose, which is not installed.
matplotlib 1.3.1 requires tornado, which is not installed.

**Comment by JoaoDeDynam** [comment]
At this point, the team has not decided on using the Python API, but it very likely could become one of our goals. At this point we want to take advantage of the large file storage capabilities and likely use the CLI with Jenkins. We run everything in docker-compose, so I don't really need the pip package installed locally, so I can uninstall that if it is what is causing the issue.

**Comment by karajan1001** [comment]
> pip3 check
> timezonefinder 5.0.0 requires numpy, which is not installed.
> tifffile 2021.1.14 requires numpy, which is not installed.
> snuggs 1.4.7 requires numpy, which is not installed.
> scipy 1.6.0 requires numpy, which is not installed.
> scikit-image 0.18.1 requires numpy, which is not installed.
> rasterio 1.1.8 requires numpy, which is not installed.
> pywavelets 1.1.1 requires numpy, which is not installed.
> pandas 1.2.0 requires numpy, which is not installed.
> opencv-python 4.5.1.48 requires numpy, which is not installed.
> matplotlib 3.3.3 requires numpy, which is not installed.
> imageio 2.9.0 requires numpy, which is not installed.
> flirimageextractor 1.4.0 requires numpy, which is not installed.
> bottleneck 1.3.2 requires numpy, which is not installed.
> johnathan@Johnathans-MBP repo % pip check
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
> matplotlib 1.3.1 requires nose, which is not installed.
> matplotlib 1.3.1 requires tornado, which is not installed.

Yes, NumPy is required for DVC.

**Comment by efiop** [comment]
> pip3 check
> timezonefinder 5.0.0 requires numpy, which is not installed.
> tifffile 2021.1.14 requires numpy, which is not installed.
> snuggs 1.4.7 requires numpy, which is not installed.
> scipy 1.6.0 requires numpy, which is not installed.
> scikit-image 0.18.1 requires numpy, which is not installed.
> rasterio 1.1.8 requires numpy, which is not installed.
> pywavelets 1.1.1 requires numpy, which is not installed.
> pandas 1.2.0 requires numpy, which is not installed.
> opencv-python 4.5.1.48 requires numpy, which is not installed.
> matplotlib 3.3.3 requires numpy, which is not installed.
> imageio 2.9.0 requires numpy, which is not installed.
> flirimageextractor 1.4.0 requires numpy, which is not installed.
> bottleneck 1.3.2 requires numpy, which is not installed.

It says that numpy is not installed. Something is going on with your environment, you could try recreating it and installing it from scratch. Or consider homebrew package for your mac or https://github.com/iterative/dvc-s3-repo deb/rpm package for your docker image.

Closing since it is a particular env problem. Let us know if one of workarounds works for you.

**Comment by JoaoDeDynam** [comment]
Homebrew did the trick here
