### ISSUE TITLE
`ERROR: failed update data - <...> is git-ignored.` - Space in empty line in `.gitignore` breaks `dvc update`?

### ISSUE THREAD

**Issue by rabefabi** [iterative/dvc#5902]
# Bug Report

The following command fails:

```bash
$ dvc update data/ham10000.dvc
ERROR: failed update data - 'data/ham10000.dvc' is git-ignored. 
```

## Description

After having upgraded from dvc version 1 to version 2.0.18  the error above appeared, with no other changes to the repo.

The problem is, the `data/ham10000.dvc`  is not git-ignored. I verified this by changing that file and these changes being noticed by `git status`.

I then played around with my `.gitignore`, and realized that one empty line had a space (` `) in it:

Snippet from `.gitignore` which throws an error:

```.gitignore
# No notebooks shall be tracked, this is done via jupytext
**/*.ipynb
 
# Ignore all reports
reports/
```

`.gitignore` with space removed, which does not throw an error:

```.gitignore
*/.ipynb_checkpoints/*
# No notebooks shall be tracked, this is done via jupytext
**/*.ipynb

# Ignore all reports
reports/
```

### Reproduce

If the error description above is not reproducible for you, I'd be happy to create a more elaborate example, I just don't have the time for it right now.

### Expected

Since gitignore doesn't care about spaces in empty lines, I expected dvc to do the same

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.0.18 (conda)
---------------------------------
Platform: Python 3.8.8 on Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.10
Supports: gdrive, hdfs, http, https, s3, ssh, oss
Cache types: hardlink, symlink
Cache directory: 9p on C:\
Caches: local
Remotes: ssh
Workspace directory: 9p on C:\
Repo: dvc, git
```

**Comment by efiop** [comment]
Hi @rabefabi !

Could you show `git check-ignore data/ham10000.dvc`, please? Are you sure you didn't gitignore the whole `data` and then `git add -f`-ed that dvc file?

**Comment by rabefabi** [comment]
Hi @efiop ,

Thanks for taking the time!

I ran the command:

```bash
$ git check-ignore data/ham10000.dvc
$ git check-ignore data/ham10000
data/ham10000
$ git check-ignore __pycache__
__pycache__
``

The lower 2 commands were my sanity checks on actually ignored files/directories .

> Are you sure you didn't gitignore the whole data and then git add -f-ed that dvc file?

To be honest, that might have happened in the past. But if that were the case, wouldn't the output above be different, and wouldn't git ignore any future changes to the `ham10000.dvc` unless I force-add it again?

If this issue isn't as reproducible as I hoped, I'm happy to verify the problem on a minimal example or to dig deeper into my project, but this will have to wait till the end of next week :/

Thanks again!

**Comment by efiop** [comment]
@rabefabi Thanks! Btw, just to clarify, you are not using git submodules and you are not using dvc subrepos (.dvc dirs in dirs other than git repo root), right?

**Comment by efiop** [comment]
Closing as stale.
