### ISSUE TITLE
dvc pull: Misleading error on dvc pull [ssh] with windows and RSA key with keyphrase

### ISSUE THREAD

**Issue by AssassinTee** [iterative/dvc#5908]
# Bug Report

## Misleading SSH-error

dvc pull: Misleading SSH-error

## Description

I use dvc with an ssh server and generated an ssh-`RSA`-key WITH PASSPHRASE to login, it works all fine on linux so I know the ssh server is running.

I kopied my key to windows and ran into the following error:

```
User: dvc pull
ERROR: unexpected error - encountered RSA key, expected OPENSSH key
```

After a lot of debuging and searching I set

```
dvc remote modify <my_remote> ask_password true
```
and dvc promted me for a keyphrase for my rsa key and everything was working as expected

### Reproduce

1. Be on Windows
2. Use dvc with an ssh-storage remote
3. Use a SSH-RSA-Key WITH PASSPHRASE for authentification
4. Have ask_password set to false
5. `dvc pull`

### Expected

An error message, which is not wrong:
```
You don't have a password configured. Your ssh-key might have a passphrase. Set ask_password to true or configure the password with ...
```

### Environment information

**Output of `dvc doctor`:**

```console
Platform: Python 3.8.8 on Windows-10-10.0.19041-SP0
Supports: http, https, ssh
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: ssh, ssh
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by efiop** [comment]
Hi @AssassinTee !

So it needs a passphrase on windows, but doesn't need it on linux? Do you have it in a keychain on linux?

The issue comes from paramiko not being able to tell us that we need to ask for a password, hence why we have an explicit `ask_password` option right now :(

**Comment by AssassinTee** [comment]
My linux is configured to ask me automatically on system start/first bash start for the passphrase and the rest is handled by the ssh-agent. I was never asked for a password by dvc or changed the settings there

**Comment by isidentical** [comment]
We have recently refactored our SSH infrastructure, it would be really nice if you could test again by installing from the master branch and let us know if you still continue to experience this issue.
