### ISSUE TITLE
exp show: show only changed parameters

### ISSUE THREAD

**Issue by ciaochiaociao** [iterative/dvc#5966]
Currently I have tens of parameters in my `params.yaml`. After I `dvc exp run --queue` several experiments and `dvc exp show`, it is hard for me to recognize the parameters I just set. I know I could use `--include-params or --exclude-params`, but it somehow just takes me some efforts to list my previous commands, recall what I have changed in `params.yaml` before queuing. It would be nice to just show the **changed** parameters in `dvc exp show`, e.g., via `dvc exp show --only-changed`

**Comment by karajan1001** [comment]
@ciaochiaociao Hello, first thanks for your suggestion.

Currently `dvc exp show` can show all the parameters metrics of all experiments in a table.`dvc exp diff` can compare two experiments' parameters and metrics and only show the different ones. Maybe this command can help you now?

**Comment by ciaochiaociao** [comment]
Yes, right now I kind of write a bash script to automate running `dvc exp diff` over all my experiments compared to HEAD.
