### ISSUE TITLE
s3: performance implications of s3fs

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#5969]
This issue is for tracking the progress related s3fs/aiobotocore issues for the performance degradations that we might experience.

- [x] [exists() on non-existent files](https://github.com/dask/s3fs/issues/470)
- [ ] [HeadObject calls are slower than the regular boto](https://github.com/aio-libs/aiobotocore/issues/866)

**Comment by isidentical** [comment]
import time itself is not something that affects greatly, but still there is `~0.3` seconds (on HDD, might be different for a SSD user) startup overhead;

## `import boto3`
![image](https://user-images.githubusercontent.com/47358913/117134713-96273a00-adae-11eb-8816-9f85a7e7ea46.png)

## `import aiobotocore, boto3`
![image](https://user-images.githubusercontent.com/47358913/117134781-b35c0880-adae-11eb-8c99-f3be96b1bb1b.png)

**Comment by isidentical** [comment]
One important thing after I noticed working with the dataset-private-registry is that the listing take some time to happen since fsspec doesn't have iterators (not for ls/find) and I feel like this is bad for UX. For small sets, it is not that noticeable but if you have one million files then it is obvious that the dvc is blocked and there is no reactivity of any sort.  

Regarding that, there is not much we can do on the dvc side though if we consider that the `find()` is mostly used for multi-level directories (like our remote cache) then we can do a first level `ls()` and then call `find()` with the each sub level. This definitely increases the responsiveness, and at the same time if we parallelize these calls I think it might be faster than the original `walk_files()` since now it is making N listings concurrently. CC: @efiop @shcheklein

**Comment by efiop** [comment]
@isidentical My guess is that iterators should be there, I suppose they were simply not implemented yet. We should be able to implement them for us and possibly send the patch back to upstream, let's create an issue and ask about it.

**Comment by isidentical** [comment]
> but that is not really walk_files anymore, more of a listing by prefix that we use for estimation.

What do you mean by that?

**Comment by efiop** [comment]
@isidentical Ah, sorry, I'm wrong. Didn't notice the `find` in the executor. Still, it is rather tailored to handle our specific remote dir structure, so it is no longer a general `walk_files` (that is expected to return an iterator) and we could use such a workaround directly where needed. The results are very interesting though.

**Comment by isidentical** [comment]
I started writing a proposal as an issue to the fsspec repo with describing the potential APIs and how would they work

**Comment by isidentical** [comment]
we have narrowed down the issue of when the region is not specified, the underlying boto implementation doing extra work to locate the bucket region which resulted with the aiohttp connection being halted down. so we end up paying the creation of the connection for each request, which is making stuff terrible. 

https://github.com/aio-libs/aiobotocore/issues/866#issuecomment-848185110

we might implement some sort of bucket-region caching, though it is just basically a theory (didn't had time to actually test it out).

**Comment by isidentical** [comment]
See: https://github.com/dask/s3fs/pull/495

**Comment by isidentical** [comment]
Hopefully this will cut out a lot of import time; https://github.com/benoitc/gunicorn/issues/2613
