### ISSUE TITLE
Missing dvc show in current version

### ISSUE THREAD

**Issue by rahulguptajss** [iterative/dvc#598]
Hi,

I am unable to generate DAG in current release 0.9.3. Is it removed?

**Comment by efiop** [comment]
Hi @rahulguptajss !

Do you mean autotomatic dependencies? If so, then yes, it was removed in 0.9.0 in favor of explicit dependencies notation.

**Comment by rahulguptajss** [comment]
yes, I wanted to use dvc show pipeline command. Can you confirm the command in 0.9.3 for the same.

Thanks.

**Comment by efiop** [comment]
@rahulguptajss ah, I see. Unfortunately 'dvc show pipeline' was also removed in 0.9.0, we felt like it was way too raw and it required additional dependencies which were not very easy to install everywhere. We do think about bringing it back in the future though.

**Comment by rahulguptajss** [comment]
ok thanks for the update. dvc docs seems to be out of date currently.

https://dataversioncontrol.com/docs/#commands_command_reference_show

**Comment by efiop** [comment]
@rahulguptajss Oops, sorry for that. We will be sure to update that. Thanks for the feedback!

**Comment by rahulguptajss** [comment]
Thank you for your quick responses.

**Comment by efiop** [comment]
@rahulguptajss And thank you for the feeback!

I'll leave this issue open while documentation is not fixed.

**Comment by efiop** [comment]
Turns out site doesn't auto-update from out docs/doc.rst, so the issue is not fully resolved yet. Keeping open for now.

**Comment by dmpetrov** [comment]
I'll take care of it.

**Comment by rahulguptajss** [comment]
Can you please confirm if there is any plan to reintroduce the GUI feature of DVC show . Currently if project is huge then generating and making changes to pipeline is very painful due to lack of view.

**Comment by efiop** [comment]
@rahulguptajss I can 100% confirm that. We are fully aware of the need to visually represent repository structure. We are currently considering a few options, including the possibility to re-introduce refactored `dvc show`. I suppose we are going to have something ready in the nearest few releases. Thank you for your interest!

**Comment by efiop** [comment]
@rahulguptajss Btw, it seems like you are doing some pretty interesting stuff with jenkins and dvc. We are thinking about something related and would love to discuss it. Would you mind discussing it in more details? My email is kupruser@gmail.com, feel free to drop a message if you are interested. We could arrange a skype call or something.

**Comment by rahulguptajss** [comment]
yes sure. I'll drop you an email on what we have been trying to do and some recommendations about dvc.

**Comment by efiop** [comment]
@rahulguptajss Thank you! Looking forward to it!

**Comment by efiop** [comment]
Fixed https://dvc.org/documentation .

**Comment by efiop** [comment]
Hi @rahulguptajss !

Just wanted to let you know that we now have ASCII DAG visualization. Here is an example https://dvc.org/doc/get-started/visualize . Please feel free to give it a try :slightly_smiling_face: 

Thanks,
Ruslan
