### ISSUE TITLE
License confirmation for `dvc get` and `dvc import`

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc#5986]
There are various licenses for downloadable datasets. `dvc get` and `dvc import` can check if there is a `LICENSE` file within a tracked directory and print this license, and ask the user for confirmation before download. This allows us to conform with _attribution_ and _copyright_ requirements in licenses like MIT or Apache.

For a Git repository directory in the form

```
.
├── README.md
├── fashion-mnist
│   ├── LICENSE
│   ├── raw
│   │   ├── t10k-images-idx3-ubyte.gz
│   │   ├── t10k-labels-idx1-ubyte.gz
│   │   ├── train-images-idx3-ubyte.gz
│   │   └── train-labels-idx1-ubyte.gz
│   └── raw.dvc
```

we use `dvc get https://github.com/iterative/dataset-registry/fashion-mnist/raw.dvc`  to get the dataset. 

At this point, instead of directly downloading, DVC can check whether there is a `LICENSE` file in the directory `fashion-mnist/` and present it to the user for confirmation. The same is applicable to `dvc import`. 

I think this should be the default behavior and an option like `--skip-license-confirmation` is also needed for scripts. 

This provides a basis to provide all public datasets with different license restrictions in a single dataset registry.

**Comment by pmrowla** [comment]
This sounds like something that is just on the user to determine rather than DVC?

Git doesn't prompt you to comply with a license on `git clone` or when you add an external git repo as a submodule. (Or when I just use `wget` or `curl` to download a file directly from someone's github/gitlab/etc repo)

**Comment by pmrowla** [comment]
DVC doesn't host or distribute anything though, it's just tooling. I guess the line is blurred a bit when it comes to Studio, but it still seems to me like anything on the licensing/attribution side of things would be a Studio issue, and not a core DVC issue (similar to the difference between github/gitlab and git).

**Comment by iesahin** [comment]
DVC is not a package manager, but a _dataset manager._

DVC has this functionality as _shared remote._ The one piece missing is associating metadata like description, license, etc. with `.dvc` files. 

> Agree that it could be a need, hypothetically. But I'd wait to see if any users or potential users express this first.

I doubt anybody will ask it first 😄 `LICENSE` files is necessary only when you index and distribute the datasets. I doubt anyone other than us would do that. 

"We have a datasets collection in `datasets.dvc.org` and you can add yours with a PR, `import` any of them in your pipelines, use in any library or language, or simply `get` them to hack" would be a nice feature for anyone who works with data. It will increase the adoption extensively. 

If another CLI tool would be used for this, it would need DVC's features.

**Comment by dberenbaum** [comment]
@iesahin I think @pmrowla is suggesting that this could be built on top of DVC but be considered a separate product. 

It seems like this issue is more of a feature request for a public dataset registry, with license confirmation being one of the requirements of that feature request. Would you agree @iesahin? Am I missing anything?
