### ISSUE TITLE
dvc pull: Computing md5 for a large file 

### ISSUE THREAD

**Issue by korshunovdv** [iterative/dvc#5996]
# Bug Report

## Description

I add some folder with large files to .dvcignore. 

~ dvc check-ignore **/bags                                                         
... data/bags_historical/bags

Then when I try to pull data, DVC calculate hash for files from ignored directories.
I have real large files, and calculating hash spend a lot of time. 
I ques it shouldn't calculate hash for ignored folder.

~ dvc pull                
... Computing md5 for a large file 'data/bags_historical/bags/kalibr_03_2020-06-01_kalibr_2020-06-01-16-38-16_0.bag'. This is only done once.                                                                              
... Computing md5 for a large file 'data/bags_historical/bags/kalibr_04_2021-01-18_snow_2021-01-18-15-37-39_0.bag'. This is only done once.                                                           
...

### Environment information

DVC version: 1.11.16 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.0.0-32-generic-x86_64-with-glibc2.10
Supports: http, https, s3, ssh
Cache types: hardlink, symlink
Caches: local
Remotes: ssh, s3, ssh
Repo: dvc, git

**Comment by pmrowla** [comment]
Hi @korshunovdv can you try using the latest version of DVC (2.1.0) and see if you still experience the issue? 1.11.16 is pretty outdated at this point and 1.x in general is no longer supported
