### ISSUE TITLE
Expand Python API

### ISSUE THREAD

**Issue by akbir** [iterative/dvc#5999]
Is there a way to  call dvc.api.pull from the python api? 

This would be very useful in use cases where models needed to pulled and run under a larger set of tasks.

**Comment by pmrowla** [comment]
It's not part of the official `dvc.api` module, but our internal `dvc.repo.Repo` class is stable and can be used to programmatically run DVC commands.

So you can do
```py
from dvc.repo import Repo

repo = Repo(".")
repo.pull()
```

If you refer to the code for the CLI [dvc pull](https://github.com/iterative/dvc/blob/da0f0406fbb924f7831b98afb763e6c9b1323e22/dvc/command/data_sync.py#L25) command you can see how the CLI args get translated into the `repo.pull` function parameters

**Comment by Clayrisee** [comment]
> It's not part of the official `dvc.api` module, but our internal `dvc.repo.Repo` class is stable and can be used to programmatically run DVC commands.
> 
> So you can do
> 
> ```python
> from dvc.repo import Repo
> 
> repo = Repo(".")
> repo.pull()
> ```
> 
> If you refer to the code for the CLI [dvc pull](https://github.com/iterative/dvc/blob/da0f0406fbb924f7831b98afb763e6c9b1323e22/dvc/command/data_sync.py#L25) command you can see how the CLI args get translated into the `repo.pull` function parameters

Hai @pmrowla , is it supports remote repository?

**Comment by pmrowla** [comment]
@Clayrisee what do you mean by remote repository? Using `Repo.pull` works the same way as `dvc pull`, so you need a local DVC repository, and then you pull from DVC remotes into that local repository.

**Comment by Clayrisee** [comment]
> @Clayrisee what do you mean by remote repository? Using `Repo.pull` works the same way as `dvc pull`, so you need a local DVC repository, and then you pull from DVC remotes into that local repository.

What I mean is if I want to read the dataset from another remote repository and download the dataset into the current repository.

Like if I have 2 repositories, 1 repository for the dataset and 1 for the trainer, I want to read the dataset repository with the given URL git dataset repository and automatically pull the dataset into the trainer repository. is it possible to achieve this?

**Comment by pmrowla** [comment]
It sounds like you are looking for `dvc import` and not `dvc pull`: https://dvc.org/doc/command-reference/import#import

To do it from python you can use `Repo.imp()` (see the code for `dvc import`)
https://github.com/iterative/dvc/blob/23e62a9ff7970de697f6a1ebbf55e6fc1538dee7/dvc/commands/imp.py#L15

**Comment by Clayrisee** [comment]
> It sounds like you are looking for `dvc import` and not `dvc pull`: https://dvc.org/doc/command-reference/import#import
> 
> To do it from python you can use `Repo.imp()` (see the code for `dvc import`)
> 
> https://github.com/iterative/dvc/blob/23e62a9ff7970de697f6a1ebbf55e6fc1538dee7/dvc/commands/imp.py#L15

Awesome! Thanks for your help!
