### ISSUE TITLE
cache dir: no longer needed; deprecate?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#6003]
> From https://github.com/iterative/dvc.org/issues/2465#issuecomment-840248507

`dvc config cache.dir` seems to behave exactly the same now:

```console
$ dvc config cache.dir relative-dir
$ dvc config cache.dir relative-dir
[cache]
    dir = ../relative-dir
$ dvc cache dir relative-dir
$ dvc config cache.dir relative-dir
[cache]
    dir = ../relative-dir

$ dvc cache dir ../parent/sibling/dir
$ cat .dvc/config
[cache]
    dir = ../../parent/sibling/dir
$ dvc cache dir ../parent/sibling/dir
$ cat .dvc/config
[cache]
    dir = ../../parent/sibling/dir
```

**Comment by jorgeorpinel** [comment]
p.s. when did this change? We totally missed this in docs.

**Comment by shcheklein** [comment]
I think this is a regression if they behave the same way

**Comment by jorgeorpinel** [comment]
Hi @skshetry (since I see you triaged) what do you think may be the answer to this Q? Thanks

**Comment by efiop** [comment]
Might be a regression, need to take a closer look.
