### ISSUE TITLE
Adding Zenodo as a Remote

### ISSUE THREAD

**Issue by 4aHxKzD** [iterative/dvc#6009]
Is there a reason for not having Zenodo as a remote (for data) apart from nobody having dedicated time to develop the feature?

I know that that Zenodo creates a DOI for each version of a data set, which makes it harder do update the "repository" with `push`,
but they provide a DOI that represents every version of a file and points to the latest. Maybe that could be used as a remote.

I searched older Issues, but it seems that nobody suggested this feature, so I don't know if it out of scope for this project or if there really isn't any interest from the community.

Thanks

**Comment by efiop** [comment]
Hi @4aHxKzD 

Indeed, we just didn't receive any requests for it. I'm personally not familiar with zenodo as storage. If one would like to add support for it, it would require first implementing an fsspec-compatible https://github.com/intake/filesystem_spec/ filesystem in his own repository and dvc will then be able to use it as a plugin in the near future https://github.com/iterative/dvc/issues/5162.

**Comment by 4aHxKzD** [comment]
> Indeed, we just didn't receive any requests for it. I'm personally not familiar with zenodo as storage.


I think that we could use plain HTTP remote, but the repo would need to have a different remote for each data file. I already tried using `dvc pull` using the URL of a specific version of a file and it works. But `push` would be harder since we would need to create a new version of the file in Zenodo's platform, which they consider a separate object with a different DOI.

**Comment by efiop** [comment]
@4aHxKzD Seems somewhat similar to ipfs https://github.com/iterative/dvc/pull/4736 , we had similar problems there. I'm not sure how to use such remotes right now, they are just too unconventional compared to the rest of remotes.

**Comment by pmrowla** [comment]
This seems related to https://github.com/iterative/dvc/issues/5450 - I'm not too familiar with Zenodo, but it looks more like it would be suited to keeping track of "snapshots" of the entire DVC repo state, rather than for versioning live data as a regular DVC remote?

**Comment by 4aHxKzD** [comment]
@pmrowla It probably is more suited to the first case you mention, but I'm more interested in the latter.
