### ISSUE TITLE
S3 configpath is not properly treated as a relpath

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#6020]
From reading `dvc/config.py` I see that `configpath` option of S3 configuration is not included into `Config._map_dirs()`. This will mean that any relative paths there would be resolved concerning current dir not the dir config file is in.

So the fix is to include `configpath` into `Config._map_dirs()`. 

The more complex fix, which will save from future errors of this type is removing duplication. I.e. using some subtype of `str`, in `dvc/config_schema.py` to mark things to be handled specially. Deducing schema in `Config._map_dirs()` automatically.

**Comment by shcheklein** [comment]
@Suor what is the priority for this from the Studio perspective?

**Comment by Suor** [comment]
Not an issue for Studio. I found it reading dvc code for an unrelated issue, which I've already fixed.
