### ISSUE TITLE
Revert temporary azure changes and update adlfs to 0.7.5

### ISSUE THREAD

**Issue by friggog** [iterative/dvc#6023]
As of https://github.com/dask/adlfs/pull/229 the issue with event loops in adlfs is resolved, the temporary solution from @isidentical  for DVC in https://github.com/iterative/dvc/pull/5958 can be reverted with adlfs requirement pinned to 0.7.5 instead of 0.7.1

I've tested this with DVC 2.1.0 and manually installed adlfs 0.7.5 and everything seems to work

PS it would be great to have this (or the previous hack) in a DVC release soon so I can update my packages to make use of it! 😄

**Comment by isidentical** [comment]
Pre-requisite: https://github.com/intake/filesystem_spec/pull/658

**Comment by isidentical** [comment]
Pre-requisite: intake/filesystem_spec/pull/671
