### ISSUE TITLE
Repo api: be able to distinguish between external repo and local repo

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6025]
I just noticed that in Viewer, the `dvc-bench` was failed to parse because of https://github.com/iterative/dvc-bench/issues/255.

The gitignore issue should not affect the repos opened from Git, as it is supposed to only affect the local workspace.
But, Studio opens the cloned repo from the workspace rather than from git, the checks get applied and fail to parse for the specific commit. 

See: https://studio.iterative.ai/user/skshetry/views/dvc-bench-zd96w2mobj

---

I'd propose to set some state, eg: `repo.external = True` when opening from git repo in this case and use that to differentiate if it should be checked or not.

Though it's not a bug on our side, we just need to provide appropriate ways to handle that.

cc @Suor

**Comment by efiop** [comment]
@skshetry What is `external` though? The one that is not opened from a local path? Or any that is cloned and opened and not just opened?

**Comment by Suor** [comment]
I don't really understand why dvc fails at all. As far as I remember from original discussion about lock files they were supposed to be optional to commit. Many things might still work, e.g. metrics or plots collection. This would be enough for Viewer.

**Comment by skshetry** [comment]
> @skshetry What is `external` though?

The naming might be bad, but essentially the repos that should be considered as an `external` repo even if it's not.

**Comment by karajan1001** [comment]
Excuse me, I don't know why not a remote repo work with its own gitignore/dvcginore? In my opinion, they are components of the repo. Discriminate them here make things more complex.

**Comment by dberenbaum** [comment]
> I don't really understand why dvc fails at all. As far as I remember from original discussion about lock files they were supposed to be optional to commit. Many things might still work, e.g. metrics or plots collection. This would be enough for Viewer.

It seems like anything tracked by Git should get parsed, right? Seems somewhat related to other discussions about when parsing should fail (cc @pared). What commands or calls is Studio making that are failing?

> Excuse me, I don't know why not a remote repo work with its own gitignore/dvcginore? In my opinion, they are components of the repo. Discriminate them here make things more complex.

Could you elaborate more? I'm not following how gitignore/dvcignore are related.

**Comment by karajan1001** [comment]
I agreed with @efiop, we should distinguish gitignore files already been and not tracked. And maybe Dvcignore suffers from a same problem.

**Comment by Suor** [comment]
> It seems like anything tracked by Git should get parsed, right? Seems somewhat related to other discussions about when parsing should fail (cc @pared). What commands or calls is Studio making that are failing?

[FileIsGitIgnored](https://sentry.io/organizations/iterative/issues/2400969496/?project=5220519&referrer=github_integration) is raised during stage collection, which is the first thing DVC does for most ops. Studio is trying to collect metrics, params, plots and files info via `Repo.metrics.show()` and friends. All of the above require stage collection.

**Comment by dberenbaum** [comment]
Yup, @Suor, I was agreeing with you that DVC should still collect all of those if they are Git tracked, even if `dvc.lock` is missing or ignored.

**Comment by Suor** [comment]
Created an issue about stage collection errors confinement https://github.com/iterative/dvc/issues/6042

**Comment by skshetry** [comment]
@efiop ping

**Comment by efiop** [comment]
@skshetry Really sorry for the delays, I seem to be losing context here and end up trying to get back into it only to get distracted again. Looking into it...

**Comment by skshetry** [comment]
@efiop, if we go with #6291, this is no longer an issue. 🙂

**Comment by efiop** [comment]
@skshetry Gotcha. Yeah, sounds like it is great that all of these issues came up together :slightly_smiling_face: So let's try #6291 and if we stick to it, we'll close this one, right?

**Comment by skshetry** [comment]
Closing as stale.

**Comment by skshetry** [comment]
Thanks @daavoo.
