### ISSUE TITLE
installation from the master on a clean environment raises some errors

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#6030]
```
ERROR: networkx 2.5.1 has requirement decorator<5,>=4.3, but you'll have decorator 5.0.9 which is incompatible.
```
[full logs](https://gist.github.com/isidentical/918da389e97e7c1b664d6a91ed522a78)

related: https://github.com/networkx/networkx/issues/4718

**Comment by skshetry** [comment]
From the log, it looks like it's an issue with `pip` itself on that it failed to resolve dependency properly (or, failed to backtrack). It does install `networkx==2.5.1` which requires `decorator<5,>=4.3` but pip does not install it for some reason. We haven't had any new release on networkx, so the state should be same, but in the CI, I see that [it does install the 4.4.2 version](https://github.com/iterative/dvc/runs/2845429056#step:6:439) now, so might have been fixed.

@isidentical, did that happen in the GitHub Actions?

**Comment by isidentical** [comment]
> @isidentical, did that happen in the GitHub Actions?

No, as far as I can remember it happened on a clean machine with `python3.8` and the default pip version that came with it (don't remember which one was that). If this is unreproducible, feel free to drop it.

**Comment by skshetry** [comment]
If it was the one that com

**Comment by skshetry** [comment]
With networkx2.6 dropping `decorator` as a requirement, the decorator should no longer be an issue. `gcsfs` uses it (for no reason), we could consider sending a patch in the future if it causes us any issue.
