### ISSUE TITLE
output: don't raise RemoteCacheRequiredError when collecting repo stages

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#6031]
I have an s3 thing dvc added to a repo and I remove the remote from the repo config to prevent any network access during stage collection. Then I try to collect metrics with `repo.metrics.show()`, but get `RemoteCacheRequiredError`, which is not really required for what I am trying to do.

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.1.0 (pip)
---------------------------------
Platform: Python 3.8.2 on Linux-5.8.0-50-generic-x86_64-with-glibc2.27
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache types: hardlink, symlink
Cache directory: ecryptfs on /home/suor/.Private
Caches: local
Remotes: None
Workspace directory: ecryptfs on /home/suor/.Private
Repo: dvc, git

```

More context is [in Sentry](https://sentry.io/organizations/iterative/issues/2402555741/?project=5220519&referrer=slack)

**Comment by efiop** [comment]
For the record: we raise that in `Output.__init__`, with the intention of warning user about external cache requirement for external outputs. Need to find a better way to handle that.

**Comment by Suor** [comment]
Need to be moved to either CLI code or some code that actually uses that remote cache, e.g. some `.exists()` call.

**Comment by efiop** [comment]
Will get back to this after https://github.com/iterative/dvc/pull/5984

**Comment by karajan1001** [comment]
Might similar to first dvc add some data then use `dvcignore` to ignore it.

**Comment by dberenbaum** [comment]
@Suor Is this still an issue? I don't have access to those sentry logs.

**Comment by Suor** [comment]
It looks like this is not thrown in dvc 2.9.5 anymore, so I will be able to remove my monkey patch. Thanks.
