### ISSUE TITLE
ci/tests: test environment should ignore current user's global/system configs

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#6043]
When we run our unit/func test suite it should run in a completely clean & reproducible environment - meaning the test environment should also ignore the running user's global and system level DVC configs if any exist.

- For disabling the user's global config we should just override `$HOME` (or the windows equivalent env vars) so that it points to an empty temp directory (or some default template dir that we set up explicitly for our CI/test environment).
- For system configs we could introduce something similar to git's `$GIT_CONFIG_NOSYSTEM` env var, and enable it in our test environment

**Comment by karajan1001** [comment]
Agreed. I used to work on a `dvc config` PR last year, and suffer a lot from global config caused problem when running tests.
