### ISSUE TITLE
exp show: show names for the queued experiments

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc#6050]
It would be great to see the name of a queued experiment. Right now if we run, for example
```
dvc exp run --queue -S model.cnn.dropout=0.25 -n named-one
```
the table below won't show it's name right away:
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/6797716/119343471-2aded280-bc9f-11eb-9325-d7a4e788986f.png">
only after we run it with `dvc exp run --run-all`:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/6797716/119343665-6ed1d780-bc9f-11eb-9982-389c5a4dd55f.png">

We could live fine without names, but if for example we want to review multiple queued experiments with `dvc exp show` and look for what we forgot to add to the queue, it would be helpful to see them.

Another use case which is not supported now, AFAK, is to remove queued experiments. If I added few experiments, I may want to remove one of them before running them all. Right now I need to reset all queued experiments with `dvc exp remove --queue` and add required ones again. This removal would be convenient to do if we could reference the queued experiments by their names. If it seems like a valid use case and dvc has no such feature, I can create a feature request.

**Comment by dberenbaum** [comment]
#5965 also has some loosely related discussion about whether the final exp name should be shown in the queue from the beginning. @pmrowla what do you think? Not sure how important this is or how difficult to implement, but it does seems like it's a strict improvement on current behavior.

**Comment by jorgeorpinel** [comment]
> If the user is specifying a name with -n/--name we can display it for queued experiments.

👍

**Comment by dberenbaum** [comment]
> Another use case which is not supported now, AFAK, is to remove queued experiments. If I added few experiments, I may want to remove one of them before running them all. Right now I need to reset all queued experiments with `dvc exp remove --queue` and add required ones again. This removal would be convenient to do if we could reference the queued experiments by their names. If it seems like a valid use case and dvc has no such feature, I can create a feature request.

@aguschin This part got lost in the discussion, but see #6157.

@pmrowla I think it would be helpful to add this to the loose ends to clean up for experiments. It's not clear if or when we will have a separate `exp queue` command, or whether that will address this problem since the queue might still also show in `exp show`. How much work do you think it is to show named experiments in the queue?

**Comment by pmrowla** [comment]
> @pmrowla How much work do you think it is to show named experiments in the queue?

@dberenbaum this is pretty much just a one liner UI change. We already have names for queued experiments internally, we just don't show them in the UI right now.
