### ISSUE TITLE
dvc add: case sensitivity on windows command prompt leads to "does not overlap with base path" error

### ISSUE THREAD

**Issue by Huite** [iterative/dvc#6057]
# Bug Report

## Description

I've initialized a dvc repo and when I try to add the first file, it gives me an error. I'm on Windows, and it gives me this error:

```
(main) c:\tmp\materials\my-project>dvc add data.csv
Adding...
ERROR: Path: c:\materials\my-project does not overlap with base path: C:\materials\my-project
```

Note the difference in upper case versus lower case on the drive letter. I'm guessing it's as straightforward as that, as dvc works as expected when I run the command with Powershell (which has a different policy for cases I guess). I've looked for other issues, but somewhat surprisingly, but I can't find any duplicates.

(Unfortunately, I haven't convinced all my colleagues to switch over, so I ran into this issue when they were using command prompt.)

### Reproduce

On windows, start a (standard) command prompt:

1. `dvc init`
2. Copy data.csv
3. `dvc add data.csv`

### Expected

No error, I guess just ignore case if `platform.system() == "Windows"`?

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.1.0 (conda)
---------------------------------
Platform: Python 3.8.8 on Windows-10-10.0.18362-SP0
Supports: http, https
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by skshetry** [comment]
@Huite, could you please share how you open the command prompt? The lower-casing is not a surprise as the fs is case-insensitive, but I am not able to reproduce the lower-case command prompt locally. Thanks.

**Comment by Huite** [comment]
Hi @skshetry, I temporarily couldn't reproduce it either -- it appears to be an artifact of my `cd`'ing!

```
C:\Users\bootsma>cd c:/tmp

c:\tmp>
```

```
C:\Users\bootsma>cd C:/tmp

C:\tmp
```

Depending on whether you use lower case or upper case in the cd command, it switches!

However, changing to the current directory doesn't do anything, you have to go out, and back in to switch case:

```
C:\tmp>cd c:/tmp

C:\tmp>cd ..

C:\>cd c:/tmp

c:\tmp>
```

**Comment by efiop** [comment]
Closing as stale.
