### ISSUE TITLE
Support setting parameters from CLI for `dvc repro`

### ISSUE THREAD

**Issue by copaah** [iterative/dvc#6065]
I have just upgraded to `dvc` 2.0 and I understand that through `dvc exp` you can parameterize the `dvc` pipeline defined in `dvc.yaml`. 

I have primarily used `dvc` to access data and prepare data in a version controlled way. I don't use `dvc` to track my machine learning experiments. For this use case, I think using `dvc repro` fits better than having to use `dvc exp` which implies that you are running an experiment, when in reality you might just want to change data folder, e.g:

```
dvc repro --data_folder my_data_folder_1
dvc repro --data_folder my_data_folder_2
```

In my use case, I want to use this to execute `dvc repro` on a small dataset for my integration tests.

**Comment by karajan1001** [comment]
@copaah First thanks for your advice. I agreed that parameters setting directly from dvc cmds are more convenient than our current ways ( first modify param files, then `dvc repo` or `dvc exp run`). But maybe its better to do this like `dvc repo --setting data_folder:my_data_folder_1`. 

@pmrowla @dberenbaum , maybe `dvc exp` can borrow this idea?
