### ISSUE TITLE
JSON schema: does not support foreach stage

### ISSUE THREAD

**Issue by ClementWalter** [iterative/dvc#6076]
# Bug Report

## Description

When using the JSON schema provided by dvc on https://www.schemastore.org/json/ the inspection raises error with foreach stage "Schema validation: Missing required property 'cmd'" while dvc do manage to handle the file (no error in it).

### Reproduce

I am using PyCharm:
 - add the dvc json schema with the built-in tool
 - create a dvc.yaml file with a foreach stage

### Expected

The schema should handle foreach stages.

### Environment information

PyCharm 2020.2.3 (Professional Edition)

**Additional Information (if any):**

A "foreach" search on the [schema](https://raw.githubusercontent.com/iterative/dvcyaml-schema/master/schema.json) does not lead to any results so I guess it is simply not implemented.

**Comment by skshetry** [comment]
I am quite reluctant on supporting this outside of the DVC repo. We added a few new items and I am sure, we'll add a few more later in the `dvc.yaml`, so I'd prefer it to be in sync with the actual validator that we use, and should be maintained by the DVC core team.

I did propose #5531 that'd provide an API that'd return JSON schema and eventually replace our `voluptuous` based schema, but unfortunately, that was not accepted. 

Related to https://github.com/iterative/dvcyaml-schema/issues/7.

**Comment by ClementWalter** [comment]
Ok ! I did not realize that there were indeed actually another repo for the json schema. In any case, as you said in the close https://github.com/iterative/dvc/pull/5531 :

> Unfortunately, I haven't been able to work more on this right now, so this needs more research.

if there is something I can do, please tell me

**Comment by skshetry** [comment]
> > Unfortunately, I haven't been able to work more on this right now, so this needs more research.

It's more like not everyone in the team is convinced about changing the internal schema for the JSON schema support, so it's stuck. If you want to add support for it, [`dvcyaml-schema`](https://github.com/iterative/dvcyaml-schema) would be the place for now.

**Comment by daavoo** [comment]
`foreach` is supported on https://github.com/iterative/dvcyaml-schema/pull/9 .
