### ISSUE TITLE
plots diff/show: configure --open flag

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6091]
Enable configuration of `dvc plots diff/show --open` flag at the project level.

**Comment by skshetry** [comment]
I'd prefer it to be opened directly if it can and is a tty.

**Comment by daavoo** [comment]
Another thought: should we be more general and implement `core.no_browser`/`ui.no_browser` and `DVC_NO_BROWSER` instead?

_Originally posted by @skshetry in https://github.com/iterative/dvc/pull/7159#discussion_r772114574_

Could you elaborate a little bit more on the approach? Do you mean as a compliment or as a replacement to the `dvc config` option being added in #7159 ?

**Comment by daavoo** [comment]
> I'd prefer it to be opened directly if it can and is a tty.

This appears to be a problematic default for VSCode (and other potential integrations using `dvc` cli as dependency)

**Comment by skshetry** [comment]
> This appears to be a problematic default for VSCode (and other potential integrations using `dvc` cli as dependency)

We should provide ways to disable that for sure. It’s not good to adjust cli’s behavior for GUI-based apps. I don’t think there’s much use of plots show/diff than to check plots in the browser and it only opens once, so it’s not intrusive at all.
