### ISSUE TITLE
unify labels?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6093]
We have too many labels, and we often just triage issues with `bug 🐛` and `pX-*` labels.

And, nowadays we have started to use feature-based labels, which add a cognitive load while trying to add labels. So, I'd propose we namespace them in small categories and try to add most of the labels from the group during triage.

(I have been experimenting with some already 😉 )

The labels group that I propose:
1. `A: ` - denotes **area** of the project the issue relates to.
2. `fs: ` - related to the filesystem
3. `P: ` - Platform (os, processor, etc)
4.  `S: ` - Status of the PR/issue (eg: `S: needs-review`, `S: awaiting-response,  S: needs-repro`, etc.
5. `T: ` or `type: ` or `C:` - Type of the issue/PR (eg: `T: ci`, `T: bug`, `T: question`, `T: tests`, etc.)
6. `E: ` (or, `P: ` or `I`) - Priority/Important of the task

I also noticed that we have stopped using time estimation labels, so I'd propose we drop them. 

The `fs` does seem a bit inconsistent but feels like `F:` does not really convey it properly.
We can keep using some labels that are not used very often or does not feed into above groups could be used as-is. 
 
Let me know what you guys think. @dberenbaum

**Comment by efiop** [comment]
Sounds great! My 2c: would prob use long prefixes instead of short ones (e.g. `status:` instead of `S:`, but still `fs:`), since that makes it less cryptic for us and for users.

**Comment by shcheklein** [comment]
> that makes it less cryptic for us and for users.

💯 🙏

**Comment by skshetry** [comment]
> would prob use long prefixes instead of short ones

I think the `T: discussion` is the same as `discussion` in clarity. Having smaller prefixes might make it easier/faster to triage, encourage to add more appropriate labels, and make room for a better label/category on the right-hand side.

Maybe it just needs to get used to it, similar to `p1/p2` labels instead of `priority1` that we use. I'd prefer we solve this by making short prefixes obvious. But let's hear from others as well, and I am happy to go with the majority here.

**Comment by dberenbaum** [comment]
I lean towards longer prefixes (even `priority1` seems good to me). If we use short ones, we probably need to explain them somewhere that's easy for users to find.

**Comment by dberenbaum** [comment]
> I think the `T: discussion` is the same as `discussion` in clarity

Yeah, so why not just use `discussion` then and use the colors as categories? It doesn't seem like `T: discussion` adds much. I agree that we could get used to that over time, but again I think we need to explain them somewhere that's easy to find.

**Comment by skshetry** [comment]
> > I think the `T: discussion` is the same as `discussion` in clarity
> 
> Yeah, so why not just use `discussion` then and use the colors as categories?

This is not what the issue is about. `discussion` is more than enough, but these kinds of labels grow over time, especially when we want to add labels based on features. We already have to scroll through ~64 labels to just find the one that suits it. 

With the above proposal, I can just type `T: ` or whatever the prefix is for each of the group and select appropriate labels. 
The idea is to add more labels to an issue/PR so we could find things easily later on. Also, having smaller prefixes allows us to have more labels in the same screen estate with the same level of clarity (`T: discussion` vs `discussion`).

Most of the issues and PR don't get labels other than `bug` and `priority`. This is something that I want to change.

> I think we need to explain them somewhere that's easy to find.

I will add it to the contributing guide, but I don't see it changing much on the workflow than the label names.

**Comment by dberenbaum** [comment]
> With the above proposal, I can just type `T: ` or whatever the prefix is for each of the group and select appropriate labels.
> The idea is to add more labels to an issue/PR so we could find things easily later on. Also, having smaller prefixes allows us to have more labels in the same screen estate with the same level of clarity (`T: discussion` vs `discussion`).

So you specifically want to avoid long prefixes because they are more typing?

The points I was trying to make were:
1. Color cues are similarly powerful visual cues to me as a short label like `T:`.
2. For searching, anything in the description will be included in the search, so I don't see much difference between having categories in the label or the description.

I'm fine with whatever you want to do here as long as there's some way for everyone (including random users) to easily understand the system.

**Comment by casperdcl** [comment]
format:

- I prefer `-` to `: ` (shorter, no need to escape space & colon when using `gh issue create --label` etc.)

prefixes:

- A: don't get what "area" means
- P: I prefer `plat`
- S: I prefer `s0/1/2`, `stat` or `status`
- T: I prefer not having a prefix (we can have one category that doesn't have a prefix) or `type` 
- E/P/I: I prefer the current `p0/1/2`. What's E?
- (sub)command/cmd: I'd suggest a this separate prefix for some of the things currently in `A: `

**Comment by skshetry** [comment]
Clarity is important, but I am not quite sure to what extent on the labels.

I'll experiment with a few formats for the labels (starting with what I have proposed) in the coming weeks/months and will settle on what works for us. Thank you all for the participating in the discussions, appreciated.

Closing for now.

**Comment by casperdcl** [comment]
I'd suggest https://github.com/marketplace/actions/github-labeler for consistency
