### ISSUE TITLE
repro: rwlock file corrupted

### ISSUE THREAD

**Issue by Zaber** [iterative/dvc#6097]
# Bug Report

## Issue name
repro: rwlock file corrupted

## Description
Run multiple pipelines that read the same file as input, in the middle of the process rwlock file get corrupted

## Exception
![image (1)](https://user-images.githubusercontent.com/4652316/120436152-41fc7f00-c387-11eb-8ef0-49863358e881.png)

### Reproduce

We execute a huge amount of pipelines that share the same file as input, all processes executed on a computer cluster with GPU support, but I don't think GPU has any impact on this bug. It seems like concurrency bug that hard to reproduce. 
 [rwlock file](https://gist.github.com/Zaber/8f4760f3ceda2cbc5163d32579bef257)
See last line in this file, it's reformatted and renamed JSON for easy navigation

### Environment information

```
DVC version: 2.0.18 (pip)
---------------------------------
Platform: Python 3.8.8 on Linux-4.18.0-240.15.1.el8_3.x86_64-x86_64-with-glibc2.10
Supports: http, https, s3
```

**Comment by skshetry** [comment]
@Zaber, you could add in https://gist.github.com/ and post the link here.

**Comment by skshetry** [comment]
Somehow,a few entries in the json gets interleaved and thus gets corrupted. `rwlock` update is not atomic, but I would not expect it to get interleaved. hmm  🤔

**Comment by Zaber** [comment]
You are right, How you access rwlock file by concurrent processes ?

**Comment by Zaber** [comment]
access to rwlock should be atomic as it's key for shared resource

**Comment by skshetry** [comment]
@Zaber, Could you please see if writing to a temporary file and then renaming the file fixes this issue for you?

It should be changed here.
https://github.com/iterative/dvc/blob/59cfc2c4a43e9b9d2fdb583da80d24e82ae39c26/dvc/rwlock.py#L51-L52

**Comment by Zaber** [comment]
> @Zaber, Could you please see if writing to a temporary file and then renaming the file fixes this issue for you?
> 
> Please try to create temp file within `.dvc/tmp` directory.
> 
> It should be changed here.
> https://github.com/iterative/dvc/blob/59cfc2c4a43e9b9d2fdb583da80d24e82ae39c26/dvc/rwlock.py#L51-L52

will try to use https://github.com/untitaker/python-atomicwrites to implement this techniq

**Comment by Zaber** [comment]
Additional behavior in this code : if process crushes in the middle of the run 
![image (2)](https://user-images.githubusercontent.com/4652316/120462017-3323c580-c3a3-11eb-86b6-7b158910e73f.png)

**Comment by efiop** [comment]
@Zaber Could you show _full_ `dvc doctor` output, please?

Are you running multiple docker containers by any chance in the same project?

**Comment by Zaber** [comment]
Hi, no. It's different pipelines that share the same stage that running in parallel.

**Comment by Zaber** [comment]
![image](https://user-images.githubusercontent.com/4652316/120988219-0860b500-c787-11eb-9a85-342c97917040.png)
Continue to get errors now on lock file itself

**Comment by efiop** [comment]
@Zaber Could you run `dvc doctor` inside of the repo and show full output, please?

**Comment by Zaber** [comment]
> @Zaber Could you show _full_ `dvc doctor` output, please?
> 
> Are you running multiple docker containers by any chance in the same project?

No, we currently don't execute in inside containers.
dvc doctor output > curent version is my development build on top of 2.0.18 with fix to rwlock mutual exclusive r/w operations
--------------------------------------------
DVC version: 2.0.18+d02ab4.mod 
---------------------------------
Platform: Python 3.8.8 on Linux-4.18.0-240.22.1.el8_3.x86_64-x86_64-with-glibc2.10
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: gpfs on dcc06
Caches: local
Remotes: None
Workspace directory: gpfs on dcc06
Repo: dvc (no_scm)

**Comment by Zaber** [comment]
all jobs executed inside IBM computer cluster with jbsub operations. So each job run on different cluster node but all storage of .dvc is on centralized manager node

**Comment by Zaber** [comment]
sure, will try. 10x

**Comment by Zaber** [comment]
Hi, `dvc config core.hardlink_lock true` did a great job and we succeeded do finish the bulk of running jobs without a crash.
Now i am going to check  if rwlock issue also solved by this change, will update

**Comment by efiop** [comment]
Closing as stale
