### ISSUE TITLE
dvc init fails if repository has files marked with --skip-worktree

### ISSUE THREAD

**Issue by villasv** [iterative/dvc#610]
Using dvc 0.9.3, running `dvc init` will yield `Unexpected Error: ` (but creates the `.dvc` directory anyway).

Observed in Python 3.6 on Windows and Python 3.5 on WSL (Ubuntu) - both installed from PyPI.

**Comment by efiop** [comment]
Hi @villasv !

Is that the full error that it throws?

**Comment by villasv** [comment]
Yep, no extra messages. And it's going directly to `stdout`, not `stderr`.

**Comment by villasv** [comment]
Yes, with around 500 commits already

**Comment by efiop** [comment]
@villasv Hm... Very interesting. Tried with a bunch of exsiting git repos of different forms and sizes but `dvc init` seems to work as expected. Any chance you could share that particular repo with me?

**Comment by efiop** [comment]
Btw, cloud you try running:
```
echo -e "import git\nrepo = git.Repo('.')" | python
```
In your repository?

**Comment by villasv** [comment]
Unfortunately I can't share it, so I'll have to probe it on my own.
`echo -e "import git\nrepo = git.Repo('.')" | python` outputs nothing, but doesn't error either.

I noticed that cloning my own repo anew, `dvc init` will work. So it must be something related to a specific `git` repo state.

**Comment by villasv** [comment]
Oh, I think I got something. The error starts happening when I use `git update-index --skip-worktree .env` to ignore the local environment file.

**Comment by efiop** [comment]
Ah, I see. Ok, lets try to bypass all the dvc exception traps by running the methods directly. Please run this script in your repo:
```
echo -e "from dvc.project import Project\nProject.init()" | python
```

**Comment by villasv** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.5/dist-packages/dvc/project.py", line 75, in init
    scm.add([config.config_file, ignore_file])
  File "/usr/local/lib/python3.5/dist-packages/dvc/scm.py", line 116, in add
    self.repo.index.add(paths)
  File "/usr/local/lib/python3.5/dist-packages/git/index/base.py", line 793, in add    self.entries[(entry.path, 0)] = IndexEntry.from_base(entry)
  File "/usr/local/lib/python3.5/dist-packages/gitdb/util.py", line 256, in __getattr__
    self._set_cache_(attr)
  File "/usr/local/lib/python3.5/dist-packages/git/index/base.py", line 132, in _set_cache_
    self._deserialize(stream)
  File "/usr/local/lib/python3.5/dist-packages/git/index/base.py", line 161, in _deserialize
    self.version, self.entries, self._extension_data, conten_sha = read_cache(stream)  # @UnusedVariable
  File "/usr/local/lib/python3.5/dist-packages/git/index/fun.py", line 188, in read_cache
    version, num_entries = read_header(stream)
  File "/usr/local/lib/python3.5/dist-packages/git/index/fun.py", line 167, in read_header
    assert version in (1, 2)
AssertionError
```

**Comment by efiop** [comment]
Aha! So if we look into GitPython's code:
```
def read_header(stream):                                               
    """Return tuple(version_long, num_entries) from the given stream"""
    type_id = stream.read(4)                                           
    if type_id != b"DIRC":                                             
        raise AssertionError("Invalid index file header: %r" % type_id)
    version, num_entries = unpack(">LL", stream.read(4 * 2))           
                                                                       
    # TODO: handle version 3: extended data, see read-cache.c          
    assert version in (1, 2)                                           
    return version, num_entries                                        
```
Very interesting, looking into solving it.

**Comment by villasv** [comment]
It seems that this won't affect `dev add` or `dvc run` commands, so as long as use `--skip-worktree` after running `dvc init` I'm good to go. I'll rename the issue accordingly.

**Comment by efiop** [comment]
You are correct, it should not affect other dvc commands, as it is actually the one and only place where dvc tries to add anything using git. But this is definitely an important issue to consider. Lets leave this issue open, I might get to digging into GitPython and implementing v3 and v3 indexes in the future.

Thank you!

**Comment by maximerischard** [comment]
I just ran into this issue while running `dvc repro`. The file that I had marked with `--skip-tree` is `.dvc/config`, to be able to use hardlinks without affecting other users. Is there a better way to do so?

**Comment by efiop** [comment]
@maximerischard I suppose you were looking for `.dvc/config.local`? It is a config file that is not tracked by git and meant to be used locally. You can use `--local` flag with `dvc remote/config` commands to use it. Values in `.dvc/config.local` overwrite the ones in `.dvc/config`.

**Comment by efiop** [comment]
@maximerischard For example, if you want to use hardlinks only for your project, do:
```
dvc config cache.type hardlink --local
```

**Comment by maximerischard** [comment]
That certainly solves my particular problem, thank you @efiop!

**Comment by efiop** [comment]
For the record: another user ran into the same thing with dulwich https://discordapp.com/channels/485586884165107732/485596304961962003/824303522496643174 . Gitpython's python part and dulwich still don't support v3 and v4 index. Pygit2 seems to support it though.
