### ISSUE TITLE
Update pygtrie to 2.4.2?

### ISSUE THREAD

**Issue by Erotemic** [iterative/dvc#6102]
DVC seems to pin pygtrie to version 2.3.2

I'm wondering what the reason is, and if it would feasible to either upgrade to or allow usage of 2.4.2? Currently I'm unable to install dvc alongside another project that does require the latest pygtrie.

**Comment by efiop** [comment]
Hi @Erotemic . I don't think there is any particular reason, we didn't touch it pretty much since we've started using it. Please feel free to create a PR, let's see if CI passes.
