### ISSUE TITLE
type hinting: add types to objects and output/dependency

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6126]
As this is a core part of the DVC and a fresh codebase, it should have a good amount of type-hints. We should have complete coverage of types in the objects and good enough on the output/dependency. 

This should help us improve type coverage in the other parts of the codebase too.

**Comment by skshetry** [comment]
Also, some documentation would be nice, clarifying the concepts and some references.

**Comment by dberenbaum** [comment]
@skshetry Is this still an issue, and should it stay as p1?

**Comment by pmrowla** [comment]
Improving the state of internal docs/type hinting should continue to be done over time as people make changes to the related modules (like `dvc.objects`), I don't think this needs to be p1

**Comment by skshetry** [comment]
This issue is open for almost a year now. The technical docs have not improved over time

Closing as I don't see much keeping this issue open.
