### ISSUE TITLE
Support OCI backend

### ISSUE THREAD

**Issue by pbarker** [iterative/dvc#6148]
Would be nice if DVC could work off of OCI storage using something like https://github.com/oras-project/oras

**Comment by efiop** [comment]
@pbarker Thanks for the request! For the record: we are migrating to fsspec right now https://github.com/iterative/dvc/issues/5162 , so if anyone will be willing to add support for OCI to dvc, they would need to implement fsspec-compatible `OCIFileSystem` first and maintain it in a separate project. After that, dvc will be able to use it as a plugin (the mechanism is to be implemented in the near future)
