### ISSUE TITLE
dvc exp run --all: fails to reproduce experiments

### ISSUE THREAD

**Issue by pangshengwei** [iterative/dvc#6159]
# Bug Report

Am getting the following errors after trying to queue some experiments and running all

- `dvc exp run --queue -S prepare.learning_rate=0.01`
-  `dvc exp run --all --jobs=2`

![image](https://user-images.githubusercontent.com/19318871/121810314-ebe6e000-cc92-11eb-99f6-ed839dd62878.png)

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by pmrowla** [comment]
@pangshengwei are you able to run the experiment without using the queue/run-all feature? (i.e. just using `dvc exp run -S prepare.learning_rate=0.01` to run it in your workspace

Also, could you please run `dvc doctor` and post the output here

**Comment by efiop** [comment]
Closing as stale.
