### ISSUE TITLE
straight-to-remote: using different block size to compute md5 than the local hashing

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6160]
We use a complete chunk to determine whether the file is text or not for the straight-to-remote hashing.
https://github.com/iterative/dvc/blob/b9df4451b196082d66e15a22ecc7ca5660e02d47/dvc/utils/stream.py#L91

Whereas, we use the first 512 bytes for the heuristics.
https://github.com/iterative/dvc/blob/b9df4451b196082d66e15a22ecc7ca5660e02d47/dvc/istextfile.py#L25

This might cause issues where the file hashes do not match when the file is checked out later.
```
2021-06-14 15:48:03,158 WARNING: corrupted cache file 'http://localhost:8080/remote.php/dav/files/admin/dvc-cache/27/942e2b84fe17ce3778fd795b1cedc1'.
```

Note that I found this while trying to add a PDF file straight to the cache. The checks for PDF are always going to be tricky,
so I am not expecting that to be fixed here, but we should definitely use the same amount of chunk to check for binary or texts.

**Comment by skshetry** [comment]
This would have been caught if we were running all of our tests with remote using `verify = True`. 🙁

**Comment by isidentical** [comment]
The transfer logic that to-remote/to-cache uses depends on the `fs.CHUNK_SIZE`, which seems to be always greater than the `512`. Unless I am missing something, we could potentially just pass `chunk[:512]`

**Comment by skshetry** [comment]
@isidentical, it seems to use `read1` if it exists, so maybe read the first 512 bytes before hashing?

https://github.com/iterative/dvc/blob/b9df4451b196082d66e15a22ecc7ca5660e02d47/dvc/utils/stream.py#L84-L85

**Comment by isidentical** [comment]
> so maybe read the first 512 bytes before hashing?

So you mean we should pre-emptively read the 512 bytes, and cache it in the initialization? That seems to be rather complicated:
```py
        chunk = b""
        if self.tell() <= 512:
            if n == -1:
                chunk += self._initial_chunk[self.tell():]
            else:
                chunk += self._initial_chunk[self.tell():self.tell()+n]
                n -= len(chunk)
        chunk += self._reader(n)
```
