### ISSUE TITLE
Unpin fsspec/gcsfs dependencies?

### ISSUE THREAD

**Issue by nbren12** [iterative/dvc#6170]
We cannot currently install dvc in our project because the pinned versions of gcsfs/fsspec are not compatible with some of our other dependencies. Would ya'll be open to unpinning these deps so that dvc can be installed in a broader range of python environments? Given that dvc is primarily a command line tool I could install dvc in another virtualenv or with `pipx`, but would like to avoid this level of TLC if possible.

**Comment by nbren12** [comment]
BTW, I'm happy to see you are using gcsfs/fsspec. I've been contributing some reliability fixes there lately, so I totally understand why you are at the bleeding edge of that particular dep.

**Comment by efiop** [comment]
Hi @nbren12 :slightly_smiling_face:

Unfortunately, unpinning is likely not possible (or rather meaningless) right now, as we are effectively always using the latest fsspec and gcsfs/s3fs/adlfs/etc libraries, as @isidentical is actively working on improving all of those :pray: right now. If you are not using dvc through our python API, I would advise using either virtuaenv/pipx or just some standalone package that is already isolated (e.g. deb, rpm, homebrew, chocolatey, snap, etc)

> BTW, I'm happy to see you are using gcsfs/fsspec. I've been contributing some reliability fixes there lately, so I totally understand why you are at the bleeding edge of that particular dep.

Glad to see our users using it as well, we love fsspec so far :heart: We will also expose fsspec-compatible `DvcFileSystem` and `RepoFileSystem` in the future, so stay tuned. :wink:

**Comment by isidentical** [comment]
As @efiop said and you guessed, we depend on the features that are only available on the latest revision (most of those, we contribute to make those filesystems usable within DVC). So DVC won't function properly with the lower versions, and we have no choice but to pin. Since DVC is a tool (like black or isort or pylint), you best bet would be to install either the packages or use some sort of external environment (I haven't tested DVC with pipx, but it should work so you could also give that a shot).

**Comment by nbren12** [comment]
I did test dvc with pipx, which works for CLI usage. The python API would still be challenging to use. Is there some reason to not leave the door open to future versions of gcsfs/fsspec with a ">=" constraint? Presumably the features you require will still be there in future versions.

**Comment by skshetry** [comment]
@nbren12, we are still in the process of migrating to the fsspec, and @isidentical has been fixing bugs in the upstream, so it's unlikely we will be able to allow ranges at least for now. In the future, we might be able to do that, but it might be hard as fsspec is on calver. I think it'd better to create issues on the dependency to be in sync with fsspec releases, than for us to allow older versions (of course, easier said than done).

**Comment by selalamiTF** [comment]
I am encountering the same problem as I want to install Kedro 0.16.6 with DVC 2.3.0 and I am having a conflict over fsspec. I need to install them in the same env as they are required by the same app. Do you have any ideas how to solve this ?

**Comment by skshetry** [comment]
@selalamiTF, kedro seems to have not upgraded their `fsspec` dependencies for a long time now. I'd suggest you chime in on https://github.com/quantumblacklabs/kedro/issues/790. For now, I'd suggest you use `pipx` or different virtual environment to install DVC if possible.

**Comment by selalamiTF** [comment]
Thanks I opened an issue with kedro to request if it s possible to upgrade fsspec. Do you mean to force the installation of a newer fsspec version ? if yes, how can I do that ?

**Comment by skshetry** [comment]
@selalamiTF, what are you using to install? `pip` or `conda`? If you are using `pip` by any chance, you could just use `pip install dvc kedro` and it'll automatically select a compatible version (though `2.0` version of DVC). 

If you want to force kedro to use newer fsspec (and use latest version of DVC), you can use `pip install kedro && pip install dvc fsspec`. It'll complain that it might not be compatible but you could see for yourself. However, note that we don't support older versions of DVC.

**Comment by selalamiTF** [comment]
Yes I am using `pip` and `pip-compile` to handle dependencies. Installation is done from `requirements.ini` file. We are still in prototyping stage (luckily !) so this solution could work for now until there is a more stable solution. Thanks for the help ! I will let you know if it works out :)

**Comment by nbren12** [comment]
Maybe dvc should suggest pipx in its docs.

**Comment by efiop** [comment]
@nbren12 We actually do https://dvc.org/doc/install/linux#install-with-pip :slightly_smiling_face:
