### ISSUE TITLE
plots: Custom templates outside of `.dvc/plots`

### ISSUE THREAD

**Issue by duijf** [iterative/dvc#6179]
## Description

Plots currently accepts custom templates outside of `.dvc/plots` which can lead to unintuitive behavior when changing directories.

Discovered through a Studio user report: https://github.com/iterative/studio-support/issues/11

### How to reproduce

I've created https://github.com/duijf/dvc-plots-repro to show this off. 

`dvc.yaml` contains a stage with a plot:

```yaml
stages:
  test:
    cmd: echo "test\n1\n2" > metrics.csv
    deps:
      - foo.json
    plots:
      - metrics.csv:
          template: "custom.json"
```

And this template is not present in `.dvc/plots`, but [in the root of the repository](https://github.com/duijf/dvc-plots-repro/blob/master/custom.json).

```
# Clone + generate metrics.csv
$ git clone git@github.com:duijf/dvc-plots-repro.git
$ dvc repro

# While in the repo root
$ dvc plots show
file:///home/duijf/repos/duijf/dvc-plots-repro/plots.html

# While in a subdirectory
$ cd test
$ dvc plots show
ERROR: Template 'custom.json' not found.
```

### Expected

One of:

 1. DVC resolves `custom.json` relative to `dvc.yaml` and the plot is rendered correctly
 2. DVC does not allow `custom.json` to be located outside of `.dvc/plots` and prints the same error regardless of what directory the user is in.

### Environment information

```console
$ dvc doctor
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.9.4 on Linux-5.11.16-arch1-1-x86_64-with-glibc2.33
Supports: gdrive, http, https, s3, ssh
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/vg-root
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/mapper/vg-root
Repo: dvc, git
```

**Comment by karajan1001** [comment]
@duijf 
Thanks for your report, I recommend this one.
1. DVC resolves custom.json relative to dvc.yaml and the plot is rendered correctly. 
As we had provided custom paths for the template file.
