### ISSUE TITLE
checkpoints: write `dvc.lock` on every checkpoint

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#6180]
(Over)writing `dvc.lock` after each checkpoint (so interrupting `exp run` will mean a usable `dvc.lock` is present).

Part of https://github.com/iterative/cml/issues/560

**Comment by pmrowla** [comment]
Just to be clear here, `dvc.lock` should already be written (updated) at each checkpoint. We should also already be automatically tracking it in git for checkpoints as well. If you're seeing exp/checkpoint commits without `dvc.lock` files, it sounds like this is a bug somewhere in DVC

**Comment by casperdcl** [comment]
There may be a bug here but it's low priority if #6182 is solved, so closing for now.
