### ISSUE TITLE
`exp run`: update command `-h` desc.

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#6186]
From https://github.com/iterative/dvc.org/issues/2545#issuecomment-851740655:

> Help for the command is misleading and low level also:
`Reproduce complete or partial experiment pipelines.`
It should be probably as simple as `Run or resume an experiment`

**Comment by kurianbenoy** [comment]
Hi @jorgeorpinel can I work on this issue?

**Comment by jorgeorpinel** [comment]
Absolutely!
