### ISSUE TITLE
ui: fix `dvc diff` summary

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6205]
```
files summary: 0 added, 1 deleted, 0 renamed, 0 modified, 1 not in cache
```

We should not have `0 ...` in the summary result.

**Comment by hadasarik** [comment]
Can I take this one?

**Comment by skshetry** [comment]
Sure, @hadasarik. Please take a look around here:
https://github.com/iterative/dvc/blob/4e792ae61c5927ab2e5f6a6914d985d43aa705b4/dvc/command/diff.py#L114-L121

And, if you face any issues please, feel free to ping us here or in Discord. :)
