### ISSUE TITLE
implement 'dvc destroy'

### ISSUE THREAD

**Issue by rahulguptajss** [iterative/dvc#621]
Can you please share an example of DVC remove. I could be missing something in its command.

**Comment by efiop** [comment]
`dvc remove` removes outputs of the specified dvc file. Example:
```
echo foo > file
dvc add file
dvc remove file.dvc # Equivalent to `rm file` in this particular case
```
The usefulness in more obvious when your stage has multiple of outputs.

**Comment by rahulguptajss** [comment]
Thanks I was hoping that if we could have something like dvc destroy which would be opposite to dvc init. Currently if i were to clean up my project of dvc, I have to remove all files manually.

**Comment by efiop** [comment]
Ah, I see. Not going to lie, didn't even think of such feature until now :smiley: Turning this issue into feature request.
