### ISSUE TITLE
[bug] `dvc doctor` does not show `webdav` support for 2.4.1 build

### ISSUE THREAD

**Issue by chenrui333** [iterative/dvc#6216]
# Bug Report

`dvc doctor` does not show webdav support for 2.4.1 build

## Description

```sh
$ dvc doctor
DVC version: 2.4.1 (brew)
---------------------------------
Platform: Python 3.9.5 on macOS-10.14.6-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss
```

### Reproduce

See this brew PR, Homebrew/homebrew-core#79886

### Expected

Expected `webdav` and `webdavs` show up in the `dvc doctor` output

**Comment by efiop** [comment]
@chenrui333 Thank you for the report! :pray: We've changed the library for it to `webdav4`. Looking into it in https://github.com/Homebrew/homebrew-core/pull/79886/files

**Comment by efiop** [comment]
For the record: https://github.com/Homebrew/homebrew-core/pull/79886#issuecomment-866943939

**Comment by chenrui333** [comment]
Closing the issue now, thanks @efiop for the quick help!! Appreciate it!
