### ISSUE TITLE
Upgrade vega-lite to 5.1.0

### ISSUE THREAD

**Issue by klakhdhar** [iterative/dvc#6218]
Hi,
I was wondering if it's possible to upgrade vega-lite in the plots module to 5.1.0.

https://github.com/iterative/dvc/blob/d87ace0968656912db9e6de3b638b594ceeda43b/dvc/utils/html.py#L11

It seems for now hardcoded and couldn't find an easy way to change it.
Thanks

**Comment by pmrowla** [comment]
@klakhdhar is there a specific 5.x feature you are looking for?

@pared should have some more insight on this issue

**Comment by klakhdhar** [comment]
Thanks @pmrowla for the quick response.
I'm interested in the https://github.com/vega/vega-lite/releases/tag/v4.9.0 as it introduces repeat operator. 
I'm basically trying to get train_loss and valid_loss on the same chart.
Also the vega-lite documentation and the examples provided there don't see to work with older versions.
Thank you.

**Comment by pared** [comment]
@klakhdhar thanks for the feature request, it seems we could get update it. Anyway, until this is done, you might be interested in custom HTML template:
It is already in DVC but we are still polsihing the documentation:
https://github.com/iterative/dvc/pull/5694

Basically, you can create your own HTML that will handle the plots. Example is under the issue. You can simply create your own HTML pointing to newer versions of vega libs.

**Comment by klakhdhar** [comment]
Great thanks !

**Comment by pared** [comment]
@klakhdhar there might be a slight change in the api, please note this PR: #6221
