### ISSUE TITLE
commit: unnecessary prompt?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6228]
`dvc commit` without any arguments/targets prompts the user if it should or should not prompt. 

This feels unnecessary and quite obvious from the name on what it'll attempt to do. It'd be very much helpful if it prints what it's doing rather than asking the user.

```python
$ dvc commit
Committing data/models 0/12
```

Let me know what you think, or if I'm missing the old contexts for this _feature_. :)

**Comment by karajan1001** [comment]
Commit changes the  md5 of `dvc` files, which might not be tracked by Git. This might cause data reference missing.

**Comment by skshetry** [comment]
I think we do have a consensus that prompts are bad, and we do want to get rid of this. But we don't have capacity or plans to make this change. Closing.
