### ISSUE TITLE
azure: checksum of import-url'd file changes

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#6237]
```
$ dvc import-url remote://workspace/file
Importing 'remote://workspace/file' -> 'file'                         

$ cat file.dvc
md5: 0fa0c210159f57a03b5c9d926079c451
frozen: true
deps:
- etag: '0x1B33CC9E04F1CA0'
  size: 4
  path: remote://workspace/file
outs:
- md5: 8c7dd922ad47494fc02c388e12c00eac
  size: 4
  path: file

$ dvc status
file.dvc:
        changed checksum
```

**Comment by isidentical** [comment]
This seem to be caused by a case lowering somewhere outside of the filesystem;
```
{'metadata': {}, 'creation_time': datetime.datetime(2021, 6, 28, 7, 52, 18, tzinfo=datetime.timezone.utc), 'deleted': None, 'deleted_time': None, 'last_modified': datetime.dateti(.venv38) (Python 3.8.5+) [ 11:03ÖÖ ]  [ <hey>@<hey>:/tmp/pytest-of-isidentical/pytest-14/test_import_url_azure_0 ]
 $ dvc import-url remote://workspace/file
Importing 'remote://workspace/file' -> 'file'                         
b'{"deps": [{"path": "remote://workspace/file"}], "outs": [{"path": "file"}]}' 0512d50701668b58de0cce650ad2f470
b'{"deps": [{"etag": "0x1B33CC9E04F1CA0", "path": "remote://workspace/file"}], "outs": [{"md5": "8c7dd922ad47494fc02c388e12c00eac", "path": "file"}]}' 0fa0c210159f57a03b5c9d926079c451
(.venv38) (Python 3.8.5+) [ 11:03ÖÖ ]  [ <hey>@<hey>:/tmp/pytest-of-isidentical/pytest-14/test_import_url_azure_0 ]
 $ dvc status
WARNING: stage: 'file.dvc' is frozen. Its dependencies are not going to be shown in the status output.
b'{"deps": [{"etag": "0x1b33cc9e04f1ca0", "path": "remote://workspace/file"}], "outs": [{"md5": "8c7dd922ad47494fc02c388e12c00eac", "path": "file"}]}' 4a0a1ab3c3daf8f21795064b7574bfb9
file.dvc:
        changed checksum

```

**Comment by skshetry** [comment]
@isidentical, see https://github.com/iterative/dvc/issues/5998. When loading stage, it turns into lowercase.

**Comment by isidentical** [comment]
Right. I'm not sure about HTTP though for azure it is safe to assume both are pointing at the same object, so we might need to introduce a temporary `.lower()` call to `_entry_hook`

**Comment by skshetry** [comment]
I am not sure if this is remote-specific. Etags are case-sensitive.

**Comment by pmrowla** [comment]
According to the [RFC](https://datatracker.ietf.org/doc/html/rfc7232#section-2.3) only the `W/` prefix for weak etags should be case-sensitive, the rest of the etag value should not be.

**Comment by skshetry** [comment]
@pmrowla, the RFC says it's an opaque tag and it does not specify how `Etag` should be generated. So, it should be strongly  compared.

>  Strong comparison: two entity-tags are equivalent if both are not weak and their opaque-tags match character-by-character.

In practice, it might not matter that much though, but if we want to be standard compliant, it should be assumed case-sensitive.

**Comment by pmrowla** [comment]
Ah, that makes sense.

So then we should probably be getting back to the solution discussed in #5998 and actually define schemas for each checksum type (or at least one non-default one for etags) so that we don't force them to be `Lower` after validation

**Comment by isidentical** [comment]
Okay, if we assume all 'etags' should be compared case-sensitively, then it should be simpler. I've updated my patch to introduce a new schema object for etags (s3/gs/oss/azure/http).
