### ISSUE TITLE
Not able to push data of dependencies to the remote

### ISSUE THREAD

**Issue by alice45678** [iterative/dvc#6256]
# Bug Report

## Description
I'm not able to push data of dependencies in the dvc.yaml to the remote.

### Reproduce

../dvc.yaml
<img width="291" alt="Screenshot 2021-06-30 at 15 04 37" src="https://user-images.githubusercontent.com/39770544/123965293-9742a500-d9b4-11eb-942d-8f993ccf1b5e.png">

```console
$ dvc repro
$ dcv add ../../data/my_data.csv
$ dvc push ../../data/my_data.csv
```
Error: failed to push data to the cloud - '../../data/my_data.csv' does not exist as an output or a stage name in 'dvc.yaml': Stage '../../data/my_data.csv' not found inside 'dvc.yaml' file

### Expected

my_data.csv is uploaded to the cloud successfully.

### Environment information
- dvc 2.4.3

**Output of `dvc doctor`:**

```console
DVC version: 2.4.3 (conda)
---------------------------------
Platform: Python 3.8.10 on macOS-10.15.3-x86_64-i386-64bit
Supports: http, https
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5
Caches: local
Remotes: local
Workspace directory: apfs on /dev/disk1s5
Repo: dvc, git

```

**Additional Information (if any):**

**Comment by efiop** [comment]
Hi @alice45678 !

Could you try `dvc push ../../data/my_data.csv.dvc`?

**Comment by alice45678** [comment]
> Hi @alice45678 !
> 
> Could you try `dvc push ../../data/my_data.csv.dvc`?

Yes, I have tried. It shows that `Everything is up to date`. But we can't find the file from the remote

**Comment by efiop** [comment]
@alice45678 Are you sure your collegue on the same git revision? Check that their `my_data.csv.dvc` matches yours.

**Comment by alice45678** [comment]
> @alice45678 Are you sure your collegue on the same git revision? Check that their `my_data.csv.dvc` matches yours.

Even when I deleted the data `my_data.csv` from my local machine, I am also not able to pull the data from the remote.

**Comment by efiop** [comment]
> Even when I deleted the data my_data.csv from my local machine, I am also not able to pull the data from the remote.

Did you delete the file itself in the workspace or did you remove a corresponding object in .dvc/cache? If the former - the .dvc/cache is still up-to-date and `dvc pull` won't download anything, it will just restore the file in the workspace.

**Comment by alice45678** [comment]
> > Even when I deleted the data my_data.csv from my local machine, I am also not able to pull the data from the remote.
> 
> Did you delete the file itself in the workspace or did you remove a corresponding object in .dvc/cache? If the former - the .dvc/cache is still up-to-date and `dvc pull` won't download anything, it will just restore the file in the workspace.

I deleted the file only from the workspace. When using `dvc pull`, the file `my_data.csv  ` was not restored in the workspace.

**Comment by efiop** [comment]
@alice45678 `dvc pull` without arguments? If so, corresponding `my_data.dvc` is probably gitignored, which makes dvc not be able to see it unless you `dvc pull path/to/my_data.dvc` explicitly. What does `git check-ignore path/to/my_data.dvc` show?

**Comment by alice45678** [comment]
We tried to use `dcv push path/to/my_data.csv.dvc`, and removed the original `path/to/my_data.csv`, 'dvc pull path/to/my_data.csv.dvc' it works well.

Thanks for the help!

**Comment by efiop** [comment]
@alice45678 Is it affected when you don't specify the target? See my last comment, I'm worried that you have a .gitignore that ignores some `*.dvc` files.

**Comment by Christoph-1** [comment]
> @alice45678 Is it affected when you don't specify the target? See my last comment, I'm worried that you have a .gitignore that ignores some `*.dvc` files.

We have a .gitignore that ignores the `/data` folder, in which `my_data.csv` and `my_data.csv.dvc` reside. `my_data.csv.dvc` is added as an exception to the .gitignore.

**Comment by pmrowla** [comment]
> We have a .gitignore that ignores the /data folder

@Christoph-1 can you post the contents of this `.gitignore`? Exclusions for files inside git-ignored directories have to be written in a specific way, so depending on how you are currently writing the exclusion for `my_data.csv.dvc` it's possible that git is still ignoring it.

**Comment by efiop** [comment]
For the record: we've also created https://github.com/iterative/dvc/issues/6291 to describe it better.

**Comment by Christoph-1** [comment]
The gitignore looks like this:
```
data/*
!data/my_data.csv.dvc
!data/folder/my_data.csv.dvc
```
in case we have sub-folders in `data/`

**Comment by pmrowla** [comment]
@Christoph-1 to properly exclude your `.dvc` files you will need something like
```
data/**
!data/**/
!data/**/*.dvc
```

The issue is that git will not traverse into subdirectories of an ignored dir unless the subdirectory itself is also explicitly excluded with a `!` rule. So in your example, git won't traverse into `data/folder` at all, since it is ignored by `data/*`, and the `!data/folder/my_data.csv.dvc` exclusion will never be considered.

**Comment by Christoph-1** [comment]
> @Christoph-1 to properly exclude your `.dvc` files you will need something like
> 
> ```
> data/**
> !data/**/
> !data/**/*.dvc
> ```
> 
> The issue is that git will not traverse into subdirectories of an ignored dir unless the subdirectory itself is also explicitly excluded with a `!` rule. So in your example, git won't traverse into `data/folder` at all, since it is ignored by `data/*`, and the `!data/folder/my_data.csv.dvc` exclusion will never be considered.

Thanks for the hint. If I exclude the subdirectory from the gitignored the `my_data.csv` and `my_data.csv.dvc` will both be uploaded to git as they are both in the same folder. What would be the solution for that as I don't want the `my_data.csv` to be uploaded to git.

**Comment by pmrowla** [comment]
@Christoph-1 using the rules I suggested, `my_data.csv` will be ignored by the first rule `data/**`. The subdirectory exclusion `!data/**/` only applies to the subdirectory paths (which end in a trailing slash), and essentially just forces git to traverse into subdirectories (so that it can see the `.dvc` files. `data/folder/my_data.csv` does not match `!data/**/` since `my_data.csv` is not a directory.

So the way the rules work together is:

```
# ignore every file inside data/
data/**

# force traversal into subdirectories within data/ that would normally be skipped entirely due to the first rule
!data/**/

# un-ignore .dvc files inside data/
!data/**/*.dvc
```

**Comment by Christoph-1** [comment]
@pmrowla Thanks a lot for this explanation. That helped a lot.
