### ISSUE TITLE
dvc push uploads everything from scratch after a git reset

### ISSUE THREAD

**Issue by kiedanski** [iterative/dvc#6275]
# Bug Report

dvc push: re-uploads all files after a `git reset --soft HEAD~1` that did not affect any of the files being uploaded.

## Description

We have a complicated and quite long pipeline with several steps frozen. After uploading everything with a dvc push, I had to perform a `git reset --soft HEAD~1`. The change did not affect any of the files tracked by dvc, but after commiting again, `dvc push` started pushing ALL files.

**Output of `dvc doctor`:**

```console
DVC version: 2.4.3 (pip)
---------------------------------
Platform: Python 3.8.8 on macOS-11.4-x86_64-i386-64bit
Supports: hdfs, http, https, s3, ssh
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

```

**Comment by pared** [comment]
@danski3456 Were you pushing to s3?
