### ISSUE TITLE
DVC Add Bug

### ISSUE THREAD

**Issue by bhumeshchopda** [iterative/dvc#6279]
dvc add data/data.xml

Adding...
ERROR: unexpected error - DLL load failed: The specified procedure could not be found.

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

dvc vesrion 2.5.0

**Comment by karajan1001** [comment]
@bhumeshchopda 
Hello, could not reproduce it on my computer, `DLL load failed` looks like some C package broken ( for example NumPy )? May you please check that if your `NumPy` is working?

**Comment by efiop** [comment]
@bhumeshchopda Please add `-v` to the command you are running and show us full log that it produces.

**Comment by efiop** [comment]
Closing as stale, might be related to https://github.com/iterative/dvc/issues/6397 or https://github.com/iterative/dvc/issues/2887
