### ISSUE TITLE
`dvc push/pull --remote webdavs`: missing webdavclient3 dependency under miniconda3 install

### ISSUE THREAD

**Issue by ORippler** [iterative/dvc#6289]
# Bug Report

`dvc push/pull --remote webdavs`: missing webdavclient3 dependency under miniconda3 install

## Description

When installing `dvc` via `conda` or `mamba` on a `miniconda` install, one cannot make use of `webdavs` remotes since missing dependencies are installed

### Reproduce

1. install `miniconda`
2. install `dvc` via `conda install -c conda-forge dvc`
3. perform `dvc fetch/pull/push` with a webdavs remote

```
ERROR: failed to push data to the cloud - URL $URL is supported but requires these missing dependencies: ['webdavclient3']. To install dvc with those dependencies, run:                                                                  
                                                                                                                           
        conda install -c conda-forge dvc-webdav 
```

The funny thing is, `dvc-webdav` is not registered on conda and runnning  `conda install -c conda-forge dvc-webdav` fails.
The correct way to install the missing dependencies is via `conda install webdavclient3`

### Expected

Webdavs is either supported in the `dvc` package (e.g. by adding `webdavclient3` as a dependency) or a `dvc-webdav` is properly added to conda and referred to in the docs etc.

### Environment information

**Output of `dvc doctor`:**

```
$ dvc doctor                                                              
DVC version: 2.3.0 (conda)
---------------------------------
Platform: Python 3.7.3 on Linux-5.4.0-74-lowlatency-x86_64-with-debian-bullseye-sid
Supports: http, https, webdav, webdavs
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme1n1p1
Caches: local
Remotes: local, webdavs
Workspace directory: ext4 on /dev/nvme1n1p1
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by efiop** [comment]
Hi @ORippler .

Could you try upgrading to 2.5.0, please?

**Comment by skshetry** [comment]
We don't support webdav in Conda package yet https://github.com/conda-forge/dvc-feedstock/issues/138

**Comment by efiop** [comment]
@skshetry any plans on publishing webdav4 on conda?

**Comment by skshetry** [comment]
I'll do it shortly.

**Comment by ORippler** [comment]
Hey,

i upgraded & confirmed this under 2.5.0.
While not officially supported, by running `conda install -c conda-forge dvc webdavclient3` I can use webdav.

In either case, it would be nice to update the error message accordingly to what you plan to support :)

**Comment by skshetry** [comment]
@ORippler, we don't use webdavclient3 at all. We didn't add webdavclient3 before as it was not available in conda, looks like it is now.

**Comment by ORippler** [comment]
Okay so I failed to double-check the 2.5.0 since I have local + webdav remotes.

for `dvc <= 2.3`, `webdavclient3` was actually used and the above workaround via `conda install` works. For `dvc > 2.3`, this is not the case.

Sorry for the mishap

**Comment by skshetry** [comment]
@ORippler, no worries. I am adding the dependency in the conda-forge now(https://github.com/conda-forge/staged-recipes/pull/15518), hopefully the next release will come with `webdav` support.

**Comment by efiop** [comment]
@ORippler We'll do a release right after (conda-forge/staged-recipes#15518 is merged. Btw, note that thanks to great work by @skshetry :pray: `webdav4` is much faster and has more features than the old library we used to use, so if you'll run into issues/bugs with `webdavclient3` - just hang on tight, next version should fix it. :slightly_smiling_face:

**Comment by skshetry** [comment]
@ORippler, it is now available in conda. Please try upgrading it, and let us know how it goes. Closing the issue.
