### ISSUE TITLE
oss: get endpoint url from the environment if it is possible

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#6320]
https://github.com/iterative/dvc/blob/6275f5d0d738c0bc1611bde0be0afa0e07ba76cd/dvc/fs/oss.py#L34
Would probably require something like `os.getenv("OSS_ENDPOINT")`

Also ossfs should not fail if it can't find the endpoint url, see iterative/ossfs#48

**Comment by karajan1001** [comment]
@isidentical 
> Would probably require something like `os.getenv("OSS_ENDPOINT")`

Good suggestion.

> Also ossfs should not fail if it can't find the endpoint url, see iterative/ossfs#48

`oss` is different from `s3`, its buckets are binding with the endpoint. The addresses of `oss` are not in a similar form like `s3` or `azure` but something like `BucketName.Endpoint`. Without an endpoint, you can't get access to the bucket.

**Comment by isidentical** [comment]
> oss is different from s3, its buckets are binding with the endpoint. The addresses of oss are not in a similar form like s3 or azure but something like BucketName.Endpoint. Without an endpoint, you can't get access to the bucket. The only special endpoint is the accelerate endpoint, it can be used for all buckets, but it requires you to open the accelerate service in advance.

Right. That is really weird, but apparently there seems to be a solution. [OSS domain names](https://partners-intl.aliyun.com/help/doc-detail/31834.htm?spm=a2c63.p38356.b99.36.270824fcs2Pdte) states:

> All requests except the GetService request that are sent to OSS include third-level domains. The third-level domains contain the bucket information.

And a call to [`GetService`](https://www.alibabacloud.com/help/doc-detail/31957.htm) can yield the endpoint url, `<ExtranetEndpoint>oss-cn-shanghai.aliyuncs.com</ExtranetEndpoint>`. What we could do is just giving user a warning about they did not set their bucket's endpoint, and if they intend to do use this functionality later they can set it but if it is a simple `import-url` for example, then they can just fallback to the default solution which we resolve the bucket's location at runtime. Though after seeing this, i think it is not a priority any more. One thing that is important is just adding a check for `endpoint_url` being None, and raising the proper error then.
