### ISSUE TITLE
Very slow dvc pull from minio s3 server

### ISSUE THREAD

**Issue by shreshth211** [iterative/dvc#6324]
I have a dvc repo with about 3k files and a total size of 130G. When I restart a `dvc pull` that failed in the middle previously it starts with  `querying cache in $CACHE_DIR` which takes about 30 mins for just querying the 2.5k files.

My dvc version is `2.5.4` on linux and my remote is a self hosted minio s3 server on a docker container.

**Comment by pared** [comment]
Related #3261 #1970

**Comment by pared** [comment]
@shreshth211 have you tried tinkering with `--jobs` option?

**Comment by pared** [comment]
Closing as stale. We can reopen if the problem persists.
