### ISSUE TITLE
specify remote for data registry with push/pull command

### ISSUE THREAD

**Issue by kwon-young** [iterative/dvc#6327]
Hello,

Here is my setup:

* a private data registry `datasets`
  * git remote: org.gitlab.com/kchoi/datasets.git
  * 2 dvc remotes:
    * a default ssh dvc remote called `server`: ssh://server/somepath/datasets
    * another local dvc remote called `local`: /somepath/datasets

* my project named `myproject` consuming data from the data registry:
  * git remote: org.gitlab.com/kchoi/myproject.git
  * 2 dvc remotes:
    * a default ssh dvc remote called `server`: ssh://server/somepath/myproject
    * another local dvc remote called `local`: /somepath/myproject

In this data registry, there is two datasets: `dataset1` and `dataset2` which are imported in `myproject` using `dvc import`.

My use-case for having two dvc remotes is that I normally develop on my local machine which can access the dvc remote through ssh.

However, I also need to run my code on an hpc environment where ssh connections are not allowed.
So, when I do a `dvc pull -r local` on the hpc server, the pull fails because it cannot pull datasets from the data registry using the ssh remote `server`.

Would it be possible to add an option to commands like `dvc pull/push` to be able to specify the remote to use for data registries ?

**Comment by pared** [comment]
@kwon-young 
So in `myproject` you have `dataset1` and `dataset2` imported into the project using `dvc import` and you would like to download the data from `local` remote associated with `datasets` registry (`/sometpath/datasets`)?

**Comment by kwon-young** [comment]
yes, exactly.

**Comment by pared** [comment]
It seems that this is an original issue: https://github.com/iterative/dvc/issues/2466

**Comment by kwon-young** [comment]
ah yes, sorry I did not found that issue first.

This issue also adds the fact that `dvc pull/push` is also affected.

**Comment by kwon-young** [comment]
> @kwon-young push?

Now that you point it out, I agree that it does not make sense for push.

>  dvc pull is a bit different as it already has --remote.

Yes, it seems it will be a bit more tricky to implement for pull.

By the way, you can totally close this issue if you consider that everything is tracked by that other issue

**Comment by pared** [comment]
Sure, and I will probably do, but your point about `pull` is important, so we need to include that information in the original issue to not omit that :)

**Comment by pmrowla** [comment]
@pared can this be closed?

**Comment by pared** [comment]
@pmrowla yes, I think so #2466 seems to cover it.
