### ISSUE TITLE
Support smb:// protocal  for remote storage

### ISSUE THREAD

**Issue by roytseng-tw** [iterative/dvc#6350]
I want to use smb share for remote storage without mounting it to local.
It would be nice if you can support this. Thanks!

**Comment by efiop** [comment]
for the record: fsspec has an implementation for it in https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/smb.py , so should be fairly straightforward to make it work.

**Comment by roytseng-tw** [comment]
I tried to mimic other fs implementations and inherited the FSSpecWrapper, but encounter some problems when trying to push.
The step of "Querying cache" passed. 
However, the next step of "Transferring cache" errors for not founding the path on the remote. The path needs to be uploaded, so I thought it is okay to not exist on the remote. 
Wondering what have I missed?

**Comment by efiop** [comment]
@roytseng-tw Hard to say without looking into it. 🙁 Feel free to post verbose logs.
