### ISSUE TITLE
cli: show example usage on command line help

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6351]
Let's take an example of `poetry add -h`:
```console
$ poetry add -h
Help:
  The add command adds required packages to your pyproject.toml and installs them.

  If you do not specify a version constraint, poetry will choose a suitable one based on the available package versions.

  You can specify a package in the following forms:
    - A single name (requests)
    - A name and a constraint (requests@^2.23.0)
    - A git url (git+https://github.com/python-poetry/poetry.git)
    - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
    - A git SSH url (git+ssh://github.com/python-poetry/poetry.git)
    - A git SSH url with a revision (git+ssh://github.com/python-poetry/poetry.git#develop)
    - A file path (../my-package/my-package.whl)
    - A directory (../my-package/)
    - A url (https://example.com/packages/my-package-0.1.0.tar.gz)
```

We don't need it for all the commands, but most used commands that have too many options surely could be helpful.

**Comment by efiop** [comment]
@skshetry We have it in `import-url` and some other commands like that, but IIRC we've stopped doing that in favor of just having a doc link and updating examples on dvc.org. Less code for us, easier to maintain, fully under control of docs team to provide the best and most up-to-date examples.

**Comment by skshetry** [comment]
I don't think I have ever opened a link from some CLI tools when I am trying to use it to achieve something. 
If I am completely unfamiliar with the command, I'd open the documentation, but otherwise, I'd open `--help` and if I fail to find any information, I'll just search for it, I would never even think of opening that link.

The help message that I am proposing here is (`tldr`)[https://github.com/tldr-pages/tldr] like stuff, containing some examples of how-to achieve common scenarios rather than our docs which are a detailed reference.

And, as they are common, they should not change very often, so I don't think it's going to be more effort except when writing them at first.

**Comment by dberenbaum** [comment]
Sounds similar to https://github.com/tldr-pages/tldr:

```shell
$ tldr dvc add

dvc add

Add changed files to the index.
More information: <https://dvc.org/doc/command-reference/add>.

- Add a single target file to the index:
    dvc add path/to/file

- Add a target directory to the index:
    dvc add path/to/directory

- Recursively add all the files in a given target directory:
    dvc add --recursive path/to/directory

- Add a target file with a custom `.dvc` filename:
    dvc add --file custom_name.dvc path/to/file
```

**Comment by pmrowla** [comment]
Personally, with CLI tools I expect `-h/--help` to give me what DVC does now - a basic list of supported options & arguments.

If I need more info than that I would just check the man pages or the linked web docs.

**Comment by skshetry** [comment]
Closing as not planned.
