### ISSUE TITLE
handling authentication errors and providing how to set it up properly

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6353]
It'd be really great if we could have catch authentication errors from the filesystems and provide a link/hints on how to set it up properly.

Contextual information would be even useful (figure out if it's a `token` based login or a basic auth for example and provide appropriate links/hints).
This would also require us to have detailed how-to guides on setting up remotes individually on the docs side
(see [`rclone`'s docs](https://rclone.org/docs/) for inspiration)

cc @isidentical @shcheklein @jorgeorpinel

**Comment by shcheklein** [comment]
Related: https://github.com/iterative/dvc/issues/6325

**Comment by jorgeorpinel** [comment]
> This would also require us to have detailed how-to guides on setting up remotes individually

https://github.com/iterative/dvc.org/issues/1859

**Comment by skshetry** [comment]
Closing as not planned.
