### ISSUE TITLE
proposal: decouple pipeline runner/executor from repro?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6354]
We should decouple `Pipeline` management/runner/scheduler/executor stuff from the Repo which resides on `repro`.
It currently collects stages, builds a DAG, and then schedules the stage/task to run, and then runs them. The running part, which involves removing dependencies and outputs, checking some dependencies and outputs and running the command, and then saving the outputs later is all handled in the `Stage`. 

Honestly, to me, running yourself, as in `Stage` executing itself does not really make sense. It feels like this could be part of the `Pipeline` management thing itself.

#### Why decouple?
1. `Events` that we are discussing might make it difficult to hook into this, without a separate abstraction.
2. `exp run` calls `dvc repro` internally, which is a porcelain command, which feels like a hack. Sharing a common codebase between `exp run` and `dvc repro` is better than one using the other, as this will help us change UI output for both easily without affecting one another.
3. We might be able to separate UI output messages from data management commands. This might force us to really separate this with yet another abstraction for data management commands.
4. Decoupling is always a good thing? 

This might also open us a few opportunities to:
1. Run stages concurrently?
2. Provide hooks for runners rather than using env variables and signal files? I guess this is a "nice to have" thing.
3. Provide ways to handle outputs from the stage commands intelligently (as in, we might be able to suppress outputs from commands if required or place them in files, show them only when command errors out, etc.) and interactively.
4. Handle runtime contexts easily.

**Comment by skshetry** [comment]
@pmrowla, would be great to know what you think as you are also working on `executors`.

**Comment by pmrowla** [comment]
In general, decoupling pipeline execution from stage makes sense to me

> Provide hooks for runners rather than using env variables and signal files? I guess this is a "nice to have" thing.

More advanced hooks and a Python API would be nice for sure, but at least on the experiments/checkpoints side, signaling DVC to generate a checkpoint commit needs to be simple and language agnostic, which is why we just went with the file based signaling.

**Comment by karajan1001** [comment]
We have a stage executor experiments executor and maybe sometime later a remote executor. Any possibilities to merge them ?

**Comment by RomanSteinberg** [comment]
But, please, leave the command to build and execute pipeline at once.

**Comment by pmrowla** [comment]
@RomanSteinberg this discussion is regarding DVC code organization/modularity. The suggested changes would not affect any existing DVC commands from the user perspective

**Comment by skshetry** [comment]
> We have a stage executor experiments executor and maybe sometime later a remote executor. Any possibilities to merge them ?

@karajan1001, yeah, that's what I meant, to vertically cut-off completely from the executors to the stage run. This might help remote executors as they may have their own way of running commands. I might need this for UI as well. [pyinvoke](http://docs.pyinvoke.org/en/stable/api/__init__.html) might be a good inspiration.

**Comment by pared** [comment]
We got a request on our chat where the user would like to reproduce as many stages as possible:

When having multiple independent stages, when one of them fails, all are halted.
It seems to me that solving this issue could help introduce that.

Context: https://discord.com/channels/485586884165107732/485596304961962003/904736608950046750

**Comment by skshetry** [comment]
Another nice thing to have that'll be great for testing: support for running Python function instead of a command.

**Comment by skshetry** [comment]
Closing as stale.
