### ISSUE TITLE
Question: can one version with git files which are located inside a dvc-tracked directory

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc#6356]
There are cases when you would like to store some folder with DVC, but still version with git few files in it. This is usually the case when you treat the folder as one entity. It could be a ML model saved to a bunch of files, or folder with many images/text files if this folder represents some dataset, or just bunch of files related to each other along with few README.md and few others you want to keep in git. You may also want to see the entire folder as a whole in Studio later, to see the change in folder size or in files count.

The question is: could we do it with dvc?

As for an example, suppose we have this `folder`:

```
folder/meta.yaml
folder/something_pickled.pkl
folder/other-meta.json
folder/some-dataframe.csv
folder/plots/image1.jpg
...
```

What I want to have in my git repo is:
```
folder.dvc
folder/meta.yaml
folder/other-meta.json
```

One of the ways to achieve this would be to use `.dvcignore`. So I specify it there:
```shell
$ cat .dvcignore
*.json
*.yaml
```

But it happens that dvc adds a folder to `.gitignore` entirely, ignoring what was specified in `.dvcignore`:

```shell
$ dvc add images
100% Add|████████████|1/1 [00:01,  1.01s/file]

To track the changes with git, run:

	git add images.dvc .gitignore
$ cat .gitignore
/images
```

And even then if you do
```shell
$ git add -f folder/meta.yaml folder/other-meta.json
```

I still can't `dvc add folder` again, because some files inside are versioned with git:

```
$ dvc add images
Adding...
ERROR:  output 'images' is already tracked by SCM (e.g. Git).
    You can remove it from Git, then add to DVC.
        To stop tracking from Git:
            git rm -r --cached 'images'
            git commit -m "stop tracking images"
```

**Comment by efiop** [comment]
Hi @aguschin 

Unfortunately there is no way to store files in a dir in git while having that dir tracked by dvc. This is caused by dvc treating the directory as a one whole thing.

**Comment by shcheklein** [comment]
Can it be used with .dvcignore ? (Like I ignore one specific file in the directory for example and put it into Git, repro still deletes the whole output though).

**Comment by karajan1001** [comment]
I had tried, it can be done with the help of `.dvcignore`. The only thing that needs to be noticed is that you need to rewrite your `.gitingore` because it would ignore the whole directory. 
from 
```
folder 
```
to
```
folder/*
!folder/meta.yaml
!folder/other-meta.json
```

**Comment by RomanSteinberg** [comment]
@aguschin I would like to suggest not doing it. You are trying to separate 1 thing (model) and store its part in two different storages. Your colleague can forget to make one of two actions (`dvc pull` or `git pull`) and get strange state in repo. So, just store everything in dvc.

If you wish to separate model from its additional info, which could be useful in code repo (git) and not data repo (dvc), use folder structure like this:

-- model
---- main
---- additional 

So, you can track main with dvc and additional with git if it necessary. But I think it is rare case and my opinion is to store everything in dvc.
