### ISSUE TITLE
foreach stage invalid

### ISSUE THREAD

**Issue by RomanSteinberg** [iterative/dvc#6362]
# Bug Report

dvc.yaml schema: foreach is not valid

## Description
I use PyCharm and it notifies me that `foreach` is not valid field for `dvc.yaml` (expects `cmd` instead), but it works well!
Here is the [screenshot](https://ibb.co/zQsfD7p).

### Reproduce

1. Open Pycharm
2. Create dvc.yaml
3. Describe foreach stage

### Expected

No validation error.

### Environment information

Ubuntu 20.04
PyCharm CE 2020.2

**Output of `dvc doctor`:**

```console$ 
DVC version: 2.5.4 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.8.0-63-generic-x86_64-with-glibc2.29
Supports:
	http (requests = 2.22.0),
	https (requests = 2.22.0),
	ssh (paramiko = 2.7.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb6
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sdb6
Repo: dvc, git
```

**Additional Information (if any):**
None

**Comment by daavoo** [comment]
Hi @RomanSteinberg , this is probably a duplicate of https://github.com/iterative/dvc/issues/6076 . Please go to the link to read the discussion

**Comment by RomanSteinberg** [comment]
@daavoo right. Sorry, I forgot to search first.
