### ISSUE TITLE
Irrelevant error message: OutputDuplicationError

### ISSUE THREAD

**Issue by RomanSteinberg** [iterative/dvc#6363]
# Bug Report

## Description

I had a data file `2018-2021uvcextracted.pickle` and corresponding dvc-file (`2018-2021uvcextracted.pickle.dvc`). I decided to make pipeline (`dvc.yaml`). One of its stages used `2018-2021uvcextracted.pickle` as an output. I've got an [error message](https://ibb.co/sqXKqXs), which confused me a lot. It says "the file is specified in stages: ..." I know that stages are described in `dvc.yaml` and I couldn't find any stage named `2018-2021uvcextracted.pickle.dvc` (look at [screenshot](https://ibb.co/sqXKqXs)). Also I couldn't find any stage with duplicating `2018-2021uvcextracted.pickle`. Later I understood that dvc-file was considered as a stage by dvc-system too. But I haven't found such terminology in online documentation.

### Reproduce

1. dvc init
2. Create a.dat and b.dat
3. dvc add a.dat b.dat
4. Create dvc.yaml like this
```yaml
stages:
  cmd: cat a.dat
  deps:
    - a.dat
  outs:
    - b.dat
```
6. dvc dag -v 

### Expected

Error message like this:
OutputDuplicationError: the file ... is specified as output of the stage and is tracked using dvc-file

Or

You can consider removing .dvc-files in such case, but I'm not sure and it is a subject of discussion.

### Environment information

Ubuntu 20.04
PyCharm CE 2020.2

**Output of `dvc doctor`:**

```console$ 
DVC version: 2.5.4 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.8.0-63-generic-x86_64-with-glibc2.29
Supports:
	http (requests = 2.22.0),
	https (requests = 2.22.0),
	ssh (paramiko = 2.7.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb6
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sdb6
Repo: dvc, git
```
**Additional Information (if any):**
None

**Comment by RomanSteinberg** [comment]
@mattseddon what does it mean? Do you think this bug should live forever?

**Comment by shcheklein** [comment]
@RomanSteinberg confusing message is not okay at all, we would appreciate a quick PR to improve it (we can just expand it I guess to say "... or tracked in a dvc-file".  I can help to review and merge this.

We are closing tickets that are not the highest priority, for which we are not getting a lot of thumbs up or complaints, so that we can have a focused backlog.

Thank you for understanding! We are a small team and it's easier for us to manage the project if we have cleaner issue tracker with those tickets that we can promise to take care of soon.

**Comment by RomanSteinberg** [comment]
Hello @shcheklein !
It was 2.5 year. I am out of context for sure and can't provide you a quick PR. 

Cleaner issue tracker and focus are good points. I can understand that. But please do not do it silently.

Good luck!
