### ISSUE TITLE
Pinning for aiobotocore dependency (s3 remote) is too strict.

### ISSUE THREAD

**Issue by hugo-ricateau** [iterative/dvc#6366]
As of `dvc==2.5.4` (holds for older versions as well), `setup.py` pins `aiobotocore[boto3]==1.3.0` for `s3` remote use. Such a strict pinning of `aiobotocore` results in an equally strict pinning of `botocore` (which is quite natural for an adapter library). The direct consequence is that having both `dvc[s3]` and `boto3` in the same `requirements.in` makes it impossible to compile most of the time (at least until `pip-tools` gets a better resolver implemented). Would it be conceivable to release a bit the constraint on the `aiobotocore[boto3]` version pinning?

**Comment by efiop** [comment]
@isidentical WDYT, do we need to keep it pinned anymore?

**Comment by isidentical** [comment]
Since we use both `aiobotocore` and `boto3`, it is really important to make them both compatible. I don't recall any particular problem that was related to aiobotocore version so we might relax it a bit (`>1.0.1` instead `==1.3.0`) and see where it goes.

**Comment by hugo-ricateau** [comment]
Hi @efiop; thanks for the quick fix. Is it planned for a release today?

**Comment by efiop** [comment]
@hugo-ricateau I'm afraid that's the bad news here. We are currently in a grace period, caused by internal changes, so we didn't plan releasing this week (likely the next one). Would you be able to use upstream for now?

**Comment by hugo-ricateau** [comment]
Thanks for this fast answer. Waiting until next week is a reasonable option.
