### ISSUE TITLE
`dvc exp gc`: Get affirmation and report the deleted experiments

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc#6384]
The current behavior of `dvc exp gc` doesn't report the id's of deleted experiments. It only reports the number of experiments that have been deleted. I would like to have:

1. A confirmation dialog similar to `dvc exp show` that lists which experiments are _to be deleted_, or _to be kept_, (but _deleted_ is better IMO).
2. A list of experiments that are deleted after the command runs.

**Comment by dberenbaum** [comment]
Closing since we now have `dvc exp remove` and plan to deprecate `dvc exp gc`.
