### ISSUE TITLE
Dockerize git+dvc

### ISSUE THREAD

**Issue by INF800** [iterative/dvc#6391]
Hi,

I am planning to setup **private** git server and dvc for my organisation. 
Can anyone help me with how to write docker file?

Something like this - https://hub.docker.com/r/jkarlos/git-server-docker/ ?

**Comment by pmrowla** [comment]
Hi, we don't provide any official docker images, but there is an existing discussion regarding docker images here: https://github.com/iterative/dvc/discussions/5934

You may want to start by referring to the CML docker images (linked in that discussion) which do include DVC (but do not include a standalone git server).
