### ISSUE TITLE
Add TOML support for metrics

### ISSUE THREAD

**Issue by flippedcoder** [iterative/dvc#6402]
Right now, there is only TOML file support for params files. We need to add TOML support for metrics as well.

Here's a [link to the Discord question](https://discord.com/channels/485586884165107732/485596304961962003/865974923079319563) that brought this up.

**Comment by pmrowla** [comment]
Is this a high priority issue? We don't get many requests for TOML metrics support (that one discord question is the only one in the last couple of years as far as I can tell)

**Comment by dberenbaum** [comment]
It's not high priority, but a user did request it, so @flippedcoder volunteered to open an issue for it.

**Comment by skshetry** [comment]
Anyone looking for contributing, the place to add the support is here:
https://github.com/iterative/dvc/blob/6c646a70703cc68991eeb3232748b39c759c942c/dvc/repo/metrics/show.py#L70

Please compare that to the `params` which already supports `toml` file:
https://github.com/iterative/dvc/blob/6c646a70703cc68991eeb3232748b39c759c942c/dvc/repo/params/show.py#L53-L55

Also note that, `LOADERS` also supports reading `.py` files which we might need to forbid here, if we use it in the metrics.
