### ISSUE TITLE
how to use dvc across repositories. 

### ISSUE THREAD

**Issue by dingusagar** [iterative/dvc#6409]
I have 2 repositories. One where I maintain the training data and train the model. Another one which is actually a flask app that uses the model for inference. Wanted to use dvc for versioning the models, but dvc is coupled with one git repository, 

Basically i want to train the model in repo 2, version the model using dvc there, upload the model to the cloud (s3). 
Then in the repo 1 (flask app repo), i want to fetch this model from s3 and use it.

**Comment by dberenbaum** [comment]
Can you at least have dvc installed as a dependency in repo 1? If so, you can use `dvc.api.open()` to fetch the model: https://dvc.org/doc/api-reference/open#example-use-data-or-models-from-a-dvc-repository.

**Comment by dingusagar** [comment]
yes, dvc is installed in repo1. looks like the solution you posted will fix the issue i was facing. 
thanks a lot.
