### ISSUE TITLE
Unable to pull files from s3 remote

### ISSUE THREAD

**Issue by DrissiReda** [iterative/dvc#6410]
I have initialized an empty repository with git/dvc.

I have created a small dataset and pushed it to s3, I can see the same files under `.dvc/cache` on the correct path under my s3 storage, for reference:

```
├── 02
│   └── 9c9cd22461f6dbe8d9ab01def965c6
└── 61
    └── fdd54abdbf6a85b778e937122e1194

```
I add the files to dvc with the command:

```
dvc add data/train.csv data/test.csv
```

I push them to my remote with:

```
dvc push data/train.csv.dvc data/test.csv.dvc
```

When I delete `.dvc/cache`, and try to pull the files from s3 remote with:

```
dvc pull data/train.csv.dvc
```

I get the errors:

```
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
name: train.csv, md5: 61fdd54abdbf6a85b778e937122e1194
WARNING: Cache 'md5: 61fdd54abdbf6a85b778e937122e1194' not found. File 'train.csv' won't be created.
1 file failed                                                                   
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
train.csv
Is your cache up to date?
<https://error.dvc.org/missing-files>

```

Which is funny because it says it can't find the md5 hash: `61fdd54abdbf6a85b778e937122e1194` but the hash on the s3 remote (and the way it has been under cache) is `61/fdd54abdbf6a85b778e937122e1194`

This is my s3 config:

```ini
[core]
    remote = s3-remote
['remote "s3-remote"']
    url = s3://sample-dvc
    endpointurl = http://minio.local/dvc
    access_key_id = minio
    secret_access_key = password
```

Any ideas?

**Comment by isidentical** [comment]
Can you share the output of `dvc doctor`?

**Comment by DrissiReda** [comment]
here you go @isidentical 

```
DVC version: 2.5.4 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-80-generic-x86_64-with-glibc2.29
Supports:
	hdfs (pyarrow = 1.0.1),
	http (requests = 2.21.0),
	https (requests = 2.21.0),
	s3 (s3fs = 2021.6.1, boto3 = 1.17.49),
	ssh (paramiko = 2.7.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc1
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sdc1
Repo: dvc, git


```

**Comment by isidentical** [comment]
Can you try to install the latest version of dependencies, seems like s3fs points to an older version. `pip install --upgrade "dvc[s3]"`

**Comment by DrissiReda** [comment]
dvc[s3] keeps downgrading s3fs even when I upgrade it manually...

**Comment by isidentical** [comment]
Ah, seems like the latest revision came bundled with `6.1` instead of `7.0`. Would you mind giving a shot at installing DVC from git, `pip install "dvc[s3] @ git+https://github.com/iterative/dvc"`

**Comment by DrissiReda** [comment]
Still fails, here is the `dvc doctor`

```
DVC version: 2.5.4+fb96b1 
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-80-generic-x86_64-with-glibc2.29
Supports:
	http (requests = 2.26.0),
	https (requests = 2.26.0),
	s3 (s3fs = 2021.7.0, boto3 = 1.17.106)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sdc1
Repo: dvc, git
```

**Comment by isidentical** [comment]
Can you ensure that the file is present in the remote in the following address `s3://sample-dvc/61/fdd54abdbf6a85b778e937122e1194`?

**Comment by DrissiReda** [comment]
Like I’ve shown above it is indeed present. If I download it manually and put it under local cache in `.dvc/cache`. The command dvc pull works. It just has trouble with s3

**Comment by isidentical** [comment]
I do not see anything too obvious about what is going on. Can you check minio logs about whether is there some problem on the minio side (e.g returning 404 when DVC is trying to make an `exists` call)?

**Comment by DrissiReda** [comment]
nop minio logs are empty...

Minio errors are usually more on the client side, and the command dvc pull doesn't show any minio errors.

The verbose output doesn't shed any more light. I don't know what else to try to get more info.

**Comment by DrissiReda** [comment]
@isidentical A test I have made to make sure there is nothing I'm missing:

1. Download all of the contents of s3 from sample-dvc.
2. Create a folder `.dvc/cache`.
3. Copy everything I downloaded from `s3://sample-dvc` to `.dvc/cache`.
4. Retry `dvc pull` successfully. 

So dvc pulled the content from the local cache with success, but the same files present on s3 couldn't be downloaded.....

**Comment by isidentical** [comment]
Can you try to list `sample-dvc` through `aws s3` command line utilities? E.g `aws s3 ls s3://sample-dvc`

**Comment by DrissiReda** [comment]
it works, I'm getting :

```
                           PRE 02/
                           PRE 61/
                           PRE 8b/
                           PRE b1/
                           PRE ba/
                           PRE d8/
                           PRE ee/
```

But the command is `aws s3 ls --endpoint-url=http://minio.local/ s3://dvc/sample-dvc`.

Since awscli requires the bucket name in the s3 path, whilst dvc requires it in the url.

**Comment by isidentical** [comment]
```
['remote "s3-remote"']
    url = s3://sample-dvc
    endpointurl = http://minio.local/dvc
    access_key_id = minio
    secret_access_key = password
```

Can you set the endpoint url to `minio.local` just like you did for the s3, and then set the url to `s3://dvc/sample-dvc`?

**Comment by DrissiReda** [comment]
Surprisingly this works better. It could've been a bit easier to debug if there was an error such as `NoSuchBucket` .

**Comment by isidentical** [comment]
I am not sure about how minio endpooint url's work with buckets, though DVC urls always use this convention: `s3://<bucket>/path`. By the way what do you mean by "works better"? Did it solve the issue or is there a new error?

**Comment by DrissiReda** [comment]
It solved the issue, I got another unrelated error that's my mistake.

**Comment by msk-psp** [comment]
I just encountered this issue, but it solved when I re-configured aws credentials
