### ISSUE TITLE
dvc failed to fetch data from the remote 

### ISSUE THREAD

**Issue by darker008** [iterative/dvc#6412]
# Bug Report

### Reproduce
I setup a dvc remote with ssh, 
and push large to that.
however now I found dvc client failed to fetch data from remote 

1. dvc init --no-scm
2. dvc remote add $remote_name $url
3. dvc fetch -r $remote_name

### Expected
data files can be fetched from dvc remote

### Environment information
dvc remote: ssh, sftp
dvc version: 0.41.3

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
the console log is:
[##############################] 100% Collecting information
[##############################] 100% Analysing status.
Everything is up to date.

there is no error info in log, and no data in .dvc/cache folder

**Additional Information (if any):**

**Comment by karajan1001** [comment]
DVC only fetches caches that are tracked by `.dvc` file or `dvc.yaml`. So I guess you need to import those files into this new repo. Two common ways to do that:
1. git fetch the old repo.
2. use `dvc import` from the old repo.
