### ISSUE TITLE
http: migrate to fsspec

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#6413]
`http` is an important remote, and we should migrate it to fsspec. There is already a built-in http filesystem inside `fsspec`, but it seem to lack a couple of features we depend. So there should be some benchmarkings to determine whether we should create a sync, `requests` backed `httpfs` or just use the `HTTPFileSystem` from fsspec.

**Comment by isidentical** [comment]
It seems like with some changes (see https://github.com/intake/filesystem_spec/pull/731) passes all the functional tests against HTTP. I am now moving to the phase of running benchmarks, but some early microbenchmarks indicate that as is aiohttp is not as performant as requests when it comes to the threaded code. Still need to do more concrete examples (thinking about https://github.com/iterative/dvc/issues/6222 using as a benchmark case).

**Comment by isidentical** [comment]
I might've spoke a bit too soon, seems like it was causing due to a weird race which now is fixed but still it is not outperforming, but just catching up;

```
http://speedtest-ny.turnkeyinternet.net/1000mb.bin (get-url)

    regular: 4m9.420s
    httpsfs: 4m1.616s

dataset-registry/mnist/images (pull)

    regular: 19m0.577s (1 fail)
    httpfs: 18m54.310s (no fail)
```

**Comment by skshetry** [comment]
> but still it is not outperforming, but just catching up;

@isidentical, did you check with [`HTTPStreamFile`](https://github.com/intake/filesystem_spec/blob/06d1c7c9668377d37137e11dc7db84fee14d2d1b/fsspec/implementations/http.py#L603)? We stream download the file using `IterStream`, whereas default `open` uses chunking. 
https://github.com/iterative/dvc/blob/13d1276a12975625774fc9a802dc07f6144d0792/dvc/utils/stream.py#L11

**Comment by isidentical** [comment]
Also we directly use `get_file` / `put_file` so I don't think `HTTPStreamFile` affects anything in the benchmarks.
