### ISSUE TITLE
`exp show`: Include data files.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#6434]
If an user modifies data files in between `dvc exp run` calls, the change is not reflected in the table generated by `dvc exp show`.

In [Studio](https://studio.iterative.ai) users can view information of the data files associated to each `experiment`. I think it would be nice to include similar information in the table generated by `dvc exp show`.

Ideally, the feature would have the same options available for `metrics` and `params` (i.e. `--include-files`/`--exclude-files`).

**Comment by shcheklein** [comment]
+1 on this. I'll be important for VS Code. On a separate note. We haven't touched source files in the Studio yet, but it would be great to have signal in the table from which you can see that there are changes to the source files between experiments.

**Comment by pmrowla** [comment]
What should the table actually show? I don't think actually including a list of changed files in the CLI table is feasible due to the size constraints.

So should it just be a true/false column to note that there is a change to data files (so users know they should check the changes with `dvc diff`? Or maybe columns for `added/modified/removed` with counts that would match the summary totals you get from `dvc diff`?

**Comment by karajan1001** [comment]
But if we use `added/modified/removed`, there comes another question. These notions only represent the status compare to default/workspace version. Unlike with the numbers it is hard to know the differences between two `modified` exps.

**Comment by pmrowla** [comment]
For experiments in the table it would have to be the diff between the experiment and the original baseline git commit (not the diff of one experiment to another experiment)

**Comment by daavoo** [comment]
> +1 on this. I'll be important for VS Code. On a separate note. We haven't touched source files in the Studio yet, but it would be great to have signal in the table from which you can see that there are changes to the source files between experiments.

Any source files or just source files that are `deps` of a stage?

**Comment by dberenbaum** [comment]
What is meaningful info to show about data files? Just whether they have changed from the baseline commit? Size? Number of files? Maybe there is some tag/label/metadata that would be helpful?

Also, what files should be included (dependencies, outputs, dvc-tracked files, all files)?

> Ideally, the feature would have the same options available for `metrics` and `params` (i.e. `--include-files`/`--exclude-files`).

If we add data files to the `dvc exp show` table, it will become even more important to provide easy ways to narrow the table. Adding more info is not universally desirable since the table can become too busy. See:

* #6271
* #5966
* #6451

**Comment by shcheklein** [comment]
> Any source files or just source files that are deps of a stage?

I would say just a binary signal that some sources have changed is a good start. 

> Also, what files should be included (dependencies, outputs, dvc-tracked files, all files)?

My take (from Studio experience) - inputs (datasets) is the most important part. Les so intermediate, etc. We can start with datasets only if want to keep the table sane.

> What is meaningful info to show about data files? Just whether they have changed from the baseline commit? Size? Number of files? Maybe there is some tag/label/metadata that would be helpful?

Good question. I think some signal that data has changes is enough (we highlight values in Studio with a special dot icon or something like this). Values - we could do size to start. In Studio users can switch between those.

**Comment by karajan1001** [comment]
Show the same thing in `dvc status` is the first step.

**Comment by dberenbaum** [comment]
Another idea here is to encourage use of the `desc` field and show that in the table.

**Comment by daavoo** [comment]
> Another idea here is to encourage use of the `desc` field and show that in the table.

In addition, we could show the `rev` (or other selectable property, line in Studio https://github.com/iterative/studio-support/issues/16)

**Comment by daavoo** [comment]
> Another idea here is to encourage use of the `desc` field and show that in the table.

Related https://github.com/iterative/dvc/issues/6548

**Comment by karajan1001** [comment]
> Another idea here is to encourage use of the `desc` field and show that in the table.

But the problem is that as we didn't change the `desc` after the `.dvc` file had been generated, it stays the same in all of the revisions. Cann't be taken any comparison.

**Comment by dberenbaum** [comment]
I was thinking that users might update the description when they make changes, like `cats` -> `cats and dogs`. Maybe it would be better to track the last modified commit and show the commit message 🤷 .

**Comment by karajan1001** [comment]
> I was thinking that users might update the description when they make changes, like `cats` -> `cats and dogs`. Maybe it would be better to track the last modified commit and show the commit message 🤷 .

Only support for `.dvc` files not for pipeline generated ones? That's make sense, Only those `dvc add` generated data need a human-readable meaning, those generated via pipeline ones can be represented by the parameters from stages.
