### ISSUE TITLE
dvc in distributed file system

### ISSUE THREAD

**Issue by rahulguptajss** [iterative/dvc#644]
Can you please explain how dvc behaves if my data is scattered across multiple machines? What if data is large enough such that it can not fit in single machine?

**Comment by efiop** [comment]
Currently dvc can only use local cache, so yes, you have to have enough storage on your machine to be able to store all the cache of your current pipeline.

**Comment by efiop** [comment]
However we do plan to support external files in the future, see https://github.com/dataversioncontrol/dvc/issues/642 .

**Comment by dmpetrov** [comment]
@rahulguptajss I would appreciate if you can give more details on this scenario.

1. How is the data distributed? Do you use HDFS or just a set of machines with files or something different?
2. What do you do on the distributed system and what would you prefer to do in a single machine environment? Storing data/data preparation/data cleaning/building models/evaluating models/visualisation.
3. What do large data mean? 1Gb/10Gb/100Gb/1Tb?
4. If you do ML modeling in a distributed system what framework do you use?
5. Do you already use any ETL pipeline system such as Oozie, Airflow or Luigi? #645 
6. If you use ETL pipelines, do your data scientists (guys who work on ML models) suppose to integrate their work into the pipelines (Oozie or Airflow) or ML "productization" it is a separate engineering activity?

This will help us to understand the scenario better and provide better solution.

**Comment by rahulguptajss** [comment]
Hi,
Please find below response.
1: Data is currently in HDFS. Currently for dvc to work, all data needs to be on single machine. This is not very scalable and have several bottlenecks with respect to CI/CD pipeline. We only would want results in the Jenkins docker.
2: We will be using spark ml to work with our data which is primarily in HDFS. Idea is to kick off the work on spark clusters so that data doesn't have to reside in single machine.
3: Our use case is more for financial services so Data will be fairly huge and can very well go beyond 1 TB.
4: Spark
5: Currently it is Airflow as orchestrator and Spark jobs underneath. There is some work also going on with Apache beam.
6: It is definitely a separate activity. DS doesn't have to worry about this. It will be plug and play component.

Regards,
Rahul

**Comment by rahulguptajss** [comment]
Hi,

Can you please provide an update on this.

Thanks.

**Comment by efiop** [comment]
Hi @rahulguptajss 

Support for some types of external dependencies(s3, gcp, local for sure and maybe some others) is going to be added in 0.9.7, which we are currently working on.

**Comment by rahulguptajss** [comment]
Thanks for the info. If possible can u provide some tentative date for 0.9.7 release.

**Comment by efiop** [comment]
Unfortunately we decided to move implementing this to 0.9.8.

**Comment by efiop** [comment]
Support for s3/gs/hdfs/ssh deps/outs/cache has been merged and will be released in 0.10.0. Closing.
