### ISSUE TITLE
Epic: remote executors

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6440]
Parent issue for remote executor issues.

Linked issues:

- [x] #6263 
- [x] #6264 
- [ ] #6265 
- [ ] #6266 
- [ ] #6267 
- [ ] #6268 
- [ ] #6269 
- [ ] #6270

**Comment by dberenbaum** [comment]
Need to rescope this feature

**Comment by karajan1001** [comment]
Someone asking for running DVC in a lambda instance

https://discord.com/channels/485586884165107732/563406153334128681/1051517217478553640
