### ISSUE TITLE
`exp run`: `--glob` option doesn't work

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc#6457]
# Bug Report

## Description

`dvc repro --glob 't*'` runs all the stages starting with `t` in the current directory. 

`dvc exp run --glob 't*'` looks for a stage having the name `t*`, and it can't find. 

### Reproduce

```
dvc stage add -n t1 echo t1
dvc stage add -n t2 echo t2
dvc stage add -n t3 echo t3
dvc stage add -n t4 echo t4
dvc exp run --glob 't*'
```

### Expected

I expect `--glob` to run multiple stages. 

### Environment information

`dvc 2.6.3`

**Comment by skshetry** [comment]
`--glob` is unsupported for now, as `checkout` still does not support it.

**Comment by skshetry** [comment]
Closed by #6458.

**Comment by pmrowla** [comment]
@dberenbaum @karajan1001 this is another experiments ticket which can be addressed after the remote ref deletion issue (see https://github.com/iterative/dvc/pull/6458#discussion_r691044998 for more details)

**Comment by dberenbaum** [comment]
Referenced in https://github.com/iterative/dvc.org/issues/2730. @iesahin Can you give more context on why you want to introduce `dvc exp run --recursive` in the guide?

@pmrowla Is this still blocked by the issue linked above?

**Comment by pmrowla** [comment]
This was never blocked by the linked issue (I was just noting that this could be added to the list of potential exp issues to take in that sprint)

**Comment by dberenbaum** [comment]
It seems we should either prioritize this or remove the option then?

**Comment by iesahin** [comment]
> Can you give more context on why you want to introduce `dvc exp run --glob` in the guide?

Actually I don't want to introduce. We currently introduce it indirectly  in https://dvc.org/doc/command-reference/exp/run by saying "`dvc exp run` supports all `dvc repro` options.` If it will distract the team to implement this in the near future, I think it might be better to list supported options explicitly in the ref. @pmrowla

**Comment by dberenbaum** [comment]
@iesahin Is this the only remaining option that doesn't have parity with `repro`?

**Comment by iesahin** [comment]
I need to test each of them to be sure but if the team decides not to implement it, we should remove `--glob` from `dvc exp run --help`.

**Comment by dberenbaum** [comment]
@skshetry Is it possible to glob the stages before checkout and only checkout the pre-filtered stages? Why does this break `--glob` but other stage selection options like `--downstream` work despite not having corresponding options in checkout?

**Comment by dberenbaum** [comment]
> I need to test each of them to be sure but if the team decides not to implement it, we should remove `--glob` from `dvc exp run --help`.

This is done, so lowering the priority of this one.

**Comment by dberenbaum** [comment]
Closing until there is some request to implement `exp run --glob`.
