### ISSUE TITLE
`dvc doctor` very slow on WINDOWS

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#6463]
# Bug Report

https://user-images.githubusercontent.com/6745454/130033315-f0d54435-d253-4a2d-9095-07bf15ed02c0.mp4

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
DVC version: 2.6.0+a285d2
---------------------------------
Platform: Python 3.8.3 on Windows-10-10.0.19041-SP0
Supports:
        gdrive (pydrive2 = 1.6.2),
        hdfs (pyarrow = 1.0.1),
        http (requests = 2.24.0),
        https (requests = 2.24.0)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: NTFS on D:\
Repo: dvc, git

**Additional Information (if any):**

**Comment by efiop** [comment]
@karajan1001 Could you please run it with `--cprofile-dump doctor.prof` and share `doctor.prof`?

Btw, is antivirus or windows defender enabled? If so, could you try it with it turned off, please?

**Comment by karajan1001** [comment]
Seems that it is because of Microsoft Defender Firewall.

**Comment by efiop** [comment]
@karajan1001 Did turning off analytics or updater help?

**Comment by karajan1001** [comment]
> @karajan1001 Did turning off analytics or updater help?

Both didn't help.
