### ISSUE TITLE
push: unexpected error - module 'aiobotocore' has no attribute 'AioSession'

### ISSUE THREAD

**Issue by severinsimmler** [iterative/dvc#6466]
# Bug Report

## Description

`aiobotocore` v1.4.0 was released and it breaks DVC's `push` command. See also `aiobotocore`'s [changelog](https://github.com/aio-libs/aiobotocore/blob/master/CHANGES.rst#140-2021-08-20).

### Reproduce

1. `python -m venv .env`
2. `source .env/bin/activate`
3. `pip install dvc[s3]`
4. `dvc push`

### Expected

The files should be pushed to my S3 bucket.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.6.3 (pip)
---------------------------------
Platform: Python 3.9.6 on Linux-5.11.0-27-generic-x86_64-with-glibc2.31
Supports:
	http (requests = 2.26.0),
	https (requests = 2.26.0),
	s3 (s3fs = 2021.7.0, boto3 = 1.17.106)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/vgubuntu-root
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git
```

**Comment by SdgJlbl** [comment]
The same change also affect `dvc status --cloud` command.

**Comment by efiop** [comment]
Thanks for reporting this problem, guys! :pray: Looks like this is the cause https://github.com/dask/s3fs/issues/514 and we need to upgrade dvc to use new s3fs version. A workaround for now is for you to downgrade aiobotocore to 1.3.3

**Comment by garzillo** [comment]
confirmed that pinning to `aiobotocore==1.3.3` solves this issue

**Comment by efiop** [comment]
Thanks for the feedback! dvc 2.6.4 with the fix is out on pypi, other package will follow soon.
