### ISSUE TITLE
Run an experiment with a targeted dvc pipeline name

### ISSUE THREAD

**Issue by ankurrajdev** [iterative/dvc#6467]
Hi, I recently updated to the latest version for DVC to run experiments. I have multiple dvc piplines in my project. When I run ```dvc exp run --run-all```, it kinds of try to run all the dvc pipelines and pushes the files.

I sit possible to add a targeted verion to run a specific pipeline in an experiment.

This is in line with how dvc repro and dvc repro 'targeted step' works.

Thank you

**Comment by jorgeorpinel** [comment]
> I sit possible to add a targeted verion to run a specific pipeline in an experiment.

Yes, `dvc exp run` accepts the same targets as `dvc repro`. Please see https://dvc.org/doc/command-reference/repro#options and let us know if that answers your question @ankurrajdev .

**Comment by pmrowla** [comment]
Note that you should specify the target you want to run when you do the queuing step, rather than the `--run-all` step

```
dvc exp run --queue <target>
```

**Comment by ankurrajdev** [comment]
Thank you. I was adding it to the --run-all step.
