### ISSUE TITLE
DVC pipeline parallel steps

### ISSUE THREAD

**Issue by rahulguptajss** [iterative/dvc#647]
Does DVC supports parallel steps in its pipeline. I am unable to create parallel steps using dvc command.

**Comment by efiop** [comment]
No, dvc doesn't support parallel execution of stages as of today. We do have plans to support it in the future.

**Comment by rahulguptajss** [comment]
Can you please provide any timeline for this.

Thanks.

**Comment by efiop** [comment]
0.9.8 most certainly.

**Comment by rahulguptajss** [comment]
Thanks. It will be helpful when we have multiple models to be run on same data with separate py files.

**Comment by efiop** [comment]
Wait a minute, did you mean 'parallel execution' or just 'parallel steps'? We do not support parallel execution as of now, only executing stage-by-stage. However, parallel stages should work:
```
echo foo > foo
dvc add foo
dvc run -d foo -o out1 cp foo out1 # stage1
dvc run -d foo -o out2 cp foo out2 # stage2
```

**Comment by rahulguptajss** [comment]
yes, actually for this thread , I was looking for parallel steps. I'll try this and update.

**Comment by efiop** [comment]
Closing as stale. Please feel free to reopen.

As for parallel execution, there is a https://github.com/iterative/dvc/issues/755 planned for 0.11.0.
