### ISSUE TITLE
Enable environment variable based AWS authentication

### ISSUE THREAD

**Issue by felipegssantos** [iterative/dvc#6473]
> From https://github.com/iterative/dvc.org/issues/2746#issuecomment-903885917

Currently, DVC works properly with S3 as a remote if your authentication details are in a `~/.aws/credentials` file. However, it does not work based on `AWS_*` like environment variables, which is supported by boto3 and aws-cli. Enabling this authentication form would be desirable in order to make DVC's experience more similar to aws-cli's.

**Comment by felipegssantos** [comment]
@shcheklein sure.

Steps to reproduce: 

1. Set remote storage to an S3 bucket.
2. Set environment variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_DEFAULT_REGION`.
3. `dvc add` data files.
4. `dvc push` your changes to S3 remote.

Expected error:
```
ERROR: failed to transfer '<PATH_TO_CACHED_FILE>' - Failed to upload <PATH_TO_CACHED_FILE> to <PATH_TO_REMOTE>: An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
```

Output to `dvc version`:

```
$ dvc version
DVC version: 2.6.0 (brew)
---------------------------------
Platform: Python 3.9.6 on macOS-11.5.2-x86_64-i386-64bit
Supports:
	azure (adlfs = 2021.8.1, knack = 0.8.2, azure-identity = 1.6.0),
	gdrive (pydrive2 = 1.9.0),
	gs (gcsfs = 2021.7.0),
	http (requests = 2.26.0),
	https (requests = 2.26.0),
	s3 (s3fs = 2021.7.0, boto3 = 1.17.106),
	webdav (webdav4 = 0.9.0),
	webdavs (webdav4 = 0.9.0)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Comment by pared** [comment]
@felipegssantos and if you input your profile into `~/.aws/credentials` is setting `AWS_PROFILE` working for you?

**Comment by pared** [comment]
I am unable to reproduce the problem - setting up credentials both via `AWS_PROFILE` and `AWS_ACCESS_KEY_ID` (and friends) work for otherwise not working script. @felipegssantos could you retry with latest version of the `dvc`? What kind of terminal are you using?
