### ISSUE TITLE
import-url - error and messaging issues

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#6477]
1. Missing destination

```$ dvc import-url s3://dmpetrov
ERROR: unexpected error - [Errno 17] File exists: '.'
```
It is easy to recognize the missing parameter and exit with a proper error or import as `dmpetrov`.

2. Long and not informative error:
```
$ dvc import-url s3://dmpetrov pppp
Importing 's3://dmpetrov' -> 'pppp'  
ERROR: failed to import s3://dmpetrov. You could also try downloading it manually, and adding it with `dvc add`. - dependency 's3://dmpetrov' does not exist

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

a) `Importing 's3://dmpetrov' -> 'pppp' ` - Do we need this message? It is clear from the command.
b) `dependency 's3://dmpetrov' does not exist` - the issue is s3-authorization, not dependency. 
c) Also, do we need to use term `dependency` in this context? Why not just directory?
d) `You could also try downloading it manually, and adding it with 'dvc add'.` why should we suggest this workaround? It basically suggests not using `import-url`.

ADDED:

3. Permission issue

```
$ dvc import-url s3://dmpetrov hello
Importing 's3://dmpetrov' -> 'hello'
ERROR: unexpected error - [Errno 13] Permission denied: '/Users/dmitry/src/tmp/example-get-started/hello/../../../../../get-started'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```
The path does not look correct.

4. Path issue

See above. The path has to be relative. Also, it looks a bit strange.

5. Operation was not reverted

See the command above. The command failed but `hello/` directory stayes. It supposes to be removed.

6. Help message
```
usage: dvc import-url [-h] [-q | -v] [--file <filename>] [--no-exec]
                      [--to-remote] [-r <name>] [-j <number>] [--desc <text>]
                      url [out]
```

Output is mentioned as optional `[out]` while it is not - see (1).

**Comment by dmpetrov** [comment]
What error would I expect:
```
$ aws s3 ls s3://dmpetrov/

An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
```

**Comment by skshetry** [comment]
> `ERROR: unexpected error - [Errno 17] File exists: '.'`

1. Also unexpected error should not be there: https://github.com/iterative/dvc/issues/5387

> 2. Long and not informative error:

2. Related: https://github.com/iterative/dvc/issues/5565

> What error would I expect (for (1)-(3)):
> 
> ```
> $ aws s3 ls s3://dmpetrov/
> 
> An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
> ```

3. Related to: https://github.com/iterative/dvc/issues/6353

> Output is mentioned as optional [out] while it is not - see (1).

The output should be optional, probably the file already exists in your workspace.

**Comment by skshetry** [comment]
Closing as not planned. Some of the issues mentioned above have been fixed already, and some are closed as not planned.
