### ISSUE TITLE
dvc pull -r http_remote: fails with 401 - unauthorized for directory cache files, when basic auth is set properly

### ISSUE THREAD

**Issue by simonlsk** [iterative/dvc#6478]
# Bug Report

## Description
When running dvc pull for an HTTP cache protected with basic auth, directory files read cause:
```
ERROR: unexpected error - 401 Client Error: Unauthorized for url: http://<remote_url>/c2/f5094a84cd17aeeca0524bd422b5ab.dir
```

### Reproduce
* Git clone repository with a DVC HTTP remote protected with basic auth
* Repository should have a directory tracked by DVC.
* Configure basic auth
   ```
    dvc remote add <remote_name> http://<remote_url>
    dvc remote modify origin --local auth basic
    dvc remote modify origin --local user <user>
    dvc remote modify origin --local password <password>
    ```
* Run DVC pull -r <remote_name>

### Expected
Pull all the files from the cache, including the directory and its content.

### Environment information
* MacOS 11.4
* DVC 2.6.4 / 2.6.0
* HTTP remote - Private repository on DAGsHub

**Output of `dvc doctor`:**

```console
DVC version: 2.6.4
---------------------------------
Platform: Python 3.7.7 on Darwin-20.5.0-x86_64-i386-64bit
Supports:
	gdrive (pydrive2 = 1.7.0),
	hdfs (pyarrow = 2.0.0),
	webhdfs (hdfs = 2.5.8),
	http (requests = 2.24.0),
	https (requests = 2.24.0)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: http, http
Workspace directory: apfs on /dev/disk1s2s1
Repo: dvc, git
```

**Additional Information (if any):**
The origin of the issue seems to be in file `dvc/objects/tree.py` in the function `load` in line 106.
This line ultimately leads to an HTTP request to be done without any `auth` specified in the `open` method of the class `BaseFileSystem`, when it calls `open_url`

**Comment by guysmoilov** [comment]
Possibly related?
#5677
