### ISSUE TITLE
Support for external commands?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6489]
It'd be amazing to have a support for external command being able to run `dvc <cmd>` by just having a `dvc-<cmd>` in the user's `PATH`, similar to `git`.

Looking at the argparse, it does not seem to be possible to add support for default subparser or a fallback subparser. So, we may be need to add all the commands from the `PATH` matching `dvc-` prefix during `ArgumentParser` build. Also may need to take into account a few things for windows
(eg: `PATHEXT`, current directory has higher precedence, multiple executable extensions, etc.).

Also see: https://github.com/iterative/cml/issues/699.

**Comment by daavoo** [comment]
What about also allowing users to register custom commands via entry-points:

https://packaging.python.org/guides/creating-and-discovering-plugins/#using-package-metadata

**Comment by skshetry** [comment]
Closing, so far there has not been a usecase. `live` command was deprecated/removed.
