### ISSUE TITLE
dvc push: No module named 'pydrive2.fs' (after upgrade 2.5.4->2.6.4)

### ISSUE THREAD

**Issue by rbracco** [iterative/dvc#6499]
# Bug Report

## Description

I upgraded from 2.5.4 to 2.6.4 and when I pushed with `dvc push` it failed with error message ERROR: unexpected error - No module named 'pydrive2.fs'. I tried `pip install PyDrive2` but still get the error. 

**Edit: I was able to fix it with `pip install PyDrive2 --upgrade`. Going to leave this up in case anyone else gets stuck in a similar position. Thanks.**

**Output of `dvc doctor`:**

```console
DVC version: 2.6.4 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.11.0-27-generic-x86_64-with-glibc2.29
Supports:
        gdrive (pydrive2 = 1.8.3),
        hdfs (pyarrow = 4.0.1),
        http (requests = 2.26.0),
        https (requests = 2.26.0)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: gdrive, gdrive
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by efiop** [comment]
@rbracco Hi! Looks like you've upgraded with `pip install -U dvc` instead of `pip install -U dvc[gdrive]`, which would pull newer pydrive2 along the way.

**Comment by rbracco** [comment]
Awesome thank you I'll keep that in mind for the future.
