### ISSUE TITLE
Expose `params`/ `ParamsDependency` in the Python API.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#6507]
`params` are easy to include in a pipeline via [templating](https://dvc.org/doc/user-guide/project-structure/pipelines-files#templating) but using them inside a python script might not be that trivial and require several changes in the user's code (i.e. when a stage uses several params from different params files).

I think that it would be nice to expose some function in the public API that would take care of loading the `params` associated to a stage and returning them as python objects, directly usable in the python script. 

It could be something like `dvc.api.get_params()` and would take care of loading only the params defined in the `params` section of the stage.

**Comment by daavoo** [comment]
For reference, open source project implementing an API similar to what it's described in the issue https://docs.orchest.io/en/stable/fundamentals/sdk/index.html#api-parameters

**Comment by jorgeorpinel** [comment]
> defined in the params section of the stage

How would DVC know what stage this python file is associated with? Would it only work automatically if the file is in the `cmd` field of dvc.yaml? If you have to specify which stage then it's less "magical".
