### ISSUE TITLE
Paths break with dvc push from Windows to Linux (ssh)

### ISSUE THREAD

**Issue by benjaminalt** [iterative/dvc#6514]
# Bug Report

## Description

When pushing via SSH/SFTP from Windows (MinGW32) to an SSH server running on Linux, there seems to be a problem with forward and backward slashes in paths. The `.dvc/config` on the Windows client contains

```
['remote "storage"']
    url = ssh://user@machine/home/user/dvc_root
```

After pushing, the DVC files don't end up at `/home/user/dvc_root` on the server, however. Instead, the `/home/user` directory contains all of the DVC files directly (note the backslashes):

```
$ ls /home/user | more

\home\user\dvc_root\00
\home\user\dvc_root\00\00dad9454dc25f899090b21b3457d7
\home\user\dvc_root\00\014cf75413925c486fb0d51c4d79c3
\home\user\dvc_root\00\01ad837abddba70b1452864f4bf742
```

What went wrong here? In the above example, I would expect a file `00dad9454dc25f899090b21b3457d7` in `/home/user/dvc_root/00`, not a file `\home\user\dvc_root\00\00dad9454dc25f899090b21b3457d7` in `/home/user`.

### Reproduce

1. Set up a regular ssh server on a Linux machine, no special configuration
2. Configure it as a DVC remote for a repo on a Windows machine
3. Push from the Windows machine to the Linux remote

### Environment information

**Output of `dvc doctor`:**

Linux server:

```console
$ dvc doctor

DVC version: 2.5.1 (pip)
---------------------------------
Platform: Python 3.6.9 on Linux-5.4.0-81-generic-x86_64-with-Ubuntu-18.04-bionic
Supports:
	hdfs (pyarrow = 4.0.1),
	http (requests = 2.25.1),
	https (requests = 2.25.1)
```
 
Windows client:
```console
 $ dvc doctor
DVC version: 2.6.4 (pip)
---------------------------------
Platform: Python 3.7.5 on Windows-10-10.0.19041-SP0
Supports:
        http (requests = 2.26.0),
        https (requests = 2.26.0),
        ssh (sshfs = 2021.7.1)
```

**Comment by efiop** [comment]
CC @isidentical , could it be https://github.com/iterative/dvc/blob/b5fe9b459658bca9e9c5963b468e1d1fe18b7c15/dvc/fs/ssh.py#L41 ?
