### ISSUE TITLE
Add dvclive as a dependency

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6527]
Dvclive was separated from dvc so that it can be a standalone package and more lightweight. However, adding dvclive as a dependency to dvc adds minimal overhead and saves a step for users who want to use the dvclive methods. This makes it easier to introduce concepts in the dvc docs using dvclive calls (like checkpoints). Any opposition to adding it?

**Comment by shcheklein** [comment]
One caveat that comes to my mind here. When DVC is installed as a binary people won't be able to use it - and they will have to install DVC with `pip/conda` second time to have access to the API. (same question applies to the `dvc.api`, btw).

If we think that most people already use (and will use) `pip/conda`, it should not be a big problem then.

**Comment by dberenbaum** [comment]
Good point. I guess it does little harm in that case, but we may still need to document installation steps for dvclive.

**Comment by dberenbaum** [comment]
@mattseddon Please comment if you have thoughts on this one.
