### ISSUE TITLE
clashing requirements with black formatter

### ISSUE THREAD

**Issue by endremborza** [iterative/dvc#6555]
Hello!

dvc currentl has pathspec requirement of >=0.6.0,<0.9.0:
https://github.com/iterative/dvc/blob/1744028e09d754ea1bbea71e1d8a96af84d2209d/setup.py#L67

while black has >=0.9.0, <1
https://github.com/psf/black/blob/41e670064063e3e221b1c3c40db5aaae784b5231/setup.py#L80

I didn't find a reason behind this in other issues, and since black is immensely popular I suppose this should be addressed. Is there a specific reason I missed?

**Comment by endremborza** [comment]
this is the only test that fails with `pathspec==0.9.0`
https://github.com/iterative/dvc/blob/2b63cedfcd89484bf1ec93e86610e3009b4fa6da/tests/unit/test_pathspec_math.py#L71

as a leading `/` is added

**Comment by pared** [comment]
Related #6331

**Comment by efiop** [comment]
@endremborza Do you install dvc from pypi? Do you use our python API? If not, maybe something like pipx or one of our standalone packages like deb/rpm/snap/brew/etc would work for you?

**Comment by endremborza** [comment]
I can use it just fine, since it works with `pathspec 0.9.0` but black does not work at all with `pathspec < 0.9.0`. 

It's not a question of whether it works once you know this, but it might break a few pipelines, as it did break some of mine where black was installed first and dvc later. So it would simply be nice to fix
