### ISSUE TITLE
project: formalize extra dependency types

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#6559]
While working on #6540, I noticed that it would be a bit simpler if we had dependencies organized as sole files instead of the current way (so i can simply strip the version specifiers out on a certain directory to test with the newer versions). A simple way of doing this is just creating a `requirements/` directory and adding entries for each remote we have as a new file. This will also allow dependabot to upgrade our remote dependencies automatically (just like it is doing for the tests).

**Comment by skshetry** [comment]
Using dependabot is going to be a pain for extra dependencies, as it does not support updating dependencies together. 

Pyup.io/Renovate supports batched updates though.

**Comment by isidentical** [comment]
That certainly is a problem for fixed dependencies with fsspec :(
