### ISSUE TITLE
Add 'type' option for output

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#656]
I.e. `--type metric` `--type graph` or something like that for cli.

**Comment by villasv** [comment]
What would be the motivation to do that? Some kind of "always repro" property for metrics?

Currently, my default `Dvcfile` in the root of the project is simply `cat data/report.txt && cat data/metrics.txt`. What would change?

**Comment by efiop** [comment]
@villasv No, we are actually thinking about something like #592 . This flag will allow dvc to understand what files to parse without manually specifying them. So to view metrics you would run: `dvc metrics` or something like that, with an option to show metrics for each branch you have.
