### ISSUE TITLE
cannot conduct dvc pull ERROR: unexpected error - __init__() got an unexpected keyword argument 'cache_regions'

### ISSUE THREAD

**Issue by Hiroshi-Kumanomido** [iterative/dvc#6574]
# Bug Report

Hello, I want help with resolving issues on dvc pull.

I have succeeded in cloning a local repository file on my HDD, but I couldn't conduct dvc pull. 
The error messeage is the following: 

`ERROR: unexpected error - __init__() got an unexpected keyword argument 'cache_regions'`

my version of dvc is 2.7.1 (pip). 
MacOS Big Sur ver.11.5.2

Unfortunately, I do not know what useful information help to resolve this issue as I am a beginner of dvc.

**Comment by Hiroshi-Kumanomido** [comment]
Additional information:

I conducted clone and dvc pull yesterday (they worked at that time!), but some errors appeared and I couldn't succeed in downloading some files with error message ``max retries exceeded'' 

Thus, I quit downloading steps, deleted my cloned local file, and tried to re-clone the files. After then, I have failed to dvc pull with above Error messages.

**Comment by efiop** [comment]
@Hiroshi-Kumanomido Hi :slightly_smiling_face: Please show full output for `dvc doctor`

**Comment by Hiroshi-Kumanomido** [comment]
Thank you for your reply! 

the results of `dvc doctor` is 
******
DVC version: 2.7.1 (pip)
---------------------------------
Platform: Python 3.7.6 on Darwin-20.6.0-x86_64-i386-64bit
Supports:
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        s3 (s3fs = 2021.5.0, boto3 = 1.17.49)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: hfs on /dev/disk2s2
Repo: dvc, git
**********

As you suggested, I tried `pip install -U 'dvc[s3]'` in the terminal window. Then, dvc pull seems to work now! Now, transferring step is going on, although it takes time.

**Comment by efiop** [comment]
@Hiroshi-Kumanomido Great to hear it works :) Looks like it is resolved now? If so, closing.

**Comment by Hiroshi-Kumanomido** [comment]
@efiop 
Sorry for re-opening this issue. I am still in a transferring step, but some files seems to be failed to download with the following error messages.

`failed to transfer xxxxxxxxxxxxxxxxxxxx - Max Retries Exceeded `

And also, dev pull states that I succeeded in download some files, but I cannot find those files in working directory. 
Why do these issues happen? 

Sorry for bothering you.

**Comment by efiop** [comment]
@Hiroshi-Kumanomido Hm, are you using real aws s3 or some s3-compatible storage like minio?

Could you try running `dvc pull` a few more times, please? It will not start downloading all files from scratch, it will only download missing files that it failed to download before.

Regarding the lack of files in the workspace, I assume that it failed to download some files that are part of one dataset, so dvc didn't automatically checkout it, since it didn't have all of the files in cache.

**Comment by Hiroshi-Kumanomido** [comment]
@efiop I was using real aws s3. 

I tried running `dvc pull` three times, but at last, `dvc pull -j 1` helped. All problems were finanly resolved!!

>>>>
Regarding the lack of files in the workspace, you were right! I could confirm all the files are made after completing `dvc pull` successfully.

Thank you very much.

**Comment by efiop** [comment]
@Hiroshi-Kumanomido Hm, looks like maybe 4*NCPU default jobs might have been a little too much for your connection. Are you in the same region as the aws bucket you are accessing? Also, how many cpu cores do you have?
