### ISSUE TITLE
hdfs: migrate to fsspec/pyarrow.fs

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#6582]
To complete the fsspec migration, we need to migrate hdfs to the fsspec.

**Comment by isidentical** [comment]
It seems like `PyArrowHDFS` doesn't support per-file `info()`, neither it does support the `checksum()` logic we have.

**Comment by efiop** [comment]
@isidentical Also it seems that fsspec's is based on CLI hadoop, while we are based on libhdfs. But not 100% sure.

Regarding `checksum`, we definitely could consider dropping it, as it is mostly being misused right now for external outputs scenario. Or could keep it as it is right now - based on raw hadoop CLI for now.

**Comment by isidentical** [comment]
> it seems that fsspec's is based on CLI hadoop, while we are based on libhdfs. But not 100% sure.

I am not sure what is the difference, but from what I can assume they seem to be also using libhdfs:
https://github.com/intake/filesystem_spec/blob/d952ace9db6eea7ccf202e616dc8121a549a4dc9/fsspec/implementations/hdfs.py#L40-L41

**Comment by isidentical** [comment]
prerequisite: https://github.com/intake/filesystem_spec/pull/749

**Comment by isidentical** [comment]
From what I see now is that we can not directly use the one on the fsspec (even with my changed applied) since `pyarrow.hdfs` is deprecated and using `pyarrow.fs.HadoopFileSystem` would require substantial changes on the fsspec side :( There seems to be an open issue about supporting it on the fsspec, and I probably will take it on (there is some starter code over it) https://github.com/iterative/dvc/issues/6582

**Comment by efiop** [comment]
@isidentical Looks like you've posted a link to this same issue in your last comment. You probably meant something else.

**Comment by isidentical** [comment]
With https://github.com/intake/filesystem_spec/pull/754, now it also works on our test suite and can actually support the mocked one.

**Comment by isidentical** [comment]
Both of the PRs are now merged to the upstream fsspec, we only need a release on the fsspec side to merge #6604.
