### ISSUE TITLE
exp push/pull/list: support git credential storage

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6586]
Extracted from https://github.com/iterative/dvc/pull/6493.

`dvc exp push/pull/list` do not work today if credentials are required to be provided, such as `dvc exp push` to a public Github HTTP URL or `dvc exp push/pull/list` for a private Github HTTP URL.

Also, even if using git credential stores, in which case users don't need to manually enter credentials when performing git operations, DVC doesn't currently read these credentials and still complains that the URL is unauthenticated. Note that dulwich seems to have support for this: https://github.com/dulwich/dulwich/blob/cdc93e058fb28e4884f8d6a23b4d79b14d2a8098/dulwich/client.py#L2222.

As discussed in the linked PR, it would be helpful to read from the credential store and ask for the username and password if the `HTTPClientUnauthorized` exception is thrown. It would also be helpful to memoize to avoid having to repeatedly ask for credentials in the case of auto-pushing checkpoints. This might be generally useful because obtaining a new git client for each checkpoint seems wasteful regardless.

**Comment by pmrowla** [comment]
related:
https://github.com/iterative/dvc/issues/6586
https://github.com/iterative/dvc/pull/7674

**Comment by pmrowla** [comment]
Adding this to the backlog as follow-up to the workaround in #7674

from https://github.com/iterative/dvc/pull/7674#issuecomment-1115844175:

> Ideally we would implement support for credential helpers in either dulwich (https://github.com/jelmer/dulwich/issues/873) or libgit2/pygit (https://github.com/libgit2/libgit2/issues/4873)

Adding support for this requires implementing the [git credentials storage](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) protocol in dulwich and/or libgit. On the dulwich side, essentially this just means:

- reading the name/path of an executable from the git config
- run the executable in subprocess with the appropriate action args (`get`/`store`/`erase`)
- read/write the key=value protocol values to/from the process as described in the git docs

We also probably only need read-only support for now (i.e. likely only need to implement the `get` action)

**Comment by dtrifiro** [comment]
Released with [`2.25.0`](https://github.com/iterative/dvc/releases/tag/2.25.0)
