### ISSUE TITLE
exp push/pull: don't include baseline commit

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6592]
`dvc exp push/pull` transfer all cached outputs for all experiment commits up to and including the baseline commit on which the experiment is based. The baseline commit is a regular Git commit, so it might be unexpected that it's data is pushed/pulled by `exp push/pull`, and if no `dvc.lock` exists in the baseline commit, this will generate a warning that could be confusing.

@iesahin @pmrowla @daavoo

**Comment by pmrowla** [comment]
This should be simple to fix, we just need to remove
https://github.com/iterative/dvc/blob/049a856cd93c14e6a2efdbf6f5e02b028885a544/dvc/repo/experiments/utils.py#L90-L91
