### ISSUE TITLE
diff: use object diff

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#6594]
Currently `dvc/repo/diff.py` is quite a bit outdated, we didn't touch it since before introducing objects, so it is still based on hash_info, which makes it suboptimal and very confusing. What we should do instead is introduce `dvc/objects/diff.py` and implement generic diffing logic for `Tree` objects, that could then be used in `dvc diff`. Also it is important to remember that even though right now we don't provide one `Tree` for the whole repo (kinda like git commits do), we will do that soon, which will again simplify `dvc diff` logic, that will then use `objects.diff` even more directly.

Btw, we are already doing basic object diff when merging trees in our git merge-driver (see `merge` in `dvc/objects/tree.py`).

**Comment by efiop** [comment]
We also clearly need this for checkout.

**Comment by dberenbaum** [comment]
@efiop Is this still p1?

**Comment by skshetry** [comment]
`diff` uses `index.diff` now. Closing. 

- https://github.com/iterative/dvc/pull/8930
