### ISSUE TITLE
pull -r remote: Fails with 'No file hash info found' 

### ISSUE THREAD

**Issue by simonlsk** [iterative/dvc#6598]
# Bug Report

## Description
`dvc pull -r <remote>` fails with `WARNING: No file hash info found for 'dir'. It won't be created.` for dvc tracked directory. 
* Happens when no default remote is set
* Happens with HTTP remote
* This doesn't happen with earlier versions (tested with `2.3.0` and works fine)

### Reproduce
1. Clone a repo with a dvc tracked directory and no default remote set. (Example repo: `https://dagshub.com/Simon/baby-yoda-segmentation-dataset.git` in branch `nodefault`)
2. Run `dvc pull -r <remote>` 

### Expected
Successful pulling of files

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.7.2 (pip)
---------------------------------
Platform: Python 3.7.6 on Darwin-20.6.0-x86_64-i386-64bit
Supports:
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s2s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s2s1
Repo: dvc, git
```

**Comment by efiop** [comment]
@simonlsk Could you please provide full verbose log? That warning is just a small part of the log, I'm worried that we are not seeing full picture.

**Comment by simonlsk** [comment]
```
WARNING: No file hash info found for 'preview'. It won't be created.
WARNING: No file hash info found for 'annotations'. It won't be created.
WARNING: No file hash info found for 'images'. It won't be created.
3 files failed
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
preview
annotations
images
Is your cache up to date?
```

**Comment by simonlsk** [comment]
```
2021-09-13 13:48:10,376 DEBUG: failed to pull cache for 'preview'
2021-09-13 13:48:10,376 DEBUG: failed to pull cache for 'annotations'
2021-09-13 13:48:10,377 DEBUG: failed to pull cache for 'images'
2021-09-13 13:48:10,381 WARNING: No file hash info found for 'images'. It won't be created.
2021-09-13 13:48:10,383 WARNING: No file hash info found for 'preview'. It won't be created.
2021-09-13 13:48:10,385 WARNING: No file hash info found for 'annotations'. It won't be created.
3 files failed
2021-09-13 13:48:10,387 ERROR: failed to pull data from the cloud - Checkout failed for following targets:
images
preview
annotations
Is your cache up to date?
<https://error.dvc.org/missing-files>
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/dvc/command/data_sync.py", line 41, in run
    glob=self.args.glob,
  File "/opt/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/dvc/repo/pull.py", line 44, in pull
    recursive=recursive,
  File "/opt/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/dvc/repo/checkout.py", line 110, in checkout
    raise CheckoutError(stats["failed"], stats)
dvc.exceptions.CheckoutError: Checkout failed for following targets:
images
preview
annotations
Is your cache up to date?
<https://error.dvc.org/missing-files>
------------------------------------------------------------
2021-09-13 13:48:10,389 DEBUG: Analytics is enabled.
2021-09-13 13:48:10,437 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/2h/94x3nhzs11791ps96dkjm6k80000gn/T/tmporoazv9o']'
2021-09-13 13:48:10,439 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/2h/94x3nhzs11791ps96dkjm6k80000gn/T/tmporoazv9o']'
```

**Comment by simonlsk** [comment]
Seems like #6600 solves this issue

**Comment by kongkip** [comment]
This issue was closed but I think it was no resolved, issue [#6600 ](https://github.com/iterative/dvc/pull/6600) doesn't resolve it either

This is the error am getting from my end 

```
WARNING: No file hash info found for 'D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\data\prepared'. It won't be created.
WARNING: No file hash info found for 'D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\data\fetal-head-data'. It won't be created.
WARNING: No file hash info found for 'D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\saved_models\keras'. It won't be created.
WARNING: No file hash info found for 'D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\saved_models\tflite'. It won't be created.
WARNING: No file hash info found for 'D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\runs\linknet'. It won't be created.
WARNING: No file hash info found for 'D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\runs\old'. It won't be created.
WARNING: No file hash info found for 'D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\runs\unet'. It won't be created.
WARNING: No file hash info found for 'D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\checkpoint\linknet'. It won't be created.
8 files failed
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\data\prepared
D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\data\fetal-head-data
D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\saved_models\keras
D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\saved_models\tflite
D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\runs\linknet
D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\runs\old
D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\runs\unet
D:\Work\Tambua\SoftwareDevelopment\ml-hc-auto-measure\checkpoint\linknet
Is your cache up to date?
<https://error.dvc.org/missing-files>

```

**Comment by kevashcraft** [comment]
For me, this was a simple user error. I was running `dvc pull` instead of `dvc pull -r origin`. It only took an hour of tutorials to figure it out :D

**Comment by Ankita2019DA** [comment]
I am facing the same issue. 
I notice that the error is in checkout step: 
`  File "/Users/ankitabhatia/.pyenv/versions/3.10.4/envs/rstudio/lib/python3.10/site-packages/dvc/repo/checkout.py", line 113, in checkout
    raise CheckoutError(stats["failed"], stats)
dvc.exceptions.CheckoutError: Checkout failed for following targets:`

In dvc I have versioned a file `data/intermediate/ABC.parquet` but when I see the error I see it with the full path like 
dvc.exceptions.CheckoutError: Checkout failed for following targets:
`/Users/xyz/projectname/rsubproject/data/intermediate/ABC.parquet`. 

dvc doctor output looks like this:
DVC version: 2.33.2 (pip)
---------------------------------
Platform: Python 3.10.4 on macOS-13.1-arm64-arm-64bit
Subprojects:
	dvc_data = 0.25.2
	dvc_objects = 0.12.2
	dvc_render = 0.0.12
	dvc_task = 0.1.4
	dvclive = 2.0.2
	scmrepo = 0.1.3
Supports:
	http (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
	s3 (s3fs = 2022.10.0, boto3 = 1.24.59)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git

Can someone please help resolve this?

**Comment by efiop** [comment]
@Ankita2019DA Please share full verbose log. My guess is that you didn't push your files to that remote.

**Comment by phcerdan** [comment]
The error message could be improved. I was facing this error when pulling from an AWS remote. The problem was solved providing correct credentials to AWS.

**Comment by billtubbs** [comment]
I agree.  This error message does not make me think "Oh I haven't authenticated AWS access".
