### ISSUE TITLE
http: gzip encoding makes pull freeze

### ISSUE THREAD

**Issue by simonlsk** [iterative/dvc#6599]
# Bug Report

## Description
Running `dvc pull` on any DagsHub HTTP remotes hangs forever. This is affecting many of our users, who end up downgrading to the last known version that works (`2.3.0`). 

### Reproduce
1. `git clone` a repository that uses DagsHub storage (http remote) (example `https://dagshub.com/Simon/baby-yoda-segmentation-dataset.git`)
2. Run `dvc pull`

### Expected
Pull all the files from the remote.

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.7.2 (pip)
---------------------------------
Platform: Python 3.7.6 on Darwin-20.6.0-x86_64-i386-64bit
Supports:
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s2s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s2s1
Repo: dvc, git
```

**Additional Information (if any):**
The issue is caused internally by the third-party library `fsspec` when getting files from DagsHub. The files are transferred with `'content-encoding': 'gzip'`, therefore without the `content-length` header. This causes `fsspec` to hang.

**Comment by efiop** [comment]
> The issue is caused internally by the third-party library fsspec when getting files from DagsHub. The files are transferred with 'content-encoding': 'gzip', therefore without the content-length header. This causes fsspec to hang.

Looks like you've figured it out already. Mind creating an issue in fsspec and, maybe, sending a fix for them?

**Comment by simonlsk** [comment]
I tend to disagree with the labeling and the edited title though. This is a regression from previous versions that work fine. A simple `curl` command or python request to the URL returns the content of the file just fine, where `dvc pull` just hangs. The behaviour is that pulling the files doesn't work as expected, and not that gzip is stated as not supported. It turns out that the underlying origin of the bug is `fsspec` failing to finish requests that do not return the `content-size` header, which is standard for requests with `"content-encoding":"gzip"`. That's just a technical detail I discovered, and it's not even sure I am right about it. It might also be related thread safety in `fsspec`.

**Comment by efiop** [comment]
@simonlsk Touche. Adjusted the title. Thanks 🙏

**Comment by efiop** [comment]
For the record:

```
  File "/Users/efiop/git/dvc/dvc/objects/transfer.py", line 105, in _do_transfer
    is_dir_failed = sum(processor([dir_obj.hash_info]))
  File "/Users/efiop/git/dvc/dvc/objects/transfer.py", line 159, in func
    return dest.add(
  File "/Users/efiop/git/dvc/dvc/objects/db/base.py", line 114, in add
    self._add_file(fs, path_info, cache_info, hash_info, move=move)
  File "/Users/efiop/git/dvc/dvc/objects/db/base.py", line 89, in _add_file
    return fs.utils.transfer(
  File "/Users/efiop/git/dvc/dvc/fs/utils.py", line 33, in transfer
    return from_fs.download_file(from_info, to_info)
  File "/Users/efiop/git/dvc/dvc/fs/base.py", line 292, in download
    return self._download_file(from_info, to_info, name, no_progress_bar)
  File "/Users/efiop/git/dvc/dvc/fs/base.py", line 346, in _download_file
    self._download(  # noqa, pylint: disable=no-member
  File "/Users/efiop/git/dvc/dvc/fs/fsspec_wrapper.py", line 293, in _download
    self.fs.get_file(
  File "/Users/efiop/.pyenv/versions/3.9.7/envs/dvc-py3.9.7/lib/python3.9/site-packages/fsspec/asyn.py", 
line 88, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/efiop/.pyenv/versions/3.9.7/envs/dvc-py3.9.7/lib/python3.9/site-packages/fsspec/asyn.py", 
line 59, in sync
    if event.wait(1):
  File "/Users/efiop/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/efiop/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

```

**Comment by efiop** [comment]
Ok, looks like removing this

https://github.com/iterative/dvc/blob/eb6562207b0ee9bd7fd2067103f3ff3b6c6cd18b/dvc/progress.py#L182

fixes it. looking at that block, seems a bit odd that callback calls fs.info, trying to remember if this was a temporary workaround or something, @isidentical maybe you remember details about it?

**Comment by isidentical** [comment]
Ah, I think I know why this is troubling (you can not call sync fsspec methods from when executing an async fsspec function), so you can not make an `info()` call in `get_file` but we indirectly make it when there is no `content-length`. 

> @isidentical maybe you remember details about it?

No, it is not temporary. Not all filesystems support `set_size()` all the time (for example http, the `content-length` might not be present) so what we do in that case is that, we call the `info()` on the host filesystem to retrieve the size with an extra API call to show the full progress bar. But in this case, it gets stuck because there is another level of indirection in the async `get_file` function where it calls this sync `info()` method of the same filesystem.

**Comment by simonlsk** [comment]
> @simonlsk Touche. Adjusted the title. Thanks 🙏

@efiop Thank you I really appreciate it 🙏  !
This seems to be above my original understanding of the issue, but please let me know if there's anything I can do to help.

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/6612

@simonlsk Thanks again for reporting this bug 🙏
