### ISSUE TITLE
exp show: Shows wrong "State" for experiments in the queue that have already been run

### ISSUE THREAD

**Issue by lassepe** [iterative/dvc#6614]
# Bug Report

## Description

When scheduling a sequence of experiments with `dvc exp run --queue` and running the queue with `dvc exp run --run-all`, the output of `dvc exp show` seems to show an incorrect "State" for experiments that have already been completed. Fore example, in the screenshot below, the experiment `higher_weight_regularization` has already been completed but is assigned the state "Queued".

![image](https://user-images.githubusercontent.com/10076790/133264381-c5b3ac69-7f77-4887-a91d-50a467a60162.png)

### Reproduce

1. Schedule at least two experiments with `dvc exp run --queued`
2. Submit the queue with `dvc exp run --run-all`
3. Run `dvc exp show` while the second experiment in the queue is running and observe the value of the `State` column.

### Expected

I would expect the value of completed experiments in the output of `exp show` to be "Completed" or similar.

### Environment information

**Output of `dvc doctor`:**

```console
Platform: Python 3.7.10 on Linux-5.14.2-arch1-2-x86_64-with-arch
Supports:
	gdrive (pydrive2 = 1.9.3),
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
```

**Comment by behrica** [comment]
Just to add to this.
I would expect as well that the "completed" jobs show the metrics, which they don't currently

**Comment by karajan1001** [comment]
In the current version, it will show `-` as the status for the completed exp result.

**Comment by pmrowla** [comment]
Yes, this issue should be resolved after the queue changes are merged
