### ISSUE TITLE
support for spark and HDFS

### ISSUE THREAD

**Issue by chanansh** [iterative/dvc#663]
does the project supports big data which is hard to audit like parquet files in HDFS?
does the project supports running code on remote machines e.g. spark cluster?

**Comment by dmpetrov** [comment]
Currently, DVC supports only local disk environment. HDFS can be handled through custom wrappers.
DVC tracks parquet files in a local disk as a directory `dvc run -d input.pq/ -o output.tsv python myscript.py`.

Could you please give us more details about your scenario? Do you run all your steps on a Spark cluster? Or data processing on a cluster and ML modeling \ analytics on a local machine (using Python\R)?

**Comment by chanansh** [comment]
Spark end to end.

**Comment by dmpetrov** [comment]
Thank you @chanansh !
Can I ask a few more question to clarify?
1. Do you use pipelines?
2. How are the steps of the pipelines are connected? By input\ouput files (parquet)?
3. How do you kick off each step of pipeline now? `spark-submit` for each step or you have some spark code to execute the steps and run a single `spark-submit`?
4. Is it okay to keep all the cache file versions in HDFS?

**Comment by chanansh** [comment]
I have a main which call all steps one after the other and pass data frames
between them without explicitly writing to disk. Modeling is final step
which in some cases happen in the driver node and sometimes distributed.

**Comment by chanansh** [comment]
Does dvc pipeline supports hdfs?

**Comment by dmpetrov** [comment]
We are working on the HDFS support. I just want to make sure that our implementation will cover your needs.

We have some assumptions and would like to be sure the assumptions work for you:
1. your pipeline is separated into steps
2. you define the pipeline by submitting steps through `dvc run ... spark-submit ...` with inputs and outputs in HDFS
3. DVC creates cache directory with all the data file versions in HDFS
4. you work on a local machine by all the pipeline steps run on a cluster.
5. DVC does not sync data files to your local machine.
6. all meta information stay in a Git repository on your local machine: pipeline definition, data file checksums, and timestamps.
7. Yarn manage resources. DVC just submits jobs in a right order.
8. you have enough space in HDFS to store all copy of your experiment. `dvc gc` can clean old ones.
9. you can work together on the same pipeline using the same Git\DVC repo.

Please let me know which of the assumptions are not true with your workflow.

**Comment by chanansh** [comment]
4. Sometimes I work directly on the driver node remotely 
7. Sometimes I use "local" spark standalone mode on a strong server with 50 cores
8.

**Comment by dmpetrov** [comment]
@chanansh thank you!

The HDFS support is coming. Change #740 is a step for the external HDFS caches support. Actual HDFS will be implemented soon.

Btw... The 5th scenario with a standalone spark on a single strong server works right now. Just use `dvc run -d input.tsv -o ouput.pq/ spark-submit --jar my.jar param1 param2`

**Comment by efiop** [comment]
HDFS deps/outs/cache support is merged and will be released in 0.9.8. Closing.
