### ISSUE TITLE
exp show: --show-md for experiment tables

### ISSUE THREAD

**Issue by mattlbeck** [iterative/dvc#6632]
We want to be able to display tables of our experiments in markdown documents similar to how we can do it with dvc params and metrics.

Our use case is that we are conducting hyperparameter tuning jobs in CML, and would like to easily format a table of the results in PR comments.

I appreciate that just doing a `dvc exp show --show-md` could by default be an overwhelming table but the conversion would be extremely handy along with the filtering flags to get a summary that is much more manageable.

**Comment by dberenbaum** [comment]
Good idea, @mattlbeck!

I'm curious if you see benefits beyond ease of use for doing this over inserting the output directly as a code block like:

````
echo '```' >> report.md
dvc exp show >> report.md
echo '```' >> report.md
````

**Comment by mattlbeck** [comment]
@dberenbaum Honestly hadn't thought of placing inside of a code block. Presumably this only works with `--no-pager`?

Without having properly tested this, the only additional benefit of a `--show-md` I can think of is that it would look a bit nicer.

**Comment by dberenbaum** [comment]
Good to know. Would you be interested in either trying that workaround and letting us know how it works, or else contributing the `--show-md` option?

**Comment by mattlbeck** [comment]
No problem, I will either submit a PR or close this ticket depending on the outcome.

**Comment by dberenbaum** [comment]
Thank you! One more thought: the leftmost column condenses multiple items of info (compare to the csv output) that might be hard to show in the same way in markdown.

**Comment by dberenbaum** [comment]
Also, no need to close the ticket. This is at least a pattern we should explicitly support for cml and other ci needs.
