### ISSUE TITLE
dvc exp rename: a command line tool to rename existing experiments

### ISSUE THREAD

**Issue by macio232** [iterative/dvc#6667]
Hi, here is my use case: I often run multiple experiments with generic names and afterwards I want to rename some of them into something informative. My solution, for now, is to apply experiment, `dvc exp run --name` with the new name and finally remove the old one. It would be nice to have a dedicated command for this.

Thx :)

**Comment by dberenbaum** [comment]
See https://discord.com/channels/485586884165107732/485596304961962003/1033843165670674523

**Comment by BradyJ27** [comment]
Created a PR #9812 for this.
