### ISSUE TITLE
ssh: switch to a docker-based alternative from mock-ssh server

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#6673]
It appears to be that we are in an impasse caused by the oddities of asyncssh + mock-ssh-server. There were already some bugs (e.g decoding commands) that made us patch the actual mock-ssh-server to function, but while researching #6514 I noticed that it  works very weirdly due to a couple issues I was able to observe (path separator conflict, trying to `mkdir()` root of the filesystem and getting permission error etc.). Due to these and making this more maintainable and similiar to it's real environment, we should switch to a docker-based solution

**Comment by efiop** [comment]
CC @pmrowla , I remember you were also having some problems with mockssh.

**Comment by pmrowla** [comment]
Yeah, there are problems with mock-ssh-server not handling scenarios where you have a server-side app that streams data back and forth with a client (like git over SSH). I was able to work around it by adding an explicit handler subclass for the git SSH protocol in #6589

https://github.com/iterative/dvc/blob/00550a79aad679403290be1bfb86d58407f97e63/tests/remotes/git_server.py#L16

But if we are going to switch to using docker in for SSH general, it would also let us test against an actual git/ssh server configuration
