### ISSUE TITLE
exp show: save filters

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6708]
Extracted from https://github.com/iterative/dvc.org/pull/2759#discussion_r718159857:

> we should create a way to save table filters and sorting I think in DVC, wdyt @dberenbaum ?

I'm putting this as p3 until we decide which `exp show` improvements we want to pursue, which should be not only decided but implemented by the end of this year.

**Comment by daavoo** [comment]
I would expand the scope to pretty much any option passed to `exp show`

**Comment by dberenbaum** [comment]
Is it basically a repo-specific alias?

**Comment by daavoo** [comment]
> Is it basically a repo-specific alias?

Pretty much, but with the extra feature of being able to override some options on each call

**Comment by dberenbaum** [comment]
I think this is better left to VS Code for now. Closing.
