### ISSUE TITLE
dvc should output prettify json in tty while having --show-json

### ISSUE THREAD

**Issue by eggqq007** [iterative/dvc#6712]
Pre-issue: https://github.com/iterative/dvc/issues/6646

**Comment by pmrowla** [comment]
@eggqq007 are you planning on taking this issue yourself (to use the updated `write_json` in other commands besides list)?

**Comment by eggqq007** [comment]
Yes, I will send the patch out later. :)

> @eggqq007 are you planning on taking this issue yourself (to use the updated `write_json` in other commands besides list)?

**Comment by eggqq007** [comment]
write_json function consumes function from_data in rich. But I found it doesn't accept 'default' which just like default in json.dumps. It means it may hit issue while converting class into json. 

So I'm considering whether to continue to use from_data to print prettify json.

**Comment by skshetry** [comment]
@eggqq007, maybe we can propose this on `rich`? Also, for the time being, we could override `from_data` to support `default`, see this piece of code: https://github.com/willmcgugan/rich/blob/473eac577f42a243404c3e01ba13ba73c7aaaadd/rich/json.py#L36-L40

**Comment by eggqq007** [comment]
> @eggqq007, maybe we can propose this on `rich`? Also, for the time being, we could override `from_data` to support `default`, see this piece of code: https://github.com/willmcgugan/rich/blob/473eac577f42a243404c3e01ba13ba73c7aaaadd/rich/json.py#L36-L40

Thanks for your suggestions. I had created a new discussion at https://github.com/willmcgugan/rich/discussions/1534  last week but get no response.  
Yes, re-implement from_data in dvc is a way.
