### ISSUE TITLE
dvc repro gives inconsistent outputs if wdir is outside of dvc repo

### ISSUE THREAD

**Issue by rgrenholm** [iterative/dvc#6715]
# Bug Report
## Description

I have a monorepo with the following directory structure:

```.           # git init
├── .git
├── project-A
│   ├── .dvc    # dvc init --subdir
│   ├── dvc.yaml
│   ...
├── project-B
│   ├── .dvc    # dvc init --subdir
│   ├── write_from.txt
│   ...
```

where dvc is initialized in A and B's project directory with the command `dvc init --subdir`. In this example, project A's dvc pipeline has a stage where it reads a text file from project B's directory and saves it to project A's directory. When I run project A's dvc pipeline by `dvc repro` I get what I think are inconsistent outputs depending on the value of `wdir` and whether I use `outs` or not. Consider the following two cases:

**Case 1: wdir parent directory with outs**
```stages:

  write_from_project_b_to_a:
    cmd: cat project-B/write_from.txt > project-A/write_to.txt
    wdir: ".."
    deps:
      - project-B/write_from.txt
    outs:
      - project-A/write_to.txt
```
```console
$ dvc repro
Running stage 'write_from_project_b_to_a':                            
> cat project-B/write_from.txt > project-A/write_to.txt
ERROR: failed to reproduce 'dvc.yaml': stage working dir '/Users/robingrenholm/Documents/monorepo-test' is outside of DVC repo
```

**Case 2: wdir parent directory without outs**
```stages:

  write_from_project_b_to_a:
    cmd: cat project-B/write_from.txt > project-A/write_to.txt
    wdir: ".."
    deps:
      - project-B/write_from.txt
```
```console
$ dvc repro
Running stage 'write_from_project_b_to_a':                            
> cat project-B/write_from.txt > project-A/write_to.txt
Generating lock file 'dvc.lock'                                       
Updating lock file 'dvc.lock'

To track the changes with git, run:

	git add dvc.lock
Use `dvc push` to send your updates to remote storage.
```
In case 1 where `write_to.txt` was tracked (defined as an out), `dvc repro` threw an error because `wdir` was outside the dvc repo. This error did not appear in case 2 when I did not track `write_to.txt`.
### Expected

I expected `wdir` to be able to be outside the dvc repo with or without `outs`. I do not see the reason why one would want to limit `wdir` when `deps` and `outs` can be outside dvc repositories:

**Case 3: wdir current directory with deps and outs outside project A's dvc repo**
```stages:

  write_from_project_b_to_b:
    cmd: cat ../project-B/write_from.txt > ../project-B/write_to.txt
    wdir: "."
    deps:
      - ../project-B/write_from.txt
    outs:
      - ../project-B/write_to.txt
```
```console
$ dvc repro
Running stage 'write_from_project_b_to_b':                            
> cat ../project-B/write_from.txt > ../project-B/write_to.txt
Generating lock file 'dvc.lock'                                                 
Updating lock file 'dvc.lock'

To track the changes with git, run:

	git add dvc.lock
Use `dvc push` to send your updates to remote storage.
```
### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.7.4 (pip)
---------------------------------
Platform: Python 3.8.11 on macOS-10.14.6-x86_64-i386-64bit
Supports:
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	s3 (s3fs = 2021.8.1, boto3 = 1.17.106)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1
Repo: dvc (subdir), git
```

**Comment by pmrowla** [comment]
> ### Expected
> I expected wdir to be able to be outside the dvc repo with or without outs. I do not see the reason why one would want to limit wdir when deps and outs can be outside dvc repositories:

I think the issue in all of these cases is that outputs outside the repository are not actually allowed (unless you are explicitly using `--external` outputs - which is generally not a recommended use case: https://dvc.org/doc/user-guide/managing-external-data#how-external-outputs-work).

DVC should be detecting and failing when you try to define an output outside of the repo, in this case we may have a bug somewhere that does not catch the bad output paths because of how your monorepo is structured (where project A thinks that paths in project B are still valid).

**Comment by pmrowla** [comment]
I should also note that external dependencies (outside of the project) are allowed in DVC. So the correct way to setup your pipelines would be:

- Project A stages must have `wdir` and `outs` paths contained within `project-A/...`.
- Project A stage `deps` paths can be external (i.e. `../project-B/...`)

(and vice-versa for project B stages)

**Comment by rgrenholm** [comment]
> > ### Expected
> > I expected wdir to be able to be outside the dvc repo with or without outs. I do not see the reason why one would want to limit wdir when deps and outs can be outside dvc repositories:
> 
> I think the issue in all of these cases is that outputs outside the repository are not actually allowed (unless you are explicitly using `--external` outputs - which is generally not a recommended use case: https://dvc.org/doc/user-guide/managing-external-data#how-external-outputs-work).
> 
> DVC should always be detecting and failing when you try to define an output outside of the repo (or when `wdir` is outside of the repo).
> 
> It looks like we may have a bug somewhere that does not catch the bad output/wdir paths in certain situations because of how your monorepo is structured (where project A thinks that paths in project B are still valid due to the existence of project B's `.dvc` directory).

**Comment by rgrenholm** [comment]
It is the same outcome even if you do not initialize dvc for project B

**Comment by rgrenholm** [comment]
Why have a requirement that wdir must be inside dvc repo? I want to use git repo root as working directory for all projects in the monorepo

**Comment by pmrowla** [comment]
DVC is not supposed to be aware of anything happening outside of the repo root (containing `.dvc/`), meaning that pipeline execution is also supposed to happen inside of the repo.

Can you elaborate on your use case? If you are using a shared working directory at the git root level, do you need separate DVC subrepos at all?

**Comment by pmrowla** [comment]
Also, for reference on each example case:

- Case 1: wdir parent directory with outs
    - Failure here is expected, since `wdir` is outside of project A (`../`)
- Case 2: wdir parent directory without outs
    - Success here is unexpected since `wdir` is outside of project A.
    - This case should fail with the same error as case 1. The bug here is likely that `wdir` validity isn't being checked when there are no `outs` for a stage.
- Case 3: wdir current directory with deps and outs outside project A's dvc repo
    - Success here is unexpected since output `../project-B/write_to.txt` is outside of project A.
    - In this case, `wdir` is inside of project A, so the bug here appears to be that the output path is not being checked properly
