### ISSUE TITLE
Provides Unsubscribe Option From Mailing List

### ISSUE THREAD

**Issue by apdullahyayik** [iterative/dvc#6725]
# Bug Report

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by efiop** [comment]
Hi @apdullahyayik!

There is a button in the footer to unsubscribe. Or could you elaborate which mailing list you are talking about?

**Comment by apdullahyayik** [comment]
![364EEE26-9720-42B3-905B-63D35E254A80](https://user-images.githubusercontent.com/5982905/135740295-8ddb62d4-f088-4b44-a83f-107808457adb.jpeg)

I am talking about “mailing list”. I could not find a way to unsubscribe, my e-mail is as follows: “apdullahyayik@gmail.com”. If you can help me,I will be appreciated, Thanks.

**Comment by skshetry** [comment]
@apdullahyayik, there should be something like following at the bottom of the email:
```
Unsubscribe from this list: https://dvc.us10.list-manage.com/unsubscribe?u=XXX
```

Is it not there? 

Anyway, I'll try providing your email internally to unsubscribe.
