### ISSUE TITLE
exp save: save workspace state to an experiment ref

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6746]
`dvc exp commit` would create an experiment from the current state of the workspace.

Use cases for this command include:
* Not using DVC pipelines but still want to track experiments in a lightweight way. For example, by just having params in `params.yaml` and metrics in `metrics.json` (see #6168), DVC can track and compare experiments.
* Code has already been run. The user might have already run code and wants to record it without committing it to their working branch.
* Want to examine the results before deciding whether to save it as an experiment. Users can do `dvc repro` and do `dvc exp commit` whenever they want to track the experiment results.
* Enables users to use `dvc repro` and still use experiments. Some users may prefer this because they are already used to `dvc repro`, and in other cases `dvc exp run` might not work quite the same way. This eases the need to have `dvc repro` and `dvc exp run` behave exactly the same (see https://github.com/iterative/dvc.org/issues/2861).

**Comment by dberenbaum** [comment]
Each checkpoint is basically doing the same as `dvc exp commit` would do, right? I'm not sure what the behavior would be at each checkpoint in `dvc repro`.

**Comment by shcheklein** [comment]
One minor thought on this. When I initially read about this I thought about `dvc commit` + `git commit` semantics.  While this is more like `dvc exp stash`? or `dvc exp save`, right? I guess, my concern is that `commit` is so overloaded that might confuse people.

**Comment by dberenbaum** [comment]
@daavoo Let's assume for now at least that this workflow does not support checkpoints. However, I do think it should be possible to create a checkpoint within any workflow, including without using pipelines at all. Related: https://github.com/iterative/dvc/issues/7381.

**Comment by dberenbaum** [comment]
> * Not using DVC pipelines but still want to track experiments in a lightweight way.

Need to prioritize this feature request to support this workflow as a lightweight way to get started with experiments.
