### ISSUE TITLE
dvc gc not removing unused folders

### ISSUE THREAD

**Issue by aveek-brahmachari** [iterative/dvc#6747]
dvc gc is removing the cache data but not the folder containing the cache data
if folder e0 contains say a file 6e6b2410e54fe5244a89430fddebc1, it removes 6e6b2410e54fe5244a89430fddebc1 but does not remove the empty folder e0

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/3375

Btw, @aveek-brahmachari does it cause any problems for your usage scenarios? If so, could you elaborate how, please?

**Comment by aveek-brahmachari** [comment]
> Closing in favor of #3375
> 
> Btw, @aveek-brahmachari does it cause any problems for your usage scenarios? If so, could you elaborate how, please?

You may want to count the folders to find out how much data is there. Request you to upgrade the priority of this issue #3375.
