### ISSUE TITLE
dvc import-url: .dvcignore is not considered.

### ISSUE THREAD

**Issue by JunseongAHN** [iterative/dvc#6754]
# Bug Report (Maybe an expected behavior...)

## Issue name
dvc import-url: .dvcignore is not considered. dvc create hash files for all files in the given data directory

## Description
.dvcignore is not considered when using `dvc import-url`. I don't know if it is an expected behavior or not.
if it is expected, is there anyway not to track files filtered with .dvcignore when I add a remote storage such as NAS, S3?

### Reproduce

1. `dvc init
2. `adjust .dvcignore
3. `dvc remote add myremote YOUR_REMOTE_STORAGE
4. `dvc import-url YOUR_DATA_DIR --to-remote -r myremote 

### Expected

Don't create a hash files regarding files filted by .dvcignore in my YOUR_REMOTE_STORAGE

### Environment information

Ubuntu 20.04

**Additional Information (if any):**

If you need any more information to reproduce this issue, please let me know. Thank you!

**Comment by pmrowla** [comment]
I think this is currently expected behavior, dvcignore filtering is only done on paths that already exist locally (and is not used for import-url at all).

We could potentially consider filtering out files which would end up being ignored after the import as a feature request.
