### ISSUE TITLE
fs: migrate away from PathInfo

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#6774]
We are using and constructing `PathInfo` objects nearly everywhere in the DVC to both wrap and manipulate paths easily. The cost for them becomes noticeable when we create hundreds/thousands of them (which is a common scenerio, depending on the size of your remote). For optimizing away, and simplifying the overall interaction between the filesystem layer and the rest of the codebase we'll gradually migrate away from PathInfos to strings.

Pre-requisites:
- [x] Add type hints to the fs-layer. This should help greatly to track down type mismatches and places where we pass PathInfo objects after the migration.

**Comment by efiop** [comment]
Found initial mention for that https://github.com/iterative/dvc/issues/5162#issuecomment-775771333 😄

**Comment by isidentical** [comment]
It is a pickle that we now have to URLs (e.g an SSH URL of `ssh://a@b:3432:/x/y/z`) to `/x/y/z` before passing them into filesystems since otherwise the fsspec can't handle them. It seems like we only need them at the initial fs-construction time, so might able to normalize it in the `get_cloud_fs` but that would mean I might have to cancel my bottom-up approach (slowly migrating before changing `get_cloud_fs` to return strings instead of path infos) :(
