### ISSUE TITLE
`dvc gc --time <datetime>`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#678]
#669 

@dmpetrov : 

> the data time could be used for the garbage collector - very natural way to reduce size. dvc gc --time month - clean everything not from the current branch and older than a month.

**Comment by efiop** [comment]
Not sure about this, as not mtime on data files nor mtime on cache files is really indicative of the usage or lack of it. Plus, I don't see a good way that we will not break a particular pipeline with older files. Need to reconsider it later. Moving to 0.9.8 milestone.

**Comment by efiop** [comment]
More organic way would be to use git commits as a limiter. I.e. gc --time month will save data for all pipelines up to a week.

**Comment by efiop** [comment]
Moved to 0.11.0.

**Comment by jorgeorpinel** [comment]
A user mentioned this idea on Discord today.

**Comment by jorgeorpinel** [comment]
BTW, another "natural way to reduce size" could be **by size** e.g. `dvc gc --size-over 1G` - removes all cached files larger than a GB.

**Comment by jorgeorpinel** [comment]
BTW, this (`--time` feature) can be done currently via Git. It may be a little complicated e.g. requiring rewriting the repo history but we could write a guide or how-to about it instead of implementing the feature. If so we could move this issue over to dvc.org.

And the `--size` feature is doable via regular GNU tools like `du ... | xargs rm ...` etc. which we could also document.

**Comment by jorgeorpinel** [comment]
We had another user request this feature today, in the context of shared caches ([link](https://discord.com/channels/485586884165107732/563406153334128681/861989689891880971)).

**Comment by lassepe** [comment]
@jorgeorpinel I would also be interested in this feature. Could you elaborate on how the `--time` feature could be achieved with git?

**Comment by jorgeorpinel** [comment]
@lassepe sure, by deleting all the commits before that date (see [this Q](https://stackoverflow.com/questions/29042783)) and then using `dvc gc -A`.

**Comment by jorgeorpinel** [comment]
p.s. you could do it in a repo copy and then discard it if you didn't actually mean to discard all your Git history.

**Comment by lassepe** [comment]
Ah okay, this seems like a bit too aggressive then because I still need to keep the code history. I'll wait for the actual feature then.

**Comment by jorgeorpinel** [comment]
You could do it in a temporary repo clone and then discard it (don't rewrite the upstream or your main working repo).

**Comment by rafaelsdellama** [comment]
Any updates? this feature would be very important to me.. I currently have some models that are retrained weekly, and I was using dvc to version the models and datasets, but the bucket size was getting too big and I don't need the old models (I need keep only the last 3 or 4 models in case rollback is needed).
as currently this feature is not available it is an impediment for me to use dvc.

**Comment by daavoo** [comment]
> Any updates? this feature would be very important to me.. I currently have some models that are retrained weekly, and I was using dvc to version the models and datasets, but the bucket size was getting too big and I don't need the old models (I need keep only the last 3 or 4 models in case rollback is needed).
as currently this feature is not available it is an impediment for me to use dvc.

@rafaelsdellama Do you need the `datetime` feature specifically or would some alternative approach like `gc -n <N_COMMITS>` (https://github.com/iterative/dvc/issues/7695) work for your use case?

**Comment by rafaelsdellama** [comment]
@daavoo this alternative approach would solve in my case :smile:
