### ISSUE TITLE
`exp show`: Highlight changes in metrics and params

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#6783]
Regardless of how you are implementing it, highlighting changes in metrics and params is a nice idea for `exp show` and a good potential alternative to #5966. @daavoo What do you think about this as a table improvement?

_Originally posted by @dberenbaum in https://github.com/iterative/dvc/issues/6778#issuecomment-940225551_

**Comment by dberenbaum** [comment]
I think it's better left to more visual tools like VS Code or Studio. Closing.
