### ISSUE TITLE
exp run: Remove unsupported `dvc repro` options from the help text

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc#6791]
# Bug Report

UPDATE: Jump to https://github.com/iterative/dvc/issues/6791#issuecomment-1043363367

## Description

`dvc exp run --help` lists the following options:

```
  -s, --single-item     Reproduce only single data item without recursive dependencies check.
  -m, --metrics         Show metrics after reproduction.
  --dry                 Only print the commands that would be executed without actually executing.
  -i, --interactive     Ask for confirmation before reproducing each stage.
  -p, --pipeline        Reproduce the whole pipeline that the specified targets belong to.
  -P, --all-pipelines   Reproduce all pipelines in the repo.
  -R, --recursive       Reproduce all stages in the specified directory.
  --no-run-cache        Execute stage commands even if they have already been run with the same command/dependencies/outputs/etc
                        before.
  --force-downstream    Reproduce all descendants of a changed stage even if their direct dependencies didn't change.
  --no-commit           Don't put files/directories into cache.
  --downstream          Start from the specified stages when reproducing pipelines.
  --pull                Try automatically pulling missing cache for outputs restored from the run-cache.
  --glob                Allows targets containing shell-style wildcards.
```

Some of them are not supported. I tested a few of them and testing the rest. Could you remove those from the help text? We're going to update the command reference according to this. 

- [x] `--force`: Seems to run
- [x] `--single-item`: I didn't get what does this do in `dvc exp run` context
- [x] `--metrics` : ✅
- [x] `--interactive`: ✅
- [x] `--pipeline`: ✅
- [x] `--all-pipelines`: seems to run ✅
- [x] `--recursive`: ✅
- [x] `--no-run-cache`: seems to have no effect ❌
- [x] `--force-downstream`: 
- [x] `--no-commit`: seems to have no effect ❌
- [x] `--downstream`:
- [x] `--pull`:
- [x] `--glob`: ❌

**Comment by dberenbaum** [comment]
Thank you @iesahin, this is great!

>     * [x]  `--no-run-cache`: seems to have no effect ❌

>     * [x]  `--no-commit`: seems to have no effect ❌

It makes sense to me that these wouldn't work since experiments need to be able to cache data to retrieve it. I'm fine with removing these unless anyone else objects.


>  `--glob`: ❌

This probably still needs to be fixed in #6457. We may need to bump the priority up unless anyone has a reason not to, in which case we should remove the option for now.

>     * [x]  `--interactive`: ✅

Hm, does this make sense for experiments? How does it work with checkpoints or experiments outside of the working directory?

**Comment by iesahin** [comment]
> It makes sense to me that these wouldn't work since experiments need to be able to cache data to retrieve it. I'm fine with removing these unless anyone else objects.

I think we should remove these even if someone objects. 😄 We can ask for PRs from them. 



> Hm, does this make sense for experiments? How does it work with checkpoints or experiments outside of the working directory?

Interactive reproduction may lead to some unforeseen results about the experiments and checkpoints. It's identical with the basic `dvc exp run` if you say `y` to all stages, but what happens if you skip some of these stages, I don't know. (e.g., do we generate `exp-id` from the whole pipeline or only the stages that run?)

I believe, in general, experiments should not be granularized by stages, we already have checkpoints for this. Interaction between these two features may lead to some inconsistent behavior.

**Comment by iesahin** [comment]
I believe if some option from `dvc repro` seems not relevant clearly, we can better drop it from `dvc exp run`. If we decide on a clear behavior later, we can revive them. :)

If _stage selection_ is not particularly clear, we can drop `--glob` as well. It's about stage selection.

**Comment by iesahin** [comment]
I think, for the time being, it's better to remove these options from the help text and the documentation. If we get some feedback about the lack of these, we can create new tickets and move forward.

**Comment by dberenbaum** [comment]
@erovira `dvc repro --glob` works as expected for me. Could you open a separate issue if you are seeing an issue with it?

**Comment by jorgeorpinel** [comment]
>  --no-commit: seems to have no effect ❌

I unchecked this since the option is still shown and accepted (2.8.1).

Didn't double check any other ones.

**Comment by iesahin** [comment]
Those checkmarks show that I've checked them by running the command. :) @jorgeorpinel

**Comment by jorgeorpinel** [comment]
OK. A bit confused by the check on one side and the x on the other.

![image](https://user-images.githubusercontent.com/1477535/146501297-2e9c89c1-fa03-4cc6-bb9d-eab46d3eabee.png)

**Comment by dberenbaum** [comment]
All of these commands have been tested here or in https://github.com/iterative/dvc.org/issues/2861. We need to remove `--no-run-cache`, `--no-commit`, and `--glob` (unless someone prefers to address #6457).

cc @pmrowla @karajan1001
