### ISSUE TITLE
exp show: does not display root values

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6859]
```bash
echo "3" > metrics.yaml
tee dvc.yaml << EOF
stages:
  stage1:
    cmd: echo hello world
    metrics:
    - metrics.yaml
EOF
dvc exp show
```

`dvc metrics show` can show the root values, and since the `dvc exp show` uses the `metrics show` data, it should support that behaviour. Though I don't think this is an important feature/bug that needs to be prioritized.

**Comment by dberenbaum** [comment]
@skshetry is technically correct, and it's good to have this issue as a record, but I doubt we will prioritize it. Closing.
