### ISSUE TITLE
exp init: when to fail for non-existent params

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6865]
From https://github.com/iterative/dvc/pull/6750#issuecomment-937219108:

> Can we validate that dependencies exist at the time of entry during interactive mode? It would save a lot of trouble with having to redo the whole stage after it fails at the end.

`exp init` fails if `params.yaml` does not exist since the params are parsed to generate the stage. Related: #6605.

In interactive mode, it would be nice to fail as soon as possible (right after path to params is provided).

For other dependencies, I wonder if `dvc exp init` should also validate that the paths exist. This could help guide users. It could be annoying if users want to do `dvc exp init` before creating projects files, but this seems unlikely to me outside of toy scenarios.

**Comment by skshetry** [comment]
It makes sense to fail right away for the params as we need them to exist for us to create a stage. I am not so sure about other dependencies, we tried to decouple the runtime behaviour with the metadata tracking behaviour on `stage add`.
