### ISSUE TITLE
`exp show --json`: Interaction with other flags

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#6874]
Currently, the `--show-json`/`--json` option would return the "raw" results of the internal `repo.experiments.show`. 

Any other flags that modify the content of the table don't have any effect on the generated JSON. However, other kinds of outputs (i.e. `--show-csv`/`--csv`) are actually affected.

The docs/help only say that: "prints the command's output in easily parsable JSON format, instead of a human-readable table." but nothing about not being affected by other flags. 

Apart from updating the docs for the current behavior what I would like to discuss is: Should we consider changing `--show-json` to be actually affected by the other flags?

**Comment by dberenbaum** [comment]
I doubt we are going to prioritize this one. Closing.
