### ISSUE TITLE
DVC does not tell me if a dvc push is yet to be done

### ISSUE THREAD

**Issue by aveek-brahmachari** [iterative/dvc#6875]
Suppose *.dvc is committed in git and dvc push was not done and later we dont remember which file was not pushed, I dont see a simple method of knowing this.

I can clear cache and dvc pull again to find which md5 is missing both locally and remotely, but thats exactly what dvc status needs to do. clearing cache and pulling again is time consuming.

**Comment by aveek-brahmachari** [comment]
$ dvc doctor
DVC version: 2.7.4+0eda4b
---------------------------------
Platform: Python 3.9.7 on Windows-10-10.0.19042-SP0
Supports:
        gdrive (pydrive2 = 1.10.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        ssh (sshfs = 2021.9.0)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: ssh
Workspace directory: NTFS on C:\
Repo: dvc (subdir), git

**Comment by efiop** [comment]
@aveek-brahmachari Could you show an example of the output that you get?
