### ISSUE TITLE
Descriptions for datasets

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#688]
Define description:
```
$ dvc add -d "2018-05-02. Update and clean double-clicks" data/source.zip
```

Show description:
```
$ dvc dataset data/source.zip
2018-05-02. Update and clean double-clicks
```

```
$ dvc dataset --history data/source.zip
88c338e    2018-05-02. Update and clean double-clicks.
be762e9     2018-04-20. No annotation signals.
d638f4c     Web Logs from 2018-02-14.
```

I'm not sure about the 2nd and 3rd command syntax. Should we extract all of these together with `dvc add` under `dvc dataset` umbrella?

**Comment by denmoroz** [comment]
I think it would be nice to:
1) Add name or some additional info (source, authors, date?) at initial "dvc add" command.
2) Have "dvc list" command to show what datasets are involved in the project and their meta-info (see 1.).

**Comment by villasv** [comment]
Hmm. I'm ambivalent about bringing too much documentation to DVC. I think that's the point of versioning DVC files in git too, so you can leverage the existing VCS.

I think that anything that is immediately obvious from a `git blame` on the DVC file (such as date or description) could stay on git. Giving people many options of documentation will lead to conflicting patterns of documentation.

**Comment by dmpetrov** [comment]
@villasv is right. We should not overwhelm the DVC command set and reuse Git info as much as we can.

If we decide to add `dvc dataset` command then it can show the data sources list by default (instead of separate`dvc list`). @denmoroz how do you think?

`Author` and `date` - are git-commit author and git-commit date enough? Could you please give an example when it might be not enough?

`source` - it is an interesting idea... we can think about custom tags like: `db`, `prod-db`, `hdfs`, `tmp-ranking-hdfs`. Something like `dvc add -d "2018-05-02. Update and clean double-clicks" --source-tag prod-db data/source.zip` Will this cover your scenario @denmoroz?

**Comment by efiop** [comment]
I agree with @villasv . There is no reason to try to duplicate what git already does.

> The only issue - we do not force to make a commit right after dvc add. So, it might be a discrepancy.

But this is a part of etiquette of working with git. Make change -> commit change with an appropriate commit msg. Plus, people can always put data.dsc or something like that to keep all the notes they want. People can also put their data sources somewhere separately if they want to keep track of them. I.e. Patrick Ball in his talk explains exactly that https://www.youtube.com/watch?v=ZSunU9GQdcI . Thus I currently don't see a good reason to get into it with a core dvc. Closing.
