### ISSUE TITLE
Thread join() timed out in cmd.handle_process_output(). Timeout=10.0 seconds

### ISSUE THREAD

**Issue by inn-home** [iterative/dvc#6884]
dev get timed out.

Example: dvc get --rev (git resource)

Description:
I encountered an error about timeout in the pull model,The command is:
`dvc get --rev (commit ID) git@resource the model path`
The error:
`unexpected error - Thread join() timed out in cmd.handle_process_output(). Timeout=10.0 seconds`

I have tried other models in the same project and there is no problem, but this one cannot be downloaded, my other colleagues can.

**Comment by efiop** [comment]
closing as stale
