### ISSUE TITLE
Machine: use table for machine list and status outputs

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#6892]
Current, machine list output follows the `dvc config -l`. Which is not suitable in showing multiple machines. Considering use table to replace it.
```
$ dvc machine list
new.cloud=aws
myaws.cloud=aws
myaws.spot_price=100.00000
myaws.instance_hdd_size=10
myaws.instance_type=l
myaws.instance_gpu=k80
```

**Comment by dberenbaum** [comment]
Take a look at `dvc remote list`. It seems like `dvc machine list` should be similar.

**Comment by karajan1001** [comment]
> Take a look at `dvc remote list`. It seems like `dvc machine list` should be similar.
It only shows name and address in `dvc remote list`, while `machine list` show several fields.
Much less readable for users to align each line.
```
$ dvc remote list
ossremote	oss://dvc-temp/oss
storage	https://remote.dvc.org/example-dvc-experiments
```
