### ISSUE TITLE
prioritising zsh sub-subcommand completion

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#6904]
How many users are affected by https://github.com/iterative/shtab/issues/33? Some metrics would be nice in order to ascertain whether it's worth spending some time to implement.

```sh
(zsh)% dvc plots <TAB>       # works
(zsh)% dvc plots show <TAB>  # only completes `dvc` options
```

**Comment by casperdcl** [comment]
btw feel free to remove unneeded labels :)

**Comment by efiop** [comment]
Can't find any particular tickets and don't remember anyone complaining in quite awhile. Maybe someone will respond now, but so far looks like this is not high priority.

**Comment by rememberedbound** [comment]
It's very recently become an issue to me if that helps.

**Comment by skshetry** [comment]
This is definitely a `p1` for us, as DVC is adding more subcommands like `exp`, `machine`, etc.

I don't think we need to track this here.

**Comment by skshetry** [comment]
Closed by https://github.com/iterative/shtab/issues/33.
