### ISSUE TITLE
remote: test

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6927]
Question from DVCLearn:

Is it possible to have a dvc remote test to check if your credentials are correct before you proceed?

**Comment by dacbd** [comment]
example being:
`dvc remote <name> test`  exit code 1 or 0

**Comment by dacbd** [comment]
useful to check that permissions are correct to use the dvc remote
or 
to verify remotes are reachable by a CI or other system

**Comment by karajan1001** [comment]
I usually use

**Comment by dacbd** [comment]
> I usually use `status -c` for this.

@karajan1001 that seems to function close to what I'm looking for.

One test exited with `255` maybe it reflected the HTTP status code to the exit code? 
Also, it looks to have only reached out to the default remote?

> note I haven't used a whole lot of the dvc tool so I'm not super familiar with it yet...

**Comment by daavoo** [comment]
> Also, it looks to have only reached out to the default remote?

You can pass a specific remote name `dvc status -r {REMOTE_NAME}` . See https://dvc.org/doc/command-reference/status#options

> One test exited with 255 maybe it reflected the HTTP status code to the exit code?

I was about to also suggest `dvc status -c` as an alternative but also found some strange return codes.

**Comment by dacbd** [comment]
would it be very feasible to support pipes? like `dvc remote list | dvc status -r`
or
machine-friendly output for something like `dvc status -r $(dvc remote list -l)`  with `-l` dropping the like of s3 uri, functionally `dvc remote list | awk '{print $1}' | tr -t '\n' ' '`

**Comment by dacbd** [comment]
@mattseddon can you provide clarity, I still think this or the issue @dberenbaum linked (#8235) should be implemented.

**Comment by mattseddon** [comment]
@dacbd what would you like me to clarify?

**Comment by dacbd** [comment]
@mattseddon why is it now not planned? Going with #8235 instead?
