### ISSUE TITLE
config --local: disable/remove help text for irrelevant commands

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6940]
Extracted from https://github.com/iterative/dvc/pull/6855#issuecomment-962764180:

> `machine status` shows the machine running status which is decoupled with the original machine config. So no `--global/system/project/local` for it. But for now, it shows is in the help UI, we need to remove them. Btw, this UI issue also exists in some other machine commands, `create`, `ssh` etc. We can create an issue for it.

**Comment by karajan1001** [comment]
In #6440

Only `add`, `remove`, `list`, and `modify` needs `--local/project/system/global` flag.

Remove them in `create`, `destroy`, `rename`, `status`, `ssh`.
