### ISSUE TITLE
Possible Issue with Python 3.9.8

### ISSUE THREAD

**Issue by PythonFZ** [iterative/dvc#6956]
# Bug Report
I am sorry in advance for this incomplete Bug Report.

I am writing a package that depends on / is built for DVC.
In our CI testing we encountered an Issue with the new Python 3.9.8 release which was not present in 3.9.7.
Running the same CI with with Python 3.9.7 did not fail.

Typically I would assume that this is an issue with our software, but it occurs in a subprocess call which I think comes from DVC, because the command `Running stage <stage name>` is run by DVC.

Here is part of the log:

```
Running stage 'BasicTest':
> r u n
---------------------------- Captured stderr setup -----------------------------
/bin/sh: 1: r: not found
ERROR: failed to reproduce 'dvc.yaml': failed to run: r u n, exited with 127
```

I tried to reproduce the issue locally but with conda I am currently unable to install the Python 3.9.8 but only 3.9.7.
I wanted to let you know in advance about this and maybe it is already know.
It does not happen in 3.7, 3.8, 3.10

Here is a Link to the failing CI test https://github.com/zincware/ZnTrack/runs/4168272021?check_suite_focus=true
Here is the same CI but restricted to 3.9.7 https://github.com/zincware/ZnTrack/runs/4168558848?check_suite_focus=true

**Comment by efiop** [comment]
@PythonFZ Thanks for reporting this issue! 🙏 We are already working on it.

**Comment by pared** [comment]
Not sure if its related but `--quiet` stopped working too... Invesitgating...

**Comment by pared** [comment]
@PythonFZ thanks for the heads up! Looking at how the [issue develops](https://bugs.python.org/issue45235) it seems that this particular fix will be [scrapped](https://bugs.python.org/msg406123). The workaround, for now, will be to downgrade the CI python version to `3.9.7` and wait for the release after revert.

**Comment by efiop** [comment]
Keeping open until we decide on https://github.com/iterative/dvc/pull/6958#issuecomment-965834949

**Comment by efiop** [comment]
Looks like it is stale now. Closing
