### ISSUE TITLE
Faster S3 push by listing objects

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#696]
When the number of files in DVC cache is large, the `dvc push` command takes a long time even when only a few files need to be pushed.

This could be solved by listing the whole cache folder using [list_objects_v2](http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.list_objects_v2) and checking all the file sizes at once. The list is limited to 1000 files so if it gets truncated, we could list each prefix of the md5 hash - two characters, three characters, etc.

**Comment by efiop** [comment]
Fixed by #834 . This is going to be released in 0.10.0 next week. Thank you!
