### ISSUE TITLE
[HELP] Error when installing dvc, in Gdrive from Colab

### ISSUE THREAD

**Issue by octagomez** [iterative/dvc#6962]
# Bug Report

## Description
Hi everyone!
I am a student and I am starting in the field of data science, I hope you can help me, since I can not start the work environment.

Describe the current behavior:
I am installing dvc in the project that is hosted on drive and executed from colab.
When executing the line of code
'! dvc run -n prepare \
          -p prepare.seed, prepare.split \
          -d src / prepare.py -d data / data.xml \
          -o data / prepared \
          python src / prepare.py data / data.xml '
Extracted from the site:
https://dvc.org/doc/user-guide/setup-google-drive-remote

When running the tebngo command as a result

ERROR: Could not transfer 'md5: 6f597d341ceb7d8fbbe88859a892ef81' - [Errno 38] Function not implemented: '/ content / drive / My Drive / test_dvc_01 / data / ready / test.tsv' -> '/ content / drive / My Drive / test_dvc_01 /.dvc/cache/6f/597d341ceb7d8fbbe88859a892ef81 '
ERROR: Could not transfer 'md5: 32b715ef0d71ff4c9e61f55b09c15e75' - [Errno 38] Function not implemented: '/ content / drive / My Drive / test_dvc_01 / data / ready / train.tsv' -> '/ content / drive / My Drive / test_dvc_01 /.dvc/cache/32/b715ef0d71ff4c9e61f55b09c15e75 '
ERROR: could not load 'memory: //dvc-staging/bafae8ce6c348783d151e57a746d04ed8538943da267b8be4dcd571daa531b74/20/b786b6e6f80e2b3fcf17827ad18597.dir content' avc / drive / drive content /.
ERROR: 3 files could not be transferred

That from the analyzed it may be the space in the MyDrive folder, could you help me, I am a DC & IA student and I cannot start the project.
Thank you.
Octavio

### Reproduce

1 - from google.colab import drive
drive.mount('/content/drive')
2 - %cd /content/drive/MyDrive
3 - !git init
4 -
! git config --global user.email "xxxxx.cba@gmail.com" #MAIL DE LOGIN
! git config --global user.name "xxxxxx" #NOMBRE EL PERFIL NO ES TAN RELEVANTE
!git clone https://github.com/xxxxxx/test_dvc_01.git

5 -  %cd test_dvc_01/ 
6 - !pip install dvc
7 -  !dvc init -f
8 - !dvc get https://github.com/iterative/dataset-registry \
          get-started/data.xml -o data/data.xml
9 - !dvc remote add -f proyecto01 gdrive://TOKEN
10 - !dvc push 
11 - !wget https://code.dvc.org/get-started/code.zip
!unzip code.zip
!rm -f code.zip
!tree 
12 - !pip install -r src/requirements.txt
13 - 
!dvc run -n prepare \
          -p prepare.seed,prepare.split \
          -d src/prepare.py -d data/data.xml \
          -o data/prepared \
          python src/prepare.py data/data.xml 

point 13 gives an error

Error:```

Running stage 'prepare':
> python src/prepare.py data/data.xml
Computing file/dir hashes (only done once)          |0.00 [00:00,      ?md5/s]
!
  0%|          |                                   0.00/? [00:00<?,        ?B/s]
                                                                                
!
  0%|          |                                   0.00/? [00:00<?,        ?B/s]
ERROR: failed to transfer 'md5: 6f597d341ceb7d8fbbe88859a892ef81' - [Errno 38] Function not implemented: '/content/drive/My Drive/test_dvc_01/data/prepared/test.tsv' -> '/content/drive/My Drive/test_dvc_01/.dvc/cache/6f/597d341ceb7d8fbbe88859a892ef81'
ERROR: failed to transfer 'md5: 32b715ef0d71ff4c9e61f55b09c15e75' - [Errno 38] Function not implemented: '/content/drive/My Drive/test_dvc_01/data/prepared/train.tsv' -> '/content/drive/My Drive/test_dvc_01/.dvc/cache/32/b715ef0d71ff4c9e61f55b09c15e75'
ERROR: failed to upload 'memory://dvc-staging/bafae8ce6c348783d151e57a746d04ed8538943da267b8be4dcd571daa531b74/20/b786b6e6f80e2b3fcf17827ad18597.dir' to '/content/drive/My Drive/test_dvc_01/.dvc/cache/20/b786b6e6f80e2b3fcf17827ad18597.dir'
ERROR: 3 files failed to transfer
```

<!--
Example:

1. dvc init
2. Copy dataset.zip to the directory
3. dvc add dataset.zip
4. dvc run -d dataset.zip -o model ./train.sh
5. modify dataset.zip
6. dvc repro
-->

### Expected

I hope I can finish executing the sentences to start working.

**Comment by skshetry** [comment]
This is failing when dvc tries to hardlink. 
```
!echo foo > "foo"
!dvc run -vv -n copy -d foo -o bar "cat foo foo > bar"
```

<details>
<summary>Error log</summary>



</details>

**Comment by skshetry** [comment]
@octagomez, could you please try installing DVC using following command and see if that fixes for you? I'll make a PR shortly.

```console
!pip install git+https://github.com/skshetry/dvc.git@fix-6962#egg=dvc[dev]
```

**Comment by efiop** [comment]
For the record: a workaround is to rollback to 2.8.2 or earlier.

**Comment by octagomez** [comment]
> @octagomez , ¿podría intentar instalar DVC usando el siguiente comando y ver si se soluciona? Haré un PR en breve.
> 
> ```
> pip install git + https: //github.com/skshetry/dvc.git@fix-6962#egg=dvc [dev]
> ```

Hi @skshetry  and @skshetry 
I can run the link and the problem is solved.
Do you want me to attach the log?

Thank you.
I am very grateful
