### ISSUE TITLE
Why data is not in readable format when we push data to s3

### ISSUE THREAD

**Issue by maheshreddy-agi** [iterative/dvc#6964]
# Bug Report

    Why data is not in readable format when we push data to s3

## Description
     
      When I'm pushing data to S3 using DVC, there in S3 data is not readable format. 
      What to do, if I want the data should be in readable format in S3 when push data using DVC
 

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by skshetry** [comment]
Hi, @maheshreddy-agi, DVC stores data in a content-addressable format and handles de-duplication of files, but the content of the file is still readable and is not mangled. However, the name of the file is not preserved and the file name is the cache of the file itself. You can use [`dvc.api.open`](https://dvc.org/doc/api-reference/open) to read files using the path of your file.

If you face any issues, we are available in discord for quick chat, here's the invite: https://dvc.org/chat. Thanks. 🙂
