### ISSUE TITLE
add: hardlink limit stops execution with many identical files

### ISSUE THREAD

**Issue by manuelbastuck** [iterative/dvc#6965]
# Bug Report

## Description
When `add`ing many (on NTFS: >1024) identical files (i.e. files with the same hash), the process stops at some file (not always the same) with the message:
```
2021-11-11 09:34:51,561 DEBUG: Cache type 'hardlink' is not supported: failed to link
2021-11-11 09:34:51,563 DEBUG: Cache type 'symlink' is not supported: failed to symlink
...
Some targets could not be linked from cache to workspace.
See <https://dvc.org/doc/user-guide/troubleshooting#cache-types> for more information.
To re-link these targets, reconfigure cache types and then run:

        dvc checkout data.dvc
```
This only happens when "copy" is explicitly excluded as a link type, otherwise, it will fall back to "copy". The reason seems to be that the number of possible hardlinks to one file is limited to 1024 on NTFS (and 65000 on EXT4, according to [Wikipedia]( https://en.wikipedia.org/wiki/Hard_link#Limitations_of_hard_links)).

### Reproduce
1. dvc init (on NTFS)
2. Create 1023 files with identical content in folder `data`
3. dvc add data (works)
4. Add two more identical files in the folder `data`
5. dvc add data (fails)

Comment: I am not sure if the limit here is 1023 or 1024 because the file in the cache could already be counted as one link - but 1023 works, 1025 does not.

### Expected
Ideally, it should just work. At least, I would like a warning with an explanation what happened and why. The offending file is currently removed, but not copied back or linked, so it seems to be gone. It would be nice to move the original back if the linking fails.

### Environment information
**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.8.2 (exe)
---------------------------------
Platform: Python 3.8.10 on Windows-10-10.0.19041-SP0
Supports:
        azure (adlfs = 2021.7.1, knack = 0.8.2, azure-identity = 1.6.1),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2021.10.1),
        hdfs (fsspec = 2021.10.1, pyarrow = 5.0.0),
        webhdfs (fsspec = 2021.10.1),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.10.1, boto3 = 1.17.106),
        ssh (sshfs = 2021.11.0),
        oss (ossfs = 2021.7.5),
        webdav (webdav4 = 0.9.0),
        webdavs (webdav4 = 0.9.0)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Additional Information (if any):**
A very similar (if not the same issue) and possible workarounds/solutions is already discussed here: https://github.com/jbruchon/jdupes/issues/9

**Comment by efiop** [comment]
@manuelbastuck are symlinks enabled on your system? If they are not, would it be possible to turn them on?

Regarding the problem itself, a semi-efficient way might be to group duplicate links by 1023, so there is at least some deduplication, but that will be tricky and might be too fragile. I suppose files in question are pretty small, right? We have some optimization that just creates empty files if we are trying to create hardlinks to an empty file. If symlinks are an option I would probably try to use them instead.

> It would be nice to move the original back if the linking fails.

The data is still complete and you have `data.dvc` to `dvc checkout` it back to restore it, but indeed, we will introduce a rollback mechanism in the future https://github.com/iterative/dvc/issues/6387

**Comment by manuelbastuck** [comment]
> The data is still complete and you have data.dvc to dvc checkout it back to restore it

Yes, it's still complete, but I will have to know to allow "copy" as cache type before doing a new checkout. Granted, the error message literally says `To re-link these targets, reconfigure cache types`, but if a new user (like me) just wants to get back to the original state, and `dvc checkout` keeps failing, the assumption could be that `dvc destroy` will reset the initial state of the working copy. However, this will actually delete the file for good, right? So, a rollback mechanism will be highly appreciated :-).

I think a remark on the [page discussing pros and cons of cache types](https://dvc.org/doc/user-guide/large-dataset-optimization) with regard to NTFS and the hardlink limit could prevent some confusion here. Even better, if there is a way to figure out at runtime that the hardlinking was not permitted due to too many existing links, indicating that when the command fails would be a good guide on what to do next (e.g., try to use symlinks or copy).

> are symlinks enabled on your system? If they are not, would it be possible to turn them on?

Unfortunately, the [Microsoft docs on activating symlink creation rights](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links) explicitly states that this right should not be given to standard users to prevent vulnerabilities. So it will be hard to convince the IT department to do so anyways. Even if they did for now, they might revert that at some poiint and I will be left with weird behavior once again. Running the process as admin each time is quite tedious, so for now I'd rather adapt my project structure to have fewer identical files.

> I suppose files in question are pretty small, right?

Yes, they are JSONs containing a few lines of metadata for each associated binary file with the same file name.

**Comment by efiop** [comment]
> I think a remark on the page discussing pros and cons of cache types with regard to NTFS and the hardlink limit could prevent some confusion here. 

Would you be so kind to send a PR for docs, please?

**Comment by efiop** [comment]
Closing as stale.
