### ISSUE TITLE
Using DVC with Windows Sourcetree / GCS

### ISSUE THREAD

**Issue by meystingray** [iterative/dvc#6978]
Series of errors here that results in the the model not getting pushed to Google Cloud Storage.

This is from Sourcetree's MINGW64 git interface:

`dvc init`
ERROR: failed to initiate DVC - G:\My Drive\Location\.dvc is ignored by your SCM tool.
- Add '!.dvc' to .gitignore in root directory, `dvc init` now works.

` git commit -m 'Initialize DVC'`
- Runs Ok

`dvc add "models\MyModelFolder\MyModel.bst"`
ERROR: bad DVC file name 'models\MyModelFolder\MyModel.bst.dvc' is git-ignored.
- Add '!models/MyModel/*.dvc.  Add now works.

`git add 'models\MyModelFolder\MyModel.bst.dvc'`
ERROR: The following paths are ignored by one of your .gitignore files:
models/MyModelFolder/MyModel.bst.dvc
Use -f if you really want to add them.

However, at this point, I've realized there should be a .gitignore file in the MyModelFolder folder, and there's not.
And so on...eventually I can configure GCS and manually commit everything, but it seems wonky, and when I run `dvc push`, I get the message that 'everything is up to date', but nothing is actually pushed.  Have you guys tested in a Windows env with Sourcetree?

**Comment by skshetry** [comment]
To properly gitignore `.dvc` files, you'd need to add following to the `.gitignore` file:
```
models/**
!models/MyModelFolder/**/
!models/MyModelFolder/*.dvc
```

Please see https://github.com/iterative/dvc/issues/6256#issuecomment-874826060 and https://github.com/iterative/dvc/issues/6256#issuecomment-875170297 for more information.

Note that this issue is not related to dvc, sourcetree or gcs.
