### ISSUE TITLE
`exp show`:  Add option to filter out checkpoints

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#6988]
If multiple experiments with checkpoints are run, the table can get quickly populated with too many rows.

It would be nice to have an option to filter out intermediate checkpoints, leaving only a single row per experiment. 

For example from:

| Experiment              | Created      | step   | loss    | accuracy   |
|-------------------------|--------------|--------|---------|------------|
| workspace               | -            | 9      | 0.13434 | 0.94875    |
| main                    | Sep 14, 2021 | -      | -       | -          |
| │ ╓ 54bdc11 [exp-76ba1] | 06:16 PM     | 9      | 0.13434 | 0.94875    |
| │ ╟ 0d15982             | 06:16 PM     | 9      | 0.13434 | 0.94875    |
| │ ╟ 0221f75             | 06:16 PM     | 8      | 0.14528 | 0.94422    |
| │ ╟ 3c919ce             | 06:16 PM     | 7      | 0.16    | 0.93915    |
| │ ╟ f8614f3             | 06:15 PM     | 6      | 0.16907 | 0.93625    |
| │ ╟ 145cf38             | 06:15 PM     | 5      | 0.18693 | 0.93032    |
| │ ╟ 1380f6b             | 06:15 PM     | 4      | 0.20545 | 0.92323    |
| │ ╟ 2c261e6             | 06:15 PM     | 3      | 0.22706 | 0.9165     |
| │ ╟ 474aab2             | 06:15 PM     | 2      | 0.25087 | 0.90902    |
| │ ╟ 8574046             | 06:15 PM     | 1      | 0.29243 | 0.89367    |
| ├─╨ 89c129f             | 06:14 PM     | 0      | 0.43671 | 0.8438     |
| │ ╓ 2e3c654 [exp-12afc] | 06:14 PM     | 9      | 0.18331 | 0.92932    |
| │ ╟ ceee9e6             | 06:13 PM     | 9      | 0.18331 | 0.92932    |
| │ ╟ 92fa0de             | 06:13 PM     | 8      | 0.19382 | 0.92642    |
| │ ╟ 20d54e5             | 06:13 PM     | 7      | 0.20558 | 0.92147    |
| │ ╟ 1a98b62             | 06:13 PM     | 6      | 0.21462 | 0.91743    |
| │ ╟ e3f5963             | 06:13 PM     | 5      | 0.23029 | 0.9131     |
| │ ╟ 4ddaa64             | 06:13 PM     | 4      | 0.24762 | 0.90817    |
| │ ╟ 6f2cbd7             | 06:12 PM     | 3      | 0.26551 | 0.90218    |
| │ ╟ 0f3f2bd             | 06:12 PM     | 2      | 0.29    | 0.89392    |
| │ ╟ a769a16             | 06:12 PM     | 1      | 0.33083 | 0.8808     |
| ├─╨ ee36d3a             | 06:12 PM     | 0      | 0.48448 | 0.82805    |

To:

| Experiment              | Created      | step   | loss    | accuracy   |
|-------------------------|--------------|--------|---------|------------|
| workspace               | -            | 9      | 0.13434 | 0.94875    |
| main                    | Sep 14, 2021 | -      | -       | -          |
| 54bdc11 [exp-76ba1] | 06:16 PM     | 9      | 0.13434 | 0.94875    |
| 2e3c654 [exp-12afc] | 06:14 PM     | 9      | 0.18331 | 0.92932    |

**Comment by dberenbaum** [comment]
Related: https://github.com/iterative/dvc/issues/6194
