### ISSUE TITLE
Architectural Issue : Too many DVC repos needed for tracking for a simple use case

### ISSUE THREAD

**Issue by aveek-brahmachari** [iterative/dvc#6997]
Let us say we have the following folder structure:

&nbsp;&nbsp;Project 
      &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;  Data
      &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;   Experiments
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;  Experiment 1
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;  Experiment 2
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; .
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; .
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; .
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; Experiment N
     &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;   Models

And let us assume that we have a DVC repo each already set up for Data folder and Models folders 
The DVC repo has the master data subset or transformed version of which are used by the experiments in different Experiment folders.

Now, we move on to tracking of experiments (N models trainings for N different tasks) using CML.
**Issue1**: Do we really need N experiment repos to track N experiments ? Is there a better and more elegant solution available ?

**Issue 2**. The DVC repo for an experiment would be inside one of the Experiments, say Experiment1. This DVC repo might be needing a subset of/transformed data from the Data folder, and thus the experiment data should not need to be pushed and pulled separately in another repo.

**Observation**:
I observed that running the yaml file stages lead to creation of cache data ready to be pushed to another repo.
Also, pushing to the same data repo wont make sense as this is just a transformed version.
This did not even need dvc add and creation of .dvc files. 

**Question** : 
How can we minimize data redundancy across experiments using the Data folder outside the scope of the DVC repo set that is inside the Experiments folder ?

**Issue 3**. I would ideally want the output model to be directly written in the models folder which is git and dvc tracked. However, yaml stages do not allow models or any file to be written outside the scope of individual experiments. 
 
Please help me with answers and let me know if there is a better approach that can be taken using DVC and CML.
 Or am I missing something?

**Comment by dberenbaum** [comment]
> **Issue1**: Do we really need N experiment repos to track N experiments ? Is there a better and more elegant solution available ?

No, it's possible to have a single repo at the base of your project. It's hard to say without a bit more info about your project and needs, but it seems like a lot of your issues are about redundancy between the repos. Is a single repo at the base of the project instead possible for you? This would track the data and models and remove redundancy.

**Comment by aveek-brahmachari** [comment]
> > **Issue1**: Do we really need N experiment repos to track N experiments ? Is there a better and more elegant solution available ?
> 
> No, it's possible to have a single repo at the base of your project. It's hard to say without a bit more info about your project and needs, but it seems like a lot of your issues are about redundancy between the repos. Is a single repo at the base of the project instead possible for you? This would track the data and models and remove redundancy.

Can you point me to an example where multiple trained models are tracked using a single repo ?

**Comment by dberenbaum** [comment]
You can have the DVC repo at the base of your project and have the `dvc.yaml` files defining the pipelines anywhere (all together at the base, or separate `dvc.yaml` files within each experiment directory). There's an example of adding pipeline stages in subdirectories in https://dvc.org/doc/command-reference/stage/add#example-separate-stages-in-a-subdirectory.

If the experiments all have a similar structure, you might be able to use `foreach` stages to loop over all your experiment directories: https://dvc.org/doc/user-guide/project-structure/pipelines-files#foreach-stages.

It might help to know more about your project. What are the different experiments in the directories? Are they each entirely independent use cases?

**Comment by aveek-brahmachari** [comment]
> You can have the DVC repo at the base of your project and have the `dvc.yaml` files defining the pipelines anywhere (all together at the base, or separate `dvc.yaml` files within each experiment directory). There's an example of adding pipeline stages in subdirectories in https://dvc.org/doc/command-reference/stage/add#example-separate-stages-in-a-subdirectory.
> 
> If the experiments all have a similar structure, you might be able to use `foreach` stages to loop over all your experiment directories: https://dvc.org/doc/user-guide/project-structure/pipelines-files#foreach-stages.
> 
> It might help to know more about your project. What are the different experiments in the directories? Are they each entirely independent use cases?

Imagine it to be a project where in each experiment we segment out an object. We have trained different models to segment different objects. However, the details of the segments required in each experiment may be different and thus each model is trained on a subset of data or transformed data derived from the main data. The project already exists in a form that the stages may be different for each experiment and we dont want to refactor it to begin with.

**Comment by dberenbaum** [comment]
The easiest way to start is to leave everything the same except to initialize a single DVC repo at the base of your project instead of inside each experiment directory. Basically, this means that you have a `.dvc` directory, along with the cache and DVC metadata, at the base of the project instead of inside each experiment directory, but your `dvc.yaml`, `.dvc` files, etc. don't have to move.
