### ISSUE TITLE
dvc external add gives "inappropriate ioctl for device" on WSL2

### ISSUE THREAD

**Issue by skrishnanv** [iterative/dvc#7012]
# Bug Report

add --external: This command fails with inappropriate IOCTL.

## Description

 System is WSL2. Code repo is in C: drive(mounted as /mnt/c in WSL). I am checking the external data cache as outlined [here](https://dvc.org/doc/user-guide/managing-external-data#setting-up-an-external-cache). The dataset is in D drive(/mnt/d/ in WSL). The hash values are calculated and then the command exits with an error. The details are attached in log files.
[dvc_verbose_add.txt](https://github.com/iterative/dvc/files/7578369/dvc_verbose_add.txt)

### Expected

 I expect the external cache to be created as per the document.

### Environment information

dvc version 2.8.3

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
[dvc_doctor.txt](https://github.com/iterative/dvc/files/7578367/dvc_doctor.txt)

**Additional Information (if any):**

**Comment by efiop** [comment]
Hi @skrishnanv ! Thanks for reporting this bug! It has been fixed in upstream dvc, but hasn't been released yet. Could you try installing an upstream version and confirming that it fixes the issue for you, please? https://dvc.org/doc/install/pre-release

**Comment by skrishnanv** [comment]
thank you for such a speedy response. Yes, it does work for me. might be asking for more(compliment meant) but when can this be expected to be release? :-)

**Comment by efiop** [comment]
@skrishnanv Should be out this week.
