### ISSUE TITLE
ui: do we still need help footer on exceptions?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#7018]
These days we are not handling exceptions outside of `dvc` that well, eg: `fsspec` and `OSError`s. 

After we break SCM, it may be hard to reraise those exceptions to something from `DvcException` as the scm is used all over the codebase (see: #7017). 

Whenever we raise exceptions that are not `DvcException`, we print a small snippet for support:
```console
unexpected error - *
Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

It's not very clear what `unexpected error` and it's very hard to always raise `DvcException` (as it's only supposed to be raised when the error is known). See https://github.com/iterative/dvc/issues/4126 for some discussions around it before.

Also, I am not very sure if these messages are helpful at all.

**Comment by shcheklein** [comment]
It's looks like we have two separate problems:

1. It's not very clear what `unexpected error`. Agreed - what do you suggest to show instead?
2. Also, I am not very sure if these messages are helpful at all. Assuming this is partially about the support message. If there is at least is a small percent of people who find this link useful and used link what would be the reason to remove this? Potential downside - we'll see less bug reports.

**Comment by skshetry** [comment]
Closing as not planned.
