### ISSUE TITLE
plots: _collect: why it does not fail on data_source resolution on different branch

### ISSUE THREAD

**Issue by pared** [iterative/dvc#7021]
In #6832 
We introduced generator for data resolution, to let viewer load the plots files one by one and not strain the memory.
The test provided in https://github.com/iterative/dvc/pull/6832#issuecomment-950841004
Seems to show that if one does not resolve `data_source` before changing the branch (eg from `rev1` to `rev2`), the data resolved later will have a data from `rev2`. This test should fail, either by raising an error or resolving the data properly. Need to investigate why we allow such thing.

**Comment by dberenbaum** [comment]
I think we can close this one. Seems pretty narrow and haven't seen it come up.
