### ISSUE TITLE
Add parameter glob to freeze

### ISSUE THREAD

**Issue by rbenes** [iterative/dvc#7025]
I wanted to freeze more stages, that had some pattern in their name. I wanted to use `--glob` similarly as can be used e.g. for repro. But I found, that glob is not supported there.

```
➜  dvc_tmp dvc freeze --help
usage: dvc freeze [-h] [-q | -v] targets [targets ...]

Freeze stages or .dvc files.
Documentation: <https://man.dvc.org/freeze>

positional arguments:
  targets        Stages or .dvc files to freeze

optional arguments:
  -h, --help     show this help message and exit
  -q, --quiet    Be quiet.
  -v, --verbose  Be verbose
```

Is it possible to add it there?

**Comment by karajan1001** [comment]
Can we extract the `glob` logic from `repro`, `data_sync`, and `add`? I don't think it is a good solution to implement it separately.

**Comment by skshetry** [comment]
@karajan1001, it is already separated: ;-) 
https://github.com/iterative/dvc/blob/34f402659c34e3b958796a83337736f3b3636e13/dvc/repo/stage.py#L242-L251

There are challenges on adding `glob` on the commands that support both stages name/address and output paths, as `glob` may apply to both.
