### ISSUE TITLE
Update some of the help text on metrics/plots

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#7035]
We need to actually update some of the help text in the core repo, and then to update the command ref. So at least some of it needs to happen from the core team, and then we can see whether it makes sense to have the docs team take over some of it.

_Originally posted by @dberenbaum in https://github.com/iterative/dvc.org/issues/2956#issuecomment-966626613_

**Comment by pared** [comment]
Ill try to handle that @jorgeorpinel :)

**Comment by dberenbaum** [comment]
Thanks, @pared! Let me know if you want to discuss or have questions.

**Comment by jorgeorpinel** [comment]
Oops forgot to remove the sentence where you were mentioned @pared 😬 . Thanks though!

**Comment by pared** [comment]
Seems like, after some iterations over plot docs, this issue is no longer relevant?

cc @dberenbaum
