### ISSUE TITLE
webdav without or empty password

### ISSUE THREAD

**Issue by ANaumann85** [iterative/dvc#7069]
# Bug Report

## issue with dvc push using webdav without password

I use a webdav configuration of the form
```
['remote "webdav"']
    url = webdavs://example.cloud/public.php/webdav
    user = <code-to-shared-link>
```

Please note the non-existing entry "password" in the remote. 

Running `dvc push -v -r webdav ` shows an error message with the last lines
``` python-traceback
  File "${HOME}/.local/lib/python3.7/site-packages/httpx/_auth.py", line 136, in _build_auth_header
    userpass = b":".join((to_bytes(username), to_bytes(password)))
TypeError: sequence item 1: expected a bytes-like object, NoneType found
``` 

Inserting an empty password field is a simple solution. For backward compatibility, it would be better if one could ommit the field.

**Comment by skshetry** [comment]
Explicit is better than implicit here. I don’t like the idea of turning None/absence of values into `''`. 

We may want to add a test so that we don’t regress this _feature_ in the future. Closing for now.
