### ISSUE TITLE
Support of "dvc commit/push" in Python API

### ISSUE THREAD

**Issue by alextsakpinis** [iterative/dvc#7071]
Hello DVC Team,
I was wondering if you plan to implement functions for the Python API to execute `dvc commit` or `dvc push` from Python code? Right now, when I want to execute these commands programmatically, I execute them by running a shell script from the Python code. Is there a better way to call the CLI commands from Python code?

Thanks a lot for your help!

**Comment by daavoo** [comment]
You can use the internal `Repo` class (undocumented for now), which pretty much maps to the existing `CLI` commands (with some caveats):

```python
from dvc.api import Repo

repo = Repo(".")
# passing None as target would be equivalent to running `dvc commit` with no targets from CLI. 
repo.commit(None) 
```
