### ISSUE TITLE
plots: introduce option to show `json` result for all plots types

### ISSUE THREAD

**Issue by pared** [iterative/dvc#7073]
Related: #6752 

We need `--json` option that will basically return what any `dvc plots show/diff` would return but in form of machine-readable file.

For now, it will be a hidden option to be used only by `vscode`. We will see how useful that is and decide whether we should release it to the public.

**Comment by skshetry** [comment]
Since this is supposed to be hidden, should we name this flag to be `--json` at all?

**Comment by pared** [comment]
I think that the main point of hiding it is that as of today we are not sure how to handle the images and don't want to encourage users to utilize it. But if someone really wants to use that they will have no problem finding it, or asking us what the option name is. I don't think it makes too much difference if we will rename it, unless the option indicates that we are not encouraging to use it. So I think it could stay like that.
