### ISSUE TITLE
`dvc exp show`: Add mutually exclusive groups.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#7082]
> Also, this isn't a new issue, but `--html`, `--json`, `--csv`, `--md` should be mutually exclusive.
> _Originally posted by @dberenbaum in https://github.com/iterative/dvc/pull/6933#discussion_r752511034_

**Comment by casperdcl** [comment]
potentially https://docs.python.org/3/library/argparse.html#argument-groups or even better https://docs.python.org/3/library/argparse.html#mutual-exclusion

**Comment by skshetry** [comment]
Closing as not planned.
