### ISSUE TITLE
`exp init`: create DVC repo if needed?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#7109]
Shuold `dvc exp init` include `git init` and/or `dvc init` (if needed) so it's really a single command to onboard projects to DVC Exps?

**Comment by daavoo** [comment]
The `dvc init` part is currently being tracked as bullet point in https://github.com/iterative/dvc/issues/6446

**Comment by jorgeorpinel** [comment]
Thanks. Closed in favor of https://github.com/iterative/dvc/issues/6446#issuecomment-988256123.
