### ISSUE TITLE
`exp run`: remove `--no-commit` option?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#7110]
UPDATE: jump to https://github.com/iterative/dvc/issues/7110#issuecomment-988406787

Doing `dvc exp run --no-commit` seems pretty dangerous since it makes the experiment not reproducible. In `dvc run/repro --no-commit`, the user controls when the commit happens, so they can still make sure to `dvc commit` before doing git commit, but there's no (easy) way to update the experiment ref with the committed data.

_Originally posted by @dberenbaum in https://github.com/iterative/dvc.org/pull/3035#issuecomment-987839352_

**Comment by daavoo** [comment]
I think that `--no-commit` doesn't really do anything in `exp run`. 

It still makes sense to remove it from the CLI but just wanted to point it out.

**Comment by dberenbaum** [comment]
So dvc still caches the data even if `--no-commit` option is used? cc @pmrowla

**Comment by pmrowla** [comment]
`--no-commit` has no effect in `exp run`, by definition, in order for DVC to be saving an experiment so it can be accessed later, the data has to be cached

This is already mentioned in the command reference in the docs (https://dvc.org/doc/command-reference/exp/run#options)

> In addition to the following, dvc exp run accepts all the options in dvc repro, with the exception that --no-commit has no effect here.

**Comment by jorgeorpinel** [comment]
Thanks for confirming, so should it be removed? Throw s "bad argument" error. Currently it's accepted (always ignored).

> already mentioned in the command reference

p.s. that note is probably wrong? Not all other options from repro work for exp run. I thought you had looked into this before, right @iesahin ? Thanks

**Comment by pmrowla** [comment]
Yes, there's already a separate issue for that https://github.com/iterative/dvc/issues/6791

**Comment by iesahin** [comment]
Yep, I've checked it and even forgot that I've checked it. :) Thanks @pmrowla.

**Comment by jorgeorpinel** [comment]
Ahh OK closing this in favor of https://github.com/iterative/dvc/issues/6791#issuecomment-989338651 then. Thanks
