### ISSUE TITLE
exp show: alternate background colors slightly to make navigation easier

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#7128]
It would be way easier to navigate in the table if we had different background for items nearby, e.g. VSCode:

<img width="1051" alt="Screen Shot 2021-12-10 at 7 12 51 PM" src="https://user-images.githubusercontent.com/3659196/145661852-9a4dfd12-1690-487f-9f9e-4996e6ac0f88.png">

**Comment by skshetry** [comment]
This looks really bad on light and solarized light terminals.
<img width="1792" alt="Light Terminal" src="https://user-images.githubusercontent.com/18718008/147188154-dcbdcffa-54d6-4b04-9678-1d480630a395.png">

<img width="1792" alt="Solarized light" src="https://user-images.githubusercontent.com/18718008/147188209-b8806ac1-5255-4876-bd3b-c781c5ff5509.png">

The headers' color was already quite bad for light terminals.

**Comment by dberenbaum** [comment]
Good point, @skshetry. Looking at https://github.com/willmcgugan/rich/discussions/1170, it doesn't seem easy to solve in rich.

@shcheklein How is this handled in VS Code?

**Comment by shcheklein** [comment]
Do be honest I'm not sure. Probably we alternate and invert colors at the very least. Need to take a look.

cc @iterative/vs-code ?

**Comment by daavoo** [comment]
> Do be honest I'm not sure. Probably we alternate and invert colors at the very least. Need to take a look.
> 
> cc @iterative/vs-code ?

Not relaly equivalent to VSCode because VSCode does hace access to the theme used but there is not universal way of getting arbitrary terminal "theme"

**Comment by daavoo** [comment]
Re-opened in https://github.com/iterative/dvc/pull/7212

See background discussion #7202

Perhaps this is a feature request for rich? It doesn't look worth it to handle all the logic as part of `dvc exp show`
