### ISSUE TITLE
`exp init`: more verbose output in non-interactive mode

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7139]
Related to #7130. `dvc exp init -i` has verbose output to help guide the user. Non-interactive mode should have the same. A `-q` option can be added for experienced users to hide this output.

Current `dvc exp init -i` output:

```
$ dvc exp init -i python train.py
This command will guide you to set up a train stage in dvc.yaml.
See https://s.dvc.org/g/pipeline-files.

Enter the paths for dependencies and outputs of the command.
DVC assumes the following workspace structure:
├── data
├── metrics.json
├── models
├── params.yaml
├── plots
└── src

Path to a code file/directory [src, n to omit]:
'src' does not exist in the workspace. "exp run" may fail.
Path to a data file/directory [data, n to omit]:
'data' does not exist in the workspace. "exp run" may fail.
Path to a model file/directory [models, n to omit]:
Path to a parameters file [params.yaml, n to omit]:
Path to a metrics file [metrics.json, n to omit]:
Path to a plots file/directory [plots, n to omit]:
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
train:
  cmd: python train.py
  deps:
  - data
  - src
  params:
  - bar
  - foo
  outs:
  - models
  metrics:
  - metrics.json:
      cache: false
  plots:
  - plots:
      cache: false

Do you want to add the above contents to dvc.yaml? [Y/n]: Y

Created train stage in dvc.yaml. To run, use "dvc exp run".
See https://s.dvc.org/g/exp/run.
```

Current `dvc exp init` output:

```
$ dvc exp init python train.py
Created train stage in dvc.yaml. To run, use "dvc exp run".
See https://s.dvc.org/g/exp/run.
```

Proposed `dvc exp init` output:

```
$ dvc exp init python train.py
This command will set up a train stage in dvc.yaml.
See https://s.dvc.org/g/pipeline-files.

DVC assumes the following workspace structure:
├── data
├── metrics.json
├── models
├── params.yaml
├── plots
└── src

'src' does not exist in the workspace. "exp run" may fail.
'data' does not exist in the workspace. "exp run" may fail.
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
train:
  cmd: python train.py
  deps:
  - data
  - src
  params:
  - bar
  - foo
  outs:
  - models
  metrics:
  - metrics.json:
      cache: false
  plots:
  - plots:
      cache: false

Created train stage in dvc.yaml. To run, use "dvc exp run".
See https://s.dvc.org/g/exp/run.
```

**Comment by dberenbaum** [comment]
From #7130:

> `dvc exp init` is not fully supported without interactive mode.
It looks like today the only supported flow is — interactive. The default `dvc init` has multiple assumptions about the project structure and it is not clear how a user should know about the assumptions.

Fair point @dmpetrov. Making the output consistent between them can make non-interactive mode more like `dvc exp init -i`.

**Comment by dmpetrov** [comment]
There is a rule on https://clig.dev/#output - `Display output on success, but keep it brief.` It feels like these are not needed in the output if we follow the rule.

Two issues are here:

1. Do we need the content of dvc.yaml in the output?
```
train:
  cmd: python train.py
  deps:
  - data
```

2. Do we need links in the output? (Especially as a single line)
```
See https://s.dvc.org/g/pipeline-files.
...
See https://s.dvc.org/g/exp/run.
```

**Comment by dberenbaum** [comment]
> There is a rule on https://clig.dev/#output - `Display output on success, but keep it brief.` It feels like these are not needed in the output if we follow the rule.

I think @skshetry would agree, which explains why there is so little output in non-interactive mode now. I suggested more verbose output since this command is tailored to users with no prior dvc knowledge.

> 1. Do we need the content of dvc.yaml in the output?

No. It can be an intro to dvc stage syntax, but it's not necessary. We also don't need to show it or prompt for confirmation in `dvc exp init -i`.

> Do we need links in the output? (Especially as a single line)

No. Again, I/we opted for more verbose output to guide users more. It's not output that is/needs to be machine readable, and I thought usability should trump style in this case, but obviously it can be removed.

---

Given those suggestions, the basic output can be:

```
$ dvc exp init python train.py
DVC assumes the following workspace structure:
├── data
├── metrics.json
├── models
├── params.yaml
├── plots
└── src

Created train stage in dvc.yaml. To run, use "dvc exp run".
```

Should we also make interactive mode more concise?

```
$ dvc exp init -i python train.py
DVC assumes the following workspace structure:
├── data
├── metrics.json
├── models
├── params.yaml
├── plots
└── src

Path to a code file/directory [src, n to omit]:
Path to a data file/directory [data, n to omit]:
Path to a model file/directory [models, n to omit]:
Path to a parameters file [params.yaml, n to omit]:
Path to a metrics file [metrics.json, n to omit]:
Path to a plots file/directory [plots, n to omit]:

Created train stage in dvc.yaml. To run, use "dvc exp run".
```

**Comment by dberenbaum** [comment]
One thought on this: having quasi-unix style makes sense for dvc. In this case, I'm not so sure since the intended audience is less likely to be people familiar with that style.
