### ISSUE TITLE
Can't use `repo.metrics.show()` when have a long current dir

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#7147]
This call combined with asserts prevents it:

https://github.com/iterative/dvc/blob/0deab0118a947f3c92cf8a7dd6c7daf0fac5988f/dvc/repo/metrics/show.py#L84

https://github.com/iterative/dvc/blob/0deab0118a947f3c92cf8a7dd6c7daf0fac5988f/dvc/fs/path.py#L83-L85

This blocks Studio updating to DVC 2.9.2.

**Suggested fix:** move relpath calculation to command code, remove asserts as having a longer base should be ok. Returning relpath from API code like `repo.metrics.show()` is unexpected, that code is not really aware about cwd, both absolute paths or paths relative to repo root make sense.

**Comment by efiop** [comment]
> Suggested fix: move relpath calculation to command code, remove asserts as having a longer base should be ok. Returning relpath from API code like repo.metrics.show() is unexpected, that code is not really aware about cwd, both absolute paths or paths relative to repo root make sense.

For the record: what we really want here is paths from the repo's filesystem perspective. Similar to git, for dvc repos, no matter if they are local or "virtual"(based on gitfs with temp cloned repo) those paths should be natively relative to the root of the repo. We are working on detaching abs temporary paths from gitfs and will fix this in the future (i mean that the paths will be natively relative to the repo root, but the caller can adjust them as he pleases, e.g. if he is in some repo subdir and wants relpaths to that).
