### ISSUE TITLE
exceptions: raise generic exceptions properly

### ISSUE THREAD

**Issue by pared** [iterative/dvc#7157]
In #7120 we had ambiguous error, because the raised `FileNotFoundError` did not provide any context. I think it would be more informative if we would be raising generic errors with proper messages - like in #7156.

EDIT:
resolving this issue would require finding in the codebase where are we using `raise` with generic exceptions without any arguments and providing relevant messages.

**Comment by pared** [comment]
Related: https://github.com/iterative/cse/issues/4

**Comment by ykasimov** [comment]
I took a look at this issue and I am posting here my findings. 

I used `raise (?!NotImplemented|MachineDisabledError|.*from).*(?<!\(|\))$` regex to find exceptions that don’t end with ( or with (  and without from keyword.

It yielded 16 matches in total. all of them seem fine and produce a meaningful message. I reproduced only one (there is a note next to it in the list) and others seem fine from looking at the code. 
```
https://github.com/iterative/dvc/blob/main/dvc/scm.py#L81

https://github.com/iterative/dvc/blob/main/dvc/api/params.py#L238 (used only here with a broad exception: https://github.com/iterative/dvc/blob/main/dvc/utils/__init__.py#L415)

https://github.com/iterative/dvc/blob/main/dvc/cli/parser.py#L100

https://github.com/iterative/dvc/blob/main/dvc/commands/checkout.py#L57

https://github.com/iterative/dvc/blob/main/dvc/commands/stage.py#L90

https://github.com/iterative/dvc/blob/main/dvc/fs/data.py#L67

https://github.com/iterative/dvc/blob/main/dvc/fs/data.py#L71

https://github.com/iterative/dvc/blob/main/dvc/fs/dvc.py#L430 (exception is handled in the calling function with a message)

https://github.com/iterative/dvc/blob/main/dvc/parsing/__init__.py#L89

https://github.com/iterative/dvc/blob/main/dvc/proc/manager.py#L41

https://github.com/iterative/dvc/blob/main/dvc/repo/stage.py#L194

https://github.com/iterative/dvc/blob/main/dvc/repo/experiments/__init__.py#L58

https://github.com/iterative/dvc/blob/main/dvc/repo/experiments/__init__.py#L267

https://github.com/iterative/dvc/blob/main/dvc/utils/serialize/_json.py#L35

https://github.com/iterative/dvc/blob/main/dvc/utils/serialize/_py.py#L131

https://github.com/iterative/dvc/blob/main/dvc/utils/serialize/_py.py#L168
```

**Comment by pared** [comment]
I wonder if those errors didn't migrate to our other projects like `dvc-data` and `dvc-objects`. I guess if this issue reoccurs we can reopen. Thanks, @ykasimov for the research!
