### ISSUE TITLE
ERROR: output 'data\data.xml' does not exist

### ISSUE THREAD

**Issue by zhenzi0322** [iterative/dvc#7164]
```cmd
dvc add ./data/data.xml
```
Output：
```
Adding...
ERROR: output 'data\data.xml' does not exist
```

**Comment by zhenzi0322** [comment]
> ```batchfile
> dvc add ./data/data.xml
> ```
> 
> Output：
> 
> ```
> Adding...
> ERROR: output 'data\data.xml' does not exist
> ```

Environment：
- Windows

**Comment by karajan1001** [comment]
Hi, @zhenzi0322  could you please give some more details, for example:
1. your repository structure, if the file `data/data.xml`.
2. the log output of `dvc add ./data/data.xml`.

If you met this problem, in `https://dvc.org/doc/start/data-and-model-versioning`
please make sure you had downloaded the data set in previous.
![image](https://user-images.githubusercontent.com/6745454/146523550-a0c23b34-2949-4299-b856-3ffd355e0392.png)

**Comment by zhenzi0322** [comment]
> 嗨，@zhenzi0322你能提供更多细节吗，例如：
> 
> 1. 您的存储库结构，如果文件 .`data/data.xml`
> 2. 的日志输出。`dvc add ./data/data.xml`
> 
> 如果您遇到此问题，请确保您之前已下载了数据集。`https://dvc.org/doc/start/data-and-model-versioning` ![image](https://user-images.githubusercontent.com/6745454/146523550-a0c23b34-2949-4299-b856-3ffd355e0392.png)

OK, Thank you.

**Comment by efiop** [comment]
Closing as stale.
