### ISSUE TITLE
DVC slow md5 checksum

### ISSUE THREAD

**Issue by malolnaor** [iterative/dvc#7166]
Hi,
We have a large dataset(around 170G) with lots of small files, The `dvc add` command takes around 12H.

The `dvc add` command has an option for: 
`
  -j <number>, --jobs <number>
                        Number of jobs to run simultaneously. The default value is 4 * cpu_count().
                        For SSH remotes, the default is 4.
`
But this parameter only works together with `--to-remote` parameter.
There is any way to create md5 checksum in parallel using the jobs parameter without pushing?

**Comment by karajan1001** [comment]
Hi, @malolnaor 

Could you please provide some more details?

1, which version and what environment are you using? (can be achieved with `dvc doctor`)
2, more detailed logs with a `-vv` flag after your `dvc add` command.

Thank you.

**Comment by malolnaor** [comment]
Hi,

I created a sample dataset with 30K small files (I can't use my real dataset).
`dvc doctor` returns the following:

```
DVC version: 2.9.2 (pip)
---------------------------------
Platform: Python 3.9.2 on Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
Supports:
        webhdfs (fsspec = 2021.11.1),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.11.1, boto3 = 1.20.24)
Cache types: reflink, hardlink, symlink
Cache directory: xfs on /dev/mapper/cl-root
Caches: local
Remotes: s3
Workspace directory: xfs on /dev/mapper/cl-root
Repo: dvc, git

```
I ran 2 tests:
1. Adding an archive file containing all the files in the dataset.
2. Adding a folder containing all the files in the dataset.

The first test returns the following:
```
[root@sandbox]# time dvc add test-single-file.tar.gz
100% Adding...|█████████████████████████████████████████████████████████████|1/1 [00:00, 18.39file/s]

To track the changes with git, run:

    git add .gitignore test-single-file.tar.gz.dvc

To enable auto staging, run:

        dvc config core.autostage true

real    0m1.183s
user    0m1.101s
sys     0m0.116s

```
The second test:

```
[root@sandbox]# time dvc add test
100% Adding...|█████████████████████████████████████████████████████████████|1/1 [00:52, 52.95s/file]

To track the changes with git, run:

    git add test.dvc

To enable auto staging, run:

        dvc config core.autostage true

real    0m54.221s
user    0m41.335s
sys     0m10.362s

```

Is there any way to make `dvc add` faster?
A debug log is attached.
[dvc-debug.txt](https://github.com/iterative/dvc/files/7739751/dvc-debug.txt)

Thanks!

**Comment by karajan1001** [comment]
@malolnaor 
For the `-j` option it is used in starting multi-threads to upload to the remote storage, so it was not used here.

For the hash computing job, the default value is
```
 max(1, min(4, cpu_count() // 2))
```
If you want to set it manually, you can use `dvc config` to set a value for `core.checksum_jobs`
https://dvc.org/doc/command-reference/config#core

**Comment by efiop** [comment]
Closing as stale.
