### ISSUE TITLE
TabularData: Use `None` internally

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#7167]
> After reading your explanation, I think this PR is probably fine for now, maybe just open a separate issue regarding making `TabularData` store `None` types instead of the fill strings.

_Originally posted by @pmrowla in https://github.com/iterative/dvc/issues/7064#issuecomment-996628424_

Use `None` internally and only replace it with `fill_value` when rendering.

**Comment by karajan1001** [comment]
In pandas Dataframe, the behavior is we don't give a default value to replace `null` when the Dataframe is created. 
But the calling of method `fillna` will permanently replace the `null` value.

**Comment by skshetry** [comment]
Related: https://github.com/iterative/dvc/pull/6893#discussion_r751983684 and https://github.com/iterative/dvc/pull/6867#discussion_r736702708.

It's not just None. Ideally, I'd like to have support for arbitrary data. This will come really useful for example in floats rendering.
We may need to do some filtering based on actual floats' values and/or need to have different forms of rendering them ("%g" vs "%e" etc.) and with different precisions. 

The internals has to change significantly I think to make these adjustments, and may probably be the time for it.
