### ISSUE TITLE
Not able to switch between different datasets using Git tags and DVC Python API

### ISSUE THREAD

**Issue by Vinayaks117** [iterative/dvc#7175]
# Bug Report

## Issue name
Not able to switch between different datasets using Git tags and DVC

## Description

I have created the one version (V1) of dataset, added to dvc, committed the changes to GIT with tag details and pushed that file to remote storage.

Also I have created new version (V2) of dataset, added to dvc, committed the changes to GIT with tag details and pushed that file to remote storage.

When I tried to read the data from V2 of dataset using GIT tag then I am able to get it using dvc python API.
But when I tried to read the data from V1 of dataset using GIT tag then I am getting below errors.

**Error details**:

dvc.config.NoRemoteError: config file error: no remote specified. Create a default remote with
    dvc remote add -d <remote name> <remote url>

dvc.exceptions.PathMissingError: The path '..\..\..\..\..\Users\Vinayak \AppData\Local\Temp\tmpoy9ijqkldvc-clone\data\Products.csv' does not exist in the target repository 'https://gitlab.com/ai_pipelines.git' neither as a DVC output nor as a Git-tracked file.

### Reproduce

-----------------------------------------------------------------------------------
**DVC and GIT commands:**

git init

dvc init

git status

git commit -m 'Initialized dvc repo'

git push origin main

Create/place a csv file in data directory

git status

dvc add data/Products.csv

git add 'data\Products.csv.dvc' 'data\.gitignore'

git commit -m 'Add raw dataset'

git tag -a 'data_v1' -m 'Added tag for raw dataset'

git push origin main

git push origin main data_v1

dvc commit

git show data_v1

dvc remote add -d storage s3://Products/Datasets

git add .dvc/config

git commit -m "Configured remote storage"

git push origin main

dvc commit

dvc push

Removed few lines in Products.csv - Updated dataset

dvc add data/Products.csv

git add 'data\Products.csv.dvc'

git commit -m 'Dataset updates'

git tag -a 'data_v2' -m 'New tag for raw dataset'

git push origin main

git push origin main data_v2

dvc commit

git show data_v2

dvc push

-----------------------------------------------------------------------------------
**Note:** If I try with below commands then I can switch between different versions. 

git checkout 'data_v1'
dvc checkout

git checkout 'data_v2'
dvc checkout

But can't switch between different versions when I use below DVC python API script.

**DVC Python API code:**

import dvc.api
import pandas as pd

with dvc.api.open(
    path='data/Products.csv',
    repo='https://gitlab.com/ai_pipelines.git',
    mode="r",
    rev='data_v1'
) as fd:
    df = pd.read_csv(fd)
    print(df.head())
    print(df.shape)

**Note:** If I try with GIT tag/rev = "data_v2" in above code then it works fine. But if I try with GIT tag/rev = "data_v1" then I get an error.

### Expected

I want to switch between different datasets using GIT tags by using DVC python API.

### Environment information

Python 3.8.8
DVC 2.9.2

**Output of `dvc doctor`:**

![image](https://user-images.githubusercontent.com/37987800/146796492-de7cdd9d-663c-47b9-ba00-5af9335dd96b.png)

**Additional Information (if any):**

**Comment by daavoo** [comment]
Hi @Vinayaks117 ! 

Can you try setting a default remote (https://dvc.org/doc/command-reference/remote#example-add-a-default-local-remote) and/or pass a `remote` name to your `dvc.api.open` call (https://dvc.org/doc/api-reference/open#parameters) to see if the problem persists?

**Comment by Vinayaks117** [comment]
Thanks for your reply @daavoo 

If you look at my command list above then I am already setting default remote as "storage".

dvc remote add -d storage s3://Products/Datasets

As suggested, I tried passing the remote = "storage" in dvc.api.open call then it works fine with "data_v2" tag but it does not work with "data_v1" tag.

Issue still persists.

Here is my .dvc/config file:
![image](https://user-images.githubusercontent.com/37987800/146927987-fc0b0a69-a1a1-4589-8a79-ac891adb308d.png)

**Updated DVC Python API code:**

import dvc.api
import pandas as pd

with dvc.api.open(
   path='data/Trading_Cards_MainGrades.csv',
   repo='https://gitlab.com/ai_pipelines.git',
   mode="r",
   remote="storage"
   rev='data_v1'
) as fd:
   df = pd.read_csv(fd)
   print(df.head())
   print(df.shape)

Please have a look. Thank you.

**Comment by pmrowla** [comment]
The issue is that the remote does not exist in your `data_v1` tag.

```
git commit -m 'Add raw dataset'  # dvc remote add has not yet been run, .dvc/config contains no remotes in this git commit
git tag -a 'data_v1' -m 'Added tag for raw dataset'
git push origin main
git push origin main data_v1
dvc commit
git show data_v1
dvc remote add -d storage s3://Products/Datasets
git add .dvc/config
git commit -m "Configured remote storage"  # this git commit contains both the dataset from data_v1 and the configured DVC remote
git push origin main
```

The remote is added after the tagged commit (meaning the remote does not exist in `.dvc/config` in the tagged commit). When you use `api.open(rev="data_v1")`, DVC will clone the repo at that specific tagged commit, and look for a remote in `.dvc/config` from that commit.

Basically, what you need to do is change your tag so it points to the commit with the message `Configured remote storage` which will contain both the dataset that you want, as well as the configured DVC remote.

**Comment by Vinayaks117** [comment]
Thank you so much @pmrowla 

I have to initialize and configure remote storage then manage the dataset versions using git tags.

**Comment by parthplc** [comment]
@Vinayaks117 can you help me regarding this? I am still facing the same issue even after configuring the remote first.
