### ISSUE TITLE
2.8.1 is the latest version from `pip`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#7181]
Is that normal? Maybe it's just my system? My py env is def. messy rn...

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc/issues/7143#issuecomment-994119202_

**Comment by pmrowla** [comment]
The latest version from pip is 2.9.2: https://pypi.org/project/dvc/#history. There's something wrong with your local python environment/config.

**Comment by jorgeorpinel** [comment]
Hmmm OK shouldn't be a problem then. Hopefully I can fix up my env.

**Comment by jorgeorpinel** [comment]
Thanks

**Comment by skshetry** [comment]
Per, https://github.com/iterative/dvc/issues/7143#issue-1079219087, the Python version is 3.6.

We dropped support for Python 3.6 in 2.8.2, so the last version to support 3.6 is 2.8.1 which is why it's  being installed.

**Comment by jorgeorpinel** [comment]
That explains it! So should we specify our Python 3.7 dependency in install docs like https://dvc.org/doc/install/macos#install-with-pip ? Otherwise it probably won't be obvious to others in my situation why `pip` won't install the latest DVC. Or use something like `python37 -m pip install --upgrade dvc` which implies it.

**Comment by jorgeorpinel** [comment]
p.s. that last command is giving me an error though.

```
...
Collecting flufl.lock>=5 (from dvc)
  Using cached https://files.pythonhosted.org/packages/f4/3d/2f24d5661a51585507fede31ec6d4c4ba94366efbe046bfa6d7e8ce0425b/flufl.lock-6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_xzvuytw/flufl.lock/setup.py", line 4, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name 'find_namespace_packages' from 'setuptools' (/usr/lib/python3/dist-packages/setuptools/__init__.py)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_xzvuytw/flufl.lock/
```

**Comment by jorgeorpinel** [comment]
p.p.s. upgraded my global `pip` [like this](https://stackoverflow.com/a/56140616/761963) and it runs the install but it's much longer and it throws a bunch of `flufl.lock` errors and ends up installing DVC 2.8.1 anyway 😢 (even when it states it's going to install 2.9.3 initially).

**Comment by pmrowla** [comment]
You probably need to do
```
pip install -U setuptools
pip install -U pip
```

What python are you using?

---

On the docs side, it probably makes sense for us to make it clearer what the minimum supported python version is, it's currently only stated in the venv/pipx note:

> We strongly recommend creating a virtual environment or using pipx (on Python 3.7+) to encapsulate your local environment.

It would be better if it was noted more explicitly that 3.7+ is a hard requirement.

But beyond that, IMO it should be safe for us to assume that anyone choosing the "install via pip" method (as opposed to using the binary or conda packages) should already understand how to set up a python/pip environment on their machine. Providing support and documentation for keeping python/pip up-to-date is out of scope for us.

Users that aren't familiar with managing python themselves should already be using the system packages (or conda) which handles all of that for them.

**Comment by pmrowla** [comment]
> p.p.s. upgraded my global `pip` [like this](https://stackoverflow.com/a/56140616/761963) and it runs the install but it's much longer and it throws a bunch of `flufl.lock` errors and ends up installing DVC 2.8.1 anyway 😢 (even when it states it's going to install 2.9.3 initially).

Assuming your linux distro's system python is 3.6, your "global" `python`/`python3`/`pip`/`pip3` is always going to be python 3.6 unless you are explicitly setting up something like pyenv.

If you've installed a different python (like 3.7) from source or from a PPA, you will most likely always need to explicitly use `python3.7 -m pip` or `pip3.7`.  This is a linux configuration issue, not a DVC issue.

**Comment by jorgeorpinel** [comment]
> pip install -U pip

Thanks @pmrowla ! I managed to upgrade my global `pip` in a different way (see https://github.com/iterative/dvc/issues/7181#issuecomment-1001955857) so this now reports `pip install -U pip`. The problem is a bit different now...

> Assuming your linux distro's system python is 3.6 ...

I got Python 3.7 and pip 21 on it. I installed both manually.

```console
~ python -V
Python 3.7.5
~  pip -V
pip 21.3.1 from /home/me/.local/lib/python3.7/site-packages/pip (python 3.7)
```

> always need to explicitly use `python3.7 -m pip` or `pip3.7`

Unfort neither method is working for me as reported in https://github.com/iterative/dvc/issues/7181#issuecomment-1001950729 and https://github.com/iterative/dvc/issues/7181#issuecomment-1001955857, resp.

**Comment by pmrowla** [comment]
What command are you using to install DVC? If you are trying to install DVC via pip, you should be using virtualenvs or pipx like we recommend in the docs, specifically because managing global/system pythons on most platforms is a giant mess (as you have encountered).

On ubuntu 18.04 (where the system python is 3.6) if you still want to install it "globally" for your user into `~/.local/lib/...` you should be doing:

```
python3.7 -m pip install --user dvc
```

**Comment by jorgeorpinel** [comment]
Yeah I prefer to have it globally. It probably works just fine in a venv.

> `python3.7 -m pip install --user dvc`

This did the trick! (After I uninstalled the other `dvc`)

> you likely have more than one version of dvc installed

I don't think so 🙂 only had that one global pip-ed one which I just uninstalled.

Thanks again!

**Comment by jorgeorpinel** [comment]
> > you likely have more than one version of dvc installed
>
> I don't think so 🙂

Well, actually you're probably right since this is Windows underneath and I do have DVC installed from binary on there.

```console
~  whereis dvc
dvc: /home/me/.local/bin/dvc /mnt/c/Program Files (x86)/DVC (Data Version Control)/dvc.exe /mnt/c/Users/me/AppData/Local/Programs/Python/Python38/Scripts/dvc.exe
```
