### ISSUE TITLE
dvc push command throw an ERROR: unexpected error - __init__() got an unexpected keyword argument 'cache_regions'

### ISSUE THREAD

**Issue by Vinayaks117** [iterative/dvc#7188]
# Bug Report

## Issue name

dvc push command throwing a below error.

ERROR: unexpected error - __init__() got an unexpected keyword argument 'cache_regions'

OS: Ubuntu 18.04.5 LTS
DVC version: 2.9.2

Please refer the attached logs from dvc push -vv command.

Also I am not able to see .dvc and .dvcignore directories in Ubuntu machine, but I can execute all dvc commands except dvc push.

Could you please help me on this issue?

Thank you

[dvc_push_logs.txt](https://github.com/iterative/dvc/files/7762337/dvc_push_logs.txt)

**Comment by skshetry** [comment]
Hi, @Vinayaks117, you have a very old `s3fs` package. Could you please update with `pip install -U dvc[hdfs,s3]` and see if it that works?

**Comment by Vinayaks117** [comment]
Yes, it's working fine. Thanks a lot @skshetry

Do you know why can't we see the .dvc and .dvcignore files in Ubuntu machine?
