### ISSUE TITLE
How to use dvc python APIs in Flask application? 

### ISSUE THREAD

**Issue by Vinayaks117** [iterative/dvc#7199]
Hi All,

I know this is not a bug, but kindly request you to help me on this issue.

We want to load the dvc tracked models dynamically using flask application. I believe this is the basic requirement of serving the dvc tracked trained models.

Let's say we want to serve the respective dvc tracked model versions using flask API url.

https://<hostname:port>/version/resource/

For example: Users can pass any version in above url and analyse the model behaviour between different versions.

https://<hostname:port>/v1/customerapp
https://<hostname:port>/v2/customerapp
https://<hostname:port>/v3/customerapp

Code snippet from Flask application.

```
data_url = dvc.api.get_url(
            path='data/logistic_regression_deeplearning'+ model_version + '.pth',
            repo='https://gitlab.com/ai_pipelines.git',
            remote="storage",
            rev='tcmodel' + model_version
        )
```

**Do you have any examples on how to use dvc python APIs in Flask application?**

FYI: I tried using above code snippet in flask application hosted on uwsgi server then I was getting Segmentation fault.

**Comment by efiop** [comment]
@Vinayaks117 It is very hard to tell what specifically went wrong in your setup, as there are too many variables. Is that code snippet causing the segfault itself? Does it fix it if you comment it out and not call dvc at all?

**Comment by Vinayaks117** [comment]
@efiop Thanks for your reply.

Yes, I have tested multiple times, same code snippet is causing an issue and flask app works fine without dvc call.

FYI: I have logged an issue in uwsgi github site but no response yet

https://github.com/unbit/uwsgi/issues/2386

**Comment by efiop** [comment]
@Vinayaks117 Could you try setting `DVC_NO_ANALYTICS=1` env var and see if that helps?

**Comment by Vinayaks117** [comment]
@efiop As suggested, I did set the following environment variable in Flask app but no luck.

os.environ['DVC_NO_ANALYTICS'] = "1"

**Comment by efiop** [comment]
@Vinayaks117 Does that code snippet work outside of flask, on the same machine?

**Comment by Vinayaks117** [comment]
@efiop 

Yes, it works outside of Flask.

It works within Flask application as well. But it does not work when we deploy that Flask app on uWSGI server.

I also tried it with gUnicorn WSGI server, same code snippet works fine as well.

Looks like there is a bug in uWSGI server.

Thanks

**Comment by pmrowla** [comment]
Thanks for the clarification @Vinayaks117 , I'm going to close this since it looks like it's not a DVC issue (and is something specific in uWSGI)
