### ISSUE TITLE
pull: Incorrect error message when pip dependencies are missing

### ISSUE THREAD

**Issue by ntjess** [iterative/dvc#7211]
# Bug Report

## Description

I'm getting the following error on trying to recreate an old dataset:

```
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
C:\path\to\repo\data
Is your cache up to date?
```

Through running `dvc list -R <remote>`, I saw a much more helpful:
```
<remote> is supported but requires these missing dependencies: ['pydrive2']. To install dvc with those dependencies, run...
<commands>
```

The correct message instead of "error: failed to pull data" should inform the user they are  missing dependencies just like "list remotes" does.

### Reproduce

1. pip install dvc[gdrive]
2. Create gdrive-backed dvc repo
3. In a new venv, pip install dvc without the gdrive dependency
4. run `dvc pull <path/to/repo.git>` in the new venv
5. The error message displays

### Expected
Error message with something to the effect of

```
<remote> is supported but requires these missing dependencies: ['pydrive2']. To install dvc with those dependencies, run...
<commands>
```

**Comment by ntjess** [comment]
For reference, I first asked this question on Discord and it was recommended to create an issue here: https://discord.com/channels/485586884165107732/563406153334128681/924180307840757820

**Comment by tirkarthi** [comment]
See also https://github.com/iterative/dvc/issues/6870

**Comment by efiop** [comment]
Closing in favor of #6870
