### ISSUE TITLE
odb: index pickle version should be explicit

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#7220]
Currently we don't specify a pickle version when we use `diskcache` in the ODB/remote index, so we will potentially run into the same problem as: https://github.com/iterative/dvc/issues/5563

discord context: https://discord.com/channels/485586884165107732/485596304961962003/927613942908465162

**Comment by skshetry** [comment]
We do specify them here @pmrowla.
https://github.com/iterative/dvc/blob/0a4958bafd8797e5fe4a9c9fa189e857111facd6/dvc/state.py#L62

**Comment by pmrowla** [comment]
Right, we specify the protocol version for state (and links) but not for index
https://github.com/iterative/dvc/blob/0a4958bafd8797e5fe4a9c9fa189e857111facd6/dvc/objects/db/index.py#L99
