### ISSUE TITLE
DVC commands prohibitively slow in SageMaker Studio

### ISSUE THREAD

**Issue by olliestanley** [iterative/dvc#7230]
# Bug Report

## Description

When executing `dvc pull` on a freshly cloned Git repository within SageMaker studio, the command takes hours to run even when attempting to pull only a small section of the versioned files within the DVC store, on DVC 2.9.3. This can be partially mitigated by downgrading to DVC version 2.3.0.

In my specific case, a large number of files are versioned (approx 500,000) and I wonder if this is to do with the problem. This is for computer vision so there are many image files. I attempted to pull one versioned directory (containing around 850 files) instead of everything, and this took only 20 seconds when executing on my local machine, but when executing in SageMaker Studio was forecast to take nearly 3 hours.

### Reproduce

Version image files within DVC, using an S3 bucket as a DVC store, and push to a Git repo.

`dvc init`
`dvc add ...`
`dvc push`
`git commit ...`
`git push`

Clone the Git repo within SageMaker Studio and attempt to pull from DVC.

`git clone ...`
`dvc pull`

### Expected

Behaviour should be similar to on my local machine where `dvc pull` executes quickly when trying to pull the subset of versioned data.

### Environment information

Environment is SageMaker Studio (reproduced on multiple instance types) using the `Python 3 (Data Science)` image with dvc[s3]==2.9.3 installed using pip. Issue was also reproduced on earlier versions of DVC.

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.7.10 on Linux-4.14.256-197.484.amzn2.x86_64-x86_64-with-debian-10.6
Supports:
	hdfs (fsspec = 2021.11.1, pyarrow = 6.0.1),
	webhdfs (fsspec = 2021.11.1),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2021.11.1, boto3 = 1.20.23)
Cache types: hardlink, symlink
Cache directory: nfs4 on 127.0.0.1:/200030
Caches: local
Remotes: s3
Workspace directory: nfs4 on 127.0.0.1:/200030
Repo: dvc, git
```

**Additional Information (if any):**

I found linked but not identical problems from the past. [This one](https://issueexplorer.com/issue/iterative/dvc/6599) prompted me to try downgrading DVC to 2.3.0. This was successful in allowing me to pull a single dataset in a comparable (although still longer) length of time to when running the command on my local machine. It therefore seems that something in DVC (or a dependency) has been changed since 2.3.0 to cause this issue.

Note: I have not provided verbose output as there is no error or non-standard output when running the command, only very slow progression.

**Comment by efiop** [comment]
@olliestanley Could you run `dvc pull --cprofile-dump pull.prof` and post `pull.prof` ,please?

**Comment by olliestanley** [comment]
> @olliestanley Could you run `dvc pull --cprofile-dump pull.prof` and post `pull.prof` ,please?

Do I need to wait for the pull to finish to obtain `pull.prof`? If so that won't be possible unfortunately, as when this issue occurs the pull would take days to finish

**Comment by skshetry** [comment]
> > @olliestanley Could you run `dvc pull --cprofile-dump pull.prof` and post `pull.prof` ,please?
> 
> Do I need to wait for the pull to finish to obtain `pull.prof`? If so that won't be possible unfortunately, as when this issue occurs the pull would take days to finish

You can try pulling a smaller dataset or subset of a large dataset.
```console
dvc pull small-dataset --cprofile-dump dump.prof
dvc pull dataset/sub/set --cprofile-dump dump.prof
```

You can also create a small repo for the test if that's easier, we just need information where the time is being spent in general. Thanks.

**Comment by olliestanley** [comment]
@skshetry @efiop Apologies for the delay responding to this. In attempting to obtain the profiling information for you I realised the problem only occurs when pulling a large subsection. I pulled our smallest dataset from the store (around 850 files) and it completed in a couple of minutes on DVC 2.9.3 no problem on SageMaker. So assuming something close to linear scaling you might expect a 20,000 file dataset to take around an hour. Instead, I left the larger dataset pull running for 24 hours on SageMaker and it had not gotten close to finishing. The same large dataset pulls fine on my local machine, in around 40 minutes. I was therefore not able to obtain profiling information for a problematic pull, but here is the profiling information for the successful pull of a smaller number of files:

[pull.prof.zip](https://github.com/iterative/dvc/files/7838324/pull.prof.zip)

**Comment by skshetry** [comment]
@olliestanley, is that the correct profiling data? It seems to only run for 5.8s.

**Comment by olliestanley** [comment]
> @olliestanley, is that the correct profiling data? It seems to only run for 5.8s.

That is definitely the profiling data for one of the successful pulls I executed on a small subset of our data. I ran two in total, here's the profiling data for the other (with a slightly larger but still small subset) if it's any more useful:

[pull2.prof.zip](https://github.com/iterative/dvc/files/7838365/pull2.prof.zip)

**Comment by louis-van-der-stam** [comment]
I came here via a google search after experiencing something similar. While investigating dvc I found that running it with the workarea on a local HHD/SSD gives good performance, but running it on a workarea that is on a mounted filesystem deteriorates the performance below a usefull level for a project with a large number of files managed by dvc. When running a command to manualy md5sum and cp the files the performance does not degrade to the level where dvc brings it. Going back to version 2.3.0 indeed increased the performance somewhat, but still far below the manual level. Adding --job 10 --to-remote with a remote directory on the same mounted drive increased performance to an acceptable level.
If not relevant or discussed somewhere else please let me know.

**Comment by dberenbaum** [comment]
> I came here via a google search after experiencing something similar. While investigating dvc I found that running it with the workarea on a local HHD/SSD gives good performance, but running it on a workarea that is on a mounted filesystem deteriorates the performance below a usefull level for a project with a large number of files managed by dvc.

Possibly related: #5562

**Comment by EliAlpaca** [comment]
From my little experience with sagemaker and DVC.

Are you making these tests on files that are just being reader after starting your sagemaker instance? (Are you using sagemaker notebooks instances?)

Sagemaker uses EBS for file systems and when you turn down an instance the volume is compressed and stored away. Your problem with the pull request may be related to how long does it take for dvc to calculate the hash of the local files to see if they've been changed. In my case, the first read of a 50GB file stored in the sagemaker notebook instance took more than an hour. The problem may be related with only the download of the file, and in this case you can check that with the dstat command.

Turn your instance and open a console kernel, and run
```
sudo yum install dstat -y
dstat -n -d
```
And check the read/write performance on both network and disk. Usually, if your problem is related to EBS filesystem you will see that the disk read/write operations are really slow the first time the file is being accessed, and in subsequent operations it will be orders of magnitude higher. (6MB/s read first and 100MB/s in subsequent read operations).

I had problems with file access in sagemaker, but never related to dvc, it was an issue of how AWS handles their resources.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/5562
