### ISSUE TITLE
feat: allow user annotations in .dvc files

### ISSUE THREAD

**Issue by gvwilson** [iterative/dvc#7231]
We would like to be able to associate arbitrary tags and key=value annotations with particular versions of DVC-managed files. For example, if `a.csv` and `b.csv` are managed by DVC:

```
$ dvc note set -K color -V green a.csv

$ dvc note set -K size -V medium a.csv

$ dvc note list a.csv
color: green
size: medium

$ dvc note set -K color -V blue b.csv

$ dvc note find -K color *.csv
a.csv: green
b.csv: blue

$ dvc note remove -K color a.csv

$ dvc note find -K color *.csv
b.csv: blue
```

This can be implemented by adding a `notes` section under the `meta` key in the `.dvc` file without affecting any existing functionality. While it wouldn't necessarily be part of DVC, we are excited by the possibility of having a post-commit hook in Git that constructs a search index from these tags and annotations on every commit.

**Comment by efiop** [comment]
Hi @gvwilson

`meta` is meant for misc metadata, that is not recognized as a first class citizen by dvc, it is not suitable for notes. In your description you note that these notes are not really notes, but tags and annotations that have a higher level use-case. Could you elaborate on the scenario you are trying to solve?

**Comment by gvwilson** [comment]
Hi @efiop - thanks for the quick feedback. We're currently using a home-grown solution for large file management; DVC does everything our tool does (and a lot more) _except_ for allowing users to annotate particular revisions of large data files. Right now they create two types of annotations:

- Simple tags, which are keys without values. For example, they might mark a particular file as "luciferase", meaning it came from a luciferase experiment.
- Key/value pairs, such as "scenario=green".

A few requirements:

1. We don't know in advance what tags or key/value pairs they're going to create - every team evolves its own vocabulary to meet the needs of particular families of experiments.
2. They frequently search files by tag, or look for files that have particular values associated with particular keys.
3. The tags and key/value pairs associated with a file can change over time, and need to be associated with specific versions of the associated data files. Right now we have people copying and pasting Git hashes to track this; if we can put the info in `.dvc` files that are committed to Git, it'll make things a lot easier.

Things we *don't* do right now, but have come up in conversation:

1. Keys with multiple values in a single file (i.e., a list of values associated with a key).
2. Links between files, i.e., File A has an annotation saying, "More interesting than File B", but "File B" is explicit rather than being buried in the note.

The current prototype #7232 put notes under the `meta` key because putting them at the top level seemed to break YAML schema validation. If adding top-level sections to `.dvc` files in ways that alter the schema is OK, I'm happy to revise the PR.

**Comment by efiop** [comment]
@gvwilson Sorry for the delay. The interesting thing is that we've been talking about supporting such labeling/notes/etc for some time (and that's kinda where `desc` and `meta` came from), but we didn't want to put any constrains on the format. In your case, it looks like you could simply put both notes and/or labels files besides the artifact that you want to attach it to into one common directory and then track it with dvc, which will produce 1 effective hash for artifacts and labels/notes combined.

**Comment by gvwilson** [comment]
Hi @efiop - no need for apologies, I'm very grateful for the feedback.

1. My first prototype used separate files for annotations beside the data file and `.dvc` file. User response was negative: a second file and tool to manage datasets is already a bit confusing ("when do I DVC and when do I Git?") but a third is simply confusing ("When do I `git`, when do I `dvc`, when do I `dgn`?").
2. Wasn't aware of the `desc` tag: I'll update the PR to put notes there. And you please point me at the full description of the YAML schema? Apologies for having missed it.
3. Returning to an earlier thread, if notes is premature, would you consider adding a plugin mechanism to DVC so that groups like ours can extend it without affecting the core and other users? The DVC source is very cleanly structured; allowing us to connect a new sub-command to the CLI and implement the action dynamically looks like it would be straightforward. Happy to chat...

**Comment by gvwilson** [comment]
Any further thoughts from the dev team on whether this one's of interest?
