### ISSUE TITLE
exp show: sort commits

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7263]
It's currently only possible to sort experiments within their parent commit, but it can also be useful to sort the actual commits, tags, or branches themselves. It would be nice to have some option like `--sort-commits`, `--sort-parents`, or similar.

See https://discuss.dvc.org/t/dvc-exp-show-experiment-not-showing-wrong-position/1019/1

**Comment by dberenbaum** [comment]
@shcheklein @tapadipti What do you think about this for Studio? Have you seen any requests to sort across branches?

**Comment by shcheklein** [comment]
The only slightly related one is this one https://github.com/iterative/studio-support/issues/44 . That's all that comes to my mind, @dberenbaum . May be Tapa can remember more.

btw, @mattseddon I think we decided in VS Code to sort actual parents (and keep checkpoints as-is) or what is the current mode?

**Comment by mattseddon** [comment]
> btw, @mattseddon I think we decided in VS Code to sort actual parents (and keep checkpoints as-is) or what is the current mode?

That's correct, we only sort experiments and leave their checkpoints alone.

**Comment by dberenbaum** [comment]
Sorry for being unclear, this is not related to checkpoints. By parent commit, I mean the branch, tag, or regular Git commit from which the experiment originated.

For example:

```  ───────────────────────────────────────────────────────────────────────────────────────
  Experiment                Created        dvclive.json:epoch   dvclive.json:mult   step
 ───────────────────────────────────────────────────────────────────────────────────────
  workspace                 -                              31                  31      -
  exp                       Feb 09, 2021                    1                   -      0
  main                      Mar 10, 2021                    -                   -      -
  │ ╓ 3d73342 [exp-eae92]   Oct 25, 2021                   13                  13     10
  │ ╟ 61fd39f (e00e3e3)     Oct 25, 2021                   12                  12     10
  │ ╓ 8a03e76 [exp-6c0d3]   Oct 25, 2021                   11                  11     10
  ├─╨ 9fd6c44               Oct 25, 2021                   10                  10     10
  │ ╓ e00e3e3 [exp-9d3f2]   Oct 25, 2021                    4                   4      0
  │ ╟ 3ed4eaa               Oct 25, 2021                    3                   3      0
  │ ╟ 56a23a6               Oct 25, 2021                    2                   2      0
  ├─╨ 391628f               Oct 25, 2021                    1                   1      0
  mynewexp                  Feb 09, 2021                    3                   -    100 
 ───────────────────────────────────────────────────────────────────────────────────────
```

Not the best example, but this is about sorting between `exp`, `main`, and `mynewexp`. Not sure if that's relevant for VS Code, or if you always show only experiments based on the current workspace.

**Comment by mattseddon** [comment]
Right now we only show experiments for the current workspace. This would be a future question/problem for us, not immediate 👍🏻 .

**Comment by tapadipti** [comment]
>The only slightly related one is this one iterative/studio-support#44 . That's all that comes to my mind, @dberenbaum . May be Tapa can remember more.

There's another one related to comparing results across branches (https://github.com/iterative/cse/issues/17). But this also isn't about sorting across branches.

**Comment by dberenbaum** [comment]
Not in current plans
