### ISSUE TITLE
Reading Credential data for GCP

### ISSUE THREAD

**Issue by dacbd** [iterative/dvc#7279]
With a `gs://` remote DVC will look at the env var of `GOOGLE_APPLICATION_CREDENTIALS` for a path to the JSON file for a service account but doesn't accept `GOOGLE_APPLICATION_CREDENTIALS_DATA` which contains the actual JSON

**Comment by daavoo** [comment]
Is `GOOGLE_APPLICATION_CREDENTIALS_DATA` supported by Google Cloud API ?

**Comment by daavoo** [comment]
For the record, we rely on https://github.com/fsspec/gcsfs for handling `gs` remotes

**Comment by daavoo** [comment]
Closing it for now. @dacbd feel free to reopen if you would like to request that feature

**Comment by bmabir17-asj** [comment]
@dacbd as CML supports `GOOGLE_APPLICATION_CREDENTIALS_DATA` but DVC does not. How do you suggest we store service account credentials/keys and feed it into DVC?

**Comment by dacbd** [comment]
> @dacbd as CML supports `GOOGLE_APPLICATION_CREDENTIALS_DATA` but DVC does not. How do you suggest we store service account credentials/keys and feed it into DVC?

@bmabir17-asj in general or from cicd / a cml runner instance? 

CML supports reading the JSON key file where `GOOGLE_APPLICATION_CREDENTIALS` is a path to that file, which DVC supports.

If you are running DVC cmds from a CML made instance within something like github actions I would do this: `--cloud-permission-set=dvc-sa@[gcp-project].iam.gserviceaccount.com,scopes=storage-rw` (where this service account has permissions to the gs bucket)

I have been passively improving the documentation to make this clearer. Feel free to the reach on if you have anymore questions [discord](https://cml.dev/chat)

**Comment by bmabir17-asj** [comment]
@dacbd yes, thank you for the info. I did not find anything regarding this in the documentation except in this [issue](https://github.com/iterative/cml/issues/894#issuecomment-1043309810) .
If possible please add this to the documentation as well.

**Comment by dacbd** [comment]
@bmabir17-asj indeed you are correct, I have my "in progress" update here: https://github.com/iterative/cml.dev/pull/208 but I put a pause on working on it for "reasons" 😶‍🌫️ but intend would like to have something helpful there by the end of this week!
