### ISSUE TITLE
'None' does not contain DVC directory

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#7281]
```console
cd "$(mktemp -d)"
dvc add foo  # or any other command
```

**Comment by dberenbaum** [comment]
@skshetry Are preparing a PR for this? I'm not clear what the issue or expected behavior is.

**Comment by efiop** [comment]
This is a regression from https://github.com/iterative/dvc/pull/7214 , most likely. The expected behaviour is to complain that you are not insde of the dvc repository right now.
