### ISSUE TITLE
`exp show/list --num`: rename metavar from `<num>` to `<int>`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#7314]
..."num" is not informative since the option has the same name. "int" is a type hint at least, which some time ago we agreed to use for metavars AFAIR. Either way it should be pretty obvious here but suggesting as a UX improvement.

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc/pull/7204#discussion_r794192834_

p.s. this will apply to other `dvc exp` commands soon (not just `exp show`).

**Comment by skshetry** [comment]
> ..."num" is not informative since the option has the same name

I am not sure if I agree with this. We probably want to be consistent with other flags that require numbers too.
I think `number` is more fundamental/basic than an integer. And, `number` is a terminology used for counting.

> which some time ago we agreed to use for metavars AFAIR

Do you have a reference to this? Also, are you aware of any CLI programs that use `int` instead? Looking at Git, it uses `<number>`.
```
git log --help
...
-<number>, -n <number>, --max-count=<number>
```

**Comment by jorgeorpinel** [comment]
> We probably want to be consistent with other flags that require numbers too.

Agree. Any change here would have to apply to any other inconsistent metavars we have, if any.

> number is more fundamental/basic than an integer...
Looking at Git, it uses <number>.

Yes although not a very specific type. `<number>` would also be better although still repetitive... But given that `-n` is very common I wouldn't suggest changing the `--num` option name.
BTW Git is not a good CLI reference TBH.

> Do you have a reference to this?

Probably somewhere in https://github.com/iterative/dvc/pull/3626. I realize this is very old, maybe standards have changed since.

**Comment by jorgeorpinel** [comment]
> number is a terminology used for counting

On second thought maybe changing `--num` (`-n`) for `--count` (`-c`) could work too. At least in `exp show/list`

**Comment by pmrowla** [comment]
We use `<number>` elsewhere in DVC (like with `-j/--jobs`), so we could just change it to that.

I don't think we should use `-c/--count`, because  `-c` is commonly used for `--cloud` in a lot of DVC commands. I also would prefer not using `-C`, because IMO the lowercase/uppercase shortcuts get too confusing in a lot of cases.

**Comment by jorgeorpinel** [comment]
> We use <number> elsewhere in DVC (like with -j/--jobs), so we could just change it to that.

I agree. Also suggested in https://github.com/iterative/dvc/pull/7245#pullrequestreview-870006159 (for consistency with `git log -n`
