### ISSUE TITLE
Move: Make it possible and cosistent to move files safely without checking them out first

### ISSUE THREAD

**Issue by mistermult** [iterative/dvc#7318]
# Current situation
Assume that the file `video121.mpeg` is tracked by `video121.mpeg.dvc`. If one wants to move it to folder `subdir` it depends on whether `video121.mpeg` is checked out.

1) If `video121.mpeg` is checked out, then `dvc move video121.mpeg subdir/` must be used to do it safely.
2) If `video121.mpeg` is not checked out, then `mv video121.mpeg.dvc subdir/` can be used. `dvc move video121.mpeg.dvc subdir/` does not work.

# Problem
- If one wants to use 1), one has to first download and check out the file. This might be a quite costly operations when many large files are involved.
- If `video121.mpeg` is checked out, and one does `mv video121.mpeg.dvc subdir/` then this is unsafe, as it does not move `video121.mpeg`. This can happen if one thinks that the files are not checked out yet.
- So to make not any mistakes by accident, one should use `dvc move` all the time. Do do that one has to check out the files. However, if there are many large files it takes a lot of time to download them or might not be possible if the repo is larger than the disk of the PC.
- That `mv video121.mpeg.dvc subdir/` is safe in case 2 is not documented (as far as I know).

# Solution
1) Add documentation on how to move files for both cases (checked-out/non-checked-out).
2) Make `dvc move` work on `.dvc` files. 

Idea: Accept `.dvc` files. So `dvc move video121.mpeg.dvc subdir/` is possible. Moving a dvc file means just moving its outputs (for simplicity only with single output?). It would do (pseudo-code):
```python
inputfile = 'video121.mpeg.dvc'
target = 'subdir'
if is_dvcfile(inputfile) and number_of_tracked_files(inputfile) == 1 and exists_on_fs(get_tracked_file(inputfile)):
    tracked_file =  get_tracked_file(inputfile) # would be video121.mpeg
    perform(f'dvc move {tracked_file} {target}')
elif is_dvcfile(inputfile) and number_of_tracked_files(inputfile) == 1 and not exists_on_fs(get_tracked_file(inputfile)):
    if not exists_on_fs(os.path.join(target, inputfile)):
        perform(f'mv {inputfile} {target}')
    else:
        raise Exception(f'{os.path.join(target, inputfile)} already exists')
else:
   # Do as in past
```

# Applications
- moving files safely in any case
- supporting the use case of moving tracked files without downloading them all, e.g. a collection of many large video files

**Comment by karajan1001** [comment]
Great.
I had to apologize that I didn't realize that `dvc move` only works one data file has an implicit requirement on the status of data files. This is definitely a flaw in the design.

**Comment by dberenbaum** [comment]
> 1. Add documentation on how to move files for both cases (checked-out/non-checked-out).

Opened https://github.com/iterative/dvc.org/issues/3354 for this.
