### ISSUE TITLE
`--out`: inconsistent behavior

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#7344]
I noticed that for `add` and `import`, `-o` does NOT create the given directory path (if inexistent). But `get -o` does.

Is there a reason for that? Thanks

**Comment by eggqq007** [comment]
mkdir cctv
git init repo
cd repo
dvc init
dvc add ../cctv -o cctv

(.env) sherlock@ubuntu:/tmp/gzhenyu/new/repo$ ls 
cctv  cctv.dvc


It works on my machine.


(.env) sherlock@ubuntu:/tmp/gzhenyu/new/repo$ dvc doctor
DVC version: 2.7.5.dev430+ge430693f 
---------------------------------
Platform: Python 3.8.10 on Linux-5.11.0-40-generic-x86_64-with-glibc2.29
Supports:
	azure (adlfs = 2022.2.0, knack = 0.8.2, azure-identity = 1.6.1),
	gdrive (pydrive2 = 1.9.4),
	gs (gcsfs = 2022.1.0),
	hdfs (fsspec = 2022.1.0, pyarrow = 5.0.0),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	s3 (s3fs = 2022.1.0, boto3 = 1.17.106),
	ssh (sshfs = 2021.11.2),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.4),
	webdavs (webdav4 = 0.9.4)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda5
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/sda5
Repo: dvc, git
