### ISSUE TITLE
add / commit: overwrites per-output remote

### ISSUE THREAD

**Issue by wesleyjellis** [iterative/dvc#7356]
# Bug Report

## Description

When a .dvc has had a value set for `remote:` (under `out:`) and the actual file content is changed, then `dvc add` and `dvc commit` remove the `remote` value

### Reproduce

 1. `dvc remote add --default storage_2 /tmp/dvcstore_alt`
 2. Add a file like `cp ~/Downloads/example.tsv ./example.tsv`
 3. `dvc add example.tsv`
 4. Edit `example.tsv.dvc` to include a `remote: storage_2

```
outs:
- md5: 0f473951d64d6dd73e07965da6b2758b
  size: 4393
  path: example.tsv
  remote: storage_2

```

 5. git commit and dvc push
 6. Edit `example.tsv`
 7. `dvc add example.tsv`
 8. See that `example.tsv.dvc` has removed the `remote:` value

```diff
diff --git a/example.tsv.dvc b/example.tsv.dvc
index c39daf5..70654ae 100644
--- a/example.tsv.dvc
+++ b/example.tsv.dvc
@@ -1,5 +1,4 @@
 outs:
-- md5: 0f473951d64d6dd73e07965da6b2758b
-  size: 4393
+- md5: f18353455728c7d54aafac4d6087cd9f
+  size: 4511
   path: example.tsv
-  remote: storage_2

```

### Expected

add and commit should leave `remote` if present in a .dvc file

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.3 (brew)
---------------------------------
Platform: Python 3.9.10 on macOS-11.6.2-x86_64-i386-64bit
Supports:
	azure (adlfs = 2021.10.0, knack = 0.9.0, azure-identity = 1.7.1),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2021.11.1),
	webhdfs (fsspec = 2021.11.1),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2021.11.1, boto3 = 1.19.8),
	ssh (sshfs = 2021.11.2),
	webdav (webdav4 = 0.9.3),
	webdavs (webdav4 = 0.9.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: local, local
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

```

**Additional Information (if any):**

This feature looks relatively new/experimental from https://github.com/iterative/dvc/pull/6486 although it's in the docs at https://dvc.org/doc/user-guide/project-structure/dvc-files#output-entries

**Comment by eggqq007** [comment]
not only commit/add, some action like 'dvc move' would not count desc/remote in as well.  It seems we cannot add remote and desc into dvc file currently. 
@skshetry  how about updating the doc in  https://dvc.org/doc/user-guide/project-structure/dvc-files#output-entries

**Comment by skshetry** [comment]
We try to preserve the data for meta and desc here, but we did not do that for `remote`.

https://github.com/iterative/dvc/blob/30d6839a5f471fb02a7a2dcbd6a6616b71277762/dvc/stage/__init__.py#L116-L119

The `remote` can be accessed from `out.remote`, and can be set to the new stage that we are creating, as we do for `desc`.

---

For the `move`, it's going to be a bit more complicated, but involves the same thing that we do above.

**Comment by SamKnightGit** [comment]
Hey DVC team! Wondering whether there is an ETA on this issue or if not, whether I can take a stab at a fix? I am working with a setup where I require per-dvc-file remote outputs and this bug is making it infeasible to update (and push) ml model files to dvc remotes when conducting model training on Gitlab runners.
