### ISSUE TITLE
dvc pull exp giving error when pull from another git client

### ISSUE THREAD

**Issue by prince3103** [iterative/dvc#7361]
# Bug Report

## Issue name

dvc exp pull origin <experiment name>: unable to pull experiment from origin

## Description

I am unable to pull dvc experiment which was pushed by another git client.

### Expected

Experiment should be pulled to my git project.

### Environment information
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
agate                     1.6.1              pyhd8ed1ab_0    conda-forge
agate-dbf                 0.2.2              pyhd8ed1ab_0    conda-forge
agate-excel               0.2.3                      py_0    conda-forge
agate-sql                 0.5.8              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1            py39h3811e60_0    conda-forge
aiohttp-retry             2.4.6              pyhd8ed1ab_1    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
asyncssh                  2.8.1              pyhd8ed1ab_0    conda-forge
atpublic                  3.0.1              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
black                     22.1.0             pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py39h3811e60_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
catalogue                 2.0.6            py39hf3d152e_1    conda-forge
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.14.6           py39he32792d_0    conda-forge
charset-normalizer        2.0.11             pyhd8ed1ab_0    conda-forge
click                     8.0.3            py39hf3d152e_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
cryptography              36.0.1           py39h95dcef6_0    conda-forge
csvkit                    1.0.6              pyhd8ed1ab_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cymem                     2.0.6            py39he80948d_2    conda-forge
cython-blis               0.7.5            py39hce5d2b2_1    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dbfread                   2.0.7                      py_0    conda-forge
debugpy                   1.5.1            py39he80948d_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
dictdiffer                0.9.0              pyhd8ed1ab_0    conda-forge
diskcache                 5.4.0              pyhd8ed1ab_0    conda-forge
distro                    1.6.0              pyhd8ed1ab_0    conda-forge
dpath                     2.0.5            py39hf3d152e_1    conda-forge
dulwich                   0.20.32          py39h3811e60_0    conda-forge
dvc                       2.9.3            py39hf3d152e_0    conda-forge
dvc-gdrive                2.9.3            py39hf3d152e_0    conda-forge
elasticsearch             7.9.1              pyh9f0ad1d_0    conda-forge
en-core-web-sm            3.1.0                    pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
executing                 0.8.2              pyhd8ed1ab_0    conda-forge
flatten-dict              0.4.2              pyhd8ed1ab_1    conda-forge
flufl.lock                7.0                pyhd8ed1ab_0    conda-forge
fonttools                 4.29.1           py39h3811e60_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
frozenlist                1.3.0            py39h3811e60_0    conda-forge
fsspec                    2022.1.0           pyhd8ed1ab_0    conda-forge
ftfy                      5.5.1                      py_0    conda-forge
funcy                     1.17               pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39hf3d152e_4    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.26             pyhd8ed1ab_0    conda-forge
google-api-core           2.4.0              pyhd8ed1ab_0    conda-forge
google-api-python-client  2.36.0             pyhd8ed1ab_0    conda-forge
google-auth               2.6.0              pyh6c4a22f_0    conda-forge
google-auth-httplib2      0.1.0              pyhd8ed1ab_0    conda-forge
googleapis-common-protos  1.54.0           py39hf3d152e_0    conda-forge
grandalf                  0.6                        py_0    conda-forge
greenlet                  1.1.2            py39he80948d_1    conda-forge
httplib2                  0.20.2             pyhd8ed1ab_1    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
ipykernel                 6.7.0            py39hef51801_0    conda-forge
ipython                   8.0.1            py39hf3d152e_0    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1           py39hf3d152e_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py39hf3d152e_1    conda-forge
kiwisolver                1.3.2            py39h1a9c180_1    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
leather                   0.3.3                      py_0    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgfortran-ng            11.2.0              h69a702a_12    conda-forge
libgfortran5              11.2.0              h5c6108e_12    conda-forge
libgit2                   1.3.0                hee63804_1    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.19.4               h780b84a_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mailchecker               4.1.11             pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py39h3811e60_1    conda-forge
matplotlib-base           3.5.1            py39h2fa2bec_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
multidict                 6.0.2            py39h3811e60_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
murmurhash                1.0.6            py39he80948d_2    conda-forge
mypy_extensions           0.4.3            py39hf3d152e_4    conda-forge
nanotime                  0.5.2                      py_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
numpy                     1.22.1           py39h91f2184_0    conda-forge
oauth2client              4.1.3                      py_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.0            py39hde0f152_0    conda-forge
parsedatetime             2.6                pyh9f0ad1d_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathlib2                  2.3.6            py39hf3d152e_1    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pathy                     0.6.1              pyhd8ed1ab_0    conda-forge
pcre2                     10.37                h032f7d1_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
phonenumbers              8.12.42            pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py39ha612740_0    conda-forge
pip                       22.0.2             pyhd8ed1ab_0    conda-forge
platformdirs              2.3.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
preshed                   3.0.6            py39he80948d_1    conda-forge
prompt-toolkit            3.0.26             pyha770c72_0    conda-forge
protobuf                  3.19.4           py39he80948d_0    conda-forge
psutil                    5.9.0            py39h3811e60_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.8.2            py39h3811e60_2    conda-forge
pydot                     1.2.4                      py_0    conda-forge
pydrive2                  1.10.0             pyhd8ed1ab_1    conda-forge
pygit2                    1.7.2            py39h3811e60_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pygtrie                   2.4.2              pyhd3deb0d_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1            py39hf3d152e_4    conda-forge
python                    3.9.5           h49503c6_0_cpython    conda-forge
python-benedict           0.24.3             pyhd8ed1ab_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fsutil             0.6.0              pyhd8ed1ab_0    conda-forge
python-gssapi             1.7.2            py39hbb49be9_1    conda-forge
python-slugify            5.0.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytimeparse               1.1.8                      py_0    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h3811e60_3    conda-forge
pyzmq                     22.3.0           py39h37b5a0c_1    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
rich                      11.1.0             pyhd8ed1ab_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.19          py39h3811e60_0    conda-forge
ruamel.yaml.clib          0.2.6            py39h3811e60_0    conda-forge
scipy                     1.7.3            py39hee8e79c_0    conda-forge
scmrepo                   0.0.7              pyhd8ed1ab_0    conda-forge
setuptools                60.6.0           py39hf3d152e_0    conda-forge
shellingham               1.4.0              pyh44b312d_0    conda-forge
shortuuid                 1.0.8            py39hf3d152e_0    conda-forge
shtab                     1.5.3              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smart_open                5.2.1              pyhd8ed1ab_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
spacy                     3.1.3            py39h5472131_0    conda-forge
spacy-legacy              3.0.8              pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.31           py39h3811e60_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
srsly                     2.4.2            py39he80948d_1    conda-forge
stack_data                0.1.4              pyhd8ed1ab_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
thinc                     8.0.13           py39h5472131_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.0              pyhd8ed1ab_1    conda-forge
tornado                   6.1              py39h3811e60_2    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.2            py39h3811e60_0    conda-forge
typer                     0.4.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.0.1                hd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
unicodedata2              14.0.0           py39h3811e60_0    conda-forge
unidecode                 1.3.2              pyhd8ed1ab_0    conda-forge
uritemplate               4.1.1              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
voluptuous                0.12.2             pyhd8ed1ab_1    conda-forge
wasabi                    0.9.0              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.7.2            py39h3811e60_1    conda-forge
zc.lockfile               2.0                        py_0    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
DVC version: 2.9.3 (conda)
---------------------------------
Platform: Python 3.9.5 on Linux-5.13.0-28-generic-x86_64-with-glibc2.31
Supports:
	gdrive (pydrive2 = 1.10.0),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

**Additional Information (if any):**
ERROR: unexpected error - Length of pkt read 4000 does not match length prefix ffef

**Comment by karajan1001** [comment]
Excuse me, @prince3103  could you please provide some more detailed logs from 
```bash
dvc exp pull origin -vv
```

**Comment by pmrowla** [comment]
Also, could you please explain what you mean by 
> pushed by another git client.

Do you mean it was pushed with `dvc exp push` from a different machine? Or do you mean that you manually pushed the git refs yourself using a separate git client (and not `dvc exp push`)?

**Comment by prince3103** [comment]
> Excuse me, @prince3103 could you please provide some more detailed logs from
> 
> ```shell
> dvc exp pull origin -vv
> ```

Hi @karajan1001,
Below are detailed dvc logs:

2022-02-09 10:39:41,294 TRACE: Namespace(cprofile=False, yappi=False, cprofile_dump=None, pdb=False, instrument=False, instrument_open=False, quiet=0, verbose=2, version=None, cd='.', cmd='pull', force=False, pull_cache=True, dvc_remote=None, jobs=None, run_cache=False, git_remote='origin', experiment='exp005', func=<class 'dvc.command.experiments.pull.CmdExperimentsPull'>)
2022-02-09 10:39:41,370 DEBUG: Adding '/home/princesethi/Desktop/office_work/DVC/dvc_poc_tst/dvc-mlops/.dvc/config.local' to gitignore file.
2022-02-09 10:39:41,372 DEBUG: Adding '/home/princesethi/Desktop/office_work/DVC/dvc_poc_tst/dvc-mlops/.dvc/tmp' to gitignore file.
2022-02-09 10:39:41,372 DEBUG: Adding '/home/princesethi/Desktop/office_work/DVC/dvc_poc_tst/dvc-mlops/.dvc/cache' to gitignore file.
2022-02-09 10:39:44,279 DEBUG: git pull experiment 'origin' -> 'refs/exps/f9/17a3d05f35c961f48298b0328994f2423b85a9/exp005:refs/exps/f9/17a3d05f35c961f48298b0328994f2423b85a9/exp005'
2022-02-09 10:39:47,771 ERROR: unexpected error - Length of pkt read 4000 does not match length prefix fff0                         
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/command/experiments/pull.py", line 13, in run
    self.repo.experiments.pull(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/repo/experiments/__init__.py", line 827, in pull
    return pull(self.repo, *args, **kwargs)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/repo/scm_context.py", line 152, in run
    return method(repo, *args, **kw)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/repo/experiments/pull.py", line 38, in pull
    repo.scm.fetch_refspecs(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/scmrepo/git/__init__.py", line 253, in _backend_func
    return func(*args, **kwargs)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 529, in fetch_refspecs
    fetch_result = client.fetch(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/client.py", line 601, in fetch
    result = self.fetch_pack(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/client.py", line 1125, in fetch_pack
    self._handle_upload_pack_tail(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/client.py", line 911, in _handle_upload_pack_tail
    self._read_side_band64k_data(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/client.py", line 665, in _read_side_band64k_data
    for pkt in proto.read_pkt_seq():
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/protocol.py", line 290, in read_pkt_seq
    pkt = self.read_pkt_line()
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/protocol.py", line 245, in read_pkt_line
    raise GitProtocolError(
dulwich.errors.GitProtocolError: Length of pkt read 4000 does not match length prefix fff0
------------------------------------------------------------
2022-02-09 10:39:47,849 DEBUG: Adding '/home/princesethi/Desktop/office_work/DVC/dvc_poc_tst/dvc-mlops/.dvc/config.local' to gitignore file.
2022-02-09 10:39:47,850 DEBUG: Adding '/home/princesethi/Desktop/office_work/DVC/dvc_poc_tst/dvc-mlops/.dvc/tmp' to gitignore file.
2022-02-09 10:39:47,850 DEBUG: Adding '/home/princesethi/Desktop/office_work/DVC/dvc_poc_tst/dvc-mlops/.dvc/cache' to gitignore file.
2022-02-09 10:39:47,851 DEBUG: [Errno 95] no more link types left to try out: [Errno 95] 'reflink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>: [Errno 95] Operation not supported
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/command/experiments/pull.py", line 13, in run
    self.repo.experiments.pull(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/repo/experiments/__init__.py", line 827, in pull
    return pull(self.repo, *args, **kwargs)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/repo/scm_context.py", line 152, in run
    return method(repo, *args, **kw)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/repo/experiments/pull.py", line 38, in pull
    repo.scm.fetch_refspecs(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/scmrepo/git/__init__.py", line 253, in _backend_func
    return func(*args, **kwargs)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 529, in fetch_refspecs
    fetch_result = client.fetch(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/client.py", line 601, in fetch
    result = self.fetch_pack(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/client.py", line 1125, in fetch_pack
    self._handle_upload_pack_tail(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/client.py", line 911, in _handle_upload_pack_tail
    self._read_side_band64k_data(
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/client.py", line 665, in _read_side_band64k_data
    for pkt in proto.read_pkt_seq():
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/protocol.py", line 290, in read_pkt_seq
    pkt = self.read_pkt_line()
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dulwich/protocol.py", line 245, in read_pkt_line
    raise GitProtocolError(
dulwich.errors.GitProtocolError: Length of pkt read 4000 does not match length prefix fff0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/fs/utils.py", line 28, in _link
    func(from_path, to_path)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/fs/local.py", line 148, in reflink
    System.reflink(from_info, to_info)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/system.py", line 112, in reflink
    System._reflink_linux(source, link_name)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/system.py", line 96, in _reflink_linux
    fcntl.ioctl(d.fileno(), FICLONE, s.fileno())
OSError: [Errno 95] Operation not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/fs/utils.py", line 69, in _try_links
    return _link(link, from_fs, from_path, to_fs, to_path)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/fs/utils.py", line 32, in _link
    raise OSError(
OSError: [Errno 95] 'reflink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/fs/utils.py", line 124, in _test_link
    _try_links([link], from_fs, from_file, to_fs, to_file)
  File "/home/princesethi/anaconda3/envs/dvc_spacy/lib/python3.9/site-packages/dvc/fs/utils.py", line 77, in _try_links
    raise OSError(
OSError: [Errno 95] no more link types left to try out
------------------------------------------------------------
2022-02-09 10:39:47,851 DEBUG: Removing '/home/princesethi/Desktop/office_work/DVC/dvc_poc_tst/.2x2DpDavPo3d8VLRcATJmK.tmp'
2022-02-09 10:39:47,851 DEBUG: Removing '/home/princesethi/Desktop/office_work/DVC/dvc_poc_tst/.2x2DpDavPo3d8VLRcATJmK.tmp'
2022-02-09 10:39:47,851 DEBUG: Removing '/home/princesethi/Desktop/office_work/DVC/dvc_poc_tst/.2x2DpDavPo3d8VLRcATJmK.tmp'
2022-02-09 10:39:47,851 DEBUG: Removing '/home/princesethi/Desktop/office_work/DVC/dvc_poc_tst/dvc-mlops/.dvc/cache/.UVDeUhGzzJ8CZ4U44K2Ub2.tmp'
2022-02-09 10:39:47,856 DEBUG: Version info for developers:
DVC version: 2.9.3 (conda)
---------------------------------
Platform: Python 3.9.5 on Linux-5.13.0-28-generic-x86_64-with-glibc2.31
Supports:
	gdrive (pydrive2 = 1.10.0),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-02-09 10:39:47,857 DEBUG: Analytics is enabled.
2022-02-09 10:39:47,893 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpvm67w4jb']'
2022-02-09 10:39:47,894 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpvm67w4jb']'

**Comment by prince3103** [comment]
> Also, could you please explain what you mean by
> 
> > pushed by another git client.
> 
> Do you mean it was pushed with `dvc exp push` from a different machine? Or do you mean that you manually pushed the git refs yourself using a separate git client (and not `dvc exp push`)?

Hi,
By statement "pushed by another git client", I mean that it was pushed with `dvc exp push` from a different machine. Also I created dvc.yaml file using spacy's project.yml file

**Comment by karajan1001** [comment]
https://github.com/jelmer/dulwich/issues/473 might helpful?

Have you tried manually pull something from the remote?

**Comment by pmrowla** [comment]
Another user from the support email is encountering this issue intermittently when pulling from github, we may need to just submit an upstream patch that allows for retries when a network request fails.

**Comment by daavoo** [comment]
> Another user from the support email is encountering this issue intermittently when pulling from github, we may need to just submit an upstream patch that allows for retries when a network request fails.

I have been also randomly encountered the same issue when pulling experiments from https://github.com/iterative/example-dvc-experiments but only with SSH remote. Switched to HTTPs remote and the random failures stopped.

**Comment by dberenbaum** [comment]
@daavoo Taken from https://github.com/jelmer/dulwich/issues/473#issuecomment-270375222:

> Do you see anything unusual in e.g. a TCP dump of this request with C git versus Dulwich?

**Comment by pmrowla** [comment]
Installing `scmrepo==0.0.18` should resolve this issue (you will get a pip warning about scmrepo not matching the version required by DVC, this will be updated in the next DVC release)

**Comment by karotchykau** [comment]
Had the same issue with `scmrepo==0.0.16`. Couldn't execute any remote `dvc exp` command. Seems to be fixed after updating to `dvc==2.10.2` where it has `scmrepo==0.0.22` specified in `setup.cfg`.

> this will be updated in the next DVC release

Not an issue anymore?
