### ISSUE TITLE
checkout/pull: dvcignored contents are removed on checkout

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#7374]
```bash
cd "$(mktemp -d)"
dvc init --no-scm
dvc remote add -d local "$(mktemp -d)"
mkdir -p data/processed
echo "foo" > data/foo
echo "bar" > data/processed/bar
echo "data/processed/" >> .dvcignore
dvc add data
dvc push
rm -rf .dvc/cache data/foo
dvc pull | tee
```

This is a regression introduced in b349b39d6266a28705b03b1b06e5c0cf98a9080d (see #5812), which was released in [2.2.0](https://github.com/iterative/dvc/releases/tag/2.2.0) and is present since then.

**Comment by skshetry** [comment]
#4344 and this issue are related to staging in dvc-data.

**Comment by karajan1001** [comment]
PR #7963 partly solve this problem (for the `pull` and `checkout` after a `ststus` ). To completely close this required some following work on `dvc_data` side.

**Comment by daavoo** [comment]
>  To completely close this required some following work on dvc_data side.

@karajan1001 do you recall what is missing?

**Comment by karajan1001** [comment]
> > To completely close this required some following work on dvc_data side.
> 
> @karajan1001 do you recall what is missing?

Sorry, I forgot about it.

**Comment by skshetry** [comment]
Looks like this has been fixed at some point. Closing.
