### ISSUE TITLE
status: doesn't handle foreach stages

### ISSUE THREAD

**Issue by nkruglikov** [iterative/dvc#7385]
# Bug Report

## Description

`dvc status stage_name` can't find a stage if it contains a `foreach` clause. It works only with stage names like `stage_name@first`. This is in contrast with `dvc repro stage_name` which handles such stages without problem.

The problem also occurs with `push` and possibly with other commands.

### Reproduce

A minimal example of the problem:
```console
$ cat dvc.yaml
stages:
  stage_name:
    foreach:
      - first
      - second
    do:
      cmd: echo ${item} > ${item}.txt
      outs:
        - ${item}.txt

$ dvc repro stage_name
Running stage 'stage_name@second':
> echo second > second.txt

Running stage 'stage_name@first':
> echo first > first.txt
Use `dvc push` to send your updates to remote storage.

$ dvc status stage_name
ERROR: 'stage_name' does not exist as an output or a stage name in 'dvc.yaml': Stage 'stage_name' not found inside 'dvc.yaml' file

$ dvc pull stage_name
Everything is up to date.
ERROR: failed to pull data from the cloud - 'stage_name' does not exist as an output or a stage name in 'dvc.yaml': Stage 'stage_name' not found inside 'dvc.yaml' file

$ dvc status stage_name@first
Data and pipelines are up to date.
```

### Expected

I would expected `dvc status stage_name` to limit status information to all sub-stages of a stage. I would expected the same from `dvc pull`

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.9.10 on macOS-12.2-x86_64-i386-64bit
Supports:
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.0, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.0, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s2s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s2s1
Repo: dvc, git
```

**Comment by pmrowla** [comment]
This is the same underlying issue as https://github.com/iterative/dvc/issues/7323, will update the other issue to note that it also applies to `status` (and not just `commit`) and close this as a duplicate
