### ISSUE TITLE
exp: Add a "target" option to `dvc exp pull/push`

### ISSUE THREAD

**Issue by LoicEm** [iterative/dvc#7397]
I am working with DVC on a repository with several subfolders, each representing different projects.
The projects have similar pipelines (for the sake of simplicity, simply running `preprocessing.py` with different parameters for each project), but the data/use cases are very different.

My directory structure looks like this

```
computer-vision-training
├── computer_vision_training
│   ├── convert_labels.py
│   ├── project_1
│   │   ├── data/
│   │   ├── dvc.lock
│   │   ├── dvc.yaml
│   │   ├── params.yaml
│   │   ├── other_related_files
│   ├── project_2
│   │   ├── Same structure as project_1
│   ├── project_3
...
│   ├── preprocessing.py
├── poetry.lock
├── pyproject.toml
├── README.md
├── tests
```

I was excited about the newer `dvc exp` feature as it seemed to be a giant step moving towards being able to run a lot of experiments for a given project without getting lost in the code modification.

I ran locally `dvc exp run project_1/dvc.yaml` which had the output I expected, i.e getting data into `project_1/data` folder and updating `project_1/dvc.lock` file.

However, when trying to run  `dvc exp push origin my-experiment`, to my surprise it started to  __pull__ data from other projects before pushing the experiment. I guess this is because an experiment is not really related to a specific subfolder so it gets data from all `dvc.lock` files ?

Even though that was not a problem on my local machine as I was up-to-date on almost all projects, this means that for someone just pulling the repo this would take __hours__ (between 10 and 40 minutes per project, and we have a dozen of them). Additionnaly, this means that a data scientist only working on project_1 would be forced to push/pull data from other project folders everytime they are adding something related only to project_1 from the cache.

## My suggestion

Add a `targets` argument to `dvc exp pull/push` similar to what is already  done in `dvc exp run`, so that only data related to a specific project can be pulled

**Comment by pmrowla** [comment]
In the short term, the workaround would be to do push the DVC data for the experiment separately using regular `dvc push`:

``` 
exp push --no-cache origin my-experiment
dvc push project_1/data
```

**Comment by pmrowla** [comment]
> to my surprise it started to pull data from other projects before pushing the experiment.

If it was actually pulling data this sounds like a bug. But I think what probably happened here is that DVC is pulling directory information for other tracked dirs (but would not pull the actual file data).

As you noted, DVC considers the "experiment" to include the entire repo state, not necessarily just `project_1/data`. So if the other parts of your repo include dvc-tracked dirs that had not been pulled at all, DVC will still end up needing to fetch the lists of files that go into those dirs (but it would not fetch the actual files on `exp push`).
