### ISSUE TITLE
list: Invocation without path yields no output

### ISSUE THREAD

**Issue by JustinTervala** [iterative/dvc#7407]
# Bug Report

## Description

When invoking `dvc list` without a path argument, no output is returned. This only appears on the main branch.

### Reproduce

`dvc list https://github.com/iterative/dataset-registry` takes a very long time and yields no output on the main branch.

### Expected

There should be the same as on the most recent release
```
.gitignore
README.md
blog
dvc-course
fashion-mnist
get-started
images
mnist
tutorials
use-cases
```

### Environment information

```console
$ dvc doctor
DVC version: 2.9.4.dev107+g9b5ccb75
---------------------------------
Platform: Python 3.7.9 on Darwin-20.6.0-x86_64-i386-64bit
Supports:
	azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2022.1.0),
	hdfs (fsspec = 2022.1.0, pyarrow = 7.0.0),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	ssh (sshfs = 2021.11.2),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.4),
	webdavs (webdav4 = 0.9.4)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
```

**Additional Information (if any):**

This appears to have been introduced in the commit [dvcfs: detach from pipeline outputs](https://github.com/iterative/dvc/commit/cb584c6a53a4f3b5157de8715cf82c55de334c3b)

**Comment by efiop** [comment]
Hey @JustinTervala , thanks for the report! 🙏 

For the record: the functional bug is getting fixed in #7408 but performance has deeper roots and will be fixed after #7404
