### ISSUE TITLE
pull: Using `jobs>1` fails with `RuntimeError: Session is closed` in http remote

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#7421]
# Bug Report

## Description

Discord background: https://discord.com/channels/485586884165107732/485596304961962003/946721947599908905

User reports failures when using `jobs>1` with HTTP remote. 

Forcing `jobs=1` completes successfully.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.5 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.13.0-30-generic-x86_64-with-glibc2.29
Supports:
    azure (adlfs = 2021.10.0, knack = 0.8.2, azure-identity = 1.6.1),
    webhdfs (fsspec = 2022.1.0),
    http (aiohttp = 3.7.4, aiohttp-retry = 2.4.5),
    https (aiohttp = 3.7.4, aiohttp-retry = 2.4.5),
    ssh (sshfs = 2021.11.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p5
Caches: local
Remotes: https, http
Workspace directory: ext4 on /dev/nvme0n1p5
Repo: dvc, git
```

**Additional Information (if any):**

[Full traceback](https://github.com/iterative/dvc/files/8141064/message.1.txt)

**Comment by daavoo** [comment]
cc @dtrifiro Might be of relevance

**Comment by pmrowla** [comment]
Should note that this is with a custom HTTP backend, we probably need more information on how the user actually implemented the backend (it may not be a dvc issue)

**Comment by daavoo** [comment]
User tried https://github.com/iterative/dvc/pull/7412 but got same error

**Comment by atekoa** [comment]
This code was working with dvc 1, but I will try to upload the backend... I thinks it is related to the aiohttp-retry, but don't know...

**Comment by dtrifiro** [comment]
Hi @atekoa, are you still experiencing the issue?

**Comment by atekoa** [comment]
Yes, we have downloaded the DVC code to test the code and understand what might be going on.
We will upload the code shortly, we are waiting for the OK from the bosses to avoid problems.

**Comment by palenge** [comment]
Hi everyone, thanks for helping us.

testing a little bit about this issue we found out that works perfectly with job=1 . When you use the default Job value it gets a random error "session closed" and when this happens the rest of the files that needs to be downloaded gets the same error (the server stops receiving request from DVC),

the folders are 10 dvc folders with 400 files each.

We are using a windows machine where its running the custom http server and the DVC pull request

**Comment by dtrifiro** [comment]
Hi @palenge would you mind giving a try to [this PR](https://github.com/iterative/dvc/pull/7460) (https://github.com/iterative/dvc/pull/7460)?

**Comment by palenge** [comment]
Its working perfect with that PR.

I'm trying it a few more times to be sure that everything its working and to be honest it looks promising. Thank you guys!

**Comment by daavoo** [comment]
Closing
