### ISSUE TITLE
dvc pull: from Azure fails only on Windows10 machine

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#7423]
# Bug Report

From Discord: https://discord.com/channels/485586884165107732/485596304961962003/947464009534292008

## Description

> dvc pull results to ERROR: unexpected error - Cannot connect to host *.blob.core.windows.net:443 ssl:True [getaddrinfo failed]: on  a Windows 10 machine.

> This is all on a windows 10 workstation.
I have tested this on a Linux box as well, and dvc pull works. Also, we are running a Github test workflow using an app service principal with a secret credential, and dvc pull  works there too. So it may just be the windows config.

Using azure CLI (`az storage blob upload`) works from that Windows10 machine.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.5 (pip)
---------------------------------
Platform: Python 3.8.0 on Windows-10-10.0.19041-SP0
Supports:
        azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
        webhdfs (fsspec = 2022.2.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: NTFS on D:\
Caches: local
Remotes: azure
Workspace directory: NTFS on D:\
Repo: dvc, git
```

**Additional Information (if any):**

```console
$ dvc config -l
remote.efd_data_remote.url=azure://data/
remote.efd_data_remote.account_name=efdml4488431542
core.remote=efd_data_remote
```
[Full traceback](https://github.com/iterative/dvc/files/8151657/message.2.txt)

**Comment by wshields1** [comment]
Hiya, I have run the following as requested, but no luck:

**Comment by daavoo** [comment]
@wshields1 Could you try to set the env var `AZURE_CONFIG_DIR` pointing to https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-file .

It seems that we are not considering Windows when setting the default value for this in https://github.com/iterative/dvc/blob/30d6839a5f471fb02a7a2dcbd6a6616b71277762/dvc/fs/azure.py#L35

**Comment by daavoo** [comment]
Hi @wshields1 could you share the verbose output (`dvc pull -v`)?

**Comment by wshields1** [comment]
[dvc pull -v.txt](https://github.com/iterative/dvc/files/8161940/dvc.pull.-v.txt)

**Comment by dtrifiro** [comment]
Hi @wshields1, from the first traceback, I see that the azure remote is `efddklzoning.blob.core.windows.net` is the name of the storage account correct?

**Comment by orphefs** [comment]
The name of the storage account is `efdml4488431542`, and `nmap efdml4488431542.blob.core.windows.net` yields 
```bash 
Starting Nmap 7.80 ( https://nmap.org ) at 2022-03-01 17:35 EET
Nmap scan report for efdml4488431542.blob.core.windows.net (20.60.145.4)
Host is up (0.067s latency).
Not shown: 993 filtered ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
111/tcp  open  rpcbind
443/tcp  open  https
2048/tcp open  dls-monitor
8080/tcp open  http-proxy
8443/tcp open  https-alt
```

which means it should be accessible via port `443`. The question is why DVC is trying to access `efddklzoning` and not `efdml4488431542`? `EFD_DK_LZONING` is the name of a resource group.

**Comment by wshields1** [comment]
So we have our answer! There was an environment variable called AZURE_STORAGE_CONNECTION_STRING  which for some reason had been set to the wrong account. Not quite sure how this occurred (may have been me playing around when initially working with Azure or may have been created somewhere else in the process), but is fixed now and all working. Thanks so much all for your help with this issue! Will

**Comment by daavoo** [comment]
Closing
