### ISSUE TITLE
exp: --decorate/--no-decorate

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7430]
Related: https://github.com/iterative/dvc/issues/6051

`dvc exp show` and `dvc exp list` both show git commit hashes. Both also try to show relevant branch and tag refs when appropriate. Sometimes it's useful to prioritize branch names (`dvc exp show --all-branches`), sometimes tag names (`dvc exp show --all-tags`), and sometimes raw hashes (`dvc exp show --rev abc123 -n 5`).

We can try to guess what to show in each scenario, or we can default to some consistent behavior and use flags similar to `git log --decorate/--no-decorate` to decide what to show.

**Comment by daavoo** [comment]
How would this flag affect "experiment rows" (If I understand correctly the descriptions is about "commit rows")?

The current default display for experiment rows is:

```console
$ dvc exp show
...
  ├── 6d13f33 [cnn-64]    Sep 09, 2021   0.23385   0.9153   10
  └── 69503c6 [cnn-128]   Sep 09, 2021   0.23243    0.916   10
 ```
 
 Would this new flag imply that default show become:
 
```console
$ dvc exp show
 
  ├── 6d13f33             Sep 09, 2021   0.23385   0.9153   10
  └── 69503c6             Sep 09, 2021   0.23243    0.916   10

 ```
 
  
And with the flag:
 
```console
$ dvc exp show --decorate

  ├── 6d13f33 [cnn-64]           Sep 09, 2021   0.23385   0.9153   10
  └── 69503c6 [cnn-128]          Sep 09, 2021   0.23243    0.916   10

 ```
 ?

**Comment by dberenbaum** [comment]
That's the basic idea, but there are a lot of details to consider, like:

* What should be the default?
* What if there are multiple refs?
* Should there be options like `--decorate-refs/--decorate-refs-exclude` (see https://git-scm.com/docs/git-log#Documentation/git-log.txt---decorateshortfullautono)?
