### ISSUE TITLE
`exp push/pull`: QA

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7448]
Some issues with `exp push/pull`:

1. Message is `no experiments to pull` even when doing push:

```
$ dvc exp push origin -A
No experiments to pull.
```

2. When push/pulling an already pushed/pulled experiment, it still shows as having been pushed/pulled again:

```
$ dvc exp push origin -A
Pushed experiment '['exp-93aeb']'to Git remote 'origin'.
$ dvc exp push origin -A
Pushed experiment '['exp-93aeb']'to Git remote 'origin'.
```

3. If any commit is missing version info, an unexpected warning is shown.

Repro script:

```
#!/bin/bash
mkdir repo
mkdir dvcremote
mkdir gitremote
cd repo
git init
dvc init -q
dvc remote add -d default ../dvcremote
git remote add origin ../gitremote
git add .
git commit --quiet -m "init"
git clone --bare . ../gitremote
dvc stage add -n test -p p -o foo cp params.yaml foo
echo 'p: 1' > params.yaml
git add .
git commit -m "setup"
dvc exp run -S p=2
dvc exp push origin --rev HEAD
```

Output warning (irrelevant output excluded):

```
WARNING: Output 'foo'(stage: 'test') is missing version info. Cache for it will not be collected. Use `dvc repro` to get your pipeline up to date.
You can also use `dvc commit test` to associate existing 'foo' with stage: 'test'.
Pushed experiment '['exp-93aeb']'to Git remote 'origin'.
```

Might be related to #6592. The experiment being pushed doesn't have missing version info, nor does its parent commit.

**Comment by karajan1001** [comment]
1. is a UI problem.
2. Current we skip on those experiments which already existed on both sides, but do not exclude them from the result list. Another thing needs to be noticed is that if we have different experiment with the same name on both side, pulling/pushing them will stop the current progress and raise an exception, but didn't give any information on those experiments that had already been pulled/pushed. 
3.  looks like it is because dvc.lock is not tracked by git. (so not pushed to the remote)
```bash
#!/bin/bash
mkdir repo
mkdir dvcremote
mkdir gitremote
cd repo
git init
dvc init -q
dvc remote add -d default ../dvcremote
git remote add origin ../gitremote
git add .
git commit --quiet -m "init"
git clone --bare . ../gitremote
dvc stage add -n test -p p -o foo cp params.yaml foo
echo 'p: 1' > params.yaml
dvc repro # add this line to generate a `dvc.lock`
git add .
git commit -m "setup"
dvc exp run -S p=2
dvc exp push origin --rev HEAD
```

**Comment by karajan1001** [comment]
> Can we change it to only show what was actually transferred? In both dvc push/pull and git push/pull, the output only shows what actually gets transferred, so the current output was unexpected to me.
In `scmrepo`, `check_diverged` is used to checks if it can be fast-forwarding. 
https://github.com/iterative/scmrepo/blob/8fbc66c4f6c106786c598a08fe5c1df38083efa2/scmrepo/git/backend/dulwich/__init__.py#L528
So, actually we have no chance to get into 
https://github.com/iterative/dvc/blob/81eee059950d6a154327e3b15912a84d4b93e178/dvc/repo/experiments/push.py#L76-L77.
@peter  need to do some updations on `scmrepo` side.

**Comment by dberenbaum** [comment]
Thanks @karajan1001. I guess I overlooked your other point:

> 2\. Another thing needs to be noticed is that if we have different experiment with the same name on both side, pulling/pushing them will stop the current progress and raise an exception, but didn't give any information on those experiments that had already been pulled/pushed.

It would be nice to keep going, push/pull all the experiments it can, and then report back which ones were successful in addition to the errors for those that failed.

**Comment by karajan1001** [comment]
> Thanks @karajan1001. I guess I overlooked your other point:
> 
> > 2. Another thing needs to be noticed is that if we have different experiment with the same name on both side, pulling/pushing them will stop the current progress and raise an exception, but didn't give any information on those experiments that had already been pulled/pushed.
> 
> It would be nice to keep going, push/pull all the experiments it can, and then report back which ones were successful in addition to the errors for those that failed.

That's also what I suggested. ignore the confusion during the progress and report the failure after the whole progress.

**Comment by pmrowla** [comment]
> Can we change it to only show what was actually transferred? In both dvc push/pull and git push/pull, the output only shows what actually gets transferred, so the current output was unexpected to me.

The issue here is that on push, dulwich just returns a successful result if the ref on the remote matches the local version (so there's no straightforward way for us to tell the difference between pushing new commits to the existing ref or that nothing happened since the ref was already up-to-date)

We can check the status ourselves but that will make it a bit slower, is this actually a UI issue that needs to be addressed?
