### ISSUE TITLE
`exp run`: clarify `--rev` help output

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#7451]
... the [CLI output](https://github.com/iterative/dvc/blob/main/dvc/commands/experiments/run.py#L69-L72) `Continue the specified checkpoint experiment` isn't as clear as [the docs](https://dvc.org/doc/command-reference/exp/run#-r) `continue an experiment from a specific checkpoint`.

You don't need `--rev` to **resume** a checkpoint experiment, you need it to specify from which checkpoint to resume from.

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/pull/3319#discussion_r823354631_ Cc @omesser

- [ ] Notice the term should be "resume" instead of "continue", which probably applies to other related output strings.

**Comment by dberenbaum** [comment]
No longer an available option
