### ISSUE TITLE
Track Data Cleaning (removal) is very slow with dvc add

### ISSUE THREAD

**Issue by timothylimyl** [iterative/dvc#7484]
Hi,

When doing some data cleaning, we will delete some files from a bunch of files within a tracked folder.  Running `dvc diff` to see the difference between the local workspace in comparison to the last commit is super quick, results comes in **within a few seconds** which makes sense as dvc just had to look at the `data_folder.dvc` file, get the `.dir` hash, then check to see which file location is missing and report back what was deleted.  

However, to track this deletion, we need to update the `data_folder.dvc` to reflect these changes. When I run `dvc add data_folder`, it turns out that it is looking through every single file (thousands+) and the updates takes very long (roughly **5 minutes**) despite it being just a few files being deleted. 

**Why is the mechanism of `dvc diff` so much faster than `dvc add`?**  If the system is able to catch the differences so quick, the update should not take that long right?

**Comment by skshetry** [comment]
Hi @timothylimyl. Could you please share more details about the dvc repo? How many `.dvc` files do you have? 

Also, could you please share `dvc doctor` output?

**Comment by timothylimyl** [comment]
hi @skshetry , the dvc repo is like this:
```
data_segmentation
├── n02086240 [941 entries exceeds filelimit, not opening dir]
├── n02087394 [942 entries exceeds filelimit, not opening dir]
├── n02089973 [571 entries exceeds filelimit, not opening dir]
└── n02111889 [917 entries exceeds filelimit, not opening dir]
```

I am tracking `data_segmentation`,  I will do `dvc add data_segmentation`.  My test, I go into a folder and delete 4 images then I will do `dvc add data_segmentation`. It starts looking through every file and update takes very long (actually more than 5minutes)!

My intuition is that the `.dir` can easily check what is missing and update a new `.dir` file for the `data_segmentation.dvc` to do the tracking.

Running dvc doctor:
```
DVC version: 2.9.5 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.11.0-46-generic-x86_64-with-glibc2.29
Supports:
	gdrive (pydrive2 = 1.10.0),
	webhdfs (fsspec = 2022.2.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	ssh (sshfs = 2021.11.2)
Cache types: 
Cache directory: vfat on /dev/sda1
Caches: local
Remotes: local, ssh
Workspace directory: vfat on /dev/sda1
Repo: dvc, git

```

**Comment by skshetry** [comment]
@timothylimyl, can you please share output of `python -m dvc.repo.index`? 

Also, would you be able to share some profiling data? Here's how you can do that:
```console
pip install dvc
dvc add --yappi <>
```

This will generate a file in the format of `callgrind.dvc-XXX.out` which you can share here. See [wiki](https://github.com/iterative/dvc/wiki/Debugging,-Profiling-and-Benchmarking-DVC#generating-callgrind-data-with-yappi) for more details.

Thanks.

**Comment by timothylimyl** [comment]
Thanks for the fast reply, I actually tested with adding some images too (added like 5 images) and then run `dvc add data_segmentation`.

Output of `dvc.repo.index` after running `dvc add`:
```
no of stages 1
   13.60 ms in collecting stages
   35.37 ms in building graph
1da6003ad13d00d8f8bf03ecbbf43af8
  143.77 mks in calculating hash
    5.48 mks in updating
1da6003ad13d00d8f8bf03ecbbf43af8
   90.60 mks in calculating hash
```

Then running `dvc add --yappi data_segmentation`, provides the attached file.
[callgrind.dvc-20220328_115150.txt](https://github.com/iterative/dvc/files/8359559/callgrind.dvc-20220328_115150.txt)

**Comment by skshetry** [comment]
> Then running `dvc add --yappi data_segmentation`, provides the attached file. [callgrind.dvc-20220328_115150.txt](https://github.com/iterative/dvc/files/8359559/callgrind.dvc-20220328_115150.txt)

Thanks for the profiling data. It shows that the slowest part is the [`checkout`](https://github.com/iterative/dvc/blob/d09d39538a14dfecad877cdb8d2b40768510bf3b/dvc/output.py#L596-L604) done during `stage.commit()` which is 97.5% of the total runtime.

https://github.com/iterative/dvc/blob/d09d39538a14dfecad877cdb8d2b40768510bf3b/dvc/output.py#L596-L604

There are 3,382 files in that directory.

Half of the time is being spent on [`_reflink_linux`](https://github.com/iterative/dvc/blob/d09d39538a14dfecad877cdb8d2b40768510bf3b/dvc/system.py#L87) even though the user's system does not support reflink. So, we are making 3,382 such calls, and we are falling back to `copy` each time where we spent other half of the time (which the profiler does not show unfortunately but is a good guess).

https://github.com/iterative/dvc/blob/d09d39538a14dfecad877cdb8d2b40768510bf3b/dvc/utils/fs.py#L200-L218

---

Usually, we should be optimizing this to never checkout, but we do this step as part of handling `--reflink` changes correctly. Even if we do so, we should remember what link type system supports and always use that instead of this `fallback` logic.

**Comment by timothylimyl** [comment]
hi @skshetry , thank you for debugging. Pardon my ignorance, but what can I do and how do I check whether is my system using reflink or copy?

**Comment by skshetry** [comment]
> what can I do

@timothylimyl, given that DVC always tries to reflink first, there's not a good workaround. 

> how do I check whether is my system using reflink or copy?

`dvc doctor` has a `Cache types` output that shows whether the system supports reflink or not. From what I see above, your filesystem does not support reflink.

Btrfs, XFS, APFS are few filesystems that support them, and are efficient as they are copy-on-write links.

**Comment by timothylimyl** [comment]
is it possible to download reflink/new filesystems?

**Comment by timothylimyl** [comment]
I shall closed this, open it if you feel there is a need for any fixes.

**Comment by skshetry** [comment]
@timothylimyl, let's keep this issue open. We are working on some internal refactorings to optimize `diff` and `checkout`. 🙂

**Comment by timothylimyl** [comment]
Noted, looking forward to the update!

**Comment by timothylimyl** [comment]
assume inactivity. I will close the issue.

**Comment by efiop** [comment]
@timothylimyl Sorry for the lack of updates here, but just wanted to note that we've tweaked diff and checkout since then and it might be faster in your scenario now as well.
