### ISSUE TITLE
Init hang on NFS mount

### ISSUE THREAD

**Issue by SiftingSands** [iterative/dvc#7494]
# Bug Report

## Description

I've got several TB of data on a NFS mount, and I want to test out DVC for version control on it. However, even 'dvc init -v' just hangs (waited several minutes) on an empty test folder without any feedback. I haven't tried to see if it eventually exits.

I saw this might be a related issue https://github.com/iterative/dvc/pull/6419, but I'm not sure that helps since setting 'config' options requires 'init' to succeed?

### Environment information

**Output of `dvc doctor`:**

```
DVC version: 2.9.5 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with-glibc2.10
Supports:
	hdfs (fsspec = 2022.2.0, pyarrow = 4.0.1),
	webhdfs (fsspec = 2022.2.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
```

Thanks!

**Comment by karajan1001** [comment]
Hi, @SiftingSands 
Could you please provide some more details by running 
> dvc init --cprofile --cprofile-dump init.prof
And paste the file `init.prof` here?

**Comment by dberenbaum** [comment]
I'm playing around with dvc on nfs and can confirm that `dvc init` hangs for me, although it does complete in under a minute. The culprit looks to be the diskcache state database:

<img width="1001" alt="Screen Shot 2022-03-23 at 12 38 26 PM" src="https://user-images.githubusercontent.com/2308172/159774707-9f4251f9-8835-425c-966e-83606cfd7aa5.png">

A workaround is to globally apply the settings suggested in https://github.com/iterative/dvc/issues/5562#issuecomment-941305805:

```
$ dvc config --global core.hardlink_lock true
$ dvc config --global state.dir /tmp/state
$ dvc config --global index.dir /tmp/index
$ dvc init
```

This resolves the issue:

<img width="999" alt="Screen Shot 2022-03-23 at 3 00 03 PM" src="https://user-images.githubusercontent.com/2308172/159777214-9e52ba6a-217d-42f9-bab4-47cf9edfedd2.png">

After the repo is initialized, you can unset globally and apply locally instead:

```
$ dvc config -u --global core.hardlink_lock
$ dvc config -u --global state.dir
$ dvc config -u --global index.dir
$ dvc config --local core.hardlink_lock true
$ dvc config --local state.dir /tmp/state
$ dvc config --local index.dir /tmp/index
```

An actual fix could either be using some non-repo path for the state database by default as suggested in https://github.com/iterative/dvc/pull/6111#issuecomment-857509929, or to not create the state database during `dvc init`.

**Comment by SiftingSands** [comment]
@dberenbaum Thanks for the detailed response. Switching the state and index dir to a non-NFS location fixed the issue with init hanging.

Out of curiosity, I tried to switch those two directories to be on the NFS mount after init succeeded. However, `dvc add` would then hang.

 I wanted to test out more than just `init` before responding, and things seem to be going as expected. However, I haven't tried out push/pull to remotes.

**Comment by balvisio** [comment]
> I'm playing around with dvc on nfs and can confirm that `dvc init` hangs for me, although it does complete in under a minute. The culprit looks to be the diskcache state database:
>> ...
@dberenbaum Just for curiosity, which tool did you use to visualiz the call stack? [viztracer](https://github.com/gaogaotiantian/viztracer)?

Thanks!
