### ISSUE TITLE
install: reorder methods and add badges

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#7495]
LATEST UPDATE: Scroll to https://github.com/iterative/dvc/issues/7495#issuecomment-1067480425.

Update options including order and badges.

- conda [![Conda-forge](https://anaconda.org/conda-forge/dvc/badges/version.svg)](https://anaconda.org/conda-forge/dvc) or [![Conda-forge](https://img.shields.io/conda/v/conda-forge/dvc.svg?label=conda-forge&logo=conda-forge)](https://anaconda.org/conda-forge/dvc)
- snap [![Snapcraft](https://img.shields.io/badge/snap-install-82BEA0.svg?logo=snapcraft)](https://snapcraft.io/dvc) or [![dvc](https://snapcraft.io//dvc/badge.svg)](https://snapcraft.io/dvc)
  + also [![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/dvc) or [![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-white.svg)](https://snapcraft.io/dvc)
- pip [![PyPI-Status](https://img.shields.io/pypi/v/dvc.svg?logo=PyPI&logoColor=white)](https://pypi.org/project/dvc)
- GitHub donwloads [![GitHub release (latest by date)](https://img.shields.io/github/v/release/iterative/dvc?label=GitHub&logo=github)](https://github.com/iterative/dvc/releases/latest)
  + deb
  + pkg
  + rpm
  + exe
- apt (?)
- choco [![Chocolatey Version](https://img.shields.io/chocolatey/v/dvc)](https://chocolatey.org/packages/dvc)
- brew [![homebrew](https://img.shields.io/homebrew/v/dvc)](https://formulae.brew.sh/formula/dvc)
- anything else?

Probably need to split first based on OS:

- Linux
  + conda
  + snap
  + deb/rpm
  + pip
- Mac
  + conda
  + brew
  + pip
  + pkg
- Windows
  + conda
  + choco
  + pip
  + exe

**Comment by efiop** [comment]
closing as stale
