### ISSUE TITLE
dvc mv command?

### ISSUE THREAD

**Issue by yukw777** [iterative/dvc#750]
Sometimes I just want to change the names of large files. What would be the best way to do it? Maybe add `dvc mv`?

**Comment by efiop** [comment]
Hi @yukw777 !

We are considering adding `dvc mv` for data sources(see https://github.com/iterative/dvc/issues/336), but it is not ready just yet. For now, you can use this workaround:
```
$ mv file_name new_file_name
$ dvc add new_file_name
$ rm file_name.dvc
```

**Comment by yukw777** [comment]
@efiop thanks! I'll close this in favor of https://github.com/iterative/dvc/issues/336
