### ISSUE TITLE
dvc: regroup all command options/flags [quality]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#7525]
As suggested in https://github.com/iterative/dvc.org/pull/3345 and implemented for `run`, `repro`, and `stage add` in https://github.com/iterative/dvc/pull/7524, we could come up with a logical way to present options/flags. The criteria we came up with so far is basically:

1. Put general/misc. short options/flags first (with `-hqv`)
2. Make groups of args based on functionality e.g. `stage add -dDp` (all dependency-related)
3. Order these arg groups in some logical way e.g. chronologically (deps, then outs) or by most-needed-first.
4. Put remaining misc. args at the end.

**Comment by jorgeorpinel** [comment]
Cc @dberenbaum @omesser

**Comment by dberenbaum** [comment]
@skshetry What do you think about this as part of our UI guidelines in https://github.com/iterative/dvc/issues/5392?
