### ISSUE TITLE
dvc status -c: reports files as new even though they exist in both .dvc/cache and the s3 remote

### ISSUE THREAD

**Issue by brmanuel** [iterative/dvc#7530]
# Bug Report

## Description

I'm running my pipelines and push the new out files to a remote S3 bucket.
Running `dvc status -c` I observe that many, but not all, of the created outs are reported as `new`, i.e. not on the S3 bucket
I look up the md5 hash of one of the `new` files in the dvc.lock file: 4a3f17ce22f7e3bc93df0aefa142ed85
The corresponding file exists in both the local cache and the remote S3 bucket:

```console
$ ls -l .dvc/cache/4a/3f17ce22f7e3bc93df0aefa142ed85
-r--r--r-- 1 vscode vscode 12613 Mar 28 13:52 .dvc/cache/4a/3f17ce22f7e3bc93df0aefa142ed85
```
Relevant S3 bucket content as seen using winSCP:
![image](https://user-images.githubusercontent.com/22857883/161030737-5c0aef96-8f11-4792-8647-f336a96b432c.png)

One thing I've noticed is that all falsely as `new` reported outs are out-files. My pipeline also produces out-dirs, but none of those has this problem.

### Reproduce

1. dvc repro dvc.yaml
2. dvc push
3. dvc status -c

### Expected

I'm expecting that `dvc status -c` recognizes that this file is on the remote and not report it as `new`.
In particular, this bug also prohibits other users to pull these out-files to their machine.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.10.0 (pip)
---------------------------------
Platform: Python 3.9.9 on Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
Supports:
        webhdfs (fsspec = 2022.2.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.2.0, boto3 = 1.20.24)
Cache types: 
Cache directory: ext4 on /dev/sdb
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sdb
Repo: dvc, git
```

**Additional Information (if any):**

I'm running inside a dockerized environment which runs on WSL2 on a Windows machine

**Comment by pmrowla** [comment]
Discord context: https://discord.com/channels/485586884165107732/958705251198849054

**Comment by pmrowla** [comment]
For reference, I was unable to reproduce this in testing, but it may be a WSL specific issue
