### ISSUE TITLE
`exp show`: never add a tree character in `prepare_exp_id()` if `pcp` is enabled

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#7539]
Would it be possible to never add a tree character in `prepare_exp_id()` if `pcp` is enabled?

_Originally posted by @skshetry in https://github.com/iterative/dvc/pull/7536#discussion_r841601819_

**Comment by pmrowla** [comment]
We should probably be treating `pcp` the same as `csv` output, and not call `prepare_exp_id` at all in that case.

https://github.com/iterative/dvc/blob/117b22d58ad2e652b3f31669dacd624f448951d1/dvc/commands/experiments/show.py#L375-L380

**Comment by dberenbaum** [comment]
Closing since I doubt we will prioritize this
