### ISSUE TITLE
Modifying data files with dvc

### ISSUE THREAD

**Issue by arunchaganty** [iterative/dvc#754]
I have a fairly simple use-case: we have some situations where we genuinely want to modify our data, either by appending new data we collected or by deleting old, deemed-to-be-useless, data. DVC seems like the perfect data versioning tool for this task. However, because DVC uses hardlinks, it is extremely dangerous to modify the file in place. The current workflow I have in mind is:
```
cp file file_
vim file_ # make changes (vim is just for illustrative purposes)
mv file_ file
dvc repro
```
Does that seem right?

Independently, shouldn't dvc make data files read only to prevent corrupting the cache?

**Comment by arunchaganty** [comment]
Ah, thanks!

P.S. I imagine it might be useful to have a FAQ wiki page and add these answers in.

**Comment by dmpetrov** [comment]
FAQ or Wiki - it is a good idea. We are thinking about creating one.
