### ISSUE TITLE
Feature Request: avoid storing outputs on local disk by writing directly to NAS

### ISSUE THREAD

**Issue by johan-sightic** [iterative/dvc#7540]
**NOTE:** I use Ubuntu 20.04

### My usecase:
- I collect large amounts of very sensitive data on my computer.
- I transfer that data from my computer to an encrypted NAS that for security and regulatory reasons does not have internet access.
- This NAS can be mounted to my local filesystem.
- I want to version control the data on the NAS.
- The data should be accessible to everyone in the team.
- For practical end security reasons, once the data is on the NAS, I don't ever want it to be stored on a local disk again, not even temporarily. It can of course be stored in RAM when processed.
- The code is not as sensitive (relatively speaking) and should be accessible from everywhere so it should be stored in the cloud.

### What I have tried
- Set up a local remote and external cache (personal or shared) on the NAS and mounted it to my file system. **Result:** new outputs are still stored locally before being transferred to NAS.
- Set up local remote and personal workspaces on NAS. **Result:** although the data is never stored locally on the disk the code is now not available when not connected to the NAS.
- Set up a local remote and mount a personal, NAS based, directory into my local workspace where only the data is stored. **Result:** the most promising solution. However, this requires the most setup: changing cache location and mounting both the local remote and data directory to workspace. Git also gets confused when the NAS isn't mounted.

### Summary
DVC has some nice functionalities for working with a NAS that allows you to store and cache data there without transferring it to local disk before loading it to RAM. However there is no way of updating an output without first writing it to disk.

**Comment by EyescannerJE** [comment]
I also tried with `--external` but I'm not sure how to make that work with multiple users
