### ISSUE TITLE
exp init/exp run: fails if the repo has no root commit

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#7548]
When you do `exp init` and try to run `exp run`,
```console
git init && dvc init
dvc exp init "mkdir models plots && echo '{}' > metrics.json"
dvc exp run
```
```console
WARNING: Your workspace contains staged Git changes which will be unstaged before running this experiment.
ERROR: unexpected error - reference 'refs/heads/master' not found
```

It fails with the above error message.

We have to try to provide good hints on `exp init`, and also on `dvc exp run` what to do here.

**Comment by dberenbaum** [comment]
After #8840, `dvc exp run` fails quickly with this output:

```bash
ERROR: Empty Git repo. Add a commit to use experiments.
```

Closing as completed, but feel free to reopen if you think there's more we should do here @skshetry .
