### ISSUE TITLE
exp: Custom experiment comparison

### ISSUE THREAD

**Issue by gregstarr** [iterative/dvc#7557]
Hello,

Would it be possible to specify a custom script which runs after all experiments have finished, to compare the results of the experiments? It seems like DVC currently only provides the ability to get diffs between json metrics of the experiments, or plot multiple (maybe just 2?) ROC curves. I would like to be able to queue up several experiments, have them run in parallel, then after, a script is run in which I am able to access the files in each experiment to do custom comparisons, e.g. make a bar chart showing a metric across several experiments. 

Thanks

**Comment by daavoo** [comment]
Hi @gregstarr , you would need to run this script manually after all experiments have finished. 

You can retrieve the data of all experiments in JSON format with [`dvc exp show --json`](https://dvc.org/doc/user-guide/experiment-management/comparing-experiments#get-table-data-in-json), so you could do:

```
dvc exp run --run-all \
&& dvc exp show --json > experiments.json \
&& python custom_script.py --input-file experiments.json
```

Alternatively, you can access the same data in Python API:

```
from dvc.repo import Repo
repo = Repo(".")
experiment_results = repo.experiments.show()
```

You can find an example usage of the API here: https://github.com/iterative/dvc-streamlit-components/blob/main/dvc_streamlit/experiments.py

**Comment by gregstarr** [comment]
Thanks for the response. If I want to read a csv file from my experiment directory, what is the best way to do that?

**Comment by karotchykau** [comment]
Hi @gregstarr.

You can just use [dvc.api](https://dvc.org/doc/api-reference) to compare all your experiments in a single Jupyter notebook ([dvc.api.open](https://dvc.org/doc/api-reference/open) or [dvc.api.read](https://dvc.org/doc/api-reference/read)). You can specify experiment name using the `rev` parameter (the docs might not be updated yet, but you can also provide experiment name as `rev`). After loading, you can compare your data/metrics/etc. in any way that you actually want. Please note that you have to push your local experiments first if you want to use remote `dvc.api` (see the `repo` parameter).
