### ISSUE TITLE
Azure Data Lake Gen2 support

### ISSUE THREAD

**Issue by aitzubi** [iterative/dvc#7566]
Good morning everybody! 

I work at a R&D company and our Data Teams love DVC. We are looking forward on using it with our corporate Azure Data Lake Gen2. The documentation says that it is not supported due to Microsoft not publishing data lake blob API. It seems that there is an api published but I dunno if it is valid for dvc: https://docs.microsoft.com/en-us/rest/api/storageservices/data-lake-storage-gen2

@daavoo mentioned on discord that it seems that nowadays they support fsspec: 'It looks like there support accessing data through fsspec now (https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/tutorial-spark-pool-filesystem-spec)'

It would be really nice to have this feature as I think that it would greatly improve corporate environment adoption.

Thank you!

**Comment by efiop** [comment]
@aitzubi It could be that we already support it as blob storage (at least judging from https://github.com/fsspec/adlfs/blob/bfcc9b381641f503d0f8c6a8dd3869d959ab8896/adlfs/spec.py#L305 ), but we didn't confirm it yet ourselves. Have you tried using it with dvc yet?

**Comment by aitzubi** [comment]
@efiop i am unable to test this because I can seem to find how to configure the SAS Token. ConnectionString does not seem to work either.

Could you please provide me an example on how to configure a ConnectionString or a SAS token?

Kind regards,

**Comment by daavoo** [comment]
@aitzubi Could you try following https://dvc.org/doc/command-reference/remote/modify#example-some-azure-authentication-methods ?

**Comment by aitzubi** [comment]
@daavoo yeah, I was trying that but no luck. I just upgraded az-cli package and now I am getting a different result.

I attach the log of the dvc push command
[dvclog.txt](https://github.com/iterative/dvc/files/8506236/dvclog.txt)

**Comment by aitzubi** [comment]
Nevermind @daavoo , I just created a sas token using the storage key and it works! I can see the blobs created on the container in our data lake.

I will keep trying to use user delegation in order to leverage azure AD security benefits as Microsoft advises. I will keep you posted ;)

**Comment by daavoo** [comment]
Closing this one for now, as it was about supporting Data lake gen2. Feel free to re-open or open new issues if you encounter some

**Comment by efiop** [comment]
I guess we could also document it in https://dvc.org/doc/command-reference/remote/add and https://dvc.org/doc/command-reference/remote/modify @aitzubi If your experience will be successful, let us know or feel free to create a PR for the docs, so that other people could benefit from your research 🙂 Thank you ❤️

**Comment by aitzubi** [comment]
As I said, I will test the secure approach to create the token (AzureAD) and post the results here.

If i am successfull, I will create the PR ;)

Thx guys!
