### ISSUE TITLE
OpenSSH private key encryption requires bcrypt with KDF support

### ISSUE THREAD

**Issue by thias42** [iterative/dvc#7569]
# Bug Report
DescriptionRunning dvc push returns an error after upgrading to dvc version 2.9.5.:

ERROR: unexpected error - OpenSSH private key encryption requires bcrypt with KDF support 

## Reproduce

    mkdir test
    cd test
    git init .
    dvc init
    dvc remote add storage ssh://host:/storage
    dvc remote default storage
    echo hi > test.txt
    dvc add test.txt
    dvc push test.txt

## Expected

I expect the file to be pushed to the remote storage.

## Environment information

macOS Monterey version 12.3.1 running on MacBook Pro M1
DVC installed via Homebrew Homebrew 3.4.6-36-g6745bb2

## Output of dvc doctor:

DVC version: 2.9.5 (brew)
---------------------------------
Platform: Python 3.9.12 on macOS-12.3.1-x86_64-i386-64bit
Supports:
	azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2022.1.0),
	hdfs (fsspec = 2022.1.0, pyarrow = 4.0.1),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
	ssh (sshfs = 2021.11.2),
	webdav (webdav4 = 0.9.4),
	webdavs (webdav4 = 0.9.4)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: ssh
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc (subdir), git

**Comment by tblaschke** [comment]
I run into the same issue. I looks like the DVC macos installer does not provide an environment with a bcrypt package. Here is the issue of the underlying issue from the asyncssh library.
[https://github.com/ronf/asyncssh/issues/417](https://github.com/ronf/asyncssh/issues/417)

I fixed this by activating the dvc encloses python environment ind install the bcrypt package

`cd /usr/local/Cellar/dvc/2.9.5_1/libexec/bin && source activate && ./pip install bcrypt`
 
 It would be great if the dvc installer can ship with the bcrypt package.

**Comment by pmrowla** [comment]
@tblaschke just to clarify, did you install from the macos `.pkg` installer or from homebrew? (homebrew installs DVC from a source tarball using python/pip and not the macos pkg installer)

**Comment by tblaschke** [comment]
@pmrowla I installed it through homebrew. (I somewhat assumed that homebrew uses the macos installer and not the tar ball)

**Comment by pmrowla** [comment]
This will be resolved when 2.10.1 is released in homebrew-core
