### ISSUE TITLE
Perf issue with large number of files

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#758]
Tested with 25K files. We had a similar issue before.

**Comment by efiop** [comment]
Thank you for the heads up! I'm aware of this and will make sure to tune the performance for the release.

**Comment by franekp** [comment]
https://github.com/iterative/dvc/pull/759  ---  fixes "dvc add" performance, tested on folder containing 12K files.

**Comment by efiop** [comment]
@franekp thank you so much!

**Comment by dmpetrov** [comment]
Let's keep it open since `dvc checkout` still has a perf issue.
