### ISSUE TITLE
dvc.repo.get.get: fails for cloning private and public repos from github in dvc version 2.10.1

### ISSUE THREAD

**Issue by akmorrow13** [iterative/dvc#7584]
# Bug Report

## Description

When dvc.repo.get.get is called on both a public and private github repository using dvc version 2.10.1, it fails with error: 

`dvc.scm.CloneError: Failed to clone repo 'git@github.com:patchbio/model-registry' to '/tmp/tmpblkwhy8ydvc-clone'  `

### Reproduce

Install dvc version 2.10.1:
```console
pip install dvc==2.10.1
```

Try to get an example README.md from a public repo:

```
import dvc.repo.get

dvc.repo.get.get(
url = 'git@github.com:akmorrow13/epitome.git',
path = "README.md", 
out ="/tmp/test_out")

```

### Expected

Dvc should successfully download the file to the out directory.

### Environment information

Python 3.8.13
Debian GNU/Linux 10

**Output of `dvc doctor`:**

```console
Supports:
        gs (gcsfs = 2022.3.0),
        hdfs (fsspec = 2022.3.0, pyarrow = 4.0.1),
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
```

**Additional Information (if any):**

**Comment by dberenbaum** [comment]
This looks like it may be a duplicate of https://github.com/iterative/dvc/issues/7537. @akmorrow13 Could you try the suggestion in https://github.com/iterative/dvc/issues/7537#issuecomment-1092436420?

**Comment by akmorrow13** [comment]
Thanks for the quick reply @dberenbaum. After running` pip install scmrepo==0.0.18 ` I still get the same issue: 

```
    File "site-packages/dvc/scm.py", line 108, in clone                      
      raise CloneError(str(exc))                                                                                                  
  dvc.scm.CloneError: Failed to clone repo 
```

**Comment by pmrowla** [comment]
Can you post the full error traceback you are getting?

**Comment by akmorrow13** [comment]
It is working now. I had installed `scmrepo` `0.0.16` instead of `0.0.18`. Thanks for the help!
