### ISSUE TITLE
Disable pushing specified outputs

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7594]
Specifying different remotes per output was addressed in #6486 (see https://dvc.org/doc/user-guide/project-structure/pipelines-files#output-subfields), but there's still no way to set `remote: false` for an output. 

Note the following workaround in the meantime: you can do `dvc remote add dummy .dvc/cache`, and then use `remote: dummy` under your output in `dvc.yaml`. This will push that output only to your local cache, where it should already be, and prevent it from being pushed to other remotes.

**Comment by amka66** [comment]
Please consider the situation of ignoring _some_ files from a tracked folder that is pushed remotely, while still keeping track of them in the _local_ cache. It can be thought of a soft `.dvcignore` entry (ignoring for remote cache comparisons and maintaining in local cache comparisons) and maintaining for the sake of local sync), and maybe this is how this entire capability should be implemented.
