### ISSUE TITLE
dvc remove not working even default tutorial  example

### ISSUE THREAD

**Issue by analystanand** [iterative/dvc#760]
i was trying to replicate the [tutorial](https://blog.dataversioncontrol.com/data-version-control-tutorial-9146715eda46).

As  i have added data like below
`dvc add data/Posts.xml.tgz`

But while executing removal with below command
`dvc remove data/Posts.xml.tgz`

`Failed to obtain latest version: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/home/parma/PycharmProjects/dvc_demo/venv/lib/python3.5/site-packages/dvc/command/remove.py", line 9, in run
    self.project.remove(target)
  File "/home/parma/PycharmProjects/dvc_demo/venv/lib/python3.5/site-packages/dvc/project.py", line 129, in remove
    raise StageNotFoundError(target)
dvc.project.StageNotFoundError: Stage file data/Posts.xml.tgz does not exist
`

**Comment by efiop** [comment]
Hi @analystanand !

`dvc remove` works with dvc files and not regular files(as `dvc add` does). Try adding .dvc to your command. I.e.:
```
dvc remove data/Posts.xml.tgz**.dvc**
```

Please let us know if that helped.

Thanks,
Ruslan

**Comment by analystanand** [comment]
okay, let check

I have actually refered this [dvc remove](https://dvc.org/documentation#commands_command_reference_remove) to execute it.

Also Please update the doc..
few more deprecated commands

`dvc show`
`dvc fsck`

**Comment by analystanand** [comment]
what is the expected behaviour with `dvc remove` ?
as per understanding, It should ideally remove from the file from  ".dvc" and updated `.gitignore` by removing file name.

**Comment by efiop** [comment]
Hi @analystanand !

Sorry for the outdated doc, we are currently working on it. Will be sure to update it for 0.9.8 release.
You could use `dvc --help` for now, it always has most up-to-date info about dvc commands.

`dvc remove` removes outputs of a specified dvcfile.

I agree, we should also have some command to remove dvc file and cleanup other stuff. Thank you for pointing that! I've added https://github.com/iterative/dvc/issues/761 to our TODO list.

Thanks,
Ruslan

**Comment by analystanand** [comment]
Hi @efiop 

How soon can we expect 0.9.8 release?

**Comment by efiop** [comment]
I expect 0.9.8 to be released by the end of the next week, if everything goes as planned.

**Comment by efiop** [comment]
FYI: #761 was merged and going to be released in 0.9.8. I also fixed error msgs so they won't add to the confusion again.
