### ISSUE TITLE
gc: remove original files linked by other projects when shared cache is used

### ISSUE THREAD

**Issue by shuozhou** [iterative/dvc#7610]
# Bug Report

## Description
when shared cache is used and two projects have overlapped files, remove files via `gc` in projectA seems to also remove the original files, which broken the some links in projectB (overlapped files)

### Reproduce
Example:

```bash
mkdir dataset data repo cache remote

# dataset
touch dataset/file1.txt dataset/file2.txt

# data registry
cd data/
git init
dvc init
dvc remote add -d remote ../remote
dvc cache dir ../cache
dvc config cache.type symlink
dvc config cache.shared group
dvc add ../dataset/ -o dataset
git add .
git commit -m 'add dataset to data'
dvc push

# ml project
cd ../repo/
git init
dvc init
dvc remote add -d remote ../remote
dvc cache dir ../cache
dvc config cache.type symlink
dvc config cache.shared group
dvc import ../data dataset
dvc unprotect dataset/file1.txt
echo 'new data from repo' >> dataset/file1.txt
dvc add dataset
git add .
git commit -m 'import and update'
dvc push

# remove from repo
dvc remove dataset.dvc
dvc gc -wc

tree ..
#..
#├── cache
#│   ├── 13
#│   ├── 6b
#│   ├── 7a
#│   └── d4
#├── data
#│   ├── dataset
#│   │   ├── file1.txt -> /home/ubuntu/dvc_test/cache/d4/1d8cd98f00b204e9800998ecf8427e
#│   │   └── file2.txt -> /home/ubuntu/dvc_test/cache/d4/1d8cd98f00b204e9800998ecf8427e
#│   └── dataset.dvc
#├── dataset
#│   ├── file1.txt
#│   └── file2.txt
#├── remote
#│   ├── 13
#│   ├── 6b
#│   ├── 7a
#│   └── d4
#└── repo
#    └── dataset
#        ├── file1.txt
#        └── file2.txt
```

### Expected

the overlapped file should still be maintained in cache and remote

### Environment information
**Output of `dvc doctor`:**
```console
$ dvc doctor
DVC version: 2.10.1 (pip)                                                                                      
---------------------------------                                                                              
Platform: Python 3.7.13 on Linux-4.15.0-175-generic-x86_64-with-Ubuntu-18.04-bionic                            
Supports:                                                                                                      
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: symlink
Cache directory: nfs4 on 10.1.1.9:/mnt/titan
Caches: local
Remotes: local
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git

```

**Comment by skshetry** [comment]
@shuozhou, [`dvc gc` has `-p` flag](https://dvc.org/doc/command-reference/gc#-p) where you can specify more dvc repositories to keep the data from. Thanks.

**Comment by shuozhou** [comment]
> @shuozhou, [`dvc gc` has a `-p` flag](https://dvc.org/doc/command-reference/gc#-p) where you can specify more dvc repositories to keep the data from. Thanks.

is the <path> in -p should be the project data to remove, or to keep?
if the second case, dose that mean we have to list all remaining N-1 projects in order to delete a data safely, when the cache/remote is shared among N projects?

**Comment by skshetry** [comment]
@shuozhou, it takes path to the dvc repositories' root.

**Comment by karajan1001** [comment]
> > @shuozhou, [`dvc gc` has a `-p` flag](https://dvc.org/doc/command-reference/gc#-p) where you can specify more dvc repositories to keep the data from. Thanks.
> 
> is the `path` parameter in -p should be the project to remove data, or to keep? if the second case, dose that mean we have to list all remaining N-1 projects in order to delete a data safely, when the cache/remote is shared among N projects?

`gc` on some share storage systems is quite hard work. Without some additional information, we can not know if the caches were linked to some other repository. Even if we backup the link info on the remote, it would be outdated if some changes happened locally without any connection to the remote ( for example, the laptop was lost). What we can only do here is to give more information and trust the users.
