### ISSUE TITLE
Cloud configuration documentation out of date

### ISSUE THREAD

**Issue by arunchaganty** [iterative/dvc#762]
When using the documentation on [setting up dvc with GCP](https://dvc.org/documentation#configuration_cloud), I get the following error:
```
Initialization error: Config file error: Wrong keys 'global' in {'global': {'cloud': 'GCP'}, 'gcp': {'storagepath': '/tmp/dvc/classify', 'projectname': 'Tmp'}}
```

**Comment by arunchaganty** [comment]
It appears the right set of instructions should either be:
```
dvc config Core.Cloud GCP
```
or to edit the file manually to:
```
[Core]
Remote = GCP
[Remote "gcp"]
URL = /tmp/dvc/classify/
ProjectName = tmp
```

**Comment by efiop** [comment]
Hi @arunchaganty !

Unfortunately our docs are currently outdated, but we are working on fixing them. You can easily set your cloud up with these commands:
```
dvc remote add myremote gs://tmp/dvc/classify
dvc remote modify myremote projectname tmp
dvc config core.remote myremote
```

Thanks,
Ruslan

**Comment by arunchaganty** [comment]
Ok, thanks!

**Comment by nickbent** [comment]
so for aws should the proper commands be 
dvc remote add AWS s3://apollo-news/prc/
dvc remote modify myremote projectname prc
dvc config core.remote AWS
?

**Comment by efiop** [comment]
Hi @nickbent !

Yes, that looks correct.
