### ISSUE TITLE
diff:  `--hide-missing` doesn't seem to work

### ISSUE THREAD

**Issue by kalebo** [iterative/dvc#7620]
# Bug Report

## Description
The [documentation](https://dvc.org/doc/command-reference/diff#--hide-missing) seems to suggest that I can list only dvc files that have been explicitly checked out, ignoring any that don't exist in the local cache. This is would be very useful in my particular workflow as I am primarily doing partial checkouts of specific datasets in DVC. E.g., fetching only a specific directory of dvc files.

However, the issue is that `--hide-missing` doesn't seem to work. This was confirmed by Gao on the discord server.

### Reproduce
* `dvc add` and `push` several files.
* `git commit` and `push` to a remote
* clone the git repo on a new machine or on the same machine after clearing the local cache.
* `dvc pull` a single specific file
* run `dvc diff` and note that all the unpulled files are marked as deleted
* run `dvc diff --hide-missing` and note that the diff is identical to the previous command

### Expected
The expected behavior is that the is no output with `--hide-missing` as the unpulled files are hidden and the one explicitly pulled file has not been modified.

### Environment information
```console
DVC version: 2.9.4 (pip)
---------------------------------
Platform: Python 3.9.2 on Linux-5.10.0-10-amd64-x86_64-with-glibc2.31
Supports:
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.1.0, boto3 = 1.21.7)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/vg0-scratch
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/mapper/vg0-scratch
Repo: dvc, git
```

**Comment by dberenbaum** [comment]
This looks like it was introduced in #7353 and is coming from changes to the `if` statement  in:

https://github.com/iterative/dvc/blob/c81d841fd75d5a965613905689db174df3b5585d/dvc/repo/diff.py#L187-L199

There are a couple different issues here:
1. Under the logic introduced in #7353, it's only possible for directories to be considered missing.
2. Even directories appear not to be working as expected:

```bash
$ git clone git@github.com:iterative/example-get-started.git
$ cd example-get-started
$ dvc diff --hide-missing
Deleted:
    data/data.xml
    data/features/
    data/prepared/
    model.pkl

files summary: 2 deleted
```

@efiop Any thoughts on this?
