### ISSUE TITLE
Use `dvc remove --purge` instead of `--outs` by default

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#763]

**Comment by mroutis** [comment]
Should we remove the `--purge` flag (as it would be the default) and leave just the `--outs-only`, @efiop ?

```diff
usage: dvc remove [-h] [-q | -v] [-o | -p] [-f] targets [targets ...]

- Remove outputs of DVC file.
+Remove DVC file and all its outputs.

positional arguments:
  targets        DVC files.

optional arguments:
  -h, --help     show this help message and exit
  -q, --quiet    Be quiet.
  -v, --verbose  Be verbose.
-  -o, --outs     Only remove DVC file outputs.(default)
-  -p, --purge    Remove DVC file and all its outputs.
+  -o, --outs-only     Only remove DVC file outputs
  -f, --force    Force purge.
```

Should we clarify that this removes the files only for the "working directory" and not from the cache?

**Comment by shcheklein** [comment]
👍 for better explanation. May be it makes sense to keep both options for backward compatibility and place (default) after the description.

**Comment by efiop** [comment]
This is a part of 1.0 issues, which are backward incompatible. We should not merge this to master yet.

**Comment by shcheklein** [comment]
@efiop should we create a 1.0 branch to merge these new features into them?

**Comment by efiop** [comment]
@shcheklein Sure. We already have 1.0-dev branch. @mroutis Could you please rebase your patch?

**Comment by mroutis** [comment]
Yes, @efiop , sorry, I didn't look at the milestone :see_no_evil:

**Comment by mroutis** [comment]
Close by #1289
