### ISSUE TITLE
DVC add giving error

### ISSUE THREAD

**Issue by dparmar61** [iterative/dvc#7633]
# Bug Report
dvc add : giving error for ignored files

## Description
I am using "dvc add -R --glob **/*.json" command and I have added "**/*dummy.json" in .dvcignore. So while running command it is giving error for config_dummy.json file

**Comment by karajan1001** [comment]
Can reproduce it, I think that we should skip them instead of error out. 
```bash
dvc add -R --glob *.json
ERROR: Path '/Users/gao/test/dvcignore/config_dummy.json' is ignored by
.dvcignore:5:/*dummy.json
```
