### ISSUE TITLE
Deprecation warning with package assyncssh when using dvc.api.open

### ISSUE THREAD

**Issue by Guillaume-oso** [iterative/dvc#7656]
I get a Deprecation Warning when cloning stuff with dvc.api.open(...)

/home/guillaume/alertor/.venv/lib/python3.8/site-packages/asyncssh/crypto/cipher.py:29: CryptographyDeprecationWarning: Blowfish has been deprecated
  from cryptography.hazmat.primitives.ciphers.algorithms import Blowfish, CAST5
/home/guillaume/alertor/.venv/lib/python3.8/site-packages/asyncssh/crypto/cipher.py:29: CryptographyDeprecationWarning: CAST5 has been deprecated
  from cryptography.hazmat.primitives.ciphers.algorithms import Blowfish, CAST5
/home/guillaume/alertor/.venv/lib/python3.8/site-packages/asyncssh/crypto/cipher.py:30: CryptographyDeprecationWarning: SEED has been deprecated
  from cryptography.hazmat.primitives.ciphers.algorithms import SEED, TripleDES

## dvc doctor:

DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.13.0-40-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.3.0, boto3 = 1.21.39)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

Version assyncssh:
asyncssh==2.10.1

**Comment by dtrifiro** [comment]
https://github.com/ronf/asyncssh/issues/473

**Comment by djimboy** [comment]
Install cryptography v 36.0.2

`pip install cryptography==36.0.2`
