### ISSUE TITLE
`dvc dag --dot`: Reverse order

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7676]
# Bug Report

## Description

`dvc dag --dot` produces the DAG in reverse order.

### Reproduce

Using https://github.com/iterative/example-get-started:

```console
$ dvc dag --dot
strict digraph  {
prepare;
featurize;
train;
evaluate;
"data/data.xml.dvc";
prepare -> "data/data.xml.dvc";
featurize -> prepare;
train -> featurize;
evaluate -> featurize;
evaluate -> train;
}
```

The resulting graph:

![dag](https://user-images.githubusercontent.com/2308172/166303230-9eef7480-029c-4f25-84d0-fbc90cbdc758.png)

### Expected

```console
$ dvc dag --dot
strict digraph  {
prepare;
featurize;
train;
evaluate;
"data/data.xml.dvc";
"data/data.xml.dvc" -> prepare;
prepare -> featurize;
featurize -> train;
featurize -> evaluate;
train -> evaluate;
}
```

![dag_fixed](https://user-images.githubusercontent.com/2308172/166304037-63a326be-90c8-4006-b88b-5fcdb33e3b39.png)

### Environment information

```console
$ dvc doctor
DVC version: 2.10.3.dev0+gc81d841fd.d20220428
---------------------------------
Platform: Python 3.8.5 on macOS-10.16-x86_64-i386-64bit
Supports:
        azure (adlfs = 2022.2.0, knack = 0.7.2, azure-identity = 1.5.0),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2022.1.0),
        hdfs (fsspec = 2022.1.0, pyarrow = 3.0.0),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.7.3, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.3, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
        ssh (sshfs = 2021.11.2),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.4),
        webdavs (webdav4 = 0.9.4)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Comment by tirkarthi** [comment]
dot generation is done here where using `G.reverse()` will give the expected dot file. But it also fails the test. From the test I cannot infer the right way to look at it.

https://github.com/iterative/dvc/blob/562e61235b4c506659b8f9ded64ab1ed1badc0a8/dvc/commands/dag.py#L21-L28

https://github.com/iterative/dvc/blob/562e61235b4c506659b8f9ded64ab1ed1badc0a8/tests/unit/command/test_dag.py#L137-L154

**Comment by dberenbaum** [comment]
@tirkarthi It's likely that the test is incorrect and needs to be updated, but we should take a close look when reviewing the PR.

**Comment by tirkarthi** [comment]
@dberenbaum I think the graph is generated in the order of final stage pointing to dependencies as per docstring. Hence calling `G.reverse` looks good to me. I will add a PR with output of current image and the PR image.

https://github.com/iterative/dvc/blob/d92c6fed67828a992609c0f49548dba8b7fda15d/dvc/repo/graph.py#L56-L92

**Comment by tirkarthi** [comment]
@dberenbaum created https://github.com/iterative/dvc/pull/7725 as a fix. I have added the png files before PR and after PR for the test case. The PR makes it consistent with mermaid output linked in the PR.
