### ISSUE TITLE
Dvc silently skips non-numerics metrics warnings

### ISSUE THREAD

**Issue by erudin** [iterative/dvc#7688]
## Description

Right now when parsing metrics in studio from a `dvc` repository, all the warnings are silently skipped, so studio is not being provided with the information needed.

**Additional Information (if any):**

Related to: [Issue #3341](https://github.com/iterative/studio/issues/3341)

**Comment by dberenbaum** [comment]
@pared What do you think? Do you need more info?

**Comment by pared** [comment]
@erudin are we talking about errors or warnings? Do you have some reproduction steps?
