### ISSUE TITLE
dvc remote without a command throws an error

### ISSUE THREAD

**Issue by arunchaganty** [iterative/dvc#769]
```
$ dvc remote
Initialization error: 'Namespace' object has no attribute 'func'
```
It should probably print out help instead.

**Comment by efiop** [comment]
Nice catch! This bug only occurs on python3, but on python2 the help is printed as expected:
```
(dvc) ➜  dvc git:(master) ✗ dvc remote                          
usage: dvc remote [-h] [-q] [-v] {add,remove,modify,list} ...   
dvc remote: error: too few arguments                            
(dvc) ➜  dvc git:(master) ✗ workon python3-dvc                  
(python3-dvc) ➜  dvc git:(master) ✗ dvc remote                  
Initialization error: 'Namespace' object has no attribute 'func'
(python3-dvc) ➜  dvc git:(master) ✗                             
```

**Comment by mroutis** [comment]
According to the bug report, looks like the issue happens only on `Python 3.3, Python 3.4`.
I can replicate it on Python 3.7, however, it makes me wonder if we are doing something weird then.

**Comment by shcheklein** [comment]
@mroutis reopen the issue?

**Comment by mroutis** [comment]
Ohh, sorry for the bad wording, @shcheklein . The workaround @efiop included in the code a year ago still works. 
I can replicate it after removing his patch, however, Python 3.7 is not listed on the bug report.
