### ISSUE TITLE
gc files older than specific rev

### ISSUE THREAD

**Issue by Danial-Alh** [iterative/dvc#7695]
I want to remove all DVC files being at least ten commits behind HEAD from my remote repo. Is there any way to do that with the `gc` command?

Thanks

**Comment by karajan1001** [comment]
Looks like we should also introduce our `-n` flag to `dvc gc` and `dvc exp gc`

**Comment by dberenbaum** [comment]
@karajan1001 How much time would it take to implement this?

**Comment by karajan1001** [comment]
> @karajan1001 How much time would it take to implement this?

As we had already refactored the branched I think it'll cost about 1-2 days.
