### ISSUE TITLE
ERROR: unexpected error - cannot import name 'OrderedDict' from 'typing_extensions'

### ISSUE THREAD

**Issue by muralidhar972** [iterative/dvc#7711]
# Bug Report

## Issue name

dvc add : this command should save the data into repo.

## Description

while was running the command it guide me to run git add after running data add. unfortunately data add has thrown an error.

### Reproduce

dvc get https://github.com/iterative/dataset-registry \
          get-started/data.xml -o data/data.xml
dvc add data/data.xml

### Expected

it should make us to run the git commands.

### Environment information

OS: Ubuntu 20.04.4 LTS
OS Type: 64 bit
working on VS code

am new bee to DVC and following your documentation. while i was using dvc add data/data.xml got an error. have explored google about this error related to dvc, no luck. 

**Output of `dvc doctor`:**

laptop-obs:~/Desktop/Data_version$ dvc add data/data.xml
ERROR: unexpected error - cannot import name 'OrderedDict' from 'typing_extensions' (/home/laptop-obs-134/.local/lib/python3.8/site-packages/typing_extensions.py)                    

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

**Additional Information (if any):**

Please check https://github.com/iterative/dvc/wiki/Debugging-DVC on ways to gather more information regarding the issue.

2022-05-08 07:30:14,708 DEBUG: Version info for developers:
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.13.0-40-generic-x86_64-with-glibc2.29
Supports:
        hdfs (fsspec = 2022.1.0, pyarrow = 7.0.0),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

**Comment by skshetry** [comment]
Hi, can you please share the output from `dvc add data/data.xml -v`?  The verbose mode should have more output. Thanks.

**Comment by skshetry** [comment]
Thanks @SamKnightGit, it's coming from rich, see https://github.com/Textualize/rich/issues/2164. Please try to update rich to the latest version.

```console
pip install -U rich 
```

Let us know, how it goes. :)

**Comment by SamKnightGit** [comment]
Works with the most recent version of rich, thanks!
