### ISSUE TITLE
Consider injecting outputs to .gitignore first

### ISSUE THREAD

**Issue by villasv** [iterative/dvc#772]
I'm not sure if this would break something and require a significant refactor, but I wish `dvc` would start by updating the .gitignore file to add the expected outputs (naturally remove it later if it fails).

I have a veeery long command that fetches around 250k files into a directory. Because the directory is only ignored afterwards, `git` will be severely slowed. It isn't a dealbreaker, but it's annoying because it cascades into a slower shell and VSCode, so I can't work on other stuff, say, a net README.

**Comment by efiop** [comment]
Hi @villasv !

So sorry for the delay, this issue got lost in the heat of preparing 0.10.0. :(

This is a very interesting case! At the moment I can't find anything such strategy would break, but I'll need to take a closer look at it. I've added this to our queue and should come back to it pretty soon. Thank you for the feedback!

**Comment by efiop** [comment]
closing as stale
