### ISSUE TITLE
'dvc add' fails on files encoded in Latin-1

### ISSUE THREAD

**Issue by noeddl** [iterative/dvc#773]
Running 'dvc add TEXTFILE' fails if TEXTFILE is encoded in Latin-1. The following error message is shown: 

Unexpected error: 'utf8' codec can't decode byte 0xa3 in position 12204: invalid start byte

The error disapears if TEXTFILE is saved with encoding UTF-8 before running 'dvc add'. So does dvc only support files encoded in UTF-8?

**Comment by efiop** [comment]
Hi @noeddl !

Which dvc version are you using?

**Comment by efiop** [comment]
Nevermind, I was able to reproduce on the recent versions. Working on the fix right now. Thanks for the report!

**Comment by noeddl** [comment]
Great, thanks for the quick reaction!
