### ISSUE TITLE
Install dvc through pip in a new EC2 machine

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#7743]
Installing DVC in a new EC2 machine (Amazon Linux 2 AMI) - `pip3 install dvc` and it does not work.

[logs.txt](https://github.com/iterative/dvc/files/8695692/logs.txt)

**Comment by efiop** [comment]
Unfortunately new dulwich version release process broke and wheels weren't published. Already fixed in the upstream, waiting for a new release.

In the mean time a workaround is to `pip3 install dulwich==0.20.35` first.

**Comment by efiop** [comment]
new dulwich release is out with the wheels. Closing.
