### ISSUE TITLE
DVC FAQ, Wiki or getting started

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#776]
Inspired by #754 and our offline discussion with @shcheklein about simple data versioning scenarios.

Topics:
- installation
- data file versioning with cloud storage backend (S3, GCP, SFTP)
- data file modifications
- file versioning in HDFS
- ML pipeline basic
- DVC for in data engineering pipelines
- tracking and navigating by metrics
- remotes

**Comment by efiop** [comment]
Moved to https://github.com/iterative/dvc.org/issues/48 .
