### ISSUE TITLE
DVC pull extremely slow on Azure VM

### ISSUE THREAD

**Issue by nexmann** [iterative/dvc#7773]
# Bug Report

Not entirely sure whether this is a bug that relates to DVC implementation, configuration or bug in a dependency.

## Description

We have problems using dvc pull on an Azure VM. The pull refers to an Azure Blob storage that holds the DVC registry.
When using DVC pull locally, the download speed is very fast, but trying to pull the data on an Azure virtual machine completely kills the performance.

The disk is an SSD and should not be the limiting factor. AzCopy on the same machine works with expected speed.
Average dvc pull speed over 5 min: 500 Kb/s
Average AzCopy speed over 5 min: 100 Mb/s

### Reproduce

```console
$ dvc pull data/resized.dvc
```

### Expected

Download speed performance close to what we see when using dvc pull locally.

### Environment information

```console
$ dvc doctor
DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.8.13 on Linux-5.11.0-1021-azure-x86_64-with-glibc2.17
Supports:
        azure (adlfs = 2021.9.1, knack = 0.9.0, azure-identity = 1.7.1),
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.5)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb1
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sdb1
Repo: dvc (subdir), git
```

**Comment by daavoo** [comment]
Hi @nexmann . Could you try with the latest DVC version `2.10.` and  share a the profiler output for:

```
pip install viztracer
dvc pull data/resized.dvc --viztracer-depth 8
```

**Comment by nexmann** [comment]
Hi @daavoo 
After updating DVC it seemed to help a bit with the speed. Which I find a little odd as it worked locally with full speed on the old version. I ran a subset of the pull with the profiler for you and have attached the output.

It still seems like the concurrency of downloading does not work optimally.

[viztracer.dvc-20220518_144711.zip](https://github.com/iterative/dvc/files/8718291/viztracer.dvc-20220518_144711.zip)

**Comment by daavoo** [comment]
> It still seems like the concurrency of downloading does not work optimally.

Indeed. Thanks for tharing the profile. 

We are aware about some issues regarding our current concurrency implementation and we are currently working on it. We will hopefully have some progress in upcoming releases.

Most likely, the difference in performance is related with your local machine having more compute resources than the VM. You can try reducing the number of concurrent jobs to see if that aliviates part of the issue in the VM (https://dvc.org/doc/command-reference/pull#-j)

**Comment by nexmann** [comment]
Okay sounds good. Thanks for your help!
