### ISSUE TITLE
add: symlinks to `.dvc/cache/ha/sh` but creates `.dvc/cache/ha/sh.csv`

### ISSUE THREAD

**Issue by awadell1** [iterative/dvc#7775]
## Description

When adding files `dvc add ny.csv`, the files are correctly moved to the cache as`.dvc/cache/ae/78daccbcbb27cd66956368c36bdd8f.csv`. However, the created symlink points to `.dvc/cache/ae/78daccbcbb27cd66956368c36bdd8f` (missing the extension). This results in a dead link.

### Reproduce

1. Enable symlinks `dvc config cache.type symlink`
2. Create a dvc repo within a Google Drive Folder on a Mac M1 (Idk if this is critical) `dvc init`
3. `touch foo.csv && dvc add foo.csv`
4. Confirm that cache contains a file with a hash but points to a file without it

### Expected

I expect the created symlink to not be dead on creation.

### Environment information

```console
DVC version: 2.10.2 (brew)
---------------------------------
Platform: Python 3.9.12 on macOS-12.3.1-arm64-arm-64bit
Supports:
        azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.10.0),
        gdrive (pydrive2 = 1.10.1),
        gs (gcsfs = 2022.3.0),
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.3.0, boto3 = 1.21.21),
        ssh (sshfs = 2022.3.1),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7)
```

**Additional Information (if any):**

I have been unable to reproduce this in a test example. I suspect the issue is with Google Drive more than dvc, but I figured I'd drop a line.

Thanks for a fantastic tool!

**Comment by tirkarthi** [comment]
I am unable to reproduce this locally on Linux using local filesystem. Docs in creating files through API indicate that google drive might add an extension based on file's mime-type.

https://developers.google.com/drive/api/v3/reference/files/create

> Subsequent GET requests include the read-only fileExtension property populated with the extension originally specified in the name property. When a Google Drive user requests to download a file, or when the file is downloaded through the sync client, Drive builds a full filename (with extension) based on the name. In cases where the extension is missing, Google Drive attempts to determine the extension based on the file's MIME type.

**Comment by pared** [comment]
@awadell1 
What exactly is `google drive folder` in that case? How do you mount it on your mac?

**Comment by dberenbaum** [comment]
> Docs in creating files through API indicate that google drive might add an extension based on file's mime-type.

This seems like a plausible cause. Even if I upload a csv and then remove the file extension in Google Drive, it will get added back when I download it. If the file is created with a csv mime type, an extension might be added.

Does this issue belong in https://github.com/iterative/PyDrive2?

**Comment by shcheklein** [comment]
> Does this issue belong in https://github.com/iterative/PyDrive2?

Doesn't seem so. This is specific to the Google Drive Mac app it looks like? (`dvc push`, `dvc pull` are not involved at all so `PyDrive2` is not even touched). @awadell1 I think the best way to avoid this is to use `dvc remote` command, `dvc push` / `dvc pull` to synchronize the cache to /from `.dvc/cache` to your Google Drive.

**Comment by awadell1** [comment]
Gotcha, thank you!
