### ISSUE TITLE
`diff`: shows all files as renamed for repo created using `init --subdir`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7776]
@efiop looks like the change that introduce the [renamed](https://github.com/iterative/dvc/issues/7756#issuecomment-1129443387) issue was this one: https://github.com/iterative/dvc/commit/a80a85e6bd144189bf63df535483ae628136ce14.

Was there anything in there that would make a subrepo exhibit this diff no matter what (`~/vscode-dvc` is the git repo, `~/vscode-dvc/demo` is the dvc project):

```bash
~/vscode-dvc/demo ❯  dvc diff
Renamed:                                                              
    demo/data/MNIST/raw/ -> data/MNIST/raw/
    demo/data/MNIST/raw/t10k-images-idx3-ubyte -> data/MNIST/raw/t10k-images-idx3-ubyte
    demo/data/MNIST/raw/t10k-images-idx3-ubyte.gz -> data/MNIST/raw/t10k-images-idx3-ubyte.gz
    demo/data/MNIST/raw/t10k-labels-idx1-ubyte -> data/MNIST/raw/t10k-labels-idx1-ubyte
    demo/data/MNIST/raw/t10k-labels-idx1-ubyte.gz -> data/MNIST/raw/t10k-labels-idx1-ubyte.gz
    demo/data/MNIST/raw/train-images-idx3-ubyte -> data/MNIST/raw/train-images-idx3-ubyte
    demo/data/MNIST/raw/train-images-idx3-ubyte.gz -> data/MNIST/raw/train-images-idx3-ubyte.gz
    demo/data/MNIST/raw/train-labels-idx1-ubyte -> data/MNIST/raw/train-labels-idx1-ubyte
    demo/data/MNIST/raw/train-labels-idx1-ubyte.gz -> data/MNIST/raw/train-labels-idx1-ubyte.gz
    demo/misclassified.jpg -> misclassified.jpg
    demo/model.pt -> model.pt
    demo/predictions.json -> predictions.json
    demo/training_metrics.json -> training_metrics.json
    demo/training_metrics/ -> training_metrics/
    demo/training_metrics/scalars/acc.tsv -> training_metrics/scalars/acc.tsv
    demo/training_metrics/scalars/loss.tsv -> training_metrics/scalars/loss.tsv
```

I can see that scmrepo got bumped from `0.0.19` to `0.0.22` in that commit.

LMK if you want a separate issue for this.

Thanks.

_Originally posted by @mattseddon in https://github.com/iterative/dvc/issues/7756#issuecomment-1129633756_

**Comment by efiop** [comment]
@mattseddon Reports that this could still be the case on windows. Need to double check.

**Comment by mattseddon** [comment]
Looks like this is a symptom of #7909. Using the appropriate cwd (capitalised drive) gives the correct results.
