### ISSUE TITLE
Version 2.8.0 introcuces a breaking change, without stating in the Release Notes.

### ISSUE THREAD

**Issue by yannickfunk** [iterative/dvc#7793]
Version 2.8.0 introduces a breaking change because it bumps dvclive from 0.3.0 to 0.4.0 which [introduces a breaking change](https://github.com/iterative/dvclive/releases/tag/0.4.0).

I know dependency versions are bumped automatically by dependabot. But at least for dependencies inside the dvc ecosystem it would be nice if I could only scan one changelog to check, if a new version will break my experiment.

**Comment by daavoo** [comment]
Hi @yannickfunk . Sorry for the inconvenience. 

As far as I know, `dvclive` was not a `dvc` dependency in `2.8.0`:

https://github.com/iterative/dvc/blob/d2edbae7e3ef056f4e267a9036c6d4e38e0b7d06/setup.cfg#L33-L79

It was only listed as a `test` dependency.

Starting in dvc `2.10.2`, `dvclive` is now a pinned dependency in `dvc`:

https://github.com/iterative/dvc/blob/c81d841fd75d5a965613905689db174df3b5585d/setup.cfg#L77

And will be treated as any other dependency.

**Comment by yannickfunk** [comment]
Thank you for the clarification, I think the problem here was that I had installed dvclive separately, and when I updated dvc to a new version which included dvclive as a dependency, it automatically updated dvclive.
