### ISSUE TITLE
plots: use line types to differentiate in multi-line plots

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7809]
For example, when plotting train vs. test, use solid lines for train and dashed for test.

> how does DVC render assign colors in this case? It feels it can also benefit greatly if we do different line types of the same color per revision.

_Originally posted by @shcheklein in https://github.com/iterative/vscode-dvc/issues/1757#issuecomment-1135281671_

**Comment by daavoo** [comment]
I think this requires sister issue in https://github.com/iterative/dvc-render

**Comment by dberenbaum** [comment]
Duplicate of #8970
