### ISSUE TITLE
Windows - dvc plots show incorrect directory structure for manual plot images.

### ISSUE THREAD

**Issue by dfossl** [iterative/dvc#7812]
# Bug Report

## Description

On windows, when using a saved .png of a matplotlip plot for visualization with 'dvc plots show' the default img src is "dvc_plots\static\workspace_<file name>.png" 
When it should be "static\workspace_<file name>.png"

### Reproduce
```console
mkdir example
cd example
git init
dvc init
```
With this script as evaluate.py
```python
import os

from dvclive import Live
from matplotlib import pyplot as plt

live = Live("evaluation")

y_true = [0, 0, 1, 1]
y_pred = [0.2, 0.5, 0.3, 0.8]
live.log_plot("roc", y_true, y_pred)

fig, axes = plt.subplots(dpi=100)
fig.subplots_adjust(bottom=0.2, top=0.95)
plt.scatter([1,2,3], [4,5,6])
fig.savefig(os.path.join("evaluation", "importance.png"))
```

Running this command (Powershell 7):
```shell
dvc run -n evaluate `
-d .\evaluate.py `
--plots-no-cache .\evaluation\plots\roc.json `
--plots evaluation\importance.png `
python .\evaluate.py
```
Followed by:
```shell
dvc plots show
```
Results in directory:
```
dvc_plots
    |-index.html
    |-static\
        |-workspace_evaluation_importance.png
```
Where the img src is:
```html
 <img src="dvc_plots\static\workspace_evaluation_importance.png">
```

html page:
![image](https://user-images.githubusercontent.com/55428038/170374869-2d100bb6-0d34-4695-88e5-dea2da0338e7.png)

### Expected

Should be:
```html
 <img src="static\workspace_evaluation_importance.png">
```
html page:
![image](https://user-images.githubusercontent.com/55428038/170374965-cf1b6763-a247-42e0-a45b-8ebb0ca09848.png)

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.10.4 on Windows-10-10.0.17763-SP0
Supports:
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by pared** [comment]
Good catch! It should be partially fixed by:
https://github.com/iterative/dvc/pull/7664

We need to wait for a next release for that.

Proper fix will come after we merge and release iterative/dvc-render#39

**Comment by pared** [comment]
Leaving it open till we finish all the needed changes.
