### ISSUE TITLE
get: support git remotes

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7814]
It would be nice to support `dvc get origin models/model.h5`. It seems unnecessary to have to type out the full URL for a known Git remote.

Edit: The context for this request is in https://github.com/iterative/dvc.org/pull/3593.

**Comment by daavoo** [comment]
How would you differentiate the git remote name from a local path? 

From https://dvc.org/doc/command-reference/get#description:

> url can also be a local file system path (including the current project e.g. .).

**Comment by karajan1001** [comment]
`-g origin` to keep consist with other commands (dvc exp remove) .
