### ISSUE TITLE
`dvc plots show`: Allow for setting output directory via config or `dvc.yaml`

### ISSUE THREAD

**Issue by mseflek** [iterative/dvc#7816]
Currently the output directory (default `dvc_plots/`) for the HTML file produced by `dvc plots show` can only be defined via the command's `-o` flag. It would be great if it could be set via `dvc.yaml` or the config files so that running `dvc plots show` automatically saves the file in a predefined place. This would make it more seamless to use in projects with a well-defined directory structure.

**Comment by dberenbaum** [comment]
@pared @daavoo How hard do you think this would be? Would it make a good first issue?

**Comment by daavoo** [comment]
> @pared @daavoo How hard do you think this would be? 

I think not much, but probably there are some gotchas.

> Would it make a good first issue?

Maybe not, because of the gotchas.

**Comment by pared** [comment]
I don't see any bigger problems at first sight. We already have a config section for plots, there is only one actual line addressing `dvc_plots`, in  `plots` command code. We can access the repo there too... there might be a problem with no repo situation, but AFAIR getting config there will result in an empty dict.

**Comment by pared** [comment]
I would consider it for first issue.
