### ISSUE TITLE
plots: smart legend labeling

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7830]
Background:

* https://github.com/iterative/dvc/pull/7477#discussion_r868405583
* https://github.com/iterative/dvc/issues/7086#issuecomment-1125169586

After https://github.com/iterative/dvc/pull/7477, the legend can sometimes be too long. Removing the common parts of the legend would make it easier to read.

Also, in https://github.com/iterative/dvc/issues/7086, the y-axis isn't read from the column name even though the column name is the same in both files.

**Comment by dberenbaum** [comment]
@pared It looks like this is already addressed in #7477?

**Comment by pared** [comment]
Yes, it should be working now.

**Comment by pared** [comment]
Though I still believe we should make a change in the plots templates to address @daavoo's [idea](https://github.com/iterative/dvc/pull/7477#discussion_r868406280)

**Comment by dberenbaum** [comment]
Closing in favor of #8325

**Comment by dberenbaum** [comment]
Reopening since I think there are still improvements to make here. For example:

<img width="547" alt="Screenshot 2022-11-21 at 3 45 29 PM" src="https://user-images.githubusercontent.com/2308172/203154935-2b5c1d3f-d1a1-4fc9-9bd1-3a7a7101e43d.png">

Some possible improvements:
1. In the title, including the directory path might be useful, but I think we can omit the `dvc.yaml` filename. What other file could the configuration be coming from?
2. In the legend, `training/plots/metrics` are the same for all entries, so can we omit it?
3. The full rev is cut off but is actually `training/plots/metrics/train/acc.tsv::train/acc`. `train/acc` is redundant. One way to shorten it would be to omit the paths unless the field names conflict. Another would be to shorten the name in dvclive from `train/acc` to `acc` since `train` is already in the path (or log all dvclive metrics to one file).
