### ISSUE TITLE
Unable to pull from gdrive, file identified as malware

### ISSUE THREAD

**Issue by M-Puig** [iterative/dvc#7832]
Hi, I started following the hands-on tutorial and pushed an example file to my gdrive and tried to retrieve it using dvc pull, and I get the following error.

`<HttpError 403 when requesting *www.googleapis.com link* returned "This file has been identified as malware or spam and cannot be downloaded". Details: "[{'domain': 'global', 'reason': 'abuse', 'message': 'This file has been identified as malware or spam and cannot be downloaded'}]">`

The gdoc documentation specifies an argument `acknowledgeAbuse=true` to pass to override this error but I don't think I can pass it through the DVC wrapper.

Is this issue known ? Any way to bypass this ? Thanks

**Comment by M-Puig** [comment]
Just the one on the dvc.org [(https://dvc.org/doc/start/data-management
)]
I used the conda install

**Comment by jorgeorpinel** [comment]
Thanks. Actually could you also share the output of `dvc doctor` for the core team? Thanks again

**Comment by M-Puig** [comment]
`$ dvc doctor
DVC version: 2.10.2 (conda)
---------------------------------
Platform: Python 3.10.4 on Windows-10-10.0.22000-SP0
Supports:
        gdrive (pydrive2 = 1.10.1),
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: gdrive
Workspace directory: NTFS on C:\
Repo: dvc, git
`

**Comment by dberenbaum** [comment]
@M-Puig Is this happening consistently for you or is it intermittent?

> The gdoc documentation specifies an argument `acknowledgeAbuse=true` to pass to override this error but I don't think I can pass it through the DVC wrapper.

@iterative/dvc It seems like it should be easy for someone to contribute a PR to add this to the config options, but where would they need to do it?

**Comment by M-Puig** [comment]
It is happening consistently with my main google account, with which I never used googleAPI previously. Didn't try with other accounts, just moved away from gdrive

**Comment by DarwinCV** [comment]
I have the same problem on ubuntu 22.04 , here the output of dvc doctor

```
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.9.12 on Linux-5.15.0-39-generic-x86_64-with-glibc2.35
Supports:
	gdrive (pydrive2 = 1.10.1),
	webhdfs (fsspec = 2022.2.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.8),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.8)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p4
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/nvme0n1p4
Repo: dvc, git
```
Maybe some solution ?

**Comment by efiop** [comment]
We use https://github.com/iterative/PyDrive2 as a backend. Looks like that option needs to be set somewhere in https://github.com/iterative/PyDrive2/blob/master/pydrive2/files.py , but I haven't looked at it too close yet.

**Comment by bajaj** [comment]
I too got this issue.

```
dvc doctor
DVC version: 2.12.1 (pip)
---------------------------------
Platform: Python 3.10.4 on macOS-12.3.1-x86_64-i386-64bit
Supports:
	gdrive (pydrive2 = 1.10.1),
	webhdfs (fsspec = 2022.5.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.5.1),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.5.1)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: gdrive
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Comment by peterbonnesoeur** [comment]
Thank you @bajaj  🙏

**Comment by bonpur** [comment]
@bajaj on what line number should i add the acknowledgeAbuse=True ?

Sorry for my noob question

**Comment by bonpur** [comment]
> @peterbonnesoeur Edit the `<python_env>/lib/python3.10/site-packages/pydrive2/files.py` & set the `acknowledgeAbuse=True`. Check this - [iterative/PyDrive2#62](https://github.com/iterative/PyDrive2/pull/62)

on what line number should i add the acknowledgeAbuse=True ?

Sorry for my noob question

**Comment by bonpur** [comment]
> @peterbonnesoeur Edit the `<python_env>/lib/python3.10/site-packages/pydrive2/files.py` & set the `acknowledgeAbuse=True`. Check this - [iterative/PyDrive2#62](https://github.com/iterative/PyDrive2/pull/62)

i did exactly but still got that false identified 403 error

with open(filename, mode="w+b") as fd:
            # Should use files.export_media instead of files.get_media if
            # metadata["mimeType"].startswith("application/vnd.google-apps.").
            # But that would first require a slow call to FetchMetadata().
            # We prefer to try-except for speed.
            try:
                download(fd, files.get_media(fileId=file_id, acknowledgeAbuse=True))
            except errors.HttpError as error:
                exc = ApiRequestError(error)
                if (
                    exc.error["code"] != 403
                    or exc.GetField("reason") != "fileNotDownloadable"
                ):

error :
AppData\Local\Programs\Python\Python310\lib\site-packages\pydrive2\files.py", line 343, in GetContentFile
    raise exc
pydrive2.files.ApiRequestError: <HttpError 403 when requesting 

please help

**Comment by efiop** [comment]
@bonpur You didn't post the error though (it seems cut off). But I suggest you just wait for this feature to be added to dvc and pydrive2 (I'm working on it right now).

**Comment by bonpur** [comment]
> @bonpur You didn't post the error though (it seems cut off). But I suggest you just wait for this feature to be added to dvc and pydrive2 (I'm working on it right now).

ah sorry i'm new to python and github. Here is the full error:

Traceback (most recent call last):
  File "d:\PYTHON\fungsi_gdrive.py", line 165, in GDRIVE_DOWNLOAD_FILE_D
    GDRIVE_V.CreateFile({'id': FILE_ID_V}).GetContentFile(LOCAL_PATH_V)
  File "C:\Users\BNP\AppData\Local\Programs\Python\Python310\lib\site-packages\pydrive2\auth.py", line 84, in _decorated
    return decoratee(self, *args, **kwargs)
  File "C:\Users\BNP\AppData\Local\Programs\Python\Python310\lib\site-packages\pydrive2\files.py", line 343, in GetContentFile
    raise exc
pydrive2.files.ApiRequestError: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files/1UTIckmjK1QIoEyqaCFG80qlK79KJhWBI?acknowledgeAbuse=true&alt=media returned "This file has been identified as malware or spam and cannot be downloaded". Details: "[{'domain': 'global', 'reason': 'abuse', 'message': 'This file has been identified as malware or spam and cannot be downloaded'}]">

**Comment by efiop** [comment]
@bonpur It is not. We'll close this once it is ready. ETA is tomorrow.

**Comment by efiop** [comment]
dvc 2.14.0 is out with `gdrive_acknowledge_abuse` config option. Please give it a try

```
$ dvc remote modify myremote gdrive_acknowledge_abuse true
```

**Comment by bonpur** [comment]
> dvc 2.14.0 is out with `gdrive_acknowledge_abuse` config option. Please give it a try
> 
> ```
> $ dvc remote modify myremote gdrive_acknowledge_abuse true
> ```

@efiop sorry to ask. what is dvc ?

**Comment by bonpur** [comment]
@efiop can you add for service account too? because i still got this malware problem if using service account

**Comment by efiop** [comment]
@bonpur I think it should work with service account too. Please make sure you are using latest dvc and pydrive2 versions and post verbose log for the error you are getting.

**Comment by aliahari** [comment]
> dvc 2.14.0 is out with `gdrive_acknowledge_abuse` config option. Please give it a try
> 
> ```
> $ dvc remote modify myremote gdrive_acknowledge_abuse true
> ```

maybe it makes sense to add it to the hands on tutorial
