### ISSUE TITLE
add --to-remote usage when rolling back versions 

### ISSUE THREAD

**Issue by Joe-McC** [iterative/dvc#7850]
## My Use Case
My current setup involves using a mounted RAID drive to store large datasets, with the plan being to setup the dvc workspace on the local filesystem, ideally tracking datasets without the need to pull the data locally due to space issues. 

## Problem
Following the [docs](https://dvc.org/doc/user-guide/managing-external-data), I initially attempted to manage the remote files using the add:--remote-file option i.e. ```dvc add 'remote/path/file' --to-remote -o file```, although its usage suggests that at any time you wish to do roll back to an older version of the data (i.e. ```dvc checkout``` ), a pull to the local workspace is required (i.e.```dvc pull``` ).

Is there a mode of operation where remote files can be tracked and rolled back to earlier versions without the need to pull into the local workspace? Again, the [docs](https://dvc.org/doc/user-guide/managing-external-data) suggest the ```--external``` flag is able to perform the above operation, although not recommended.

**Comment by karajan1001** [comment]
I think you can just git checkout to an older version. As all versions of the data are already on your remote storage. And what you only need is to change the pointer (`.dvc`) value.

**Comment by Joe-McC** [comment]
But then I would still need to ```dvc pull``` the latest version of the data to my local workspace at some point (as the .dvc pointer points to the md5 files which need to be pulled)? I think what I'm looking for is maybe the ```--external``` argument to track all of my data externally without the need to ever copy to the local workspace, although as stated ```--external``` is not recommended in the docs:  

> This is an advanced feature for very specific situations and not recommended except if there's absolutely no other alternative. In most cases, alternatives like the [to-cache](https://dvc.org/doc/command-reference/add#example-transfer-to-an-external-cache) or [to-remote](https://dvc.org/doc/command-reference/add#example-transfer-to-remote-storage) strategies of [dvc add](https://dvc.org/doc/command-reference/add) and [dvc import-url](https://dvc.org/doc/command-reference/import-url) are more convenient. Note that external outputs are not pushed or pulled from/to [remote storage](https://dvc.org/doc/command-reference/remote).

Is there a specific reason why it is not recommended? And if so, is this a unecessary feature, or is it acceptable for use in a use case like mine?

**Comment by karajan1001** [comment]
> But then I would still need to `dvc pull` the latest version of the data to my local workspace at some point (as the .dvc pointer points to the md5 files which need to be pulled)? I think what I'm looking for is maybe the `--external` argument to track all of my data externally without the need to ever copy to the local workspace, although as stated `--external` is not recommended in the docs:
> 
> > This is an advanced feature for very specific situations and not recommended except if there's absolutely no other alternative. In most cases, alternatives like the [to-cache](https://dvc.org/doc/command-reference/add#example-transfer-to-an-external-cache) or [to-remote](https://dvc.org/doc/command-reference/add#example-transfer-to-remote-storage) strategies of [dvc add](https://dvc.org/doc/command-reference/add) and [dvc import-url](https://dvc.org/doc/command-reference/import-url) are more convenient. Note that external outputs are not pushed or pulled from/to [remote storage](https://dvc.org/doc/command-reference/remote).
> 
> Is there a specific reason why it is not recommended? And if so, is this a unecessary feature, or is it acceptable for use in a use case like mine?

`--to-remote` and `--external` are for different use cases. For, `--to-remote` it is used if both the data and the calculation were on a remote server,  and you want to do some data management locally. While, for `--external` it's use case is you have a large dataset can only be stored remotely and besides your remote server do not provide the ability to crunch it. In this case, your calculation resource and resource for storage are separated, and the data transfer between these two places will greatly harm the performance.

**Comment by efiop** [comment]
closing in favor of https://github.com/iterative/dvc/issues/3920
