### ISSUE TITLE
exp queue: handle failed experiments

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#7854]
* [x] display failed exps in `dvc queue`
* [x] expose logs for completed (failed and successful) exps in `dvc queue logs`

Related to https://github.com/iterative/dvc/issues/7590

**Comment by dberenbaum** [comment]
> * expose logs for completed (failed and successful) exps in `dvc queue logs`

Is the plan to have separate commands for `dvc queue logs` and `dvc queue attach`? I think we can have one command that returns logs for running, failed, and successful experiments. Do you see a reason to keep two commands?

**Comment by pmrowla** [comment]
I think it makes more sense to just have `queue logs [-a/--attach]` (or maybe just `[-f/--follow]` instead of attach). So by default it will dump the available logs for any exp (running or done) and with `-f` it stays open and continues reading (assuming the exp is running)
