### ISSUE TITLE
dvc push: misleading error message for SSH remote when SSH user does not have permissions

### ISSUE THREAD

**Issue by dmitry-kabanov** [iterative/dvc#7861]
# Bug Report

## Description

I set an SSH remote and try to `dvc push` to it.
I get errors message "No such file or directory" although the problem is that the SSH user does not have file permissions. It would be much easier to debug if the error message is something like "permission denied".

### Reproduce

1. dvc init
2. dvc get https://github.com/iterative/dataset-registry \
          get-started/data.xml -o data/data.xml
3. dvc add data/data.xml
5. dvc remote add -d storage ssh://username@host/path-to-directory where `username` does not have write access to `/path-to-directory`.
6. Observe error messages "no such file or directory", which do not help to understand that the problem is with the write permissions.

### Expected

After `dvc push` I expect to see error messages like "SSH user `username` does not have file permissions to write the given path".

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

➜ dvc doctor                                      
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.10.4 on Linux-5.4.0-81-generic-x86_64-with-glibc2.27
Supports:
	webhdfs (fsspec = 2022.5.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	ssh (sshfs = 2022.6.0)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sda
Repo: dvc, git

**Additional Information (if any):**

**Comment by dtrifiro** [comment]
Thanks for reporting this! I linked a small patch which will improve the error messages when running with debug flags (`-v`)

**Comment by dtrifiro** [comment]
Will be fixed once `dvc-data==0.0.7` is released
