### ISSUE TITLE
ui: link type errors pollute debugging logs

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#7865]
When running commands with `-v` we end up dumping link error tracebacks that are expected (like when we are on an FS that doesn't support reflinks). This ends up leading to confusing bug reports on GH and in other support channels like discord, since users assume that the link failure is the problem, when in actuality it is something else entirely. This occurs even in commands that aren't using checkout.

some examples:
https://github.com/iterative/dvc/issues/7506
https://github.com/iterative/dvc/issues/7863

may be due to calling `test_links` in `dvc.info` (which is run any time we encounter other errors) without handling/suppressing the link warnings in the `info` call

https://github.com/iterative/dvc/blob/a3ee993739420c3f84eccdfb3bbc1b3ac0da14e9/dvc/info.py#L77-L86

**Comment by alexmojaki** [comment]
The tracebacks are explicitly logged in `dvc_objects.fs.generic._test_link`:

```python
def _test_link(
    link: "str",
    from_fs: "FileSystem",
    from_file: "AnyFSPath",
    to_fs: "FileSystem",
    to_file: "AnyFSPath",
) -> bool:
    try:
        _try_links([link], from_fs, from_file, to_fs, to_file)
    except OSError:
        logger.debug("", exc_info=True)
        return False
```

`_test_link` seems to only be called by `test_links`.

I think it'd be sensible to replace `logger.debug("", exc_info=True)` with something like:

```python
logger.debug("Link %s failed with error %s", some_description, exception)
```

**Comment by dtrifiro** [comment]
I would also opt for removing `exc_info=True`. Are there any cases in which a full traceback can yield useful information though?
