### ISSUE TITLE
dvc pull: progress bar inserts new lines when run from JupyterLab Notebook/Console

### ISSUE THREAD

**Issue by adin786** [iterative/dvc#7875]
# Bug Report

## Description

**Background:** I am using dvc just to control data file versions.  I have a Git repository cloned which contains `.dvc` files for tracking data that has separately been through `dvc add` and `dvc push` to upload it to an S3 bucket as the dvc remote.  I have been able to run `dvc pull` to a fresh clone of the repository, from the usual commandline (MacOS) and the download progress bar shows nicely on one line as it is supposed to.

**The issue:** However now if I am to execute `!dvc pull` from inside a Jupyter notebook cell or console, it is working fine and downloading the data, except the progress bar output seems to be writing to a new line every time it increments.

Note: it's `!dvc pull` with the `!` prefix, because I'm telling the Jupyter notebook to execute this line as a bash command.  I am not completely sure whether the issue is with dvc's progress bar and if it doesn't play nicely with the notebook's text output, or if it is an issue on the Jupyter side, but I know that things like `!pip install <package>` which also outputs a progress bar works fine when executed from a notebook cell this way.  Leads me to think it is a dvc issue.

**Why run dvc pull from a notebook cell:** I am really trying to set up my development environment, datafiles etc inside a SageMaker Studio instance, which is basically a cloud hosted version of JupyterLab.  In this environment I don't have straightforward access to a bash terminal, so the easiest way is to run `!pip install dvc dvc[s3]` then try `!dvc pull` as above, all from inside a notebook cell.  This is where I see the bug and I can replicate it both from a local JupyterLab environment, and the SageMaker hosted one.

### Reproduce

1. Clone a Git repo and put some large-ish data files in the folder (enough to see a meaningful progress bar during the later `dvc pull` step)
2. Configure dvc for the repo with a dvc-remote
3. Track the data files and push to dvc-remote using `dvc add...`, `dvc push`, 
4. Track the .dvc files with Git using `git add...`, `git commit...`, `git push`
5. Clone the folder to somewhere else on the same machine, or a different one using `git clone...`
7. Open a Jupyter Notebook inside the new copy of the repo, run `!dvc pull` from inside a notebook cell

### Expected

Progress bar dynamically updates up as the files download, filling up the bar all one one line (or a few lines if dvc tried to do multiple files in parallel).

### Environment information

MacOS 12.4 x86
Same behaviour observed inside a Linux x86 cloud instance

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.0.18 (conda)
---------------------------------
Platform: Python 3.9.7 on macOS-12.4-x86_64-i386-64bit
Supports: hdfs, http, https, s3
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s7s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s7s1
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by dtrifiro** [comment]
Hey.
Thanks for reporting this. I can confirm this is happening

Just a note: I did a quick check for `tqdm`'s behaviour using the following code:
```bash
!for i in {1..10}; do echo $i && sleep 1; done | tqdm --total=10
```
and it behaves properly. So it's probably something on our side.

`rich`'s demo also shows the same behaviour:

```!python -m rich.progress```


Just as a curiosity: I see that you're running `dvc==2.0.18`, which is fairly old (more than 1 year old). Is there a particular reason why you haven't been updating to a more recent version?
