### ISSUE TITLE
dvc remote rename: does not change config.local

### ISSUE THREAD

**Issue by tibor-mach** [iterative/dvc#7880]
# Bug Report

## Description
dvc remote rename does not change the remote name in `.dvc/config.local`. This has two effects:
1. after `dvc remote rename <old_remote_name> <new_remote_name>` , the following error message pops up (for an azure remote, it will differ slightly for a different remote):
```
ERROR: configuration error - config file error: expected 'url' for dictionary value @ data['remote'][<old_remote_name>]
```
2. After the previous command, ``dvc remote rename <new_remote_name> <old_remote_name>`` does not work, since the old name is still present in the config.local and you get the following error message:
```
ERROR: configuration error - config file error: Rename failed. Remote name '{<old_remote_name>}' already exists.
```

### Reproduce

1.` dvc init`
2. `dvc remote add -d <old_remote_name> azure://container/`
3.  `dvc remote modify <old_remote_name> account_name <my_account_name>`
4. `dvc remote modify --local <old_remote_name> account_key <my_account_key>`
5. `dvc remote rename <old_remote_name>  <new_remote_name>` (here we get the first error above)
6. `dvc remote rename <new_remote_name> <old_remote_name>` (here we get the second error above)

### Expected
`dvc remote rename` should also rename the repo in `config.local`.

### Environment information

- OS: Manjaro Linux x86_64
- Python 3.10.4
- dvc==2.11.0 (installed with pip)

**Output of `dvc doctor`:**

identical to the two errors above.

**Additional Information:**
The root of the problem is probably with the fact that `dvc remote rename` apparently checks for the validity of a config file before renaming, but the `config.local` file is not valid as it is missing the `url` and so it is not renamed.

**Comment by karajan1001** [comment]
The problem is that currently all of the modifications on `config` only affect its lower levels. In your case, as your operation is towards the `project` level, it will only affect `project` and the lower level `global` and `system` while keeping configurations in the `local` level untouched.
