### ISSUE TITLE
queue status: show the status of the worker 

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#7900]
> 2. How can we check if the queue is active/running/processing?

For now I think we can just add this to `queue status` (start the output with line(s) listing the number of running workers). Eventually it will probably be worth it to have a `queue ps` or `queue proc` command for getting details about each worker, but for now `status` should at least indicate whether or not the queue worker is actively running.

_Originally posted by @pmrowla in https://github.com/iterative/dvc/issues/7592#issuecomment-1151880967_

**Comment by pmrowla** [comment]
closed in https://github.com/iterative/dvc/pull/7903
