### ISSUE TITLE
plots: Support plots directories in `dvc.yaml:plots`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7914]
Can we support whole directories in the `plots` section of `dvc.yaml`? Example:

```yaml
plots:
  plots_dir:
```

**Comment by pared** [comment]
Not yet, we can include it in scope of #7477 or follow up.

**Comment by daavoo** [comment]
> Not yet, we can include it in scope of https://github.com/iterative/dvc/pull/7477 or follow up.

I vote (to be prioritized) follow-up. IMO, there is already too much in the current P.R.

**Comment by shcheklein** [comment]
Can we clarify that this is about (only?) flexible plots? Or does it apply to the other types (e.g.  being able to configure directories granularly?)

**Comment by dberenbaum** [comment]
Yes @shcheklein, it is only about plots configured under the `plots` section of `dvc.yaml`, not under `stages`. There is also #6670 that addresses what I think you are asking.

**Comment by dberenbaum** [comment]
@pared Is this something you have time to address soon? I think it makes sense to prioritize it soon so we have feature parity with stage plots.
