### ISSUE TITLE
Import-url no download

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#7918]
In some cases, user needs to keep connection to a storage file in a repository but does not need to work with the model (or data) right now. `--no-exec` option is not enough because user needs to track if file changes (cloud checksums are needed) and user should have an ability to check this status in the future.

So, we need a more granular `import-url`:

- [ ] `dvc-import --no-download` (the same as `﻿--etags-only` in #6485) which is  like ﻿--no-exec but it sets cloud storage checksums
- [ ] Check for `dvc-import` (how about `--check-only` option?) which checks if file was changed in cloud storage (exit status not zero) or file is the same (zero exist status). Can we do this with status btw?

This issue is related to #6485

**Comment by casperdcl** [comment]
`dvc import --no-download` makes sense. Meanwhile for `dvc import --check-only`... not sure I follow, but sounds more like a use case for `dvc status` or #5369?

**Comment by skshetry** [comment]
> `dvc import --no-download` makes sense. Meanwhile for `dvc import --check-only`... not sure I follow, but sounds more like a use case for `dvc status` or #5369?

`dvc import` and `dvc mport-url` created stages are frozen by default, so `dvc status` will not return any outputs (unless we opt to make them non-frozen in case of `--no-download` which I think is a different behaviour than default imports which we should not do).

The `--check-only` might fit better in `dvc update` command.

**Comment by dberenbaum** [comment]
Yes, either `update` or `status` flags would make sense. We don't want users to have to recreate the whole `import-url` to find out whether the source has changed.
