### ISSUE TITLE
UI progress bar for computing hashes

### ISSUE THREAD

**Issue by justusschock** [iterative/dvc#7922]
Hi,

I regularly add large directories with many many files to dvc storages. All works fine, but I just don't know how long it takes.
Most of the steps are well shown when it comes to progress, but for computing the file/dir hashes, there is virtually no way to know how long it takes.

My Proposal: After initially scanning for files, it should be known, for how many files we have to compute hashes for. Just make the line from 

`Computing file/dir hashes (only done once)                                                | 2.33M [42:05, 1.33kmd5/s]` 

a real progressbar. It does not even have to show an eta (although that would be nice), but knowing how many files there are in total would already help a lot in order to estimate the overall progress :)

Thanks a lot!

**Comment by skshetry** [comment]
Note that DVC currently does not scan for files in advance, it builds a tree as it walks through them, so we don't know how many objects are there before that building process.

**Comment by justusschock** [comment]
@skshetry I see, that's a good point, thanks. Would scanning for files in advance slow things down? I guess it wouldn't (theoretically when the files are known, the hashing could also be parallelized I guess).

**Comment by efiop** [comment]
Unlike git, we mix both index building and object building together right now, but if (or more like when) we will start building an index first, we will be able to provide the total during object building.
