### ISSUE TITLE
`dvc.api.params_show`: More helpful error handling

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7926]
# Bug Report

## Description

Doesn't show useful errors.

### Reproduce

1. `git clone git@github.com:iterative/pipeline-conifguration.git`
2. `cd pipeline-conifguration`
3. Start Python shell:

```python
>>> import dvc.api
>>> dvc.api.params_show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dave/Code/dvc/dvc/api/params.py", line 267, in params_show
    return _postprocess(params)
  File "/Users/dave/Code/dvc/dvc/api/params.py", line 256, in _postprocess
    return processed[first(processed)]
KeyError: None
```

### Expected

I'm guessing it fails because there's no `dvc.yaml` or `params.yaml` in the project root where the shell is started, but the error message doesn't help me understand this or how to fix it.

**Comment by daavoo** [comment]
> I think an error in this case? I doubt there's much reason to call params_show if you expect an empty dict.

I was thinking about returning an empty dict instead of raising an exception because `dvc {X} show` commands don't fail when there is nothing to return.

> What would happen if there was a params.yaml but no dvc.yaml found? 

The contents of `params.yaml` will be returned.

> What about the inverse?

The `KeyError` point will be reached.

**Comment by dberenbaum** [comment]
> I was thinking about returning an empty dict instead of raising an exception because `dvc {X} show` commands don't fail when there is nothing to return.

Good point. I think we err on the side of not throwing errors in the CLI to avoid breaking CI scripts. If you feel the symmetry is important, I think it's fine to return an empty dict.

IMO, it's more likely to want an error here, especially for the intended use case of reading stage params into user code. I would much rather break early with a helpful error message than have to debug that `params_show()` returned an empty dict.

**Comment by dberenbaum** [comment]
A warning might be reasonable also, so at least it's not silently returning the empty dict?
