### ISSUE TITLE
dvc metrics show: scattered formatting

### ISSUE THREAD

**Issue by tibor-mach** [iterative/dvc#7940]
# Bug Report

## Description
When calling 

`dvc metrics show` has a very scattered output, making it hard to read. I use zsh as a terminal. long metrics filepaths or too many metrics might be the cause, but `dvc metrics diff` works just fine (perhaps it uses different formatting so it fits better?)
### Reproduce

1. (maybe) have long paths to metrics files or a lot of metrics
2. `dvc metrics show`

### Expected

I would expect the output to be aligned more like that of `dvc metrics diff`
### Environment information

zhs console

**Additional Information (if any):**
an example what the output looks like, first the correctly ordered `dvc metrics diff` and then the scattered `dvc metrics show`
![image](https://user-images.githubusercontent.com/56956998/175996149-9f4e9302-d948-44f4-b15a-0f4411f76be9.png)

**Comment by pmrowla** [comment]
One other thing to note would be that `dvc exp show` already uses a pager and can also be used to view your metrics in the CLI (even if you are not using any other `dvc exp` related features)

**Comment by daavoo** [comment]
I think this is already tracked in https://github.com/iterative/dvc/issues/6451
