### ISSUE TITLE
dvc commit takes too long

### ISSUE THREAD

**Issue by kohei-kawaguchi** [iterative/dvc#7946]
# Bug Report

## Description

Running `dvc commit` takes too long. It can take more than an hour. It still takes a long time even if I run `dvc commit` immediately after the previous `dvc commit` is finished, without any change in tracked files. 

### Reproduce

1. git pull
2. dvc pull
3. dvc commit 

### Expected

I expect that `dvc commit` does not take long when there are few file changes or no change. 

### Environment information

**Output of `dvc doctor`:**

```console
$dvc doctor
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.9.13 on Windows-10-10.0.22000-SP0
Supports:
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21)
```

**Additional Information (if any):**

I use Microsoft Windows 11 Home 10.0.22000 Build 22000.

The project folder and the local repository are in a network mount. I recently changed the laptop and it changed the drive letter from E to D. Because this could be the reason, I tried ii) changing the drive letter from D to E, ii) removing the existing folder with the local repository and newly git pull/dvc pull to create the folder, and ii) setting state.dir and index.dir at the C drive. Nevertheless, I encounter the same problem.

I have the same problem with multiple projects on the same device.

**Comment by pmrowla** [comment]
For reference, the issue appears to be related to slow `copyfile` on checkout, the read takes 89% of the runtime for copyfile, the actual write is 7%

![Screen Shot 2022-06-30 at 1 05 54 PM](https://user-images.githubusercontent.com/651988/176590571-6c710ad9-1f72-437f-b667-9a4c48a7b52b.png)
![Screen Shot 2022-06-30 at 1 05 42 PM](https://user-images.githubusercontent.com/651988/176590635-74ff80e7-b627-4291-ac2c-d3746f05d196.png)
![Screen Shot 2022-06-30 at 1 05 24 PM](https://user-images.githubusercontent.com/651988/176590650-757fce00-16eb-47c5-94eb-68878650f8fb.png)

(cprof report available in support email chain)

**Comment by skshetry** [comment]
Is the cache type `copy`? If it is, I'd say the issue is with unnecessary relinking.

**Comment by kohei-kawaguchi** [comment]
The cache type priority is the default reflink,copy. But copy will be effective because I use Windows.

**Comment by kohei-kawaguchi** [comment]
How can I stop the unnecessary relinking?
