### ISSUE TITLE
exp: apply should keep stash and hint at how to recover pre-apply workspace

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7955]
Related to https://github.com/iterative/dvc/issues/6930 and https://github.com/iterative/vscode-dvc/issues/1956.

When doing `dvc exp apply`, it's possible to overwrite dirty changes in your workspace. We already stash those changes to merge them as part of apply. If we retain that stash and hint to users how to recover it, we will avoid the possibility that users lose their work.

@pmrowla Do we stash untracked changes too?

**Comment by pmrowla** [comment]
> @pmrowla Do we stash untracked changes too?

Yes, we stash the untracked changes before applying
