### ISSUE TITLE
Preserve permissions and links

### ISSUE THREAD

**Issue by shortcipher3** [iterative/dvc#7959]
I have a file in that I would like to add to `dvc` that is a link to another file:

```
# ls -lh myfile
lrwxrwxrwx. 1 me me 13 Apr 19 01:04 myfile -> /usr/bin/perl
```
However after running `dvc add` and `dvc push` the permissions change and the link no longer works:

```
# ls -lh myfile
-rw-rw-r--. 1 me me 16K Jun 29 11:00 myfile
```

I'm using this file along with many others in a Docker image that I'm compiling, the package of files is provided by a third-party which occasionally gives a whole new dump of files, so I don't want to micromanage permissions after a `dvc add`.

It would be nice to have the option to preserve permissions and links in dvc.

----

My workaround is to create a tarball of the files, add that to dvc, and extract when I'm ready to build my docker image.

**Comment by pmrowla** [comment]
DVC will not preserve links to a file outside of the workspace. By definition, if you are adding it to DVC, DVC will end up copying the target of the link into the DVC cache, and then the workspace will contain a link or copy that points to the DVC cache version of the file (depending on your link settings).

Preserving the executable flag looks like it is a bug here, I don't think tracking a simlink to `/usr/bin/...` is something that DVC should be able to do.

**Comment by efiop** [comment]
Closing as stale.

**Comment by shortcipher3** [comment]
Sorry for the late reply. I was looking for DVC to track the simlink itself. The simlink isn't used on my machine, but rather in a docker image. I have a stage that uses a Dockerfile to create a docker image, the image is used with my model to help with the conversion to another format.

Let me know if you need more clarification.
