### ISSUE TITLE
Massive performance degradation in dvc 2.12.0 on Windows

### ISSUE THREAD

**Issue by aaron-meyers** [iterative/dvc#7964]
# Bug Report

dvc: massive slowdown for any dvc command in 2.12.0 vs 2.11.0 on Windows

## Description

After upgrading to the latest dvc release 2.12.0, any dvc command takes 50-100x longer than previously.

### Reproduce

Examples:
- dvc help - 664ms (2.11.0) vs 45s (2.12.0)
- dvc status - 2s (2.11.0) vs 106s (2.12.0)
- dvc doctor - 6s (2.11.0) vs 324s (2.12.0)

### Expected

Expecting similar performance in latest release (2.12.0) vs previous release (2.11.0).

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.12.0 (exe)
---------------------------------
Platform: Python 3.9.13 on Windows-10-10.0.22000-SP0
Supports:
        azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.10.0),
        gdrive (pydrive2 = 1.10.1),
        gs (gcsfs = 2022.5.0),
        hdfs (fsspec = 2022.5.0, pyarrow = 8.0.0),
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.5.0),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.5.0),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21),
        ssh (sshfs = 2022.6.0),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7)
```

**Additional Information (if any):**

I've only tried this on Windows (Windows 11 specifically) so I'm assuming it has something to do with that as I assume most users are on Linux.

**Comment by skshetry** [comment]
> * dvc help - 664ms (2.11.0) vs 45s (2.12.0)

if `dvc —help` is this slow, it might not be dvc, but due to some external factors, eg: antivirus, etc. 

Could you please send a profiling data for `dvc doctor`? Please try the following and post `doctor.prof` file here:
```console
dvc doctor —cprofile-dump doctor.prof
```

You can visualize that with `snakeviz doctor.prof`.

Here‘s more detail wiki if you need more information: https://github.com/iterative/dvc/wiki/Debugging,-Profiling-and-Benchmarking-DVC#profiling-dvc

**Comment by skshetry** [comment]
> # Bug Report
> dvc: massive slowdown for any dvc command in 2.12.0 vs 2.11.0 on Windows
> 
> ## Description
> After upgrading to the latest dvc release 2.12.0, any dvc command takes 50-100x longer than previously.
> 
> ### Reproduce
> Examples:
> 
> * dvc help - 664ms (2.11.0) vs 45s (2.12.0)
> * dvc status - 2s (2.11.0) vs 106s (2.12.0)
> * dvc doctor - 6s (2.11.0) vs 324s (2.12.0)
> 
> ### Expected
> Expecting similar performance in latest release (2.12.0) vs previous release (2.11.0).
> 
> ### Environment information
> **Output of `dvc doctor`:**
> 
> ```
> $ dvc doctor
> DVC version: 2.12.0 (exe)
> ---------------------------------
> Platform: Python 3.9.13 on Windows-10-10.0.22000-SP0
> Supports:
>         azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.10.0),
>         gdrive (pydrive2 = 1.10.1),
>         gs (gcsfs = 2022.5.0),
>         hdfs (fsspec = 2022.5.0, pyarrow = 8.0.0),
>         webhdfs (fsspec = 2022.5.0),
>         http (aiohttp = 3.8.1, aiohttp-retry = 2.5.0),
>         https (aiohttp = 3.8.1, aiohttp-retry = 2.5.0),
>         s3 (s3fs = 2022.5.0, boto3 = 1.21.21),
>         ssh (sshfs = 2022.6.0),
>         oss (ossfs = 2021.8.0),
>         webdav (webdav4 = 0.9.7),
>         webdavs (webdav4 = 0.9.7)
> ```
> 
> **Additional Information (if any):**
> 
> I've only tried this on Windows (Windows 11 specifically) so I'm assuming it has something to do with that as I assume most users are on Linux.

Also we changed format for the state in 2.12, which could explain the performance degradation of first invocation. It should be faster in successive invocations.

**Comment by aaron-meyers** [comment]
Well, I just installed 2.12.1 and this doesn't repro anymore, so closing for now.
Thanks!
