### ISSUE TITLE
dvc get: fails with gdrive remote

### ISSUE THREAD

**Issue by ursueugen** [iterative/dvc#7984]
# Bug Report

dvc get . $relative_path: fails with private organisational github repo and gdrive

## Description

Thanks for the amazing package - loving it.

I'm trying to download an individual file from a dvc google drive remote based on a private organisational github repository. Although `dvc list` works, `dvc get . $path` and `dvc import . $path` is unsuccessful. I'm attaching error logs.

### Reproduce

In the root of the directory corresponding to the private organizational github repository:

```
# works
dvc list . $relative_path

# doesn't work -> error.log.1
dvc get -v . $relative_path 2>& 1 | tee error.log.1.txt

# doesn't work -> error.log.2
dvc get -v $github_url $relative_path 2>&1 | tee error.log.2.txt  
```

**Error logs**:
[error.log.1.txt](https://github.com/iterative/dvc/files/9064153/error.log.1.txt)
[error.log.2.txt](https://github.com/iterative/dvc/files/9064152/error.log.2.txt)

Downgrading to `dvc==2.10.2` solves the issue.

### Expected

I expect a particular data file to be downloaded from google drive.

**Output of `dvc doctor`:**
```console
DVC version: 2.11.0 (pip)
---------------------------------
Platform: Python 3.8.13 on Linux-5.13.0-52-generic-x86_64-with-glibc2.17
Supports:
	gdrive (pydrive2 = 1.10.1),
	webhdfs (fsspec = 2022.5.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.8),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.8)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git
```

**Comment by pared** [comment]
Reproduction script:
```
#!/bin/bash

set -exu
pushd $TMPDIR

wsp=test_wspace
rep=test_repo

rm -rf $wsp && mkdir $wsp && pushd $wsp
main=$(pwd)

mkdir $rep && pushd $rep

git init
dvc init

echo data >> data


dvc remote add --default myremote gdrive://1vmk3A0bFL4zpkmR6rCv4LZr1Qd7Z80MT/remote 
dvc add data

git add -A
git commit -am "init"

dvc push

popd

dvc get test_repo data
```

The problem is that when using cloned repo, the repo with git filesystem does not have `tmp_dir` which is required to store `gdrive` credentials, hence the assert error.

The issue culprit is https://github.com/iterative/dvc/pull/7724
cc @efiop

**Comment by efiop** [comment]
Getting back to this, we detached `tmp_dir` from the `repo.fs`, which is correct, but we might need `tmp_dir` anyway for some other operations. So we might want to generate a `tmp_dir` on a `localfs` instead of just setting it to `None`. Will take a closer look...

**Comment by efiop** [comment]
Ok, getting back to this again, really hate the idea of generating random `tmp_dir`. Caching somewhere sounds way nicer (similar to what https://github.com/pydata/pydata-google-auth/blob/main/pydata_google_auth/cache.py does).  Regarding the problem of global cache, also really don't want to start with that, so we could begin with being very conservative in our cache, having a subkey that is based on things like path/user_id/etc.

Still, the auth is overly complex right now for pydrive2fs, so this logic should ideally be in pydrive and not in dvc https://github.com/iterative/PyDrive2/issues/193 , but we could start with keeping it in dvc for now.

**Comment by ursueugen** [comment]
Thanks!
