### ISSUE TITLE
pull: slow with hot cache and lots of files due to sqlite state

### ISSUE THREAD

**Issue by bsilver8192** [iterative/dvc#8006]
# Bug Report

## Description

`dvc pull` even with everything cached is slower than necessary. I have a folder with 128k files. It takes around 75 seconds to `dvc pull` on my machine (modern desktop processor, fast SSD, ext4). In my CI job that takes around 2 minutes (modern Xeon, fast SSD, btrfs). This change takes it down to 15 seconds on my machine:
```patch
diff --git a/dvc/repo/__init__.py b/dvc/repo/__init__.py
index 9a8b6264..1e86e09f 100644
--- a/dvc/repo/__init__.py
+++ b/dvc/repo/__init__.py
@@ -210,6 +210,7 @@ class Repo:
 
             state_db_dir = self._get_database_dir("state")
             self.state = State(self.root_dir, state_db_dir, self.dvcignore)
+            self.state = StateNoop()
             self.odb = ODBManager(self)
 
             self.stage_cache = StageCache(self)
```

When CI is doing a `dvc pull` where the results will be discarded afterwards, tracking the state of files like this is a waste of time. Could an option to work in this mode be added for situations like this?

If you tell me where the best place to add this option is (config? flag? environment variable?), I'd be happy to send a PR.

### Reproduce

1. Get a DVC repository with lots of files
2. Set up a symlink cache
3. `dvc pull`
4. Remove the local copies of the files, but leave the cache alone
5. `dvc pull` again

### Expected

Is faster.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.13.0 (pip)
---------------------------------
Platform: Python 3.9.2 on Linux-5.10.0-15-amd64-x86_64-with-glibc2.31
Supports:
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/main_vg-root_lv
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/mapper/main_vg-root_lv
Repo: dvc (subdir), git
```

**Additional Information (if any):**

**Comment by efiop** [comment]
Hi @bsilver8192 !

Thanks for opening this issue. We are aware of state implications, @skshetry did a research for it too in https://github.com/iterative/dvc-data/pull/93 . `--no-state` could be an option, but we probably can get this faster with using state.

Closing in favor of https://github.com/iterative/dvc-data/pull/93 for now.
