### ISSUE TITLE
Running dvc push to google drive for the first time in WSL2 changes commandline font styles to italic

### ISSUE THREAD

**Issue by sorenwacker** [iterative/dvc#8019]
# Bug Report

I follow the instruction https://www.youtube.com/watch?v=kLKBcPonMYw&ab_channel=DVCorg

running the commands in WSL2.

After `dvc push` the commandline has changed its appearance. For example, some text is italic.

**Comment by dtrifiro** [comment]
Hi @sorenwacker, would you mind providing the output of `dvc doctor`? A screenshot would also be appreciated, thanks!

**Comment by sorenwacker** [comment]
It might be a more general problem with WSL. I experienced that also when running pip. Will try to capture a screenshot when it happens next time.

**Comment by dtrifiro** [comment]
Closing this for now as it seems more generally related to WSL. Feel free to reopen if you think this is relevant to/happens because of dvc.
