### ISSUE TITLE
Incompatible dependency for dvc-render library

### ISSUE THREAD

**Issue by karimtemsah** [iterative/dvc#8047]
Currently this library has the following two dependencies:
```
    dvc-render==0.0.6
    dvclive>=0.7.3

```  
`dvclive` now introduced a newer version (0.10.0) which pins the following dependency:
`dvc_render[table]>=0.0.8`

So obviously the `dvc` library now has an incompatible versions for the `dvc-render` library, which causes the installation for this library to fail in case of using a tool like `pip-compile` or using up to date `pip` versions.

**Comment by pared** [comment]
@karimtemsah thanks for pointing that out, handled in #8055

**Comment by karimtemsah** [comment]
@pared thank you very much for the quick response :)
