### ISSUE TITLE
`data:status`: `--granular --with-dirs` returns duplicates for deleted directory

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#8053]
# Bug Report

## Description

Working on integrating `dvc data status --show-json --with-dirs --granular --untracked --unchanged` into the extension. Noticed that deleting a tracked directory gives a strange result.

### Reproduce

1. Open `vscode-dvc` demo repository
2. `rm -rf training_metrics` (contents was `training_metrics/scalars/loss.tsv` & `training_metrics/scalars/acc.tsv`)
3. `dvc data status --show-json --with-dirs --granular`

```bash
{
  "uncommitted": {
    "deleted": [
      "training_metrics",
      "training_metrics",
      "training_metrics"
    ]
  }
}
```

### Expected

Expected output would be:

```bash
{
  "uncommitted": {
    "deleted": [
      "training_metrics/",
      "training_metrics/scalars/acc.tsv",
      "training_metrics/scalars/loss.tsv"
    ]
  }
}
```

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.15.0 (pip)
---------------------------------
Platform: Python 3.8.9 on macOS-12.2.1-arm64-arm-64bit
Supports:
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.5.1),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.5.1),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc (subdir), git
```

**Additional Information (if any):**

Also verified against `2.15.1.dev7+gd0eda1d5`.

The `training_metrics` folder is produced by DVCLive. The nested structure does cause some issues with decorations/SCM in the UI but that is something that we can fix on the VS Code side.

**Comment by mattseddon** [comment]
The primary use case of the expected output would be to restore different parts of the deleted directory using checkout.

If this is not a normal/expected use case then I would expect:

```bash
{
  "uncommitted": {
    "deleted": [
      "training_metrics"
    ]
  }
}
```

**Comment by efiop** [comment]
@skshetry Could you take a look, please?

**Comment by skshetry** [comment]
@mattseddon, thank you for opening an issue with a good reproducer. I have opened #8107 which should fix the issue.
