### ISSUE TITLE
Corresponding of `dvc get` for uploading (`dvc set`?)

### ISSUE THREAD

**Issue by francesco086** [iterative/dvc#8066]
As part of the [large ticket created for GTO](https://github.com/iterative/gto/issues/220), @aguschin identified one part that belongs to `dvc`.

### Desired feature

Given a git repository using dvc, I would like to commit a dvc-tracked file without explicitely git cloning it (or be inside of it already). The file could be new, or it could just be an updated version of an existing one.

The feature is in the same spirit as `dvc get`, but it's for the other direction, uploading instead of downloading.

### Behavior

Behavior in its simplest form could be equivalent to what one can obtain with the following bash function:
```shell
function git-dvc-remote-commit-and-push {
	# Args:
	# 1. repo url
	# 2. absolute path to files to register. IMPORTANT: if it is a folder the path must end with a "/"
	# 3. destination relative path in artifact registry git repo
	# 4. commit message
	# 5. dvc remote modify OPTION
	# 6. dvc remote modify VALUE
	TMP_REPO_FOLDER=".tmp-model-registry-$(date +'%s')"
	git clone -q --depth 1 $1 ${TMP_REPO_FOLDER}
	pushd ${TMP_REPO_FOLDER}
	mkdir -p $3
	cp -r $2 $3
	dvc add -R $3
	git commit -m "$4"
	git push --repo $1
	DEFAULT_REMOTE="$(cat .dvc/config | grep -e "remote =" |  sed 's/.*remote = \(.*\)/\1/g')"
	dvc remote modify ${DEFAULT_REMOTE} $5 $6
	dvc push -R $3
	popd
	rm -rf $TMP_REPO_FOLDER
}
```

**Comment by daavoo** [comment]
I think https://github.com/iterative/dvc/issues/6485 is a (long) related discussion

**Comment by mattseddon** [comment]
Tracked in #6485

**Comment by evatt-harvey-salinger** [comment]
Hi, was this feature actually implemented into `dvc`? Haven't found it in the docs. Agree that it would be a worthwhile addition. 

My use case is that I have 3 repos: a `data_registry` , a `labelling_pipeline`, and a `training_pipeline`. I can easily import and update the datasets into my training pipeline using `dvc import` and `dvc update`. However, I'd like to be able to import the data into my labelling pipeline, update the dataset (label new examples), and the "export" those changes back to the data registry.

In the meantime, I can house the datasets and the labelling pipeline in the same registry, and modify the datasets in place. However, I would very much like to keep them separate. For example, if new method of labelling data comes online, but I want to maintain my old labelling pipeline and use both, I would (once again) need a way to update the datasets from an external project.

**Comment by evatt-harvey-salinger** [comment]
I supposed another option is to make my git repo `data_registry` a submodule of both `labelling_pipeline` and `training_pipeline`... but I hate git submodules.
