### ISSUE TITLE
api: Add `metrics_show`.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#8076]
Should be similar to `params_show`:
 https://github.com/iterative/dvc/blob/main/dvc/api/params.py

**Comment by Abelarm** [comment]
Hi @daavoo,

I can take this, but I need a bit of help, is there some doc from where I can start? 
Is this from where I should start? https://dvc.org/doc/command-reference/metrics/show#metrics-show

**Comment by daavoo** [comment]
Hi @Abelarm . Sorry for the late reply.

The idea is to add a public API method to `dvc.api` for showing metrics.

The API method should be implemented in a similar way as https://dvc.org/doc/api-reference/params_show (which is implemented in https://github.com/iterative/dvc/blob/main/dvc/api/params.py).

> Is this from where I should start? https://dvc.org/doc/command-reference/metrics/show#metrics-show

It's a good start. The idea is to provide a Python function that behaves similarly to that CLI command. There are some differences on how the outputs should be displayed, that's why I linked https://github.com/iterative/dvc/blob/main/dvc/api/params.py

**Comment by codamuse** [comment]
Hi @daavoo I've taken a first shot at this with a pretty straightforward implementation that works using the `example-get-started` repo:

https://github.com/codamuse/dvc/blob/78e64f627275f99d84ce23498fe3e5a819d0406e/dvc/api/metrics.py

Just wanted to confirm it's going in the right direction.  I still need to write a test, document, and maybe refactor since `params.py` and `metrics.py` are using the same `_postprocess` and `_onerror_raise`.   What do you think?

**Comment by daavoo** [comment]
> Just wanted to confirm it's going in the right direction. I still need to write a test, document, and maybe refactor since `params.py` and `metrics.py` are using the same `_postprocess` and `_onerror_raise`. What do you think?

Hi @codamuse . It looks good to me so far 🚀

**Comment by codamuse** [comment]
> > Just wanted to confirm it's going in the right direction. I still need to write a test, document, and maybe refactor since `params.py` and `metrics.py` are using the same `_postprocess` and `_onerror_raise`. What do you think?
> 
> Hi @codamuse . It looks good to me so far rocket

I just posted a draft PR with some questions.  Hopefully the write up isn't too long!
