### ISSUE TITLE
ci: experiment related tests are flakey

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#8087]
example: https://github.com/iterative/dvc/runs/7649735321?check_suite_focus=true#step:7:5540

Need to take a look.

**Comment by pmrowla** [comment]
We can probably disable the default pytest-celery worker ping timeout:

https://github.com/celery/celery/blob/128f0027005f2bf9d4b93082049d2c96c2bcd879/celery/contrib/testing/worker.py#L63

it should just need to be set in our fixture:
https://github.com/iterative/dvc/blob/7a0b3e93771c212fea3fa7d80f710877e9fdf958/tests/unit/repo/experiments/conftest.py#L15

_Originally posted by @pmrowla in https://github.com/iterative/dvc/issues/8108#issuecomment-1209294091_
