### ISSUE TITLE
404

### ISSUE THREAD

**Issue by FrankyTang** [iterative/dvc#8130]
# Bug Report

when I call: dvc status -c
a msg printed:
ERROR:unexpected error -Not Found:An error occurred(404) when calling the ListObjectsV2 operation:Not Found.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
base) ➜  recognition git:(dev) ✗ dvc doctor                        
DVC version: 2.17.0 (snap)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-124-generic-x86_64-with-glibc2.29
Supports:
	azure (adlfs = 2022.7.0, knack = 0.9.0, azure-identity = 1.10.0),
	gdrive (pydrive2 = 1.14.0),
	gs (gcsfs = 2022.7.1),
	hdfs (fsspec = 2022.7.1, pyarrow = 9.0.0),
	webhdfs (fsspec = 2022.7.1),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.7.0),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.7.0),
	s3 (s3fs = 2022.7.1, boto3 = 1.21.21),
	ssh (sshfs = 2022.6.0),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.7),
	webdavs (webdav4 = 0.9.7)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sdb
Repo: dvc, git
**Additional Information (if any):**

**Comment by FrankyTang** [comment]
base) ➜  recognition git:(dev) ✗ dvc doctor                        
DVC version: 2.17.0 (snap)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-124-generic-x86_64-with-glibc2.29
Supports:
	azure (adlfs = 2022.7.0, knack = 0.9.0, azure-identity = 1.10.0),
	gdrive (pydrive2 = 1.14.0),
	gs (gcsfs = 2022.7.1),
	hdfs (fsspec = 2022.7.1, pyarrow = 9.0.0),
	webhdfs (fsspec = 2022.7.1),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.7.0),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.7.0),
	s3 (s3fs = 2022.7.1, boto3 = 1.21.21),
	ssh (sshfs = 2022.6.0),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.7),
	webdavs (webdav4 = 0.9.7)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sdb
Repo: dvc, git

**Comment by karajan1001** [comment]
Hi, @FrankyTang 
Could you please provide a detailed log via `dvc status -c -vv`?

**Comment by FrankyTang** [comment]
Finally, the reason is that my it change s3 dns.
