### ISSUE TITLE
Adding working directory to PYTHONPATH

### ISSUE THREAD

**Issue by evgenytsydenov** [iterative/dvc#8132]
# Adding working directory to PYTHONPATH

Why is the working directory not added to `PYTHONPATH` when calling `dvc repro`? I think this is expected behaviour. Here is an example where this might be useful.

### Project structure
```
dvc.yaml
src / 
  __init__.py
  data /
    __init__.py
    prepare.py
  utils /
    __init__.py
    converters.py
```
### Files content
```
# dvc.yaml

stages:
  prepare:
    cmd: python src/data/prepare.py
```
```
# src/data/prepare.py

from src.utils.converters import convert_smth_to_smth

def prepare_data():
    convert_smth_to_smth()
    print("Prepare function")

if __name__ == '__main__':
    prepare_data()
```
```
# src/utils/converters.py

def convert_smth_to_smth():
    print("Function for conversion")
```

## Expected

```
$ dvc repro

Running stage 'prepare':                                              
> python src/data/prepare.py
Function for conversion
Prepare function
Use `dvc push` to send your updates to remote storage.
```

## Actual
```
$ dvc repro

Running stage 'prepare':
> python src/data/prepare.py
Traceback (most recent call last):
  File "...\src\data\prepare.py", line 1, in <module>
    from src.utils.converters import convert_smt_to_smt
ModuleNotFoundError: No module named 'src'
ERROR: failed to reproduce 'prepare': failed to run: python src/data/prepare.py, exited with 1
```

## Environment
```
$ dvc doctor

DVC version: 2.18.0 (pip)
---------------------------------
Platform: Python 3.10.4 on Windows-10-10.0.19044-SP0
Supports:
        webhdfs (fsspec = 2022.7.1),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
```

## Additional Information

This problem can be solved by using the terminal command `export PYTHONPATH=$PWD` or the python statement `sys.path.append(os.getcwd())` inside `prepare.py`. However, instead of manually modifying PYTHONPATH, I think it would be nice if DVC did this.

**Comment by pmrowla** [comment]
DVC is meant to be platform/language agnostic, meaning you can run any type of command in DVC stages (so not necessarily Python code). Because of this we do not set any type of environment configuration for whatever potential types of code the user is running. If your stage relies on a specific environment variable being set, we expect the user to set it before running DVC.
