### ISSUE TITLE
list: optimize -R/--recursive

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#8135]
http://bench.dvc.org/
<img width="448" alt="Screenshot 2022-08-16 at 15 32 39" src="https://user-images.githubusercontent.com/5367102/184880410-2755f123-91fd-4249-a089-1770e47a4216.png">

**Comment by rlamy** [comment]
A significant part of the recent performance regression comes from 496599518a2f79a79b63888a1d9eaa30d8712021, specifically this line:
https://github.com/iterative/dvc/blob/3c3cbee7fddd7a087cda5b1e0c821786bdd57be9/dvc/repo/ls.py#L88

We could swipe that issue under the rug by swapping the arguments of the `or`, but looking at the rest of the code in `_ls()`, that `fs.isdvc()` seems redundant.

But the main issue seems to be that there are a lot of redundant path operations, splitting and recombining them multiple times in `_DvcFileSystem.info()` and similar methods.

**Comment by efiop** [comment]
<img width="451" alt="Screenshot 2022-08-24 at 13 35 0📉 ="https://user-images.githubusercontent.com/5367102/186397608-91b5bd7a-b6fa-465b-a51e-7feb3a903fca.png">
:trend

**Comment by rlamy** [comment]
After #8241 is merged, there will still be a few easy targets for optimisation:
* `_DvcFileSystem.ls()` shouldn't call `._info()` but rather directly gather the relevant info from the underlying `fs`/`dvc_fs`, using `.ls(.., detail=True)`.
* `_info()` ends up calling `_update()` on every file that is passed to it, it should probably only do that for directories. (Note that the impact of this is compounded by the previous point).
* In `dvc.repo.ls._ls()`, the following lines take 30% of the run-time just to convert filenames into paths: https://github.com/iterative/dvc/blob/8432de5980d42d3929b7df7741eb8ed2134a0c74/dvc/repo/ls.py#L73-L76

**Comment by efiop** [comment]
Turns out I accidentally re-discovered and fixed all three points from @rlamy 's research ^

Fixed by https://github.com/iterative/dvc/pull/8779 and https://github.com/iterative/dvc/pull/8780 . Closing.

Kudos @rlamy 🙏

**Comment by efiop** [comment]
For the record, this is how it looks now
<img width="425" alt="Screenshot 2023-01-09 at 22 02 03" src="https://user-images.githubusercontent.com/5367102/211397331-b41e4935-f4c9-4832-8adf-0bd57e7f57a3.png">
