### ISSUE TITLE
Get experiment run id or hash in python API

### ISSUE THREAD

**Issue by trancenoid** [iterative/dvc#8155]
I want to get some run id or exp run hash so that I can name my results and models in a more meaningful and retrackable way. I cannot find anything related to this and would like to request if this can be added to the python api

**Comment by daavoo** [comment]
Hi @trancenoid ! Could you give some additional details on what you would like to do with the API?

**Comment by daavoo** [comment]
> I can name my results and models in a more meaningful and retrackable way

Note that you can give custom names to experiments using https://dvc.org/doc/command-reference/exp/run#-n

**Comment by trancenoid** [comment]
I cannot find any way to programmatically fetch the run name (through the python API https://dvc.org/doc/api-reference ) ; So if there is a function in the API to get the name of the current run-id (either manually specified as you said or auto-hashed id), I can use it to name/tag the files generated in that run.

**Comment by daavoo** [comment]
Got it. Closing as duplicate of https://github.com/iterative/dvc/issues/6668 , don't hesitate on continue the discussion there
