### ISSUE TITLE
dvc.api.params_show: conflict of `stages` with `deps=True` with nondefault target

### ISSUE THREAD

**Issue by tibor-mach** [iterative/dvc#8161]
# Bug Report

## Description

When run with `stages!=None` and a nondefault params file in `*targets` (or one which is not in the same directory as dvc.yaml), the `deps` parameter is ignored (as if it were always `False` as in default) and so even even parameters which do not belong to any stages are shown.

### Reproduce

1. Clone e.g. the [example-starged-repo](https://github.com/iterative/example-get-started)
2. Create `params_foo.yaml` as `foo: bar`
4. run the following script in python from 
```
import dvc.api
print(dvc.api.params_show("params_foo.yaml", stages="prepare", deps=True))
```
The output is then `{'foo': 'bar'}`

### Expected

The output should be empty (or perhaps a warning raised that no such parameters exist)

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.19.0 (pip)
---------------------------------
Platform: Python 3.10.5 on Linux-5.19.1-3-MANJARO-x86_64-with-glibc2.36
Supports:
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by daavoo** [comment]
For the record, `deps=True` is redundant if `stages` is also provided, `deps=True` is ignored in this case. `stages` does the same as `deps` but at a more granular level and takes priority

`deps` was kept in the API for consistency with the CLI, but we have discussed the potential removal as it makes the UX confusing.

**Comment by tibor-mach** [comment]
I think `deps` can be useful for when you just want a shorthand for `params` from all stages in all dvc.yaml files. Although I am not sure how useful that really is :-)
