### ISSUE TITLE
dvc.api.params_show: Relative stages paths required when run from a different directory than dvc.yaml

### ISSUE THREAD

**Issue by tibor-mach** [iterative/dvc#8162]
# Bug Report

## Description

When run from a different directory than one where `dvc.yaml` is, `dvc.api.params_show` fails with `DvcException: No params found
` unless the `stages` parameter is provided as "relative/path/to/dvc.yaml:stage_name" (or a list of such stage names). 

I.e. for example when run with a working directory one level below where `dvc.yaml` is, then this works:
```
dvc.api.params_show(stages="../dvc.yaml:prepare", deps=True)
```
and this does not:
```
dvc.api.params_show(stages="prepare", deps=True)
```

I am pretty sure this is because in `dvc.repo.Repo` the `addressing` attribute of  `index.stages` is initialized in such a path-relative fashion and it is then checked that the string in `addressing` corresponds to the strings from `stages` parameter of `dvc.api.params_show`. This is checked by [_read_params ](https://github.com/iterative/dvc/blob/78dd045d29f274960bcaf48fd2d055366abaf2c1/dvc/repo/params/show.py#L81) and [_collect_vars](https://github.com/iterative/dvc/blob/78dd045d29f274960bcaf48fd2d055366abaf2c1/dvc/repo/params/show.py#L108).

### Expected

I am not completely sure if this second issue can be considered a bug it works if I specify the stages strings in the specific way above and it is not quite clear how this could be dealt with when there are multiple `dvc.yaml` files. Still, even if this is not considered a bug, I think it should at least be mentioned in documentation that the stages should be given as paths relative to the working directory (plus the `dvc.yaml:<stage_name>` syntax) in this case, since this is not completely obvious to the user.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.19.0 (pip)
---------------------------------
Platform: Python 3.10.5 on Linux-5.19.1-3-MANJARO-x86_64-with-glibc2.36
Supports:
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by daavoo** [comment]
> I am not completely sure if this second issue can be considered a bug it works if I specify the stages strings in the specific way above and it is not quite clear how this could be dealt with when there are multiple dvc.yaml files. 

The use of `addressing` was deliberately introduced for dealing with conflicts in multiple dvc.yaml files.

> Still, even if this is not considered a bug, I think it should at least be mentioned in documentation that the stages should be given as paths relative to the working directory (plus the dvc.yaml:<stage_name> syntax) in this case, since this is not completely obvious to the user.

Agree, I will update the docs accordingly and add an example
