### ISSUE TITLE
`plots diff` & `exp show`: unexpected error - Empty git repo

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#8163]
# Bug Report

## Description

After initialising a repository with both `Git` and `DVC` both `plots diff` and `exp show` throw `ERROR: unexpected error - Empty git repo`.

### Reproduce

1. `mkdir new`
2. `cd new`
3. `git init`
4. `dvc init`
5. `dvc exp show` => throws error
6. `dvc plots diff` => throws error

### Expected

Neither of these commands should throws an error under these circumstances but they should return an empty dict for the `--json` option.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.18.1 (pip)
---------------------------------
Platform: Python 3.9.13 on macOS-12.5.1-arm64-arm-64bit
Supports:
	http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
	webhdfs (fsspec = 2022.7.1)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Additional Information (if any):**

This was brought up in the cross team meeting and is part of a larger discussion on error handling.

The requested behaviour is exhibited under the same circumstances for the following commands:

```bash
/new master +3 ❯ dvc list . --dvc-only --recursive --json
[]
/new master +3 ❯ dvc status --json
{}
/new master +3 ❯ dvc diff --json
{}
/new master +3 ❯ dvc data status --json
{}
```

**Comment by dberenbaum** [comment]
Thanks @mattseddon! Could you describe how it impacts VS Code and how important it is?

I see that it's inconsistent with other commands, but both behaviors seem initially reasonable to me, and since I have never seen a user complaint about it, I would only prioritize it based on your needs.

**Comment by mattseddon** [comment]
This broke the workflow of getting setup with a new project/repository. That is something that we want to cover with the extension so it is fairly important to us. 

Here are a couple of thoughts that I've had:

1. If the error is expected (which I think is reasonable) then we should not get an "unexpected error"
2. If we have to have a commit for some commands to work then maybe `dvc init` should generate that commit.

**Comment by daavoo** [comment]
> If the error is expected (which I think is reasonable) then we should not get an "unexpected error"

Before the extraction and creation of https://github.com/iterative/scmrepo (`dvc<=2.8.3`), `dvc exp show` didn't raise any error but showed an empty table / returned this with `--json` flag:

```
{                                                                     
  "": {
    "baseline": {
      "error": {
        "type": "InvalidSpecError",
        "msg": ": failed to parse revision specifier - Invalid pattern ''"
      }
    }
  }
}
```

`plots diff` failed but with `dvc.scm.base.RevError` instead of unexpected error

**Comment by daavoo** [comment]
I think we just need to do the same as `dvd diff`:

https://github.com/iterative/dvc/blob/460d08057cf355686e1337b94640ac8522497bb1/dvc/repo/diff.py#L23-L24

**Comment by pmrowla** [comment]
https://github.com/iterative/dvc/blob/460d08057cf355686e1337b94640ac8522497bb1/dvc/scm.py#L163

This should also be
```py
if not (rev == "HEAD" or rev.startswith("refs/")):
```

(This does not resolve the issue, but it makes DVC generate a proper error message rather than unexpected error.)
> ERROR: failed to show experiments - unknown Git revision 'HEAD'

**Comment by daavoo** [comment]
@mattseddon Could you try https://github.com/iterative/dvc/issues/8163 to see if it matches what you expected

**Comment by mattseddon** [comment]
Will test after the weekend 🙏🏻.

**Comment by mattseddon** [comment]
I can confirm that everything works as expected 👍🏻 🙏🏻.
