### ISSUE TITLE
import-url: `--no-download` and `dvc commit`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8173]
What is the expected behavior of `dvc commit` when a repo has partial imports? Currently it will fail because there is no output file in the workspace

```
$ cat file.dvc
md5: 750c9e509a218cbbcde864ce15515c0d
frozen: true
deps:
- etag: '0x8DA79D118EC7839'
  size: 2
  path: remote://azure/dir/file
outs:
- path: file

$ dvc commit
outputs ['file'] of stage: 'file.dvc' changed. Are you sure you want to commit it? [y/n] y
ERROR: failed to commit - output 'file' does not exist
```

It seems to me that committing a partial import should just be a no-op and silently pass?

_Originally posted by @pmrowla in https://github.com/iterative/dvc/issues/8024#issuecomment-1223824647_

**Comment by shcheklein** [comment]
What happens if it's just a regular output that is missing in the workspace? Also an error?

From the top of my head it's fine to throw an error, may be put a flag to silence these kind of errors (and add to the error message)

**Comment by dberenbaum** [comment]
> What happens if it's just a regular output that is missing in the workspace? Also an error?

Yes.

I agree that it's not critical to address this, and it seems consistent with current behavior as is. 

However, I like the idea of it being a no-op and silently passing. It's a step towards being smarter about missing outputs instead of always throwing an error. Why should `dvc commit` throw an error for a valid workflow?

**Comment by shaunc** [comment]
I want to use the pre-commit hooks and this is getting in the way. Is there a workaround? Can I mark as "not to worry" in the dvc file somehow?
