### ISSUE TITLE
Latest release missing Windows binary

### ISSUE THREAD

**Issue by tech189** [iterative/dvc#8174]
# Bug Report

## Description

The latest release (2.19.0) does not include an exe to download for Windows, such as for the previous release: https://github.com/iterative/dvc/releases/download/2.18.1/dvc-2.18.1.exe

### Reproduce

Visit the releases page to confirm this: https://github.com/iterative/dvc/releases/tag/2.19.0

**Comment by skshetry** [comment]
The CI was broken and failed to upload. Do you use that release artifact?
I'll suggest downloading from https://dvc.org/download/win/dvc-2.19.0, which is an officially signed release.

This has now been fixed in the default branch and 2.20.0 (now the latest release) has release artifacts.

**Comment by tech189** [comment]
Yes, the [Scoop package for DVC](https://github.com/ScoopInstaller/Main/blob/master/bucket/dvc.json) uses the assets attached to the releases. I tried downloading 2.20.0 from dvc.org but [it's a 404 currently](https://dvc.org/download/win/dvc-2.20.0), so it would be really helpful if you could keep the CI uploading the built releases to GitHub! Thanks for fixing it!
