### ISSUE TITLE
Perf improvements

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#819]
The perf issue #758 was resolved. Kudos @efiop!

There is still a potential for perf improvements. It takes almost 30 seconds to check out (without any actions) 25K files:
```
$ time dvc checkout
real	0m27.597s
user	0m12.977s
sys	0m9.390s
```

12 seconds of user time is just a matter of code optimization and we should probably not care about this today. But it takes 9 seconds at the system level.

1. Is there any chance to change our algorithm for reducing the number of the system calls (and reduce the sys time)?
2. Can we understand that a directory didn't change and just skip all the actions? Like in this case:
```
$ dvc checkout
$ dvc checkout
```
Each of the commands take 30 seconds. Can we optimize the second command out?

**Comment by efiop** [comment]
Sorry for closing #758 silently. I should've mentioned that I'm not done with perf changes yet, more patches are coming. Moving to 0.10.0.

**Comment by dmpetrov** [comment]
#758 was fixed. Now DVC performance at the level we had before.
Next step is to improve this level.

**Comment by efiop** [comment]
Hm, are you sure you used the latest master for your test? This is what i'm getting with 25K small files:
```
+ dvc checkout   
                 
real    0m10.195s
user    0m8.305s 
sys     0m2.288s 
```

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/849 . Dvc checkout with no actions for 25K files now takes 7 second if there is no state saved and only 2 seconds if there is state saved.
