### ISSUE TITLE
installing from Ubuntu repo does not install s3 adapter

### ISSUE THREAD

**Issue by mbergal** [iterative/dvc#8194]
# Bug Report

DVC version 2.6.3

![image](https://user-images.githubusercontent.com/167835/186968532-080d228a-054f-4688-8967-8ec62cd17458.png)

DVC version 2.21.1

![image](https://user-images.githubusercontent.com/167835/186968664-c2b3edcb-2dca-4eba-9cee-fbdd472979eb.png)

**Comment by efiop** [comment]
Looks like we need to add dvc-* packages to pyinstaller hooks as hidden imports.

**Comment by dacbd** [comment]
related? https://github.com/iterative/setup-dvc/issues/41

**Comment by efiop** [comment]
Hey folks. This should be fixed in 2.21.3. Packages will be ready in a few hours.
