### ISSUE TITLE
Dict unpacking in Windows adds extra quotations to string arguments

### ISSUE THREAD

**Issue by abhmul** [iterative/dvc#8203]
# Bug Report

## Description

When running `dvc repro` with a stage that uses dict-unpacking on Windows, all string arguments get an extra set of quotations when parsed by argparse. For example "hello" turns into "'hello'". If I copy the command run by DVC and run it myself, the code works as expected.

### Reproduce

I have created a git repo with a minimal example of this bug. 

```bash
>>> git clone https://github.com/abhmul/dvc-scratch.git
>>> git switch dvc-quote-bug
>>> dvc repro
stage1.py: error: argument --a_str: invalid choice: "'hello'" (choose from 'hello', 'goodbye')
```

Now copy the command run by DVC. Running it will work as expected
```bash
>>> python stage1.py --a_str 'hello' --a_bool --a_list 'a' 'b' 'c'
Namespace(a_str='hello', a_bool=True, a_list=['a', 'b', 'c'])
```

### Expected

All string arguments are parsed by argparse successfully without extra quotations.

### Environment information

python==3.10.6
dvc==2.22.0

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.22.0 (pip)
---------------------------------
Platform: Python 3.10.6 on Windows-10-10.0.19042-SP0
Supports:
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by abhmul** [comment]
A simple hack until this is fixed: add a `type` to the argument that strips extra quotes.

```python
parser.add_argument("--a_str", choices=["hello", "goodbye"], type=lambda x: x.strip("'"))
```

**Comment by daavoo** [comment]
Hi @abhmul , Thanks for reporting. How does your 'params.yaml' look?
