### ISSUE TITLE
Hint to see exps from previous commits

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8236]
@daavoo Mentioned how users repeatedly find it confusing that their experiments disappear after `git commit`. I doubt we want to default to `dvc exp show -A`, so can we reduce the confusion with a hint about how to see experiments from previous commits? We could either show it always or try to detect when it's likely to be an issue (for example, no experiments exist at HEAD).

**Comment by maxagin** [comment]
@dberenbaum I have a question.
After `git commit`, I have made some adjustments to the source files and now my table header has different names. --> I want to see both commits in the table, but the headers are different. 
Can this happen? If yes, we probably won't be able to show multiple commits in the same table.

**Comment by maxagin** [comment]
If the above is true, we could have a dropdown with all commits, when one is selected we display it, but only one at a time. In this case, we won't be able to compare EXPs from different commits.
Q: would multiple tables in one view be a solution?

**Comment by dberenbaum** [comment]
@maxagin It's possible that columns change between commits. However, this is also possible within a single commit. We show all columns from all experiments and commits in that case. We can iterate on improving this, but I think it's separate from this issue.

We already do allow for showing multiple commits in the CLI table. We should also be concerned with all the experiments disappearing on git commit, especially since I think there's currently no way to bring them back in VS Code.

**Comment by dberenbaum** [comment]
@shcheklein @mattseddon What is the default number of commits in VS Code now? Maybe we can make it consistent between both products by defaulting to the same in CLI?

**Comment by mattseddon** [comment]
We show three commits. The HEAD + 2 previous:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/37993418/217083518-b8c72602-fb43-4b4e-96a1-8a8d95053da0.png">


I think there is a plan to let the user expand this number through the UI. The only mention of that I could find in an open ticket was here: https://github.com/iterative/vscode-dvc/issues/1966

**Comment by dberenbaum** [comment]
@mattseddon Closing this as basically a duplicate of #1966
