### ISSUE TITLE
Pull: Moved data from an old remote to a new remote, DVC cannot pull from the new remote

### ISSUE THREAD

**Issue by FeryET** [iterative/dvc#8242]
# Bug Report

## Description

I have created a new bucket in a self hosted MinIO instance, and used `rclone sync   old_remote:dvc_bucket   new_remote:dvc_bucket` to move data from my old remote to the new remote. Given the correct endpoint, s3 url and authorization information, I cannot pull the moved data from my new remote. The error I'm getting is:

```
ERROR: unexpected error - There were headers present in the request which were not signed: An error occurred (AccessDenied) when calling the GetObject operation: There were headers present in the request which were not signed
```

I've posted a complete detail in **[this discussion](https://github.com/iterative/dvc/discussions/8227)** thread a few days ago.

### Reproduce

1. Create an s3 bucket and push the data using dvc to it.
2. Create a new s3 bucket in another remote and sync it with the previous one using `rclone`.
3. Add the configuration to DVC and pull from the new remote and new bucket.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.24.0 (pip)
---------------------------------
Platform: Python 3.10.4 on Linux-5.15.0-47-generic-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 0.4.0
        dvc_objects = 0.2.0
        dvc_render = 0.0.9
        dvc_task = 0.1.2
        dvclive = 0.10.0
        scmrepo = 0.0.25
Supports:
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2022.8.2, boto3 = 1.24.59)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3, s3, s3
Workspace directory: ext4 on /dev/nvme0n1p5
Repo: dvc, git
```

**Additional Information (if any):**

I have created a new bucket in the new remote for testing stuff, and I can use a new dvc project in that bucket flawlessly. It pushes, pulls and fetches correctly. But apparently in the transition between remotes, something changes and I'm not aware what is it.

**Comment by dberenbaum** [comment]
Discussed in https://github.com/iterative/dvc/discussions/8227. Appears to be a MinIO issue. Feel free to reopen or continue the discussion in the other thread as needed. Thank you!
