### ISSUE TITLE
exp: queuing with `--set-param` deletes untracked params files

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8256]
# Bug Report

## Description

If the params file is untracked, doing `dvc exp run --queue --set-param...` will delete the params file in the workspace.

### Reproduce

```
git init repo
cd repo
dvc init
git add .
git commit -m "setup"
echo 'p: 1' > params.yaml
dvc stage add -n test -p 'params.yaml:' -o out.yaml 'cp params.yaml > out.yaml'
dvc exp run --queue --set-params p=2
ls
```

`ls` at the end returns only `dvc.yaml` in the workspace. `params.yaml` no longer exists.

### Expected

`ls` to show that `params.yaml` still exists with the same content (`p: 1`) as before doing `dvc exp run --queue --set-param`.

**Comment by daavoo** [comment]
Duplicate of https://github.com/iterative/dvc/issues/7842
