### ISSUE TITLE
feature: System-level .dvcignore

### ISSUE THREAD

**Issue by DbCrWk** [iterative/dvc#8261]
Creating a new `dvc` data registry is pretty straightforward, but the one repetitive thing I have to do is set the `.dvcignore`. Would it be possible to have a system-level `.dvcignore` that would cut across all projects? It could be placed right next to the `.gitignore` at `~/.dvcignore`.

Philosophically, I think it aligns well with both how `.gitignore` works and how I think about project-level and system-level issues. For example, if my personal computer produces `.DS_Store` files or `.icloud` files, I don't want to put this in a project-level ignore file because it's not something in the project that is producing that clutter. On the other hand, if we have a build script that produces logs that should be excluded, then it makes sense to put those in a project-level ignore file because those are clutter produced by a project tool.

Thanks!

**Comment by meshde** [comment]
#8280 adds support for a system-level `.dvcignore` file.

The approach used there is to read the patterns from the `~/.dvcignore` file (if it exists) and include it as part of the list of patterns used to initiate the ignore trie (along with the default ignore patterns).

Happy to to change the approach if the iterative team has a better one in mind.

**Comment by DbCrWk** [comment]
Thank for addressing this so quickly!

**Comment by zmughal** [comment]
Even if this has been closed, this would still be useful when dealing with a user's OS-specific and editor-specific ignores that should not be part of a particular project's configuration.
