### ISSUE TITLE
Introduce dir cache v2

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#827]
Currently in our v1 dir cache, we are storing a json file with relative paths to files and their md5s, that are stored separately as standalone files. That approach was adopted for two main reasons:
1) we were having in mind a scenario with directories that have a relatively small amount of big files. Unfortunately the reality showed that our assumptions were wrong and the much more common scenario is a directory with a large amount of tiny files, which makes our v1 dir cache extremely slow and inefficient, especially when we are talking about `dvc push/pull/status`.
2) we needed a simple format that would produce deterministic outputs for the same dirs and v1 dir cache fully suited that. The problem of deterministic archives is a very well-known one, especially in pkg world(see https://wiki.debian.org/ReproducibleBuilds/Howto). We would need to solve it in an efficient and cross-platform and pythonic way. Unfortunately at the time of developing v1 we couldn't find a proper solution, thus we would need to do more research. Suggestions are very welcomed.

Adding this task to 0.11.0.

**Comment by villasv** [comment]
> we are storing a json file with relative paths to files and their md5s

Are you referring to the `link.sate` file? Can you give more details on what are the performance bottlenecks caused by many files?

Just to share my POV, this was the case for me too. I generated a directory with 250k json files and `dvc add` wouldn't even finish. So I changed my pipeline to output a single file with 250k lines, and things went on smoothly.

Perhaps you could keep cache v1 in place if only there was a way to treat directories as single files. Like automatic compression and stuff like that.

**Comment by efiop** [comment]
>Are you referring to the link.sate file? Can you give more details on what are the performance bottlenecks caused by many files?

No, I'm actually talking about directory cache files. E.g.:
```
$ mkdir dir
$ echo foo > dir/foo
$ dvc add dir
$ cat dir.dvc
md5: d3e69fcd3581b123c971ee7d86e0b27f
outs:
- cache: true
  md5: aa5f690fab1a8e34ad009d3de2ad38cb.dir
  metric: false
  path: dir
$ cat .dvc/cache/aa/5f690fab1a8e34ad009d3de2ad38cb.dir
[{"md5": "d3b07384d113edec49eaa6238ad5ff00", "relpath": "foo"}]
$ cat .dvc/cache/d3/b07384d113edec49eaa6238ad5ff00
foo
```

As to performance bottlenecks, our current algorithm for pulling cache consists of two stages: downloading missing .dir cache files so that we can collect from those what cache do we need for files from that directory and then pulling all the rest. This is not optimal not only because of the algo, but also simply downloading thousands of small files will take longer than a tar archive with those compressed.

> Just to share my POV, this was the case for me too. I generated a directory with 250k json files and dvc add wouldn't even finish. So I changed my pipeline to output a single file with 250k lines, and things went on smoothly.

Yeah, this is one of the ways to work around the inefficiency of v1 dir cache. Other would be to pack your dirs into tar archives yourself in your pipeline. However, if you do so, dvc would have to store cache for the whole archive, when in our current v1 implementation it is actually able to track only those files that has been changed under your directory. 

> Perhaps you could keep cache v1 in place if only there was a way to treat directories as single files. Like automatic compression and stuff like that.

There is also a great suggestion from @shcheklein https://github.com/iterative/dvc/issues/829 to split our cache into even smaller bits and pieces, so that we could manage them more efficiently. Maybe that approach could also help us with cache for directories. Will have to do more research for 0.11.0.

**Comment by efiop** [comment]
Ok, most of the bottlenecks were cleared when we were doing RFC for 0.11.0 making this issue not relevant anymore, since our current dir cache suits our needs perfectly.
