### ISSUE TITLE
dvc plots diff 

### ISSUE THREAD

**Issue by arbDEVbest** [iterative/dvc#8270]
### Report

Hi
I have this error when I execute pipeline gitlab-ci:
ERROR: unexpected error -  --targets: failed to parse revision specifier - Invalid pattern ' --targets'
code: $ dvc plots diff \ --targets metrics.csv \ --show-vega master > vega.json

**Comment by jorgeorpinel** [comment]
@arbDEVbest you should not use `\` characters in your terminal except at the end to continue a command in the next line (in Mac/Linux).

Dod you copy that command from somewhere in our docs?

Try `dvc plots diff --targets metrics.csv --show-vega master > vega.json`

> If you're still having issues please provide all the details requested in the [bug issue template](https://github.com/iterative/dvc/issues/new?assignees=&labels=&template=bug_report.md). Thanks

**Comment by arbDEVbest** [comment]
Thanks for your response.
I fixed this error, indeed the error was the backslash for line break. but now I have an other error 
$ cml publish --md plot.png >> report.md
/scripts-426-3100/step_script: line 157: cml: command not found
I'm using this image dvcorg/cml-py3:latest

**Comment by jorgeorpinel** [comment]
Glad that worked.

> now I have an other error

Please ask in https://github.com/iterative/cml/issues or reach CML support directly via https://cml.dev/chat @arbDEVbest

**Comment by dberenbaum** [comment]
@arbDEVbest It looks like cml is not installed on the machine you are using. Is this inside of GitHub/GitLab/Bitbucket? You can find examples in https://cml.dev/doc/start of how to setup each one.
