### ISSUE TITLE
update: inconsistent hash calculation

### ISSUE THREAD

**Issue by thomasgilgenast** [iterative/dvc#8279]
# Bug Report

update: inconsistent hash calculation

## Description

When running `dvc update` on an unchanged `.dvc` target, dvc computes a different hash (even though the file has not changed) and therefore incorrectly deduces that the file has changed.

When running `dvc status`, the hash is computed "normally" and DVC reports "Data and pipelines are up to date." as expected.

### Reproduce

1. `git init`
2. `dvc init`
3. `dvc import --rev a470fae https://github.com/iterative/example-get-started data/data.xml`
4. `dvc update --verbose data.xml.dvc`

```
...
2022-09-09 19:07:39,604 DEBUG: Computed stage: 'data.xml.dvc' md5: 'af11a1d48d48643f0152078af2fb2b00'
2022-09-09 19:07:39,604 DEBUG: 'md5' of stage: 'data.xml.dvc' changed.
2022-09-09 19:07:39,604 DEBUG: stage: 'data.xml.dvc' changed.
2022-09-09 19:07:39,606 DEBUG: Removing output 'data.xml' of stage: 'data.xml.dvc'.
2022-09-09 19:07:39,606 DEBUG: Removing '/Users/thomas/git/dvc-bug-repro/data.xml'
Importing 'data/data.xml (https://github.com/iterative/example-get-started)' -> 'data.xml'
...
```

Inside `dvc.stage.utils.compute_md5()`, `dvc status` and `dvc update` are passing the following two different dicts to `dvc.utils.dict_md5()` (note that the 'frozen' key is ignored and so has been popped to make the two dicts easier to diff by eye):

```
{'md5': '6a0daa61174a15e2f2f606ea6ffe1f19', 'deps': [{'path': 'data/data.xml', 'repo': {'url': 'https://github.com/iterative/example-get-started', 'rev': 'a470fae', 'rev_lock': 'a470fae5c0ccf71641e10d99e69e97534c3d811e'}}], 'outs': [{'md5': '22a1a2931c8370d3aeedd7183606fd7f', 'size': 14445097, 'path': 'data.xml'}]}
{'md5': '6a0daa61174a15e2f2f606ea6ffe1f19', 'deps': [{'path': 'data/data.xml', 'repo': {'url': 'https://github.com/iterative/example-get-started', 'rev': 'a470fae', 'rev_lock': 'a470fae5c0ccf71641e10d99e69e97534c3d811e'}}], 'outs': [{'path': 'data.xml'}]}
```

`dvc status` hashes the first dict, which hashes to `6a0daa61174a15e2f2f606ea6ffe1f19` as expected and reports "Data and pipelines are up to date."

`dvc update` hashes the second dict which is missing the `md5` and `size` keys of `outs`, and this causes it to compute the "incorrect" hash `af11a1d48d48643f0152078af2fb2b00`.

### Expected

`dvc update` should not treat the file as changed if it hasn't changed.

The hash of the file should not change if the file contents and relevant context have not changed.

`dvc update` and `dvc status` should compute the same hash.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.24.0 (pip)
---------------------------------
Platform: Python 3.8.13 on macOS-12.5.1-x86_64-i386-64bit
Subprojects:
	dvc_data = 0.4.0
	dvc_objects = 0.2.0
	dvc_render = 0.0.9
	dvc_task = 0.1.2
	dvclive = 0.10.0
	scmrepo = 0.0.25
Supports:
	gs (gcsfs = 2022.8.2),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by dtrifiro** [comment]
Hi @thomasgilgenast,
thanks for the detailed report.

I tried reproducing the issue on both 2.24.0 and 2.25.0 and did not succeed. Could you try updating dvc and see if this keeps happening? Thanks

**Comment by thomasgilgenast** [comment]
I just tried reproducing from scratch in a clean venv which got dvc 2.25.0 and when I get to `dvc update --verbose data.xml.dvc` I still get

```
2022-09-14 11:47:58,092 DEBUG: 'md5' of stage: 'data.xml.dvc' changed.
2022-09-14 11:47:58,092 DEBUG: stage: 'data.xml.dvc' changed.
2022-09-14 11:47:58,093 DEBUG: Removing output 'data.xml' of stage: 'data.xml.dvc'.
```

<details><summary>dvc doctor</summary>
<pre>
DVC version: 2.25.0 (pip)
---------------------------------
Platform: Python 3.8.13 on macOS-12.5.1-x86_64-i386-64bit
Subprojects:
	dvc_data = 0.7.1
	dvc_objects = 0.2.2
	dvc_render = 0.0.10
	dvc_task = 0.1.2
	dvclive = 0.10.0
	scmrepo = 0.1.1
Supports:
	http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
</pre>
</details>

<details><summary>pip freeze</summary>
<pre>
aiohttp==3.8.1
aiohttp-retry==2.8.3
aiosignal==1.2.0
amqp==5.1.1
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.12.0
atpublic==3.1.1
attrs==22.1.0
billiard==3.6.4.0
celery==5.2.7
certifi==2022.6.15.2
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
colorama==0.4.5
commonmark==0.9.1
configobj==5.0.6
cryptography==38.0.1
dictdiffer==0.9.0
diskcache==5.4.0
distro==1.7.0
dpath==2.0.6
dulwich==0.20.46
dvc==2.25.0
dvc-data==0.7.1
dvc-http==2.19.1
dvc-objects==0.2.2
dvc-render==0.0.10
dvc-task==0.1.2
dvclive==0.10.0
flatten-dict==0.4.2
flufl.lock==7.1.1
frozenlist==1.3.1
fsspec==2022.8.2
funcy==1.17
future==0.18.2
gitdb==4.0.9
GitPython==3.1.27
grandalf==0.6
hydra-core==1.2.0
idna==3.4
importlib-resources==5.9.0
kombu==5.2.4
multidict==6.0.2
nanotime==0.5.2
networkx==2.8.6
omegaconf==2.2.3
packaging==21.3
pathspec==0.9.0
prompt-toolkit==3.0.31
psutil==5.9.2
pycparser==2.21
pydot==1.4.2
pygit2==1.10.1
Pygments==2.13.0
pygtrie==2.5.0
pyparsing==3.0.9
pytz==2022.2.1
PyYAML==6.0
requests==2.28.1
rich==12.5.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
scmrepo==0.1.1
shortuuid==1.0.9
shtab==1.5.5
six==1.16.0
smmap==5.0.0
tabulate==0.8.10
tomlkit==0.11.4
tqdm==4.64.1
typing_extensions==4.3.0
urllib3==1.26.12
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.5
yarl==1.8.1
zc.lockfile==2.0
zipp==3.8.1
</pre>
</details>

I then tried in docker and still get the `af11a1d48d48643f0152078af2fb2b00` hash:

```
$ docker run --rm -it python:3.10.7-bullseye bash
root@e8c667997c6a:/# mkdir test && cd test
root@e8c667997c6a:/test# pip install dvc
root@e8c667997c6a:/test# git init
root@e8c667997c6a:/test# dvc init
root@e8c667997c6a:/test# dvc import --rev a470fae https://github.com/iterative/example-get-started data/data.xml
root@e8c667997c6a:/test# dvc status
Data and pipelines are up to date.
root@e8c667997c6a:/test# dvc update --verbose data.xml.dvc
2022-09-14 15:56:02,397 DEBUG: Creating external repo https://github.com/iterative/example-get-started@a470fae
2022-09-14 15:56:02,398 DEBUG: erepo: git clone 'https://github.com/iterative/example-get-started' to a temporary dir
2022-09-14 15:56:05,674 DEBUG: Computed stage: 'data.xml.dvc' md5: 'af11a1d48d48643f0152078af2fb2b00'
2022-09-14 15:56:05,674 DEBUG: 'md5' of stage: 'data.xml.dvc' changed.
2022-09-14 15:56:05,674 DEBUG: stage: 'data.xml.dvc' changed.
2022-09-14 15:56:05,677 DEBUG: Removing output 'data.xml' of stage: 'data.xml.dvc'.
2022-09-14 15:56:05,677 DEBUG: Removing '/test/data.xml'
...
```

<details><summary>dvc doctor</summary>
<pre>
DVC version: 2.25.0 (pip)
---------------------------------
Platform: Python 3.10.7 on Linux-5.10.104-linuxkit-x86_64-with-glibc2.31
Subprojects:
	dvc_data = 0.7.1
	dvc_objects = 0.2.2
	dvc_render = 0.0.10
	dvc_task = 0.1.2
	dvclive = 0.10.0
	scmrepo = 0.1.1
Supports:
	http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: overlay on overlay
Caches: local
Remotes: None
Workspace directory: overlay on overlay
Repo: dvc, git
</pre>
</details>

<details><summary>pip freeze</summary>
<pre>
aiohttp==3.8.1
aiohttp-retry==2.8.3
aiosignal==1.2.0
amqp==5.1.1
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.12.0
atpublic==3.1.1
attrs==22.1.0
billiard==3.6.4.0
celery==5.2.7
certifi==2022.6.15.2
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
colorama==0.4.5
commonmark==0.9.1
configobj==5.0.6
cryptography==38.0.1
dictdiffer==0.9.0
diskcache==5.4.0
distro==1.7.0
dpath==2.0.6
dulwich==0.20.46
dvc==2.25.0
dvc-data==0.7.1
dvc-http==2.19.1
dvc-objects==0.2.2
dvc-render==0.0.10
dvc-task==0.1.2
dvclive==0.10.0
flatten-dict==0.4.2
flufl.lock==7.1.1
frozenlist==1.3.1
fsspec==2022.8.2
funcy==1.17
future==0.18.2
gitdb==4.0.9
GitPython==3.1.27
grandalf==0.6
hydra-core==1.2.0
idna==3.4
kombu==5.2.4
multidict==6.0.2
nanotime==0.5.2
networkx==2.8.6
omegaconf==2.2.3
packaging==21.3
pathspec==0.9.0
prompt-toolkit==3.0.31
psutil==5.9.2
pycparser==2.21
pydot==1.4.2
pygit2==1.10.1
Pygments==2.13.0
pygtrie==2.5.0
pyparsing==3.0.9
pytz==2022.2.1
PyYAML==6.0
requests==2.28.1
rich==12.5.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
scmrepo==0.1.1
shortuuid==1.0.9
shtab==1.5.5
six==1.16.0
smmap==5.0.0
tabulate==0.8.10
tomlkit==0.11.4
tqdm==4.64.1
typing_extensions==4.3.0
urllib3==1.26.12
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.5
yarl==1.8.1
zc.lockfile==2.0
</pre>
</details>

**Comment by thomasgilgenast** [comment]
To provide an update on this: I tried
- a newer DVC version (2.31.0)
- removing the `--rev` flag when doing `dvc import`
- importing `model.pkl` instead of `data.xml.dvc`
- removing the `--verbose` flag when doing `dvc update`
- using the SSH clone URL instead of the HTTPS clone URL when doing `dvc import` (this last one I did not do in Docker because I didn't want to figure out how to configure SSH in the Docker container)

None of these change the result. With all of them combined, my reproduction of the bug is the same thing as the example in the DVC docs here https://dvc.org/doc/command-reference/update#example

```
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install dvc
$ git init
$ dvc init
$ dvc import git@github.com:iterative/example-get-started model.pkl
$ dvc update model.pkl.dvc
Importing 'model.pkl (git@github.com:iterative/example-get-started)' -> 'model.pkl'
```

while the example in the docs suggests that we should instead see

```
Output 'model.pkl' didn't change. Skipping saving.
Saving information to 'model.pkl.dvc'.
```

<details><summary>dvc doctor</summary>
<pre>
DVC version: 2.31.0 (pip)
---------------------------------
Platform: Python 3.8.13 on macOS-12.5.1-x86_64-i386-64bit
Subprojects:
	dvc_data = 0.22.0
	dvc_objects = 0.11.0
	dvc_render = 0.0.12
	dvc_task = 0.1.4
	dvclive = 0.12.1
	scmrepo = 0.1.2
Supports:
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
</pre>
</details>

**Comment by skshetry** [comment]
I tried above steps, and was not able to reproduce. @thomasgilgenast, could you check if you can still retry with latest dvc version? Thanks.

**Comment by thomasgilgenast** [comment]
Sorry for missing the notification 2 weeks ago - it slipped passed my inbox around the new year.

I can confirm that this issue is gone with dvc==2.42.0

Testing updating model.pkl.dvc in Docker (python:3.10.7-bullseye) I get the expected:

```
(venv) root@41ef03b4b4d4:/temp# dvc update model.pkl.dvc
'model.pkl.dvc' didn't change, skipping 
```

Thank you for following up on this!
