### ISSUE TITLE
How to handle `hydra.sweeper.params` configuration

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#8284]
Not a blocker, but we should follow up on how to handle `hydra.sweeper` configuration from https://hydra.cc/docs/tutorials/basic/running_your_app/multi-run/#sweeping-via-hydrasweeperparams.

_Originally posted by @dberenbaum in https://github.com/iterative/dvc/issues/8187#issuecomment-1238518016_

**Comment by dberenbaum** [comment]
Note that documenting that it's not supported should be sufficient to close this for now (although not ruling out that we may want to revisit it in the future).
