### ISSUE TITLE
ERROR: Cannot add 'folder-path', because it is overlapping with other DVC tracked output:

### ISSUE THREAD

**Issue by danielbellsa** [iterative/dvc#8285]
Goal: `add` `commit` `push` all contents of `project_model/data/` to **dvcstore**.

I don't have any `.dvc` files in my project.

```
$ dvc add ./project_model/data/
ERROR: Cannot add '/home/me/PycharmProjects/project/project_model/data/images', because it is overlapping with other DVC tracked output: '/home/me/PycharmProjects/project/project_model/data'.
To include '/home/me/PycharmProjects/project/project_model/data/images' in '/home/me/PycharmProjects/project/project_model/data', run 'dvc commit project_model/data.dvc'

$ dvc commit project_model/data.dvc
ERROR: failed to commit project_model/data.dvc - 'project_model/data.dvc' does not exist
```

I've deleted contents from `.dvc/cache/` and **S3** `s3://foo/bar/dvcstore/`, with no luck.

---

```
$ dvc -V
2.10.2
```

```
$ dvc doctor
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.9.12 on Linux-5.15.0-47-generic-x86_64-with-glibc2.35
Supports:
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p5
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p5
Repo: dvc, git
```

Please let me know if there's anything else I can add to post.

**Comment by dtrifiro** [comment]
You might have previously `dvc add`'ed some file/directory in the `project_model/data` directory. You can check there and remove any `.dvc` files  you find. After that you should be able to `dvc add project_model/data`.

Please refer to https://dvc.org/doc/start/data-management and https://dvc.org/doc/command-reference/add. If you have any further question, you might want to check out our [discord](https://discord.com/invite/dvwXA2N)

**Comment by vamshisaideep9** [comment]
(sample) PS C:\Users\vamsh\OneDrive\Desktop\mlops\MLOPS> dvc add sample_app/data_given/winequality.csv
Adding...                                                      
ERROR: unexpected error - no such column: "size" - should this be a string literal in single-quotes?
