### ISSUE TITLE
dvc connectivity with Azure Blob Storage

### ISSUE THREAD

**Issue by debanshu08** [iterative/dvc#8309]
I am trying to use dvc remote with Azure Blob Storage but I get this as error whenever I do dvc push 
unexpected error - Cannot connect to host sientityfiles.blob.core.windows.net':443 ssl:True [getaddrinfo failed]: Cannot connect to host sientityfiles.blob.core.windows.net':443 ssl:True [getaddrinfo failed]: [Errno 11001] getaddrinfo failed

Commands I have tried :-
dvc remote add -d myremote azure://dvcdemo 
dvcdemo is the Container name

dvc remote modify --local myremote account_name 'sientityfiles'
This is the storage account name 

dvc remote modify --local myremote connection_string 'mysecret'
dvc push

unexpected error - Cannot connect to host sientityfiles.blob.core.windows.net':443 ssl:True [getaddrinfo failed]: Cannot connect to host sientityfiles.blob.core.windows.net':443 ssl:True [getaddrinfo failed]: [Errno 11001] getaddrinfo failed

Getting this, can you help in fixing this?

**Comment by dtrifiro** [comment]
Hi, it looks like your storage account's endpoint url does not exists. Please check that the storage account's name is correct and that it exists.
