### ISSUE TITLE
push: can't upload single files to second remote without pushing data from other remotes as well

### ISSUE THREAD

**Issue by yvesbeutler** [iterative/dvc#8311]
# Bug Report

## Description

I'm working with multiple remotes within the same Git repository. To logically separate my data, I'm using the following config (without a set default remote):

```
['remote "campaigns"']
    url = azure://my-campaigns/campaign-xy
    account_name = <my-account-name>
    exclude_environment_credential = True
    exclude_visual_studio_code_credential = True
    exclude_managed_identity_credential = True
    exclude_shared_token_cache_credential = True

['remote "user-scores"']
    url = azure://my-users/scores
    account_name = <my-account-name>
    exclude_environment_credential = True
    exclude_visual_studio_code_credential = True
    exclude_managed_identity_credential = True
    exclude_shared_token_cache_credential = True
```

Assuming the following project structure:

```
|-- .dvc/
|-- data/
     |---- raw/
            |---- campaign.csv
            |---- campaign.csv.dvc
            |---- scores.csv
            |---- scores.csv.dvc
```

My problem is, that every time I want to `dvc push -r user-scores`, all files I previously pushed to the campaigns remote will also be uploaded to user-scores.

### Reproduce

1. dvc add data/raw/campaign.csv
2. dvc push -r campaigns
3. dvc add data/raw/scores.csv
4. dvc push -r user-scores

### Expected

The `campaigns.csv` should not be uploaded to the user-scores remote.

### Environment information

I'm working on Azure with dvc `2.26.2`.

Thanks for any help relating my issues.

**Comment by dtrifiro** [comment]
Hi, you can add a `target` argument to only push the specified targets:

```bash
dvc push -r user-scores data/raw/scores.csv.dvc
```

**Comment by yvesbeutler** [comment]
Thank you for your answer, @dtrifiro. Your solution seems to work fine for a small amount of files, but might be a bit cumbersome for larger amounts. Initially I expected some kind of staging area like in git and that I can use
```
dvc data status
```
to show just currently active files which I can upload to any remote I want to. I might need to rethink my overall data architecture.

**Comment by pmrowla** [comment]
You can also use the `remote:` field in the `outs` section of .dvc files to specify where a particular DVC-tracked file or directory should be pushed/pulled from. https://dvc.org/doc/user-guide/project-structure/dvc-files#output-entries

So in your case you could add `remote: campaigns` in `campaigns.csv.dvc` and `remote: user-scores` in `scores.csv.dvc`. You would then just run `dvc push`/`dvc pull` without using `-r` to specify a remote and without needing to specify individual target files to push/pull.

The one thing to note here would be that you will have to manually add the `remote:` field in all of your `.dvc` files.

**Comment by yvesbeutler** [comment]
Hi @pmrowla, this is exactly what I was looking for. Contains few manual tasks, but I very much welcome the fact that this solution gives me more insight into where the data is on Azure, as dvc customises the file structure to suit its needs.

Thank you all, I'll close this issue.

**Comment by meierale** [comment]
> You can also use the `remote:` field in the `outs` section of .dvc files to specify where a particular DVC-tracked file or directory should be pushed/pulled from. https://dvc.org/doc/user-guide/project-structure/dvc-files#output-entries
> 
> So in your case you could add `remote: campaigns` in `campaigns.csv.dvc` and `remote: user-scores` in `scores.csv.dvc`. You would then just run `dvc push`/`dvc pull` without using `-r` to specify a remote and without needing to specify individual target files to push/pull.
> 
> The one thing to note here would be that you will have to manually add the `remote:` field in all of your `.dvc` files.

Would it be possible to add an additional, optional flag to the `dvc add` command which allows to specify the `remote:` field of the resulting `.dvc` file? This would allow to specify the remote to be used upon initial adding of new files.
I know there's the `dvc add -r` to be used together with `--to-remote` so one would have to make sure the options are not confused with each other...

**Comment by pmrowla** [comment]
@meierale I moved your question into a new feature request. Currently, `remote:` must be specified manually and not via the CLI flags, as you noted we would have to work out a way to remove any potential confusion between setting `remote:` and passing a remote name to be used with `--to-remote`.
