### ISSUE TITLE
Bug Bounty : Critical Bug

### ISSUE THREAD

**Issue by ankushgoel27** [iterative/dvc#8322]
Hi,

I am a security researcher and a bug bounty hunter.
Does iterative has a bug bounty program in place. I have found a critical bug and would like to report it.

Thanks,

**Comment by dtrifiro** [comment]
Hi, please contact security@iterative.ai

**Comment by omesser** [comment]
@ankushgoel27 Hi Ankush!
Thanks for reaching out, we don't have a formal bounty program yet - but let's follow up over your email
