### ISSUE TITLE
Add --file_size_min and --file_size_max options to `pull` command 

### ISSUE THREAD

**Issue by golebiewicz-shareablee** [iterative/dvc#8334]
I have a project where we have a lot of small files which are used pretty often and few very big ones which are rarely needed. 
Having an option to filter by file size would be quite useful in many situations where one wants to avoid running out of disk space accidentally.

I propose two new flags (names of course are subject to discussion), to allow filtering pulled files by size: 
- `--file_size_min` (lower limit), 
- `--file_size_max` (upper limit)

Since .dvc files store the size anyway it seems like a doable thing.

**Comment by skshetry** [comment]
Thank you for creating the issue. It’s a nice feature, it reminds me of git’s `--filter=blob:limit=<n>[kmg]` flag. But unfortunately we don’t have the capability to filter by size right now. The size in `.dvc` files are not granular and are not really true size of the files/directory.

I am closing this as not planned for now.
