### ISSUE TITLE
UnicodeDecodeError during parsing Config file

### ISSUE THREAD

**Issue by amritghimire** [iterative/dvc#8339]
We had an repository using GITCRYPT for the config file. As a result, during the parsing of repo in Studio, we had the error as below:
```python
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 17: invalid start byte
......
    config = dict(Config(dvc_dir, validate=False))
  File "dvc/config.py", line 105, in __init__
    self.load(validate=validate, config=config)
  File "dvc/config.py", line 151, in load
    conf = self.load_config_to_level()
  File "dvc/config.py", line 283, in load_config_to_level
    merge(merged_conf, self.load_one(merge_level))
  File "dvc/config.py", line 200, in load_one
    conf = self._load_config(level)
  File "dvc/config.py", line 179, in _load_config
    conf_obj = ConfigObj(fobj)
  File "configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "configobj.py", line 1279, in _load
    content = infile.read() or []
  File "codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
```

I think it should be wrapped by ConfigError. 

More context at https://sentry.io/organizations/iterative/issues/3606551247/?project=5220519&referrer=slack#exception

DVC Version
-----
2.24.0

**Comment by mvshmakov** [comment]
We have a user report for this stating the repo is unavailable for them: https://iterativeai.slack.com/archives/C01CLQERD9P/p1664166967252009.

**Comment by Suor** [comment]
I don't think it's possible it will work with a gitcrypted config or anything else for that matter. If we don't have an encryption key there is no way for us to read it. 

The possible cases for "worked before" are:
1. It worked before `gitcrypt` was used on the same repo.
2. `gitcrypt` was used but the history was not encrypted only newer commits, which might not event exist, or be only in some branches. Then someone encrypted and rewrote the history.
3. `gitcrypt` was used, but the config file itself was added before and was not altered since. Someone updated the config file and it was encrypted.

I never used `gitcrypt` so no big expert here, but at least option 1 is possible.

**Comment by dberenbaum** [comment]
Do we want to support this use case? It seems pretty narrow.

If we do, the options seem to be:
1. Provide a way to save the encryption key on Studio.
2. Provide a way to add a GPG user ID for Studio.

Seems like they would encounter similar issues if using `dvc ls/import/get` on a remote repo, and we would have similar options to address it.

**Comment by mvshmakov** [comment]
> Provide a way to save the encryption key on Studio.

Not sure a lot of people will provide Studio SaaS with their private GPG encryption keys. Some people also store their keys in a non-exportable way on smartcards like YubiKey/Solokey. Creating a dedicated subkey just for the Studio also sounds like an unnecessary complication and is not a very flexible option.

> Provide a way to add a GPG user ID for Studio.

Though this option sounds better, symmetric encryption algorithms will not work in this case, so we'll need to constrain users to asymmetric encryption usage only (e.g., no AES256).

`gitcrypt` is also one of many tools to encrypt files. Some of the alternatives work on top of GPG, but others (e.g., Cryptomator) are not interoperable with GPG.

**Comment by Suor** [comment]
@daavoo wrapping with a `ConfigError` will help. We automatically show such messages to a user, for now it's an "unexpected error".
