### ISSUE TITLE
Make `exp show` handle errors better

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#8350]
_Originally posted by @karajan1001 in https://github.com/iterative/dvc/issues/8158#issuecomment-1254604883_

**Comment by karajan1001** [comment]
We shouldn't add locks to `exp show` to prevent race conditions as this command is calling continuously by the extension. So we had to make a better way to handle all kinds of reference failures.

**Comment by dberenbaum** [comment]
@karajan1001 Is there already a plan for how to do this?

**Comment by karajan1001** [comment]
> @karajan1001 Is there already a plan for how to do this?

A new PR had been created.
