### ISSUE TITLE
md5 calc is wrong in some win files

### ISSUE THREAD

**Issue by palenge** [iterative/dvc#8374]
# Bug Report

## Description

when the md5 its calculated for a text file with win line ending sometimes the calc its wrong because sometimes there is a CRCL just between two chunks

### Reproduce

a file with only jump lines CRCL

create a file with more than 800000 new lines (CRCL) and add one space in the first one (I think its enough maybe less)

### Environment information

any version

**Comment by efiop** [comment]
Hey @palenge . The way we compute md5 is `md5(dos2unix(data))`. We do that mostly for legacy reasons and will likely change that in the future. See https://github.com/iterative/dvc/issues/4658
