### ISSUE TITLE
dvc add interrupts running script that appends lines to file

### ISSUE THREAD

**Issue by junwang-wish** [iterative/dvc#8391]
`dvc add` seems to interrupts script that append lines to file:
1. I have a long-running script `dont_interrupt.py` that shouldn't be interrupted. It append lines to a large file `large.txt`, which was previously added to dvc through `dvc add large.txt`, and thus have `large.txt.dvc`. `dont_interrupt.py` looks like 
```python
with open('large.txt', 'a', buffering=1) as f:
    while True: 
        x = f(x) # expensive stateful computation that should not be interrupted
        f.write(F'{x}\n')
```
3. After some time of running the script that appends lines to `large.txt`, now I want to checkpoint the current status of `large.txt`, but want to let the script keep appending lines to it, so I run `dvc add large.txt`, which runs successfully.
4. However, one would expect the script to keep running and keep appending lines to `large.txt`, but no... It keeps running but new lines don't get appended to `large.txt`. This can be monitored by `watch wc -l large.txt`

Now if one wants to be able to keep running `dont_interrupt.py`, one needs to kill the current running `python dont_interrupt.py`, and restart. 

Does `dvc add large.txt` do something unexpected to `large.txt` such that a running `dont_interrupt.py` that uses python file IO to append lines to file malfunction?
```python
with open('large.txt', 'a', buffering=1) as f: 
    f.write(...)
```

**Comment by pmrowla** [comment]
`dvc add` moves the file into the DVC cache directory and then does the equivalent of `dvc checkout` to link the file back into the workspace. So after `dvc add`, you would need to open a new file handle to `large.txt` in order to write to it.

It is not safe to use `dvc add` in this way (while you continue to actively write data to the file). Depending on your particular cache link type configuration (https://dvc.org/doc/user-guide/large-dataset-optimization#file-link-types-for-the-dvc-cache) your script may actually be continuing to write to the original (moved or hardlinked) file in `.dvc/cache/...` rather than the newly checked-out workspace version, which is essentially corrupting your DVC cache.

**Comment by junwang-wish** [comment]
Thx @pmrowla, knowing how `dvc add` as you described, it makes sense why this behavior occurs as in my case. However, in cases like this where a stateful append is long-running and I do indeed want to checkpoint intermediate results. What is the recommended way to do it using dvc?

**Comment by pmrowla** [comment]
You would need to have a way to signal your long running script that it needs to pause while you run `dvc add`. Ideally you would probably want to consider using some kind of filesystem lock (like https://py-filelock.readthedocs.io/en/latest/index.html or https://flufllock.readthedocs.io/en/stable/) that your long running script acquires while writing to the file. And then you would have a separate script that acquires the same lock and runs `dvc add`.

So your long running script would look something like
```py
while True:
    x = f(x) # expensive stateful computation that should not be interrupted
    with file_lock:  # wait until lock can be acquired
        with open('large.txt', 'a', buffering=1) as f:
            f.write(F'{x}\n')
```

and then you would have a separate script that does something like
```py
with file_lock:  # wait for any active write() to finish and acquire lock
    subprocess.run(['dvc', 'add'[)
```

**Comment by pmrowla** [comment]
Should also note that if you just want to run `dvc add` at fixed intervals (rather than running it manually when needed) it may be easier to just include the `dvc add` step in your long-running script, which would not require the use of any separate filesystem locks.

**Comment by junwang-wish** [comment]
Thanks @pmrowla it makes sense in my case to run dvc add inside the long-running script at regular interval. By that you mean something like?
```
while True:
    x = f(x) # expensive stateful computation that should not be interrupted
    c = 0
    with open('large.txt', 'a', buffering=1) as f:
        f.write(F'{x}\n')
        c += 1
    if c == 10000:
        c = 0
        os.system("dvc add large.txt")
```

**Comment by pmrowla** [comment]
@junwang-wish yes, that should work fine.

**Comment by junwang-wish** [comment]
Thanks!
