### ISSUE TITLE
dvc get https://github.com/iterative/dataset-registry \  tutorials/versioning/data.zip not working

### ISSUE THREAD

**Issue by stavyadatta** [iterative/dvc#8397]
Hello there
I am trying to run this command and am getting an unexpected error saying connection timeout to host at https://remote.dvc.org/dataset-registry/fa/9c0eb4173d86695b4e800219651360. 

Can anyone please help?

**Comment by jorgeorpinel** [comment]
Please give more context by following this [bug template](https://github.com/iterative/dvc/issues/new?assignees=&labels=&template=bug_report.md) or reach out at https://dvc.org/chat @stavyadatta .

**Comment by crizCraig** [comment]
I am able to download this dataset @stavyadatta . Perhaps the host is back up!
