### ISSUE TITLE
DVC METRICS: --precision doesn't work with --json

### ISSUE THREAD

**Issue by rafalparadowski** [iterative/dvc#8406]
DVC version: 2.29.0 and 2.8.1

`--precision n` option takes no effect when specifying json as output:

```
$ dvc metrics diff
Path                     Metric        Old    New    Change
memory_metrics.json      metrics       0.01   0.02   0.01
$
$ dvc metrics diff --precision 1
Path                     Metric        Old    New    Change
memory_metrics.json      metrics       0.0    0.0    0.0
$
$ dvc metrics diff --precision 1 --json
{                                                                     
  "memory_metrics.json": {
    "metrics": {
      "old": 0.01,
      "new": 0.02,
      "diff": 0.01
    }
  }
}
$
```

Would be nice if it could be fixed for older python as well.

**Comment by daavoo** [comment]
Hi @rafalparadowski, this is by design.
 The `--json` flag in all `dvc {method} {diff|show}` commands returns the "raw" internal object as returned by `repo.{method}.{show|diff}` so other flags don't affect it's behavior. 
 This could be better reflected in the docs. 
 
 Adding the feature request flag.

**Comment by rafalparadowski** [comment]
Hi David. Thank you for so quick reply!

I have several thoughts (probably most of them you have already discussed):
1. `json` word does't implify that data will not be affected by filters. It's just a format, so name of flag and action are slightly disconnected here.
2. Maybe it would be reasonable to add new flag (`--raw`?) for printing raw data in whatever format?
3. Having output in json is very useful for further reading/steps in pipelines. And being able to apply filters (maybe more in future?) will be cool. In current state all filters need to be done separately in pipeline - not terrible, but if those filters already exist in dvc, why to do it separately.

Thank you for your great work!
Cheers!
