### ISSUE TITLE
queue start: `dvc.lock.LockError` in `dvc queue start`.

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#8417]
> Yes, we still need to wait on some bug fixes, although I don't think any are related to concurrency (cc @karajan1001 ). Did you have a specific issue in mind?

If I start the queue with `j > 1` then experiments will automatically fail. E.g queue 3 experiments, start the queue with `-j 3` and 2 will fail.

_Originally posted by @mattseddon in https://github.com/iterative/vscode-dvc/issues/1995#issuecomment-1272651403_
     
looking into the logs. it shows 

> dvc.lock.LockError: Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.

To start multiple workers requires to change the `rw` lock mode in queue start

**Comment by dberenbaum** [comment]
@karajan1001 Do we know when this started? I thought it was working after https://github.com/iterative/dvc-task/pull/90.

Is it specific to checkpoints?

Do we have a test for it?

> looking into the logs.

How are you seeing the logs? When I run them, I get:

```
$ dvc queue status
Task     Name       Created    Status
86cc14e             08:32 AM   Failed
6c692f3             08:32 AM   Failed
e826f79             08:32 AM   Failed
a917eca  exp-1c88f  08:32 AM   Success

Worker status: 0 active, 0 idle
$ dvc queue logs 86cc14e
ERROR: No output logs found for experiment '86cc14e'
```

**Comment by karajan1001** [comment]
> @karajan1001 Do we know when this started? I thought it was working after [iterative/dvc-task#90](https://github.com/iterative/dvc-task/pull/90).

Start from init. 

> Do we have a test for it?
No. 

> looking into the logs.
You can use `cat .dvc/tmp/exps/celery/dvc-exp-worker-1{2,3,4,5}.out` to see the logs from each worker.
