### ISSUE TITLE
exp run: Running <stage_1> creates a since deleted deps source file of another stage

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#8431]
# Bug Report

## Description

I had run a stage (`stage_1`) which declares a source file as dependency previously. Then added an unrelated stage (`stage_2`) to the dvc.yaml file which does not depend on the first stage, and also renamed the source file which that first stage (`stage_1`) depends on. I was then running the new stage (`stage_2`) using `dvc exp run stage_2`. To my surprise, this restored the `deps` source file of `stage_1`.

### Reproduce

- Create a first stage with a source file as `deps`.
- Run this stage using `dvc repro` or `dvc exp run`.
- Delete the source file that this stage depends on, do not repro the stage.
- Create a second stage which has no `deps` and `outs`. In my case, just a `cmd: cat params.yaml` to test Hydra composition.
- Run second stage using `dvc exp run`.

Example `dvc.yaml`:
```
stages:
  stage_1:
    cmd: python main.py
    deps:
    - main.py
  stage_2:
    cmd: cat params.yaml
```

### Expected

The deleted source file of the stage that is not being reproduced / run should not be restored from the cache.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.28.0 (rpm)
---------------------------------
Platform: Python 3.8.3 on Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.14
Subprojects:

Supports:
        azure (adlfs = None, knack = 0.10.0, azure-identity = None),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = None),
        hdfs (fsspec = None, pyarrow = 9.0.0),
        http (aiohttp = None, aiohttp-retry = 2.8.3),
        https (aiohttp = None, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = None, boto3 = None),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7),
        webhdfs (fsspec = None)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local, s3
Remotes: s3, s3
Workspace directory: xfs on /dev/md124
Repo: dvc (subdir), git
```

**Additional Information (if any):**

**Comment by aschuh-hf** [comment]
This does not happen with `dvc repro`. Trying to reproduce this in a different folder with dummy files, I noticed that `dvc exp run` temporarily makes changes to my other untracked / uncommitted / modified files in the Git repository that I had open in a tab in VS Code while running `dvc exp run`.

**Comment by dberenbaum** [comment]
> The `deps` source file is also only restored if it was tracked by Git previously.

@aschuh-hf Do you use `git rm` or otherwise stop tracking it with Git before running `dvc exp run`?

**Comment by aschuh-hf** [comment]
Indeed I hadn't used `git rm`.

**Comment by dberenbaum** [comment]
In that case, I think it's expected that it will be tracked, right? We recently tried to clarify this a bit better in the docs (see https://github.com/iterative/dvc.org/issues/4044). Is there something more that would help clarify it further?
