### ISSUE TITLE
Make queued experiments initialization progress run in parallel.

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#8448]
For now, when we run queued experiments we would lock the whole scm during the whole initialization progress. 

https://github.com/iterative/dvc/blob/29b3dc1f9ec96fbd4116f8adabaeb17c9633afb2/dvc/repo/experiments/queue/base.py#L566-L568.

This makes the initialization progress only run sequentially. We can do a more precise control on this progress to make the 

1. We should only lock some of the exp refs or an exp reference namespace.
2. We should only add the lock on a few steps instead of on the whole progress.
3. We do not need to set `EXEC_*` branches to the before pushing them to the remote.

**Comment by dberenbaum** [comment]
Thanks @karajan1001! Is this causing a significant slowdown in queuing many experiments? Are there other issues caused by the current behavior?

**Comment by karajan1001** [comment]
> Thanks @karajan1001! Is this causing a significant slowdown in queuing many experiments? Are there other issues caused by the current behavior?

It depends on the complexity of the `Git` repo and the time cost of the training progress. The demo repo provided by the `vs-code` extension team is `Git` history complex and training quickly. This makes that it causes significant performance slowdown. By comparison, in my past experience, most of the ML repo is the opposite. Trainning costs hours or days, so it will only have a limited effect on time cost. But the problem is that most of the demos to show to the users would not be such a long training one.

**Comment by dberenbaum** [comment]
@karajan1001 Is this during `exp run --queue` or during `queue start/exp run --run-all`? I'm not seeing anything that looks painfully slow when messing with queuing a few experiments in https://github.com/iterative/vscode-dvc-demo.

**Comment by karajan1001** [comment]
During `queue start -j n` when `n > 1`, this functionality hasn't been integrated into `vscode` extension.

**Comment by karajan1001** [comment]
> I'm starting from the command line using that repo. Are you seeing slowdown during `exp run --queue` or during `queue start`?

It is not about slowdown but about the experiments running in sequence even if I started several workers. The reason for this is that we use an SCM lock during the initialization progress. And because 1. the workers are only reading each of the stashes, 2. The queue stashes are different for different workers. So we can make some modifications and then release the lock, and make the workers run in parallel.

**Comment by dberenbaum** [comment]
> The queue stashes are different for different workers

Is this the way it's supposed to work? I would think they would consume tasks from the same queue.

**Comment by karajan1001** [comment]
> > The queue stashes are different for different workers
> 
> Is this the way it's supposed to work? I would think they would consume tasks from the same queue.

The queue itself is thread safety, but no one can guarantee that the stash queue is too. For example, If I use `git stash list` first to find the desired stash, and then want to `git stash pop stash@{n}` it. But in the interval time, some other processes did some operation on the stash queue.
