### ISSUE TITLE
Cannot kill / remove crashed job from queue.

### ISSUE THREAD

**Issue by behrica** [iterative/dvc#8461]
Cannot kill crashed job from queue.

The job is in state Running looking at `dvc queue status`, but the process and worker are dead.

Running:
```
 dvc queue kill f70e2e7
```
gives:
```
ERROR: unexpected error - : [Errno 2] No such file or directory: 'xxxx/.dvc/tmp/exps/run/f70e2e74831986b0def28ec2a3c614dd3ba4054a/f70e2e74831986b0def28ec2a3c614dd3ba4054a.json'
```
And indeed, the directory is missing.
Is there any manual cleanup I can do ?

**Comment by rlamy** [comment]
This looks like an instance of #8450. IIUC, #8469 should fix it automatically (cc @karajan1001 ).

**Comment by karajan1001** [comment]
Duplicated with #8449

**Comment by dberenbaum** [comment]
@karajan1001 Do you know the cause of this or how to fix it already?
