### ISSUE TITLE
Unable to find the server 

### ISSUE THREAD

**Issue by MuhammadKhalid3975** [iterative/dvc#8462]
# Bug Report

## Description
![image](https://user-images.githubusercontent.com/42286079/197344008-6009c598-9514-4e3b-8264-6c2c0ba37df4.png)

### Reproduce
using google drive as remote (shared drive)
dvc version 2.30.0
Windows 10

**Comment by pared** [comment]
Hello @MuhammadKhalid3975, would it be possible to post the stack trace of the error that can be seen when running `dvc push -v`?
