### ISSUE TITLE
`queue kill`: Can't stop running task: improve message

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#8473]
# Bug Report

## Description

After adding some experiments to the queue and having initiated the execution with `queue start`, I try to stop a running task with `dvc queue kill {task}`.

### Reproduce

- `git init && dvc init`
- `dvc stage add -n test -O foo 'sleep 10 && echo ${foo} > foo'`
- `echo 'foo: 1' > params.yaml`
- `git add . && git commit -m "init"`
- `dvc exp run --queue -S 'foo=range(5, 10)'`
- `dvc queue start`
- `watch dvc queue status`
Look for the `{task}` with `Running`.
- `dvc queue kill {task}`

```python
2022-10-25 18:12:00,092 ERROR: '9be29ba' is not a valid queued experiment name
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/daviddelaiglesiacastro/miniconda3/lib/python3.9/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/Users/daviddelaiglesiacastro/miniconda3/lib/python3.9/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/daviddelaiglesiacastro/miniconda3/lib/python3.9/site-packages/dvc/commands/queue/kill.py", line 14, in run
    self.repo.experiments.celery_queue.kill(revs=self.args.task)
  File "/Users/daviddelaiglesiacastro/miniconda3/lib/python3.9/site-packages/dvc/repo/experiments/queue/celery.py", line 302, in kill
    raise UnresolvedQueueExpNamesError(missing_rev)
dvc.repo.experiments.exceptions.UnresolvedQueueExpNamesError: '9be29ba' is not a valid queued experiment name
```
### Expected

Stops execution of the specified (running) experiment tasks.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.31.0 (pip)
---------------------------------
Platform: Python 3.9.5 on macOS-10.16-x86_64-i386-64bit
Subprojects:
	dvc_data = 0.22.0
	dvc_objects = 0.11.0
	dvc_render = 0.0.12
	dvc_task = 0.1.4
	dvclive = 0.11.0
	scmrepo = 0.1.2
Supports:
	gs (gcsfs = 2022.8.2),
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2022.8.2, boto3 = 1.19.8)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

```

**Comment by dberenbaum** [comment]
@daavoo Are you sure the experiment doesn't just complete too fast? Can you try with `sleep 30` or more? I'm unable to reproduce when I set `sleep` to a long enough time period to make sure the experiment is still running.

For experiments that are completed, we should have a better error message and indicate that the experiment is already completed.

**Comment by karajan1001** [comment]
I guess it is the same one as #8449

**Comment by daavoo** [comment]
> For experiments that are completed, we should have a better error message and indicate that the experiment is already completed.

Looks like this was the issue

**Comment by dberenbaum** [comment]
Let's keep it open to fix the UI
