### ISSUE TITLE
Add locks to experiment operations which would modify the exp ref space.

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#8516]
For now, in the experiments related cmds we only have locks over 
1. initialization of experiments for temp directory running.
2. add new experiments.

We should add them to all other operations that will modify the exp ref space to prevent race conditions. 

# Bug Report

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by dberenbaum** [comment]
@karajan1001 Have you seen this causing problems?

**Comment by karajan1001** [comment]
> @karajan1001 Have you seen this causing problems?

Currently no, but it's possible, so I set it to p2
