### ISSUE TITLE
Help to add dvc.pkg to Homebrew Cask

### ISSUE THREAD

**Issue by ivaquero** [iterative/dvc#8522]
Hi, I am trying to submit a PR to add dvc.pkg to Homebrew Cask. However, the script needs an `uninstall stanza` to complete the test. Please help.

The PR is at https://github.com/Homebrew/homebrew-cask/pull/134994

```console
audit for dvc: failed
 - installer and pkg stanzas require an uninstall stanza
 - The URL's domain github.com does not match the homepage domain dvc.org, a 'verified' parameter has to be added to the 'url' stanza. See https://docs.brew.sh/Cask-Cookbook#when-url-and-homepage-domains-differ-add-verified
Error: 2 problems in 1 cask detected
Error: installer and pkg stanzas require an uninstall stanza
Error: The URL's domain github.com does not match the homepage domain dvc.org, a 'verified' parameter has to be added to the 'url' stanza. See https://docs.brew.sh/Cask-Cookbook#when-url-and-homepage-domains-differ-add-verified
Error: Process completed with exit code 1.
```

**Comment by efiop** [comment]
@ivaquero Hm, any particular reason for wanting a cask specifically? There is dvc package in core homebrew formulas already https://formulae.brew.sh/formula/dvc

**Comment by ivaquero** [comment]
Yeah, I saw the package in Homebrew Core. However, a Cask takes less time to download.

**Comment by efiop** [comment]
@ivaquero Are there other packages that have both formula and a cask? I worry that it might not get accepted. Or are you planning to use a private tap?

**Comment by ivaquero** [comment]
Sure, R is in Homebrew Core and Homebrew Cask.

**Comment by efiop** [comment]
@ivaquero Thanks, good to know.

Regarding the issue itself, it looks like you are simply missing `uninstall pkgutil: 'com.iterative.dvc'` in your `dvc.rb`. We used to have a cask in our private tap too long time ago.

**Comment by efiop** [comment]
Also, you are using `https://github.com/iterative/dvc/releases/download`, which is not the official pkg source. Use `https://dvc.org/download/osx/dvc-2.31.0` instead, as those are signed.

**Comment by efiop** [comment]
Closing since this is cask's `dvc.rb` issue and has nothing to do with dvc itself

**Comment by ivaquero** [comment]
Thank you.
