### ISSUE TITLE
Add 'This operation may take a while' for long running commands

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#853]
I.e. add for 100K files and so on.

**Comment by vfdev-5** [comment]
As  commands like `gvc add dataset` are syncronious, maybe add a progress bar would cool and useful to know how much time it will take to add files. In my case dataset is 500GB and it take too much time...

Thanks

**Comment by efiop** [comment]
@vfdev-5 Thank you for your feedback! We've actually added a progress bar for large files(>1G) and directories(>100files) yesterday, which greatly helps with that. We will release it later today.

Thanks,
Ruslan

**Comment by vfdev-5** [comment]
Oh, sounds great! Thank you, will try the master version
