### ISSUE TITLE
_DVCFileSystem returns extra part on relative path. Impact on dvc.api.get_url on r2.34.0

### ISSUE THREAD

**Issue by giannipablo** [iterative/dvc#8545]
# Bug Report

## Description

I've updated from release 2.8.3 to 2.34.0 and dvc.api.get_url crashes. 

### Reproduce

Repo structure:

```
repo_root_dir
  |_ common
      |_ other_deps
          |_ other.bin
  |_ module_a
      |_ dependencies
          |_ dep_1.bin
          |_ dep_2.bin
      |_ my_app.py
      |_ setup.py
  |_ module_b
  |
  .
  .
  . 
  | _module_n
```
During the building, located at module_a folder, I resolve some binaries dependencies URLs based on path using  

```python
dvc.api.get_url('module_a/dependencies/dep_1.bin')
```
under release 2.8.3 it worked ok but now with release 2.34.0 i got the following error

```console
>>> FileNotFoundError: [Errno 2] No such file or directory: '/Users/myuser/projects/repo_root_dir/module_a/module_a/dependencies/dep_1.bin'
```

Notice that the module_a part is repeated in the path arisen from the error. Following the code I was able to find that

```console
$ pwd
/Users/myuser/projects/repo_root_dir/module_a/
$ python
>>> from dvc.fs.dvc import _DVCFileSystem

>>> path = module_a/dependencies/dep_1.bin'

>>> dvc_file_system = _DVCFileSystem()
>>> dvc_file_system.path.relparts(path, '/')

Out: 
( 'module_a', 
  'module_a', 
  'dependencies', 
  'dep_1.bin' )
```
The same but in the repo root directory
```console
$ pwd
/Users/myuser/projects/repo_root_dir/
$ python
>>> from dvc.fs.dvc import _DVCFileSystem

>>> path = module_a/dependencies/dep_1.bin'

>>> dvc_file_system = _DVCFileSystem()
>>> dvc_file_system.path.relparts(path, '/')

Out: 
( 'module_a', 
  'dependencies', 
  'dep_1.bin' )
```

#### Lookin the code
Looking at this line 
https://github.com/iterative/dvc/blob/a6bfc7db4ed3a86c58b4bfac3b22f5ad0b08e338/dvc/fs/dvc.py#L165
Looks like the comparison is not removing the extra part. `os.curdir` is the local folder `.` if i tested right.

Hope this helps.

Thanks and grate job!

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.34.0 (pip)
---------------------------------
Platform: Python 3.8.5 on macOS-11.6.5-x86_64-i386-64bit
Subprojects:
        dvc_data = 0.25.3
        dvc_objects = 0.12.2
        dvc_render = 0.0.12
        dvc_task = 0.1.4
        dvclive = 1.0.1
        scmrepo = 0.1.3
Supports:
        azure (adlfs = 2022.10.0, knack = 0.9.0, azure-identity = 1.7.1),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: azure
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Comment by giannipablo** [comment]
let me know if you need any test from my side.

**Comment by dberenbaum** [comment]
@giannipablo Good catch! Since you have already debugged it, would you be interested in submitting the PR to fix this?

**Comment by dberenbaum** [comment]
> Looks like the comparison is not removing the extra part. `os.curdir` is the local folder `.` if i tested right.

By the way, I think this is intentional (sometimes `path[0] == "."`), so we should not get rid of this logic, but instead add another check for something like `parts[0] == self.path.split(os.getcwd())[-1]`. cc @skshetry

**Comment by giannipablo** [comment]
@dberenbaum PR submitted! Please take a look at the fix just to be sure. I tested it and the dvc.api.get_url solved the url properly.

**Comment by skshetry** [comment]
Hi @giannipablo, is the problem happening because you are changing the directory to `module_a`? The path that you are passing should be a relative path, so instead of `module_a/dependencies/dep_1.bin`, it should be `dependencies/dep_1.bin` as you are inside `module_a` already.

Let me know if I did not understand correctly. Thanks.

**Comment by giannipablo** [comment]
Hi @skshetry , sorry for the delayed answer! Based on your comments, I've tested the get_url method from version 2.8.3 and current version and looks like the former version works relative to repo root directory but the later version works relative to current directory. 

That was somnthing I didn't test before. And ofcourse that make sens why our application started crashing after `pip install  --upgrade dvc`. We loosed compatibility.

**Comment by skshetry** [comment]
I think this behaviour is more correct. There have been a lot of internal changes since 2.8 in DVC. I do see that the API docs are not clear  what paths are supposed to be for local repositories. I’ll try to update it soon.

closing the issue for now.
