### ISSUE TITLE
gc: `dvc gc -c` is slow on s3 storage with many files

### ISSUE THREAD

**Issue by SolomidHero** [iterative/dvc#8549]
Hi I accidentally pushed big datasets with many small files  (~500GB, 5M+ files, <100 folders).
I `dvc add` each folder then `dvc push`.
I realised I should process them via archives and stage unzipping.
But now I can't remove cache from s3 storage of data I pushed before, because of really slow process. It consumes a lot of time and money :(

What I do is:
```
dvc gc -c --rev HEAD
```

I see that it worked about 20h and removed only 200k files from cloud storage (it was expensive to push data to storage bcs of number of requests, now it is expensive bcs of time instance running).
Can you please elaborate speed up of this process?

### Expected

Remove files from cloud faster than it has been uploaded.

### Environment information
```
dvc==2.34.0
dvc-data==0.25.3
dvc-http==2.27.2
dvc-objects==0.12.2
dvc-render==0.0.12
dvc-s3==2.21.0
dvc-task==0.1.4
dvclive==1.0.1
```

**Comment by pmrowla** [comment]
This is probably the same issue as https://github.com/iterative/dvc/issues/5961

**Comment by pmrowla** [comment]
> Remove files from cloud faster than it has been uploaded.

`gc` is inherently slower than upload due to how the S3 API works. `gc` requires listing all of the objects in the bucket which is slow, especially because we do not currently do the listing in parallel (see the linked issue)

**Comment by skshetry** [comment]
s3 supports bulk-delete of upto 1000 objects (and so does s3fs). I think the problem may be `fs.remove()` than the listing.

**Comment by SolomidHero** [comment]
Haha, finally they were deleted from storage.
<img width="453" alt="Screenshot 2022-11-16 at 16 29 41" src="https://user-images.githubusercontent.com/28161779/202142527-bf9bdea4-47b3-4e39-b369-d8e8cd1d046b.png">

**Comment by daavoo** [comment]
I think we can close this one in favor of #5961. 
Don't mean to dismiss the issue, just trying to keep the conversation in 1 place.
