### ISSUE TITLE
dvc push: progress bar frozen at 0% when pushing to S3 until completed on M1 MacBook Pro

### ISSUE THREAD

**Issue by BlackHC** [iterative/dvc#8557]
# Bug Report

## Description

The progress bar remained frozen at 0% until it had completed sending data to S3. I thought S3 was broken or so, but it was just the progress bar not working. This was not a short push but 100 MB and took a few minutes on my connection. The upload finished fine, however. (Took me a random break to not ctrl-c and see that it finished eventually.)

### Reproduce

Setup a remote to S3 and add some data.

dvc push

### Expected

A progress bar that keeps updating every 10 seconds or so.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.33.0 (brew)
---------------------------------
Platform: Python 3.10.8 on macOS-12.6-arm64-arm-64bit
Subprojects:
	dvc_data = 0.25.1
	dvc_objects = 0.12.1
	dvc_render = 0.0.12
	dvc_task = 0.1.4
	dvclive = 0.12.1
	scmrepo = 0.1.2
Supports:
	azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.11.0),
	gdrive (pydrive2 = 1.14.0),
	gs (gcsfs = 2022.10.0),
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	oss (ossfs = 2021.8.0),
	s3 (s3fs = 2022.10.0, boto3 = 1.24.59),
	ssh (sshfs = 2022.6.0),
	webdav (webdav4 = 0.9.8),
	webdavs (webdav4 = 0.9.8),
	webhdfs (fsspec = 2022.10.0)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Comment by skshetry** [comment]
Locally, I can see that the progress bar is working fine. Would you please try updating and see if it fixes the issue? If not, please check with the pip-installed package as well.

**Comment by skshetry** [comment]
Also @BlackHC, is that 100 MB file tracked using `dvc add`?

**Comment by BlackHC** [comment]
I've tested with the 2.34.0 pip version as well. It has the same issue.

The files were added with `dvc add`. I just had the same issue again with a few files that are 1MB each.

I'm using S3. It would seem that it's a problem with reporting progress when pushing to S3. The push itself succeeds and the files are copied to S3. It's just the progress bar that is not working at all and remains at 0%.

Thanks!

**Comment by daavoo** [comment]
Hi @BlackHC , which terminal are you using?

**Comment by BlackHC** [comment]
PyCharm's terminal. Note that it's not a TQDM or similar issue. The overall progress bar works:

E.g.:
```
 33% Transferring|█████████████████████████████████████████████████████                                                                                                          |1/3 [00:08<00:17,  8.57s/file]
                                                                                                                                                                                                                
  0%|          |/Users/andreaskirsch/PycharmProjects/xxxx/.dvc/cache/43/7b424ca7ed779658b02c45da716a2c                                                     0.00/1.95M [00:00<?,        ?B/s]
  0%|          |/Users/andreaskirsch/PycharmProjects/xxxx/.dvc/cache/7b/cbf03e78f78cfbc1ca8145115e06b8                                                     0.00/3.11M [00:00<?,        ?B/s]
```
