### ISSUE TITLE
`dvc metrics show` does not warn on invalid values

### ISSUE THREAD

**Issue by PythonFZ** [iterative/dvc#8560]
# Bug Report

**EDIT**
The issue was due to me saving the output as a `str` and not a `float` in the json file.
In principle this issue can be closed but I still think that instead of printing nothing it could be helpful to log a warning that the metrics could not be parsed?

-----------

I was using the current time as a metric, which as a float looks like `20221114150758.770046`.
I know this might be an edge case but neither `dvc metris show / diff` nor `dvc exp show` is able to show the output.
It does not log a warning and just prints the filename the metric is stored at.

### Reproduce

Create a metrics file: 

```json
{
    "time": "20221114150758.770046"
}
```
and use any `dvc metrics show`

### Expected

Either a warning that the metric could not be parsed or displaying the actual value.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.34.1 (pip)
---------------------------------
Platform: Python 3.10.6 on Linux-5.4.0-131-generic-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.25.3
        dvc_objects = 0.12.2
        dvc_render = 0.0.12
        dvc_task = 0.1.5
        dvclive = 1.0.1
        scmrepo = 0.1.3
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2022.11.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: nfs4 on 129.69.120.96:/zfswork
Caches: local
Remotes: None
Workspace directory: nfs4 on 129.69.120.96:/zfswork
Repo: dvc, git
```

**Comment by pmrowla** [comment]
If you run `metrics show -v` you will get a more detailed message like
```
2022-11-15 16:16:35,055 DEBUG: Could not parse 'foo' metric from 'foo.json' at '' due to its unsupported type: 'str'
```

We currently do not output this at a higher level than DEBUG since some users do this intentionally (and keep strings in metrics files that they use internally but want to be silently ignored by DVC)
