### ISSUE TITLE
dvcignore: allow for git tracking of gitignored files

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8574]
Should dvcignored files within a dvc-tracked directory be gitignored? It would be useful to be able to still track those files. For example, https://mlem.ai/doc/user-guide/dvc#versioning-binaries-manually suggests `echo "/**/?*.mlem" > .dvcignore` for `.mlem` files. If you `dvc add` a directory, it will not be tracked at either git or dvc, when ideally it would be tracked by dvc.

Example:

```
$ mkdir dir
$ echo foo > dir/foo
$ echo bar > dir/bar
$ echo dir/bar >> .dvcignore
$ dvc add dir
$ cat .gitignore
/dir
```

Instead, `.gitignore` could be something like:

```
/dir/*
!/dir/bar
```

**Comment by aurelm95** [comment]
As I commented in https://github.com/iterative/dvc/issues/8598#issue-1458207157 , My dataset matches the following schema

```
dataset/
├─ annotation1.txt
├─ img1.jpg
├─ annotation2.txt
├─ img2.jpg
.
.
.
```

Typically, I would run `echo *.txt >> .dvcignore` and `dvc add dataset` . 

If I also wanted to track the annotations files (which are dvcignored) with git , a workaround for me would be to run `dvc add dataset/*.jpg` (without telling dvc to ignore the `.txt` files) and `git add dataset`.

The thing is that for me is a little bit annoying to have the `.dvc` files inside the  dataset folder.

Isn't there a way to create a single `.dvc` file outside the dataset folder to track all the `.jpg` files ??
