### ISSUE TITLE
exp run: Incorrect string handling

### ISSUE THREAD

**Issue by KernelA** [iterative/dvc#8583]
# Bug Report

## Description

DVC with hydra composition does not write quotes in the strings to `param.yaml` and changes type of parameter from a string to a bool when a string is `'no'`

### Reproduce

1. [Enable hydra composition](https://dvc.org/doc/user-guide/experiment-management/hydra-composition)
2. Create simple config `conf/config.yaml`: 
```yaml
param_as_string: 'no'
```
3. Create `dvc.yaml`:
```yaml
stages:
  test:
    cmd: "python --version"
```
4. `dvc exp run`

### Expected

`params.yaml`:
```yaml
param_as_string: 'no' # string type
```
### Actual

`params.yaml`:
```yaml
param_as_string: no # bool type
```

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.34.2 (pip)
---------------------------------
Platform: Python 3.9.13 on Linux-5.15.0-52-generic-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.25.3
        dvc_objects = 0.12.2
        dvc_render = 0.0.12
        dvc_task = 0.1.5
        dvclive = 1.0.1
        scmrepo = 0.1.3
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2022.10.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme2n1p2
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme2n1p2
Repo: dvc, git
```

**Comment by daavoo** [comment]
Hi @KernelA , thanks for the report. It should be fixed with #8587
