### ISSUE TITLE
.dvcattributes like git-lfs

### ISSUE THREAD

**Issue by dktanwar** [iterative/dvc#8584]
## Example content of `.gitattributes`

```bash
*.7z filter=lfs diff=lfs merge=lfs -text
*.br filter=lfs diff=lfs merge=lfs -text
*.gz filter=lfs diff=lfs merge=lfs -text
*.tar filter=lfs diff=lfs merge=lfs -text
*.zip filter=lfs diff=lfs merge=lfs -text
```

This file then automatically filter matching pattern to `git-lfs`. A similar way would be good for `dvc`

**Comment by skshetry** [comment]
It's unclear to me what `.dvcattributes` would do.

**Comment by dktanwar** [comment]
Let's say I have the following directory:

```bash
project
     |--- data
          |--- folder1
                    |--- file1.gz
                    |--- file2.gz
          |--- folder2
                    |--- file3.gz
                    |--- file4.gz
          |--- folder3
                    |--- file5.gz
                    |--- file6.gz
```

Now, I would like all the `.gz` file to be added by `dvc`.

With `.dvcattributes` file, I should be able to define the files extensions I would like to be added by `dvc`.

Please let me know if this is still unclear.
