### ISSUE TITLE
ERROR: unexpected error - Unable to decrypt PKCS#1 private key

### ISSUE THREAD

**Issue by sudapure** [iterative/dvc#8592]
# Bug Report

## Description

While fetching the data from `ssh-remote` storage mentioned error is occurring, however while trying this on other machines and other remotes everything is working fine by simply providing the ssh password for authentication. below are the contents of dvc `.config`
```
[core]
    remote = storage
[remote "ssh-storage"]
    url = ssh://192.168.1.127/home/cemtrex/Core-Research-Experimentation
    user = cemtrex
    port = 22
    ask_password = true
    #password = ssh_password
```
### Reproduce
After entering the correct ssh password below error appears. 

```
$ dvc fetch -r ssh-storage

Enter a private key passphrase or a password for host '192.168.1.127' port '22' user 'cemtrex': 

ERROR: unexpected error - Unable to decrypt PKCS#1 private key                                                                                                                                

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

### Expected

As a output to mentioned command the `dvc` should authenticate with ssh password as `ask_password` is set in dvc `.config` and all data artifacts should get downloaded from the remote ssh storage.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.6.9 on Linux-5.4.0-128-generic-x86_64-with-Ubuntu-18.04-bionic
Supports:
        webhdfs (fsspec = 2021.10.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.10.0, boto3 = 1.17.106),
        ssh (sshfs = 2021.11.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p4
Caches: local
Remotes: s3, ssh
Workspace directory: ext4 on /dev/nvme0n1p4
Repo: dvc, git
```

**Additional Information (if any):**

 I also tried running this with different dvc versions but still the same issue, it looks like something is wrong with the ssh settings configured in the O.S settings, but i am not able to figure it out exactly what causing the problem. I also referred to issue #3519 but still not able to figure it out.

**Comment by daavoo** [comment]
Hi @sudapure , could you try upgrading to the latest version and share the verbose (`-vv`) error traceback (if any)?

**Comment by sudapure** [comment]
I downgraded the version from `2.8.1` to `2.0.5` and added `allow_agent=False` to `[remote "ssh-storage"]` section and everything is working fine.

**Comment by sudapure** [comment]
closing this issue as it is resolved.

**Comment by dberenbaum** [comment]
@sudapure Is it resolved for you on newer versions of DVC, or by using an old version?

**Comment by sudapure** [comment]
@dberenbaum i tried with newer `dvc==2.10.2` and  `dvc[ssh]==2.10.2` versions, but problem still persists it's working with older (2.0.5) version only.

**Comment by pmrowla** [comment]
@sudapure the current DVC release is `2.35.1`, however DVC now requires Python 3.8 or later. It looks like you are still using 3.6, so you would be unable to update to newer versions of DVC unless you also update Python.
