### ISSUE TITLE
exp: Standalone experiment running in `--temp` folder should be included in `dvc exp show` table

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#8613]
When executing an experiment using `dvc exp run --temp`, the running experiment is not included in the output of `dvc exp list` nor `dvc exp show`. Using `--queue`, on the other hand, shows the experiment as running. It would be great if also in case of `dvc exp run --temp` the experiment would be included in the output of `dvc exp show`. Similarly, it should be possible to follow metrics and other plots produced by DVCLive (e.g., using VS Code extension).

**Comment by karajan1001** [comment]
Hi @aschuh-hf , in which version of DVC and vscode-extention are you? I'm in the latest one and can get a proper exp table on VS Code extension. 

![image](https://user-images.githubusercontent.com/6745454/203741379-e892cf8a-9bbb-49e6-9ca8-fa9aca4dc3cf.png)
![image](https://user-images.githubusercontent.com/6745454/203741410-1e6a6b31-91dd-4a78-a265-8700705081fc.png)

**Comment by aschuh-hf** [comment]
@karajan1001 Are you using `dvc exp run --queue`? In that case it does work. But not when using `dvc exp run --temp`.

```
$ dvc doctor
DVC version: 2.31.0 (rpm)
---------------------------------
Platform: Python 3.8.3 on Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.14
Subprojects:

Supports:
        azure (adlfs = None, knack = 0.10.0, azure-identity = 1.11.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = None),
        hdfs (fsspec = None, pyarrow = 9.0.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = None, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7),
        webhdfs (fsspec = None)
Cache types: hardlink, symlink
Cache directory: xfs on /dev/md124
Caches: local, s3
Remotes: s3, s3
Workspace directory: xfs on /dev/md124
Repo: dvc (subdir), git
```

**Comment by aschuh-hf** [comment]
@karajan1001 Which version of DVC were you using? Would 2.34.2 be sufficient? Having some troubles installing 2.35.

**Comment by karajan1001** [comment]
> Would 2.34.2 be sufficient

I think `2.34.3` includes most of the recently merged exp related PRs.

**Comment by aschuh-hf** [comment]
Thanks, I finally got 2.35.1 installed (cf. https://github.com/iterative/dvc-s3-repo/issues/89#issuecomment-1326644656) and can give it a try with the updated VS Code extension as well.

**Comment by aschuh-hf** [comment]
With the latest DVC version and VS Code Extension, I can now see the experiment executed with `dvc exp run --temp` in both the `dvc exp show` output and the VS Code Experiments tab. It took a few minutes after starting the experiment and a first checkpoint was made before it showed up. The VS Code Experiments table shows an entry for the checkpoints, but not a row with spinning wheel to indicate the running experiment (past the last checkpoint). Live plots of the running experiment are not showing.

The VS Code Experiments table seems to take quite some time to update (my Git repo is a larger mono-repo), but once I see it was executing `dvc exp show -n 3 --json` in the DVC Output window, the new checkpoints of the standalone experiment running in the `--temp` folder appear in the list / table.

I'm closing this issue and may open a new one for the DVC Live plots if I continue to observe these not showing.

**Comment by daavoo** [comment]
@aschuh-hf would be helpful if you could share a profile (i.e. https://github.com/iterative/dvc/wiki/Debugging,-Profiling-and-Benchmarking-DVC#generating-viztracer-data) of `dvc exp show -n 3 --json` / `dvc plots diff` to figure out what's taking so long

**Comment by aschuh-hf** [comment]
How should I share the ~150MB trace file?

Looking at the output, it is unfortunately not included a breakdown of all the steps in `experiments.show()` up to `_collect_branches`, i.e., where the majority of the time is actually spent.
<img width="2781" alt="Screen Shot 2022-11-24 at 5 28 47 PM" src="https://user-images.githubusercontent.com/77496589/203840574-ad284a8c-b469-4e42-89c2-f9f43a5cf27a.png">

**Comment by aschuh-hf** [comment]
This screenshot shows all the code that doesn't have a more detailed breakdown, but which consumes most of the time.

<img width="3002" alt="Screen Shot 2022-11-24 at 5 31 48 PM" src="https://user-images.githubusercontent.com/77496589/203840773-4e586087-3a4f-497c-9abf-bb4e955965db.png">

**Comment by aschuh-hf** [comment]
OK, I've increased the depth of the trace.

<img width="2998" alt="Screen Shot 2022-11-24 at 5 35 39 PM" src="https://user-images.githubusercontent.com/77496589/203841283-92f78f08-0ed7-40d9-bde8-9fae860e5f93.png">

**Comment by daavoo** [comment]
> OK, I've increased the depth of the trace.
> 
> <img alt="Screen Shot 2022-11-24 at 5 35 39 PM" width="2000" src="https://user-images.githubusercontent.com/77496589/203841283-92f78f08-0ed7-40d9-bde8-9fae860e5f93.png">

cc @karajan1001 any ideas?

**Comment by aschuh-hf** [comment]
```
$ time dvc exp show -n 3 --json --hide-failed > /dev/null

real    0m6.875s
user    0m4.751s
sys     0m2.081s

$ time dvc exp show -n 3 --json > /dev/null

real    0m47.790s
user    0m31.023s
sys     0m16.655s
```

Seems related to
- https://github.com/iterative/dvc/pull/8318
- https://github.com/iterative/vscode-dvc/issues/1995

It would be great if one could check / uncheck these options through the VS Code Settings. A workaround for me here would indeed be to be able to ignore failed experiments.

**Comment by karajan1001** [comment]
> It took a few minutes after starting the experiment and a first checkpoint was made before it showed up.

Might related to https://github.com/iterative/dvc/issues/8477
