### ISSUE TITLE
queue: Queue status output displays incorrect number of workers

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#8614]
# Bug Report

## Description

After starting multiple queue task workers with `dvc queue start --jobs 4`, the `dvc queue status` output displays incorrect number of workers. It first showed `1 active,  0 idle` and then only `0 active,  0 idle` although two tasks are `Running` (only two tasks had been queued when starting the workers).

### Reproduce

1. Start workers with `dvc queue start --jobs 4`
2. Check output of `dvc queue status`

### Expected

The sum of active and idle queue task workers should match the number of started workers.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.31.0 (rpm)
---------------------------------
Platform: Python 3.8.3 on Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.14
Subprojects:

Supports:
        azure (adlfs = None, knack = 0.10.0, azure-identity = 1.11.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = None),
        hdfs (fsspec = None, pyarrow = 9.0.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = None, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7),
        webhdfs (fsspec = None)
Cache types: hardlink, symlink
Cache directory: xfs on /dev/md124
Caches: local, s3
Remotes: s3, s3
Workspace directory: xfs on /dev/md124
Repo: dvc (subdir), git
```

**Additional Information (if any):**

Note that I am running DVC inside a Docker container, though it seems this should be irrelevant.

**Comment by karajan1001** [comment]
Hi, @aschuh-hf, 

The worker number output of `dvc queue status` ie `0 active, 0 idle: 0` is through the celery API, and shows the real number. And the `Running` status is actually incorrect. It is better use the worker status to double check the tasks tasks here. BTW  a wrong `Running` status usually indicates that something goes wrong with the worker. Could you please provide the logs of your worker, please? You can get them in 
`.dvc/tmp/exps/celery/dvc-exp-worker-1.out` ... `.dvc/tmp/exps/celery/dvc-exp-worker-4.out`

Thank you.

**Comment by aschuh-hf** [comment]
The output of `0 active, 0 idle` was however after the tasks were already running. I could see that by the GPU utilization as well as output of `dvc queue logs <task_id>`.

**Comment by aschuh-hf** [comment]
Checking the worker processes given the process IDs from `.dvc/tmp/celery/dcv-exp-worker-?.pid` using `ps aux | grep <pid>`, I can see that three of the worker processes (2-4) do not actually exist, but only one of the still running task.

Maybe the `dvc queue status` output should include a third column for available workers before the maximum limit of allowed workers is reached?
