### ISSUE TITLE
error: git push hook 

### ISSUE THREAD

**Issue by kspiderman** [iterative/dvc#8620]
# Bug Report

## Description
![error](https://user-images.githubusercontent.com/118428586/203772567-5220a0fb-fb7a-4c93-bc5e-c25c195acb36.png)

### Reproduce

1.dvc init
2.dvc install --use-pre-commit-tool
3.pre-commit install --hook-type pre-push --hook-type post-checkout --hook-type pre-commit
4.dvc remote add -d myremote  webdavs://example.com/owncloud/remote.php/dav
5.dvc add ./myfolder/
6.git commit
7.git push

### Expected

No error

### Environment information
dvc                                  2.34.2
dvc-data                             0.25.3
dvc-http                             2.27.2
dvc-objects                          0.12.2
dvc-render                           0.0.12
dvc-task                             0.1.5
dvc-webdav                           2.19.0
dvclive                              1.0.1

**Comment by pmrowla** [comment]
`pre-commit` uses it's own virtualenv (and separate DVC installation). You have to specify the remote dependencies to install in the appropriate hook's `additional_dependencies`  of your `.pre-commit-config.yaml` as described in the docs: https://dvc.org/doc/command-reference/install#using-the-pre-commit-tool

so for your pre-push config you would need `additional_dependencies: ['.[webdav]']`

**Comment by kspiderman** [comment]
thanks
