### ISSUE TITLE
exp run/save: untracked files

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8629]
I'm still seeing issues with files not being saved by the experiment:

```
# Add stage to dvc.yaml
$ dvc stage add -q -n exp_save -M metrics.yaml 'echo "foo: 1" > metrics.yaml'
# Add random file
$ echo misc > misc
# Generate metrics
$ dvc repro -q
# Track everything with git
$ git add .
# Save experiment
$ dvc exp save -q
# Stash everything from the workspace
$ git stash -u
# Apply the experiment to recover saved files
$ dvc exp apply exp-48145
# Metrics aren't saved
$ dvc exp show
 ────────────────────────────────────
  Experiment                Created
 ────────────────────────────────────
  workspace                 -
  main                      09:14 AM
  └── d453430 [exp-48145]   09:14 AM
 ────────────────────────────────────
# No files were recovered during apply
$ git status
On branch main
nothing to commit, working tree clean
```

There are 2 issues:
1. `dvc exp run` saves `metrics.yaml`, `dvc.yaml`, and `dvc.lock` regardless of whether they are added to git, but `dvc exp save` loses all of these. It seems like this is needed for it to be useful the first time the experiment is saved.
2. Neither `dvc exp run` or `dvc exp save` saves arbitrary new files, even if they are added to git. This is related to the idea from the previous PR that it should include all untracked files. It might not be a blocker for now if solving the first issue is enough for dvclive, but it seems like there needs to be some mechanism to save new files to an experiment (either all untracked files or at least those that have been added to git).

_Originally posted by @dberenbaum in https://github.com/iterative/dvc/issues/8599#issuecomment-1326523109_

**Comment by dberenbaum** [comment]
>     1. `dvc exp run` saves `metrics.yaml`, `dvc.yaml`, and `dvc.lock` regardless of whether they are added to git, but `dvc exp save` loses all of these. It seems like this is needed for it to be useful the first time the experiment is saved.

`dvc exp run` will not save `dvc.lock` in the experiment ref if you run the same steps, replacing `exp save` with `exp run`. After `exp apply` you will only see `dvc.yaml` and `metrics.yaml`. 

It will include in the ref the `dvc.yaml` because it is needed for executing the pipeline and `metrics.yaml` because it's produced by the execution pipeline.  `dvc.lock` will be present in the workspace as an untracked file as a result of the execution, but it will not be the `dvc.lock` produced by `repro -q`, that one is lost.

I don't mean to dismiss the point, but in `exp save` there is no execution at all, so the differences in behavior kind of make sense to me. If we want to match `exp run`, I guess we could default to use `include_untracked` with `dvc.lock`, `dvc.yaml` and all outputs in the pipeline?

In the DVCLive scenario, DVCLive will take care of including the untracked files by https://github.com/iterative/dvc/pull/8599#discussion_r1031727100

In the DVC scenario, I can expose the same option to the CLI, and/or we can be very explicit in docs about the behavior of staged and/or untracked files.

I think the UI is already clear. These are the current warnings:

```console
# staged
$ dvc exp save
WARNING: Your workspace contains staged Git changes which will be unstaged before saving this experiment.
WARNING: The following untracked files were present in the workspace before saving but will not be included in the experiment commit:
	metrics.yaml, dvc.lock, dvc.yaml
```

```console
# untracked
$ dvc exp save
WARNING: The following untracked files were present in the workspace before saving but will not be included in the experiment commit:
	metrics.yaml, dvc.lock, dvc.yaml
```

_Originally posted by @daavoo in https://github.com/iterative/dvc/pull/8599#issuecomment-1326716109

**Comment by dberenbaum** [comment]
> `dvc exp run` will not save `dvc.lock` in the experiment ref if you run the same steps, replacing `exp save` with `exp run`. After `exp apply` you will only see `dvc.yaml` and `metrics.yaml`.

I ran `dvc exp run` in place of multiple steps:


```
# Generate metrics
$ dvc repro -q
# Track everything with git
$ git add .
# Save experiment
$ dvc exp save -q
```

When I do that `dvc.lock` does get saved. Why is it saved in that case?

---

> It will include in the ref the `dvc.yaml` because it is needed for executing the pipeline and `metrics.yaml` because it's produced by the execution pipeline. `dvc.lock` will be present in the workspace as an untracked file as a result of the execution, but it will not be the `dvc.lock` produced by `repro -q`, that one is lost.
> 
> I don't mean to dismiss the point, but in `exp save` there is no execution at all, so the differences in behavior kind of make sense to me. If we want to match `exp run`, I guess we could default to use `include_untracked` with `dvc.lock`, `dvc.yaml` and all outputs in the pipeline?

What about top-level metrics, params, and plots in `dvc.yaml`? Should `exp save` include those? Should `exp run`?

---

More generally, does it make sense (for `exp run` or `exp save`) to unstage and ignore these files? What is the recommended workflow here?

**Comment by jorgeorpinel** [comment]
Note: this feature solves https://github.com/iterative/dvc/issues/5800, I think?

**Comment by dberenbaum** [comment]
> Note: this feature solves #5800, I think?

🤔 It's not available for `dvc exp run` today, although we should add it there @dtrifiro. Even if it were, I don't think it's quite the same because:
* I don't know whether it works for gitignored files
* Once they are included, the files will be tracked by Git, which I don't think is the desired behavior

**Comment by dberenbaum** [comment]
I think this can be closed.
