### ISSUE TITLE
`dvc.cli.main` disables logging of other packages

### ISSUE THREAD

**Issue by PythonFZ** [iterative/dvc#8631]
## Description
I'm developing the https://github.com/zincware/ZnTrack package to interface with DVC.
I was relying on `subprocess.check_call(["dvc", ...])` but wanted to switch to `dvc.cli.main([...])` instead.
Using the DVC API gives a noticeable performance increase.
Unfortunately, doing so the logger of my package will be permanently disabled.

### Reproduce

```python
import logging
import sys
import dvc.cli

logger = logging.getLogger("mypackage")
logger.setLevel(logging.DEBUG)

channel = logging.StreamHandler(sys.stdout)
channel.setLevel(logging.DEBUG)

logger.addHandler(channel)

print(logger.disabled)
# False
dvc.cli.main(["init"])
print(logger.disabled)
# True
```

### Expected

I know the `dvc.cli` API is currently not exposed but it would be helpful if it would not disable logging of other python packages.

### Fix

capture the  disabled loggers from
https://github.com/iterative/dvc/blob/bb80eab77ae5830790113acd1b5b49bf311e5127/dvc/cli/__init__.py#L159
and enable them at the end.
If this would be an accepted fix, I can implement it and make a PR?

**Comment by daavoo** [comment]
> I was relying on subprocess.check_call(["dvc", ...]) but wanted to switch to dvc.cli.main([...]) instead.
Using the DVC API gives a noticeable performance increase.

hi @PythonFZ , don't mean to dismiss this request, but have you considered using the [ `dvc.repo.Repo` ](https://github.com/iterative/dvc/blob/main/dvc/repo/__init__.py#L53)API? 

It should be more efficient than `cli.main` calls while still providing the same (minus some UI) features. For example, you could reuse the same `Repo` instance for multiple calls.

**Comment by PythonFZ** [comment]
That is what I want to do eventually.
I'm already using it for my DVC and HPC package https://github.com/zincware/dask4dvc but I'm still in the progress of understanding. Switching to cli already sped up my Test suit by a Factor of 3.

**Comment by skshetry** [comment]
We might be able to get rid of `disable_other_loggers()` in `main()`, since we lazily import most of the libraries, so it's probably not doing anything at all. I see it disabling the following loggers:
```
tqdm.cli
tqdm
asyncio
aiohttp
dvc_objects
dvc_data
```

`tqdm.cli` and `tqdm` should not be a problem, `asyncio` and `aiohttp` are already explicitly changed to `CRITICAL` only in `dvc.logger.setup()` and the last two are explicitly enabled later through config.

**Comment by skshetry** [comment]
Note that DVC only has one stable API: the command line. The `dvc.cli.main` also is guaranteed to be backward-compatible as it is an entry point to the commandline even if it's undocumented. `Repo` api has no such guarantees, although they don't change very often.

**Comment by PythonFZ** [comment]
The following should work as a replacement for the `disable_other_loggers()` increasing the execution time on my machine  from `6.14 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)` to `7.31 µs ± 613 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)`.  Changing `if logger_name != "dvc" and not logger_name.startswith("dvc.")` to `if not logger_name.startswith("dvc")` gave a performance incrase of about `1 µs`.

Would this be an acceptable solution to you?

```python
import contextlib

@contextlib.contextmanager
def disable_other_loggers():
    logging.captureWarnings(True)
    loggerDict = logging.root.manager.loggerDict  # pylint: disable=no-member

    disabled_logger_list = []

    for logger_name, logger in loggerDict.items():
        if not logger_name.startswith("dvc"): 
            if not logger.disabled:
                disabled_logger_list.append(logger)
                logger.disabled = True
    try:
        yield
    finally:
        for logger in disabled_logger_list:
            logger.disabled = False
```
and then

```python
with disable_other_loggers():
   ...
```
