### ISSUE TITLE
Continue running non-dependent stages after stage failure

### ISSUE THREAD

**Issue by cgokmen** [iterative/dvc#8647]
Hi,

First of all, many thanks for all the work you guys have been putting into DVC. We're using it as a key part of our assets pipeline for our robotics simulation environment at Stanford's AI lab, and it is definitely a great tool to have in our toolkit.

The particular context of our project involves thousands of pipeline stages that first perform a serial chain of operations (check/export/postprocess in the below diagram) on each input file, and then an aggregation across the different chains.  This is of course a simplified version of what we are actually doing.

```mermaid
  graph TD;
      Check_Potato-->Export_Potato;
      Export_Potato-->Postprocess_Potato;
      Postprocess_Potato-->Aggregate;
      Check_Tomato-->Export_Tomato;
      Export_Tomato-->Postprocess_Tomato;
      Postprocess_Tomato-->Aggregate;
```

When we make changes in our code and run `dvc repro`, we typically need to leave the process running over multiple days for it to complete due to the sheer number of stages we have. However, in case one of the stages fails, `repro` will exit, despite the fact that most of the remaining stages in the execution queue are still executable w/o a problem. This means, in order to make sure that we are still making progress and not losing days of time, we need to babysit the process by repeatedly checking the status. I also jury-rigged a tool to help with this that simply calls `dvc repro` separately with the name of each stage. However, with a project of this size, whatever initialization task (e.g. checking stages) that DVC does before starting to repro stages makes this approach take prohibitively long.

The feature I would like to request is a `--continue-on-failure` flag for `dvc repro` that would make DVC keep executing stages even if one of them fails. The simple way to implement this would be that after applying its topological sort, DVC would iterate through the stages executing them one by one **unless** one of their dependencies was run and failed, in which case they would be skipped. So for example, if `Export Potato` fails, `Postprocess Potato` and `Aggregate` would be blocked from executing, but all of the `Tomato` stages would still execute.

Let me know what you think & also if you have any existing ways of reproducing this behavior.

**Comment by skshetry** [comment]
Duplicate: https://github.com/iterative/dvc/issues/7292
