### ISSUE TITLE
exp: generate random experiment names at start of each experiment

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8650]
Move the logic from dvclive in https://github.com/iterative/dvclive/blob/127cbd4dd7f55ca573c0c45bb90073cada93e87f/src/dvclive/dvc.py#L80 to dvc to assign a human-readable experiment name at the start of each experiment.

**Comment by shcheklein** [comment]
Can we do this as a p1? Otherwise I feel we'll start on this soon in VS Code independently :) If we agree on this path it's better to do it now I think.

**Comment by daavoo** [comment]
I have already started because is also convenient for the live metrics proposal. Unless I am missing something it should be ready this sprint

**Comment by shcheklein** [comment]
Thanks @daavoo !!
