### ISSUE TITLE
Running `exp queue status` is very slow 

### ISSUE THREAD

**Issue by behrica** [iterative/dvc#8676]
Running `exp queue status` is very slow.

I noticed that after submitting 200 run jobs the queue, the `dvc exp queue  status`  became very slow.
In the order of 5 minutes for giving a result.

dvc doctor:

```
DVC version: 2.36.0 (pip)
---------------------------------
Platform: Python 3.10.8 on Linux-6.0.11-arch1-1-x86_64-with-glibc2.36
Subprojects:
	dvc_data = 0.28.3
	dvc_objects = 0.14.0
	dvc_render = 0.0.14
	dvc_task = 0.1.6
	dvclive = 1.1.0
	scmrepo = 0.1.4
Supports:
	azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.11.0),
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb1
Caches: local
Remotes: azure, local
Workspace directory: ext4 on /dev/sdb1
Repo: dvc, git
```

**Comment by behrica** [comment]
I can imgine that this is hard to look at to you.
so maybe a bit more of information.

It seems to me that "search tasks" is very slow. If I run the `dvc queue status` with `-v` I see a rather slowy progressing line of 


```
2022-12-20 18:16:57,134 DEBUG: Found done task 71046ebe10172885891d4bf4ee2c0322b2f4ab90
2022-12-20 18:16:58,738 DEBUG: Found done task 0d83d52ee66434f6ddadf39cc324fc8cb33253ef
2022-12-20 18:17:00,387 DEBUG: Found done task 95345375b06afeeca8171a5cc07e7547c6b533cc
2022-12-20 18:17:03,179 DEBUG: Found done task 71046ebe10172885891d4bf4ee2c0322b2f4ab90
```

One every second. Even after emptying the queue, I still have those.

Any idea, what I could do to speed up my experiment database ?

**Comment by behrica** [comment]
I think my problem is still related to "crashing tasks" resulting into a "bad state" of the task queue.
In this situation other dvc commands become very slow as well, like `dvx exp show`
The machine was rebooted several times, so there is nothing left running , but I still see "one running" tasks in the queue. I can neither stop  nor kill it.

Is there a way to "wipe" certain folders / files on disk and remove all remains from queued tasks, so I can use my dvc repo again.

**Comment by daavoo** [comment]
> Is there a way to "wipe" certain folders / files on disk and remove all remains from queued tasks, so I can use my dvc repo again ?

@behrica You could force a reset by removing  `.dvc/tmp/exps` (https://dvc.org/doc/user-guide/project-structure/internal-files#internal-directories-and-files) if you are certain that there is no important information there

**Comment by dberenbaum** [comment]
@behrica Is it still an issue for you?

**Comment by behrica** [comment]
I have not tried it for a while.
Have you fixed something ?

It happens every time , when I queue a few thousand runs and need to kill processes or similar.

**Comment by behrica** [comment]
So it goes a bit into the question of how stable DVC is for queuing thousands of tasks and let it run for days.
I tried this 3 or 4 times and it always gave issues. I used version 2.36

**Comment by behrica** [comment]
Apart from stable, I could not recover from the crash as described before.

**Comment by karajan1001** [comment]
> queue a few thousand runs 

I guess the problem comes from the number of experiments in the queue. For now, both collecting them and rendering them all takes some time, it's not very serious problem for small number experiments.

**Comment by daavoo** [comment]
> I guess the problem comes from the number of experiments in the queue. For now, both collecting them and rendering them all takes some time, it's not very serious problem for small number experiments.

Do we have some heuristics to determine at which number it starts to be a problem?
Should we add a warning in the docs?

**Comment by behrica** [comment]
I would of course argue, that the "thousands of tasks" and running for days,
is a main usecase for DVC .... (apart from data management)
I would hope that in long run this thousand of individual processes are more stable then one big process for days (and doing the hyperparameter sweep in code)
But maybe the current design of DVC and it's "files on disk approach", does not scale that high.

**Comment by behrica** [comment]
I still think it is not "only big number of tasks"  but "big number of tasks and the need/attempt to kill some of them",
which made teh problem.

**Comment by karajan1001** [comment]
Hello, @behrica I have a few questions. 

1. Are the experiments checkpoint ones or normal ones. 
2. When does the slowly `exp queue status`, after you add all the experiments to the queue or during the queue worker's running? 
3. Could you please give me the `cprofile` dumps from `dvc queue status --cprofile-dump dump.prof`

**Comment by behrica** [comment]
1. Normal
2. during run, I think. But not sure.
3. I did not know aubit this profile. I guess I would need to run something again

**Comment by karajan1001** [comment]
> I did not know about this dump. I guess I would need to run something again

Yes, if you had any chance when you got this problem, run `dvc queue status` with `--cprofile-dump dump.prof` will give us a `cprofile` file `dump.prof` to help us to know the bottleneck of the `dvc queue status` cmd.

**Comment by gregstarr** [comment]
I am seeing this problem as well.

I have 20-30 experiments on the commit, some queued, some failed, some finished successfully and some running. `dvc exp show`, `dvc queue status` and `dvc queue logs <task>` all take a long time, over 5 minutes.

**Comment by pmrowla** [comment]
@gregstarr removing `.dvc/tmp/exps` will not remove any experiments that have already been finished (but it will remove logs for those experiments).

**Comment by behrica** [comment]
I think it is important to provide instructions (or a command line comment) to help clean up the situation that @gregstarr  described. I experienced the same issue and it made my DVC project directory unusable. I was able to recover, but I can't remember exactly what I did. Perhaps the solution is in one of the comments above.

**Comment by dberenbaum** [comment]
It seems we haven't fully identified the problem or steps to remedy it. If we can confirm that something like removing `.dvc/tmp/exps` helps, we can add it to the docs as a way to work around this. I think the hope is that we can prevent these problems so we don't even need to document a workaround.

**Comment by pmrowla** [comment]
The main performance issue here is w/having too many celery message files (since we have to iterate over them for things like `queue status`). Doing the garbage collection to clean up messages which are either expired or irrelevant is implemented in dvc-task now (see linked PR).

On the DVC end, we can add something like `exp clean` so users can force us to cleanup things we know we don't need, but for the celery messages in particular we can also just automatically do it in the background when queue workers exit.

**Comment by patrick-egenlauf** [comment]
I am still observing this issue. I queued 7500 experiments and called `dvc queue status` which took a while but did not output anything, so I killed the command. I started running all the experiments. After a while, all experiments seemed to be finished or crashed, so I called `dvc queue status -v`, which had the following result

```bash
2024-12-19 10:47:05,617 DEBUG: v3.51.2 (pip), CPython 3.10.12 on Linux-5.15.0-117-generic-x86_64-with-glibc2.35
2024-12-19 10:47:05,618 DEBUG: command: /datapool/homes/usr/.local/bin/dvc queue status -v
```

Then nothing happens except that my `ssh` connection terminates after ~40 minutes, which also kills the command. I tried `dvc exp clean`, but that didn't help. I tried running `dvc queue status --cprofile-dump dump.prof`, but I run into the same problem.

I tried to use the vscode extension to check my experiments, but it just loads forever (over 3 hours now).

Since I don't know how many of the experiments failed, I don't want to remove `.dvc/tmp/exps`.

```bash
> dvc doctor
DVC version: 3.58.0 (pip)
-------------------------
Platform: Python 3.12.5 on Linux-5.15.0-117-generic-x86_64-with-glibc2.35
Subprojects:
	dvc_data = 3.16.7
	dvc_objects = 5.1.0
	dvc_render = 1.0.2
	dvc_task = 0.40.2
	scmrepo = 3.3.9
Supports:
	http (aiohttp = 3.11.9, aiohttp-retry = 2.9.1),
	https (aiohttp = 3.11.9, aiohttp-retry = 2.9.1)
Config:
	Global: /datapool/homes/usr/.config/dvc
	System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: zfs on datapool/homes/usr
Caches: local
Remotes: None
Workspace directory: zfs on datapool/homes/usr
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/d3f55d3fba8ee50620add362dd47a685
```
