### ISSUE TITLE
exp branch: includes extra files when used with exp save

### ISSUE THREAD

**Issue by dtrifiro** [iterative/dvc#8680]
# Bug Report

## Description
When creating a branch from an experiment saved with `dvc exp save`, an extra file (`.dvc/tmp/repro.dat`) is commited.

### Reproduce
```bash
cd $(mktemp -d)
git init
dvc init
git commit -m "dvc init"
dvc exp save -n expname
dvc exp branch expname branchname
git show branchname # includes `.dvc/tmp/repro.dat`
```
### Expected

In the case when the workspace is clean, an error should be returned (nothing changed in the experiment). When modified files are present or untracked files are included, the experiment should succeed but should not contain the extra `.dvc/tmp/repro.dat`, which is just used for `dvc exp run` to pass repro arguments.

**Comment by daavoo** [comment]
> should not contain the extra .dvc/tmp/repro.dat, which is just used for dvc exp run to pass repro arguments.

We should probably not generate that file (add an option to skip?) when calling ` _stash_exp` from `experiments.save`
