### ISSUE TITLE
top-level params/metrics/plots/artifacts: support templating and foreach

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8696]
Templating and foreach are only supported in `stages` in `dvc.yaml`. It would be nice to have support in top-level `params`, `metrics`, `plots`, and `artifacts`.

**Comment by dberenbaum** [comment]
@skshetry pointed out that these should probably be separate issues since templating should be straightforward (syntax doesn't change, reuse existing top-level `vars`), whereas foreach will require new syntax (for one thing, `stages` are dicts whereas other top-level fields are lists). When we get to these, we can split them up.

**Comment by daavoo** [comment]
I am not sure I fully understand what `foreach` means for top-level metrics/params/plots

**Comment by skshetry** [comment]
yeah, I don't understand it as well. We are looking for a way to make it DRY, and less repeatable. Think of cases where the stages are already created with foreach and looped.

I proposed adding support for regex/globbing or directory params/metrics supports as an alternative too.

Also see https://iterativeai.slack.com/archives/CB41NAL8H/p1667074000124059.

**Comment by xnhp** [comment]
Globbing (also for `deps`, `out`, etc.) would be incredibly useful!

**Comment by paluchasz** [comment]
Would this feature be added any time soon? 

There's a lack of consistency between the stage plots and top level plots. Stage plots support templating but not the functionality of top level plots. Will have to hard code paths for the plots for the moment.

**Comment by dberenbaum** [comment]
@paluchasz Unfortunately, there's no estimate now for this feature. Do you use dvclive or is it possible for you to do so? That would write the paths to plots out for you automatically.

**Comment by dberenbaum** [comment]
Let's include all top-level sections in this issue and close #9999 as a duplicate.

**Comment by skshetry** [comment]
Planning on working on this week.

**Comment by uditrana** [comment]
Just wanted to +1 the glob patterns request
