### ISSUE TITLE
DVCLive experiments fail on Windows due to missing sqlite binaries

### ISSUE THREAD

**Issue by alex000kim** [iterative/dvc#8697]
When trying to run `python train.py` from this [project](https://github.com/iterative/dvclive-exp-tracking) on Windows, I was getting this error:
`ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.` 
(sorry, I didn't save the full error stack) 

The issue went away after following these instructions: https://stackoverflow.com/a/55642416

**Comment by skshetry** [comment]
How did you install dvc? Unless it is a binary executable, it seems to be an environment issue. 
Nothing we can do here.

**Comment by skshetry** [comment]
Closing as stale.
