### ISSUE TITLE
`dvc exp show` gives an error if `less` isn't installed on Windows

### ISSUE THREAD

**Issue by alex000kim** [iterative/dvc#8698]
`dvc exp show` gives an error if `less` isn't installed.
This issue is easily fixed by following this: https://dvc.org/doc/user-guide/how-to/run-dvc-on-windows#enabling-paging-with-less

**Comment by skshetry** [comment]
What's the error?

**Comment by skshetry** [comment]
ping @alex000kim.

**Comment by alex000kim** [comment]
Sorry, I don't have the error message now. 
The issue is that by default `less` isn't installed on Windows.

**Comment by pmrowla** [comment]
Seems like we probably just need to update the "running on windows" guide to note that `exp show` needs `less` to be installed as well (the current docs only list `dvc dag`)

**Comment by skshetry** [comment]
We should still be falling back to plain-pager, which just prints to stdout (there might be encoding errors or some bug in how we fall back to `less`). Looking at the code, it does seem to be checked correctly.

https://github.com/iterative/dvc/blob/a24c389674831024955f00b34075e096d45223f0/dvc/ui/pager.py#L50

**Comment by skshetry** [comment]
Closing as i was not able to reproduce in Windows. I uninstalled less, but it still printed to stdout.

will reopen if we get further information.
