### ISSUE TITLE
Cannot change the Google drive account after reinitializing dvc

### ISSUE THREAD

**Issue by sagar-harry** [iterative/dvc#8700]
# Bug Report
Unable to reauthenticate for different google account.

## Description

I have pushed the files using dvc push to my google drive; The followed procedure was:</br>
1. git init
2. dvc init
3. dvc add <files-location/file-name>
4. dvc remote add -d storage gdrive://<file-id>
5. dvc push

Browser opened up and asked for authentication and I selected the account and authentication was successful and files were pushed to gdrive as expected.</br></br>
But now I wanted to change the google drive account hence I followed the following procedure:</br>
1. dvc destroy
2. dvc init
3. dvc add <files-location/file-name>
4. dvc remote add -d storage gdrive://<new-file-id-account2>
5. dvc push

The issue is now the program is failing to push the files

### Expected
 Expecting a re- authentication for new gdrive account</br>
But got the following issue:</br>

`$ dvc push`
_ERROR: unexpected error - : <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/1YvqGNV6FyS-WvqVM017NCim_2MesgxVG?fields=driveId&supportsAllDrives=true&alt=json returned "File not found: 1YvqGNV6FyS-WvqVM017NCim_2MesgxVG". Details: "[{'message': 'File not found: 1YvqGNV6FyS-WvqVM017NCim_2MesgxVG', 'domain': 'global', 'reason': 'notFound', 'location': 'file', 'locationType': 'other'}]">_

### Environment information
**Output of `dvc doctor`:**

```console
$ dvc doctor
```
DVC version: 2.38.1 (pip)
---------------------------------
Platform: Python 3.10.8 on Windows-10-10.0.19044-SP0
Subprojects:
        dvc_data = 0.28.4
        dvc_objects = 0.14.0
        dvc_render = 0.0.15
        dvc_task = 0.1.8
        dvclive = 1.2.2
        scmrepo = 0.1.4
Supports:
        gdrive (pydrive2 = 1.15.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: hardlink
Cache directory: NTFS on D:\
Caches: local
Remotes: gdrive
Workspace directory: NTFS on D:\
Repo: dvc, git

**Comment by efiop** [comment]
Hi @sagar-harry

Please take a look at https://dvc.org/doc/user-guide/how-to/setup-google-drive-remote

> if multiple GDrive remotes use the same client ID, by default they will share the same cached credentials. To isolate them, you can use custom profile names for different remotes:
> 
> dvc remote modify --local myremote profile myprofile

using profiles should solve your issue.

**Comment by sagar-harry** [comment]
Thanks a lot @efiop it worked. </br>
Used the below command from the documentation shared.
`dvc remote modify --local myremote profile myprofile`

My bad I missed that section of documentation, thanks for the support.

**Comment by sagar-harry** [comment]
Hii @efiop when I ran the same command now again, it's raising the following issue: </br>
`dvc remote modify --local storage1 profile myprofile`
ERROR: configuration error - config file error: extra keys not allowed @ data['remote']['storage1']['profile']

In the above command storage1 is my gdrive remote.

**Comment by efiop** [comment]
@sagar-harry Please show `dvc config --list`. Looks like you have a corrupted remote config.

**Comment by sagar-harry** [comment]
@efiop I have re-intialized git and dvc the program worked fine, but can you please tell me the reasons for corrupted remote config.

**Comment by efiop** [comment]
@sagar-harry My guess is maybe you had a wrong url (not gdrive:// one). But that's why I was asking for `dvc config --list` 🙂 Good to hear it works now.
