### ISSUE TITLE
`dvc queue status` shows tasks as running even after system restart. 

### ISSUE THREAD

**Issue by karanjakhar** [iterative/dvc#8702]
# Bug Report

`dvc queue status` shows tasks as running instead of failed.     
And tasks are not removed and their status also didn't change even after running `dvc queue stop --kill` multiple times.

I started jobs and then restarted the system. 

`dvc queue stop --kill --verbose`  show:     

![Screenshot from 2022-12-16 01-32-52](https://user-images.githubusercontent.com/29913676/207955990-71a7c198-744b-4e99-9d69-bce851ac8771.png)

Even after running it multiple times. 

### Reproduce

Queue and start jobs and then restart the system. Then do `dvc queue status` 
All tasks should show status as "failed" however, some show "running" but they are not running. This didn't update even after running `dvc queue stop --kill`

![Screenshot from 2022-12-16 01-29-53](https://user-images.githubusercontent.com/29913676/207955515-4bcd5bdd-24cb-42aa-b44b-359c30fc849e.png)

**Comment by karanjakhar** [comment]
Hi, @karajan1001 'dvc queue kill` is working. Is there an option to kill them all?

**Comment by karanjakhar** [comment]
Hi, @karajan1001 thank you for looking into it. Have you reproduced the bug?

**Comment by karajan1001** [comment]
Yeah, the problem is quite simple, I had already created a PR for it.

**Comment by karanjakhar** [comment]
Great :)
