### ISSUE TITLE
Using dvc with zoho workdrive remote

### ISSUE THREAD

**Issue by umang299** [iterative/dvc#8707]
# Unable to push data to zoho workdrive, despite setting up the dvc remote 

I want to push data to a zoho workdrive because i have more storage space there. I have created a git repository and initialized dvc in it. I have setup the dvc remote to the workdrive folder. After I add the data using ``dvc add data``, when i try to push the data using ``dvc push`` it throws the below error

ERROR: failed to transfer 'md5: b196b41c0741faa0bf933264d3958122' - 500, message='', url=URL('https://workdrive.zohoexternal.com/external/3b62633d1761b0fc3aa65154b718b8e8f5e39fa1a0a5c549c1809f8be6ed8f15/b1/96b41c0741f')

**Comment by rlamy** [comment]
How did you setup the remote? dvc currently has no explicit support for Zoho, so I'm not sure it's actually possible to use it as a remote ATM.

**Comment by umang299** [comment]
I have created a folder in my zohoworkdrive. Used the https link of that
folder to setup the remote. However, was unable to push data into the
drive.

**Comment by skshetry** [comment]
Looking into https://workdrive.zoho.com/apidocs/v1/filesfolders/uploadlargefile, it seems zoho requires specific ways to upload/download files, which our simple http filesystem won't work with. Bascially, dvc http remote tries to upload into `<root>/<path>` where `path` is an md5 hash, and it sends the file in the request body. Meanwhile, Zoho requires to always upload to the same url, but send the content in request body with other metadata like filename being in headers.

This will require to have a separate fsspec implementation for zoho-workdrive, and won't work with plain http remote. Closing ...
