### ISSUE TITLE
[dvc forget] Is there a command to wipe out all local checkouts of data, leaving only stubs?

### ISSUE THREAD

**Issue by chrisdonlan** [iterative/dvc#8717]
Use case: I have PII data that cannot stay in my local development context after I am done using it.  

DVC will be a fantastic tool to checkout data as needed, per file, then wipe out that data (incl. local cache) when I am done. Is this something that can be done now? 

Otherwise, I imagine I'll need to write a script to walk the directory and delete everything that DVC is managing, *then* delete the local cache so that it is as if I'd never run `dvc pull` or `dvc checkout`, and had simply run `git clone`. 

E.g., this would be a (conventional) `dvc clean` or (ergonomic), `dvc forget`.   Is this already possible, coming or can it be added to DVC?

Or, I can add this? I have implemented `dvc forget` separately.

**Comment by dberenbaum** [comment]
Hi @chrisdonlan! I'm glad you got `dvc forget` working. 

We don't have any plan to introduce a feature like this at the moment as it has not been a general enough use case to come up that often, but if it turns out this is a more common request, we would be happy to revisit.
