### ISSUE TITLE
Missing value in parallel coordinates plot

### ISSUE THREAD

**Issue by SamuelAnsel** [iterative/dvc#8730]
## Description

Here is my experiment table, in which I have a column 'model_name' with different string values :

![image](https://user-images.githubusercontent.com/86078997/209308192-d90383df-64e5-4e4a-b967-ad67558d2ead.png)

And here is the plot I get with the command `dvc exp show --pcp --all-branches --sort-by precision` :

![image](https://user-images.githubusercontent.com/86078997/209308571-2a818e3a-e796-4b42-b37c-bc73cd7ac8fd.png)

Notice that the model name 'SimpleCNN' does not display and the experiment highlighted in yellow in the table (exp-db57c) goes to the wrong model_name in the plot.

**Comment by dberenbaum** [comment]
cc @daavoo
