### ISSUE TITLE
queue remove --all does not remove all queued jobs

### ISSUE THREAD

**Issue by Mohamed-E-Fayed** [iterative/dvc#8734]
# Bug Report

## Description

When I run $dvc queue remove --all, I find some experiments are still queued.

### Reproduce

$ dvc queue status 
Task     Name    Created    Status
55a2e22          09:22 AM   Failed
969cd2a          09:23 AM   Failed
3ff1092          09:26 AM   Failed
b6a8f20          09:26 AM   Failed
e7a3a30          09:58 AM   Failed
e2f83c0          09:59 AM   Failed

Worker status: 0 active, 1 idle
$ dvc queue remove --all 
Removed tasks in queue: 55a2e22, 969cd2a, 3ff1092, b6a8f20, e7a3a30, e2f83c0
$ dvc queue status 
Task     Name    Created    Status
e7a3a30          09:58 AM   Failed
e2f83c0          09:59 AM   Failed

Worker status: 0 active, 1 idle

### Expected

$dvc queue status 
No experiment tasks in the queue.

Worker status: 0 active, 1 idle

### Environment information

linux: Red Hat Enterprise 
Version: 7.9

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.30.0 (pip)
---------------------------------
Platform: Python 3.10.4 on Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 0.17.1
        dvc_objects = 0.7.0
        dvc_render = 0.0.12
        dvc_task = 0.1.3
        dvclive = 0.12.0
        scmrepo = 0.1.1
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: symlink
Cache directory: beegfs on beegfs_nodev
Caches: local
Remotes: local
Workspace directory: beegfs on beegfs_nodev
Repo: dvc, git


**Additional Information (if any):**

<!--
Please check https://github.com/iterative/dvc/wiki/Debugging-DVC on ways to gather more information regarding the issue.

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.
If the issue is regarding the performance, please attach the profiling information and the benchmark comparisons.
-->

**Comment by dberenbaum** [comment]
cc @karajan1001

**Comment by karajan1001** [comment]
On my computer in the latest version `2.38.2`, I tried `dvc queue remove --all` can remove all failed tasks.  

```
$ dvc queue status                                                                                                                                      [ins][18:48:23]
Task     Name        Created    Status
edae2c6  burry-send  06:47 PM   Failed
18f3132  quack-darg  06:30 PM   Success

Worker status: 0 active, 1 idle
$ dvc queue remove --all                                                                                                                                [ins][18:48:30]
Removed tasks in queue: burry-send, quack-darg
$ dvc queue status                                                                                                                                      [ins][18:48:50]
No experiment tasks in the queue.

Worker status: 0 active, 0 idle
```



```
$ dvc queue remove --all
Removed tasks in queue: 55a2e22, 969cd2a, 3ff1092, b6a8f20, e7a3a30, e2f83c0
$ dvc queue status
Task Name Created Status
e7a3a30 09:58 AM Failed
e2f83c0 09:59 AM Failed
```

I noticed that in your logs `e7a3a30, e2f83c0` had already been found, and marked as removed in logs. Could you please provide more detailed logs here with `dvc queue remove e7a3a30, e2f83c0 -vv`.
