### ISSUE TITLE
Git system settings not picked up for credential helper

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8739]
# Bug Report

## Description

When using `dvc ls/get/import` or other operations that do a `git clone`, system-level credential helpers are not working even though they work for cli git.

### Reproduce

Start with a private repo for which you have cached credentials. Then you can use this repro script:

```
REPO=https://github.com/<slug>/<private_repo>
DIR=$(mktemp -d)
cd $DIR
dvc init --no-scm -q
git config --system credential.helper cache
dvc ls -v $REPO
git config --system --unset credential.helper
```

The repo fails to clone. The same script works when using `--global` instead of `--system`.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.38.2.dev14+gea8a4a3db
---------------------------------
Platform: Python 3.10.2 on macOS-13.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.28.4
        dvc_objects = 0.14.0
        dvc_render = 0.0.17
        dvc_task = 0.1.8
        dvclive = 1.2.2
        scmrepo = 0.1.4
Supports:
        azure (adlfs = 2022.9.1, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.15.0),
        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0, pyarrow = 7.0.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.4),
        webdavs (webdav4 = 0.9.4),
        webhdfs (fsspec = 2022.11.0)
```

**Comment by dtrifiro** [comment]
These two commands require sudo privileges on MacOS (and linux):
```bash
git config --system credential.helper cache
...
git config --system --unset credential.helper
```
Thus I'm assuming you're running git provided by brew.

Running those commands with brew-provided git results in editing `$(brew --prefix)/etc/gitconfig`, which is not a path which dulwich (and scmrepo) uses when reading configs (unless explicitly providing it)

default config backends for dulwich: https://github.com/jelmer/dulwich/blob/a3da1da12bfdb0f7c7ca96fb8b7969c5b9af8b70/dulwich/config.py#L697-L718

**Comment by dberenbaum** [comment]
🤦 I didn't realize brew git was so bespoke. Thanks for taking a look. So the solution is to uninstall the brew version of Git.

**Comment by dtrifiro** [comment]
>  So the solution is to uninstall the brew version of Git.

Well, I just would avoid using the `--system` config, `--global` (`~/.gitconfig`) is usually enough
