### ISSUE TITLE
queue: conflicting experiment name silently overrides existing experiment

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8742]
# Bug Report

## Description

The name check for conflicting experiments isn't working with the queue.

### Reproduce

```
$ dvc stage add -n test echo test
$ dvc exp save -n exp1
$ dvc exp run -n exp1 --queue
$ dvc exp list
main:
        exp1
```

### Expected

`dvc exp run -n exp1 --queue` should raise ExperimentExistsError.

**Comment by dberenbaum** [comment]
Looks like it's due to this line:

https://github.com/iterative/dvc/blob/ea8a4a3db423eca1b169b304f6a47ab1d74da641/dvc/repo/experiments/__init__.py#L262

Naming conflicts are ignored when `reset=True`, which is always the case for queues experiments. This was needed before when experiment names were deterministic, but now that experiment names are random, we should disallow conflicting names even when `reset=True`.

**Comment by dberenbaum** [comment]
There's also no checks to stop someone from doing:

```
$ dvc exp run -n exp1 --queue
$ dvc exp run -n exp1 --queue
```

**Comment by daavoo** [comment]
> This was needed before when experiment names were deterministic, but now that experiment names are random, we should disallow conflicting names even when reset=True.

> There's also no checks to stop someone from doing:

I am not sure I follow why the change to name generation is relevant.
The problem here is when names are provided manually and the logic hasn't changed for that case.

In `dvc<=2.38.0` (where the new logic for random names was introduced):

```
$ dvc doctor
DVC version: 2.37.0 (pip)
---------------------------------
Platform: Python 3.8.12 on macOS-10.16-x86_64-i386-64bit
Subprojects:
	dvc_data = 0.28.4
	dvc_objects = 0.14.0
	dvc_render = 0.0.15
	dvc_task = 0.1.6
	dvclive = 1.2.3.dev0+g42eff97.d20221215
	scmrepo = 0.1.4
Supports:
	http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
$ dvc exp run -n exp1
...
Ran experiment(s): exp1
...
$ dvc exp run -n exp1 --queue
Queued experiment 'exp1' for future execution.                                                                                     
```

```
$ dvc exp run -n exp2 --queue
Queued experiment 'exp2' for future execution.                                                                                     
$ dvc exp run -n exp1 --queue
Queued experiment 'exp2' for future execution.                                                                                     
```

**Comment by daavoo** [comment]
So I assume we want to change the existing behavior?

**Comment by dberenbaum** [comment]
> I am not sure I follow how the change to name generation is relevant.
> The problem here is when names are provided manually and the logic hasn't changed for that case.

Right, this is not new behavior, I just noticed it now. I'll drop the priority since it hasn't caused issues up to this point.

Only the reset behavior is related to the random names. Previously, if you reset an experiment, by default it would get the same name as the previous experiment, so dvc would always overwrite the previous experiment. Reset would never work if dvc checked for conflicts. Now, you will end up keeping the old experiment and generating a new one with a different random name, so we can start checking for conflicts even when using reset.

**Comment by dberenbaum** [comment]
> There's also no checks to stop someone from doing:
> 
> ```
> $ dvc exp run -n exp1 --queue
> $ dvc exp run -n exp1 --queue
> ```

After #8743, this should be the only issue remaining.
