### ISSUE TITLE
caching per-revision `exp show` output

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#8748]
This equally applies to `metrics`/`params` and `plots`. We can cache the computed results from every revisions which might be faster than trying to cache the whole index.

At first, we could try caching results without any error but in the long run, we should be able to distinguish between retryable errors (eg: `FileNotFoundError` in cache and remotes) vs unretryable errors (eg: `dvc.yaml` being broken and since it's tied to an _immutable_ commit, it's never going to be fixed).

**Comment by skshetry** [comment]
I think we can close this as this was implemented in #9069.

**Comment by dberenbaum** [comment]
Should we open other issues for these items?

> This equally applies to `metrics`/`params` and `plots`.

> At first, we could try caching results without any error but in the long run, we should be able to distinguish between retryable errors (eg: `FileNotFoundError` in cache and remotes) vs unretryable errors (eg: `dvc.yaml` being broken and since it's tied to an _immutable_ commit, it's never going to be fixed).
