### ISSUE TITLE
dvc add is stuck on Adding ... for ~20 hours

### ISSUE THREAD

**Issue by mehadi92** [iterative/dvc#8753]
I'm trying to version control my 210 G data which contains 2.41M files. When I run
```sh
dvc -v add data_clean/                                                        
Adding...
```
It stuck here for 20 hours. Is it supposed to happen?

My DVC repository is present in the GCE instance. 

Thanks

**Comment by pmrowla** [comment]
discord context: https://discord.com/channels/485586884165107732/485596304961962003/1059331772468432896

**Comment by pmrowla** [comment]
See discord thread for more context, but it seems like this may be something specific to google compute engine environments and will probably require deeper investigation on our end whenever we have the availability to do so

**Comment by mehadi92** [comment]
@pmrowla output log on `dvc add -v --cprofile-dump gce-long-add.prof <smaller-dataset-dir>` 
![Screenshot from 2023-01-05 10-56-03](https://user-images.githubusercontent.com/104126711/210705847-50607b26-b154-4a78-b3ec-47f46db062f9.png)

I think `.prof` don't support by github. So I'm sending it you by `discord`. Please check `discord`

**Comment by pmrowla** [comment]
[gce-long-add.prof.zip](https://github.com/iterative/dvc/files/10349487/gce-long-add.prof.zip)
