### ISSUE TITLE
Bypass pull push on large files (gb) thats already on aws 

### ISSUE THREAD

**Issue by gilgilad** [iterative/dvc#8756]
### Report

Perhaps i missed something, but assume that you have a large dataset that is already on s3 bucket. is there no way to start tracking it without the get,add,push, pull sequence? 
Downloading a 100+GB  to a local machine just to reupload it again for tracking is the accurate way to track it ?

**Comment by dtrifiro** [comment]
Hi, you might want to read the documentation for [`import-url`](https://dvc.org/doc/command-reference/import-url) (especially `--no-download`) as well as the [managing external data](https://dvc.org/doc/user-guide/data-management/managing-external-data) page.

Feel free to reach on [discord](https://dvc.org/chat) if you have any other questions.

**Comment by dberenbaum** [comment]
Hi @gilgilad! How do you want the data to be tracked and how do you plan to use it? Do you expect to save a copy somewhere to be able to recover old versions of the data? What do you want to do with the data in DVC?
