### ISSUE TITLE
external outputs: broken if pipeline output doesn't exist during stage initialization

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8757]
# Bug Report

## Description

S3 external outputs are broken for pipelines since https://github.com/iterative/dvc/commit/7211bd02eda74d5434f1b7996647f7027e6e83b0 because of a bug in s3fs (and probably in other filesystems). They will only break if running a stage for which an output doesn't already exist. When initializing the stage, DVC will try to remove the nonexistent output and raise a `FileNotFound` error.

### Reproduce

`dvc repro` will break if there is an external output and that output does not exist yet.

In a new repo, using some `<s3_path>` that doesn't exist yet, do this:

```
$ echo 'foo' > foo
$ dvc stage add --external -n foo -d foo -O <s3_path> 'aws s3 cp params.yaml <s3_path>'
$ dvc repro -v
```

### Expected

`dvc repro` shouldn't fail while removing outputs. In this case, it fails because of what seems like a bug or at least inconsistent behavior in fsspec. Like mentioned in https://github.com/iterative/dvc/issues/5961#issuecomment-1365822275, [`output.remove`](https://github.com/iterative/dvc/blob/main/dvc/output.py#L901) for s3fs and other async filesystems calls [_expand_path](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/asyn.py#L719). When the path doesn't exist and `recursive=True`, `_expand_path` raises `FileNotFoundError`. When `recursive=False`, it returns the path. It also returns the path for the `LocalFileSystem` regardless of whether `recursive=True`, so not sure if it was intended to raise an error only for this specific scenario.

**Comment by rmlopes** [comment]
Same happens with Azure

**Comment by dberenbaum** [comment]
Not sure if this should be a new issue, but I'm seeing the same problem now because we have `recursive=True` in https://github.com/iterative/dvc/blob/8f768addf956b56820b325bd717613bef7f0c141/dvc/output.py#L968.

**Comment by dberenbaum** [comment]
@daavoo Do you recall from https://github.com/iterative/dvc/pull/8825 if we need `recursive=True`?

**Comment by daavoo** [comment]
> @daavoo Do you recall from #8825 if we need `recursive=True`?

I didn't test its removal but it was supposed to be a legacy option no longer needed https://github.com/iterative/dvc-objects/pull/176#discussion_r1068110883

**Comment by daavoo** [comment]
So @dberenbaum to see if I got it right, is this because fsspec raises FileNotFound error?
I don't know if this is a bug in fsspec or expected behavior

**Comment by dberenbaum** [comment]
Correct. It also wasn't clear to me whether it's intended.
