### ISSUE TITLE
api: add `dvc.api.exp_show`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8775]
`dvc.api.exp_show` should return tabular data similar to `dvc exp show` (we could use `dvc exp show --csv` as an example for what the output should look like). It should be possible to get a dataframe from this output with `pd.DataFrame(dvc.api.exp_show())`.

**Comment by dberenbaum** [comment]
The args for this method should include the revision selectors args in `dvc exp show`. Other args from `dvc exp show` (format types, filtering, sorting, etc.) aren't needed.

**Comment by daavoo** [comment]
I think it's probably worth waiting for https://github.com/iterative/dvc/pull/9170 , but I estimate the implementation as 1 day or less of work
