### ISSUE TITLE
repro: external dependencies in Azure not tracked correctly

### ISSUE THREAD

**Issue by rmlopes** [iterative/dvc#8783]
# Bug Report

## Description

I have an external dependency set to an Azure container folder. Even though there are no changes to the folder the repro command always executes the stage.

### Reproduce

1. Create a stage with an external dependency to a storage container folder
```
remote_dep:
    cmd: myscript    
    deps:
    - remote://mycontainer/myfolder
```
2. Run dvc repro (the script should do something)
3. Run dvc repro again (it should skip the stage)

### Expected

The stage should be skipped if there are no modifications to the folder (files added or removed).

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.38.1 (pip)
---------------------------------
Platform: Python 3.9.6 on macOS-13.1-x86_64-i386-64bit
Subprojects:
	dvc_data = 0.28.4
	dvc_objects = 0.14.0
	dvc_render = 0.0.15
	dvc_task = 0.1.8
	dvclive = 1.3.1
	scmrepo = 0.1.4
Supports:
	azure (adlfs = 2022.11.2, knack = 0.10.1, azure-identity = 1.12.0),
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: azure, azure
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Comment by karajan1001** [comment]
Hi, @rmlopes 

First, we do not have official support for external azure data, like what #8759 said. 
Second, if you need a temporary solution, you can use `dvc freeze` to manually freeze this stage in `dvc repro`

**Comment by daavoo** [comment]
> First, we do not have official support for external azure data, like what https://github.com/iterative/dvc/issues/8759 said.

@karajan1001 I think this one is about external dependencies (where we do document `azure` as supported) while #8579 is about external outputs

**Comment by rmlopes** [comment]
Hi @karajan1001 

I opened this new issue because I got the idea they were separate issues because in the documentation it looks like it. In [importing external data](https://dvc.org/doc/user-guide/data-management/importing-external-data) it looks like these functionalities are supported. However, in [managing external data](https://dvc.org/doc/user-guide/data-management/managing-external-data) it does not state anywhere that Azure is supported.

I just tested now that using `import-url` does not work with Azure as well (it imports, but the changes are not detected). I found a PR discussing this that seemed like dependencies could work because they rely on etags, if I can find it again I will post it here.

**Comment by daavoo** [comment]
I can reproduce it. Taking a look

**Comment by daavoo** [comment]
For the record: This only happens when the external dependency targets a directory. For individual files works as expected

**Comment by daavoo** [comment]
This actually affects any filesystem that defines a `PARAM_CHECKSUM` different from `md5`, meaning that from the full list in https://dvc.org/doc/user-guide/data-management/importing-external-data#how-external-dependencies-work , only SSH and Local actually work.
