### ISSUE TITLE
queue kill: add a message when it's successfully run

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc#8797]
If you successfully run the `dvc queue kill` command, you don't get any response. You don't see any message in the terminal and the DVC VSCode extension returns a generic message:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/43496356/211827510-93365426-44aa-48dc-8b45-531a8947a644.png">

![image](https://user-images.githubusercontent.com/43496356/211827561-c6ed46e7-9153-411a-ac3c-8ca4c0407684.png)

Could we make it more clear that the command was successful by returning a message? `Killed experiment EXP_NAME` for example?

**Comment by skshetry** [comment]
Classic unix behaviour. 😄

**Comment by skshetry** [comment]
I think it is upto VSCode extension for the output, the success code is enough.

**Comment by dberenbaum** [comment]
We put out simple outputs like this (and sometimes way more) on success for other commands. No reason not to do it here. The clig.dev guideline states:

> **Display output on success, but keep it brief.** Traditionally, when nothing is wrong, UNIX commands display no output to the user. This makes sense when they’re being used in scripts, but can make commands appear to be hanging or broken when used by humans. For example, cp will not print anything, even if it takes a long time.
>
> It’s rare that printing nothing at all is the best default behavior, but it’s usually best to err on the side of less.
>
> For instances where you do want no output (for example, when used in shell scripts), to avoid clumsy redirection of stderr to /dev/null, you can provide a -q option to suppress all non-essential output.

I think we had bigger problems when this was first implemented and didn't polish the UI very much. I see no reason not to show the experiments that were successfully killed in the output. cc @karajan1001
