### ISSUE TITLE
Unexpected error: 'utf8' codec can't decode byte 0xc3 in position 1048575: unexpected end of data

### ISSUE THREAD

**Issue by NicolasDutronc** [iterative/dvc#882]
Hello ! As we are starting a data science project, we decided to give `dvc` a try since it has a lot of great features.

__Problem__:

I am trying to add a csv file to the project with the `dvc add` command and it rejects it with the following error:

```Unexpected error: 'utf8' codec can't decode byte 0xc3 in position 1048575: unexpected end of data```

I first found out that the file was encoded in iso-8859-1 so I reencoded it in utf-8 by doing ```iconv -f ISO-8859-1 -t UTF-8 file.csv > utf8_file.csv```.  

Now the file is encoded in utf-8: ```file -I data/sirene.csv``` gives ```data/sirene.csv: text/plain; charset=utf-8```

I do not understand the error since the file is encoded in utf-8.

__Environment__:

I am working on Mac OS and installed `dvc` via `Homebrew`.
The file can be found [here](https://www.data.gouv.fr/fr/datasets/r/e0e2aa5f-e3f6-45ec-b350-86e69121a30b) for reproduction.

**Comment by efiop** [comment]
Hi @NicolasDutronc !

The bug you are experiencing is from 0.9.7 and is already fixed(I can confirm that it doesn't occur on dvc 0.11.0). Looks like I've forgotten to update our brew formulas to use the most recent dvc version. They are updated now, so sorry for inconvenience :( . Could you please upgrade and give it another try?

Thanks,
Ruslan

**Comment by NicolasDutronc** [comment]
Hi @efiop ,
Thank you very much for your quick answer and reaction. It seems to work perfectly now ! :)
Just out of curiosity, does dvc now support several encoding ?

**Comment by efiop** [comment]
Hi @NicolasDutronc !

Glad it worked for you! :) Thank you so much for the feedback!

> Just out of curiosity, does dvc now support several encoding ?

DVC is actually encoding-agnostic when it comes to data. This error was caused by a bug in our code, where we were trying to open data in a text-mode causing such exception to raise when the data file wasn't encoded in UTF-8.

Thanks,
Ruslan

**Comment by NicolasDutronc** [comment]
Thanks for the answer ! :)

I'm closing the issue now.
