### ISSUE TITLE
cloud versioning: enforce that remote supports cloud versioning on push

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#8824]
Looks like if the remote does not support cloud versioning, the `push` does not check if the metadata contains `version_id` or not. Or tell the user if the remote supports it or not.

I tried on a local unversioned bucket with `minio` and got the following metadata:
```console
$ dvc push -r minio
1 file pushed
$ cat foo.dvc
outs:
- md5: d3b07384d113edec49eaa6238ad5ff00
  size: 4
  path: foo
  etag: d3b07384d113edec49eaa6238ad5ff00
```

**Comment by daavoo** [comment]
cc @dtrifiro ^ We discussed this in a call today.

**Comment by skshetry** [comment]
It does not seem possible to know whether the bucket supports cloud versioning or not. We could try getting some info about files, but they may not have any versions if the versioning was turned on later. Versioning can be suspended too, so any new objects may not have any versions, but old objects will still have versions.
 
Also, since we do batched uploads, I think we should just raise a warning message on `push`.

**Comment by pmrowla** [comment]
This is already implemented in s3fs at least (as an internal s3fs-only call, not part of the fsspec spec) https://github.com/fsspec/s3fs/blob/9b6f8c0eed2fb83217ac74c469250a0cf3d45f3c/s3fs/core.py#L1870

It should be possible to do for gcs and azure as well:
https://cloud.google.com/storage/docs/using-object-versioning#check

**Comment by skshetry** [comment]
We decided to try to upload an object and then check the metadata returned, if it contains versionId or not.

**Comment by skshetry** [comment]
Object versioning status, on Google Cloud requires `storage.buckets.get` permissions, and is not available by default:

> If the bucket you want to access exists in a project that you did not create, you might need the project owner to give you a role that contains the necessary permissions.
