### ISSUE TITLE
cloud versioning: Support `add --to-remote`.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#8826]

**Comment by daavoo** [comment]
> dvc push changes the .dvc file so user should be recommended to git commit after the dvc push

My idea here would be to implement https://github.com/iterative/dvc/issues/8826 and enforce/suggest `add --to-remote` as the main workflow for cloud versioning, so the common steps remain `dvc add -> git commit/push -> dvc push`

_Originally posted by @daavoo in https://github.com/iterative/iterative.ai/issues/690#issuecomment-1384469700_

**Comment by dberenbaum** [comment]
I think it would require changes to the behavior of `add --to-remote` since it currently doesn't cache the data locally. If I understand, the goal here would be to do a regular local `add` followed by an automatic `push`, right?

**Comment by daavoo** [comment]
> I think it would require changes to the behavior of add --to-remote since it currently doesn't cache the data locally.

True. It doesn't cache data locally and it's also not meant to receive a local path as a target, right?

> the goal here would be to do a regular local add followed by an automatic push, right?

Yes. The main point was to try to don't break the common workflow where people usually track the changes to the medatada files with Git before doing `dvc push`.

**Comment by dberenbaum** [comment]
WDYT about making `dvc install` do a `dvc push` as part of the pre-commit hook? Probably wouldn't want to make this happen by default, but maybe we could add an option for cloud versioning that does it?
