### ISSUE TITLE
cloud versioning: add tests

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8850]
Need to add testing for cloud versioning (this could be a meta-ticket for tests in other packages for each cloud filesystem).

Thanks to @dtrifiro for pointing out that we can use versioned mock remotes for S3 and GCS starting from https://github.com/iterative/pytest-servers/releases/tag/0.2.0.

**Comment by daavoo** [comment]
I might call this `p0` 😄

**Comment by dberenbaum** [comment]
I thought maybe I was being a little overly aggressive putting p0 on cloud versioning issues since it's still in development, but agreed that it needs to be one of the essential stories of the epic for release.

**Comment by daavoo** [comment]
> I thought maybe I was being a little overly aggressive putting p0 on cloud versioning issues since it's still in development, but agreed that it needs to be one of the essential stories of the epic for release.

It was just a joke to remark importance 😅

**Comment by skshetry** [comment]
I have to add tests for output-specific remotes after we have the tests infrastructure. See https://github.com/iterative/dvc/pull/8862.
