### ISSUE TITLE
exp run: support [-m | --message] parameter

### ISSUE THREAD

**Issue by mvshmakov** [iterative/dvc#8870]
Would be nice if the user is able to assign a description for a live experiment. I.e.:

```sh
dvc exp run -S epochs=12 -m "Increase epochs count due to under-fitting"
```

<details><summary>This will help us to display this information in the `Message` field in the Studio, potentially in VSCode as well. Now we display nothing there.</summary>

![image](https://user-images.githubusercontent.com/28868855/214280013-ddca8479-298f-497b-bb65-9f6de3a9b201.png)

</details>

This should probably be a part of the [dvc-studio-client](https://github.com/iterative/dvc-studio-client) contract.

CC @daavoo

**Comment by daavoo** [comment]
Outside of `live experiments`, I think it could be also used to optionally replace the hardcoded message we currently have in the generated commit:

https://github.com/iterative/dvc/blob/6a6bc7035ab7c2525c024d536b5e4686b2fb40bf/dvc/repo/experiments/executor/base.py#L688-L690
