### ISSUE TITLE
DVC Add --external Deletes all files, Can't find in Cache

### ISSUE THREAD

**Issue by kevinj22** [iterative/dvc#8874]
Hello,

I ran dvc add --external /path/to/files

It stopped after adding most of the files claiming the files were not in cache. It deleted the files from my computer.

I do not see them in the cache directory, how can I recover my files?

**Comment by dtrifiro** [comment]
Hi, can you provide the output of `dvc doctor` and/or the exact error you got when running `dvc add`? Is the path `/path/to/files` a local path or is it a mounted remote filesystem?
