### ISSUE TITLE
Command `dvc exp show` returned in ERROR: unexpected error - unsupported format string passed to list.__format__

### ISSUE THREAD

**Issue by AIladin** [iterative/dvc#8891]
https://github.com/iterative/dvc/blob/38e9b2ba95fa4b50868f971c2616a84e6877eb38/dvc/compare.py#L332-L333

**Comment by AIladin** [comment]
Command `dvc exp show` returned in 
```ERROR: unexpected error - unsupported format string passed to list.__format__```

There is a typo leading to this error in function lines, 332-333 
- Solution: `_val` should be instead of `val`
https://github.com/iterative/dvc/blob/38e9b2ba95fa4b50868f971c2616a84e6877eb38/dvc/compare.py#L326-L340

**Comment by daavoo** [comment]
Looks like it was introduced in https://github.com/iterative/dvc/pull/8815

**Comment by AIladin** [comment]
Created a pull request to fix https://github.com/iterative/dvc/pull/8892
