### ISSUE TITLE
Pipeline show stage status

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#894]
Hi, the `dvc pipeline show` command could show simplified status information about each file. It would be very useful to find out which dependencies will be reproduced first when reproducing the target.

**Comment by efiop** [comment]
Ah, do you mean something like:

```
$ dvc pipeline show process.dvc
raw
data
output
```

in a simple pipeline of raw -> (cleanup) -> data -> (process) -> output ?

**Comment by prihoda** [comment]
The question I would like answered is:
*Which stages will be reproduced when I run `dvc repro process.dvc`?*

So actually I don't care about the exact status, I just want to get the `dvc pipeline show` list of stages, but only with those stages that will be reproduced. 

For example, with this pipeline:
```
   raw -> (cleanup) -> data \ 
                              => (predict) -> output
samples -> (train) -> model /
```
When the `samples` file is changed, the regular `dvc pipeline show predict.dvc` will output:
```
cleanup.dvc
train.dvc
predict.dvc
```
And I want to see only the stages that will be reproduced, which is:
```
train.dvc
predict.dvc
```

Some of the stages actually might not be reproduced if the first dependencies turn out to produce the same output as before, but there's no way to go around that.

Thinking about the implementation, this algorithm could work:
- get a list of all changed stages (those with non-empty status)
- for each changed stage, find its `networkx.ancestors` (stages that depend on it, directly or indirectly), combine into one set of stages to be reproduced.
- remove those stages from `dvc pipeline show` not found in this set

**Comment by efiop** [comment]
Ah, I see. `dvc pipeline show` is not actually for the status updates, but rather for being able to overlook the whole project. What you are suggesting is very useful and I think it should be a part of `dvc status`. For example in a form of `dvc status -s|--stages` or something like that. Naming suggestions are very welcomed :)

**Comment by prihoda** [comment]
Ok I see, well since it will probably often be used with the `dvc repro` command, it could be run as `dvc repro -p|--preview`: Do not run the reproduction, just show the reproduction steps.

**Comment by prihoda** [comment]
Or `dvc repro -p|--prompt`: Show the reproduction steps and run the reproduction with Enter key or (y/n). I would personally love to have this as default, set in the `.dvc/config` file. Very useful for beginners :)

**Comment by efiop** [comment]
Hm, this is actually not the first time we hear a similar request about the `dvc repro -p` :) How about we add both `dvc repro -p|--preview` and `dvc repro -i|--interactive`(instead of --prompt). `dvc repro -i` will walk through the stages, tell what dependencies/output had changed and ask for (y/n) confirmation to execute? What do you think?

**Comment by prihoda** [comment]
Sounds great!

**Comment by efiop** [comment]
Hi @prihoda !

FYI: I've added `--dry` and `-i|--iterative`(please ignore the commit msg that says `--prompt` in the header :slightly_smiling_face: ) options for `dvc repro`. Feel free to try it out :slightly_smiling_face:

Thanks,
Ruslan

**Comment by prihoda** [comment]
Works great! 👏 

I'd also suggest not to include the locked files since they won't actually be reproduced:

```
dvc repro --dry target.dvc
# DVC file 'myfile.dvc' is locked. Its dependencies are not going to be reproduced.
# Reproducing 'myfile.dvc'
# Verifying outputs in locked stage 'myfile.dvc'
# ...

dvc repro --interactive target.dvc
# DVC file 'myfile.dvc' is locked. Its dependecies are not going to be reproduced.
# Going to reproduce 'myfile.dvc'. Are you sure you want to continue?
y
# Reproducing 'myfile.dvc'
# --- note: file is locked so it's not reproduced! --- 
# Verifying outputs in locked stage 'myfile.dvc'
# Saving information to 'myfile.dvc'.
```

**Comment by prihoda** [comment]
Also, I'd really appreciate having the option to set `--iterative` as default behaviour in DVC config 🙏
