### ISSUE TITLE
Reorder metadata in dvc files

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8941]
Summary: reorder metadata in `.dvc` to show `relpath` first.

From https://github.com/iterative/dvc/pull/8862#issuecomment-1410872838:

> Yes, just wondering about the specific order of each field. Right now, I see it like this:
> 
> ```
>       - size: 89
>         md5: 5d9cac1ada35234756d0119b3223f933
>         relpath: 1.txt
>         cloud:
>           versioned:
>             etag: 5d9cac1ada35234756d0119b3223f933
>             version_id: BKOwHqopJRA2i8JmP8xa.30p7TnPWFqq
> ```
> 
> Is this order enforced consistently? I'm wondering for ease of merging, and also because `relpath` seems best at the top it we expect users to view/modify this file.

From https://github.com/iterative/dvc/pull/8862#issuecomment-1411650256:

> yes, the order should be consistent. For .dvc files, if it gets reordered, updates may happen in-place AFAIK, but `dvc.lock` files are strict. We are using the same logic behind `.dir` files here, so the order here is `size/nfiles/` kind of metadata, followed by `<hash_algo>: <hash_value>` (eg: `md5: ...`) followed by `relpath`, and cloud info.
> 
> I think the order should be reversed, `relpath`, then hash info, followed by metadata and then cloud info for `files`.

From https://github.com/iterative/dvc/pull/8862#issuecomment-1412426533:

> Added to #7093. We discussed recently that we should do a major release whenever we want to make some breaking change like this instead of waiting to gather up a bunch of these issues. What do you think of doing this and making a 3.0 release?

From https://github.com/iterative/dvc/pull/8862#issuecomment-1413171280:

> For `files`, we don't have to break anything. We can reorder it in dvc itself.

**Comment by dberenbaum** [comment]
@skshetry Do you mean we can reorder only for the cloud-versioned `files` section but not for `dvc.lock`? or other places we list this metadata? What do you think about doing that vs. reordering it everywhere?

**Comment by skshetry** [comment]
We don't want to change the order in `.dir` files, because it will break compatibility since it will change its hash. And we don't need to.

Since the contents are the same regardless of the ordering, it does not matter internally. The ordering logic only comes during save, either to `files` section or `.dir`, which can be changed. 

(Note to self: check how run-cache behaves with `files` section, it should just use `.dir` file instead)

**Comment by dberenbaum** [comment]
> We can reorder for `files` section in both `.dvc` and `dvc.lock` files.

Could doing this in a minor version cause some unexpected consequences (like merge conflicts if users work on different versions)?

**Comment by skshetry** [comment]
In `.dvc` file, at least the conflicts won't happen as updates happen in-place. In `dvc.lock` however, there may be chances of a conflict. We usually don't try to change order in a minor version as much as possible.

So for a `.dvc`/`dvc.lock` file that is tracking a file, the order probably should not change (but I'm okay if we decide to do so). Changing the order of `files` section can be done easily today, as it only concerns cloud versioning.

**Comment by dberenbaum** [comment]
@skshetry I think we decided not to take further action here, but I can't recall the details, so please reopen if I'm wrong/you disagree.
