### ISSUE TITLE
Cloud versioning issue: `dvc pull` doesn’t work after `dvc import-url ….  --no-download`

### ISSUE THREAD

**Issue by mnrozhkov** [iterative/dvc#8954]
# Bug Report

## Description

`dvc pull` doesn’t download files after `dvc import-url ….  --no-download` 

### Reproduce

1. Create a DVC remote storage with `version-aware` enabled, add  `dirname/` with images to DVC control, and `dvc push` to AWS s3 bucket 

2. Run `dvc import-url` for command to get `dirname.dvc` with tracking files medata 

Example: 
```
dvc import-url \
    s3://cse-cloud-version/dvc_label_studio/datasets/animals_example/images \
    --version-aware --no-download
    
Note: Auth to Iterative AWS s3 bucket is required
```

3. Run `dvc pull` command produces UNEXPECTED output: `dirname`  directory is empty
Example: 
```
❯ dvc pull
A       images/
1 file added
``` 
 If I don’t use `--no-download` flag, ` dvc import-url` works as expected

### Expected

`dvc pull` downloads files references in the `dirname.dvc`

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.43.3.dev5+g5d270134
----------------------------------
Platform: Python 3.10.4 on macOS-13.2-x86_64-i386-64bit
Subprojects:
	dvc_data = 0.37.5
	dvc_objects = 0.19.1
	dvc_render = 0.1.0
	dvc_task = 0.1.11
	dvclive = 2.0.0
	scmrepo = 0.1.7
Supports:
	azure (adlfs = 2022.11.1, knack = 0.10.0, azure-identity = 1.12.0),
	gdrive (pydrive2 = 1.15.0),
	gs (gcsfs = 2022.11.0),
	hdfs (fsspec = 2022.11.0, pyarrow = 10.0.1),
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	oss (ossfs = 2021.8.0),
	s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
	ssh (sshfs = 2022.6.0),
	webdav (webdav4 = 0.9.8),
	webdavs (webdav4 = 0.9.8),
	webhdfs (fsspec = 2022.11.0)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
```

**Additional Information (if any):**

- the same issue with previous versions of DVC
- not sure if this problem relates to `--version-aware` or only  `--no-download` flag
- DVC version used to version/push data to s3: `2.43.1 (pip)`

**Comment by skshetry** [comment]
Note that this is a blocker for official release of cloud versioning, but not for other intermediate releases.

**Comment by skshetry** [comment]
I don’t think I’ll have the capacity to look into this, unassigning myself.

@iterative/dvc, please feel free to take.

**Comment by pmrowla** [comment]
looks like this is due to `view.ls()` traverse not working properly (probably requires https://github.com/iterative/dvc-data/issues/278 be addressed)
