### ISSUE TITLE
experiments: make PID of experiment running in the workspace available

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#8963]
One of the features provided by the extension is the ability to stop experiments. E.g 

https://user-images.githubusercontent.com/37993418/216881762-a6651192-5814-4175-ac62-e0ca74f04543.mov

Currently, we can do this for:

1. Experiments started by the extension.
2. Experiments being run in the queue (we use `dvc queue kill <id>` or `dvc queue stop --kill` depending on the situation).

This means that experiments being run in the workspace outside of the extension cannot currently be stopped by the extension. As a result, we can't provide the stop option under these circumstances (global or inline). I have been unable to locate the PID of an experiment running in the workspace through any of the data provided to the extension (`exp show`) or in any of the internal files that DVC creates (e.g. `demo/.dvc/tmp/exps/rwlock`).

If the extension can get access to the PID of experiments running in the workspace (through any means) then we would be able to enable the missing piece of functionality.

Note: I am not sure if it makes sense to provide a stop/kill option from the CLI for experiments running in the workspace as the usual workflow would be to kill the process which is running in the terminal. This would only make sense to me if users were running experiments in the workspace as a background process (perhaps so they can still track live metrics but use the terminal for something else) but that seems unlikely. This is an alternative option. Happy to go with whatever is easier to implement.

**Comment by pmrowla** [comment]
When `.dvc/tmp/exps/rwlock.lock` exists it contains the pid for the workspace experiment. The one thing to be aware of here is that `rwlock.lock` may not always be cleanly removed after the experiment ends (i.e. in the event process crashed entirely or a user forcefully killed it with something like `kill -9`).

**Comment by mattseddon** [comment]
Thanks @pmrowla

**Comment by karajan1001** [comment]
> Thanks @pmrowla

Experiments started from cli can also be shown in the `vs-code` extension. Before `queue start` being added to the extension, I used to start queue worker from the cli
