### ISSUE TITLE
exp run: showing unhelpful error message for invalid pipeline

### ISSUE THREAD

**Issue by nv-pipo** [iterative/dvc#8973]
# Problem
As a follow up to https://github.com/iterative/dvclive/issues/435, DVCLIVE fails to track metrics for each checkpoint.

## Expected
Expected to have params/metrics (columns 'step', 'loss' and 'acc' in the following sample image) displayed for each checkpoint (https://dvc.org/doc/user-guide/experiment-management/checkpoints):
<img width="684" alt="Screenshot 2023-02-04 at 12 31 30 PM" src="https://user-images.githubusercontent.com/7769945/216764986-5e1f1688-77a7-4baa-8dcb-6c69a5285a6d.png">

## Result 1
Instead dvclive throws an error:
<img width="978" alt="Screenshot 2023-02-04 at 12 25 17 PM" src="https://user-images.githubusercontent.com/7769945/216764996-eb2efe78-b5d0-4c47-b79e-1053280e322f.png">

## Result 2
With ```metrics``` and ```plots``` directives disabled in ```dvc.yaml```, the experiment runs and the checkpoints are created, but no metrics are tracked:
<img width="863" alt="Screenshot 2023-02-04 at 12 33 18 PM" src="https://user-images.githubusercontent.com/7769945/216765037-cf857427-78d1-4559-9716-c9be95ca0de1.png">

# How to replicate
## Files
~~~python
# train.py
from random import random

from dvclive import Live

NUM_EPOCHS = 10


with Live(save_dvc_exp=True) as live:

    live.log_param("NUM_EPOCHS", NUM_EPOCHS)

    for epoch in range(NUM_EPOCHS):
        step = live.read_step()
        live.log_metric("metric", random())
        live.log_param("my_step", step)
        live.next_step()
~~~

~~~yaml
# dvc.yaml
stages:
  train:
    cmd: python train.py
    deps:
      - train.py
    outs:
      - dvclive:
          checkpoint: true
    metrics:
      - dvclive/metrics.json
    plots:
      - dvclive/plots
~~~

~~~shell
# init_repo.sh
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
git init
git add .
git commit -am 'Initial'
dvc init
~~~

~~~shell
# cleanup.sh
rm -rf .dvc dvclive .git .dvcignore .gitignore dvc.lock logs/ dvclive.* logs.* metrics.json
~~~

## Run

~~~shell
docker run -it -v $(pwd):/dvclive_test python:3.9 /bin/bash
# once in the docker container:
pip install dvc dvclive
cd /dvclive_test
init_repo.sh
dvc exp run
dvc exp show
~~~

**Comment by dberenbaum** [comment]
Transferred from dvclive -> dvc, but actually I think it's better to create a new issue

**Comment by shcheklein** [comment]
> Maybe worthwhile to update the https://github.com/iterative/dvc-checkpoints-mnist repo and the https://www.youtube.com/watch?v=PcDo-hCvYpw video? I had been using these as reference, but they are based on DVCLIVE 0.0.3.

The project is not being used on dvc.org or iterative.ai/blog. I think we can update the description to mention that it's outdated and redirect people to a new project.
