### ISSUE TITLE
dvc pull: failed to pull data from the cloud

### ISSUE THREAD

**Issue by haimat** [iterative/dvc#9006]
# Bug Report

## Description
I was working on one machine and pushed my changes in a local DVC project to Github. Then I wanted to `dvc push` in order to send all DVC data to our cloud storage. However, there have been some technical issues on the machine I was working on so that this DVC push was not correctly done. The result is now that these files I changed locally have not been pushed via DVC. Unfortunately that local machine is gone and I am not able to push via DVC any more.

Now I am working on another machine - I cloned the git project and tried to pull via DVC:

```console
$ dvc pull --run-cache
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
name: None, md5: bb9598f22fcc262a0f1527be353f009f.dir
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
name: None, md5: 664dc24ab058324683d60f4195d7d98f.dir
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
name: training/defects-sample/results.png, md5: 6de353ae2df3fabb0b84224839db32f0
name: training/defects-sample/args.yaml, md5: da079b1c834f24c1b3a0f7705fb37ac3
name: training/defects-sample/results.json, md5: 37b88b67d03f18dabc833c77d6e019dd
WARNING: No file hash info found for '/tmp/head/data/workspace'. It won't be created.
WARNING: No file hash info found for '/tmp/head/training/defects-sample/weights'. It won't be created.
A       data/defects/
A       training/defects-sample/confusion_matrix.png
A       data/defects-sample/
3 files added and 5 files failed
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
/tmp/head/data/workspace
/tmp/head/training/defects-sample/weights
/tmp/head/training/defects-sample/args.yaml
/tmp/head/training/defects-sample/results.png
/tmp/head/training/defects-sample/results.json
Is your cache up to date?
<https://error.dvc.org/missing-files>
```

The [DVC docs](https://dvc.org/doc/user-guide/troubleshooting#missing-files) say that one should "make sure to [dvc push](https://dvc.org/doc/command-reference/push) from the original project, and try again." But as said that is not an option any more in my case. How else can I fix this error?

### Reproduce

- run experiments on the local DVC project
- do a `git push` to send all changes to git
- do not push via DVC
- on another machine (or another local folder on the same machine) clone the git project and do `dvc pull`

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.44.0 (pip)
-------------------------
Platform: Python 3.10.6 on Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 0.39.3                                                                                                                                     dvc_objects = 0.19.3                                                                                                                                  dvc_render = 0.1.1
        dvc_task = 0.1.11                                                                                                                                     dvclive = 2.0.2                                                                                                                                       scmrepo = 0.1.9
Supports:                                                                                                                                                     http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),                                                                                                       ssh (sshfs = 2023.1.0)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
```

**Comment by shcheklein** [comment]
Hi @haimat ! Sorry to hear about the missing data issue. I think the only option in this case is to reproduce this one more time, do `dvc push` and either create a new commit or force push and update the broken one. The error should go away after that I think.

Do you have any specific expected behavior for DVC in this case? Please feel free to reopen if you have any specific suggestions / ideas.
