### ISSUE TITLE
Integration with Quilt

### ISSUE THREAD

**Issue by villasv** [iterative/dvc#901]
[Quilt](https://quiltdata.com/) is a pretty cool project and perhaps there's some room for integrating it as a remote option.

**Comment by dmpetrov** [comment]
That's interesting. Let's take a look at what we can do.
It looks like quilt provides two features:
1. provide proprietary storage for data files
2. data file versioning

DVC covers (2). But we might integrate DVC with their proprietary storage in addition to our S3\GCP\SSH...

Let's think about the integration. My biggest concern is the proprietary nature of this storage.

Is there anything special about quilt? I'd love to know scenarios when a DVC project with quilt will be more useful then DVC project with S3, for example.

**Comment by villasv** [comment]
The project seems to be getting some [organic traction](https://blog.paperspace.com/reproducible-data-with-pytorch-and-quilt/) and there are no successful alternatives AFAIK, so I expect it to be widely adopted in the near future.

Though this is definitely not a priority, mostly because people can just get around the lack of integration with the usual CLI commands from both projects separately. Let's just leave this issue open as a reminder :-)

**Comment by efiop** [comment]
Closing because of the lack of demand. Please feel free to reopen.
