### ISSUE TITLE
dvc does not cache stream opened files

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#9030]
Noticed during https://github.com/iterative/dvc/issues/8786 that we don't cache files that were streamed from remotes. So subsequent `plots show` always hits the remote and is thus slow.

**Comment by efiop** [comment]
Might be solved by https://github.com/iterative/dvc/pull/9037

**Comment by efiop** [comment]
@skshetry Could you try with the upstream, please?

**Comment by skshetry** [comment]
I don't think so. DVCFileSystem does not support caching, we just use `fs.open()` which only streams. AFAIR we had `fetch=True` that would fetch and then re-open from local cache in the past but we got rid of that in 2.0.

**Comment by efiop** [comment]
@skshetry Ah, I see. Maybe it is worth doing `dvc fetch` explicitly there instead.

**Comment by skshetry** [comment]
In plots, we return a dict with partial function to read file, and resolved later, so we can't do a fetch there.

https://github.com/iterative/dvc/blob/4f49023a0855d37536aeb8df3d4860697b6d690e/dvc/repo/plots/__init__.py#L169-L179

Since we are reading the file completely in memory on `fs.open()`, an easier way would be to bring `fetch=True` in `fs.open()` that'd first cache locally and reopen from it. :)
