### ISSUE TITLE
pull: error message when dir missing

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9066]
Yeah, it's related to DVC but I am not able to know the exact reason. A file called `None`(could be a bug on naming) is causing the issue and probably is not pushed to the remote.
<img width="1057" alt="Screenshot 2023-02-19 at 12 52 31" src="https://user-images.githubusercontent.com/20840228/219934077-6abab0ca-2c4e-4369-bcbe-7ecc7efc591b.png">

_Originally posted by @yathomasi in https://github.com/iterative/iterative.ai/issues/761#issuecomment-1435912415_

**Comment by yathomasi** [comment]
More on this https://github.com/iterative/iterative.ai/pull/761#issuecomment-1438231629
> the issue was that I had a different remote URL from another task. So, the issue can be closed but can be kept open for a better error message instead of `None`.

**Comment by omesser** [comment]
@dberenbaum - Hi, reading the original thread, want to clarify what's actually actionable by this bug.
Is this now about changing the warning about dir cached files missing, so they won't have "name: `None`" ?

**Comment by dberenbaum** [comment]
Yep, that's right @omesser
