### ISSUE TITLE
Specify profile name when importing file from repository

### ISSUE THREAD

**Issue by ElisaSuarez** [iterative/dvc#9068]
Hi, currently when importing a file from one repository to another you would use `dvc import <GIT URL> <PATH_TO_FILE>`command. The problem is that this assumes all you need is the information inside the `.dvc/config` file that is in git, but when you have many people working on the same repository, with different configurations, some information will be set up in the `.dvc/config.local`, for example the AWS CLI profile name when you use SSO. This means that, even if you are importing into a repo with a `config.local` file with the profile name, if the remote doesn't have it, it will throw an authentication error.

My request is to add a `--profile <PROFILE_NAME>` option for the `dvc import` command.

**Comment by ssmatana** [comment]
Also, wouldn't it be good if there was a possibility to set default SSO profile that my DVC uses to interact with repositories ? It seems to me that SSO profile name is specific to a person and maybe shouldn't be different from remote to remote.

**Comment by dberenbaum** [comment]
Are you using `export AWS_PROFILE=<PROFILE_NAME>`? DVC should respect that environment variable. Is there a specific reason why you need to specify the profile as part of the `dvc import` command?

**Comment by daavoo** [comment]
Feel free to reopen
