### ISSUE TITLE
tests: use stubbers for unit tests

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#907]
- [] s3: http://botocore.readthedocs.io/en/latest/reference/stubber.html (or better to use moto)
- [ ] gs: https://cloud.google.com/appengine/docs/standard/python/tools/localunittesting
- [ ] http: https://github.com/iterative/dvc/issues/1573

**Comment by mroutis** [comment]
We are already using moto for S3 since https://github.com/iterative/dvc/pull/2853

**Comment by efiop** [comment]
@mroutis Not really, lots of stuff is still tied to the real aws.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/4972
