### ISSUE TITLE
Ensure git hooks are using the correct python

### ISSUE THREAD

**Issue by david-waterworth** [iterative/dvc#9075]
I'm not sure if there's a great solution to this, but if you use virtualenv and install dvc from pip (as opposed to say apt) then dvc gets installed into the project virtualenv i.e.

```
python3 -m venv .venv
. .venv/bin/activate
pip install dvc[s3]
dvc install
```

The issue here is the hooks now fail as they cannot find dvc (or worst still they find a version installed in system python)

I manually edited my hooks to activate the venv, i.e.

`cat .git/hooks/post-checkout`

```
#!/usr/bin/sh
. .venv/bin/activate
exec dvc git-hook post-checkout $@
```

I'm not sure how this can easily be automated - maybe you could update https://dvc.org/doc/command-reference/install to add a note that if you're using a virtualenv you need to manually edit the hooks?

**Comment by daavoo** [comment]
> The issue here is the hooks now fail as they cannot find dvc (or worst still they find a version installed in system python)

Which OS and shell are you using?

The git hooks would use whatever `which dvc` is set on the shell.

As an example:

```console
$ cat .git/hooks/pre-commit
#!/bin/sh
exec which dvc
$ git commit
/Users/daviddelaiglesiacastro/miniconda3/bin/dvc
On branch master
nothing to commit, working tree clean
$ source .venv/bin/activate
$ git commit
/Users/daviddelaiglesiacastro/Desktop/git-hooks/.venv/bin/dvc
On branch master
nothing to commit, working tree clean
```

**Comment by david-waterworth** [comment]
I'm using vscode, you're correct if you use git from the shell, and you `source .venv/bin/activate` first it works. The issue seems to be with the vscode git integration, it seems to use its own shell and hence the hooks attempt to use the system version.

I guess you can close this as its a vscode thing - I'm having similar issues with a jupyter hook as well.
