### ISSUE TITLE
exp: save logs for workspace experiments

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9079]
We save the logs for queued experiments, but it would also be nice to have these for workspace experiments.

**Comment by mattseddon** [comment]
@dberenbaum should there be a way to grab the logs for any experiment? Similar to `dvc queue logs <task> [-f]`?

That would mean that the extension would be able to "Show Logs" for all experiments and it would also mean that we (either DVC or the extension) won't have to add an indicator for experiments that were processed in the queue/have accessible logs.

Related to this comment: https://github.com/iterative/vscode-dvc/pull/3347#issuecomment-1443729554

**Comment by dberenbaum** [comment]
No, there are no logs for workspace experiments today. The output goes right to the stdout/stderr streams. 

There should be logs for any queued experiment, regardless of whether they were successful.

`dvc queue remove` drops the logs for experiments, but the experiments remain, so it's always possible that experiments may not have logs available.

**Comment by mattseddon** [comment]
>  We could make this a dvc exp command instead of a dvc queue command if that's what you mean

This is what I meant, sorry for the lack of clarity.

What I was suggesting:

1. capture workspace run logs
2. (after 1) expose all logs via a new command `dvc exp logs <id>`

🙏🏻
