### ISSUE TITLE
investigate perf regressions

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#9098]
E.g. `dvc get` seems to have jumped significantly.

Probably related to persistent index cache.

**Comment by dberenbaum** [comment]
Putting my "real-world" timings below using our public data.

2.45.1

```bash
$ time dvc import git@github.com:iterative/dataset-registry.git use-cases/cats-dogs/data/validation
dvc import git@github.com:iterative/dataset-registry.git   2.83s user 0.94s system 43% cpu 8.571 total
```

main

```bash
$ time dvc import git@github.com:iterative/dataset-registry.git use-cases/cats-dogs/data/validation
dvc import git@github.com:iterative/dataset-registry.git   561.23s user 170.47s system 57% cpu 21:19.81 total
```

**Comment by efiop** [comment]
With `dvc-bench`-es `tiny` dataset seeing old dvc transferring 14 files, while new one is transferring 90. Couldn't pinpoint the problem yet, likely somewhere in transfer changes, but can't put my finger on anything yet. Looking into it...

**Comment by skshetry** [comment]
The copy is batched, so the `continue` makes it loop infinitely.
https://github.com/iterative/dvc-objects/commit/a0a173926e90ee52d8a2b5bfca333db9f19e0420

**Comment by efiop** [comment]
@skshetry Indeed, great catch! Do you want to submit a patch?

**Comment by skshetry** [comment]
It seemed like you wanted to catch errors from the `copy()` like we do for `try_links()`, so I did not try to fix it.

**Comment by efiop** [comment]
There are still some perf problems in the latest benchmarks, need to take another look.

**Comment by dberenbaum** [comment]
The real-world benchmark looks much better now:

```
$ time dvc import git@github.com:iterative/dataset-registry.git use-cases/cats-dogs/data/validation
dvc import git@github.com:iterative/dataset-registry.git   3.01s user 1.27s system 60% cpu 7.032 total
```

**Comment by dberenbaum** [comment]
Given the above comment, can we remove this as a release blocker?

**Comment by efiop** [comment]
Takes awhile to get back to this. Yeah, lets release for now.

**Comment by efiop** [comment]
Locally still slow, but acceptable with real remotes. Seems to be taking awhile to get back to this. Closing for now.

**Comment by skshetry** [comment]
I think we should still keep this open and investigate why. checkout/get/update has regressed significantly.

**Comment by dberenbaum** [comment]
I think we need to reconsider our benchmarks since they don't seem to reflect real use cases from my testing above. I'd be happy to hear if others see similar performance or not, but I don't have a lot of confidence that most of our benchmarks tell us anything meaningful now.
