### ISSUE TITLE
Add support for saving DVC plots as image files

### ISSUE THREAD

**Issue by sisp** [iterative/dvc#9121]
Currently, DVC supports saving plots in two formats: HTML (which uses Vega) and Vega JSON. To create PNG or SVG image files, it's necessary to convert the Vega JSON file, e.g., using the Node.js package `vega-cli` (`vl2png` or `vl2svg`). I think it would be nice if DVC had a builtin way to save plots as image files, so that no additional tools are needed.

I found the official Vega project [vl-convert](https://github.com/vega/vl-convert) (written in Rust) that includes [Python bindings](https://github.com/vega/vl-convert#python) which would make it easy to offer a builtin image export in DVC. I suggest to deprecate (and keep it for backwards compatibility) the `--show-vega` flag in the `dvc plots show` command and add a flag `--format html|vega|png|svg` where `html` is the default (as it is now).

WDYT?

**Comment by daavoo** [comment]
> WDYT?

I like the idea. 

The last time we considered it we deprioritized it because there was no project with python bindings like https://github.com/vega/vl-convert.

I would need to check `vl-convert` but it looks promising, thanks for sharing!

**Comment by dberenbaum** [comment]
This is great, thanks for the tip @sisp! One minor note: not sure if `--format png|svg` is that simple since there can be multiple plots/images for a single `dvc plots show` call. I think the use case we looked into previously was to generate images to be used inside `--format md` (see #8278). Maybe that would be enough since it would still generate the image files?

**Comment by sisp** [comment]
I think both cases are possible. `--format png|svg|vega` could require a target like `--show-vega` does while `--format html|md` does not because multiple images can be include in those documents.

**Comment by sisp** [comment]
By the way, there might even be two Markdown-based formats: `--format md+png|md+png`.

**Comment by adamliter** [comment]
I see this was closed as not planned. Is it something you all are still open to? This is functionality that I'd be interested in. If so, I'd be happy to try to find some time to work on a PR. (Also not sure how the status of this issue relates to #9272.)

**Comment by dberenbaum** [comment]
Thanks for your interest @adamliter! I closed #9272 now since that is also not in any near term plans, but feel free to work on `--md` or `--png` or similar if you are interested.
