### ISSUE TITLE
ci: celery queue remove/status race condition

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#9143]
see:
- https://github.com/iterative/dvc/actions/runs/4371541807/jobs/7647506453
- https://github.com/iterative/dvc/actions/runs/4485105768/jobs/7886311287

**Comment by pmrowla** [comment]
still some windows scm synchronization issues https://github.com/iterative/dvc/actions/runs/4496151375/jobs/7910539526

**Comment by dberenbaum** [comment]
Is it only about CI? I still sometimes get issues like a random experiment failing (with no logs available for it) or the queue stopping before consuming all jobs. Don't have a reproducible example though unfortunately.

**Comment by pmrowla** [comment]
@dberenbaum This is mainly for CI, but it's possible there's some other issue remaining? If the exp task fails before it actually runs a pipeline stage there won't be any logs, since the logs that we save are just the pipeline stage output.

If/when this happens to you again, you can also check `.dvc/tmp/exps/celery/dvc-exp-worker-*.out` (where `*` will be a # for each worker you started w/`--jobs`) which is the actual raw celery worker logs to see if/why a particular worker died

**Comment by daavoo** [comment]
> you can also check .dvc/tmp/exps/celery/dvc-exp-worker-*.out

Maybe is worth putting this info somewhere like https://dvc.org/doc/user-guide/troubleshooting . 
I recall saying it to users at least a couple of times in support duty, so it might be helpful to have direct link
