### ISSUE TITLE
ERROR: unexpected error - Can't create any SFTP connections!

### ISSUE THREAD

**Issue by drozzy** [iterative/dvc#9216]
> Copy of issue in dvc-ssh: https://github.com/iterative/dvc-ssh/issues/16

When doing dvc push or pull the following err
`ERROR: unexpected error - Can't create any SFTP connections!`

I've traced the error to this dvc version: `dvc==2.42.0`

In DVC version `2.41.1` the `dvc push` still work.
In DVC version `2.42.0` the `push` no longer works, and an error is produced:
`ERROR: unexpected error - Can't create any SFTP connections!`

Error persists in the latest (as of today) version `dvc == 2.50.1`.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc-ssh/issues/16

**Comment by dberenbaum** [comment]
@drozzy Did you post in both places for greater visibility?

**Comment by drozzy** [comment]
Yes, because git hook automatically calls dvc push, and the whole thing fails.
Additionally now the requirement for the old version old dvc 2.41.1 breaks the VSCode dvc plugin.
