### ISSUE TITLE
config: disallow configuring some options in the default config

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9217]
For options like `studio_token` in https://github.com/iterative/dvc/pull/9213, should we disallow them to be written to `.dvc/config`, at least without `dvc config -f`? It could be helpful for other sensitive options also, but especially in this case where it's our own token, it feels like it would be nice to try to prevent user error in exposing secrets.

**Comment by daavoo** [comment]
> So I don't think this is limited to just studio_token.

It is not limited but as Dave mentioned in this case we can be more opinionated as is "our" token.

> I think it's better to recommend chmod 600 or umask 077 to the .dvc/config so that it's only readable/writable by the user if there are any sensitive credentials.

Those recommendations might feel out of context for some users (and we would need to document an equivalent, separate section for windows).

Why not enforce/handle it using the existing tools in DVC, like the scopes of `dvc config` like `--local`?
That's what we currently document/recommend.

**Comment by skshetry** [comment]
> in this case we can be more opinionated as it is "our" token.

What I am trying to say is that it equally applies to other configs, and should be treated similarly. The goals are the same: to try to prevent leaking credentials.

> Why not enforce/handle it using the existing tools in DVC, like the scopes of dvc config?

`dvc config` is a lower-level command though, and I'm not quite sure if it should disallow from writing config. I value security more on this though, so don't have strong opinion.

---

To be honest, I'd prefer not even requiring a token: no token, no risk of leaking it.

**Comment by daavoo** [comment]
> dvc config is a lower-level command though, and I'm not quite sure if it should disallow from writing config.
Someone could still write manually.

I think it's not about completely disallowing but more about preventing inexperienced/unfamiliar users from leaking credentials unintentionally. So, maybe warning with a clear explanation + error with workaround (or ask for confirmation?):

```console
$ dvc config studio_token FOO
ERROR: You are trying to store `studio_token` in a file tracked by Git (`.dvc/config`).
If you are sure you want to do this, you can run `dvc config -f studio_token FOO`.
You could run `dvc config --local studio_token FOO` to store it in a git-ignored file (`.dvc/config.local`).
```

```console
$ dvc config studio_token FOO
WARNING: You are trying to store `studio_token` in a file tracked by Git (`.dvc/config`).
You could run `dvc config --local studio_token FOO` to store it in a git-ignored file (`.dvc/config.local`).
Do you want to continue (y/N)
```

**Comment by daavoo** [comment]
> What I am trying to say is that it equally applies to other configs, and should be treated similarly. The goals are the same: to try to prevent leaking credentials.

I think we could easily make a list of config fields that we know people would not want to leak and validate against it
