### ISSUE TITLE
exp remove: ping studio to remove experiment

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9227]
`dvc exp remove -g` should also ping Studio to drop the experiment from the UI. Currently, there is no way to clean up experiments once they have been added in Studio.

**Comment by skshetry** [comment]
I wonder how Studio removes existing commits. It’s probably tied to branch lifecycle.  cc @amritghimire

Anyway, I don’t think we should eagerly remove from CLI. It’s better to remove it from the web UI or automatically on the next parse.

**Comment by amritghimire** [comment]
It will be marked as deleted commit in next parse. We can use the same webhook trigger on delete to start the parse.

**Comment by dberenbaum** [comment]
Here's what it looks like when a branch is deleted in Studio (the `scatter-jitter` branch in this case):

https://user-images.githubusercontent.com/2308172/227249234-c9b9b6c4-7f18-47c4-8732-2dc007f9b402.mov

@skshetry I agree that removing from the web UI would be better, but we still need to address what should happen when using `dvc exp remove -g`. It could look similar to this branch delete workflow where Studio shows that there is an update and removes the experiment when the user clicks to update or reloads.

**Comment by skshetry** [comment]
As long as it gets eventually removed, I'd prefer to focus on other parts of the integration. If Studio does not do that yet, it should do that during parse automatically.

I think for now, we should think of extending the payload to `{added: list[str], removed: list[str]}` to be safe. But we are still discussing changing the API that I don't want to propose this right away. It's something that we should keep in mind though.

For the release on the DVC side, I don't think this is urgent or P1. We can do it later as long as it gets removed eventually.

**Comment by dberenbaum** [comment]
Sounds good @skshetry, I agree we can make it a follow-up once we have solidified, so I can move this down to p2 for now.

**Comment by skshetry** [comment]
Closed by https://github.com/iterative/dvc/pull/9248.
