### ISSUE TITLE
S3 AWS: default profile is always used

### ISSUE THREAD

**Issue by wardvl-ixor** [iterative/dvc#923]
Hi!

Defining a profile in dvc-config has no influence on the used profile in AWS credentials file.

I quickly took a look at the code and  I never see boto3.session(profile=..) called. Or is this done using the AWS_PROFILE env variable?

(using dvc 0.14.0)

**Comment by efiop** [comment]
@wardvl-ixor I've merged the fix and creating a 0.14.1 release right now. It should be out in an hour or so.

Thank you so much for the feedback!

**Comment by wardvl-ixor** [comment]
hi @efiop , thanks for the quick fix!
