### ISSUE TITLE
ERROR: unexpected error - Failed to initialize: Bad git executable.

### ISSUE THREAD

**Issue by bwassim** [iterative/dvc#9234]
# Bug Report

## Issue name
ERROR: unexpected error - Failed to initialize: Bad git executable.

## Description
after trying to generate another experiment in vscode with DVClive I had a message saying DVC Terminal and after the error you see below. dvc exp run with my selected parameters did not go through because of some issue with variable environement of GIT and Python. I tried to follow the instruction but it does not seem to solve the error. Thanks for your help.

### Reproduce

ERROR: unexpected error - Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

### Expected
I am using the option of running modify params and run inside vscode with DVClive. I am also running on gitbash inside vs code

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.43.4 (pip)
-------------------------
Platform: Python 3.9.15 on Windows-10-10.0.19044-SP0  
Subprojects:
        dvc_data = 0.37.8
        dvc_objects = 0.19.3
        dvc_render = 0.1.0
        dvc_task = 0.1.11
        dvclive = 2.0.2
        scmrepo = 0.1.7
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by daavoo** [comment]
Hi @bwassim , have you tried setting the env var `GIT_PYTHON_REFRESH` (`set GIT_PYTHON_REFRESH=quiet`) in the terminal?

**Comment by bwassim** [comment]
I actually did. Didn't resolve the problem.

**Comment by daavoo** [comment]
> I actually did. Didn't resolve the problem.

Ok. Could you try checking/following the answer here: https://stackoverflow.com/a/51038428/6076911 (check the position of the git executable in PATH and ensure is/move it above the Python executable)
