### ISSUE TITLE
Updater.py does not work with python 2

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#924]
Hi there, I noticed that with python 2, the updater fails since it is trying to import the `requests` module.

Cheers,
David

**Comment by efiop** [comment]
Hi @prihoda !

I'm not able to reproduce this. Could you share more info please? For example could you please run this:

```
$ rm .dvc/updater
$ dvc status -v
```

and share the output?

**Comment by prihoda** [comment]
Sorry my bad, it was just a problem with my python environment. Closing this issue.
