### ISSUE TITLE
plots: remove `--show-vega` flag

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#9272]
There is a discussion there starting from https://github.com/iterative/dvc/issues/7093#issuecomment-997887278 .
To give a more recent summary:

- The --show-vega flag is superseded by --json (supports multiple plots + images)
- The use case of --show-vega can be replaced with --json but requires some handling of the output with (i.e. jq), making it less convenient for integrating with cml pr.

My take on this is that is not enough reason for keeping the old flag and we should instead implement https://github.com/iterative/dvc/issues/9121 / https://github.com/iterative/dvc/issues/8728

**Comment by shcheklein** [comment]
@daavoo could you please put some motivation?

**Comment by dberenbaum** [comment]
@daavoo Agreed, but do you think it's a high priority for 3.0? I think we could add it later and "soft deprecate" `--show-vega` if needed.

My rationale for not prioritizing it would be that we have increasingly better ways to show the plots than putting them into a markdown doc, so I'm not sure how many scenarios we still would suggest it.

**Comment by omesser** [comment]
+1 for soft-deprecating `--show-vega` now (doesn't need to wait for 3.0), and hard deprecating it in the future once #9121 is implemented (#8728 more nice to have, I think?)
This means this can be decoupled from 3.0 release efforts

Is this acceptable, wdyt?

**Comment by shcheklein** [comment]
btw, one thing where I was using this is to debug plots - copy paste the output into the Vega editor and iterate on the template for example. Not sure it's substantial enough tbh or if `--json` can replace it easily, but it was handy.

**Comment by dberenbaum** [comment]
@daavoo I get the motivation to not rely on `--show-vega` for generating markdown reports, but what's the motivation to deprecate the flag altogether?

**Comment by dberenbaum** [comment]
Discussed with @daavoo and agreed we can do soft deprecation or maybe even leave the flag alone if we don't use it in CML or other docs and focus on better markdown support and `--json` instead.

**Comment by omesser** [comment]
@dberenbaum  - so which is it? no deprecation (no AR, close this) or soft-deprecation (AR: remove docs) ? 😄

**Comment by dberenbaum** [comment]
I vote for no deprecation (don't really see the benefit) but I don't feel that strongly, so @daavoo can decide whatever he prefers.
