### ISSUE TITLE
push: ERROR: unexpected error - No module named 'funcy.py3'

### ISSUE THREAD

**Issue by justin-barton** [iterative/dvc#9312]
# Bug Report

## Description
Attempting `dvc push` after upgrading to 2.25.0 via homebrew results in the following error:
```
ERROR: unexpected error - No module named 'funcy.py3'
```

Error also occurs with:
`dvc gc --workspace --cloud`

### Reproduce

1. brew upgrade dvc
2. dvc push (in a dvc repo)

### Expected

A successful push with no error

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.52.0 (brew)
--------------------------
Platform: Python 3.11.2 on macOS-13.2.1-x86_64-i386-64bit
Subprojects:
	dvc_data = 0.46.0
	dvc_objects = 0.21.1
	dvc_render = 0.3.1
	dvc_task = 0.2.0
	scmrepo = 0.2.0
Supports:
	azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
	gdrive (pydrive2 = 1.15.1),
	gs (gcsfs = 2023.3.0),
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	oss (ossfs = 2021.8.0),
	s3 (s3fs = 2023.3.0, boto3 = 1.24.59),
	ssh (sshfs = 2023.1.0),
	webdav (webdav4 = 0.9.8),
	webdavs (webdav4 = 0.9.8),
	webhdfs (fsspec = 2023.3.0)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: gdrive
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/4e0f73890d5804a3573058e36cb97bc0
```

**Additional Information (if any):**
`python3.11 -m pip install funcy` reports the following:
```
Requirement already satisfied: funcy in /usr/local/lib/python3.11/site-packages (2.0)
```

As does `/usr/local/Cellar/dvc/2.52.0/libexec/bin/python3.11 -m pip install funcy`:
```
Requirement already satisfied: funcy in /usr/local/Cellar/dvc/2.52.0/libexec/lib/python3.11/site-packages (2.0)
```

**Comment by justin-barton** [comment]
Installing funcy==1.17 resolves this, so I'm guessing that it's an issue with funcy>=2.0 (current)

**Comment by efiop** [comment]
2.25.0 is very old, homebrew already has latest 2.53.0 which has this solved (as well as older version). Please upgrade dvc.

**Comment by justin-barton** [comment]
@efiop this was in 2.52.0 not 2.25.0.  I have upgraded to 2.53.0 and the issue is there as well.

**Comment by efiop** [comment]
@justin-barton Could you show full verbose log, please? (add -v flag)

**Comment by Hitdahit2** [comment]
I'm having same issue. Here is my my full verbose log.
I've installed dvc 2.53.0 with home brew.
[verboselog.txt](https://github.com/iterative/dvc/files/11184872/verboselog.txt)

**Comment by efiop** [comment]
@Hitdahit2 Seems like part of the log is missing?

**Comment by Hitdahit2** [comment]
@efiop Sorry, which part of the log is missing?
I just used the command below to make that file.
`dvc push ./data.xml -v > verboselog.txt`

**Comment by efiop** [comment]
@Hitdahit2 Try:

```
dvc push ./data.xml -v &> verboselog.txt
```

**Comment by Hitdahit2** [comment]
@efiop Thank you for your advice. Here is my log file.
[verboselog.txt](https://github.com/iterative/dvc/files/11184991/verboselog.txt)

**Comment by efiop** [comment]
@Hitdahit2 Thank you! Looks like it is pydrive2 that is triggering this. Let me double check...

**Comment by efiop** [comment]
Ok, https://github.com/iterative/PyDrive2/pull/274 should fix it in the next release.

If possible, a workaround for you might be to just use dvc installed from `pip` for now instead of `brew`. Another one could be to mess with the env in which brew installed dvc to downgrade funcy to <2, but that's more involved.

Next dvc release should have this fixed out of the box.

Thank you for reporting this problem! 🙏

**Comment by Hitdahit2** [comment]
Thank you for your kind comments! Have a nice day! @
