### ISSUE TITLE
Dvc 2.52.0 and 2.53.0 experiments no longer work

### ISSUE THREAD

**Issue by drozzy** [iterative/dvc#9320]
Create a stage with `metrics` output.
Run dvc exp run.
Run dvc exp show.

In dvc 2.41.1 this works and shows experiments created, but in 2.52 and 2.53 it doesn't show anything except exclamation marks `!`.

In both cases, there are new git refs created under `refs/exps`.

**Comment by shcheklein** [comment]
@drozzy could you please try to create a small reproducible example?

Also, give us please a bit more details. How do you run it - just `dvc exp run` or something else? Could you try `dvc exp run -v`, etc, etc.

**Comment by daavoo** [comment]
@drozzy Could you also try `dvc exp show --force`?

**Comment by efiop** [comment]
Closing as stale.
