### ISSUE TITLE
Bug Report: failed to pull data from the cloud

### ISSUE THREAD

**Issue by rolandpinter** [iterative/dvc#9324]
# Bug Report: failed to pull data from the cloud

Hello! 

We've started using `dvc` with an `Azure` cloud storage backend. We are adding files to cloud according to the expected way: 
```Bash
dvc add $filename
git add $filename.dvc
git commit -m "added $filename"
git push
dvc push $filename.dvc
```
99% of the time, the system is stable, however, there are some random cases, when a file is downloadable one day via `dvc pull` but the other day, it yields the following error:
```
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
name: $filename, md5: $some_md5_hash
1 file failed
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
$filename
Is your cache up to date?
<https://error.dvc.org/missing-files>
##[error]Bash exited with code '1'.
```

Has anyone experienced a similar issue? We've tried looking into this, but so far, we could not find a solution.  We are using `2.42.0` version of `dvc`.

Thanks in advance!

**Comment by skshetry** [comment]
Hi, could you please try with the latest release and see?

**Comment by rolandpinter** [comment]
Hi!
Yes, we have tried with the latest release as well! However, this is a recurring issue, which we had some time ago with a previous dvc version also, so I would not think that this has anything to do with the actual version.

**Comment by skshetry** [comment]
@rolandpinter, try adding a `-vv` to the `dvc push` command, and see why it's failing.
AFAIK s3/gcs do retry but adlfs does not (not sure if underlying library handles them).
Anyway, the verbose logging would help us know why it's failing. If it's a network or a transient error, we can add a retry to adlfs upstream. Thanks.

**Comment by rolandpinter** [comment]
Sure thing from now on we can do push with -vv. However, as I've mentioned in the bug report, the push itself is successful. After pushing, we can pull the files, but after some time, there are some files which become un-pullable with the above mentioned error message.

**Comment by skshetry** [comment]
@rolandpinter, any updates? Does this still happen?

**Comment by madacsbotond** [comment]
Hi @skshetry, we didn't encounter this error again so far, we created github action to make sure that the new dvc files are really pushed, not just added and we are trying to make sure that we use the latest dvc version.

**Comment by skshetry** [comment]
Thanks. We do have some plans to improve this in the near future. I am going to close this issue for now, then.

**Comment by skshetry** [comment]
cc @dberenbaum, this was the Azure flaky issue that I was talking about.
