### ISSUE TITLE
Add Huggingface Dataset as a remote store for dvc

### ISSUE THREAD

**Issue by jagadeeshi2i** [iterative/dvc#9327]
DVC has support for remote storage like gDrive, s3 etc. It will be great if it support huggingface dataset as one of the remote stores. This would help users make use of capabilities of dvc with huggingface.

**Comment by efiop** [comment]
@jagadeeshi2i Could you elaborate, please?

**Comment by jagadeeshi2i** [comment]
Updated

**Comment by dberenbaum** [comment]
Closing in favor of #9175 since it has more detail about how dvc should work with huggingface datasets. If you feel that this should remain open as a separate issue, feel free to provide more info.
