### ISSUE TITLE
kombu installation failed: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers

### ISSUE THREAD

**Issue by chenrui333** [iterative/dvc#9328]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
    /opt/homebrew/Cellar/dvc/2.54.0/libexec/lib/python3.11/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
      warnings.warn(msg, warning_class)
    error in kombu setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
        pytz>dev
            ^
    error: subprocess-exited-with-error
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4685005370/jobs/8301749271
relates to Homebrew/homebrew-core#128229

**Comment by efiop** [comment]
Hi @chenrui333 !

Replied in the PR.

Thank you! 🙏

**Comment by chenrui333** [comment]
no problem :)

**Comment by skshetry** [comment]
I don't think there's anything that we can do on this until kombu 5.3 is released (see https://github.com/celery/kombu/issues/1677). 

The failure is not just homebrew related. If anyone is having this issue, they can try installing `wheel` before installing dvc, as that won't require building wheels or calling setuptools.
```console
pip install wheel
pip install dvc
```

If you are using `--no-binary` or don't want to install binary, you have to downgrade to `setuptools<67` before installing dvc.
```console
pip install "setuptools<67"
pip install dvc
```

**Comment by pmrowla** [comment]
You can also install the kombu 5.3 beta (the setuptools issue is fixed in `5.3.0b3`) prior to installing DVC with
```
pip install --pre kombu
```

**Comment by skshetry** [comment]
Closing as there's nothing to do on our side.

**Comment by skshetry** [comment]
@chenrui333, see https://github.com/celery/celery/issues/7605#issuecomment-1544123225. They are targeting to release by the end of this month but 🤞🏼.
