### ISSUE TITLE
exp push: notify studio even if cache push fails

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9342]
During `exp push`, Studio will not be notified of the pushed experiments if the cache push fails because the error is raised before calling to notify Studio:

```
$ dvc exp push origin outer-chum
Pushed experiment outer-chum to Git remote 'origin'.
ERROR: failed to push cache: Unable to locate credentials
```

**Comment by skshetry** [comment]
This is intentional. There is no cache for Studio to parse. I am not sure how Studio handles this case (and users may have to force-import them). cc @amritghimire

**Comment by skshetry** [comment]
yeah, it is treated as commits. The part that I worry is:

> and users may have to force-import them to fix it

**Comment by dberenbaum** [comment]
Let's please still notify Studio and follow up in Studio with how to fix the missing data status in Studio. I don't think it's even specific to exp refs, right? I also don't know how Studio handles reparsing regular commits when the cache is pushed after initial parsing.

**Comment by skshetry** [comment]
I don't have strong opinion on DVC side. Maybe let's wait to hear from @iterative/studio-backend team? 

Also, should `dvc exp push` fail if cache push fails?

**Comment by dberenbaum** [comment]
> Also, should `dvc exp push` fail if cache push fails?

Good question. I think it probably should by default, since for example pushing the cache may be critical in CI.

@skshetry What's your concern with fixing on the DVC side and then following up with Studio about the missing data status? As I mentioned above, I don't see how it's even specific to `dvc exp push`. Even if you believe Studio shouldn't show these experiments, Studio will show them now as soon as there are any other updates to the repo or the user clicks the new reload/update button, so the current state feels broken to me.
