### ISSUE TITLE
exp: include names for running experiments

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9348]
Running experiments have different naming conventions between CLI/VS Code and Studio. See the comparison below taken at the same time across all 3 products (`mucky-cwms` is the workspace experiment and the other two are experiments running in the queue):

<img width="535" alt="Screenshot 2023-04-19 at 4 02 26 PM" src="https://user-images.githubusercontent.com/2308172/233190157-f9b09675-f405-4802-bcaa-fbe0c7c8b7ff.png">
<img width="341" alt="Screenshot 2023-04-19 at 4 02 38 PM" src="https://user-images.githubusercontent.com/2308172/233190167-1415ccd8-2ea3-4507-b8c2-e20478e7cbb8.png">
<img width="454" alt="Screenshot 2023-04-19 at 4 02 47 PM" src="https://user-images.githubusercontent.com/2308172/233190174-7e778c2a-d434-4b81-b93f-2daa1de1c7c0.png">

* Workspace experiments are only named `workspace` in CLI/VS Code. Can we include the experiment name also in the CLI/VS Code for a running experiment in the workspace?
* Experiments running in the queue have only hashes in CLI/VS Code (although experiments still waiting in the queue have names). Can we include the experiment name for a running experiment from the queue?

**Comment by dberenbaum** [comment]
> * Experiments running in the queue have only hashes in CLI/VS Code (although experiments still waiting in the queue have names). Can we include the experiment name for a running experiment from the queue?

It looks like this will be resolved by #9170, so that would only leave the issue of having names somewhere for experiments running in the workspace. 

In the workspace, I believe these may be set by dvclive, but I don't see any reason dvc can't name experiments at the start and show them in `dvc exp show`.

**Comment by pmrowla** [comment]
This will be resolved by #9170. DVC already sets exp names before running them, whether or not dvclive is being used
