### ISSUE TITLE
Get EV code signing certificate to sign our binary packages

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#936]
I.e. https://www.certum.eu/en/cert_offer_microsoft_code_signing/ .

The "untrusted source" window is annoying, but it is only a small part of the problem. A much bigger problem is that when you install dvc from binary windows package, windows defender thinks that this is a virus and makes it extremely slow. To fix that we need to sign our packages with a trusted certificate.

**Comment by efiop** [comment]
No longer needed after https://github.com/iterative/dvc/pull/1447 , since we no longer build a single binary and all binaries in --onedir are already signed.

**Comment by efiop** [comment]
Reopenning since we still need this for our installers.

**Comment by jorgeorpinel** [comment]
Just want to post what this looks like on Windwos. The installer is stopped by Windows Defender with a "Windows protected your PC" screen:

![image](https://user-images.githubusercontent.com/1477535/78174517-9f5d0f00-7416-11ea-8c84-4918c8c3357d.png)

You need to click "More info" to be able to use the [Run anyway] button:

![image](https://user-images.githubusercontent.com/1477535/78174716-f06d0300-7416-11ea-9221-db8079616e03.png)

**Comment by efiop** [comment]
For the record:

- [x] [rpm and deb](https://github.com/iterative/dvc-s3-repo)
- [ ] [windows](https://dvc-public.s3.us-east-2.amazonaws.com/dvc-pkgs/exe/dvc-2.0.6.exe) signed but download links on dvc.org are not updated yet.
- [ ] mac pkg
