### ISSUE TITLE
cloud versioning: add gc support

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9360]
Add support for:

- [ ] `dvc gc --not-in-remote` (see https://github.com/iterative/dvc/pull/9350)
- [ ] `dvc gc --cloud`

**Comment by daavoo** [comment]
> Is it possible to have this feature implemented? I believe it is essential to keep consistency on the remote side. Thanks in advance!

@manucalop would you expect DVC to "hard delete" the old versions of the files?

**Comment by manucalop** [comment]
Hi @daavoo ! Thanks for the quick reply :) I'd expect to delete the live object, leaving its version history to be managed by the cloud-versioning system.

**Comment by nullhack** [comment]
I've been exploring DVC and I've also noticed this feature gap. Ideally, I'd prefer that the cloud storage's state mirrors the current state of the DVC repository. My expectation is that when using dvc gc -cw, it should remove the current version of any deleted file, aligning the cloud storage more closely with the repository's present status
