### ISSUE TITLE
exp run: add --no-save flag

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9370]
The first step could be adding a flag (`--no-save`?) to make the current `dvc exp run` behave like `repro` so that we have one consolidated command we could use when we are ready to deprecate the others.

_Originally posted by @dberenbaum in https://github.com/iterative/dvc/issues/7866#issuecomment-1518280846_

**Comment by dberenbaum** [comment]
> What's our goal here? Do we want to have the same behaviour as `dvc repro` in `dvc exp run --no-save`? Or, is it just `--no-save` variant of `dvc exp run`? Ideally, they should be the same, but there are going to be subtle behaviour differences.

_Originally posted by @skshetry in https://github.com/iterative/dvc/issues/7866#issuecomment-1553914112_

**Comment by dberenbaum** [comment]
@skshetry Copying your comment here since #7866 has a lot of other noise.

What are the differences implementation-wise since they do both eventually call `reproduce`, right? One concern with basing it on `exp run` is additional overhead. If this is not doing any of the git tracking of the experiment and is always running in the workspace (no queueing or cloning to temp dirs), what overhead is left?

From https://github.com/iterative/dvc/issues/6791#issuecomment-1043363367, there are a few options that aren't supported in `exp run`:
* `--no-run-cache`
* `--no-commit`
* `--glob`

I can't recall the issue with trying to support `glob`, but if it's too much of a mess to support it properly, I think we could drop it. The other two seem reasonable to keep only with `--no-save`, although I doubt either is commonly used.

**Comment by dberenbaum** [comment]
Another discrepancy between the commands: `--no-run-cache` is only supported in `repro`.

**Comment by daavoo** [comment]
If we add `--no-save` and just make it an if that calls `repo.reproduce`, I don't see the need for any discussion. There is no overhead and all flags could be supported

**Comment by dberenbaum** [comment]
Another important distinction to preserve is that `dvc repro` can run with no_scm.

**Comment by dberenbaum** [comment]
@skshetry I've been playing with using `exp run` for everything, and TBH it feels annoying a lot of the time when you don't actually need an experiment. Even with `--no-save`, I would prefer not to have to add that flag all the time. So I don't think we even need to prioritize this flag.

What is critical is to make `repro` and `exp run` as similar as possible so we can say that they are functionally equivalent except for the additional overhead of saving, queuing, etc. without users needing to worry about small differences between them.

For now, it seems that these are the known discrepancies to address then:

> From [#6791 (comment)](https://github.com/iterative/dvc/issues/6791#issuecomment-1043363367), there are a few options that aren't supported in `exp run`:
> 
>     * `--no-run-cache`
> 
>     * `--no-commit`
> 
>     * `--glob`
> 
> 
> I can't recall the issue with trying to support `glob`, but if it's too much of a mess to support it properly, I think we could drop it. The other two seem reasonable to keep only with `--no-save`, although I doubt either is commonly used.
