### ISSUE TITLE
Being able to call  `exp show` with multiple branches (`--rev`) and a number of commits (`-n`)

### ISSUE THREAD

**Issue by sroy3** [iterative/dvc#9390]
In the VS Code extension, we would like to show multiple branches at the same time in the table. Each with its own number of commits. We're currently doing this by calling `exp show` once per branch (`dvc exp show --rev main -n 5`, `dvc exp show --rev other-branch -n 3`...). We'd like to be able to do this in one call only (something like `dvc exp show --rev main -n 5 --rev other-branch -n 3...`). Would it be possible?

**Comment by daavoo** [comment]
> Would it be possible?

The internal API already supports multiple `revs`.

This should be a simple change to make for the CLI (TBH I thought the CLI also supported it)

**Comment by sroy3** [comment]
That was fast! Thanks!

**Comment by shcheklein** [comment]
Tbh, it feels we should have the mapping on the VS Code side and pass only unique hashes to the API. @mattseddon how complicated is it? Why is it an issue considering that we already run `git log`, etc? I though that we had this information already tbh.

**Comment by mattseddon** [comment]
> Are you also going to duplicate experiments in that case? More importantly, if we can make dvc exp show return stable results, is it an option to drop the duplicates in VS Code

If a commit is on both `branch-a` and `branch-b` and we are displaying both branches separately then how would we de-duplicate and not have to explain in detail to a user why a commit is missing from one of the selected branches?

> Tbh, it feels we should have the mapping on the VS Code side and pass only unique hashes to the API. @mattseddon how complicated is it? Why is it an issue considering that we already run git log, etc? I though that we had this information already tbh.

We need to rework what has been written to do this. Atm `exp show` provides the list of commits which we then pass to `git log` to get the commit information. I did not dig into the code before writing https://github.com/iterative/dvc/issues/9390#issuecomment-1560459523

**Comment by sroy3** [comment]
> Re: git log calls, if we add the commit message to `dvc exp show`, could we get rid of the `git log` calls? I'd like to reduce the number of calls if we can.

We don't know what we are asking for until after it was sent back. If we're asking for `branch~1` and it's the same as `main~3` and it's not returned because of that, we have no way of associating it with `branch`, and the branch association gets shifted by one. This can be circumvented by taking calling `git log` before with the revision `branch~1` and getting a commit hash that we will associate with `branch`; later, we will run `git log` on the revision `main~3` and get the same hash and add `main` to that hash as well. When we get the results from `exp show`, we'll add the branch to the output with the previous mapping. If a hash has more than one branch, we'll duplicate the output for the other branch. Adding the commit message to the `exp show` output won't allow us to remove the `git log` calls for that reason, unfortunately. 

We need duplication because when asking for more commits, we need to show more commits. We don't know ahead of time which commit is duplicated. Even if we call `git log` with a previous revision (`branch~2`, `branch~3`...) until we get another unique hash (or not), there is no way for us to know if we can allow the user to show more commits or not previous to that.

**Comment by dberenbaum** [comment]
Thanks @sroy3! Sorry to make you explain all that, but now I understand.
