### ISSUE TITLE
repro: run cache doesn't work for nondeterministic stages after `dvc gc`

### ISSUE THREAD

**Issue by peper0** [iterative/dvc#9420]
## Description

`dvc gc` removes unused output files, but does not remove runs from the cache.

If, after `gc`, we do repro such that it gets hit in the run-cache but outputs are not in the cache, then `repro` reruns the command. If that command produces another output (e.g. due to some randomness, or hardware dependency), the new run often does not override the old one in the cache. In this situation, the subsequent runs for the same inputs in the future won't restore the output from the run cache, since the outputs for the original run are not present.

### Reproduce

1. `dvc init`
2. Create a stage, that depends on a file, but may be not deterministic, e. g.:
```
echo 1 >a
dvc run -f -n makeb -d a -o b 'echo "$(cat a) $DISTURBANCE" >b'
```
3. One run is not always sufficient to reproduce the bug (probably it depends on the order of files in the run cache directory), so we force repro 10 times.
```
for ((DISTURBANCE=0; DISTURBANCE<10; ++DISTURBANCE)) ; do
  export DISTURBANCE
  dvc repro -f >/dev/null
done
```
3. Change, the input and run repro (`a=2`):
```
echo 2 >a
dvc repro
```
4. `dvc gc -wf`
5. Do repro again for `a=1`, to reproduce files lost during `dvc gc`
```
echo 1 >a
export DISTURBANCE=5
dvc repro
```
6. Do repro for `a=2`
```
echo 2 >a
dvc repro
```
7. Do repro for `a=1` again.
```
echo 1 >a
export DISTURBANCE=5
dvc repro
```
The output is being reproduced (the stage command is called).

### Expected

In step 7 The output should be restored from the run-cache, since it was already produced in step 5, and `gc` was not called since then.

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.56.0 (pip)
-------------------------
Platform: Python 3.11.3 on Linux-5.4.0-132-generic-x86_64-with-glibc2.31
Subprojects:
	dvc_data = 0.47.5
	dvc_objects = 0.21.2
	dvc_render = 0.4.0
	dvc_task = 0.2.1
	scmrepo = 1.0.3
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Config:
	Global: /home/tlakota/.config/dvc
	System: /etc/xdg/dvc
```

**Comment by peper0** [comment]
IMO it could be fixed in one of the following ways:
* when searching the run-cache, ignore "values" for the current run hash ("key") that cannot be restored, since outputs referenced there are not in the cache
* during `gc`, remove runs that depend on the removed files
* when adding a run to the run-cache remove the others (effectively overriding them)

**Comment by peper0** [comment]
I've posted PR that implements the first of the solutions proposed by me, which is the easiest and the least intrusive one.

**Comment by dberenbaum** [comment]
@peper0 Sorry for the lack of responsiveness here. Taking a look at #9421, there are some product questions to resolve as to what should be the correct behavior here (as you noted above). Can you clarify how you ran into this bug, and how does it impact you?

> BTW, what is the reason to have multiple "values" for every "key" in the run cache? As I understand, we want to store more than one entry for one set of inputs of a given stage. Why?

@iterative/dvc Does anyone have an answer for this? How is the run-cache supposed to work in this case?

**Comment by peper0** [comment]
> Can you clarify how you ran into this bug, and how does it impact you?

@dberenbaum In practice, I observe that some runs are apparently not cached. Commands are run after each change of inputs, even if they were already run in the past for such inputs. It significantly increases the build time of the whole pipeline.

**Comment by dberenbaum** [comment]
TBH I'm not sure if the run cache should be enabled at all for non-deterministic stages. How do we decide which one to restore?

@iterative/dvc PTAL and add your thoughts.

**Comment by dberenbaum** [comment]
Hi @peper0, we had some internal discussion on this, so wanted to share and get your feedback:

> BTW, what is the reason to have multiple "values" for every "key" in the run cache? As I understand, we want to store more than one entry for one set of inputs of a given stage. Why?

It sounds like there wasn't really a great reason here and we would be open to making it a strict one-to-one pairing, but that's likely a more major and possible breaking change, so it's not something we can do right now.

We can instead restore the newest run cache entry, so that it basically always acts like that's the only one. Would that help?

**Comment by peper0** [comment]
> TBH I'm not sure if the run cache should be enabled at all for non-deterministic stages. How do we decide which one to restore?

IMO, if we accept it as a valid situation, then theoretically _any_ of the outputs is valid. In practice, they often differ in things that are meaningless for processing, e.g. creation timestamps (enabled in hdf5 by default), internal order of blocks etc.

However, in practice, it would be better IMO to use the last generated output (i.e. to overwrite data in the cache). It would help in situations when someone is continuously modifying the script during development and running it with `dvc repro --force`. Assuming she didn't push the cache to the remote before having the final version of the script, it would work correctly.

> We can instead restore the newest run cache entry, so that it basically always acts like that's the only one. Would that help?

Perfectly :) We could also push and pull only the newest entry, if possible.
