### ISSUE TITLE
`exp show`: provide executor information for finished experiments

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#9425]
The extension has a "Show Logs" command that user's can use to show the logs of experiments running in the queue. This uses `dvc queue logs <id> -f` under the hood. I would like to extend this functionality to show logs of completed/failed experiments. In order to do this I need some indicator that the experiment has available logs. 

To me it makes sense for the API to provide executor information for finished experiments but I am open to suggestions. I would like to avoid introducing calls to another CLI command if possible.

### Demo of show logs

https://user-images.githubusercontent.com/37993418/237017012-ba6f9a62-e24e-448e-959f-9e425ca61310.mov

**Comment by dberenbaum** [comment]
@pmrowla What are your thoughts?

**Comment by pmrowla** [comment]
This is doable, but it's not straightforward since we currently don't associate the task/executor information with finished experiments at all. It's probably a couple of days worth of work to fix in DVC

**Comment by dberenbaum** [comment]
@mattseddon I think it makes sense as part of a bigger epic on improving the logs. Added an epic in #9442 to discuss, but let me know if you think it's important to prioritize this as a standalone improvement.

**Comment by mattseddon** [comment]
https://github.com/iterative/vscode-dvc/issues/3178#issuecomment-1429990393 is related. This is the relevant part:

> I think it's important but complicated, and for now let's start with exposing the logs so at least people know what happened.

☝🏻 this is currently not possible. Does this bump the priority?

**Comment by dberenbaum** [comment]
@mattseddon Could you expand? Why isn't it possible?

**Comment by mattseddon** [comment]
> @mattseddon Could you expand? Why isn't it possible?

Without anything to indicate that the experiment was run in a temporary directory we don't know which experiments have "saved logs"and which don't.

**Comment by dberenbaum** [comment]
@mattseddon So if we save logs for workspace experiments, does it mean this issue becomes irrelevant? Trying to figure out if our time is better spent there.

**Comment by mattseddon** [comment]
> @mattseddon So if we save logs for workspace experiments, does it mean this issue becomes irrelevant? Trying to figure out if our time is better spent there.

Yep as long as there is a simple way to get to them. `dvc queue logs` doesn't seem appropriate (or like it would work) under those circumstances.

**Comment by dberenbaum** [comment]
> `dvc queue logs` doesn't seem appropriate

No it doesn't 😄 .

Now that we have dropped checkpoints, it might be worth revisiting [this discussion](https://github.com/iterative/dvc/discussions/8123) about whether we need a separate logs command. I think a lot of the need for it was about checkpoints, which are no longer supported.

**Comment by dberenbaum** [comment]
I guess we will never have logs for dvclive-only experiments, so there's probably no getting around having some way to know which experiments have logs.

**Comment by dberenbaum** [comment]
@mattseddon Sorry if we already discussed this and I forgot, but is it possible to use `dvc queue status` for this?

**Comment by mattseddon** [comment]
> @mattseddon Sorry if we already discussed this and I forgot, but is it possible to use `dvc queue status` for this?

We have talked about this a few times (but I couldn't find anything quickly on GH). Up until this point we've avoided adding that call. The main reasons are performance and not wanting to add to the Git locks issues.

**Comment by dberenbaum** [comment]
@pmrowla Does calling `dvc queue status` do any git operations or use the git lock?

**Comment by pmrowla** [comment]
No, it just queries the celery worker processes, it shouldn't be affecting git locks in either the workspace or the queued exp tempdirs

**Comment by mattseddon** [comment]
Discussed this in the cross-team meeting. Requirements to use `dvc queue status` would be that it would need to 

- have the same performance as `exp show` / ability to pass `--rev` flag for each commit we are currently showing
- ability to provide JSON output
- not take any of the DVC locks
- not interfere with the queue if it is called repeatedly

**Comment by mattseddon** [comment]
I'll follow up in the extension after the next release.
