### ISSUE TITLE
plots: fail silently on errors

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9441]
# Bug Report

## Description

`dvc plots show` has started failing silently when there are errors instead of reporting an error was found. It looks like this was introduced in https://github.com/iterative/dvc/commit/43195a806d690b65f9429b82444e48992b7442d9 (cc @skshetry).

### Reproduce

Clone https://github.com/iterative/vscode-dvc-demo and make these changes to `dvc.yaml`:

```
$ git diff
diff --git a/dvc.yaml b/dvc.yaml
index 3a4fa26..cd91913 100644
--- a/dvc.yaml
+++ b/dvc.yaml
@@ -2,8 +2,8 @@ plots:
   - Accuracy:
       x: step
       y:
-        training/plots/metrics/train/acc.tsv: acc
-        training/plots/metrics/test/acc.tsv: acc
+        training/plots/metrics/train/acc.tsv: train/acc
+        training/plots/metrics/test/acc.tsv: test/acc
       y_label: accuracy
   - Loss:
       x: step
```

Then run `dvc plots show`.

### Expected

Prior to this change, `dvc plots show` would return an error message like this:

```
$ dvc plots show
ERROR: Could not find provided field ('train/acc') in data fields ('step, acc').
```

**Comment by skshetry** [comment]
I think I did it in this way to fix https://github.com/iterative/dvc/issues/9025. 
Before we just used to fail, but now we reuse the same merged spec over multiple revisions data.

So, you may see multiple messages in this case if we logged them:
```console
$ dvc plots diff workspace $(git log --oneline --pretty=format:"%h" -n2)
WARNING: Could not find provided field ('acc/loss') in data fields ('step, loss').                                                                                                                                   
WARNING: Could not find provided field ('acc/loss') in data fields ('step, loss').
WARNING: Could not find provided field ('acc/loss') in data fields ('step, loss').
```

**Comment by dberenbaum** [comment]
Makes sense for `diff` but what about for `show`?
