### ISSUE TITLE
A feature to pruge old/unimportant data from DVC history to free up cloud storage space

### ISSUE THREAD

**Issue by sreevatsank1999** [iterative/dvc#9451]
I want to be able to purge old/unimportant data from DVC history to free up cloud storage. I want to be able to tag specific points in my git history that I deem to be important and only retain data associated with those git commits. 

An example of data that is unimportant is when:
 1. Dataset is generated/added but never used to train any ML model with that data. 
 2. Dataset is later determined to be flawed/incorrectly generated and the dataset is no longer needed, but was at the time tracked and used to train models.
  3. Single-use datasets, i.e. data that is needed for experimentation and testing at the moment but may not be required later.
 
 
It will be nice to have some sort of mechanism to set cloud storage usage quotas and auto-purge settings for data that is old and not tagged as important. 

A feature like this could result in some points in the git history referencing deleted data which I think is fine, as the data was not deemed important enough to tag/preserve.

**Comment by dberenbaum** [comment]
> It will be nice to have some sort of mechanism to set cloud storage usage quotas and auto-purge settings for data that is old and not tagged as important.

This might also be related to https://github.com/iterative/studio-support/issues/67, so you could set some auto-purge policy. The Studio UI might also be a simpler way to "star" particular commits and files that you want to keep or purge.

**Comment by sreevatsank1999** [comment]
Thank you very much. I think `--cloud` is the feature that I was looking for.
