### ISSUE TITLE
top-level params and metrics: support directories

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9452]
Top-level params and metrics now support only files, but like plots, it would be helpful to also support directories.  See https://github.com/iterative/dvc/issues/7224#issuecomment-1547773408.

**Comment by daavoo** [comment]
I think the `metrics` directory support also makes sense at the stage level.

This should be a simple thing to implement (unless I am missing something) because the collection already supports directories via the `recursive` flag (https://dvc.org/doc/command-reference/metrics/show#-R)

**Comment by dberenbaum** [comment]
Looks to be related/duplicate of #2973.
