### ISSUE TITLE
Add mechanism to pull a single stage

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#9467]
See https://github.com/iterative/dvc/pull/9434#discussion_r1195129947

**Comment by daavoo** [comment]
Could be something like `Stage.pull` with options to decide on `deps` and/or `outs`.

**Comment by skshetry** [comment]
No, we want an internal API that has less surface area and you can see the reasoning in linked comment above.

**Comment by skshetry** [comment]
Closing as not planned.
