### ISSUE TITLE
DVC causes pytest errors

### ISSUE THREAD

**Issue by Ostyk** [iterative/dvc#9468]
# Bug Report

## DVC causes pytest errors

Hi, we've been using DVC for quite sometime in our pipeline and it's been running with the same versions for quite some time very smoothly. However, suddenly about an hour ago on our CI/CD it came into conflict with pytest

Has anyone ran into the same issue by any chance?

## Description
```
File "/home/ubuntu/repos/vision_pipeline/env/lib/python3.9/site-packages/dvc/testing/benchmarks/fixtures.py", line 10, in <module>
    from pytest_virtualenv import VirtualEnv
ModuleNotFoundError: No module named 'pytest_virtualenv'
```

### Reproduce

At first I thought it's an issue with pytest. However, you can easily reproduce it by installing a clean env with pytest (works) and with pytest and dvc (fails).

`python3 -m pytest`

#### python 3.9.14/15/16 (it worked as normal until an hour ago)
```
python3 -m venv env
source env/bin/activate
pip3 install pytest
pip3 install dvc

python3 -m pytest
```

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.57.0 (pip)
-------------------------
Platform: Python 3.9.15 on Linux-5.15.0-1022-aws-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.51.0
        dvc_objects = 0.22.0
        dvc_render = 0.5.2
        dvc_task = 0.2.1
        scmrepo = 1.0.3
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.5.0, boto3 = 1.26.76)
Config:
        Global: /home/ubuntu/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p1
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p1
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/ae02cd0917fa33dee1478a0600423a1e
```

**Additional Information (if any):**

**Comment by daavoo** [comment]
Hi @Ostyk , thanks for the report. 

We have identified the problem and taking a look. It is coming from https://github.com/iterative/dvc/pull/9383 .

As a current workaround, you can pass `-p no:dvc-testing` to pytets
