### ISSUE TITLE
`exp show`: experiment order randomly changing

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#9504]
# Bug Report

## Description

When calling `exp show` multiple times the order of experiments can change between calls (no sorts applied):

https://github.com/iterative/dvc/assets/37993418/7ca95c89-907a-438c-ae10-343c19c9f50d

### Reproduce

1. queue several experiments
2. start the queue with multiple workers
3. monitor exp show

### Expected

Experiments order is static unless sorts are applied.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.58.1 (pip)
-------------------------
Platform: Python 3.10.6 on macOS-13.3.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.51.0
        dvc_objects = 0.22.0
        dvc_render = 0.5.0
        dvc_task = 0.2.1
        scmrepo = 1.0.3
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.5.0, boto3 = 1.26.76)
Config:
        Global: /Users/mattseddon/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/9b2d1355ef26cb2a38a704c54d1f3710
```

**Additional Information (if any):**

Noticed while integrating https://github.com/iterative/dvc/pull/9432 with the extension (for https://github.com/iterative/vscode-dvc/issues/3436 & https://github.com/iterative/vscode-dvc/issues/3178)

**Comment by pmrowla** [comment]
Discussed this in slack, the issue is probably due to (lack of) git commit timestamp precision. The default sort is chronological by git timestamp, there may be a way to get more consistent ordering but I don't think it needs to be prioritized

**Comment by omesser** [comment]
@mattseddon - tried a very simple fix in: https://github.com/omesser/dvc/tree/stable_exp_sorting
Can you please check if this fixes the issue?

**Comment by mattseddon** [comment]
> @mattseddon - tried a very simple fix in: https://github.com/omesser/dvc/tree/stable_exp_sorting Can you please check if this fixes the issue?

That does seem like it worked. Did you add the commit/name to the default order?
