### ISSUE TITLE
status: add `missing` to local workspace status

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9532]
In https://dvc.org/doc/command-reference/status#local-workspace-status, a dep or out can be in the following states:

>  - new: An output is found in the workspace, but there is no corresponding file hash saved in the [dvc.lock](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#dvclock-file) or [.dvc](https://dvc.org/doc/user-guide/project-structure/dvc-files) file yet.
>  - modified: An output or dependency is found in the workspace, but the corresponding file hash in the [dvc.lock](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#dvclock-file) or [.dvc](https://dvc.org/doc/user-guide/project-structure/dvc-files) file is not up to date.
>  - deleted: The output or dependency is referenced in a [dvc.lock](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#dvclock-file) or [.dvc](https://dvc.org/doc/user-guide/project-structure/dvc-files) file, but does not exist in the workspace.
> - not in cache: An output exists in the workspace, and the corresponding file hash in the [dvc.lock](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#dvclock-file) or [.dvc](https://dvc.org/doc/user-guide/project-structure/dvc-files) file is up to date, but there is no corresponding cache file or directory.

If the dep/out is deleted and missing from the cache, can dvc report it as `missing` rather than `deleted`? The most common scenario is when data has not yet been pulled, and `deleted` is misleading.

Related:
* https://github.com/iterative/dvc/issues/8327
* https://github.com/iterative/dvc/issues/9530

**Comment by dberenbaum** [comment]
@daavoo Let me know what you think about this as you work on #9530. Since it would be a breaking change, it might be worth considering doing this (and maybe #8327) now.

**Comment by shcheklein** [comment]
A thing to consider - how will it look like in the VS Code interface when someone actually deletes a file. I think now it's designated / marked as "D" similar to Git, and "M" stands for modified. Will we need to change those marks as well? Will it confuse people even more? (No easy answer here - clearly two use cases that are not easy to disambiguate 🤔 )

**Comment by dberenbaum** [comment]
> how will it look like in the VS Code interface when someone actually deletes a file.

Would you want to change the mark for the deleted files or the ones with the new "missing" status? I think `D` for actually deleted files is much more in line with what people expect (I can't find now but recall people asking in both CLI and VS Code for why everything shows as deleted when they clone/don't pull). I don't think there's a Git analog for "missing" and we could come up with something else for that (agree that it's not ideal that it starts with `M`).

@mattseddon Have you heard about it from users? What's your take?

**Comment by mattseddon** [comment]
We can only display one status (badge + decoration) per file. Under the above circumstances we show NC + `.gitignored` decoration to encourage the user to `dvc pull`. The SCM tree looks like this:

<img width="1728" alt="image" src="https://github.com/iterative/dvc/assets/37993418/983154de-899f-418a-8833-f57b446a7045">

The files are duplicated under the "Uncommitted" and "Not In Cache" groups. 

It would be good to make this more intuitive/less complicated. 

I do feel like we should still have to explain exactly what "Missing" (or any other term) means. My $0.02 is that we need some succinct way of explaining that there is no local copy of the file/directory but there probably is one on the remote.

**Comment by dberenbaum** [comment]
> I do feel like we should still have to explain exactly what "Missing" (or any other term) means. My $0.02 is that we need some succinct way of explaining that there is no local copy of the file/directory but there probably is one on the remote.

What do you think of "Not Pulled"?

**Comment by mattseddon** [comment]
> What do you think of "Not Pulled"?

I think it is fine. Would "not pulled" co-exist with "not in cache"? We could still end up with the files missing on the remote. Could we use the missing status then?... it gets complicated fast.
