### ISSUE TITLE
dvc import: apostrophe breaks import

### ISSUE THREAD

**Issue by alexpavlidespyrra** [iterative/dvc#9539]
# Bug Report

## Description

DVC push doesn't check file names for issues, but complains when trying to import that data. The error was also a little cryptic "sqlite3.OperationalError: near "s": syntax error", however I guessed that it was something to do with the filenames containing apostrophes ("'s"). Once files with apostrophes in their filename were removed I was able to import. 

### Reproduce
Push some data to an S3 bucket with a filename like alex's-issue.jpg and then try and import with `dvc import`

### Expected

I would expect if I can push data using DVC that I will be able to pull/import that data without issues. 

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.58.2 (pip)
-------------------------
Platform: Python 3.8.16 on Linux-5.15.0-1033-aws-x86_64-with-glibc2.35
Subprojects:
	dvc_data = 0.51.0
	dvc_objects = 0.22.0
	dvc_render = 0.5.3
	dvc_task = 0.2.1
	scmrepo = 1.0.3
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.5.0, boto3 = 1.26.76)
Config:
	Global: /root/.config/dvc
	System: /etc/xdg/dvc
Cache types: symlink
Cache directory: ext4 on /dev/root
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/root
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/594ea283c7c9112590dff602ca4ff7f6
```

**Additional Information (if any):**

**Comment by daavoo** [comment]
This is a bug in https://github.com/iterative/sqltrie which is not escaping the filenames containing `'`
