### ISSUE TITLE
boto3 dependency

### ISSUE THREAD

**Issue by wardvl-ixor** [iterative/dvc#954]
Hi,

Is it possible that boto3 is not automatically installed in pip install dvc?
when using dvc for the first time, dvc pull will give the error "url should evaluate to True", which is fixed after pip install boto3.

Thanks and regards from Belgium!

**Comment by efiop** [comment]
Hi @wardvl-ixor !

Boto3, google-cloud-storage, etc are indeed not installed by default when you call `pip install dvc` to avoid unnecessary dependencies. To install all dependencies use `pip install dvc[all]`.

Let's keep this issue open, I'll send a patch soon to output a better error msg that will have an instructions on what to do if such situation with dependencies occurs.

Thanks,
Ruslan
