### ISSUE TITLE
`exp show`: `--json` does not respect the `--only-changed` flag

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#9544]
# Bug Report

## Description

Passing the `--only-changed` flag to `exp show` has no effect when provided in conjunction with `--json` .

Example:

`params.yaml`:
```yaml
lr: 0.003
weight_decay: 0
epochs: 15

```

`dvc exp show --only-changed ` yields (unchanged parameters `weight_decay` & `epochs` excluded):

<img width="967" alt="image" src="https://github.com/iterative/dvc/assets/37993418/ac7d5c77-4ef1-43d7-9c6b-d779511643af">

and `dvc exp show --only-changed --json` (unchanged parameters `weight_decay` & `epochs` included for all records):

```json
[{
    "rev": "workspace",
    "name": null,
    "data": {
      "rev": "workspace",
      "timestamp": null,
      "params": {
        "params.yaml": {
          "data": { "lr": 0.003, "weight_decay": 0, "epochs": 15 }
        }
      },
      ....
```

### Reproduce

1. run `dvc exp show --only-changed` (get expected results)
2. run `dvc exp show --only-changed --json` (get all unchanged columns)

### Expected

Same behaviour with and without the `--json` flag.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.58.1 (pip)
-------------------------
Platform: Python 3.10.6 on macOS-13.3.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.51.0
        dvc_objects = 0.22.0
        dvc_render = 0.5.0
        dvc_task = 0.2.1
        scmrepo = 1.0.3
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.5.0, boto3 = 1.26.76)
Config:
        Global: /Users/mattseddon/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/9b2d1355ef26cb2a38a704c54d1f3710
```

**Additional Information (if any):**

This is relevant for https://github.com/iterative/vscode-dvc/issues/1994 which should be straightforward to implement (in time for 3.0) if this bug gets fixed.

**Comment by mattseddon** [comment]
Might not be a priority but thought that I would raise it in case we wanted a version of https://github.com/iterative/vscode-dvc/issues/1994 implemented in time for 3.0.

**Comment by daavoo** [comment]
This is expected behavior but I guess it was not clear enough. 

The logic is applied once the raw results (internal `repo.experiments.show()`) have been converted to a table, similar to other flags like `--drop`, `--kep`, `--sort`.

**Comment by dberenbaum** [comment]
Agreed it seems like it would be nice @mattseddon.

For whatever flags we ignore, let's mention that in the `--json` docs.

**Comment by dberenbaum** [comment]
@mattseddon Let's discuss next meeting whether we want to prioritize showing only changed columns.

A quick look tells me that it's unfortunately not straightforward to do ☹️

**Comment by mattseddon** [comment]
Turns out this isn't that difficult to do in the extension.
