### ISSUE TITLE
Question: How to approach running same pipeline with different parameters.

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#956]
Hi guys, I have been using DVC for a while and I'm really excited about it! I have a general question if you have a minute.

How would you approach running the same pipeline again, with different parameters (input file, model hyperparameters, etc.) if you want to be able to compare the two pipelines? 

- Create a new branch, replace the parameters in the original DVC file, reproduce pipeline. Very simple, but the disadvantage is that 
  1) I have to switch between branches to be able to open the output files 
  2) I cannot open the two versions at the same time (without cloning the repo twice) 
  3) since I won't have both of the alternatives in a single (master) branch, it's hard to reproduce both pipelines again in the future if I change a common dependency - for example after fixing a bug in a script, I would have to apply the fix to both branches

- Copy the pipeline into a new directory, replace the parameters in the copied DVC file, reproduce pipeline. The disadvantage is that the number of files is increasing rapidly with each version.

- Define the whole pipeline with a script that executes `dvc run` for each of the stages. For example, I would run `./build_validate.sh modelParams.json trainingFiles/ outputPath/` which would generate all the files and the DVC stage files with dynamically assigned filenames based on the parameters. But this takes a lot of extra work and it seems redundant if DVC can already manage pipelines.

I appreciate any input.

Cheers,
David

**Comment by efiop** [comment]
Hi David!

How do the outputs you are comparing look like? If it is something that can be viewed in a simple text format (e.g. raw text, json, csv, tsv, etc), you could consider to go with the "create branch" approach and utilize `dvc metrics` to show and compare the outputs for the different branches. Here is a small doc describing how to use it: https://dvc.org/doc/commands-reference/metrics . Would that suit you?

Thanks,
Ruslan

**Comment by prihoda** [comment]
Thanks, I missed the --all-branches option, that's a perfect match for this scenario 👍

I also have some PNG files showing the output plots. I will consider creating a jupyter notebook that will read all the outputs from the current branch and show them in one place. Then I can generate PDFs, which should make it easier to compare all the branches at the same time.

I will close this issue now but if you have any more ideas, please feel free to leave a comment.

Cheers,
David
