### ISSUE TITLE
push/pull: slow

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9575]
Got report that push/pull is scanning the entire remote on a fresh vm and taking too long. Need to take a closer look and try to reproduce.

**Comment by efiop** [comment]
@dberenbaum Any additional details? Regular remotes, cloud versioning, etc?

**Comment by dberenbaum** [comment]
s3 regular remote AFAIK

**Comment by dberenbaum** [comment]
@efiop What would be most helpful here? Should I ask them to run a profiler? Or maybe I should just try to put you in touch with them to debug?

**Comment by efiop** [comment]
@dberenbaum Some basic info would be great to start with. But happy to get in touch and ask directly, if that's an option.

**Comment by dberenbaum** [comment]
s3 afaik

**Comment by efiop** [comment]
@dberenbaum Any new info on this? Just making sure I didn't miss it anywhere.

**Comment by efiop** [comment]
@dberenbaum Let's close this then? There is no info here at all and this issue is kinda useless at this point.

**Comment by dberenbaum** [comment]
Okay, closing until I can get more details
