### ISSUE TITLE
DVC install is not silent with the innosetup default silent flags

### ISSUE THREAD

**Issue by superusercode** [iterative/dvc#9582]
Per https://github.com/microsoft/winget-pkgs/pull/109459#pullrequestreview-1473842718 there si a popup message that is not automatically dismissed when the silent flags are used, preventing this program from being added to winget.

**Comment by efiop** [comment]
Looks like we are missing a check for `WizardSilent` in https://github.com/iterative/dvc/blob/main/scripts/innosetup/setup.iss or in `addsymlink.iss` nearby.  Would you be interested in contributing a fix?

**Comment by skshetry** [comment]
@superusercode, how does update work in winget? Is it automated?
