### ISSUE TITLE
`dvc stage add --group` Create Groups of stages

### ISSUE THREAD

**Issue by PythonFZ** [iterative/dvc#9586]
# `dvc stage add --group`
I'd suggest adding:

```python
dvc stage add --group Grp1
dvc stage add --group Grp2
```
where groups can also be targeted via `dvc repro Grp1` or similar.

# Examples

Assume two developers  working on a project like the following leading to one final Model in the end.
Currently one would run `dvc repro Grp1_Evalulate1 Grp_Evaluate2` which could be replaced by a single `dvc repro Grp1`.
Futhermore, visualisations such as `dvc dag --mermaid` could be improved by grouping stages together

```mermaid
flowchart LR
    Data --> Grp1_Model
    Data --> Grp2_Model

    subgraph Grp1
        Grp1_Model --> Grp1_Evaluate1
        Grp1_Model --> Grp1_Evaluate2
    end

    subgraph Grp2
        Grp2_Model --> Grp2_Evaluate1
        Grp2_Model --> Grp2_Evaluate2
    end

    Grp1_Model --> EnsembleModel
    Grp2_Model --> EnsembleModel
```

related issues I found:
- https://github.com/iterative/dvc/issues/4118

**Comment by skshetry** [comment]
DVC supports globbing in repro for stages: 

```console
dvc repro grp*
```

It's not clear to me what other benefits a group has.

**Comment by PythonFZ** [comment]
@skshetry I did not know, this was possible.
Better organisation of Nodes, if you have plenty of them would be the only remaining benefit I can see.

**Comment by skshetry** [comment]
I forgot to add `--glob` in above command. That is still needed.
