### ISSUE TITLE
params: collect only stage params/separate top-level params

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9588]
See https://github.com/iterative/vscode-dvc/issues/4088 and https://github.com/iterative/studio/issues/5837.

VS Code and Studio give users the option to run experiments by modifying parameters, and their input forms include dvclive-tracked top-level params that aren't associated with the pipeline and at best have no effect on the experiment. DVC needs some mechanism for them to collect only those params that are part of the pipeline so they don't erroneously show these top-level params.

**Comment by dberenbaum** [comment]
@daavoo Not sure it's working as expected. Using example-get-started-experiments, I still see params from `results/train/params.yaml` with `dvc exp show --param-deps`.

Then I think we would also need to make sure to respect the flag when using `--json`, right?

**Comment by daavoo** [comment]
> Using example-get-started-experiments, I still see params from results/train/params.yaml with dvc exp show --param-deps.

This is a bug, IMO, because top-level params are not respecting `params-deps` flag. 

> Then I think we would also need to make sure to respect the flag when using --json, right?

It is currently respected, unless I am missing something

**Comment by mattseddon** [comment]
I get the same error as shown in https://github.com/iterative/dvc/issues/9565 when I use `--params-deps` and `--json` in both `vscode-dvc-demo` & `example-get-started-experiments`:

```
dvc exp show --param-deps --json
ERROR: unexpected error - first argument must be callable or None

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

```
dvc doctor                                                                                                               ✘ 255  .env  base 21:00:48
DVC version: 3.0.0 (pip)
------------------------
Platform: Python 3.10.10 on macOS-13.4-arm64-arm-64bit
Subprojects:
        dvc_data = 1.11.0
        dvc_objects = 0.23.0
        dvc_render = 0.5.0
        dvc_task = 0.3.0
        scmrepo = 1.0.3
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
        Global: /Users/mattseddon/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink 
Cache directory: apfs on /dev/disk3s1s1 
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/9b2d1355ef26cb2a38a704c54d1f3710
```

**Comment by dberenbaum** [comment]
@mattseddon If `dvc exp show --param-deps --json` were working as expected, is it enough?

**Comment by mattseddon** [comment]
I think it should be enough 👍🏻.

**Comment by dberenbaum** [comment]
So the only action item here is to make `dvc exp show --param-deps` ignore top-level params.

**Comment by dberenbaum** [comment]
Need to look more into how it can be resolved in Studio (needs params show to know which are top-level)

**Comment by skshetry** [comment]
@dberenbaum @daavoo, what's the requirement here for the Studio (other than `exp show` issue)?

**Comment by daavoo** [comment]
> @dberenbaum @daavoo, what's the requirement here for the Studio (other than `exp show` issue)?

To have a signal differentiating between param deps and top-level params so we can prevent showing top-level params in the form used to submit experiments.

**Comment by skshetry** [comment]
It's not always clear. We allow declaring paths on both top-level and param deps, so they might have multiple sources.

**Comment by skshetry** [comment]
> Can we clearly differentiate which are deps and which are not ( I assume yes)? That covers the use case, sorry for unclear forumlation

The parameters' dependencies are granular, so an ideal solution would be for Studio to collect themselves (or, I can provide an internal function that does this).

```python
deps_params = {
    relpath(param.fs_path, repo.root_dir): param.read_file()
    for param in repo.index.params
}
# Additionally read `params.yaml` file if need
```

I can provide a result in the format of `{error: Exc, data: ..., dep: bool}`, which will be equivalent to what ` dvc params diff --deps` does.

But if granularity is required, I'm afraid that won't be simple. We'll add a lot of complexity in generating `dep` properly, and similarly, it'll have to be processed on Studio side which won't be simple as well.

So I'd push for using the above snippet in Studio for this. But again, I'm happy to provide 
`dep: bool` signal in the result (but requires invalidating `exp show` cache, not a big deal on itself though).

**Comment by dberenbaum** [comment]
Lowering the priority since it sounds complex to implement and have not heard people asking about it
