### ISSUE TITLE
Unit-test coverage drop

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#959]
From 92% to 81%.

It looks like a test-environment issue.

**Comment by dmpetrov** [comment]
It might be just an issue with the widget.

Also "Travis" and "Windows Build" widgets do not work.

**Comment by efiop** [comment]
Is it running on your local environment? If so, there are a few reasons:

1) You don't have your aws/azure/gcp/ssh/hdfs creds setup, so those parts of code are not covered on your machine;
2) You can't test windows/linux/macos at the same time, so some parts of the code are not covered on your machine;

You can easily identify which tests didn't run by looking grep-ing SKIP in your test logs. We should probably list required test creds in our docs to enable Our CI is setup to test everything on every os with every remote driver. 

> Also "Travis" and "Windows Build" widgets do not work.

They work through the shields.io and sometimes when the load is too high they indeed don't show up. We can switch back to stock if you want.

**Comment by dmpetrov** [comment]
81% was a value on the widget, not my local environment. 

Is there a way to mitigate the windows issue? It does not look good on the readme page.

**Comment by efiop** [comment]
> 81% was a value on the widget, not my local environment.

I see. The testing was pending, that is all. It is updated when other tests are done running.

> Is there a way to mitigate the windows issue? It does not look good on the readme page.

We use shields.io for *nix too. Simple page reloading usually helps :) It is not that common, but sure, lets just switch to the stock plucks.

**Comment by efiop** [comment]
Added stock plucks back https://github.com/iterative/dvc/commit/1bfcc12853fab6417508881106eada9d3ae7e917
