### ISSUE TITLE
exp push: default to `--rev HEAD`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9595]
Let's make `dvc exp push origin` push all experiments derived from the HEAD revision by default. This is especially useful in CI, where it's common to want to push the latest experiment and `dvc exp push origin --rev HEAD` feels like it's too complicated.

See discussion in https://iterativeai.slack.com/archives/C01116VLT7D/p1686321601633079.

**Comment by shcheklein** [comment]
Also, `dvc exp push origin --rev HEAD` seems to be not working on CI. I didn't manage to make it work the last time I tried (I didn't have enough time unfortunately). It comes down to the supported E2E scenarios and making sure that they are not broken / fairly simple to use.

**Comment by dberenbaum** [comment]
@shcheklein Added a separate ticket to discuss the more general problem.

**Comment by shcheklein** [comment]
@dberenbaum thanks a lot for moving forward this quickly! qq - do we plan to also make `origin` a default (similar to Git)?

**Comment by dberenbaum** [comment]
No, we discussed (and have [discussed](https://github.com/iterative/dvc/discussions/6427) before) but decided not to for now for a few reasons:

1. Breaking change (because it's a positional arg, `origin` would be misread as an exp name) - CI/scripts will break, and Studio and VS Code need to coordinate this change
2. [Potentially confusing behavior for what remote to track](https://github.com/iterative/dvc/pull/6332#discussion_r680291425)
3. Consistency with git (without upstream tracking branch, git will similarly fail)
4. Consistency with `dvc exp list`
5. Doesn't feel as painful as `--rev HEAD`
6. Bias towards explicit over implicit
