### ISSUE TITLE
api: support config for params_show/exp_show/metrics_show

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#9613]
Related 
https://github.com/iterative/dvc/issues/9154
https://github.com/iterative/dvc/issues/9610

**Comment by dberenbaum** [comment]
@efiop Do you plan to work on it or just noting it as a possible follow up? Doesn't feel like a priority unless I'm missing something.

**Comment by efiop** [comment]
@dberenbaum It is a few oneliners with the most complications in the docstrings. I have it around already, will cleanup docstrings in the morning and will send it off. Just for the sake of completeness in api department.
