### ISSUE TITLE
plots show: plots outputs in stages are also included

### ISSUE THREAD

**Issue by ZhiliangWu** [iterative/dvc#9637]
# Bug Report

## Description

> plots show: Generate [plot](https://dvc.org/doc/command-reference/plots) from a plots file or plots [top-level definition](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#plots) from [dvc.yaml](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files)

IIUC, only plots within the top-level definition should be included. 

Meanwhile,  when we include the entry [`plots`](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#metrics-and-plots-outputs) in stages within a [`dvc.yaml`](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#dvcyaml) file. It is also (unexpectedly) included in the plots generated by [`dvc plots show`](https://dvc.org/doc/command-reference/plots/show#plots-show). Taking the data from [`dvc plots show`](https://dvc.org/doc/command-reference/plots/show#multiple-data-series-plot) as an example, we would have the following:
![image](https://github.com/iterative/dvc/assets/18686697/7b300011-c680-472d-8e48-5cad7dfdf097)

### Reproduce

```console
$ git init
$ dvc init
$ mkdir plots
# create a file called training_data.csv as following
$ cat training_data.csv
epoch,train_loss,test_loss
1,0.33,0.4
2,0.3,0.28
3,0.2,0.25
4,0.1,0.23
# create a dvc.yaml file as following
$ cat dvc.yaml
stages:
  save_plots:
    cmd: cp training_data.csv plots/data.csv
    deps:
      - training_data.csv
    plots:
      - plots/data.csv

plots:
  - test_vs_train_loss:
      x: epoch
      y:
        training_data.csv: [test_loss, train_loss]
      title: Compare loss training versus test
$ dvc repro
$ dvc plots show
# open the `index.html` under `dvc_plots` in browser
```

### Expected

![image](https://github.com/iterative/dvc/assets/18686697/d687ca35-8374-4925-b554-f8c7776d5025)

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.1.0 (pip)
------------------------
Platform: Python 3.9.1 on macOS-13.4-arm64-arm-64bit
Subprojects:
        dvc_data = 2.0.2
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Config:
        Global: /Users/********/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/f721df5afaec997dbd784bbc2e2854db
```

**Additional Information (if any):**

**Comment by dberenbaum** [comment]
Sorry, I think we need to explain it better in the help text. It is expected that it will show all plots, whether they are defined at the top level or inside a stage. Could you explain why you would like to define a plot inside your stage but have `dvc plots` commands ignore it? Maybe you want to change them to regular `outs` instead of `plots`, in which case they won't show up when you run `dvc plots show`?

**Comment by ZhiliangWu** [comment]
> Sorry, I think we need to explain it better in the help text. It is expected that it will show all plots, whether they are defined at the top level or inside a stage. Could you explain why you would like to define a plot inside your stage but have `dvc plots` commands ignore it? Maybe you want to change them to regular `outs` instead of `plots`, in which case they won't show up when you run `dvc plots show`?

Thanks for your quick reply. 

If including plots from all levels are included, then the documentation of the [`plots show`](https://dvc.org/doc/command-reference/plots/show) is misleading as it even points to 

> plots [top-level definition](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#plots) from [dvc.yaml](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files)

Putting different output artefacts into `outs:`, `metrics:`, `plots:` helps me to better group the expected outputs. Meanwhile, as the plots under stages are not customizable with things like `title`, `x_label`, etc., I didn't expect it to see them in the generated file.

**Comment by dberenbaum** [comment]
The poor wording in the docs is meant to indicate that it can reference any kind of plots:

1. A plots file in any part of `dvc.yaml` (at the top or inside a stage)
2. A _non-file_ plots definition (which is only valid in the top level)
3. Any arbitrary file, even if it's not referenced in `dvc.yaml` (you can run `dvc plots show` on any random file if you want)

I submitted a pull request for the docs to clarify in https://github.com/iterative/dvc.org/pull/4643. Feel free to comment with any suggestions on the wording.
