### ISSUE TITLE
dvc checkout with ref

### ISSUE THREAD

**Issue by lainisourgod** [iterative/dvc#9644]
Hi! I had a usecase that I wanted to bring in the current state of repo state of the dvc-tracked dataset I used 3 months ago. I wanted to do it to check out how will my current code perform on the data I was using then.

I guess this should be allowed with command like `dvc checkout dataset.pq.dvc the-old-commit`. Inside, dvc can do `git show the-old-commit:dataset.pq.dvc` to get the hash of the file we need and bring it into workspace. Note that my git state doesn't change during these operations as I only want to bring the dataset, not all the other code.

**Comment by pmrowla** [comment]
You can do this with git + DVC using
```
git checkout the-old-commit -- dataset.pq.dvc
dvc checkout dataset.pq.dvc
```

This will git-checkout the specific version of the `.dvc` file you want (but leave the rest of your git repo alone), and then do the DVC checkout to get the specific version of the dataset you are looking for

**Comment by lainisourgod** [comment]
@pmrowla actually I just realized it too. Thanks for claryfiying!

Maybe I'm not the only one to encounter this usecase, and so we could add it to dvc checkout examples page in docs? https://dvc.org/doc/command-reference/checkout#example-specific-files-or-directories
