### ISSUE TITLE
dvc status: --verify

### ISSUE THREAD

**Issue by bardsleypt** [iterative/dvc#9652]
We ran into an issue where a local cache became corrupted (it pulled a partial file), but since the file was tracked via a .dir file, the output of 'dvc status' showed there was no issue (see https://github.com/iterative/dvc/issues/9641). This was essentially because we did not force a local re-hash of the files using the 'verify = true' option for our remote config. 

In any case, many on my team have expressed desire for a forced-rehash of the local workspace, as a manual check to ensure this type of data corruption does not happen. Something to the effect of
```
dvc status --verify
```
or some other flag, possibly with options for level of rehash (similar to `gc` with workspace, all branches, etc.).

**Comment by efiop** [comment]
@bardsleypt Hm, what remote was it? Corrupted cache shouldn't usually happen, especially not during transfer from remote.

Regarding `--verify`, i think we will have `dvc cache check` instead https://github.com/iterative/dvc/issues/9561

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/9561 for now.

**Comment by bardsleypt** [comment]
`dvc cache check` works for me, `--verify` was merely a suggestion. Thanks!
