### ISSUE TITLE
Suspected incompatibility with flufl.lock==8

### ISSUE THREAD

**Issue by hugo-ricateau** [iterative/dvc#9654]
## Description

`open` from Python API fails with a
```
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flufl.lock>=5' distribution was not found and is required by dvc
```
when `flufl-lock` is installed in version `==8.0` (that has been released a fee hours ago). The exact same setup was perfectly working with `flufl-lock==7.1`.

### Reproduce

I don't have a MNWE yet, but I suspect the problem to be very generic; if you'r unable to reproduce I'll invest the time to determine minimal reproductible steps.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.2.0 (pip)
------------------------
Platform: Python 3.9.16 on macOS-13.4-arm64-arm-64bit
Subprojects:
	dvc_data = 2.3.0
	dvc_objects = 0.23.0
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.0.4
Supports:
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
	ssh (sshfs = 2022.6.0)
Config:
	Global: /Users/Work/Library/Application Support/dvc
	System: /Library/Application Support/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Comment by efiop** [comment]
@hugo-ricateau Are you still able to reproduce it? Could you show `pip freeze | grep flufl`, please? The error seems to say that there is no flufl-lock at all. I can see that our CI succeeded with 8.0, hence me wondering if maybe you just didn't have it installed or you had an older version installed by some other dependency.

**Comment by drasmuss** [comment]
We're seeing the same error (`pkg_resources.DistributionNotFound: The 'flufl.lock>=5' distribution was not found and is required by dvc`). Installing `flufl.lock<8.0` fixes it for us.

**Comment by hugo-ricateau** [comment]
I'm still investigating to produce a MNWE, but I have strong suspicions that the problem is not actually coming from DVC, but from the ([deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html)) `pkg_resources` package.

**Comment by skshetry** [comment]
@hugo-ricateau, do you have a full traceback?

**Comment by ZohoHari** [comment]
I am also facing the same issue, When updating lock with verbose, I found that it is running indefinitely for `flufl-lock` when trying to resolve for `dvc` with version `flufl-lock==8.0.1`.

Snippet of the output: 
```
   ...
   1: selecting flufl-lock (8.0.1)
   1: fact: flufl-lock (8.0.1) depends on atpublic (*)
   1: fact: flufl-lock (8.0.1) depends on psutil (*)
   ...
```

As mentioned in the comments, I tried adding `flufl-lock < 8.0` to the poetry, but it fails to add it, when trying to resolve.
I have attached the screenshot of the terminal output here for reference
![image](https://github.com/iterative/dvc/assets/135852136/84be547d-e08c-4696-84f9-72f93b431956)


# Environment Information

### Output of `dvc doctor` : 
![image](https://github.com/iterative/dvc/assets/135852136/2386a696-2711-4806-9d5e-ba749bedf915)

**Comment by efiop** [comment]
Looks like flufl switched to pdm in 8.0 https://gitlab.com/warsaw/flufl.lock/-/commit/3393166de048ac698a280c106f579b99ed7d0a1e, probably something is triggering this because of that. Also ran into this today 🙁  Can't put my finger on anything specific right now, will probably just limit flufl to <8
