### ISSUE TITLE
api/cli: introduce remote_config

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#9656]
We already have `config` as the most powerful option, but `remote_config` would be convenient in most cases. As a start, it is fine to only make it set the default remote's config and not care about per-output remotes (one could use `config` if he needs to tweak that).

e.g. this will merge {"passphrase": "mypass"} with the default remote's config

```
with dvc.api.open(url, path, remote_config={"passphrase": "mypass"}):
....
```

this will set default remote to `myremote` and then merge {"passphrase": "mypass"} with `myremote`s remote's config

```
with dvc.api.open(url, path, remote="myremote", remote_config={"passphrase": "mypass"}):
....
```

**Comment by dberenbaum** [comment]
Let's use the same format as `dvc exp run --set-param key=val`

**Comment by efiop** [comment]
@dberenbaum You probably mean `--remote-config` for CLI, right? In api we can just pass a dict.
