### ISSUE TITLE
[Bug] Unexpected error: No module named concurrent.futures on python 2.7 

### ISSUE THREAD

**Issue by vfdev-5** [iterative/dvc#967]
How to reproduce:
```
python --version
> Python 2.7.12
pip install --user dvc
cd dataset && dvc init
> Unexpected error: No module named concurrent.futures
```
There is a missing dependency on python 2.7: `futures`. To install it:
```
pip install futures
```
and `dvc init` works

**Comment by efiop** [comment]
Hi @vfdev-5 !

Nice catch! Already merged the fix for it. It will be released with a new version later today.

Thanks,
Ruslan
