### ISSUE TITLE
add: Cached output(s) outside of DVC project

### ISSUE THREAD

**Issue by auroraRag** [iterative/dvc#9697]
# Bug Report

## Description

i followed this https://dvc.org/doc/start/data-management/data-versioning#tracking-data
and when i use [dvc add] to start tracking the dataset file, it happens
$ dvc add data/data.xml
ERROR: Cached output(s) outside of DVC project: data\1.txt. See <https://dvc.org/doc/user-guide/pipelines/external-dependencies-and-outputs> for more info.

### Reproduce

1. dvc init
2. Copy dataset.zip to the directory
3. dvc add dataset.zip

### Environment information
DVC version: 3.2.4
------------------
Platform: Python 3.10.11 on Windows-10-10.0.19044-SP0
Subprojects:

Supports:
        azure (adlfs = 2023.4.0, knack = 0.10.1, azure-identity = 1.13.0),
        gdrive (pydrive2 = 1.16.0),
        gs (gcsfs = 2023.6.0),
        hdfs (fsspec = 2023.6.0, pyarrow = 12.0.1),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.161),
        ssh (sshfs = 2023.4.1),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2023.6.0)
Config:
        Global: C:\Users\Administrator\AppData\Local\iterative\dvc
        System: C:\ProgramData\iterative\dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: NTFS on E:\
Repo: dvc, git
Repo.site_cache_dir: C:\ProgramData\iterative\dvc\Cache\repo\e9c957124aa961a326533f79cd946a9e

**Comment by dberenbaum** [comment]
Sorry @auroraRag, it looks like this one slipped through without anyone responding. I'm guessing it's stale at this point, so I'm going to close it, but feel free to follow up if you still have issues.
