### ISSUE TITLE
Binary installers no longer attached to Github releases

### ISSUE THREAD

**Issue by michaelstepner** [iterative/dvc#9700]
# Bug Report

## Description

For all releases until dvc [v3.1.0](https://github.com/iterative/dvc/releases/tag/3.1.0), the tagged release on Github had binary installers attached as assets:

![image](https://github.com/iterative/dvc/assets/6315497/0e217edb-6b3e-4086-a7d7-0d4f89f58dfa)

For releases since then ([v3.2.0](https://github.com/iterative/dvc/releases/tag/3.2.0) onward), no binary assets are attached:

![image](https://github.com/iterative/dvc/assets/6315497/e4351a6e-9063-4752-8eb8-ef98628e2845)

### Reproduce

View [dvc releases page](https://github.com/iterative/dvc/releases/).

### Expected

I hope this regression was unintentional, and there will be interest in restoring the versioned binary installers associated with each release.

In my own experience, these installers are very useful for CI/CD environments. It is helpful to pin to a specific version and test upgrades before deploying. I'm sure other users have other uses as well.

**Comment by efiop** [comment]
@michaelstepner Those binaries were not official, see https://github.com/iterative/dvc/pull/9627#issuecomment-1605733550

**Comment by efiop** [comment]
Ah, looks like we need to update our plack in the readme too, reopening

**Comment by efiop** [comment]
@michaelstepner If you need direct links, you could use ones from dvc.org, e.g. `https://dvc.org/download/linux-deb/dvc-3.2.1` Would that work for you?

**Comment by michaelstepner** [comment]
@efiop the download link on dvc.org works great. Two comments/requests:

1. I hope you'll continue hosting installers for outdated binaries, to facilitate version pinning in dependent software. If you don't plan to keep the binaries posted for older versions, it would be helpful if you let us know so that we can cache them as needed.
2. The best of all worlds would be if you include links to the dvc.org installers as text in your Github releases. For example:

> ### 📦 Installers
> - MacOS: [dvc-3.4.0.pkg](https://dvc.org/download/osx/dvc-3.4.0)
> - Windows: [dvc-3.4.0.exe](https://dvc.org/download/win/dvc-3.4.0)
> - Linux Deb: [dvc_3.4.0_amd64.deb](https://dvc.org/download/linux-deb/dvc-3.4.0)
> - Linux RPM: [dvc-3.4.0.x86_64.rpm](https://dvc.org/download/linux-rpm/dvc-3.4.0)

**Comment by michaelstepner** [comment]
One other note @efiop: it seems that the releases linked on [dvc.org](https://dvc.org/) are not automatically synced with the [latest version released on Github](https://github.com/iterative/dvc/releases). Right now, the version history on Github is:

- v3.4.0 (17 hours ago)
- v3.3.1 (2 days ago)
- v3.3.0 (2 days ago)
- v3.2.4 (4 days ago)
    - This is the version linked on dvc.org

Perhaps that's intentional behaviour so that you stagger releases to the public? But if not, you might wish to incorporate an update to dvc.org links as part of your CD pipeline.

If you'd like me to open Issues with feature requests for any of the items I've mentioned here, let me know.

**Comment by efiop** [comment]
> The best of all worlds would be if you include links to the dvc.org installers as text in your Github releases. For example:

Github releases happen before packages are available. Doesn't seem reasonable to do that at this point, from what I can see. Also note that those packages are really completely separate from the main github project (same as conda/snap/brew/etc), so a product release (which includes packages) is really on dvc.org and not on our github.

> One other note @efiop: it seems that the releases linked on [dvc.org](https://dvc.org/) are not automatically synced with the [latest version released on Github](https://github.com/iterative/dvc/releases). Right now, the version history on Github is:

They are not, dvc.org is updated only when all packages are available for a certain version (usually happens within a few days).

**Comment by efiop** [comment]
@michaelstepner Regarding caching, we do indeed preserve old versions. If you were able to download some version once - you will be able to download it later. That being said, I don't know what kind setup requirements you might have in your particular case, maybe it would make sense to cache it yourself somewhere as well.

**Comment by michaelstepner** [comment]
Thanks for clarifying @efiop, I'll use the dvc.org links going forward.
