### ISSUE TITLE
how to use dvc with gitlab

### ISSUE THREAD

**Issue by liyan1997** [iterative/dvc#9710]
I uploaded the "dvcimg. dvc" generated by my own data "dvcimg" (this is a folder) to Gitlab for experimentation, but when I tried to "dvc get" these images using another terminal, the prompt was not allowed. I would like to follow the official link: https://dvc.org/doc/studio/user-guide/connect-custom-gitlab-server To solve this problem, but I don't understand the specific operation of this link.

**Comment by shcheklein** [comment]
Closing as stale.
