### ISSUE TITLE
plots diff/show: caching is broken for files in legacy cache format

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#9727]
```console
git clone https://github.com/iterative/vscode-dvc-demo
cd vscode-dvc-demo
dvc plots diff
ls .dvc/cache -la
dvc plots diff
```

The `plots diff` refetches them from remote, and is not being cached.
See https://github.com/iterative/dvc/pull/9183.

**Comment by dberenbaum** [comment]
@skshetry This is another outstanding 3.0 regression.

**Comment by skshetry** [comment]
Previously @efiop was against introducing caching built into `dvc_data.fs.DataFileSystem`. 
It is a bit difficult to introspect the appropriate odb/cache from the outside. I'll try to look into this again.

@efiop, if you have any ideas?

**Comment by skshetry** [comment]
I decided to look into adding support for caching to DataFileSystem.
