### ISSUE TITLE
poetry add dvc not working

### ISSUE THREAD

**Issue by ShankarChavan** [iterative/dvc#9728]
# Bug Report

poetry add dvc is not working

## Description
I am trying to install **dvc** in poetry environment and the installation is not working, after debugging the installation process I found out that it is stopped in some kind of loop at **flufl-lock** package

Below is output when we debug the installation, you can see this in fresh install with command `poetry add dvc -vvv`

<img width="486" alt="image" src="https://github.com/iterative/dvc/assets/6409350/2dd68661-006b-45e6-ae34-1a043949388c">

 

### Reproduce

create poetry environment
1. poetry init 
2. <img width="447" alt="image" src="https://github.com/iterative/dvc/assets/6409350/65b05be9-4223-42b9-887f-4629472fd2ca">
3. Answer all the questions and pyproject.toml file will be created
4. poetry shell
5. poetry add dvc -vvv
6. <img width="422" alt="image" src="https://github.com/iterative/dvc/assets/6409350/ca164279-fa36-43d4-8a63-e134251d7e16">
7. if we scroll down in the command prompt we can see the below screen where installation is stucked in circular loop
8. <img width="486" alt="image" src="https://github.com/iterative/dvc/assets/6409350/2dd68661-006b-45e6-ae34-1a043949388c"> 

### Expected
Ideally I expect the package to get installed in the environment

### Environment information

OS: Windows

create conda env -> pip install poetry-windows-fix->mkdir poetry-demo->poetry init->poetry shell->poetry add dvc -vvv

**Additional Information (if any):**

**Comment by efiop** [comment]
Does `pip install` work? If so, would you mind opening an issue in poetry and linking it here? Seems like it is a problem on their side.

**Comment by efiop** [comment]
Though also interesting that it is flufl-lock again that is causing these problems. (e.g. https://github.com/iterative/dvc/issues/9654) Might be related to it specifically too, there seems to be a lot going on in that project regarding packaging/tooling.

**Comment by ShankarChavan** [comment]
> Does `pip install` work? If so, would you mind opening an issue in poetry and linking it here? Seems like it is a problem on their side.

Yes `pip install` is working but it will not be part of poetry dependencies package

**Comment by ShankarChavan** [comment]
> Though also interesting that it is flufl-lock again that is causing these problems. (e.g. #9654) Might be related to it specifically too, there seems to be a lot going on in that project regarding packaging/tooling.

I assume then it has to do with 'flufl-lock' package and not with dvc

**Comment by daunsid** [comment]
Has this been resolved? I am currently experiencing a similar issue
