### ISSUE TITLE
fetch: silently fails to download files from 2.0 remote

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#9733]
https://stackoverflow.com/questions/76675501/problem-in-downloading-audio-transcription-datasets

Can reproduce as well.

**Comment by efiop** [comment]
Looks like the issue is the lack of default remote set. Once you set it - it works fine.

**Comment by dberenbaum** [comment]
Failing on `fetch` also seems needed here though and would fail further upstream, which would be nice.

**Comment by dberenbaum** [comment]
@efiop This one still appears to be broken.

**Comment by efiop** [comment]
Ok, so this is about checkout ignoring DataIndexTreeError during comparison stage and thus thinking that it just needs to create empty dirs, while what we really need is error-out. I think  the proper solution here is to not ignore that exception (at least for the `new` index). Looking into it.

**Comment by efiop** [comment]
Keeping open to double check the ui. Not liking that `Everything is up to date` message in pull, it wasn't there before.

**Comment by skshetry** [comment]
@efiop, what's up with this? Can i help you in any way on this?

**Comment by efiop** [comment]
@skshetry Functially fixed, wanted to maybe revisit the ui, but I think I'll just close this for now and we can get back to that later.

**Comment by skshetry** [comment]
What is the ui issue? Could you please elaborate for the record?

**Comment by dberenbaum** [comment]
I think you were right to leave it open then @efiop. Feels too confusing to leave like that for long.

**Comment by efiop** [comment]
I guess generally it is hard for us to detect if this is intended or not, because you might not have a default remote set, but have per-output remotes or you just don't have default remote set and that's inteded behaviour (e.g. you care about imports and that's all). I think the best we can do here is just throw a warning saying that "hey, you don't have any default remote set" or smth like that if we weren't able to transfer anything. So you'd get the warning and the rest of the output will be the same as illustrated above.

**Comment by dberenbaum** [comment]
So in this case `Everything is up to date.` means that fetch was successful because nothing was expected to be fetched? Can we indicate that it comes from the fetch step somehow (and show that the rest comes from the checkout step) to make the messaging less confusing? 

> I think the best we can do here is just throw a warning saying that "hey, you don't have any default remote set" or smth like that if we weren't able to transfer anything.

👍 During fetch, can we show a warning if no remote is explicitly provided and no default remote is set?
