### ISSUE TITLE
Can we have a CI mode for logging?

### ISSUE THREAD

**Issue by Ykid** [iterative/dvc#9734]
When running `dvc pull`, dvc outputs the download progress in the terminal and keeps refreshing the stdout from time to time. This works perfectly fine in the case of local laptop, but I came across an issue recently in a CI. [Some CI detects whether a task is stuck by checking whether there is new line printed to std out](https://support.circleci.com/hc/en-us/articles/360045268074-Build-Fails-with-Too-long-with-no-output-exceeded-10m0s-context-deadline-exceeded-). As [other tools will not forward the log to the std out unless there is a new line written](https://docs.fastlane.tools/actions/sh/), the `dvc pull` task timed out in our CI as there are quite a few files to download ( like 20 .dvc files and each of which is around .5 GB ). I suspect it is because `tqdm` keep refreshing the current line of stdout without adding a new line. 

I am thinking if we can have a logging mode for CI related tasks in which dvc flush some output to the stdout from time to time?

**Comment by pmrowla** [comment]
It depends on how your particular CI logging capture setup works, but setting `DVC_IGNORE_ISATTY=1` in your environment (before running `dvc pull`) may fix this for you.

**Comment by Ykid** [comment]
Thanks @pmrowla . Setting the env variable helped!
