### ISSUE TITLE
migrate: Only works if cache.dir inside .dvc/ folder?

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#9735]
# Bug Report

## Description

In my project, I had moved the DVC cache to `data/cache` and set `cache.dir` in `.dvc/config` accordingly to `../data/cache`. When I run `dvc cache migrate --dry`, it tells me that 0 files are going to be re-hashed and migrated. When I move the cache folder back inside `.dvc/` and change `cache.dir` to `cache`, it tells me that it will re-hash the ~90k files I have in the cache as expected.

The command reference of `dvc cache migrate` does not state whether there is any need to have the old DVC cache in the default `.dvc/cache` location.

### Reproduce

Change `cache.dir` to a location outside of `.dvc/` and run `dvc cache migrate --dry`.

### Expected

DVC should re-hash and migrate the cached files regardless of where it is located given the `cache.dir` setting.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.5.1 (conda)
--------------------------
Platform: Python 3.10.6 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 2.5.0
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
        Global: /home/aschuh/.config/dvc
        System: /etc/xdg/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3, s3
Workspace directory: xfs on /dev/sda1
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/764b1d03f8b416f032df6c50c3809e7f
```

**Additional Information (if any):**

I see the `dvc doctor` output does not list my `Cache types`. I use `cache.type = symlink`.

**Comment by dberenbaum** [comment]
@pmrowla Is it expected?

**Comment by pmrowla** [comment]
It's not expected, I'll look into it
