### ISSUE TITLE
Support packaged (pkg://) configs for Hydra

### ISSUE THREAD

**Issue by exs-dmiketa** [iterative/dvc#9740]
Hi,

Hydra supports several ways to define config directories. The two relevant to this issue are:
1. Relative to some directory. This translates to "relative to `.dvc/config`" in DVC and is the supported mode.
2. As a Python module `pkg://some.python.module`.

Would it be possible to support the second route too?

It seems likely that replacing `initialize_config_dir` [here](https://github.com/iterative/dvc/blob/ea5f7d40c131aa949f307e31e14e5d99024c20da/dvc/utils/hydra.py#L40) with `initialize_config_module` ([docs](https://hydra.cc/docs/1.3/advanced/compose_api/)) would be enough to enable packaged configs and a simple check for a `pkg://` prefix should be enough to distinguish between the two cases.

The reason for this feature request is that I'd like to set up automatic unit tests which involves copying `.dvc` into a temporary directory. That would break the relative path but a packaged config would still resolve correctly.

Thanks! :)

Edit: I was able to get around this with a bit of surgery but it'd still be a nice feature for more readable and transferable configs. :)

**Comment by dberenbaum** [comment]
@daavoo Any concerns with this?

@exs-dmiketa Would you want to contribute the change?

**Comment by daavoo** [comment]
> @daavoo Any concerns with this?

At first glance, nothing against it.

> Happy to contribute it but I'm unfamiliar with your test setup so would appreciate pointers!

Example tests are in https://github.com/iterative/dvc/blob/main/tests/func/utils/test_hydra.py

For the `pkg`, it might be worth creating a dummy Python inside the test (using `tmp_dir` , adding `__init__.py` file, and dumping some example config). The closest one today would be:

https://github.com/iterative/dvc/blob/ea5f7d40c131aa949f307e31e14e5d99024c20da/tests/func/utils/test_hydra.py#L192-L203

Alternatively (or in addition) we could test a globally available package like:

```py
def test_compose_and_dump_pkg(tmp_dir):
    """Regression test for https://github.com/iterative/dvc/issues/9196"""
    from dvc.utils.hydra import compose_and_dump

    output_file = tmp_dir / "params.yaml"
    compose_and_dump(output_file, "pkg://hydra.test_utils.configs"), "config", [])
    assert output_file.parse() == something
```

**Comment by exs-dmiketa** [comment]
I had a look around the codebase and it looks like I'll have to do one of these:

1. Use the `config_dir` field for `config_module` too, distinguishing between modules and absolute or relative paths by checking for a `pkg://` prefix. This is a bit strange because a config module is not a `config_dir`.
2. Add `hydra.config_module` to config settings and handle cases where people set both `config_dir` and `config_module` (or neither).
3. Like 1, but rename `config_dir` to `config_source` or similar.

**Comment by daavoo** [comment]
> I had a look around the codebase and it looks like I'll have to do one of these:
> 
> 1. Use the `config_dir` field for `config_module` too, distinguishing between modules and absolute or relative paths by checking for a `pkg://` prefix. This is a bit strange because a config module is not a `config_dir`.
> 2. Add `hydra.config_module` to config settings and handle cases where people set both `config_dir` and `config_module` (or neither).
> 3. Like 1, but rename `config_dir` to `config_source` or similar.
> 
> What do you think?

I vote `2`,  to keep it consistent with the naming in the Hydra API itself (`initialize_config_dir` / `initialize_config_module`). 

Hopefully, the logic could be handled using voluptuous [Exclusive](http://alecthomas.github.io/voluptuous/docs/_build/html/voluptuous.html#voluptuous.schema_builder.Exclusive) in:

https://github.com/iterative/dvc/blob/ca0ad239f71badbf3267189d49a95b39911ed320/dvc/config_schema.py#L327C27-L327C27

**Comment by exs-dmiketa** [comment]
Thanks @daavoo, I'll go that route. The configuration cascade will be:
1. use `config_module` if present, raise schema error if `config_module` and `config_dir` are both specified
2. use `config_dir` if `config_module` is missing and `config_dir` is specified
3. impute `config_dir==conf` if neither `config_dir` nor `config_module` are missing.

I'll open a PR once I have a test for `config_module`, everything else is there and it's testing green.
