### ISSUE TITLE
`dvc.cli.main` support running multiple commands

### ISSUE THREAD

**Issue by PythonFZ** [iterative/dvc#9742]
I'm using the `dvc.cli.main` interface to add many stages at once.
This leads to a noticeably slowdown, because the `dvc.cli.main` command reads and validates the dvc configuration each time it is called.
It would be a great feature, if one could read the configuration once, add all e.g. stages and then _commit_ the changes to be written to a configuration file.

This could look something like
```python
with dvc.repo.Repo() as repo:
    for cmd in cmds:
        repo.main(cmd)
# maybe with a final repo.save()
```
or
```python
repo = dvc.repo.Repo()

for cmd in cmds:
   dvc.cli.main(cmd, repo=repo)
```

which could lead to a significant speed up in adding many (> 100 stages) at once through the Python API.

This feature would be really handy for the [ZnTrack](https://github.com/zincware/zntrack) package I'm developing as also discussed with @skshetry

**Comment by dberenbaum** [comment]
Hey @PythonFZ! Sounds good. I should warn that since it is unlikely that it helps with more typical workflows, I doubt we will be able to prioritize it. Are you interested in contributing it?

**Comment by skshetry** [comment]
Closing as not planned.
