### ISSUE TITLE
'.../plots/metrics/metrics' - file type error

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#9745]
Using the `dvclive.lightning.DVCLiveLogger` with `dir="data/train/dvclive"`, I can see the plots of the metrics in the "Plots" view of the VS Code DVC extension. But at the top where it shows the selected experiments, it displays an error with message:

> 'data/train/dvclive/plots/metrics/metrics' - file type error
Only JSON, YAML, CSV and TSV formats are supported.

The summary metrics are stored in `data/train/dvclive/metrics.json` and the `.tsv` files of the logged metrics are in `data/train/dvclive/plots/metrics/`. There exists no file named `metrics` without extension inside this folder.

**Comment by aschuh-hf** [comment]
I have a `dvc.yaml` file with a `train` stage with a `plots` entry.

This entry is returned by `dvc.repo.plots._collect_plots` with key `fs_path` equal to `data/train/plots/metrics` as this is the folder specified in my `dvc.yaml:train.plots` entry. This `fs_path` key is checked against the expected file name extensions in the `dvc.repo.plots.parse` function which raises this error.

<img width="346" alt="Screen Shot 2023-07-18 at 11 08 04 PM" src="https://github.com/iterative/dvc/assets/77496589/87c0e310-a5e4-4e6b-9e01-60407ba92737">

https://github.com/iterative/dvc/blob/ea5f7d40c131aa949f307e31e14e5d99024c20da/dvc/repo/plots/__init__.py#L323-L341

https://github.com/iterative/dvc/blob/ea5f7d40c131aa949f307e31e14e5d99024c20da/dvc/repo/plots/__init__.py#L182-L188

**Comment by aschuh-hf** [comment]
Output of `dvc.repo.plots.Plots.collect()` when `data/train/plots/metrics` directory does not exist:

```
[{'workspace': {'definitions': {'data': {'': {'data': {'data/train/plots/metrics': {'x': 'step'}}}}},
   'sources': {'data': {'data/train/plots/metrics': {'props': {'x': 'step'},
      'data_source': functools.partial(<function error_handler.<locals>.wrapper at 0x7ff81e2a9000>, <dvc.fs.dvc.DVCFileSystem object at 0x7ff834102cb0>, 'data/train/plots/metrics', props={'x': 'step'}, onerror=None)}}}}}]
```

Once the directory exists (e.g., written by DVCLive), the `Plots.collect()` method lists individual `.tsv` files instead.

**Comment by dberenbaum** [comment]
Thanks @aschuh-hf! I can confirm that with the `dvc.yaml` you shared, I get the same error from `dvc plots show/diff`. It looks like for some reason it duplicates the basename of the path when a plot stage output points to a directory path.

**Comment by dberenbaum** [comment]
It only happens when `dvc.lock` is missing, in which case `dvc_data.fs.DataFileSystem.ls(data/train/plots/metrics)` does not know if `data/train/plots/metrics` is a directory or file [here](https://github.com/iterative/dvc-data/blob/efa543a2b600eb93461ad55234d500d0ba0df370/src/dvc_data/fs.py#L97-L102). It assumes it is a file and `dvc_data.fs.DataFileSystem.ls("data/train/plots/metrics")` returns itself. `LocalFileSystem.ls(path)` only returns subpaths and fails if `path` is a file, so not sure if it's expected that `dvc_data.fs.DataFileSystem.ls(path)` returns `path` itself. cc @efiop
