### ISSUE TITLE
dvc exp run: Repeated execution of dvc exp run leads to second experiment being corrupted

### ISSUE THREAD

**Issue by kpetersen-hf** [iterative/dvc#9781]
# Bug Report

## Issue name

dvc exp run: Repeated execution of `dvc exp run` leads to second experiment being corrupted

## Description

When running `dvc exp run` twice in a row without any code change, I obtain two different experiments. It seems that the second experiment equals the original branch.

### Reproduce

```
git init -q dvc_issue
cd dvc_issue
dvc init -q

cat <<EOT >> .dvc/config
[core]
    remote = store
    analytics = false
[cache]
    dir = dvc_cache
    shared = group
    type = reflink,symlink
    slow_link_warning = true
['remote "store"']
    url = dvc_store
EOT

cat <<EOT >> dvc.yaml
vars:
  - uri_model: model.pkl

stages:
  train:
    cmd: python train.py
    deps:
    - train.py
    outs:
    - \${uri_model}:
        cache: false
  evaluate:
    cmd: python evaluate.py
    deps:
    - evaluate.py
    - \${uri_model}
    metrics:
      - metrics.json:
          cache: false
EOT

cat <<EOT >> train.py
import json
def main():
    metrics_filename = "model.pkl"
    data = {"auc": 0.29}
    with open(metrics_filename, 'w') as f:
        json.dump(data, f)
    print("Finished train.")
if __name__ == "__main__":
    main()
EOT

cat <<EOT >> evaluate.py
import json
def main():
    metrics_filename = "metrics.json"
    data = {"auc": 0.29}
    with open(metrics_filename, 'w') as f:
        json.dump(data, f)
    print("Finished evaluate.")
if __name__ == "__main__":
    main()
EOT

git add .
git commit -q -m "initial"
dvc exp run train -n exp0
dvc exp run train -n exp1
dvc exp show -v
```

### Expected

My expectation is that both experiments are the same. However, if I delete all files and the call `dvc exp apply exp0`, compared to `dvc exp apply exp1` I get two different experiments. This is also reflected when calling `dvc exp show`.

### Environment information

**Output of `dvc doctor`:**

```
DVC version: 3.9.1 (pip)
------------------------
Platform: Python 3.10.8 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
	dvc_data = 2.8.0
	dvc_objects = 0.23.0
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.1.0
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
	Global: /home/kpetersen/.config/dvc
	System: /etc/xdg/dvc
```

**Comment by pmrowla** [comment]
Can you clarify what you mean by `second experiment being corrupted`?

If you mean that you see two separate experiments (but with matching outputs/metrics) listed in `exp show`, this is expected behavior. DVC no longer checks for duplicate experiments. In older releases DVC would check to see if the two results were identical and then drop the second experiment in those cases, but this behavior was dropped around a year ago (see https://github.com/iterative/dvc/issues/8669).

**Comment by kpetersen-hf** [comment]
Hi Peter,

Thanks for checking! I obtain two separate experiments but they don't match! The first experiment (exp0) is as expected and tracks `train.py` as well as its output `model.pkl`. However, the second experiment (exp1) does not track either. This can be seen with `dvc exp show` (see image) and is also apparent when deleting all files in the folder and running `dvc exp apply exp0` vs. `dvc exp apply exp1`. The second one (`exp1`) does not track `model.pkl` and `dvc.lock`.

<img width="582" alt="image" src="https://github.com/iterative/dvc/assets/56620752/af2028f9-5144-46e0-b7d4-4d2784109d64">

**Comment by kpetersen-hf** [comment]
If I remove experiment `exp1`, modify `train.py` by adding an empty line and save it again with `dvc exp run train -n exp1', I obtain an experiment that -- as expected -- shows a different hash for `train.py`. 

<img width="595" alt="image" src="https://github.com/iterative/dvc/assets/56620752/90d84443-d405-46d8-a34a-ad0ead2c0e2b">

If I then again remove experiment `exp1`, undo this change in `train.py`, and add it again with `dvc exp run train -n exp1' I obtain what I would have expected when running the experiments as described above in the issue:

<img width="576" alt="image" src="https://github.com/iterative/dvc/assets/56620752/1b026478-c7ae-4cd3-af41-1b636aaa184b">

**Comment by pmrowla** [comment]
Ok, I'm able to reproduce it. It looks like we aren't generating a lock file whenever the entire pipeline is loaded from run cache. Using `exp run -f` more than once gives me the expected result, but `exp run` does not.
