### ISSUE TITLE
drop dvc.machine and tpi/python-terraform dependency

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#9792]
cc @pmrowla

**Comment by ChillarAnand** [comment]
Can you add a warning message that `machine` is removed on the wiki page(or get rid of the page)?

https://github.com/treeverse/dvc/wiki/Remote-executors#machine-management

From search engines, it is directly reachable and causes confusion for new users.

**Comment by skshetry** [comment]
@ChillarAnand, done, PTAL at https://github.com/treeverse/dvc/wiki/Remote-executors.

**Comment by ChillarAnand** [comment]
Looks good. Thanks, @skshetry 

Any reason for dropping `dvc machine`? I couldn't find any discussions related to it.

Are there any plans to support external plugins for `dvc`? Just wondering if it is worth adding `machine` support via a separate plugin.

**Comment by skshetry** [comment]
> Any reason for dropping `dvc machine`? I couldn't find any discussions related to it.

I don't remember exactly as it was a long time ago, but I think the technology (use of terraform) was to blame. Later, this feature was also considered to be part of a paid offering, but no such product exists today.

> Are there any plans to support external plugins for `dvc`? Just wondering if it is worth adding `machine` support via a separate plugin.

There are no plans to implement such plugins in the foreseeable future.
