### ISSUE TITLE
3.11 debian package not available?

### ISSUE THREAD

**Issue by PeterJCLaw** [iterative/dvc#9803]
# Bug Report

I'm using the `iterative/setup-dvc` GitHub Action, which installs debian packages from urls like <https://dvc.org/download/linux-deb/dvc-3.10.1>. This works fine for 3.10, however the 3.11 release appears to be missing the packages -- <https://dvc.org/download/linux-deb/dvc-3.11.0> and <https://dvc.org/download/linux-deb/dvc-3.11.1> don't resolve.

The action falls back to <https://github.com/iterative/dvc/releases/download/3.11.0/dvc_3.11.0_amd64.deb> which also doesn't resolve (none of the recent releases have debian packages attached as assets, so this part might be a general issue with the action?)

**Comment by efiop** [comment]
@PeterJCLaw Thanks for the feedback! deb building is currently failing for 3.11, we will fix https://github.com/iterative/dvc-s3-repo soon.

But we also indeed stopped building debs in the main repo, so falling back to  https://github.com/iterative/dvc/releases/download/3.11.0/dvc_3.11.0_amd64.deb is no longer possible. So we need to fix setup-dvc as well.

**Comment by efiop** [comment]
Sent a PR to setup-dvc https://github.com/iterative/setup-dvc/pull/56

And waiting for 3.11.1 deb to become available.
