### ISSUE TITLE
Running `dvc repro` in parallel does not work

### ISSUE THREAD

**Issue by Numeri** [iterative/dvc#9805]
# Bug Report

## Description
In the documentation for `dvc repro`, it says that one can [run independent steps in parallel](https://dvc.org/doc/command-reference/repro#parallel-stage-execution). This does not work, as each step tries to obtain `dvc.lock`.

Looking through your issues, it seems like `dvc` doesn't support stage parallelism _at all_, which truly surprised me, and contradicts this documentation.

### Reproduce
I have a stage which downloads a large list of data sources, using a `foreach`. I run each version in parallel with the following:
```bash
for download_stage in $(dvc stage list | grep download | cut -d ' ' -f 1)
do
    echo $download_stage
    dvc repro $download_stage &
done

wait
```

### Expected
All `download@${something}` stages run in parallel, without trying to obtain `dvc.lock`.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.43.1 (pip)
---------------------------------
Platform: Python 3.9.15 on Linux-6.4.6-1-MANJARO-x86_64-with-glibc2.37
Subprojects:
	dvc_data = 0.35.1
	dvc_objects = 0.19.0
	dvc_render = 0.0.17
	dvc_task = 0.1.11
	dvclive = 1.3.3
	scmrepo = 0.1.6
Supports:
	gs (gcsfs = 2023.1.0),
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: local
Workspace directory: ext4 on /dev/sda
Repo: dvc, git
```

**Comment by dberenbaum** [comment]
There is limited support for parallelism. Each parallel run will have to write to `dvc.lock`, but if they are independent stages, it should not be an issue unless multiple runs try to write to `dvc.lock` at the same time. Building on your example, I'm able to run a very simple reproduction using this `dvc.yaml`:

```yaml
stages:
  download:
    foreach:
      - nlp
      - versioning
    do:
      cmd: dvc get https://github.com/iterative/dataset-registry tutorials/${item}
      outs:
      - ${item}
```

Then running your bash script above gives me an output of:

```
download@nlp
download@versioning
Running stage 'download@versioning':
> dvc get https://github.com/iterative/dataset-registry tutorials/versioning
Running stage 'download@nlp':                                         00:00,      ?obj/s]
> dvc get https://github.com/iterative/dataset-registry tutorials/nlp
Generating lock file 'dvc.lock'
Updating lock file 'dvc.lock'
Use `dvc push` to send your updates to remote storage.9M/39.2M [00:03<00:05,    4.33MB/s]
Updating lock file 'dvc.lock'
Use `dvc push` to send your updates to remote storage.
```

**Comment by Numeri** [comment]
Interesting. I'll go back to my use case and try to boil it down to a more minimal example to see if we can figure out why it's failing. Thanks!

**Comment by Antho2422** [comment]
Hello, 

Is there any solution in the work about that ? We would be really interested to be able to run stages in a `foreach` loop in parallel and handle the access to the dvc.lock file properly

Thanks, 
Anthony
