### ISSUE TITLE
dvc get: throws error when file is in subfolder

### ISSUE THREAD

**Issue by kpetersen-hf** [iterative/dvc#9814]
# Bug Report

dvc get: throws error when file is in subfolder

## Description

I tracked a file `$SUBDIR/filedata.txt` with DVC. When trying to retrieve this file with `dvc get`, I get an error 
```
ERROR: unexpected error - 'NoneType' object has no attribute 'fs' 
``` 

if `$SUBDIR` is not set to the root folder. In other words, the following script works as expected for `SUBDIR=.` but throws the error for `SUBDIR=sub`.

### Reproduce
Please specify some absolute path in line 2. The script works as expected if `SUBDIR=.` is used in line 1, i.e., it obtains the file `datafile.txt` and saves it as `datafile_get.txt`. However, if a subdirectory name (here: `sub`) is specified, the script crashes. 

```
SUBDIR=sub
MY_PATH=<SOME_ABSOLUTE_PATH>
mkdir $MY_PATH
cd $MY_PATH

REMOTE_PATH=$MY_PATH/remote/git_storage.git
LOCAL_PATH=$MY_PATH/local
STORE_PATH=$MY_PATH/store
CACHE_PATH=$MY_PATH/cache

git init --bare -q $REMOTE_PATH
git clone $REMOTE_PATH $LOCAL_PATH

cd $LOCAL_PATH
dvc init -q

cat <<EOT >> .dvc/config
[core]
    remote = store
[cache]
    dir = $CACHE_PATH
    type = reflink,symlink
['remote "store"']
    url = $STORE_PATH
EOT

# First commit
mkdir $SUBDIR
cd $SUBDIR
echo "Hello World!" >> datafile.txt
dvc add datafile.txt
git add .
git commit -q -m "initial"
dvc push
git push

# Retrieve file
PREVIOUS_COMMIT=$(git log -n 1 --pretty=format:"%H")
dvc get $REMOTE_PATH $SUBDIR/datafile.txt -o datafile_get.txt --rev $PREVIOUS_COMMIT
```

### Expected

I expect that no error is thrown, the file `sub/datafile.txt` can be successfully retrieved, and will be saved as  `sub/datafile_get.txt`.

### Environment information

**Output of `dvc doctor`:**

```
$ dvc doctor

DVC version: 3.12.0 (pip)
-------------------------
Platform: Python 3.10.8 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
	dvc_data = 2.11.0
	dvc_objects = 0.24.1
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.1.0
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
	Global: /home/kpetersen/.config/dvc
	System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sda1
Caches: local
Remotes: local
Workspace directory: xfs on /dev/sda1
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/0f7f5db67dbdcb6608d56609eb9b05eb
```

**Additional Information (if any):**

**Comment by dberenbaum** [comment]
Thanks for the reproduction script! Can you try to change `git add .` to `git add ..` since you are inside the subdir? That seems to fix it for me.
