### ISSUE TITLE
dvc exp run --queue: can't access another subdir

### ISSUE THREAD

**Issue by bencaldwell** [iterative/dvc#9829]
# Bug Report

## Description

I have a monorepo with two models ("A" and "B"), each in their own subdir. These models are destined to be deployed as a chain: input -> A -> B -> prediction. The monorepo structure is:

```
monorepo
  - model_a
    - dvc.yaml
  - model_b
    - dvc.yaml
```

I have run `dvc int --subdir` in model_a and model_b and have run the model_a and model_b pipelines described in the respective dvc.yaml using `dvc repro`.

The model_b pipeline has a preprocessing stage that uses the model output from model_a pipeline. In the dvc.yaml file this is done using relative path i.e. `../model_a/data/model/best.pt`

This works as expected when I use dvc repro. However I have a problem when I try to run experiments in model_b, e.g. a grid search using `dvc exp run -S 'myparam=range(0,1,0.1)` --queue`
This results in the experiment not being able to find the model file from the other (model_a) subdir.

### Reproduce
Example:

1. Create two subdirs model_a and model_b
2. Run dvc init --subdir in each subdir
3. Create an out in model_a
4. Add the out from model_a as a dep in model_b
6. dvc exp run --queue
7. dvc queue start

### Expected

I expect dvc exp run to behave in the same way as dvc repro.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.11.0 (pip)
-------------------------
Platform: Python 3.10.12 on Linux-5.15.0-1031-aws-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 2.9.1
        dvc_objects = 0.24.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.1.0
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.161)
Config:
        Global: /home/ubuntu/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/xvda1
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/xvda1
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/b6c825babd1a70932ca8ee2f0f2f2ac0
```

**Comment by pmrowla** [comment]
When you use `--queue`, DVC will run the experiment in a temporary directory containing a copy of your workspace, but in this case we will only copy the one DVC subdir (where you are running the experiment). So in the temporary directory, the relative path to your other model won't be valid.

The only workaround for this right now would be to use the absolute path to the other DVC repo's model as the dep path (instead of a relpath).

**Comment by dberenbaum** [comment]
@bencaldwell Are you making changes to both models in the experiments you queue?

**Comment by shcheklein** [comment]
@dberenbaum from the discussion we had it was more of an ensemble of models. Model is used of inference. So, probably no changes. But @bencaldwell can conform on that part.

**Comment by dberenbaum** [comment]
If that's the case, inside `model_b` you could do `dvc import git@github.com:org/repo-name.git model_a/data/model/best.pt -o best.pt`. Then you can use `best.pt` from within `model_b` (and it shouldn't use additional storage). There's a simple example [here](https://github.com/dberenbaum/example-get-started-mono/blob/main/train/data/features.dvc) that separates data prep and training into separate subdirs.

**Comment by bencaldwell** [comment]
@dberenbaum I have tried the dvc import. However, I am running all experiments inside a private AWS VPC and the repo is AWS codecommit. So far I haven't got dvc import to work with that. I've tried the codecommit, git, and https urls supported by codecommit. Any tips here would also be appreciated!
The dual pipelines are for an ensemble as @shcheklein mentioned. When deployed the input will go to model_a, the output of model_a will go to model_b. I figured while training it would make sense to split the pipelines then just use model_a as a "preprocessor" on the data used to train model_b. Does that make sense?

**Comment by dberenbaum** [comment]
It makes sense. Is this a larger monorepo than these two "projects"? If it's not a massive repo, the simplest solution would be to initialize dvc at the root of the repo rather than within each subdir (you can keep the subdirs and separate dvc.yaml files). Would that work for you?

**Comment by shcheklein** [comment]
Since it's a part of the same repo, `dvc import` should work with a local path to my mind, w/o involving GH, clones, etc.

**Comment by bencaldwell** [comment]
@dberenbaum I've tried what you suggested. After some initial problems I thought it simplest to run `dvc destroy` in both model_a and model_b subdirs, then `dvc init` in the root. I just git checkout the old dvc.yaml back out into the subdirs. `dvc repro model_a/dvc.yaml` then had problems with finding the params.yaml file, so I ran `dvc repro` from within the model_a subdir. Same for model_b. 
Then I tried to run the experiment inside the model_b subdir and it couldn't find a json file. So I tried running the experiment from the root with `dvc exp run --queue model_b/dvc.yaml` and I get an error that crop_classify/dvc.yaml is dvc-ignored

**Comment by dberenbaum** [comment]
Sorry for the frustrations @bencaldwell. 

The dvc-ignored error looks especially odd. The only way I am able to reproduce is if I still have a `.dvc` folder at the root of `model_b`. Can you check and try to run `dvc destroy` again or manually drop that folder if it still exists? If you still encounter issues, would you mind adding `-v` to your commands and posting the full traceback here so we can take a look?

I updated https://github.com/dberenbaum/example-get-started-mono to match your scenario (single .dvc folder at the root with separate subfolders) and show how it's supposed to work.

For example, to run from the root of the repo, you can run it like this:

```
$ dvc exp run --queue -S prepare/params.yaml:featurize.ngrams=1 train/dvc.yaml
Queueing with overrides '{'prepare/params.yaml': ['featurize.ngrams=1']}'.
Queued experiment 'third-toke' for future execution.

$ dvc exp run --run-all
Following logs for all queued experiments. Use Ctrl+C to stop following logs (experiment execution will continue).

Reproducing experiment 'third-toke'
'prepare/data/data.xml.dvc' didn't change, skipping
Stage 'prepare/dvc.yaml:prepare' didn't change, skipping
Running stage 'prepare/dvc.yaml:featurize':
> python src/featurization.py data/prepared data/features
The input data frame data/prepared/train.tsv size is (7996, 3)
The output matrix data/features/train.pkl size is (7996, 202) and data type is float64
The input data frame data/prepared/test.tsv size is (2004, 3)
The output matrix data/features/test.pkl size is (2004, 202) and data type is float64
Updating lock file 'prepare/dvc.lock'

Running stage 'train/dvc.yaml:train':
> python src/train.py ../prepare/data/features model.pkl
Input matrix size (7996, 202)
X matrix size (7996, 200)
Y matrix size (7996,)
Updating lock file 'train/dvc.lock'

Running stage 'train/dvc.yaml:evaluate':
> python src/evaluate.py model.pkl ../prepare/data/features
Updating lock file 'train/dvc.lock'

Ran experiment(s):
To apply the results of an experiment to your workspace run:

        dvc exp apply <exp>

To promote an experiment to a Git branch run:

        dvc exp branch <exp> <branch>
```

To run from within a subfolder, you can run it like this:

```
$ cd prepare

$ dvc exp run --queue -S featurize.ngrams=4
Queueing with overrides '{'params.yaml': ['featurize.ngrams=4']}'.
Queued experiment 'rooky-soke' for future execution.

$ dvc exp run --run-all
Following logs for all queued experiments. Use Ctrl+C to stop following logs (experiment execution will continue).

Reproducing experiment 'rooky-soke'
'data/data.xml.dvc' didn't change, skipping
Stage 'prepare' didn't change, skipping
Running stage 'featurize':
> python src/featurization.py data/prepared data/features
The input data frame data/prepared/train.tsv size is (7996, 3)
The output matrix data/features/train.pkl size is (7996, 202) and data type is float64
The input data frame data/prepared/test.tsv size is (2004, 3)
The output matrix data/features/test.pkl size is (2004, 202) and data type is float64
Updating lock file 'dvc.lock'

Ran experiment(s):
To apply the results of an experiment to your workspace run:

        dvc exp apply <exp>

To promote an experiment to a Git branch run:

        dvc exp branch <exp> <branch>
```

**Comment by bencaldwell** [comment]
@dberenbaum I had a look at your repo and the structure matched mine. 
After some more poking around it looks like there is a fair amount of dvc git interaction going on under the hood. I had to remove the .dvc folders in the model subdirs *then git commit* then `dvc repro model_a/dvc.yaml works`.
I guess I was just expecting dvc to look at my working tree not second guess me based on my git commits.

However after running `dvc repro model_a/dvc.yaml` then `dvc repro model_b/dvc.yaml` once I end up with a .dvc folder and a dvclive folder inside each subdir. The presence of each of these means I can't run dvc repro again because I now get the model_a/dvc.yaml is dvc-ignored error. 

When I delete the .dvc folders and try again I get an error about a model_b/dvclive/params.yaml not being found. This file actually *does* exist. 

If I then delete the dvclive folders then dvc doesn't look for a params file there and I can run `dvc repro model_b/dvc.yaml` again. But if I wanted to run it again I'd have to delete the .dvc and dvclive folders inside each subdir again.

What am I doing wrong here? Are these folders supposed to appear?

**Comment by bencaldwell** [comment]
Ok I think I've narrowed the creation of the .dvc folders to the vscode dvc extension. I updated my extension to the latest version and it seems to have stopped happening.

**Comment by dberenbaum** [comment]
@bencaldwell Is it working for you now or are you still facing issues?

**Comment by dberenbaum** [comment]
Closing as stale
