### ISSUE TITLE
`dvc status --remote`

### ISSUE THREAD

**Issue by helpmefindaname** [iterative/dvc#9832]
Hello,

my team and I are currently utilzing a dvc pipeline that checks if all data is pushted to the remote storage. This is currently done by pulling all data and then run `dvc status -q`. Pulling all data is slow, especially if you are storing many images. A faster way would be to only download all `.dir` cache files and just verify the existence of the respective hashes on the remote server, not having to spend much time on downloading all the files.

Ideally `dvc status --remote` or `dvc status -r` would do such a check for me.

**Comment by Otterpatsch** [comment]
try to run did you try to run `dvc data status --not-in-remote --json | grep -v not_in_remote` it will fail if there is missing data on remote.
see https://dvc.org/doc/user-guide/pipelines/running-pipelines#verify-pipeline-status

**Comment by helpmefindaname** [comment]
Thank you,
I will try that out instead.

**Comment by dberenbaum** [comment]
@helpmefindaname Let me know if it fixes the issue for you. How do you plan to use it? Are you running a CI job to check that everything is up to date?
