### ISSUE TITLE
`dvc exp pull` hangs

### ISSUE THREAD

**Issue by leduckhc** [iterative/dvc#9845]
# Bug Report

## Description

I run an experiment in the gitlab CI. I can see that the experiment finished and is shown in the studio. the experiment's name is correct, eg `fleet-aura`.  However, on my local machine, `dvc exp pull` timeouts. Strangely this is not a problem when I clone the repo from scratch and pull the experiment from there.

### Reproduce
Part of gitlab CI job

```yaml
# part of .gitlab-ci.yml
- cml ci
- dvc pull --allow-missing
- dvc exp run
- dvc exp push origin
```

Running following commands
```bash
# the command pull exp. None of which works
dvc exp pull origin fleet-aura
dvc exp pull origin fleet-aura -r s3remote
dvc exp pull --rev <parent git commit> origin

# all of them timeout even with --jobs <n> arg
```

Results in

```error
ERROR: unexpected error - The remote server unexpectedly closed the connection.                                                                            

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

### Expected
Pulled experiment

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 3.15.2 (pip)
-------------------------
Platform: Python 3.9.17 on macOS-13.4.1-arm64-arm-64bit
Subprojects:
        dvc_data = 2.13.1
        dvc_objects = 0.24.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.2.1
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
        Global: /Users/khanhchuong.le/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc (subdir), git
Repo.site_cache_dir: /Library/Caches/dvc/repo/40be3fb0ca87177d28a290b2ca4184af
```

**Additional Information (if any):**

**Comment by dberenbaum** [comment]
> Strangely this is not a problem when I clone the repo from scratch and pull the experiment from there.

So `dvc exp pull` works on a fresh clone but not on your existing clone? Would you mind trying `rm -rf /Library/Caches/dvc/repo/40be3fb0ca87177d28a290b2ca4184af` and seeing if that helps? We have recently fixed some bugs, but sometimes the [site cache dir](https://dvc.org/doc/user-guide/project-structure/internal-files#site-cache-dir) needs to be reset.

**Comment by skshetry** [comment]
Closing due to lack of response.
