### ISSUE TITLE
Add Mega cloud to remote storage for data management

### ISSUE THREAD

**Issue by Giovo17** [iterative/dvc#9850]
Can you please add Mega (https://mega.io/) as supported remote storage?

**Comment by skshetry** [comment]
Hi @Giovo17. Thank you for creating the issue. However, we already support 10 different remote storages that we don't really have capacity to support this on our own. 

DVC depends on [fsspec](https://filesystem-spec.readthedocs.io/en/latest/),so theoretically dvc can support any remote storages that have a good fsspec implementation. So a pre-requisite for adding a remote storage is to have a good `fsspec` implementation of Mega that dvc can use.

Even then, we'll need enough interests in the community for us to support it.

Again, thanks for creating this issue. But I am closing this for the time being.

**Comment by efiop** [comment]
Worth noting that if there will be an fsspec implementation and we finally finalize dvc plugins, then one could use that as an unofficial plugin with dvc. E.g. https://github.com/iterative/dvc-s3
