### ISSUE TITLE
`dvc repro --dry`: should fail if any stage has to run

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9861]
So i fixed the issue (i think) on our side. I basically run `dvc repro --allow-missing --dry` couple of times to get each time one of the datasets which where still dvc2. Then i readd those and not anymore crashing. 

But now the pipeline succeeds even tho i get a the following lines in the command. Which makes sense because i changed a lot of .dvc files which are also in that path. 
```
13:57:33  2023-08-21 11:57:24,369 DEBUG: built tree 'object 880a0f10a0350a3ed636a6a395a7cd4a.dir'
13:57:33  2023-08-21 11:57:24,370 DEBUG: Dependency 'datasets/training-sets' of stage: 'training' changed because it is 'modified'.
13:57:33  2023-08-21 11:57:24,371 DEBUG: stage: 'training' changed.
13:57:33  2023-08-21 11:57:24,384 DEBUG: built tree 'object 880a0f10a0350a3ed636a6a395a7cd4a.dir'
13:57:33  2023-08-21 11:57:24,386 DEBUG: built tree 'object 2ead35ca4cf9b96e0f4ad3cc696e78d7.dir'
13:57:33  2023-08-21 11:57:24,397 DEBUG: built tree 'object 880a0f10a0350a3ed636a6a395a7cd4a.dir'
13:57:33  2023-08-21 11:57:24,397 DEBUG: {'datasets/training-sets': 'modified'}
13:57:33  2023-08-21 11:57:24,408 DEBUG: built tree 'object 880a0f10a0350a3ed636a6a395a7cd4a.dir'
13:57:33  2023-08-21 11:57:24,409 DEBUG: built tree 'object 2ead35ca4cf9b96e0f4ad3cc696e78d7.dir'
13:57:33  Running stage 'training':
13:57:33  > conda env export --prefix .conda-envs/training | grep -v "\(^prefix:\)\|\(^name:\)" > stages/training/exported-conda-env.yaml
13:57:33  > conda run --no-capture --prefix .conda-envs/training/ mmocr train --config_path stages/training/abinet_config_handwriting.py
13:57:33  > conda run --no-capture --prefix .conda-envs/training/ python dependencies/scripts/rename.py model/
13:57:33  > cp -r stages/training/charsets model/
13:57:33  2023-08-21 11:57:24,412 DEBUG: stage: 'training' was reproduced
```

How can i fix this? Like it seems that i dont use the correct command for my pipeline. I mean the command succeeds but it should fail in a pipeline sense because a repro would be run if i just would use `dvc repro`.

I believe im missing something similar to the dvc data status one
`dvc data status --not-in-remote --json | grep -v not_in_remote`

which got the grep but not sure how do it for dvc repro --allow-missing --dry so it failes for all kinds of the dependecies.

So i tried:
` dvc repro --dry --allow-missing | grep -v "Running stage "`
But it still succeds even tho if i just use grep "Running stage " i get some output

```
> dvc repro --dry --allow-missing | grep "Running stage "
Running stage 'training':
Running stage 'collect_benchmarks':

```

_Originally posted by @Otterpatsch in https://github.com/iterative/dvc/issues/9818#issuecomment-1686203104_

**Comment by dberenbaum** [comment]
@Otterpatsch I opened a separate issue for this one to keep track. 

@iterative/dvc I think once we hit a stage that needs to be run, we need to stop execution for downstream stages, or at least we should raise a non-0 exit code.

**Comment by dberenbaum** [comment]
@Otterpatsch do you hit this in CI or only when testing locally? I would expect that you would hit this when you have already pulled the data but not in CI since the data won't be pulled and downstream stages will likely fail to find the necessary dependencies.

**Comment by Otterpatsch** [comment]
I hit this on the ci. I assume because of the --allow-missing the command doesnt fail on the non present dependencies

**Comment by dberenbaum** [comment]
Have you git committed and pushed all changes as well? I'm a bit confused whether you are trying to simulate a clean state when no pipeline stages should run, or a messy state when it should run and fail?

**Comment by Otterpatsch** [comment]
Everything is git pushed. Im trying to have a clean state. The state itself is also clean i think. At least when i pull everything is fine. I just cannt get the ci pipeline to indicate that. 
`dvc repro --dry --allow-missing` outputs that some stages dependecies changed. If i pull the command does not indcate that any stage depedency changed.

**Comment by dberenbaum** [comment]
In that case, it may not be about `--dry --allow-missing`. What is the output of `dvc data status` on the CI machines?

**Comment by Otterpatsch** [comment]
> In that case, it may not be about `--dry --allow-missing`. What is the output of `dvc data status` on the CI machines?

```
> dvc data status                                           
Not in cache:                                                                                                       
  (use "dvc fetch <file>..." to download files)
        model/
....
        datasets/training-sets/customer/some_customer/2022-09-03_training_somedata_1/
        datasets/training-sets/customer/some_customer/2022-09-03_training_somedata_2/
        datasets/training-sets/customer/some_customer/2022-09-03_training_somedata_3/
        datasets/training-sets/customer/some_customer/2022-09-03_training_somedata_4/
        stages/extract/outputs/customer/some-dataset1
        stages/extract/outputs/customer/some-dataset2
        stages/extract/outputs/customer/some-dataset3
...

DVC uncommitted changes:
  (use "dvc commit <file>..." to track changes)
  (use "dvc checkout <file>..." to discard changes)
        modified: model/
...
        stages/extract/outputs/customer/some-dataset1
        stages/extract/outputs/customer/some-dataset2
        stages/extract/outputs/customer/some-dataset3
```
Just to clarify the stage `dvc data status --not-in-remote --json | grep -v not_in_remote` succeeds (expected).


> Edit: you may need to run `dvc pull` so that they don't all show as missing, but after that I'd expect it to show a clean state.
Yes, if i run dvc pull everything is fine. But thats expected but the idea is that i dont have to dvc pull to verify the pipeline status? So i guess i have to combine the commands? And maybe dvc data status would be enough? 
https://dvc.org/doc/user-guide/pipelines/running-pipelines#verify-pipeline-status indicates that the command

**Comment by dberenbaum** [comment]
> Yes, if i run dvc pull everything is fine.

Is this true even on the CI machine? Does `dvc data status` report a clean status in CI after `dvc pull`? I know you don't want to pull in the final scenario, but I'm trying to understand why DVC tries to run those stages, and why it only tries to run them in CI.

> Basically instead of adding all full paths to the dependencies (which would be ~200-300 lines) we decided to just add the parent directory. This parent folder is not dvc tracked but all the subdirectories are. Could this may cause the issue?
> It kinda make sense that datasets/training-sets changed as its subdirs were not filled by dvc pull

What do you mean that the subdirs were not filled by `dvc pull`?

**Comment by Otterpatsch** [comment]
> Is this true even on the CI machine? 

yes this is also the case on the ci machine. Just to clarify this is the case on any machine which didnt not do dvc pull prior to the repro command. 

> Does `dvc data status` report a clean status in CI after `dvc pull`? I know you don't want to pull in the final scenario, but I'm trying to understand why DVC tries to run those stages, and why it only tries to run them in CI.

the dvc pull failes to pull some data. Which maybe has to do with the site-cache, which at least on our site caused a lot of issues. So i will try to remove it on the ci machine. Is there a command which to archive this? Otherwise i would just try to pipe the output of dvc doctor to archive this

> What do you mean that the subdirs were not filled by dvc pull?
As a dvc were not done. I assume(d) the check for the dependency like datasets/training-sets depends on some check. But as this dependency is not a git tracked file nor a .dvc file i assume the check if differs to those files? Because pipelines which have only git tracked dependency are fine (are shown as "not changed, skipping")

**Comment by Otterpatsch** [comment]
Small update: As im very much confused why i cannt pull data i can earlier on any other branch, while not changing the corresponding .dvc file i basically cherry picking everything commit by commit and check if its fine. So it will take i while. I will report back :)

**Comment by dberenbaum** [comment]
Closing as stale, but feel free to reopen if you are still facing issues with this
