### ISSUE TITLE
Unable connect dvc to Google Drive. Access blocked!

### ISSUE THREAD

**Issue by faizan1234567** [iterative/dvc#9876]
# Bug Report

## Description

Dear Author, I am working with an NLP model. I want to push to Google Drive but cannot do that because it blocks the access.
I am trying to implement [this tutorial](https://www.ravirajag.dev/blog/mlops-dvc).  I don't why it doesn't work.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by pmrowla** [comment]
Can you please run `dvc doctor` and post the output?

Also it would help if you could post the command that fails and the full error you get.

**Comment by faizan1234567** [comment]
DVC version: 2.9.5 (pip)
---------------------------------
Platform: Python 3.9.0 on Windows-10-10.0.19041-SP0
Supports:
        gdrive (pydrive2 = 1.17.0),
        hdfs (fsspec = 2022.7.1, pyarrow = 11.0.0),
        webhdfs (fsspec = 2022.7.1),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: hardlink
Cache directory: NTFS on E:\
Caches: local
Remotes: gdrive, gdrive
Workspace directory: NTFS on E:\
Repo: dvc, git
-------------------------------------------------
I am running dvc push trained_model.dvc and then it generates a link, when I click on the link it access blocked message pops up

**Comment by pmrowla** [comment]
2.9.5 is a very old DVC release, you most likely have an outdated version of the gdrive dependencies that do not support the current gdrive auth system. Please update to the latest DVC release with
```
pip install -U dvc[gdrive]
```

**Comment by faizan1234567** [comment]
Issue solved. Thank you.
