### ISSUE TITLE
dvc get/artifacts get: repo clone is slow

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9880]
# Bug Report

## Description

`dvc get` is slow to clone the git repo.

This is shown in the DVC benchmarks:

![visualization(11)](https://github.com/iterative/dvc/assets/2308172/0e3a59eb-dd55-45fb-8bfb-b37d8c67fdeb)

### Reproduce

I can also see it by profiling the example command `dvc get -f git@github.com:iterative/example-get-started-experiments.git models/model.pkl --viztracer --viztracer-depth=32` (CLI `git clone` for this repo takes <1 second):

<img width="1440" alt="Screenshot 2023-08-28 at 9 17 06 AM" src="https://github.com/iterative/dvc/assets/2308172/f4f7fe4f-a203-49a4-be95-5fb432699a41">

[viztracer.tar.gz](https://github.com/iterative/dvc/files/12454794/viztracer.tar.gz)

### Expected

The operation should take a few seconds at most instead of almost a minute.

**Comment by skshetry** [comment]
@dberenbaum can you try with more depth?

**Comment by skshetry** [comment]
@dberenbaum, yes, `fetch` is slow, but more information about where it's getting blocked would be helpful. 

For me, it's not working at all. It's just getting stuck forever on `client.fetch_pack()`. It could be that my internet is slow. But this has likely to do something with `asyncssh` client.

**Comment by skshetry** [comment]
Also, could you please try with `--viztracer-async`? There should be some tasks from asyncssh that should be visible, but above log does not have anything like that.

**Comment by pmrowla** [comment]
Also, do you get different clone performance with https github URLs vs ssh?

I'm not sure this would is related to the asyncssh client given that the dvc-bench test is only cloning local paths

**Comment by dberenbaum** [comment]
@pmrowla I get similarly slow performance with https and ssh

**Comment by pmrowla** [comment]
I can reproduce this but it looks like it's specific to `iterative/example-get-started-experiments.git`. Doing a complete clone of that repo (which is what happens on `dvc get`) is also slow for me, even with CLI git
```
$ time git clone --mirror https://github.com/iterative/example-get-started-experiments.git
Cloning into bare repository 'example-get-started-experiments.git'...
remote: Enumerating objects: 6431, done.
remote: Counting objects: 100% (405/405), done.
remote: Compressing objects: 100% (301/301), done.
remote: Total 6431 (delta 64), reused 351 (delta 35), pack-reused 6026
Receiving objects: 100% (6431/6431), 348.63 MiB | 9.65 MiB/s, done.
Resolving deltas: 100% (1484/1484), done.
git clone --mirror   6.36s user 3.32s system 26% cpu 36.997 total
```

It looks like the issue is that the repo contains a large amount of binary blobs, the repo has git committed `.png` plot images and `.pt` model checkpoint files, as well as notebooks and markdown reports that also contain embedded b64-encoded images.

```
...
c30d5dac0e2e  1.6MiB results/evaluate/plots/images/REGION_3-25_1024_2048_1024_2048.png
c33807249aac  1.6MiB results/evaluate/plots/images/REGION_3-25_1024_2048_1024_2048.png
...
9dcd06ee0cd9  1.7MiB results/evaluate/report.md
bd749d1c73a4  1.7MiB results/evaluate/report.md
...
737dbdfaacf8  1.8MiB notebooks/TrainSegModel.ipynb
afd85afc8c0b  1.8MiB notebooks/TrainSegModel.ipynb
...
d61ef50d3a52  6.2MiB notebooks/yolov8n.pt
6d8d8b575793  6.7MiB notebooks/yolov8n-seg.pt
```

All of these things should be tracked with DVC and not Git, especially in a DVC example repo.

Dulwich fetch is slower than CLI git when fetching these objects. We can speed this up by trying to move back to using libgit/pygit for clone/fetch now that we have proper remote callbacks implemented in scmrepo, but IMO this is just as much an `example-get-started-experiments` problem as it is a DVC/scmrepo problem.

**Comment by dberenbaum** [comment]
Okay, thanks for the research @pmrowla. 

For the get started repo, some of those issues look to be because we force push when we make updates and garbage collecting looks to not be happening frequently enough to clean up some of the old objects (although `.ipynb` and `.md` files are still in Git and I think that's a typical pattern). We could try to delete the repo and recreate it in GH, although I don't know whether that will reuse the same underlying Git repo.

Anyway, it does look the issue is pretty unique to that repo, and I have otherwise not been able to reproduce the performance regressions shown in dvc-bench for `dvc get`, so we can close it.

**Comment by daavoo** [comment]
> All of these things should be tracked with DVC and not Git, especially in a DVC example repo.

We should clean those things from the Git remote

**Comment by dberenbaum** [comment]
@daavoo How would we do that other than drop and recreate the repo?
