### ISSUE TITLE
dvc pull data. dvc does nothing

### ISSUE THREAD

**Issue by sgummuluru** [iterative/dvc#9894]
# Bug Report

## Description

My teammate updated a .dvc file that tracks data from AWS S3 using 
```dvc update data.dvc```

On my end I am using this dvc file and did

```dvc pull data.dvc```

When I run this nothing happens and terminal gets stuck in the command. 
The terminal does not output any progress bar/status messages as it does usually. I see no errors as well. 
I have tried adding --verbose to the above command and that outputs the following and nothing more
```
v3.15.3 (pip), CPython 3.9.6 on macOS-12.6-arm64-arm-64bit
2023-08-31 11:58:30,376 DEBUG: command: {path_to_virtual_environment}/bin/dvc pull data.dvc --verbose
```

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

DVC version: 3.15.3 (pip)
-------------------------
Platform: Python 3.9.6 on macOS-12.6-arm64-arm-64bit
Subprojects:
	dvc_data = 2.14.0
	dvc_objects = 1.0.1
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.3.1
Supports:
	http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
	Global: /Users/{user_name}/Library/Application Support/dvc
	System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/2cb10f4854de87e938b8db3f2fde0207

**Additional Information (if any):**

**Comment by efiop** [comment]
@sgummuluru Hi. Could you show that `data.dvc`?

**Comment by sgummuluru** [comment]
Thank you for your response @efiop!
Weirdly DVC started downloading data after about 2 hours of the above inactivity on terminal. When I repeat the above now, it just works right away. Not sure what was happening under hood during this long period of inactivity though.

**Comment by efiop** [comment]
Good to hear that it works now. Closing for now.
