### ISSUE TITLE
run-cache: Stages using only templating are not supported

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#9895]
Given a stage using templating:

```yaml
stages:
  echo-foo:
    cmd: echo ${foo} > out
    outs:
      - out
 ```
 
 It is ignored by the run cache (`_can_hash` is False) :
 
 https://github.com/iterative/dvc/blob/7a9da0f4a1d2790f2dcfd2774854b6ab2a10cd97/dvc/stage/cache.py#L185-L189
 
 ```py
>>> from dvc.repo import Repo
>>> from dvc.stage.cache import _can_hash
>>> _can_hash(Repo().index.stages[0])
False
 ```
 
It works when explicitly indicating the interpolated param:

```yaml
stages:
  echo-foo:
    cmd: echo ${foo} > out
    params:
      - foo
    outs:
      - out
 ```
 
 ```py
>>> from dvc.repo import Repo
>>> from dvc.stage.cache import _can_hash
>>> _can_hash(Repo().index.stages[0])
True
```

**Comment by skshetry** [comment]
This is not being cached, because there are no dependencies. There is https://github.com/iterative/dvc/issues/10258 with more context. Closing in favour of that.
