### ISSUE TITLE
Alias `dvc mv` to `dvc move`

### ISSUE THREAD

**Issue by feefladder** [iterative/dvc#9901]
In being similar to git, it would be nice to be able to use `dvc mv` in addition to `dvc move`, it put me off at first.

**Comment by dberenbaum** [comment]
Good idea @feefladder! It should be quite a small change if you are interested in contributing it.

**Comment by BradyJ27** [comment]
Opened PR #9905 for this. Thoughts on adding this for `rm` = `remove` and the same for `exp remove`?

**Comment by feefladder** [comment]
@dberenbaum I barely had a chance.... 🙄🤣
