### ISSUE TITLE
queue start: `.git` directory in temp folder not being removed once done

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#9902]
# Bug Report

## Description

I just noticed that with DVC 3.17, the `.dvc/tmp/exps/tmp*` folders are ~~empty~~ contain only the `.git/` tree once the experiment task has terminated. Previously, these would be cleaned up properly as well.

### Reproduce

- `dvc exp run --queue`
- `dvc queue start -j 1`

### Expected

The ~~empty~~ temp folders (e.g., `tmpcw_48u8h` in `.dvc/tmp/exps/`) should be deleted once the experiment task finished.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.17.0 (conda)
---------------------------
Platform: Python 3.10.6 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 2.15.4
        dvc_objects = 1.0.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.3.1
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
        Global: /home/aschuh/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sda1
Caches: local
Remotes: s3, s3
Workspace directory: xfs on /dev/sda1
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/8d2f5d68bb223da9776a9d6301681efd
```

**Additional Information (if any):**

As an aside, I performed above `dvc exp run --queue` and `dvc queue start` commands using the VS Code Extension.

**Comment by aschuh-hf** [comment]
Actually, the folders are not empty but contain the complete `.git` subdirectory still.

**Comment by aschuh-hf** [comment]
The temp folder of a more recently finished experiment task was removed, however. Not sure what prevented it before.

**Comment by pmrowla** [comment]
The likeliest cause here is that another git process had open git file locks which would prevent DVC from removing `.git/` (and the temp directory) when the experiment finished. @aschuh-hf are using vscode when you run experiments (or another IDE)?

**Comment by aschuh-hf** [comment]
Yes, I was using VS Code with the DVC Extension.

**Comment by pmrowla** [comment]
In that case I think this should be mitigated going forward since the vscode extension now sets `GIT_OPTIONAL_LOCKS=0` for any git operations. Going to close this issue for now, feel free to reopen it if it comes up again.
