### ISSUE TITLE
`repro`: does not run stage if params are removed from dvc.yaml (in some cases)

### ISSUE THREAD

**Issue by lumbric** [iterative/dvc#9913]
# Bug Report

## Description

DVC runs a stage if params are changed, but in some cases the stage is considered as unchanged if params are compeletely removed from `dvc.yaml`.

If params are changed in params.yaml, everything works as expected (stage is run).

I have not tested how DVC behaves if dependencies are removed (again I'd expect this to be treated as change).

### Reproduce

**Example 1:**

Here we demonstrate that a stage is not run if params are removed.

1. `mkdir dvctest; cd dvctest; git init; dvc init`
2. create a file `params.yaml` with the content:
```
name: lumbric
```
3. create a file `dvc.yaml` with the content:
```
stages:
    do_something:
        cmd: echo "hello world, my name is ${name}"
        deps:
            - in
        params:
            - name
```
4. `echo "some input" > in`
5. `dvc repro` will then print:
```
Running stage 'do_something':                                                                            
> echo "hello world, my name is lumbric"
hello world, my name is lumbric
Generating lock file 'dvc.lock'                                                                          
Updating lock file 'dvc.lock'

To track the changes with git, run:

        git add dvc.lock

To enable auto staging, run:

        dvc config core.autostage true
Use `dvc push` to send your updates to remote storage.
```
6. note that the lock file contains params: 
```console
$ cat dvc.lock 
schema: '2.0'
stages:
  do_something:
    cmd: echo "hello world, my name is lumbric"
    deps:
    - path: in
      hash: md5
      md5: 38debce1fb87347226e0c14d0084ef5c
      size: 11
    params:
      params.yaml:
        name: lumbric
```
7. now remove the params section from dvc.yaml, it should look like this:
```console
$ cat dvc.yaml 
stages:
    do_something:
        cmd: echo "hello world, my name is ${name}"
        deps:
            - in
```
8. `dvc repro` will then print:
```console
dvc repro   
Stage 'do_something' didn't change, skipping                                                             
Data and pipelines are up to date
```
9. note that dvc.lock is unchanged (see step 6)

**Example 2:**

Here we demonstrate that a stage is run if params are removed. The difference is that there is no dependency on the stage.

1. `mkdir dvctest; cd dvctest; git init; dvc init`
2. create a file `params.yaml` with the content:
```
name: lumbric
```
3. create a file `dvc.yaml` with the content:
```
stages:
    do_something:
        cmd: echo "hello world, my name is ${name}"
        params:
            - name
```
4. `dvc repro` will then print:
```
Running stage 'do_something':                                         
> echo "hello world, my name is lumbric"
hello world, my name is lumbric
Generating lock file 'dvc.lock'                                       
Updating lock file 'dvc.lock'

To track the changes with git, run:

        git add dvc.lock

To enable auto staging, run:

        dvc config core.autostage true
Use `dvc push` to send your updates to remote storage.
```
5. note that the lock file contains params: 
```console
$ cat dvc.lock
schema: '2.0'
stages:
  do_something:
    cmd: echo "hello world, my name is lumbric"
    params:
      params.yaml:
        name: lumbric
```
6. now remove the params section from dvc.yaml, it should look like this:
```console
$ cat dvc.yaml 
stages:
    do_something:
        cmd: echo "hello world, my name is ${name}"
```
7. `dvc repro` will then print:
```console
Running stage 'do_something':                                         
> echo "hello world, my name is lumbric"
hello world, my name is lumbric
Updating lock file 'dvc.lock'                                         

To track the changes with git, run:

        git add dvc.lock

To enable auto staging, run:

        dvc config core.autostage true
Use `dvc push` to send your updates to remote storage.
```
8. note that the params section is removed from dvc.lock:
```console
$ cat dvc.lock
cat dvc.lock 
schema: '2.0'
stages:
  do_something:
    cmd: echo "hello world, my name is lumbric"
```

### Expected

A stage should run if a dependency changes or if a parameter changes. Removing all params should be treated as change independently if dependencies exist or not. In Example 1 above the stage is not treated as changed and is not run. Example 2 behaves as expected. The only difference is a dependency in Example 1.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.16.0 (conda)
---------------------------
Platform: Python 3.9.15 on Linux-5.4.0-146-generic-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 2.15.4
        dvc_objects = 1.0.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.3.1
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3)
Config:
        Global: /home/snip/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/md1
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/md1
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/89d1c207de8c87e2e774811a63cbdd62
```

**Comment by dberenbaum** [comment]
@skshetry Could you take a look here please?

**Comment by dberenbaum** [comment]
@lumbric Does it cause any major issue for you, or did you just happen to notice it? You can use `dvc repro -f` if you need to force the stage to run. 

Discussed with @skshetry and this is "expected" although it's arguable which is correct.

In example 1, dvc only checks if the deps/outs defined in the current `dvc.yaml` has changed. The same behavior would happen if you drop a regular dependency from the stage, and dvc errs on the side of not running stages.

In example 2, dvc always re-runs stages with no dependencies.

**Comment by lumbric** [comment]
I just stumbled by chance over it and considered it as unexpected behavior. However, if it happens unnoticed it might lead to wrong end results, because the pipeline is run with unexpected parameters.

If I understand your explanation correctly, dvc runs a stage if one of the following is true:
 - there is no param/dependency defined
 - at least one of the defined dependency or parameter changed since the last time
 
I think it would be better to add another condition here: run the stage if the set of params/deps changed.
 
But I see your point - it is probably a minor issue and it's probably fine to keep things as they are. A change in the set of params/deps without a change in the code does not really make sense if the set of params/deps was correct.

**Comment by dberenbaum** [comment]
Agreed, it's questionable behavior, but I'm going to close this one and we can come back to it if we see it become a more prevalent problem.
