### ISSUE TITLE
dvc quick tips 

### ISSUE THREAD

**Issue by pjaol** [iterative/dvc#9946]
Two items in one - feel free to close, primarily for google and anyone who has been dealing with the same issue.

It would be great if there were a quick tips page alongside the how to section of the dvc.org site for community contributions.

The tip I'd add is
If you are building a docker image with models baked in using dvc with google/gcloud cloud build, 
authentication for cloud storage is described as requiring 

```bash
$ export GOOGLE_APPLICATION_CREDENTIALS='.../project-XXX.json'
```
A path to a service account key file. https://dvc.org/doc/user-guide/data-management/remote-storage/google-cloud-storage#custom-authentication

This raises an issue of how do you store a sensitive key for CI?

## Assumptions
* You are using dvc and google storage
* You are using source control and storing your .dvc reference files in source control
* You are using cloud build with a repo cloudbuild.yaml file (can also be done in json)

An approach is to add read permissions to the build principal to access the bucket you are using for your models / data
```
gcloud storage buckets add-iam-policy-binding gs://BUCKET_NAME --member=CLOUD_BUILD_PRINCIPAL_IDENTIFIER --role=storage.objects.get
```
Substituting CLOUD_BUILD_PRINCIPAL_IDENTIFIER for the cloudbuilder service account, which is generally found on the settings tab of your cloud builds page https://console.cloud.google.com/cloud-build/settings/service-account
And BUCKET_NAME for the bucket you are storing your models / data in

Once that's done modify the cloudbuild.yaml to add a step using a python image, install dvc and pull the modules from your source control references. Modify dvc pull models as required.

```yaml
steps:
  - name: python
    entrypoint: bash
    args: ['-c', 'pip install -U dvc dvc[gs]; dvc pull models;']
    id: Model_Pull
..... 
```

DVC will authenticate using a metaserver that's available in the cloud and not require GOOGLE_APPLICATION_CREDENTIALS or service key files. 
All steps in a cloud build load docker images, which mount /workspace/[your code], any modifications to that file system remain for the next step e.g. Build

At which point you will have performed a dvc pull on your models allowing a Dockerfile with a 
```Dockerfile
COPY models /destination
```
to copy your models to the appropriate destination 
An additional tip is that you may need to run a chown or chmod on the destination directory if you are using a non-root user
e.g.
```Dockerfile
RUN chmod -R 644 /models
```

**Comment by efiop** [comment]
Thanks for the info!

Closing since this is not actionable.
