### ISSUE TITLE
`dvc push` doesn't update cloud info with cloud versioned remotes

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#9947]
Context: https://github.com/iterative/dvc/discussions/9907#discussioncomment-6990738

Let's say we have two remotes:

```
['remote "dev"']
    url = s3://yury-cloud-versioning-test/test-dev
    version_aware=true
['remote "prod"']
    url = s3://yury-cloud-versioning-test/test-prod
    version_aware=true
```

Let's say we need to migrate data from one to another.

I would expect commands like this:

```
dvc pull -r dev
dvc push -r prod
```

to work and update `.dvc` \ `dvc.lock` files with an appropriate info, in reality I'm getting:

```
(.venv) √ Projects/test-cloud-versioned % git diff
diff --git a/test.txt.dvc b/test.txt.dvc
index d5fbaa9..03f455c 100644
--- a/test.txt.dvc
+++ b/test.txt.dvc
@@ -4,6 +4,6 @@ outs:
   hash: md5
   path: test.txt
   cloud:
-    dev:
+    prod:
       etag: d8e8fca2dc0f896fd7cb4cb0031ba249
       version_id: UK3s0VcueuAIttMw7FROG8pRospYWNQI
```

(only remote name is updated, info stays the same, which is wrong for that remote).

In the original issue, even the object is not pushed to the new remote.

Also, in case of cloud versioning I think `prod` / `dev` don't make much sense in `.dvc` \ `dvc.lock`. Version_id is unique (I assume) and can't repeat in a different location. I guess we need to use some hash, or location itself in this case. How do we use these names at all? do we expect that specific remote name to exist in a config?

**Comment by dberenbaum** [comment]
Related: 
https://github.com/iterative/dvc/issues/8356
https://github.com/iterative/dvc/pull/8862

@skshetry Can you remember what the expected behavior is here? Should we be overwriting the remote info? Or disallowing this operation?

**Comment by dberenbaum** [comment]
I can also reproduce this with a single remote by changing the remote path. DVC will update the remote name but won't notice that it needs to push again. 

It seems like DVC isn't checking whether the version IDs actually exist. I remember discussing this in https://github.com/iterative/dvc/pull/8766 but I think @pmrowla rightly saw it as dangerous and we continued to check which version were available.
