### ISSUE TITLE
gc: fail to gc 2.x cache/remote objects

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9953]
# Bug Report

## Description

`gc` does not garbage collect 2.x cache/remote objects

### Reproduce

```bash
set -x
# setup repos
REPO_DIR=$(mktemp -d)
REMOTE_DIR=$(mktemp -d)
cd $REPO_DIR
git init -q
dvc init -q
dvc remote add local $REMOTE_DIR
dvc remote default local
# add file to cache and push
echo foo >> foo
dvc add foo
dvc push
# update file and push
echo foo >> foo
dvc add foo
dvc push
# mimic old cache/remote and gc
cp -R .dvc/cache/files/md5 .dvc/cache
cp -R .dvc/cache/files/md5 $REMOTE_DIR
dvc gc -c -w 
tree $REPO_DIR/.dvc/cache
tree $REMOTE_DIR
```

### Expected

The output of the `tree` commands looks like:

```console
+ tree /var/folders/24/99_tf1xj3vx8k1k_jkdmnhq00000gn/T/tmp.A2IHOWGJ/.dvc/cache
/var/folders/24/99_tf1xj3vx8k1k_jkdmnhq00000gn/T/tmp.A2IHOWGJ/.dvc/cache
├── files
│   └── md5
│       ├── 5f
│       │   └── b7ba7e8447a836e774b66155f5776a
│       └── d3
└── md5
    ├── 5f
    │   └── b7ba7e8447a836e774b66155f5776a
    └── d3
        └── b07384d113edec49eaa6238ad5ff00

7 directories, 3 files
+ tree /var/folders/24/99_tf1xj3vx8k1k_jkdmnhq00000gn/T/tmp.LrAxuWxO
/var/folders/24/99_tf1xj3vx8k1k_jkdmnhq00000gn/T/tmp.LrAxuWxO
├── files
│   └── md5
│       ├── 5f
│       │   └── b7ba7e8447a836e774b66155f5776a
│       └── d3
└── md5
    ├── 5f
    │   └── b7ba7e8447a836e774b66155f5776a
    └── d3
        └── b07384d113edec49eaa6238ad5ff00
```

I would expect:

1. `d3/b07384d113edec49eaa6238ad5ff00` to be removed everywhere.
2. Non-3.x copies of `5f/b7ba7e8447a836e774b66155f5776a` to be removed.

### Environment information

```console
$ dvc doctor
DVC version: 3.19.1.dev20+gbf2af8639.d20230915
----------------------------------------------
Platform: Python 3.11.5 on macOS-13.5-arm64-arm-64bit
Subprojects:
        dvc_data = 2.16.2.dev1+g1672e69.d20230915
        dvc_objects = 1.0.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.3.1
Supports:
        azure (adlfs = 2023.8.0, knack = 0.11.0, azure-identity = 1.14.0),
        gdrive (pydrive2 = 1.17.0),
        gs (gcsfs = 2023.6.0),
        hdfs (fsspec = 2023.6.0, pyarrow = 13.0.0),
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        oss (ossfs = 2023.8.0),
        s3 (s3fs = 2023.6.0, boto3 = 1.28.17),
        ssh (sshfs = 2023.7.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2023.6.0)
Config:
        Global: /Users/dave/Library/Application Support/dvc
        System: /Library/Application Support/dvc
```

**Comment by dberenbaum** [comment]
Marking as a p0 since it seems to break the ability to gc after 3.0 migration.

**Comment by pmrowla** [comment]
Just to clarify, this is reproducible but the repro script should contain 

```
cp -R .dvc/cache/files/md5/* .dvc/cache
cp -R .dvc/cache/files/md5/* $REMOTE_DIR
```

(the original script ends up copying into `.dvc/cache/md5/...` instead of `.dvc/cache/...` when trying to populate the legacy cache location)

**Comment by pmrowla** [comment]
Two issues here:

1. We were not checking hashname in dvc-data when GC'ing, so in cases where a 2.x and 3.x hash had the same hash string both 2.x and 3.x versions would be preserved (this affected it both ways where 2.x objects could be preserved when we only wanted to keep the 3.x version, and vice-versa)
2. DVC `gc -c` logic would only call gc for the remotes which contained the used objects we wanted to preserve (so in the event we only have 3.x objects we would not try to gc the 2.x remote location). In cases where we had a mix of 3.x and 2.x used objects to preserve `gc -c` would behave as expected (except for the 2.x/3.x hash overlap case from `1.`)

**Comment by dberenbaum** [comment]
Discord context for the record: https://discord.com/channels/485586884165107732/485596304961962003/1152153467155136542
