### ISSUE TITLE
AWS Sagemaker: unable to import-url --version-aware s3://bucket/prefix/data

### ISSUE THREAD

**Issue by vivianwu18** [iterative/dvc#9993]
## Description

I used AWS Sagemaker to run my scripts and would like to use cloud versioning on the S3 bucket. However, it returned an unexpected error when calling the HeadObject operation.

### Reproduce

```
sagemaker-user@studio$ dvc import-url s3://bucket/prefix/data.csv --version-aware --no-download
Importing 's3://bucket/prefix/data.csv' -> 'data.csv'
ERROR: unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden                           

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

### Expected

It should not return anything and DVC should know that my cloud storage is already versioning data.csv.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.22.0 (pip)
-------------------------
Platform: Python 3.9.15 on Linux-4.14.320-243.544.amzn2.x86_64-x86_64-with-glibc2.26
Subprojects:
        dvc_data = 2.16.1
        dvc_objects = 1.0.1
        dvc_render = 0.6.0
        dvc_task = 0.3.0
        scmrepo = 1.3.1
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.9.1, boto3 = 1.28.17)
Config:
        Global: /home/sagemaker-user/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: nfs4 on 127.0.0.1:/200010
Caches: local
Remotes: s3, s3
Workspace directory: nfs4 on 127.0.0.1:/200010
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/c0b5f00be4a7d123cbf45864a8a1f86c
```

**Additional Information (if any):**

**Comment by Ayushlion8** [comment]
Hey @vivianwu18, 
To resolve this issue, follow these steps:

Review IAM Permissions: Ensure that your AWS IAM user or role has the necessary permissions to perform the HeadObject operation on the specified S3 object in the S3 bucket. You need to have the s3:GetObject permission for the object.

Check AWS S3 Bucket Policies: Verify if there are any bucket policies applied to the S3 bucket that restrict access to specific IAM users or roles. If such policies exist, make sure your IAM user or role is included and allowed.

AWS S3 Object ACLs: Check the Access Control Lists (ACLs) for the specific S3 object (data.csv) in question. You can do this through the AWS S3 console. Ensure that your IAM user or role has read permissions (e.g., "Read" or "Read ACP") for the object.

**Comment by vivianwu18** [comment]
Hi @Ayushlion8,

Thanks for your reply!
I went through all steps you mentioned but it seemed that my account already had a full access to the S3 bucket. Would you please help review all the settings related to my account to assure I did not make any mistake? 
Here below are the screenshots or scripts of the current setting.

Please help advise on it. Thanks again!

#### IAM permissions
<img width="1041" alt="image" src="https://github.com/iterative/dvc/assets/123716809/e39ce385-832b-4e09-82ce-e35aada7a913">

#### AWS S3 bucket policies
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::account:user/username",
                "Service": "sagemaker.amazonaws.com"
            },
            "Action": [
                "s3:ListBucketVersions",
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucketname",
                "arn:aws:s3:::bucketname/*"
            ]
        }
    ]
}
```
#### AWS S3 object ACLs
<img width="1041" alt="Screenshot 2023-10-03 at 1 55 06 PM" src="https://github.com/iterative/dvc/assets/123716809/830d06d4-0a49-4638-9c92-41f0ec21aa84">

**Comment by dberenbaum** [comment]
@Ayushlion8 Are you sure that those permissions are attached to your [SageMaker role](https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-roles.html)? You may need to go to SageMaker in the AWS CLI, click on your domain and user, and look for the Execution Role in your user info. Then you need to find that role in the IAM service and add that AmazonS3FullAccess policy to that role.

**Comment by skshetry** [comment]
Closing due to lack of response.
